### ISSUE TITLE
Add launch.openshift.io template to minishift addon list

### ISSUE THREAD

**Issue by gastaldi** [minishift/minishift#1000]
As discussed in the devtools-program mailing list, it would be nice to have the Openshift template used in launch.openshift.io as part of the Minishift/CDK catalog

**Comment by gastaldi** [comment]
PR created: https://github.com/minishift/minishift/pull/998

**Comment by LalatenduMohanty** [comment]
The question is whether we want to make it a default addon or not. I would vote for making it a default add-on. Lets see what others think.

**Comment by hferentschik** [comment]
I think this would be more something for the add-on repo we discussed. Not sure whether we should add it as a default add-on. We can for sure add it to our repo until we figure out where we want to take the add-on registry, but adding it right away to the defaults seems a bit too much right now.

**Comment by LalatenduMohanty** [comment]
> We can for sure add it to our repo until we figure out where we want to take the add-on registry, but adding it right away to the defaults seems a bit too much right now.

+1. @gastaldi I thought that this add-on would be useful for upstream Minishift users but it seems like it is not. comments?

**Comment by jorgemoralespou** [comment]
I agree 100% with @hferentschik Default addons should be a few, and valuable to 100% of the population (whether they use them or not is something else). Rest of addons should be created in the addon registry.

Nevertheless, it should be possible and easy to list and install addons from the (default and alternates) registry.

Something like:

````
minishift addons list --from= 
````

And depending how you want to support registries, this could alse be:
````
minishift addons list --from-url=https://github.com/jorgemoralespou/minishift-addons 
minishift addons list --from-file=addons-registry.zip 
minishift addons list --from-dir=/home/jmorales/minishift-addons 
````

**Comment by hferentschik** [comment]
> I agree 100% with @hferentschik Default addons should be a few, and valuable to 100% of the population

+1

> it should be possible and easy to list and install addons from the (default and alternates) registry.

+1

> minishift addons list --from-url=https://github.com/jorgemoralespou/minishift-addons 
> minishift addons list --from-file=addons-registry.zip 
> minishift addons list --from-dir=/home/jmorales/minishift-addons 

not sure about the zip case, but from directory as well as URL for sure.

**Comment by jorgemoralespou** [comment]
@hferentchik yeah. Not sure about zip also myself, but used same syntax as oc did for start-build to try to be consistent with existing options, either from minikube or openshift.

**Comment by hferentschik** [comment]
We created actually not a dedicated community driven repo for add-ons - https://github.com/minishift/minishift-addons

@gastaldi, would you mind creating a pull request there? README with instructions will soon be updated in the new repo.
