### ISSUE TITLE
Allow to specify additional default and blocked docker registries

### ISSUE THREAD

**Issue by sabre1041** [minishift/minishift#1002]
Add support to specify additional default registries and blocked registries at startup

**Comment by LalatenduMohanty** [comment]
@sabre1041 Can you please explain the use case for `default and blocked registries`. 

It seems it would be useful for users when they want to completely work with 3rd party or private registries. However it is tricky as we download OpenShift images from docker hub and if users blocks it during startup `minishift start` will fail. 

Also do you want to have these flags for both secure and in-secure registry?

**Comment by jorgemoralespou** [comment]
In RHEL based docker (RHEL and centos) these flags exist. Upstream docker
don't support them.

This is useful in an Enterprise environment when they want to prevent
developers or deployments from images coming from dockerhub or any other
registry not trusted by the organization. The default registry prevents
having to fully qualify the registry, so the images can be hosted in places
like satellite that makes the organization not dependent on internet and
prevents having to configure docker proxies.

This only makes sense in downstream minishift.

**Comment by praveenkumar** [comment]
Having it upstream will fail for b2d iso which doesn't have RHEL based docker. If we implement those flags here then user might be hit bug for b2d.

**Comment by jorgemoralespou** [comment]
@praveenkumar Agree with you, but for CDK you might end up in trouble. So either you support all the bootstrapping and don't act in case of B2D image, or don't support it and run into CDK not supporting same features as OCP. I would think the former is better :-D, Although I guess it needs more thought than what @sabre1041 has provided.

**Comment by sabre1041** [comment]
@jorgemoralespou @praveenkumar I would like to at least see this in the RHEL based CDK.

I can configure these options to only apply to the RHEL template if it is detected

**Comment by praveenkumar** [comment]
> I  can configure these options to only apply to the RHEL template if it is detected

@sabre1041 For me it need some more time to figure out if we can have those options only passed to our provision templates.

> but for CDK you might end up in trouble. So either you support all the bootstrapping and don't act in case of B2D image, or don't support it and run into CDK not supporting same features as OCP. I would think the former is better :-D

@jorgemoralespou I hear you and will try to make to make sure those options only work for rhel/centos ISO.

**Comment by hferentschik** [comment]
So what have we decided is the way forward on this. Where do we add what type of functionality?

**Comment by praveenkumar** [comment]
> So what have we decided is the way forward on this. Where do we add what type of functionality?

@hferentschik it's trivial right now only have to update downstream document. We can have this as part of implement upstream only  https://github.com/minishift/minishift/compare/master...praveenkumar:sabre1041-docker-options?expand=1

**Comment by sabre1041** [comment]
@praveenkumar I really like your approach as it is agnostic and generic. It would support the concerns in this issue with examples/documentation on how to implement in the downstream CDK

**Comment by hferentschik** [comment]
Merged via pull request #1027
