### ISSUE TITLE
'--iso-url' works with other iso other than boot2docker.iso?

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#101]
Hi,

Does the option `--iso-url` works with other type of iso other than `boot2docker.iso`? 

I tried with [rancheros.iso](https://github.com/rancher/os/releases/download/v0.6.1/rancheros.iso) but looks like its not working.

```
➜  minishift git:(master) ✗ minishift start --memory=4000 --iso-url='https://github.com/rancher/os/releases/download/v0.6.1/rancheros.iso' --vm-driver=virtualbox
Starting local OpenShift cluster...
Downloading ISO
 41.00 MB / 41.00 MB [=============================================================================================================================] 100.00% 0
E0921 00:33:58.260267   22248 start.go:100] Error updating cluster:  Process exited with: 1. Reason was:  ()
```

**Comment by praveenkumar** [comment]
@budhrg using any iso is not something works directly with minishift, it should be like boot2docker and also those config in place https://github.com/jimmidyson/minishift/tree/master/deploy/iso as part of it.

**Comment by hferentschik** [comment]
Right, Rancher seems to be a Linux distro which runs Docker in a "special" way, but it is not a boot2docker ISO.

**Comment by LalatenduMohanty** [comment]
@budhrg @praveenkumar @hferentschik Have you guys tried this with https://github.com/LalatenduMohanty/centos-live-iso ?

**Comment by hferentschik** [comment]
Not an issue.
