### ISSUE TITLE
Releasing Chocolatey and brew packages?

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1012]
Currently, it seems packages for both [brew cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/minishift.rb) and [Chocolatey](https://github.com/abejenaru/chocolatey-packages/blob/master/automatic/minishift/minishift.nuspec) are published by outside maintainers. While this is not per se a problem, this can lead to a skew in expectation and availability of the release. Would like to be able to make this part of our releases. WDYT?

For caskroom it is an easy PR we can issue... but for Chocolatey there is a maintainer model. This means we need to get in touch with the current maintainer and see what we can do to either transfer ownership or find a way to share this?

**Comment by budhrg** [comment]
> Would like to be able to make this part of our releases. WDYT?

Make sense.

**Comment by hferentschik** [comment]
+1 for creating a pull request for brew as part of the release. In fact the pull request creation can easily be automated. Let's create a script which does that.

Regarding Chocolatey, let's see what's required there.

**Comment by gastaldi** [comment]
I created a PR to Homebrew with Minishift formulas: https://github.com/Homebrew/homebrew-core/pull/14817

**Comment by gastaldi** [comment]
For LinuxBrew, I opened a PR in https://github.com/Linuxbrew/homebrew-extra/pull/17

**Comment by gastaldi** [comment]
There are some CI failures in the Homebrew PR because, as beforementioned, there is already a cask file (https://github.com/caskroom/homebrew-cask/blob/master/Casks/minishift.rb). IMHO I believe it should be a Homebrew Formula, not a Cask, since Minishift is not a GUI app. 

If that makes sense, I can provide a PR to remove the existing cask file. Thoughts?

**Comment by gastaldi** [comment]
A PR was created in https://github.com/caskroom/homebrew-cask/pull/35760 to remove the Cask file. Can someone else approve it?

**Comment by gbraad** [comment]
I think we need to make the cask PR automated

**Comment by gbraad** [comment]
@budhrg would you be able to have a look into this?

it would be great if we have an automated release for this package on brew caskroom (note: the brew recipe got closed).

**Comment by hferentschik** [comment]
Basically [this](https://github.com/caskroom/homebrew-cask/blob/master/Casks/minishift.rb) Cask definition needs to be updated. I guess minishift-bot could have a clone of the repo. Then we can checkout the repo, make the change, push the change to the minishift-bot clone and use the [GitHub API to trigger the pull request creation](https://developer.github.com/v3/pulls/#create-a-pull-request).

We can either do all this as part of the main script, or we create a separate job for this and just trigger it.

**Comment by gbraad** [comment]
Current cask: https://github.com/caskroom/homebrew-cask/blob/master/Casks/minishift.rb

**Comment by budhrg** [comment]
@gbraad @hferentschik  I will assign it myself and have a closer look into it.

**Comment by hferentschik** [comment]
+1

**Comment by hferentschik** [comment]
@budhrg if you want to do the brew thing, let's create a dedicated issue just for that.

**Comment by budhrg** [comment]
@hferentschik Created https://github.com/minishift/minishift/issues/1324 for brew.

IMO, it make sense to create separate issue to track chocolatey as well as this issue address both and now we are tracking brew in separate. WDYT @gbraad @hferentschik @LalatenduMohanty @praveenkumar ?

**Comment by budhrg** [comment]
We just need chocolatey package now as cask is done.

**Comment by anjannath** [comment]
Chocolaty package already exists, well maintained by the community... 
https://chocolatey.org/packages/minishift

**Comment by LalatenduMohanty** [comment]
I am inclined to close this issue as we do not need to do anything here.

**Comment by gbraad** [comment]
taken care of by others

**Comment by agajdosi** [comment]
Issue resolved by awesome people in community.
