### ISSUE TITLE
Pods Liveliness/Readiness fails

### ISSUE THREAD

**Issue by kameshsampath** [minishift/minishift#1015]
When deploying Spring Boot application in OpenShift (minishift v1.1.0) once the application is deployed i see the following logs repeatedly in the `oc get events -w`and it really takes very long time for the liveliness/readiness to make the pod live, even if that happens the pod's state is quickly back to check live and ready.

Sample error logs in the oc get events -w 
```
2017-06-12 12:08:10 +0530 IST   2017-06-12 12:03:50 +0530 IST   14        config-server-1-k40fc   Pod       spec.containers{spring-boot}   Warning   Unhealthy   {kubelet 192.168.64.4}   Readiness probe failed: Get http://172.17.0.3:8080/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
I tried switching the vm-driver from xhyve to virtualbox, and see the same issue.

My Platform:

OS X: 10.12.5
Docker version:  1.12.3

**Comment by praveenkumar** [comment]
@jorgemoralespou any idea about this, do we need anything from minishift side?

**Comment by LalatenduMohanty** [comment]
> it really takes very long time for the liveliness/readiness to make the pod live, even if that happens the pod's state is quickly back to check live and ready.

@kameshsampath Can you please check after increasing the CPU and memory and see if it makes any difference.

**Comment by kameshsampath** [comment]
@LalatenduMohanty yes i did try it no luck..  i was running minishift with 8G and 2 CPU.

**Comment by LalatenduMohanty** [comment]
@kameshsampath Can you please point us to the application and instructions for running it. I think it is worth to check what kind of checks the liveliness/readiness do.

**Comment by budhrg** [comment]
@kameshsampath , Could you still able to reproduce this with latest minishift version if yes could you point us to the application and instructions for running it?

**Comment by kameshsampath** [comment]
@budhrg  - we can close it as i dont see it any more.

**Comment by budhrg** [comment]
Closing as per above comment.
