### ISSUE TITLE
Minishift VM hangs indefinitely on Windows10+HyperV due to possible missing hardware support in the B2D image

### ISSUE THREAD

**Issue by nanomad** [minishift/minishift#1022]
Steps run:

- Add minishift to PATH
- Set HYPERV_VIRTUAL_SWITCH
- Run minishift start

VM gets stuck in the following state:
Waiting as requested ... 10

System details:
- Windows 10 build 1703
- minishift version v1.1.0 (clean install)
- CPU: AMD Ryzen 5 1600

**Comment by gbraad** [comment]
Can you provide more information? What is the hypervisor you are using? What is the full output you are seeing?

Would it be possible to run `minishift start --show-libmachine-logs -v 9` and post the results here?

**Comment by nanomad** [comment]
I'm using HyperV. The log is below:

https://gist.github.com/nanomad/f0316fe77410cf074a8818f3ebf817ae

(it continues the same way without changes)

To me the VM looks stuck, maybe a kernel panic or similar but I have no idea how to check for it. There no feedback on the console when pressing F1-F12

![Screenshot](http://i.imgur.com/NhL1VZ2.png)

**Comment by nanomad** [comment]
Possibly related to https://github.com/boot2docker/boot2docker/issues/1245 ?

**Comment by gbraad** [comment]
There are several issues we have filed for this: #417 #418 #419 (and most likely exhibits the feeling the VM hangs). But to be sure, can you remove the cached iso from `C:\Users\[username]\.minishift\cache\iso\` and rerun? This way we are sure it is not a broken download.

And yes, make sure you have assigned a Virtual Switch that has DHCP (and allows external communication). There are limitations to the current networking infra in Windows 10's version of HyperV. Also, do not use the `dockernat` network if you have this.

**Comment by gbraad** [comment]
As you can see in the log:
```
(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : c:\windows\system32\windowspowershell\v1.0\powershell.exe -NoProfile -NonInteractive (( Get-VM minishift ).networkadapters[0]).ipaddresses[0]
```
we try to get the assigned IP address, but fail to do so. Please verify you did: https://github.com/minishift/minishift/blob/master/docs/source/getting-started/setting-up-driver-plugin.adoc#hyper-v (follow the links as provided)

**Comment by nanomad** [comment]
The network is properly configured: it's bridged to the Ethernet network adapter where DHCP is available.
Truth be told, I don't think this is a network-related issue. 
I was able to boot properly on a different machine with the same configuration steps but with different, older, hardware.

I have a feeling this may be just hardware incompatibility with my workstation setup. Ryzen CPUs are supported by newer kernels than the one shipping with boot2docker/minishift image and the telling sign is that the boot process hangs at the hardware detection/configuration stage.

**Comment by gbraad** [comment]
@nanomad Unfortunately I can not reproduce this, as I have no access to a Ryzen-based machine. Will try to see what I can do. Since you have the issue with the boot2docker image. There are several things we can try to narrow this down:

   * can you try to use the CentOS image?  
     https://github.com/minishift/minishift/blob/master/docs/source/using/managing-minishift.adoc#choosing-the-iso-image
  * use virtualbox instead, as this hypervisor will usually deal much better with hardware issues
  * also try to reproduce this issue with minikube (as you also reported this to boot2docker already). this would help us to co-ordinate with them.

**Comment by nanomad** [comment]
@gbraad 
Indeed I was looking into testing it with minikube. I'll also try minikube later this evening

**Comment by nanomad** [comment]
Tests Result:
- Pass: CentOS Image v1.0.0 (Kernel 3.10.0)
- Pass: minikube v0.19.1 (Kernel 4.7.2)

Any ideas on how to debug the boot2docker boot process?

**Comment by gbraad** [comment]
@nanomad We will investigate what we can do, but it seems to be related to the hardware supports (some calls might not be properly passed to or interpreted by the underlying AMD). I suggest you to use the CentOS image for now...

**Comment by gbraad** [comment]
would it be possible to check the outcome when using Virtualbox? This means you have to disable Hyper-V for the moment

**Comment by nanomad** [comment]
@gbraad 
Booting fine on VirtualBox

The bump to 4.4 broke something in b2d according to git bisect (you can check that ticket if you want). Notice that if I take vanilla TCL (either 7.x or 8.x) it boots properly and that has 4.8 kernel

**Comment by gbraad** [comment]
Very valuable. At least glad an alternative exists; CentOS or virtualbox.
But we'll try to schedule the upgrade sooner than later

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by carljmosca** [comment]
I was able to start minishift (HyperV on Windows 10) after adding an external virtual network switch and removing the DockerNAT.

**Comment by gbraad** [comment]
@carljmosca removal of DockerNAT should not have been needed. Can you please reinstall Docker for Windows to make sure DockerNAT is recreated and let us know the results.

**Comment by carljmosca** [comment]
DockerNAT was created but is not enabled for minishift 

Should it be?

**Comment by gbraad** [comment]
@carljmosca DockerNAT does not provide DHCP #418, which at the moment is essential to operate properly. As the current documentation describes, you should use an External virtual switch. Removal of DockerNAT is not needed, and we actually explicitly test for the co-existence with Docker for Windows. Can you please confirm this is thee case. If not, please file a new issue.

**Comment by carljmosca** [comment]
I do have an external virtual switch.  

I have not been able to get it to work with DockerNAT but it seems fine w/o it so far (pulled images, started, etc.)

Now I am trying it on the VPN w/o DockerNAT.  I will try various combinations before filing a new issue.

**Comment by gbraad** [comment]
@carljmosca connecting Minishift to DockerNAT does not work; #418. Using a VPN might also lead to unexpecred behaviour as is described in the troubleshooting guide: #842.

**Comment by carljmosca** [comment]
@gbraad I am confused.  I thought you wanted me to try it with DockerNAT.

**Comment by nanomad** [comment]
@carljmosca Did you tell minishift which adapter it should use?
It is explained here:
https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html#hyper-v

**Comment by gbraad** [comment]
I had not mentioned to use it, but remind you that removal was not necessary. This is in response to:

> removing the DockerNAT.

As removal makes Docker for Windows unusable. but be aware that the issue you are having is unrelated to the OP.

**Comment by nanomad** [comment]
@gbraad Maybe it's better to change the issue title to reflect that this ticket is for an hardware incompatibility between b2d and hyperv

**Comment by gbraad** [comment]
Thanks, @nanomad, this is the reason why I pointed at https://github.com/minishift/minishift/issues/590#issuecomment-297928009 (was unable to access the docs, but knew when the functionality got introduced). Much appreciated.

**Comment by carljmosca** [comment]
Docker for Windows does not seem to have an issue with removing DockerNAT.  I stopped all VMs (including Docker), installed minishift, and restarted Docker.  DockerNAT was available once again and I have not noticed issues with Docker or minishift...so far. :)

**Comment by gbraad** [comment]
We have created a new ISO, based of a slighter newer Boot2Docker: https://github.com/minishift/minishift-b2d-iso/pull/54 Please have a look at the artifacts and hope you could try...

**Comment by nanomad** [comment]
Nope, still broken.

To be fair, it's the upstream B2D that is broken so not much that minshift can do at this point...
See: https://github.com/boot2docker/boot2docker/issues/1245
