### ISSUE TITLE
Document installation of SSH client on Windows

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1024]
Since https://github.com/DarwinJS/ChocoPackages/issues/34 got resolved, we can describe the installation process using chocolatey. Is this what we want?

**Comment by LalatenduMohanty** [comment]
@gbraad My understanding is that we do not need a SSH client now isn't it? If we do not want a SSH client we need to document this.

**Comment by LalatenduMohanty** [comment]
As discussed with @gbraad his question is related to our plan for host folder implementation using SSHFS.

**Comment by hferentschik** [comment]
I don't think for the hostfolder implementation we need a native client. Preferably we also do it natively.

**Comment by gbraad** [comment]
a native client => external client
natively, use a Go implementation? If so, this means that minishift forks a
daemon task?

**Comment by hferentschik** [comment]
> natively, use a Go implementation?

yes

> If so, this means that minishift forks a daemon task?

yes

**Comment by hferentschik** [comment]
Also, for the sshfs approach to work we don't need the SSH client on the host, but the SSH server. Not sure whether this is part of the package you are referring to. When using cygwin you need the sftp binary, not necessarily the ssh client.

**Comment by gbraad** [comment]
Exactly. in openssh-win32 there is a sftp-server. but this is also part of the same openssh install. There is no difference between server and client.

**Comment by hferentschik** [comment]
Cool. So yes, if we are going to rely on a native sftp-server binary, openssh-win32 is a viable solution and definitely preferable over Cygwin (not that I think a Windows without Cygwin would make sense ;-)

**Comment by gbraad** [comment]
There are still pros and cons of using cygwin over the powershell based openssh port or even using WSL, but that is a separate discussion ;-)

In this case, let's marks this as a possible item to pick up for the milestone when sshfs is considered.

**Comment by gbraad** [comment]
I think it is valid to also have a look at #1836, either to put a comment in the docs that this is Beta and still has to be tested, or that preliminary results show that is works, or... that it might not work.

**Comment by gbraad** [comment]
> So yes, if we are going to rely on a native sftp-server binary, openssh-win32 is a viable solution and definitely preferable over Cygwin

Is this still a consideration for #317? If so, we would need to test for conflicts, as the OpenSSH-Win32 packages can be made a daemon task... but even more worrying, if Remote Debugging is enabled on the host, port 22 will be claimed by the SSH-proxy service for Developer Mode.

**Comment by gbraad** [comment]
@robin-owen this describes something that is not a necessity for the working of minishift, as we communicate with the VM using a library. This would be an installation of the ssh client when people want to be a 'super-user', by using the `minishift ssh` command.

Since the documentation is in need of a restructure, what would be the best place for this?

**Comment by LalatenduMohanty** [comment]
Closing this issue as we do not need a ssh client for SSHFS (in minishift hostfolder).
