### ISSUE TITLE
Add test for verifying content of oc-env and docker-env commands

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1025]
This is a follow up issue as a result of the PR https://github.com/minishift/minishift/pull/1016 where we need to add tests to verify the content generated as part of `minishift oc-env` and `minishift docker-env` commands.

**Comment by agajdosi** [comment]
Hi @budhrg, this issue seems to be stuck in old milestone. Is the verification of docker-env and oc-env in this issue meant on level of unit tests, or integration tests? Might be related to #1332.

**Comment by budhrg** [comment]
Yes @agajdosi , you are right. It is duplicate of #1332
