### ISSUE TITLE
Connect to dockerized rest service from mobile app in development

### ISSUE THREAD

**Issue by johnreytanquinco** [minishift/minishift#1026]
We are developing both a mobile app and a backend REST service. The rest service (and database) run in OpenShift (using Minishift), as docker containers.

We would like to be able to develop both the mobile app and the backend rest service on the same laptop. But, when running the app, we are not able to connect to the REST services running in OpenShift.

How can we enable requests from the app to be networked to the applications running inside OpenShift, in a local development environment?

We can, from the mobile device, browse to the rest service, when the service is NOT dockerized - that is, when running on the host, but when running in OpenShift (dockerized).

Here are all details when I issue: `oc get all`

```
NAME             REVISION   DESIRED   CURRENT   TRIGGERED BY
dc/drupal8-db    1          1         1         config
dc/drupal8-web   1          1         1         config

NAME               DESIRED   CURRENT   READY     AGE
rc/drupal8-db-1    1         1         1         42d
rc/drupal8-web-1   1         1         1         42d

NAME                HOST/PORT                                    PATH      SERVICES      PORT      TERMINATION     WILDCARD
routes/drupal       drupal-myproject.192.168.42.244.nip.io                 drupal8-web   <all>                     None
routes/drupal-dav   drupal-dav-myproject.192.168.42.244.nip.io             drupal8-dav   <all>     edge/Redirect   None

NAME              CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
svc/drupal8-dav   172.30.2.97      <none>        5005/TCP   42d
svc/drupal8-db    172.30.253.230   <none>        3306/TCP   42d
svc/drupal8-web   172.30.246.0     <none>        5000/TCP   42d

NAME                     READY     STATUS    RESTARTS   AGE
po/drupal8-db-1-cqfr5    1/1       Running   7          42d
po/drupal8-web-1-kzwgp   1/1       Running   7          42d

```

Thanks!

**Comment by gbraad** [comment]
Can you provide an overview of the services and how they are exposed by routes?

**Comment by johnreytanquinco** [comment]
Hi @gbraad , I updated the post.

**Comment by gbraad** [comment]
Understanding your use case better now, you want the VM network to be exposed on the external IP address of the laptop. The issue here is: we can not bind as 0.0.0.0 on the laptop interface, as this only lives inside the VM. This is why your local non-dockerized environment works. It can bind to 0.0.0.0.

I would suggest you to setup a reverse proxy. You can use either nginx or Apache for this:
  * https://www.nginx.com/resources/admin-guide/reverse-proxy/
  * https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension

**Comment by LalatenduMohanty** [comment]
I think this is an use case which application developers will try with Minishift and we need to come up with a recommended solution.

**Comment by nanomad** [comment]
Wouldn't oc port-forward suffice for this scenario? 

This is what we are currently using on a real openshift cluster for development. I'm assuming it also works on minishift (I'll try it later today)

**Comment by hferentschik** [comment]
So where is this mobile app running? Are you trying to connect literally with a external phone to the service running on the laptop, or are you trying to connect from your mobile phone application environment to the service?

In the case of the former you will have to jump through some hoops as @gbraad mentioned. If your mobile dev environment is on your laptop itself, you should have several options. 

* Given that you are using a REST service, you should be able to use the preferred way of exposing the service as a route
* If that is not what you want, you can expose the service port as a so called NodePort. All NodePorts will be available on the VM IP
* Use oc port-forward as mentioned by @nanomad. For dev that should be sufficient 

See also https://github.com/minishift/minishift/blob/master/docs/source/openshift/exposing-services.adoc

I feel there is a bit of context missing to give you a better answer. First of all we need to fully understand your environment and provided all is (ap development as well as deployed services) are on your host, there is a bit of information missing on what you try to do and what the error is.

**Comment by johnreytanquinco** [comment]
HI @hferentschik ,

Both my mobile app(connected as external phone) and REST api is running in the same laptop. I want that the app can talk/connect to the api. In minishift, REST api service is already exposed as route and that is what I am testing, adding the link as base URL in my code for the app to be able to talk to the api.

I have already spin up another REST api in OpenShift server, which is like to consider a production site and  do the same steps to call/connect the REST api and it actually works.

I will try to test all of your suggestion since it is always a better way of development when we just work locally(minishift) running in our laptop. Thanks!

**Comment by hferentschik** [comment]
@johnreytanquinco, thanks for the update. 

> Both my mobile app(connected as external phone) and REST api is running in the same laptop. I want that the app can talk/connect to the api. In minishift, REST api service is already exposed as route and that is what I am testing, adding the link as base URL in my code for the app to be able to talk to the api.

So is there still an actual problem or do you have it working?

> I will try to test all of your suggestion since it is always a better way of development when we just work locally(minishift) running in our laptop. Thanks!

Sure, let us know how it goes.

**Comment by agajdosi** [comment]
Hi @johnreytanquinco, have you managed to resolve this problem, or is it still bothering you? Please let us know if there are any updates on this.
