### ISSUE TITLE
Add spinning wheel during registration process

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1036]
It would be great to have a progress bar to show the on going status during registration.

Mostly, the progress bar would be in the form of spinning wheel as we don't the total time taken here.

**Comment by hferentschik** [comment]
As part of this we want to add some timings as well.

**Comment by gbraad** [comment]
@LalatenduMohanty 
It seems the milestone has been modified to the next one, and timing has been added.

**Comment by hferentschik** [comment]
Merged via pull request #1060
