### ISSUE TITLE
Unable to compile/build binary in Windows without cygwin

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1037]
I am unable to build/compile the binary in Windows without cygwin. With cygwin installed, it is working as expected.

```
PS C:\gowork\src\github.com\minishift\minishift> $env:GOPATH
C:\gowork

PS C:\gowork\src\github.com\minishift\minishift> $env:GOBIN
C:\gowork\bin\

PS C:\gowork\src\github.com\minishift\minishift> make
go get -u github.com/jteeuwen/go-bindata/...
process_begin: CreateProcess(NULL, mkdir -p C:/gowork/src/github.com/minishift/minishift/out/bindata, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [C:/gowork/src/github.com/minishift/minishift/out/bindata/addon_assets.go] Error 2

PS C:\gowork\src\github.com\minishift\minishift> make clean
rm -rf C:\gowork/pkg/windows_amd64/github.com/minishift
process_begin: CreateProcess(NULL, rm -rf C:\gowork/pkg/windows_amd64/github.com/minishift, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [clean] Error 2
```

**Comment by budhrg** [comment]
I am also tempted to add documentation on how to build/compile binary in Windows with Cygwin till we have this issue resolved.

**Comment by hferentschik** [comment]
My guess is that it is the _mkdir -p_. Not sure whether this is portable.

**Comment by hferentschik** [comment]
one could make the mkdir command a variable or create the various parts explicitly skipping the '-p' option.

**Comment by budhrg** [comment]
Also, rm -rf <folder>  where `rm -r` works but -f is not there.

**Comment by hferentschik** [comment]
So I take it that AppVeyor has the mingw tools or similar installed per default in this case? Otherwise we would have noticed this, right? 

BTW, we should btw, on all CI jobs call `make clean` as well. For the actual build on the CI server it might not be so important, since we are getting a new VM on each build, but it might help us to detect errors in `make clean`. Atm we don't call it at all on any of the CI systems.

**Comment by budhrg** [comment]
> So I take it that AppVeyor has the mingw tools or similar installed per default in this case? Otherwise we would have noticed this, right?

Yes.

> it might help us to detect errors in make clean. Atm we don't call it at all on any of the CI systems.

:+1:

**Comment by gbraad** [comment]
Appveyor has cygwin installed on path, but undocumented it does so

**Comment by budhrg** [comment]
Need to add documentation as it seems in Windows it's not possible to compile without cygwin. Things like `rm -rf foo` in `make clean` will not work without cygwin or mingw tools.

**Comment by praveenkumar** [comment]
@budhrg what is the state of this one will it only around documents for compile it in windows or any code changes stuff needed?

**Comment by LalatenduMohanty** [comment]
> rm -rf foo in make clean will not work without cygwin or mingw tools.

I think that is correct as it is a Linux command. Can you check if Powershell supports it?

**Comment by gbraad** [comment]
Make can be installed from chocolatey, but the issue is with grep... not
the make command.

I compile from a VM, or from WSL.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by LalatenduMohanty** [comment]
As discussed with @minishift/minishift-dev we are going to fix this as we are fine with Appveyor environment and not planning to fix this.

**Comment by pthorson** [comment]
OK so can a build without Cygwin and where is the open issue with the documentation update neede to https://docs.okd.io/latest/minishift/contributing/developing.html?
