### ISSUE TITLE
Support `dnf install minishift`

### ISSUE THREAD

**Issue by gastaldi** [minishift/minishift#1039]
It would be nice to have minishift installed using DNF (Fedora) or YUM (CentOS). 
That would ease the adoption and keep clients updated.

Another option is by providing a Homebrew formula, so `brew install minishift` would do the job.

**Comment by gbraad** [comment]
@gastaldi someone has already provided a `brew cask install minishift`. Does this work for you?

@LalatenduMohanty I remember you once worked on an initial .spec to create an RPM package.

**Comment by gastaldi** [comment]
@gbraad unfortunately `brew cask` works only in macOS. I am using [Linuxbrew](http://linuxbrew.sh) in Fedora 25, where a Brew Formula would be a better choice instead.

**Comment by gbraad** [comment]
Cask and Chocolatey are described in #1012

**Comment by LalatenduMohanty** [comment]
@gbraad That was for CentOS PaaS SIG. I have not worked it for long now.

**Comment by gbraad** [comment]
@gastaldi Please see our comments on #1300. Do you believe this is still needed?

**Comment by gastaldi** [comment]
@gbraad I think it's fine to close this issue
