### ISSUE TITLE
Error during post cluster up configuration: Error reading config file ~/.minishift/machines/minishift_kubeconfig

### ISSUE THREAD

**Issue by jeremyeder** [minishift/minishift#1040]
```
$ minishift version
minishift v1.1.0

$ time minishift start
Starting local OpenShift cluster using 'kvm' hypervisor...
<snip>
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.77:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

Error during post cluster up configuration: Error reading config file /home/jeder/.minishift/machines/minishift_kubeconfig
```

This appears to be because I have an existing ~/.kube directory.

If I rename that directory and re-run minishift start, then the error does not occur.
Note that while .kube exists and I run minishift start, minishift does successfully update my .kube/config file but still the error is emitted.

**Comment by praveenkumar** [comment]
@jeremyeder `Error during post cluster up configuration: Error reading config file /home/jeder/.minishift/machines/minishift_kubeconfig` this mean `minishift_kubeconfig` is not a valid yaml file any more can you please do `minishift delete` and then again `minishift start`. you shouldn't need to do any manual changes for these config file.
