### ISSUE TITLE
How should an addon enable CORS?

### ISSUE THREAD

**Issue by jstrachan** [minishift/minishift#1047]
doesn't seem like we have a command we can use in the addon yet?

**Comment by hferentschik** [comment]
You should use the _openshift_ command - https://docs.openshift.org/latest/minishift/using/addons.html#addon-commands. This executes the _openshift_ binary on the container. Something like:

    openshift ex config patch /var/lib/origin/openshift.local.config/master/master-config.yaml --patch='{"corsAllowedOrigins": [".*"]}'

**Comment by gbraad** [comment]
@hferentschik @jstrachan https://github.com/sabre1041/cdk-minishift-utils/blob/master/addons/cors-allowed-origins-wildcard/cors-allowed-origins-wildcard.addon
