### ISSUE TITLE
Volume mounted under /var/cache & permission denied

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#105]
This error is reported using this config to mount a volume 

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0001
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data01"


kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

kind: Pod
apiVersion: v1
metadata:
  name: mypod
  labels:
    name: frontendhttp
spec:
  containers:
    - name: myfrontend
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
       claimName: myclaim-1      
```

using minishift 0.7.1 & xhyve docker-machine 0.3.2

```
2016/09/23 15:58:10 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
2016/09/23 15:58:10 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
```

**Comment by jimmidyson** [comment]
There are a couple of issues here.

1. You cannot run the default nginx image on openshift due to requirements to run as arbitrary his.

2. Host path volumes are auto created but only writable by root user. Again, due to openshift policy to run as arbitrary uid your will hit permission issues.

You have 2 options:

1. Precreate the host path directory with correct permissions (world writable).
2. Configure the default SCC to allow run as root uid.

**Comment by cmoulliard** [comment]
I have changed the scc permissions 

```
oc edit scc restricted
 
and

Change the runAsUser.Type strategy to RunAsAny.
```

but I get another error now

```
 oc logs local-nginx
2016/09/23 16:52:49 [emerg] 5#5: setgid(107) failed (1: Operation not permitted)
2016/09/23 16:52:49 [alert] 1#1: worker process 5 exited with fatal code 2 and cannot be respawned
```

**Comment by cmoulliard** [comment]
Tested also these modifications without success

```
oadm policy add-scc-to-user anyuid -z default

or 

oadm policy add-scc-to-user restricted admin
oc describe scc restricted
Name:  						restricted
Priority:      					<none>
Access:
  Users:       					admin
...

but 

oc logs local-nginx
2016/09/23 17:20:13 [emerg] 5#5: setgid(107) failed (1: Operation not permitted)
```

**Comment by ccustine** [comment]
I solved this last issue by doing this:
`$ oc edit scc anyuid`

and add:
```
users:
- system:serviceaccount:default:default
```
adjust to a more specific project or user as needed.  I tried the same commands as you but they do not seem to be valid any longer.

**Comment by budhrg** [comment]
@cmoulliard , By any chance, you have tried this with [latest minishift version](https://github.com/minishift/minishift/releases/tag/v1.0.0-beta.2)?

Also, did @ccustine comment help you to resolve it?

**Comment by budhrg** [comment]
Closing this issue now with resolution mentioned by @ccustine here https://github.com/minishift/minishift/issues/105#issuecomment-253692044.

Feel free to reopen it if you still face any issue related to it.
