### ISSUE TITLE
Make documentation about Hyper-V setup slightly more specific about virtual switch setup

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1051]
Currently it states:

---
### To use Minishift with Hyper-V:
 1. Install Hyper-V.
 2. Add a Virtual Switch.
---

I believe we should mention:

---
### To use Minishift with Hyper-V:
 1. Install Hyper-V.
 2. Add an **external** Virtual Switch.
---

As the only mention of External is now in point 3:

---
 3. <snip/> set the environment variable HYPERV_VIRTUAL_SWITCH to the name of the **external** virtual switch you want to use for Minishift.
---

**Comment by gbraad** [comment]
Would rather call it trivial, but that means assigning two priorities, and easyfix would prevent us from working on this.

**Comment by hferentschik** [comment]
Merged via pull request #1052.
