### ISSUE TITLE
Failure in `oc cluster up` does not abort bootstrapping

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1055]
If an error occurs in the following code in _start.go_

        err = clusterup.ClusterUp(clusterUpConfig, clusterUpParams, &util.RealRunner{})
	if err != nil {
		atexit.ExitWithMessage(1, fmt.Sprintf("Error during 'cluster up' execution: %v", err))
	}

	if !isRestart {
		postClusterUp(hostVm, clusterUpConfig)
	}

there won't be an error returned from clusterup.ClusterUp, meaning that _postClusterUp_ runs even though OpenShift is not running. This leads to errors in _postClusterUp_.

**Comment by gbraad** [comment]
This means that `oc cluster up` does not return appropriate error codes in all cases?
Maybe @csrwng can shed some light on this...

**Comment by csrwng** [comment]
@hferentschik @gbraad do you have the output of cluster up in such a case? Could it be that the server died after cluster up thought it was running?

**Comment by gbraad** [comment]
@csrwng for me it happens when the OpenShift origin fails to be pulled (such as index.docker.io being unreachable by timeout).

**Comment by hferentschik** [comment]
> for me it happens when the OpenShift origin container fails to be pulled

That's one of the cases, but not the only one.

**Comment by budhrg** [comment]
@csrwng It happened with me when testing one of PR here https://github.com/minishift/minishift/pull/1017#issuecomment-309434671. 

It says
```
Error during post cluster up configuration: Unable to add sudoer role
```
righter after `Docker up and running`.

**Comment by LalatenduMohanty** [comment]
@hferentschik  Shouldn't we open an issue in Origin as `cluster up` does not return proper error codes.

**Comment by hferentschik** [comment]
> Shouldn't we open an issue in Origin as cluster up does not return proper error codes.

Sure, once we looked into this and can confirm that this is the case. In fact there is already now some additional check in place on our side. We need to look at the full call change to see what needs to be done.

**Comment by csrwng** [comment]
If someone can reproduce locally, it'd be great to get a log of the failure to get a better idea of where things are failing.
