### ISSUE TITLE
Add support for Minikube ISO

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1058]
Currently we are only supporting b2d and centOS, we should also check minikube iso which is based on buildroot and have docker + rkt runtime.

### related pulls
  * [x] bind mount https://github.com/kubernetes/minikube/pull/1968
  * [x] Minishift paths https://github.com/kubernetes/minikube/pull/1993

**Comment by hferentschik** [comment]
Relates to issue #195

**Comment by hferentschik** [comment]
Depends on #1251

**Comment by gbraad** [comment]
Can you collect the PR you proposed, so we can track what is still needed to integrate on their end?

**Comment by praveenkumar** [comment]
@gbraad thanks for updating description along with PR 👍

**Comment by praveenkumar** [comment]
We have both merged so now with updated minikube-iso we can have provision minishift. I will send the provisioner update PR.

**Comment by budhrg** [comment]
> We have both merged so now with updated minikube-iso we can have provision minishift. I will send the provisioner update PR.

Cool :+1:

**Comment by gbraad** [comment]
Merged with a4373c0ab35b5eea77a4dca5783bfe36bc593e18
