### ISSUE TITLE
Add the ability to know the "commit sha" from where a client has been built

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1062]
When trying to debug multiple features, I have downloaded multiple different clients from PR and master URLs from CI server. Now I don't know which client is which, as there's no way to tell the difference.

It owuld be nice to be able to do:

````
$ minishift version
minishift v1.1.0

$ minishift version -v
minishift v1.1.0 (9948df3)
````

Or similar

**Comment by budhrg** [comment]
Duplicate of https://github.com/minishift/minishift/issues/515. :smile:
