### ISSUE TITLE
Use Minikube as dependency 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1063]
Core idea is to consume _pgk/minikube_ as a dependency. Moving forward this will make it easier to quicker get changes from Minikube and in return make it easier to contribute bug fixes.

The idea is to "share" the core of Minikube which sits on top of libmachine. Effectively this is _pgk/minikube_. This packages are mainly untouched, but we need to make sure to back port some changes we made. 

Regarding the command structure the plan is to not share the code, but rather try to align in user experience as much as possible.

**Comment by LalatenduMohanty** [comment]
@praveenkumar @gbraad @budhrg WDYT about this issue? Should we close this ?

**Comment by praveenkumar** [comment]
Yes, we should close this.
