### ISSUE TITLE
Error deleting a running VM

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1066]
Scenario:

I was running minishift, when I restarted the host laptop. After restart the laptop, I updated the client to latest minishift (1.2.0) although I don't think this is related. I tried to delete the minishift VM to test caching of images, and I got this output:

````
$ minishift delete
Current Minishift VM is registered, but unregistration failed. Do you still want to delete the VM [y/N]?: n
Delete aborted.

$ minishift status
Running

$ minishift stop
Stopping local OpenShift cluster...
Error unregistering the VM: ssh command error:
command : sudo cat /etc/os-release
err     : exit status 255
output  : No user exists for uid 501
````

**Comment by jorgemoralespou** [comment]
I deleted the VM, and started a new one, and got:

````
$ minishift start
Starting local OpenShift cluster using 'xhyve' hypervisor...
E0627 13:20:01.201424   70973 start.go:275] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: exit status 1. Retrying.
````

And stuck there. I have deleted *.minishift/machines* and same error.

Deleted .minishift, and then this error:

````
 minishift start
-- Installing default add-ons ... OK
Starting local OpenShift cluster using 'xhyve' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
E0627 13:22:22.262010   71562 start.go:275] Error starting the VM: Get https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso: x509: certificate signed by unknown authority. Retrying.
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
E0627 13:22:22.463088   71562 start.go:275] Error starting the VM: Get https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso: x509: certificate signed by unknown authority. Retrying.
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
E0627 13:22:22.661905   71562 start.go:275] Error starting the VM: Get https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso: x509: certificate signed by unknown authority. Retrying.
Error starting the VM: Get https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso: x509: certificate signed by unknown authority
Get https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso: x509: certificate signed by unknown authority
Get https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso: x509: certificate signed by unknown authority

$ minishift delete
The execution of this command requires an existing 'minishift' VM. However, there is currently none defined.

$ minishift stop
The execution of this command requires an existing 'minishift' VM. However, there is currently none defined.

$ minishift start
Starting local OpenShift cluster using 'xhyve' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
E0627 13:23:14.446466   71687 start.go:275] Error starting the VM: Get https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso: x509: certificate signed by unknown authority. Retrying.
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
E0627 13:23:14.648756   71687 start.go:275] Error starting the VM: Get https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso: x509: certificate signed by unknown authority. Retrying.
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
E0627 13:23:14.849242   71687 start.go:275] Error starting the VM: Get https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso: x509: certificate signed by unknown authority. Retrying.
Error starting the VM: Get https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso: x509: certificate signed by unknown authority
Get https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso: x509: certificate signed by unknown authority
Get https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso: x509: certificate signed by unknown authority
````

**Comment by jorgemoralespou** [comment]
Restarting seem to have fixed the issue for me. Although I'm working, there's an issue with deleting a VM that has been somehow stopped by a host restart.

Using xhyve.

**Comment by LalatenduMohanty** [comment]
@jorgemoralespou Once you deleted `.minishift` then `delete` and `stop` gave you right feedback. 

> I deleted the VM, and started a new one, and got:

You did not mention, how you deleted the VM. 

```
$ minishift start
Starting local OpenShift cluster using 'xhyve' hypervisor...
E0627 13:20:01.201424   70973 start.go:275] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: exit status 1. Retrying.
```
This is something is we need to dig more. It error comes from Xhyve and thats why when you restarted the machine Xhyve got reset e.g. existing processes got killed .

**Comment by gbraad** [comment]
for xhyve you first need to look for a stall process with `ps ax` and then minishift delete would work. this issue happens when the state is `Running`, but the instance can not be logged into.

on KVM you can do the following:
```
$ sudo virsh destroy minishift      # stop
$ sudo virsh undefine minishift     # delete
```

**Comment by hferentschik** [comment]
@jorgemoralespou, so xhyve works for you now?

**Comment by hferentschik** [comment]
We have seen similar issues before and I think the initial issue is about "bad" or insufficient error handling in when executing the ssh registration command.

**Comment by jorgemoralespou** [comment]
Guys,
I did delete the VM with "rm -rf ~/.minishift/machines/minishift" as described in my second comment, after "minishift delete", so both actions were taken.

Having instructions for KVM didn't help me solve the issue. I didn't found any stalled process.

I switched to use Virtualbox. I have retried again now (after 2 hours) and it's working fine with xhyve, so I guess it's something related to xhyve networking that time eventually fixed.

And yes, before reporting, I did clean the dhcp_leases and restarted the host.

@hferentschik I disagree (although without much base here). I would think that because of the restart the state was not consistent, so minishift was detecting the VM as running but it was not, due to the reboot, or that the Ip that the VM got assigned was different (maybe because of the dhcp lease).

I would think that as part of a graceful shutdown of the laptop, the VM needs to be stopped, and I would think that's not happening. I could guess this would prevent the issue.

**Comment by gbraad** [comment]
@hferentschik it is not only about the SSH handling. It seems that xhyve can be in a inconsistent state, where the hypervisor is `running`, but not reported correctly. In those cases I was only able to move forward by looking for a stall process or even a reboot.

Note: KVM instructions were given for those who will find the issue as this is similar on other platforms.

**Comment by jorgemoralespou** [comment]
@gbraad then, make sure the instructions make into the troubleshooting section of the docs ;-)

**Comment by gbraad** [comment]
@jorgemoralespou The instructions for KVM are described: https://github.com/minishift/minishift/blob/master/docs/source/using/troubleshooting.adoc#kvm-domain-minishift-already-exists but the title might need an update. For xhyve I do not have a good alternative, as there are to my knowledge no real commandline tools ?

**Comment by gbraad** [comment]
> insufficient error handling in when executing the ssh registration command.

The `stop` command wants to check if the instance is registered. But if the node is not registered, and we keep this state in the config of instance, we only `unregister` when registered. In the current code we always unregister: https://github.com/minishift/minishift/blob/master/cmd/minishift/cmd/stop.go#L65 (unless we skip). This seems to be wrong, as this is not needed with b2d and the centos image, but will always be performed. /cc: @hferentschik @LalatenduMohanty @budhrg I gues registration should always be set to 'false', unless the provisioner was able to register... WDYT?

**Comment by gbraad** [comment]
Would could happen is the following:

1. Minishift is started and registers an PID in `~/.minishift/machines/minishift/minishift.pid`
2. The machine is rebooted
3. `minishift status` uses the recorded PID to get the status
4. It finds a running process (note: this is not `xhyve`)
5. docker-machine wrongly assumes that the machine instance is active and SSH fails

See: https://github.com/zchee/docker-machine-driver-xhyve/blob/master/xhyve/xhyve.go#L316

**Comment by jorgemoralespou** [comment]
As I said, typically processes have a shutdown hook. I guess minishift does not as it's not a daemon, but a command, so probably you need to better validate that the pid corresponds to minishift.

**Comment by budhrg** [comment]
@amitkrout @agajdosi , can you verify this issue and do the needful action? Its quite an old issue and not sure it is still valid.

**Comment by amitkrout** [comment]
Looking into it

**Comment by amitkrout** [comment]
```
Environment : OS X + xhyve
```
I dint see a any error/issue mentioned as above while running the same on minishift 1.6.0 and 1.7.0.
```
1. Amits-MacBook-Pro:v1.6.0 amit$ ./minishift start
-- Installing default add-ons ... OK
-- Checking if xhyve driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
.
.
2. Restarted the host machine 
3. Amits-MacBook-Pro:v1.7.0 amit$ ./minishift delete
You are deleting the Minishift VM: 'minishift'. Do you want to continue [y/N]?: y
Deleting the Minishift VM...
Minishift VM deleted.
Amits-MacBook-Pro:v1.7.0 amit$ ./minishift start
-- Checking if xhyve driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
.
.
```
Closing the issue. If you find the issue still persist, please feel free to reopen it or create a new issue in minishift repo.
