### ISSUE TITLE
Networking issues inside VM fail to download containers

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1067]
I have a new .minishift directory and I have image-caching enabled and I get this error:

````
$ minishift start
Starting local OpenShift cluster using 'xhyve' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
 40.00 MiB / 40.00 MiB [===================================================================================================================================================================================================] 100.00% 0s
Downloading OpenShift binary 'oc' version 'v1.5.1'
 18.94 MiB / 18.94 MiB [===================================================================================================================================================================================================] 100.00% 0s
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.1 image ...
   Pulling image openshift/origin:v1.5.1
FAIL
   Error: error pulling Docker image openshift/origin:v1.5.1
   Caused By:
     Error: Network timed out while trying to connect to https://index.docker.io/v1/repositories/openshift/origin/images. You may want to check your internet connection or if you are behind a proxy.
OpenShift provisioning failed. origin container failed to start.
````

But of course docker is working:

````
$ docker pull openshift/origin:v1.5.1
v1.5.1: Pulling from openshift/origin
343b09361036: Already exists
61608a27509c: Pull complete
e532a8f89bff: Pull complete
Digest: sha256:6875fa269911889d29003a566654caab710df3bd2fa9ce8e894b85c21da45de7
Status: Downloaded newer image for openshift/origin:v1.5.1
````

Seems like networking from the VM is not working correctly after #1066

**Comment by LalatenduMohanty** [comment]
@jorgemoralespou as mentioned in #1066 I guess after the restart things would have worked for you. I feel the issue occurs when Xhyve does not respond properly.

**Comment by hferentschik** [comment]
@jorgemoralespou are you sure this is tied to the empty Minishift directory and not a (temporary) network  issue? The required Minishift folders are created when needed, so I am a bit puzzled about the connection here. 

Can you reproduce this? Empty $MINISHIFT_HOME and start over. Does it fail the same way?

**Comment by jorgemoralespou** [comment]
@hferentschik I think it has nothing to do with both, but with the fact that somehow xhyve has been screwed after the previous VM got deleted as described in #1066.

Networking from inside the VM is not working. I can not resolve external servers.

**Comment by LalatenduMohanty** [comment]
@jorgemoralespou I think we can close this issue or do you have any thing specific to fix?

**Comment by jorgemoralespou** [comment]
As long as #1066 tries to adress the underlying problem here described, I'm fine.

Although, maybe it would be good to add some pre-flight tests to validate there's networking from within the VM, and provide a nicer error.

**Comment by gbraad** [comment]
Preflight checks for this are easy to add, as these test functions have
been added as part of the bodybuilders functionality. They only need to be
called for a static address (url and IP) to test outgoing traffic and DNS.

https://github.com/minishift/minishift/issues/485#issuecomment-284710930

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by budhrg** [comment]
@gbraad , I think this has been address in pre-flight checks now.

**Comment by agajdosi** [comment]
@gbraad I have same understanding as @budhrg, Minishift now pings the external host and checks http connectivity. If you agree, we can close this issue.

```
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
```

**Comment by gbraad** [comment]
Closing
