### ISSUE TITLE
Hyper-V support 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#107]
I am a bit confused about whether Hyper-V is really supported by minishift/minikube. In the README I can see:

> VirtualBox or Hyper-V installation,

as a Windows prerequisite, but I don't seem to be able to get minishift to start using Hyper-V. I am getting the following:

```
.\minishift-windows-amd64.exe start  --vm-driver=hyperv --show-libmachine-logs=true
Starting local OpenShift cluster...
Found binary path at C:\Users\hardy\work\minishift\minishift-windows-amd64.exe
Launching plugin server for driver hyperv
() DBG | F0926 19:11:41.751512    4164 client.go:39] Unsupported driver: hyperv
Plugin server listening at address
E0926 19:11:41.775618    3756 start.go:89] Error starting host: Error creating new     host: dial tcp: missing address. Retr
ying.
Found binary path at C:\Users\hardy\work\minishift\minishift-windows-amd64.exe
Launching plugin server for driver hyperv
() DBG | F0926 19:11:41.817208    2624 client.go:39] Unsupported driver: hyperv
Plugin server listening at address
E0926 19:11:41.834723    3756 start.go:89] Error starting host: Error creating new     host: dial tcp: missing address. Retr
ying.
Found binary path at C:\Users\hardy\work\minishift\minishift-windows-amd64.exe
Launching plugin server for driver hyperv
() DBG | F0926 19:11:41.882768    7996 client.go:39] Unsupported driver: hyperv
Plugin server listening at address
E0926 19:11:41.914938    3756 start.go:89] Error starting host: Error creating new     host: dial tcp: missing address. Retr
ying.
E0926 19:11:41.918025    3756 start.go:95] Error starting host:  Error creating new     host: dial tcp: missing address
Error creating new host: dial tcp: missing address
Error creating new host: dial tcp: missing address
```

Looking at the code in question - https://github.com/jimmidyson/minishift/blob/master/pkg/minikube/machine/client.go#L39 - it seems all except _virtualbox_ and _vmwarefusion_ won't work.  Am I missing something? If nothing else there is at least some documentation missing on how to get this to work for Hyper-V.

**Comment by hferentschik** [comment]
FYI, I am able to use docker-machine with Hyper-V, but only after using the _hyperv-virtual-switch_ flag. 

    docker-machine create --driver hyperv --hyperv-virtual-switch machine-switch default

Looking at minikube, I can see that there is a feature request to enable this option also on minikube - https://github.com/kubernetes/minikube/issues/561. Given that I needed this option to get docker-machine to work, I am wondering whether I would need it for minikube/minishift as well.

**Comment by hferentschik** [comment]
BTW, I am using Minishift version 0.7.1. Is there anyone who got this version to work with on Windows using Hyper-V? And if so, how? (BTW, it works fine with VirtualBox).

**Comment by jimmidyson** [comment]
I have to admit to it being untested - should have marked it as experimental really... Would love someone Windows-y being able to help out with this fix.

**Comment by hferentschik** [comment]
> I have to admit to it being untested - should have marked it as experimental really... Would love someone Windows-y being able to help out with this fix.

Ok, thanks. That's kind of what I expected at this stage. I really could not understand how the code would even process beyond this simple switch in case of _hyperv_. I am happy to to test anything which moves this into the right direction.

**Comment by jimmidyson** [comment]
So that bit of code you linked to above is not the bit of code that does anything to do with hyper-v as you've noticed. What that's doing is registering some bundled drivers with minishift/minikube. Docker Machine, which they both use embedded under the hood, forks a new process for configuration of machine drivers to create the Docker machine (VM). If the driver specified is registered in the way you've linked, then it actually execs its own process... Bit confusing but it works :)

The actual code where the hyper-v driver is configured is in https://github.com/jimmidyson/minishift/blob/master/pkg/minikube/cluster/cluster_windows.go. You can see the options being passed to the driver. Details on the options are at https://docs.docker.com/machine/drivers/hyper-v/ & https://github.com/docker/machine/blob/master/drivers/hyperv/hyperv.go.

**Comment by hferentschik** [comment]
Ok got you, so it might be just a small change which is needed. Fair enough

**Comment by hferentschik** [comment]
Closing - out of date.
