### ISSUE TITLE
Sprint planning script does not return all issues for a milestone

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1075]
Sprint planning script [1] does not return all issues for a milestone e.g. https://github.com/minishift/minishift/milestone/11.

I have observed that it happens when a milestone for an issue has changed multiple time and it is an old issue. 

[1] minishift/scripts/planning/sprint-planning.sh

**Comment by hferentschik** [comment]
Closing this issue since it is a duplicate of #1526.
