### ISSUE TITLE
CentOS/RHEL lock-up due to exhausting the live-rw filesystem of the VM

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1076]
Opening a new issue as #355 is closed now (we have fixed the original issues mentioned in #355) 

As @jhcook mentioned in #355 user is facing similar issue of lock-up due to exhausting the live-rw filesystem of the VM but this is because of `yum install` of packages or extracting an archive inside a directory under /, which is still inside the RW filesystem

P:S: updated the description as per https://github.com/minishift/minishift/issues/1076#issuecomment-311616674

**Comment by gbraad** [comment]
... and extracting an archive inside a directory under `/`, which is still inside the RW filesystem.

**Comment by jhcook** [comment]
Thank you gentlemen. This sums it up nicely.

**Comment by gbraad** [comment]
The next step for us is to come up with possible solutions and pros and cons for them.

Possible solutions are:
  * use SPC (super privileged containers) instead of package install
  * add symlink to `/opt` and describe relocate of `RPMROOT` when installing
  * add an overlay to allow package insralls
  * etc ...

**Comment by gbraad** [comment]
https://github.com/minishift/minishift-centos-iso/issues/116

**Comment by hferentschik** [comment]
> until we have found a solution to the above-described problem.

As a temporary measurement ok. Trying to install software might be the most common use case where this issue occurs, but the user might fill up the file system in many other ways. Really this feels like a bandaid at best.

**Comment by gbraad** [comment]
@hferentschik the other case(s) we have under control, as the usage of VM is for running OpenShift. For this we relocate onto a persistent disk. Sure, when this disk is full, we have a similar problem. Having an overlay would not solve this either, so we also would need some feedback on the disk state maybe? This is something I can add easily as part of #485, as I already check if the disk is mounted... I can also check if enough storage is available on this disk.

Which solution would you prefer? At this moment I do not want to prevent installation, but I would like to demotivate it...

**Comment by hferentschik** [comment]
>  At this moment I do not want to prevent installation, but I would like to demotivate it...

That works for me. A warning is probably a good thing. Maybe you can even print the amount of space left, so that one can make a conscious decision?

**Comment by gbraad** [comment]
We can not determine the amount of space left, as this is based on memory usage and not actual storage. Commands like `df -h` give misleading results... and this is why most people do not notice this at first.

**Comment by praveenkumar** [comment]
@gbraad/ @hferentschik As warning we already put banner in the ISO for this. what action item left for this issue?

**Comment by gbraad** [comment]
>  * add symlink to /opt and describe relocate of RPMROOT when installing

The following PR, related to this, is still open: https://github.com/minishift/minishift-centos-iso/pull/127

> use SPC (super privileged containers) instead of package install

We might be able to close this issue, but want further discussion about this. I believe we can support some of the additional software, like the nfs-utils, cifs, etc, from containers instead. especially going forward, this comes close to a modular OS image. In our case this would not need a big change...

**Comment by gbraad** [comment]
we should also consider promoting the re-use of the Docker environment, like in an article, blog post or documentation, as a way to setup/deal with a development workflow where they do NOT use the Live R/W filesystem of the VM.

**Comment by LalatenduMohanty** [comment]
I think https://docs.openshift.org/latest/minishift/troubleshooting/troubleshooting-misc.html#root-filesystem-exceeds-overlay-size has enough information for users. Hence closing this issue as we want to go down the path where users should use containers rather than installing through YUM.
