### ISSUE TITLE
Feedback when clearing cache

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1078]
The command `minishift delete --clear-cache` does not provide feedback about the action happening or not.

**Comment by certainlynotbarton** [comment]
Can I have this as my first-time contribution ?

https://github.com/minishift/minishift/blob/7544af22b6bd3953d516d3fc2f49827b04093ab0/cmd/minishift/cmd/delete.go#L63

**Comment by gbraad** [comment]
Worked on by @dharmit

**Comment by hferentschik** [comment]
Merged via pull request #1089
