### ISSUE TITLE
Minishift not working with CentOs and VirtualBox

### ISSUE THREAD

**Issue by aberhallo** [minishift/minishift#1080]
Running minishift with following command `minishift.exe start --vm-driver virtualbox --iso-url centos`  leads to the error: _"Error to register VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s"_ 

Looking at the VirtualBox Manager I can see that it stopped at prompt "`localhost login:`".

Env: VirtualBox v5.1.22, minishift v1.2.0, no proxies set 

Any idea?

**Comment by hferentschik** [comment]
And it works for the default ISO? Did you have another Minishift VM running before that? 
Could you try:

     $ minishift delete
     $ minishift.exe start --vm-driver virtualbox --iso-url centos

You could also try opening the VirtualBox manager to check whether there is Minishift VM running and potentially delete it.

**Comment by aberhallo** [comment]
Hi,

Thanks for your quick reply. The other image fails due to
https://github.com/minishift/minishift/issues/920

I tried to delete - also the cache - several times. Sometimes it fails
already creating the vm with the same error msg mentioned above or it is
waiting within the vm for login as described.


Regards
Andreas

**Comment by aberhallo** [comment]
Also deleted the VM in the VB manager.

**Comment by gbraad** [comment]
This might be similar to what we saw in ealier versions: #159. Something like a version conflict or not yet supported. Or... what is your host platform? If you are on Windows, please make sure you are running `minishift.exe` from the `C:` drive.

**Comment by hferentschik** [comment]
And you can otherwise use VirtualBox? Independent of Minishift?

**Comment by aberhallo** [comment]
Yes, I have several images which work in VB without any problem.

**Comment by aberhallo** [comment]
Ps: also in combination with vagrant...

**Comment by hferentschik** [comment]
ok, fair enough. Just checking.

**Comment by aberhallo** [comment]
Hi,

The docu says "_you need to execute the minishift binary from the drive containing your %USERPROFILE% directory"..._ and since my user is on D: I used D: up to now...

Changing this to C: (and specify the ISO location on startup since it's not found anymore otherwise) it is working now! 

Documentation should be updated I think :-)   

Thanks for Support, regards
Andreas

**Comment by gbraad** [comment]
Good to hear and we will make sure the documentation gets updated.
BTW, was `D:` a local disk or a network disk?

**Comment by aberhallo** [comment]
local disk.
