### ISSUE TITLE
Create integration test for proxy

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1084]
Upstream version for [CDK-90](https://issues.jboss.org/browse/CDK-90).

**About**
Integration tests needs to cover "behind the proxy" situation, which gave us some problems in past. Current plan is to use [go-proxy](https://github.com/elazarl/goproxy) to setup proxy directly on developer's computer to keep integration tests close to developers.

**Current state**
In what I have now: feature is able to start proxy, then start minishift with --http-proxy - and start runs successfully. However IP address of network device is still needed. Will try to automate this process. Another big task is to take care of all the logging and checking that the traffic really goes through the proxy.

**Comment by hferentschik** [comment]
merged via pull request #1095
