### ISSUE TITLE
Not able to hit MiniShift docker registry

### ISSUE THREAD

**Issue by khatribharat** [minishift/minishift#1091]
I'm running MiniShift under qemu/kvm on Ubuntu 17.04. I got into the VM and looked into the networking fabric

- *docker0* - `172.17.0.1/16`
- *router* - using Docker's `host` network, MiniShift web console shows its IP as `172.30.157.198`
- *docker-registry* - using Docker's `bridge` network, MiniShift web console shows its IP as `172.30.1.1`

I got into **router**'s container and pinged `172.30.1.1` (**registry**) and it was unreachable.

How do I hit the **registry** using its IP from docker host/VM?

This all started with applying the `registry-route` addon. At first it failed with the error 

`The Route "docker-registry" is invalid: spec.host: Invalid value: "docker-registry-default.": host must conform to DNS 952 subdomain conventions` 

This happened even when I specified a `routing-suffix` with `minishift start`

To fix the error, I edited the `registry-route` addon file replacing `#{routing-suffix}` with `khatri.local` and reran `minishift addons apply registry-route` and it worked.

However, running 
```
eval $(minishift docker-env)
docker login -u developer -p `oc whoami -t` docker-registry-default.khatri.local:443
```
failed with the error 

`Error response from daemon: Get https://docker-registry-default.khatri.local:443/v1/users/: dial tcp: lookup docker-registry-default.khatri.local on 192.168.122.1:53: server misbehaving`

Going inside the VM and running `nslookup docker-registry-default.khatri.local` failed too.

**Comment by hferentschik** [comment]
> To fix the error, I edited the registry-route addon file replacing #{routing-suffix} with khatri.local

Unless you specified the routing-suffix as part of the `minishift start` command as well, this is not going to work. Also if you have some special networking configuration in place, _khatri.local_ is not going to work as a routing suffix. 

To be honest, I am a bit lost on what you are trying to do and what the error is. Can you maybe post what you want to do and the steps to re-produce the issue?

**Comment by hferentschik** [comment]
Going to close this. If you are still having issues and some more context, please re-open.
