### ISSUE TITLE
PostgreSQL from MiniShift catalog fails on permissions for /var/lib/pgsql/data

### ISSUE THREAD

**Issue by khatribharat** [minishift/minishift#1092]
This is probably related to https://github.com/kubernetes/kubernetes/issues/2630

The PostgreSQL pod fails with the error : 
`mkdir: cannot create directory '/var/lib/pgsql/data': Permission denied`

I tried the following steps but it didn't work.

1. `oc adm policy add-scc-to-user anyuid system:serviceaccount:myproject:default`
2.  Inside the PostgreSQL container 
```
> id postgres                                                             
uid=26(postgres) gid=26(postgres) groups=26(postgres)
```
3. Add the following to the PostgreSQL pod spec
```
securityContext:
        fsGroup: 26
```
4. Rerun the deployment

**Comment by hferentschik** [comment]
Which Postgres image do you try to deploy and how do you do it?

**Comment by jorgemoralespou** [comment]
Might be SElinux if using Centos or RHEL ISOs?

**Comment by gbraad** [comment]
@khatribharat please provide the requested information

**Comment by khatribharat** [comment]
I'm running MiniShift under qemu/kvm on Ubuntu 17.04.

**VM**
```
Boot2Docker version 1.12.3, build HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
Docker version 1.12.3, build 6b644ec
```

**MiniShift**
```
> minishift openshift version
openshift v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
etcd 3.1.0
```

**PostgreSQL**
```
centos/postgresql-95-centos7@sha256:07ef74dad137ffd51131b17e8ddec1cf7281eb06769c30c605f1e82e4b0cc02c
```

**Comment by hferentschik** [comment]
@khatribharat, can you provide the steps to re-produce this. I am running Minishift out of the box with no add-ons enabled and I run:

     $ oc new-app -e POSTGRESQL_ADMIN_PASSWORD=foo centos/postgresql-95-centos7 --name postgres-95
     $ oc rollout status deploymentconfig postgres-95 --watch

The DB pod starts fine. For what it's worth, here are the logs from the pod:

    The files belonging to this database system will be owned by user "postgres".
    This user must also own the server process.
    
    The database cluster will be initialized with locale "en_US.utf8".
    The default database encoding has accordingly been set to "UTF8".
    The default text search configuration will be set to "english".
    
    Data page checksums are disabled.
    
    fixing permissions on existing directory /var/lib/pgsql/data/userdata ... ok
    creating subdirectories ... ok
    selecting default max_connections ... 100
    selecting default shared_buffers ... 128MB
    selecting dynamic shared memory implementation ... posix
    creating configuration files ... ok
    creating template1 database in /var/lib/pgsql/data/userdata/base/1 ... ok
    initializing pg_authid ... ok
    initializing dependencies ... ok
    creating system views ... ok
    loading system objects' descriptions ... ok
    creating collations ... ok
    creating conversions ... ok
    creating dictionaries ... ok
    setting privileges on built-in objects ... ok
    creating information schema ... ok
    loading PL/pgSQL server-side language ... ok
    vacuuming database template1 ... ok
    copying template1 to template0 ... ok
    copying template1 to postgres ... ok
    
    WARNING: enabling "trust" authentication for local connections
    You can change this by editing pg_hba.conf or using the option -A, or
    --auth-local and --auth-host, the next time you run initdb.
    syncing data to disk ... ok
    
    Success. You can now start the database server using:
    
        pg_ctl -D /var/lib/pgsql/data/userdata -l logfile start
    
    waiting for server to start....LOG:  redirecting log output to logging collector process
    HINT:  Future log output will appear in directory "pg_log".
     done
    server started
    ALTER ROLE
    waiting for server to shut down.... done
    server stopped
    LOG:  redirecting log output to logging collector process
    HINT: Future log output will appear in directory "pg_log".

**Comment by khatribharat** [comment]
Deleted the VM, and restarted minishift. It works now, not sure how to reproduce this. For now, I'm closing the issue.

The log line `fixing permissions on existing directory /var/lib/pgsql/data/userdata ... ok` explains that the permissions are set correctly.
