### ISSUE TITLE
Update documentation: minishift.exe only works properly from C:\

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1098]
In the current documentation it mentions:

*On Windows operating system, due to issue #236, you need to execute the minishift binary from the drive containing your %USERPROFILE% directory.*

This is not completely true. If the user by domain policy has his profile served over a network drive, or places it on another disc, it seems minishift.exe will still only work from `C:\`.

This might need further investigation, but in recent time 3 issues have resulted from this... and the solution was "run from C:\".

**Comment by thatdocslady** [comment]
@gbraad based on the description of this issue and of issue #236 I propose that we add to the existing sentence the following sentence: "The %USERPROFILE% directory must be located in your C:\ drive, and cannot be on a network drive." Double-explicit :) WDYT?

**Comment by hferentschik** [comment]
Merged via pull request #1142

**Comment by victorhanxu** [comment]
On the Windows operating system, we need to execute the minishift.exe binary from the root dir of C:\ drive. Otherwise it will fail while starting oc cluster.

**Comment by gbraad** [comment]
it is actually `$WINDRIVE` (the location where the OS is installed. For some people they use `D:` or otherwise. The selection is actually more strict, ... but usually `C:\` for the exedcutable (and user profile) is preferred.
