### ISSUE TITLE
Minishift not starting

### ISSUE THREAD

**Issue by ibaboo** [minishift/minishift#1100]
Minishift is not starting.

OS: Linux Mint 18 Sarah
Minishift version: 1.0.1
KVM: QEMU emulator version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.14)
libvirt-bin: 1.3.1-1ubuntu10.10

Below is the output of my logs and the start command

`sudo minishift start --vm-driver kvm --show-libmachine-logs --v=10 --alsologtostderr`

```
Getting to WaitForSSH function...
(minishift) Calling .GetSSHHostname
(minishift) DBG | GetIP called for minishift
(minishift) DBG | Failed to decode dnsmasq lease status: unexpected end of JSON input
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:a5:2a:9c
Error getting ssh command 'exit 0' : unexpected end of JSON input
```

**Comment by gbraad** [comment]
Please try with a newer version of Minishift. Current release is 1.2.0. First do a `minishift delete --clear-cache` and retry to start.

**Comment by ibaboo** [comment]
Hi @gbraad thanks that worked. Apologies :)
