### ISSUE TITLE
CentOS CI build should send build notifications 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1101]
It would be nice to integrate CentOS CI builds into minibot notifications as well. For that to work the CentOS CI build need to be able to send HTTP notifications with JSON/XML payload.

There is a plugin for that https://wiki.jenkins.io/display/JENKINS/Notification+Plugin, however, it might be easier to do this manually as part of the centos-ci.sh script. `curl` can for example be used to send the notifications. This way we can hand-roll the payload. In particular it would be nice to post the URLs for the atifact downloads directly into the chat as part of the success message.

Since we also control the receiving end in Minibot we cam send just the payload we need.

**Comment by LalatenduMohanty** [comment]
@hferentschik Is this something we want to fix?
