### ISSUE TITLE
Incorrect variable quoting for Fish shell

### ISSUE THREAD

**Issue by james-mcelwain** [minishift/minishift#1103]
This appears to have been introduced recently, so I'm a little confused.

The output of `minishift oc-env` (V1.2.0) produces:

`set -gx PATH "/Users/36781/.minishift/cache/oc/v1.5.1" "$PATH";`

However, Fish complains about quoting "$PATH" due to the way this works in Fish shell with lists. See:
```
set LIST 1 2 3
count $LIST  # shows 3
count "$LIST" # shows 1
```
Also verifiable with `set PATH "$PATH"` which will always complain about the single argument being passed to set rather than a list.

Someone correct me if I'm wrong.

**Comment by budhrg** [comment]
@james-mcelwain , we just want to be more on defensive side by enclosing `$PATH` in double quotes. See https://github.com/minishift/minishift/issues/1006#issuecomment-307363886. 

Though we are not really fish shell users, but both (with  or w/o double quotes) were working. We enclosed in double quotes to be on safer side.

**Comment by hferentschik** [comment]
@james-mcelwain, so what is the exact error when you paste the output of _oc-env_?

**Comment by james-mcelwain** [comment]
On my regular Fish theme, the output of `minishift oc-env` blows up my terminal such that I have to completely kill it. [1] As you'll notice, there's a bunch of references to internal Fish functions, but then below that, it's failing to find a bunch of basic utilities that should exist on path (I promise, I didn't uninstall `sed` :P). Curiously, there's also a reference to a theme ("cmorrell"), which is my Fish theme. However, I have switched to the default Fish theme and uninstalled that theme. 

Switching to default theme also allows me to remain connected to my current terminal session (I think this is because cmorrell theme uses git). Since I can execute some Fish commands on the default theme, I just ran `count $PATH` which returns `2`, suggesting that my path is `/oc/binary/path /usr/local/bin\ /bin\ ...`.

Executing `set PATH "$PATH"` complains
```
set: Warning: path component /usr/local/bin /usr/bin /bin /usr/sbin /sbin may not be valid in PATH.
set: No such file or directory
```
but interestingly, `count $PATH` still returns `5` and everything still works.

I also made sure to upgrade my Fish version from `2.2.0` to `2.6.0` and same problem.

[1]:
```
set: Warning: path component /usr/local/bin /usr/bin /bin /usr/sbin /sbin may not be valid in PATH.
set: No such file or directory
/usr/local/Cellar/fish/2.2.0/share/fish/functions/type.fish (line 1): seq (count $argv)
                                                                      ^
in command substitution
	called on line 2 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/type.fish

in function 'type'
	called on standard input
	with parameter list '-q -p command-not-found'

in function '__fish_command_not_found_setup'
	called on line 40 of file ~/.config/fish/functions/fish_prompt.fish
	with parameter list 'hostname -s'

in event handler: handler for generic event 'fish_command_not_found'

/usr/local/Cellar/fish/2.2.0/share/fish/functions/type.fish (line 1): seq (count $argv)
                                                                      ^
in command substitution
	called on line 2 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/type.fish

in function 'type'
	called on standard input
	with parameter list '-p -q pkgfile'

in function '__fish_command_not_found_setup'
	called on line 40 of file ~/.config/fish/functions/fish_prompt.fish
	with parameter list 'hostname -s'

in event handler: handler for generic event 'fish_command_not_found'

fish: Unknown command 'hostname'
~/.config/fish/functions/fish_prompt.fish (line 1): hostname -s
                                                    ^
in command substitution
	called on line 38 of file ~/.config/fish/functions/fish_prompt.fish

in function 'show_user'
	called on line 79 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'whoami'
~/.config/fish/functions/fish_prompt.fish (line 1): whoami
                                                    ^
in command substitution
	called on line 38 of file ~/.config/fish/functions/fish_prompt.fish

in function 'show_user'
	called on line 79 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'sed'
/usr/local/Cellar/fish/2.2.0/share/fish/functions/prompt_pwd.fish (line 2): 	echo $PWD | sed -e "s|^$realhome|~|" $args_pre -e 's-\([^/.]\)[^/]*/-\1/-g' $args_post
                                                                            	            ^
in function 'prompt_pwd'
	called on line 56 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
	called on line 54 of file ~/.config/fish/functions/fish_prompt.fish

in function 'show_pwd'
	called on line 80 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'id'
~/.config/fish/functions/fish_prompt.fish (line 1): id -u $USER
                                                    ^
in command substitution
	called on line 60 of file ~/.config/fish/functions/fish_prompt.fish

in function 'show_prompt'
	called on line 81 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

test: Missing argument at index 2
fish: Unknown command 'git'
~/.local/share/omf/themes/cmorrell/fish_right_prompt.fish (line 1): if command git rev-parse --is-inside-work-tree >/dev/null 2>&1
                                                                               ^
in function 'get_git_status'
	called on line 28 of file ~/.local/share/omf/themes/cmorrell/fish_right_prompt.fish

in function 'fish_right_prompt'
	called on standard input

in command substitution
	called on standard input
```

**Comment by james-mcelwain** [comment]
Looks like the Fish documentation is pretty explicit about this behavior too:

> Variable expansion is the only type of expansion performed on double quoted strings. There is, however, an important difference in how variables are expanded when quoted and when unquoted. An unquoted variable expansion will result in a variable number of arguments. For example, if the variable $foo has zero elements or is undefined, the argument $foo will expand to zero elements. If the variable $foo is an array of five elements, the argument $foo will expand to five elements. When quoted, like "$foo", a variable expansion will always result in exactly one argument. Undefined variables will expand to the empty string, and array variables will be concatenated using the space character.

Also, I'm sure these kinds of cross-shell issues are annoying, thank you so much for taking the time to support Fish in the first place!

**Comment by budhrg** [comment]
hi @james-mcelwain ,

Thanks for the explanation.  
Does the following works for you?
```
set -gx PATH "/Users/36781/.minishift/cache/oc/v1.5.1" $PATH;
```

**Comment by james-mcelwain** [comment]
@budhrg Yup, that works!

```
set -gx PATH "/Users/36781/.minishift/cache/oc/v1.5.1" $PATH;
echo $PATH
/Users/36781/.minishift/cache/oc/v1.5.1 /usr/local/bin /usr/bin /bin /usr/sbin /sbin
count $PATH
6
```

**Comment by budhrg** [comment]
Closed via https://github.com/minishift/minishift/pull/1350
