### ISSUE TITLE
KVM issues on Manjaro (Arch Linux)

### ISSUE THREAD

**Issue by SuperNami** [minishift/minishift#1112]
Manjaro linux with latest updates installed
[minishift v1.1.0](https://aur.archlinux.org/packages/minishift-bin/)
docker-machine version 0.12.1, build HEAD
[docker-machine-kvm 0.7.0-2](https://aur.archlinux.org/packages/docker-machine-kvm/)

Output when running `minishift start` fails:
```
[user@desktop folder]$ minishift start
Starting local OpenShift cluster using 'kvm' hypervisor...
E0709 18:47:45.557327   32615 start.go:234] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
E0709 18:47:47.309234   32615 start.go:234] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
E0709 18:47:49.053310   32615 start.go:234] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
Error starting the VM: Error getting the state for host: unexpected EOF
Error getting the state for host: unexpected EOF
Error getting the state for host: unexpected EOF
```

**Comment by gbraad** [comment]
When KVM responds with unexpected EOF it is usually the communication of the driver and libvirt.
Can you try to make sure they can run a VM without minishift?

And can you describe more about your installation procedure?

**Comment by gbraad** [comment]
Any updates on this matter?

**Comment by agajdosi** [comment]
Hi @SuperNami, this issue is lying here inactive for a while, have you managed to resolve the problem or is it still bothering you?

**Comment by agajdosi** [comment]
Hi @SuperNami, are you still facing this issue?

**Comment by gbraad** [comment]
Since July no feedback. I am closing...

**Comment by khoukhaa** [comment]
![heeeelp](https://user-images.githubusercontent.com/37330719/37911647-eec1b26c-3110-11e8-9b89-b0775eef40a0.PNG)
I faced the same prblem
