### ISSUE TITLE
Create uninstall add-on command

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1129]
I want to be able to use addon mechanism to remove an addon.

As I'm currently developing some addons, I find myself having to do manual removal of things through oc commands, and eventually outputing the command needed as part of the addon installation. That's useful but I will not have a way to access that information some time later.

e.g.
````
-- Applying addon 'cockpit':....
  You have installed cockpit
  To access cockpit go to http://cockpit.192.168.64.2.nip.io
  or
  Use minishift:
  minishift openshift service cockpit -n cockpit

  To delete:
  oc delete oauthclients/cockpit-oauth-client project/cockpit --as=system:admin
````

I want a way to uninstall an addon. Having in the addon folder two files:

````
myaddon.addon
myaddon.addon.uninstall
````

So that when I do "minishift addon remove" will execute that other script.
If I do "minishift addon uninstall" will also uninstall the addon, hence will be marked in the configuration as not installed.

**Comment by hferentschik** [comment]
+1 for the idea. Let's try to think that trough. I guess some uninstall file is a good idea and quite intuitive.

**Comment by praveenkumar** [comment]
Here is my thought on this issue.

- Right now we have `addon apply` which even doesn't update configuration so when we run uninstall script we only change it to disable if it enabled or we don't do anything so in next run it again come up?

- Does uninstall also need to have mandatory metadata field like (name, description) etc,?

**Comment by hferentschik** [comment]
> Right now we have addon apply which even doesn't update configuration so when we run uninstall script we only change it to disable if it enabled or we don't do anything so in next run it again come up?

Not quite sure what you mean. I have problems to "parse" this sentence. Can you please clarify?

> Does uninstall also need to have mandatory metadata field like (name, description) etc,?

I like what @jorgemoralespou suggested. So there would be a new command 'minishfift add-on uninstall foo'. This command would look at the directory of the foo addon for foo.addon.uninstall and if found execute it. If the file does not exist we report "No uninstall action defined for add-on foo". If it exists we execute the commands in there. The DSL would really be the same, so we would just re-use the same parser. We might want to relax the required meta data. For example 'Description' might not be needed. Whether we enforce a name is discussable. From a technical point of view it would not be necessary. What for example if they don't match? The name in the add-on 'foo' and in the un-install 'bar'. My gut feeling is that for the uninstall we don't require any meta-data and just ignore all lines with '#'.

When we create the AddOnManager, we not only look for directories with '*.addon'. If a directory contains the .addon file we parse it and map the add-on to the name specified in the add-on. We add another step here which once the add-on is found, also look for a foo.addon.uninstall and parses it (ignoring meta data) and add it to the AddOnManager. The latter gets extended with something like _UninstallAddOn_.

**Comment by gbraad** [comment]
> > Right now we have addon apply which even doesn't update configuration so when we run uninstall script we only change it to disable if it enabled or we don't do anything so in next run it again come up?

> Not quite sure what you mean. I have problems to "parse" this sentence. Can you please clarify?

I believe it can be summed up in one term: "Roll-back". Will roll-back support be needed for this, or does the uninstall only disable the add-on from being installed.

**Comment by praveenkumar** [comment]
> Not quite sure what you mean. I have problems to "parse" this sentence. Can you please clarify?

I was just getting clarification for `If I do "minishift addon uninstall" will also uninstall the addon, hence will be marked in the configuration as not installed` when we say marked in the configuration as not installed it mean we read the config and mark it `disabled` right?

**Comment by hferentschik** [comment]
@praveenkumar, ahh I get you, you are wondering whether a 

    $ minishift add-on uninstall <name> 

implies a disable of the add-on as well? Whether we run an implicit 

    $ minishift add-on disable <name>

Or even more, disable and literally remove the add-on from the MINISHIFT_HOME directory (since we don't have a command for that either). My initial gut feel around this would be to not implicitly disable. Just run the uninstall commands (maybe rollback is indeed a better name and we should use it instead of un-instsall).

I think we should also not remove the actual add-on from MINISHIFT_HOME and have a dedicated `minishift add-on remove <name>`.

**Comment by praveenkumar** [comment]
> Or even more, disable and literally remove the add-on from the MINISHIFT_HOME directory (since we don't have a command for that either). My initial gut feel around this would be to not implicitly disable. Just run the uninstall commands (maybe rollback is indeed a better name and we should use it instead of un-instsall).

I do agree, I also don't want to remove/disable addon but just rollback.

> I think we should also not remove the actual add-on from MINISHIFT_HOME and have a dedicated minishift add-on remove <name>.

+1 For this issue I will not touch remove part but only focus on this rollback stuff.

**Comment by jorgemoralespou** [comment]
I would consider these use-cases:

- "minishift addon uninstall" does remove the addons from the addons folder (opposite of install)
- "minishift addon remove" does remove it inmediately (opposite of apply)
- "minishift addon disable" does not install on next run (opposite of enable)

**Comment by hferentschik** [comment]
@jorgemoralespou, and in which cases do you run the uninstall add-on commands? In your case for _uninstall_ and _remove_, right? 

I think _remove_ is a bit ambigious, but I am at loss for a better command atm. 'un-apply' ;-)

**Comment by jorgemoralespou** [comment]
Does install have the effect of applying an addon to an already running instance? In that case, uninstall would remove it. But I don't think it does.

For what I know, immediate installation of the addon to the cluster only happens with _apply_ so, immediate removal of the addon should only happen with _remove_.

For what I know, _install_ just add the addon to the addons folder, so _uninstall_ should remove it from the folder.

For what I know, _enable_ just add the addon to the list of addons that will be installed on next bootstrap, so _disable_ should remove it from that list.

But I must be wrong.

As for the name, yes, it can be a little loose, so another name can be used, although un-apply sounds not so "natural".

**Comment by hferentschik** [comment]
> Does install have the effect of applying an addon to an already running instance? 

No. It just copies the add-on into the $MINISHIFT_HOME directory. Then it is available to be used via the _apply_ command against a running instance or it gets enabled via the _enable_ command and gets applied during the next VM/instance creation.

> In that case, uninstall would remove it. But I don't think it does.

So _uninstall_ is literally about removing it from $MINIHSIHFT_HOME and from config.json in case it is enabled (this is technically not necessary I believe. AFAIR if you remove an add-on, but leave it enabled in the config it gets ignored. The AddOnManager configures itself by what is available in $MINISHIFT_HOME/add-ons. To do things cleanly though it should potentially be removed from config.json)

Either way, I can live with that. The _uninstall_ command is about removing the add-on files.

> For what I know, immediate installation of the addon to the cluster only happens with apply so, immediate removal of the addon should only happen with remove.

Ok

> For what I know, install just add the addon to the addons folder, so uninstall should remove it from the folder.

Ok

> For what I know, enable just add the addon to the list of addons that will be installed on next bootstrap, so disable should remove it from that list.

Right, that's the current behaviour.

> As for the name, yes, it can be a little loose, so another name can be used, although un-apply sounds not so "natural".

I think I agree what we want to achieve in terms of functionality and behaviour. What is still a bit in the air is the name of the _remove_ command. It is not so easily discernible as opposite to the _apply_ command. _unapply_ does, but it is not a proper verb I guess. I can see it is used in some cases, but it sounds unnatural indeed. Any other candidates?

**Comment by hferentschik** [comment]
Merged via pull request #1305

**Comment by praveenkumar** [comment]
@jorgemoralespou Can you try that uninstall feature now, binary available => http://artifacts.ci.centos.org/minishift/minishift/pr/1305/

**Comment by budhrg** [comment]
@jorgemoralespou And, documentation can be found here http://artifacts.ci.centos.org/minishift/minishift/master/291/openshift-docs/latest/minishift/command-ref/minishift_addons_remove.html
