### ISSUE TITLE
Add-on command that will skip errors (not fail on errors)

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1130]
When developing addons, you might find yourself that you want to install something on a namespace that might or might not exist. Probably many oc commands that you execute you might want to fail or continue.

I want to have a way to express on the addon definition that I don't care about a specific failure, so I can continue processing the addon.

e.g.:

````
oc adm new-project example
# Now if I execute the creation, I don't want to fail
!oc adm new-project example
````

Possibly, you might want to capture the output of the error, depending of it is stdout or stderr both or none, so there could exist four variants of the command:

&oc: shows both, stdout and stderr
1&oc: only shows stdout
2&oc: only shows stderr
!oc: don't show any, but don't fail

This is really helpful for debugging purposes. But I could accept living without this if the output is logged to the minishift.log so it can be later seen, or depends on --loglevel

Of course, notation is suggested. To be discussed when implementing

**Comment by jorgemoralespou** [comment]
Example of where this can be really handy can be found in the [prometheus addon](https://github.com/jorgemoralespou/minishift-addons/tree/master/prometheus).

The addon can be installed in different projects as the project is specified as a parameter to the addon, in the form of --addon-env namespace=<my-namespace>

When you choose a namespace that exists, you don't need to create it, but when you use a non-existent namespace, you need to create it. It would be helpful to use "oc new-project" or "oc adm new-project" with the passed namespace, and in case it does exist not fail, and continue.

**Comment by hferentschik** [comment]
Interesting. What is Prometheus anyways? Never heard.

**Comment by jorgemoralespou** [comment]
@hferentschik are you kidding? Metrics, to be the default in openshift soon, replacing hawkular. Although that's not the point. This applies to multiple add-ons.

**Comment by hferentschik** [comment]
> Metrics, to be the default in openshift soon, replacing hawkular.

That's sounds good. Hawkular never really worked for me, even when it "properly" provisioned.

**Comment by jorgemoralespou** [comment]
@LalatenduMohanty This is preventing from creating addons. I have some addons in the pipeline that can't work as can't be run twice and safe removal is not an option.

e.g. Validate that kube-system namespace is there, if not create it, if there is, use it. I can't just delete that namespace on removal, so the namespace might or might not exist. I would hope this is done soon. It's been delayed for more than  months and prevents addons authoring.

**Comment by praveenkumar** [comment]
@jorgemoralespou What if we only provide a single notation `@` for the command which you want to ignore the failure and remaining dsl will be as it is? Instead of creating 3-4 different abbreviation for it.

```
oc adm new-project foo => This will fail the addon
@oc adm new-project foo => This will ignore the error and continue 
```

**Comment by praveenkumar** [comment]
I am changing the milestone for this issue `v1.15.0` since @jorgemoralespou requested this for some time now and this issue is here for months.

**Comment by jorgemoralespou** [comment]
@praveenkumar I'm fine. As described in the issue, request to handle output is nice to have, but would be fine if only logged internally and without that notation, but providing appropriate log levels.

With regards to whether **@** or **!**, I would favour the latter, as IMHO is more clear, but maybe just in my mind. I'll accept anything as long as feature is done.

**Comment by LalatenduMohanty** [comment]
Resolved through https://github.com/minishift/minishift/pull/2130
