### ISSUE TITLE
Add a minimum Openshift version for executing add-ons

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1134]
OpenShift 3.6 will introduce a big change on the APIs where now are using APIGroups, that means that the resource version definitions of many things, like templates created for 3.6+ will no longer work in previous releases. All those addons and templates that will be created with this API need to guarantee that the version of OpenShift is at a minimum.

Add an annotation to the addon with similar syntax:

````
# Required-OpenShift-Version 3.6+
````

Example of such an addon can be found [here](https://github.com/jorgemoralespou/minishift-addons/tree/master/prometheus)

**Comment by hferentschik** [comment]
Thanks for the heads up. So much for OpenShift staying backward compatible ;-)

**Comment by hferentschik** [comment]
Merged via pull request #1487
