### ISSUE TITLE
Provide notation for default value for addon-envs

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1135]
It would be cool, if one could define a default value for an addon-env so that you don't require to add it for those addons where a default value could be provided.

Example can be found in the [prometheus addon](https://github.com/minishift/minishift-addons/tree/master/add-ons/prometheus) where the template would install in the *kube-system* namespace, but in order to make that configurable so the user can select the namespace, a default will no longer apply. The user will always be required to install it.

Also it would be nice to provide the ability to have a notation in the description for the variables an addon can have, so that you can get details on the addon:

e.g:
````
minishift addons list --verbose
Name       : prometheus
Description: This template creates a Prometheus instance preconfigured to gather OpenShift and Kubernetes platform and node metrics and report them to admins. It is protected by an OAuth proxy that only allows access for users who have view access to the prometheus namespace. You may customize where the images (built from openshift/prometheus and openshift/oauth-proxy) are pulled from via template parameters.
Enabled    : disabled
Priority   : 0
Required-Envs: namespace
Default-Envs: namespace=kube-system
````

Additionally, bringing this out into an addon info command for that single addon would also be handy.

**Comment by budhrg** [comment]
Hi @jorgemoralespou ,

Is this the expected details of `.addon` file with default env values?

```
# Name: prometheus
# Description: some-description
# Url: some-url
# Required-Vars: namespace,configpath
# Default-Envs: namespace=kube-system
[...]
```
### Deploy prometheus as: 
```
minishift addons apply prometheus --addon-env configpath=path-to-some-config
```

**Comment by praveenkumar** [comment]
Right and if I want to overwrite then should able to use `--addon-env namespace=my_namespace`

**Comment by budhrg** [comment]
> Right and if I want to overwrite then should able to use --addon-env namespace=my_namespace

Ya correct. thanks

**Comment by jorgemoralespou** [comment]
Yes

**Comment by hferentschik** [comment]
I am not a big fan of adding another metadata header for this. I think it is more concise to say something like this within the add-on defintions '#{USER:developer}'.

Also in this solution you effectively define a default value for any use of the variable. What if the variable is used multiple times in the add-on and in one context it is ok with the default whereas in another you require the value. A default value needs imo be implemented per variable use.

**Comment by jorgemoralespou** [comment]
I like the notation idea, but in the header.
I don't think there will be different values for the same variable in the
same add-on.
Could you provide an example where this would be the case?

**Comment by budhrg** [comment]
@hferentschik , Need your comment as well.

And your opinion @LalatenduMohanty, @praveenkumar and @gbraad ?

**Comment by hferentschik** [comment]
@jorgemoralespou

> I like the notation idea, but in the header.

So how would that look like? 

    # Default-Envs: #{NAMESPACE:myapp}, #{USER:myuser}

As said, for me it would feel more natural to be able to define the default at the point of variable usage. Of course this would mean, one has to potentially repeat the default.

**Comment by hferentschik** [comment]
I am also not so sure about the name _Default-Envs_. We have _Required-Vars_ so I somehow expect something with _Var_, e.g. _Var_Defaults_

**Comment by budhrg** [comment]
> I am also not so sure about the name Default-Envs.

Yes, `Default-Envs` is completely taking context away from `Required-Vars`.

+1 for `Var-Defaults` or `Default-Vars`.

**Comment by budhrg** [comment]
@jorgemoralespou , looking for your feedback here.

**Comment by LalatenduMohanty** [comment]
> +1 for Var-Defaults

+1. I also do not like `Default-Envs`.

**Comment by budhrg** [comment]
@LalatenduMohanty , What about `Default-Vars` ?  I sounds more intuitive and align with `Required-Vars` IMO

**Comment by hferentschik** [comment]
> What about Default-Vars

Except you are not defining default variables, bur rather specifying default values for variables.

**Comment by budhrg** [comment]
@hferentschik @jorgemoralespou ,

If we are using this format in header
```
# Var-Defaults: #{NAMESPACE:myapp}, #{USER:myuser}
```

Since, `#{...}` this is the way doing interpolation, it doesn't make sense in metadata header. Also, user need to typoe those extra `#` and curly braces.

How about?

```
# Var-Defaults: NAMESPACE:myapp, USER:myuser
```

**Comment by hferentschik** [comment]
I agree that the syntax ' #{...}' does not work in the header. I would choose it for the case where the default is specified at the point of use of the variable. 

> # Var-Defaults: NAMESPACE:myapp, USER:myuser

Seems reasonable to me

**Comment by jorgemoralespou** [comment]
Sorry for taking long to answer. I meant to mix all options in one header, as that would simplify the add-on definition.

Vars: USER, NAMESPACE:openshift

Notation not proposed, but functionality.

This would imply that:
- There's 2 cars used by the add-on and can be user provided
- First variable used need to provide a value
- Second variable, there's a default if it don't provide a value

And then, on the var use itself, you could additionally expand a default as well, in case there's one occurrence where the default would differ from the global default, as @hferentschik describes.

I would not add different sections in the header as it was implied on my first response.

I hope this is more clear.

And a comment about notation. If you use colon as split, you can not use colon in the value.

**Comment by budhrg** [comment]
@jorgemoralespou 

> Vars: USER, NAMESPACE:openshift

You mean `Required-Vars` right?

> And a comment about notation. If you use colon as split, you can not use colon in the value.

> And then, on the var use itself, you could additionally expand a default as well, in case there's one occurrence where the default would differ from the global default, as @hferentschik describes.

Just to be clarifying myself here, so, in the command itself, if there is syntax like `#{NAMESPACE:kube-system}` it should override any other value right?

So, priority order is:
- Default specified in `Required-Vars`
- Default specified in command itself inside `.addon` file. Override above value.
- Value specified via `minishift config set addon-env` or `--addon-env` option during `minishift addon apply`.

@hferentschik and I agreed with `=` and I personally feel it will aligned with `--addon-env` format of `ENV=VALUE`.

**Comment by jorgemoralespou** [comment]
+1

**Comment by hferentschik** [comment]
I am confused, _Required-Vars_ is about specifying a list of variable names for which a value must be provided, right? The idea is that you can enforce that a value is given for a variable when the add-on is applied. There might be more variables, but they are not required and the add-on does not enforce that there is a value set for them. So if I understand correctly the idea is to do something like:

    # Required-Vars: USER, NAMESPACE=openshift

This allows to specify defaults for required variables. This is probably where it is needed most. This also avoids adding a new metadata field. I like that. But how do I specify defaults for variables which are not required? There we use the #{NAMESPACE:kube-system} syntax as part of the add-on command. So for non required variables one would need to set their defaults on each occurrence  of the variable?

**Comment by jorgemoralespou** [comment]
This is where I think I would mix the headers into a Vars:

I like that there's one single header reflecting the variable, whether is
required and where there's a default, for documentation and readability
purposes it helps.

One can just look at that header and know what option he has.

How would you make this?

An idea would be to add an additional flag to the required vars, e.g (not
this is not proposed notation).

Vars: NAMESPACE, +USER, +SERVICE ACCOUNT: default, PROJECT:example

There you have:
- a var without default and not required
- a var with no default and required
- a bar with default and required
- a bar with default and not required

**Comment by hferentschik** [comment]
I hear where you are coming from. I kind of like the idea. A couple of questions:

* What if one uses a variable in the commands which is not listed in the _Vars_ header? That would in this model be an error, right?
* How do we deal with backward compatibility? Switch completely to _Vars_ and make existing add-on using _Required_Var_ obsolete, forcing users to update the add-on or do we support both?

The disadvantage of _Vars_ is that it needs more meta character and hence there is a bigger chance of parsing problems and ambiguities. There is also the point that _Vars_ is harder to understand, since one needs to understand the meta characters. Having explicit headers is more explicit.

**Comment by budhrg** [comment]
@jorgemoralespou , any follow comments on @hferentschik questions?

**Comment by jorgemoralespou** [comment]
> What if one uses a variable in the commands which is not listed in the Vars header? That would in this model be an error, right?

Yes, I would make the card in the header mandatory. This should be the contract, else it will be too confusing to know how things work unless reading the implementation.


> How do we deal with backward compatibility? Switch completely to Vars and make existing add-on using Required_Var obsolete, forcing users to update the add-on or do we support both?

Yes. Not so many addons. In the release notes I would maybe give hints on how to migrate an add-on.
Else, you can introduce addons versioning, but this would be too complex.
Or you can support current functionality for 1-2 releases, which would also be too complex.

**Comment by budhrg** [comment]
> Yes, I would make the card in the header mandatory. This should be the contract, else it will be too confusing to know how things work unless reading the implementation.

Make sense. +1

> In the release notes I would maybe give hints on how to migrate an add-on.

This will work IMO.

Final approved format is:
```
# Vars: USER, NAMESPACE=openshift
``` 

Implies:
- `USER` and `NAMESPACE` are required vars
- There should be check for value of `USER` from `config set addon-env` or `--adon-env`. Error if not found.
- If value of `NAMESPACE` is not set via `config set addon-env` or `--addon-env` then use `openshift`.

@jorgemoralespou @hferentschik , Please add your comment/suggestion if I missed anything.

**Comment by LalatenduMohanty** [comment]
> How do we deal with backward compatibility? Switch completely to Vars and make existing add-on using Required_Var obsolete, forcing users to update the add-on or do we support both?

Even if the new format of `Vars` sounds good to me , the loss of backward compatibility is a serious matter. Personally I would try to avoid it till we have a minishift version 2.0.0 release.

**Comment by LalatenduMohanty** [comment]
We should go with the backward compatible solution now and push the new `var` format for Minishift 2.0.0?

**Comment by budhrg** [comment]
@LalatenduMohanty , @jorgemoralespou @hferentschik , then I would stick to `Required-Vars` and `Var-Defaults` since it is explicit and making things clear. 

Agree that major changes should be done in 2.0.0 release. 

See example https://github.com/minishift/minishift/pull/1546#issue-264663235
```
# ~/.minishift/addons/demo-addon/demo-addon.addon 
# Name: demo-addon
# Description: Created for demo purpose
# Required-Vars: USER, NAMESPACE
# Var-Defaults: USER, NAMESPACE=myproject

echo User is #{USER} and project is #{NAMESPACE}
```

**Comment by hferentschik** [comment]
I am not convinced whether we should not go with the 'Var-Defaults' approach. It means there is potential duplication when I have to list a variable in the Required-Vars as well as in the _Var-Defaults_, but it is still reasonable imo. Amongst other things it gets around introducing some sort of metalanguage to distinguish between variable, required variable and a default value for either of them (eg 'Vars: NAMESPACE, +USER, +SERVICE ACCOUNT=default, PROJECT=example').

In case of switching to _Vars_, I would have the following conditions:
* To allow for the same sort of expressiveness we need a syntax to express both, whether a variable is required or not and whether or not it has a default value
* All variables used in the add-ons needs to be specified in the _Var_ metadata field (needs some changes in the impl of the add-on manager)
* _Required-Vars_ gets deprecated and an appropriate warning is displayed to help users to migrate/adjust add-on

**Comment by hferentschik** [comment]
> We should go with the backward compatible solution now and push the new var format for Minishift 2.0.0.

As said, I am also drawn towards _Var-Defaults_ atm, but mind you that in this case, I don't think we should switch to _Vars_ then. There would be no driving reason and the longer one waits the more add-ons would need to be updated. If we think the _Vars_ notation is so much superior, then we should do it now.

**Comment by jorgemoralespou** [comment]
+1 to the sooner the better, or never.
Once CDK ships with addons, and we start promoting them more it will be
more complex, so if it makes sense, do it now.
Once thing that I like about using one single header is simplicity to read
and for addons authoring.
We already have 4 headers if we keep this simpler notation.

In the future, for authoring, a command to scaffold an add-on might be
convenient.

**Comment by gbraad** [comment]
I think to go for the backward-compatible solution, by not breaking the current parsing, is the better approach. This is not a big feature where we can risk to introduce a breaking change.

**Comment by LalatenduMohanty** [comment]
> As said, I am also drawn towards Var-Defaults atm, but mind you that in this case, I don't think we should switch to Vars then. There would be no driving reason and the longer one waits the more add-ons would need to be updated. If we think the Vars notation is so much superior, then we should do it now

Agreed.  Lets go with Var-Defaults

**Comment by LalatenduMohanty** [comment]
In future id we want to improve things (like reduce number of headers) then we should first introduce version in to add-ons and then fix the parser to work with older versions.

**Comment by hferentschik** [comment]
Merge by pull request #1546
