### ISSUE TITLE
Insecure registry not working

### ISSUE THREAD

**Issue by mibaboo** [minishift/minishift#1138]
Hi 

I cannot access my local docker registry. 

I have started minishift with the --insecure-registry 172.30.0.0/16 flag. However when I run 
`oc describe service docker-registry`
I get the following error

> Error from server (NotFound): services "docker-registry" not found

**Comment by LalatenduMohanty** [comment]
@mibaboo Minishift bydefault starts the local registry and you can get the details using command `minishift openshift registry`. For details please refer https://docs.openshift.org/latest/minishift/openshift/openshift-docker-registry.html

**Comment by LalatenduMohanty** [comment]
@mibaboo Let us know if this works for you?

**Comment by ibaboo** [comment]
@LalatenduMohanty yes this has worked for me. I was under the impression I needed to start a local insecure-registry. Thanks for the help

**Comment by LalatenduMohanty** [comment]
@ibaboo Thanks for the confirmation.
