### ISSUE TITLE
Allow cache to be cleared without having defined an instance

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1144]
It seems the command: `minishift delete --clear-cache` only works when an instance has been defined.

     Running this command requires an existing 'minishift' VM, but no VM is defined.

This does not seem like the expected behaviour.

**Comment by LalatenduMohanty** [comment]
@gbraad Just to be clear, you are saying `minishift delete` fine to check if VM is defined before deleting it , but in case of `minishift delete --clear-cache` it should bypass the check and just delete the cache if VM is not defined?

**Comment by gbraad** [comment]
Well, this is a question we need an answer to... else we need to advice to do `rm -rf ~/.minishift/cache` which defeats the purpose of this command.

But also, should clearing the cache really remove the VM? It seems to be a command that does two things: deleting the instance, and removing the cache. Sounds like a side-effect.

**Comment by LalatenduMohanty** [comment]
I see , you mean --clear-cache operation should be done independently, right?  Example: if user has deleted the instance but then want to delete the cache how does he do it.  In practice if we just talk about ISO and OC user should not need to clean the cache unless it is an uninstall. For uninstall we suggest deleting the `.minishift` which is ok I think. With respect to images , I think image command should provide some command for image management.

**Comment by gbraad** [comment]
currently, we can have corrupted downloads in the cache. this is the reason why we have a `--clear-cache` command. if downloads are checked, this might become irrelevant.

although, at the moment using this command is not error-free, as it suffers from a side-effect (existence of a VM is needed).

**Comment by budhrg** [comment]
@anjannath Can you have a look?

**Comment by anjannath** [comment]
@budhrg Sure, looking into it

**Comment by anjannath** [comment]
We still need to fix this.. right?

**Comment by gbraad** [comment]
Fixed with 675539a
