### ISSUE TITLE
prune image without certificate

### ISSUE THREAD

**Issue by Emmanuel35** [minishift/minishift#1145]
When I use prune functionnality, I prune:
- builds
- deployments
without certificate.
- images 
with certificate !

Why I need certificate for images and not for the others ?

**Comment by Emmanuel35** [comment]
My commands:
`oc login -u system:admin

oc adm prune deployments --orphans --keep-complete=2 --keep-failed=1 --keep-younger-than=60m

oc adm prune builds --orphans --keep-complete=2 --keep-failed=1 --keep-younger-than=60m

oc adm prune images --keep-tag-revisions=1 --keep-younger-than=60m`

**Comment by praveenkumar** [comment]
@Emmanuel35 I don't think this is minishift specific issue but let's hear from @jorgemoralespou .

**Comment by jorgemoralespou** [comment]
@Emmanuel35 I would be interested in knowing why you're running administrative commands. As you should know minishift is meant as a developer sandbox, and many of the typical administration you would do on a real OpenShift install will not work. 

Next, there is a way to use administrative commands with the regular user, by using a "--as=system:admin" as the developer user has sudoer role.

And then, lastly, this is a question to make in "https://github.com/openshift/origin" as it has nothing to do really with minishift.

I can not reproduce your output. For me all the 3 commands work fine.

**Comment by gbraad** [comment]
Closing this issue; not related to Minishift. If issues remain, please file an issue at openshift/origin.

**Comment by Emmanuel35** [comment]
Hi,

It is easy to reproduce with Windows 10 and minishift 1.3.0...

'c:\RedHat\MiniShift>oc login -u system:admin
Logged into "https://192.168.99.100:8443" as "system:admin" using existing
credentials.

You have access to the following projects and can switch between them with
'oc project <projectname>':

    cicd
    default
    elastic
  * jboss-apps
    kube-dashboard
    kube-system
    myproject
    openshift
    openshift-infra

Using project "jboss-apps".

c:\RedHat\MiniShift>oc adm prune deployments --orphans --keep-complete=2
--keep-failed=1 --keep-younger-than=60m --confirm

c:\RedHat\MiniShift>oc adm prune builds --orphans --keep-complete=2
--keep-failed=1 --keep-younger-than=60m --confirm
NAMESPACE    NAME
jboss-apps   jboss-wildfly-3
jboss-apps   jboss-wildfly-2

c:\RedHat\MiniShift>oc adm prune images --keep-tag-revisions=1
--keep-younger-than=60m --confirm
error: you must use a client config with a token'

Emmanuel

2017-07-24 17:47 GMT+02:00 Gerard Braad <notifications@github.com>:

**Comment by LalatenduMohanty** [comment]
@Emmanuel35 I think this is a Origin issue unless you have reasons to say this is a Minishift issue. I would suggest you to open an issue at https://github.com/openshift/origin/issues. WDYT?

**Comment by Emmanuel35** [comment]
Ok minishift console work fine. It's an oc bug :-) .

Emmanuel

2017-07-25 10:34 GMT+02:00 Lalatendu Mohanty <notifications@github.com>:

**Comment by dagniel** [comment]
Hello all!

Not wanting to open this again, but I believe even in a dev environment - catching on what jorgemoralespou pointed out - it's useful to have some means to clean.
In my particular situation, the testing and configurations done for raising 2 (skinny) apps with their layers ended up with 30GB of stuff for my minishift disk.

So as an option for minishift delete and then restart from scratch, I've managed to prune images and blobs as by following the guidelines on the OShift docs (https://docs.openshift.org/latest/admin_guide/pruning_resources.html#hard-pruning-registry) with creating an external route to the docker-registry pod that's running inside the default namespace. 
The command would look like this:
`oc --token=$(oc sa get-token registry) adm prune images --keep-tag-revisions=1 --registry-url="http://reg-default.XX.XX.XX.XX.nip.io" --force-insecure=true --confirm`

The url depends on what you've used as a name when creating the route and your IP address and it routes to the internal ip:5000 so you can access the registry. The `--token` option is required, as specified in the docs and it should get a key for a serviceaccount user that has the system:image-pruner role. The procedure for this is described in the docs' page.

**Comment by dak1n1** [comment]
`oc sa get-token` <serviceaccountname> can get you that token

**Comment by gbraad** [comment]
No new functionality will be added to Minishift as we are focussed on a new
effort around OpenShift 4.0.

To prune you can delete the VM and included cache, or manually by opening
the .minishift/cache folder in your home using the file explorer. Be sure
to check iso, of and images.
