### ISSUE TITLE
Include registry-route addon in defaults

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1147]
When you install default addons, this one is not installed, so it needs to be installed through directory install, which requires you to clone the minishift repo.

Test if it works fine and add it by default.

**Comment by LalatenduMohanty** [comment]
@jorgemoralespou AFAIR it was not working as expected because we found some issues in `cluster up`  while including the add-on and @cesar fixed them in 3.6.

**Comment by jorgemoralespou** [comment]
That can explain it. I'm using 3.6
