### ISSUE TITLE
Describe the issue of filling up the live root filesystem

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1152]
Due to the way we run the Minishift instance, it can happen that the `/` (root) feilsystem on the VM gets exhausted. This has been resolved for OpenShift is part of #355, but since people still install software #1076, this issue can still lead to problems.

On the ISO side, we have now implemented something that will show a banner when software is installed using `yum`: https://github.com/minishift/minishift-centos-iso/issues/116
However, as part of the message we show, we want to refer to the documentation that addresses this problem and explains why this is currently unsupported (without having to point to an issue).

Since we do not have a wiki, this has to be done as part of the Minishhift documentation?

**Comment by hferentschik** [comment]
Troubleshooting guide?

**Comment by gbraad** [comment]
I had the same idea of including it in the troubleshooting guide... as long as the can directly link to an anchor within that document as part of the URL in the banner:

```
Installing packages using yum is not supported. For more information, please check: http://docs.openshift.org/latest/minishift/troubleshooting#livecd-root
Continue [y/n]
```

**Comment by gbraad** [comment]
The documentation/troubleshoooting entry will need to contain:

  * why this is unsupported
    * it exhausts the root filesystem of the LiveCD and can lock up the system
    * information provided by tools like `df` are unreliable and misleading about available space
  * what are the alternatives
    * use the persistent disk instead (/mnt/sda1)  
      task: maybe at a relocation of /opt -> /mnt/sda1/opt ?
    * use containers to perform development tasks

**Comment by LalatenduMohanty** [comment]
As I mentioned in the other issue i.e. https://github.com/minishift/minishift-centos-iso/issues/116#issuecomment-316975519 

We should add little more context e.g. `Installing additional packages is not supported because it will exhaust the root file system (/) and will lock the virtual machine. For more information, see:` 

As this communicates the consequences of the action and hopefully create the curiosity of the user to read more about it.

**Comment by LalatenduMohanty** [comment]
@gbraad I am fine with adding the content in troubleshooting guide.

**Comment by LalatenduMohanty** [comment]
Fixed by https://github.com/minishift/minishift/commit/1b1a21a8b069bde499a1d4e48ce7d8d283302794
