### ISSUE TITLE
Provide a storage location for binaries to survive restarts of the VM

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1156]
Relocate/symlink from `/opt` to `/mnt/sda1/opt`, to allow an alternative install location to prevent issues like #1076.

  * https://github.com/minishift/minishift-b2d-iso/issues/46
  * https://github.com/minishift/minishift-centos-iso/issues/125

**Comment by gbraad** [comment]
@hferentschik @LalatenduMohanty @praveenkumar WDYT? This could be described in #1152 if needed, and is a way to mitigate a problem as described in https://github.com/minishift/minishift/issues/355#issuecomment-310972408.

**Comment by budhrg** [comment]
@hferentschik @LalatenduMohanty @praveenkumar Any opinion here?

**Comment by gbraad** [comment]
If this is about the VM (LiveCD overlay), then this is handled by the
symlinking of /opt => /mnt/sda1/opt
