### ISSUE TITLE
Docker container fails to start during minishift start - VirtualBox, no VPN, Ubuntu 16.04

### ISSUE THREAD

**Issue by jgreene-cwt** [minishift/minishift#1160]
Hello -
First, see my previous recent thread [here](https://github.com/minishift/minishift/issues/1127).

First of all, I acknowledge there is likely a network stack problem when working over vpn that could be causing our problem.  However, today I got my personal laptop fired up - it is running Ubuntu 16.04, with a good wifi connection.  I got the latest nodejs and npm and @angular/cli installed, then grabbed minishift and openshift cli, making sure they were all good.  I ran the following minishift command to try to start openshift in a centOS VM, same as in my previous post (which was done on my Windows work box):

`minishift start --memory 4096 --cpus 2 --vm-driver virtualbox --show-libmachine-logs --iso-url centos`

The OpenShift cluster actually started as before (I can see it if i fire up the VirtualBox console), but I got pretty much the same Docker client issue as before (see my previous thread linked above):

```
Detecting the provisioner...
Provisioning with minishift...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
E0720 13:13:42.811365   14787 start.go:278] Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.
. Retrying.
Waiting for SSH to be available...
Detecting the provisioner...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Downloading OpenShift binary oc version v1.5.1
 19.96 MiB / 19.96 MiB [============================================] 100.00% 0s
-- Checking OpenShift client ... OK
-- Checking Docker client ... FAIL
   Error: cannot communicate with Docker
   Solution:

     Ensure that Docker is installed and accessible in your environment.
     Use your package manager or follow instructions at:

        https://docs.docker.com/linux/

   Caused By:
     Error: Get https://192.168.99.100:2376/_ping: dial tcp 192.168.99.100:2376: i/o timeout
OpenShift provisioning failed. origin container failed to start.
```
I totally did not expect this, since I had pretty much convinced myself with the help of the replies that this is a VPN issue.  

So now, since I'm not on VPN, and not on Windows, what could this be?  How can this be fixed or worked around on Ubuntu?  Any help would be greatly appreciated.

**Comment by gbraad** [comment]
When not able to communicate with Docker, this usually is the result of a network connectivity issue. Of which, using a VPN is the most likely cause. However, there are other possible issues when it concerns a VM... if which the virtual networking stack might be one. It is an issue we see often...

When you start the VM, and it fails like this... try to ping the node with the IP you see: `192.168.99.100`. It that fails, it indicates an issue with routes. For VirtualBox this can be that the VM is attached to a wrong network... please check this from the VirtualBox interface...

**Comment by jgreene-cwt** [comment]
Thanks for your response again.

Summary of my current setup:
- Ubuntu 16.04
- No VPN, just a satisfactory wifi connection
- ***Note:**  I am using the same minishift start command as in my previous thread, but this current laptop running Ubuntu is not very beefy.  I will not have multiple CPUs available, and the memory specification is too much because this is an older laptop.  Although the VB ui recognizes these settings as invalid, I did not change them.  Hopefully, this is irrelevant for the Docker communication issue.

Per your guidance:
1.  VirtualBox version:  5.1.24

2.  I pinged 192.168.99.100 - results were:
`From 12.81.246.1 icmp_seq=13 Destination Net Unreachable`

3.  From VirtualBox interface for routing and network settings:
Settings --> Network
Adapter 1: Attached to **NAT**
Adapter 2: Attached to **Host-only Adapter**, Name=**vboxnet0**

I did not see anything explicity for "routes", but hopefully this is what you needed.  Let me know if I can provide you with any more info.  And thank you again.

**Comment by quagliero** [comment]
@jgreene-cwt I ran into this problem yesterday (also on Ubuntu 16.04, VB 5.1.24, MS 1.3.0), and after much digging it turned out in my case that for some reason the network adapter for virtualbox just wasn't running and there was no entry for it in the routing table.

Check your output of `ifconfig vboxnet0`, if it's doesn't include `UP` and `RUNNING` then try and bring it up manually, `ifconfig vboxnet0 up` (may require sudo).

**Comment by gbraad** [comment]
> network adapter for virtualbox 

with this you mean not the wireless (or wired) connection, but the virtual network adapter (`vboxnet0`), This would also have impeded/hindered the other virtual machines from communicating. Correct?

**Comment by quagliero** [comment]
@gbraad Yes, correct.

**Comment by jgreene-cwt** [comment]
@quagliero Thanks for your response.   I will try this when I get home tonight and post the results.

**Comment by gbraad** [comment]
Any results?

**Comment by jgreene-cwt** [comment]
1.  Prior to attempting to start minishift (so before starting the centos VM):

ifconfig vboxnet0
_vboxnet0: error fetching interface information: Device not found_

2.  After attempting to start minishift again (with command shown in first post), and failing as expected:

ifconfig vboxnet0
_vboxnet0  Link encap:Ethernet  HWaddr 0a:00:27:00:00:00 
          inet addr:192.168.99.1  Bcast:0.0.0.0  Mask:255.255.255.0
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:12 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)_

3.  Checking the routing table:

netstat -rn
_Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG        0 0          0 wlan0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 wlan0
192.168.0.0     0.0.0.0         255.255.255.0   U         0 0          0 wlan0
192.168.122.0   0.0.0.0         255.255.255.0   U         0 0          0 virbr0_

192.168.100.99 does not appear in the routing table, so

4.  Try to bring up vboxnet0 and recheck routing table:

ifconfig vboxnet0 up
netstat -rn
_Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG        0 0          0 wlan0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 wlan0
192.168.0.0     0.0.0.0         255.255.255.0   U         0 0          0 wlan0
**192.168.99.0    0.0.0.0         255.255.255.0   U         0 0          0 vboxnet0**_

5.  Quick check:

ping 192.168.99.100
_PING 192.168.99.100 (192.168.99.100) 56(84) bytes of data.
64 bytes from 192.168.99.100: icmp_seq=1 ttl=64 time=0.910 ms
64 bytes from 192.168.99.100: icmp_seq=2 ttl=64 time=0.372 ms
64 bytes from 192.168.99.100: icmp_seq=3 ttl=64 time=0.450 ms
64 bytes from 192.168.99.100: icmp_seq=4 ttl=64 time=0.346 ms_


So it seems like these results indicate that vboxnet0 is up and running, but I would think I'd need to restart minishift.  So I did a 'minishift stop'.  I then checked 'netstat -rn' again, and vboxnet0 was still listed.  I then restarted minishift with the same command, and **this time the start process finished successfully.**

6.  I tried to log in as admin with the 'oc login...' command provided at the end of the start, and received the following result:

oc login -u system:admin
_error: dial tcp 192.168.99.100:8443: getsockopt: no route to host_

and in a browser, I'm of course unable to connect to the `https://192.168.100.99:8443` url provided

So this vnetbox0 solution seems to have fixed my minishift start problem, but looks like there's another hurdle here.  Any ideas?  THANK YOU.

**Comment by quagliero** [comment]
@jgreene-cwt it might be worth doing `minishift delete`, rather than `stop`, and then running the `start` command again afresh now that the virtualbox network issue seems to be fixed.

**Comment by jgreene-cwt** [comment]
Ok, another update.  I began to think about the resources specified in the `minishift start...` command argument list (since my ubuntu box is not bursting at the seams with RAM).  So after making sure minishift was stopped, I did a `minishift delete`, used the `netstat -rn` command to double-check that the vboxnet0 network adapter was still up, and executed the following (different) `minishift start...` command:

`minishift start --vm-driver virtualbox --show-libmachine-logs --iso-url centos`

This time, the startup went smoothly, and I was able to login as administrator and access the server at `https://192.168.100.99:8443`.  The openshift origin console loaded quickly, and all looks like I expected so far.  Here's the last part of the console at `minishift start...`:

```
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Checking container networking ... OK
-- Server Information ...
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.99.100:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
```


@quagliero, @gbraad thank you for your help.  I hope this thread helps more of us.  I'll keep this issue open in case either of you or anyone else has another comment.  Thanks again.

**Comment by gbraad** [comment]
Closing issue
