### ISSUE TITLE
"developer document" on page "contribution Guidelines" show 404

### ISSUE THREAD

**Issue by liangxia** [minishift/minishift#1161]
1. Access https://github.com/minishift/minishift/blob/master/CONTRIBUTING.adoc
2. Click "developer document", show 404

**Comment by LalatenduMohanty** [comment]
The page got moved to https://docs.openshift.org/latest/minishift/contributing/developing.html from https://docs.openshift.org/latest/minishift/developing/developing.html

**Comment by thatdocslady** [comment]
Whoops, looks like the link needs to be changed. I'll pick this up if nobody objects.

**Comment by hferentschik** [comment]
Merged via pull request #1163
