### ISSUE TITLE
Duplicate IDs in docs hamper downstreaming

### ISSUE THREAD

**Issue by rkratky** [minishift/minishift#1164]
The `homebrew-install` and `overview` IDs are duplicated in the AsciiDoc docs sources, which prevents seamless downstreaming of the docs -- downstream docs cannot be built with dupl. IDs, thus necessitating additional modifications.

I propose to submit a PR that would make all the IDs unique.

**Comment by thatdocslady** [comment]
@rkratky do you want to submit this PR or are you proposing that someone else does it? It's unclear from the phrasing of your proposal.

**Comment by rkratky** [comment]
@thatdocslady, I'll do it, I just wanted to ask before I do the work. The guidelines for contributing to this repo suggest an issue is to be created first, which the repo owners will triage and respond to. Had that not been the case, I would've just submitted the PR directly.

**Comment by thatdocslady** [comment]
@rkratky the main reason we request poeple to open issues is to prevent drive-by PRs that might be risky. In your case I'm less concernd :)

Anyway, please do submit the PR if you can hunt all the duplicate IDs, I did try to make this up-to-spec when I cleaned up the doc set but I guess I must've missed a few.

Thanks for your help!

**Comment by gbraad** [comment]
It is always a good practice to have an issue, as the PR can refer to this. However, in future, you can use a very short summary which could even be the same as the commit message.

**Comment by gbraad** [comment]
Merged with #1166. Thanks...
