### ISSUE TITLE
Using ovs network plugin

### ISSUE THREAD

**Issue by iwarapter** [minishift/minishift#1167]
Is it possible to use the ovs network plugins with minishift? I'd like to use ovs-multitenant and ovs-networkpolicy, i have patched the config into the openshift config:

`minishift openshift config set --patch '{"networkConfig": {"networkPluginName": "redhat/openshift-ovs-multitenant"}}'`

I'm using the centos base image and have installed openvswitch, but not sure how best to configure it to get this all working :(

**Comment by gbraad** [comment]
See: https://bugzilla.redhat.com/show_bug.cgi?id=1444144

/cc: @cewong, @jorgemoralespou

**Comment by jorgemoralespou** [comment]
Cc/ @csrwng

**Comment by iwarapter** [comment]
Hi guys, thanks for your answer, i ended up using the vagrant ansible containerized openshift deployment in the end for this, but following from the bug report you linked do you know if anyone is actively working on it? I'd be happy to contribute to help get the feature in minishift if possible.

**Comment by csrwng** [comment]
On the origin side side, we want to move to using openshift-ansible playbooks for cluster up, that way we can leverage the existing playbook codebase. I don't see us putting the effort to add ovs before that happens.

**Comment by jorgemoralespou** [comment]
In minishift we could easily create an addon to do this.

@csrwng oc cluster up + ansible? Where did we leave the "oc cluster up is the fastest way to soon up a cluster, not to do an installation?"

Maybe it's time to fork 😂😂😂

**Comment by csrwng** [comment]
@jorgemoralespou it may not be as bad as you think ... an openshift master should be running fairly quickly, but there's no reason to duplicate the provisioning code inside the cluster up command and in the openshift-ansible repo.

**Comment by budhrg** [comment]
Still under discussion.

**Comment by LalatenduMohanty** [comment]
Closed this issue as we do not have any plan to address this.

**Comment by ramanrupal** [comment]
I am unable to use ovs-multi-tenant plugin for minishift. Is there any way to join two projects in minishift..
I am trying the below command to join two projects i minishift.
"oc adm pod-network join-projects --to=app1 app2"
output: managing pod network is only supported for openshift multitenant network plugin
