### ISSUE TITLE
Unsupported cluster up flags are not returned as error

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1169]
See: https://github.com/minishift/minishift/blob/5c02dee1f8814d07dace81a11e594bdfbc79a1db/pkg/minishift/clusterup/clusterup.go#L69

The flag is checked for support, but it is not returned as error.

**Comment by gbraad** [comment]
I would like to see the following:

```
$ minishift start --openshift-version=v1.5.1 --service-catalog
Starting local OpenShift cluster using 'kvm' hypervisor...
-- Checking `oc` support for flags ... 
   version ... OK
   routing-suffix ... OK
   service-catalog ... FAIL
Error during 'cluster up' execution: Flag service-catalog is not supported for oc version v1.5.1. Use 'openshift-version' flag to select a different version of OpenShift.
```

as this is in line with #485

**Comment by jorgemoralespou** [comment]
@gbraad agreed that if you can fall fast in the pre flight checks that would be the best.

**Comment by gbraad** [comment]
Currently, these flags are tested after the VM is created. This is too late
in the process to fail early... And also feels like bad experience; you
first wait a few moments (minutes) to spin up a VM... after which you get a
message that 'oc' doesn't support a flag? Ouch.

We will not fix it in this issue, but we certainly have to look into this.

On Tuesday, July 25, 2017, Jorge Morales Pou <notifications@github.com>
wrote:
> @gbraad agreed that if you can fall fast in the pre flight checks that
would be the best.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by praveenkumar** [comment]
> @praveenkumar is this deliberate?

@gbraad No looks like we forgot to put `return` keyword before error message :( , Good catch!

>Currently, these flags are tested after the VM is created. This is too late in the process to fail early... And also feels like bad experience; you first wait a few moments (minutes) to spin up a VM... after which you get a message that 'oc' doesn't support a flag? Ouch.

We discussed it ( me and @hferentschik ) before I implemented it and we have it that way because we can only check supported args once we have `oc` binary which get downloaded after VM is created. Now we can have it downloaded along with iso but then if vm creation fail then it's just bad to pull down around 30 MB of data :(

**Comment by gbraad** [comment]
I really want to see the check happening earlier... "fail early, fail
fast". It is not just the download, but also the VM startup time. On
Windows, the creation and conversion of the disk image can take about 1min
or more.
