### ISSUE TITLE
Perform support checks for `oc cluster up` as part of preflight checks

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1175]
At the moment we check for support of `oc cluster up` flags in clusterup.go after the VM has been created and started. This means that the user has to wait for the download and startup of the VM before being told that the cluster startup might fail, because of an unsupported flag.

It is suggested to perform these checks as early as possible... preferably before the creation of the VM.

**Comment by gbraad** [comment]
See #1169 for some background

**Comment by praveenkumar** [comment]
@gbraad Can we close this or still we need to work around it?

**Comment by gbraad** [comment]
They are currently started from the cluster.go, so nothing has been done to this end.

I believe we should also check version and such as part of the pre-flight. This would allow us to move to using 'minikube' as a library (if they implement pre- and post-hooks). Note: but when to download the binary remains as a question.

**Comment by gbraad** [comment]
#1918
