### ISSUE TITLE
Handle slice variables explicitly in the start command

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1176]
This is follow up for #1153 we found out there is problem is in the viper and the way it handle config option and command line option is not consistent and that's kind of back us using Var at all and instead we should create our own Flag with custom implementation of slice so it work consistently with config and command line options. @hferentschik already did all hard work to implement that custom string slice we need to consume and test our all start slice option and then use it.

- https://github.com/minishift/minishift/blob/master/cmd/minishift/cmd/util/shared_flags.go#L56

**Comment by hferentschik** [comment]
Merged via pull request #1220
