### ISSUE TITLE
Spike: investigate if service-catalog can be deployed as add-on

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1179]
Documentation:
  * https://docs.openshift.org/latest/architecture/service_catalog/index.html

**Comment by gbraad** [comment]
@praveenkumar let's collect information here.

**Comment by gbraad** [comment]
```
$ oc create -f https://raw.githubusercontent.com/openshift/origin/master/examples/service-catalog/service-catalog.yaml
```

**Comment by gbraad** [comment]
```
--> Deploying template "myproject/service-catalog" for "https://raw.githubusercontent.com/openshift/origin/master/examples/service-catalog/service-catalog.yaml" to project myproject

     * With parameters:
        * CORS Allowed Origin=10.192.213.116
        * Service catalog image name=openshift/origin-service-catalog:latest
        * Service Catalog Service IP=172.30.1.2
        * Name of the kube-system namespace=kube-system

--> Creating resources ...
    clusterrole "servicecatalog-serviceclass-viewer" created
    clusterrolebinding "servicecatalog-serviceclass-viewer-binding" created
    serviceaccount "service-catalog-controller" created
    serviceaccount "service-catalog-apiserver" created
    clusterrole "namespace-viewer" created
    clusterrolebinding "service-catalog-namespace-viewer-binding" created
    clusterrolebinding "service-catalog-controller-namespace-viewer-binding" created
    clusterrole "service-catalog-controller" created
    clusterrolebinding "service-catalog-controller-binding" created
    role "endpoint-accessor" created
    error: role.authorization.openshift.io "endpoint-accessor" not found
    role "extension-apiserver-authentication-reader" created
    rolebinding "extension-apiserver-authentication-reader-binding" created
    clusterrolebinding "system:auth-delegator-binding" created
    deployment "apiserver" created
    service "apiserver" created
    deployment "controller-manager" created
    service "controller-manager" created
--> Failed
```

Would it be possible to deploy without relying on settings made by `oc cluster up` ? /cc: @bparees @pmorie

**Comment by bparees** [comment]
cluster up does a few things you'd have to replicate:

1) various master-config settings including some extensions for the webconsole so it will use the new SC experience
2) setting up some roles/permissions
3) deploying some service catalog resources
4) making some registration calls to api aggregation to register the SC w/ the api server
5) making some broker registration calls to the SC to register the template service broker (or other brokers you might want)

So those are the things you'd need to replicate if you want to stand it up without using the cluster up logic.

https://github.com/openshift/origin/blob/master/pkg/oc/bootstrap/docker/openshift/servicecatalog.go#L35
https://github.com/openshift/origin/blob/master/pkg/oc/bootstrap/docker/openshift/helper.go#L760-L863

**Comment by gbraad** [comment]
replicating this seems to be something that would also be needed on a stock
OpenShift deployment?

If so, this is valuable to collect and automate or at least describe in
some form

**Comment by bparees** [comment]
@gbraad the ansible installer is being updated to handle most of this.

**Comment by gbraad** [comment]
we do not support Ansible... (yet?)...

**Comment by gbraad** [comment]
It would be possible, and might be an effort we will undertake later. But for now, the effort is on figuring out what makes the current deployment fail.

**Comment by budhrg** [comment]
>  the effort is on figuring out what makes the current deployment fail.
Which is being track here https://github.com/minishift/minishift/issues/1252.
