### ISSUE TITLE
Rename of b2d image fails after completing download on Windows

### ISSUE THREAD

**Issue by abbr** [minishift/minishift#1186]
vbox shows minishift vm is running but cli hung.
![image](https://user-images.githubusercontent.com/6158277/28654700-2b069326-724b-11e7-90dc-23f00878cc07.png)

Edit by gbraad:
```
C:\Users\x>minishift start --vm-driver virtualbox
-- Installing default add-ons ... OOK
Starting local OpenShift cluster using 'virtualbox' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso
 40.00 MiB / 40.00 MiB {=============================================] 100.00% 0s
Error starting the VM: rename C:\Users\x\.minishift\cache\iso\minishift-b2d.iso.part C:\Users\x\.minishift\cache\iso\minishift-b2d.iso: The process cannot access the file because it is being used by another process.. Retrying.
Error starting the VM. Error creating machine: Error in driver during machine creation: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe storageattach minishift --storagectl SATA --port 0 --device 0 --type dvddrive --medium C:\Users\x\.minishift\boot2docker.iso failed:
...
```

**Comment by gbraad** [comment]
@praveenkumar seems the rename action on Windows needs to be checked for inconsistencies/race-conditions :-s

Similarly, someone mentioned seeing `.part` on #1180

**Comment by praveenkumar** [comment]
@gbraad ah, I have win10 box and that works as expected. now have to find someone who have win7 to reproduce or check if rename logic works.

**Comment by gbraad** [comment]
This is on Windows 10 as I can see from the version in the prompt.

**Comment by gbraad** [comment]
The error likely happened at: https://github.com/minishift/minishift/commit/854d63c5d069cddb54b0ae9662938f0ada063b4f#diff-221fdad1b39f75fb2d0214c25944dcb3R284

**Comment by praveenkumar** [comment]
@abbr  I think we know what causing this issue looks like os.Rename  is platform dependent and not working with windows. There are already  lot of discussion around it on github. We need to find a fix for it  apply asap.  -

- golang/go#8914 
- golang/go#14527

**Comment by gbraad** [comment]
How about using a mutex around the action, to prevent us from renaming or continuing, before the file download or rename has finished...

**Comment by praveenkumar** [comment]
So I kind of found why this was happening looks like we are renaming the file without closing file descriptor, it somehow (God knows) work in Linux but not in windows. below sample perfectly works in Linux (https://play.golang.org/p/6imaCE6fNm) but fail in windows.

```golang
package main

import (
	"os"
	"fmt"
)

func main() {
	tmpISOFile, err := os.Create(`C:\Users\prkumar\.minishift\cache\minishift.iso` + ".part")
	if err != nil {
		fmt.Println("Error creating tmpISO", err)
	} 
       defer tmpISOFile
	out, err := os.Create(`C:\Users\prkumar\.minishift\cache\minishift.iso`)

	if err != nil {
		fmt.Println("Error creating OutISO", err)
	}
	defer out.Close()
	if err := os.Rename(tmpISOFile.Name(), out.Name()); err != nil {
		fmt.Println("Error is:", err)
	}
}
```

```
PS C:\work\go\src\github.com\praveenkumar> go run .\test.go
Error is: rename C:\Users\prkumar\.minishift\cache\minishift.iso.part C:\Users\prkumar\.minishift\cache\minishift.iso: The process cannot access the file because it is being used by another process.
```

**Comment by gbraad** [comment]
@abbr, would be nice if future issues you do not use a screenshot, but copy-paste the text from the cmd prompt. Drag to select and use enter, or select and right-click on the titlebar to get edit options. this makes searching easier for others.

**Comment by gbraad** [comment]
@abbr can you try to use the version from: https://ci.appveyor.com/api/buildjobs/28sivxqxgm3oq3qm/artifacts/out%2Fwindows-amd64%2Fminishift.exe and let us know if this solved your problem. /cc: @jverger @qpiprob

**Comment by hferentschik** [comment]
I don't think that rename should be an issue when implemented correctly. Windows is notoriously tricky when dealing with fine handles. That does not mean though that renaming a file does not work.

**Comment by gbraad** [comment]
@hferentschik it was a hanging/open file handle. And yes, Windows is notoriously picky about this...

**Comment by jverger** [comment]
Thanks to @gbraad , i've just tried the minishift.exe that he provided and there is no more '.part' file issue.
Should this version could be available on the official minishift's download area ?

Many thanks for the reactivity guys !!!

**Comment by gbraad** [comment]
@praveenkumar approved fix ;-)

**Comment by abbr** [comment]
Works. Thx for quick response.
