### ISSUE TITLE
Warn or fail when doing minishift restart with options that require VM recreation

### ISSUE THREAD

**Issue by chadlwilson** [minishift/minishift#1190]
Certain (maybe all?) options to minishift start appear to require recreation of the VM in order to be effective; for example the `--insecure-registry` and `--registry-mirror` flags.

It's not immediately clear which of the options (or maybe all) require a `minishift delete` before `minishift start` in order to be picked up and applied permanently; or which are possibly a "per-run" option that is transient in nature and will be lost after `minishift stop`.

I would suggest either warning the user (or possibly even failing) upon `minishift start` if options are supplied that cannot be picked up except with recreation of the underlying VM.

**Comment by gbraad** [comment]
Yes, this is also not something I am very happy about... especially when doing this on Windows. However, it is the only guarantee that the environment is clean when deploying.

At the moment I am working on preflight checks which alleviate some of problem... but I understand your pain, as I also feel it.

**Comment by chadlwilson** [comment]
Thanks for the response - just a suggestion to make it a bit more usable. I was particularly confused when trying to verify that #873 was resolved earlier until I realised that the flags were only effective on first-time creation :)

From an automation perspective it'd probably be useful for it to fail, so a script could detect the failure and do a delete if it wants the VM to be recreated to pick up changes to options (which are perhaps coming externally from the environment)

**Comment by gbraad** [comment]
We have a task that deals with the startup parameters #179, but it has been open for a while. It should deal with detecting these changes

**Comment by praveenkumar** [comment]
@chadlwilson you can also use `config set` for any start options which will persistent across start and stop.

**Comment by gbraad** [comment]
I think it is more the experimental state, or reconfig that makes this more of a PITA than it should be.

**Comment by budhrg** [comment]
Still to do.

**Comment by tmds** [comment]
+1
