### ISSUE TITLE
Unable to install minishift on Windows 7 Enterprise with VirtualBox driver

### ISSUE THREAD

**Issue by biancaculea** [minishift/minishift#1199]
Hi, 
I want to install Minishift on Windows 7 Enterprise / I7/ 8GB RAM, 64-bit Operating System;

I ‘m using Minishift version 1.3.1 and version 4.3.12r93733 of VirtualBox.
Windows 7 Enterprise / I7/ 8GB RAM, 64-bit Operating System, VT-x enable;

I tried VirtualBox  5.1.26 but I had “Error in supR3HardNtChildPurify: supHardenedWinVerifyProcess failed with
VERR_SUP_VP_REPLACE_VIRTUAL_MEMORY_FAILED: (rc=-5673)  ] “. I changed to 4.3.12r93733

(I tried also VirtualBox  5.1.12 but I had  some virtualbox bug notification during installation and the installation exit )
 
Then I had the problems described in  https://github.com/minishift/minishift/issues/1180
and I had the .part issue using  1.3.0 and 1.3.1 minishift versions.

So, I manually download the file from: https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso  into cache/iso directory;      
(Is this is the correct version correlated with Minishift  1.3.1 version?)

Then and I obtained the error
  
"Cannot access master readiness URL https://192.168.99.101:8443/healthz "

I verified with curl https://192.168.99.101:8443/healthz/ready -k   and the answer was “ok” .

I h
[VBox.txt](https://github.com/minishift/minishift/files/1184219/VBox.txt)

ave no idea how to move on !  and I will appreciate some help !

These are the details:
```
minishift delete
minishift.exe start --show-libmachine-logs  --vm-driver virtualbox

Starting local OpenShift cluster using 'virtualbox' hypervisor...
(minishift) Trying to access option engine-install-url which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key engine-install-url
(minishift) Trying to access option swarm-master which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to bool for key swarm-master
(minishift) Trying to access option swarm-host which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key swarm-host
(minishift) Trying to access option swarm-discovery which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key swarm-discovery
(minishift) Type assertion did not go smoothly to bool for key virtualbox-host-dns-resolver
(minishift) Type assertion did not go smoothly to bool for key virtualbox-hostonly-no-dhcp
(minishift) Type assertion did not go smoothly to bool for key virtualbox-no-share
(minishift) Type assertion did not go smoothly to bool for key virtualbox-no-dns-proxy
(minishift) Type assertion did not go smoothly to bool for key virtualbox-no-vtx-check
Running pre-create checks...
(minishift) You are using version 4.3.12r93733 of VirtualBox. If you encounter issues, you might want to upgrade to version 5 at https://www
.virtualbox.org
Creating machine...
(minishift) Downloading D:\Users\george.culea\.minishift\cache\boot2docker.iso from file://D:/Users/george.culea/.minishift/cache/iso/minish
ift-b2d.iso...
(minishift) Creating VirtualBox VM...
(minishift) Creating SSH key...
(minishift) Starting the VM...
(minishift) Check network to re-create if needed...
(minishift) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.1 image ...
   Pulling image openshift/origin:v1.5.1
   Pulled 0/3 layers, 3% complete
   Pulled 1/3 layers, 78% complete
   Pulled 2/3 layers, 93% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ...
   Using 192.168.99.100 as the server IP
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
FAIL
   Error: cannot access master readiness URL https://192.168.99.100:8443/healthz/ready
   Details:
     Last 10 lines of "origin" container log:
     I0728 20:17:59.309386    3318 ensure.go:207] Created default security context constraint restricted
     I0728 20:17:59.311898    3318 ensure.go:207] Created default security context constraint anyuid
     I0728 20:17:59.314573    3318 ensure.go:207] Created default security context constraint hostnetwork
     I0728 20:18:00.263371    3318 trace.go:61] Trace "Create /oapi/v1/namespaces/default/rolebindings" (started 2017-07-28 20:17:59.3189134
18 +0000 UTC):
     [18.91µs] [18.91µs] About to convert to expected version
     [39.366µs] [20.456µs] Conversion done
     [928.442755ms] [928.403389ms] About to store object in database
     [943.857864ms] [15.415109ms] Object stored in database
     [943.872162ms] [14.298µs] Self-link added
     "Create /oapi/v1/namespaces/default/rolebindings" [944.372167ms] [500.005µs] END

Error during 'cluster up' execution: Error starting the cluster.
```

In the same time, I can see in the Vbox log :
…………………………..
```
00:00:40.294650 Guest Log: VBoxService 5.1.8 r111374 (verbosity: 0) linux.amd64 (Oct 18 2016 15:52:41) release log
00:00:40.294700 Guest Log: 00:00:00.000090 main     Log opened 2017-07-28T20:16:13.889619000Z
00:00:40.294780 Guest Log: 00:00:00.000227 main     OS Product: Linux
00:00:40.294813 Guest Log: 00:00:00.000261 main     OS Release: 4.4.27-boot2docker
00:00:40.294842 Guest Log: 00:00:00.000291 main     OS Version: #1 SMP Tue Oct 25 19:51:49 UTC 2016
00:00:40.294874 Guest Log: 00:00:00.000317 main     Executable: /sbin/VBoxService
00:00:40.294880 Guest Log: 00:00:00.000321 main     Process ID: 2410
00:00:40.294885 Guest Log: 00:00:00.000323 main     Package type: LINUX_64BITS_GENERIC
00:00:40.296388 Guest Log: 00:00:00.001824 main     5.1.8 r111374 started. Verbose level = 0
00:00:40.313922 Guest Log: 00:00:00.019237 vminfo   rtldrNativeLoad: dlopen('libdbus-1.so.3', RTLD_NOW | RTLD_LOCAL) failed: libdbus-1.so.3: cannot open shared object file: No such file or directory
00:00:40.313976 Guest Log: 00:00:00.019305 vminfo   Error: Unable to connect to system D-Bus (1/3): D-Bus not installed
00:00:40.743950 NAT: IPv6 not supported
00:00:45.325394 Guest Log: 00:00:05.033614 vminfo   Error: Unable to connect to system D-Bus (2/3): D-Bus not installed
00:00:50.323984 Guest Log: 00:00:10.034696 vminfo   Error: Unable to connect to system D-Bus (3/3): D-Bus not installed
```

**Comment by gbraad** [comment]
There's a lot of information here... and took me a little to sort through. I understand you had some issues with our current release, and this is very unfortunate. The issue with the downloading on Windows will hopefully be resolved soon.

Summary:
  * Windows 7 Enterprise / I7/ 8GB RAM, 64-bit Operating System
  * VirtualBox 5.1.26
  * `oc cluster up` fails with: 

```
Waiting for API server to start listening
FAIL
Error: cannot access master readiness URL https://192.168.99.100:8443/healthz/ready
```

I can only suggest to do `minishift delete` and `minishift start` at this moment. It can be an issue with the `oc` command... but if it repeats, it might be related to network. But for this I need to verify some code.

**Comment by biancaculea** [comment]
Minishift delete and minishift start does not help. I'm stacked in yhe same error!

**Comment by agajdosi** [comment]
@gbraad This issue reminds me of #291, when minishift start also ended for me on check at /healthz/ready. Later then it was dependent on iso image used. 

@biancaculea Only advice I can add now is to try `minishift start --iso-url centos` (or for manual download: https://github.com/minishift/minishift-centos-iso/releases/tag/v1.1.0) and see if that helps, maybe it will give you functional environment until this issue is resolved for b2d image.

**Comment by biancaculea** [comment]
Thank you ! 
With this new ISO the installation was ok & fast !

Summary:
•	Windows 7 Enterprise / I7/ 8GB RAM, 64-bit Operating System
•	Downgraded VirtualBox 4.3.12r93733
•	Downloaded ISO from https://github.com/minishift/minishift-centos-iso/releases/download/v1.1.0/minishift-centos7.iso
•	Installation :
o	- Checking Docker daemon configuration ... OK
o	- Checking for available ports ... OK
o	- Checking type of volume mount ...
o	  Using nsenter mounter for OpenShift volumes
o	- Creating host directories ... OK
o	- Finding server IP ...
o	  Using 192.168.99.100 as the server IP
o	- Starting OpenShift container ...
o	  Creating initial OpenShift configuration
o	  Starting OpenShift using container 'origin'
o	  Waiting for API server to start listening
o	  OpenShift server started
o	- Adding default OAuthClient redirect URIs ...
o	- Installing registry ... OK
o	- Installing router ... OK
o	- Importing image streams ... OK
o	- Importing templates ... OK
o	- Login to server ... OK
o	- Creating initial project "myproject" ... OK
o	- Removing temporary directory ... OK
o	- Checking container networking ... OK
o	- Server Information ...
o	  OpenShift server started.
o	  The server is accessible via web console at  https://192.168.99.100:8443

When the issue is resolved for b2d image I can be available for testing,

Now, when I launched the web console,  I experimented website's security certificate problem:
Using IE9: there is a problem with this website's security certificate….. 
Using Chrome, Version 60.0.3112.78 (Official Build) (64-bit)  :  NET::ERR_CERT_AUTHORITY_INVALID…..

openssl s_client -showcerts -connect 192.168.99.100:8443

Loading 'screen' into random state - done
CONNECTED(00000288)
7212:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:.\ssl\s23_clnt.c:578:

**Comment by gbraad** [comment]
Since it says "OpenShift server started", it means it worked as expected. The security issue is expected for the moment, as we can only have self-signed certificates at the moment.

I do not think the B2D image has an error... but it is likely a combination of software on your machine. I will see if I can test with Win7 Enterprise myself. So, I looked more into the issue with the more recent version you had with the newer version of VirtualBox: `VERR_SUP_VP_REPLACE_VIRTUAL_MEMORY_FAILED`. This might be related to Windows 7 and your virus scanner software (Trend Micro or McAfee?).

**Comment by biancaculea** [comment]
[ ESET Endpoint Antivirus, version  5.0.2265.0]

**Comment by biancaculea** [comment]
I was looking here, when  I decided to downgrade the VirtualBox to  4.3.12r93733 : 
•	https://www.virtualbox.org/ticket/13697
