### ISSUE TITLE
Update OpenShift version to v3.6.0

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1202]
Refer: https://github.com/openshift/origin/releases/tag/v3.6.0

**Comment by hferentschik** [comment]
@LalatenduMohanty are you creating a pull request for this?

**Comment by gbraad** [comment]
Be aware that we might have to include `--loglevel=1` to get the output we are used to.
And the printed output is not the same as before (as it misses all OK confirmations ATM.
See https://github.com/minishift/minishift/issues/1137#issuecomment-319248918 and onward.

**Comment by LalatenduMohanty** [comment]
@gbraad feel the path with --loglevel=1 might not be good for us. If we do that than we have to change it everytime `cluster up` changes it and we need to maintain backward compatibility with older Origin versions with respect to the output of `minishift start`. 

> And the printed output is not the same as before (as it misses all OK confirmations ATM.
> See #1137 (comment) and onward.

You mean the ok confirmations from cluster up right.

**Comment by hferentschik** [comment]
Merged via pull request #1213
