### ISSUE TITLE
Create a latest symlink for master builds in CentOS CI

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1209]
We have http://artifacts.ci.centos.org/minishift/minishift/master/ which can be used by community if they want minishift binary with a fix immediately after the merge till we release it formally. However at current state it is not intuitive to find out the latest build. So we should create a latest symlink which should always point to the latest build. 

Also we have an old build http://artifacts.ci.centos.org/minishift/minishift/master/877/ which needs to be removed.

**Comment by budhrg** [comment]
As part of it I am cleaning the archive server and keeping last 10 builds of pr, master. http://artifacts.ci.centos.org/minishift/minishift/

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift/pull/1424
