### ISSUE TITLE
Improve `make integration` to be friendlier to use

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1216]
As per discussion with @agajdosi, it seems to be a better idea to retag `coolstore.feature` as `@nightly` instead of `@coolstore`.

Also, the command itself should use be able to use tags as specifier without having to resort to using `GODOG_OPTS` from the command ;-).

Example:
```
$ make integration             # will run @basic
$ make integration nightly     # will run all tests tagged as nightly
```

Note:
The command should always run with `-format pretty`.

---
Todo
---

  * [ ] Provide a default option to run the basic scenario
      * [ ] Hide the need for `GODOG_OPTS`
      * [ ] retag tests
  * [ ] Provide option to run "smoke" tests (more than just basic, should not run more than 30 to 45 min, used by all request builds)
  * [ ] Provide option to run all features (used by nightly CI job)
    * [ ] includes coolstore

**Comment by gbraad** [comment]
https://github.com/minishift/minishift/pull/1213#issuecomment-319700705

**Comment by amitkrout** [comment]
After a short sync call with @agajdosi , We come to a point to add @all tag in make integration to perform the end to end validation. Basically @all will include the basic and nightly in the run. IMO, We should keep this option open though its a time consuming execution. 

```
$ make integration             # will run @basic
$ make integration nightly     #will run @nightly
$ make integration all      # will run @basic and @nightly
```

**Comment by gbraad** [comment]
the `GODOG_OPTS` is way too cryptic to use, so if we can hide this use from the developer, and make it easier to run, this is what we want. the syntax is not set in stone, and can surely be changed; because a `make integration_nightly` is likely easier to implement.

**Comment by hferentschik** [comment]
> $ make integration nightly     #will run @nightly

Well, technically 'integration_nightly', since targets have not spaces. Also what would be the difference between _integration_all_ and _integration_nightly_? The aim of the nightly job is to run all features, right? 

What we also need is a target the pull request builds use. All probably takes to long and we can for sure do more than basic. So there I would expect something like _integration_smoke_?

**Comment by amitkrout** [comment]
> Well, technically 'integration_nightly', since targets have not spaces. Also what would be the difference between integration_all and integration_nightly? The aim of the nightly job is to run all features, right?

hmm..agree. It was a miss judge from my end on ```@nightly``` and  ```@all```

>What we also need is a target the pull request builds use. All probably takes to long and we can for sure do more than basic. So there I would expect something like integration_smoke?

@hferentschik Adding ```integration_smoke``` again create one more option to implement. If you are looking to split make integration ```@basic``` then it not a good way to do because ```smoke``` test scenario will be repeated in ```basic``` (```@smoke``` is subset of ```@basic```). So keeping ```make integration``` intact is not a bad idea IMO.  

Now this looks something like this 
```
$ make integration                 # will run @basic
$ make integration_nightly      # will run all the feature 
```
And this looks more friendlier in testing terminology.

**Comment by hferentschik** [comment]
> Adding integration_smoke again create one more option to implement. 

I am not sure what you mean. I am not talking about changing anything in the tagging/structure of the tests. I am just talking about having another target in the Makefile which runs somewhere in the middle of basic (minimal, fast) and all (all tests, especially cool store, long). _smoke_ might be a bad choice of name. Let's try to find something different maybe.

> $ make integration                 # will run @basic

+1, we agree on that 

> $ make integration_nightly      # will run all the feature 

    $ make intrgration_all 

Let's try not to name the targets on when they are run, but rather what they are run. Look at it this way. Say I am new and try to figure out what integration test target to run. What is more interesting to know, which tests are getting run or when they are run? If I read _all_ without looking at the target definition or the feature files, I have a pretty good idea what this target does. `make integration_nightly` not so much.

**Comment by amitkrout** [comment]
#1327

**Comment by amitkrout** [comment]
#Coolstore integration test failed with timeout issue #1327

**Comment by amitkrout** [comment]
#1327

**Comment by amitkrout** [comment]
https://github.com/minishift/minishift/issues/1327

**Comment by agajdosi** [comment]
Not sure if it is planned to do, but to be sure: I just realized, that it would be useful to also implement a possibility to change the timeout value. Right now it is fixed on 3600 seconds and sometimes tests are hitting this 1 hour limit. For make integration all we should raise the default value probably, for basic it can be maybe lowered. But for sure being able to set it manually will be great - some machines are slower, have slower network etc.

For example: `make integration_all TIMEOUT=7200`.

@gbraad @amitkrout

**Comment by LalatenduMohanty** [comment]
As discussed with @agajdosi @amitkrout 

After trying to do as discussed in this issue (in #1379) it seems it need a lot of effort to completely bypass GODOG_OPTS as there are so many use cases it already covers e.g. pointing to a directory or pointing to a feature file and trying to put the logic to bypass it in Makefile is making things complicated Also we do not think it worth it. 

However we agreed as part of this issue we will do as follows:
 
* `$ make inegration` : It will run `@basic` by default and if user uses `GODOG_OPTS ` it will respect that as it does now. 

* `$ make integration_all` : It will run all tests. At this point it wont have coolstore. But once coolstore starts working we will add it here. 

*  We will add a variable for timeout e.g. `make integration_all TIMEOUT=7200`

@agajdosi Will create another issue where we can discuss how we can break down the tests further i.e. something similar to smoke tests, intermediate tests and all tests as ths needs further discussion about how we want to categorize our tests.

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/pull/1379
