### ISSUE TITLE
Make Minishift update code resilient towards exact location of minishift binary 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1217]
As part of issue #680, we wanted to change the structure of the release artefacts. However, [update.extractBinary](https://github.com/minishift/minishift/blob/88843dbfcdba668256fbf273b6bbc0b87cf5c277/pkg/minishift/update/update.go#L245-L245) does make explicit assumptions on where to find the _minishift_ binary. 

This prevents us from merging pull request #1212. 

To mitigate this, we need to change the implementation of _extractBinary_ to dynamically locate the _minishift_ binary. This change should then be released one release prior to a change for #680. Assuming the change will occur in 1.5.0, people can update to that version and then when 1.6.0 with a fix for #680 is released, they can seamlessly upgrade to 1.6.0 with the changed artefact layout.

As part of this issue we should also add a flag to the _update_ command which allows to "update" to a specific version. This will allow users who for example stayed on 1.4.0 to upgrade to 1.6.0 as well. For these users a 'minishift update' would fail, since their version of Minishift would not be able to handle the new layout. For them it would be:

    $ minishift update --to-version 1.5.0
    $ minishift update

Having the _--to-version_ might be handy feature to have regardless.

**Comment by gbraad** [comment]
>  one release prior

safe bet... at least two releases prior.

**Comment by hferentschik** [comment]
> safe bet... at least two releases prior.

sure. Good idea.

**Comment by hferentschik** [comment]
Merged via pull request #1217. Note there is no '--to-version' flag. Really it would not help as described anyways.
