### ISSUE TITLE
Restructure troubleshooting topic

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1219]
The troubleshooting topic is getting quite lengthy and hard to take in. I think we should try to find a better format. Maybe we also have already enough material to split based on the type of issues - advanced options, driver issues, etc

**Comment by thatdocslady** [comment]
@hferentschik can I take this on and propose a PR with a new structure? Or do you want to discuss some options before I give it a shot?

**Comment by hferentschik** [comment]
Why don't you outline on the issue what your plan is? At least roughly?

**Comment by thatdocslady** [comment]
Here is my proposal to restructure the document based on existing headings. The logic behind this division should be clear, but of course questions and feedback welcome.

== General
=== The root filesystem of the Minishift VM exceeds overlay size
=== Special characters cause passwords to fail

== Getting Started
=== GitHub API rate limit exceeded
=== Minishift startup check failed
=== Permission denied error when updating Minishift

== Driver Plug-ins
=== Undefining virsh snapshots fail
=== KVM: Error creating new host: dial tcp: missing address
=== KVM: Failed to connect socket to '/var/run/libvirt/virtlogd-sock'
=== KVM: Domain 'minishift' already exists…​
=== xhyve: Could not create vmnet interface
=== VirtualBox: Error machine does not exist
=== Hyper-V: Hyper-V commands must be run as an Administrator
=== Hyper-V: Minishift running with Hyper-V fails when connected to OpenVPN

NOTE: I still think that we should separate out the startup checks section into its own topic or as a part of one of the getting started topics. It's already structured like a standard topic so all we need to do is decide where to move it. Then I can rephrase the troubleshooting entry to be just 1-2 sentences with a link to the main topic.

**Comment by hferentschik** [comment]
> Here is my proposal to restructure the document based on existing headings. The logic behind this division should be clear, but of course questions and feedback welcome.

So you "just" want to split them out into more categories. Introducing a better grouping? +1 to that. I was wondering whether we should go one or two steps further. 

For example, we could make the troubleshooting guide it's own top level topic ("troubleshooting and advanced config"). This way it becomes more prominent in the navigation and we can also use multiple files to group issues. WDYT?

Also I am wondering whether we could have a more Q&A look and feel for this.

**Comment by hferentschik** [comment]
If we pull troubleshooting one level up, we also create room for our dedicated startup check section.

**Comment by gbraad** [comment]
If you move the troubleshooting guide, be sure to update the CentOS ISO
scripts/yum-wrapper too.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by thatdocslady** [comment]
Aha ok, it seemed to me from the description of the issue that you expected the restructuring to happen within the topic itself, so that's the assumption I was working under.

I don't see a problem splitting off the troubleshooting topic into its own category, but I would be careful to combine it with anything else, like advance config as you mention, since it might be confusing and historically troubleshooting guides/topics are usually better off as standalone/separate things.

I'm not sure what you would include under advanced config, but I imagine that most of those topics would be better put under the Using Minishift category. And again, I still feel that the startup check description doesn't belong under troubleshooting, since it's a part of the normal getting started and only if a check fails then people might look for it in the troubleshooting guide.

**Comment by hferentschik** [comment]
> Aha ok, it seemed to me from the description of the issue that you expected the restructuring to happen within the topic itself, so that's the assumption I was working under.

I thought I had kept it quite open in terms of what I meant. Also the description talks about a split. But anyways...

> I don't see a problem splitting off the troubleshooting topic into its own category, but I would be careful to combine it with anything else, like advance config as you mention, since it might be confusing and historically troubleshooting guides/topics are usually better off as standalone/separate things.

Sure, I am fine to call it "Troubleshooting". I think that is the right name and making it a top level navigation item is imo a good thing. The things in there are partly "advanced config" items, whether you somehow express this in the title or not. But let's stick to "Troubleshooting".

> And again, I still feel that the startup check description doesn't belong under troubleshooting

I think it does. These checks should be transparent to you. I would expect/hope to get very little if any feedback on these tests failing in a way where customisation is needed. Put yourself into the shoes of a user. Will he read the full getting started guide? In most cases note. He will download the binary and run `minishift start`. He then gets failures during startup that for example the internet connectively check does not pass. Assuming the user now to the docs and looks at the root level and assuming there is a top level "Troubleshooting" item, would you not agree that this is a natural place to look? I would. I probably would look there first over going to "Getting started". 

> since it's a part of the normal getting started and only if a check fails then people might look for it in the troubleshooting guide.

Exactly, you say it yourself. If a check fails you look at troubleshooting. Until it fails there is no need to even know about this. Why adding irrelevant information to the Getting Started section?

**Comment by hferentschik** [comment]
> If you move the troubleshooting guide, be sure to update the CentOS ISO
scripts/yum-wrapper too.

+1

**Comment by thatdocslady** [comment]
Ok @hferentschik I'm not going to fight over the startup check topic, you can always move it later if you change your mind. In the case of moving Troubleshooting to its own category, I still think the division of topics is logical, except that now you can look at them as separate topics under the category:

= General
== The root filesystem of the Minishift VM exceeds overlay size
== Special characters cause passwords to fail

= Getting Started
== GitHub API rate limit exceeded
== Minishift startup check failed
== Permission denied error when updating Minishift

= Driver Plug-ins
== Undefining virsh snapshots fail
== KVM: Error creating new host: dial tcp: missing address
== KVM: Failed to connect socket to '/var/run/libvirt/virtlogd-sock'
== KVM: Domain 'minishift' already exists…​
== xhyve: Could not create vmnet interface
== VirtualBox: Error machine does not exist
== Hyper-V: Hyper-V commands must be run as an Administrator
== Hyper-V: Minishift running with Hyper-V fails when connected to OpenVPN

**Comment by hferentschik** [comment]
> Troubleshooting to its own category, I still think the division of topics is logical, except that now you can look at them as separate topics under the category

+1, please go ahead and create a pull request.

**Comment by hferentschik** [comment]
Merged by pull request #1295
