### ISSUE TITLE
Support for Docker rather than KVM, VirtualBox, etc.

### ISSUE THREAD

**Issue by cdrage** [minishift/minishift#1229]
Similar to https://github.com/kubernetes/minikube/tree/master/deploy/docker is there any support for using Docker for OpenShift testing / deployment rather than hypberv/kvm/virtualbox/etc.?

**Comment by LalatenduMohanty** [comment]
@cdrage Minishift uses VM to provison OpenShift. So if you do not want the VM part and just want to run OpenShift locally using a docker daemon please use "oc cluster up".

**Comment by cdrage** [comment]
@LalatenduMohanty What I mean, is implementing `oc cluster up` __into__ minishift. Similar to what Minikube has done (you used to be able to deploy a single-node Kubernetes cluster with just Docker).

**Comment by gbraad** [comment]
This sounds like #392 ?

**Comment by gbraad** [comment]
We did discuss recently to target 'any possible' VM, with something like #1108. At the moment our priorities are different...

> "implementing oc cluster up into minishift"

Not really following this... could you explain? In minikube they recently have been considering the following: https://github.com/kubernetes/minikube/issues/1456 This way they would actually use something like `kubeadm` to accomplish the same as we do...

**Comment by budhrg** [comment]
@cdrage , any follow up comment on @gbraad question?
