### ISSUE TITLE
Proxy not set for Docker engine

### ISSUE THREAD

**Issue by sl0n** [minishift/minishift#1230]
That's really the same as #1153, I've just tested it on:

CentOS 7.3.1611
minishift v1.3.1+f4900b07

```
Running minishift as follows:
./minishift  start --iso-url centos  --https-proxy http://10.252.13.67:3128 -docker-env "HTTPS_PROXY=http://10.252.13.67:3128"
```

results in the following in minishift's VM:

```
# ./minishft ssh
Last login: Fri Aug  4 11:39:27 2017 from 192.168.42.1

[docker@minishift ~]$  cat /etc/systemd/system/docker.service.d/10-machine.conf
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd-current -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock            --selinux-enabled            --log-driver=journald            --signature-verification=false            --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current            --default-runtime=docker-runc            --exec-opt native.cgroupdriver=systemd            --userland-proxy-path=/usr/libexec/docker/docker-proxy-current            --storage-driver devicemapper --tlsverify --tlscacert /etc/docker/ca.pem            --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem            --label provider=kvm --insecure-registry 172.30.0.0/16 
Environment=[HTTPS_PROXY=http://10.252.13.67:3128/,HTTPS_PROXY=http://10.252.13.67:3128,"NO_PROXY=localhost,127.0.0.1,172.30.1.1"]

```
Where the following is expected:

```
Environment="HTTPS_PROXY=http://10.253.13.67:3128/"
Environment="NO_PROXY=localhost,127.0.0.1,172.30.1.1"
```

**Comment by hferentschik** [comment]
So you would expect one _Environment_ line per variable, right? You get a single "array" of sorts, right? Are there any errors in the service logs? Is this invalid as systemd config or is it just ignored? 

BTW, you don't have to use  --https-proxy and --docker-env. --https-proxy will take care of setting the Docker proxy settings, there is no need for using --docker-env as well. 

@praveenkumar WDYT?

**Comment by praveenkumar** [comment]
@sl0n we already have it fixed and soon it will be released as part of 1.4.0, If you compile from master right now you will not see any issue for proxy and unit file.

```
$ ./minishift start --docker-env foo=bar --docker-env bar=foo --iso-url centos --http-proxy=http://fedora:fedora123@10.70.49.109:3128
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/sbin/docker-machine-driver-kvm ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
[...]
The server is accessible via web console at:
    https://192.168.42.25:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin
[...]

$ ./minishift ssh
$ docker info
[..]
Debug Mode (server): false
Http Proxy: http://fedora:fedora123@10.70.49.109:3128
No Proxy: localhost,127.0.0.1,172.30.1.1
Registry: https://index.docker.io/v1/
[..]
$ cat /etc/systemd/system/docker.service.d/10-machine.conf 
[Service]
[...]
Environment=HTTP_PROXY=http://fedora:fedora123@10.70.49.109:3128 NO_PROXY=localhost,127.0.0.1,172.30.1.1 foo=bar bar=foo 
```

**Comment by sl0n** [comment]
@praveenkumar v1.3.1 release says the following for "Bugs" section (among other things):
..
Issue #1153 (bug) - Proxy not set for Docker engine
..

I get it as "the bug #1153 has been fixed in v1.3.1 release",  so I tested it with the v1.3.1 release and confirmed the bug is still present.

**Comment by praveenkumar** [comment]
@sl0n yeah, we missed some of other expect and thought fixed in place but had issue. Can you please try with latest master and see if you still face same issue.

**Comment by hferentschik** [comment]
@sl0n, the easiest is to just take the latest master build from there - http://artifacts.ci.centos.org/minishift/minishift/master/258/

**Comment by sl0n** [comment]
I see v1.4.0 has been release just 20 mins ago, I'm going to test that one.

**Comment by gbraad** [comment]
reopened?

**Comment by sl0n** [comment]
@gbraad clicked wrong button, will close it once v1.4.0 is tested and the bug is confirmed to get fixed.

**Comment by sl0n** [comment]
So, I downloaded this file - https://github.com/minishift/minishift/releases/download/v1.4.0/minishift-1.4.0-linux-amd64.tgz

The proxy issue has been indeed fixed, thank you guys!

I noticed the following:

```
# ./minishift version
minishift v1.3.1+27ec32a
```
I expect to see v1.4.0, however given the original issue is fixed, I'm going to close this issue.

**Comment by gbraad** [comment]
there is an issue with the newly introduced automated release scripts.
Thanks...
