### ISSUE TITLE
Don't show empty headers in release notes

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1237]
Hi,

Currently, if there is not issues related to tasks/bugs/features in milestone, then as output of `issue_list.sh` script it show the headers as empty as : 

```
# Features

# Bugs

# Tasks
```

**Comment by gbraad** [comment]
depends on how you look at it; if there are no tasks/bugs and/or features in a milestone, you would expect this to be empty. or is this due to an error with the milestone's JSON result you get back?

or is this an optimization, if no bugs exist, then do not show the "Bugs" header, and so forth... ?

**Comment by budhrg** [comment]
> or is this an optimization, if no bugs exist, then do not show the "Bugs" header, and so forth... ?

Yes optimization. Suppose, I have only one bug and one feature in the milestone then, the output should be
```
# Features

- Foo feature

# Bugs

- Bar bug
```
