### ISSUE TITLE
Minishift unable to add impersonation 'sudoer' role when try to provision OpenShift == v3.6.0

### ISSUE THREAD

**Issue by sl0n** [minishift/minishift#1246]
I have:

**CentOS 7.3.1611
minishift v1.4.1+0f658ea
libvirt-daemon-kvm-2.0.0-10.el7_3.9.x86_64
qemu-kvm-1.5.3-126.el7_3.10.x86_64**

I want to run "minishift" as non root user. I add "myuser" to 'libvirt' OS group to be able to interact with "libvirt" layer: 

```
$ sudo usermod -a -G libvirt myuser
$ newgrp libvirt
```
Now I start minishift:

```
$ ./minishift start --iso-url centos  --https-proxy https://10.252.13.67:3128 --logging  --logtostderr --v=5 --show-libmachine-logs
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:44484
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM ... I0808 11:30:41.210091   20501 cluster.go:80] Machine exists!
| Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:33717
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
I0808 11:30:41.230463   20501 cluster.go:88] Machine state:  Stopped
(minishift) Calling .Start
(minishift) DBG | Starting VM minishift
| (minishift) DBG | GetIP called for minishift
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) DBG | IP address: 192.168.42.116
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:b9:b5:72
/ (minishift) Calling .GetConfigRaw
Waiting for SSH to be available...
Getting to WaitForSSH function...
(minishift) Calling .GetSSHHostname
(minishift) DBG | GetIP called for minishift
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) DBG | IP address: 192.168.42.116
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:b9:b5:72
..
```
Error: `(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases`

And it keeps cycling around this until you "CTRL+C" it.

**Comment by sl0n** [comment]
It works just find, if I run the same as root user.

**Comment by praveenkumar** [comment]
@sl0n As per your logs what I can see `-- Starting Minishift VM ... I0808 11:30:41.210091   20501 cluster.go:80] Machine exists!` that means your environment is not cleaned or you are trying to restart a Minishift (start => stop => start). Can you follow below and see if still a issue.

Our integration test always happen on CentOS infra and we didn't face this type of issue.

1. Make sure you did `minishift delete` from your root user also remove completely `/root/.minishift/` this is not a good thing to do.
2. Back to your normal user and then try  `minishift delete clear-cache`
3. Start minishift again.

**Comment by sl0n** [comment]
@praveenkumar cleaning up as you suggested it was able to finish the start. There are still plenty of  messages about the lease file though, can I just ignore it?

Also, there the following message by the very end:

```
..
To login as administrator:
    oc login -u system:admin

**Error during post cluster up configuration: Unable to add sudoer role**
```

**Comment by praveenkumar** [comment]
> There are still plenty of messages about the lease file though, can I just ignore it?

These messages are there because you used --show-libmachine-logs --v=5 and yes you can ignore those.

> Also, there is the following message by the very end:

Which version of minishift are you using and what all command line options you provided when started it? Check #1242 also.

**Comment by sl0n** [comment]
minishift v1.4.1+0f658ea

```
$ ./minishift start --iso-url centos  --https-proxy https://10.252.13.67:3128
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ... - 
   Setting hostname ..\ OK
| -- Setting proxy information ..- OK
OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ... 
   host-config-dir ... OK
   https-proxy ... OK
   env ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   no-proxy ... OK
   public-hostname ... OK
   routing-suffix ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
Pulling image openshift/origin:v3.6.0
Pulled 1/4 layers, 26% complete
Pulled 2/4 layers, 77% complete
Pulled 3/4 layers, 88% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://myhostname:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

Error during post cluster up configuration: Unable to add sudoer role
```

**Comment by gbraad** [comment]
The error you are seeing is something that we perform within OpenShift, and the terminology can be confusing as 'sudo' in this case is not the same as used on the host or your workstation, but actually an impersonation functionality which can be used as `oc --as system:admin get status`, etc.

Your OpenShift cluster is actually functional, but we are working on fixing this...

**Comment by sl0n** [comment]
OK, thanks everyone for your comments and help! Please close the issue, if needed, it seems to be a duplicate at this point.

**Comment by praveenkumar** [comment]
@sl0n So you are provisioning openshift-3.6.0 and this shouldn't occur. looks like your `kubeconfig` file got corrupted. Can you please do below steps and let us know if still same issue?

1. minishift delete --clear-cache
2. rm -fr ~/.kube
3. ./minishift start --iso-url centos  --https-proxy https://10.252.13.67:3128

**Comment by gbraad** [comment]
@praveenkumar you suspect the same issue with `~/.kube`  as earlier... instead of not being able to login as developer, but in this case not able to use admin credentials?

**Comment by sl0n** [comment]
@praveenkumar repeated the steps as you suggested and saw no error anymore.

**Comment by budhrg** [comment]
@sl0n 

> repeated the steps as you suggested and saw no error anymore.

Glad to hear that. So it was mostly file corruption issue as @praveenkumar mentioned.

Closing this issue. Feel free to reopen it when you hit by it again :)
