### ISSUE TITLE
ISO caching need to be restructure to have version information

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1258]
Currently we don't have any version directory structure for ISO cache and moving forward if we want to decouple our ISO releases with minishift then we need to put some plan for it. 

- Should have `/cache/iso/<iso_verison>/minishift.iso` structure.
- Have a default iso version flag/variable on minishift side so that we understand what should be be downloaded and compatible.

@gbraad please add your points.

**Comment by gbraad** [comment]
The concern I have is how to treat the previously downloaded images.

We could however, for once force the user to re-download the image... because we know it is 'outdated' (unknown) anyways. this would allows us to clear the folder and start from scratch.

**Comment by LalatenduMohanty** [comment]
I guess we can only get the version information when the ISO get downloaded from github right? For file:///URI the ISO is not saved in the cache directory.

**Comment by hferentschik** [comment]
> The concern I have is how to treat the previously downloaded images.

I don't think we have to overthink this. I think it is fair to just download the image again.

**Comment by praveenkumar** [comment]
>  For file:///URI the ISO is not saved in the cache directory.

No, it's not saved in the cache directory.

**Comment by hferentschik** [comment]
I was thinking along these lines:

    tree cache/
    cache/
    └── iso
        ├── b2d
        │   ├── 1.1.0
        │   │   └── minishift-b2d.iso
        │   └── 1.2.0
        │       └── minishift-b2d.iso
        ├── centos
        │   ├── 1.2.0
        │   │   └── minihsift-centos.iso
        │   └── 1.3.0
        │       └── minishift-centos.iso
        └── minikube
            └── 1.0.0
                └── minikube.iso

Not sure whether we could get the version into the ISO filename as well, eg minihsift-centos-1.2.0.iso. This way the file itself is more useful. If we can get the version into the filename, we could maybe skip the _version_ level. On the other hand, it does not hurt either way and with it, it aligns with how we cache _oc_.

**Comment by hferentschik** [comment]
Merged by #1618
