### ISSUE TITLE
Ability to create multiple Minishift  clusters

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#126]
Would it be possible to have different named clusters, so I can start/stop the cluster I want?

It would be nice to have a workflow that could enable this:

```
minishift start my-example-cluster
minishift stop

minishift start my-minimal-cluster
minishift stop

minishift start my-example-cluster
minishift stop

minishift delete my-example-cluster
```

**Comment by LalatenduMohanty** [comment]
Good idea. But as per my understanding it wont be easy or trivial. So the question is what is the priority of this feature.

**Comment by jorgemoralespou** [comment]
Why can't be easy? Don't have to be running at the same time, but as long as you give the machine a name you can create multiple machines.

**Comment by jimmidyson** [comment]
If it's so easy then I wait for your contribution :-b

It's definitely doable, just need to refactor stuff a bit. I'm sure this would be useful upstream as well btw.

**Comment by LalatenduMohanty** [comment]
@jorgemoralespou I think thats good news. If you can give the steps, I can try to put in minishift.

**Comment by budhrg** [comment]
+1 for the idea @jorgemoralespou

**Comment by jorgemoralespou** [comment]
@jimmidyson I would contribute if I knew go. 
The only thing I can do is blog about my thoughts and how I would like this to work. I have it working with oc cluster up although not the tool. Just a workaround for me for now. 

Since I know you've already read it. I leave it here for others:
http://jorgemoral.es/2016/10/developing-locally-with-openshift/

**Comment by jimmidyson** [comment]
I really love that post - you've explained the use cases for each of your requirements really clearly, thank you. One thing we've talked about is trying to keep minishift ux as close to minikube's as possible. With that in mind, would you be able to raise an issue in https://github.com/kubernetes/minikube/issues with a similar discussion?

**Comment by jimmidyson** [comment]
Next step will be to break down your post into separate issues & then we'll be able to start working towards them. Help to raise those issues, discuss the details & review the implementations would be awesome contributions - & there were you saying you couldn't contribute because it's written in go 😜

**Comment by jorgemoralespou** [comment]
For reference: https://github.com/kubernetes/minikube/issues/886

**Comment by jorgemoralespou** [comment]
Also, I've seen minikube supports addons, which is similar to the plugins we do support in [oc-cluster -wrapper](https://github.com/openshift-evangelists/oc-cluster-wrapper/tree/plugins). Does minishift support addons?

**Comment by hferentschik** [comment]
There is a discussion ongoing on Minikube on how this should look like from an ux perspective - https://github.com/kubernetes/minikube/issues/886

**Comment by hferentschik** [comment]
Seems Minikube went ahead and implemented something - https://github.com/kubernetes/minikube/pull/1320#issue-218975764

**Comment by budhrg** [comment]
Yes @hferentschik  :)

**Comment by jorgemoralespou** [comment]
This is great. I find it complex how to switch the active profile/VM but in
any case great that it landed. I would probably look if the experience can
be improved before it's been finally released.

**Comment by hferentschik** [comment]
>  I find it complex how to switch the active profile/VM 

+1 I am not a big fan yet either. We need to test drive with Minikube a bit and see how much we want to align. As we discussed with other related issues, there is a tradeoff between providing a user a smooth transition between Minikube and Minishift and having a potentially better ux. 

Right now my biggest concern is the re-use of 'config set'. I think it would have been better to have dedicated commands there. 

Anyways, it has landed. So we need in a first step evaluate it, see how much we can potentially re-use and last but not least decide whether we want to (at least partly) go different ways.

**Comment by jorgemoralespou** [comment]
I like how it sounds.

**Comment by jorgemoralespou** [comment]
This seems to have been addressed. They changed from --name to --profile (-p) and added a command "profile".

I'm flattered.

https://github.com/kubernetes/minikube/pull/1466

**Comment by hferentschik** [comment]
> This seems to have been addressed. They changed from --name to --profile (-p) and added a command "profile".

+1 yeah. Good stuff.

**Comment by gbraad** [comment]
Minikube supports multiple instances from https://github.com/kubernetes/minikube/pull/1320

**Comment by jorgemoralespou** [comment]
@hferentschik @gbraad I would consider looking at this feature, as to enable this, a lot of things related to config and addons would probably need to change. Configuration should now be per-cluster and not global, as well as addons enablement, etc...

**Comment by hferentschik** [comment]
It is scheduled for the next sprint. I also envision this to cause quite some changes.

**Comment by budhrg** [comment]
> to enable this, a lot of things related to config and addons would probably need to change. 

I feel the same.

> Configuration should now be per-cluster and not global, as well as addons enablement, etc...

+1. Most of the major changes will happen around this.

**Comment by LalatenduMohanty** [comment]
Here is my current plan to implement this 

Over all objective : User should be able to start a new instance of Minishift with `minishift start --profile xyz`. The instance will be a completely new instance and will get the default add-ons i.e. similar to how a fresh minishift setup gets. it will not be affected by what add-ons, configurations other minishift instances have.  The instance will have a directory in `.minishift/machines/\<instance name`>` . user can provide config set  parameters for each instance separately.  

I have divided the task in to 4 sections
* Code modification to use a profile name  for Minishift. 
* 2nd, each add-ons modifications should be specific to each instance/profile
* Separate configs for (config.jsons) for each instance.
* Handle kubeconfig contexts for each instance.

**Comment by hferentschik** [comment]
@LalatenduMohanty I am wondering how you are going to implement this. I would have thought that point 2 - 4 of your list will follow automatically once you have isolated instances. AFAIR we said that each instance is completely isolated, aka has it's own home directory. This functionality we already have with $MINISHIFT_HOME. So really we have a fair bit of what's needed to handle multiple instances already. 

The reason it does not work to truly have multiple instances at the moment is the VM name. This is currently still a fixed constant. Hence, even if I were to use multiple instances using MINISHIFT_HOME using the same driver things will fail (if one uses different drivers per VM it actually works).

So I would assume that if we make the VM name dynamic as the Minishift home directory, everything will work. Then one only has to provide the required commands and flags to create the VMs and manage them. WDYT?

**Comment by hferentschik** [comment]
@LalatenduMohanty what's the plan to select/switch  between instances? `minishift start --profile foo` will create the foo instance. How to I switch then between multiple instances? Will all existing commands get a --profile parameter to make it apply to a given instance? Will there be a `minishift profile set foo` command selecting the current VM (which once set will apply all commands against the foo instance)? Will it be a combination of this? How does Minikube do it?

**Comment by LalatenduMohanty** [comment]
> So I would assume that if we make the VM name dynamic as the Minishift home directory, everything will work. Then one only has to provide the required commands and flags to create the VMs and manage them. WDYT?

Thats exactly what I am working on right now. IMO thats the right way to do it.

**Comment by LalatenduMohanty** [comment]
> what's the plan to select/switch between instances? minishift start --profile foo will create the foo instance. How to I switch then between multiple instances? Will all existing commands get a --profile parameter to make it apply to a given instance? Will there be a minishift profile set foo command selecting the current VM (which once set will apply all commands against the foo instance)? Will it be a combination of this? How does Minikube do it?

I am fine the way Minikube do it and mostly planning to do the same. You can have multiple instances up, however the last `minishift start --profile` would have its kubecontext set properly and user can directly interact with the instance. If you want to change there is a command Minikube provides (got merged recently) to change context. Also there be a minishift profile set foo command.

**Comment by hferentschik** [comment]
> You can have multiple instances up, however the last minishift start --profile would have its kubecontext set properly and user can directly interact with the instance. 

sure, that's an implicit `profile set`.


> If you want to change there is a command Minikube provides (got merged recently) to change context.

That I don't get. Change what? The Kube context? That would be implicit by using `minishift profile set foo` right? This command tells Minishift that from now on I want to talk to instance 'foo'. At this stage I would also think that the Kube context to interact with OpenShift via oc gets transparently set.

**Comment by LalatenduMohanty** [comment]
> That I don't get. Change what? The Kube context? That would be implicit by using minishift profile set foo right?

That does not happen in Minikube AFAIR.  Let me look in to that and then discuss. If required I can change things like this in both Minikube and MInishift in a similar way.

**Comment by jorgemoralespou** [comment]
@LalatenduMohanty @hferentschik I mostly agree with most of what you say, and I would think that having a design document to "have all these" properly defined could help.

Also, remember minishift and minikube are different as there's no login in minikube, but yes, changing the profile should also change the context. And the context should be aligned with the name of the profile, so I can easily relate one to the other.

````
minishift start -p cluster1
oc config current-context    --> cluster1
minishift start -p cluster2
oc config current-context    --> cluster2
minishift use cluster1
oc config current-context    --> cluster1
oc config get-contexts -o name --> cluster1, cluster2
````

I also think that at some point, minishift will have to deal with contexts. I have started a project (bash script) to experiment and understand contexts [here](https://github.com/openshift-evangelists/oc-login)

**Comment by budhrg** [comment]
> Code modification to use a profile name for Minishift.
> 2nd, each add-ons modifications should be specific to each instance/profile
> Separate configs for (config.json and instance config) for each instance.
> Handle kubeconfig contexts for each instance.

Along with above I think we need to manage separate caching folder for separate instances.

**Comment by hferentschik** [comment]
> Along with above I think we need to manage separate caching folder for separate instances.

We get this for free. Everything is under $MINISHIFT_HOME.

**Comment by LalatenduMohanty** [comment]
> Along with above I think we need to manage separate caching folder for separate instances.

This is tricky as we do not want to download the ISO and OC binary again if we already have a copy. However for container images as we are saying the new instance would be a fresh start we might not want to share the cached container images as this would mean reusing older container images.

**Comment by LalatenduMohanty** [comment]
> I also think that at some point, minishift will have to deal with contexts. I have started a project (bash script) to experiment and understand contexts here

@jorgemoralespou will take a look.

**Comment by hferentschik** [comment]
> This is tricky as we do not want to download the ISO and OC binary again

I am confused. If we are going down the above discussed road, there is no sharing of the cache. Trying to do so will open up a whole range of problems. So if you create two instances, you would re-download the ISOs. Moving forward we might be able to investigate sharing some of the cache, but we would change of multiple levels here to make this happen. The cache directories are not properly structured to handle multiple instances.

**Comment by LalatenduMohanty** [comment]
> Trying to do so will open up a whole range of problems. So if you create two instances, you would re-download the ISOs. Moving forward we might be able to investigate sharing some of the cache, but we would change of multiple levels here to make this happen. The cache directories are not properly structured to handle multiple instances.

Make sense. Lets postpone this (sharing cache) for future.

**Comment by hferentschik** [comment]
>  Lets postpone this (sharing cache) for future.

+1, I am not saying it is not possible, but I think it is better done incrementally. The _oc_ binary should be cached properly, but for the ISO we for example would need to get the version into the cache paths to allows for the case of two VMs using the same ISO in different versions (atm we don't have any version information in the cached ISO). Regarding cached images, once we would be using a OCI based stored we should be fine there, right now with the current docker save/load approach it will most likely work, but won't be ideal.

There is a different aspect to this as well. One of the ideas of MINISHIFT_HOME is to get data away from ~/.minishift, we we know pull the cache out MINISHIFT_HOME won't be applying to all data of Minishift anymore. If nothing else, it has implications for testing. 

BTW, where will the information be stored on which VM is currently active? Will there be a new config file?

**Comment by budhrg** [comment]
> BTW, where will the information be stored on which VM is currently active? Will there be a new config file?

Since this config `~/.minishift/config/config.json` will be pull out to instances, we should use this as top level config which will store global information like above `currently active VM`, `current context` etc

**Comment by hferentschik** [comment]
> Since this config ~/.minishift/config/config.json will be pull out to instances, 

Not sure what you mean. Each instance will have its own config.json. We need a new place to store global state.

**Comment by gbraad** [comment]
Am I missing something... but we already have an allinstances config (used
by hostfolders)

**Comment by hferentschik** [comment]
> Am I missing something... but we already have an allinstances config (usedby hostfolders)

This might be more like it. We definitely need to see how this is handled in the context of this issue.

**Comment by LalatenduMohanty** [comment]
Here are some scenarios which we can take as acceptance criteria for the feature.

Case -1
```

$ minishift start


$ minishift profile list

- minishift	Running	(Active profile)


$ minishift start --profile test

$ minishift profile list
- test		Running
- minishift	Running	(Active profile)

$ minishift profile set test
Profile set to 'test' successfully

$ oc status
In project My Project (myproject) on server https://192.168.42.147:8443

You have no services, deployment configs, or build configs.
Run 'oc new-app' to create an application.

$ minishift ip --profile test
192.168.42.147

$ minishift profile list
- minishift	Running
- test		Running	(Active profile)
```

**Comment by LalatenduMohanty** [comment]
Case -2 : User moving to new minishift binary from older minishift binary

1. If user has an instance running then user should stop the instance and move to the new binary. Then the subsequent `minishift start` should set `minishift` as the default profile

**Comment by LalatenduMohanty** [comment]
Case-3
--------
If user starts with a specific profile by default `minishift` will be present

```
$ minishift start --profile test
-- Installing default add-ons ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% OK
-- Adding profile 'test' to config
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ... 
   host-pv-dir ... OK
   host-volumes-dir ... OK
   routing-suffix ... OK
   host-config-dir ... OK
   host-data-dir ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
Pulling image openshift/origin:v3.6.0
Pulled 1/4 layers, 26% complete
Pulled 2/4 layers, 67% complete
Pulled 3/4 layers, 93% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.83:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

[lmohanty@LalatenduM-laptop minishift]$ minishift profile list
- test		Running
- minishift	Does Not Exist	(Active profile)
```

**Comment by hferentschik** [comment]
+1 for the scenarios, they are of great help. They also make sense to me.

On a side note, I think we should use the commands in the form:

    $ minishift --profile test start 
    $ minishift --profile test ip
    ...

'--profile' are global options.

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift/pull/1380
