### ISSUE TITLE
Restructure code around ValidateOpenshiftMinVersion

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1261]
Currently ValidateOpenshiftMinVersion() [1]  is in pkg/minishift/clusterup/clusterup.go but it should be in 
https://github.com/minishift/minishift/blob/master/pkg/minishift/openshift/version/openshift_versions.go as this package supposed to contains function around OpenShift versions. 

Also the function name ` ValidateOpenshiftMinVersion` does not sound correct as it is actually doing a semantic version comparison between two versions and just not with minimum supported version. 

[1] https://github.com/minishift/minishift/blob/master/pkg/minishift/clusterup/clusterup.go#L282-L299

**Comment by budhrg** [comment]
Still to do.

**Comment by LalatenduMohanty** [comment]
Fixed via #1806
