### ISSUE TITLE
Can't open minishift dashboard

### ISSUE THREAD

**Issue by mjbright** [minishift/minishift#1262]
First steps using minishift, I installed v1.4.1, using VirtualBox v5.1.26 on Fedora 24.

Installation seems fine but I'm unable to open the dashboard.

When I run ```minishift dashboard``` it tries to open https://192.168.99.100:8443/ in the browser.
I get "refused to connect".
Which seems normal as it doesn't look like anything is listening on port 8443.

Running nmap to see which ports my VM is listening on shows:
```
nmap -Pn 192.168.99.100

Starting Nmap 7.40 ( https://nmap.org ) at 2017-08-12 10:30 CEST
Nmap scan report for 192.168.99.100
Host is up (0.00014s latency).
Not shown: 997 closed ports
PORT    STATE SERVICE
22/tcp  open  ssh
80/tcp  open  http
443/tcp open  https
```

If I try to open https://192.168.99.100:443 the browser shows
```
Application is not available

The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

Possible reasons you are seeing this page:

The host doesn't exist. Make sure the hostname was typed correctly and that a route matching this hostname exists.
The host exists, but doesn't have a matching path. Check if the URL path was typed correctly and that the route was created using the desired path.
Route and path matches, but all pods are down. Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.
```

**Comment by mjbright** [comment]
Poking around in the VM I saw that the origin container itself had crashed ...

minikube stop
minikube start

solved the problem.

**Comment by gbraad** [comment]
Can you provide some more information:

  * is this repeatable?
    if so, please provide a `minishift start --show-libmachine-logs -v 5`
  * which version of the ISO are you using?
    * CentOS or B2D
    * has these images been cached with a previous version of Minishift?
  * `minishift ssh -- docker ps`

More questions might follow ...

Note: be aware that Fedora 24 is EOL: https://fedoramagazine.org/fedora-24-eol/ Please consider updating to Fedora 25/26.

**Comment by mjbright** [comment]
Thanks, but stop/start was all I needed - but I note the sort of
information I should provide when opening issues.

Yes, I know for F24 ... must do a backup one of these days so I can jump
straight to F26  ...
