### ISSUE TITLE
Refactor: proxy URL validation redundant

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1266]
https://github.com/minishift/minishift/blob/3b82cbed7eba3ee6890621e5e966ea4515b19fa0/pkg/util/proxy.go#L145-L154

https://github.com/minishift/minishift/blob/377c7db723615794dceabdbfcbf8c4979f5d33dd/cmd/minishift/cmd/config/validations.go#L95-L100

**Comment by gbraad** [comment]
With #1263 most of the validation code is moved from `cmd/config` to `pkg/minishift`.

**Comment by gbraad** [comment]
Needs to be addressed

**Comment by anjannath** [comment]
@gbraad the refactor would involve removing the check from `proxy.go` and making it contained in the `validations.go` file?

**Comment by gbraad** [comment]
likely, as currently it is used in `m config set`, `m start` and maybe in future rather as a pre-flight check (instead of start).

**Comment by anjannath** [comment]
This will be implemented as part of #1569
