### ISSUE TITLE
Still seeing this issue

### ISSUE THREAD

**Issue by ishuverma** [minishift/minishift#1275]
This issue suddenly started occuring for me after months of using minishift without any problem. 

I'm seeing it both xhyve and virtualbox and with latest release of CDK 3.1.0-1

The issue is perhaps with docker networking and not minishift so any suggestions on the fix you tested will be great. Thanks.

**Comment by budhrg** [comment]
> This issue suddenly started occuring for me a

which issue @ishuverma ? Could you describe in details about the issue?

**Comment by ishuverma** [comment]
Sorry, was referring to this issue: https://github.com/minishift/minishift/issues/1275#issuecomment-322822518

Please see the log below for the details of the error I'm getting:
$ minishift start --username=<username> --password=<password> --logtostderr --show-libmachine-logs --vm-driver=virtualbox start

Starting local OpenShift cluster using 'virtualbox' hypervisor...
(minishift) Trying to access option engine-install-url which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key engine-install-url
(minishift) Trying to access option swarm-master which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to bool for key swarm-master
(minishift) Trying to access option swarm-host which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key swarm-host
(minishift) Trying to access option swarm-discovery which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key swarm-discovery
(minishift) Type assertion did not go smoothly to bool for key virtualbox-host-dns-resolver
(minishift) Type assertion did not go smoothly to bool for key virtualbox-hostonly-no-dhcp
(minishift) Type assertion did not go smoothly to bool for key virtualbox-no-share
(minishift) Type assertion did not go smoothly to bool for key virtualbox-no-dns-proxy
(minishift) Type assertion did not go smoothly to bool for key virtualbox-no-vtx-check
Running pre-create checks...
Creating machine...

**Comment by gbraad** [comment]
This is a message from libmachine (docker-machine), which is only visible when ` --show-libmachine-logs ` is used. they do not have any effect on our use-case.

Closing this issue...

**Comment by budhrg** [comment]
> This is a message from libmachine (docker-machine), which is only visible when --show-libmachine-logs is used.

Agreed :+1:
