### ISSUE TITLE
Setting custom minishift home directory fails

### ISSUE THREAD

**Issue by siamaksade** [minishift/minishift#1278]
When setting a custom home directory for minishift during `setup-cdk` on CDK 3.1, the setup fails:

```
$ minishift-cdk setup-cdk --minishift-home /Users/ssadeghi/.minishift-cdk-3-1

Setting up CDK 3 on host using '/Users/ssadeghi/.minishift-cdk-3-1' as Minishift's home directory
Copying minishift-rhel7.iso to '/Users/ssadeghi/.minishift-cdk-3-1/cache/iso/minishift-rhel7.iso'
Copying oc to '/Users/ssadeghi/.minishift-cdk-3-1/cache/oc/v3.5.5.31/oc'
Creating configuration file '/Users/ssadeghi/.minishift-cdk-3-1/config/config.json'
Creating marker file '/Users/ssadeghi/.minishift-cdk-3-1/cdk'
Default add-ons anyuid, admin-user, xpaas installed
Cannot write the Minishift configuration: Cannot create file /Users/ssadeghi/.minishift/config/config.json: open /Users/ssadeghi/.minishift/config/config.json: no such file or directory
```

**Comment by hferentschik** [comment]
This is really a CDK issue and should be reported here - https://issues.jboss.org/projects/CDK. Do you mind opening a JIRA ticket.

> Cannot write the Minishift configuration: Cannot create file /Users/ssadeghi/.minishift/config/config.json: open /Users/ssadeghi/.minishift/config/config.json: no such file or directory

This is a direct outcome of the `minishift-cdk setup-cdk --minishift-home /Users/ssadeghi/.minishift-cdk-3-1`?

**Comment by gbraad** [comment]
Off-topic: I do think we might have to use Minishift/CDK or CDK in that
case in the error message. WDYT?

**Comment by siamaksade** [comment]
@hferentschik Done https://issues.jboss.org/browse/CDK-162

Yes, that's the direct outcome of `setup-cdk`.

**Comment by budhrg** [comment]
Closing this issue as it is a CDK issue.
