### ISSUE TITLE
Reduce time used in CI by using a prebuilt document generation image

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1279]
At the moment we use a `docker build` for a container, which used on CI to generate some of the documentation. The process of docker pull and docker build takes 8+ mins (of which 45 secs is the pull). This can be optimized by using a prebuilt image.

Note: I have access to the `minishift` namespace on docker hub IIRC.

**Comment by budhrg** [comment]
I am unsure whether I understood you here properly. Could you elaborate more? What will the prebuilt image contain?

**Comment by gbraad** [comment]
The result of this Dockerfile: https://github.com/minishift/minishift/blob/master/docs/Dockerfile

so it just a `docker pull minishift/gendocs:latest` instead of waiting 7+ mins for a `docker build -t gendocs .`

**Comment by budhrg** [comment]
> docker build -t minishift/docs .

For me, I always need to pass `IMAGE_UID` explicitly due to error mentioned here https://docs.openshift.org/latest/minishift/contributing/writing-docs.html#building-docs-locally.

Let try to build the image `minishift/docs-base-image:latest` and see if it works smoothly without getting error as mentioned in https://docs.openshift.org/latest/minishift/contributing/writing-docs.html#building-docs-locally.

**Comment by gbraad** [comment]
The useradd can be done in a script as part of entrypoint or cmd.

Or at least this part should be layered on top of a base. The current process feels unnecessary taxing on CI time.

**Comment by hferentschik** [comment]
> so it just a docker pull minishift/gendocs:latest instead of waiting 7+ mins for a docker build -t gendocs .

+1. It means we need to put a bit of infrastructure in place as well. I would like to create a Minishift Docker Hub user which can host the image. Then we need a bit of infrastructure to build the image and put it there. Most likely you want even a dedicated repo for minishift/docs-base. 

Once we have this, we can simplify the Minishift Makefile to make use of minishift/docs-base.

Note, we probably have to put something into place to handle the UID, but that should not be too hard.

Last but not least, going ahead with a Minishift Docker Hub user, we can then also host the minibot image properly.

**Comment by gbraad** [comment]
> Minishift Docker Hub user

I created this, as I can see now, somewhere in Feb of this year.

To get a little bit of speed before dealing with the the UID issue, is to move the following lines into a specific Dockerfile which uses a base which does the installation. The installation of pandoc and dependencies takes about 6+ mins of the whole process.

https://github.com/minishift/minishift/blob/b67692e13b696d9c65979337d5e246ce3b0d6419/docs/Dockerfile#L24

**Comment by gbraad** [comment]
Merged with 76e922ebda54b6d1f3148be2c97c97a3e851b949

**Comment by hferentschik** [comment]
The current change to the Makefile introduces some inconsistent behaviour and a broken dependency chain for the _link_check_docs_ target. The Makefile should not change for this. Caching of the image can easily be achieved by doing a `docker pull minishift/docs` prior to running any docs target. This way caching works for any doc target. 

If we want to make a change to the Makefile I recommend changing the name of the image (for all targets). The long-term goal is to always use this image and never have to build it locally (for that we need to solve the UID issue). This should be the case for CI systems as well as developers. In foresight of this, maybe we should rename the image to something more telling like minishift/docs-build.

**Comment by hferentschik** [comment]
Merged via pull request #1542
