### ISSUE TITLE
Minishift should make OC binary available 

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#128]
Minishift should make OC binary available on the host so that user can start using  `OC` command line. Currently I had to download the OC binary and then I can start using it.

**Comment by jimmidyson** [comment]
Agreed. An `install-cli` or something, optionally invoked on first start if oc is not available in path. Can also check for updates to oc version if user wants.

Should default to same dir as minishift, but give option to user to choose different dir, recommending in PATH.

**Comment by rawlingsj** [comment]
FWIW we download the oc client in gofabric8 now, although the code used isn't the best as for now we're hardcoding the version.  The openshift cli tools release name includes the short git sha which means we need to figure that out.  Anyways code is here incase it's of any use:

https://github.com/fabric8io/gofabric8/blob/master/cmds/install.go#L242

Once its done (better) in minishift we can delegate to it from gofabric8 to install the CLI tool.

**Comment by budhrg** [comment]
@jimmidyson I think we have discussed here about that https://github.com/jimmidyson/minishift/issues/88

@LalatenduMohanty , we agreed that we should make it as part of default workflow too during minishift start.

**Comment by hferentschik** [comment]
I think we can close this one. The _oc_ binary is already cached now on the host as part of the "cluster up" work. The remaining work should be covered by issue #142 which will offer an _oc-env_.
