### ISSUE TITLE
Use named pipes on windows to communicate with Hyper-V image

### ISSUE THREAD

**Issue by lucastheisen** [minishift/minishift#1286]
My corporate VPN takes over all routes (including reserved ips: 10.x, 192.168.x, ...)  This means that if i try to access the openshift image using tcp the traffic gets rerouted over the VPN at which point the 10.x addresses no longer map to my VM switch and the communication fails.  Docker for Windows works because it uses npipe blackmagic for the docker commands (_and probably exposing ports from containers cause that works too..._).  I understand if this is not high priority, but it would be nice if minishift implemented the same approach.

_(I mentioned this in [this comment](https://github.com/minishift/minishift/issues/1256#issuecomment-323127164) and on the [mailing list](https://lists.minishift.io/archives/list/minishift@lists.minishift.io/thread/JHQ3PMP5ZR5ZGECEBYWKN7PY4N4BYUOP/?sort=date), but figured it would be worth opening its own issue for tracking purposes)_

**Comment by gbraad** [comment]
npipes = named pipes
