### ISSUE TITLE
Update "executing" steps in integration tests to accept commands with quotes

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1289]
Currently nearly all steps which execute a command have problem with commands containing quotes.

```golang
s.Step(`([^"]*) of command "minishift ([^"]*)" (is equal|is not equal) to "([^"]*)"$`,
commandReturnEquals)
```
Most commands for minishift do not use quotes, but there are some exceptions, for example `minishift openshift config set` where following argument must be a JSON, which uses quotes. And this will not be matched properly by adequate steps in test suite.

This can be probably fixed by using matching group and its surroundings similar to this: ```"minishift (.*)"```, which is already added in one place into tests by @hferentschik.

**Comment by hferentschik** [comment]
Merged via pull request #1290
