### ISSUE TITLE
Spike Provisioning of VM with a static IP address

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1293]
This would solve some of the problems we have with changing IP addresses and would be a workaround until we address the NAT issues (like providing IP by DHCP, which need external components)

```
PS> $env:HYPERV_VIRTUAL_SWITCH="DockerNAT"
PS> minishift start --vm-driver hyperv --ipaddress 10.0.75.128
```

Functions like `minishift ip` already work for this.

Note: we need to find a way to allow the IP address information to be injected... thoughts? Cloud-init like?

Related to: #418, #419

**Comment by gbraad** [comment]
[Data Exchange: Using key-value pairs to share information between the host and guest on Hyper-V](https://technet.microsoft.com/en-us/library/dn798287(v=ws.11).aspx)

**Comment by gbraad** [comment]
```powershell
$VmMgmt = Get-WmiObject -Namespace root\virtualization\v2 -Class Msvm_VirtualSystemManagementService  
$vm = Get-WmiObject -Namespace root\virtualization\v2 -Class Msvm_ComputerSystem -Filter {ElementName = 'minishift'}

$kvpDataItem = ([WMIClass][String]::Format("\\{0}\{1}:{2}", $VmMgmt.ClassPath.Server, $VmMgmt.ClassPath.NamespacePath, "Msvm_KvpExchangeDataItem")).CreateInstance()

$kvpDataItem.Name = "IpAddress"
$kvpDataItem.Data = "10.0.75.1"
$kvpDataItem.Source = 0

$VmMgmt.AddKvpItems($Vm, $kvpDataItem.PSBase.GetText(1))
```

```
$ cat .kvp_pool_0
```

**Comment by gbraad** [comment]
```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <fcntl.h>
#include "../include/linux/hyperv.h"
  
typedef struct kvp_record
{  
    unsigned char key [HV_KVP_EXCHANGE_MAX_KEY_SIZE];
    unsigned char value [HV_KVP_EXCHANGE_MAX_VALUE_SIZE];
} KVP_RECORD;
  
KVP_RECORD myRecords[200];
  
void KVPAcquireLock(int fd)
{  
    struct flock fl = {F_RDLCK, SEEK_SET, 0, 0, 0};
    fl.l_pid = getpid();

    if (-1 == fcntl(fd, F_SETLKW, &fl))
    {
        perror("fcntl lock");
        exit (-10);
    }
}
  
void KVPReleaseLock(int fd)
{
    struct flock fl = {F_UNLCK, SEEK_SET, 0, 0, 0};
    fl.l_pid = getpid();

    if (-1 == fcntl(fd, F_SETLK, &fl))
    {
        perror("fcntl unlock");
        exit (-20);
    }
}

int main (int argc, char **argv)
{
    char poolName[] = "/var/lib/hyperv/.kvp_pool_0";
    int   i;
    int   fd;
    int   bytesRead;
    int   numRecords;

    //
    // Open the specific pool file
    //
    fd = open(poolName, O_RDONLY);
    if (-1 == fd)
    {
        printf("Error: Unable to open pool file %s\n", poolName);
        exit (-30);
    }

    //
    // Read a bunch of records.  Note, this sample code
    // may not read all records (it will read a max of 200 records).
    //
    KVPAcquireLock(fd);
    bytesRead = read(fd, myRecords, sizeof(myRecords));
    KVPReleaseLock(fd);

    //
    // Compute the number of records read and display the data
    //
    numRecords = bytesRead / sizeof(struct kvp_record);
    printf("Number of records : %d\n", numRecords);

    for (i=0; i<numRecords; i++)
    {
        printf("  Key  : %s\n  Value: %s\n\n", myRecords[i].key, myRecords[i].value);
    }

    close(fd);

    return 0;
}
```

**Comment by gbraad** [comment]
```go
package main

import (
        "io"
        "fmt"
        "os"
        "bytes"
        "encoding/binary"
)

type kvp_record struct {
        Key   [MAX_KEY_SIZE]byte
        Value [MAX_VALUE_SIZE]byte
}

func (record *kvp_record) GetKey() string {
        return string(record.Key[:MAX_KEY_SIZE])
}

func (record *kvp_record) GetValue() string {
        return string(record.Value[:MAX_VALUE_SIZE])
}

const (
        MAX_KEY_SIZE   = 512
        MAX_VALUE_SIZE = 2048
)

func readNextBytes(file *os.File, number int) ([]byte, error) {
        bytes := make([]byte, number)

        _, err := file.Read(bytes)
        if err != nil {
                return nil, err
        }

        return bytes, nil
}

func main() {
        poolName := "/var/lib/hyperv/.kvp_pool_0"

        file, err := os.Open(poolName)
        if err != nil {
                panic("Oops")
        }

        var records []kvp_record

        for {
                record := kvp_record{}
                data, err := readNextBytes(file, MAX_KEY_SIZE + MAX_VALUE_SIZE)
                buffer := bytes.NewBuffer(data)
                err = binary.Read(buffer, binary.LittleEndian, &record)
                if err == io.EOF {
                        break
                }

                records = append(records, record)
        }

        for _, record := range records {
                fmt.Printf("Key: %s, Value: %s\n", record.GetKey(), record.GetValue())
        }
}
```

**Comment by gbraad** [comment]
Moved code to https://github.com/gbraad/go-hvkvp/

**Comment by hferentschik** [comment]
> minishift start --vm-driver hyperv --ipaddress 10.0.75.128

We need to think about the other drivers as well here. It would be nice to be able to provision with static IP for a hypervisors. This might or might not be possible. If not, something like '--ipaddress' might be better of as a driver (aka Hyper-V) specific option.

**Comment by gbraad** [comment]
exactly... I have been looking into alternatives

I would at first define this as a Hyper-V/Windows-only option, and also when experimental options is enabled. This was one of the reasons why I wanted to refactor the feature-toggle code.

**Comment by hferentschik** [comment]
>  What about Cloud-init

Can you describe what that would mean? I have not used this before, just heard the name. What would that mean? Which parts of the system would need to change? The Minishift code, the ISO? Both? Do we need to add more dependencies? 

> I would at first of all define this solution as a Hyper-V/Windows-only option, and also when experimental options are enabled. This was one of the reasons why I wanted to refactor the feature-toggle code.

Ok. Be careful so in case your code is making use of CGO. If we loose the ability to easily cross compile, we open a whole can of worms.

**Comment by gbraad** [comment]
This solution uses Go to create an executable that in our case is only for use within the VM anyway. But it can still be cross-compiled. This is only a Hyper-V solution, as none of the other hypervisors support a form of data exchange.

Cloud-init is a whole different story and I'd rather avoid this. This is used as an alternative to using a PXE like environment. It expects the VM to use a link-local address to retrieve meta-data on how to set up. This is how AWS (and OpenStack) provisioning their VMs.

Spike has been concluded. A new task is needed for the actual implementation...
