### ISSUE TITLE
Version unit test fails when building from tarball / when performing RPM build

### ISSUE THREAD

**Issue by marcindulak** [minishift/minishift#1300]
`make test` on Fedora 26 and minishift https://github.com/minishift/minishift/commit/0f658ea057b72cac35d6fb22cfa6bec28ef61079:

```
...
go-bindata  -prefix /root/rpmbuild/BUILD/minishift-0f658ea057b72cac35d6fb22cfa6bec28ef61079/src/github.com/minishift/minishift/addons -o /root/rpmbuild/BUILD/minishift-0f658ea057b72cac35d6fb22cfa6bec28ef61079/src/github.com/minishift/minishift/out/bindata/addon_assets.go -pkg bindata /root/rpmbuild/BUILD/minishift-0f658ea057b72cac35d6fb22cfa6bec28ef61079/src/github.com/minishift/minishift/addons/...
go install -pkgdir=/root/rpmbuild/BUILD/minishift-0f658ea057b72cac35d6fb22cfa6bec28ef61079/src/github.com/minishift/minishift/out/bindata -ldflags="-X github.com/minishift/minishift/pkg/version.minishiftVersion=1.4.1 -X github.com/minishift/minishift/pkg/version.b2dIsoVersion=v1.1.0 -X github.com/minishift/minishift/pkg/version.centOsIsoVersion=v1.1.0 -X github.com/minishift/minishift/pkg/version.openshiftVersion=v3.6.0 -X github.com/minishift/minishift/pkg/version.commitSha=" ./cmd/minishift
+ GO_BINDATA=/usr/bin/go-bindata
+ make test
fatal: Not a git repository (or any of the parent directories): .git
can't load package: package github.com/minishift/minishift/vendor/github.com/docker/docker/libnetwork-0f534354b813003a754606689722fe253101bc4e/src/github.com/docker/libnetwork: open /root/rpmbuild/BUILD/minishift-0f658ea057b72cac35d6fb22cfa6bec28ef61079/src/github.com/minishift/minishift/vendor/github.com/docker/docker/libnetwork-0f534354b813003a754606689722fe253101bc4e/src/github.com/docker/libnetwork/agent.go: no such file or directory
?   	github.com/minishift/minishift	[no test files]
?   	github.com/minishift/minishift/cmd/minishift	[no test files]
...
=== RUN   Test_version_output_has_correct_format
minishift v1.4.1+
--- FAIL: Test_version_output_has_correct_format (0.00s)
	version_test.go:41: Expected version string to match 'minishift v[0-9]+\.[0-9]+\.[0-9]+\+[a-z0-9]{7,8}
		' but 'minishift v1.4.1+
		' does not.
FAIL
exit status 1
FAIL	github.com/minishift/minishift/cmd/minishift/cmd	0.039s
...
```
It's the only failing test, any idea what could be causing this?

**Comment by gbraad** [comment]
This is likely due to the environment it runs in.

It responds with: `fatal: Not a git repository (or any of the parent directories): .git` and therefore the error makes sense, as the version should have been something like: `v1.4.1+0f658ea` (which is the version + the sha of the commit).

**Comment by gbraad** [comment]
Please provide more information about the RPM build environment. But take note, we depend on the git repository to provide information about the version.

**Comment by marcindulak** [comment]
I'm using https://github.com/marcindulak/minishift-rpm-centos7 for building of RPM, found this problem when updating to 1.4.1

Maybe It's not a good idea to rely on .git because the tarballs do not contain it: https://github.com/minishift/minishift/archive/v1.4.1.tar.gz
The static source files included in the tarball should uniquely define the version and be version control system agnostic. 

Maybe you could just drop +githash part in case .git is not found?

**Comment by hferentschik** [comment]
What do you mean, building from tarball? Which tarball and which RPMs. I am heavily opposed to fiddling with the build and calling whatever comes out of it Minishift. a big -1

**Comment by marcindulak** [comment]
https://github.com/minishift/minishift/archive/v1.4.1.tar.gz - it does not contain .git

I've added a note at https://github.com/marcindulak/minishift-rpm-centos7/ that the idea of minishift RPM has been abandoned.

**Comment by hferentschik** [comment]
Personally I would for sure not invest more time in this. Other people might have another opinion on that. However, if one wants to build an RPM, there must be other ways than trying to re-write the whole build script and building against other rpm dependencies. IMO this makes no sense whatsoever. The whole concept of "rpm-ifying" Go dependencies does not make sense to me. I also have issues with the major build modifications needed to make this happen. 

I am not an expert, so I am not sure what and what not is possible. I guess in the simplest form one can just package and install a ready build binary into an RPM, right? But for some reason it seems we want to achieve much more here.

**Comment by marcindulak** [comment]
Packaging of a pre-built minishift binary as RPM exists already https://github.com/LalatenduMohanty/cdk-minishift-rpm , but in order for an RPM to be included in a distribution (Fedora/EPEL) it needs to be built from source,
and must not download anything from the internet during the build.

Packaging minishift from source, using the native build method would be feasible if minishift bundled all its dependencies in the github repo, directly under the vendor directory (already mentioned here https://github.com/minishift/minishift/issues/828#issuecomment-324430455). Alternatively one cold prepare and maintain a separate vendor directory based on glide.lock. minishift's glide.lock and minishift-vendor repo would have to be kept in sync.

I see also now that the creation of minishift tarballs (https://github.com/minishift/minishift/archive/v1.4.1.tar.gz) would need to be modified to include .git

**Comment by gbraad** [comment]
Well, the githash is actually used as part of the version identification. This is why the test was added.

Let's see what we can find as an alternative approach...

**Comment by gbraad** [comment]
> Packaging of a pre-built minishift binary as RPM exists already https://github.com/LalatenduMohanty/cdk-minishift-rpm

prebuilt versions will include the version string as generated during the build process, and therefore have passed unit tests.

> I see also now that the creation of minishift tarballs (https://github.com/minishift/minishift/archive/v1.4.1.tar.gz) would need to be modified to include .git

These are created by GitHub as part of tagging a release. They are a dump of the workdirectory of that version and do not contain a .git. And this is also not something we can change.

**Comment by gbraad** [comment]
@marcindulak can you explain more about:

> Note: only Fedora RPMS available, no CentOS 7 yet!

It means this buildstream is used to create packages for Fedora? https://copr.fedorainfracloud.org/coprs/marcindulak/minishift/ If so, they follow the same debundling? In that case, we are unable to guarantee the working of the executable according to our tests.

This reminds me of:
![](http://gbraad.gitlab.io/presentation-bjgug-flatpak/img/answer.png)

Or as on [Installing pandoc]:
> Note, however, that versions in the repositories are often old.

I have nothing against packaging, when the libraries have interdependencies and create a cohesive whole, such as in the case of GNOME as a Desktop Environment, and offering the API or others to use. But in our case, we are delivering a static binary, mostly used by the user... who wants to use this without installing (Relocatable RPM is not the same). There is no re-use of the offered libraries, we purposely package our currated versions, etc. We already experience issues with the driver plugins being externally provided... I do not hope to see this with the main binary.

**Comment by hferentschik** [comment]
> Packaging of a pre-built minishift binary as RPM exists already https://github.com/LalatenduMohanty/cdk-minishift-rpm , but in order for an RPM to be included in a distribution (Fedora/EPEL) it needs to be built from source, and must not download anything from the internet during the build.

Ok, here are some ideas. As you say it needs to build from source. I understand that. So why don't you create your rpm fork of Minishift and track the main master branch. Then when you want to do a RPM release of Minishift x.y.z, you create a branch of the point from which you want to create the RPM (most likely a Minishift release tag). Then you call `make vendor`, get all dependencies and check them in. Now you have a branch from which you can build your Minishift RPM x.y.z from source (you still need to work out how to deal with build tools like go-bindata, but that's should be easy. If nothing else you check it in as part of the rpm release branch as well). Now you should be able to check this branch out and build without anything getting downloaded. Most importantly you are building Minishift. Changing the Makefile and changing dependencies, etc means you are not building Minsihift x.y.z anymore, but something else. Could this be a viable approach?

**Comment by hferentschik** [comment]
> But in our case, we are delivering a static binary, mostly used by the user... who wants to use this without installing (Relocatable RPM is not the same). There is no re-use of the offered libraries, we purposely package our currated versions

+1
