### ISSUE TITLE
Possible issue with systemd drop-in on restart

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1301]
In the CentOS CI we have issues https://github.com/minishift/minishift-centos-iso/issues/121 and as part of this, some tests have been tried to get debug info, According to the most recent run, (https://ci.centos.org/job/minishift-centos-iso-pr/149/consoleText) it seems there is an issue with Docker not starting correctly after restarting VM:

```
-- Logs begin at Wed 2017-08-23 11:36:55 EDT, end at Wed 2017-08-23 11:48:13 EDT. --
Aug 23 11:37:11 localhost.localdomain systemd[1]: Starting Docker Application Container Engine...
Aug 23 11:37:13 localhost.localdomain dockerd-current[1430]: time="2017-08-23T11:37:13.271287002-04:00" level=info msg="libcontainerd: new containerd process, pid: 2248"\nAug 23 11:37:14 minishift dockerd-current[1430]: time="2017-08-23T11:37:14.494271048-04:00" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section."
Aug 23 11:37:14 minishift dockerd-current[1430]: time="2017-08-23T11:37:14.591844353-04:00" level=warning msg="devmapper: Base device already exists and has filesystem xfs on it. User specified filesystem  will be ignored."
Aug 23 11:37:14 minishift dockerd-current[1430]: time="2017-08-23T11:37:14.949765467-04:00" level=fatal msg="Error starting daemon: layer does not exist"
Aug 23 11:37:15 minishift systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Aug 23 11:37:15 minishift systemd[1]: Failed to start Docker Application Container Engine.
Aug 23 11:37:15 minishift systemd[1]: Unit docker.service entered failed state.
Aug 23 11:37:15 minishift systemd[1]: docker.service failed.
```

And it seems on restart there is no `10-machine.conf` drop-in:
```
*******
Executing command : /root/payload/tests/../build/bin/minishift ssh -- cat /etc/systemd/system/docker.service.d/10-machine.conf
*******
Error: cat: /etc/systemd/system/docker.service.d/10-machine.conf: No such file or directory
Command failed: exit status 1
```

Could there be a problem with the provisioner when it concerns a restart?

**Comment by gbraad** [comment]
@praveenkumar WDYT?

**Comment by hferentschik** [comment]
Interesting.

**Comment by gbraad** [comment]
The dropin has not even been created yet, as the provisioner fails at:

https://github.com/minishift/minishift/blob/0f658c83baa5591c54a4519fff99c76c2b5181c2/pkg/minishift/provisioner/minishift_provisioner.go#L122

https://github.com/docker/machine/blob/39e78dff7df191501a034282366c82e4bcbfacdb/libmachine/provision/redhat.go#L121

and this happens with running Docker from the livecd setup

**Comment by praveenkumar** [comment]
@gbraad I will take a look into this. So is this reproducible for our development box also or only with CentOS CI?

**Comment by gbraad** [comment]
At the moment I am not able to reproduce this on my local dev box.

@hferentschik the milestone is incorrect. this is part of the current cycle as https://github.com/minishift/minishift-centos-iso/issues/121

**Comment by gbraad** [comment]
Error configuring authorization on host: Maximum number of retries (60) exceeded. Retrying.

**Comment by gbraad** [comment]
Closing this issue as more information is needed to determine the actual cause.
