### ISSUE TITLE
metrics and logging does not work with minishift community and oc enterprise

### ISSUE THREAD

**Issue by gordillo-ramon-redhat** [minishift/minishift#1302]
When using:

  - openshift oc enterprise version (v3.6.173.0.5)
  - minishift community (1.4.1) - to be able to use the service-catalog flag on enterprise

centos or rhel image (from cdk),

There is an error from ansible-container deployer about package prerequisites:

Log from metrics:
```
ok: [192.168.99.106] => {
    "ansible_facts": {
        "l_is_atomic": false
    }, 
    "changed": false
}
TASK [openshift_facts : set_fact] **********************************************
ok: [192.168.99.106] => {
    "ansible_facts": {
        "l_is_containerized": false, 
        "l_is_etcd_system_container": false, 
        "l_is_master_system_container": false, 
        "l_is_node_system_container": false, 
        "l_is_openvswitch_system_container": false
    }, 
    "changed": false
}
TASK [openshift_facts : set_fact] **********************************************
ok: [192.168.99.106] => {
    "ansible_facts": {
        "l_any_system_container": false
    }, 
    "changed": false
}
TASK [openshift_facts : set_fact] **********************************************
ok: [192.168.99.106] => {
    "ansible_facts": {
        "l_etcd_runtime": "host"
    }, 
    "changed": false
}
TASK [openshift_facts : Validate python version] *******************************
skipping: [192.168.99.106] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}
TASK [openshift_facts : Validate python version] *******************************
skipping: [192.168.99.106] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}
TASK [openshift_facts : Determine Atomic Host Docker Version] ******************
skipping: [192.168.99.106] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}
TASK [openshift_facts : assert] ************************************************
skipping: [192.168.99.106] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}
TASK [openshift_facts : Load variables] ****************************************
ok: [192.168.99.106] => (item=/usr/share/ansible/openshift-ansible/roles/openshift_facts/vars/default.yml) => {
    "ansible_facts": {
        "required_packages": [
            "iproute", 
            "python-dbus", 
            "PyYAML", 
            "yum-utils"
        ]
    }, 
    "item": "/usr/share/ansible/openshift-ansible/roles/openshift_facts/vars/default.yml"
}
TASK [openshift_facts : Ensure various deps are installed] *********************
failed: [192.168.99.106] (item=[u'iproute', u'python-dbus', u'PyYAML', u'yum-utils']) => {
    "changed": false, 
    "failed": true, 
    "item": [
        "iproute", 
        "python-dbus", 
        "PyYAML", 
        "yum-utils"
    ], 
    "rc": 126, 
    "results": [
        "No package matching 'iproute' found available, installed or updated"
    ]
}
MSG:
No package matching 'iproute' found available, installed or updated
PLAY RECAP *********************************************************************
192.168.99.106             : ok=8    changed=0    unreachable=0    failed=1   
localhost                  : ok=8    changed=0    unreachable=0    failed=0
```

**Comment by hferentschik** [comment]
Might be related to #510

**Comment by gordillo-ramon-redhat** [comment]
I don't see the relationship. From my PoV, it seems like ansible scripts for installing enterprise metrics, checks some packages that are not installed in iso image on minishift.

**Comment by gbraad** [comment]
That would be a very unwanted situation, as it would mean it dictates the requirements we have to provide to deploy a containerized app? If that is the case, I believe they should provide a means to have these dependencies offered in a system-like container.

Our image for CentOS is already quite hefty... 

  * iproute (installed)
  * python-dbus (**NOT** installed)
  * PyYAML (**NOT** installed)
  * yum-utils (**NOT** installed)

**Comment by gbraad** [comment]
I also question the use of `yum-utils`, as this indicates they are performing download or management actions on the host? If so, this is a no-go... #355

**Comment by hferentschik** [comment]
> I don't see the relationship. From my PoV, it seems like ansible scripts for installing enterprise metrics, checks some packages that are not installed in iso image on minishift.

The Ansible scripts run against the Origin containers. It is OpenShift which needs configuration in order to enable logging/metrics. The VM provides the environment to run the Origin container. 

Could you clarify a bit more what you are doing. What is the exact command you are executing and you seem to mix and match pieces from Minishift and CDK. What are the steps to reproduce this?

**Comment by gbraad** [comment]
Using `minishift start --iso-url centos --metrics`:

```
Starting OpenShift using openshift/origin:v3.6.0 ...
Pulling image openshift/origin:v3.6.0
...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.176:8443

The metrics service is available at:
    https://hawkular-metrics-openshift-infra.192.168.42.176.nip.io/hawkular/metrics

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin
```

**Comment by gordillo-ramon-redhat** [comment]
@gbraad, the issue comes with OCP, not with origin.
@hferentschik to reproduce the issue:
- Install CDK 3.1.
- Set up cdk:
`minishift setup-cdk`
- Install minishift community.
- change .minishift/cache/oc/v3.6.0 with the enterprise release (3.6.173.0.5)

Start it using
`MINISHIFT_ENABLE_EXPERIMENTAL=y ./minishift start --skip-registration --service-catalog --metrics --show-libmachine-logs -v 5`

**Comment by gbraad** [comment]
Unsupported scenario, as you are intermixing both CDK and upstream Minishift to achieve something that is also using an as-of-now 'unsupported' featured, `--service-catalog`.

I am pretty much inclined to mark this as invalid.

**Comment by hferentschik** [comment]
> I am pretty much inclined to mark this as invalid.

+1, this is not something we support.

**Comment by gordillo-ramon-redhat** [comment]
¿How can I test a OCP 3.6 (not origin) with minishift/CDK?

**Comment by gbraad** [comment]
A new version will be released not long from now.

**Comment by hferentschik** [comment]
https://issues.jboss.org/browse/CDK-160?focusedCommentId=13451203&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13451203

**Comment by gbraad** [comment]
Didn't want to suggest a workaround, but yeah... that is possible... but he would still miss the `--service-catalog` option, and that is why this mixing exercise was done.

**Comment by gordillo-ramon-redhat** [comment]
Exactly. I did the same as @hferentschik suggested at first moment, then I realised I could not use the service-catalog flag.

**Comment by gordillo-ramon-redhat** [comment]
It happens exactly the same with "oc cluster up" on v3.6.173.0.5, and it has nothing to do with packages installed in the host machine.

**Comment by gordillo-ramon-redhat** [comment]
Still having the same issue with CDK 3.1.1

**Comment by gbraad** [comment]
This is an issue with OpenShift. Do you have a BZ?

**Comment by noushi** [comment]
I'm experiencing the same issue with:
- minishift v1.3.1+a2d3799
- CDK v3.1.1-1

CDK downloaded from https://developers.redhat.com/products/cdk/download/ .

tried both with:
```
minishift start --metrics --logging
```
and 
```
minishift start --metrics --logging --iso-url centos
```

**Comment by karstengresch** [comment]
Hint: I also have 

`localhost:RH karsten$ minishift version
minishift v1.3.1+a2d3799
CDK v3.1.1-1`

both on macOS and F25. 

F25 works fine (both --metrics and --service-catalog), macOS not. Also changed oc (macOS) to v3.6.173.0.5, v3.6.173.0.21 and v3.6.173.0.49 - no success (i.e. 'unknown flag: --service-catalog').

@noushi - on which OS did you test?

**Comment by noushi** [comment]
@karstengresch I have Ubuntu 16.04.03 LTS .

**Comment by gbraad** [comment]
`--service-catalog` is still Tech Preview, and is therefore only available behind an experimental flag (which needs to be set to enable). The documentation is very explicit about this.

**Comment by karstengresch** [comment]
@gbraad - thanks, I just had forgotten I'd set

`export MINISHIFT_ENABLE_EXPERIMENTAL=y`

(as per https://docs.openshift.org/latest/minishift/using/experimental-features.html )

This is why it worked on my Linux machine, no relation to the underlying OS.

@noushi, @gordillo-ramon-redhat - does this solve your problem, too?

**Comment by noushi** [comment]
@karstengresch @gbraad , I'm not using the service-catalog option, just metrics and logging.
Do I still need to enable experimental features?
Thanks

**Comment by gbraad** [comment]
`--metrics` and `--logging` are not experimental, however, the images for this version of OCE seem to have an issue with the Ansible installation step. I am not sure what the conclusion of the discussion around this was. Can you try with another `--ocp-tag` ?

**Comment by noushi** [comment]
@gbraad okay, so I've tried with : 
```
minishift start --metrics --logging --ocp-tag v3.5.5.31.36-4
```

And it's the same issue.

I've found this BZ : https://bugzilla.redhat.com/show_bug.cgi?id=1492562 
seems to be the same issue, and it's not yet fixed.

Which brings me to this question: what is the most recent of OCP that is known to work with metrics and logging?

**Comment by noushi** [comment]
addendum:
In the [CDK release notes ***and known issues***](https://access.redhat.com/documentation/en-us/red_hat_container_development_kit/3.1/pdf/release_notes_and_known_issues/Red_Hat_Container_Development_Kit-3.1-Release_Notes_and_Known_Issues-en-US.pdf) pdf, it is apparently a "known issue" but the proposed fix (using `--ocp-tag v3.6` ) fails miserably, the openshift can't even install:
```
...
   Starting OpenShift using container 'origin'
FAIL
   Error: could not start OpenShift container "origin"
   Details:
     No log available from "origin" container

Error during 'cluster up' execution: Error starting the cluster.
```

**Comment by jorgemoralespou** [comment]
Does minishift support the ocp-tag, or it's a CDK only flag?

Have you tried plain minishift upstream to see if metrics/logging works?

**Comment by gbraad** [comment]
`--ocp-tag` is CDK-only

**Comment by noushi** [comment]
Even openshift.com has broken metrics, the same haproxy router message shows here: https://metrics.starter-ca-central-1.openshift.com/hawkular/metrics

@jorgemoralespou unfortunately, I currently can't test upstream minishift, but seeing the same error on openshift.com, it is probable that the error is in openshift itself.
