### ISSUE TITLE
Spike on image caching via host folders 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1303]
One alternative to the caching of images to the current import/export approach (either via plain `docker [load|save]` or via containers/image) could be to use host volumes. 

The idea is to mount a directory, e.g. $MINISHIFT_HOME/cache/images, into the VM at the location where Docker stores its images. This way the images get stored directly on the host. A VM can be deleted and a new one created with all the images directly in place. No time consuming import/export needed. 

AFAICR this used to work in earlier versions of Minishift, but stopped working. There might be permission problems or issues with the selected Docker driver (loopback vs overlay, etc). Also, it would be at least for now an issue to fully automate this, since we have no generic (configuration free) way to mount host folders. This might change so with a working solution for #317 (host folders via sshfs).

I think there are several steps we can take here:

* Investigate whether this still works and if not what the problem is
* Assuming one can do it in a consistent way, we could document the required steps to do it manually (configure a samba share x, create a hostfolder using this share mounting against y, ...)
* If we can get it to work manually, I am pretty sure we can then via sshfs based host folders mounts, make it a fully automated solution.

In the end this could be a replacement for current image caching and issue #952. Or maybe one can offer both approaches?

**Comment by LalatenduMohanty** [comment]
@hferentschik Do we still need this. IMO we can close this as we are using oci tools now in #1589

**Comment by hferentschik** [comment]
> Do we still need this. IMO we can close this as we are using oci tools now in #1123

No, this is a completely different approach which would by far be more effective.

**Comment by gbraad** [comment]
For this, we need to make sure permissions are honoured. This will therefore likely not work with all types of host folder mounts (let's say CIFS). Hopefully, the spike will reveal this...

**Comment by LalatenduMohanty** [comment]
Not planning to open this as e do not any plans around this issue.
