### ISSUE TITLE
Configuration flag --registry-mirror is not working with minishift start

### ISSUE THREAD

**Issue by stararks** [minishift/minishift#1308]
I am trying to start minishift with pulling origin images from my-local-registry. Seems it is still looking for index.docker.io

###
```
$ minishift version
minishift v1.4.1+0f658ea
```

```
$ minishift start --registry-mirror http://my-local-registry:5000
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    12 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ...
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   routing-suffix ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
Pulling image openshift/origin:v3.6.0
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v3.6.0 image ...
   Pulling image openshift/origin:v3.6.0
FAIL
   Error: error pulling Docker image openshift/origin:v3.6.0
   Caused By:
     Error: Error while pulling image: Get https://index.docker.io/v1/repositories/openshift/origin/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: no such host
Error during 'cluster up' execution: Error starting the cluster.
```

**Comment by gbraad** [comment]
You likely have connectivity issues from your VM. As you can see, the pre-flight tests failed:

  * `Retrieving http://minishift.io/index.html ...` failed.
  * `Pinging 8.8.8.8 ...` => `VM is unable to ping external host`

Please check connectivity. I tentatively mark this as `invalid`.

**Comment by stararks** [comment]
I am running minishift in a network not able to access internet. So the error of below is expected.
Retrieving http://minishift.io/index.html ... failed.
Pinging 8.8.8.8 ... => VM is unable to ping external host

Before start minishift, the minishift-b2d.iso is in .minishift/iso, those origin images were pushed to the mirror registry.

**Comment by gbraad** [comment]
You can see that the docker daemon responds with:

`lookup index.docker.io on 10.0.2.3:53: no such host`

This is why I also doubt the registry is reachable or connectivity works as expected.

**Comment by stararks** [comment]
I did more test with minishift ssh to login the vm.
1. the default command to start dockerd is
dockerd -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --label provider=virtualbox --insecure-registry my-local-registry:5000 --insecure-registry 172.30.0.0/16 **--registry-mirror http://my-local-registry:5000** --tlsverify --tlscacert=/var/lib/boot2docker/ca.pem --tlscert=/var/lib/boot2docker/server.pem --tlskey=/var/lib/boot2docker/server-key.pem -s aufs

2. pull image alpine, got same error as below
docker@minishift:~$ docker pull alpine
Using default tag: latest
Pulling repository docker.io/library/alpine
Error while pulling image: Get https://index.docker.io/v1/repositories/library/alpine/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: no such host


3. However, restart docker daemon with above command, but replace --registry-mirror http://my-local-registry:5000 with "--registry-mirror=http://my-local-registry:5000". My local registry is the first one looked up this time as below:

root@minishift:/mnt/sda1/var/lib/boot2docker# docker pull alpine
Using default tag: latest
DEBU[0017] Calling GET /v1.24/info
DEBU[0017] Calling POST /v1.24/images/create?fromImage=alpine&tag=latest
**DEBU[0017] Trying to pull alpine from http://my-local-registry:5000/ v2**
ERRO[0017] Attempting next endpoint for pull after error: manifest unknown: manifest unknown
DEBU[0017] Trying to pull alpine from https://registry-1.docker.io v2
WARN[0017] Error getting v2 registry: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: no such host
ERRO[0017] Attempting next endpoint for pull after error: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: no such host
DEBU[0017] Trying to pull alpine from https://index.docker.io v1
DEBU[0017] hostDir: /etc/docker/certs.d/docker.io
DEBU[0017] [registry] Calling GET https://index.docker.io/v1/repositories/library/alpine/images
Pulling repository docker.io/library/alpine
ERRO[0017] Not continuing with pull after error: Error while pulling image: Get https://index.docker.io/v1/repositories/library/alpine/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: no such host
Error while pulling image: Get https://index.docker.io/v1/repositories/library/alpine/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: no such host

**Comment by stararks** [comment]
$ minishift config set check-network-ping-host my-local-registry
$ minishift config set check-network-http-host http://my-local-registry:5000/v2/
# more config flag set here
$ minishift start 
- check-network-http-host: http://my-local-registry:5000/v2/
- check-network-ping-host: my-local-registry
- cpus                 : 2
- insecure-registry    : [my-local-registry:5000]
- memory               : 12288
- registry-mirror      : [http://my-local-registry:5000]
- vm-driver            : virtualbox
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    12 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   **Pinging my-local-registry ... OK**
-- Checking HTTP connectivity from the VM ...
   **Retrieving http://my-local-registry:5000/v2/ ... OK**
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ...
   routing-suffix ... OK
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
Pulling image openshift/origin:v3.6.0
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v3.6.0 image ...
   Pulling image openshift/origin:v3.6.0
FAIL
   Error: error pulling Docker image openshift/origin:v3.6.0
   Caused By:
     Error: Error while pulling image: Get https://index.docker.io/v1/repositories/openshift/origin/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: no such host

**Comment by gbraad** [comment]
I looked at the code and tried this, and as you also conclude, this sets the values for the docker daemon as expected. Trying to setup a similar environment... but I do notice:

```
DEBU[0017] Trying to pull alpine from http://my-local-registry:5000/ v2
ERRO[0017] Attempting next endpoint for pull after error: manifest unknown: manifest unknown
```

This would mean that the image can not be found in the registry, and likely this is why it will try to resolve index.docker.io

**Comment by stararks** [comment]
I am also looking the issue of manifest unknown. No idea so far. 
Pull image with full name without such issue. e.g. docker pull my-registry:5000/alpine

**Comment by gbraad** [comment]
So did the OpenShift origin container pull?
```
$ docker pull my-registry:5000/openshift/origin:3.6.0
```

**Comment by gbraad** [comment]
Also looking into 3. as you mentioned:

```
--registry-mirror http://my-local-registry:5000
```

or
```
--registry-mirror=http://my-local-registry:5000
```

This should not matter, and if this is an issue, it means it is wrong in libmachine.

**Comment by gbraad** [comment]
Setting up a local registry mirror works for me:

```
$ minishift config view
- insecure-registry    : [10.0.21.42:5000]
- registry-mirror      : [http://10.0.21.42:5000]
$ curl http://10.0.21.42:5000/v2/_catalog
{"repositories":[]}
$ minishift start --iso-url centos
$ curl http://10.0.21.42:5000/v2/_catalog
{"repositories":["openshift/origin","openshift/origin-pod"]}
$ minishift start --iso-url centos
```

This surely pulled the image from the local registry

**Comment by stararks** [comment]
Thanks gbraad. 
I find the reason. It is because I also running a DNS sever (dnsmasq) on local computer (to parse nip.io with internet access) . 
It works after modified vm with command: 
VBoxManage modifyvm minishift --natdnshostresolver1 on

I tried to enable natdnshostresolver1 while start minishift and create vm. but it it not a valid config flag. it is not supported by minishift so far, right? (I will close issue)

**Comment by gbraad** [comment]
`--natdnshostresolve1 on` runs DNS proxy mode for VirtualBox, but not sure ehat you mean with minishift supporting this? You mean to enable virtualbox to start with this? If so, no... all of these settings would need to be specified/implemented by us to be passed to the driver. This should be dealt with by issue: #305

**Comment by stararks** [comment]
I meant enable natdnshostresolve1 by minishift config set. 
It is connivence that minishift can pass this flag to driver, otherwise we have to stop the vm, set the flag by "VBoxManage modifyvm minishift ..." and restart mv.

It is great for minishift supports set flags that needs restart vm.
