### ISSUE TITLE
Path error on Windows when running with --virtual-driver=virtualbox

### ISSUE THREAD

**Issue by rhuss** [minishift/minishift#131]
Disabling Hyper-V and using Virtualbox works, but the following error is printed on the console:

```
minishift.exe start --vm-driver virtualbox
Starting local OpenShift cluster...
E1024 19:15:04.219958    5528 start.go:92] Error starting host: Error creating. Error creating machine: Error in driver during machine creation: Checking if hardware virtualization is enabled failed: open C:\Users\Roland\.minishift\machines\minishift\minishift\Logs\VBox.log: The system cannot find the path specified.. Retrying.
oc is now configured to use the cluster.
Run this command to use the cluster:
oc login --username=admin --password=admin
```

In fact, after the retry the log files was created at the given location. Wonder whether this is a race condition ?

**Comment by hferentschik** [comment]
I have switched multiple times between Hyper-V and VirtualBox providers now and have not seen this issue. @rhuss Could you maybe try with the latest Minishift release? Also what are the steps to re-produce this?

**Comment by hferentschik** [comment]
Closing this issue. I cannot re-produce this with the latest version of Minishift.
