### ISSUE TITLE
Improve test coverage in profile.feature

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1310]
This is a follow up issue for #126, respectively for PR #1304.

As discussed before there probably will be a basic integration test as part of the PR. But for further proper testing we will need to cover this new functionality in more detail.

**Comment by gbraad** [comment]
Would it be possible for you to show/track the scenario you have envisioned to test this?

**Comment by agajdosi** [comment]
@gbraad Not yet, but as soon as this will have any progress I will update it first here to consult. I am still not well familiar with these new changes.

**Comment by LalatenduMohanty** [comment]
@agajdosi I have updated #126 with some use cases and will add more of them going forward. I think that should give a fair idea about what the feature is going to do .

**Comment by LalatenduMohanty** [comment]
@agajdosi One of the things we should test is each profile can run with different config (i.e. different RAM, CPU, disk etc).

**Comment by LalatenduMohanty** [comment]
Resolved via #1692
