### ISSUE TITLE
Add a minimum Minishift version for executing add-ons

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1313]
Add the ability to set a minimum minishift version with which an addon will work with.  When addind/extending capabilities for addons, if not specified, the addons can break.

e.g. in minishift 1.5.0 a multiline for descriptions has been provided. If the addons are written with the new spec, they might not install any longer in previous minishift versions.

Also, remember, the lifecycle of minishift is much shorter than the one of CDK, so I might want to install new addons in a CDK version that does not support the feature yet.

**Comment by gbraad** [comment]
In relation to #877, I strongly suggest to have refactored the Minisift config and state. This is very specific Minishift information, that is only valid when `oc` has deployed. Therefore it is state.

**Comment by LalatenduMohanty** [comment]
Resolved via #2678
