### ISSUE TITLE
Add an # openshift-version to addons

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1314]
Provide the ability to specify te minimum openshift-version an addon will support. Now that origin versioning is aligned with ocp versioning, we can align the features.

e.g. I might write an addon that modifies openshift functionality or that uses a new functionality present in a specific version. I want to avoid users to try the addon if it will not work or if it will break their environment.

Possibly adding a minimum version required, and "maybe" a maximum version required, for an addon that provides a functionality that at some point is covered by the core platform, so no longer required for greater versions.

**Comment by gbraad** [comment]
Isn't this a duplicate of #1134

**Comment by jorgemoralespou** [comment]
Yes. Closing.
