### ISSUE TITLE
minishift start stuck at Waiting for SSH to be available

### ISSUE THREAD

**Issue by HouJaI** [minishift/minishift#1315]
i am tried deleting the entire .minishift folder and re-initiate `minishift start --show-libmachine-logs`

i can see the VM is started properly in Hyper-V. but then it got stuck at "Waiting for SSH to be available..."

I have checked all the network connection settings and all are in place e.g. i can browse the internet etc ...

I am using the wireless connection for this.

please help. I managed to get passed this stage last night though ...

```
C:\>minishift start --show-libmachine-logs
-- Checking if Hyper-V driver is configured ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Starting Minishift VM ... (minishift) Waiting for host to start...
/ Waiting for SSH to be available...
```

**Comment by gbraad** [comment]
Can you provide more details about your setup? This is not the full startup log ...
Please make sure you use an External Virtual Switch: https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html#hyper-v-driver

**Comment by HouJaI** [comment]
Hi apologies, i just included -v 5 and following is the error:

SSH binary not found, using native Go implementation
&{{{<nil> 0 [] [] []} docker [0x8329b0] <nil>  []} 192.168.43.81 22 <nil> <nil>}
About to run SSH command:
exit 0
- Error dialing TCP: dial tcp 192.168.43.81:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
| Error dialing TCP: dial tcp 192.168.43.81:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
\ Error dialing TCP: dial tcp 192.168.43.81:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
/ Error dialing TCP: dial tcp 192.168.43.81:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Yes, i am using the Hyper-V as external network.

**Comment by gbraad** [comment]
SSH is not a necessity to be available, as Minishift has an embedded SSH client. As you can see:

The connection to `192.168.43.8` times out: "connection attempt failed because the connected party did not properly respond after a period of time".

This means something is not configured as expected. I need more information to help you. Mostly networking information and how you setup the virtual switch.

**Comment by HouJaI** [comment]
I open up Hyper-V as admin. and then in the Virtual Switch Manager, I created a Virtual Switch by just selecting the Connection Type as External Network. I have selected the "Intel(R) Dual Band Wireless-AC 7260 #3". Provided a name "Minishift" for it and close. I have also added in "HYPERV_VIRTUAL_SWITCH" environment variable with "Minishift".

After i perform the first minishift start. I can see in my "Network Connections" folder, my wireless network connection is bridged with a "microsoft network adapter multiplexor driver". in the properties of this connection, i am able to see the Hyper-V Extensible Virtual Switch checkbox is checked.

The Virtual Machine is started and i can see in the boottodocker, the same ip address is being assigned, 192.168.43.81/24.

**Comment by gbraad** [comment]
Can you try to ping from B2D to your gateway?
Can you try to ping the guest from the host?
Are you running a VPN on your host?

**Comment by HouJaI** [comment]
1. can 
![image](https://user-images.githubusercontent.com/29627120/29803105-319d5bea-8cac-11e7-9652-7212c7106501.png)

2. tried to ping from pc to b2d: not reachable
![image](https://user-images.githubusercontent.com/29627120/29803189-ccc5ee66-8cac-11e7-967e-f9f2efc85891.png)

3. try to ping from b2d to pc: not reachable
![image](https://user-images.githubusercontent.com/29627120/29803223-f729a79c-8cac-11e7-8aab-972312188493.png)

no i am not using VPN, i am connecting to the internet using my phone's hotspot.

**Comment by gbraad** [comment]
Next step is to get a routing table, but I can already tell this is not related to Minishift, but a network misconfiguration. Just like a VPN, some of the hotspot setups are aggressive routing, and therefore do not really act like a proper hub/switch setup. This surely happens when a VPN or adblock is used on the phone, as in that case, none of the requests from the host end up on the guest, but gets routed over the phone to ... well... the VPN. Can you provide `traceroute` output or routing tables, such as `route print` ?

I have given several demos using a similar setup. Android phone acts like a hub on 4G, presentation laptop connect to phone for the VGA out, demo laptop with Hyper-V connected to the phone. Connecting demo laptop using Remote desktop to the demo laptop. And this does work for me... I do, however, always use the CentOS image (but this shouldn't matter).

I suggest you to test it with a slightly simpler setup first.

**Comment by gbraad** [comment]
Tentatively marked as invalid as network configuration is not part of Minishift

**Comment by HouJaI** [comment]
thanks for the response so far, appreciate your help here as i am pretty new to this. do direct me to some reference if possible.

1. routing table from b2d:
![image](https://user-images.githubusercontent.com/29627120/29803619-d18e8644-8caf-11e7-97dc-6904c2933c36.png)


2. routing table from local pc:
![image](https://user-images.githubusercontent.com/29627120/29803646-0025ef42-8cb0-11e7-9fdb-e466d3c7febd.png)

**Comment by gbraad** [comment]
It is likely your phone who prevents the routing to happen; only `traceroute` or `tracert` will tell.

As mentioned, try to get this working first with a wireless accesspoint or router instead. You have a very potential point of failure in your setup, that is hard to debug: the hotspot option on your phone.

**Comment by HouJaI** [comment]
hi gb, managed to fix the issue by clearing up all the rogue connections. but now, i am getting the following error.

-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
FAIL
   Error: cannot access master readiness URL https://192.168.43.254:8443/healthz/ready
   Details:
     No log available from "origin" container

   Caused By:
     Error: Get https://192.168.43.254:8443/healthz/ready: read tcp 192.168.43.16:50016->192.168.43.254:8443: wsarecv: An existing connection was forcibly closed by the remote host.
Error during 'cluster up' execution: Error starting the cluster.

actually i have used the same laptop for minishift and was ok. and due to some network issue, i have to clean up the connections, hence, the initial issue above. 

is there anything that i need to clean up for this?

**Comment by gbraad** [comment]
this still feels like a networking issue... the `oc cluster up` command tried to verify if the master is reachable and it seems the healthcheck is not reachable.

**Comment by HouJaI** [comment]
please close this, already found out the issues and fixed it. apparently too many rogue connection was in my hidden network adapter... i have login as admin into device manager and cleared up everything and refresh to only have wifi and ethernet connection. and then start from scratch to rebuild minishift.

previously was using virtual box and hence all the rogue connections. so suggest to fully cleanup all the rogue connections before starting anything on minishift. thanks again for the help!

**Comment by gbraad** [comment]
You mean, half-open connections... is in fact your network got saturated and did not have enough bandwidth or ports available?. I am happy it works now...

**Comment by HouJaI** [comment]
![image](https://user-images.githubusercontent.com/29627120/29852353-32b71c12-8d6c-11e7-88ab-131f6e4096a5.png)
in device manager i noticed there are multiple same adapters in my case, e.g. i have up to 6 Microsoft Network Adapter Multiplexor Driver previously, and hence i believe that where the problem is. and its caused by multiple time of install, uninstalling minishift and hyper-V that created all these duplicates. after cleaning up all the connections, its working fine now.

**Comment by gbraad** [comment]
Once in a while I have to do the following:

Windows Settings -> Network & Internet -> Status -> "Network reset" (At the bottom) -> "Reset now"

![image](https://user-images.githubusercontent.com/1894/29852651-ddbe17f4-8d6d-11e7-815f-70b429428485.png)

The "Network reset" functionality causes all Wifi-passwords to be dropped, but also the Virtual networking stack, bridges, etc. Sometimes I ended up in a situation where only half of the stuff worked. Especially when used with VPN Software or virtual network adapters, e.g. Zerotier.
