### ISSUE TITLE
Create uninstall add-on command

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1317]
Follow up of #1129 

`minishift addon uninstall` should remove the add-on from the add-ons folder (opposite of install). It also removes add-on detail from config file. 

@hferentschik @jorgemoralespou  What should we do if add-on is enabled? Should we ask user for confirmation or just uninstall it?

**Comment by hferentschik** [comment]
> What should we do if add-on is enabled? Should we ask user for confirmation or just uninstall it?

I don't think this is required. uninstalling is not really a destructive operations per se. You can quite easily recover. The less user interaction of this type we have the better. Wherever we add such a y/n question we will always have to provide an option to force the uninstall. See also issue #1320.

**Comment by hferentschik** [comment]
Merged via pull request #1321
