### ISSUE TITLE
Have an option to force answer of minishift prompts

### ISSUE THREAD

**Issue by odockal** [minishift/minishift#1320]
I have in mind this. When doing some automation in scripts that operates with minishift, it would be willing to have possibility that would confirm/decline user interaction to minishift's command prompts, ie. minishift delete could ask user whether it is alright to continue the process, even if unregistration of ISO image failed. (Current Minishift VM is registered, but unregistration failed. Do you want to continue [y/N]?).

Would you consider to add such option/flag to minishift commands? Thanks!

**Comment by hferentschik** [comment]
This is pretty much a given. The aim is to provide options in the form '--force' wherever there is a user interaction. For example issue #405, if we add the prompt for confirmation to delete the VM, I expect that at the same time we add an option to force the deletion. The aim is always to be able to script the minishift commands as well. 

There is also issue #959 which is about non interactive host folder configuration. This is a missing feature and we should implement it asap. 

Apart from this @odockal, do you have a concrete example where there is no way to bypass the user interaction? Then we should open a concrete issue for this. TBH, I am not quite sure what to do with this issue atm. There seems to be no actual action which needs to be taken, or?

**Comment by odockal** [comment]
hm, I see, so there might be opened a new issue because for example minishift delete command's help says that: "--force Forces the deletion of the VM specific files in MINISHIFT_HOME." which is not clear about that the failed unregistration will be skipped. And using this flag is not working for me. So I create new issue, right?

**Comment by hferentschik** [comment]
>  so there might be opened a new issue

+1, you seem to have a specific issue.

> because for example minishift delete command's help says that: "--force Forces the deletion of the VM specific files in MINISHIFT_HOME." which is not clear about that the failed unregistration will be skipped. And using this flag is not working for me. 

'--force' in this case means that the VM files gets deleted even if a running VM could not be stopped. Maybe this needs to be clarified. However, we need a bit more context in terms of what exactly is not working for you.

> So I create new issue, right?

+1

I close this issue in the meantime.
