### ISSUE TITLE
Add integration test for add-on command

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1322]
We should test addons command in more depth, we are missing some subcommands and edge cases. Also we should focus on failures, if minishift is able handle or recover from installation of totally wrong addon - for example just a random text file or broken addon file etc.

Also we should keep an eye on #1321 and test for `minishift addons uninstall` which is incoming into master.

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/pull/1385/
