### ISSUE TITLE
Add script to create PR for brew cask for minishift

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1324]
Automate the process of sending the PR to update brew cask for minishift.

For 1.5.0, I manually updated with [this PR](https://github.com/caskroom/homebrew-cask/pull/38073). 

#### Update

Now, we will create a script file which will help to create PR for brew cask.

**Comment by budhrg** [comment]
Tasks:
- [x] Clone repository https://github.com/caskroom/homebrew-cask/ into `minishift-bot` user space
- [ ] Update `centos_ci.sh` script
- [ ] Test with sending PR to my fork `budhrg/homebrew-cask`

**Comment by budhrg** [comment]
Sending a PR to update cask include following steps:
1. Edit cask file
   $ vim minishift.rb
2. Install new cask locally
   $ brew cask install minishift.rb
3. Audit Check
   $ brew cask audit minishift.rb --download
4. Style Check
   $ brew cask style minishift.rb

Step 1 is complete. However, to proceed with step 2 onwards, one need to have `brew cask` command available. 
I had tried with [Linuxbrew/brew](https://github.com/Linuxbrew/brew) but failed in install cask
```
$ brew install cask
Error: Unsupported special dependency :perl
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/budhram/.linuxbrew/Library/Homebrew/dependency_collector.rb:123:in `parse_symbol_spec'
/home/budhram/.linuxbrew/Library/Homebrew/compat/dependency_collector.rb:17:in `parse_symbol_spec'
...
```
or
```
brew cask install minishift.rb
==> Tapping caskroom/cask
Cloning into '/home/budhram/.linuxbrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3819, done.
remote: Compressing objects: 100% (3798/3798), done.
remote: Total 3819 (delta 39), reused 504 (delta 17), pack-reused 0
Receiving objects: 100% (3819/3819), 1.30 MiB | 458.00 KiB/s, done.
Resolving deltas: 100% (39/39), done.
Tapped 0 formulae (3,828 files, 4.2M)
Error: Unknown command: cask
```

I am just not sure whether it would be good idea to send the PR without verifying at sender's end.

Any thoughts @gbraad @LalatenduMohanty @praveenkumar ?

**Comment by budhrg** [comment]
Might possible through Circle CI but at the moment it seems not possible through any of Linux based CI.

**Comment by praveenkumar** [comment]
@budhrg Let's discuss if this is possible by circleci then what steps we need to add.
