### ISSUE TITLE
Using Hyperkit as a driver on macOS

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1326]
Minikube recently added an initial driver implementation for using Hyperkit: https://github.com/kubernetes/minikube/commit/caa8a540e6920c646441503ff919f6dc307e6930

**Comment by praveenkumar** [comment]
Same kind of effort from xhyve driver side also https://github.com/zchee/docker-machine-driver-xhyve/pull/189

**Comment by budhrg** [comment]
Still need investigation

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/commit/d314d539836105846e3963687a99c13b0def41a8 #2071
