### ISSUE TITLE
Remove outdated documentation on installing minishift beta in macOS

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1329]
The documentation on [latest beta](https://docs.openshift.org/latest/minishift/getting-started/installing.html#homebrew-latest-install) is invalid now.

```
$ brew cask install minishift-beta
Error: Cask 'minishift-beta' is unavailable: No Cask with this name exists.
Error: Install incomplete.
```

**Comment by LalatenduMohanty** [comment]
@budhrg Anyidea why it is failing? IMO it should install the old beta version but should not fail.

**Comment by gbraad** [comment]
it has been removed a while back
https://github.com/caskroom/homebrew-versions/pull/4051
