### ISSUE TITLE
Setup CI pipeline for macOS platform

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1334]
With macOS machine available, if we could setup CI pipeline then we can run PR builds there which will run integration tests.

**Comment by LalatenduMohanty** [comment]
@budhrg The machine should be accessible to community members. If the machine is behind a company network then we need make sure it is possible from IT security point of view.

**Comment by budhrg** [comment]
> If the machine is behind a company network then we need make sure it is possible from IT security point of view.

Good point.

**Comment by agajdosi** [comment]
Heard from @LalatenduMohanty today that there was a project planned by OSAS team, called "community cage", which was meant to make community access to selected machines owned by Red Hat. I can ask on their mailing list, probably after my PTO, if this project is around and if we could use it. If so then we have at least 1 macOS machine which could be used.

**Comment by budhrg** [comment]
Closing it for now.
