### ISSUE TITLE
Erroneous behaviour on Windows 10 Hyper-V when VTx is not available

### ISSUE THREAD

**Issue by chrisfalter** [minishift/minishift#1335]
[The latest Minishift documentation](https://docs.openshift.org/latest/minishift/getting-started/installing.html) states:

"To use Minishift with Hyper-V ensure that, after you install Hyper-V, you also add a Virtual Switch using the Hyper-V Manager. For specific configuration steps see the Setting Up the Driver Plug-in section."

I performed the following setup steps on my Windows 10 Pro laptop:
* Enabled Hyper-V
* In Hyper-V Manager, configured an external virtual switch named "ExternalVSwitch"
* Added an environment variable HYPERV_VIRTUAL_SWITCH=ExternalVSwitch
* Downloaded minishift-1.5.0-windows-amd64.zip and extracted to C:\minishift folder
* Added C:\minishift to my PATH environment variable.

After opening Powershell prompt, I typed the command `minishift start` with the following result:

`FAIL E0831 17:42:14.943140    7968 start.go:344] Error starting the VM: Error starting stopped host: Unable to start the
 VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minishift --type headless failed:
VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole`

I will attempt to do the "recommended" configuration with Virtualbox. However, the current documentation implies that Hyper-V is also supported. While a fix to the underlying issue would be nice, fixing the documentation in the meantime would be really helpful. It would help minishift users on Windows not waste perfectly good afternoons, as I did. :/

Thanks in advance!

**Comment by chrisfalter** [comment]
A couple of clarifications:
* the Powershell command to start minishift was `minishift start --vm-driver=hyperv`
* Complete console output was as follows:

`-- Checking if Hyper-V driver is configured ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Starting Minishift VM ... \ FAIL E0831 18:08:19.258852   16208 start.go:344] Error starting the VM: Error starting st
VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:01.464503 Power up failed (vrc=VERR_VMX_NO_VMX, rc=E_FAIL (0X80004005)). Retrying.`

This was repeated a few times (starting at "FAIL") before the command terminated.

**Comment by gbraad** [comment]
You still have virtualbox installed. Uninstall or use the correct driver.
Both hypervisors can not be used at the same time.

Please enable virtualisation is extension from your computer's BIOS and
ensure Hyperk is installed from Windows features.

On Friday, September 1, 2017, Christopher Falter <notifications@github.com>
wrote:
> A couple of clarifications:
>
> the Powershell command to start minishift was minishift start
--vm-driver=hyperv
> Complete console output was as follows:
>
> `-- Checking if Hyper-V driver is configured ... OK
> -- Starting local OpenShift cluster using 'hyperv' hypervisor ...
> -- Starting Minishift VM ... \ FAIL E0831 18:08:19.258852 16208
start.go:344] Error starting the VM: Error starting st
> VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
> VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component
ConsoleWrap, interface IConsole
>
> Details: 00:00:01.464503 Power up failed (vrc=VERR_VMX_NO_VMX, rc=E_FAIL
(0X80004005)). Retrying.`
>
> This was repeated a few times (starting at "FAIL") before the command
terminated.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/m_KmGVArO5ARZ1Gh8OCsip34ZzDSkpsMca9dbNGTNKmuxMvINO_jBjQ9cVTpge4PCzScL3yAotEjvMgFAEkvB3ZJ5D0Qj5tcE2TEi7nTothmE4IlFatjuh_kGIxGxxRH3k6nxEuDmsOuGGxNI3l56X9-nJNp2A=s0-d-e1-ft#https://github.com/notifications/beacon/AAAHZuDSZy0eRJVTyqwLFj46egBCukRVks5sdy9ngaJpZM4PJdlq.gif
>

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by gbraad** [comment]
> VT-x is not available (VERR_VMX_NO_VMX)

Please ensure VT-x is enabled. Check the instructions in your BIOS or
system manual how to enable.


On Friday, September 1, 2017, Christopher Falter <notifications@github.com>
wrote:
> A couple of clarifications:
>
> the Powershell command to start minishift was minishift start
--vm-driver=hyperv
> Complete console output was as follows:
>
> `-- Checking if Hyper-V driver is configured ... OK
> -- Starting local OpenShift cluster using 'hyperv' hypervisor ...
> -- Starting Minishift VM ... \ FAIL E0831 18:08:19.258852 16208
start.go:344] Error starting the VM: Error starting st
> VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
> VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component
ConsoleWrap, interface IConsole
>
> Details: 00:00:01.464503 Power up failed (vrc=VERR_VMX_NO_VMX, rc=E_FAIL
(0X80004005)). Retrying.`
>
> This was repeated a few times (starting at "FAIL") before the command
terminated.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/m_KmGVArO5ARZ1Gh8OCsip34ZzDSkpsMca9dbNGTNKmuxMvINO_jBjQ9cVTpge4PCzScL3yAotEjvMgFAEkvB3ZJ5D0Qj5tcE2TEi7nTothmE4IlFatjuh_kGIxGxxRH3k6nxEuDmsOuGGxNI3l56X9-nJNp2A=s0-d-e1-ft#https://github.com/notifications/beacon/AAAHZuDSZy0eRJVTyqwLFj46egBCukRVks5sdy9ngaJpZM4PJdlq.gif
>

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by budhrg** [comment]
> Please ensure VT-x is enabled.

It is sad to tell people like this instead of being documented as part of installation documentation. Even minikube has documented in its [requirement list](https://github.com/kubernetes/minikube#requirements).

I feel this is required for users who are trying first time any virtualization stuff.

**Comment by gbraad** [comment]
It used to have the same structure, but some things regarded as 'generally known' might have been remved prematurely: The current [Prequisites](https://github.com/minishift/minishift/blob/master/docs/source/getting-started/installing.adoc#prerequisites) do not mention the need of Virtual Extension (VTx/Vanderpool Technology) in any form.

**Comment by LalatenduMohanty** [comment]
@chrisfalter Are you still having this issue? Did the suggestions work for you?

**Comment by chrisfalter** [comment]
The suggestions did not work for me, and I eventually had my laptop re-imaged. I started over from scratch, but encountered new issues. See #1381 and #1382. Since documentation issue #1337 has been created, there is no reason to keep this issue open. I am therefore closing it.

My thanks to all who responded. :)
