### ISSUE TITLE
Split ISO creation out into its own repository

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#134]
The ISO creation is really a orthogonal problem to the minishift CLI. Moving forward we want to offer multiple pluggable ISO images to work with minishift. Having dedicated repositories for the various ISO will create a clear split. 

Suggested repo name for the default ISO - _minishift-iso_.

**Comment by budhrg** [comment]
> Moving forward we want to offer multiple pluggable ISO images to work with minishift

+1 and name is also fine.

**Comment by hferentschik** [comment]
After discussing a bit with @LalatenduMohanty around names, my vote would be atm for something like _minishift-b2d-iso_. Then we move our current CentOS based ISO to the minishift org as _minishift-centos-iso_ and hopefully some time down the road (after the technical issues on the Atomic side have been solved) we can add a _minishift-atomic-iso_ which will be our ultimate goal.

**Comment by LalatenduMohanty** [comment]
> minishift-b2d-iso

+1. sounds good.

**Comment by budhrg** [comment]
> minishift-b2d-iso

What is 'minishift-b2d-iso'?

**Comment by LalatenduMohanty** [comment]
@budhrg minishift-b2d-iso is for the boot2docker ISO

**Comment by praveenkumar** [comment]
I just created repo `minishift-b2d-iso` and we can start moving deploy part to that repo and add Makefile and README and also remove those bits from minishift once we complete this switch.

**Comment by LalatenduMohanty** [comment]
@praveenkumar I am on it. I was trying to understand how Viper config can be changed to make minishift-centos-iso or minishift-rhel-iso default.

**Comment by praveenkumar** [comment]
@LalatenduMohanty I am not sure why you need that right now to separate the repo, minishift-rhel-iso as default we need downstream and that something we will take care. For upstream once we have that separation we just need to update the ISO url to fetch by default image, IIRC.

- https://github.com/minishift/minishift/blob/7b93c2c80a2421d09cdce17b9c437f01ef42cf52/pkg/minikube/constants/constants.go#L61

**Comment by LalatenduMohanty** [comment]
I think there are two things we need to fix. 

1.  At this point of time the boot2docker ISO used in minishift is strongly tied with the version of minishift [1] [2] , when we break the ISO in to separate repository we need to fix it, so that it can be configured (through Viper) to use a particular release of the ISO or other ISOs. 

2. Along with making the ISO version independent of minishift version, we need to see how we can create a generic code to include RHEL ISO for CDK as  for RHEL ISO we will not have a github release version.


[1] https://github.com/minishift/minishift/blob/master/Makefile#L65
[2] https://github.com/minishift/minishift/blob/master/Makefile#L65

**Comment by LalatenduMohanty** [comment]
For RHEL ISO we should be able to override the version logic in getting an ISO and we should be able to use a hard coded path or --iso-url path.

**Comment by hferentschik** [comment]
So, I think what you are after is here - https://github.com/minishift/minishift/blob/9f871ac6984a8ed522a71522f17c1357617b37b7/cmd/minikube/cmd/root.go#L140

This code initializes the file based config. The config file used is `~/.minishift/config/config.json`. However, it is empty per default and you cannot just add any odd parameter.

Once you have a running minishift instance try:

    minishift config set WantUpdateNotification false

And then check the content of the config file. You end up with something like:

    {
        "WantUpdateNotification": false
    } 

AFAICT, there are only a couple of options supported. The plan would be to make sure to make 'ISO URL' also a configurable item with a specified default. This allows to downstream provide a config file pointing to pre-installed ISO on disk. 

There are several code changes which need to happen once the code is extracted.

**Comment by hferentschik** [comment]
I think so, we are jumping ahead of ourselves. Let's get https://github.com/minishift/minishift-b2d-iso into shape and do an alpha release on it. Then we have something we can actually work with and play with the various alternatives.

**Comment by LalatenduMohanty** [comment]
> minishift config set WantUpdateNotification false

@hferentschik thanks for the information. Yes, I am working on minishift-b2d-iso first.

**Comment by LalatenduMohanty** [comment]
Fixed with https://github.com/minishift/minishift/pull/286
