### ISSUE TITLE
Default add-ons install message should not come for all commands

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#1342]
```
$ make integration GODOG_OPTS="-tags command -format pretty"
go install -pkgdir=/home/amit/go/src/github.com/minishift/minishift/out/bindata -ldflags="-X github.com/minishift/minishift/pkg/version.minishiftVersion=1.5.0 -X github.com/minishift/minishift/pkg/version.b2dIsoVersion=v1.1.0 -X github.com/minishift/minishift/pkg/version.centOsIsoVersion=v1.1.0 -X github.com/minishift/minishift/pkg/version.openshiftVersion=v3.6.0 -X github.com/minishift/minishift/pkg/version.commitSha=0e75c4ec" ./cmd/minishift
mkdir -p /home/amit/go/src/github.com/minishift/minishift/out/integration-test
go test -timeout 3600s github.com/minishift/minishift/test/integration --tags=integration -v -args --test-dir /home/amit/go/src/github.com/minishift/minishift/out/integration-test --binary /home/amit/go/bin/minishift -tags command -format pretty
Test run using Boot2Docker iso image.
Keeping Minishift cache directory '/home/amit/go/src/github.com/minishift/minishift/out/integration-test/cache' for test run.
Log successfully started, logging into: /home/amit/go/src/github.com/minishift/minishift/out/integration-test/integration.log
Running Integration test in: /home/amit/go/src/github.com/minishift/minishift/out/integration-test
Using binary: /home/amit/go/bin/minishift
Feature: Basic
  As a user I can perform basic operations of Minishift and OpenShift

Feature: Openshift commands
  Commands "minishift openshift [sub-command]" are used for interaction with Openshift
  cluster in VM provided by Minishift.

Feature: Version command
  Command "minishift version" shows version of minishift binary.

  Scenario: User can get information about version of Minishift                  # features/cmd-version.feature:5
    When executing "minishift version" succeeds                                  # integration_test.go:652 -> github.com/minishift/minishift/test/integration.executingMinishiftCommandSucceedsOrFails
    Then stdout should match "^minishift v[0-9]\.[0-9]\.[0-9]\+[a-z0-9]{7,8}\n$" # integration_test.go:630 -> github.com/minishift/minishift/test/integration.commandReturnShouldMatchRegex
    Output did not match. Expected: '^minishift v[0-9]\.[0-9]\.[0-9]\+[a-z0-9]{7,8}\n$', Actual: '-- Installing default add-ons ... OK
minishift v1.5.0+0e75c4ec
'

Feature: Cool Store
  In order to test Minishift under load
  I need to setup a test environment
  Using CentOS and 4G of memory
  After which I will import image streams
  Finally I will deploy the Cool Store

Feature: Flags
  As a user I can perform advanced operations
  such as starting Minishift with optional features

Feature: Provision an older major release
  As a user I can provision an older major version of minishift

Feature: Minishift can run behind proxy
  As a user I can use Minishift behind a proxy.
  INFO: Code behind this feature will start a proxy server in background
  on port 8181 and will try to get IP of host machine automatically
  to set MINISHIFT_HTTP_PROXY for this feature only.
  However one can override port number or set IP manually if needed.
  To use custom port number run this test with environmental variable
  INTEGRATION_PROXY_CUSTOM_PORT.
  To use custom IP address please set INTEGRATION_PROXY_CUSTOM_IP
  environmental variable.

--- Failed scenarios:

    features/cmd-version.feature:7

1 scenarios (1 failed)
2 steps (1 passed, 1 failed)
67.708103ms
testing: warning: no tests to run
PASS
exit status 1
FAIL    github.com/minishift/minishift/test/integration 0.085s
make: *** [Makefile:176: integration] Error 1
12:46 $
```

**Comment by amitkrout** [comment]
Here the problem is minishift version returns version and one extra add-ons installation line in the first run. 
```
$ ./minishift version
-- Installing default add-ons ... OK
minishift v1.5.0+0e75c4ec
$
```
On second run on same binary returns the proper result.
```
$ ./minishift version
minishift v1.5.0+0e75c4ec
$ 
```
This case ```$ make integration GODOG_OPTS="-tags command -format pretty"``` creates each time the compiled binary and runs the ```minishift version``` command . So the result doesn't match with the actual minishift version output i.e ```minishift v1.5.0+0e75c4ec```.

I have checked it on master branch.

**Comment by LalatenduMohanty** [comment]
@amitkrout I think you are seeing this because https://github.com/minishift/minishift/issues/1203 got fixed. The add-ons behavior is same some time but you did not see this in your testing before. We should change the test https://github.com/minishift/minishift/blob/master/test/integration/features/cmd-version.feature to accommodate this

**Comment by LalatenduMohanty** [comment]
@amitkrout If you want keep this to track the change required we should change the description of the issue else we can close this.

**Comment by amitkrout** [comment]
@LalatenduMohanty 
> We should change the test https://github.com/minishift/minishift/blob/master/test/integration/features/cmd-version.feature to accommodate this

Ack

> If you want keep this to track the change required we should change the description of the issue else we can close this

I am unsure which description you are saying. IMO rather closing this let the same issue for tracking the integration test changes

**Comment by gbraad** [comment]
Version command should not trigger an update of add-ons. This is a
side-effect

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by amitkrout** [comment]
> We should change the test https://github.com/minishift/minishift/blob/master/test/integration/features/cmd-version.feature to accommodate this

Have some more confusion on this. If scenario [step](https://github.com/minishift/minishift/blob/master/test/integration/features/cmd-version.feature#L7) grep the particular minishift version string some thing like this way ```Then stdout should conatin "regexp"``` then we are just hiding/ignoring the other string which might not be expected. IMO instead of changing the integration module we should fix the version command.

**Comment by LalatenduMohanty** [comment]
@amitkrout @agajdosi you do not see this in the vanilla path i.e. with `minishift start`. 

@amitkrout you are seeing this because you have deleted the addons directory after `minishift start`. Can you please confirm?

**Comment by amitkrout** [comment]
@LalatenduMohanty Thanks for clarifying vanilla path over irc i.e.  ```minishift start without changing .minishift directory``` 

> you do not see this in the vanilla path i.e. with ```minishift start```.

True

> you are seeing this because you have deleted the addons directory after minishift start. Can you please confirm?

With a clean setup i am able to reproduce it on fresh download of minishift binary (1.3.0, 1.3.1, 1.4.0 and 1.5.0) in first run. Then after in the consecutive run i am unable to reproduce it. As you mentioned above, same problem can be found if .minishift dir is deleted after any consecutive run.

```
$ ./minishift version
-- Installing default add-ons ... OK
minishift v1.3.1+27ec32a
$ ./minishift version
minishift v1.3.1+27ec32a
```
```
$ rm -rf ~/.minishift/
$ ./minishift version
-- Installing default add-ons ... OK
minishift v1.3.1+27ec32a
$
```

**Comment by LalatenduMohanty** [comment]
We need find out if there can be anyway we can change the behaviour of `-- Installing default add-ons ... OK`. At this point this happens in root.go hence it shows up for every command. 

@amitkrout please file another issue to change the test and lets track this issue for changing the behavior of `minishift version`.

**Comment by LalatenduMohanty** [comment]
I think we should move the `-- Installing default add-ons ... OK`  to `minishift start`and then it is better as user can anytime install the add-on with `minishift addon install --defaults` . @budhrg do you remeber why we have kept the code in root.go and not in start.go?

**Comment by gbraad** [comment]
This seems to be related to the fact to trigger an update of addons IIRC

**Comment by LalatenduMohanty** [comment]
@gbraad Thats a different code responsible for handling the update scenario

**Comment by gbraad** [comment]
Merged with 349f4084b706e55e96cc536e441b161a7c6c2f87

**Comment by LalatenduMohanty** [comment]
Re-opening the issue as per discussion we want to keep the installing/un-packing of add-ons in PersistentPreRun to support the following use-case and to keep consistency around `minishift update` command + updation of default add-ons.

```
$ minishift add-on enable anyuid
$ minishift start
```

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/pull/1489
