### ISSUE TITLE
Abstract the code to create progress dots

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1348]
As per the fix of #1277 in the PR #1340 , we missed extracting the code to create progress dots here https://github.com/minishift/minishift/blob/master/cmd/minishift/cmd/start.go#L300.

Probably, good to extract this into `pkg/util/utils.go` along with functions like `StartProgressDots`.

**Comment by gbraad** [comment]
Merged with 9aa240d (renamed package `progress` to `progressdots`)
