### ISSUE TITLE
minishift doesn't start with an alternate public-hostname/routing-suffix

### ISSUE THREAD

**Issue by chmouel** [minishift/minishift#1351]
A new issue opened following comment on this bug https://github.com/minishift/minishift/issues/1011#issuecomment-327459567

When trying to use the switch : 

    minishift start --public-hostname localhost --routing-suffix 127.0.0.1.nip.io --vm-driver=kvm --memory=6144 --cpus=4 --disk-size=50g

minishift will error at the end with : 

    Error during post cluster up configuration: Unable to add sudoer role

It seems that the command line switch cause the issue : 

    --public-hostname localhost --routing-suffix 127.0.0.1.nip.io

This used to work but I don't really know until which version

**Comment by praveenkumar** [comment]
@chmouel what is the use case of using `localhost` as public-hostname for minishift? We might need to put an documentation around it.

**Comment by chmouel** [comment]
I get a fairly limited laptop so I deploy minishift on another laptop and use 

```
ssh -L 8443:localhost:8443  remotelaptop
```

to forward the connection. 

And connect with https://localhost:8443 from my locallaptop

**Comment by praveenkumar** [comment]
> I get a fairly limited laptop so I deploy minishift on another laptop and use

@chmouel Ack, I will try to get a patch in for it. Thanks for clarification.

**Comment by praveenkumar** [comment]
@csrwng I need some insight about this. Below is explanation about what we do currently, let me know if we are missing something here.

1. We try to extract configuration from the `~/.kube/config` file and make it part of local to instance.

 - https://github.com/minishift/minishift/blob/master/pkg/minishift/clusterup/clusterup.go#L115
  - https://github.com/minishift/minishift/blob/master/pkg/minikube/kubeconfig/config.go

Generated file not works when we use public-hostname with minishift but it works without it.

**Comment by csrwng** [comment]
The code in cluster up that appends to ~/.kube/config (and logs in) is here:
https://github.com/openshift/origin/blob/master/pkg/oc/bootstrap/docker/openshift/login.go

Does it not work with any public hostname or just 'localhost' ?

**Comment by praveenkumar** [comment]
@chmouel  Can you please try out http://artifacts.ci.centos.org/minishift/minishift/pr/1372/ binary and see if your issue #1351 resolved?

**Comment by chmouel** [comment]
This works perfecty thanks : 

after downloading it, i ran it with the public-hostname=localhost : 

![image](https://user-images.githubusercontent.com/98980/30390071-2d87191e-98b5-11e7-87a2-d08f191e2d58.png)

I ran a tunnel to that otherlaptop where installed from my desktop

> ssh -L 8443:192.168.42.152:8443 otherlaptop

and I can now access to the console from my desktop on localhost : 

![image](https://user-images.githubusercontent.com/98980/30390173-74a64b08-98b5-11e7-8494-a417f995f46c.png)

Thanks!

**Comment by praveenkumar** [comment]
Fixed by #1372

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/pull/1372/

**Comment by vmvmpvm** [comment]
Does this this fully work?

I get below error (after cluster up), I believe it is in the call to ocRunner.AddClientContext where myvmip:8443 is being used instead of the configured public-hostname.

```
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://localhost:8443/console


error: dial tcp myvmip:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. - verify you have provided the correct host and port and that the server is currently running.
Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: Unable to login to cluster
```

Using minishift version 1.34.2. My expectation is for all calls to cluster to use localhost:8443 instead of myvmip:8443.
