### ISSUE TITLE
VM startup fails using Gow

### ISSUE THREAD

**Issue by rhdoslande** [minishift/minishift#1354]
Gow was put on this machine by the Red Hat Corporate Standard Build (CSB) for Windows 7.

`C:\Program Files (x86)\Gow\bin\ssh.bat`

It causes an issue with invoking SSH

That results in the VM not starting, and the command times out with errors:
```
0907 09:49:02.791900    3456 start.go:282] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
```

**Comment by gbraad** [comment]
Gow uses a batch file called ssh.bat to wrap plink. https://github.com/bmatzelle/gow/blob/master/bin/ssh.bat Somehow this results in an error when ssh is used for provisioning.

**Comment by gbraad** [comment]
```
Getting to WaitForSSH function...
(minishift) Calling .GetSSHHostname
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o Lo
gLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0
.0.1 -o IdentitiesOnly=yes -i C:\Users\doslande\.minishift\machines\minishift\id_rsa -p 22] C:\Program Files (
x86)\Gow\bin\ssh.bat <nil>}
About to run SSH command:
exit 0
SSH cmd err, output: exit status 1: 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
 
Error getting ssh command 'exit 0' : ssh command error:
command : exit 0
err     : exit status 1
output  : 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by gbraad** [comment]
Closing, as this is a known issue and will/can not be solved on Minishift's side.

**Comment by manjrem** [comment]
(minishift) DBG | Waiting for VM "minishift" to power on...
(minishift) DBG | VM "minishift" has been successfully started.
(minishift) DBG | }
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | Checking vm logs: C:\Users\mmanjrek\.minishift\machines\minishift\minishift\Logs\VBox.log
(minishift) DBG | Getting to WaitForSSH function...
(minishift) DBG | Using SSH client type: external
(minishift) DBG | &{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@127.0.0.1 -o IdentitiesOnly=yes -i C:\Users\mmanjrek\.minishift\machines\minishift\id_rsa -p 1790] C:\Program Files (x86)\Gow\bin\ssh.bat <nil>}
(minishift) DBG | About to run SSH command:
(minishift) DBG | exit 0
(minishift) DBG | SSH cmd err, output: exit status 1: 'C:\Program' is not recognized as an internal or external command,
(minishift) DBG | operable program or batch file.
(minishift) DBG |
(minishift) DBG | Error getting ssh command 'exit 0' : ssh command error:
(minishift) DBG | command : exit 0
(minishift) DBG | err     : exit status 1
(minishift) DBG | output  : 'C:\Program' is not recognized as an internal or external command,
(minishift) DBG | operable program or batch file.
(minishift) DBG |

Getting the same error !!!

**Comment by gbraad** [comment]
@manjrem remove Gow from your path. It is an awful hack anyway, as `plink` is not compatible with the actual `ssh` command.

**Comment by gbraad** [comment]
@LalatenduMohanty @robin-owen document this?

**Comment by robin-owen** [comment]
@gbraad @LalatenduMohanty Documenting this in the troubleshooting section makes sense to me.
