### ISSUE TITLE
minishift start ignores changes to --vm-driver option after starting with a different driver

### ISSUE THREAD

**Issue by gtcode** [minishift/minishift#1359]
Hi,

On macos, I installed the latest `1.5` minishift, as well as the latest supported `xhyve` vm driver per the Minishift install docs.   For the installation and for my first `minishift start` command, it used the default virtualbox driver, which added a VM to my Virtualbox host by the name of `minishift`.

Once `minishift start` worked with the default virtualbox, and after `minishift stop`, I attempted to start using `minishift start --vm-driver=xhyve`.  However this still invoked the virtualbox instance, which seems to be a bug.

This workaround worked successfully:
```
minishift delete --clear-cache --force
minishift start --vm-driver=xhyve
```

Sorry if this is a known issue or expected behavior, I could not find any similar ticket.  Although, the behavior does seem unexpected, intuitively.

**Comment by gtcode** [comment]
The issue occurs in the other direction.  Starting from scratch using xhyve, and then stopping the cluster, then starting again with `minishift start --vm-driver=virtualbox` shows the "using virtualbox" output but proceeds to silently start with xhyve.  Once again, deleting and clearing cache works around the issue.

**Comment by gbraad** [comment]
This is a known issue and is related to #179 The VM driver as stored in the machine profile will be used.
Can you include a startup log with more detail?

**Comment by gbraad** [comment]
>  it used the default virtualbox driver

This is not the default, unless you have VirtualBox installed. In wich Docker Machine (libmachine) will use this as a fallback. this is behaviour we probably can not avoid.

However, usually having two hypervisors in use is not recommended due to stability issues.
