### ISSUE TITLE
Wrong URL in warning when using system commands in minishift ssh

### ISSUE THREAD

**Issue by jeffmaury** [minishift/minishift#1362]
When using a system command (like yum for example), Minishift will display the following warning message:
`--------------------------------------------------------------------------------------------------------
                                                                                                        
Installing additional packages on the root filesystem might exceed the allocated overlay size and lock t
he Minishift VM. Proceed with the installation at your own risk.                                        
For more information, see https://docs.openshift.org/latest/minishift/using/troubleshooting.html#root-filesystem-exceeds-overlay-size                                                                           
--------------------------------------------------------------------------------------------------------
                                                                                                        
Are you sure you want to continue? [y/N]                                                                `

The URL is wrong, it should be https://docs.openshift.org/latest/minishift/troubleshooting/troubleshooting-misc.html#root-filesystem-exceeds-overlay-size

**Comment by gbraad** [comment]
Easy fix. Link should be:

https://docs.openshift.org/latest/minishift/troubleshooting/troubleshooting-misc.html#root-filesystem-exceeds-overlay-size

Issue is actually in the CentOS ISO

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by praveenkumar** [comment]
Created https://github.com/minishift/minishift-centos-iso/issues/145 from CentOS iso side. Closing it from this repo.
