### ISSUE TITLE
shortnames broke case-sensitive iso-urls

### ISSUE THREAD

**Issue by hguerrero** [minishift/minishift#1363]
Issue #1033 added a new function where it changes the parameter for iso-url to all lowercase. This breaks when file path is case sensitive.
```
func determineIsoUrl(iso string) string {
	iso = strings.ToLower(iso)  <<<--------------
	isoNotSpecified := ""

	switch iso {
	case minishiftConstants.B2dIsoAlias, isoNotSpecified:
		iso = constants.DefaultB2dIsoUrl
	case minishiftConstants.CentOsIsoAlias:
		iso = constants.DefaultCentOsIsoUrl
	default:
		if !(govalidator.IsURL(iso) || strings.HasPrefix(iso, "file:")) {
			fmt.Println()
			atexit.ExitWithMessage(1, unsupportedIsoUrlFormat)
		}
	}

	return iso <<<-------
}
```

**Comment by gbraad** [comment]
Ouch. To Lower() should only be used to compare, but not to return/alter the given URL

**Comment by rahulbajaj0509** [comment]
I would like to work on this bug :)

**Comment by budhrg** [comment]
> I would like to work on this bug :)

@rahulbajaj0509 Thanks for showing great interest in resolving this bug. However, its PR is ready https://github.com/minishift/minishift/pull/1393. You can work on other issues :smile:

**Comment by gbraad** [comment]
A fix has been provided, but only tests are remaining, and he is working on this.

**Comment by gbraad** [comment]
Thanks for the contribution @anjannath. @hguerrero, check the release once available. If the problem persists, please reopen this issue.
