### ISSUE TITLE
hostfolders need to add extra flags to cifs mount for selinux labels

### ISSUE THREAD

**Issue by gordillo-ramon-redhat** [minishift/minishift#1364]
Using RHEL as a minishift iso (CDK), when mounting a hostfolder, the following command is executed (example):
```
sudo mount -t cifs //192.168.99.1/rgordill/Clients/minishift/persistent /var/lib/persistent-on-hosts -o username=rgordill,password=minishift
```
With that, selinux labels are as follows:

`system_u:object_r:cifs_t:s0      persistent-on-hosts/`

If we want to use this share to persist the configuration, we get the following error:
```
   Creating initial OpenShift configuration
FAIL
   Error: could not copy OpenShift configuration
   Caused By:
     Error: Error response from daemon: {"message":"SELinux relabeling of /var/lib/persistent-on-hosts/openshift.local.config is not allowed: \"operation not supported\""}
```
That is because docker cannot relabel the selinux policy. But if we mount with:
```
sudo mount -t cifs //192.168.99.1/rgordill/Clients/minishift/persistent /var/lib/persistent-on-hosts -o username=rgordill,password=minishift,context=system_u:object_r:svirt_sandbox_file_t:s0
```
Then, the context is correct:

`system_u:object_r:svirt_sandbox_file_t:s0 persistent-on-hosts/`

Is it possible to add some extra flags, like "context" to hostfolders, to pass them to cifs mount?

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift/pull/1416
