### ISSUE TITLE
hosthome seems not to be mount in some linux with virtualbox

### ISSUE THREAD

**Issue by gordillo-ramon-redhat** [minishift/minishift#1366]
Apparently, hosthome is added as a auto shared folder in B2D (host = fedora), but it is not mounted on 
startup, even if it is configured so in virtualbox.

If I do a minishift ssh into b2d, it avoids the mount until "/hosthome" is created.

Could it be because B2D Guest Additions is 5.1.8 r111374, but virtualbox is latest (5.1.26)?

**Comment by gbraad** [comment]
We do not directly support guest additions. This is a feature that does not use `m hostfolder` and is therefore hard for us to track.

I'll try later to reproduce this...

**Comment by gordillo-ramon-redhat** [comment]
But it is in the docs...
https://github.com/minishift/minishift/blob/7710cf134275413bd5207a027a807643663f8dee/docs/source/using/host-folders.adoc#driver-provided-host-folders

**Comment by gbraad** [comment]
It seems to be a known issue that goes far back: https://gist.github.com/dschep/8f617de28157f8d35e69 (https://github.com/boot2docker/boot2docker/pull/1086), and has been reported in the boot2docker, docker/machine and minikube repo.

I am not really in favor either to introduce a hypervisor specific solution to mount host folders, when we provide an alternative which works across the board. Besides, long term we might move away from the B2D image entirely (favoring the minikube iso).

**Comment by gbraad** [comment]
@gordillo-ramon-redhat can you try to see if : https://gitlab.com/gbraad/minishift-b2d-iso/-/jobs/29206639/artifacts/file/public/minishift-b2d.iso would solve your problem?

**Comment by gordillo-ramon-redhat** [comment]
Yep, it works with that version.

I will use it until next release.

**Comment by gbraad** [comment]
@praveenkumar we can update to 1.13.1?

**Comment by gbraad** [comment]
@gordillo-ramon-redhat not sure about a possible new release. Although B2D is the default image, it does not receive as much attention/scrutiny as the CentOS counterpart.

**Comment by gordillo-ramon-redhat** [comment]
Can we have then virtualbox guest additions added to our CentOS iso?

**Comment by gbraad** [comment]
Due to possible legal issues we can not add these to the image.

**Comment by gbraad** [comment]
We have removed the mention of Hypervisor/ISO related mounting options, as these are hard for us to verify/test continuously.
