### ISSUE TITLE
Improve isolation of features by using before- and afterFeature() hooks

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1375]
The beforeFeature() and afterFeature() hooks have been added into Godog recently. We could update to newest Godog and improve the isolation of individual features. Right now we are doing cleaning and checks just before the whole suite, but we should do it on individual features to make sure there is nothing which leaks into following features - for example when we manipulate the config file.

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/pull/1385/
