### ISSUE TITLE
Improve error message on start for using Virtualbox when Hyper-V is enabled

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1376]
While trying to start with minishift with Virtualbox driver when Hyper-V is enabled, I am getting error messages which looks quite ugly and not user friendly.

```
PS C:\Users\budhram> minishift start --vm-driver virtualbox --iso-url file://C:/ms_cache/iso/1.1.0/minishift-b2d.iso
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ..... FAIL E0913 12:36:13.753837   10688 start.go:339] Error starting the VM: Error creating the VM. Error with pre-create check: "This computer is running Hyper-V. Vi
rtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)". Retrying.
. FAIL E0913 12:36:16.093452   10688 start.go:339] Error starting the VM: Error creating the VM. Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits
VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)". Retrying.
. FAIL E0913 12:36:18.447673   10688 start.go:339] Error starting the VM: Error creating the VM. Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits
VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)". Retrying.
Error starting the VM: Error creating the VM. Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as
 a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)"
Error creating the VM. Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable t
he Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)"
Error creating the VM. Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable t
he Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)"
```

**Comment by gbraad** [comment]
We can not properly detect this. We can see if Hyper-V is installed, and then check with `systeminfo` if the value for "VM Monitor" is returning "No", because of the desktop running as ring 0:

![image](https://user-images.githubusercontent.com/1894/30371826-61912b84-98ae-11e7-8276-11982fe48e93.png)

**Comment by budhrg** [comment]
@gbraad , I have VirtualBox installed but don't use it when HyperV is enabled. Till now, it is working fine. So when I desire to use VirtualBox, I just disable HyperV from `Features on or off window`.

I just raised this issue to improve the error message if by chance user try to run VirtualBox when HyperV is enabled.

**Comment by gbraad** [comment]
On macOS a fallback is performed when virtualbox is available. This can be observed when people did not uninstall virtualbox, but only removed the manager app from `/Applications`. I expect similar behaviour on Windows. @budhrg please verify this: #1336

**Comment by gbraad** [comment]
Well, I wonder what you have installed and how.

The current message can not be modified, as it comes from libmachine. We can however implement a pre-flight check... but for this a check pattern needs to be known.

**Comment by praveenkumar** [comment]
@budhrg @gbraad are we still want to have any action regarding this. I think #1676, what is more important and can be implemented.

**Comment by gbraad** [comment]
@praveenkumar they are two very different things. On Windows 10 I can use either VirtualBox or Hyper-V. But when Hyper-V is installed, I should NOT be able to support VirtualBox, and vice versa. But also #1719 and #1720 should be considered.

**Comment by anjannath** [comment]
@budhrg @gbraad What is the action course for this, are we going to add a preflight check in case of virtualbox to check if hyperv is already enabled and if it is we fail?

**Comment by budhrg** [comment]
I think it is better to error out here by checking if HyperV is enabled here or not when we specify vm-driver as virtualbox.

**Comment by gbraad** [comment]
Can this be reproduced first? The steps involved will lead to two possible scenarios I guess. Based on this, we need to take appropriate steps.

But checking if Hyper-V is enabled or possible is not an easy check, as having the management tools installed will lead to the same results if not mistaken. I remember an issue for this.

**Comment by anjannath** [comment]
@gbraad I think having only the `Hyper-V Management Tools` installed does not result in detecting Hyperv, only if the `Hyper-V platform` features are enabled then the error occures.

I was able to reproduce this on windows 10 fall creators edition by following the below steps: 

### First scenario, all the Hyper-V components are turned on
1. Turn all the Hyper-V components on in windows features.
2. start minishift with `minishift start --vm-driver virtualbox`
and you will see the error [message](https://github.com/minishift/minishift/issues/1376#issue-257316829) from libmachine side [pre-create check](https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox.go#L254)

### Second scenario, only management tools are turned on
1. Turn on only the `Hyper-V Management Tools`
2. start minishift with `minishift start --vm-driver virtualbox`
and minishift starts succesfully with `virtualbox` as the driver

### Third scenario, only Hyper-V platform is turned on
1. Turn on only the `Hyper-V Platform`
2. start minishift with `minishift start --vm-driver virtualbox`
and you will get the error message as in this [comment](https://github.com/minishift/minishift/issues/1376#issue-257316829)

What i can conclude from this is that libmachine is able to detect properly if hyperv is enabled on the system when trying to start a vm using virtualbox.
The check is done by [`isHyperVInstalled()`](https://github.com/docker/machine/blob/d8b1195a3631cb2d8dc63a539c480d893a3d6bed/drivers/virtualbox/virtualbox_windows.go#L97)

/cc @budhrg
