### ISSUE TITLE
Command addons remove tries to run when Minishift is not running

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1377]
Command `minishift addons remove` should work as other commands which need Minishift to be in `Running state`, expected:

```gherkin
  Scenario: Removing addon when Minishift is not running
    Given Minishift has state "Does Not Exist"
     When executing "minishift addons remove xpaas" succeeds
     Then stdout should contain
      """
      Running this command requires an existing 'minishift' VM, but no VM is defined.
      """
```
But instead it gives:
```
No xpaas.addon.remove file found for xpaas add-on.
```

**Comment by gbraad** [comment]
Isn't this related to #1378

**Comment by agajdosi** [comment]
@gbraad Good point, is related. However this is about fact that Minishift shoukd first check if the command can be run in current `state`. If it can't be run, then it will tell me. Now for this command it first checks if it can uninstall the addon. The #1378 is a story when state is running but .remove was not installed so we still can not uninstall.

**Comment by gbraad** [comment]
Is this still reproducible?

**Comment by agajdosi** [comment]
Thanks for noticing, @gbraad. Fortunately it is no longer reproducible! I am adding integration-test tag and will take this issue as task to implement needed changes into integration test suite. There are some not failing but also not truly correct lines around https://github.com/minishift/minishift/blob/master/test/integration/features/cmd-addons.feature#L40.
