### ISSUE TITLE
Review and update documentation

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#138]
Some of the documentation seems out of date, for example _ADD_DEPENDENCY_. The latter references Godep, even though Glide is used now. 

Let's do a review of the various documentation documents and make sure they are up to date.

**Comment by thatdocslady** [comment]
More tasks from #157 that should be done here:

- Restructure existing files in a hierarchical way, right now everything is in the root folder and some files need to be placed in /docs/ directory, etc
- Convert all docs to ASCIIDoc
- Clean up readme and other files as needed to be more user-friendly

**Comment by hferentschik** [comment]
> Convert all docs to ASCIIDoc

See also issue #140

**Comment by hferentschik** [comment]
BTW, I would think that we won't be able to address all in one go. So we should create dedicated issues for any changes which we want to merge.

**Comment by thatdocslady** [comment]
@hferentschik Makes sense, actually. Maybe we should reopen #157 so that it can focus on structural changes, and close #140 to be handled as a part of that.

**Comment by hferentschik** [comment]
> Maybe we should reopen #157 so that it can focus on structural changes, and close #140 to be handled as a part of that.

Why re-open #157? If with structural changes you mean a straight conversion to Asciidoc, why don't you use #140.

**Comment by hferentschik** [comment]
@thatdocslady Also we need to be careful here, the markdown in the docs directory is generated - https://github.com/minishift/minishift/blob/master/gen_help_text.go

So Cobra is giving us a way to generate Markdown docs. We need to investigate whether we can generate into Asciidoc as well. If not, we might not want to switch to Asciidoc as yet, since dealing with two different markdown languages does not seem to be the right approach.

**Comment by thatdocslady** [comment]
@hferentschik now that we know about the asciidoc complications, I can remove it from #157 but there are other changes that should be made directly in the markdown (proofreading, moving files around to their proper place, etc). WDYT?

**Comment by hferentschik** [comment]
> there are other changes that should be made directly in the markdown (proofreading, moving files around to their proper place, etc). WDYT?

Sure, let's do it as part of this issue

**Comment by thatdocslady** [comment]
@LalatenduMohanty @hferentschik can we close this issue now after the PRs were merged? we can open more specific issues for anything else that comes up

**Comment by LalatenduMohanty** [comment]
@thatdocslady agree.
