### ISSUE TITLE
Include version information in the debug logs

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1388]
Too often I have to ask for the version information when analyzing a log. It would be helpful to just include this information...

**Comment by rahulbajaj0509** [comment]
I would like to work on this bug :)

**Comment by budhrg** [comment]
> I would like to work on this bug :)

:+1:

**Comment by LalatenduMohanty** [comment]
Along with minishift version information we should include  OS name and version in the output of ` --show-libmachine-logs -v 5`. Specifically Minishift version and OS name and version should be part of `-v 5` logs.

**Comment by LalatenduMohanty** [comment]
@rahulbajaj0509 Have you started working on this?

**Comment by rahulbajaj0509** [comment]
@LalatenduMohanty yes.

**Comment by LalatenduMohanty** [comment]
Can not assign @rahulbajaj0509 to this bug, hence keeping it in my name to prevent assigning the issue to someone else.

**Comment by LalatenduMohanty** [comment]
@rahulbajaj0509 Any update on this issue. Looks are you are busy in other stuff. If we do not get any update in next 1 week I am going to re-assign this issue.

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift/pull/1881
