### ISSUE TITLE
Display available add-ons in the documentation

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1389]
It would be good to display list of available add-ons on the minishift documentation [here](https://docs.openshift.org/latest/minishift/using/addons.html) to bring more visibility.

**Comment by LalatenduMohanty** [comment]
@budhrg Do you mean we need to put the names of the add-ons and description of them in https://docs.openshift.org/latest/minishift/using/addons.html#default-addons ?

**Comment by budhrg** [comment]
> Do you mean we need to put the names of the add-ons and description of them in https://docs.openshift.org/latest/minishift/using/addons.html#default-addons ?

Yes @LalatenduMohanty and hyperlink to respective add-ons.

**Comment by rahulbajaj0509** [comment]
i would like to work on this bug. Since i am new to this project, it will also bring me some insight about the default-addons :)

**Comment by budhrg** [comment]
> i would like to work on this bug. Since i am new to this project, it will also bring me some insight about the default-addons :)

:+1:

**Comment by anjannath** [comment]
@rahulbajaj0509 is this a WIP?

**Comment by rahulbajaj0509** [comment]
@anjannath yes :) i shall resolve it by the weekend.

**Comment by LalatenduMohanty** [comment]
@rahulbajaj0509 You already have an assigned issue #1388, so unless you have a PR ready we should reassign this issue as it has been 2 weeks and there is no progress.

**Comment by rahulbajaj0509** [comment]
@LalatenduMohanty hey, i am really sorry but i am caught up in some work. It would be nice if some other contributor could handle this one. Sorry for the delay.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1640
