### ISSUE TITLE
Create build target to build HTML documentation

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#139]
At release time the documentation should be rendered into HTML. This allows to have versioned documentation which can be deployed on some web server (and included into the dist zip).

**Comment by gbraad** [comment]
Which tools are we using to generate the documentation? using pandoc (or jekyll) allows us to create a template and generate HTML from there based on markdown. Are we still switching?

**Comment by hferentschik** [comment]
Right now we have no tooling as part of Minihshift. Downstream, there are several tools at play, I think including pandoc. Also the preferred format is actually  asciidoc.

The problem with the downstream toolchain adds additional prerequisites to the build setup which might be even hard to meet on say Windows. So the idea is to provide a Docker container with all the required tooling and build/render the docs in the container, while still editing on the host using your preferred editor. Also one can then use Minishift itself to run this container :-)

**Comment by gbraad** [comment]
@hferentschik a container is ideal; https://github.com/gbraad/docugen/blob/master/Dockerfile I used pandoc and jekyll (and also did PDF generation)... but I would strongly suggest not to do PDF (using xelatex) as it increases the container size dramatically. Also, pandoc in most distros is way too old... so an image with the latest is preferred.

**Comment by hferentschik** [comment]
> a container is ideal; 

lol, we seem to have same experience. We did this when switching to awestruct for the in.relation.to website - https://github.com/hibernate/in.relation.to/tree/staging/docker

> https://github.com/gbraad/docugen/blob/master/Dockerfile I used pandoc and jekyll

I see. Does this allow for live rendering of the site? Basically you make a change and just reload (or even better use live-reload) the page in the browser. 

@rkratky, maybe this setup can help you as well.

**Comment by gbraad** [comment]
> live rendering

`jekyll` can run in a server-watch mode, and actually gitbook AFAIR also, but that is kinda nice for technical documentation: https://github.com/gbraad/dockerfile-gitbook-server.

**Comment by hferentschik** [comment]
whichever way works. 

Once we have the Dockerfile with the dependencies to build and render the docs we can integrate everything into the Makefile and add some convenience targets.

**Comment by hferentschik** [comment]
@thatdocslady on that note, we will need the appropriate styles from docs.openshift.org so that we can render the right HTML. Could you please follow up on these?

**Comment by LalatenduMohanty** [comment]
Closing the issue as #530 is merged.
