### ISSUE TITLE
The Windows file location of "sh-4.2$" shown in Terminal

### ISSUE THREAD

**Issue by kvance11** [minishift/minishift#1395]
In a running container, Application-->Pods--> Terminal, sh-4.2$> 
Where is this root file location? how could I "cd" to a Windows file location from the Terminal? 
C:\minishift>minishift version
minishift v1.5.0+ae62cf2
C:\minishift>minishift openshift version
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
etcd 3.2.1

Thanks,
Kathy

**Comment by gbraad** [comment]
Container run inside the Minishift VM and have no knowledge of the host filesystem, unless configured. For this you need to setup hostfolxers and accordingly configure the application to use persistent volumes.

What is the use case you need to access the host filesystem?

**Comment by kvance11** [comment]
Thanks for your response. I try to run a sql file to create tables and to insert records in POSTGRESQL DB within a container.

**Comment by kvance11** [comment]
Another question is about minishift working folder where its log file or its configuration files are. I thought it has to be in ./minishift (In Windows). But I do not see them. Thanks.

**Comment by gbraad** [comment]
@kvance11 this sounds like the wrong way to do it. This will result in a what we call a snowflake; a workaround/patch, that is not easy to replicate without manual intervention. Poking around in the container is usually only done for debugging...

The better way it to use posthooks, such as https://blog.openshift.com/using-post-hook-to-initialize-a-database/, or just connect to the container instance with the pgqsl tool to achieve the same.

It would be best to drop by in the #openshift IRC room on freenode, or in a forum like #stackoverflow or  #serverfault. Be sure to tag your question with #openshift.

**Comment by gbraad** [comment]
@kvance11 the `.minishift` folder resides in the users home folder. On Windows this can be found at `C:\Users\[username]\.minishift` (depending on the version used).

**Comment by kvance11** [comment]
OK. I will try posthooks approach. 
You are right, I can find the ./minishift folder. Also I set MINISHIFT_HOME locally. I do not see any config there except log files. 
Thanks all.

**Comment by gbraad** [comment]
Logs files for Minishift are not helpful, they only concern about the startup of the VM. You probably want OpenShift logs. Minishift provides a command for this `minishift logs`. I strongly suggest you to read the documentation at: https://docs.openshift.org/latest/minishift/ and learn to use the `oc` command. Which can be enabled with `minishft oc-env`. Please use: 
```
 @FOR /f "tokens=*" %i IN ('minishift oc-env') DO @call %i
```
from a Command Prompt to enable this.

**Comment by gbraad** [comment]
Closing this as no real issue is reported.

If questions remain, please consider dropping by on IRC at freenode: #minishift
