### ISSUE TITLE
Reduce the time of integration test run on ci.centos.org

### ISSUE THREAD

**Issue by budhram** [minishift/minishift#1396]
Currently, the CentOS CI job is taking too much time. Example https://ci.centos.org/job/minishift-pr/1983/console which is making it timeout.

One idea is to split into multi-stage jobs.

Suggestions are welcome.

**Comment by gbraad** [comment]
I suggest to do this based on the following pattern:

```
Compile -> Unit-tests -> Basic (smoke) test -> artifacts exported ----> commands test
                                                                  | \-> profiles tests
                                                                   \--> coolstore test
```

**Comment by gbraad** [comment]
I rather want to see us actually using a pipeline (with stages), instead of enriching the CentOS_CI.sh file with a lot of state and actions.

See: https://jenkins.io/doc/book/pipeline/

**Comment by praveenkumar** [comment]
https://docs.openstack.org/infra/jenkins-job-builder/project_pipeline.html even now JJB also support pipeline so we shouldn't have issue to update our JJB templates and create it as per our need. We might have to split centos_ci.sh into smaller bash script for each test case and than run those.

**Comment by budhrg** [comment]
> We might have to split centos_ci.sh into smaller bash script for each test case and then run those.

Actually, it is integration tests which is taking time.

#### Stats for 21 min total build PR - https://ci.centos.org/job/minishift-pr/2010/consoleFull
```
10:49 - 10:51 ( ~2 mins)  - Build Machine Setup

10:51 - 10:56 ( ~5 mins)  - Prerelease test

10:56 - 11:10 (~14 mins)  - Integration tests   
```

**Comment by gbraad** [comment]
currently a run for PR takes 40+ mins

**Comment by gbraad** [comment]
https://ci.centos.org/job/minishift-pr/2011/ (43mins)

**Comment by budhrg** [comment]
### Stats for 43 mins total build PR - https://ci.centos.org/job/minishift-pr/2011/consoleFull
```
10:58 - 11:01 ( ~3 mins)  - Build Machine Setup

11:01 - 11:11 ( ~9 mins)  - Prerelease test

11:11 - 11:41 (~30 mins)  - Integration tests   
```

**Comment by kbsingh** [comment]
what problem are you really trying to solve here ? There doesnt seem to be a clear msg around that, so is this just unneeded premature optimisation ?

**Comment by gbraad** [comment]
@kbsingh this is not premature optimisation. in just a few days, the test load has increased from 15 minutes to 45 mins... this is after we got the taste of using BDD/Cucumber. We have not even achieved full coverage, so we are surely going to see an increase.

**Comment by kbsingh** [comment]
@gbraad  I should have been clearer in my msg earlier - I meant the system contextualisation optimisation feels a bit premature - its clearly only 6% of the overall runtime, and not a contributor to the 400% increase in the test run-time itself.

**Comment by hferentschik** [comment]
So what is the game plan. I guess splitting into multiple jobs only helps, if we can run some of them in parallel. If we run everything in sequence nothing is gained, right? Parallelisation comes with an overhead as well. Can we even do it (infrastructure wise)?

**Comment by budhrg** [comment]
@hferentschik , if you see in this comment https://github.com/minishift/minishift/issues/1396#issuecomment-330543924 , most of time is consumed by integration tests.

The plan here is to split into multi-stage jobs : 
1. Pre-release tests
2. Basic integration tests
3. Others integration tests
4. Coolstore integration test (may be) 

At any step, build fail, it will fail entire job. Each steps above is suppose to be a separate job(so 4 jobs above one by one). 

WDYT @praveenkumar @LalatenduMohanty @gbraad

**Comment by hferentschik** [comment]
> The plan here is to split into multi-stage jobs

Sure, but can we run them in parallel? If we need to run in sequence a multi-stage job does not give us anything, right?

**Comment by budhrg** [comment]
> Sure, but can we run them in parallel?

Yes.

> If we need to run in sequence a multi-stage job does not give us anything, right?

It does give something. Like if 2nd job (Basic one) failed, it will not run other builds 3rd and 4th.

**Comment by hferentschik** [comment]
> It does give something. Like if 2nd job (Basic one) failed, it will not run other builds 3rd and 4th.

That's not really depended on a multi stage build. If your single build runs multiple integration test targets, you can also stop as soon as the first test fails.

**Comment by budhrg** [comment]
> That's not really depended on a multi stage build. If your single build runs multiple integration test targets, you can also stop as soon as the first test fails.

Sure. 

We will mostly run integration tests in parallel. For that we will discuss with CI admin about max available infrastructure for us. With current scenario (4 parallel jobs), we will be in a situation where only 1 PR will be tested at a time.

**Comment by hferentschik** [comment]
So do we really want a multi stage build or do we want to split in general into multiple CI jobs? For example, we always said that the pull request build should run the basic/sanity integration tests, whereas there would be a nightly CI job which runs all integration tests. That's different though to a multi stage build. 

Another option is to  not build the docs on each pull request. Or even better, do a quick check on the changed coming in via the pull request and only do a docs build in case any docs related files changed.

**Comment by budhrg** [comment]
> we always said that the pull request build should run the basic/sanity integration tests, whereas there would be a nightly CI job which runs all integration tests. That's different though to a multi stage build.

So, it means if we found issue in nightly CI job (need to create this one), which is mostly from integration test other than basic/sanity, then we debug and resolve next day, right? 

> Another option is to not build the docs on each pull request. Or even better, do a quick check on the changed coming in via the pull request and only do a docs build in case any docs related files changed.

+1. Like the idea.

**Comment by budhrg** [comment]
Found that the CI time also depends on the load/network connectivity of the build machine

Master job stats
- [job/minishift/382](https://ci.centos.org/job/minishift/382/) Completed in ~27 mins
- [job/minishift/381](https://ci.centos.org/job/minishift/381)  Completed in ~45 mins

**Comment by budhrg** [comment]
Another, important parameter is the number of times Minishift VM starts during build

Minishift VM start timing (Six time start) based on Job https://ci.centos.org/job/minishift-pr/2554/consoleFull.

7:19  - 11:57 = 4:38 (278s) 
15:25 - 20:58 = 5:33 (333s)
21:34 - 24:13 = 2:39 (159s)
24:18 - 26:53 = 2:35 (155s)
30:59 - 33:35 = 2:36 (156s)
39:08 - 41:46 = 2:38 (158s)

Total Start up time - 20m39s (1239s) out of 38mins.

So, more than 50% is being used in just starting VM. 
As the number of feature file increases, it will increase.

**Comment by budhrg** [comment]
> Enable caching of images while running integration tests.

is not working as it is increasing load on system which is making `minishit start` timing more. Also, found that caching one of the image `router` is not happening properly i.e while the router image is being cache, another `minishift start` happened and something break the caching at all.

**Comment by hferentschik** [comment]
> Enable caching of images while running integration tests.

I think this might indeed help, but it will need to wait until #952 is merged, since you want to do a explicit image export. The alternative is to put some infrastructure in place to monitor the exporting background process. This is something we will eventually need anyways in order to write features for image caching. For example we need a way to monitor a given pid.

**Comment by hferentschik** [comment]
@budhrg, does CentOS have a build cache functionality. Travis and Co offer the ability to store certain build artefacts in a cache. This coulee be the Go dependencies and/or the required base images. This would reduce network traffic considerably.

**Comment by budhrg** [comment]
> does CentOS have a build cache functionality. Travis and Co offer the ability to store certain build artifacts in a cache

No AFAIR since they just spin a bare metal machine from their pool of machines.

**Comment by hferentschik** [comment]
That does not have to exclude a cache option. The cache would be linked in after the machine is ready.

**Comment by gbraad** [comment]
We can however have the build run in a prepared docker image. This would also eliminate variables in the actual build process that could occur because of the release of new(er) packages.

**Comment by hferentschik** [comment]
> We can however have the build run in a prepared docker image

we might be able to build in a Docker image, but what do we do with the integration tests?

**Comment by gbraad** [comment]
For the time being we would have to `docker cp` the artifacts out and still run them on the node. Eventually I want to also run this against a `libvirt-client` container.

**Comment by hferentschik** [comment]
> For the time being we would have to docker cp the artifacts out and still run them on the node. 

You still need Go itself installed on the box. Is this possible w/o all the other update stuff which seems to be going on? Can we maybe skip these updates in the first place? Have a newer slave image maybe? 

IMO there is little value in doing just the compile in a Docker container. Different if you can drive the whole build in the container. 

Also, the setup lies around 4 minutes. In the great scheme of things that's really not so much. A lot of effort to shave off a few minutes which are lost again with the next new integration test which needs to start a new VM.

**Comment by gbraad** [comment]
The VM start issue is never gonna be resolved... but that is just a fact, and working around it by having the machine not restart, seems like the wrong approach. I thought we wanted to start several tests in parallel... but this seems to be off the table now?
