### ISSUE TITLE
Minishift should provide additional information when disabling already disabled addon

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1398]
Issue based on this [comment](https://github.com/minishift/minishift/pull/1385#discussion_r139349820).

Currently messages for disabling enabled addon and disabling disabled addon are the same:

```
Add-on 'xpaas' disabled
```

However it should differentiate between the two situations: in first the addon was disabled - the message is fine, in second case Minishift just found out it is already disabled and has done nothing, so the message should be maybe: `Add-on 'xpaas' already disabled` or something similar.

I also recall similar cases on other places in Minishift - for example `minishift config set` and other config subcommands where behaviour is similar as with `addons disable xyz`. We could expand the topic of this issue to improve the reports overall. That would require an investigation to find problematic cases and then the fix.

WDYT @LalatenduMohanty ?

**Comment by LalatenduMohanty** [comment]
@agajdosi I have similar thoughts as well. Would be interested to know what others think about it.

**Comment by budhrg** [comment]
Similar case with `minishift profile set foo`. If my current profile is `foo`, and I by mistake do `minishift profile set foo`, it gaves the same message as we get during switch.

> so the message should be maybe: Add-on 'xpaas' already disabled or something similar.

+1

**Comment by ulyssessouza** [comment]
Can I take this one?

**Comment by agajdosi** [comment]
Hi @ulyssessouza, thank you for your interest. Minishift welcomes contributions from community. The original part of this issue around reports in `minishift addons` subcommand is, I think, open to be taken and nothing blocks it. To be sure I am pinging @LalatenduMohanty who can also tell us more about the @budhrg's note about report messages of `minishift profile set`. It could be practical to join both problems in one PR.

**Comment by LalatenduMohanty** [comment]
@ulyssessouza I would suggest that we change nothing  in `profile set` with respect to this issue as it just do not set the profile as active profile but also changes the `oc` CLI context for the active profile. So in case the context is out of sync because of some reason `minishift profile set` fixes it.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1747
