### ISSUE TITLE
Switch documentation to Asciidoc

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#140]
Relates to issue #139. Using Asciidoc(tor) gives us more possibilities to build a complete documentation set with  various output formats (for example HTML or PDF).

Given that Asciidoc also renders directly when viewed on GitHub, we don't loose anything there.

**Comment by hferentschik** [comment]
As a reference - https://github.com/spf13/hugo/issues/470
There seems to be a way to generate Asciidoc as well from the Cobra source files. See also gen_help_test.go in the root directory of the repo.

**Comment by aheusingfeld** [comment]
There is an ongoing discussion in the asciidoctor project https://github.com/asciidoctor/asciidoctor.org/issues/462 - AFAIK the java tooling is still the best way to convert markdown to asciidoc at the moment, though Dan started a converter in https://github.com/opendevise/kramdown-asciidoc

**Comment by hferentschik** [comment]
@aheusingfeld thanks for the info. Interesting. A shame though to add something like Java or Ruby into the mix. I guess there is nothing intrinsically wrong with Markdown. Provided the site generator we are going to use can cope with it, there is really no need to switch to Asciidoc(tor) for now.

**Comment by aheusingfeld** [comment]
Well, we're still just talking about the one-time effort to convert the marksown files into asciidoc files, right?

To afterwards generate output from the asciidoc sources, asciidoctor is definitely the best option. What I personally like about asciidoc is the increased flexibility i.e. I very often include parts of the sourcecode into my asccidoc documentation files. This ensures that samples in the docs are always uptodate.

BTW: What are your requirements and which output formats would you want to target ATM and midterm?

**Comment by hferentschik** [comment]
> Well, we're still just talking about the one-time effort to convert the marksown files into asciidoc files, right?

Yes and no. There is a bunch of markdown files which we only need to convert once. However, there are also some generated Markdown files (https://github.com/minishift/minishift/blob/master/gen_help_text.go) which Cobra generates from the CLI sources. This generator afaiu just generates manpage or markdown format. So if we decide to keep this generated docs (which is nice, since this ensures that the docs are in sync with the actual sources), we would need to re-generate each time we build the the Cobra docs.

> To afterwards generate output from the asciidoc sources, asciidoctor is definitely the best option.

Sure, no questions asked.

> What I personally like about asciidoc is the increased flexibility i.e. I very often include parts of the sourcecode into my asccidoc documentation files. 

Same here, Asciidoc is ways more powerful

**Comment by thatdocslady** [comment]
TODO: Fix links in the usage docs or anywhere that points to the command ref docs (because we moved them).

**Comment by hferentschik** [comment]
Closing this issue, since it is a duplicate of #534
