### ISSUE TITLE
Ability to create new profile without starting Minishift

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1401]
Currently the only way to create a profile is to start new Minishift instance:
```
minishift start --profile xyz
```
It would be nice to implement `minishift profile new xyz` so user would be able to create new instance, set configuration and when everything is ready then she could start Minishift.

Now it is also possible but it would require workaround, which doubles the work: using flags and later setting config, or starting minishift, deleting it and then setting the config.

**Comment by agajdosi** [comment]
Ok, so another and probably most easy/fast workaround is:
```
minishift config set --profile bigger memory 8gb
minishift profile set bigger
[...]
minishift start
```

**Comment by LalatenduMohanty** [comment]
@agajdosi the workaround be one step less. 
```
minishift config set --profile bigger memory 8gb
minishift --profile bigger start
```
Also `profile new` will add to improved user experience I think.

**Comment by gbraad** [comment]
Remember we once discussed the need of a create command? Let's check what
the status is on minikube's end. I suggest to stay close to minikube first,
a possible Docker machine second, before doing our own commands.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by anjannath** [comment]
This can be closed i guess, as the creation of profiles without starting them can now be done using `minishift profile set`
