### ISSUE TITLE
Warning "unable to list petsets resources. Not all status relationships can be established" for oc status

### ISSUE THREAD

**Issue by apupier** [minishift/minishift#1404]
using minishift 1.5.0
on Windows 10 with Hyper-V

I can see the message when I run "oc status -v"

I have no idea what is it and if it is important or not.

**Comment by praveenkumar** [comment]
@apupier Can you check which version of oc binary you using? I am not able to see it.

```
$ oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.250:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

$ oc status -v
In project My Project (myproject) on server https://192.168.42.250:8443

You have no services, deployment configs, or build configs.
Run 'oc new-app' to create an application.
```
@csrwng do you have any idea about this warning from openshift client binary side?

**Comment by apupier** [comment]
C:\install\minishift-1.5.0-windows-amd64>minishift version
minishift v1.5.0+ae62cf2

C:\install\minishift-1.5.0-windows-amd64>oc version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994

**Comment by csrwng** [comment]
Issue https://github.com/openshift/origin/issues/13913

**Comment by praveenkumar** [comment]
Thanks @csrwng . @apupier Can we close this issue from minishift side now and you can add yourself as watcher for upstream issue?
