### ISSUE TITLE
Line "Checking available disk space ... 0% OK" in minishift start log looks weird

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#1406]
```
minishift version : 1.6.0
```
```
$ ./minishift start
-- Installing default add-ons ... OK
.
.
-- Checking available disk space ... 0% OK
-- Downloading OpenShift binary 'oc' version 'v3.6.0'
.
.
$
```

**Comment by praveenkumar** [comment]
@amitkrout it's not weird, here we check the space of mounted drive so that we also know if disk is mounted as expected. cc @gbraad

**Comment by gbraad** [comment]
It actually says: checking available space...
0% is used... so OK follows.

... as expected.


Suggestion on how to improve the message?

**Comment by amitkrout** [comment]
@praveenkumar The line is ok, however the ```0%``` confuses me. As a user i would consider this as ```no disk space is available``` cc @gbraad

**Comment by gbraad** [comment]
The whole message is
```
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% OK
```

Maybe we could include:
```
-- Checking available disk space ... 1% used OK
```

**Comment by budhrg** [comment]
> -- Checking available disk space ... 0% OK

Agree with @amitkrout , as the wording is little confusing. One might think here that disk space is 0% available. 

+1 for changing the wording here. 

> Checking available disk space ... 1% used OK

Looks fine. WDYT @amitkrout ?

**Comment by gbraad** [comment]
add easyfix tag

**Comment by amitkrout** [comment]
> Checking available disk space ... 1% used OK

+1

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/pull/1422
