### ISSUE TITLE
Enable profile integration tests in CentOS CI

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1407]
Currently https://github.com/minishift/minishift/blob/master/centos_ci.sh only runs below tests. 
```
MINISHIFT_VM_DRIVER=kvm make integration GODOG_OPTS="-tags=basic,openshift,version,cmd-config -format pretty"
```
So we should add basic tag to profile tests [1]  i.e. `s/@profile/@profile @basic/` as this should be part of sanity testing.

[1] https://github.com/minishift/minishift/blob/master/test/integration/features/profile.feature#L1

**Comment by gbraad** [comment]
They are not part of the basic test, but rather advanced or commands test.

Our basic test covers a smoke test scenario => https://en.wikipedia.org/wiki/Smoke_testing_(software)

**Comment by LalatenduMohanty** [comment]
@gbraad I think a test to check the default profile i.e. `minishift profile list` after `minishift start` must be part of basic testing and we can keep the detailed testing separate as you suggested. 
```
Scenario: User should be able to list default profile 'minishift'
    Given Minishift has state "Running"
     When executing "minishift profile list" succeeds
     Then stdout should contain
     """
     - minishift	Running	(active)
     """
```

**Comment by gbraad** [comment]
I disagree. as long as `m status` returns the expected value, we have covered a smoke test scenari

**Comment by gbraad** [comment]
Since you introduce new functionality, it should not break the basic flow... so, if status returns the expected value and the deployment succeeds, the smoke test passed.

Basic test:
  * start
  * status
  * deploy testapp
  * stop
  * delete

**Comment by agajdosi** [comment]
@gbraad @LalatenduMohanty I think it depends on how community see the profile feature, is it really wanted by broad public or was that a wish from few users who have quite specific use case? I can't tell.
Maybe it would be better to rather invest test-time to OSO related features like provision_earlier_version.feature or cmd-openshift.feature.

However I would not add --profile to basic.feature as it is a nice story of happy path of new user, rather I would suggest to add `@basic` tag to profile.feature - if we really want to spent our test-time on profile.

**Comment by LalatenduMohanty** [comment]
> I would suggest to add @basic tag to profile.feature - if we really want to spent our test-time on profile.

That's what I originally did. By adding @basic tag to profile tests, all profile tests will be run when someone run basic tests. But @gbraad does not agree to that as he thinks profile tests should not be in basic tests.

**Comment by gbraad** [comment]
> However I would not add --profile to basic.feature as it is a nice story of happy path of new user,

To me `@basic` and `basic.feature` are the same thing. They should not start to mean more than the basic happy path for a new user.

**Comment by agajdosi** [comment]
@gbraad Until now we have run all tags except the `coolstore`. So we could run more than a basic.feature. Maybe a `smoke` tag would be handy for this - we would tag as smoke the basic.feature and one or two more features we want to run. This way we would have unique tag for basic.feature - `basic` and special tag meaning the set of smoke tests we want to run on PRs in Centos-CI.

**Comment by gbraad** [comment]
@agajdosi CI/CD ultimately should give quick feedback to the user about the state of the build... but at the moment we add more and more and a PR build takes over 40+ mins. That is way beyond the usual threshold of +/- 10 mins as used in CI practices.

I strongly suggest rethinking our strategy before adding more: #1396. I will not add those comments here...

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift/pull/1410
