### ISSUE TITLE
Feature request: allow custom oc command to be used for deployment/use

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1409]
Currently, we offer a `--iso-url` option to specify a custom image. We should also allow specifying a custom `oc` client to be used.

**Comment by gbraad** [comment]
Implementing this can aid in development

**Comment by thomasmckay** [comment]
+1

**Comment by LalatenduMohanty** [comment]
@thomasmckay Can you please explain here what is the use case you are trying to solve with the custom oc binary? It will help us prioritizing the task

**Comment by thomasmckay** [comment]
As a user, I want to specify an oc executable that matches my openshift/origin image.
As a developer, I want to specify my a locally built oc executable.

Currently I specify --openshift-version, which determines the version of oc, along with --extra-clusterup-flags to get the openshift/origin tagged image. My specific case I'm using :latest tag but all released versions of oc do not work with that image.

**Comment by budhrg** [comment]
This is duplicate of https://github.com/minishift/minishift/issues/963 which is closed now. And we had a disagreement that time.

**Comment by gbraad** [comment]
disagreement? this makes it just more valid to have outside input and re-discuss this topic

**Comment by budhrg** [comment]
@hferentschik @praveenkumar WDYT about it?

**Comment by hferentschik** [comment]
I don't think it makes any sense. We the user wants to use its own version of oc, she is free to download it and put it on the PATH. I don't see a good a reason why this should be offered via Minishift.

**Comment by thomasmckay** [comment]
Does PATH work? I was told that I could use my own _oc_ by pre-populating the cache prior to calling start.
```
      mkdir ~/.minishift/cache/oc/v3.7.0-rc.0
      ln -s /home/thomasmckay/code/minishift/build/bin/oc  ~/.minishift/cache/oc/v3.7.0-rc.0/oc
```

If this isn't a desired use case, I can accept that. I will say that minishift provides a very accessible and convenient way to stand up openshift in a production-like way for testing tool integrations. For myself I have used it both for cockpit and foreman development with great success. Having to integrate with unreleased openshift features (image signatures) has exposed aspects outside what, it seems, are typical minishift work flows.

**Comment by budhrg** [comment]
@thomasmckay 

> As a developer, I want to specify my a locally built oc executable.

I believe, you can use following for development
```
$ ln -s ~/cache/oc/v1.5.1/oc ~/.minishift/cache/oc/v3.6.0/oc

$ ~/.minishift/cache/oc/v3.6.0/oc version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

$ minishift start
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
[...]
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.1 image ... 
   Pulling image openshift/origin:v1.5.1
   Pulled 0/3 layers, 3% complete
[...]
```

**Comment by praveenkumar** [comment]
@thomasmckay https://github.com/minishift/minishift/issues/1409#issuecomment-345149770 does this works for you? if yes we will close this issue.

**Comment by thomasmckay** [comment]
This method has been working for me. If there is a place in the docs or in developer on-boarding notes where this could be suggested, that would be helpful for future.
+1 to close

**Comment by gbraad** [comment]
@budhrg @gbraad we will document this on the Wiki
