### ISSUE TITLE
Deleting a profile does not remove the instance main folder and structure

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1412]
```powershell
PS > C:\work\src\github.com\minishift\minishift\out\windows-amd64\minishift.exe profile test3
Will remove the VM and all the related artifacts. Do you want to continue [y/N]?: n
PS > C:\work\src\github.com\minishift\minishift\out\windows-amd64\minishift.exe delete
Running this command requires an existing 'test3' VM, but no VM is defined.
PS > C:\work\src\github.com\minishift\minishift\out\windows-amd64\minishift.exe delete --profile test2
You are deleting the Minishift VM: 'test2'. Do you want to continue [y/N]?: y
Deleting the Minishift VM...
Minishift VM deleted.
PS > dir C:\Users\gbraad\.minishift\profiles\

    Directory: C:\Users\gbraad\.minishift\profiles

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        19-Sep-17     16:42                default
d-----        19-Sep-17     14:32                test2
d-----        19-Sep-17     14:46                test3
```

**Comment by LalatenduMohanty** [comment]
@gbraad this is as designed. `minishift delete` never deletes the home directory for an instance. It only deletes the artifacts in `machines` directory. If you want to delete the profile we should use `minishift profile delete`.

**Comment by gbraad** [comment]
What is the motivation to not delete? In this case, it leaves "trash" behind, and conflicts with user expectation.

Because after this step has been performed you can not use the command `m profile delete` anymore, and means user interaction is needed

**Comment by LalatenduMohanty** [comment]
> What is the motivation to not delete? In this case, it leaves "trash" behind, and conflicts with user expectation.

It is not trash. It is user configuration. For example if an user has started with a different RAM or CPU number or separate add-on and user want to just delete the instance and start again.  If we want to talk about changing `minishift delete` thats a different discussion.

**Comment by gbraad** [comment]
General configuration and all instances config is not touched by delete. But with a remove I expect this specific config to disappear.

Else, this needs to be specifically tested and enforced in a behavioural test/integration test.

**Comment by gbraad** [comment]
I believe this breaks building a mental model for the user. The user should be able to expect commands to behave in a certain way. Consider the following:

```cucumber
Given a user
 When executing `minishift profile set test`
   And `executing `minishift profile delete`
 Then active profile is removed
  And no artifacts remain
```

Given a user
 When executing `minishift delete --profile test`
 Then active profile is removed
  And artifacts remain
```

Lets break this down semantically

  * `minishift profile delete`  
    As user I want the profile to be deleted that is active
  * `minishift delete --profile test`
    As user I want to delete a profile identified by name 'test'

There is no real difference in the meaning of the action:

  * `To *drive* a *car*` or `the *car* is *driven*`
  * `To *delete* a *profile*` or `the *profile* gets *deleted*`

I suggest to have the two commands act in the same way... and allow a flag `--erase-all` or whatever. Note: we can't use clear or remove, since `erase` is already used in the cache option. To build a mental model you need to be consistent.

**Comment by jorgemoralespou** [comment]
I think the behaviour as it stands is ok. If I delete a VM, I want the profile and config to remain. If I want it to be removed, I delete the profile itself.

**Comment by praveenkumar** [comment]
@gbraad I think this is now expected behaviour and we can close this issue?
