### ISSUE TITLE
Document usage of @cmd, @openshift and @addon tags

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1423]
Issue #1216 brought a need for more clear naming and definition of test sets we want to use. I am creating this issue as we agreed that further discussion is needed and that these changes are not necessary needed for #1216.

From previous discussion on #1216 there are three sets with their tags proposed:
- smoke
- basic
- all

First I would like to suggest to **rename the basic.feature to something else** - could be something like first-usage.feature, sample-story.feature or any other we would like.

Then **for smoke tests we should check for minimal basic functionality** for me it is:
- Minishift is able to start
- we can deploy sample application on OpenShift
- Minishift is able to stop and delete

Basically we can take whole **basic.feature aka new sample-story.feature to be tagged as `@smoke`**. Another possibility is to exclude some cases which take time - might be deployment of an application, or exclude those which are not really absolutely basic functionality. Exclusion needs more discussion for sure. Run time should be as short as possible - for continuous checks of developers, go for snack and have the feedback in 5-10 minutes. (basic.feature's run time is around 5 minutes on my laptop, so it could match.)

Basic set will then be freed from being associated with basic.feature aka new sample-story.feature. And so **in basic set we could have the sample-story.feature, profile.feature and 2 or 3 more "key" feature files**. Run time could be around 20 to 40 minutes. This could be the before-PR-test. And can be the one we run on PRs.

All other tag sets - currently we have `@command`, `@openshift` should be mentioned in documentation with an example command, so devs will be aware of their existence and usage.

**Comment by budhrg** [comment]
@agajdosi What is the status now?

**Comment by agajdosi** [comment]
@budhrg With introduction of `make integration_pr` target the road for implementation changed and this issue has no meaning. Once we add nightly tests, we just need to add `make integration_nightly` target. However I suggest to keep this open and take it as a need to add additional documentation around some tags we currently use:

> All other tag sets - currently we have @command, @openshift should be mentioned in documentation with an example command, so devs will be aware of their existence and usage.

**Comment by praveenkumar** [comment]
@agajdosi Do you still think this is valid?

**Comment by agajdosi** [comment]
@budhrg I agree.

**Comment by agajdosi** [comment]
Resolved via #2090.
