### ISSUE TITLE
Add documentation of adding Hyper-V environment variable in installation step

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1430]
The installation step of [minishift in Windows](https://docs.openshift.org/latest/minishift/getting-started/installing.html) doesn't specific says that it is mandatory to add switch name as environment variable. It is not visible. 

> To use Minishift with Hyper-V ensure that, after you install Hyper-V, you also add a Virtual Switch using the Hyper-V Manager. For specific configuration steps see the Setting Up the Driver Plug-in section.

We need to mention here that it is now mandatory to add switch name as an environment variable.

cc @gbraad 

#### Update
```
PS C:\Users\budhram> minishift start
-- Checking if Hyper-V driver is configured ... FAIL
   See the 'Setting Up the Driver Plug-in' topic for more information

PS C:\Users\budhram> $env:HYPERV_VIRTUAL_SWITCH="New Virtual Switch"

PS C:\Users\budhram> minishift start
-- Checking if Hyper-V driver is configured ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.2.0/minishift-b2d.iso'
 0 B / 40.00 MiB [--------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%
```

**Comment by gbraad** [comment]
This is described in the section https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html

**Comment by gbraad** [comment]
Not sure if this should be more explicit, as the paragraph already says: for more information, see

**Comment by budhrg** [comment]
> Not sure if this should be more explicit, as the paragraph already says: for more information, see

Not explicit for users IMO, since there it says 

> For specific configuration steps see the Setting Up the Driver Plug-in section.

It says if _you need any specific configuration steps_ which is not general IMO not sure what @LalatenduMohanty @praveenkumar think about it.

**Comment by dragerot** [comment]
If DockerNAT already is defined, do I need to remove this?  I call my external virtual network switch "minishift-swift", but it does not work.  I have set HYPERV_VIRTUAL_SWITCH=minishift-swift. Same error...
Tore Gard

**Comment by budhrg** [comment]
> If DockerNAT already is defined, do I need to remove this? 

No. 

> set HYPERV_VIRTUAL_SWITCH=minishift-swift

Should have work. It works for us.

**Comment by gbraad** [comment]
Any update on this?

**Comment by budhrg** [comment]
@anjannath Can you take care of it?

**Comment by dragerot** [comment]
I Set HYPERV_VIRTUAL_SWITCH environment to the new Virtual External  Switch name set in Hyper V.
My problem was that I selected the wrong externel network.

**Comment by budhrg** [comment]
> My problem was that I selected the wrong externel network.

If this wrongly selected external network doesn't has internet then, minishift start will fail. The requirement here is to have Virtual External Switch maped to network adapter which has internet.

**Comment by hferentschik** [comment]
> We need to mention here that it is now mandatory to add switch name as an environment variable.

Is it? How come?
