### ISSUE TITLE
Run acceptance tests on Travis CI

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#144]
Once we have some acceptance tests we should try to run some on Travis CI. For this we need nested virtualization which can be achieved with some tweaking - https://github.com/jimmidyson/gofabric8/blob/travis/.travis.yml#L1-L36

**Comment by jimmidyson** [comment]
Seems like this may have problems... hvm type not supported on travis. Might have to look elsewhere for something we can use.

**Comment by hferentschik** [comment]
> Seems like this may have problems... hvm type not supported on travis. Might have to look elsewhere for something we can use.

ok :-(

**Comment by budhrg** [comment]
> Seems like this may have problems... hvm type not supported on travis. Might have to look elsewhere for something we can use.

We can try for `ci.centos.org`.

**Comment by hferentschik** [comment]
That's the plan. Hence issue #173

**Comment by budhrg** [comment]
@hferentschik I am closing this issue since #173 has been closed now.
