### ISSUE TITLE
Provide feedback during 'Starting Minishift VM'

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1444]
On Hyper-V, the startup already takes quite long (although feedback of the creation and conversion of the disk image is given from `libmachine`), there is a provisioning happening that is under our control. It would be nice to provide some kind of feedback what is happening besides the progress dots:

```
PS C:\work\src\github.com\minishift\minishift\out\windows-amd64> .\minishift.exe start --networ
eserver 8.8.8.8 --iso-url file://c:/Users/gbraad/.minishift/cache/iso/minishift-centos7.iso
-- Checking if Hyper-V driver is configured ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:     2 GB
   vCPUs :     2
   Disk size:  20 GB
   IP address: attempting to set '10.0.75.124'
-- Starting Minishift VM ................................................................... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
```

Note: startup took about 3+ mins. While the VM console was available, some of the steps were slow to perform, but inside the VM I could see several ssh connections were made, docker was called, etc. It would be nice to get some kind of feedback of the steps perform in the provisioning stage.

**Comment by LalatenduMohanty** [comment]
> It would be nice to provide some kind of feedback what is happening besides the progress dots:

I do not think a normal user would be interested to know the details.  May be we can make the logging better for`--v 5` , so that if user wants to know whats happening in the background he can find out.

**Comment by gbraad** [comment]
I didn't go in detail what kind of feedback, but the mentioned `-v 5` is already done in the static IP PR:

```go
		if glog.V(5) {
			fmt.Printf("*")
		}
```

Ref: https://github.com/minishift/minishift/pull/1391/files#diff-2a4f72614435ed06b98e18eece588047R53

**Comment by agajdosi** [comment]
@gbraad I am +1 for some kind of feedback during startup, with Hyper-V I was sometimes telling myself: "What's taking it that much time?".

Do you think it would be possible to add a milestone to this issue, so it does not hide?

**Comment by gbraad** [comment]
No agreement was reached. Especially in some cases we want to provide too much information it seems, such as on startup to reduce messages: #1617, but provide more on delete #1706.

From a UX perspective you should provide the information a user expects, and when actions take long. But it seems we probably have to look more at implementing levels of logging instead.

However, many things inside libmachine are not exposed or are harder to expose...

**Comment by praveenkumar** [comment]
@gbraad @agajdosi not sure if still have same thought around this issue, otherwise we can just close it.

**Comment by gbraad** [comment]
The problem at the moment would be 'it breaks the alignment of the output messages', which became worse due to the progress dots. At the moment I do not have a real solution on my mind besides dumping this as part of `-v5`. We will eventually also move the preflight-checks under this level... unless an error occurs.

WDYT?

**Comment by LalatenduMohanty** [comment]
+1 to give the extra information /feedback for higher log levels. I would be fine with -v2 also.

**Comment by budhrg** [comment]
> +1 to give the extra information /feedback for higher log levels. I would be fine with -v2 also.

+1 and -v 2 is fine.
