### ISSUE TITLE
Preflight check  for default network when using the KVM driver plugin

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1454]
Currently, the KVM driver plugin has hard-coded the default network:

https://github.com/dhiltgen/docker-machine-kvm/blob/f328c4b81d36269845812a6bd0046e64a9c7d877/kvm.go#L121

When libvirt is used for the first time, it could happen this network does not exist, as the driver does not handle the actual creation. This can be seen in #1432. While documentation is going to be added to the troubleshooting guide, I believe this can be tested for on startup.

**Comment by gbraad** [comment]
If our codebase is able to use:

https://github.com/dhiltgen/docker-machine-kvm/blob/f328c4b81d36269845812a6bd0046e64a9c7d877/kvm.go#L191

we need to check for this network instead.

**Comment by gbraad** [comment]
you can use something like:
```
$ sudo virsh net-list
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes
 docker-machines      active     yes           yes
 vagrant-libvirt      active     no            yes
```

although this needs root/sudo privileges. Maybe there is another way to check this without using `sudo`?

**Comment by anjannath** [comment]
@gbraad there's supposed to be an xml file where the networks are defined, `/usr/share/libvirt/network/default.xml` [1]. But in my system (Arch linux) the `default` network is active, bu that file is not present.

[1] https://wiki.libvirt.org/page/Networking#Host_configuration

**Comment by gbraad** [comment]
@anjannath wrong approach... configuration files are not consistent among platforms.

**Comment by gbraad** [comment]
nope... the solution is simple:

```
$ virsh --connect qemu:///system net-list 
```

this connect to `system` as context, instead of the strandard `session` that is used for a user.

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift/pull/1462
