### ISSUE TITLE
Why default addons have no .addon.remove file other than admin-user addon? 

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1455]
I noticed that we have `.addon.remove` file for `admin-user` addon only. 
Did we miss to add for other addons ?
Or
Any other reason?

See https://github.com/minishift/minishift/tree/master/addons/anyuid

**Comment by agajdosi** [comment]
Hi @budhrg I was wondering about this also. To me the ability to remove the add-on seems practical. Question is whether I am not alone here, I am curious what's the opinion of others from @minishift/minishift-dev.

Removal of anyuid is probably easy, [`oc adm policy remove-scc-from-group`](https://www.mankier.com/1/oc-adm-policy-remove-scc-from-group) could be just used, however the rest of add-ons might take much more work.

**Comment by hferentschik** [comment]
For the anyuid the removal could be easy indeed. The remove commands are optional and this feature came after we already had the existing default add-ons. 

Note, that a removal does not always make sense, depending on which commands are executed in the add-on. Some add-ons might not change the state of the cluster. No need to roll anything back there. So whether a .remove makes sense needs to be decided on a case per case basis. a .remove for anyuid seems reasonable. Not sure about the other add-ons.

**Comment by praveenkumar** [comment]
As @hferentschik said, it doesn't make sense or we can't force each addon to have a remove feature. I am closing this issue now if you folks have any strong opinions around it then we will reopen.

**Comment by praveenkumar** [comment]
As @hferentschik said, it doesn't make sense or we can't force each addon to have a remove feature. I am closing this issue now if you folks have any strong opinions around it then we will reopen.
