### ISSUE TITLE
Move integration.log from integration-test directory

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1461]
Having integration.log in integration-test directory causes problems in downstream. It will be better to move it from integration-test dir as this could cause further problems in future. The new location can be probably just `out/integration.log`.

**Comment by amitkrout** [comment]
It would be nice if the time stamp is appended to the log file something like ```integration_TismeStamp.log```. This will be very help full to keep record of all integartion test result rather overwriting the log file on each run.

**Comment by agajdosi** [comment]
This is needed to be a quick fix, so I am not going to add/change any not necessary functionality, but I agree: it would be nice. Please create a separate issue where we can discuss how others see this.

**Comment by agajdosi** [comment]
Merged via #1463.
