### ISSUE TITLE
Append timestamp to integration.log

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#1464]
It would be nice to append timestamp in integration test log file for example ```integration_YYYY-MM-DD_HH:MM:DD.log```

This will be very help full to keep record of all integartion test result rather overwriting the log file on each run.

**Comment by amitkrout** [comment]
#1461

**Comment by agajdosi** [comment]
Not critical and was not planned, moving to next milestone.

**Comment by anjannath** [comment]
@amitkrout How do i generate the `integration.log` file without running all the integration tests?

**Comment by agajdosi** [comment]
@anjannath The only way is to run the tests I think, but you can run just one feature and it will generate it. For example:

```
make integration GODOG_OPTS="-tags=cmd-version"
```

This should be quite fast (around 20secs) and creates no VM during the run.

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/pull/1490
