### ISSUE TITLE
`minishift start' fails with 'open config.json: The system cannot find the file specified'

### ISSUE THREAD

**Issue by dgolovin** [minishift/minishift#1468]
I was running minishift for a while, stopping and starting it. Then suddenly after several errors during 'minishift stop' it starts failing with message
```
open C:\Users\eskimo\.minishift\machines\minishift\config.json: The system cannot find the file specified'
```

Even if I do
``` shell
minishift config vm-driver virualbox
No Minishift instance exists. New vm-driver setting will be applied on next 'minishift start'
```
next 
``` shell
minishift start
open C:\Users\eskimo\.minishift\machines\minishift\config.json: The system cannot find the file specified.
```
still complains about missing config.json

**Comment by gbraad** [comment]
I am very curious about the errors during `m stop`. You have them?
This state might happen when configuration, like registration state, fails to write. This was `minishift` or `cdk`?

This can likely be solved by doing a `m delete`.

**Comment by dgolovin** [comment]
It was minishift v1.6.0.
I remember I was trying to do ```minishift delete``` when vm was running. It failed to delete virtualbox log file, because it was locked by running instance of virtualbox obviously. After that I started getting that error. The solution was killing virtualbox from task manager and then ```rm -rf %USERPROFILE%/.minishift```.

```m config``` worked properly and config.json had properties I defined.

**Comment by gbraad** [comment]
Closing as the issue seems to have been resolved (no information was provided).

Might have been an inconsistency in the state of the driver.

**Comment by tiny-dancer** [comment]
resolved same error by executing `rm -rf ~/.minishift` from the [uninstall docs](https://docs.openshift.org/latest/minishift/getting-started/uninstalling.html) and re-running `minishift start`

**Comment by nitsmrinal** [comment]
For windows the path would be C:\Users\<Username>\.minishift

**Comment by eranilkrsharma** [comment]
removing .minishift file from C:\Users\<<username.> helped to resolve this issue. 
Using minshift with HyperV on Windows 10

**Comment by tmeckel** [comment]
No need to remove the complete `.minishift` directory because that will also remove the downloaded ISO image from the `.minishift/cache`directory. The only directory that has to be removed, when a `minishift` deployment is corrupt, is the `machines` folder inside `.minishift`. This is valid for all platforms.
