### ISSUE TITLE
Remove the vendor directory and add it to .gitignore

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#147]
Personally, I'd like to remove the _vendor_ directory and just keep _glide.yaml_ and _glide.yaml_. As a developer this means you need after a first checkout run _glide install --strip-vendor_, but this takes only a few seconds (provided you have the dependencies in the Glide cache).

The benefits are that it becomes clear that one should not change anything in the _vendor_ directory. Also one cannot accidentally check in changes to this directory. It becomes also clear how dependencies are managed and how new ones are added.

One drawback might be that the very first time you use Glide to get the dependencies, it takes time to download everything. For me that's acceptable.

Thoughts?

**Comment by jimmidyson** [comment]
As discussed, committing vendor dir to source control is the geneal approach of both Kubernetes, OpenShift & a lot of other go projects. It means that dependencies are always up to date once a developer does a clone or pull without the need for another `glide install` step & continuously checking whether glide.yaml/lock have changed.

> As a developer this means you need after a first checkout run `glide install --strip-vendor`

No you don't need to run that at all - as a contributor you clone/pull the repo & can run the build immediately. Why do you think you need to run `glide install --strip-vendor`? Adding new dependencies is a case of running `glide get --strip-vendor your/new/dependency`. You then commit the changed files as you would any other file.

**Comment by hferentschik** [comment]
> As discussed, committing vendor dir to source control is the geneal approach of both Kubernetes, OpenShift & a lot of other go projects.

Sure, that does not make it right though and there are other projects which don't commit it, for example Almighty.

> It means that dependencies are always up to date once a developer does a clone or pull without the need for another glide install step

With the risk that whatever is in _vendor_ is not in sync with the current Glide config which can lead to problems when trying to update the _vendor_ directory, for example when adding a new dependency. 

> continuously checking whether glide.yaml/lock have changed.

> Why do you think you need to run glide install --strip-vendor

If we were to remove the _vendor_ directory. Then a developer would first need to run _glide install_. Right now he does not have to.

You really don't have to check. If you want to be on the safe side, you can just run _glide install_. If nothing has changed, it is pretty much a noop. Right now you have to check the commits to whether someone modifies the _vendor_ directory. Also not optimal.

**Comment by jimmidyson** [comment]
These kind of discussions really have no winner - both sides have what they want to do due to personal experience & both have their merits. I can't personally be bothered to waste any time discussing this so if you feel strongly about not committing vendor directory go for it.

**Comment by LalatenduMohanty** [comment]
@hferentschik @jimmidyson  IMO this discussion should happen in minikube as we inherited from them.

I have not much experience in go. But it seems we are not gaining much my checking in the vendors directory. With respect to make it easy for contributors , if we have good documentation around how user can contribute we would be good I think.

**Comment by jimmidyson** [comment]
@LalatenduMohanty I switched to glide because godep management is much harder, especially with forked dependencies that we quite often require when working with openshift. I'm happy to go our own way as long as we can manage dependencies appropriately. We've already diverged dependency wise anyway... It does mean that syncing dependencies with minikube is a bit trickier but whatever works for us we should adopt IMO.

**Comment by LalatenduMohanty** [comment]
@jimmidyson Agree. Lets go ahead with removing the vendor directory. 

@praveenkumar @budhrg Do you have any other opinions?

**Comment by budhrg** [comment]
> @budhrg Do you have any other opinions?

I am fine with removing vendor directory :+1:

**Comment by hferentschik** [comment]
Merged by pull request #164
