### ISSUE TITLE
Preflight: check if hypervisor is installed (VBox, libvirt, etc)

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1472]
For Hyper-V we check if the actual hypervisor is installed (by checking for the management tools `get-vmhost`), but we can also check for `VBoxManage` for VirtualBox and `virsh` for KVM/Libvirt. The check of VirtualBox might have to involve `GOOS`-checks and specific paths as I do not think it gets added to the system paths.

we might have to duplicate some of the effort as done in: https://github.com/docker/machine/blob/47068ae5853d2f7136155b09673ec4153d89972d/drivers/virtualbox/virtualbox_windows.go#L44, https://github.com/docker/machine/blob/47068ae5853d2f7136155b09673ec4153d89972d/drivers/virtualbox/virtualbox_linux.go#L35 and https://github.com/docker/machine/blob/47068ae5853d2f7136155b09673ec4153d89972d/drivers/virtualbox/virtualbox_darwin.go#L25 (seems darwin and linux are both in path)

### Todo
  * [x] KVM / Libvirt check  
    Merged with 2b005fb7ad8a16b00d91b5174a66e8e041c26145
  * [x] HyperV  
    Issue #1429 - af7bffc54d5e030af37a38419756dc82e2a159a0
  * [ ] VirtualBox

### Note
Addresses #1467

**Comment by gbraad** [comment]
@anjannath /cc: @LalatenduMohanty

**Comment by anjannath** [comment]
@gbraad I guess we could also check for `vboxmanage` in the path in linux? we have to determine the OS from `GOOS` and check on different location if it is windows?

**Comment by gbraad** [comment]
What remains to be done? I guess we need to record this in the issue as a
todo-list.

**Comment by anjannath** [comment]
XHyve and and VIrtualBox Checks are left to do here, your first [comment](https://github.com/minishift/minishift/issues/1472#issue-262288073) already has the list.

**Comment by gbraad** [comment]
OK, can't see this from the email ;-)

Note: this has to be pinned

**Comment by anjannath** [comment]
@gbraad We don't need to check if XHyve is installed as it is included in the driver. removing XHyve from the list. reference comment [minishift/pull#1822](https://github.com/minishift/minishift/pull/1822#discussion_r156330881)
