### ISSUE TITLE
Download OCP client binary from mirrors.openshift.com

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1475]
We now have OCP client binaries available to mirrors.openshift.com. This issue is for implement feature which will download it from there when CDK is used. We do need some kind of tag to make sure download the binary from dev.rh.c instead GitHub when provided.

P:S: Replaced //developers.redhat.com with mirrors.openshift.com

**Comment by gbraad** [comment]
Example (`oc 3.6`)
  * https://developers.redhat.com/download-manager/file/oc-3.6.173.0.21-windows.zip
  * https://developers.redhat.com/download-manager/file/oc-3.6.173.0.21-macosx.tar.gz
  * https://developers.redhat.com/download-manager/file/oc-3.6.173.0.21-linux.tar.gz

**Comment by praveenkumar** [comment]
@LalatenduMohanty Currently if you see we don't scrap downloading functionality from GitHub even for downstream (codebase is there and we just blocked `openshift-version` flag) if we implement it as part of upstream we can have a toggle which can be only changed as part of downstream to download clients from dev.rh.com, might be change `--ocp-tag` with `--ocp-version` which enable that toggle/flag.

**Comment by gbraad** [comment]
Added https://github.com/gbraad/minishift/tree/ocp a few days ago, but forgot mention it here :-s.

There are several issues with the build:

  * builds on mirror do not all refer to containers that exist on the registry for OSE (while those on dev.rh.c have)
  * they do not follow semantic versioning
  * why have a `--ocp-version` when we can use `--openshift-version` ?
  * at the moment looking for a build solution that can use a tag option

**Comment by praveenkumar** [comment]
> builds on mirror do not all refer to containers that exist on the registry for OSE (while those on dev.rh.c have)

@gbraad Right, I just matched some of the versions against what available to registry.access.redhat.com and looks like there is a diff. This is something we should mail and get more info.

> they do not follow semantic versioning

Right, Downstream OCP release doesn't follow semantic versioning at all.

> why have a --ocp-version when we can use --openshift-version ?

I think we have `--ocp-tag` as of now and once we able to download oc binary with the specified version like we do upstream then we should drop that --ocp-tag and only have --openshift-version.

> at the moment looking for a build solution that can use a tag option

Didn't able to follow this :(

**Comment by gbraad** [comment]
> > at the moment looking for a build solution that can use a tag option

> Didn't able to follow this :(

We need to be able to distinguish between either downstream or upstream, pretty much like `_test.go` and `_windows.go` does automatically, you can probably use tags `@cdk` and `@minishift` to control the build process (inclusion of code or not). haven't been able to try this yet... do you know if this can work?

**Comment by budhrg** [comment]
New location is https://mirror.openshift.com/pub/openshift-v3/clients/.

**Comment by gbraad** [comment]
Current implementation: https://github.com/gbraad/minishift/commit/8fadb2dfc12b102744e5365f745af6c2f7c04511

Remaining issues:

  * `semver` for OCP will not work (see next issue)
  * implementation should be controlled with compile tags, but this can help with semver needs (this is also done in the containers/image codebase)
  * ...

**Comment by gbraad** [comment]
tagged compile, is something like:

https://github.com/containers/image/blob/c8bcd6aa11c62637c5a7da1420f43dd6a15f0e8d/ostree/ostree_src.go#L1

**Comment by budhrg** [comment]
@gbraad Added support of progress bar https://github.com/budhrg/minishift/commits/issue-1475

Many refactoring is needed along with tagged compilation.

**Comment by budhrg** [comment]
Four subtasks:

- [x] Initial work by @gbraad 
- [x] Add progress bar
- [ ] Refactor code
- [ ] Use tag compilation

**Comment by budhrg** [comment]
> I am starting to get following error since rebase with upstream from last working change

Need to comment this 
https://github.com/minishift/minishift/blob/9feb6c4de44682775c7d18b7afe17d342580fae9/pkg/minishift/openshift/version/openshift_versions.go#L143-L158

**Comment by budhrg** [comment]
It's implemented in downstream and I don't think it is upstream specific.

I am voting to close it.

**Comment by LalatenduMohanty** [comment]
@budhrg Agree.
