### ISSUE TITLE
Add CDK related scenarios into integration tests

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1477]
This is a follow up issue for #1433. Related is also work on #1466.

Needed can be taken from this "condensed" file of CDK related scenarios of mine:

```gherkin
@cdk-only @cdk-specific
Feature: CDK adds several changes to behaviour of Minishift
Note: setup-cdk is being silently executed by test runner at the start of whole test suite.

  Scenario: User can get information about version of CDK
      When executing "minishift version" succeeds
      Then stdout should match
      """
      ^minishift v1\.[0-9]\.[0-9]\+[a-z0-9]{7,8}
      CDK v3\.[0-9]\.[0-9](-[0-9]{8})?-[0-9]\n$
      """

  Scenario: Setup-cdk can reinstall previous configuration of CDK
      When executing "minishift setup-cdk --force" succeeds
      Then stdout should contain
      """
      CDK 3 setup complete.
      """

  Scenario: Setup-cdk set minishift-rhel7 iso image to be used
      Then JSON config file "config/config.json" contains key "iso-url" with value matching "file:\/\/\/[\w\/\.-]*minishift-rhel7\.iso"

  Scenario: Setup-cdk set more memory to be used
      Then JSON config file "config/config.json" contains key "memory" with value matching "4096"

  Scenario: Setup-cdk installed and enabled specific addons
  CDK automatically installs and enables specific addons for user during setup-cdk.
      When executing "minishift addons list" succeeds
      Then stdout should contain
      """
      - admin-user     : enabled    P(0)
      - anyuid         : enabled    P(0)
      - xpaas          : enabled    P(0)
      """
       And JSON config file "config/config.json" contains key "addons.admin-user.Enabled" with value matching "true"
       And JSON config file "config/config.json" contains key "addons.anyuid.Enabled" with value matching "true"
       And JSON config file "config/config.json" contains key "addons.xpaas.Enabled" with value matching "true"

  Scenario: Enabled addons are used after minishift startup
     Given Minishift has state "Does Not Exist"
      When executing "minishift start" succeeds
      Then stdout should contain "Applying addon 'admin-user'"
       And stdout should contain "Add-on 'anyuid' changed the default security context constraints"
       And stdout should contain "XPaaS OpenShift imagestream and templates installed"

  Scenario: Getting information about OpenShift and kubernetes versions
  Prints the current running OpenShift version to the standard output.
     Given Minishift has state "Running"
      When executing "minishift openshift version" succeeds
      Then stdout should match
      """
      ^openshift v3\.[6-9]\.[0-9]+\.[0-9]+\.[0-9]+
      kubernetes v[0-9]+\.[0-9]+\.[0-9]+\+[0-9a-z]{10}
      etcd [0-9]+\.[0-9]+\.[0-9]+
      """
      
  Scenario: Deleting minishift
     Given Minishift has state "Running"
      When executing "minishift delete --force" succeeds
      Then Minishift should have state "Does Not Exist"
```

**Comment by agajdosi** [comment]
@amitkrout Just realized, this could be taken as part of #1470. WDYT?

**Comment by amitkrout** [comment]
@agajdosi i don't understand this ```@cdk-specific``` tag. As per the recent discussion only @cdk-only will be added to the feature file for cdk specific test.

Is there any requirement of this file ? or i misunderstood it

**Comment by agajdosi** [comment]
@amitkrout This file is copy-pasted from downstream PR. It is about individual scenarios which can be used in different places here in upstream. But probably it will be better if I will do it as it will require less communication. Please finish your PR and I will create new one from this. Sorry for complications.

**Comment by amitkrout** [comment]
@agajdosi np :) ack...

**Comment by hferentschik** [comment]
This is really downstream stuff, right? Would that not be tracked in JIRA?

**Comment by agajdosi** [comment]
@hferentschik Based on results question of #1433 these changes are planned to be implemented upstream, so the issue is here.

**Comment by amitkrout** [comment]
@hferentschik As per the feedback from #1433 , we are adding it to upstream repo.

**Comment by hferentschik** [comment]
@agajdosi This makes no sense to me. We discussed this before. We have the CDK specific modifications in the GitLab repo, why would you add the tests to Minishift. First, they don't run out of this repo, since it cannot even build the CDK. Secondly, it blurs the line between community and product. IMO these tests belong where they can also be run - in the CDK repo.

**Comment by agajdosi** [comment]
@hferentschik Yes, I know we agreed on this, then I had complaint/suggestion from @praveenkumar to not put more into downstream and complicate rebasing more. So I have created an issue here, to open and resolve this question finally. I have kept it for 10 days, to secure that everybody can raise his opinion. Only 2 responses were collected and both were positive. I have mentioned the issue several times, pinged Lala on that, no response.

However I have no problem implement this downstream or upstream, I would just be happy to walk on a stable ground.

**Comment by hferentschik** [comment]
> Yes, I know we agreed on this, then I had complaint/suggestion from @praveenkumar to not put more into downstream and complicate rebasing more

As said, this is a weak argument. We can discuss and see how we can improve any pain points downstream. 

> So I have created an issue here, to open and resolve this question finally. I have kept it for 10 days, to secure that everybody can raise his opinion.

Sure, no problem. As you know I was on vacation, so I had not seen this up to now.

> However I have no problem implement this downstream or upstream

IMO it needs to go downstream for various reasons. Maybe this needs to be once more discussed in a meeting.

**Comment by agajdosi** [comment]
> Sure, no problem. As you know I was on vacation, so I had not seen this up to now.

@hferentschik Yes, I know, it was unfortunate timing for this issue to come... Lets keep the discussion on #1433, I have reopened the issue.

**Comment by hferentschik** [comment]
Sure.

**Comment by agajdosi** [comment]
Closing this issue due to results of #1433. Changes will be implemented in downstream.
