### ISSUE TITLE
Build fails for master branch

### ISSUE THREAD

**Issue by LalatenduMohanty** [MiniShift/minishift#148]
Go build fails even if I create the workaround for #146 and created required jimmidyson/minishift
```
 $ go build
# github.com/jimmidyson/minishift/pkg/minikube/cluster
../../jimmidyson/minishift/pkg/minikube/cluster/openshift_caching.go:42: undefined: Asset

```

**Comment by jimmidyson** [comment]
@LalatenduMohanty You need to run `make build` - it's not go gettable as it does some build time generation (embedding binary assets) that require separate build step right now.

**Comment by LalatenduMohanty** [comment]
@jimmidyson My understanding was `go build` should work always even if we have Makefile for the project.

**Comment by LalatenduMohanty** [comment]
cc @hferentschik

**Comment by jimmidyson** [comment]
Your understanding isn't quite right. There are many, many examples of non go buildable projects, this is just one of them.

**Comment by hferentschik** [comment]
> You need to run make build - it's not go gettable as it does some build time generation (embedding binary assets) that require separate build step right now.

@jimmidyson OOI, Which assets are getting included? Can you point me to the code

> Your understanding isn't quite right. There are many, many examples of non go buildable projects, this is just one of them.

I think it is enough to make sure to run 'make' once, after that _go build_ works. I think this is essential, since otherwise IDE integration gets problematic. 

@LalatenduMohanty, can you run _make_ once and then _go build_?

**Comment by jimmidyson** [comment]
See https://github.com/MiniShift/minishift/blob/master/Makefile#L78-L79

Personally I just run make every time... it handles updating assets as required.

**Comment by jimmidyson** [comment]
Once we decide whether we're going to embed the OpenShift binary in MiniShift binary (I don't think we should any more if we're going `oc cluster up`) then we can remove this build step.

**Comment by hferentschik** [comment]
Right, so go-bindata is used to embed the _openshift_ binary - https://github.com/MiniShift/minishift/blob/master/Makefile#L78

This won't be required anymore once we use _cluster up_. For now we should be good.

**Comment by hferentschik** [comment]
See also issues #151

**Comment by LalatenduMohanty** [comment]
@jimmidyson @hferentschik `make` followed by `go build` does not fix the issue. It seems `make` is completing the build process and creating a minishift binary at the end. 
Also `make build` fails as there is no rule in the `Makefile` for `make build`.

```
$ make
mkdir -p /Users/lmohanty/code/gocode/src/github.com/MiniShift/minishift/_gopath/src/github.com/jimmidyson
ln -s -f /Users/lmohanty/code/gocode/src/github.com/MiniShift/minishift /Users/lmohanty/code/gocode/src/github.com/MiniShift/minishift/_gopath/src/github.com/jimmidyson
mkdir out 2>/dev/null || true
cd /Users/lmohanty/code/gocode/src/github.com/MiniShift/minishift/_gopath/src/github.com/jimmidyson/minishift && go run hack/get_openshift.go v1.3.1
Downloading OpenShift v1.3.1
 59.49 MB / 59.49 MB [==========================================================================================================================================================] 100.00% 0sDownloading OpenShift v1.3.1 checksums
 0 B / 947 B [---------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%
 947 B / 947 B [================================================================================================================================================================] 100.00% 0s
GOBIN=/Users/lmohanty/code/gocode/src/github.com/MiniShift/minishift/_gopath/bin go get github.com/jteeuwen/go-bindata/...
/Users/lmohanty/code/gocode/src/github.com/MiniShift/minishift/_gopath/bin/go-bindata -nomemcopy -o pkg/minikube/cluster/assets.go -pkg cluster ./out/openshift
CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build --installsuffix cgo -ldflags="-X github.com/jimmidyson/minishift/pkg/version.version=0.9.0 -X github.com/jimmidyson/minishift/pkg/version.openshiftVersion=v1.3.1 -s -w -extldflags '-static'" -o ./out/minishift-darwin-amd64 ./cmd/minikube
cp ./out/minishift-darwin-amd64 /Users/lmohanty/code/gocode/bin/minishift


Lalatendus-MacBook-Pro:minishift lmohanty$ go build
# github.com/jimmidyson/minishift/pkg/minikube/cluster
../../jimmidyson/minishift/pkg/minikube/cluster/openshift_caching.go:42: undefined: Asset
```
`make build` also returning error as there is no rule in Makefile for it.

**Comment by jimmidyson** [comment]
As I said above:

> Personally I just run make every time... it handles updating assets as required.

**Comment by LalatenduMohanty** [comment]
So it seems there is no standard way to deal of these kind of things.  So we should document the workflow we are following (even contribute it back to minikube).

**Comment by gbraad** [comment]
@LalatenduMohanty after doing #152 I can build with `GOPATH=`pwd`/_gopath make`
