### ISSUE TITLE
Improve profile documentation 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1485]
The profile documentation is currently very short and basically just list briefly the existing commands. We should explain the feature in more detail, providing background and context as well as some more examples.

**Comment by LalatenduMohanty** [comment]
We need to add that each profile have a separate home directory and what it means i.e. a separate config.jason files, separate cache etc. for each profile. Also if an user runs any command (e.g. config set) it by default runs against the current active profile. An example if how user can set globla config using environment variables at this moment. Also what is a typical work flow user can follow.

**Comment by robin-owen** [comment]
@hferentschik I'd love to help with this. Context is essential, especially when explaining a feature which is largely conceptual: "what is a profile, why would I want to use one, what can I do with it?"

> We need to add that each profile have a separate home directory and what it means i.e. a separate config.jason files, separate cache etc. for each profile.

@LalatenduMohanty Do you think it would also make sense to explain files which exist in **$MINISHIFT_HOME**, but _not_ in the "home" for each respective profile (for example, **_allinstances.json_**)?

> Also what is a typical work flow user can follow.

I would like to have more information about this. If I don't know what a typical workflow for using profiles looks like, I can't accurately write about it.

**Comment by LalatenduMohanty** [comment]
> @LalatenduMohanty Do you think it would also make sense to explain files which exist in $MINISHIFT_HOME, but not in the "home" for each respective profile (for example, allinstances.json)?

@robin-owen I do not think we need to explain the directory structure as it might be overkill for the user. 

Also I am planning to put the PR and you can review it.

**Comment by robin-owen** [comment]
> I do not think we need to explain the directory structure as it might be overkill for the user.

Agreed, a complete breakdown would be overkill -- I simply meant to mention the few files that exist in **$MINISHIFT_HOME** which all profiles make use of (I'm not sure if there are any more files than **_allinstances.json_** which fit this description).

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/pull/1605
