### ISSUE TITLE
Improvement: assign gateway based on given IP address

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1492]
Related to #1316 

An update/improvement can be to 'assume' `--network-gateway` from the given IP address `--network-ipaddress`, like ${IPADDRESS%.*}.1  This this does not have to be true, although it is in about 80% of the cases... especially on /24 networks

**Comment by gbraad** [comment]
```

```
ip := net.ParseIP(IPAddress)
ip = ip.To4()
ip[3] = 1
Gateway = ip
```

**Comment by budhrg** [comment]
It seems this issue is done as I see here https://github.com/minishift/minishift/projects/3#card-6247096

**Comment by LalatenduMohanty** [comment]
Resolved via #1849
