### ISSUE TITLE
cloud.docker.com instead of local registry/dockerhub

### ISSUE THREAD

**Issue by robdaems** [minishift/minishift#1494]
Hello,

Minishift uses it's local registry, dockerhub to get it's (base) images from.
But is it possible to use images from cloud.docker.com (private repo)

e.g when deploying a javascript project is starts from base image 'openshift/nodejs:6', but can I use my own images (in cloud.docker.com) as base image.

Br, Rob

**Comment by praveenkumar** [comment]
@robdaems I think you can change the base image from `openshift/nodejs:6` to `cloud.docker.com/<my_namespace>/<my_image>` in the template so that s2i pull the image from your provide registry instead docker hub.

**Comment by robdaems** [comment]
Minishift replies with "error: no match for "<my  repo on docker.cloud.com>"
May be it's working for public repo's in cloud.docker.com, but not for private, since a docker login is required.

**Comment by robdaems** [comment]
https://docs.openshift.com/enterprise/3.0/dev_guide/image_pull_secrets.html#allowing-pods-to-reference-images-from-other-secured-registries
