### ISSUE TITLE
Add integration test for deployment of EAP applications

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1498]
We should add a test which would check if image streams added by xpaas add-on are working. This check could consist of deploying several application templates from image stream. Planned steps are:

1   deploy template (e.g. oc new-app eap64-basic-s2i)
2    check endopoint of deployed application
3    delete everything in project (e.g. oc delete all --all)
4    repeat

**Comment by agajdosi** [comment]
I have a working prototype for this issue, which deploys and checks the `eap70-basic-s2i` template from xpaas image stream:

```gherkin
  Scenario: Deploy eap70-basic-s2i
   Given Minishift has state "Running"
    When executing "oc new-app eap70-basic-s2i" succeeds
    Then stdout should contain "Success"

  Scenario: Check
    When services "eap-app" rollout successfully
     And body of HTTP request to "/index.jsf" of service "eap-app" in namespace "myproject" contains "Welcome to JBoss!"
     And status code of HTTP request to "/index.jsf" of service "eap-app" in namespace "myproject" is equal to "200"

  Scenario: Delete all in project
    When executing "oc delete all --all" succeeds
    Then stdout should contain
     """
     service "eap-app" deleted
     """
```

Next steps will be to transform this into a Scenario Outline so we could test deployment of large number of JBoss and FSI application templates.

**Comment by hferentschik** [comment]
Merged via pull request #1657

**Comment by odockal** [comment]
@agajdosi Thanks!

**Comment by agajdosi** [comment]
@odockal Thanks for submitting idea for this test. Just want to add - for now the test is not a part of PR acceptance testing and we do not have nightly builds and tests. However the nightlys will come soon and then xpaas will be covered.

**Comment by odockal** [comment]
@agajdosi Sure thing. Alright, please, let me know when nightly will be available.
