### ISSUE TITLE
Improvement: add IP assignment support to minikube-iso

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1499]
Add support of IP assignment as implemented in #1316 to the minikube ISO

**Comment by gbraad** [comment]
The changes that were needed on our end (for the CentOS ISO) were as follows:

  * Add the `hvkvp` binary from http://files.gbraad.nl/hvkvp/  
    (or build from source: https://github.com/gbraad/go-hvkvp)
  * add a set script:

```
#!/bin/bash

NETWORK_SCRIPT=/var/lib/minishift/networking
HVNETWORKING=`hvkvp -key MINISHIFT_NETWORKING`
HVKVP_RESULT=$?

if [ $HVKVP_RESULT -eq 0 ] && [ ! -z "$HVNETWORKING" ]; then
  echo $HVNETWORKING | base64 --decode > $NETWORK_SCRIPT
fi

if [ -e $NETWORK_SCRIPT ]; then
  . $NETWORK_SCRIPT
  
  echo "Set temporary IP: $IPADDR"
  ip link set dev $DEVICE up
  ip a add $IPADDR/$NETMASK dev $DEVICE
  [ ! -z "$GATEWAY" ] && ip route add default via $GATEWAY dev $DEVICE
  [ ! -z "$DNS1" ] && echo "nameserver $DNS1" >  /etc/resolv.conf
  [ ! -z "$DNS2" ] && echo "nameserver $DNS2" >> /etc/resolv.conf
fi

exit 0
```
  * Allow fallback to using DHCP

Ref: https://github.com/gbraad/minishift-centos-iso/blob/8810bba6c13165ae62616c87488d113edc9ee61e/scripts/set-ipaddress

**Comment by gbraad** [comment]
Pinned

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by anjannath** [comment]
@gbraad Shall we close this now since minikube iso is deprecated..?

**Comment by budhram** [comment]
Looks like documentation is still saying we support `minikube iso`, creating a PR for that.
This issues says https://github.com/minishift/minishift/issues/2578 we have completely removed the minikube iso.

**Comment by budhram** [comment]
Closing it as remaining references of minikube iso has been taken care by PR https://github.com/minishift/minishift/issues/3025
