### ISSUE TITLE
Improvement: use a more generic solution for the VMDriver usage

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1503]
In #1316 (settings_windows.go) I do:

```go
func ConfigureNetworking(machineName string, networkSettings NetworkSettings) {
	// Instruct the user that this does not work for other Hypervisors on Windows
	if viper.GetString("vm-driver") != "hyperv" {
		fmt.Println(configureIPAddressMessage, configureIPAddressFailure)
		return
	}
```

this means we need to rely on `spf13/viper`. In #1288 it was suggested to find an alternative way to handle this situation more elegantly. Something like:

`minishiftConfig.VMDriver` or `minishiftConfig.IsHyperV`

**Comment by brian-avery** [comment]
@gbraad If I understand correctly, this issue is purely about creating a constant for the VMDriver rather than relying on reading the config each time, correct? I'd like to take this one.

**Comment by gbraad** [comment]
Either in code we have to consider an abstraction, to prevent reading the configuration each time, or consider something that sets a configuration for us in the form of booleans `IsHyperV`, `IsVirtualBox`,

Haven't looked into it too much to decide what is a nicer approach.

**Comment by budhrg** [comment]
Resolved via #1728 1728

**Comment by gbraad** [comment]
Reopening, as the solution asked for is not implemented

**Comment by LalatenduMohanty** [comment]
@gbraad I see that you have added the code as part of #1457 in #1849 . I am in the opinion of closing the issue as we had merged a code which addresses the issue in a way and #1457 is an further improvement.

**Comment by LalatenduMohanty** [comment]
Also we should be conservative re-opening an existing issue if it is closed because of an code change as it breaks our git commit history.
