### ISSUE TITLE
Update the Roadmap docs

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1504]
We need to update the roadmap docs [1] to match the current roadmap.
[1] https://github.com/minishift/minishift/blob/master/ROADMAP.adoc

**Comment by gbraad** [comment]
@LalatenduMohanty might be good to state here what the changes are...

**Comment by LalatenduMohanty** [comment]
@gbraad Not planning to change anything drastic. There were few items which were scheduled for older releases but we were not able to finish them. So we need to update the roadmap accordingly.

**Comment by gbraad** [comment]
I think we should look at the ROADMAP with better glasses, as some are long-term goals and not milestone specific. This gives the wrong idea and expectation.

**Comment by LalatenduMohanty** [comment]
@gbraad agree but it gives some sense of priority given to the major features. If you have an better idea how we can represent this differently than please let us know.

**Comment by gbraad** [comment]
We should not put an 'Epic' on a milestone, but rather on a long term schedule, in which we target a quarter.

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/pull/1677
