### ISSUE TITLE
What do we want to show about the the add-ons in the minishift start output?

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1505]
With #1342 getting fixed now there is no message in the console when add-ons are getting unpacked or getting installed.  So this is an issue to figure out if we want to  communicate something about it to the user i.e.
* Print the default add-ons names
or
* installed add-on names  
in the `minishift start` output. E.g. 

```
-- Installed addons : admin-user, anyuid, registry-route, xpaas 
```

**Comment by agajdosi** [comment]
So when I run `minishift info` and it installs the add-ons, I would like to get some kind of info about this. For me the old `installed default add-ons` or similar worked well. However more explicit version which prints names of installed add-ons seems also fine.

From integration tests point of view, currently the tests run `minishift info` before every feature, which is here to secure that these `installed addons...` messages will not soak into actual test run. So if add-on installation is planned also for `minishift info` command, then integration tests should live with it without any need for update AFAIU now.

**Comment by LalatenduMohanty** [comment]
@agajdosi Not sure which `minishift info` command you mentioned. We do not have a `minishift info` command in Minishift for sure.

**Comment by agajdosi** [comment]
@LalatenduMohanty Sorry for that. True, I meant `minishift addons list`. Somehow I mixed with docker probably...

**Comment by gbraad** [comment]
I think we should show a message when things go wrong or need attention, or as part of the startup feedback: "Installed and enabled addons ...". This can be seen as part of information that a person would like to know about, but only when he took an action. Another option could be to enrich `minishift status` with a specific `--addons` option (although this is to me a little far fecthed). Or, simply, why not `m addons list`?
