### ISSUE TITLE
Improvement: hosting location for the hvkvp binaries as used by the ISOs

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1506]
Currently the binaries (for go-hvkvp) are hosted on a generic web host, however, a good location to serve them for use by the image build process is recommended.

**Comment by gbraad** [comment]
What about copr? https://github.com/gbraad/go-hvkvp/issues/9

**Comment by LalatenduMohanty** [comment]
+1 for creating a copr repo and then giving access to other developers of Minishift.

**Comment by gbraad** [comment]
the Copr repo exists, but at the moment the spec build relies on just a simple packaging action from the binary release. It does not actually build it from the specfile.

**Comment by gbraad** [comment]
Have proposed a package https://bugzilla.redhat.com/show_bug.cgi?id=1524245

https://copr.fedorainfracloud.org/coprs/gbraad/go-hvkvp/

**Comment by praveenkumar** [comment]
@gbraad Is it still relevant or we can close it?

**Comment by gbraad** [comment]
The PR for the CentOS iso has merged. Closing

**Comment by gbraad** [comment]
https://github.com/minishift/minishift-centos-iso/pull/179
