### ISSUE TITLE
Switch dependency management from Glide to dep

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1507]
Glide is in support mode and no new feature development happens there. The community has aligned behind [dep](https://github.com/golang/dep) which behaves similar and is a candidate to be part of the official Go toolchain.

From the Glide homepage:

> The Go community now has the dep project to manage dependencies. Please consider trying to migrate from Glide to dep. If there is an issue preventing you from migrating please file an issue with dep so the problem can be corrected. Glide will continue to be supported for some time but is considered to be in a state of support rather than active feature development.

**Comment by gbraad** [comment]
The glide importer has since been removed: `cmd/dep/glide_importer.go` => https://github.com/golang/dep/blob/f88c2339516836dad313a6b8b6de8430f0cfa65f/cmd/dep/glide_importer.go (older version) It is a one-shot anyways... Import once, if it worked we move on...

**Comment by hferentschik** [comment]
I am not quite sure why this is part of the next sprint. Even though it is something we should do eventually, there is no need for doing this right now. This can easily become a time sink.

There are plenty of things which have a much higher value imo.

**Comment by gbraad** [comment]
> There are plenty of things which have a much higher value imo.

such as #1714

**Comment by hferentschik** [comment]
Or the "default" Virtual Switch.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1715
