### ISSUE TITLE
Remove the embedding of openshift binary into minishift

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#151]
Currently the _openshift_ binary is embedded into the _minishift_ binary. This won't be required anymore once we use _oc cluster up_. 

See also https://github.com/MiniShift/minishift/blob/master/Makefile#L78

Follows up on issue #141

**Comment by jorgemoralespou** [comment]
@hferentschik I doubt if you'll still need some actions be done with the openshift client (at least in the VM). 
I've found out myself that I still need it, when I want to configure the cluster and "oc cluster up" does not provide the switch. (e.g pipelines activating, for this I need to use openshift ex config" instead of sed, which is much nicer and less error prone. https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/plugins/oc-cluster#L81)

**Comment by jimmidyson** [comment]
@jorgemoralespou I wonder if we can do that in combination with `minishift ssh` somehow? Also we could just compile in the required code into minishift itself possibly.

**Comment by jorgemoralespou** [comment]
@jimmidyson How I don't know, but the truth is that "oc cluster up" is limited in it's abilities to configure further that what's provided by default, as I explained in my blog, there needs to be extended, or ... you get openshift engineering to provide those functions in the tool, which I'd love

At the end, once a cluster is provisioned, via "oc cluster up" there needs to be further configuration to satisfy many use cases. 

Again, how you can solve it in minishift I don't know, just wanted to let you guys know.

**Comment by praveenkumar** [comment]
>  you get openshift engineering to provide those functions in the tool, which I'd love

@jorgemoralespou do we have similar type of issue as feature request to openshift origin repo. if not then I think better to create a feature request and ask if that feasible for them to provide as part of `oc cluster` functionality.

**Comment by jorgemoralespou** [comment]
There's no issue but they left that clear to me in discussions that was
nothing they were looking to do. Now that the consumer is minishift and not
me they might be more tolerant.
I'm happy to support you if you open the issue. It will be easier than the
other way around.

**Comment by hferentschik** [comment]
Removal of asset inclusion into minishift binary was part of pull request #167
