### ISSUE TITLE
S2I : Use of own Dockerfile

### ISSUE THREAD

**Issue by robdaems** [minishift/minishift#1510]
Hello,

How can I use my own Dockerfile ?
I don't see anything in the UI to do this. Is this only possible via oc ?
Or not at all?

Br, Rob

**Comment by praveenkumar** [comment]
@robdaems I don't think you can directly use Dockerfile with oc command but I still redirect your query to @jorgemoralespou and @GrahamDumpleton.

**Comment by jorgemoralespou** [comment]
Yes, you can build your dockerImageRepoitory.

https://docs.openshift.org/latest/dev_guide/builds/build_strategies.html#docker-strategy-options

**Comment by gbraad** [comment]
This is not a specific Minishift question, but rather OpenShift in general. I suggest to read more about the S2I process on https://github.com/openshift/source-to-image and https://docs.openmshift.org/

Most common is to actually use S2I to use a build process, which results in a container that can run the application. A primer I wrote about at: http://gbraad.nl/blog/run-an-example-application-on-openshift.html

Another way is for instance you use the dockerfile to create an image, push this to a docker registry, and then deploy this as a container... and just run the container.  This I used for: https://github.com/gbraad/dockerfile-c9ide The result can be run as:

```
$ oc new-app gbraad/c9ide:f25 --name=c9ide
```

But you can also have the build run an application build by itself. I did this a while back with https://github.com/gbraad/openshift-asterisk

To run as mage (as the previous example)
```
oc new-app gbraad/openshift-asterisk:latest --name=asterisk
```

Or to run as a build, which is using something similar to the first suggestion.
```
oc new-app https://github.com/gbraad/openshift-asterisk.git --name=asterisk
```

**Comment by GrahamDumpleton** [comment]
This answers seem to have wandered off into talking about S2I when question was about Docker. Let me try and add my own comments on the original question.

> How can I use my own Dockerfile ?

The answer it yes, you can.

> I don't see anything in the UI to do this. Is this only possible via oc ?

It is difficult to setup a ``docker`` type build using a ``Dockerfile`` from the web console so I will skip that as probably not what you are going to want, so the easiest way is from the ``oc`` command line.

Simplest method if you have a hosted Git repository with a ``Dockerfile`` and all the bits in it need by the ``Dockerfile``, to turn that into an image, run:

```
oc new-build --name myimagename <git-repository-url>
```

or if you want to go direct to trying to deploy it as a web application image instead use:

```
oc new-app --name myimagename <git-repository-url>
oc expose svc/myimagename
```

Note that this method relies on ``oc`` command doing some analysis of files in the repo, so it needs to checkout the repository behind the scenes to the local computer first. So long as no files in the repo to make it think has stuff for specific language and that it should instead apply a S2I builder, it will eventually find the ``Dockerfile`` and setup the ``docker`` type build.

If it gets confused, tell it you want a ``docker`` build explicitly.

```
oc new-build --strategy docker --name myimagename <git-repository-url>
```

or:

```
oc new-app --strategy --name myimagename <git-repository-url>
```

If you don't have it in a Git repository, but a local directory only, then you need to instead use what is called a binary input build.

```
oc new-build --strategy docker --binary --name myimagename
oc start-build myimagename --from-dir=.
```

and if want to deploy:

```
oc new-app myimagename
```

If you had only a ``Dockerfile`` and no files with it, there is also a way of passing the contents of a ``Dockerfile`` direct to the command and the contents of it will be kept in the configuration of OpenShift when doing the build. Will skip how to do that now as usually you would have everything in a Git repository or file system.

Note that there are various requirements for how to set up a container image you build yourself to run in OpenShift with a default setup. So must be able to run as arbitrary user, needs to set up which port exposes the application etc etc. So beyond how to setup the build, you may have to contend with that and adjust how you image is built.

**Comment by gbraad** [comment]
@GrahamDumpleton 

> about S2I 

See title... I believe the OP is not clear about the process, and how things work.

**Comment by GrahamDumpleton** [comment]
We need to wait for OP then. All those S2I example show how to write your own S2I, and not really how to customise one, which the subject is suggestive of, which why pointing at them is confusing.

For customisation of the S2I process there are a few paths.

If needing to add extra system packages, you need to use a ``docker`` type build to create a new derived S2I builder. Few tricks to doing that, especially if want it to appear in the service catalog after.

If instead want to add additional actions before or after build, or before deploy, for a particular application, then can use override ``assemble`` or ``run`` scripts in the application source code repo, which run additional actions and then call original scripts.

If want to use an existing S2I builder base image to create your own custom S2I builder, specifying own ``assemble`` and ``run`` to do things differently, can either use a ``docker`` type build to replace them, or use a trick where can generate a new S2I builder as the result of an S2I build. No way of adding additional system packages using latter method though, only a ``docker`` build type.

So too many interpretations due to lack of clarity in the question. :-)

**Comment by robdaems** [comment]
As requested, my usecase a little bit more clarified:
I have a repo which I want to build/deploy (almost the same as the javascript template), but now with my own Dockerfile. 
If needed (for openshift), I can add the Dockerfile at a specific location in the repo.
I'd like to have the same build/deploy triggers, meaning automated build/deploy when code changes in repo.

**Comment by jorgemoralespou** [comment]
@robdaems this is the link I sent you.

You can add the Dockerfile to the root directory and just do:

oc new-app https://github.com/my-repo 

Additionally you can explicitly say to use the DOckerfile, as there might also be source code, and to be more explicit to the platform.

oc new-app https://github.com/my-repo --strategy=docker

And you can place the Dockerfile in a subdirectory, and tell the platform which subdir to use:

oc new-app https://github.com/my-repo --strategy=docker --context-dir=src/docker

**Comment by gbraad** [comment]
@robdaems please let us know if this worked for you... in that case we can close this question.

**Comment by robdaems** [comment]
When the Dockerfile is included in the repo, it's working, thanks.
