### ISSUE TITLE
Minikube ISO name does not show in the iso-url usage

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1512]
Currently on b2d and CentOS is shown in the usage and the documentation does not have information about minikube ISO [1].
```
$ minishift start --help | grep iso-url
      --iso-url string                  Location of the minishift ISO. Can be an URL, file URI or one of the following short names: [b2d centos]. (default "b2d")
```
[1] https://docs.openshift.org/latest/minishift/using/managing-minishift.html#choosing-iso-image

**Comment by gbraad** [comment]
At the moment I think this is done on purpose... however, I think some of this also needs to be behind a feature toggle.

**Comment by LalatenduMohanty** [comment]
@gbraad I understand your concerns but unless we do not expose the `minikube` ISO name in the usage I do not it will get any proper testing.  I would suggest that we expose the short name and mention in the documentation [1] that the ISO is newly added to Minishift and should be considered experimental. 
@minishift/minishift-dev  comments?

[1] https://docs.openshift.org/latest/minishift/using/managing-minishift.html#choosing-iso-image

**Comment by gbraad** [comment]
But when EnableExperimental is enabled I would say, as we have not performed any rigorous testing by ourselves.

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift/pull/1514
