### ISSUE TITLE
Introduce update-context command to fix Minishift instance when VM IP changes

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1515]
We have a lot of user feedback where the VM IP changes after change of host network and Minishift becomes unusable.It is has been a pain point for Minishift users. 

 Minikube has a command called `update-context` and it seems to fix the kubeconfig when VM IP changed between a stop->start. In our case we also need to update the OpenShift config. ATM I am not sure if this can be done but it worth a try. 

```
$ minikube update-context --help
Retrieves the IP address of the running cluster, checks it
			with IP in kubeconfig, and corrects kubeconfig if incorrect.

Usage:
  minikube update-context [flags]

```
Note: @minishift/minishift-dev  As discussed consider this as a spike.

**Comment by gbraad** [comment]
@csrwng Does OpenShift now provide a way to update the IP address in the configuration files?

**Comment by gbraad** [comment]
See comment https://github.com/minishift/minishift/issues/1508#issuecomment-334901665 for motivation and a possible case where this would have helped (however, a static address would prevent unnecessary trouble).

**Comment by csrwng** [comment]
@gbraad it doesn't. If you specify a numeric public ip address, it should use that.

**Comment by gbraad** [comment]
In our case it is mostly the certificates

```
 Error: Get https://192.168.99.100:8443/healthz/ready: x509: certificate is valid for 10.0.2.15, 127.0.0.1, 172.17.0.1, 172.30.0.1, 192.168.99.101, not 192.168.99.100 Error during 'cluster up' execution: Error starting the cluster.
```

**Comment by gbraad** [comment]
Determining the `ServerIP` and `AdditionalIPs` is done here:
https://github.com/openshift/origin/blob/c79599c62a5b5129b54fd21dffd5df40bda872c6/pkg/oc/bootstrap/docker/up.go#L802-L815

just curious where the actual certificate creation happens. /cc: @csrwng

**Comment by csrwng** [comment]
@gbraad certificates are generated when the openshift configuration is created:
https://github.com/openshift/origin/blob/master/pkg/oc/bootstrap/docker/openshift/helper.go#L336-L353

**Comment by praveenkumar** [comment]
https://docs.openshift.com/container-platform/3.3/install_config/redeploying_certificates.html#redeploying-master-certificates is something we need to do I think but right now this playbook reference to a different one, which has a lot of roles. @csrwng do we have any command from openshift side which can use to regenerate cluster cert not from `co cluster up` side so we can use openshift runner to generate?

**Comment by praveenkumar** [comment]
Another thing which I tried is to implement a method CreateCerts which should run before cluster up using @jorgemoralespou blog https://blog.openshift.com/local-development-self-signed-certificates/ but the problem is to make sure this run we do need `oc` binary as part of iso :( or we can pull down origin images first and use it execute but both look like dirty hack. Do `oc` have an option which it can create certs on a remote machine?

```golang
// CreateCerts create the certificate for oc cluster up.
func CreateCerts(config *ClusterUpConfig, clusterUpParams map[string]string, runner util.Runner) error {
	fmt.Println("-- Creating openshift certs ...", clusterUpParams[configCmd.HostConfigDir.Name], configCmd.HostConfigDir.Name)
	cmdArgs := []string{
		"adm", "ca", "create-master-certs",
		"--cert-dir=" + clusterUpParams[configCmd.HostConfigDir.Name],
		"--master=https://127.0.0.1:8443",
		"--public-master="+ "https://" + config.Ip + ":8443",
		"--hostnames=kubernetes,kubernetes.default,kubernetes.default.svc," +
			"kubernetes.default.svc.cluster,kubernetes.default.svc.cluster.local," +
			"localhost,openshift,openshift.default,openshift.default.svc," +
			"openshift.default.svc.cluster,openshift.default.svc.cluster.local," +
			"127.0.0.1,172.17.0.1,172.30.0.1" + config.Ip,
	}
	exitCode := runner.Run(os.Stdout, os.Stderr, config.OcPath, cmdArgs...)
	if exitCode != 0 {
		return errors.New("Error creating certs for the cluster.")
	}
	return nil
}
```

**Comment by csrwng** [comment]
Hi @praveenkumar I don't know of a command to generate certs on a remote machine. You can use 'oc adm create-master-certs' as you mention above, but it will create them locally. It may be worth investigating whether containerized openshift-ansible can be used with a simple hosts file that points to your vm for both master and node.

**Comment by gbraad** [comment]
Some good news and some bad news: with #1457 I can assign/change the IP address to the VM after it got started, but I have to delete part of the config to make it work on a restart:

```
C:\> minishift start
...
The server is accessible via web console at:
    https://192.168.99.100:8443

C:\>minishift ssh -- "echo REVWSUNFPWV0aDAKVVNFREhDUD15Cg== | base64 --decode | sudo tee /var/lib/minishift/networking-eth0 > /dev/null; echo REVWSUNFPWV0aDEKSVBBRERSPTE5Mi4xNjguOTkuMTAxCk5FVE1BU0s9MjQKR0FURVdBWT0xOTIuMTY4Ljk5LjEKRE5TPTEwLjAuMi4zCg== | base64 --decode | sudo tee /var/lib/minishift/networking-eth1 > /dev/null;"
C:\>minishift ssh -- "sudo rm -rf /var/lib/minishift/openshift.local.config"
C:\>minishift stop
C:\>minishift start
...
The server is accessible via web console at:
    https://192.168.99.101:8443

```

**Comment by praveenkumar** [comment]
@gbraad So I also tried something after removing `/var/lib/minishift/openshift.local.config` and looks like that regenerate this directory structure and also certs.

```
$ minishift start
[...]
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.110.215:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

$ minishift ssh -- "sudo rm -rf /var/lib/minishift/openshift.local.config"

$ minishift stop
Stopping local OpenShift cluster...
Cluster stopped.
<== Here I also recreated the docker-machine vnet so I will get a new IP ==>

$ minishift start
[...]
The server is accessible via web console at:
    https://192.168.100.215:8443
```

**Comment by gbraad** [comment]
Selectively removing a cert will fail the startup:

```
$ minishift ssh "sudo rm /var/lib/minishift/openshift.local.config/master/openshift-master*"
$ minishift stop
Stopping local OpenShift cluster...
Cluster stopped.
$ minishift start --iso-url file://$HOME/.minishift/cache/iso/custom/minishift-centos7.iso
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM .............. OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 30% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ... 
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   routing-suffix ... OK
   host-config-dir ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... 
   Deleted existing OpenShift container
-- Checking for openshift/origin:v3.6.0 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.42.175 as the server IP
-- Starting OpenShift container ... 
   Starting OpenShift using container 'origin'
FAIL
   Error: could not start OpenShift container "origin"
   Details:
     No log available from "origin" container

Error during 'cluster up' execution: Error starting the cluster.
```

**Comment by praveenkumar** [comment]
@LalatenduMohanty  @gbraad I am going to defer and change milestone for it until we have some plan to handle the creation of cert.

**Comment by mshahat** [comment]
@LalatenduMohanty i can see that the latest milestone was v1.14 a month ago. I've that installed `minishift v1.14.0+1ec5877`

any idea how to use minishift for more than few minutes ? 

Cheers,

**Comment by LalatenduMohanty** [comment]
@mshahat The issue is not resolved yet. 

> any idea how to use minishift for more than few minutes ?

Sorry I do not understand what you are saying here. Do you mean the IP of the VM changes every few minutes for you? If so that's an issue. I am struggling hard to reproduce the IP change ( I have two wifi networks) but have not able to reproduce even once.

**Comment by mshahat** [comment]
Well it mainly happens for me after stop then start again , every other time.

I am using virtualbox, but also happened with xhyve 

Cheers

**Comment by gbraad** [comment]
Hmmmm, that is weird. The lease is actually quite long.

Can you try to use the PR 1849? Please find me on IRC and I explain or
debug with you; gbraad @ freenode, #minishift

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by jorgemoralespou** [comment]
This issue is probably too difficult to address.

**Comment by LalatenduMohanty** [comment]
I am not planning to reopen this as I am not sure if this will be relevant when we move to local OpenShift solution for OpenShift 4.0

**Comment by budhram** [comment]
Agree :+1:
