### ISSUE TITLE
Profile set should create the profile and set it as active profile

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1518]
Currently `profile set` returns error if a profile does not exist. 
```
$ minishift profile set test123
Error: 'test123' is not a valid profile
```
But it will be useful if it creates a empty profile and sets it as an active profile for use cases where users wants to set config values for a profile and then want to start it. Here is an example

```
$ minishift profile set xyz
created an empty profile 'xyz' and set it as an active profile

$ minishift profile list
- minishift	Does Not Exist 
- xyz		Does Not Exist (active)

$ minishift config set memory 8GB

$ minishift start
```

**Comment by LalatenduMohanty** [comment]
CC @jorgemoralespou @hferentschik @praveenkumar

**Comment by praveenkumar** [comment]
@LalatenduMohanty thanks, I am assigning it to myself to get some idea around profile codebase.

**Comment by budhrg** [comment]
There is a discussion going on adding create command here https://github.com/minishift/minishift/issues/179.  

I assumed that `set` command has pre-requisite of existing profile. 
I feel with `profile set` has a different meaning altogether. 

`minishift profile create` would have been ideal command to achieve that.

**Comment by LalatenduMohanty** [comment]
@budhrg From an user experience point of view `profile set xyz` should set zyz as the active profile and we all agree to this. Now the question is if the profile does not exists, what should be the behavior. 

It seems users want to run the config set commands first to set parameters and then run `minishift start`. Also they want to set active profile before hand so that any config set commands  they run it would be against this profile. So I think we can extend profile set to create a profile if it does not exist. 

Regarding `minishift create` we still need to think about it.

**Comment by gbraad** [comment]
I think this is a side-effect which is not expected. This could lead to creating a multiple of profiles which are not intended. Think of the user who wants to set to a demo profile: `m profile set demo2`. But it doesn't exist and creates it... "Eh, that is not what I wanted?", so he actually moved to a config and execution context of something that is empty.

This is not the expected result of the command I performed.

**Comment by jorgemoralespou** [comment]
Agree. I don't like side effects.

I would warn the user that the profile does not exist, and then let him create. I would probably not add a create command, but add a flag to both "m profile set". This could be combined with the flag I describe here (https://github.com/minishift/minishift/issues/1517#issuecomment-335540444) to make template profiles

As an example:

```
$m profile set example
-- example profile does not exist, use --force if you want to create the profile
$m profile set example --force 
-- You're now in example profile
```


```
$m profile set example
-- example profile does not exist, use --force if you want to create the profile
$m profile set example --force --bare
-- Template profile example has been created. Remember you can not start a minishift instance with this profile.
```

**Comment by gbraad** [comment]
`--force` might not be a indicative term. rather name the flag `--create` to indicate the intent of the action.

**Comment by hferentschik** [comment]
I think the '--force' (or any other option) is really overkill. What do we try to mitigate here? There is no great cost in a wrongly created profile. Also if the profile does not exist, the message on the console will indicate that a new one got created. If this is a mistake the user can delete the profile. I think the option is not required. 

If an option, I'd go for _create_ though.

**Comment by praveenkumar** [comment]
> I think the '--force' (or any other option) is really overkill. What do we try to mitigate here? There is no great cost in a wrongly created profile. Also if the profile does not exist, the message on the console will indicate that a new one got created. If this is a mistake the user can delete the profile. I think the option is not required.

This is what I am thinking we anyway providing a message that given profile not exist but created and set as an active profile and it is a clear message. I don't have any strong argument about creating but #179 is something different. It is not about creating an profile but also keep track of all the options which use to start that profile so user don't need to provide same options during start-stop-start cycle.

**Comment by gbraad** [comment]
I still do not understand why `profile create` could not work. The defualt profile exists, so a create here is not necessary and people can understand this. For each other situation, having an explicit create makes sense. What is wrong with this?

**Comment by hferentschik** [comment]
+1 to what @praveenkumar says.

> This is what I am thinking we anyway providing a message that given profile not exist but created and set as an active profile and it is a clear message.

I think additional options are required where executing a command looses data or makes certain aspects of the system unusable. In this case just an additional directory potentially with a JSON is created. And it can easily be reverted. If you introduce '--create' the user needs to know beforehand whether the profile exists. If the user keeps using the same profile names over and over (I do), he does not want to think about whether the last time around he deleted the profile first and hence an additional '--create' would be required for the _profile set_ command.  

> I don't have any strong argument about creating but #179 is something different. 

Right. In fact in terms of #179 we said that it is most likely too late now to create this split between _create_ and _start_. Partly due to the fact that we want to be alingned with Minikube. The _create_ _start_ split was coming up in the context of profiles, since it was discussed as a potential solution (introducing profiles plus a create/start split) also on the Minikube side. However, this split was never implemented. At this stage I think #179 could almost be closed as out of date. 

It is not about creating an profile but also keep track of all the options which use to start that profile so user don't need to provide same options during start-stop-start cycle.

**Comment by hferentschik** [comment]
> I still do not understand why profile create could not work. 

Not saying that it could not work. In fact I would prefer a dedicated `profile create <NAME>` over the discussed `profile set --create <NAME>`. 

IMO though it is not needed. In my workflows I don't want to first determine whether the profile I am going to use already exists and whether I hence have to first do a `profile set --create <NAME>`.

What's about things like:

    $ minishift --profile foo start

Does this keep implicitly creating the profile or do you want to enforce the use of `profile set --create <NAME>` first?

**Comment by praveenkumar** [comment]
@gbraad it not about only the start/set command, right now if you try something like `minishift status --profile` behind the scene it does create the profile and says doesn't exist same with other commands. if you think we should force user to use `create` before any profile operation then that something different discussion.

**Comment by gbraad** [comment]
It seems some people want to create a profile beforehand, so give them that. But do not hide it inside another command.

If status wants to create a profile you have to fix this. Consistency is more important. And consistency you get with creating/allowing the user to have a mental model of the commands (expectation). Set should not create, as shouldn't status, while start is expected to do this...

**Comment by LalatenduMohanty** [comment]
> I still do not understand why profile create could not work. The defualt profile exists, so a create here is not necessary and people can understand this. For each other situation, having an explicit create makes sense. What is wrong with this?

I do not see value in create command. Because create will just create the profile but will not set it as active profile. Thinking from an user prospective , what I need is to make sure the config set commands for a profile then start the profile i.e. 

1. Run bunch of config set commands 
2. Install/enable some addons
3. Start the profile.

So even if we provide create the user will still need to run a `profile set` command to set it as active profile.  So I do not see value in doing create command at this point. 

Because `--profile` is a persistent flag `$ minishift profile set foo --profile foo` in current code will do the trick i.e. will create the profile and set it as active profile. So simplifying this will help I believe.

**Comment by LalatenduMohanty** [comment]
@gbraad I am little confused by your comments, are you advocating for `minishift profile create` command or `minishift profile set PROFILE_NAME --create`?

**Comment by LalatenduMohanty** [comment]
So more and more I think about this `minishift profile set PROFILE_NAME` makes perfect sense as the command supposed to set the active profile. That's a fair expectation and if a profile does not exist it should create it. Otherwise the user has to run another extra command i.e. create without getting anything substantial in return.  Regrading the concern around user mistakenly running it , I do not think  we should take this in to account as there are many ways user can screw up the setup.

Here are the two use cases we are talking about.
```
$ minishift profile set demo
$ minishift config set vm-driver virtualbox
$ minishift config set CPU 2
$ minishift config set memory 8GB
$ minishift addon enable admin-user
$ minishift start
```
VS

```
```
$ minishift profile create demo
$ minishift profile set demo
$ minishift config set vm-driver virtualbox
$ minishift config set CPU 2
$ minishift config set memory 8GB
$ minishift addon enable admin-user
$ minishift start
```

**Comment by gbraad** [comment]
3.

**Comment by LalatenduMohanty** [comment]
As discussed with @minishift/minishift-dev we agreed to have `profile set` set the profile as active profile even if the profile does not exist. It is important to note that it does not create any directory structure but only sets the profile as active profile.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1540
