### ISSUE TITLE
Using minishift with Hyper-V is crashing 

### ISSUE THREAD

**Issue by Emmanuel35** [minishift/minishift#1521]
# Description
On windows 10 pro 
Hyper-V enable
Minishift v3.6

# Installation
Add virtual swith called "externe"

# Command

```
set HYPERV_VIRTUAL_SWITCH=externe

minishift start --show-libmachine-logs -v 5 --vm-driver hyperv
-- Checking if Hyper-V driver is configured ... panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x5dc1cc]

goroutine 1 [running]:
panic(0xa53080, 0xc04200a090)
        /usr/local/go/src/runtime/panic.go:500 +0x1af
github.com/minishift/minishift/pkg/minishift/shell/powershell.(*PowerShell).Execute(0xc0421136e0, 0xb1ce48, 0x20, 0x7, 0xc04213c3c0, 0xb15ea2, 0x18)
        /home/minishift_ci/gopath/src/github.com/minishift/minishift/pkg/minishift/shell/powershell/powershell.go:34 +0x2c
github.com/minishift/minishift/cmd/minishift/cmd.checkHypervDriver(0xb15ea2)
        /home/minishift_ci/gopath/src/github.com/minishift/minishift/cmd/minishift/cmd/start_preflight.go:242 +0x7b
github.com/minishift/minishift/cmd/minishift/cmd.preflightCheckSucceedsOrFails(0xb15c4a, 0x18, 0xb6ff88, 0xb22e23, 0x28, 0xc042209a00, 0xb15ea2, 0x18, 0xb2ee4f, 0x42)
        /home/minishift_ci/gopath/src/github.com/minishift/minishift/cmd/minishift/cmd/start_preflight.go:136 +0x1f7
github.com/minishift/minishift/cmd/minishift/cmd.preflightChecksBeforeStartingHost()
        /home/minishift_ci/gopath/src/github.com/minishift/minishift/cmd/minishift/cmd/start_preflight.go:65 +0x117
github.com/minishift/minishift/cmd/minishift/cmd.runStart(0xc0422f8000, 0xc04210e3c0, 0x0, 0x5)
        /home/minishift_ci/gopath/src/github.com/minishift/minishift/cmd/minishift/cmd/start.go:154 +0x2f3
github.com/minishift/minishift/vendor/github.com/spf13/cobra.(*Command).execute(0xc0422f8000, 0xc04210e370, 0x5, 0x5, 0xc0422f8000, 0xc04210e370)
        /home/minishift_ci/gopath/src/github.com/minishift/minishift/vendor/github.com/spf13/cobra/command.go:651 +0x453
github.com/minishift/minishift/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xe93b40, 0x0, 0x0, 0x0)
        /home/minishift_ci/gopath/src/github.com/minishift/minishift/vendor/github.com/spf13/cobra/command.go:726 +0x36e
github.com/minishift/minishift/vendor/github.com/spf13/cobra.(*Command).Execute(0xe93b40, 0xc042209f50, 0xc042209f50)
        /home/minishift_ci/gopath/src/github.com/minishift/minishift/vendor/github.com/spf13/cobra/command.go:685 +0x32
github.com/minishift/minishift/cmd/minishift/cmd.Execute()
        /home/minishift_ci/gopath/src/github.com/minishift/minishift/cmd/minishift/cmd/root.go:137 +0x34
main.main()
        /home/minishift_ci/gopath/src/github.com/minishift/minishift/cmd/minishift/main.go:26 +0x20`
```

# Expected
minishift VM created on Hyper-V supervisor.

**Comment by budhrg** [comment]
@Emmanuel35 , 

Can you try with `minishift start --show-libmachine-logs -v 5 ` (**Without `--vm-driver hyperv`**) ? `Hyper-V` is default driver for Windows.

**Comment by Emmanuel35** [comment]
same trace...

**Comment by gbraad** [comment]
You can skip the check with

```
minishift config set skip-check-hyperv-driver true
```


This way you can at least start.

But which version do you run? There is no minishift 3.6.0... Is this CDK? Also, are yiunon a multilingual install of Windows... Innither words, localized in French or other language?

**Comment by gbraad** [comment]
It fails on Powershell, so likely on

https://github.com/minishift/minishift/blob/79c0fa9faad30892d664edb70a4e260d4046ab93/cmd/minishift/cmd/start_preflight.go#L303

or

https://github.com/minishift/minishift/blob/79c0fa9faad30892d664edb70a4e260d4046ab93/cmd/minishift/cmd/start_preflight.go#L315

Maybe localization causes an issue in the second fucntion. I suggest to run these commands in a power shell session and see if the respond correctly.

**Comment by gbraad** [comment]
Do you run these commands from a command prompt? And if so, can you start powershell from the command prompt? Maybe path us modified and powershell can not be started correctly.

**Comment by Emmanuel35** [comment]
Hi Gerard,

I will try it:
@(Get-Command Get-VM).ModuleName
@([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole("Hyper-V
Administrators")

I was rebase with VirtualBox. But I have some crash with it...

My windows is well a French version.

Emmanuel

2017-10-10 16:58 GMT+02:00 Gerard Braad <notifications@github.com>:

**Comment by gbraad** [comment]
VirtualBox also fails? It is best to do`minishift delete` before each attempt.

**Comment by Emmanuel35** [comment]
Hi,

Creation and use are well with VirtualBox.
Just some windows crash (blue screen) which I must analyse with more
precision.

Regards,
Emmanuel

Le 11 oct. 2017 10:47 AM, "Gerard Braad" <notifications@github.com> a
écrit :

**Comment by gbraad** [comment]
Do you have HyperV and VirtualBox installed on the same machine?

**Comment by Emmanuel35** [comment]
Hi,

Environment:
- Windows 10 Pro French
- User is Administrator
- PowerShell run as Administrator

Starting environment:
- minishift delete --clear-cache
- Install Hyper-V functionnality

After windows restart:
'PS C:\RedHat\MiniShift> minishift version
minishift v1.6.0+7a71565
PS C:\WINDOWS\system32> @(Get-Command Get-VM).ModuleName
Hyper-V
PS C:\WINDOWS\system32>
@([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole("Hyper-V
Administrators")
False'

Hyper-V:
- Add network named: "minishift-network"

Creation of minishift:
'PS C:\RedHat\MiniShift> $env:HYPERV_VIRTUAL_SWITCH="minishift-network"
PS C:\RedHat\MiniShift> minishift start --show-libmachine-logs -v 5
-- Checking if Hyper-V driver is configured ... panic: runtime error:
invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x5dc1cc]

goroutine 1 [running]:
panic(0xa53080, 0xc04200a080)
        /usr/local/go/src/runtime/panic.go:500 +0x1af
github.com/minishift/minishift/pkg/minishift/shell/powershell.(*PowerShell).Execute(0xc04200b8e0,
0xb1ce48, 0x20, 0x11, 0xc04213a4b0, 0xb15ea2, 0x18)
        /home/minishift_ci/gopath/src/
github.com/minishift/minishift/pkg/minishift/shell/powershell/powershell.go:34
+0x2c
github.com/minishift/minishift/cmd/minishift/cmd.checkHypervDriver(0xb15ea2)
        /home/minishift_ci/gopath/src/
github.com/minishift/minishift/cmd/minishift/cmd/start_preflight.go:242
+0x7b
github.com/minishift/minishift/cmd/minishift/cmd.preflightCheckSucceedsOrFails(0xb15c4a,
0x18, 0xb6ff88, 0xb22e23, 0x28, 0xc04220ba00, 0xb15ea2, 0x18, 0xb2ee4f,
0x42)
        /home/minishift_ci/gopath/src/
github.com/minishift/minishift/cmd/minishift/cmd/start_preflight.go:136
+0x1f7
github.com/minishift/minishift/cmd/minishift/cmd.preflightChecksBeforeStartingHost()
        /home/minishift_ci/gopath/src/
github.com/minishift/minishift/cmd/minishift/cmd/start_preflight.go:65
+0x117
github.com/minishift/minishift/cmd/minishift/cmd.runStart(0xc04200e240,
0xc042005560, 0x0, 0x3)
        /home/minishift_ci/gopath/src/
github.com/minishift/minishift/cmd/minishift/cmd/start.go:154 +0x2f3
github.com/minishift/minishift/vendor/github.com/spf13/cobra.(*Command).execute(0xc04200e240,
0xc0420054d0, 0x3, 0x3, 0xc04200e240, 0xc0420054d0)
        /home/minishift_ci/gopath/src/
github.com/minishift/minishift/vendor/github.com/spf13/cobra/command.go:651
+0x453
github.com/minishift/minishift/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xe93b40,
0x0, 0x0, 0x0)
        /home/minishift_ci/gopath/src/
github.com/minishift/minishift/vendor/github.com/spf13/cobra/command.go:726
+0x36e
github.com/minishift/minishift/vendor/github.com/spf13/cobra.(*Command).Execute(0xe93b40,
0xc04220bf50, 0xc04220bf50)
        /home/minishift_ci/gopath/src/
github.com/minishift/minishift/vendor/github.com/spf13/cobra/command.go:685
+0x32
github.com/minishift/minishift/cmd/minishift/cmd.Execute()
        /home/minishift_ci/gopath/src/
github.com/minishift/minishift/cmd/minishift/cmd/root.go:137 +0x34
main.main()
        /home/minishift_ci/gopath/src/
github.com/minishift/minishift/cmd/minishift/main.go:26 +0x20'

PS: Docker Community edition is working well with HyperV.

Emmanuel

2017-10-12 7:17 GMT+02:00 Gerard Braad <notifications@github.com>:

**Comment by chrisfalter** [comment]
It is possible to switch between Hyper-V and VirtualBox on Windows 10 by using the Hyper-V Manager and rebooting. However, minishift seems to insist on trying to use VirtualBox once it finds that VirtualBox has been installed at some point in history on Windows. That was the behavior that I experienced with minishift 1.5.x (see #1335).

**Comment by Emmanuel35** [comment]
I dont't undertand by it is not working.
Docker Community Edition is working well.

I will use VirtualBox !

Emmanuel

2017-10-12 18:15 GMT+02:00 Christopher Falter <notifications@github.com>:

**Comment by gbraad** [comment]
@Emmanuel35 
have you used:  `minishift config set skip-check-hyperv-driver true` as suggested to bypass the check?

**Comment by Emmanuel35** [comment]
Hi Gerard,

With with, minishift install b2b and oc.
But:
* I need to add Powershell to my Path.

On starting, docker machine use a IPV v6. I was not able to use it :-( .
I rollback to VirtualBox. It is working better.

Thanks all for your help.

Emmanuel

2017-10-14 10:33 GMT+02:00 Gerard Braad <notifications@github.com>:

**Comment by gbraad** [comment]
To avoid IPv6, you need an external Virtual Switch that has a local DHCP
server handing out IPv4 addresses,or assign one on HyperV +centos with the
functionality as described in #1316

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by gbraad** [comment]
@Emmanuel35 can you test if the earlier issue, as described in the first message, still occurs for: http://artifacts.ci.centos.org/minishift/minishift/pr/1566/windows-amd64/ ?
If not, please close the issue.

**Comment by gbraad** [comment]
Does minishift still crash when checking the user group membership for the version I mentioned in the previous comment?

**Comment by budhrg** [comment]
Closing it as the OP has switched to Virtualbox instead of HyperV.
