### ISSUE TITLE
./minishift status --profile ProfileName returns wrong profile name

### ISSUE THREAD

**Issue by odockal** [minishift/minishift#1524]
Above mentioned command returns wrong profile name in status output:

[odockal@odockal-pc cdk-3.2.0]$ ./minishift status --profile test
Minishift:  Stopped
Profile:    **test**
OpenShift:  Stopped
DiskUsage:  Unknown
[odockal@odockal-pc cdk-3.2.0]$ ./minishift profile list
minishift	Running
test		Stopped	(active)
[odockal@odockal-pc cdk-3.2.0]$ ./minishift status --profile minishift
Minishift:  Running
Profile:    **test**
OpenShift:  Running (openshift v3.6.173.0.21)
DiskUsage:  11% of 18G

**Comment by praveenkumar** [comment]
Resolved by #1525
