### ISSUE TITLE
minishift openshift config set fails on Windows 7 and 10

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1530]
`minishift openshift config set` fails to setup the config on Windows 7. Also it gives wrong exit code, which masks that the setup of config actually failed:

```
C:\Users\CDKQE> minishift openshift config set --patch "{\"assetConfig" : { \"logoutURL\" : \"http://www.minishift.io\"}}
Patching OpenShift configuration /var/lib/origin/openshift.local.config/master/master-config.yaml with {"assetConfig" : { "logoutURL" : "http://www.minishift.io"}}
    ssh command error:
    command : sudo echo 'admissionConfig:
      pluginConfig:
        openshift.io/ImagePolicy:
          configuration:
            apiVersion: v1
            executionRules:
[...]
    servingInfo:
      bindAddress: 0.0.0.0:8443
      bindNetwork: tcp4
      certFile: master.server.crt
      clientCA: ca.crt
      keyFile: master.server.key
      maxRequestsInFlight: 1200
      namedCertificates: null
      requestTimeoutSeconds: 3600
    templateServiceBrokerConfig: null
    volumeConfig:
      dynamicProvisioningEnabled: true
    ' | sed 's/.$//' | sudo tee /var/lib/minishift/openshift.local.config/master/master-config
    .yaml > /dev/null
    err     : exit status 1
    output  : bash: -c: line 164: unexpected EOF while looking for matching `''
    bash: -c: line 288: syntax error: unexpected end of file
     
    Restarting OpenShift
     
C:\Users\CDKQE>echo %errorlevel%
0
```

With integration tests I am facing this issue only on Windows 7. Linux and macOS are fine. Windows 10 I was unable to check.

**Comment by hferentschik** [comment]
Most likely a quoting issue.

**Comment by agajdosi** [comment]
@hferentschik Might be, trying to figure out the right schema to fix integration tests. But even then there is still a problem with bad exit code, which should not be 0 when the command being run inside of the VM returns error.

**Comment by agajdosi** [comment]
@hferentschik Command `minishift openshift config set --patch "{\"corsAllowedOrigins\": [\".*\"]}"` which we have in documentation for Windows's Command line does not work also. And I know that this worked before as I have tested these alternatives for cmd and powershell. Looks like regression.

**Comment by gbraad** [comment]
We have to create testcases around this behaviour:

https://github.com/minishift/minishift/blob/master/docs/source/openshift/openshift-client-binary.adoc#example-configuring-cross-origin-resource-sharing

**Comment by agajdosi** [comment]
@gbraad There is a test around this: https://github.com/minishift/minishift/blob/master/test/integration/features/cmd-openshift.feature#L110. Found this issue this way on Windows 7. But if we are going also for escaping problematic with different shells the #1332 will be needed before.

**Comment by agajdosi** [comment]
@gbraad Tried as we talked, `minishift openshift config set --patch '{"corsAllowedOrigins": [".*"]}'` works well on RHEL 7.4.

**Comment by agajdosi** [comment]
Failing on both Windows 7 and 10, with cmd and also with PowerShell. (Tested with CDK 3.2.0 RC1).

**Comment by gbraad** [comment]
must be a regression, but I do not remember we touched this code...

**Comment by gbraad** [comment]
PowerShell

```
PS C:\work\src\github.com\minishift\minishift\out\windows-amd64> .\minishift.exe openshift config set --patch '{\"corsAl
lowedOrigins\": [\".*\"]}'
Patching OpenShift configuration /var/lib/origin/openshift.local.config/master/master-config.yaml with {"corsAllowedOrigins": [".*"]}
Restarting OpenShift
```

**Comment by gbraad** [comment]
Command Prompt (win10)

```
c:\work\src\github.com\minishift\minishift\out\windows-amd64>minishift openshift config set --patch "{\"corsAllowedOrigins\": [\".*\"]}"
Patching OpenShift configuration /var/lib/origin/openshift.local.config/master/master-config.yaml with {"corsAllowedOrigins": [".*"]}
Restarting OpenShift
```

![image](https://user-images.githubusercontent.com/1894/31983602-85b4b398-b990-11e7-9ca5-a9450fa7a880.png)

**Comment by gbraad** [comment]
| prompt | legacy? | working? |
|---|---|---|
| Command Prompt (win10) |  | ✓ |
| PowerShell (win10) |  | ✓ |
| Command Prompt (win10) | ✓ | ✓ |
| PowerShell (win10) | ✓ | ✓ |

**Comment by budhrg** [comment]
hi @agajdosi ,

Now, not able to reproduce in the affected Win 10 provided by you.

```
C:\Users\CDKQE>minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Running (openshift v3.6.0+c4dd4cf)
DiskUsage:  12% of 18G

C:\Users\CDKQE>minishift openshift config set --patch "{\"corsAllowedOrigins\": [\".*\"]}"
Patching OpenShift configuration /var/lib/origin/openshift.local.config/master/master-config.yaml with {"corsAllowedOrigins": [".*"]}
Restarting OpenShift

# ---------------------------------------- PowerShell ----------------------------
PS C:\Users\CDKQE\go\src\github.com\minishift\minishift> minishift openshift config set --patch '{\"corsAllowedOrigins\": [\".*\"]}'
Patching OpenShift configuration /var/lib/origin/openshift.local.config/master/master-config.yaml with {"corsAllowedOrigins": [".*"]}
Restarting OpenShift

```

**Comment by budhrg** [comment]
With affected Windows 7

```
PS C:\Users\CDKQE> ./minishift version
minishift v1.7.0+26a37b4

PS C:\Users\CDKQE> ./minishift openshift config set --patch '{\"corsAllowedOrigins\": [\".*\"]}'
Patching OpenShift configuration /var/lib/origin/openshift.local.config/master/master-config.yaml with {"corsAllowedOrigins": [".*"]}
Restarting OpenShift

#-------------------------- CMD -------------------------------
C:\Users\CDKQE>minishift.exe version
minishift v1.7.0+26a37b4

C:\Users\CDKQE> minishift.exe openshift config set --patch "{\"corsAllowedOrigins\": [\".*\"]}"
Patching OpenShift configuration /var/lib/origin/openshift.local.config/master/master-config.yaml with {"corsAllowedOrigins": [".*"]}
Restarting OpenShift
```

**Comment by budhrg** [comment]
Hi @agajdosi , please verify again.

**Comment by agajdosi** [comment]
This issue is no longer reproducible for me on Windows or Fedora. Will reopen if I face it again.
