### ISSUE TITLE
Add Minikube ISO as part of integration tests.

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1532]
Recently we have added support for Minikube ISO i.e. https://github.com/minishift/minishift/issues/1058 to Minishift. However we do not run any tests of Minishift on it.  We should add Minikube ISO as another ISO in our integration tests. 

PS: Updated the description as discussed in #1552

**Comment by amitkrout** [comment]
@LalatenduMohanty i got the abstract of the issue however this confuses me when Minikube ISO comes to picture. In [minishift](https://github.com/minishift) repo as we have ISO like centos, b2d. The question is where we can get latest release minikube iso? are we maintaining any repo for this or referring to some other location? How i attach it to minishift start ?

**Comment by agajdosi** [comment]
@amitkrout From this line https://github.com/kubernetes/minikube/blob/master/pkg/minikube/constants/constants.go#L103 and https://github.com/kubernetes/minikube/blob/master/Makefile#L29 the location should be: https://storage.googleapis.com/minikube/iso/minikube-v0.23.5.iso

**Comment by praveenkumar** [comment]
> The question is where we can get latest release minikube iso? 

you can get released iso from https://storage.googleapis.com/minikube/iso/minikube-v<iso_version>.iso

>are we maintaining any repo for this or referring to some other location? 

We are not maintaining any repo for this ourself and it's complete on minikube side. 

>How i attach it to minishift start ?

`minishift start --iso-url minikube`

**Comment by amitkrout** [comment]
I use ```minishift start --iso-url https://storage.googleapis.com/minikube/iso/minikube-v0.23.5.iso``` instead of ```minishift start``` and run integration test with all the [features](https://github.com/minishift/minishift/tree/master/test/integration/features) one by one (including coolstore). I dont see any major functionlity issue, though there is some failure. For example 
```
Command 'ssh -- cat /var/lib/boot2docker/profile' did not execute successfully. cmdExit: 1, cmdErr: cat: /var/lib/boot2docker/profile: No such file or directory
Command failed: exit status 1
```
```
Output did not match. Expected: 'Disk \/dev\/sda: 2[4-6]\.?[0-9]{0,2} GB', Actual: 'Disk /dev/sda: 24.4 GiB,26214400000 bytes, 51200000 sectors
Disklabel type: dos
Disk identifier: 0x9c76f717
```
>  I would suggest to run the tests on the ISO as a separate job in ci.centos.org. However I am open to other suggestions too.

+1. If we make it parallel execution that  will cost us  less

**Comment by agajdosi** [comment]
@amitkrout We need to fix these errors, second one should be easy, just failing on GB vs GiB. First one will need some code changes as `/var/lib/boot2docker/profile` is not a valid location for minikube.iso.

**Comment by amitkrout** [comment]
@agajdosi right

**Comment by budhrg** [comment]
> @amitkrout We need to fix these errors, second one should be easy, just failing on GB vs GiB. First one will need some code changes as /var/lib/boot2docker/profile is not a valid location for minikube.iso.

@amitkrout @agajdosi anyone working on it? Since, it is CI task so I had assigned myself and then found we need to fix few features file to adapt with minikube ISO.

**Comment by agajdosi** [comment]
@budhrg Will start on it today as discussed on IRC.

**Comment by amitkrout** [comment]
Sorry i was away for some time. @agajdosi if you are overburden with this task please feel free to assign to my name. cc_ @budhrg

**Comment by agajdosi** [comment]
@budhrg Adding the support for Minikube iso in opened PR #1552.
