### ISSUE TITLE
Improve beforeFeature() and beforeSuite() parts in integration tests

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1535]
In case of beforeFeature() the Godog is running it even if the feature is not selected with tags. Would be nice to skip this part to omit not needed operations.

For beforeSuite() the setUp(), ensureTestDirEmpty() and other involved functions in some places lack the checks for errors. For example if there is problem with deletion of files due to permission problems, these errors are silently ignored.

**Comment by agajdosi** [comment]
I looked on what could be used to get information if feature should or should not be run to skip the beforeFeature(). It can be done by mimicing tag matching of Godog. To not duplicate the functionality I have open an issue in Godog: https://github.com/DATA-DOG/godog/issues/104. Based on reaction I can wait or help there with implementation, or if rejected I will then open a follow up issue here.

Now working on rest of the issue.

**Comment by agajdosi** [comment]
Found out issue with closing the log when I have added the error checks: `Error closing the log: invalid argument`. Will investigate more.

**Comment by agajdosi** [comment]
> Hi, yes should be fixed in the near future, thanks for reporting that

The beforeFeature() will be fixed in Godog.

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/pull/1558
