### ISSUE TITLE
Minishift's 'status' and 'profile list' should be aware of already created specific profile with 'setup-cdk --profile ProfileName'

### ISSUE THREAD

**Issue by odockal** [minishift/minishift#1537]

**Comment by praveenkumar** [comment]
@odockal Can you please add some details in the description about what is your expectations and what currently displayed?

**Comment by odockal** [comment]
@praveenkumar I am sorry, this should be placed under CDK (https://issues.jboss.org/browse/CDK-192). Please, close this issue.
