### ISSUE TITLE
brew cask can't install latest minishift version

### ISSUE THREAD

**Issue by xiaods** [minishift/minishift#1538]
> xiaods at XiaoTommydeMacBook-Pro in ~
$ brew cask install --force minishift
==> Satisfying dependencies
==> Downloading https://github.com/minishift/minishift/releases/download/v1.6.0/minishift-1.6.0-darwin-amd64.tgz
######################################################################## 100.0%
==> Verifying checksum for Cask minishift
==> Installing Cask minishift
==> Linking Binary 'minishift' to '/usr/local/bin/minishift'.
🍺  minishift was successfully installed!
xiaods at XiaoTommydeMacBook-Pro in ~
$ minishift version
minishift v1.6.0+7a71565

current minishift is 1.7

anyone know the process?

**Comment by gbraad** [comment]
Brew packages are not provided by us, but the caskroom project. This is a manual process... and current PR is under review/not accepted: https://github.com/caskroom/homebrew-cask/pull/39496

**Comment by gbraad** [comment]
In the meantime, use `minishift update`

**Comment by LalatenduMohanty** [comment]
I can see https://github.com/caskroom/homebrew-cask/pull/39496 is merged already. @xiaods It should be resolved for you now. Can you please confirm.

**Comment by gbraad** [comment]
I suggest to update the metadata from the remote repo. Not sure which command this was anymore (not behind my desk)

**Comment by xiaods** [comment]
thanks all. it works.
