### ISSUE TITLE
Update hostfolder mount doc for macOS

### ISSUE THREAD

**Issue by kameshsampath** [minishift/minishift#1539]
Followed the document https://docs.openshift.org/latest/minishift/using/host-folders.html to add and mount hostfolder, does not work as expected.

OS: `macOS Sierra (10.12.6)`
minishift version:` minishift v1.6.0+7a71565`

**Profile Config**
minishift --profile myche config view
- cpus                 : 5
- disk-size            : 50g
- iso-url              : file:///Users/kameshs/Downloads/minishift-centos7.iso
- memory               : 8192
- vm-driver            : xhyve

**Step 1:** 
```
minishift hostfolder add che-data
UNC path: //192.168.64.9/myche-data
Mountpoint [/mnt/sda1/che-data]:
Username: che
Password: [HIDDEN]
Domain:
Added: che-data
```

**Step 2:**
```
minishift hostfolder list
Name       Mountpoint           Remote path                 Mounted
che-data   /mnt/sda1/che-data   //192.168.64.9/myche-data   N
```

**Step 3**
```
minishift hostfolder mount che-data
Mounting 'che-data': '//192.168.64.9/myche-data' as '/mnt/sda1/che-data' ... FAIL
```

Also am not able to get any logs of the failure even with `minishift hostfolder mount --v=10 che-data`

**Comment by gbraad** [comment]
Use smbUP to verify this is not related to the Samba implementation provided by macOS. Will review/test after my PTO, or someone else needs to have a look for debug info.  I do suggest to use `--show-libmachine-logs` for debug

**Comment by praveenkumar** [comment]
@kameshsampath so I used below steps and able to mount.  

Last time what we misunderstood about `test1`, should it be complete path or how to share it. Below screenshot will show how I added this test1 to smb share.

1. Create a directory I have it in `~/Documents/test1`.

2. Settings => Sharing => Select `Options...` dialog which will open options window. Make you select your username and click on `Done` button.

<img width="399" alt="screen shot 2017-10-12 at 9 18 31 pm" src="https://user-images.githubusercontent.com/410007/31505730-278edb88-af93-11e7-8535-c111dba18413.png">

3. In `Sharing` Window under `Shared Folders:` you will see an `+` button click that and chose directory which created `~/Documents/test1` and click `Add` button.

<img width="704" alt="screen shot 2017-10-12 at 9 27 03 pm" src="https://user-images.githubusercontent.com/410007/31506121-33f1dc4e-af94-11e7-8f66-13de07cf13ca.png">

4. You will now see as below where `test1` reflected under `Shared Folders`.

<img width="437" alt="screen shot 2017-10-12 at 9 30 15 pm" src="https://user-images.githubusercontent.com/410007/31506271-95687050-af94-11e7-85ea-f881ec7b3f47.png">


```
21:12 $ ./minishift ip
192.168.64.11

21:30 $ ifconfig | grep 192.168.64
	inet 192.168.64.1 netmask 0xffffff00 broadcast 192.168.64.255

21:11 $ ./minishift hostfolder add test
UNC path: //192.168.64.1/test1    => here IP is from your host like we used during discussion
Mountpoint [/mnt/sda1/test]: 
Username: prkumar   => your username
Password: [HIDDEN]
Domain: 
Added: test

21:12 $ ./minishift hostfolder list
Name   Mountpoint       Remote path            Mounted
test   /mnt/sda1/test   //192.168.64.1/test1   N
 
21:12 $ ./minishift hostfolder mount test
   Mounting 'test': '//192.168.64.1/test1' as '/mnt/sda1/test' ... OK
```

**Comment by kameshsampath** [comment]
@praveenkumar - works as expected, do you want the ticket to be opened for updating the doc, else please feel free to close the same.

**Comment by gbraad** [comment]
Images in the documentation are much appreciated. But what is the stance about this?

**Comment by eliu** [comment]
I got the same issue here. But the solution that @praveenkumar provided did not work for me.
I have a macOS High Sierra (10.13.1) and minishift v1.8.0+6455fc3 installed on my mac.

**Comment by praveenkumar** [comment]
@eliu do you get the same error even setting up required permissions?

**Comment by eliu** [comment]
@praveenkumar I did all the steps that you provided in your comment, and they didn't ask me for extra permissions. anyways, it just ended up with a `FAIL`. can't find more details why

**Comment by gbraad** [comment]
can you perform the same command as follows: `m hostfolder mount <name> --show-libmachine-logs -v5` and see what the error is you are getting.

**Comment by eliu** [comment]
@gbraad you're right. I've got some permission issues here:
```
sudo mount -t cifs //192.168.99.1/local /mnt/sda1/local -o username=eliuhy,password=xxxxxx,context=system_u:object_r:svirt_sandbox_file_t:s0
SSH cmd err, output: exit status 32: mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```

**Comment by eliu** [comment]
@gbraad seems the macOS mount command does not recognize it:
```
~ $ sudo mount -t cifs //192.168.99.1/local /mnt/sda1/local -o credentials=/tmp/credentials.txt,context=system_u:object_r:svirt_sandbox_file_t:s0
Password:
usage: mount [-dfruvw] [-o options] [-t external_type] special node
       mount [-adfruvw] [-t external_type]
       mount [-dfruvw] special | node
~ $ sudo mount -t cifs //192.168.99.1/local /mnt/sda1/local -o credentials=/tmp/credentials.txt,context=system_u:object_r:svirt_sandbox_file_t:s0
usage: mount [-dfruvw] [-o options] [-t external_type] special node
       mount [-adfruvw] [-t external_type]
       mount [-dfruvw] special | node
~ $ sudo mount -t cifs //192.168.99.1/local /mnt/sda1/local -o credentials=/tmp/credentials.txt,context=system_u:object_r:svirt_sandbox_file_t:s0
usage: mount [-dfruvw] [-o options] [-t external_type] special node
       mount [-adfruvw] [-t external_type]
       mount [-dfruvw] special | node
~ $
```

**Comment by eliu** [comment]
by the way, should i have to add a `sudo` command before `minishift hostfolder mount local`?

**Comment by eliu** [comment]
@gbraad Sorry but that mount command i just executed outside the minishift. Here is the updated output when i did it inside minishift VM:

```
[docker@minishift ~]$ sudo mount -t cifs //192.168.99.1/local /mnt/sda1/local -o credentials=/tmp/credentials.txt,context=system_u:object_r:svirt_sandbox_file_t:s0
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
[docker@minishift ~]$
```

**Comment by gbraad** [comment]
I mentioned to use `minishift ssh`. This opens the terminal inside the VM.
From here you have to perform the mount command.

And no, `sudo` has no effect, as the mount happens inside the Minishift VM.

**Comment by gbraad** [comment]
If using the `credentials.txt` file also fails, this is most likely an
issue with how macOS is set up. Can you try using smbUP instead?

**Comment by eliu** [comment]
I didn't see any options about `smbUP` in Share window of System Preference. Can you provide more details on how to set it up?

**Comment by eliu** [comment]
@gbraad I mounted it successfully after checking the corresponding user in `Windows File Sharing` list.
<img width="409" alt="win-file-share" src="https://user-images.githubusercontent.com/831707/33412047-2bd22d6a-d5c4-11e7-9c14-5d472eab58fd.png">

But this is for the `credentials.txt` way only. the normal `minishift hostfolder mount local` still failed.

**Comment by gbraad** [comment]
smbUP is the Samba release for macOS, as the Apple implementation for Windows Sharing is often failing with permission errors. See http://eduo.info/apps/smbup

  * http://blog.rubbingalcoholic.com/post/39412902216/fix-smb-windows-sharing-permissions-issue-in-os-x
  * http://hsti.freshdesk.com/support/articles/28166-re-installing-smb-samba-on-mac-os-x-lion-10-7-x

**Comment by gbraad** [comment]
The only difference with credentials.txt and `m hostfolder mount` is how the password is specified. Do you have any non-alphanumeric character in your password? And if so, which?

**Comment by eliu** [comment]
yes it is, some dollar sign used for mypassword

**Comment by gbraad** [comment]
can you the following command from the Minishift VM?

```
$ minishift ssh
# sudo mount -t cifs //192.168.99.1/local /mnt/sda1/local -o username=eliuhy,password='xxxxxx',context=system_u:object_r:svirt_sandbox_file_t:s0
```

Note: there are single quotes around the password.

**Comment by eliu** [comment]
it's a $

**Comment by eliu** [comment]
@gbraad the `Single Quotes` solution works for me.

**Comment by gbraad** [comment]
@eliu Can you create a separate issue for this?
"Hostfolder password with a non-alphanumeric character like $ fails to mount`

**Comment by eliu** [comment]
@gbraad sure, i'll create another one for tracking this.
