### ISSUE TITLE
Unused variable in Makefile

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#154]
Currently Makefile contain `PYTHON`, `BUILD_OS` and `BUILD_IMAGE` which have no use during any section of Makefile. I propose we should remove those unused variables and if requirement need those then add it.

**Comment by LalatenduMohanty** [comment]
@praveenkumar minishift has inherited these from minikube `Makefile`. Can you please check if updating K8s [1] in Minishift has any thing to do with these variables. 

[1] https://github.com/minishift/minishift/blob/master/UPDATE_KUBERNETES.md

**Comment by r2d4** [comment]
In minikube, we use these to build localkube in a container so that we can compile a linux binary on OS X

**Comment by praveenkumar** [comment]
@LalatenduMohanty as @r2d4 pointed it used for build localkube in container to compile linux binary but  right now we are not doing it for minishift so until we have similar plan better we can remove those.

**Comment by hferentschik** [comment]
> minishift has inherited these from minikube Makefile

this is not the only variable which is not needed. I went much further with the Makefile "cleanup". There is no need to keep legacy around there. The Makfile should be as simple and concise as possible and suite our needs.

**Comment by hferentschik** [comment]
Merged via pull request #155
