### ISSUE TITLE
User In Hyper-V Administrators group check fails on Windows due to localization of group name.

### ISSUE THREAD

**Issue by hygl** [minishift/minishift#1541]
I want to launch minishift local on windows 10 with hyper-v. my local user is part of the hyper-v admin group. i get an error  " Checking if user is a member of the Hyper-V Administrators group ... FAIL" running minishift start as a local user and as an administrator. 

```
([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole('Hyper-V Administrators')
```

    False

I have added the user to the hyper-v group. 

The problem was fixed after I installed the lates cullumaltive update (oktober) by microsoft. After that the check returned true.

Minioshift Version is 1.7.0

**Comment by gbraad** [comment]
Remember that preflight checks can all be individually disabled. For the HyperV check you can use:

```
minishift config set skip-check-hyperv-driver true
```

If you prefer the check to happen, but not fail startup, you can use the want option instead:

```
minishift config set warn-check-hyperv-driver true
```

**Comment by psevestre** [comment]
I´ve faced the same issue on a non-English version of Windows (Brazilian Portuguese in my case).

Digging into the code, I´ve noticed that the test checks for a literal role name, but those roles are localized, so:
([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole('Hyper-V Administrators')

returns false in my Windows machine but,
([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole('Administradores do Hyper-V')

returns "True"

**Comment by hygl** [comment]
My Windows Version ist installed in German.

**Comment by gbraad** [comment]
Localized roles is what I thought would be the problem. :-s

**Comment by psevestre** [comment]
Maybe using something like Get-WinUserLanguageList could be used on order to lookup the proper locale-specific role, and the check should fail with a proper message if run on a non-supported locale, but I´m not sure if it is worth the trouble.

A notice for non-English Windows users in the docs and/or a FAQ entry would be nice, tough.

**Comment by gbraad** [comment]
@LalatenduMohanty @anjannath 
It seems the HyperV Administrator role is localized.

https://github.com/minishift/minishift/blob/0a3b29aa3b34f7b0620612617be6b5931d325045/cmd/minishift/cmd/start_preflight.go#L87-L92

This test needs to be made WARN-only:

```diff
			"Checking if user is a member of the Hyper-V Administrators group",
-			false, configCmd.WarnCheckHyperVDriver.Name,
+			true, configCmd.WarnCheckHyperVDriver.Name,
			driverErrorMessage)
```

**Comment by gbraad** [comment]
After this we will look for a better solution, such as the localization issue.

**Comment by gbraad** [comment]
We need to check if the "Hyper-V Administrators" group has an RID:
```
Relative identifiers (RIDs) are components of a Windows user group's security identifier (SID) and are supported to help prevent cross-platform localization issues. Many user accounts, local groups, and global groups have a default RID value that is constant across all versions of Windows.
For example, the RID for the BUILTIN\Administrators role is 0x220. Using 0x220 as the input parameter for the IsInRole method results in true being returned if the current principal is an administrator.
```

Ref: https://msdn.microsoft.com/en-us/library/86wd8zba(v=vs.110).aspx

**Comment by psevestre** [comment]
It seems that there is ideed such RID.

According to:
https://support.microsoft.com/en-us/help/243330/well-known-security-identifiers-in-windows-operating-systems

SID: S-1-5-32-578
Name: BUILTIN\Hyper-V Administrators
Description: A Builtin Local group. Members of this group have complete and unrestricted access to all features of Hyper-V.

The last part (578) is the RID

**Comment by gbraad** [comment]
Thanks so far for the help. I will see if this can be updated ASAP.

**Comment by gbraad** [comment]
```
([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole('
S-1-5-32-578')
```
     True

**Comment by gbraad** [comment]
@hygl @psevestre Would it be possible to test the following binary for us? http://artifacts.ci.centos.org/minishift/minishift/pr/1566/windows-amd64/

This version should check the group by the static Security ID, instead of by name.

**Comment by hygl** [comment]
@gbraad works for me.

**Comment by psevestre** [comment]
@gbraad  Works for me too. Thanks !

**Comment by gbraad** [comment]
Thanks. The next release will be much friendlier on localisation :-D

**Comment by ThomasSchoenbeck** [comment]
Just to raise your awareness, this is still an issue in minishift version 1.2.0

**Comment by gbraad** [comment]
This check can be skipped as workaround

**Comment by hafizusman530** [comment]
I was facing same issue despite adding user into hyper v administrator group. It work after applying universal solution (Restarting computer). 💯

**Comment by ccronemberger** [comment]
According to the instructions after adding your user to admin group you should log out and login again.

**Comment by galishmann** [comment]
solution: https://www.ibm.com/support/knowledgecenter/en/SSMKFH/com.ibm.apmaas.doc/install/hyperv_config_add_nonadmin_user_hyperv_usergroup.html
