### ISSUE TITLE
Build secret when strategy=docker

### ISSUE THREAD

**Issue by robdaems** [minishift/minishift#1545]
Hello,
I'm using my own Dockerfile to build an image. (strategy=docker)
Since I assume a build secret cannot be used, and the secret has to be provided in the Dockerfile, I was planning to copy my id_rsa file temporary in the Dockerfile.
But I don't know the relative/absolute path to my id_rsa file, since I don't know as which user minishift will build my image.
I've logged in via 'minishift ssh' and made a symbolic link to my id_rsa file, but during the build it seems that docker uses a different context?
How can I add my id_rsa, or is their a better way to use a build-secret when strategy = docker

**Comment by gbraad** [comment]
To be frank: Including any kind of key inside an image is bad practice when it comes to security.

Maybe it is best to explain first why this key is needed.

Note: the key will not be resolved on disk inside the VM, but inside a ephemeral/temporary location which is used for the build process.

**Comment by robdaems** [comment]
I know it's bad practice when it comes to security, but I don't know a better solution for it.
In my dockerfile, I execute a 'npm install', where the package.json has a reference to another git repo, therefor I need to authenticate with my key.

**Comment by gbraad** [comment]
So you want to checkout a private repo which uses git@github.com:user/private.git. right?

**Comment by robdaems** [comment]
Yes and no :-) , the clone of my repo which contains the javascript code succeeds, but package.json (which is in my repo) contains a reference to another repo where I need to authorize.
So the docker-strategy starts build my image (since my Dockerfile is in my repo) so far so good, but when I come to the point in my Dockerfile 'RUN npm install', the npm install fails because I cannot authorize to the reference in my package.json

**Comment by robdaems** [comment]
It seems not so easy to solve:
https://github.com/moby/moby/issues/13490

A solution could be:
https://github.com/abourget/secrets-bridge
