### ISSUE TITLE
restorecon fails with new persistent volume for registry

### ISSUE THREAD

**Issue by thomasmckay** [minishift/minishift#1554]
These two lines, the first to chmod _pv*_ dirs and the last to restorecon, fails since there is a new persistent volume dir named _registry_.
https://github.com/minishift/minishift/blob/master/pkg/minishift/clusterup/clusterup.go#L254-L263

```
About to run SSH command:
sudo which restorecon; if [ $? -eq 0 ]; then restorecon -R /var/lib/minishift/openshift.local.pv; fi
SSH cmd err, output: <nil>: /sbin/restorecon
restorecon:  unable to read directory /mnt/sda1/var/lib/minishift/openshift.local.pv/registry
```

**Comment by praveenkumar** [comment]
This is regression #916 we fixed it and looks like when refactored code then we didn't moved code along :(
