### ISSUE TITLE
'minishift start' for CDK hangs on Windows 10 with VirtualBox 5.1.28

### ISSUE THREAD

**Issue by chrisfalter** [minishift/minishift#1555]
Steps:
* Disabled Hyper-V
* Installed VirtualBox 5.1.28 (latest)
* Downloaded cdk-3.1.1-1-minishift-windows-amd64.exe
* Renamed to minishift.exe
* Moved minishift.exe to a directory in %path
* Followed instructions at https://access.redhat.com/documentation/en-us/red_hat_container_development_kit/3.1/html-single/getting_started_guide/index

Remainder of this issue/post is console i/o while following instructions. I have put my typed commands in bold. After the _minishift start --vm-driver virtualbox_ process printed "Retrying" to the console, the process hung. 

**PS C:\Users\582139> minishift setup-cdk**
Setting up CDK 3 on host using 'C:\Users\582139\.minishift' as Minishift's home directory
The MINISHIFT_HOME directory 'C:\Users\582139\.minishift' exists. Continuing will delete any existing VM and all other d
ata in this directory. Do you want to continue? [y/N]
y
Warning:  Failed to find the VM status
Existing VM deleted
Copying minishift-rhel7.iso to 'C:\Users\582139\.minishift/cache/iso/minishift-rhel7.iso'
Copying oc.exe to 'C:\Users\582139\.minishift/cache/oc/v3.6.173.0.5/oc.exe'
Creating configuration file 'C:\Users\582139\.minishift/config/config.json'
Creating marker file 'C:\Users\582139\.minishift/cdk'
Default add-ons anyuid, admin-user, xpaas installed
Default add-ons anyuid, admin-user, xpaas enabled
CDK 3 setup complete.
**PS C:\Users\582139> minishift start --vm-driver virtualbox**
Starting local OpenShift cluster using 'virtualbox' hypervisor...
E1012 16:31:30.482610    5276 start.go:282] Error starting the VM: Error creating the VM. Error creating machine: Error
in driver during machine creation: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm minishift --firmware bios
--bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 2
--memory 0 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 off --natdnsproxy1 on --cpuhotplug off --pae on --
hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd failed:
VBoxManage.exe: error: Invalid RAM size: 0 MB (must be in range [4, 2097152] MB)
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component SessionMachine, interface IMachine, callee IUn
known
VBoxManage.exe: error: Context: "COMSETTER(MemorySize)(ValueUnion.u32)" at line 599 of file VBoxManageModifyVM.cpp
. Retrying.

**Comment by LalatenduMohanty** [comment]
@chrisfalter It is a CDK issue and it should be raised in https://issues.jboss.org/projects/CDK/issues.

**Comment by LalatenduMohanty** [comment]
@chrisfalter Please let us know if you need help raising it in CDK Jira.

**Comment by chrisfalter** [comment]
I have opened https://issues.jboss.org/browse/CDK-196 for this issue, so I am closing this one as a duplicate.
