### ISSUE TITLE
kubctl commands in minishift

### ISSUE THREAD

**Issue by vikasgubbi** [minishift/minishift#1556]
how to use kubernetes kubectl commands in minishift.

Regards,
Vikas

**Comment by budhrg** [comment]
@vikasgubbi ,

Once minishift start is done do following:
```
$ eval $(minishift oc-env) # Get oc client
$ oc status 
$ oc login -u developer -p developer # Required if you are not already logged in
$ ln -s $(which oc) $(pwd)/kubectl
$ ./kubectl version
```

Let us know if it doesn't work.

**Comment by vikasgubbi** [comment]
Its not working.

Getting following message

In project xxx on server xxx
You have no services,deployment configs,or build configs.
Run 'oc new-app' to create an application.

Please assist.

**Comment by praveenkumar** [comment]
@vikasgubbi can you please add a comment (step by step) what you actually tried and what you expected vs what actual result is?

**Comment by budhrg** [comment]
@vikasgubbi , also try to join #minishift channel in irc.freenode.net to get quick and interactive help.

**Comment by vikasgubbi** [comment]
Please find the steps i followed .

[docker@lab client]$ ./oc status
In project vikas on server https://192.168.42.244:8443

You have no services, deployment configs, or build configs.
Run 'oc new-app' to create an application.

[docker@lab client]$ ./oc login -u developer -p developer
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    myproject
  * vikas

Using project "vikas".


[docker@lab client]$ ./kubectl version
-bash: ./kubectl: Too many levels of symbolic links

[docker@lab client]$ ls -ltr
total 190496
-rwxr-xr-x. 1 docker docker 194837552 Aug 30 06:20 oc
-rw-r--r--. 1 docker docker     17760 Aug 30 06:20 README.md
-rw-r--r--. 1 docker docker     10759 Aug 30 06:20 LICENSE
lrwxrwxrwx. 1 docker docker        37 Oct 14 01:52 kubectl -> /home/docker/minishift/client/kubectl

**Comment by budhrg** [comment]
@vikasgubbi , could you try to symlink as 
```
$ ln -s $(which oc) /usr/local/bin/kubectl
```

**Comment by vikasgubbi** [comment]
Thanks.Its working now.

Regards,
Vikas

**Comment by budhrg** [comment]
Cool @vikasgubbi , closing it now.
