### ISSUE TITLE
Minishift start error - Too many retries waiting for SSH to be available.

### ISSUE THREAD

**Issue by putztzu** [minishift/minishift#1565]
Win10 Home edition
Brand new Minishift-1.7.0-windows-am64 isntall using virtualbox driver
Command and error as follows:

```
c:\Users\User\Downloads\vm>minishift.exe start --vm-driver=virtualbox
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.2.0/minishift-b2d.iso'
 40.00 MiB / 40.00 MiB [===========================================] 100.00% 0s
-- Starting Minishift VM ...................................................... FAIL E1013 19:46:33.490458    1788 start.go:355] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```

Also results in the Client Binary not installed,
The following directory is empty

`~\.minishift\cache\oc\`

Curiously, I don't know if rebooting might help but after starting the vm, the system PATH to the minishift binary does not work(The PATH worked before the first vm was started). I have to browse to the minishift binary to execute it.

Have stopped and restarted the vm but no change.

TIA

**Comment by gbraad** [comment]
The `oc`-binary will only be download after successfully starting the VM. Can you provide logs using:

```
C:\> minishift start --vm-driver virtualbox --show-libmachine-logs -v5
```

In this case, since a start never fully happened, it might be advisable to actually perform a delete with `minishift delete --force --clear-cache`

**Comment by putztzu** [comment]
`minishift start --vm-driver virtualbox --show-libmachine-logs -v5
Found binary path at minishift.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:49174
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minishift --machinereadable
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | name="minishift"
(minishift) DBG | groups="/"
(minishift) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
(minishift) DBG | UUID="2d3de0ed-c7ab-476a-9c79-3849f727f595"
(minishift) DBG | CfgFile="C:\\Users\\Tony\\.minishift\\machines\\minishift\\minishift\\minishift.vbox"
(minishift) DBG | SnapFldr="C:\\Users\\Tony\\.minishift\\machines\\minishift\\minishift\\Snapshots"
(minishift) DBG | LogFldr="C:\\Users\\Tony\\.minishift\\machines\\minishift\\minishift\\Logs"
(minishift) DBG | hardwareuuid="2d3de0ed-c7ab-476a-9c79-3849f727f595"
(minishift) DBG | memory=2048
(minishift) DBG | pagefusion="off"
(minishift) DBG | vram=8
(minishift) DBG | cpuexecutioncap=100
(minishift) DBG | hpet="on"
(minishift) DBG | chipset="piix3"
(minishift) DBG | firmware="BIOS"
(minishift) DBG | cpus=2
(minishift) DBG | pae="on"
(minishift) DBG | longmode="on"
(minishift) DBG | triplefaultreset="off"
(minishift) DBG | apic="on"
(minishift) DBG | x2apic="off"
(minishift) DBG | cpuid-portability-level=0
(minishift) DBG | bootmenu="disabled"
(minishift) DBG | boot1="dvd"
(minishift) DBG | boot2="dvd"
(minishift) DBG | boot3="disk"
(minishift) DBG | boot4="none"
(minishift) DBG | acpi="on"
(minishift) DBG | ioapic="on"
(minishift) DBG | biosapic="apic"
(minishift) DBG | biossystemtimeoffset=0
(minishift) DBG | rtcuseutc="on"
(minishift) DBG | hwvirtex="on"
(minishift) DBG | nestedpaging="on"
(minishift) DBG | largepages="on"
(minishift) DBG | vtxvpid="on"
(minishift) DBG | vtxux="on"
(minishift) DBG | paravirtprovider="default"
(minishift) DBG | effparavirtprovider="kvm"
(minishift) DBG | VMState="running"
(minishift) DBG | VMStateChangeTime="2017-10-14T03:28:38.363000000"
(minishift) DBG | monitorcount=1
(minishift) DBG | accelerate3d="off"
(minishift) DBG | accelerate2dvideo="off"
(minishift) DBG | teleporterenabled="off"
(minishift) DBG | teleporterport=0
(minishift) DBG | teleporteraddress=""
(minishift) DBG | teleporterpassword=""
(minishift) DBG | tracing-enabled="off"
(minishift) DBG | tracing-allow-vm-access="off"
(minishift) DBG | tracing-config=""
(minishift) DBG | autostart-enabled="off"
(minishift) DBG | autostart-delay=0
(minishift) DBG | defaultfrontend=""
(minishift) DBG | storagecontrollername0="SATA"
(minishift) DBG | storagecontrollertype0="IntelAhci"
(minishift) DBG | storagecontrollerinstance0="0"
(minishift) DBG | storagecontrollermaxportcount0="30"
(minishift) DBG | storagecontrollerportcount0="30"
(minishift) DBG | storagecontrollerbootable0="on"
(minishift) DBG | "SATA-0-0"="C:\Users\Tony\.minishift\machines\minishift\boot2docker.iso"
(minishift) DBG | "SATA-ImageUUID-0-0"="c5a3fe62-016b-40ee-a5c9-0e5f40504ffe"
(minishift) DBG | "SATA-tempeject"="off"
(minishift) DBG | "SATA-IsEjected"="off"
(minishift) DBG | "SATA-1-0"="C:\Users\Tony\.minishift\machines\minishift\disk.vmdk"
(minishift) DBG | "SATA-ImageUUID-1-0"="2abb142b-16cd-410a-b9f1-5fc556755f06"
(minishift) DBG | "SATA-2-0"="none"
(minishift) DBG | "SATA-3-0"="none"
(minishift) DBG | "SATA-4-0"="none"
(minishift) DBG | "SATA-5-0"="none"
(minishift) DBG | "SATA-6-0"="none"
(minishift) DBG | "SATA-7-0"="none"
(minishift) DBG | "SATA-8-0"="none"
(minishift) DBG | "SATA-9-0"="none"
(minishift) DBG | "SATA-10-0"="none"
(minishift) DBG | "SATA-11-0"="none"
(minishift) DBG | "SATA-12-0"="none"
(minishift) DBG | "SATA-13-0"="none"
(minishift) DBG | "SATA-14-0"="none"
(minishift) DBG | "SATA-15-0"="none"
(minishift) DBG | "SATA-16-0"="none"
(minishift) DBG | "SATA-17-0"="none"
(minishift) DBG | "SATA-18-0"="none"
(minishift) DBG | "SATA-19-0"="none"
(minishift) DBG | "SATA-20-0"="none"
(minishift) DBG | "SATA-21-0"="none"
(minishift) DBG | "SATA-22-0"="none"
(minishift) DBG | "SATA-23-0"="none"
(minishift) DBG | "SATA-24-0"="none"
(minishift) DBG | "SATA-25-0"="none"
(minishift) DBG | "SATA-26-0"="none"
(minishift) DBG | "SATA-27-0"="none"
(minishift) DBG | "SATA-28-0"="none"
(minishift) DBG | "SATA-29-0"="none"
(minishift) DBG | natnet1="nat"
(minishift) DBG | macaddress1="080027E429C8"
(minishift) DBG | cableconnected1="on"
(minishift) DBG | nic1="nat"
(minishift) DBG | nictype1="82540EM"
(minishift) DBG | nicspeed1="0"
(minishift) DBG | mtu="0"
(minishift) DBG | sockSnd="64"
(minishift) DBG | sockRcv="64"
(minishift) DBG | tcpWndSnd="64"
(minishift) DBG | tcpWndRcv="64"
(minishift) DBG | Forwarding(0)="ssh,tcp,127.0.0.1,51471,,22"
(minishift) DBG | hostonlyadapter2="VirtualBox Host-Only Ethernet Adapter"
(minishift) DBG | macaddress2="080027F34D45"
(minishift) DBG | cableconnected2="on"
(minishift) DBG | nic2="hostonly"
(minishift) DBG | nictype2="82540EM"
(minishift) DBG | nicspeed2="0"
(minishift) DBG | nic3="none"
(minishift) DBG | nic4="none"
(minishift) DBG | nic5="none"
(minishift) DBG | nic6="none"
(minishift) DBG | nic7="none"
(minishift) DBG | nic8="none"
(minishift) DBG | hidpointing="ps2mouse"
(minishift) DBG | hidkeyboard="ps2kbd"
(minishift) DBG | uart1="off"
(minishift) DBG | uart2="off"
(minishift) DBG | uart3="off"
(minishift) DBG | uart4="off"
(minishift) DBG | lpt1="off"
(minishift) DBG | lpt2="off"
(minishift) DBG | audio="dsound"
(minishift) DBG | clipboard="disabled"
(minishift) DBG | draganddrop="disabled"
(minishift) DBG | SessionName="headless"
(minishift) DBG | VideoMode="720,400,0"@0,0 1
(minishift) DBG | vrde="off"
(minishift) DBG | usb="off"
(minishift) DBG | ehci="off"
(minishift) DBG | xhci="off"
(minishift) DBG | SharedFolderNameMachineMapping1="c/Users"
(minishift) DBG | SharedFolderPathMachineMapping1="\\?\c:\Users"
(minishift) DBG | VRDEActiveConnection="off"
(minishift) DBG | VRDEClients=0
(minishift) DBG | vcpenabled="off"
(minishift) DBG | vcpscreens=0
(minishift) DBG | vcpfile="C:\Users\Tony\.minishift\machines\minishift\minishift\minishift.webm"
(minishift) DBG | vcpwidth=1024
(minishift) DBG | vcpheight=768
(minishift) DBG | vcprate=512
(minishift) DBG | vcpfps=25
(minishift) DBG | GuestMemoryBalloon=0
(minishift) DBG | GuestOSType="Linux26_64"
(minishift) DBG | GuestAdditionsRunLevel=2
(minishift) DBG | GuestAdditionsVersion="5.1.12 r112440"
(minishift) DBG | GuestAdditionsFacility_VirtualBox Base Driver=50,1507951737829
(minishift) DBG | GuestAdditionsFacility_VirtualBox System Service=50,1507951745447
(minishift) DBG | GuestAdditionsFacility_Seamless Mode=0,1507951737829
(minishift) DBG | GuestAdditionsFacility_Graphics Mode=0,1507951737829
(minishift) DBG | }
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | }
The 'minishift' VM is already running.`

**Comment by gbraad** [comment]
Instructions were not followed

```
The 'minishift' VM is already running.
```

**Comment by putztzu** [comment]
The vm starts and runs. As in the first post, I can stop the vm so it was running. But, the vm is not accessible due to the SSH error.

After stopping the vm again, I deleted the vm with the command
`
minishift delete --force --clear-cache

Then started again. The stdout is identical to what was posted in the first post, throwing the SSH error.`

**Comment by gbraad** [comment]
But I want to see the startup log after the delete happened. At the moment I have no usable information.

**Comment by putztzu** [comment]
Ok  i assume that the following is what you want, it will take me some time to re-run everythiing to re-direct full log output to a file which can be posted, stdout buffer not large enough for entire log

`(minishift) DBG | &{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i C:\Users\Tony\.minishift\machines\minishift\id_rsa -p 49383] C:\Program Files\OpenSSH\ssh.exe <nil>}
(minishift) DBG | About to run SSH command:
(minishift) DBG | exit 0
(minishift) DBG | SSH cmd err, output: exit status 255:
(minishift) DBG | Error getting ssh command 'exit 0' : ssh command error:
(minishift) DBG | command : exit 0
(minishift) DBG | err     : exit status 255
(minishift) DBG | output  :
. FAIL E1014 08:55:03.845226   11864 start.go:355] Error starting the VM: Error starting stopped host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
Error starting the VM: Error starting stopped host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded`

**Comment by putztzu** [comment]
interestingly, redirecting output to a file generated a very different output with the following likely useful error
`
-- Starting Minishift VM ....(minishift) Trying to access option engine-install-url which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key engine-install-url
(minishift) Trying to access option swarm-master which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to bool for key swarm-master
(minishift) Trying to access option swarm-host which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key swarm-host
(minishift) Trying to access option swarm-discovery which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key swarm-discovery
(minishift) Type assertion did not go smoothly to bool for key virtualbox-host-dns-resolver
(minishift) Type assertion did not go smoothly to bool for key virtualbox-hostonly-no-dhcp
(minishift) Type assertion did not go smoothly to bool for key virtualbox-no-share
(minishift) Type assertion did not go smoothly to bool for key virtualbox-no-dns-proxy
(minishift) Type assertion did not go smoothly to bool for key virtualbox-no-vtx-check
Running pre-create checks...
Creating machine...
`



[logfile.txt](https://github.com/minishift/minishift/files/1384822/logfile.txt)

**Comment by putztzu** [comment]
Question:
i had installed OpenSSH separately on this machine long ago for another use.
Skimming some other, old minishift/openshift issues there were some reports at that time that this might cause a problem. 
Is this still a latent issue?

**Comment by tsmilam** [comment]
You may be right about the version of OpenSSH being a factor. I also was getting "Too many retries waiting for SSH to be available".  I'm using OpenSSH-Win64 (on Windows 10 managed via chocolatey). After I upgraded OpenSSH-Win64 to the latest version, and then ran the command posted above:

`minishift delete --force --clear-cache

` 

The problem cleared up. I was able to run minishift start without errors.

**Comment by putztzu** [comment]
looks like that did the trick.
There are many Windows OpenSSH packages available, I have Win32-OpenSSH installed, from the following page, the original install date Nov 2016
https://github.com/PowerShell/Win32-OpenSSH/releases

Removed and replaced with current latest, version 0.0.21.0.

Deleted the existing minishift vm
Ran the command to start and display logfile
I could see when the point where previous attempts failed, and there were about 6 retries (the data was flying across the screen)
Then, seemed to resolve and continue.
And reached the point where oc binary was installed and beyond.

I assume that minishift is now running properly, I can now invoke the command which displays environmental variables.

Thx!

**Comment by gbraad** [comment]
There might be something wrong with your version of OpenSSH. Have you tried to use OpenSSH-Win64 or Cygwin instead? Perhaps test by removing the current version (or just renaming `ssh.exe` to `no-ssh.exe` to test). The internal SSH client might pick up and deploy.

**Comment by scjothi** [comment]
It worked for me when  I added SSH folder to the PATH variable.
