### ISSUE TITLE
CONTRIBUTING.adoc should be part of Minishift documentation.

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1567]
I think we should add a copy of CONTRIBUTING.adoc [1] to Minishift documentation also. 

At this point of time it is only exists in the github repo. So when a contributor send a PR for an existing issue  or goes through documentation i.e. https://docs.openshift.org/latest/minishift/contributing/index.html and does not see this. Also an user opens an issue there is a good chance that user will miss it. 

[1] https://github.com/minishift/minishift/blob/master/CONTRIBUTING.adoc

**Comment by LalatenduMohanty** [comment]
May be we can move the file to docs directory and create a symlink in the root directory for github to pick it up.

**Comment by budhrg** [comment]
> I think we should add a copy of CONTRIBUTING.adoc [1] to Minishift documentation also.

Content of CONTRIBUTING.adoc you mean right? Then yes, it seems to be missing from published docs.

**Comment by robin-owen** [comment]
I agree that this would make the contribution guidelines significantly more visible when reading the documentation. Currently, a link exists in **_docs/source/contributing/index.adoc_**, but it's easy to miss.

Note that **_CONTRIBUTING.adoc_** [1] currently has a `link` to the published developer documentation [2] for Minishift. If the contribution guidelines were placed in **_docs/source/contributing_**, I think that it makes more sense to use an `xref` to the **_docs/source/contributing/developing.adoc_** file within the repository. Thoughts?

[1] https://github.com/minishift/minishift/blob/master/CONTRIBUTING.adoc
[2] https://docs.openshift.org/latest/minishift/contributing/developing.html

**Comment by hferentschik** [comment]
Remember CONTRIBUTING.adoc has a special meaning with GitHub and a link to the file will appear when creating an issue. For this reason CONTRIBUTING.adoc exists for the first place in the root of the repo. 

If we think this is not valuable, then let's move to the docs. I don't think so that you can work with a symlink or similar here. In the best case, you can add just a link to the online docs to CONTRIBUTING.adoc. This will, however, create a bit of a odd workflow for the user creating an issue, since now he gets from creating an issue  to CONTRIBURING.adoc which in turn will refer him to the Origin docs.

**Comment by robin-owen** [comment]
It's also entirely possible to make the contribution guidelines far more visible in the existing documentation without requiring movement/symlinking of CONTRIBUTING.adoc.

**Comment by hferentschik** [comment]
> It's also entirely possible to make the contribution guidelines far more visible in the existing documentation without requiring movement/symlinking of CONTRIBUTING.adoc.

Right, but you also want to avoid duplication, no? But if you guys think there is content missing in the docs and you also believe there is value in CONTRIBUTING.adoc, some level of duplication is needed.

**Comment by robin-owen** [comment]
> Right, but you also want to avoid duplication, no?

Yes, apologies for not being clear. At present, the contributing guidelines are linked to as part of the introductory information in **_contributing/index.adoc_** [1] ("learn about the project and how to contribute"). This could be made far more visible by prepending an item to the list currently on that page. For example:

```adoc
- link:https://github.com/minishift/minishift/blob/master/CONTRIBUTING.adoc[Contribution Guidelines]
- xref:../contributing/developing.adoc#[Developing {project}]
- xref:../contributing/ci.adoc#[{project} CI]
//  --snip--
```

This way, even if someone is simply skimming the page for information, the contribution guidelines are the first item seen. We don't duplicate the information anywhere, but it's far more discoverable.

[1] https://github.com/minishift/minishift/blob/master/docs/source/contributing/index.adoc

**Comment by hferentschik** [comment]
> This way, even if someone is simply skimming the page for information, the contribution guidelines are the first item seen. We don't duplicate the information anywhere, but it's far more discoverable.

+1 Got you

**Comment by LalatenduMohanty** [comment]
> This way, even if someone is simply skimming the page for information, the contribution guidelines are the first item seen. We don't duplicate the information anywhere, but it's far more discoverable.

+1 . I have definitely missed the link in the existing docs. So lets make it more discoverable.

**Comment by robin-owen** [comment]
I can go ahead and get a PR for this in moments if we're all in agreement here.

Just for clarification, I don't think we need to do anything more than add a second, more visible link to **_CONTRIBUTING.adoc_** in **_docs/source/contributing/index.adoc_**. There's no need to remove the already existing link in my opinion.

Benefits are:

* Contribution guidelines are far more visible to the reader
* No duplication of already-existing information in CONTRIBUTING.adoc
* Information in CONTRIBUTING.adoc on the `master` branch should always be up-to-date

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1576
