### ISSUE TITLE
Clean up documentation

### ISSUE THREAD

**Issue by thatdocslady** [minishift/minishift#157]
This issue covers the following requirements:

- Restructure existing files in a hierarchical way, right now everything is in the root folder and some files need to be placed in /docs/ directory, etc
- Convert all docs to ASCIIDoc
- Clean up readme and other files as needed to be more user-friendly

**Comment by LalatenduMohanty** [comment]
@jimmidyson thoughts?

**Comment by jimmidyson** [comment]
:100: I have spent no time on docs since forking minikube so all help appreciated.

**Comment by thatdocslady** [comment]
@jimmidyson this is what I'm here for :-)

**Comment by jimmidyson** [comment]
Then make it so, docs wiz - thanks!

**Comment by hferentschik** [comment]
Duplicate of #138
