### ISSUE TITLE
oc can't connect minishift, because tls key

### ISSUE THREAD

**Issue by xiaods** [minishift/minishift#1573]
```
$ oc login https://192.168.64.6:8443 --token=_ltiB-_T80fm3csc8n-onjWh7vxLVSkrI3SJNsAXs80
error: Service Unavailable

```

**Comment by gbraad** [comment]
Sorry, more information is needed.
marking as invalid for now

**Comment by xiaods** [comment]
i want to use oc command line to connect minishift server, but i can't login.

**Comment by gbraad** [comment]
After deployment you are automatically logged in as developer, and using `oc login` you can use system:admin as the admin user. but alternatively use `os --as system:admin ...` to perform commands as a different user.

**Comment by xiaods** [comment]
`
$ oc
OpenShift Client

This client helps you develop, build, deploy, and run your applications on any OpenShift or Kubernetes compatible
platform. It also includes the administrative commands for managing a cluster under the 'adm' subcommand.

To create a new application, login to your server and then run new-app:

  oc login https://mycluster.mycompany.com
  oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git
  oc logs -f bc/ruby-ex

This will create an application based on the Docker image 'centos/ruby-22-centos7' that builds the source code from
GitHub. A build will start automatically, push the resulting image to the registry, and a deployment will roll that
change out in your project.

Once your application is deployed, use the status, describe, and get commands to see more about the created components:

  oc status
  oc describe deploymentconfig ruby-ex
  oc get pods

To make this application visible outside of the cluster, use the expose command on the service we just created to create
a 'route' (which will connect your application over the HTTP port to a public domain name).

  oc expose svc/ruby-ex
  oc status

You should now see the URL the application can be reached at.

To see the full list of commands supported, run 'oc --help'.
xiaods at XiaoTommydeMacBook-Pro in ~/go/src/github.com/openshift/origin on master*
$ minishift oc-env
export PATH="/Users/xiaods/.minishift/cache/oc/v3.6.0:$PATH"
# Run this command to configure your shell:
# eval $(minishift oc-env)
xiaods at XiaoTommydeMacBook-Pro in ~/go/src/github.com/openshift/origin on master*
$ export PATH="/Users/xiaods/.minishift/cache/oc/v3.6.0:$PATH"
xiaods at XiaoTommydeMacBook-Pro in ~/go/src/github.com/openshift/origin on master*
$ oc config use-context minishift
error: no context exists with the name: "minishift".

`

**Comment by xiaods** [comment]
i have resolve it. because i have install another minikube project tools, so it conflict with minishift.
when i clean the environment, it works like a charm.
