### ISSUE TITLE
Unable to switch to non existing profile 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1574]
I am having two profiles defined:

    $ minishift profile list
    - minishift	Does Not Exist
    - msa		Running	(active)

_msa_ is active and now I want to switch to the _minishift_ profile:

    $ minishift profile set minishift
    oc cli context could not changed for 'minishift'. Make sure the profile is in running state or restart if the problem persists.

I am getting an error message and I still on the _msa_ profile. 

I expect to be able to switch to the _minishift_ profile. If the VM does not exist or is not running, the current _oc_ context should be unset. It gets then reset when I either switch to a running profile or I run `minishift start` on the _minishift_ profile.

**Comment by hferentschik** [comment]
Funny enough with the latest changes, this works:

    $ minishift profile set snafu
    $ minishift profile list 
    - minishift	Does Not Exist
    - msa		Running
    - snafu		Does Not Exist	(active)

**Comment by LalatenduMohanty** [comment]
@hferentschik this is recently introduced by https://github.com/minishift/minishift/commit/c2aeff6604c57a7caaaf36ab534cce2053a2fafd. I missed it in the review.

**Comment by LalatenduMohanty** [comment]
Previously we used to print the message that teh oc context can not be changed but change the active profile anyways.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1578/
