### ISSUE TITLE
Use OCI storage for current image cache implementation 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1575]
As a pre step for issue #952 which will provide a way to cache arbitrary images from the Docker daemon we can switch the current 'docker load|save' approach with an OCI image cache based on [containers/image](https://github.com/containers/image).

**Comment by gbraad** [comment]
is this possible with the current state of containers/image?

**Comment by hferentschik** [comment]
In order to merge #1589, the following [containers/image](https://github.com/containers/image) pull requests needs to be merged:

- [ ] https://github.com/containers/image/pull/328
- [ ] https://github.com/containers/image/pull/326
- [ ] https://github.com/containers/image/pull/362
- [ ] https://github.com/containers/image/pull/325 (optional, not really required for our purposes)

**Comment by gbraad** [comment]
When the folder contains leftovers from the previous `image-caching` solution, the process will just stop and not report any error.

I would suggest to inform the user (as part of deprecation/transition) that a new cache needs to be created.

**Comment by praveenkumar** [comment]
@hferentschik Since you are working on this issue so I am assigned you here.

**Comment by hferentschik** [comment]
@praveenkumar, sure. Thanks.

**Comment by hferentschik** [comment]
Closing this issue, since now there is an implementation for #952
