### ISSUE TITLE
Integration log name contains colon

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1579]
With change of introducing timestamp into integration log's file name we overlooked that it contains a colon, which is not allowed symbol on Windows 7 and 10. Thus tests on these platforms do not create the log, or fails strictly - from my understandings Win7 just do not create the file, while Win10 fails the tests.

Current format:
```go
logFileName := fmt.Sprintf("integration_%d-%d-%d_%02d:%02d:%02d.log", t.Year(), t.Month(),
t.Day(), t.Hour(), t.Minute(), t.Second())
```

As fix we could probably just change colon for a hyphen resulting it:
```go
logFileName := fmt.Sprintf("integration_%d-%d-%d_%02d-%02d-%02d.log", t.Year(), t.Month(),
t.Day(), t.Hour(), t.Minute(), t.Second())
```

**Comment by hferentschik** [comment]
merged by pull request #1580
