### ISSUE TITLE
minishift start failing using xhyve driver

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#158]
I have a broken the minishift setup on my OS X setup. `minishift start` is failing for me.
I am using xhyve driver.

It had worked for me when first time I tried it. But the setup broke at some point. The initial installation was done using `brew cask install minishift`.  But at this point I am getting the same error if I download the minishift binary from releases and use it.

Steps to reproduce:
* minishift start

```
$ minishift start
Starting local OpenShift cluster...
E1125 11:45:53.385417     805 start.go:92] Error starting host: Error starting stopped host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
E1125 11:48:54.857884     805 start.go:92] Error starting host: Error starting stopped host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
E1125 11:51:56.251645     805 start.go:92] Error starting host: Error starting stopped host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
E1125 11:51:56.251703     805 start.go:98] Error starting host:  Error starting stopped host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
Error starting stopped host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
Error starting stopped host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```

**Comment by praveenkumar** [comment]
@LalatenduMohanty minishift and docker-machine share different directory structure and not aware of changes for each other. Minishift only uses libmachine component not whole docker-machine as tool.

```
16:50 $ ls -a ~ | grep docker
.docker

16:51 $ ls -a ~ | grep minishift
.minishift
```

**Comment by hferentschik** [comment]
As @praveenkumar is saying, you cannot get minishift info from docker-machine. The former keeps its metadata in ~/.minishift, the latter in ~/.docker/machine. 

If minishift won't start a good strategy is to delete _~/.minishift/machines/minishift/_. Or even the whole ~/.minishift directory if you want.

**Comment by LalatenduMohanty** [comment]
@hferentschik Sure, do you want to add any explanation why you closed this issue?

**Comment by LalatenduMohanty** [comment]
@hferentschik I will consider this as a bug unless we find the root cause of the issue and then decide.

**Comment by LalatenduMohanty** [comment]
@praveenkumar @hferentschik I have updated the issue and removed `docker-machine` text from the issue.

**Comment by hferentschik** [comment]
> Sure, do you want to add any explanation why you closed this issue?

Mainly because of the title and the reference to docker-machine. I felt there was not much if anything to go about. IMO you got into an inconsistent state. Can you actually re-produce this?

**Comment by LalatenduMohanty** [comment]
@hferentschik Not sure about reproducing it as I can not fix the current broken setup. Deleting .minishift directory does not help much.  I am debugging the issue and will update here if I find something.

**Comment by hferentschik** [comment]
This might be a duplicate of issue #153

**Comment by LalatenduMohanty** [comment]
I can use minishift with Vrtualbox on that machine without any issue e.g. `minishift start --vm-driver=virtualbox`

**Comment by LalatenduMohanty** [comment]
It turned out to be an issue with the compiled (i.e. go build) binary of  https://github.com/zchee/docker-machine-driver-xhyve. Minishift by default uses `Virtio9pFolder: "/Users"` which needs `lib9p` sub module to be complied. But `go build` is not compiling the submodule. Once I use the released xhyve driver, it started to work. 

[1] https://github.com/kubernetes/minikube/issues/646#issuecomment-254463366
