### ISSUE TITLE
Add .github/ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1581]
### General information

  * Minishift version: 
  * Download from: github releases / brew / chocolatey
  * OS: Linux / macOS / Windows
  * OS version/distro: 
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox
  * `minishift start --show-libmachine-logs -v5`
    If long, please consider posting this on http://gists.github.com/ and post the link in your issue

#### Steps to reproduce

  1. 
  2. 
  3. 
  4.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1582
