### ISSUE TITLE
minishift starts fails on Fedora with German locale

### ISSUE THREAD

**Issue by hygl** [minishift/minishift#1583]
minishift 1.7.0
fedora 26 

Minishift does not start with german locale, when I change to "en_US:UTF-8" it works. 

```
[hygl@localhost ~]$ virsh net-list --all
 Name                 Status     Automatischer Start Bleibend
----------------------------------------------------------

[hygl@localhost ~]$ sudo virsh net-list --all
 Name                 Status     Automatischer Start Bleibend
----------------------------------------------------------
 default              Aktiv      ja            ja

[hygl@localhost ~]$ groups
hygl wheel libvirt docker
[hygl@localhost ~]$ minishift start --metrics
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present and active ... FAIL
   See the 'Setting Up the Driver Plug-in' topic for more information`
```

**Comment by LalatenduMohanty** [comment]
@hygl Thanks for the report. Minishift does have any internationalization and localization support IAFAIK. We will work towards fixing it.

**Comment by gbraad** [comment]
@agajdosi locale-based testing also needed on Linux. I think we can create a general task to have our tests also run against other than `lc_all=en_us.utf8`

@LalatenduMohanty this issue seems to come from the driver plugin or libmachine :-s. unfortunately these only do text-based checks to determine the state of the VM. This likely also affects minikube, might be a good idea to see what their stance on this is.

**Comment by gbraad** [comment]
I see the following options:

  1. We make the libvirt default network check WARN instead if FAIL.
  2. We remove the 'active' check from the network check
  3. We do both
  4. We do nothing

/cc: @anjannath

**Comment by gbraad** [comment]
Reproducible and fixable as:

```
$ LC_ALL=de_DE.UTF-8 virsh --connect qemu:///system net-list
```

     Name                 Status     Automatischer Start Bleibend
    ----------------------------------------------------------
     default              Aktiv      ja            ja
     docker-machines      Aktiv      ja            ja

```
$ export LC_ALL=de_DE.UTF-8
$ virsh --connect  qemu:///system net-list
```

     Name                 Status     Automatischer Start Bleibend
    ----------------------------------------------------------
     default              Aktiv      ja            ja
     docker-machines      Aktiv      ja            ja

```
$ LC_ALL=en_US.UTF-8 virsh --connect qemu:///system net-list
```

     Name                 State      Autostart     Persistent
    ----------------------------------------------------------
     default              active     yes           yes
     docker-machines      active     yes           yes

**Comment by gbraad** [comment]
@hygl Please test with the following version: http://artifacts.ci.centos.org/minishift/minishift/pr/1593/linux-amd64/

**Comment by hygl** [comment]
@gbraad works for me.

**Comment by anjannath** [comment]
Hey @gbraad This is fixed now..right? Except adding it to documentation (No. 6)

**Comment by gbraad** [comment]
didn't add a unittest for ReplaceEnv yet. have been debugging a possible
major/critical issue

**Comment by LorbusChris** [comment]
Has this been fixed?
I had to run `LC_ALL=en_US.UTF-8 minishift start` to get it going.

**Comment by budhrg** [comment]
Yes @LorbusChris , please use later version.
