### ISSUE TITLE
Confusing message when switching profiles

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1591]
Following up on issue #1578, I am trying to switch  to an existing profile where the VM is not started:

    $ minishift profile set msa
     oc cli context could not changed for 'msa'. Make sure the profile is in running state or restart if the problem persists.
    Profile 'msa' set as active profile
    $ minishift profile list
     - minishift	Stopped
     - bar		Does Not Exist
     - msa		Stopped	(active)
     - snafu        Does Not Exist

I can now switch to the profile, but still get the message "oc cli context could not changed for 'msa'. Make sure the profile is in running state or restart if the problem persists." Apart of the misleading wording I am wondering why this is relevant. It gives me as a user the impression that something went wrong, but it is not. IMO this message should be removed. Switching to a profile whose VM does not exist or is not running, should just unset any exiting context. The context should then be set when `start` is executed. 

Regarding the message itself. Right now there is at the very least a 'be' missing, as in "oc cli context could not be changed for 'msa'.". However, even then the message is not quite accurate. It should be more like: "No oc CLI context could be activated for the 'msa' profile."

**Comment by praveenkumar** [comment]
@hferentschik I think we should add a check if VM running then only try to set `oc context` and add message which you specified during `minishift set <profile_name>` otherwise this message should be ignored.

**Comment by hferentschik** [comment]
>  I think we should add a check if VM running then only try to set oc context and add message which you specified during minishift set <profile_name> otherwise this message should be ignored.

I am not 100% sure what you mean. Let me see whether I understand you correctly. When we want to switch the oc CLI context as part of a profile switch we check whether the VM is running. If it is running, we try to switch the CLI context. If it succeeds, no worries. If it fails, we display an error. If the VM does not exist or is not started, we unset the current CLI context and no error is reported. Does that align with what you have in mind?

**Comment by praveenkumar** [comment]
> Does that align with what you have in mind?

Yes, that's exactly I have in mind. If a VM doesn't exist or not started then we switch the context but don't show the oc cli context error.

**Comment by LalatenduMohanty** [comment]
> If it is running, we try to switch the CLI context. If it succeeds, no worries. If it fails, we display an error. If the VM does not exist or is not started, we unset the current CLI context and no error is reported

+1. However we do not have any existing code for unsetting the context, so it needs to be written.

**Comment by hferentschik** [comment]
> However we do not have any existing code for unsetting the context, so it needs to be written.

Sure.

**Comment by anjannath** [comment]
@hferentschik @LalatenduMohanty We don't really need to unset the context, as the context is updated in [PersistentPreRun](https://github.com/minishift/minishift/blob/76219ae13db1c7192109b8a963318af8fa5ad242/cmd/minishift/cmd/root.go#L132) so it always gets updated with the default profile, and we don't run into risk of running `oc` commands which are intended for a different conext.

**Comment by hferentschik** [comment]
> We don't really need to unset the context, as the context is updated in PersistentPreRun so it always gets updated with the default profile, and we don't run into risk of running oc commands which are intended for a different conext.

How does this piece of code help? So say I am using profile 'minishift' and hence using the oc CLI context 'minishift'. Now I run `minishift profile set foo`. Foo does not exist, so the profile gets switched, but there is no oc CLI context to switch to. The currently set one, however, is still 'minishift', not 'foo', right? So if I try to execute an _oc_ command, it would run against the 'minishift profile'. What I would expect though, is to get queried for the oc login credentials again, since there should be no active context. Does this make sense? Can you try the described workflow and check how _oc_ behaves?

**Comment by anjannath** [comment]
@hferentschik I tried the workflow here's a [pastebin](https://paste.fedoraproject.org/paste/U7ENBLt~J7bzF2e1ZnRkyg), and the commands will be run against previous context because the `oc` binary in the `PATH` is still the old one, we need to add the new `oc` binary of the profile to the path, which is created upon `m start`. if we run `minishift oc-env` after `minishift profile set foo` we will get an error 
```
Cannot find the OpenShift client binary.
Make sure that OpenShift was provisioned successfully.
```
so from what i understand we have to remove the old `oc` from the `PATH` or revoke its credentials to prevent it from running the commands against the old context, is that what are you suggesting?

**Comment by anjannath** [comment]
So @LalatenduMohanty and i had a discussion, we found out a solution to this issue, the way we can achieve this or avoid `oc` running commands gainst the previous context, is to remove the previous `oc` context entirely.
When switching from a profile, we check if it's context exists and if it does we delete it using `oc config delete-context` and set the new profile as active, if the previous profile's context does not exist then we do nothing and just make the new profile active.

there'll be a new helper function `OcRunner.DeleteCliContext` which would wrap the oc command.

**Comment by hferentschik** [comment]
> so from what i understand we have to remove the old oc from the PATH or revoke its credentials to prevent it from running the commands against the old context, is that what are you suggesting?

The CLI context is not directly related to the _oc_ binary on the PATH. What we have to do is to work with _~/.kube/config_.

> When switching from a profile, we check if it's context exists and if it does we delete it using oc config delete-context and set the new profile as active, if the previous profile's context does not exist then we do nothing and just make the new profile active.

Sounds reasonable. Might also help to keep the config tidy. We need to test though, whether deleting the context and then re-creating it when switching back, also requires a new login. We don't want that. I cannot remember out of the top of my head how the config entries are stitched together. 

> there'll be a new helper function OcRunner.DeleteCliContext which would wrap the oc command.

Before writing the code, please verify it will give us the desired behaviour. Just manually edit the config file between profile switches and see what happens.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1621
