### ISSUE TITLE
Unclear display of active profile

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1592]
Currently a `minishift profile list` displays like:

    $ minishift profile list
     - minishift	Stopped
     - bar		Does Not Exist
     - msa		Stopped	(active)
     - snafu        Does Not Exist

The active marker '(active)' disappears in the VM status message. Instead of appended to the status, it should display in tabular form in its own column.

**Comment by anjannath** [comment]
@hferentschik WDYT about this??
```
+-----------+----------------+--------+
|  PROFILE  |   VM STATUS    | STATE  |
+-----------+----------------+--------+
| minishift | Stopped        |        |
| anjan     | Stopped        | Active |
| foo       | Does Not Exist |        |
+-----------+----------------+--------+
```

**Comment by gbraad** [comment]
Please, let's not start using OpenStack-like table listings...

Just use a tab writer... and always place active at the top, and provide the rest as sorted added to the end?

**Comment by hferentschik** [comment]
> Just use a tab writer... and always place active at the top, and provide the rest as sorted added to the end?

+1. I am not a fan of this either. Tab writer will do just fine.

**Comment by anjannath** [comment]
@gbraad @hferentschik I thought the tabular form looked more pleasing, but using a tabwriter now. Also i have to iterate over the `profiles` slice twice to have a sorted output, you guys can review that in the PR and suggest a nicer solution.

**Comment by LalatenduMohanty** [comment]
@hferentschik so I think we just needs to add more tabs before the `(active)` string.  I think we should sort the profile names before printing but not sure if we want to print the active profile as the first one. cc @gbraad @anjannath

**Comment by anjannath** [comment]
@LalatenduMohanty Printing the active profile first  makes sense to me, because then it'll attract more attention, and that's what we are trying to do.

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/pull/1599
