### ISSUE TITLE
 could not find capabilities for domaintype=kvm

### ISSUE THREAD

**Issue by delubi** [minishift/minishift#1594]
#I'm trying to start up minishift in a VM hosted on ESXi host. Getting the following errors during startup.

```
minishift start --iso-url=file:///root/minishift-b2d.iso
-- Checking if KVM driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ...
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present and active ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ........ FAIL E1020 11:23:47.967627    2001 start.go:355] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: [Code-8] [Domain-44] invalid argument: could not find capabilities for domaintype=kvm . Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: [Code-8] [Domain-44] invalid argument: could not find capabilities for domaintype=kvm
```

The ESXi host already have Virtualization Technology option enabled.

Can someone help identify what the problem is?

Thanks,
Forrest

**Comment by gbraad** [comment]
You will need a way to support nested virtualization. I am unsure if ESXi is able to allow this for use with KVM.

It is in a way an unsupported setup. We only develop for use on bare-metal...

**Comment by gbraad** [comment]
this is what I can find about enabling this:

  * http://www.bloggerbaru.com/how-to-enable-nested-virtualization-on-vmware-esxi-5-0esxi-5-1esxi-5-5esxi-6-0/
  * https://www.virtuallyghetto.com/2012/08/how-to-enable-nested-esxi-other.html

Closing the issue with a 'wontfix'.
