### ISSUE TITLE
Issues while running minikube and minishift in parallel

### ISSUE THREAD

**Issue by surajssd** [minishift/minishift#1596]
**Type of issue**:

/kind feature-request

**Problem**:

I have on my machine, an instance of minikube running where I also run minishift. Now problem occurs when changing contexts/clusters, I have to run really long oc commands. Later I also discovered that minishift has a sub-command which you can use to set appropriate context, which worked for me.

**Proposal**:

So how about minishift shows me command to run to use the cluster that was started right now? Which minishift does not do right now!

**What should happen?**:

I propose to have a help at the end that might look something like this:
```
$ minishift start --cpus 4 --memory 8192 
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
...
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.16:8443

Run following command to use this cluster:
    minishift profile set minishift-1
```

(**Note**: `minishift-1` I just made up this name, I am not sure how minishift handles naming of multiple instances.)

**Steps to reproduce**:

```
$ minishift status
Minishift:  Stopped
Profile:    minishift
OpenShift:  Stopped
DiskUsage:  Unknown

```
```
 $ minikube start
 $ minishift start
```
now run oc commands and see if it works, oc still points to the minikube cluster, verify that by running

```
 $ oc config current-context
```
if it says `minikube` then minishift did not make config changes properly!

**Comment by LalatenduMohanty** [comment]
@surajssd  when you start an profile using the `minishift start` command e.g. `minishift start --profile foo` the profile is automatically set to active profile. you can check `profile list` after the start. So as the profile get set to active by-default , so IMO it does not make sense to tell user the command to set it active.

**Comment by gbraad** [comment]
Can you motivate this more, such as what is missing at the moment? Maybe a different message can be displayed...

**Comment by LalatenduMohanty** [comment]
@surajssd @gbraad I am working on the profile documentation right now, I think that would make few things more clear.

**Comment by gbraad** [comment]
Might be helpful to share this early with @robin-owen for peer-review

**Comment by surajssd** [comment]
So the thing is that when I am using mix of minikube and minishift, minishift does not reflect changes in `~/.kube/config` for me. oc was still talking to minikube, so I had to struggle with finding the cluster ip and setting proper cluster context and then `oc` worked for me, so it is better if minishift told me what command to run similar to the way it tells me how to login.

**Comment by surajssd** [comment]
```
$ minikube start --vm-driver kvm --cpus 4 --memory 6000
Starting local Kubernetes v1.7.5 cluster...
Starting VM...
Downloading Minikube ISO
 139.09 MB / 139.09 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
```

`Kubectl is now configured to use the cluster.` is doing it automatically if minishift also did this it will be really helpful.

**Comment by LalatenduMohanty** [comment]
@surajssd I think this will be fixed when we address https://github.com/minishift/minishift/issues/1515. This is also similar to what Minikube provides. WDYT?

**Comment by LalatenduMohanty** [comment]
The issue is Minishift does not set the context for `oc` when minishift is restarting i.e. stop->start. But for fresh starts it sets the context properly. So you are are seeing this issue.
