### ISSUE TITLE
Minishift start not working on OS X Sierra

### ISSUE THREAD

**Issue by stevef1uk** [minishift/minishift#160]
I keep getting:
(minishift) DBG | Not there yet 1/60, error: IP not found for MAC  in DHCP leases
(minishift) Waiting on a pseudo-terminal to be ready... virtio_net: Could not create vmnet interface, permission denied or no entitlement?
(minishift) DBG | exit status 1 &{0xc82000c1a0} &{0xc82000c1c0}
(minishift) DBG | 
(minishift) DBG | Not there yet 2/60, error: IP not found for MAC  in DHCP leases
(minishift) DBG | 
(minishift) DBG | Not there yet 3/60, error: IP not found for MAC  in DHCP leases
(minishift) DBG | 

From the command line: 
minishift start  --memory=12000 --vm-driver=xhyve --v=999 --logtostderr  --show-libmachine-logs --cpus=4

I get the same rersult f I drop the --vm-driver=xhyve

**Comment by cescoffier** [comment]
@stevef1uk Did you try to delete the image and recreate it. It worked for me:

```
minishift delete
minishift start --memory=12000 --vm-driver=xhyve --v=999 --logtostderr --show-libmachine-logs --cpus=4
```

**Comment by stevef1uk** [comment]
No, but I deleted the .minishift directory without success

**Comment by LalatenduMohanty** [comment]
It is the same issue as https://github.com/kubernetes/minikube/issues/646

**Comment by jorgemoralespou** [comment]
I'm hitting the same issue but it's not related to Sierra, since I'm not on that version yet.

Starts fine in Virtualbox

**Comment by hferentschik** [comment]
I think this might be a variation of the issue documented here - https://github.com/minishift/minishift/blob/master/docs/troubleshooting.md#error-getting-state-for-host-machine-does-not-exist

If so, there is not much we can do about this for now. The lack of a hypervisor manager for xhyve is really a pita. Once in a inconsistent state, it really is hard to get back to a state where the xhyve backed VM is starting again. Editing the files mentioned in the docs is one thing, but a restart still needs to be also required. TBH, for now VirtualBox stays my preferred choice of hypervisor. At least I have a way to tell what the VM is doing and I have better options to recover.

@stevef1uk, any chance the referenced issues is the one you have been running into?

**Comment by stevef1uk** [comment]
Yes, I deleted the DHCP lease entry for mini shift tried again and it works! 

Thanks

**Comment by hferentschik** [comment]
> Yes, I deleted the DHCP lease entry for mini shift tried again and it works!

Awesome, thanks for the feedback. Much appreciated.
