### ISSUE TITLE
Improve 'Using Minishift' documentation 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1600]
There are a few things I'd like to address in order to then add documentation for #952.

* Rename "Managing Minishift" to "Basic Commands". Naming is ambiguous 
* Extract image caching and experimental features in their own topics
* Adjust cross-links
* Align header styles, eg headers should use present continuous

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1601
