### ISSUE TITLE
Correct inconsistencies in documentation

### ISSUE THREAD

**Issue by robin-owen** [minishift/minishift#1604]
At the moment, there are numerous small inconsistencies present throughout the documentation. These include inconsistent use of the following:

* Title case:
    - Title case should be used for all topic titles and section headings.
* References to `PATH` and other environment variables:
    - `PATH` is referred to as both PATH and `PATH`.
        * `PATH` should be used.
    - `MINISHIFT_HOME` is referred to as $MINISHIFT_HOME, MINISHIFT_HOME, and `MINISHIFT_HOME`.
        * `MINISHIFT_HOME` should be used.
* Styling of file path references:
    - Bold and italic are often used, sometimes only italic is present.
        * Bold and italic should be used.
* Styling of profile names:
    - Profile `foo` may appear as 'foo', `foo`, or foo.
        * `foo` should be used.

There may be other inconsistencies as well, but these were immediately apparent to me.

The rationale for the proposed forms comes from the OpenShift [Documentation Guidelines](https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc).

**Comment by hferentschik** [comment]
I think we used to be quite close at some stage to be consistent, but it is easy for "mistakes" to sneak in over time.

@robin-owen, we try to run some "tech" discussions every now and then. I would love to see a meeting where everyone gets an intro to the various style things you are pointing out. I know we are referencing the style guidelines in the development topic, but I fear not many really looked at it yet. WDYT?

**Comment by robin-owen** [comment]
@hferentschik, I agree, it looks like most of these inconsistencies have just been slowly sneaking in over time.

I'd like to make a small reference for our own style, perhaps in **_contributing/writing_docs.adoc_**. Hopefully, this can be easily glanced at so that documentation changes remain as stylistically consistent as possible.

In our case, we have a few edge cases that the OpenShift guidelines don't cover particularly well. As an example, the OpenShift guidelines use backticks to mark up environment variables and use the combination of bold and italic for file paths and directories. In our case, we have file paths which _start_ with an environment variable (`MINISHIFT_HOME`). Personally, I'm inclined to use only bold and italic markup in this case, but there's a reasonable argument for using backticks around the variable.

If we can have a discussion around edge cases such as this _and_ the overall style that we want to apply to the documentation, that would be great.

**Comment by hferentschik** [comment]
> I'd like to make a small reference for our own style, perhaps in contributing/writing_docs.adoc. Hopefully, this can be easily glanced at so that documentation changes remain as stylistically consistent as possible.

+1  I think a quick reference in our own docs make sense. Linking to the external guidelines just makes it less probable that people look at it. 

> In our case, we have a few edge cases that the OpenShift guidelines don't cover particularly well. As an example, the OpenShift guidelines use backticks to mark up environment variables and use the combination of bold and italic for file paths and directories. In our case, we have file paths which start with an environment variable (MINISHIFT_HOME). Personally, I'm inclined to use only bold and italic markup in this case, but there's a reasonable argument for using backticks around the variable.

+1 I have been wondering about these cases myself. Let's decide on how we want to do it and add it to our own quick reference.

> If we can have a discussion around edge cases such as this and the overall style that we want to apply to the documentation, that would be great.

+1

**Comment by robin-owen** [comment]
Noticed while reviewing #1605: references to profile names inconsistently use backticks, single quotes, or no style whatsoever. Following the OpenShift guidelines, we should be using backticks.

**Comment by robin-owen** [comment]
Resolved by #1684.
