### ISSUE TITLE
Extend the 'minishift status' command to show cache usage

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1609]
After introducing ISO image cache (and/or global cache), we will likely accumulate some images over time which could account for some disk space. it might be helpful to the user to somehow show the total disk space used for the cache, perhaps by means of `m status`.

**Comment by gbraad** [comment]
@praveenkumar @budhrg please a have look at the PR. There are maybe some minor things that can also be fixes, like the duplicated "Unknown", which could be a constant value, etc. But overall it looks good and can be merged as-is.

**Comment by LalatenduMohanty** [comment]
Resolved by #2369
