### ISSUE TITLE
Issues in updating minishift through "homebrew cask"

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#161]
Steps to reproduce:
* I had minishift 0.7.1 installed already 
* uninstall minishift
* install minishift
* Run any minishift commands. It will try to update it to latest version.
```
$ brew cask uninstall minishift
==> Removing Binary symlink: '/usr/local/bin/minishift'
```
```
$ brew cask install minishift
==> Satisfying dependencies
complete
==> Downloading https://github.com/jimmidyson/minishift/releases/download/v0.7.1/minishift-darwin-amd64
Already downloaded: /Users/lmohanty/Library/Caches/Homebrew/Cask/minishift--0.7.1
==> Verifying checksum for Cask minishift
==> Symlinking Binary 'minishift-darwin-amd64' to '/usr/local/bin/minishift'
🍺  minishift was successfully installed!
```
Error:
```
$ minishift status
There is a newer version of minishift available. Do you want to
automatically update from v0.7.1 to v0.9.0 now? [y/N] y
Updating to version 0.9.0
Does Not Exist
```

**Comment by LalatenduMohanty** [comment]
How ever `$brew cask update minishift` worked fine.
* `$brew cask update minishift`
* `$brew cask status`

```
$ brew cask info minishift
minishift: 0.9.0
https://github.com/minishift/minishift
/usr/local/Caskroom/minishift/0.7.1 (67.2M)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/minishift.rb
==> Name
Minishift
==> Artifacts
minishift-darwin-amd64 (binary)
```

**Comment by jimmidyson** [comment]
I think this is due to the change of github organisation name. References to jimmidyson in code should all be updated, one I just noticed is the github releases url that is used for upgrades. We should also make sure the brew cask is updated properly & make a release with the new organisation name asap.

**Comment by LalatenduMohanty** [comment]
@jimmidyson Let me know if you need any help maintaining the `homebrew cask` or release process for minishift, I will be happy to help.

**Comment by hferentschik** [comment]
@LalatenduMohanty any idea how this works? I don't use homebrew, so I did not test this after the 1.0.0-beta.1 release. Not even sure what to look at!?

**Comment by LalatenduMohanty** [comment]
@hferentschik I had stopped looking in to the issue as I thought @jimmidyson will fix it. Let me look in to it.

**Comment by hferentschik** [comment]
> Let me look in to it.

Ok. My guess is, it might be broken still, but try.

**Comment by LalatenduMohanty** [comment]
I am going to close this as a duplicate of #204 as the issue is not relevent anymore because I can not install 0.7.1 through brew cask. Brew cask does not support installing previous versions of software , refer: https://github.com/caskroom/homebrew-cask/issues/471 and updating from 0.9.0 to latest will reproduce #204. 

```
$ brew cask install minishift
==> Satisfying dependencies
complete
==> Downloading https://github.com/minishift/minishift/releases/download/v0.9.0/minishift-darwin-amd64
Already downloaded: /Users/lmohanty/Library/Caches/Homebrew/Cask/minishift--0.9.0
==> Verifying checksum for Cask minishift
==> Symlinking Binary 'minishift-darwin-amd64' to '/usr/local/bin/minishift'
Password:
🍺  minishift was successfully installed!

$ sudo rm -rf ~/.minishift/

$ minishift start
There is a newer version of minishift available. Do you want to
automatically update from v0.9.0 to v1.0.0-beta.1 now? [y/N] y
Updating to version 1.0.0-beta.1
Downloading updated binary checksum to validate updated binary
E1223 00:28:23.989040    7980 update.go:155] Cannot download checksum: received 404
```
