### ISSUE TITLE
Drive letters and command prompts for Windows

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1613]
In several places of the documentation the usage on Windows is wrongly represented, such as `C:/` as the drive letter and `$` as the command prompt, or `minishift` as the binary:

eg.
https://github.com/minishift/minishift/blob/86c0f8c556db16abb0333c55a566c99a91e88619/docs/source/getting-started/installing.adoc#L70

https://github.com/minishift/minishift/blob/86c0f8c556db16abb0333c55a566c99a91e88619/docs/source/using/basic-usage.adoc#L102

https://github.com/minishift/minishift/blob/a9925e445a317f6e08a1d4d06a3cca11306fdd0a/docs/source/openshift/openshift-client-binary.adoc#L147

This needs to be consistent and suggested to change to:

  * `C:\` when talking about drives and paths
  * `C:\>` for the Command Prompt
  * `PS>` for PowerShell
  * `minishift.exe` when talked about the command

Note: only when specifically is referred to usage on Windows or in a particular shell.

**Comment by gbraad** [comment]
![image](https://user-images.githubusercontent.com/1894/31980258-d8a56416-b97d-11e7-9b9d-ed4bc311bb86.png)

**Comment by gbraad** [comment]
In this case explicitly usage of each shell is explained, but not clear due to the prompt:
```
For example, if you use PowerShell on Windows 7 or 10, modify the above command to:

$ minishift openshift config set --patch '{\"corsAllowedOrigins\": [\".*\"]}'
If you use Command Prompt you might need to use:

$ minishift openshift config set --patch "{\"corsAllowedOrigins\": [\".*\"]}"
```

https://github.com/minishift/minishift/blob/a9925e445a317f6e08a1d4d06a3cca11306fdd0a/docs/source/openshift/openshift-client-binary.adoc#L147

https://github.com/minishift/minishift/blob/a9925e445a317f6e08a1d4d06a3cca11306fdd0a/docs/source/openshift/openshift-client-binary.adoc#L150

**Comment by gbraad** [comment]
@robin-owen WDYT?

**Comment by robin-owen** [comment]
For the most part, I agree completely, and have noted some of these myself. As long as we keep these changes to areas of the documentation that are explicitly referring to usage on Windows, I think this makes perfect sense.

In the example given using `--iso-url`, though, aren't slashes (rather than Windows backslashes) appropriate for a URI?

**Comment by gbraad** [comment]
@robin-owen URLand URIs are an exception here, yes. But why I mentioned this example was for the prompt and the executable name:

```diff
- $ minishift start --iso-url file://c:/path/to/image.iso 
+ C:\> minishift.exe start --iso-url file://c:/path/to/image.iso 
```

as this small change demonstrates the use in a better way.

**Comment by gbraad** [comment]
```diff
For example, if you use PowerShell on Windows 7 or 10, modify the above command to:

- $ minishift openshift config set --patch '{\"corsAllowedOrigins\": [\".*\"]}'
+ PS> minishift.exe openshift config set --patch '{\"corsAllowedOrigins\": [\".*\"]}'

If you use Command Prompt you might need to use:

- $ minishift openshift config set --patch "{\"corsAllowedOrigins\": [\".*\"]}"
+ C:\> minishift.exe openshift config set --patch "{\"corsAllowedOrigins\": [\".*\"]}"
```

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/pull/1670
