### ISSUE TITLE
Missing root slash for the persistent disk path

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1614]
The persistent disk is shown as `mnt/sda1`, instead of `/mnt/sda1`

https://github.com/minishift/minishift/blob/86c0f8c556db16abb0333c55a566c99a91e88619/docs/source/troubleshooting/troubleshooting-misc.adoc#L26

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift/pull/1619
