### ISSUE TITLE
Feature request: Minishift should store essential VM/OpenShift parameter data with the profile

### ISSUE THREAD

**Issue by oweise** [minishift/minishift#1616]
Having profile support in minishift I think it is a viable use case to use different OpenShift versions with different profiles, so we can use the matching version for each project. We can do this by passing different OpenShift versions via parameter "--openshift-version" when we start a profile the first time.

Currently, as far as I see it, I am also obliged to use that parameter  each time I start an already existing profile, so the version used to initialize the profile gets used again. If I omit that then the default version will be used to start minishift (which in some situations simply might not work).

I think this information plus some more essential parameters, that were used creating a profile, should be stored with the profile and then on restarts be used from that storage.

Candidates from my perspective are:

- vm-driver
- memory
- disk-size (obviously)

**Comment by gbraad** [comment]
I am slightly confused, as memory and disk-size are configuration options and are therefore already part of the profile. Not sure what is missing. /cc: @LalatenduMohanty 


However, the VM-driver is kind of a weird one here. As this should be a global configuration. In most cases you can not have multiple hypervisors on your system, and if done is is often a hack/workaround. This is especially the case with Hyper-V, but also in the case of KVM (as when VirtualBox is running or vice versa, you can not start the other).

**Comment by gbraad** [comment]
Note: at the moment you can use environment variables to set global values.

**Comment by LalatenduMohanty** [comment]
@oweise it can be stored with the profile config files. I am not sure if you have used `minishift config set` command.  https://docs.openshift.org/latest/minishift/using/managing-minishift.html#persistent-configuration . Also as @gbraad suggested you can set environment variables. Also take a look at https://github.com/minishift/minishift/pull/1605 it has information you seek. 

```
$ minishift config
Modifies Minishift configuration properties. Some of the configuration properties are equivalent
to the options that you set when you run the minishift start command.

Configurable properties (enter as SUBCOMMAND):

 * iso-url
 * cpus
 * memory
 * disk-size
 * vm-driver
 * openshift-version
xxxxxxxxxxxx
```

**Comment by oweise** [comment]
Hi guys, thanks for your responses. So ok, the memory, CPU, disk size are all already baked into each profile. Didn't know that, good to hear.

In fact my own problems were not with those but with --vm-driver and --openshift-version which seem to be not stored into the profiles. If I start a profile with --vm-driver=virtualbox and then restart it without that switch it tries to use kvm on my machine. But that is a good use case for the environment variable approach, as I'm not going to use anything else but Virtualbox on my machine.

...which I can't say about the OpenShift-Version. I would like to use multiple profiles with different versions, as the projects deployed there would also be deployed to live clusters of varying version.

If "minishift config set" is the solution, what would be the best usage approach to this? Let's say I create a new profile "foo" where I need Openshift Version "v1.5.1". As far as I know we can only create new profiles by directly starting it. So I cannot set this configuration in the first place. I would do:

minishift start --profile foo --openshift-version=v1.5.1

Which starts the profile in the right version, but will not persist that information. After that I could use "minishift config set openshift-version v1.5.1" to actually fix the openshift version for that profile.

While that two-step process is doable I myself still think it would be better, if the openshift version was automatically fixed with the profile when it is first started.

**Comment by gbraad** [comment]
the VM-driver is surely persisted as part of the libmachine config, but not inside the configuration of a Minishift profile. I doubt about the need/use of this, as this is a static setting that is best to be set by
```
$ export MINISHIFT_VM_DRIVER=virtualbox
PS> $ENV:MINISIFT_VM_DRIVER="hyperv"
```

**Comment by oweise** [comment]
> about the OpenShift-version, sure... I agree. Have you tried: minishift config set openshift-version 1.4.1

Yes. But you need to create this profile first. And the only way to do that seems to be to directly start it (where I already need to specify a version). Possible to do that first and then set the config, but still not a good workflow in my opinion. Best would be that the version config was set on start automatically, according to what is started.

**Comment by gbraad** [comment]
`minishift profile set ...` will create the profile before starting

**Comment by oweise** [comment]
> `minishift profile set ...` will create the profile before starting

Yes, since recent minishift 1.8, just read that. So now I could create the profile and issue it an OpenShift version (only once). That works for me, thanks. Case closed.
