### ISSUE TITLE
Include link in README to the build process

### ISSUE THREAD

**Issue by jaseemabid** [minishift/minishift#1623]
The README doesn't say anything about building minishift from source, but it will be useful to have.

**Comment by hferentschik** [comment]
It's in the online docs - https://docs.openshift.org/latest/minishift/contributing/developing.html

**Comment by jaseemabid** [comment]
@hferentschik Awesome. Then maybe all we need is a link to the page from README

**Comment by gbraad** [comment]
We have a contributing topic but not a "Build Minishift" topic. Surely appreciated to link to the developing topic from the README.

**Comment by jaseemabid** [comment]
@gbraad @hferentschik https://github.com/minishift/minishift/pull/1624

**Comment by hferentschik** [comment]
Merged via pull request #1642

**Comment by jaseemabid** [comment]
Thanks
