### ISSUE TITLE
Minishift: Retrieving http://minishift.io/index.html ... FAIL

### ISSUE THREAD

**Issue by garyyang6** [minishift/minishift#1626]
I cannot start minishift. I installed docker, minishift, KVM driver and Virtural Box at CentOS 7.

minishift start
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present and active ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM .............. OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- Downloading OpenShift binary 'oc' version 'v3.6.0'
 34.72 MiB / 34.72 MiB [=======================================================================================================================================================] 100.00% 0s-- Downloading OpenShift v3.6.0 checksums ... OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ... 
   routing-suffix ... OK
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... 
   WARNING: Cannot verify Docker version
-- Checking for existing OpenShift container ... FAIL
   Error: unexpected error while checking OpenShift container state
   Caused By:
     Error: An error occurred trying to connect: Get https://192.168.42.64:2376/v1.24/containers/origin/json: remote error: tls: bad certificate
Error during 'cluster up' execution: Error starting the cluster.

minishift version
minishift v1.7.0+1549135
[root@docker ~]# docker --version
Docker version 17.09.0-ce, build afdb6d4

I am able to ping www.google.com. So, the network works fine. Below are errors.
ping www.google.com
PING www.google.com (172.217.12.100) 56(84) bytes of data.
64 bytes from atl26s14-in-f4.1e100.net (172.217.12.100): icmp_seq=1 ttl=51 time=145 ms

wget http://minishift.io/index.html
--2017-10-26 20:31:39--  http://minishift.io/index.html
Resolving lasproxy.is.ad.igt.com (lasproxy.is.ad.igt.com)... 10.220.15.21
Connecting to lasproxy.is.ad.igt.com (lasproxy.is.ad.igt.com)|10.220.15.21|:9000... connected.
Proxy request sent, awaiting response... 301 Moved Permanently
Location: https://minishift.io/index.html [following]
--2017-10-26 20:31:39--  https://minishift.io/index.html
Connecting to lasproxy.is.ad.igt.com (lasproxy.is.ad.igt.com)|10.220.15.21|:9000... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: \u2018index.html\u2019

**Comment by gbraad** [comment]
Please, when filing an issue, state your steps to reproduce, what is expected and the actual outcome.

Currently, the test you refer to
```
-- Checking HTTP connectivity from the VM ...
Retrieving http://minishift.io/index.html ... FAIL
```
does not support proxy settings, and therefore FAILs, but does not error the execution to continue. This is already recorded in another task and will be fixed.

Closing this issue

**Comment by gbraad** [comment]
I created a new issue based on earlier discussions. Ref: #1628

**Comment by santhanamuthu** [comment]
I resolve this .. I unset the config .. minishift config unset http-proxy and minishift config unset https-proxy

**Comment by minaxijoshi3101** [comment]
>minishift config unset http-proxy
Property name 'http-proxy' is not set

C:\Users\Minaxi>minishift config unset https-proxy
Property name 'https-proxy' is not set
