### ISSUE TITLE
Preflight: HTTP connectivity check should use proxy settings

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1628]
It seems the pre-flight check for HTTP connectivity does not use the proxy settings. This is due to libcurl not using httpsx_proxy environment variables. As part of https://github.com/minishift/minishift/issues/1534#issuecomment-335534679 this was highlighted. We likely have to implement the following:

`CURLOPT_PROXY`, `CURLOPT_PROXYUSERPWD` and `CURLOPT_PROXYTYPE` and set like `CURLPROXY_HTTPS` => https://curl.haxx.se/libcurl/c/CURLOPT_PROXYTYPE.html

**Comment by anjannath** [comment]
Fix in #2250

**Comment by gbraad** [comment]
Thanks. Can you ask him to use this issue number instead?

On Saturday, April 7, 2018, Anjan Nath <notifications@github.com> wrote:
> Fix in #2250
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/6Duy2aHLeDus1PcqeIR-26Iqu0pWVIp2VGWx2AEe3McFW9YHnk1f2MFYa4UW2SmtOySdM4HiprmghatKV3sk5y9I0plCJu2vZwUpmQmxliB7Mn2Eo054WAE305EK63y2WkQzSmVxzFbnQFOnu0MkN5l6-oWH4g=s0-d-e1-ft#https://github.com/notifications/beacon/AAAHZkrHHe0Nk5F4bTVcxflcqqSmwCm4ks5tmLcEgaJpZM4QIgyl.gif
>

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by svenstaro** [comment]
This can now be closed.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/2250
