### ISSUE TITLE
Minishift fails to start on Arch Linux with error `failed to initialize KVM: Permission denied`

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#1629]
The complete error message looks something like this: 
```
-- Starting Minishift VM .... FAIL E1027 09:19:46.631295    1869 start.go:356] Error starting the VM: 
Error starting stopped host: [Code-1] [Domain-10] internal error: process exited while connecting to 
monitor: Could not access KVM kernel module: Permission denied
2017-10-27T03:49:46.495880Z qemu-system-x86_64: failed to initialize KVM: Permission denied. 
Retrying.
Error starting the VM: Error starting stopped host: [Code-1] [Domain-10] internal error: process exited 
while connecting to monitor: Could not access KVM kernel module: Permission denied
2017-10-27T03:49:46.495880Z qemu-system-x86_64: failed to initialize KVM: Permission denied
```

This happens because correct permissions are not set for the user who is running minishift.

To fix it, after [installing the docker-machine-driver-kvm](https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html#kvm-driver-install), the current user needs to be added to `kvm` group, and qemu has to be told to use that group to run the instances.

In the qemu configuration file `/etc/libvirt/qemu.conf`.  add `group="kvm"`.
Then restart the machine for the changes to take effect, and NO a log out login won't work.

**Comment by gbraad** [comment]
Can you please explain the steps that were followed that led to this. Were the install instructions followed?

**Comment by anjannath** [comment]
@gbraad Yes, even after following the install instructions in the this error occures in Arch Linux.

**Comment by gbraad** [comment]
Thanks for updating the description. So in short, for some distros, such as Argh Linux, you might need to change the group of the libvirt daemon.

This might be a documentation thing... however, it is also very specific.

**Comment by anjannath** [comment]
@gbraad I think this is something that should go into the FAQ, as you said it's very specific to _Arch Linux_

**Comment by gbraad** [comment]
Well, we do have instructions for Debian?Ubuntu, and Fedora: https://github.com/minishift/minishift/blob/master/docs/source/getting-started/setting-up-driver-plugin.adoc#on-debianubuntu, so a specific _Argh Linux_ comment would be OK

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/pull/1654
