### ISSUE TITLE
run minishift without Internet connection

### ISSUE THREAD

**Issue by delubi** [minishift/minishift#1638]
I'm building minishift in a VM with no connection to Internet. When I start up minishift, there is error

[root@ontazupocav0003 ~]# minishift start --iso-url=file:///root/minishift-b2d.iso
-- Checking if KVM driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ...
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present and active ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .............................. OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
Error starting the cluster: Error attempting to download and cache oc: Cannot get the OpenShift release version v3.6.0: Get https://api.github.com/repos/openshift/origin/releases/tags/v3.6.0: dial tcp: lookup api.github.com on 10.69.0.153:53: dial udp 10.69.0.153:53: i/o timeout
[root@ontazupocav0003 ~]#

Looks like it's trying to connect to minishift.io and github but failed as there is no Internet connection. Is there a way to configure minishift to run in offline mode (with no Internet connection)?

Thanks,
Forrest

**Comment by delubi** [comment]
duplicate as 1637. sorry about that.

**Comment by gbraad** [comment]
Duplicate #1637
