### ISSUE TITLE
Remove (or annotate) Host folders table related to B2D and driver plugins

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1644]
While #1602 got addressed, it might even be advisable to remove this table entirely. We do not actively test these mounts as they are dependent on software inside the ISO images, and the driver plugin configuration.

We have our own solution #480 #317, while not perfect, we at least can test this and have 'full' control.

**Comment by gbraad** [comment]
See: https://issues.jboss.org/browse/CDK-167

**Comment by gbraad** [comment]
@LalatenduMohanty @robin-owen 

Note: added "Needs Investigation" as this needs some effort (discussion?) from our side.

**Comment by gbraad** [comment]
CentOS (RHEL)-based images do not come with the necessary support for Filesystem Passthrough (9p) that is used by xhyve:

```
[docker@minishift ~]$ cat /boot/config-3.10.0-693.2.2.el7.x86_64 |grep 9P
# CONFIG_NET_9P is not set
```

**Comment by gbraad** [comment]
The information in the table is not up-to-date or reflects reality (unless the driver settings are documented in the case of xhyve and NFS shares) or uses the correct version of the guest additions (as in the case of VirtualBox).

**Comment by robin-owen** [comment]
My apologies for missing this issue until just now. Having the information in the table out of date is problematic, and honestly, I'm in favor of removing the table entirely if we don't directly support it.

**Comment by gbraad** [comment]
@robin-owen the information mostly only applies to the B2D, and worst of all... it is not actively tested. So we can't even guarantee this will work.

**Comment by robin-owen** [comment]
@gbraad In that case, I absolutely think it should be removed. Having the table in our documentation means support is assumed.

**Comment by gbraad** [comment]
Documentation has been updated and the table has been removed. 👍
