### ISSUE TITLE
Failure in new builds due to external documentation link returning 404

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1651]
```
06:34:45 - build/openshift/exposing-services.html
06:34:45   *  External link https://docs.openshift.org/latest/dev_guide/getting_traffic_into_cluster.html#using-ingress-IP-self-service failed: 404 No error
```

Ref: https://ci.centos.org/job/minishift-pr/2430/console

**Comment by gbraad** [comment]
The actual documentation at OpenShift is at fault: https://docs.openshift.org/latest/minishift/openshift/exposing-services.html links to a non-existent link https://docs.openshift.org/latest/dev_guide/getting_traffic_into_cluster.html#using-ingress-IP-self-service

**Comment by hferentschik** [comment]
As an at least temporary fix we can link to 3.6 explicitly.

**Comment by hferentschik** [comment]
I guess this is actually what we are after - https://docs.openshift.org/latest/admin_guide/tcp_ingress_external_ports.html#unique-external-ips-ingress-traffic-configure-service

**Comment by LalatenduMohanty** [comment]
I think we replace the link with https://docs.openshift.org/latest/dev_guide/expose_service/expose_internal_ip_nodeport.html#getting-traffic-into-cluster-nodeport

**Comment by LalatenduMohanty** [comment]
Upstream issue: https://github.com/openshift/origin/issues/17165

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1658
