### ISSUE TITLE
minishift profile set downloads the oc client

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1660]
I have created a profile with openshift-version=3.7.0-rc.1  (profile1) then I create a new profile (profile 2), then I switch back to my profile 1, and I get:

```
minishift profile set istio
-- Downloading OpenShift binary 'oc' version 'v3.6.0'
 33.74 MiB / 33.74 MiB [==============================================================================================] 100.00% 0s-- Downloading OpenShift v3.6.0 checksums ... OK
oc cli context could not changed for 'istio'. Make sure the profile is in running state or restart if the problem persists.
Profile 'istio' set as active profile
```

And now I have in that profiles cache:
```
ls .minishift/profiles/istio/cache/oc/
v3.6.0/      v3.7.0-rc.0/
```

It should use the oc for that profile, or it should cache the client, etc in a global dir. Profiles feature is getting not too usable, if every command pulls down things again.

**Comment by gbraad** [comment]
This is an unwanted side-effect.

Did something of the profile already exist, or was this a new profile (only switched between them)?

**Comment by jorgemoralespou** [comment]
It did exist. So I'd mostly because when you do oc profile set, it don't take into account the OC client for that profile, and since that profile was created with 3.7.0-rc.0 and the image internally uses 3.6.0 it downloaded the client

**Comment by gbraad** [comment]
I try to understand which profile istio is, profile 1. Right? So what is
created in the folders for profile 2? Will replay this tomorrow.. As this
will likely fail for other specified versions of oc.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by jorgemoralespou** [comment]
@gbraad in this comment there's a description of how I create the profile.
https://github.com/minishift/minishift/issues/1661#issue-271219491

basically, in a fresh install, execute script:

create profile1
create profile2
minishift profile set profile1

you'll hit the issue

**Comment by gbraad** [comment]
This is actually similar and maybe even the same cause to an issue I filed
for CDK: https://issues.jboss.org/browse/CDK-204 It seems an action happens
between the switches that is unexpected.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by gbraad** [comment]
Which steps happen in:

./bin/minishift/minishift-create.sh istio

As that wasn't clear from that report. But yes, see the same... Same
behaviour as the CDK issue I filed.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by hferentschik** [comment]
There is also a bug at play here - https://github.com/minishift/minishift/pull/1621/files#r148792194.

**Comment by jorgemoralespou** [comment]
Yeah, sounds like it.

**Comment by gbraad** [comment]
@hferentschik I am not following, The code/bug you refer to is from a non-merged Pull Request.

Currently what happens in the set command is a check for a valid profile, and if it is:
https://github.com/minishift/minishift/blob/a9fc054fca4820cb9e249b71e6c28b01a7b123f8/cmd/minishift/cmd/profile/profile_set.go#L50

Which will run the oc command due means of:
https://github.com/minishift/minishift/blob/a9fc054fca4820cb9e249b71e6c28b01a7b123f8/cmd/minishift/cmd/util/oc.go#L56-L94

And in this part of code it does:
https://github.com/minishift/minishift/blob/a9fc054fca4820cb9e249b71e6c28b01a7b123f8/cmd/minishift/cmd/util/oc.go#L81-L82

This `configCmd` reference is not correct, but this however should only occur when the profile has a running instance.

**Comment by hferentschik** [comment]
> I am not following, The code/bug you refer to is from a non-merged Pull Request. Please let's only review this issue from the current codebase

I do. The code I am pointing out is just duplicating an error which already exists in the other methods in this utility class. The problem exists w/ or w/o this pull request. 

The rub is the following:

> viper.GetString(configCmd.OpenshiftVersion.Name)

This does only make sense in the context of the start command where the _--openshift-version_ is potentially specified. For all other commands, in particular, any _profile_ command, you will just get the default version. 

> CacheOc(clusterup.DetermineOcVersion(requestedOpenShiftVersion))

Is also a problem, depending on the state of the active profile. 

Generally, we try to use the _oc_ version matching the current Minishift instance. We keep the path for a created instance in the instance config from where it could be retrieved. There is also the possibility that we actually need to download _oc_ (when there is no cached version available), in which case we might have to download a version. Sticking to the idea of using an aligned version of _oc_ one would have to

1.  Check whether the active profile has a cached oc version. If so use it. If not goto 2.
2. Check whether the target profile has a cached oc version. If so use it. If not goto 3.
3. Determine correct _oc_ version to download (falling back to default, if not information is availabe). Download and use.

Also, in the context in which we use _oc_ with the profile commands, there is really no need to align versions. We just could, for now, find any cached version and use it. What we want to avoid is the unnecessary download.

Note, the problem goes away when we share the cache. We should not put too much effort into it. I recommend a function which looks for any cached _oc_ and used it. The same function (with adjusted functionality) can then be used when we have the shared cached. 

With #1589 and #1618 we can almost immediately switch to a shared cache.

**Comment by gbraad** [comment]
So, therefore I rather focus on the current code base. The problems partially stems from the fact that we do not persist the openshift-version after start. But also, we have the instanceconfig for this purpose. Right.

Even if we have a shared cache, the problem is in the invocation. If this is corrected, this would not happen. The download is unnecessary and very wrong, as this is also the command being used for the context switch.

**Comment by hferentschik** [comment]
> Even if we have a shared cache, the problem is in the invocation.

Well, in some cases you might have to do the download. 

 > If this is corrected, this would not happen. 

As said, the algorithm is to simplistic and does not cater for the various scenarios which exist.

> The download is unnecessary and very wrong, as this is also the command being used for the context switch.

In most cases it is not correct, but there are cases (no oc in the cache) where you need it. The whole logic needs to be wrapped up in a function which encapsulates the logic we want to apply. And depending on which standpoint you take, there are several alternatives.

**Comment by gbraad** [comment]
The simplest solution would be to check for the existence of `OcPath` in the instance config, as this only available when the deployment was successful, and then accordingly use this.

**Comment by hferentschik** [comment]
> The simplest solution would be to check for the existence of OcPath in the instance config, as this is only available when the deployment was successful, and then accordingly use this.

Right, except nothing stops you from switching between non started profiles in which case there won't be anything in instance config, but you still might have a cached oc instance in a different profile. Hence I suggest to just locate any _oc_ from the list of profiles and use it. For the use of _oc_ within the profile command, any _oc_ will do. Once we have the unified cache it will become even simpler in terms of locating the _oc_ version to use.

**Comment by gbraad** [comment]
If the profile has no ocpath, it never started completely.

Why in that case try to locate any oc? This sounds bad, as this you might find a very old version... To do what? Very unlikely OpenShift runs in target profile as ocpath was empty (never fully started).

Switching  to a non started profile and locating oc serves no purpose... You have no target anyways.

**Comment by LalatenduMohanty** [comment]
I think this got fixed as a side effect of https://github.com/minishift/minishift/commit/0a81e090908af4266556951d1f9aeadbf3155746. We need to cross check in v 1.10.0.

**Comment by gbraad** [comment]
Not reproducible in later versions
