### ISSUE TITLE
No indication of profile being started

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1662]
I would like to have as first line of the logs when you start, something like:

```
-- Starting minishift profile XYZ
```

**Comment by gbraad** [comment]
I also believe this is a duplicate, but I can not remember/find the issue related. But yes, this is considered part of the pre-start feedback, before the VM is actually started (just like the amount of memory, etc)

**Comment by hferentschik** [comment]
+1 We talked about this before, there are several commands which needs some indiction of the profile in their output. Most importantly the _start_ command.

**Comment by gbraad** [comment]
@ulyssessouza Please, print this line earlier.

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/pull/1713
