### ISSUE TITLE
Error on setting extra-clusterup-flags as config

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1664]
I'm trying to create a profile with --extra-clusterup-flags to enable the service catalog. I want to set that config in the persitent config, so that is always used, but I got an error when the command line is parsed.

```
minishift config set extra-clusterup-flags "--service-catalog=true"
Error: unknown flag: --service-catalog
Usage:
  minishift config set PROPERTY_NAME PROPERTY_VALUE [flags]

Flags:
  -h, --help   help for set

Global Flags:
      --alsologtostderr                  log to standard error as well as files
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory (default "")
      --logtostderr                      log to standard error instead of files
      --profile string                   Profile name (default "minishift")
      --show-libmachine-logs             Show logs from libmachine.
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

unknown flag: --service-catalog
```

No matter if I don't use quote, or single quote or double quote for the value of the flag, that it always parses the flag as a flag to the config, as can be seen in the last line of output.

**Comment by gbraad** [comment]
This is something in the config code, and I have seen this before. No matter what you try, the config command always tries to interpret anything that resembles a fla, and tries to compare this to the flags available on the command used, `config` in this case.

This I actually found in an unrelated part/task, but here it is really unwanted behaviour. But do consider, the `extra-cluster-flags` are part of the ENABLE_EXPERIMENTAL setting, so in this case, it is kind of 'unsupported' territory. I will classify it as a bug anyways, but it is kind of more a 'feature' as none of the other config options suffer from this.

**Comment by jorgemoralespou** [comment]
I guess this is the only option that receives a flag as param. I would not consider this part experimental since this is parsing the command line to set up config.

**Comment by gbraad** [comment]
I agree and disagree I mean. It is part of the experimental option, but
also this is a valid config option.

This likely fails somewhere in the flags library of Golang.


-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]
