### ISSUE TITLE
Delete a profile retains the profile dir, if it was active

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1665]
I have created a profile, used it, deleted it and it still shows in listing.

```
[jmorales:~] $ minishift profile list
- istio		Stopped
- minishift	Does Not Exist
- test		Stopped		(Active)
 [developer@192.168.64.10:8443/myproject]
[jmorales:~] $ minishift delete
You are deleting the Minishift VM: 'test'. Do you want to continue [y/N]?: y
Deleting the Minishift VM...
Minishift VM deleted.
 [developer@192.168.64.10:8443/myproject]
[jmorales:~] $ minishift profile list
- istio		Stopped
- minishift	Does Not Exist
- test		Does Not Exist	(Active)
```

As you can see, after doing a delete of profile test, it shows as "Does Not Exist (Active)"

I would consider that, deleting a profile would:
- Remove it completely
- Set active the default profile (as none can not be set)
- .kube/context would get cleaned of information on that profile

**Comment by jorgemoralespou** [comment]
I was going to close the issue as I have found that the command to do is:

```
minishift profile delete <PROFILE>
```

But I would still think that cleaning the .kube/config is needed, as I have information there relative to the profile I just deleted.

**Comment by gbraad** [comment]
Is this the same as you see here? #1412

**Comment by anjannath** [comment]
I too tried it out, works as expected:
```
$ minishift profile list
- minishift	Stopped		(Active)
$ minishift profile set abc
Profile 'abc' set as active profile
$ minishift profile list
- abc		Does Not Exist	(Active)
- minishift	Stopped
$ minishift profile delete abc --force
VM for profile 'abc' does not exist
Deleted:  /home/anath/.minishift/profiles/abc
Profile 'abc' deleted successfully
Switching to default profile 'minishift' as the active profile.
$ minishift profile list
- minishift	Stopped		(Active)
```

**Comment by budhrg** [comment]
> But I would still think that cleaning the .kube/config is needed, as I have information there relative to the profile I just deleted.

I don't think we should touch this file. What if the cleaning process didn't happen successfully. Even I believe minikube also doesn't clean their config from it.

**Comment by jorgemoralespou** [comment]
Does minikube log you in by default? The existence is different in both
tools, so how we interact did be different.
And I think they should handle this file as well.
What's the point of having stale entries in that file?

**Comment by gbraad** [comment]
AFAIR, minikube does modify the configuration file, but does not clean this on removal. (but I could be wrong) => gonna test now.

**Comment by praveenkumar** [comment]
I did also testing for minikube binary side and same result which @gbraad get. It doesn't touch anything from ~/.kube 

```
$ cat ~/.kube/config | wc -l
1431
[prkumar@dhcp193-13 bin]$ ls -al ~/.kube | wc -l
69
$ ./minikube start --vm-driver kvm
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
$ cat ~/.kube/config | wc -l
1431
$ ./minikube delete
Deleting local Kubernetes cluster...
Machine deleted.
$ cat ~/.kube/config | wc -l
1431
$ ls -al ~/.kube | wc -l
69
```

**Comment by jorgemoralespou** [comment]
I still think that leaving garbage in .kube/config is a PITA. I'd love for all the tools to clean the context when logging out.

**Comment by anjannath** [comment]
As part of PR #1621 the `current-context` is unset on profile switch, we could do the same upon profile delete, but it is not removing the context from the `.kube/config` file.
