### ISSUE TITLE
Start Minishift VM... stuck for more than an hour 

### ISSUE THREAD

**Issue by Dinesh63** [minishift/minishift#1667]
I am stuck at this.
PS C:\Users\dineshgodara> minishift start --insecure-registry 172.30.0.0/16 --insecure-registry minishift --memory 8GB --disk-size 40g --logging --metrics
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Starting Minishift VM ................................................................................................................................................................... ..............................................................................................................................................................................................................................................................

**Comment by gbraad** [comment]
Can you verify with `--show club machine blogs -v5` what happens. Likely you do not get an IP address assigned from your local network. You do have configured an external virtual switch that allows DHCP to assign you an address? If not, you need to assign one with the `--network-ipaddress` option (see documentation for more info)

**Comment by Dinesh63** [comment]
when i stopped that process and tried again then i am getting following

Command:
minishift start --insecure-registry 172.30.0.0/16 --insecure-registry minishift --memory 8GB --disk-size 40g --logging --metrics

Error:
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    8 GB
   vCPUs :    2
   Disk size: 40 GB
-- Starting Minishift VM ....................................................................... FAIL E1106 15:36:25.546365   10108 start.go:355] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: exit status 1. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: exit status 1


What is the complete command to check --show club machine blogs -v5

**Comment by gbraad** [comment]
Sorry, spellcheck on the phone

`--show-libmachine-logs -v5`

**Comment by Dinesh63** [comment]
Thank you,

It is working now, as i switched off hyper-v and removed existing virtual switch and restarted hyper-v and created new switch, as of now it is working properly.

**Comment by gbraad** [comment]
Good to hear.

Do consider using the static IP option, as OpenShift doesn't like changing addresses.

**Comment by gbraad** [comment]
Closing

**Comment by nitsmrinal** [comment]
Using SSH client type: external
(minishift) DBG | &{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@127.0.0.1 -o IdentitiesOnly=yes -i C:\Users\nitsm\.minishift\machines\minishift\id_rsa -p 61745] C:\WINDOWS\System32\OpenSSH\ssh.exe <nil>}
(minishift) DBG | About to run SSH command:
(minishift) DBG | ip addr show

**Comment by ericwanga** [comment]
Same issue, starting VM took forever. 
Then back home, out of office network, it worked straightaway. Tried to login to company VPN, starting VM failed again. Off VPN, worked again. So feels like network issue, or office firewall etc.
