### ISSUE TITLE
RBAC error set up the oc cli

### ISSUE THREAD

**Issue by mazzy89** [minishift/minishift#1668]
I'm running the following version of minishift:

```
$  minishift version                                                                                                              
minishift v1.8.0+6455fc3
```

When I try to login I get the following error:
```
$ oc login -u developer                                                                                                           
Server [https://localhost:8443]: 192.168.99.100:8443
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

Authentication required for https://192.168.99.100:8443 (openshift)
Username: developer
Password:
Login successful.

Error from server (Forbidden): User "developer" cannot create selfsubjectaccessreviews.authorization.k8s.io in project "default"
```

Definitely RBAC is not configured properly but how to fix this issue?

**Comment by gbraad** [comment]
Have you tried to redeploy?

```
$ minishift delete
$ minishift start
```

Note: what options did you pass on startup?

**Comment by jorgemoralespou** [comment]
User developer should not report default as project, as that is not a project that belongs to the user.

I'm guessing that your .kube/context file is messed somehow, but would not be easy to know without knowing what you did. Maybe you had a previous instance of minishift using the same ip, and hence you have an entry matching in .kube/context.

Actually, .kube/context file is very fragile, and at some point minishift should provide commands to interact with it in a more easy/convenient way.

**Comment by mazzy89** [comment]
@gbraad Fixed. Thank you.
