### ISSUE TITLE
Setting MINISHIFT_ENABLE_EXPERIMENTAL=y in minishift help should list available experimental options

### ISSUE THREAD

**Issue by cunningt** [minishift/minishift#1671]
MINISHIFT_ENABLE_EXPERIMENTAL=y minishift help 

should list experimental options.     If I do MINISHIFT_ENABLE_EXPERIMENTAL=y minishift help, neither --service-catalog or --extra-clusterup-flags are listed although they are listed in the documentation of experimental features : 

https://docs.openshift.org/latest/minishift/using/experimental-features.html

**Comment by robin-owen** [comment]
These exist in the help for `minishift start`:

```
$ MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start -h | grep 'experimental\|unsupported'
      --extra-clusterup-flags string    Specify optional flags for use with 'cluster up' (unsupported)
      --logging                         Install logging (experimental)
      --metrics                         Install metrics (experimental)
      --service-catalog                 Install service catalog (experimental)
```

**Comment by cunningt** [comment]
Shoot, totally missed that.
