### ISSUE TITLE
Unable to uninstall add-on when directory name is different than add-on name in meta data

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1672]
**Steps to reproduce**
- Create a addon directory `demoaddon` : `mkdir demoaddon`
- Create addon file : 
```
cat <<EOF > demoaddon/demoaddon.addon
# Name: demo-addon
# Description: Demo addon
# Required-Vars: USER,NAMESPACE
# Var-Defaults: NAMESPACE=kube-system

echo User is #{USER} and namespace is #{NAMESPACE}.
EOF
```
- Install addon
```
$ minishift addons install demoaddon
Addon 'demo-addon' installed
```
- List addons
``` 
$ minishift addons list
- admin-user     : disabled   P(0)
- anyuid         : disabled   P(0)
- demo-addon     : disabled   P(0)
- registry-route : disabled   P(0)
- xpaas          : disabled   P(0)
```
- Uninstall addon
```
$ minishift addons uninstall demo-addon
Cannot Uninstall the add-on demo-addon: Unable to find addon directory /home/budhram/.minishift/addons/demo-addon
```

**Comment by gbraad** [comment]
Is also any of the addons in `minishift/addons` or `minishift-addons/addons` at fault here or is this currently only an issue when manual steps are involved?

**Comment by praveenkumar** [comment]
The way we are doing right now for `uninstall` is assuming addon name is also the directory name and get this from add-on metadata. We might need to add another logic where we find the base directory name where addon is installed.

**Comment by budhrg** [comment]
> We might need to add another logic where we find the base directory name where addon is installed.

Or put a constraint on `Name` metadata header to be equal to addon directory name.

**Comment by praveenkumar** [comment]
> Or put a constraint on Name metadata header to be equal to addon directory name.

You mean we first parse the addon metadata and create directory named as addon metadata `Name`?

**Comment by anjannath** [comment]
This is still needs to be fixed.

**Comment by budhrg** [comment]
This should be easy fix. Will do.

**Comment by budhrg** [comment]
I am thinking of this solution as I mentioned in this comment https://github.com/minishift/minishift/issues/1672#issuecomment-343538579
```
Or put a constraint on Name metadata header to be equal to addon directory name.
```
@minishift/minishift-dev  WDYT ?
