### ISSUE TITLE
Locally installed dnsmasq server causes DNS lookups to fail for instances using the xhyve driver

### ISSUE THREAD

**Issue by dwojciec** [minishift/minishift#1674]
```
dwojciec-osx:bin dwojciec$ minishift start 
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... 
   Checking if /Users/dwojciec/.minishift/cache/iso/minishift-rhel7.iso exists ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Starting Minishift VM ............... OK
-- Registering machine using subscription-manager
   Registration in progress . FAIL [2s]
Error to register VM: ssh command error:
command : sudo -E subscription-manager register --auto-attach --username XXXXX --password 'XXXXX' 
err     : exit status 70
output  : Registering to: subscription.rhsm.redhat.com:443/subscription
Network error, unable to connect to server. Please see /var/log/rhsm/rhsm.log for more information.

I tried to start it using this command to have more information 
minishift start -v 5 --show-libmachine-logs
but not real additional information.
Except the version of subscription-manager

sudo -E subscription-manager version
SSH cmd err, output: <nil>: server type: This system is currently not registered.
subscription management server: Unknown
subscription management rules: Unknown
subscription-manager: 1.19.23-1.el7_4
python-rhsm: 1.19.10-1.el7_4
```

by using `minishift ssh` I checked the `/var/log/rhsm/rhsm.log`

see here https://gist.github.com/dwojciec/c05459256b0016214883ea52ae62cf21

any helps are welcome

**Comment by LalatenduMohanty** [comment]
@dwojciec Thanks for the report. As it is a CDK issue, It should be raised with CDK issue tracker i.e. https://issues.jboss.org/projects/CDK/issues/. Please let us know if want us to open the issue in CDK issue tracker.

**Comment by LalatenduMohanty** [comment]
Also I guess you are using CDK in a proxy environement, is that correct?

**Comment by gbraad** [comment]
```
2017-10-24 03:30:49,648 [INFO] yum:22036:MainThread @connection.py:821 - Connection built: host=subscription.rhsm.redhat.com port=443 handler=/subscription auth=identity_cert ca_dir=/etc/rhsm/ca/ insecure=False
2017-10-24 03:30:49,650 [INFO] yum:22036:MainThread @repolib.py:326 - repos updated: Repo updates

Total repo updates: 0
Updated
    <NONE>
Added (new)
    <NONE>
Deleted
    <NONE>
2017-10-24 03:30:52,707 [WARNING] yum:22036:MainThread @logutil.py:142 - logging already initialized
2017-10-24 03:30:53,368 [INFO] yum:22052:MainThread @connection.py:821 - Connection built: host=subscription.rhsm.redhat.com port=443 handler=/subscription auth=identity_cert ca_dir=/etc/rhsm/ca/ insecure=False
2017-10-24 03:30:53,370 [INFO] yum:22052:MainThread @repolib.py:326 - repos updated: Repo updates

Total repo updates: 0
Updated
    <NONE>
Added (new)
    <NONE>
Deleted
    <NONE>
2017-11-09 02:42:40,586 [INFO] rhsmd:1925:MainThread @rhsmd:270 - rhsmd started
2017-11-09 02:42:41,223 [INFO] subscription-manager:1947:MainThread @managercli.py:518 - X-Correlation-ID: 1d4ec4de17004c63b6c6606932eb2d77
2017-11-09 02:42:41,223 [INFO] subscription-manager:1947:MainThread @managercli.py:407 - Client Versions: {'python-rhsm': '1.19.10-1.el7_4', 'subscription-manager': '1.19.23-1.el7_4'}
2017-11-09 02:42:41,224 [INFO] subscription-manager:1947:MainThread @connection.py:821 - Connection built: host=subscription.rhsm.redhat.com port=443 handler=/subscription auth=identity_cert ca_dir=/etc/rhsm/ca/ insecure=False
2017-11-09 02:42:41,224 [INFO] subscription-manager:1947:MainThread @connection.py:821 - Connection built: host=subscription.rhsm.redhat.com port=443 handler=/subscription auth=none
2017-11-09 02:42:41,293 [ERROR] subscription-manager:1947:MainThread @utils.py:271 - Error while checking server version: [Errno -2] Name or service not known
2017-11-09 02:42:41,293 [ERROR] subscription-manager:1947:MainThread @utils.py:273 - [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/subscription_manager/utils.py", line 251, in get_server_versions
    if cp.supports_resource("status"):
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 847, in supports_resource
    self._load_supported_resources()
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 834, in _load_supported_resources
    resources_list = self.conn.request_get("/")
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 645, in request_get
    return self._request("GET", method, headers=headers)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 671, in _request
    info=info, headers=headers)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 527, in _request
    conn.request(request_type, handler, body=body, headers=final_headers)
  File "/usr/lib64/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1227, in connect
    HTTPConnection.connect(self)
  File "/usr/lib64/python2.7/httplib.py", line 807, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
2017-11-09 02:42:41,297 [INFO] subscription-manager:1947:MainThread @managercli.py:418 - Server Versions: {'rules-version': u'Unknown', 'candlepin': u'Unknown', 'server-type': u'This system is currently not registered.'}
2017-11-09 02:42:41,714 [INFO] subscription-manager:1968:MainThread @managercli.py:518 - X-Correlation-ID: b50f4c796e2f4e5795df2254e0e7e620
2017-11-09 02:42:41,714 [INFO] subscription-manager:1968:MainThread @managercli.py:407 - Client Versions: {'python-rhsm': '1.19.10-1.el7_4', 'subscription-manager': '1.19.23-1.el7_4'}
2017-11-09 02:42:41,715 [INFO] subscription-manager:1968:MainThread @connection.py:821 - Connection built: host=subscription.rhsm.redhat.com port=443 handler=/subscription auth=identity_cert ca_dir=/etc/rhsm/ca/ insecure=False
2017-11-09 02:42:41,715 [INFO] subscription-manager:1968:MainThread @connection.py:821 - Connection built: host=subscription.rhsm.redhat.com port=443 handler=/subscription auth=none
2017-11-09 02:42:41,715 [INFO] subscription-manager:1968:MainThread @managercli.py:407 - Client Versions: {'python-rhsm': '1.19.10-1.el7_4', 'subscription-manager': '1.19.23-1.el7_4'}
2017-11-09 02:42:41,726 [INFO] subscription-manager:1968:MainThread @managercli.py:382 - Consumer Identity name=None uuid=None
2017-11-09 02:42:41,727 [INFO] subscription-manager:1968:MainThread @managercli.py:382 - Consumer Identity name=None uuid=None
2017-11-09 02:42:41,728 [INFO] subscription-manager:1968:MainThread @connection.py:821 - Connection built: host=subscription.rhsm.redhat.com port=443 handler=/subscription auth=basic username=XXXXX
2017-11-09 02:42:41,779 [INFO] subscription-manager:1968:MainThread @dmiinfo.py:73 - Using dmidecode dump file: /dev/mem
2017-11-09 02:42:41,821 [INFO] subscription-manager:1968:MainThread @custom.py:85 - Loading custom facts from: /etc/rhsm/facts/cdk.facts
2017-11-09 02:42:41,829 [ERROR] subscription-manager:1968:MainThread @managercli.py:177 - Error during registration: [Errno -2] Name or service not known
2017-11-09 02:42:41,829 [ERROR] subscription-manager:1968:MainThread @managercli.py:178 - [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/subscription_manager/managercli.py", line 1184, in _do_command
    owner_key = self._determine_owner_key(admin_cp)
  File "/usr/lib/python2.7/site-packages/subscription_manager/managercli.py", line 1336, in _determine_owner_key
    owners = cp.getOwnerList(self.username)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 1117, in getOwnerList
    return self.conn.request_get(method)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 645, in request_get
    return self._request("GET", method, headers=headers)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 671, in _request
    info=info, headers=headers)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 527, in _request
    conn.request(request_type, handler, body=body, headers=final_headers)
  File "/usr/lib64/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1227, in connect
    HTTPConnection.connect(self)
  File "/usr/lib64/python2.7/httplib.py", line 807, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
```


This looks like a connectivity issue. Can you make sure the VM is able to resolve addresses?

```
$ minishift ssh -- ping 8.8.8.8
$ minishift ssh -- wget http://minishift.io/index,html
```

**Comment by praveenkumar** [comment]
This is mostly network connectivity issue which should be temporary I hope.

**Comment by gbraad** [comment]
This means that alos the `pre-flight checks start start host` need to happen before the registration happens. as at tht moment we can not verify connecttivity correctly.

**Comment by dwojciec** [comment]
I tried by skipping registration and by using a community image of minishift and it seems to be a connectivity issue:
minishift start --iso-url file://Users/dwojciec/bin/image/minishift.iso --skip-registration
-- Checking if xhyve driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Starting Minishift VM ............... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.173.0.21
-- Checking `oc` support for startup flags ... 
   host-volumes-dir ... OK
   routing-suffix ... OK
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
Starting OpenShift using registry.access.redhat.com/openshift3/ose:v3.6.173.0.21 ...
Pulling image registry.access.redhat.com/openshift3/ose:v3.6.173.0.21
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for registry.access.redhat.com/openshift3/ose:v3.6.173.0.21 image ... 
   Pulling image registry.access.redhat.com/openshift3/ose:v3.6.173.0.21
FAIL
   Error: error pulling Docker image registry.access.redhat.com/openshift3/ose:v3.6.173.0.21
   Caused By:
     Error: Get https://registry.access.redhat.com/v1/_ping: dial tcp: lookup registry.access.redhat.com on 192.168.64.1:53: read udp 192.168.64.6:39922->192.168.64.1:53: read: connection refused
Error during 'cluster up' execution: Error starting the cluster.

I'm directly connected to internet (without proxy) but I'm using MacOS High Sierra. Maybe the reason. I'm investigating more.

**Comment by dwojciec** [comment]
I added here the result of "minishift start --iso-url file://Users/dwojciec/bin/image/minishift.iso --skip-registration -v 5 --show-libmachine-logs"
https://gist.github.com/dwojciec/7cb651ef5aa935e6bd0727bfea9cf1ef

problem is located here 
curl -s -m 5 http://minishift.io/index.html > /dev/null 2>&1
SSH cmd err, output: exit status 6: 
FAIL
   VM cannot connect to external URL with HTTP

I have to solve it

**Comment by dwojciec** [comment]
dwojciec$ minishift ssh
Last login: Thu Nov  9 04:02:38 2017 from gateway
[docker@minishift ~]$ ping minishift.io
ping: minishift.io: Name or service not known
[docker@minishift ~]$ ping 104.28.22.36
PING 104.28.22.36 (104.28.22.36) 56(84) bytes of data.
64 bytes from 104.28.22.36: icmp_seq=1 ttl=52 time=28.0 ms
64 bytes from 104.28.22.36: icmp_seq=2 ttl=52 time=28.2 ms
64 bytes from 104.28.22.36: icmp_seq=3 ttl=52 time=27.9 ms
^C
--- 104.28.22.36 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2012ms
rtt min/avg/max/mdev = 27.915/28.054/28.247/0.196 ms
[docker@minishift ~]$ ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:57:14:34:f4  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.64.6  netmask 255.255.255.0  broadcast 192.168.64.255
        inet6 fe80::1411:1aff:fe8e:e4a6  prefixlen 64  scopeid 0x20<link>
        ether 16:11:1a:8e:e4:a6  txqueuelen 1000  (Ethernet)
        RX packets 2287  bytes 245237 (239.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1959  bytes 240600 (234.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 6  bytes 416 (416.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6  bytes 416 (416.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
[docker@minishift ~]$ hostname
minishift
[docker@minishift ~]$ hostname -i
127.0.1.1
[docker@minishift ~]$ cat /etc/resolv.conf 
# Generated by NetworkManager
nameserver 192.168.64.1
[docker@minishift ~]$ ping 192.168.64.1
PING 192.168.64.1 (192.168.64.1) 56(84) bytes of data.
64 bytes from 192.168.64.1: icmp_seq=1 ttl=64 time=0.251 ms
64 bytes from 192.168.64.1: icmp_seq=2 ttl=64 time=0.214 ms
64 bytes from 192.168.64.1: icmp_seq=3 ttl=64 time=0.247 ms
.....

[docker@minishift ~]$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=44 time=28.3 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=44 time=29.2 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=44 time=32.0 ms
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2006ms
rtt min/avg/max/mdev = 28.394/29.896/32.074/1.576 ms

[docker@minishift ~]$ sudo -i
[root@minishift ~]# systemctl status network
* network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2017-11-09 03:56:38 EST; 17min ago
     Docs: man:systemd-sysv-generator(8)

Nov 09 03:56:38 localhost systemd[1]: Starting LSB: Bring up/down networking...
Nov 09 03:56:38 localhost network[842]: Bringing up loopback interface:  [  OK  ]
Nov 09 03:56:38 localhost network[842]: Bringing up interface eth0:  [  OK  ]
Nov 09 03:56:38 localhost network[842]: Bringing up interface eth1:  Error: Connection activation failed: No s...tion.
Nov 09 03:56:38 localhost network[842]: [FAILED]
Nov 09 03:56:38 localhost systemd[1]: network.service: control process exited, code=exited status=1
Nov 09 03:56:38 localhost systemd[1]: Failed to start LSB: Bring up/down networking.
Nov 09 03:56:38 localhost systemd[1]: Unit network.service entered failed state.
Nov 09 03:56:38 localhost systemd[1]: network.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[root@minishift ~]# systemctl start network
Job for network.service failed because the control process exited with error code. See "systemctl status network.service" and "journalctl -xe" for details.

[root@minishift ~]# cat /etc/sysconfig/network-scripts/ifcfg-eth1 
DEVICE="eth1"
BOOTPROTO="dhcp"
ONBOOT="yes"
TYPE="Ethernet"
PERSISTENT_DHCLIENT="yes"
[root@minishift ~]# cat /etc/sysconfig/network-scripts/ifcfg-eth0 
DEVICE="eth0"
BOOTPROTO="dhcp"
ONBOOT="yes"
TYPE="Ethernet"
PERSISTENT_DHCLIENT="yes"
[root@minishift ~]# 

Checking now using the RHEL iso image

**Comment by gbraad** [comment]
This https://github.com/minishift/minishift/issues/1674#issuecomment-343089745 is not the issue, but  away to detect you have an issue with connectivity. There is an issue that is does not pick up proxy, but it usually does the trick. We do not make this test failing for this reason.

But, I can conclude there is an issue with your DNS. have you restarted your machine? Sometimes `xhyve` can have unpredictible results...

**Comment by dwojciec** [comment]
nslookup is not installed in the VM.

I compared with a colleague using the previous MAC OS version and the main difference is with the command netstat -tln

the result of mine 
[root@minishift ~]# netstat -tln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp6       0      0 :::111                  :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::2376                 :::*                    LISTEN 


and here the result of the command on my colleague laptop
[docker@minishift ~]$ netstat -tln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 127.0.0.1:10443         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:10444         0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8053            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN     
tcp6       0      0 :::111                  :::*                    LISTEN     
tcp6       0      0 :::1936                 :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::7001                 :::*                    LISTEN     
tcp6       0      0 :::4001                 :::*                    LISTEN     
tcp6       0      0 :::2376                 :::*                    LISTEN     
tcp6       0      0 :::10250                :::*                    LISTEN

I don't have all the  8443, 80 and 443 entries.

**Comment by dwojciec** [comment]
I tried another test 
 docker-machine create --driver xhyve xhyve-test
Running pre-create checks...
Creating machine...
(xhyve-test) Default Boot2Docker ISO is out-of-date, downloading the latest release...
(xhyve-test) Latest release for github.com/boot2docker/boot2docker is v17.10.0-ce
(xhyve-test) Downloading /Users/dwojciec/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v17.10.0-ce/boot2docker.iso...
(xhyve-test) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(xhyve-test) Copying /Users/dwojciec/.docker/machine/cache/boot2docker.iso to /Users/dwojciec/.docker/machine/machines/xhyve-test/boot2docker.iso...
(xhyve-test) Creating VM...
(xhyve-test) /dev/disk5          	                               	/Users/dwojciec/.docker/machine/machines/xhyve-test/b2d-image
(xhyve-test) "disk5" unmounted.
(xhyve-test) "disk5" ejected.
(xhyve-test) Generating 20000MB disk image...
(xhyve-test) created: /Users/dwojciec/.docker/machine/machines/xhyve-test/root-volume.sparsebundle
(xhyve-test) Creating SSH key...
(xhyve-test) Fix file permission...
(xhyve-test) Generate UUID...
(xhyve-test) Convert UUID to MAC address...
(xhyve-test) Starting xhyve-test...
(xhyve-test) Waiting for VM to come online...
(xhyve-test) Waiting on a pseudo-terminal to be ready... done
(xhyve-test) Hook up your terminal emulator to /dev/ttys002 in order to connect to your VM
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env xhyve-test
dwojciec-osx:bin dwojciec$ docker-machine env xhyve-test
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.64.2:2376"
export DOCKER_CERT_PATH="/Users/dwojciec/.docker/machine/machines/xhyve-test"
export DOCKER_MACHINE_NAME="xhyve-test"
# Run this command to configure your shell: 
# eval $(docker-machine env xhyve-test)
dwojciec-osx:bin dwojciec$ minishift ssh
Command failed: Machine 'minishift' does not exist. You need to run 'minishift start' first
dwojciec-osx:bin dwojciec$ docker-machine ssh
Error: No machine name(s) specified and no "default" machine exists
dwojciec-osx:bin dwojciec$ docker-machine ssh xhyve-test
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 17.10.0-ce, build HEAD : 34fe485 - Wed Oct 18 17:16:34 UTC 2017
Docker version 17.10.0-ce, build f4ffd25
docker@xhyve-test:~$ ping minishift.io
ping: bad address 'minishift.io'
docker@xhyve-test:~$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=44 time=28.149 ms
64 bytes from 8.8.8.8: seq=1 ttl=44 time=27.805 ms
64 bytes from 8.8.8.8: seq=2 ttl=44 time=27.462 ms
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 27.462/27.805/28.149 ms
docker@xhyve-test:~$ nslookup 
BusyBox v1.24.2 (2016-05-16 13:28:30 UTC) multi-call binary.

Usage: nslookup [HOST] [SERVER]

Query the nameserver for the IP address of the given HOST
optionally using a specified DNS server
docker@xhyve-test:~$ nslookup google.com
Server:    192.168.64.1
Address 1: 192.168.64.1

nslookup: can't resolve 'google.com'
docker@xhyve-test:~$ nslookup google.com 192.168.64.1
Server:    192.168.64.1
Address 1: 192.168.64.1

nslookup: can't resolve 'google.com'
docker@xhyve-test:~$ 

the VM generated is not 192.168.64.1 but 192.168.64.2 
it seems the problem is the issue mentionned here  https://github.com/zchee/docker-machine-driver-xhyve#does-not-clean-up-the-vmnet-when-remove-a-vm


tail -f /var/db/dhcpd_leases
{
	name=boot2docker
	ip_address=192.168.64.2
	hw_address=1,56:73:81:ca:2c:cf
	identifier=1,56:73:81:ca:2c:cf
	lease=0x5a05903b
}

**Comment by gbraad** [comment]
This is also part of our troubleshooting guide: https://docs.openshift.org/latest/minishift/troubleshooting/troubleshooting-driver-plugins.html#create-vmnet-interface-permission

This is an issue with how xhyve and the driver works. We have no influence of the IP configuration assignment at this moment (this is handed over to the driver). And concluding in your tests, this is confirmed as also docker-machine suffers from this problem. Please try to remove these entries from the lease file and try again.

**Comment by gbraad** [comment]
`nslookup` is available after doing:

```
$ minishift ssh -- sudo yum install -y bind-utils
```

Note: sorry, forgot about this fact...

**Comment by dwojciec** [comment]
@gbraad . I can't use `$ minishift ssh -- sudo yum install -y bind-utils`

because 

```
` minishift ssh -- sudo yum install -y bind-utils
tput: unknown terminal "unknown"

Installing additional packages on the root filesystem might exceed the allocated overlay size and lock the Minishift VM. Proceed with the installation at your own risk.
For more information, see https://docs.openshift.org/latest/minishift/troubleshooting/troubleshooting-misc.html#root-filesystem-exceeds-overlay-size
tput: unknown terminal "unknown"

Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 To enable Red Hat Subscription Management repositories:
     subscription-manager repos --enable <repo>
 To enable custom repositories:
     yum-config-manager --enable <repo>
Command failed: exit status 1
`
```

But by adding 8.8.8.8 inside /etc/resolv.conf I'm able to ping any URL link

```
[root@minishift ~]# ping www.amazon.com
ping: www.amazon.com: Name or service not known
[root@minishift ~]# cat /etc/resolv.conf 
# Generated by NetworkManager
nameserver 192.168.64.1
[root@minishift ~]# ping 192.168.64.1
PING 192.168.64.1 (192.168.64.1) 56(84) bytes of data.
64 bytes from 192.168.64.1: icmp_seq=1 ttl=64 time=0.259 ms
64 bytes from 192.168.64.1: icmp_seq=2 ttl=64 time=0.321 ms
64 bytes from 192.168.64.1: icmp_seq=3 ttl=64 time=0.311 ms
^C
--- 192.168.64.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2006ms
rtt min/avg/max/mdev = 0.259/0.297/0.321/0.027 ms
[root@minishift ~]# echo nameserver 8.8.8.8 > /etc/resolv.conf
[root@minishift ~]# ping www.amazon.com
PING d3ag4hukkh62yn.cloudfront.net (54.192.202.232) 56(84) bytes of data.
64 bytes from server-54-192-202-232.fra50.r.cloudfront.net (54.192.202.232): icmp_seq=1 ttl=245 time=27.1 ms
64 bytes from server-54-192-202-232.fra50.r.cloudfront.net (54.192.202.232): icmp_seq=2 ttl=245 time=27.6 ms
64 bytes from server-54-192-202-232.fra50.r.cloudfront.net (54.192.202.232): icmp_seq=3 ttl=245 time=27.6 ms
^C
--- d3ag4hukkh62yn.cloudfront.net ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2007ms
```

The problem I have seems very similar to this https://github.com/ailispaw/boot2docker-xhyve/issues/23
But don't know yet how to solve it.

**Comment by gbraad** [comment]
I'll check this in the morning, but this seems to be a problem on your host. It needs to provide a way to allow DNS requests to happen, but for some reason this doesn't.

There is a workaround to this, but this is not my preferred approach ATM, as this is still in development and will certainly not work yet with the RHEL images.

**Comment by dwojciec** [comment]
I solved it now. dnsmasq   ran on my MAC OSX I have just 

`sudo launchctl stop homebrew.mxcl.dnsmasq`

and now it's working 

```
dwojciec-osx:.minishift dwojciec$ minishift stop
Stopping local OpenShift cluster...
Cluster stopped.
dwojciec-osx:.minishift dwojciec$ minishift start
-- Checking if xhyve driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Starting Minishift VM ............... OK
-- Registering machine using subscription-manager
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.173.0.21
-- Checking `oc` support for startup flags ... 
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   routing-suffix ... OK
Starting OpenShift using registry.access.redhat.com/openshift3/ose:v3.6.173.0.21 ...
Pulling image registry.access.redhat.com/openshift3/ose:v3.6.173.0.21
Pulled 1/4 layers, 26% complete
Pulled 1/4 layers, 49% complete
Pulled 1/4 layers, 71% complete
Pulled 2/4 layers, 89% complete
Pulled 3/4 layers, 92% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.2:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

dwojciec-osx:.minishift dwojciec$ minishift ssh
Last login: Thu Nov  9 10:35:08 2017 from gateway
[docker@minishift ~]$ cat /etc/resolv.conf 
# Generated by NetworkManager
nameserver 192.168.64.1
[docker@minishift ~]$ ping minishift.io
PING minishift.io (104.28.22.36) 56(84) bytes of data.
64 bytes from 104.28.22.36 (104.28.22.36): icmp_seq=1 ttl=52 time=28.6 ms
64 bytes from 104.28.22.36 (104.28.22.36): icmp_seq=2 ttl=52 time=28.5 ms
64 bytes from 104.28.22.36 (104.28.22.36): icmp_seq=3 ttl=52 time=28.1 ms
https://192.168.64.2:844364 bytes from 104.28.22.36 (104.28.22.36): icmp_seq=4 ttl=52 time=28.3 ms
64 bytes from 104.28.22.36 (104.28.22.36): icmp_seq=5 ttl=52 time=27.3 ms
64 bytes from 104.28.22.36 (104.28.22.36): icmp_seq=6 ttl=52 time=27.8 ms
^C
--- minishift.io ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5005ms
rtt min/avg/max/mdev = 27.397/28.140/28.637/0.458 ms
[docker@minishift ~]$ 
```

Thanks again for all your help.

**Comment by dwojciec** [comment]
Problem solved due to dnsmasq running on MAC OSX

**Comment by gbraad** [comment]
I figured, but was unable to recall the service name ;-). Good to hear it works now. Thanks for the debug info, as this has been helpful...

**Comment by gbraad** [comment]
We might have to add an entry to the troubleshooting guide to mention this behaviour for the `xhyve` driver. Re-opening and labeling this as a docuementation task.

**Comment by sensadrome** [comment]
I am also seeing this error - and can confirm that either stopping the local dnsmasq server *or* making it listen on all interfaces (`listen-address=0.0.0.0`) will alleviate the issue (presumably the latter is not desired since it will break any internal dns?). 

It should also be noted that the error is reported in the console and spits out the RHN password which is, presumably, not desirable.

```
Registering machine using subscription-manager
Registration unsuccessful [554.5ms]
Error to register VM: ssh command error:
command : sudo -E subscription-manager register --auto-attach --username simon-13 --password 'MyActualPassword!'
```

**Comment by gbraad** [comment]
@sensadrome The error about seeing a password should be filed against CDK,  http://issues.jboss.org/ This is likely do to the way libmachine handles the ssh command (as it fails, it dumps it). Seems we didn't find all the cases...

**Comment by gbraad** [comment]
If dnsmasq can forward requests it would not be a problem. We do not actually use internal DNS but rely on xip/nip.io to provide an alternative to having local DNS (but needs connectivity).

**Comment by praveenkumar** [comment]
@LalatenduMohanty we need to put a proper milestone for this.

**Comment by budhrg** [comment]
@LalatenduMohanty we need to put a proper milestone for this.
