### ISSUE TITLE
Preflight check for Hyper-V setup too restrictive

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1675]
I have a new fresh Windows install, enabled Hyper-V and configured the external switch. I even set _HYPERV_VIRTUAL_SWITCH_. With or without this variable, I cannot pass the driver check:

    PS C:\Users\Administrator\Desktop> .\minishift.exe start
    -- Checking if requested hypervisor 'hyperv' is supported on this platform ..
    -- Checking if Hyper-V driver is installed ... OK
    -- Checking if Hyper-V driver is configured to use a Virtual Switch ... FAIL 

I then skip the driver checks via:

    > .\minishift.exe config set warn-check-hyperv-driver true

After that Minishift starts as expected.

**Comment by gbraad** [comment]
Please let me know what you have set as `HYPERV_VIRTUAL_SWITCH` ?

**Comment by gbraad** [comment]
The option `m config set warn-check-hyperv-driver true` will not fail the steps, but give the output... So I would like to know what the output was after setting this.

**Comment by gbraad** [comment]
A possible option for default: #1676

**Comment by gbraad** [comment]
Accidently closed

**Comment by hferentschik** [comment]
I will update once I am back to Hyper-V. For now, I am using VirtualBox. AFAIR there was no additonal output w/ or w/o warn-check-hyperv-driver set. When it was not set, the check just failed. 

I set HYPERV_VIRTUAL_SWITCH via:

     set HYPERV_VIRTUAL_SWITCH=External

as per docs https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html#hyper-v-driver

**Comment by gbraad** [comment]
Either must have been a typo, or a syntax error: In the command prompt, do not use `"`. Looking forward to the output...

For me it is currently "cannot reproduce" (using Hyper-V every day).

**Comment by hferentschik** [comment]
I think the problem is:

    PS C:\Users\Administrator> Get-Command Get-VM
    Get-Command : The term 'Get-VM' is not recognized as the name of a cmdlet,     function, script file, or operable program.
    Check the spelling of the name, or if a path was included, verify that the     path is correct and try again.
    At line:1 char:1
    + Get-Command Get-VM
    + ~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (Get-VM:String) [    Get-Command], CommandNotFoundException
        + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell    .Commands.GetCommandCommand

**Comment by gbraad** [comment]
how about `Get-VMHost` ?

**Comment by gbraad** [comment]
This is one of the essential commands, as it is used for vm state and network state: 
  * https://github.com/AlainRoy/docker-machine/blob/master/drivers/hyperv/hyperv.go#L136
  * https://github.com/AlainRoy/docker-machine/blob/master/drivers/hyperv/hyperv.go#L409

**Comment by hferentschik** [comment]
I see, maybe something else then. Just a guess.

**Comment by gbraad** [comment]
Any feedback?
