### ISSUE TITLE
Provide a default for the Hyper-V switch name

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1676]
Currently, you are forced to specify the HYPERV_VIRTUAL_SWITCH environment variable to start Minishift on Windows. It feels wrong that the Minishift usage depends on it, without a default option.

We should change our documentation to specify that the user needs to create a Virtual Switch called _minishift_. Then in code we would per default check for the existence of this switch. HYPERV_VIRTUAL_SWITCH becomes again an option for the non-default case.

**Comment by gbraad** [comment]
The following changes are needed
  * [ ] if `HYPERV_VIRTUAL_SWITCH=="" && Get-VMSwitch minishift`  
    * if (`SwitchType` == external) return true
  * [ ] if `HYPERV_VIRTUAL_SWITCH!="" && Get-VMSwitch <name>`
    return true
  * [ ] return false  

eg.
```
Name      SwitchType NetAdapterInterfaceDescription
----      ---------- ------------------------------
minishift External   Intel(R) Dual Band Wireless-AC 8260
```

**Comment by LalatenduMohanty** [comment]
Why not adding a flag (--vswitch) so that user can provide it during `minishift start`. The default value of the flag should be `minishift`. This way it would be more transparent to the user.

**Comment by anjannath** [comment]
The flag has to be dependent on the vm-driver, only for hyperv.

**Comment by gbraad** [comment]
@LalatenduMohanty This was already suggested as #1622, but we would still need a sane default.

**Comment by hferentschik** [comment]
I think from a usability point of view we need a out-of-box/default solution (once the switch was created).

**Comment by gbraad** [comment]
I do not see why this needs the critical label.

**Comment by gbraad** [comment]
An out-of-the-box solution would entail creating it automatically, however this is not possible as you can not infer much about the network interfaces (such as what the general device is). It works different from VirtualBox. so... I agree it can be a fixed name. However, this is currently unplanned

**Comment by hferentschik** [comment]
As I said, assuming I create a switch with a given name. Once this precondition is met, there should be no additional setting or env variable be required.

**Comment by gbraad** [comment]
See: https://github.com/minishift/minishift/issues/1676#issuecomment-343136426

**Comment by gbraad** [comment]
This task will have to be changed: The default name will be "Default Switch". See #1792.

We can still have the pre-flight check in, as older releases of Windows 10 (pre Fall Creator's update) do not have this pre-defined switch. And also, if you have already configured NAT, theis switch will not be created.

**Comment by anjannath** [comment]
@gbraad Happy to help you on this :)

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/commit/a5a49dc9158b4df7caf1b8639203217f21e16040
