### ISSUE TITLE
Fix documentation grammatical/typo errors

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1678]
Small documentation changes required like:
- https://docs.openshift.org/latest/minishift/using/addons.html#remove-addons 
  `Example: Removing admin-user add-ons` to `Example: Removing admin-user add-on`
- https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html#xhyve-driver-install
  Note: `The downloaded docker-machine-driver-xhyve binaries are compiled against ...` to `The downloaded docker-machine-driver-xhyve binary is compiled against...`

and others as I am continue to review

**Comment by robin-owen** [comment]
Work on this issue is being done in PR #1684.

**Comment by robin-owen** [comment]
Resolved by #1684.
