### ISSUE TITLE
Remove dependency to k8s.io/kubernetes

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#168]
At the moment the k8s.io/kubernetes takes up a most of the vendor files, but minishift has no need for this dependency. In total we have 14 reference to packages within this dependencies. There is maybe a couple of helper function (_Homedir_) which we can inline and other than that we are dealing with either minikube specific things or some testing infrastructure. The latter can be replaced with something more suitable for our needs. See also issue #135.

If nothing else we gain a much improved setup time (k8s.io/kubernetes takes most time to check out via glide) as well as improved build time (much less files to check by make)

**Comment by hferentschik** [comment]
With pull #243 merged, this becomes actually quite easy. The remaining dependency to Kubernetes is in _minishift service_ which uses the Kube API to get the list of services. Really this implementation should just use _oc_. 

Moving this into another milestone though, since it has a low priority.

**Comment by gbraad** [comment]
Would like to see this happen, as `[INFO]  --> Fetching k8s.io/kubernetes.` takes minutes on my connection. I am also sure it will improve the situation for build times on CI.

**Comment by budhrg** [comment]
>  it will improve the situation for build times on CI.

Agree :+1:

**Comment by budhrg** [comment]
Related to #342

**Comment by budhrg** [comment]
While working for #342 , I had removed most of the dependencies for k8s, but it seems that even for openshift/origin, it need to be checked in here

```
....
go install -ldflags="-X github.com/minishift/minishift/pkg/version.version=1.0.0-beta.5 -X github.com/minishift/minishift/pkg/version.isoVersion=v1.0.2 -X github.com/minishift/minishift/pkg/version.openshiftVersion=v1.4.1" ./cmd/minishift
vendor/github.com/openshift/origin/pkg/route/api/helper.go:6:2: cannot find package "k8s.io/kubernetes/pkg/api" in any of:
	/home/budhram/gowork/src/github.com/minishift/minishift/vendor/k8s.io/kubernetes/pkg/api (vendor tree)
	/home/budhram/go/src/k8s.io/kubernetes/pkg/api (from $GOROOT)
	/home/budhram/gowork/src/k8s.io/kubernetes/pkg/api (from $GOPATH)
vendor/github.com/openshift/origin/pkg/route/api/register.go:4:2: cannot find package "k8s.io/kubernetes/pkg/api/unversioned" in any of:
	/home/budhram/gowork/src/github.com/minishift/minishift/vendor/k8s.io/kubernetes/pkg/api/unversioned (vendor tree)
	/home/budhram/go/src/k8s.io/kubernetes/pkg/api/unversioned (from $GOROOT)
	/home/budhram/gowork/src/k8s.io/kubernetes/pkg/api/unversioned (from $GOPATH)
vendor/github.com/openshift/origin/pkg/route/api/zz_generated.deepcopy.go:10:2: cannot find package "k8s.io/kubernetes/pkg/conversion" in any of:
	/home/budhram/gowork/src/github.com/minishift/minishift/vendor/k8s.io/kubernetes/pkg/conversion (vendor tree)
	/home/budhram/go/src/k8s.io/kubernetes/pkg/conversion (from $GOROOT)
	/home/budhram/gowork/src/k8s.io/kubernetes/pkg/conversion (from $GOPATH)
vendor/github.com/openshift/origin/pkg/route/api/fields.go:3:8: cannot find package "k8s.io/kubernetes/pkg/fields" in any of:
	/home/budhram/gowork/src/github.com/minishift/minishift/vendor/k8s.io/kubernetes/pkg/fields (vendor tree)
	/home/budhram/go/src/k8s.io/kubernetes/pkg/fields (from $GOROOT)
	/home/budhram/gowork/src/k8s.io/kubernetes/pkg/fields (from $GOPATH)
vendor/github.com/openshift/origin/pkg/route/api/register.go:5:2: cannot find package "k8s.io/kubernetes/pkg/runtime" in any of:
	/home/budhram/gowork/src/github.com/minishift/minishift/vendor/k8s.io/kubernetes/pkg/runtime (vendor tree)
	/home/budhram/go/src/k8s.io/kubernetes/pkg/runtime (from $GOROOT)
	/home/budhram/gowork/src/k8s.io/kubernetes/pkg/runtime (from $GOPATH)
vendor/github.com/openshift/origin/pkg/route/api/types.go:6:2: cannot find package "k8s.io/kubernetes/pkg/util/intstr" in any of:
	/home/budhram/gowork/src/github.com/minishift/minishift/vendor/k8s.io/kubernetes/pkg/util/intstr (vendor tree)
	/home/budhram/go/src/k8s.io/kubernetes/pkg/util/intstr (from $GOROOT)
	/home/budhram/gowork/src/k8s.io/kubernetes/pkg/util/intstr (from $GOPATH)
Makefile:41: recipe for target '/home/budhram/gowork/bin/minishift' failed
make: *** [/home/budhram/gowork/bin/minishift] Error 1
```

Need to investigate more here.

**Comment by gbraad** [comment]
Likely because we call the functions within the OpenShift library, instead of using the binary to perform some of the logic.

**Comment by hferentschik** [comment]
I have a branch where I already started to take the last step. Let's get 'minishift openshift service' working, then we take this last step.

**Comment by budhrg** [comment]
> I have a branch where I already started to take the last step. Let's get 'minishift openshift service' working, then we take this last step.

Cool :+1:

**Comment by hferentschik** [comment]
Merged via pull request #747

**Comment by budhrg** [comment]
@gbraad , you must be super happy now 😄

**Comment by gbraad** [comment]
the whole world rejoices... it is not just in my interest, but it saves the Internet some needed bandwidth ;-)
