### ISSUE TITLE
Integration test should run against dedicated profile

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1680]
With profiles in place, we should be able to change the integration tests to run against a dedicated 'integration-test' profile to avoid conflicts with the default minishift profile used during development.

**Comment by LalatenduMohanty** [comment]
@hferentschik The integration test always runs in a different minishift_home and does not interfere with the development, so not sure how it it can create conflict.

**Comment by hferentschik** [comment]
It does by name. The location of the VM files is one part, the other is the name of the VM.

**Comment by gbraad** [comment]
yes and no. There should never be a situation in which the previous test was not removed... if something remained, it is wrong right away.

Also, by using a profile for the tests, we might have a situation where we end up running maybe two instances, without knowing about this.

This feels like an optimization to a problem that doesn't/shouldn't exist.

**Comment by hferentschik** [comment]
Local development, yes. But effectively it is the same on CI, except that it does not matter there so much.

**Comment by gbraad** [comment]
If identified by a fixed ID (not dynamically generated) I would be OK with the suggestion.

**Comment by hferentschik** [comment]
Sure, a fixed 'integration-test' profile/id

**Comment by agajdosi** [comment]
but.. then we are not testing the product as it is. 

This functionality could be probably achieved by using RUN_BEFORE_FEATURE parameter (https://docs.openshift.org/latest/minishift/contributing/developing.html#additional-parameters) - I can test if that works fine. If so we can document this use case so those who wants to use it can find a source for it. Also one can keep her VMs not named `minishift`...

But this does not mean I am hardly agoinst it, I just somehow still think there are not so many users who would develop on Minishift for OpenShift and in the same time would really need integration tests, but I can be wrong.

If we want to go for renaming the profile on tests to `integration-test`, I am +100 for having a possibility to turn this feature off.

**Comment by hferentschik** [comment]
> but.. then we are not testing the product as it is.

Fair enough. I have no issues with the CI jobs running against 'minishift'. It is more for development where it can come into the way and where I would like to have a possibility to have no intercept at all between dev work and running integration tests.

**Comment by gbraad** [comment]
If we can introduce a pre-step to set the profile name before the test, this would be a valid option... but I would still see this causing a possible conflict for the actual profiles tests we run as part of the integration tests.

**Comment by agajdosi** [comment]
@gbraad agree, it might cause troubles with `profile.feature`. But if I am not mistaken, we could probably implement a new step, which will fix it. This step will then not match `default` but will check for "default profile name" whatever one defines under that.
