### ISSUE TITLE
Minishift architecture diagram is not rendering due to permission issue

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1682]
Seem to be permission issue 
![screenshot from 2017-11-10 16-02-53](https://user-images.githubusercontent.com/1132451/32654303-b99dd11a-c630-11e7-83e1-0afacca4384c.png)

**Comment by hferentschik** [comment]
Good catch. I don't think this is an issue directly on our side. Can you try to build the OpenShift docs locally? Most likely there is an issue on the Jenkins instance the overall docs are getting build.

**Comment by budhrg** [comment]
> Can you try to build the OpenShift docs locally? 

Same behavior with locally as well.

**Comment by hferentschik** [comment]
> Same behavior with OpenShift docs locally as well.

It's not getting build?

**Comment by budhrg** [comment]
> It's not getting build? Same error message?

Yes

**Comment by hferentschik** [comment]
Same error? What's about the digaa diagram which is part of the OpenShift docs (I believe when it come to S2I)? Is that generated? And what's the error. If you are building locally, it won't be something around /var/lib/jenkins right? Do you have Java installed?

**Comment by budhrg** [comment]
```
Failed to generate image: Permission denied @ rb_sysopen - /home/budhram/redhat/openshift-docs/minishift/using/images/minishift-architecture.png
```

This is the error I am getting when using doc tar in openshift-docs. I do have Java.

**Comment by hferentschik** [comment]
hmm, that might be a Ruby install issue

**Comment by hferentschik** [comment]
I did a build of the OpenShift docs locally using the tarball generated by _make gen_adoc_tar_. The rendering worked fine. I am pretty sure that this is a Ruby installation problem on your machine as well as on the Jenkins slave the build occurred. Nothing seems to be wrong from our end. I rather think we have an environmental problem here.

**Comment by hferentschik** [comment]
As a workaround, we can on our side call _make gen_docs_ before building the tarball. This will build the docs including the image. The image gets then included in the tarball and will hopefully be directly picked up w/o generating the error. Worth a try. @budhrg Maybe you can change the CI job accordingly and drop another tarball. We can then see how the result looks like. This way we also get the updated profile docs up.

**Comment by budhrg** [comment]
> As a workaround, we can on our side call make gen_docs before building the tarball. This will build the docs including the image. The image gets then included in the tarball and will hopefully be directly picked up w/o generating the error. Worth a try.  

No need to do all hacks :smile: 

Its a version issue `gem 'asciidoctor-diagram', '~> 1.4.0'` while in `openshift-docs` repo version used is `asciidoctor-diagram 1.5.6`.

Able to see the image when `1.4.0` is used in `openshift-docs`.
![screenshot from 2017-11-14 22-23-39](https://user-images.githubusercontent.com/1132451/32793162-30747a98-c98b-11e7-9b18-f17151311b16.png)

**Comment by budhrg** [comment]
Found the root cause.

The `rake build` task of `openshift-docs` is not copying `using/images` folder properly.

**Comment by budhrg** [comment]
>  This will build the docs including the image. The image gets then included in the tarball and will hopefully be directly picked up w/o generating the error. Worth a try.

The `minishift-adoc.tar` has images. It's the above issue. that `rake build` is not picking the `images` folder until it has `image::<>` written in  `.adoc` file.

**Comment by budhrg** [comment]
We need to modify `*.adoc` containing the texts

```
[ditaa, "minishift-architecture"]
----

 host machine
 +-------------------------------------------------------------------------------------+
 |                      /-------------> Minishift VM                                   |

.....

 |                                                                                     |
 +-------+-----------------------------------------------------------------------------+

----
```

With 
```
image::minishift-architecture.png[{product-title} Architecture Overview]
endif::[]
```

before packaging into `*.tar` file.

**Comment by hferentschik** [comment]
> The rake build task of openshift-docs is not copying using/images folder into _preview/openshift-origin/latest/minishift/using.

How is this the root cause? In a perfect world, the image should be generated anyways and afaict it does do that.

**Comment by hferentschik** [comment]
> We need to modify *.adoc containing the texts

I am not following here. What do you need to modify and why? I don't think this is required.

**Comment by hferentschik** [comment]
@budhrg so what's about the other ditaa diagrams in your local docs.openshift.org checkout? Are they getting build? Is it just the Minishift diagram which does not get build?

**Comment by budhrg** [comment]
> How is this the root cause? In a perfect world, the image should be generated anyways and afaict it does do that.

Wrong assumption.

> @budhrg so what's about the other ditaa diagrams in your local docs.openshift.org checkout? Are they getting build? Is it just the Minishift diagram which does not get build?

Found that the `basic-usage.adoc` has ditaa diagram format but required is `image:<something something>` while other docs.openshift.org has `image:...`.

**Comment by hferentschik** [comment]
> The rake build task of openshift-docs is not copying using/images folder into _preview/openshift-origin/latest/minishift/using.

If images where not copied then how come this renders fine - https://docs.openshift.org/latest/minishift/contributing/ci.html?

**Comment by hferentschik** [comment]
@budhrg so what are you trying to do here? Are you trying to fix the image generation issue are you trying to pre-render the image and include it into the tarball. If it is the latter and the changes in pull request #1699 are required to do this, then I think it is not a viable solution, especially since this almost certainly is an environment issue.

**Comment by budhrg** [comment]
> you trying to pre-render the image and include it into the tarball.

Fix the content of tarball. As I mentioned here https://github.com/minishift/minishift/issues/1682#issuecomment-344352588 that the adoc file contains asciidoctor diagram format.

> this almost certainly is an environment issue.

Not an environment issue. Can show you.

**Comment by LalatenduMohanty** [comment]
@budhrg It is still not clear from your comments what is the root cause of the issue. Can you please explain that.

**Comment by budhrg** [comment]
@LalatenduMohanty , @hferentschik  empty line was missing https://github.com/minishift/minishift/pull/1700

**Comment by LalatenduMohanty** [comment]
I can see the image properly rendered in https://docs.openshift.org/latest/minishift/using/basic-usage.html after this fix is applied and uploaded in docs.openshift.org
