### ISSUE TITLE
New profile xyz is being created on passing the command "./minishift --profile xyz status"

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#1695]
```Minishift version : 1.8.0/master```
The command ```./minishift --profile xyz status``` creating the profile xyz rather throwing the exception something like ```Profile is not created. Create the profile first```
```
$ ./minishift profile list
- foo        Running        (Active)
- minishift    Running

$ ./minishift --profile xyz status
Does Not Exist

$ ./minishift profile list
- foo        Running        (Active)
- minishift    Running
- xyz        Does Not Exist
$
```

**Comment by budhrg** [comment]
Hmm, not sure about this as AFAIR we agreed to create new profile on `profile set`.

**Comment by amitkrout** [comment]
@budhrg i find this when i am writing the step definition of ```Profile "foo" has state "Does Not Exist"``` for profile.feature file. This is passing on any profile name which is not created. As per the step definition implementation it should fail if profile is not created.

**Comment by hferentschik** [comment]
In this case I'd argue the test is out of sync. I agree w/ @budhrg that things are as designed.

**Comment by amitkrout** [comment]
@hferentschik Consider this example 
```
$ ./minishift profile list
- minishift    Does Not Exist    (Active)

Case1: 
Then Profile "minishift" should have state "Does Not Exist " - Will be successful (Expected)

Case2:
Then Profile "xyz" should have state "Does Not Exist " - Should fail because there is no profile available in the name of xyz.
The reason behind the failure is the command ./minishift --profile xyz status (which is being used in my step defination) creates a profile xyz instead of throwing the exception.
```

**Comment by hferentschik** [comment]
> creates a profile xyz of state "Does Not Exist" instead of throwing the exception.

That's per design. Any command executed against another profile using the global --profile command will "touch" this profile. Arguably we could handle this case explicitly, but on the other hand it is consistent as it is.

**Comment by gbraad** [comment]
I do not believe this is per design.

We only create a profile on `minishift start` and `minishift profile set`. Commands like `minishift status` should never create a profile.

**Comment by agajdosi** [comment]
@gbraad @hferentschik I would like to also add that this feature of --profile flag to create a new profile can cause in some cases quite strange things. For example, lets try this puzzle:

On default profile `minishift`, no other were created, I am executing:
```
[agajdosi@dhcp-24-156 bin]$ ./minishift profile set andreas --profile coolfeature
```

What will happen?

**Comment by gbraad** [comment]
A precedence have to be chosen... will `--profile` take priority over `profile ...` ? 

I am also in favour of removing the ability to create a profile with `--profile`, as we explicitly implemented this as part of `m profile set`.

**Comment by anjannath** [comment]
> I am also in favour of removing the ability to create a profile with `--profile`

+1

`minishift status --profile` should not create a new profile. any command run with the flag `--profile` should run against the profile name provided with the flag if that profile does not exists it should give an error.

**Comment by praveenkumar** [comment]
Doesn't we had a long discussion around it when implemented `profile set` command and that time also we kind of discussed that we should limit what commands should create the profile when `--profile` option used. If we all agree then we should just limit it to `set` and `start` command and add profile checks for others instead of creating implicitly.

**Comment by gbraad** [comment]
@praveenkumar yep, we had that discussion and we agreed...
however, seems it is not documented and remembered, as this behaviour is currently 'per design'. And I strongly disagree with this, especially when testing this with @agajdosi earlier on the CDK side. Currently it opens a can of worms, which always typo and mistakes to move to a new context/profile without a real clear indication.

**Comment by praveenkumar** [comment]
@minishift/minishift-dev I spent around 3-4 hours to find if we can have a cleaner way of doing it. I come up with only 2 different solutions.

1. Only `profile set` will create the profile and `--profile` will only work for profiles and doesn't interfere with profile creation stuff. 

2. If we still want `--profile` should also work with start command (for profile creation) then we have to maintain a command list which require interacting with `instanceconfig` (like delete, addons, image ..etc.) and only whitelist those commands but that seems bit hacky to me. 

My vote is to go with option 1 which is much cleaner.

**Comment by gbraad** [comment]
Option 1

**Comment by agajdosi** [comment]
Option 1 - clean, logical, consistent (+safe for CDK)

**Comment by budhrg** [comment]
Option 1

**Comment by anjannath** [comment]
Option 1

**Comment by LalatenduMohanty** [comment]
As @hferentschik mentioned the behavior was as designed and it is documented in https://docs.openshift.org/latest/minishift/using/profiles.html#example-workflow-profile-config.

The reasoning was it gives user flexibility of continue using what ever older commands user was using. User needs to just add the `--profile flag`. 

That being said, If we stop the profile creation using `--profile` then we still need to make sure user can do things as mentioned in the example workflow, else we are breaking backward compatibility.  That means we need v2.0.0 release.

Also we will have to fix the code to handle a lot of corner cases which might be bigger than what we see now.  For example if we go by option-1, what do we expect the output of `minishift status --profile NEW_PROFILE`. We need to fix individual commands for handling this.

**Comment by gbraad** [comment]
I believe we are in an early enough stage to modify this behaviour and document or error to the user that the profile does not exist.

**Comment by praveenkumar** [comment]
@LalatenduMohanty we are not going to break any backward compatibility, what we will do is just add a profile check for each command which will tell if a profile exists before using it or not.  Why do you think it breaks the backward compatibility?

Assume I am using 1.9.0 version today so commands which you pointed out works as per documents. but tomorrow when we are going to release 1.10.0 release and after a user tries to perform same commands then following should happen.

```
$ minishift --profile profile-demo config set memory 8GB
It will behave as it is if *profile-demo* exist
or 
Profile: profile-demo doesn't exist, Use *minishift profile set profile-demo* to create
```

**Comment by LalatenduMohanty** [comment]
> @LalatenduMohanty we are not going to break any backward compatibility, what we will do is just add a profile check for each command which will tell if a profile exists before using it or not. Why do you think it breaks the backward compatibility?

If an user can not perform the commands mentioned in https://docs.openshift.org/latest/minishift/using/profiles.html#example-workflow-profile-config IMO it is breaking the compatibility. If you can convince me that it is not braking compatibility then we can discuss option-1. I will also give it some more thought.

**Comment by LalatenduMohanty** [comment]
@jorgemoralespou WDYT? What workflow you use to create profiles?

**Comment by jorgemoralespou** [comment]
I would expect only profile set (at most and since that has been long time
agreed) to be the only extraneous command to ever create a profile, else
people will end up having multiple/ invalid profiles of they wrongly enter
commands.

So, I would assume no other way to create a profile than "minishift start
--profile" and "minishift config set --profile", since there's no create
command.

**Comment by praveenkumar** [comment]
> I would expect only profile set (at most and since that has been a long time agreed) to be the only extraneous command to ever create a profile, else people will end up having multiple/ invalid profiles of they wrongly enter commands.

@jorgemoralespou Right we want that to stop where people are having invalid profiles when using `--profile` args to a command like `m status` . Now changes which we are going to block `--profile` to create any profile but only deal with available/created profiles. So moving forward if you do `m start --profile foo` or `m config set --profile foo` and profile `foo` not exist then it throw out an error that profile doesn't exist use `m profile set` first to create it but if an profile exist then `--profile` will works as expected.

**Comment by jorgemoralespou** [comment]
@praveenkummar Let me know if I got this right. The only way a profile will
be created is "minishift profile set <profile>"?

**Comment by LalatenduMohanty** [comment]
@jorgemoralespou there will be two ways:

* `minishift --profile PROFILE_NAME start
* `minishift profile set PROFILE_NAME

**Comment by gbraad** [comment]
`m start` will NOT create, as this is for consistency and having maintainable code. if we introduce this as an exception, it means we have two entrypoints to handle the creation case. I prefer not to have this situation.

**Comment by LalatenduMohanty** [comment]
From the beginning of profile feature we have communicated that  `minishift --profile PROFILE_NAME start` will create the profile and start it. We can not break it now.  -1 for breaking it.

**Comment by budhrg** [comment]
> From the beginning of profile feature we have communicated that minishift --profile PROFILE_NAME start will create the profile and start it. We can not break it now. -1 for breaking it.

+1, and IMO it is so convenient way to start Minishift VM which implicitly create profile I believe users might backfire here saying why we have removed it as they need to start another command to actually start Minishift with non-default profile. https://docs.openshift.org/latest/minishift/using/profiles.html#creating-profiles

**Comment by gbraad** [comment]
What if instead for the current release we will add a dreprecation notice? This is pretty much how we can handle changes over time.

As for example, we also allowed the use of vmware, but have also dropped this (has this backfired?)

**Comment by budhrg** [comment]
> As for example, we also allowed the use of vmware, but have also dropped this with a deprecation note. (has this backfired?)

I disagree with backfire point here since both are the completely different scenario. Even though we had `vmware` in documentation, we hardly get any user complaining about it. Also, not known whether they use it or not.
In case of `minishift start --profile name`, which we made default to implicitly create profile during start, removing this behavior will cause the extra effort everytime when starting new profile.

**Comment by gbraad** [comment]
The extra effort is minimal, as it needs only `m profile set <name>`, this is only a few characters more...

Since this functionality is also in for just a short time, the impact is minimal. And yes, we have (had) users of the VMware driver. You can check the issue tracker. And yes, the scenario is different, as it is far worse to drop support entirely... Note: we will have to change more commands over time, such as 'm hostfolder add' as example. I do not see why this has such a special status. Add a deprecation notice, and work towards maintainable code.

**Comment by agajdosi** [comment]
> Add a deprecation notice, and work towards maintainable code.

Big +1. The `minishift --profile newprofile start` is saving like 10 characters? Also is usable just for those who want to start just "vanilla" Minishift and who do not need any configuration etc.

**Comment by jorgemoralespou** [comment]
I can agree with @gbraad, but then I would reopen the conversation on
whether the "profile set" is the most intuitive command for creating the
profile. We discussed long about "minishift create" (or similar) and that
sound more intuitive.

In my opinion, all the discussion boils down to what's more intuitive for
users. I would poll some of the current users that you have identified to
gather their opinion.

**Comment by LalatenduMohanty** [comment]
Going by last few comments it seems to me that , we are just trying for good maintainable code at the cost of backward compatibility of commands. 

Honestly if we are really pissed off about the current behavior, lets go for Minishift 2.0.0 version and we can change the behavior of minishift commands.  `minishift start --profile` is so convenient  for people that I can not think of removing it. We are talking about global config parameters in future, isn't it?  With that in place , users will just start/create new profiles with `minishift start --profile` it is so convenient.  Even if I ignore that for a moment , there are cases users can use env variables for CPU, memory can start with `minishift start --profile PROFILE_NAME`. 

> Do not forget we are fixing #1695 (comment)
> 
> $ minishift profile set myfirstcluster --profile myothercluster

I do not think fixing this is an issue. The question is how much consistency in code/ CLI commands matters vs user experience.

**Comment by LalatenduMohanty** [comment]
> As for example, we also allowed the use of vmware, but have also dropped this with a deprecation note. (has this backfired?)

The main reason we removed the support because we never tested it and never supported it from the team goal point of view. So it did not make any sense to say something is supported when it is not tested in CI and we do not use it also.

**Comment by LalatenduMohanty** [comment]
> Big +1. The minishift --profile newprofile start is saving like 10 characters? Also is usable just for those who want to start just "vanilla" Minishift and who do not need any configuration etc.

That is not right. It is not about saving characters but what is more intuitive.  You can have env variables and then do `minishift start --profile PROFILE_NAME` to have non default parameters.

**Comment by LalatenduMohanty** [comment]
> As for example, we also allowed the use of vmware, but have also dropped this with a deprecation note. (has this backfired?)

Also the most important part, we did not remove the code for it. We only removed the documentation.

**Comment by gbraad** [comment]
> dropped this with a deprecation note

**Comment by LalatenduMohanty** [comment]
> Note: do not twist words, as I mentioned we show a deprecation note

Ok, I missed that I think. However I do not think we need to deprecate `minishift start --profile PROFILE_NAME` till we figure out what is the best way to create a profile.

**Comment by gbraad** [comment]
> I do not think fixing this is an issue.

-1

This is an issue. It affects every command, but the worst in the case of `m profile set <name> --profile <name>`
