### ISSUE TITLE
remove an addon asks for a Required Var

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1698]
I have an addon with a Required-Var, and an addon.remove file, without the Required-Var defined.

When I do remove the addon, I get an error, asking me for the var.

istio.addon
```
# Name: istio
# Description: YET TO BE WRITTEN
# Url: https://istio.io
# Required-Vars: example-project
```

istio.addon.remove
```
# Name: istio
# Description: Removes the istio installation
```

```
$ minishift addon remove istio
-- Removing addon 'istio':Error removing the add-on: The variable(s) example-project are required by the add-on, but are not defined in the context
```

It also seems like it looks for all the metadata in the addon file, as I also had a typo in the Name tag in the addon.remove and was removing the addon just fine.

**Comment by gbraad** [comment]
Workaround: to force the removal, you could add an additional `#` in front of the line, or remove the line.

**Comment by jorgemoralespou** [comment]
@gbraad thanks. Providing the var is easier.

**Comment by gbraad** [comment]
we will fix this, but at the moment no ETA (hence the workaround)

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/commit/4ccff78fc09a6da882c283a3043a243c61f4798f
