### ISSUE TITLE
Minishift next

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#170]
The next community release of Minishift is coming up and the question is which version to use for it. It will be a major change, since provisioning will occur via 'oc cluster up' opposed to running the openshift binary on the VM. The current version is 0.9.0.

Do we go for 0.10.0? Or 1.0.0? IMO a major version change would make sense, especially since I'd like to start with semantic versioning asap. On the other hand, moving directly to 1.0.0 after making so substantial changes to the code might feel odd.

Thoughts?

For now I created a 1.0.0 milestone. Once we agreed on the Minishift next version, we can rename this to whatever we want to use.

**Comment by jimmidyson** [comment]
How about a 1.0.0-beta.1? We should probably review commands, etc to make sure we agree on what we're going to remain strict on for backwards compatibility but that's fine.

**Comment by hferentschik** [comment]
> How about a 1.0.0-beta.1

+1 Works for me

**Comment by LalatenduMohanty** [comment]
I do not have strong opinion on the version we choose now. However another major version change in future will be to replace boot2docker ISO with the CentOS based ISO.

**Comment by jimmidyson** [comment]
@LalatenduMohanty Do we think we could do that in an alpha/beta/rc cycle, with the change being mandatory for a 1.0.0 release?

**Comment by praveenkumar** [comment]
I am favor to follow alpha/beta/rc cycle as features comes along.

**Comment by LalatenduMohanty** [comment]
@jimmidyson  sure, we can try that.

**Comment by hferentschik** [comment]
> I do not have strong opinion on the version we choose now. However another major version change in future will be to replace boot2docker ISO with the CentOS based ISO.

Why would that be a major version change? I would think this is just going from 1.0.0 to say 1.1.0. This change is really transparent to the user and just adds a new feature of optionally changing the ISO. 

We can discuss the version once we cross this bridge. I think this particular question is resolved for now.
