### ISSUE TITLE
minishift dial tcp missing address virtualbox win7 after restart of host

### ISSUE THREAD

**Issue by carlolrac** [minishift/minishift#1701]
Hi, I need help...

after Windows update restarting my computer over night, I get the following error with minishift whatever I am trying to do:
dial tcp: missing address
This happened before and the only solution was to completely remove Virtualbox and minishift from the computer and rebuilt everything from scratch...
...there must be an easier way, but google won't tell me... on the other hand, I cannot imagine to be the only one running into that issue, as I have a pretty standard setup...
Any ideas ?

**Comment by praveenkumar** [comment]
@carlolrac Can you provide try steps mentioned below and then provide us the logs.

```
$ minishift delete --force
$ minishift start --show-libmachine-logs --v=5
```

**Comment by gbraad** [comment]
`dial tcp missing address` sounds like an issue with the VM being unable to connect to the internet, or the us being unable to communicate with the VM. If it would happen again, use the `minishift start --show-libmachine-logs --v=5` option to confirm what fails.

But as @praveenkumar indicates, being a `delete` beforehand will usually solve any issue you had. This is advisable if you can afford to lose the images stored inside the VM.

**Comment by carlolrac** [comment]
Sorry for my late reply and thank you very much for your input !!!
As I was under fierce pressure, I ended up deleting all dot folders from C:/users/MYUSER/ (namely: .minishift, .kube, .Virualbox, etc.)...
...then I ran a Virtualbox installation file and chose the "REMOVE" option in the process and restarted my computer subsequently...
...after startup I launched the same Virtualbox installation file again and went for the INSTALL option this time...
...in order to get a new .Virtualbox folder (plus content) I had to start Virtualbox once, but closed it immediately afterwards...
..when running minishift thereafter, everything worked fine (minishift start --vm-driver=virtualbox)

I did not shut down the computer since (because we have to urgently get a project running), so I do not know, if I'll see the issue again... it certainly seems to be connected to Virtualbox IPs being messed up... possibly, it could be connected to having also VirtualBox portable installed ?!

if I see it again I will post the logs... otherwise, I hope, this is helpful to someone...

before above remedy, I could delete --force only, but do nothing afterwards without immediately getting the tcp dial: missing address error...

Thanks again for your help !!!

**Comment by gbraad** [comment]
Thanks for the feedback.
