### ISSUE TITLE
Add a timeout to"services xyz rollout successfully"

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1703]
Sometimes when network is bad, the slaves on which we test CDK get stuck on `And services "ruby-ex" rollout successfully` step. The test then ends by a timeout of `go test`. Firstly this slows the tests down, extensively consumes our resources and also the forced quit `SIGQUIT: quit`caused by timeout is not really friendly for our testing environment.

Thus it would be useful to have a timeout on the rollout step, so it automatically fails after some time and tests continue. Also would be useful to be able to define non-default time limit, if one needs. For example:

```gherkin
And services "ruby-ex" rollout successfully                             #by default fails after 15 minutes
And services "ruby-ex" rollout successfully in 20 minutes               #fails after 20 minutes
```

**Comment by LalatenduMohanty** [comment]
Resolved via #1951
