### ISSUE TITLE
Release artifacts should be tar/zip bundles

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#171]
We should align what we release with for example OpenShift. There the oc binary is in a tar/zip bundle depending on the target platform. 

Right now it is not quite clear what the artifacts are and one needs to potentially make them executable after downloading. Also the binary is not always 'minishift', but platform specific eg 'minishift-darwin-amd64'. 

By adding the binaries into a tar/zip bundle we can have a single named _minishift_ binary and make sure it is directly executable. Also we can add a README and LICENSE into the bundle for good measure.

**Comment by jimmidyson** [comment]
OpenShift uses tarballs because it bundles multiple binaries/symlinks. This is a single binary, although if we start to bundle blessed drivers then perhaps it makes more sense.

**Comment by hferentschik** [comment]
> OpenShift uses tarballs because it bundles multiple binaries/symlinks

Hmm, not so sure. Look at all the various bundles for the _oc_ binary. I don't think the driving force is having "multiple binaries/symlinks". Or at least it is not the only one. I think having a uniquely named binary which is directly executable is a big plus. 

For what it's worth, I am not the one who came up with this initially, but it comes from an actual user. @robstryker, maybe you want to add to this.

**Comment by jimmidyson** [comment]
That is a good point. I do kind of expect packages to be produced so don't need to be downloaded from github in future though, RPM, DEB, brew, etc., but I get your point.

**Comment by hferentschik** [comment]
Resolved via pull request #185
