### ISSUE TITLE
Ability to set multiple configurations at once

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1712]
If would be nice user experience if one can able to set multiple configs at once.

```
./minishift profile set helloworldmsa
./minishift config set memory 6GB
./minishift config set cpus 2
./minishift config set vm-driver virtualbox
./minishift addon enable admin-user
./minishift config set openshift-version v3.7.0-rc.0
./minishift config set iso-url centos
```
to
```
./minishift profile set helloworldmsa
./minishift config set memory=6GB,cpus=2,vm-driver=virtualbox
./minishift addon enable admin-user
./minishift config set openshift-version=v3.7.0-rc.0,iso-url=centos
```

Example is taken from https://www.redhat.com/archives/devtools/2017-October/msg00003.html

**Comment by gbraad** [comment]
What to do when one of the values fails to parse, or has the wrong type of value. Would they all fail to set? (atomic action), or in that case ignore/report, but set the other values?

**Comment by budhrg** [comment]
> What to do when one of the values fails to parse, or has the wrong type of value. Would they all fail to set? (atomic action), or in that case ignore/report, but set the other values?

I would say set other values and print messages for unset values  so that user can set it explicitly.

@burrsutter What do you prefer?

**Comment by hferentschik** [comment]
-1, this becomes easily ambiguous with values which take a string slice. I vote to close this issue.

**Comment by gbraad** [comment]
What problem does it really solve? I also see more edge cases, just like @hferentschik mentions.
Since when is verbosity a problem? Especially in a command line you can use an alias, or substitute values easily.

**Comment by hferentschik** [comment]
Having the ability to specify multiple things, makes sense in the case of things being the same. For example, `minishift profile delete`. Or some of the add-on commands. There is no ambiguity involved and the semantics fairly easy to work out and understand. Different beast with the `config set` command where you effectively need to introduce a new syntax (comma separating the different key/value pairs, as well as using an = to separate key and value). This is not intuitive and worst of all can easily get you into trouble in the case of slice based values.

**Comment by gbraad** [comment]
> can easily get you into trouble in the case of slice based values.

or wrongly interpreted as a flag, as we already have:

```
$ minishift config set memory=8G,extra-clusterup-flags="--service-catalog"
```

would already fail, see #1664

**Comment by budhrg** [comment]
Looks like setting multiple config values is going to have issues and there will be ambiguity and trouble with slice based values as per our mentioned discussion. Hence, closing the issue.
