### ISSUE TITLE
Only alpha-numeric characters should be allowed as a valid profile name

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#1714]
As discussed with @LalatenduMohanty and @gbraad , there need to put some check around some special character.

for example : 
 ```. ? / & * % # $ @```

**Comment by gbraad** [comment]
The profile name is used in the folder structure, hypervisor name (inside the tooling), and possible other locations. Therefore we need to be cautious about the use of characters. For instance, libvirt restrict the name to: *should consist only of alpha-numeric characters and is required to be unique within the scope of a single host.* (Ref: https://libvirt.org/formatdomain.html#elementsMetadata) I can expect the same for Hyper-V, VirtualBox and xhyve. I would suggest to play it safe and only allow `[a-zA-Z]` as start character, followed by a sequence of `[a-zA-Z][0-9]` as name

**Comment by gbraad** [comment]
Current behaviour can cause issues when a `.` is used:

```
Amits-MacBook-Pro:bin amit$ ./minishift profile list
- minishift    Does Not Exist    (Active)
Amits-MacBook-Pro:bin amit$ ./minishift profile set .
Profile '.' set as active profile
Amits-MacBook-Pro:bin amit$ ./minishift profile list
- addons    Does Not Exist
- cache        Does Not Exist
- certs        Does Not Exist
- config    Does Not Exist
- logs        Does Not Exist
- machines    Does Not Exist
- minishift    Does Not Exist
- tmp        Does Not Exist
Amits-MacBook-Pro:bin amit$ 
```

**Comment by amitkrout** [comment]
#1692

**Comment by LalatenduMohanty** [comment]
> I would suggest to play it safe and only allow [a-zA-Z] as start character, followed by a sequence of [a-zA-Z][0-9] as name => [a-zA-Z]+[0-9]*

The only concern I have is the restriction on `[a-zA-Z] as start character`, I feel it is more restrictive than required. @minishift/minishift-dev WDYT?

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1723
