### ISSUE TITLE
Preflight check for libvirt check FAILs when only OpenVSwitch bridge has been defined 

### ISSUE THREAD

**Issue by zenny** [minishift/minishift#1718]
Hi,

I am getting an unexpected "libvirt FAIL" error message On ubuntu 14.04 as follows, though all requirments seems to have been fulfilled (as evident from virt-manager working)

# ERROR

```
$ ./minishift version
minishift v1.7.0+1549135
$ ./minishift start
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present and active ... FAIL
   See the 'Setting Up the Driver Plug-in' topic for more information
```
# ALL REQUIREED COMPONENTS FULFILLED
In pursuant to https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html

1. THE DOCKER-MACHINE-DRIVER-KVM PULLED IN THE RIGHT PLACE
```
$ ls -la /usr/local/bin/docker-machine*
-rwxr-xr-x 1 root root 26574656 Oct 29 16:47 /usr/local/bin/docker-machine
-rwxr-xr-x 1 root root 12096944 Oct 27 13:00 /usr/local/bin/docker-machine-driver-kvm
```

2. THE OPENVSWITCH BRIDGE CONFIGURED
```
$ virsh net-list --all
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 ovsbr0               active     yes           yes
```

3. REQUIRED PACKAGES INSTALLED
```
$ dpkg -l | grep libvirt-bin
ii  libvirt-bin                                 1.2.2-0ubuntu13.1.23                                        amd64        programs for the libvirt library
$ dpkg -l | grep qemu-kvm
ii  qemu-kvm                                    2.0.0+dfsg-2ubuntu1.36                                      amd64        QEMU Full virtualization
```

4. USER ALREADY IN THE LIBVIRTD GROUP
```
$ cat /etc/group | grep libvirtd
libvirtd:x:120:zenny,vnc
```

***Just wondering why minishift reports 'Checking if Libvirt default network is present and active ... FAIL'?***

Cheers,
zenny

**Comment by gbraad** [comment]
Can you verify if you have an active default network?

```
$ sudo virsh net-list --all
```

If not, please add this according to the instructions at:  https://wiki.libvirt.org/page/Networking#Host_configuration

**Comment by gbraad** [comment]
@LalatenduMohanty @praveenkumar what happened to the topic that would be added that relates to the libvirt default network not existing? Might have tro review #1403 #1437, as I believe this needs to be added to the documentation.

**Comment by zenny** [comment]
@gbraad I have defined the openvswitch bridge ovsbr0 as the default in my machine, fyi.

```
 sudo virsh net-list --all
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 ovsbr0               active     yes           yes
```

**Comment by anjannath** [comment]
@zenny The network name has to be default. Define another one with the name
"default", and set it actice.

On Nov 18, 2017 1:13 PM, "zenny" <notifications@github.com> wrote:

@gbraad <https://github.com/gbraad> I have defined the openvswitch bridge
ovsbr0 as the default in my machine, fyi.

 sudo virsh net-list --all
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 ovsbr0               active     yes           yes

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/minishift/minishift/issues/1718#issuecomment-345425343>,
or mute the thread

**Comment by zenny** [comment]
@anjannath I cannot define another name because it messes up with my openvswitch-libvirt combo. 

There should be an option to use a specific network switch in minishift rather than forcing to 'default' imho.

**Comment by gbraad** [comment]
As mentioned, this is a limitation in the KVM driver. It currently uses the
name default as it's primary bridge. This is also the most likely situation
that will work ...

I am not sure why changing the name would mess up your config as ovsbr0 is
a very arbitrary name.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by helio-frota** [comment]
I saw the same error :
`-- Checking if Libvirt default network is present and active ... FAIL` 
Then after reboot, the error gone. I did nothing, only reboot.

This was the clean installation on my fedora and I followed these steps (from copied from oficial docs)
https://gist.github.com/helio-frota/339991b88c6e4983c6e6d09af2d477c8

**Comment by praveenkumar** [comment]
@zenny Unfortunately at this moment we can't have any solution for your problem and you do need to use `default` as the network name. I am closing this issue, maybe when we integrate kvm2 driver than can be looked again.

**Comment by mwaeckerlin** [comment]
I have the same error _with_ a network named `default`:
```
$ LANG= sudo virsh net-list --all
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes

$ minishift start
-- Starting profile 'minishift'
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... FAIL
   See the 'Setting Up the Driver Plug-in' topic (https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html) for more information
```

Any idea, @praveenkumar, @gbraad, @anjannath?

**Comment by anjannath** [comment]
The check if default network is active failed, but from the o/p of `net-list` it looks like it is active.

I haven't faced this issue in kvm. @mwaeckerlin Was minishift working before? or this is the first time you are trying to run it? also a reboot helps in most cases. HTH

**Comment by mwaeckerlin** [comment]
It's the first time I setup Openshift. I am currently experimenting on my laptop to check if we could use it in production. Another prototype in the server room should follow later.

Ok, I'll try a reboot. Thx, @anjannath.

BTW: Openshift wants `--insecure-registry 172.30.0.0/16`, but I'm in a company network where a lot of `172.x.x.x` are already in use, including `172.30.0.0`. Is there a way to change the defaults? I already had to set `DOCKER_OPTS="--bip=172.21.42.1/16"` before. Can I just there add a different insecure registry?

**Comment by anjannath** [comment]
AFAIK You can use the default `registry-route` addon for this, here's the docs link to addons: https://docs.openshift.org/latest/minishift/using/addons.html#default-addons

**Comment by mwaeckerlin** [comment]
@anjannath, any idea where I could find documentation on `registry-route`?

**Comment by budhrg** [comment]
@mwaeckerlin There is not much documentation https://docs.openshift.org/latest/minishift/using/addons.html#default-addons

You can find the content of it here https://github.com/minishift/minishift/blob/master/addons/registry-route/registry-route.addon.

**Comment by mwaeckerlin** [comment]
@budhrg, that's also what I found. But how can I use that to specify a different repository URL?

**Comment by Rajpratik71** [comment]
> 
> 
> I have the same error _with_ a network named `default`:
> 
> ```
> $ LANG= sudo virsh net-list --all
>  Name                 State      Autostart     Persistent
> ----------------------------------------------------------
>  default              active     yes           yes
> 
> $ minishift start
> -- Starting profile 'minishift'
> -- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
> -- Checking if KVM driver is installed ... 
>    Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
>    Checking driver binary is executable ... OK
> -- Checking if Libvirt is installed ... OK
> -- Checking if Libvirt default network is present ... OK
> -- Checking if Libvirt default network is active ... FAIL
>    See the 'Setting Up the Driver Plug-in' topic (https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html) for more information
> ```
> 
> Any idea, @praveenkumar, @gbraad, @anjannath?

 Running "minishift" as sudo doesn't throw "Checking if Libvirt default network is present ... FAIL" error.
