### ISSUE TITLE
Update xhyve driver version from 0.3.1 to 0.3.3 in the documents

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1725]
Currently, we mentioned `v0.3.1` xhyve-docker-driver version to docs and it already released to `v0.3.3`, this should need to be updated.

- https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html#xhyve-driver-install

**Comment by LalatenduMohanty** [comment]
@minishift/minishift-dev Anyone using v0.3.3 xhyve-docker-driver with `minishift`.

**Comment by anjannath** [comment]
Checked in the mac server in our office and it is running v0.3.3
