### ISSUE TITLE
Minishift architecture diagram is not rendering due to permission issue

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1729]
Again getting permission issue for image rendering. It was fixed as part of https://github.com/minishift/minishift/pull/1700 but not sure what happened after latest sync.

Link - https://docs.openshift.org/latest/minishift/using/basic-usage.html

![screenshot from 2017-11-21 11-26-18](https://user-images.githubusercontent.com/1132451/33057088-0cb92d1e-ceaf-11e7-9e85-b1d967e47a5c.png)

**Comment by hferentschik** [comment]
> Again getting permission issue for image rendering. It was fixed as part of https://github.com/minishift/minishift/pull/1700 but not sure what happened after latest sync.

TBH, I still not convinced that what we did "fixed" the issue. FAICT the issue you have had locally is different to the one seen on the Jenkins build. I think we are not getting around syncing with the Openshift Docs guys.

**Comment by budhrg** [comment]
> TBH, I still not convinced that what we did "fixed" the issue. FAICT the issue you have had locally is different to the one seen on the Jenkins build. I think we are not getting around syncing with the Openshift Docs guys.

The thing which is confusing me is how it was rendering last time when I update the doc tar.

**Comment by budhrg** [comment]
> The thing which is confusing me is how it was rendering last time when I update the doc tar.

I am able to reproduce it locally. Debugging now.

**Comment by budhrg** [comment]
@hferentschik , Root cause now is we are having images folder containing images. 

```
$ ls minishift/using/ -R
minishift/using/:
addons.adoc  basic-usage.adoc  docker-daemon.adoc  experimental-features.adoc  host-folders.adoc  image-caching.adoc  images  index.adoc  profiles.adoc  variables.adoc

minishift/using/images:
minishift-architecture.png  minishift-architecture.png.cache
```

When I removed the `images` folder and rebuild openshift docs, I am able to render docs properly.

**Comment by budhrg** [comment]
I have now updated the link in the archive server http://artifacts.ci.centos.org/minishift/minishift/docs/latest/ . Image should be visible with tomorrow's sync.

**Comment by budhrg** [comment]
Fixing from minishift side.

**Comment by LalatenduMohanty** [comment]
> @hferentschik , Root cause now is we are having images folder containing images.

Sorry I am still not able to understand why this is an issue.

**Comment by budhrg** [comment]
> Sorry I am still not able to understand why this is an issue.

To answer your question @LalatenduMohanty , following things happened:
```
# Copied from http://artifacts.ci.centos.org/minishift/minishift/docs/latest/minishift-adoc.tar (Fixed now though)
$ tar -xvf minishift-adoc.tar --strip 1

$ ls -l using/
total 80
-rw-rw-r--. 1 budhram budhram 15870 Nov 22 20:38 addons.adoc
[...]
drwxrwxr-x. 2 budhram budhram  4096 Nov 22 20:38 images    <------------ Might be culprit here
[...]
-rw-rw-r--. 1 budhram budhram   132 Nov 22 20:38 variables.adoc

$ rake build (To generate html files)
# The existence of images folder is mostly hindering the ditaa diagram generation. 
# Need to dig more into how asciidoctor / asciidoctor-diagram code to go into details.

# Right now, when I create tar with images folder mentioned above, then rendering is
# working fine. 
```

**Comment by LalatenduMohanty** [comment]
@budhrg 

> Right now, when I create tar with images folder mentioned above, then rendering is # working fine.

You mean, without the image folder right?

**Comment by budhrg** [comment]
> You mean, without the image folder right?

Yes. Check https://docs.openshift.org/latest/minishift/using/basic-usage.html#basic-usage-overview , it is now properly rendering after I repackage the doc.tar without `images` folder.

**Comment by LalatenduMohanty** [comment]
> Yes. Check https://docs.openshift.org/latest/minishift/using/basic-usage.html#basic-usage-overview , it is now properly rendering after I repackage the doc.tar without images folder.

Yes I can see that it is fine now. But it still does not explain what is the root cause of the issue.

**Comment by hferentschik** [comment]
> When I removed the images folder and rebuild openshift docs, I am able to render docs properly.

And with the images it does not work? Locally I mean? You are able to re-produce the same error?

**Comment by hferentschik** [comment]
If the existence of the images is the reason, then the reason for the problem is that atm we call link check before generating the tarball. This will generate the images and then when the tarball gets created they get included. The reason it might have worked when you did it manually was maybe that you build the tarball locally and not via the ci script. 

If this is the case, there are two issues here:

* _gen_adoc_tar_ should depend on _clean_docs_ to make sure that the tarball is build from a clean source directory
* the _clean_ target in the _Rakefile_ should also delete generated images (something we should do anyway)

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift/pull/1751

**Comment by budhrg** [comment]
Created `openshift-docs` issue https://github.com/openshift/openshift-docs/issues/6604.
