### ISSUE TITLE
Setup CI build on CentOS CI

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#173]
Using CentOS CI will give us nested virtualization, so that we will be able to run proper integration tests. See also:

* https://wiki.centos.org/QaWiki/CI/Duffy
* https://github.com/projectatomic/vagrant-service-manager/tree/master/.ci

**Comment by hferentschik** [comment]
@budhrg this one might be easy, after minishift-centos-iso!?

**Comment by budhrg** [comment]
> this one might be easy, after minishift-centos-iso!? 

Yes :+1:

**Comment by hferentschik** [comment]
Merged via pull request #311
