### ISSUE TITLE
Less than symbol in section 'OpenShift-Version Semantics' of docs rendered as a left arrow

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#1730]
https://docs.openshift.org/latest/minishift/using/addons.html#addon-openshift-version-semantics

![image](https://user-images.githubusercontent.com/8885742/33061903-accf56b6-cec3-11e7-9c43-bc13bc8f79a2.png)

/cc @robin-owen @LalatenduMohanty

**Comment by robin-owen** [comment]
I routinely forget about how AsciiDoc performs some replacements.

In any case, we can wrap the text in `+` to escape the replacement. Using `+<=3.8.0+` should work.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1736
