### ISSUE TITLE
Improve UX while applying registry-route 

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#1733]
oc-env setting is missing in the UX. Command `oc whoami -t` won't be executed without setting oc environment. ```$ eval $(minishift oc-env)``` should be added to the UX.

Current output:
```
$ ./minishift addons apply registry-route
[...]
$ eval $(minishift docker-env)
$ docker login -u developer -p `oc whoami -t` docker-registry-default.192.168.42.235.nip.io:443
```

Expected output:
```
$ ./minishift addons apply registry-route
[...]
$ eval $(minishift docker-env)
$ eval $(minishift oc-env)
$ docker login -u developer -p `oc whoami -t` docker-registry-default.192.168.42.235.nip.io:443
```
Same can be experienced on minishift start

**Comment by budhrg** [comment]
I had already discussed it and noticed that but I found we have assumed here that oc is already present.
