### ISSUE TITLE
-u --in-browser flags of minishift openshift service should be exclusive

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#1740]
The flags should be exclusive and this is not the case as we can use
```
minishift openshift service --in-browser -u say-service 
http://say-service-demo.192.168.64.24.nip.io
```
Remark : When combined, the browser is not opened

instead of 

- Get Service
```
minishift openshift service -u say-service
http://say-service-demo.192.168.64.24.nip.io
```

- Open in Browser
```
minishift openshift service --in-browser say-service
Opening the route/NodePort http://say-service-demo.192.168.64.24.nip.io in the default browser...
```

**Comment by LalatenduMohanty** [comment]
@cmoulliard In this case we should error out giving proper reason to the user. WDYT?

example:
```
$ minishift openshift service --in-browser -u SERVICE_NAME
Both flags can not be used together. Please use one of them at one time
```

**Comment by cmoulliard** [comment]
> WDYT?

I'm fine with your proposition

**Comment by LalatenduMohanty** [comment]
Or we can perform both the action i.e. show in the browser and also print the url in the terminal. I feel this is more intuitive for user.

**Comment by cmoulliard** [comment]
Performing both actions is more intuitive as you mentioned ;-)

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/issues/1744
