### ISSUE TITLE
Update centos_ci.sh for on demand job for minishift docs 

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1744]
This is aligning with https://github.com/minishift/minishift-ci-jobs/issues/32

**Comment by budhrg** [comment]
Job is ready now. https://ci.centos.org/job/minishift-docs/

**Comment by LalatenduMohanty** [comment]
@budhrg Looks good to me.

**Comment by hferentschik** [comment]
Merged by pull request #1745
