### ISSUE TITLE
Unable to set profile name with single letter alphanumeric character

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#1748]
As per the current changes profile name should be alphanumeric. However there is an issue of profile name having single char or a single digit number. In both the case minishift fails to set the profile.
Case 1:
```
Amits-MacBook-Pro:bin amit$ ./minishift profile set 'a'
Profile names must consist of alphanumeric characters only.
Amits-MacBook-Pro:bin amit$ ./minishift profile set 'aa'
Profile 'aa' set as active profile.
```
Case 2:
```
Amits-MacBook-Pro:bin amit$ ./minishift profile set '1'
Profile names must consist of alphanumeric characters only.
Amits-MacBook-Pro:bin amit$ ./minishift profile set '11'
Profile '11' set as active profile.

**Comment by amitkrout** [comment]
#1692

**Comment by LalatenduMohanty** [comment]
I think single alpha numeric character is fine with any hypervisor. So we should fix it asap.

**Comment by LalatenduMohanty** [comment]
> We do need to check if _ is vaild VM name for different hypervisors otherwise we might force it to use minimum 2 characters.

You mean *-* right? not *_*. I do not think *-* should be allowed as a single character for profile name as *-* should be only used as a separator.

**Comment by praveenkumar** [comment]
> You mean - right? not _. 

@LalatenduMohanty No, I meant `_` only because write now we are using `\w` which is word range and contain `_` also so if we allow single character that means `_` shouldn't have any issue.

**Comment by LalatenduMohanty** [comment]
I am afraid `_` (underscore) is not accepted as a valid character in KVM/libvirt. I need to first cross check it.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1749/

**Comment by thisiskatewinsle** [comment]
Thanks for sharing the link I never read about it before. In return, I would like to share [nhs argos discount](https://www.voucherpro.co.uk/argos.co.uk ) and some other discount codes that will be beneficial for everyone visiting here. If you are planning to travel you can go through the [travelodge discount code student](https://www.voucherpro.co.uk/travelodge.co.uk), it is easy to avail.

**Comment by jamescharles111** [comment]
With the latest <a href="https://www.voucherpro.co.uk/gardening-naturally.com">gardening naturally voucher code</a>, you can enjoy a greener and more sustainable lifestyle without breaking the bank.

**Comment by jamescharles111** [comment]
Use the <a href="https://www.voucherpro.co.uk/bedkings.co.uk">bed kings discount code</a>at checkout to get the perfect bed for your home at a reduced price.
