### ISSUE TITLE
Openshift docker registry doesn't reflect after applying registry-route addon

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#1750]
Registry route addon is successfully applied after `m start`. However the issue is with the command output of ```minishift openshift registry```. It does not show the host name as ```'docker-registry-default.#{routing-suffix}'``` instead of default minishift openshift registry hostname ```172.30.1.1:5000```.
```
Amits-MacBook-Pro:bin amit$ ./minishift start
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
[…]
To login as administrator:
    oc login -u system:admin

Amits-MacBook-Pro:bin amit$ ./minishift openshift registry
172.30.1.1:5000

Amits-MacBook-Pro:bin amit$ ./minishift addons apply registry-route
-- Applying addon 'registry-route':........
Add-on 'registry-route' created docker-registry route. Please run following commands to login to the OpenShift docker registry:
$ eval $(minishift docker-env)
$ docker login -u developer -p `oc whoami -t` docker-registry-default.192.168.64.12.nip.io:443

Amits-MacBook-Pro:bin amit$ ./minishift openshift registry
172.30.1.1:5000
```

In the case when registry route is enabled before m start then ```minishift openshift registry``` gives the below output
``` 
Amits-MacBook-Pro:bin amit$ ./minishift openshift registry
docker-registry-default.192.168.64.14.nip.io:443
```

**Comment by praveenkumar** [comment]
@amitkrout That is expected, we have it in this way because what if a user manually exposed the registry instead of using an addon then, in this case, we should display what he is created. We thought it and decided that until a user enables the add-on we will always show the registry uri as an internal one. 

cc @hferentschik

**Comment by hferentschik** [comment]
Right, also there is no easy way for us to determine whether the add-on got applied. The current code checks whether the add-on is enabled in this case displays the route. Not ideal, but given the circumstances we said it would be the right trade-off.

I think we can close this issue.

**Comment by amitkrout** [comment]
Thanks for the clarification. I am closing this.
