### ISSUE TITLE
Build not getting completed with minishift locally.

### ISSUE THREAD

**Issue by Ashish-bhatia** [minishift/minishift#1752]
Hi, 

I am new to minishift, I am using mac. I am able to install and run minishift on my mac. 

But when i upload a mini php or java project, its status is build is running.  It stuck at cloning repository.  I just forked the simplephp project. 
![screen shot 2017-11-25 at 10 41 44](https://user-images.githubusercontent.com/22721110/33227645-4cf9f5c2-d1cd-11e7-8cc3-86142ace303a.png)

Is it a normal behaviour?  Does it download something in backend? How to check those logs.

**Comment by gbraad** [comment]
This is likely due to a network issue on your end.

Please try to clone the repo manually and check the results of the clone.
Also let us know the steps you performed to get here.

**Comment by gbraad** [comment]
Also, it has been six minutes ago... have you waited long enough?
If the network is slow, checkouts and image pulls will take longer than usual.

**Comment by gbraad** [comment]
Cannot reproduce... need info

**Comment by Ashish-bhatia** [comment]
I have waited long enough but not able to do it. So I SSH into VM of minishift. Downloaded PHP 56 + CENTOS image. I am able to complete the build. But now there is a push to registry error. 

It seems service registry is blank. 

GITHUB LINK :   https://github.com/Ashish-bhatia/simplephp.git

Log:

  | Cloning "https://github.com/Ashish-bhatia/simplephp.git" ...
-- | --
  | Commit:	1bfb2550986ac809f4cb448d9f443aa4468d49bb (Test)
  | Author:	grant shipley <grant shipley>
  | Date:	Thu Aug 10 11:06:00 2017 -0500
  | ---> Installing application source...
  |  
  | Pushing image 172.30.1.1:5000/phpabproject/phpabapp:latest ...
  | Warning: Push failed, retrying in 5s ...
  | Warning: Push failed, retrying in 5s ...
  | Warning: Push failed, retrying in 5s ...
  | Warning: Push failed, retrying in 5s ...
  | Warning: Push failed, retrying in 5s ...
  | Warning: Push failed, retrying in 5s ...
  | Warning: Push failed, retrying in 5s ...
  | Registry server Address:
  | Registry server User Name: serviceaccount
  | Registry server Email: serviceaccount@example.org
  | Registry server Password: <<non-empty>>
  | error: build error: Failed to push image: After retrying 6 times, Push image still failed



Any input will be really appreciated. So I need to enter registry server address somewhere. 

Some tasks I completed: 
1) I Logged into VM via ssh 
     Used : $ docker push 172.30.1.1:5000/myproject/nodejs-ex
     I got the below error::::



The push refers to a repository [172.30.1.1:5000/myproject/nodejs-ex]
Put http://172.30.1.1:5000/v1/repositories/myproject/nodejs-ex/: dial tcp 172.30.1.1:5000: getsockopt: connection refused


2) I can see there is an image "openshift/origin-docker-registry      v3.6.0"
     I tried updating that too.

**Comment by gbraad** [comment]
Can you provide all instructions as performed, step by step? I am not able to reproduce this issue...

Also, is this issue consistently reproducible for you... as in, have yo tried a `minishift delete; minishift start` and see if the problem persists?

**Comment by gbraad** [comment]
Not following what you mean with "I tried updating that too." concerning the origin-docker-registry image. Can you expain mor ewhat you tried to do with it?

**Comment by Ashish-bhatia** [comment]
Hi, I performed the steps : 
1) minishift delete    
2) minishift start 

Not Sure what was wrong in initial steps, Did the same while installing first time. But it is working as of now. Thanks for all help.

**Comment by gbraad** [comment]
Rare, but deployment failures can occur... and perhaps this happaned during the setup of the registry.
