### ISSUE TITLE
Document X.509 cert issue when VM IP change during start => stop => start

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1756]
Currently, some of the users are facing an issue like below when try to start a stopped minishift VM and IP get changed. We do have some issue to resolve it as part of code but this will take time (check #1515 , #1457 , #391)

In meantime, we should document this behavior in the troubleshooting section of the document. 

```
Error: Get https://192.168.99.100:8443/healthz/ready: x509: certificate is valid for 10.0.2.15, 127.0.0.1, 172.17.0.1, 172.30.0.1, 192.168.99.101, not 192.168.99.100 Error during 'cluster up' execution: Error starting the cluster.
```

**Comment by gbraad** [comment]
@hferentschik Why is the title changed to "certificate regeneration" ? This is something we can not do at the moment, so it is remains an issue. When you want a regenerate, we have to remove ALL configuration, which means we can not regenerate without loss of configuration.

**Comment by praveenkumar** [comment]
@gbraad I again changed the issue to make sure what we are dealing with as part of document changes.

**Comment by gbraad** [comment]
thanks, as this is essential for the changelog/release notes

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1757/
