### ISSUE TITLE
Upgrade docker/machine dependency 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1758]
Currently, we are using 0.11.0. We could try to upgrade to 0.13.0. This way we might get better alignment between the docker/docker and docker/distribution versions required by docker/machine and container/image.

**Comment by praveenkumar** [comment]
@hferentschik any reason you added `v1.11.0` milestone for it. I can have a quick check if it is trivial then we can have PR ready asap.

**Comment by praveenkumar** [comment]
Did a dry run and looks like it's trivial to do. I am sending PR against it.

**Comment by gbraad** [comment]
This means we can also finally remove some workarounds I placed in code, due to them finally being available....

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1685
