### ISSUE TITLE
Add '-f' shortcut to commands where  --force is present

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1759]
Recently we fixed https://github.com/minishift/minishift/issues/1705 but there are other places where `--force` is present without the shortcut `-f`.  IMO we should fix them for consistency. 

```
Usage:
  minishift update [flags]

Flags:
      --force                Force update the add-ons after the binary update. Otherwise, prompt the user to update add-ons.
  -h, --help                 help for update
```

```
Usage:
  minishift addons install [SOURCE] [flags]

Flags:
      --force      Forces the installation of the add-on even if the add-on was previously installed.
  -h, --help       help for install
```

**Comment by praveenkumar** [comment]
@bhavin192 want to take it again :)

**Comment by bhavin192** [comment]
Even after checking all the files, seems like I missed those :( 
@praveenkumar yes!

**Comment by gbraad** [comment]
The description of the issue was not clear enough, so don't worry

**Comment by amitkrout** [comment]
This change would affect the integration test for sure 
For example : 
Scenario [steps](https://github.com/minishift/minishift/blob/master/test/integration/features/basic.feature#L205) like ``` executing "minishift delete --force" succeeds```.

**Comment by gbraad** [comment]
@amitkrout a shorthand is added, not replaced... and, we would not have to test the shorthand.
