### ISSUE TITLE
Error while start minishift using `minishift start --vm-driver=virtualbox`

### ISSUE THREAD

**Issue by vishalcloudyuga** [minishift/minishift#1762]
minishift start --vm-driver=virtualbox
```
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Starting profile 'minishift'
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.2.0/minishift-b2d.iso'
Error caching the ISO: Get https://github.com/minishift/minishift-b2d-iso/releases/download/v1.2.0/minishift-b2d.iso: dial tcp: lookup github.com on 127.0.1.1:53: read udp 127.0.0.1:52817->127.0.1.1:53: read: connection refused
```
Minishift version:  v1.9.0+a511b25
Virtualbox version:  5.2
OS: Ubuntu 17.04

**Comment by gbraad** [comment]
You are experiencing connectitity issues; `connection refused` when downloading the ISO from github.com. Please make sure your connection is stable.

**Comment by vishalcloudyuga** [comment]
fyi: with *wget*, download works.

**Comment by gbraad** [comment]
Have you retried the deployment... as the download happens from the host machine. So if `wget` works now, it should work for minishift. You probably experienced a glitch or issue with the download redirect from github.com.

Either do:
```
$ minishift start --vm-driver=virtualbox
```
or
```
$ minishift delete --force
$ minishift start --vm-driver=virtualbox
```

**Comment by LalatenduMohanty** [comment]
@vishalcloudyuga Are you able to reproduce this consistently? As @gbraad commented, if the wget is working then `minishift start` should be able to cache the ISO. It might be some temporary networking glitch. Also are you behind any kind of proxy server? 

If you download the ISO manually from https://github.com/minishift/minishift-b2d-iso/releases and put it in the ~/.minishift/cache/iso/b2d/v1.2.0 (for v1.2.0) as below

```
├── iso
│   ├── b2d
│   │   └── v1.2.0
│   │       └── minishift-b2d.iso
```

**Comment by gbraad** [comment]
Note: if really an issue, this would also occur for the download of the `oc` binary.

**Comment by vishalcloudyuga** [comment]
@LalatenduMohanty @gbraad 
After downloading ISO manually and placing it in directory then it gives following error.
```
$ minishift start --vm-driver=virtualbox

-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Starting profile 'minishift'
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ............................... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
Error starting the cluster: Error attempting to download and cache oc: Cannot get the OpenShift release version v3.6.0: Get https://api.github.com/repos/openshift/origin/releases/tags/v3.6.0: dial tcp: lookup api.github.com on 127.0.1.1:53: read udp 127.0.0.1:53988->127.0.1.1:53: read: connection refused

```

**Comment by gbraad** [comment]
This is what I expected... 

Can you explain more about your setup? It seems I see a redirection for the DNS lookup `127.0.0.1:53988->127.0.1.1:53` and it fails to find github,com (or find a wrong address).

**Comment by vishalcloudyuga** [comment]
My local machine running with ubuntu 17.04.
Then i get minishift binary from `https://github.com/minishift/minishift/releases/download/v1.9.0/minishift-1.9.0-linux-amd64.tgz` and i started the 
minishift using 
`$ minishift start --vm-driver=virtualbox`
initially there was virtual box 5.1.3 then i have installed the Virtual box 5.2

**Comment by gbraad** [comment]
are you using VirtualBox on a wireless connection?

**Comment by vishalcloudyuga** [comment]
No i have wired connection.  And i have tested with both wireless and wired connection but the issue remains usolved

**Comment by LalatenduMohanty** [comment]
This is odd. The VM does not have access to internet connection. 
```
Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... FAIL
```

**Comment by gbraad** [comment]
It is not just the VM, but the download happens outside of the virtualization. It seems to check `127.0.1.1` for the DNS lookup.

What does `nslookup github.com` report? and what is in your `/etc/resolv.conf` file?

**Comment by vishalcloudyuga** [comment]
```
nslookup github.com
;; connection timed out; no servers could be reached
```
Then i modified the contents of `/etc/resolv.conf` from `127.0.0.1` to `8.8.8.8`
Then it worked like this
root@VISHU:/root/.minishift# 
root@VISHU:/root/.minishift# vi /etc/resolv.conf 
root@VISHU:/root/.minishift# nslookup github.com
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	github.com
Address: 192.30.255.113
Name:	github.com
Address: 192.30.255.112

```

**Comment by vishalcloudyuga** [comment]
Thanks @gbraad  @LalatenduMohanty  It works perfectly after modifying the contents of /etc/resolv.conf
