### ISSUE TITLE
minishift delete should stop the VM first

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1764]
I've deleted a running minishift instance and I had the following output:

```
$ minishift delete
You are deleting the Minishift VM: 'roadshow'. Do you want to continue [y/N]?: y
Deleting the Minishift VM...
Error deleting the Minishift VM: unexpected EOF
remove /Users/jmorales/.minishift/profiles/roadshow/machines/roadshow/root-volume.sparsebundle/bands/797: permission denied
```

Which indicates that it was trying to delete the files in the profile, and they were in use. If the VM is stopped as part of the lifecycle, I would expect a clear log saying:

```
$ minishift delete
You are deleting the Minishift VM: 'roadshow'. Do you want to continue [y/N]?: y
Instance is running. Let's stop it.
Stopping the Minishift VM...
Deleting the Minishift VM...
```

**Comment by LalatenduMohanty** [comment]
@jorgemoralespou We actually call  a function from docker machine to remove the host. docker machine redirects the call to respective docker drivers . Fir example the remove function in xhyve driver is as follows:
```
func (d *Driver) Remove() error {
        s, err := d.GetState()
        if err != nil {
                if err == ErrMachineNotExist {
                        log.Infof("machine does not exist, assuming it has been removed already")
                        return nil
                }
                return err
        }
        if s == state.Running {
                if err := d.Stop(); err != nil {
                        return err
                }
        }

        if err := d.removeDiskImage(); err != nil {
                return err
        }

        if len(d.NFSShares) > 0 {
                log.Infof("Remove NFS share folder must be root. Please insert root password.")
                for _, share := range d.NFSShares {
                        if _, err := nfsexports.Remove("", d.nfsExportIdentifier(share)); err != nil {
                                log.Errorf("failed removing nfs share (%s): %s", share, err.Error())
                        }
                }

                if err := nfsexports.ReloadDaemon(); err != nil {
                        log.Errorf("failed reload nfs daemon: %s", err.Error())
                }
        }
        return nil
}
```

It stops the VM and then removes it. So atm we do not control the stopping of the VM when we delete the VM. 

The question is, should we first stop it and then delete it?  Yes, we can do that and I think it wont reduce the performance.

**Comment by jorgemoralespou** [comment]
@LalatenduMohanty given that the method you pointed for some reason failed, I would do it manually and control the errors, and give proper feedback to the user.

**Comment by gbraad** [comment]
Performing a stop beforehand might also solve a possible issue in the
virtualbox driver. As often times, it will not delete all the files (as the
process still holds a filehandle on `vbox.log`. This mostly happens on
Windows.

Let's see if a forced stop might resolve this

**Comment by praveenkumar** [comment]
@jorgemoralespou so error which you specified above is resolved if you do `m stop` first and then `m delete`?

**Comment by gbraad** [comment]
I do not think this is the issue... but rather something with xhyve itself that kept the filehandle...

**Comment by praveenkumar** [comment]
@gbraad right issue somewhere lies in xhyve driver plugin side. Below is what I am getting.

```
$ ./minishift delete
--
You are deleting the Minishift VM: 'minishift'. Do you want to continue [y/N]?: y
Deleting the Minishift VM...
Error deleting the Minishift VM: unexpected EOF
remove /Users/prkumar/.minishift/machines/minishift/root-volume.sparsebundle/bands/909: permission denied

$ ./minishift stop
--
Stopping local OpenShift cluster...
Error stopping cluster: unexpected EOF
```

**Comment by gbraad** [comment]
This seems to be something to write about as a known issue, and see if we can move to the hyperkit driver instead.
