### ISSUE TITLE
Provide mechanism to configure OpenShift 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#177]
At least for the CDK usecase we need a way to configure OpenShift with a given set of templates (and potentially run other _oc_ administration commands).

The question is whether we build anything specific into minishift or whether we just include a couple of config (JSON) files as part of the release bundle and let the user run the _oc create_ command. I could image a 'openshift-create' flag in minishift which when specified and pointing to a file/directory processes all found json files. This somehow automates the process a bit. 

Also in some cases it might be necessary to change the config of OpenShift directly. How is this going to work? Is minishift providing any means beyond _minishift ssh_? 

Me preferred setup of minishift is the one where the OpenShift setup is mapped out onto the host. This way OpenShift settings persist even across VM re-creation and it allows to make any OpenShift config changes directly by editing the config file on the host. Problem with that is, that host mounts are not stable across OSes and virtualization frameworks.

Thoughts?

**Comment by praveenkumar** [comment]
> The question is whether we build anything specific into minishift or whether we just include a couple of config (JSON) files as part of the release bundle and let the user run the oc create command.

I think till now minishift had some of the example templates. if we add as part of minishift then we also make sure it's get updated when upstream template get update.

> Is minishift providing any means beyond minishift ssh?

There is `config` flag in earlier minishift version, it have some capability like `set, get, unset and view` but I didn't try it, might be worth to take a look.

 Problem with that is, that host mounts are not stable across OSes and virtualization frameworks.

That is valid point and it not going to work with different providers.

**Comment by LalatenduMohanty** [comment]
> The question is whether we build anything specific into minishift or whether we just include a couple of config (JSON) files as part of the release bundle and let the user run the oc create command. I could image a 'openshift-create' flag in minishift which when specified and pointing to a file/directory processes all found json files. This somehow automates the process a bit.

I would suggest to make it part of default experience. 

For templates `oc cluster up` i.e #167 provides some templates out of the box. Are we talking about some more templates?

**Comment by hferentschik** [comment]
> For templates oc cluster up  provides some templates out of the box. 

Sure, but how does one change these. Replace them with others or add additional configuration, not necessarily only app templates. How are we solving this for CDK?

> Are we talking about some more templates?

We are talking about a generic way of applying configuration and whether minishift is involved at all or whether we basically say, once the initial OpenShift instance is up, it us up to the user to configure OpenShift in whatever ways by using for example the _oc_ command.

**Comment by jorgemoralespou** [comment]
> >For templates oc cluster up provides some templates out of the box.

>Sure, but how does one change these. Replace them with others or add additional configuration, not necessarily only app templates. How are we solving this for CDK?

Should be as easy as --skip-configuration. This should also be supported by "oc cluster up" but that change can be requested to them.

>> Are we talking about some more templates?

> We are talking about a generic way of applying configuration and whether minishift is involved at all or whether we basically say, once the initial OpenShift instance is up, it us up to the user to configure OpenShift in whatever ways by using for example the oc command.

Once the instance is up, a user will probably want to further configure their cluster, so I would think that there needs to be something like:

- *minishift start <profile> --config=my_config*  // This could apply the configuration at bootstrap (Could be cool if oc cluster supported this, but even if not, it's easy to do, like I do in the oc-cluster-wrapper)
- *minishift start <profile> --skip-config*  // This will not load any of the "by default" bootstrapping
- *minishift start <profile>* // Out of the box cluster with default configuration/bootstraping

Also, if "oc cluster up" provided a way to configure it, it could be cool to extend that same mechanism to minishift, so that minishift just calls same mechanism, and people can use same "configuration" for minishift or "oc cluster up". Then allow to use this from addons, and support people creating their own addons, while providing maybe some by default.

**Comment by hferentschik** [comment]
@jorgemoralespou +1, I am basically thinking along the same lines. The details need to be discussed, but I think something in this form makes most sense.

**Comment by LalatenduMohanty** [comment]
+1 @jorgemoralespou. 

One thing to keep in mind that the default configuration (e.g templates )of `minishift start` in CDK vs upstream Minishift might differ.

**Comment by hferentschik** [comment]
See also issue #177

**Comment by jorgemoralespou** [comment]
@hferentschik did you mean other issue? This is 177

**Comment by budhrg** [comment]
> See also issue #177

@hferentschik I think you are referencing wrong issue here.

**Comment by hferentschik** [comment]
I meant issue #59.

**Comment by hferentschik** [comment]
So here is my current thinking around this. Following up on issue #276, we will have  a _minishift openshift_ context. Under this context we add:

    $ minishift openshift package [view|enable|disable|export|install]

A _Package_ or maybe _OpenShiftConfigPackage_ is an interface with two methods methods _apply_ and _isExportable_. A default and probably most commonly used implementation of _Package_ is _OcPackage_, which is basically a package containing of a list of _oc_ command which need to be executed to enable a certain functionality.

We will have our own internal list of packages we always apply, eg exposure of the OpenShift registry (see #254), and we will (further down the road) also maintain several common add on packages which a user can use. A user can use _minishift openshift package view_ to see which packages are available and which ones are enabled. He can also enable (and potentially disable them) via _minishift openshift package [enable|disable] [name]_.

_OcPackage_ instance can also be exported (_minishift openshift package export [name]_) to get a list of oc commands. The user can modify it and then use this new custom package. One can install a package by _minishift openshift package install \<file\>_ which copies the package into the _MINISHIFT_HOME_ directory from where it will be picked up.

Last but not least, we add a _OpenShiftConfigurator_ to the bootstrapping process whose tasks it is to determine which implicit and explicit defined packages to apply. 

This mechanism should allow us to maintain and offer well known packages for ease of use, but also give the user the ability to define its own custom configuration. 

There are several details which still needs some thoughts, but it would be the basic approach. Thoughts?

**Comment by gbraad** [comment]
@hferentschik the idea is a good improvement, but package sounds a lot like a software package. Of course naming is always a difficult thing, but maybe ConfigurationBundle sounds clearer about the intention?

**Comment by hferentschik** [comment]
_Bundle _or better _ConfigBundle_ sounds indeed better +1

> Hope we can keep this as much as possible as a separate tool that we consume, as the use-case seems very generic. This way it is possible to have "which we" be substituted by any other invoker.

+1

**Comment by hferentschik** [comment]
See also https://github.com/minishift/minishift/issues/207#issuecomment-277669143

**Comment by hferentschik** [comment]
@jorgemoralespou, out of your experience what type of commands does one need to do configuration of OpenShiff. Obviously _oc_, but do you also need to run arbitrary system commands on the VM for example (via ssh). I am trying to figure out whether for a user provided configuration bundle we get away with a list of _oc_ commands which we just execute, or whether we need to handle different types of commands (ssh, oc, openshift) and hence maybe need to put some sort of DSL on top. WDYT?

**Comment by jorgemoralespou** [comment]
@hferentschik so far, in my experience all where "oc" and "oc adm" and "openshift" commands to deploy stuff and change configuration.
Also I have some util functions to check things like:
- Is it connected to internet (for when the plugin will pull down things from the internet, not to execute if there's no connectivity) [example](https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/oc-cluster-engineers/plugins.d/cfme.local.plugin#L17)
- Provide some self values like:
  - default domain (in case templates need to provide the domain suffix) [example](https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/oc-cluster-engineers/plugins.d/gitlab.local.plugin#L44)
  - default ip of the master [example](https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/oc-cluster-engineers/plugins.d/cockpit.local.plugin#L48)
- ability to provide some templates to be processed [example](https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/oc-cluster-engineers/plugins.d/volumes.global.plugin#L34-L51)
- ability to patch config [example](https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/oc-cluster-engineers/plugins.d/user.local.plugin#L23)

Adding some more people to chime in. @grahamdumpleton @siamaksade @marekjelen @thesteve0

**Comment by hferentschik** [comment]
@jorgemoralespou awesome, thanks a lot. That helps a lot.

**Comment by hferentschik** [comment]
@jorgemoralespou regarding self referencing values, would you think that we can define a reasonable subset of variables (ip, route suffix, etc) which is useful. I don't think it is realistic to be able to "interpolate" any sort of variable used w/i OpenShift. WDYT?

**Comment by jorgemoralespou** [comment]
@hferentschik I don't understand your question really well, but I will take a guess and say that only a subset related to the things that might change are relevant. Usually domain, master ip, hostname, and possibly some others (In my case Platform, but I understand here is not relevant).

**Comment by hferentschik** [comment]
>  say that only a subset related to the things that might change are relevant

ok

> domain, master ip, hostname

they are the usual suspects I guess

> possibly some others

we would need to be more specific here ;-) Maybe we start with supporting the obvious ones and then add more as people request them

> Platform

What do you mean with that?

**Comment by jorgemoralespou** [comment]
> Platform 
In my use case, as oc-cluster can be run on linux, docker for mac, and docker for windows, there's some things I do that depends on the platform, like get the IP of the cluster. On linux it's native, on Mac runs on a VM, ... And there's some other stuff, like the file permissions, SELinux on the host. When I mount volumes from the host, if Platform is Linux, I fix SELinux tags. Also, to remove things, on Linux platform some files are created with root user (as Docker runs with root), so there's special treatment.

(e.g. https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/master/oc-cluster#L510)

**Comment by hferentschik** [comment]
So here is what I am thinking right now:

The key for this is a (config) bundle. A bundle consist of some meta data (for now name and description should do). There are built-in bundles, like the ability to change the default security policy around running containers to 'run-as-any'.

A user can also write a custom bundle by creating a simple text file (*.bundle) and placing it into
_$MINISHIFT_HOME/bundles_. Eventually we can also offer a command to copy the bundle to the right location. 

- `$ minishift openshift bundle list` - list available bundles (internal ones as well as user provided ones)
- `$ minishift openshift bundle set 'bundle-1,bundle-2,bundle-3'` - the user specifies a comma separated list of bundles to enable. This defines also the order in which bundles are applied. The enabled bundle list will be persisted in _config.json_ and applied on each creation of a VM/OpenShift. Moving forward we might find a better way let the user specify the bundles to executes and its orders.

Regarding `minishift openshift bundle set`, one could consider using `minishift config set`. This wold be more aligned with setting other configuration related properties.

**Comment by hferentschik** [comment]
Adding a pointer to my current working branch https://github.com/hferentschik/minishift/commits/issue-177. Feedback welcome. It defines the skeleton structs and interfaces I think are needed. 

Some notes:

* I actually settled for _addon_ as term for now. Mainly to align with Minikube's terminology. This is work in progress. As part of the implementation or based on feedback, I might switch back to the term _bundle_
* To align with Minikube there are `minishift config add ons [enable|disable|list]`
* Also instead of having some internal addons, all addons will be maintained as files. At compile time we are adding the provided addons to the minishift binary (go-bindata) and extract then into _$MINISHIFT_HOME/addon_ when we detect that none are there. 
  * This will make provided addons explicit
  * Even provided addons can be modified by the user (be editing the file _$MINISHIFT_HOME/addon_)
  * The user has examples to build/create new addons
* Each addon needs to be put into its own directory. This allows adding other resource file, like yaml templates to be processed as part of the addon
* The idea is to have some sort of mini DSL, in terms of the addon requiring some simple metadata (name, description) and then allowing  to run _oc_, _docker_, _openshift_ commands as well as having a _wait_
* Implementation wise there will be an AddOnParser which is responsible to parse the file based addon and transfer it into the internal Addon struct. Then it is the responsibility of the AddonManager to apply an Addon and manage enabling/disabling it
* Command is the internal interface for all command types allowed in a addon

**Comment by budhrg** [comment]
@hferentschik  From your comment https://github.com/minishift/minishift/issues/177#issuecomment-284344200 

> $ minishift openshift bundle set 'bundle-1,bundle-2,bundle-3' - the user specifies a comma separated list of bundles to enable. This defines also the order in which bundles are applied. The enabled bundle list will be persisted in config.json and applied on each creation of a VM/OpenShift. 

I hope you mean `set` with `enable` here. Or are we using `set` here?
 
Is this `config.json` is `MINISHIFT_HOME/config/config.json` or we will have machine specific `config.json`.
I am thinking of multiple machines scenario here since users can have different bundles enabled for different machines. I know this is just a future prospects but if we name the things accordingly then it would help.

WDYT?

**Comment by budhrg** [comment]
> To align with Minikube there are minishift config add ons [enable|disable|list]

So this means, we are making it as part of config command not separate `addons` command like `minikube`.

> Also instead of having some internal addons, all addons will be maintained as files. 

Like the idea :+1:  So I believe parser will take care of all invalid entries in the file, error handling etc.

Rest seems good to me. Exciting to see it live :)

**Comment by hferentschik** [comment]
>  hope you mean set with enable here. Or are we using set here?

You are looking at something obsolete.  You need to look at the last comment I made.

> Is this config.json is MINISHIFT_HOME/config/config.json

Yes, at least initially. It becomes part of the other config options. 

> I am thinking of multiple machines scenario here since users can have different bundles enabled for different machines.

Good point and you are right. However, the whole config.json has this problem. Part of switching the "profile" could also be to have different driver or memory and cpus setting. Once we implement profiles we most likely handle config.json in some way. We could use the newly created machine specific config file, not sure. Let's see.

> So this means, we are making it as part of config command not separate addons command like minikube.

Ahh, another good one, thanks. I got a bit confused, in code the Haddon commands in Minikube live under the config package - https://github.com/kubernetes/minikube/tree/master/cmd/minikube/cmd/config, so I automatically assumed that they are config sub-commands. Even though of course they add it to the root command. So in this case the _addon_ commands would go under the root. I'll adjust the code accordingly. However, I will create a dedicated addon package instead.

> So I believe parser will take care of all invalid entries in the file, error handling etc.

That's the idea. The parser makes sure that there are only commands we support and that there is the appropriate meta data, etc. If any of this fails, it would log at the very least a WARNING. One could imagine logging a warning for non enabled addons and aborting for addons which are enabled. 

Thanks for the feedback. Much appreciated. Already shaking out some things ;-)

**Comment by budhrg** [comment]
> Good point and you are right. However, the whole config.json has this problem. Part of switching the "profile" could also be to have different driver or memory and cpus setting. Once we implement profiles we most likely handle config.json in some way. We could use the newly created machine specific config file, not sure. Let's see.

**Comment by jorgemoralespou** [comment]
@hferentschik Regarding to the profile point that @budhrg  raises, since this type of changes will break compatibility, I would probably at least have an R&D cycle and make things in such a way that compatibility is not an issue.
Also, if the addon will have a descriptor file, for name, description, help, ... it would be interesting to add a compatibility option. Something like "requires >= oc-version" so that user can not run addons with a version of openshift that don't support the feature. It would be good also to have maximum version, for those addons that are created for specific version ranges (1.4.x) so that if you get the feature from openshift itself, the addon can not be enabled.
Eventually there will be addons re-distribution and there's a lot of things that are subject to change in openshift with respect to, for example, resource definitions. There's API groups coming soon https://github.com/openshift/origin/pull/12986 that will make current templates (made for 1.4) obsolete, but you will still want to support different openshift versions.

**Comment by hferentschik** [comment]
Merged via pull request #625
