### ISSUE TITLE
Minishift unable to find oc binary

### ISSUE THREAD

**Issue by mmclanerh** [minishift/minishift#1770]
Hi! 

I've deployed the oc binary from "openshift-origin-client-tools-v3.6.1-008f2d5-linux-64bit.tar.gz" to ~/bin/oc.  When running "minishift oc-env", minishift is reporting an error attempting to find the oc binary.  I'm confused about what it's not able to find.

```
[mmclane@mmclane ~]$ which minishift
~/bin/minishift
mmclane@mmclane ~]$ which oc
~/bin/oc

[mmclane@mmclane ~]$ echo $PATH
{..snip..}:/home/mmclane/bin

[mmclane@mmclane ~]$ minishift oc-env
Cannot find the OpenShift client binary.
Make sure that OpenShift was provisioned successfully.
```

**Comment by gbraad** [comment]
We do not use a manuaklly downloaded `oc` client. In the documentation it is described that after you have succesfully started a cluster with `minishift start`, you can use either:
```
$ eval `minishift oc-env`
```
or
```
$ eval $(minishift oc-env)
```
for instance, to add `oc` to your `$PATH` variable.

**Comment by gbraad** [comment]
Closing the issue. If the problem persists after a successful `minishift start`, please reopen this issue with the steps performed.
