### ISSUE TITLE
Hostfolder password with a non-alphanumeric character like $ fails to mount

### ISSUE THREAD

**Issue by eliu** [minishift/minishift#1772]
### Issue Description
I create a share folder via SMB from `Share` window of `System Preference` on my macOS. However the `minishift hostfolder mount` command got a `FAILED` result while mounting this shared folder.

and from the discussion of #1539 , i believe the issue occurs because of the special character such as dollar sign `$` existing in my password.

### Debugging info

```
# sudo mount -t cifs //192.168.99.1/local /mnt/sda1/local -o username=eliuhy,password=xxxxxx,context=system_u:object_r:svirt_sandbox_file_t:s0
# xxxxxx is a password that contains dollar sign $
...
SSH cmd err, output: exit status 32: mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
...
```

### Version info
```
$ minishift version
minishift v1.8.0+6455fc3
```

**Comment by gbraad** [comment]
Best solution would be to do:

```
$ minishift ssh -- "echo [base64messageofpasswordusername] | base64 -d > /tmp/creds > /dev/null && mount [folder] -o credentials=/tmp/creds/ && rm /tmp/creds"
```

from code, as this would work around any need to escape the password. This is also used for the network configuration.

**Comment by gbraad** [comment]
Merged as f6cdb9597ea106d6469b32361e08c67d6454ca10

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1777

**Comment by gbraad** [comment]
Technically it was not fixed with that PR, as the SHA's are different due to the rebase and changed commit title. ;-)

**Comment by LalatenduMohanty** [comment]
@gbraad The reason I mark the PR because it helps to quickly track what discussions we had on the PR which lead to merging of the code and closing of the issue.  At least I feel it will be useful at some point.
