### ISSUE TITLE
Integration tests are failing because nip.io is down

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1773]
Our CentOS CI jobs are failing continuously due to issue in `basic.feature` file. Not sure how it is coming even though we don't have any change in `basic.feature`.

![screenshot from 2017-11-30 14-22-31](https://user-images.githubusercontent.com/1132451/33421964-f0320fa8-d5d9-11e7-9da2-c0334e431114.png)

Seems to be error on verifying the `ruby-ex` application url.
![screenshot from 2017-11-30 14-25-13](https://user-images.githubusercontent.com/1132451/33422104-77a6eecc-d5da-11e7-827a-f0914fb961f9.png)

**Comment by gbraad** [comment]
Please run manually. Maybe the message has changed?

**Comment by budhrg** [comment]
Though all jobs are failing, here are few
- https://ci.centos.org/job/minishift-pr/2847/console
- https://ci.centos.org/job/minishift-pr/2846/console

**Comment by LalatenduMohanty** [comment]
This got passed https://ci.centos.org/job/minishift-pr/2848/

**Comment by agajdosi** [comment]
@LalatenduMohanty It also fails for me while checking manually, is probably due to the nip.io being offline. However I am wondering how is it possible that nodejs-ex in cmd-openshift.feature passed every single time? Might be just a luck? Maybe some requests gets through? (Applies also for 2848 pass.)

**Comment by budhrg** [comment]
> This got passed https://ci.centos.org/job/minishift-pr/2848/

That job completed in ~28 mins and usual build time is ~46mins. May be this time hardware is in top performace.

**Comment by agajdosi** [comment]
Ended my wonders, we deploy applications in proxy.feature and cmd-openshift.feature, however these do not have the checks on http endpoints, so that's why just ruby-ex in basic.feature fails.

**Comment by lucascosti** [comment]
DNS resolution to nip.io seems to be all over the place for at least the past 24 hours https://dnschecker.org/#A/nip.io

Perhaps going back to xip.io might be worth considering..

**Comment by praveenkumar** [comment]
@lucascosti I kind of agree, now it more than 24 hours and they even don't have mentioned anywhere when it will be back :(

**Comment by budhrg** [comment]
Closing this issue as nip.io is back to online and all integration tests are passing.

**Comment by gbraad** [comment]
We are looking at a way to mitigate the risk in the future.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]
