### ISSUE TITLE
Future release artifact of openshift/orgin will landup to GCS

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1775]
According to [this ML post](http://lists.openshift.redhat.com/openshift-archives/dev/2017-November/msg00035.html) @smarterclayton kind of made sure that feature releases of origin going to land up to GCS. 

If origin team doesn't have any plan to publish release artifacts to GitHub then we need to start putting effort how to handle it. I do like one of the suggestions from @GrahamDumpleton in [this ML post](http://lists.openshift.redhat.com/openshift-archives/dev/2017-November/msg00034.html) to have an index file in minishift org to contain version to binary URL mapping.

I am not sure how painful this will be for China users since @gbraad had issued to pull anything from GCS without VPN. 

Note (gbraad): Posted the contents on the mailinglist posts here

**Comment by gbraad** [comment]
The connectivity for China is at best described as intermittent, as mostly 90% of the connectivity is blocked when it concerns Google services. Google Cloud Storage seems to be a hit-miss case, it might work... or might not. This is also why I filed https://github.com/openshift/origin/issues/17525 (but have closed as for this release it is resolved).

But, the issue remains that the path to download these artifacts is riddled with 'test' and a build ID. This feels misleading and is not easily guessable.

**Comment by gbraad** [comment]
*From*: Graham Dumpleton <gdumplet redhat com>
*Subject*: Re: Unpredictable oc binary path for Origin version v3.7.0
*Date*: Thu, 30 Nov 2017 19:08:59 +1100

---

Personally I would have had a GitHub repo under Minishift org which had just an index file in it keyed by versions which are known to work and can be used. Minishift could then pull down the index file, get the URL for where binary is, which could be anywhere, and then fetch it from there.

Yes it means the index file has to be updated, but being a separate repo that doesn't need a new Minishift release and could be done at any time.

This would also solve problem of GitHub API rate limiting when Minishift is behind a corporate fire wall, something that I believe was affecting the Minishift developers themselves early on. Not sure if workaround for that was worked out.

So as is always the case, a level of indirection solves all problems.

---

**Comment by gbraad** [comment]
*From*: Clayton Coleman <ccoleman redhat com>
*Subject*: Re: Unpredictable oc binary path for Origin version v3.7.0
*Date*: Thu, 30 Nov 2017 10:11:20 -0500

---

I can  publish them to github for 3.7.  We’re looking to reduce the amount of  effort required to publish binaries so we can do it more often.  Expect  binaries to be published to GCS in the future.

---

**Comment by praveenkumar** [comment]
@minishift/minishift-dev Looks like 3.7.1 artifacts land up correctly on GitHub itself not sure if Openshift folks hear us out and will make sure it will be same this way for future releases also.

**Comment by budhrg** [comment]
This is still not sure.

**Comment by LalatenduMohanty** [comment]
@minishift/minishift-dev With recent releases, the artifacts were only released on github, so I am not sure if it happening. I am inclined to close this issue and recreate a new issue when it happens again. WDYT?

**Comment by gbraad** [comment]
We can close.

**Comment by budhram** [comment]
Closing this issue as per above discussion.
