### ISSUE TITLE
Update default OpenShift Origin version to 3.7.1 in Minishift

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1776]
Now that Origin v3.7.0 is released we should move to the latest GA version.

**Comment by hferentschik** [comment]
There is also the service catalog question. Per 3.7 it should be enabled er default. Does this work? With the upgrade does the service catalog get provisioned automatically? If so, there is no need anymore for the experimental flag and it should be removed from the code and docs.

**Comment by praveenkumar** [comment]
> There is also the service catalog question. Per 3.7 it should be enabled er default. Does this work? With the upgrade does the service catalog get provisioned automatically? If so, there is no need anymore for the experimental flag and it should be removed from the code and docs.

Problem is `oc cluster up` still have this as an experimental feature like logging/metrics so I still think we should not expose this by default.

```
$ oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.110.218:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

$ oc cluster up -h | grep catalog
      --service-catalog=false: Install service catalog (experimental).
```

**Comment by jorgemoralespou** [comment]
@LalatenduMohanty Service Catalog should no longer be an experimental flag, as it is a GA feature in OpenShift 3.7 and should be exposed and available.

**Comment by praveenkumar** [comment]
@jorgemoralespou As I said https://github.com/minishift/minishift/issues/1776#issuecomment-349870979 since for `oc cluster up` it's experimental flag then we can't go ahead and make it permanent and internally use same logic :(

**Comment by jorgemoralespou** [comment]
@praveenkumar. Totally disagree. The same way logging and metrics are
experimental and they are exposed. They are marked experimental because
provisioning of the feature is not really bullet proof, but to be honest,
service catalog is more reliable than metrics or logging, since it's
developed by same team as oc cluster.

**Comment by praveenkumar** [comment]
> Totally disagree. The same way logging and metrics are experimental and they are exposed. They are marked experimental because provisioning of the feature is not really bullet proof, but to be honest, service catalog is more reliable than metrics or logging, since it's developed by same team as oc cluster.

@jorgemoralespou right but even metrics and logging has still experimented from the minishift side. If you want same with `service catalog` then we can expose that option but our help string will show that it experiment same as oc cluster up.

```
$ ./minishift start -h | grep metrics
      --metrics                         Install metrics (experimental)
```

**Comment by praveenkumar** [comment]
@jorgemoralespou ah I get it so you want that option of `service-catalog` should not be behind experiment flag but directly part of start option. Does following works?

```
$ ./minishift start -h | grep service
            --service-catalog                    Install service catalog (experimental).
```

**Comment by jorgemoralespou** [comment]
Yes
