### ISSUE TITLE
Support for Addon Dependency

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1781]
_From @kameshsampath on December 4, 2017 6:42_

Currently the addon can't depend on another addon, it will be nice to add the add on dependency  so that we can specify them via the addo scripts using `include my-addon` or when doing install i can add `--dependencies='addon-a,addon-b'` etc.,

_Copied from original issue: minishift/minishift-addons#56_

**Comment by gbraad** [comment]
I think this would be part of the meta data on the header, as a dependency is a Requirement, much like OpenShift version.

**Comment by jorgemoralespou** [comment]
I think we discussed this. We tried this in the oc-cluster plugins and we decided that addons should be self contained or documented that dependencies exist, and not install other addons automatically as can have side effects.

e.g. If I have an addon that depends on xpaas, the imagestreams could be replaced, and it might screw some other deployments that are already in place.
