### ISSUE TITLE
Validating Requirements for add-on

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1782]
_From @kameshsampath on December 4, 2017 6:44_

When installing some addons we might have some pre-req like 4GB of RAM, 4 CPUS etc., it will be great if we can add option via metadata file or something so that when installing the addon the developer might know what the pre-req

_Copied from original issue: minishift/minishift-addons#57_

**Comment by gbraad** [comment]
This check would not be sufficient, as checking the startup parameters of the Minishift VM is not enough. I might have 4GB assigned, but actually run several heavy applications, like CoolStore, etc. If the add-on would check this, it should have to check 'available memory' and 'available storage', etc.

I think a good first step is to enhance the `m status` command further, like we added the storage check, but for available memory and swap. This way we can also use this during the integration tests, and use this for future checks related to add-on requirements.

**Comment by gbraad** [comment]
When I think more about it, I'd rather not call them hard requirements, but rather minimums.

  * `Required-Memory: 4G`
  * `Minimum-Memory: 4G`

**Comment by jorgemoralespou** [comment]
I think this should be documentation of the addon. Enforcing this type of requirements on addons is a -1 from me. 
Also the configuration can be changed after the fact, when the addon has already been applied. Or I can have an addon with a minimum requirement of 4GB that I apply on a profile that already has many other deployments, and it would still fail.

I think this should be part of the documentation the addon creator needs to write, and that should need to be displayed to the user.

```
$ minishift addon list --verbose
Name       : coolstore-demo
Description: Installs the coolstore demo. You should have at least 4GB of ram free on the VM to run this addon
Enabled    : enabled
Priority   : 0
```
