### ISSUE TITLE
server misbehaving error on https://index.docker.io

### ISSUE THREAD

**Issue by honghuac** [minishift/minishift#1784]
Received this error message when starting up minishift today.

Pulling image openshift/origin:v3.6.0
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v3.6.0 image ... 
   Pulling image openshift/origin:v3.6.0
FAIL
   Error: error pulling Docker image openshift/origin:v3.6.0
   Caused By:
     Error: Error while pulling image: Get https://index.docker.io/v1/repositories/openshift/origin/images: dial tcp: lookup index.docker.io on 192.168.42.1:53: server misbehaving
Error during 'cluster up' execution: Error starting the cluster.

**Comment by praveenkumar** [comment]
@honghuac looks like network glitch here, you might try again after some time. Also please provide the complete logs where we have network preflight check.

**Comment by praveenkumar** [comment]
@honghuac I hope it is fixed for you, closing this now. Please reopen if you still seeing this issue.
