### ISSUE TITLE
Fix commit message validation regex

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1788]
[Commit message validation](https://docs.openshift.org/latest/minishift/contributing/developing.html#commit-message-requirements) seems to be using the wrong regex here 

https://github.com/minishift/minishift/blob/e99350316a8a15a7f489f15aeec44b919fd78c71/Makefile#L233

I was expecting my PR https://github.com/minishift/minishift/pull/1786  with message `Must fail Issue #1785 Validate commit message as part of CI builds` should fail but it is not.

**Comment by gbraad** [comment]
https://regex101.com/r/Iv69Jr/2 (switch to unit test view)

Actually, we should also prevent spaces after the cut of the release.
![image](https://user-images.githubusercontent.com/1894/33591253-6f192700-d9bf-11e7-8ea6-d1e3624adb64.png)

**Comment by gbraad** [comment]
`^(Issue #[0-9]+ .*|cut v[0-9]+.[0-9]+.[0-9]+$)`

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1789
