### ISSUE TITLE
Improve checks for existing machine during 'minishift start'

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#179]
When executing 'minishift start' a check for an existing VM occurs. If a machine exists, minishift tries to resume it. This causes problems when the user actually wants to start a new minishift instance using other CLI options, most notably a different driver. 

Checks around this should be improved.

**Comment by hferentschik** [comment]
The error looks somewhat like this:

    C:\Users\cdk\Desktop>minishift.exe start
    Starting local OpenShift cluster...
    E1206 11:59:36.234074     748 start.go:117] Error starting host: Error getting state for host: Failed to find the VM     status. Retrying.
    E1206 11:59:36.816459     748 start.go:117] Error starting host: Error getting state for host: Failed to find the VM     status. Retrying.
    E1206 11:59:37.355990     748 start.go:117] Error starting host: Error getting state for host: Failed to find the VM     status. Retrying.
    E1206 11:59:37.355990     748 start.go:123] Error starting host:  Error getting state for host: Failed to find the     VM status
    Error getting state for host: Failed to find the VM status
    Error getting state for host: Failed to find the VM status

**Comment by hferentschik** [comment]
A way to resolve this issue, would be to have dedicated 'create' and 'start' commands. This would make it easier to determine the cases and provide better error messages.

**Comment by LalatenduMohanty** [comment]
What about adding a flag in `minishift start` to do a clean start i.e. it should delete the existing .minishift and start fresh.

**Comment by hferentschik** [comment]
> What about adding a flag in minishift start to do a clean start i.e. it should delete the existing .minishift and start fresh

Sure, possible. However, in this case I find a dedicated command more explicit and self documenting.

**Comment by LalatenduMohanty** [comment]
Also it should ask for confirmation from user if he wants to delete existing .minishift and start fresh. The benefit of having it in `start` is that user does not have to remember another new command. I think from user experience point of view it is more appropriate as user does not want to create but want to start but as a fresh setup.

**Comment by LalatenduMohanty** [comment]
I think `minishift start --factory-reset` or something similar will be more intuitive than create.

**Comment by LalatenduMohanty** [comment]
@jimmidyson any suggestion?

**Comment by jimmidyson** [comment]
`minishift clean` sounds good to me, with confirmation from user. I think that `start` should exit if already started, not try to update running machine.

`create` is problematic as docker machine doesn't have that in library iirc.

**Comment by hferentschik** [comment]
This ties very much into another discussion we need to have. Do we want to support multiple OpenShift instances created and managed by minishift? Similar to what docker-machine does. If so, a _create_ makes sense, since now we also need to take things like minishift instance name into account. 

>  ... but want to start but as a fresh setup.

which is _create_ right. I think a distinction is very intuitive. IMO the current _minishift start_ tries to mangle two things into one command.

> minishift clean sounds good to me, with confirmation from user.

How does that differ from the current _delete_ command?

> I think that start should exit if already started, not try to update running machine.

So, if it is running and you run _start_ again, nothing should happen. But what if the machine is _stopped_ (not deleted) and a new _start_ command is issued? I think that is the case which we see most often. The code seems to detect that there is a exiting stopped machine, tries to resume it and gets into trouble (at least I think this is what we are seeing. This needs a bit more investigation as well).

> create is problematic as docker machine doesn't have that in library iirc.

We don't need necessarily a create from the underlying libmachine. The distinction between _create_ and _start_ is something we handle within minishift.

**Comment by LalatenduMohanty** [comment]
@hferentschik I have seen some command lines have `create` and `start` as verbs and I do not find it intuitive as I always get confused. 
Think from this prospective, `minishift create` will not do anything extra from `minishift start`  apart from deleting the .minishift directory. `Create` is not creating anything but deleting the .minishift directory. So it is not logical to call it create IMO.

I think `clean` is better than `create` as @jimmidyson suggested. As it will clean the .minishift directory. `delete` will delete the VM and `clean` will clean the directory.

**Comment by hferentschik** [comment]
> I have seen some command lines have create and start as verbs and I do not find it intuitive as I always get confused.

How come? Personally I think it makes these two things actually explicit and easier to understand. I think docker-machine does it actually right there. _create_ for me means build something from scratch, and _start_ get something existing to run. 

> Think from this prospective, minishift create will not do anything extra from minishift start apart from deleting the .minishift directory.

Well, the essence of _create_ is not to delete the existing machine. This is _minishift delete_. _create_ is about taking the two steps _start_ does and putting the _creation_ part into _create_ and only have the start part in the _start_ command. 

> I think clean is better than create

_clean_ is also needed and there is an issue for that, but it addresses another problem. Having _clean_ is not going to improve the situation reported in this issue.

**Comment by hferentschik** [comment]
Another advantage of a separation between _clean_ and _start_ would be that minishift could controls the use of the _--use-existing-config_ flag for _cluster up_. During create it would be _false_, but during _start_ you would set it to _true_. Otherwise it would be up to the user to manage this.

**Comment by LalatenduMohanty** [comment]
I was actually talking a different context then what @hferentschik mentioned here.  I was actually thinking about completely starting from fresh (i.e. without minishift ISO cached), hence the references to deleting .minishift directory.

**Comment by LalatenduMohanty** [comment]
@hferentschik Is there possibility that user can still get in to issues if he runs `minishift delete`  before `minishift start`  with a different driver?

**Comment by jorgemoralespou** [comment]
@hferentschik @LalatenduMohanty @jimmidyson What is your idea for the lifecycle of minishift vms?
I'm asking as I see a clean/create rather superfluous, of course, depending on how you implement things. I think that simplicity is really a must, and the less commands the better. I've seen this workflow with vagrant which has been very successful over time.

I like the fact that simple start/stop or up/down exist and these command with a delete/destroy should be sufficient. Creation and starting of a VM should be handle at the same time, and if the machine is new, then it should go through all the creation lifecycle (although not providing this as separate step).

In case a VM needs to be recreated, we should aim to be able to destroy/start with the less impact to the user. This ultimately means that:
- the iso needs to be cached (multiple isos can be stored and managed, like vagrant box create |list|delete)
- the images should also be cached on the host (at least provide an option to cache them)

If we can provide these 2 options, destroying and creating should always be easier to implement and safer in resulting configuration than any update you can do to an existing VM. 

Also, if this is the case, what would a clean provide? Shouldn't that be something handled by "destroy" that would delete .minishift/<profile>

NOTE: I have included a <profile> in minishift directory as I think we should aim to have it as there are specific configuration that will be local to a VM (start params, config,...) and other that will be global to all VMs(isos, images,...). 

Is there a proposal/design document with all the goals you want minishift to have and how you're thinking on addressing them?

**Comment by hferentschik** [comment]
> I'm asking as I see a clean/create rather superfluous, of course, depending on how you implement things. 

Agreed, one alternative for example is to store some meta information about the start parameters and on a successive start act accordingly:

* Same parameters -> no issue
* Parameters differ -> warning, user interaction needed, potentially abort
* No parameters -> things get a bit interesting here. 
   * No parameters and there is no machine -> create machine and bootstrap. 
    * Machine exists, apply the stored parameters and give feedback to the user (otherwise it is magic why sometimes parameters are needed and sometimes not)

We will have to work more with metadata sooner or later, since we will also need to at some stage find ways to make sure that for example custom configurations only get applied once. 

>  I think that simplicity is really a must, and the less commands the better.

+1, however sometimes more commands can be better as well. There is a trade-off here, between simplicity and clarity to the user. All I was saying was so far,  that to me an additional separation in commands could make sense. I am partly looking at docker-machine behavior here. 

> I like the fact that simple start/stop or up/down exist and these command with a delete/destroy should be sufficient

As you say, it depends. 

> the iso needs to be cached (multiple isos can be stored and managed, like vagrant box create |list|delete)

+1 and partly already working this way.

> the images should also be cached on the host (at least provide an option to cache them)

+1 There is an issue for this - https://github.com/minishift/minishift/issues/143. Even though the plan for now is to just cache the main OpenShift image to improve startup time. There is another idea to keep all state on the host allowing even to throw away the VM and re-creating it w/o loosing OpenShift configuration state. This can be done already and I use it regularly, but it depends on the ability to consistently mount host directories into the VM.

And +1 to make this optional. 

> Also, if this is the case, what would a clean provide? Shouldn't that be something handled by "destroy" that would delete .minishift/

No, delete is currently just deleting the machine sub directory. This is the VM and its state effectively. What we need and want is a full clean, roughly equivalent to deleting the whole ~/.minishift directory. In this context I am leaning atm towards an additional flag 'minishift delete --all'. I also want to provide a command which gives the user an indication on which data is stored on the host, what it means and how much memory it takes up.

>  I have included a in minishift directory as I think we should aim to have it as there are specific configuration that will be local to a VM (start params, config,...) and other that will be global to all VMs(isos, images,...).

I am not quite sure what you mean here. Are you missing parts of a sentence?

> Is there a proposal/design document with all the goals you want minishift to have and how you're thinking on addressing them?

ATM things would be spread out across the issues here. I guess one way of getting a better feel for things is to look at all issues marked as [feature](https://github.com/minishift/minishift/issues?q=is%3Aissue+is%3Aopen+label%3Afeature). That said, it might make sense to create a roadmap of some form and make it part of the docs.

**Comment by hferentschik** [comment]
@jorgemoralespou - fyi https://github.com/minishift/minishift/issues/207

**Comment by jorgemoralespou** [comment]
>Agreed, one alternative for example is to store some meta information about the start parameters and on a successive start act accordingly:
>* Same parameters -> no issue
>* Parameters differ -> warning, user interaction needed, potentially abort
>* No parameters -> things get a bit interesting here.
>   - No parameters and there is no machine -> create machine and bootstrap.
>   - Machine exists, apply the stored parameters and give feedback to the user (otherwise it is magic why sometimes parameters are needed and sometimes not)
>We will have to work more with metadata sooner or later, since we will also need to at some stage find ways to make sure that for example custom configurations only get applied once.

Once a machine is created, why should a user want to change some configuration? I would only support that configuration that can be applied via a plugin/config command, and not the configuration needed to bootstrap, so that a user would implicitly change configuration. And to be honest, the only option I can think of is to support proxies as you move from a location into another, I can not think of another change that should occur with a configured cluster. Hence, I would try to simplify these scenarios to the maximum. This is very much what many developers are already used to.

>> I think that simplicity is really a must, and the less commands the better.

> +1, however sometimes more commands can be better as well. There is a trade-off here, between simplicity and clarity to the user. All I was saying was so far, that to me an additional separation in commands could make sense. I am partly looking at docker-machine behavior here.

Agree


>> the images should also be cached on the host (at least provide an option to cache them)

> +1 There is an issue for this - #143. Even though the plan for now is to just cache the main OpenShift image to improve startup time. There is another idea to keep all state on the host allowing even to throw away the VM and re-creating it w/o loosing OpenShift configuration state. This can be done already and I use it regularly, but it depends on the ability to consistently mount host directories into the VM.

I think state should not be on the host and mainly as depends on mounting host filesystems. Only things that should live in the host, IMHO are:
- isos
- images (and possibly not all, definitely not the ones built as part of s2i)
- startup configuration to minishift, bootstrap log,
This would provide the benefit that:
- size on host can be easily controlled
- deleting a machine can delete anything related to that cluster
That would just add some additional management to isos, cached images and profiles.
- A destroy/delete would delete the profile and the machine but keep the isos and cached images
- A "nuke" command will delete the complete minishift. Although I don't see this useful, and maybe could be handled by an uninstall process.

> No, delete is currently just deleting the machine sub directory. This is the VM and its state effectively. What we need and want is a full clean, roughly equivalent to deleting the whole ~/.minishift directory. In this context I am leaning atm towards an additional flag 'minishift delete --all'. I also want to provide a command which gives the user an indication on which data is stored on the host, what it means and how much memory it takes up.

I see this so dangerous as a command, that I would not implement it, or call it "uninstall". Deleting .minishift if you have multiple clusters will delete each one of them, and I don't think a user would want to do that regularly enough to provide a command, and less with that name.

>> I have included a in minishift directory as I think we should aim to have it as there are specific configuration that will be local to a VM (start params, config,...) and other that will be global to all VMs(isos, images,...).

> I am not quite sure what you mean here. Are you missing parts of a sentence?

This was linked to previous comment, that markdown messed up:

__Also, if this is the case, what would a clean provide? Shouldn't that be something handled by "destroy" that would delete .minishift/PROFILE__

I was referring to the fact that the profiles need to be centralized under a .minishift, but every profile should have their own folder that can be safely deleted, but again, I think that providing a command to delete .minishift would not be a priority for me, and if implemented, definitely with a more clear name: nuke/uninstall/... 

I saw the issue for the Roadmap #207. Waiting for your comments there.

**Comment by rkratky** [comment]
From a usability point of view (also considering the documentation aspect -- how easy/difficult it would be to explain the different stages to users), I'd suggest splitting the start command into _create_ and _start_ as @hferentschik proposes. The bigger number of commands wouldn't add complexity -- instead, it would be more intuitive -- and it would also be easier to document it without ambiguity.

Consider the following VM lifecycle:

1. _create_ (initialize a VM)
2. _start_ (run a created VM)
3. _stop_ (halt a VM) (with an optional _--force_ parameter)
4. (optional) _start_ (run a stopped VM)
5. _destroy_ (get rid of a stopped VM -- now handled by _delete_)

On top of that, there would be an _uninstall_ command as proposed by @jorgemoralespou -- to remove the Minishift environment (`~/.minishift`).

**Comment by hferentschik** [comment]
So, it seems the Minikube folks are onboard with the split of the _start_ command into something like _create_ + _start_. See also:

* https://github.com/kubernetes/minikube/issues/1147
* https://github.com/kubernetes/minikube/issues/364

We should provide input for https://github.com/kubernetes/minikube/issues/364, so that we can eventually keep the same/similar ux for the user.

**Comment by gbraad** [comment]
Will this mean we will wait for them to implement this and port back... or... do it ourselves?

**Comment by hferentschik** [comment]
> Will this mean we will wait for them to implement this and port back... or... do it ourselves?

It depends ;-) I am not sure how a backport really would be. It also depends when they start implementing this and how long it takes. Most important imo is to align how this is going to work. Then we can see who is getting to this first. It could also be that we implement it first and contribute to Minikube?

Let's start with trying to reach an agreement how this is going to work and then try to discuss a schedule.

**Comment by budhrg** [comment]
> Let's start with trying to reach an agreement how this is going to work and then try to discuss a schedule.

:+1:  Sounds good @hferentschik

**Comment by praveenkumar** [comment]
We had a lot of discussion on this issue but even from minikube side it's not implemented yet. I see this one is very high priority kind of issue may be we should tackle it v1.2.0 time frame.

**Comment by hferentschik** [comment]
+1, but I also think it heavily depends on issue #126 and the ability to create multiple instances. Potentially implementing #126 can also address this issue.

**Comment by jorgemoralespou** [comment]
@hferentschik @praveenkumar As I've commented in #126, I would recommend you to raise priority of that issue (at least for planning the rest of the features taking into consideration all the changes that will be required by #126 in the future).

I'm pretty sure a lot of things will need to change, like:

- One folder per profile
- oc client downloaded per profile or globally, also per architecture or globally? #546 
- Configuration that applies only to a profile vs configuration that applies to minishift (every profile)
- Enabling addons per profile or globally
- Status of minishift instances

And probably more

**Comment by budhrg** [comment]
It looks like things would be more clear once #1304 is merged. Then, we can decide how to approach it.

**Comment by gbraad** [comment]
I think we need to break down this task in several steps:

  * [ ] provide feedback that the instance is restarting
  * [ ] provide feedback which settings are used (mostly implemented as part of #485)
    * [ ] ISO
  * [ ] ...

**Comment by gunnarmorling** [comment]
I encountered problems in that area, too (https://github.com/minishift/minishift/issues/1647), specifically about the "provide feedback for ignored settings" and "provide feedback how to make ignored settings works". A message like this would be nice:

> Specified vm-driver "abc" will be ignored as the Minishift VM already exists and has been created using driver "xyz". To recreate the VM using another driver, delete the existing one using "minishift delete".

**Comment by LalatenduMohanty** [comment]
As discussed with @minishift/minishift-dev in face2face we will fix https://github.com/minishift/minishift/issues/1622 but this issue is not relevant now as we expect user to do `minishift config set` for persistent configuration.
