### ISSUE TITLE
https://index.docker.io/v1/repositories/openshift/origin/images: Proxy Authentication Required

### ISSUE THREAD

**Issue by GolanTrevize10** [minishift/minishift#1794]
Hi I am trying to start minishift on windows 7 behind a corporate firewall using VirtualBox. I configured proxy using the env variables http_proxy and https_proxy. However I get an error when it is trying to pull the openshift image. 

minishift start --vm-driver=virtualbox
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Starting profile 'minishift'
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM .................................. OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ...
   https-proxy ... OK
   no-proxy ... OK
   routing-suffix ... OK
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   http-proxy ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
Pulling image openshift/origin:v3.6.0
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v3.6.0 image ...
   Pulling image openshift/origin:v3.6.0
FAIL
   Error: error pulling Docker image openshift/origin:v3.6.0
   Caused By:
     Error: Error while pulling image: Get https://index.docker.io/v1/repositories/openshift/origin/images: Proxy Authentication Required
Error during 'cluster up' execution: Error starting the cluster.

I don't think it is a proxy issue because it manages to download correctly the minishift image. 

My versions
minishift v1.9.0+a511b25
VirtualBox 5.2.0

**Comment by praveenkumar** [comment]
> I don't think it is a proxy issue because it manages to download correctly the minishift image.

It does a proxy issue because as per your logs it is not able to pull the images and also not able to resolve `Retrieving http://minishift.io/index.html ... FAIL`. It is able to ping `8.8.8.8` which mean network connectivity is in the VM but name resolution not working.

**Comment by GolanTrevize10** [comment]
Hi, it might be some proxy problem in the virtual machine. How can I configure proxy in the virtual machine?
The error you mentioned is related to 1628

**Comment by praveenkumar** [comment]
> How can I configure proxy in the virtual machine?

Proxy configuration should happen automatically in the VM. Even you are getting that error you can do `minishift ssh` and check the `env` where proxy should be part of it or do `docker info` which should contain proxy details.

**Comment by GolanTrevize10** [comment]
I did that but https_proxy is empty. It is not taking my Windows env variable

**Comment by GolanTrevize10** [comment]
Ok, after deleting the minishift VM and recreate it now it is working

**Comment by gbraad** [comment]
Thank you
