### ISSUE TITLE
Fix implementation of InstanceConfig (prevent delete, add InstanceState)

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1796]
The current implementation of `InstanceConfig` is used to store both configuration (`HostFolders`) and state (`OcPath`, `IsRegistered`, `IsRHELBased`). What happens is that this file gets removed on delete of the instance... to aid in the recreation of the instance using the same config, we keep configuration around.

Several things needs to happen to fix this.
  * The current `minishift.json` config file needs to live in a directory higher up in the tree, to prevent it from being deleted. Needs to be confirmed.
  * a `InstanceState` implementation needs to be added
  * The content needs to be split based on config and state information

**Comment by gbraad** [comment]
Needed for #1457

**Comment by LalatenduMohanty** [comment]
@gbraad I think config information should leave in config.jsona and state information should be in another file, may be `minishift_state.json`. May be we can move respective information to config.json and rename `minishift.json` to `minishift_state.json` (or something appropriate).

**Comment by gbraad** [comment]
It seems we have `"github.com/minishift/minishift/cmd/minishift/state"` as this is used for the InstanceDirs.

We need to take a good look at the current 'wild growth' of implementations related to state and config.

**Comment by praveenkumar** [comment]
@gbraad Right, below is what we have currently, we probably want to rethink around allinstance.json and config.json (this should only for viper config).  If we move `minishift.json` one directory up that means it is at the same level were all directories are. Do you think we should make `minishift.json` profile specific so until a profile is not deleted we always have this config file (we do need to think about our default profile which can't be removed atm)

```
$ tree ~/.minishift/
├── addons
│   ├── admin-user
[...]
├── config
│   ├── allinstances.json => This currently contain hostfolder/activeprofile details across instances.
│   └── config.json => This is used for viper related config but also now used for cache-images 
[...]
├── machines
│   ├── minishift
│   │   ├── boot2docker.iso
│   │   ├── config.json
│   │   ├── id_rsa
│   │   ├── id_rsa.pub
│   │   └── minishift.img
│   ├── minishift.json  => This is used for config which we need to user delete VM (like registration/osbase/oc-path etc...
│   ├── minishift_kubeconfig
│   ├── server-key.pem
│   └── server.pem
├── profiles
└── tmp
```

**Comment by LalatenduMohanty** [comment]
@minishift/minishift-dev we agreed to move minishift.json to minishift_state.json right?

**Comment by budhrg** [comment]
> we agreed to move minishift.json to minishift_state.json right?

Sound good to me. Use `minishift-state.json` as name though.

**Comment by praveenkumar** [comment]
@gbraad I looked a bit more in the details and as I said https://github.com/minishift/minishift/issues/1796#issuecomment-349553935 only `image-caching` info is part of `config` file which shouldn't be.

Now I am a bit confused where to put that since `allinstances.json` is something applicable across profiles and `minishift.json` applicable till user does not perform delete and `image` config doesn't fit any of those criteria. A user can set image cache details specific to profile and don't want it to vanish when deleting the VM (not profile). 

@minishift/minishift-dev  Do you folks think we need to add an additional config file for same?

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/commit/781349690090db8711a30d0f5fd3d84accc27732 #2502
