### ISSUE TITLE
CentOS CI should only run the latest job and kill the old jobs against a PR

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1801]
### Expected

CentOS CI should run only one job against one PR.

### Actual

Right now, if we force push changes to existing PR, then CentOS CI is running new job against new commit.

**Comment by LalatenduMohanty** [comment]
Basically when force push happens and a new integration test is started we should kill the old job.

**Comment by hferentschik** [comment]
My guess is that this is not possible. I would think that the required hooks to make this happen are not there. But it would be nice :-)

**Comment by budhrg** [comment]
> My guess is that this is not possible. I would think that the required hooks to make this happen are not there. 

Yes, I doubt same.

> But it would be nice :-)

Yes, it would be nice :+1:

**Comment by praveenkumar** [comment]
@budhrg Did we contacted to centos-ci admin folks if it possible at all otherwise we might just close this issue?

**Comment by budhrg** [comment]
> Did we contacted to centos-ci admin folks if it possible at all otherwise we might just close this issue?

Not yet.

@bstinsonmhk By any way this is possible in CI?

**Comment by bstinsonmhk** [comment]
https://docs.openstack.org/infra/jenkins-job-builder/triggers.html#triggers.github-pull-request

Are you looking for something like the `cancel-build-on-update` parameter?

**Comment by budhrg** [comment]
> Are you looking for something like the cancel-build-on-update parameter?

I think it is :smile: . Trying now.

**Comment by budhrg** [comment]
@LalatenduMohanty @praveenkumar @gbraad It seems `cancel-build-on-update` parameter is working. Thanks @bstinsonmhk .

See https://ci.centos.org/job/minishift-pr/3236/ which got cancelled when PR https://github.com/minishift/minishift/pull/1901 is updated. New build was https://ci.centos.org/job/minishift-pr/3237/

**Comment by LalatenduMohanty** [comment]
Thats great news @budhrg 👍

**Comment by budhrg** [comment]
We can resolve this issue @LalatenduMohanty

**Comment by LalatenduMohanty** [comment]
Thanks @budhrg
