### ISSUE TITLE
Add ability to clear a given image from the cache

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1802]
At the moment there is no way to selectively remove an image from the image cache. It's all or nothing (in fact you need to clear the whole cache). We need a way to selective delete an image, eg

    $ minishift image prune <image names>

This most likely will need changes to underlying container/images.

**Comment by praveenkumar** [comment]
This is something I would like to work on once we have a proper milestone to it.

**Comment by anjannath** [comment]
@praveenkumar since you are pre-occupied with the 3.10 work, would you like me to work on it?

**Comment by praveenkumar** [comment]
@anjannath https://github.com/minishift/minishift/pull/2336 3.10 work is mostly done and waiting for feedback mostly. I want to work on this because this is the codebase which is dark for me, implementing this feature might give some insight for this codebase.

**Comment by LalatenduMohanty** [comment]
Resolved via #2381
