### ISSUE TITLE
Add ability to force a pull of images during image export

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1803]
ATM, during an `image export` the only criteria of whether an image needs to be (re-)exported is whether there is an entry in the OCI index. Images which change (_latest_ tag) will not get updated. An option should be provided to force a re-export, eg

    $ minishift image export --validate

**Comment by budhrg** [comment]
Not sure `--validate` will convey the right message to force re-export the image.

**Comment by gbraad** [comment]
same for me; `validate` does not convey the meaning to force a re-export and actually pulling `:latest` again.
Validate to me means to 'check the validity or accuracy of the requested image`, with accuracy meaning more along the lines of the hash (to ensure the image is not corrupted).

**Comment by hferentschik** [comment]
Note the "eg". Could be "forced" (I was leaning to this initially, but it seems a bit too strong), or "re-pull" or ....

**Comment by gbraad** [comment]
`re-pull` comes closer... but likely without the dash...

**Comment by hferentschik** [comment]
Well, not quite. Since "re-pull" implies that the image gets pulled again from the Docker daemon side, but that is not necessarily the case.

**Comment by gbraad** [comment]
in that case, since it will not 're-pull' from the registry, it might be more appropriate to call it as the alternatives: `--refresh`... :-/ `--freshen`... :-s `--update` :-|

**Comment by praveenkumar** [comment]
If we check from docker side `docker pull` always checks the layers and if any layer updated it re-pull. If we want to implement the same behavior with `export` then it going to depend on the internet. So I think `--refresh` or `freshen` looks like a good option.

**Comment by jorgemoralespou** [comment]
--overwrite sounds better?

```
minishift image export --overwrite
```

**Comment by budhrg** [comment]
> minishift image export --overwrite

:+1: Sounds better

**Comment by LalatenduMohanty** [comment]
Resolved via #2436
