### ISSUE TITLE
Update developing minishift guide

### ISSUE THREAD

**Issue by jaseemabid** [minishift/minishift#1810]
The [developing minishift](https://docs.openshift.org/latest/minishift/contributing/developing.html) guide still mentions glide, which seems to have been replaced by go dep in #1507. 

Docs needs to be updated to reflect the current approach.

**Comment by budhrg** [comment]
@jaseemabid , the changes have been already there in master.
The one you are seeing is the documentation till version 1.9.0.

Once, 1.10.0 is out, it should be there.
See the master documentation here http://artifacts.ci.centos.org/minishift/minishift/docs/master/openshift-origin/latest/minishift/contributing/developing.html#install-dep.

Closing it now.

**Comment by LalatenduMohanty** [comment]
@jaseemabid the docs are already updated (in the PR which changed to deb from glide) [1] , the docs are pushed in to https://docs.openshift.org/latest/minishift once the code is released.
[1] http://artifacts.ci.centos.org/minishift/minishift/docs/master/openshift-origin/latest/minishift/contributing/developing.html
