### ISSUE TITLE
'minishift-doc' job Fails when triggered from terminal using curl

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#1814]
### Steps to reproduce

  1.  `export REPO=https://github.com/anjannath/minishift`
  2.  `export API_KEY= <you know what>`
  3.  `export BRANCH=ondemand-doc-build`
  4.  `curl -H "$(curl --user minishift:$API_KEY 'https://ci.centos.org//crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')" -X POST https://ci.centos.org/job/minishift-docs/build --user "minishift:$API_KEY" --data-urlencode json='{"parameter": [{"name":"REPO", "value":"$REPO"}, {"name":"BRANCH", "value":"$BRANCH"}]}'`

### Expected
`minishift-docs` job should successfully build the docs and publish the artifacts when triggered via terminal

### Actual
Build fails, as the `REPO` and `BRANCH` variables are not reaching centos ci.

### Logs

```
++ echo
++ cut -d/ -f4
+ REPO_OWNER=
+ perform_docs_publish '' '' minishift/docs/ondemand/-
+ REPO=https://github.com//minishift
+ git remote add remote-repo https://github.com//minishift
+ git fetch remote-repo
fatal: could not read Username for 'https://github.com': No such device or address
Connection to 172.19.3.69 closed.
+ rtn_code=128
+ [[ 128 -eq 124 ]]
+ cico node done f70c5d62
Starting new HTTP connection (1): admin.ci.centos.org
Resetting dropped connection: admin.ci.centos.org
Resetting dropped connection: admin.ci.centos.org
```
* NOTE: it works when triggered from the UI

**Comment by budhrg** [comment]
From UI - https://ci.centos.org/job/minishift-docs/34/consoleFull

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1820
