### ISSUE TITLE
Create a formatting rules for Godog features and add them to docs

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1815]
As discussed on #1692 we do not have any written rules/recommendation for step alignment, max. length of step and other Gherkin formatting which should be used in feature files. We should agree on set of rules, add them to docs and re-format the current feature files accordingly.

All aspects of formatting are open for the discussion.

**Comment by gbraad** [comment]
The current style was chosen for readability. it aligns all steps at the same level.
![image](https://user-images.githubusercontent.com/1894/33745982-1e806bc2-dbf5-11e7-9947-e1fce5c7f66b.png)
With the right tools, they are easy to examine and understand.

**Comment by amitkrout** [comment]
I searched two indentation extensions for vs code ```1.18.1```. 

1. Gherkin Indent 2.0.0 (Probably this is applied in falg.feature)
However there is a problem in parsing the feature file when it encountered ```Example``` clause. It throws ```Error Running the contributed command:'gherkin-indent.format' failed.```. See the long pending open issue https://github.com/Aravind00Kumar/gherkin-indent/issues/1 for more details.

2. Cucumber (Gherkin) Full Support 2.5.0
This format i can see a major indentation shift compare to the above one (Gherkin Indent 2.0.0). All the clauses ```Given When Then And``` fall under same indentation.

<img width="660" alt="screen shot 2017-12-10 at 10 27 44 pm" src="https://user-images.githubusercontent.com/19851115/33816511-635e7ba0-de5f-11e7-9cab-79bda03f9431.png">

@minishift/minishift-dev Any suggestions ?

**Comment by budhrg** [comment]
@agajdosi Do we still consider this issue?

**Comment by gbraad** [comment]
Too little benefit in my opinion

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by budhrg** [comment]
> Too little benefit in my opinion

I think we are good with current format.

**Comment by LalatenduMohanty** [comment]
Actually we do not have any rule about the alignment which was the original issue @agajdosi reported. I agree that this has less priority. But we should keep it open.

**Comment by agajdosi** [comment]
@LalatenduMohanty There was not any activity for a while. It seems to me that we as the community got used to the Gherkin formatting we use and that no longer there is any need for automated check of it. I am suggesting to close this.
