### ISSUE TITLE
Streamline installation instructions

### ISSUE THREAD

**Issue by robin-owen** [minishift/minishift#1817]
Currently, the installation instructions for Minishift involve using a few separate locations within the documentation (namely the installation page and the page for setting up the driver plug-in). This causes some amount of context switching for the user, as they must navigate from installation to setting up the driver plug-in and back. Considering the driver plug-in step is an expected part of the installation procedure (at least for most), I think it makes sense to include this information with the installation steps themselves.

Likewise, the installation procedure may benefit from separating it into explicit sections dedicated to _preparing_ your environment followed by the installation itself.

Addressing this issue would also assist us in maintaining the documentation both upstream and downstream. At the moment, upstream is less affected by this issue, as the installation procedure is included as part of OpenShift's page-based documentation. Downstream, this information is presented linearly, which requires manual modification of the content in order to make sense.

**Comment by praveenkumar** [comment]
@minishift/minishift-dev please go through once. If I remember correctly we did that split later to make sure installation prerequisites should be in a different section but then I also agree with @robin-owen here it's a forward-backward for first-time users. *preparing your environment followed by the installation itself*, This should be great as per my opinion.

**Comment by gbraad** [comment]
Can we create an outline of the flow?

At the moment we have two situations
  * driver is available as part of minishift
  * driver needs is externally provided and needs to be installed

Is this a point to start from?

**Comment by robin-owen** [comment]
> Is this a point to start from?

Absolutely.

By the way, at the moment, I'm looking at consolidating the documentation that we currently have both upstream and downstream. I'd like to make changes to streamline the installation instructions as much as possible and ensure that we can maintain this documentation in _both_ sets.

I'll create an overview of my thoughts on this which I will share as soon as possible.

**Comment by robin-owen** [comment]
@minishift/minishift-dev These are my current thoughts. This could certainly use a good bit of further information and exploration, so please, share your thoughts. :)

At the moment, the organization of the Getting Started section doesn't reflect the actual process of preparing a virtualization environment and installing Minishift. I'd recommend something along the lines of the following:

1. Preparing to Install Minishift
    1. Overview
    2. Prerequisites
    3. Understanding Minishift Installation
    4. Setting Up the Virtualization Environment
        1. Use the VirtualBox hypervisor
        2. Set up the KVM hypervisor
        3. Set up the xhyve hypervisor
        4. Set up the Hyper-V hypervisor
2. Installing Minishift
3. Minishift Quickstart

Note that **Setting Up the Driver Plug-in** has been replaced with **Preparing to Install Minishift**. This conveys the _idea_ behind the procedures involved. For individuals getting started with Minishift, the concept of a driver plug-in may be meaningless until the concept is introduced. By creating a **Preparing to Install Minishift** section, we explicitly state that some form of preparation will be required (this remains true even with a Minishift-provided driver plug-in). We also place this information first in the list of topics within the section -- this allows the prerequisites to be placed in their own file without negatively affecting the documentation when presented linearly.

Now, in **Preparing to Install Minishift**, we currently deal with two possibilities which must be addressed quickly:

1. The driver plug-in is provided by Minishift.
    - This is the case for the VirtualBox driver plug-in.
    - In this case, the `--vm-driver` flag or persistent configuration option must be used.
2. The driver plug-in must be installed and configured manually.
    - This is the case for KVM, xhyve, and Hyper-V.
    - All of these are the default for their respective platform.
    - Links can be provided which guide the user to the setup procedure for the hypervisor of their choice.
    - Likewise, a link can be placed at the end of each setup procedure which guides the user to the next logical step of the installation process, allowing the user to skip over procedures they do not need to personally pay attention to.

**Note:** Rather than focus on operating system platforms, perhaps we should place emphasis on the hypervisors themselves. This would result in listing VirtualBox only once instead of once per platform. The operating system is still important and should be prominently mentioned, but does not have to be the primary focus.

Beyond this, I believe the installation procedure is quite easy to follow and should not require much further editing, if any. Essentially, we want to reorganize and rewrite the procedures which must take place as prerequisites for installing Minishift.

Let me know what you think. :)

**Comment by LalatenduMohanty** [comment]
@robin-owen the plan sounds good to me. I think the trick is to arrange the steps so that it is easier for humans to follow. So I am looking forward to see how it will look. 
FYI, HyperV does not need any driver plugin installation but there are other steps required to configure the virtual switch.

**Comment by LalatenduMohanty** [comment]
@robin-owen IMO now is the good time to fix this.

**Comment by robin-owen** [comment]
@LalatenduMohanty Agreed, I'll be focusing on this directly over the next couple of days. :)

**Comment by JimTyrrell** [comment]
Some comments from a user:
Specific curated journeys for the typical OS's we are supporting.  Mixing Mac, Linux, Windows on the same page is confusing and takes up brain cycles.  For Mac noting that Safari doesn't always work and if you see an error message in the browser, you should try another browser.
- Documenting what are the default VM technologies used under the covers should be on the OS pages and how to use them.  If specific versions are required they should be documented.

For Mac OS and using this command "brew install docker-machine-driver-xhyve" and documenting that these commands need to run:
sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve

The follow commands are probably a first set of instructions to remove past installs and start with a clean environment.
minishift delete
rm -rf ~/.minishift
rm -rf ~/.kube 

Documenting the differences between minishift stop and minishift delete
Maybe a section of typical minishift commands and why you would use them.

"minishift ssh" as a command should be talked about and a few options like "docker ps" and other typical use cases should be documented.

Thank you for your time and attention.  Please let me know if you have any questions.

**Comment by JimTyrrell** [comment]
Other comments, how do I set larger VM CPU and Memory settings when running minishift with either of the Virtualization Technologies you are supporting.  Recommended typical settings would be a good idea.

**Comment by robin-owen** [comment]
@JimTyrrell Thank you for the comments and suggestions! I'm working on the installation process today, and I'll be sure to keep some of this in mind. :)

**Comment by JimTyrrell** [comment]
@robin-owen Happy to review or even work within the repo where this work is happening.

**Comment by robin-owen** [comment]
@JimTyrrell The work is currently local for me, but I should be pushing to branch `issue-1817` on my fork of this repository sometime soon in order to prepare a PR. :)

**Comment by robin-owen** [comment]
@JimTyrrell PR #2025 has been opened if you'd like to review the current progress and see what the plan is for future updates.
