### ISSUE TITLE
Minishift install error with existing ~/.kube directory

### ISSUE THREAD

**Issue by dsandersAzure** [minishift/minishift#1827]
### General information

  * Minishift version: v1.8.0 and v1.9.0 (tried both)
  * OS: Linux
  * Hypervisor: kvm
  * Reference issue: #993 

### Steps to reproduce

  1. Have existing minikube, GCP or Azure clusters managed from the machine minishift is being installed on
  2. Download minishift
  3. minishift start
 
### Expected

- Cluster starts successfully
- Able to follow the example at https://docs.openshift.org/latest/minishift/getting-started/quickstart.html

### Actual

- minishift start reports error

```
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.79:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

Error during post cluster up configuration: Error reading config file /home/{user}/.minishift/machines/minishift_kubeconfig
```

There is no minishift_kubeconfig file in the ~/.minishift/machines directory.

### Following the quickstart
The namespace issue (reference #933) appears when you try to interact with the minishift service:
```
$ minishift openshift service nodejs-ex --in-browser
Error getting valid namespaces user belongs to.: exit status 1
```

### Workaround

1. minishift stop
2. Remove ~/.minishift
3. move ~/.kube ~/.OLDkube
4. minishift delete
5. minishift start

### Recreating problem

1. minishift stop
2. remove ~/.minishift
3. move ~/.OLDkube ~/.kube
4. minishift delete
5. minishift start

### Challenge
To use minishift, I have to be able to continue using minikube and the GCP and Azure clusters I create, destory, and manage.

**Comment by praveenkumar** [comment]
@dsandersAzure Can you paste your old `~/.kube/config` file after removing tokens etc because we usually use minikube and minishift parallel and doesn't have issue might be some extra tag part of Azure config which needs to be taken care of in our codebase.

**Comment by dsandersAzure** [comment]
@praveenkumar Hi Praveen, that's going to be difficult as the config file is quite large. I think this is part of the challenge - I have been spinning up and tearing down clusters about 4 to 5 times a day (for various tests) and removing all security information from the config is going to take forever :) The file size of the config file is 172,317 bytes and I wonder if that could be related to the problem?

The only other thing I do after every teardown (they're scripted) is go back to my minikube context.

Cheers, David.

**Comment by ceridwen** [comment]
I've seen this error too, with a much smaller kubeconfig file.

**Comment by praveenkumar** [comment]
@ceridwen Can you provide that kubeconfig file so that we can parse it and check if our parser has some issue?

**Comment by ceridwen** [comment]
Unfortunately, I didn't save my .kube/config from when I saw this, and I've edited since then.  If I see it again, I'll post it here.

**Comment by praveenkumar** [comment]
@ceridwen sure, please do post if you again hit the same situation.

**Comment by indrayam** [comment]
I am facing the same error with the latest version on a Mac:
Minishift version: minishift v1.12.0+daa0943
OS: Mac
Hypervisor: virtualbox

**Comment by praveenkumar** [comment]
@indrayam Can you provide your `~/.kube/config` file, please make sure you remove all the private token before paste is on github gist or a pastebin.

**Comment by praveenkumar** [comment]
This is resolved now.
