### ISSUE TITLE
Fix regex to test minishift version in integration test

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1829]
### General information

  * Minishift version: v.1.10.0
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

Also [master build](https://ci.centos.org/job/minishift/) is failing too.

### Steps to reproduce

  1. Run integration test `make integration`

### Expected

Integration test for `cmd-version.feature` should pass. 

### Actual

Integration test for `cmd-version.feature` is failing.

### Logs

https://ci.centos.org/job/minishift/429/consoleFull

**Comment by praveenkumar** [comment]
@budhrg Commit message should be *Fix regex to test minishift version in integration test* because we do have tests for Openshift version also so better to be explicit here.

**Comment by budhrg** [comment]
> Commit message should be Fix regex to test minishift version in integration test because we do have tests for Openshift version also so better to be explicit here.

Done @praveenkumar

**Comment by LalatenduMohanty** [comment]
@budhrg  so the release job passed because the version was 1.9.0 when the integration test ran, isn't it?

**Comment by budhrg** [comment]
> so the release job passed because the version was 1.9.0 when the integration test ran, isn't it?

Yes @LalatenduMohanty , I was wondering same then realize that bump the version after test in release job.
