### ISSUE TITLE
Use consistent format to show command in the output of any minishift command

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1833]
### General information

As reference to this https://github.com/minishift/minishift/pull/1731#issuecomment-350985247, we found that during the output of minishift command, we are not consistent in showing command.

See below:
1. Using single quote:
```
$ minishift stop -h
Stops the running local OpenShift cluster. This command stops the Minishift
VM but does not delete any associated files. To start the cluster again, use the 'minishift start' command.
[...]
```

2. Use back tick:
```
$ minishift addon apply
You must specify an add-on name. Run `minishift addons list` to view installed add-ons.
```

Let's decide the format and update all of its occurrences.

**Comment by praveenkumar** [comment]
I will also go with backticks in this case because this is part of messages so not going to interpret as commands.

**Comment by LalatenduMohanty** [comment]
We have used single quotes for giving importance to particular words.

```
$ minishift profile set hello
Profile 'hello' set as active profile.

$ minishift docker-env
Running this command requires an existing 'minishift' VM, but no VM is defined.
```

**Comment by gbraad** [comment]
> We have used single quotes for giving importance to particular words.

Which is confusing, as a command is something to be emphasized.

**Comment by bhavin192** [comment]
I will work on this.

**Comment by bhavin192** [comment]
> We have used single quotes for giving importance to particular words.

@LalatenduMohanty I think single quotes for the word `'hello'` makes sense, but for the second command we can remove single quotes from minishift

**Comment by LalatenduMohanty** [comment]
> Which is confusing, as a command is something to be emphasized.

@gbraad  Are you suggesting that for both commands and words  we should use single quotes?

**Comment by LalatenduMohanty** [comment]
> Like this way, we have to decide for every command, every output.

-1. That's not the right to approach this IMO. Because that would lead to more disagreements when code will get reviewed. Lets decide what we want to do then apply it to the code. The initial decision might take time but once we have a simple rule we can apply it to  code.  For example we can just decide to use single quotes to words and commands both and then it is pretty easy to do the change and review.

**Comment by LalatenduMohanty** [comment]
As discussed with @minishift/minishift-dev @robin-owen , we agreed that we will use single quotes i.e. `'` for both commands and to give importance to words in the output of `minishift` command output.

**Comment by budhrg** [comment]
> we agreed that we will use single quotes

+1

**Comment by bhavin192** [comment]
At some places there is output like, 
```go
fmt.Errorf("Error occured while creating mountpoint. %s", err)
```
Should this `err` have single quotes?

**Comment by budhrg** [comment]
> Should this err have single quotes?

No
