### ISSUE TITLE
Test compatibility with Windows SSH client

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1836]
### General information

  * Minishift version: any
  * OS: Windows
  * Hypervisor: Hyper-V / VirtualBox

Compatility needs to be tested with the Windows SSH beta feature. This will be an option for later versions of Windows 10; https://www.servethehome.com/say-farewell-putty-microsoft-adds-openssh-client-windows-10/

**Comment by anjannath** [comment]
Did we not discuss about Documenting the SSH clients that works on windows around this issue? But it seems it was originally meant to test the windows SSH client.

**Comment by jahpola** [comment]
As that Windows SSH beta(or inside FCU) only supports ed25519 for now - it won't work. See #1943 for more details.
