### ISSUE TITLE
Getting import logs error on first time start when caching enabled

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1837]
### General information

  * Minishift version: 1.10.0
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. Enable image caching with `minishift config set image-caching true`
  2. Do `minishift start`

### Expected
Should not get any import logs error on first time `minishift start`

### Actual
Getting weird import logs error on first time `minishift start`

### Logs

```
-- Checking available disk space ... 0% used OK
   Importing openshift/origin:v3.6.0  FAIL
   Importing openshift/origin-docker-registry:v3.6.0  FAIL
   Importing openshift/origin-haproxy-router:v3.6.0  FAIL
  WARN: Import of cached images failed. Continuing without importing images. Error: Unable to import image 'openshift/origin:v3.6.0' because it is not available in the local cache.
Unable to import image 'openshift/origin-docker-registry:v3.6.0' because it is not available in the local cache.
Unable to import image 'openshift/origin-haproxy-router:v3.6.0' because it is not available in the local cache. 
```

**Comment by LalatenduMohanty** [comment]
Resolved via #1839
