### ISSUE TITLE
Unable to start minishift - wsarecv: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by MarkRx** [minishift/minishift#184]
I am unable to start openshift using minishift.

This could be related to https://github.com/docker/machine/issues/2318.

minishift version: 0.9.0
virtualbox 5.1.4r110228
Windows 7
McAfee Enterprise

> >minishift start
> Starting local OpenShift cluster...
> E1208 10:16:54.668390   40332 start.go:92] Error starting host: Error creating. Error with pre-create check: "read tcp 127.0.0.1:57484->127.0.0.1:57481: wsarecv: An existing connection was forcibly closed by the remote host.". Retrying.
> E1208 10:16:58.183390   40332 start.go:92] Error starting host: Error creating. Error with pre-create check: "read tcp 127.0.0.1:57492->127.0.0.1:57491: wsarecv: An existing connection was forcibly closed by the remote host.". Retrying.
> E1208 10:17:01.630390   40332 start.go:92] Error starting host: Error creating. Error with pre-create check: "read tcp 127.0.0.1:57499->127.0.0.1:57498: wsarecv: An existing connection was forcibly closed by the remote host.". Retrying.
> E1208 10:17:01.630390   40332 start.go:98] Error starting host:  Error creating. Error with pre-create check: "read tcp 127.0.0.1:57484->127.0.0.1:57481: wsarecv: An existing connection was forcibly closed by the remote host."
> Error creating. Error with pre-create check: "read tcp 127.0.0.1:57492->127.0.0.1:57491: wsarecv: An existing connection was forcibly closed by the remote host."
> Error creating. Error with pre-create check: "read tcp 127.0.0.1:57499->127.0.0.1:57498: wsarecv: An existing connection was forcibly closed by the remote host."

**Comment by budhrg** [comment]
Duplicate of #159

**Comment by MarkRx** [comment]
Is it? The issue on #159 seems to be this:

> E1208 19:03:22.253767     476 start.go:92] Error starting host: Error getting state for host: machine does not exist. Retrying.

**Comment by budhrg** [comment]
@MarkRx Could you give us the debug logs as

`minishift start -v 5 --show-libmachine-logs`

**Comment by MarkRx** [comment]
It was defaulting to HyperV. Adding --vm-driver=virtualbox gives me a network error that I will look into now.

> VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #3' (VERR_SUPDRV_COMPONENT_NOT_FOUND).
> VBoxManage.exe: error: Failed to attach the network LUN (VERR_SUPDRV_COMPONENT_NOT_FOUND)
> VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
> 
> Details: 00:00:01.018664 Power up failed (vrc=VERR_SUPDRV_COMPONENT_NOT_FOUND, rc=E_FAIL (0X80004005)). Retrying.
> E1208 10:59:00.705183   13688 start.go:92] Error starting host: Error starting stopped host: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minishift --type headless failed:

> minishift start -v 5 --show-libmachine-logs

> Starting local OpenShift cluster...
> Found binary path at C:\home\bin\minishift.exe
> Launching plugin server for driver hyperv
> Plugin server listening at address 127.0.0.1:60622
> () Calling .GetVersion
> Using API Version  1
> () Calling .SetConfigRaw
> () Calling .GetMachineName
> (minishift) Calling .GetMachineName
> (minishift) Calling .DriverName
> Running pre-create checks...
> (minishift) Calling .PreCreateCheck
> (minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Command Get-VM).ModuleName
> (minishift) DBG | [stdout =====>] : 
> (minishift) DBG | [stderr =====>] : Get-Command : The term 'Get-VM' is not recognized as the name of a cmdlet, function, script file, or op
> (minishift) DBG | erable program. Check the spelling of the name, or if a path was included, verify that the path is corr
> (minishift) DBG | ect and try again.
> (minishift) DBG | At line:1 char:14
> (minishift) DBG | + @(Get-Command <<<<  Get-VM).ModuleName
> (minishift) DBG |     + CategoryInfo          : ObjectNotFound: (Get-VM:String) [Get-Command], CommandNotFoundException
> (minishift) DBG |     + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
> (minishift) DBG |  
> (minishift) DBG | 
> (minishift) DBG | panic: runtime error: index out of range
> (minishift) DBG | 
> (minishift) DBG | goroutine 16 [running]:
> (minishift) DBG | panic(0x1122c60, 0xc04200e060)
> (minishift) DBG | 	/usr/local/go/src/runtime/panic.go:500 +0x1af
> (minishift) DBG | github.com/jimmidyson/minishift/vendor/github.com/docker/machine/drivers/hyperv.hypervAvailable(0x6e6038, 0x106bce0)
> (minishift) DBG | 	/home/jdyson/go/src/github.com/jimmidyson/minishift/_gopath/src/github.com/jimmidyson/minishift/vendor/github.com/docker/machine/drivers/hyperv/powershell.go:64 +0x10c
> (minishift) DBG | github.com/jimmidyson/minishift/vendor/github.com/docker/machine/drivers/hyperv.(*Driver).PreCreateCheck(0xc0422fa540, 0xc042250ce0, 0xc042250d40)
> (minishift) DBG | 	/home/jdyson/go/src/github.com/jimmidyson/minishift/_gopath/src/github.com/jimmidyson/minishift/vendor/github.com/docker/machine/drivers/hyperv/hyperv.go:164 +0x3d
> (minishift) DBG | github.com/jimmidyson/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).PreCreateCheck(0xc0422610a0, 0x43c6208, 0x43c6208, 0x0, 0x0)
> (minishift) DBG | 	/home/jdyson/go/src/github.com/jimmidyson/minishift/_gopath/src/github.com/jimmidyson/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:201 +0x3d
> (minishift) DBG | reflect.Value.call(0xc0422fa660, 0xc042118230, 0x13, 0x12ad9a8, 0x4, 0xc04240fed0, 0x3, 0x3, 0xc04200df60, 0x0, ...)
> (minishift) DBG | 	/usr/local/go/src/reflect/value.go:434 +0x5cf
> (minishift) DBG | reflect.Value.Call(0xc0422fa660, 0xc042118230, 0x13, 0xc04240fed0, 0x3, 0x3, 0xc042113a70, 0x0, 0x0)
> (minishift) DBG | 	/usr/local/go/src/reflect/value.go:302 +0xab
> (minishift) DBG | net/rpc.(*service).call(0xc042122c80, 0xc04200df40, 0xc0422e01e8, 0xc042125b00, 0xc042296e20, 0x106bce0, 0x43c6208, 0x16, 0x106bce0, 0x43c6208, ...)
> (minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:383 +0x14f
> (minishift) DBG | created by net/rpc.(*Server).ServeCodec
> (minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:477 +0x428
> E1208 10:55:42.370020   38816 start.go:92] Error starting host: Error creating. Error with pre-create check: "read tcp 127.0.0.1:60623->127.0.0.1:60622: wsarecv: An existing connection was forcibly closed by the remote host.". Retrying.
> Found binary path at C:\home\bin\minishift.exe
> Launching plugin server for driver hyperv
> Plugin server listening at address 127.0.0.1:60628
> () Calling .GetVersion
> Using API Version  1
> () Calling .SetConfigRaw
> () Calling .GetMachineName
> (minishift) Calling .GetMachineName
> (minishift) Calling .DriverName
> Running pre-create checks...
> (minishift) Calling .PreCreateCheck
> (minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Command Get-VM).ModuleName
> (minishift) DBG | [stdout =====>] : 
> (minishift) DBG | [stderr =====>] : Get-Command : The term 'Get-VM' is not recognized as the name of a cmdlet, function, script file, or op
> (minishift) DBG | erable program. Check the spelling of the name, or if a path was included, verify that the path is corr
> (minishift) DBG | ect and try again.
> (minishift) DBG | At line:1 char:14
> (minishift) DBG | + @(Get-Command <<<<  Get-VM).ModuleName
> (minishift) DBG |     + CategoryInfo          : ObjectNotFound: (Get-VM:String) [Get-Command], CommandNotFoundException
> (minishift) DBG |     + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
> (minishift) DBG |  
> (minishift) DBG | 
> (minishift) DBG | panic: runtime error: index out of range
> (minishift) DBG | 
> (minishift) DBG | goroutine 22 [running]:
> (minishift) DBG | panic(0x1122c60, 0xc04200e060)
> (minishift) DBG | 	/usr/local/go/src/runtime/panic.go:500 +0x1af
> (minishift) DBG | github.com/jimmidyson/minishift/vendor/github.com/docker/machine/drivers/hyperv.hypervAvailable(0x6e6038, 0x106bce0)
> (minishift) DBG | 	/home/jdyson/go/src/github.com/jimmidyson/minishift/_gopath/src/github.com/jimmidyson/minishift/vendor/github.com/docker/machine/drivers/hyperv/powershell.go:64 +0x10c
> (minishift) DBG | github.com/jimmidyson/minishift/vendor/github.com/docker/machine/drivers/hyperv.(*Driver).PreCreateCheck(0xc04212c540, 0xc04221d640, 0xc04221d6a0)
> (minishift) DBG | 	/home/jdyson/go/src/github.com/jimmidyson/minishift/_gopath/src/github.com/jimmidyson/minishift/vendor/github.com/docker/machine/drivers/hyperv/hyperv.go:164 +0x3d
> (minishift) DBG | github.com/jimmidyson/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).PreCreateCheck(0xc042225a40, 0x43c6208, 0x43c6208, 0x0, 0x0)
> (minishift) DBG | 	/home/jdyson/go/src/github.com/jimmidyson/minishift/_gopath/src/github.com/jimmidyson/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:201 +0x3d
> (minishift) DBG | reflect.Value.call(0xc04212c660, 0xc04211c220, 0x13, 0x12ad9a8, 0x4, 0xc042083ed0, 0x3, 0x3, 0xc042120160, 0x0, ...)
> (minishift) DBG | 	/usr/local/go/src/reflect/value.go:434 +0x5cf
> (minishift) DBG | reflect.Value.Call(0xc04212c660, 0xc04211c220, 0x13, 0xc042083ed0, 0x3, 0x3, 0xc0421981e0, 0x0, 0x0)
> (minishift) DBG | 	/usr/local/go/src/reflect/value.go:302 +0xab
> (minishift) DBG | net/rpc.(*service).call(0xc04215f080, 0xc042120140, 0xc0421e2078, 0xc0423f7b80, 0xc04221d2e0, 0x106bce0, 0x43c6208, 0x16, 0x106bce0, 0x43c6208, ...)
> (minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:383 +0x14f
> (minishift) DBG | created by net/rpc.(*Server).ServeCodec
> (minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:477 +0x428
> Wrapper Docker Machine process exiting due to closed plugin server (connection is shut down)
> E1208 10:55:45.889372   38816 start.go:92] Error starting host: Error creating. Error with pre-create check: "read tcp 127.0.0.1:60629->127.0.0.1:60628: wsarecv: An existing connection was forcibly closed by the remote host.". Retrying.
> Found binary path at C:\home\bin\minishift.exe
> Launching plugin server for driver hyperv
> Plugin server listening at address 127.0.0.1:60639
> () Calling .GetVersion
> Using API Version  1
> () Calling .SetConfigRaw
> () Calling .GetMachineName
> (minishift) Calling .GetMachineName
> (minishift) Calling .DriverName
> Running pre-create checks...
> (minishift) Calling .PreCreateCheck
> (minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Command Get-VM).ModuleName
> (minishift) DBG | [stdout =====>] : 
> (minishift) DBG | [stderr =====>] : Get-Command : The term 'Get-VM' is not recognized as the name of a cmdlet, function, script file, or op
> (minishift) DBG | erable program. Check the spelling of the name, or if a path was included, verify that the path is corr
> (minishift) DBG | ect and try again.
> (minishift) DBG | At line:1 char:14
> (minishift) DBG | + @(Get-Command <<<<  Get-VM).ModuleName
> (minishift) DBG |     + CategoryInfo          : ObjectNotFound: (Get-VM:String) [Get-Command], CommandNotFoundException
> (minishift) DBG |     + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
> (minishift) DBG |  
> (minishift) DBG | 
> (minishift) DBG | panic: runtime error: index out of range
> (minishift) DBG | 
> (minishift) DBG | goroutine 53 [running]:
> (minishift) DBG | panic(0x1122c60, 0xc04200e060)
> (minishift) DBG | 	/usr/local/go/src/runtime/panic.go:500 +0x1af
> (minishift) DBG | github.com/jimmidyson/minishift/vendor/github.com/docker/machine/drivers/hyperv.hypervAvailable(0x6e6038, 0x106bce0)
> (minishift) DBG | 	/home/jdyson/go/src/github.com/jimmidyson/minishift/_gopath/src/github.com/jimmidyson/minishift/vendor/github.com/docker/machine/drivers/hyperv/powershell.go:64 +0x10c
> (minishift) DBG | github.com/jimmidyson/minishift/vendor/github.com/docker/machine/drivers/hyperv.(*Driver).PreCreateCheck(0xc0421ac540, 0xc04214ac60, 0xc04214ac80)
> (minishift) DBG | 	/home/jdyson/go/src/github.com/jimmidyson/minishift/_gopath/src/github.com/jimmidyson/minishift/vendor/github.com/docker/machine/drivers/hyperv/hyperv.go:164 +0x3d
> (minishift) DBG | github.com/jimmidyson/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).PreCreateCheck(0xc0421ca280, 0x43c6208, 0x43c6208, 0x0, 0x0)
> (minishift) DBG | 	/home/jdyson/go/src/github.com/jimmidyson/minishift/_gopath/src/github.com/jimmidyson/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:201 +0x3d
> (minishift) DBG | reflect.Value.call(0xc0421ac660, 0xc042116228, 0x13, 0x12ad9a8, 0x4, 0xc042311ed0, 0x3, 0x3, 0xc04200df20, 0x0, ...)
> (minishift) DBG | 	/usr/local/go/src/reflect/value.go:434 +0x5cf
> (minishift) DBG | reflect.Value.Call(0xc0421ac660, 0xc042116228, 0x13, 0xc042311ed0, 0x3, 0x3, 0xc0423a2210, 0x0, 0x0)
> (minishift) DBG | 	/usr/local/go/src/reflect/value.go:302 +0xab
> (minishift) DBG | net/rpc.(*service).call(0xc04211acc0, 0xc04200df00, 0xc042184078, 0xc042125b80, 0xc04214a9e0, 0x106bce0, 0x43c6208, 0x16, 0x106bce0, 0x43c6208, ...)
> (minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:383 +0x14f
> (minishift) DBG | created by net/rpc.(*Server).ServeCodec
> (minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:477 +0x428
> Wrapper Docker Machine process exiting due to closed plugin server (connection is shut down)
> E1208 10:55:49.350718   38816 start.go:92] Error starting host: Error creating. Error with pre-create check: "read tcp 127.0.0.1:60640->127.0.0.1:60639: wsarecv: An existing connection was forcibly closed by the remote host.". Retrying.
> E1208 10:55:49.350718   38816 start.go:98] Error starting host:  Error creating. Error with pre-create check: "read tcp 127.0.0.1:60623->127.0.0.1:60622: wsarecv: An existing connection was forcibly closed by the remote host."
> Error creating. Error with pre-create check: "read tcp 127.0.0.1:60629->127.0.0.1:60628: wsarecv: An existing connection was forcibly closed by the remote host."
> Error creating. Error with pre-create check: "read tcp 127.0.0.1:60640->127.0.0.1:60639: wsarecv: An existing connection was forcibly closed by the remote host."
>

**Comment by MarkRx** [comment]
Got it working. I had tried 5.1.10 to see if it would fix the issue and must have improperly installed it. When the popup came up to install the network drivers I might have accidentally hit 'don't install' since it was on the right most button. I reverted back to 5.1.4 and it seems to have started up correctly.

**Comment by budhrg** [comment]
@MarkRx Good to know that its working for you :+1:
