### ISSUE TITLE
.DS_Store: not a directory message showed with command "profile list"

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#1840]
Minihisft version : 1.10
OS : Macos

```
minishift profile list
- .DS_Store     Error getting the VM status: stat /Users/dabou/.minishift/profiles/.DS_Store/machines/.DS_Store: not a directory
```

**Comment by gbraad** [comment]
This file is created when you use the Finder on a folder and it holds metadata about the contents and thumbnails for images.

We should probably just do a `^\.` for ignore. This means hidden folders are ignored.

**Comment by LalatenduMohanty** [comment]
http://osxdaily.com/2009/12/31/what-is-a-ds_store-file/
I think the file got created while @cmoulliard was doing some file operation , but we can fix `minishift` to ignore this. Actually minishift should ignore files in ~/.minishift/profiles, it should only care about directories

**Comment by anjannath** [comment]
If we add a check for directory in this for loop we can fix this issue, or we can check for both directory and names not starting with a `.`

https://github.com/minishift/minishift/blob/master/pkg/minishift/profile/profile.go#L49-L53

```go
for _, f := range files {
		if !filehelper.IsDirectory(f.Name()){
			continue
		}
		profileList = append(profileList, f.Name())
	}
	return profileList
} 
```
