### ISSUE TITLE
Minishift 1.10.0 can not provision OpenShift v3.6.1

### ISSUE THREAD

**Issue by paoloantinori** [minishift/minishift#1841]
### General information

  * Minishift version: `minishift v1.10.0+10461c6`
  * OS: `Linux `
  * Hypervisor: `KVM `

### Steps to reproduce

  1. `minishift start --memory 2048 --cpus 2 --show-libmachine-logs  --openshift-version v3.6.1  --alsologtostderr`
  2. 
  3. 
  4. 

### Expected
Minishift being able to handle `v3.6.1` correctly

### Actual
```
FAIL
   Error: could not start OpenShift container "origin"
   Details:
     No log available from "origin" container

Error during 'cluster up' execution: Error starting the cluster.
```

### Logs

The issue reported in logs is very specific and it's related to the lack of an attribute:

```
F1213 11:39:01.486397    2973 start_allinone.go:99] Server could not start: Couldn't init admission plugin "openshift.io/ImagePolicy": [openshift.io/ImagePolicy.resolutionRules[0].policy: Required value: a policy must be specified for this resource, openshift.io/ImagePolicy.resolutionRules[1].policy: Required value: a policy must be specified for this resource, openshift.io/ImagePolicy.resolutionRules[2].policy: Required value: a policy must be specified for this resource, openshift.io/ImagePolicy.resolutionRules[3].policy: Required value: a policy must be specified for this resource, openshift.io/ImagePolicy.resolutionRules[4].policy: Required value: a policy must be specified for this resource]
```

I'm trying to patch config to put those required values there with this command:

```
JSON='{"admissionConfig":{"pluginConfig":{"openshift.io/ImagePolicy":{"configuration":{"resolutionRules":[{"localNames":true,"policy":"AttemptRewrite"}]}}}}}'
minishift openshift config set --patch $JSON --target master
```

But that fails since `origin` container is stopped.

Now, I'm not sure that my patch is all I need to make 3.6.1 to work, anyhow I'm looking for a workflow that can allow me to patch master configuration before starting it, so that I can accomplish something lik what's defined in this scenario.

**Comment by LalatenduMohanty** [comment]
@paoloantinori It looks like a bug in Minishift we introduced recently. We will fix it asap. Till then 
you can do following manual steps to get it working.

* Download the oc client for Linux from https://github.com/openshift/origin/releases/tag/v3.6.1
 * Extract the oc binary and replace the existing oc binary with the new one ~/.minishift/cache/oc/v3.6.0/linux/
 * minishift start  --openshift-version v3.6.1

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/issues/1841

**Comment by paoloantinori** [comment]
thanks. actually the link to the fix should be: https://github.com/minishift/minishift/pull/1845
