### ISSUE TITLE
Allow multiple network configuration files for CentOS/RHEL ISO

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1854]
Related to issue #1457 and #1513 

https://github.com/minishift/minishift-centos-iso/pull/179

**Comment by gbraad** [comment]
@minishift/minishift-dev this needs to be included in the next release

**Comment by LalatenduMohanty** [comment]
As discussed with @gbraad I am closing this issue as this does not need any code change from Minishift side. Also updated #1513 description to reflect dependency on https://github.com/minishift/minishift-centos-iso/pull/179
