### ISSUE TITLE
`minishift config unset` does not return error message if an invalid property name is passed

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#1858]
### General information

  * Minishift version: master
  * OS: All (Linux / macOS / Windows) 
  * Hypervisor: All (KVM / xhyve / Hyper-V / VirtualBox)

### Steps to reproduce

  1. `minishift config unset foo`

### Expected
An error message saying foo is not a valid property or the syntax for `minishift config unset` command

### Actual
nothing happens, and the user has no idea if the value was unset

**Comment by LalatenduMohanty** [comment]
Does this look ok
```
$ minishift config unset dummyconfig
Cannot find property name dummyconfig
```

**Comment by anjannath** [comment]
Yes, this looks fine, also the `minidhift config set` command doesn't show a message on succes, but i am a bit unsure if we want to show a message saying something like `iso url property successfuly set`. I feel it might be an overkill. @LalatenduMohanty WDYT?

**Comment by LalatenduMohanty** [comment]
@anjannath yeah we can print success message.

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/commit/fe75c68dd7e547c8739997f762b3963caef9cb1c #1903
