### ISSUE TITLE
minishift version should ignore profile details

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1861]
* Minishift version: current master
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1.  Delete any running VM
  2.  rm -fr ~/.minishift
  3.  minishift version

### Expected
minishift v1.10.0+77422c5c

### Actual
Profile: minishift doesn't exist, Use `minishift profile set minishift` or `minishift start --profile minishift` to create

**Comment by LalatenduMohanty** [comment]
Resolved via #1862
