### ISSUE TITLE
Unnecessary property 'cache-images' is listed in config view 

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1874]
### General information

  * Minishift version: All
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. `minishift config | grep cache-images`

### Expected

Should not be listed.

### Actual

Not sure if I remember it's usage but it seems to be unnecessary property listed.

**Comment by budhrg** [comment]
This is what user will assume
```
$ minishift config | grep cache-images
 * cache-images

# This implies I can set images to be cached before start with this property. 
# Obviously we have image "minishift image cache-config add" to do it but
# this property 'cache-images' listed as part of config help will create confusion 
$ minishift config set cache-images openshift/origin:v3.6.0

$ minishift config view
# Empty
```

**Comment by anjannath** [comment]
So after reading the docs, what i understand is `cache-images` property is used to transparently persist the names of the OpenShift images, once implicit caching is enabled.

Also the property is used from `minishift image cache-config` to store the names of images.

```
$ minishift image cache-config view
true 
# true should not be shown here

$ minishift image cache-config add busybox:latest

$ minishift image cache-config view              
busybox:latest
true
# again the value for the property is shown

$ minishift config view cache-config
- image-caching        : true

$ minishift config view image-caching
- image-caching        : true

$ minishift config view cache-images 
- image-caching        : true
```

**Comment by LalatenduMohanty** [comment]
@budhrg Right,  it should vot show up only in `minishift config` usage. We expect the user to add images  to cache configuration through `minishift images cache-config add` and view it through `minishift images cache-config view`.

**Comment by LalatenduMohanty** [comment]
> $ minishift image cache-config view true # true should not be shown here

@anjannath I can not reproduce `true` in the output.

**Comment by anjannath** [comment]
@LalatenduMohanty Have you set the property `image-caching` to true?

**Comment by praveenkumar** [comment]
If you look the occurrence of https://github.com/minishift/minishift/blob/master/cmd/minishift/cmd/config/config.go#L100 you will notice this is used as a variable (not more than that) so to remove from the list we just need to set `isApply` as false and good to go.
