### ISSUE TITLE
Preflight check: For corporate Windows users, Preflight Check for Hyper-V fails, when primary domain cannot be reached.

### ISSUE THREAD

**Issue by 3wh** [minishift/minishift#1882]
# General information
- Minishift version: 1.11.0 (1.11.0-windows-amd64)
- OS: Windows (10.0.15063)
- Hypervisor: Hyper-V
- Powershell version: 5.1.15063.726
- Local Administrator: yes

# Specific context
This problem ONLY occurs for corporate Winows users, when the user is NOT connected to the corporate network (primary domain cannot be reached).
Local Users are NOT affected.

# Steps to reproduce
1. Be detached from the corporate network
1. Setup minishift for Hyper-V as described on https://docs.openshift.org/latest/minishift/getting-started/installing.html & https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html#hyper-v-driver
    - including adding the user to the Hyper-V administrators group `([adsi]"WinNT://./Hyper-V Administrators,group").Add("WinNT://$env:UserDomain/$env:Username,user")`
1. Start minishift (`.\minishift.exe start`)

# Expected
The Preflight check correctly identifies my user as part of the Hyper-V administrators group.
Minishift starts.
# Actual
Minishift fails to start
```
PS C:\Users\kavn\Downloads\minishift-1.11.0-windows-amd64> .\minishift.exe start
-- Starting profile 'minishift'
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... OK
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... FAIL
   See the 'Setting Up the Driver Plug-in' topic (https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html) for more information
```
# Caused by
This problem is caused by the powershell command executed by the preflight check (Line 377), as this powershell validation relies on network connectivity to the primary domain or AD-server.
https://github.com/minishift/minishift/blob/44599174664e8d7afa2e5e796a509b7ee4e1f694/cmd/minishift/cmd/start_preflight.go#L377

```
PS C:\WINDOWS\system32> @([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole("S-1-5-32-578")
Exception calling "IsInRole" with "1" argument(s): "The trust relationship between this workstation and the primary domain failed.
"
At line:1 char:1
+ @([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIde ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SystemException
```

**Comment by anjannath** [comment]
For now you can skip this check by setting `skip-check-hyperv` to true.

`$ minishift config set skip-check-hyperv-driver true`

/cc @gbraad

**Comment by gbraad** [comment]
This actual error is usually a larger problem, such as being out of sync with the Domain information.

However, we can verify the content of the error message and instead give a warning...

**Comment by gbraad** [comment]
@anjannath this needs to be fixed. maybe by setting this as WARN by default... and checking for the error message content? ref: https://github.com/minishift/minishift/issues/1987#issue-295091070

**Comment by gbraad** [comment]
Or ...
```powershell
if ((Get-WMIObject Win32_ComputerSystem).PartOfDomain -eq $true) {
   # maybe react different when member of a domain
}
```

**Comment by anjannath** [comment]
@gbraad Awesome.. now we can detect if we need to set the check as WARN, if the user is part of domain we can set it as WARN.

**Comment by anjannath** [comment]
@3wh  Could try this minishift [binary](https://github.com/anjannath/minishift/releases/download/v1.12.0/minishift.exe) its from my repo, and see if you can successfuly start minishift?

/cc @itscaro

**Comment by itscaro** [comment]
@anjannath Works for me

```
-- Starting profile 'minishift'
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... OK
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ... OK
-- Checking if user is in a Domain ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... FAIL
   See the 'Setting Up the Driver Plug-in' topic (https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html) for more information
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    4
   Disk size: 20 GB
-- Starting Minishift VM ......
```

**Comment by gbraad** [comment]
Better not to show FAIL and continue, but have it show WARN.

**Comment by anjannath** [comment]
Thanks @itscaro for trying it out. @gbraad will do and send a PR

**Comment by anjannath** [comment]
@itscaro PTAL at [minishift#2050/comment](https://github.com/minishift/minishift/pull/2050#issuecomment-366978109)

**Comment by itscaro** [comment]
I can but the message is not what I expected, it says `OK`:

```
-- Checking if user is a member of the Hyper-V Administrators group ... OK
```

**Comment by anjannath** [comment]
Thanks a lot @itscaro :)
