### ISSUE TITLE
minishift start with origin v3.7.0 and metrics enabled failed to run metrics itself.

### ISSUE THREAD

**Issue by eliu** [minishift/minishift#1886]
### General information

  * Minishift version:  minishift v1.11.0+4459917
  * OS: macOS
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. run `minishift start --openshift-version v3.7.0 --metrics`
  2. Enable cluster admin role: `oc adm policy add-cluster-role-to-user cluster-admin admin`
  3. Open web console using `admin` and switch to `openshift-infra` project
  4. View events and get the following error message:

```
Failed to pull image "openshift/origin-ansible:v3.7.0": rpc error: code = 2 desc = Tag v3.7.0 not found in repository docker.io/openshift/origin-ansible
```

*the minishift is trying to find `openshift/origin-ansible:v3.7.0` but there's no such tag on docker hub. only `v3.7` tag can be found there.*

### Expected
Metrics can be enabled and running normally.

### Actual
Metrics failed to run and ends with no image found exception.

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@eliu Looks like the way it tagged as v3.7 https://hub.docker.com/r/openshift/origin-ansible/tags/ can you please delete existing and try again?

```
minishift start --openshift-version v3.7 --metrics 
```

**Comment by eliu** [comment]
@praveenkumar that version format is not working actually:
```
$ minishift start --metrics --openshift-version v3.7
-- Starting profile 'minishift'
Invalid version format 'v3.7': No Major.Minor.Patch elements found
```

**Comment by praveenkumar** [comment]
> that version format is not working actually:

@eliu my bad, give us some time to provide a better alternative.

**Comment by praveenkumar** [comment]
Following is coming from origin logs. 

```
E0104 12:25:31.972781    2823 pod_workers.go:186] Error syncing pod 9515b034-f149-11e7-a25a-1e1ca437b2e5 ("openshift-ansible-metrics-job-59w4l_openshift-infra(9515b034-f149-11e7-a25a-1e1ca437b2e5)"), skipping: failed to "StartContainer" for "openshift-ansible-metrics-job" with ImagePullBackOff: "Back-off pulling image \"openshift/origin-ansible:v3.7.0\""
```

**Comment by praveenkumar** [comment]
@eliu looks like this is the issue from openshift/origin side and we tried manually `oc cluster up` along with `metrics` flag and got the same error. We filled issue https://github.com/openshift/origin/issues/17986 to track.

**Comment by praveenkumar** [comment]
@eliu this in now fix in upstream can you please try and verify. If it fixed for you then please close this isuse.

**Comment by eliu** [comment]
hi @praveenkumar that error message is now faded away and the metrics image is properly pulled successfully. however, the metrics seems not to work normally. 
```
An error occurred getting metrics for container openshift-ansible-metrics-job from 
https://hawkular-metrics-openshift-infra.192.168.99.100.nip.io/hawkular/metrics.
```
the address above refused to connect.

Should I open another issue for tracking that?

**Comment by jorgemoralespou** [comment]
Metrics and logging works for me, but memory requirements if you enable both are high. They failed to start on a 8GB VM.
![image](https://user-images.githubusercontent.com/78350/35093738-869b8a3e-fc43-11e7-84ec-651e65a6401f.png)


![image](https://user-images.githubusercontent.com/78350/35093785-a3ebf1fa-fc43-11e7-8c3c-3b1aba185897.png)

**Comment by eliu** [comment]
Keeping running for a while and I found hawkular-metrics also got warning of `Insufficient memory`.
I'll try enlarge the memory size against 2 GB by default. Will update later ...

**Comment by eliu** [comment]
@praveenkumar the metrics now works by specifying memory size to **4 GB** after checking the comments by @jorgemoralespou . I'll close this issue since it is resolved and thanks everyone for help.
