### ISSUE TITLE
Update profile tests

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1889]
Update profile tests to work for both upstream and downstream. 

See https://issues.jboss.org/browse/CDK-234.

```
# In profile.feature
{code}
Scenario: As user, I can apply independent settings in profile 'foo'
[...]    
Then stdout should match "<nil>"                                          # integration_test.go:677 -> commandReturnShouldMatchRegex
    Output did not match. Expected: '<nil>', Actual: '4096
```
And
```
Scenario: As user, I can execute a command against a non active profile
[...]    
And stdout should contain                                                                   # integration_test.go:649 -> commandReturnShouldContainContent
      """
      Stopping local OpenShift cluster...
      Cluster stopped.
      """
    Output did not match. Expected: 'Stopping local OpenShift cluster...
Cluster stopped.', Actual: 'Stopping local OpenShift cluster...
Unregistering machine
Cluster stopped.
'
```

Here, we found in `profile.feature`, two test cases are related to minishift only. 
We should search other test cases and tag them `@minishift-only` to avoid failure in downstream.

**Comment by agajdosi** [comment]
We should however focus on tagging `@minishift-only` only in inevitable cases, meaning that some longer scenarios has to be split or edited.

**Comment by LalatenduMohanty** [comment]
we should tag them minishift only once we have these tests modified for CDK and merged in CDK  in separate files to avoid merge conflicts.
