### ISSUE TITLE
Readiness URL Certificate Expired

### ISSUE THREAD

**Issue by lance** [minishift/minishift#1890]
### General information

  * Minishift version: 1.11.0
  * OS: macOS 
  * Hypervisor: VirtualBox

When starting a newly installed version of minishift on OSX the startup logs display an error. 

```txt
Error: Get https://192.168.99.101:8443/healthz/ready: x509: certificate has expired or is not yet valid
```
It appears that minishift does actually start, however (see logs below).

### Steps to reproduce

  1. minishift delete --force
  2. minishift update
  3. minishift  start --vm-driver=virtualbox --memory=4096 --cpus=2

### Expected

Minishift should start without error.

### Actual

Minishift displays an error for the readiness URL `https://192.168.99.101:8443/healthz/ready`. 

### Logs

<details>
<summary>Minishift delete/update/start log</summary>
<code><pre>
~/s/s/adjective minishift delete --force
Deleting the Minishift VM...
Minishift VM deleted.
~/s/s/adjective minishift update
Nothing to update.
Already using the latest version: 1.11.0.
~/s/s/adjective minishift start --vm-driver=virtualbox --memory=4096 --cpus=2
-- Starting profile 'minishift'
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .......................... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.7.0
-- Checking `oc` support for startup flags ...
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   version ... OK
   routing-suffix ... OK
   host-config-dir ... OK
Starting OpenShift using openshift/origin:v3.7.0 ...
Pulling image openshift/origin:v3.7.0
Pulled 1/4 layers, 26% complete
Pulled 2/4 layers, 84% complete
Pulled 3/4 layers, 94% complete
Pulled 3/4 layers, 100% complete
Pulled 3/4 layers, 75% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v3.7.0 image ...
   Pulling image openshift/origin:v3.7.0
   Pulled 1/4 layers, 26% complete
   Pulled 2/4 layers, 84% complete
   Pulled 3/4 layers, 94% complete
   Pulled 3/4 layers, 100% complete
   Pulled 3/4 layers, 75% complete
   Pulled 4/4 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ...
   Using 192.168.99.101 as the server IP
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
FAIL
   Error: cannot access master readiness URL https://192.168.99.101:8443/healthz/ready
   Details:
     Last 10 lines of "origin" container log:
     I0105 20:40:24.119674    3468 tprregistration_controller.go:147] Starting tpr-autoregister controller
     I0105 20:40:24.119743    3468 controller_utils.go:1025] Waiting for caches to sync for tpr-autoregister controller
     I0105 20:40:24.120044    3468 openshift_apiserver.go:642] Using default project node label selector:
     I0105 20:40:24.120566    3468 clusterquotamapping.go:160] Starting ClusterQuotaMappingController controller
     I0105 20:40:24.120661    3468 customresource_discovery_controller.go:152] Starting DiscoveryController
     I0105 20:40:24.120736    3468 naming_controller.go:284] Starting NamingConditionController
     I0105 20:40:24.135181    3468 autoregister_controller.go:141] Starting autoregister controller
     I0105 20:40:24.135229    3468 cache.go:32] Waiting for caches to sync for autoregister controller
     I0105 20:40:24.429468    3468 cache.go:39] Caches are synced for APIServiceRegistrationController controller
     I0105 20:40:24.429531    3468 cache.go:39] Caches are synced for AvailableConditionController controller

   Caused By:
     Error: Get https://192.168.99.101:8443/healthz/ready: x509: certificate has expired or is not yet valid
Error during 'cluster up' execution: Error starting the cluster.
~/s/s/adjective minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Running (openshift v3.7.0+7ed6862)
DiskUsage:  7% of 17.9G
~/s/s/adjective

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

</pre>
</code>
</details>

**Comment by gbraad** [comment]
Please check if your system needs to synchronize its clock. Likely the
certificate is not valid as there is a skew of a few seconds between valid
or not. (We have seen this before)

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by lance** [comment]
@gbraad I guess this is what the issue was. It resolved itself after an unrelated system restart. Closing this.
