### ISSUE TITLE
Update xpaas templates for OpenShift 3.7

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1898]
We need to update xpaas templates which are already updated https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples/v3.7

**Comment by LalatenduMohanty** [comment]
Related issue in downstream: https://issues.jboss.org/projects/CDK/issues/CDK-235

**Comment by LalatenduMohanty** [comment]
Resolved via #1899
