### ISSUE TITLE
Persist date/time changes across start/stop cycles

### ISSUE THREAD

**Issue by benemon** [minishift/minishift#1906]
### General information

It would be useful to have minishift set, or at least persist time/timezone information between restarts. The default EST is not applicable to everyone, and clock drift can have a negative impact on user experience if a minishift instance is operational over a number of days with multiple start/stop lifecycles over that time. Consider this a quality of life improvement.

  * Minishift version: 
     minishift v1.7.0+204ce19 
     CDK v3.2.0-1

  * OS: macOS 

  * Hypervisor: VirtualBox

I've created an addon to automatically address the issue of setting the correct timezone issue on first boot, but this neither persists nor is it executed on subsequent runs of the minishift instance.

### Steps to reproduce

  1. minishift start
  2. minishift ssh
  3. sudo timedatectl set-timezone Europe/London
  4. sudo timedatectl status
  5. exit
  6. minishift stop
  7. minishift start
  8. minishift ssh
  9. sudo timedatectl status

### Expected

Maintain timezone setting as displayed by timedatectl status

### Actual

Timezone resets to EST.

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
Perhaps it is better to force the liveCD to use UTC as timezone  as a first solution, and for those who really want to change the settings, we should provide a means to force this.

One of them was to use a custom-script to run on startup: https://github.com/minishift/minishift-centos-iso/issues/133

**Comment by jorgemoralespou** [comment]
And then you need to start openshift with the appropriate TZ in the VM. For that, there's a TZ environment variable one can pass to the "oc cluster up" process.

https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/master/oc-cluster#L69
and
https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/master/oc-cluster#L515

**Comment by benemon** [comment]
I was using timedatectl to explicit avoid setting TZ variables. It was pretty simple to do that as an addon e.g.

```
# Name: timezone
# Description: Sets the timezone on minishift startup

ssh sudo timedatectl set-timezone $(curl -s 'https://timezoneapi.io/api/ip' | python -c "import sys, json; print json.load(sys.stdin)['data']['timezone']['id']")
```

**Comment by anjannath** [comment]
I think this will also be resolved after #2864 Is merged, since the timezone will be set at the start of the VM.

/cc @praveenkumar

**Comment by praveenkumar** [comment]
We have now timezone option in the start and also a hidden `timezone` command if user want to set it later. 

Resolved by #2864

**Comment by jorgemoralespou** [comment]
Does it have any default to the timezone of my host?

**Comment by anjannath** [comment]
Nope, it does not check the host's timezone and default to it. 

Atm #2864 Only allows you to set a timezone during the start using the `--timezone` flag.

**Comment by jorgemoralespou** [comment]
Wouldn't it be nicer to default to the host timezone, which is what most of
the times a user will want, preventing him from having to issue an
additional command?

**Comment by praveenkumar** [comment]
> Wouldn't it be nicer to default to the host timezone, which is what most of the times a user will want, preventing him from having to issue an additional command?

@jorgemoralespou I know but that is something not possible to get required details from the host on all the platform and then set it. This is the best I found atm.
