### ISSUE TITLE
VersionOrdinal in util is return false for 3.7 >= 3.7.0

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1907]
### General information

  * Minishift version: master
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. The following piece of code is not working as expected

https://github.com/minishift/minishift/blob/d7f374aaa585bf9b967631683f030f809ad0a0ea/pkg/util/utils.go#L100-L131

### Expected
`3.7 >= 3.7.0` should return true.

### Actual
`3.7 >= 3.7.0` should return false.

**Comment by LalatenduMohanty** [comment]
Because of this `minishift start --ocp-tag 3.7` will provision OpenShift cluster with `oc` binary of v3.6.173.0.63. But in Red Hat container catalog 3.7 tag points to latest builds in 3.7.x series.

**Comment by LalatenduMohanty** [comment]
Downstream issue https://issues.jboss.org/projects/CDK/issues/CDK-242

**Comment by jorgemoralespou** [comment]
@LalatenduMohanty Why can you specify version 3.7 for ocp but not for origin?

```
$ minishift config set openshift-version 3.7
$ minishift start --logging
-- Starting profile 'service-catalog'
Invalid version format '3.7': No Major.Minor.Patch elements found
```

**Comment by praveenkumar** [comment]
@jorgemoralespou OCP doesn't follow semantic version but origin follow so for origin we have preflight check which tell user before even start of VM, same behaviour right now not posible for OCP.

**Comment by jorgemoralespou** [comment]
If one could use 3.7 instead of 3.7.0 then logging and metrics would work.
Or at least the one that has that tag.

**Comment by LalatenduMohanty** [comment]
> Why can you specify version 3.7 for ocp but not for origin?

@jorgemoralespou you mean "Why `can not` you specify version 3.7 for ocp but not for origin?" right?  In that case the current error is fine because as Origin follows semantic version scheme where `3.7` is an invalid version.

**Comment by LalatenduMohanty** [comment]
Closing the issue as cdk-242 is not relevant to `VersionOrdinal` function.
