### ISSUE TITLE
Service catalog option behind experimental feature is no longer needed

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1908]
### General information

  * Minishift version: `master` branch
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. Run
```
$ MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start -h | grep service
      --service-catalog                 Install service catalog (experimental)
```

### Expected
We don't require service catalog option as experimental as it is no more experimental.

**Comment by gbraad** [comment]
@budhrg Where can you see it is not experimental anymore? The documentation for `oc cluster up` hasn't changed yet https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#installing-the-service-catalog

**Comment by LalatenduMohanty** [comment]
@gbraad Refer https://blog.openshift.com/whats-new-in-openshift-3-7-service-catalog-and-brokers/

**Comment by gbraad** [comment]
If so, we should also file a documentation issue against OpenShift

**Comment by jorgemoralespou** [comment]
@gbraad what is experimental is the flag to "oc cluster up" in the sense that, as this feature uses ansible-broker it is not guarantee to always work. Same as logging and metrics, which are marked as experimental in the output of "oc cluster up -h" but they are GA features in OpenShift, and they both have 1st level support in minishift.

**Comment by gbraad** [comment]
in other words, we are still experimental in that case. We can not guarantee that the deployment will succeed. or should we remove the minishift's experimental state.... This means we have to deal with the possible issues that come our way and re-assign to `oc cluster up`. I am OK with this is, as it will improve the code and maybe put pressure behind the fact to fix the implementation. Just the expectation of the user would be my concern...

**Comment by gbraad** [comment]
Known issues exist: #1910 (restart causes service catalog to fail)

**Comment by gbraad** [comment]
Another issue with the current version: #2116

**Comment by praveenkumar** [comment]
Since we removed service catalog completely, I am closing this issue now.
