### ISSUE TITLE
Github security warning for nokogiri version < 1.8.1

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1911]
On my fork of Minishift I can see following warning i.e. `The nokogiri dependency defined in Gemfile.lock has a known critical severity security vulnerability in version range < 1.8.1 and should be updated.`

We use nokogiri v1.8.0 for building our documentation builder docker image. So it is not a Minishift security issue as it does not touch Minishift binary.  But we should still fix it as would effect developers/contributors who build documentation locally .

![nokogiri-cve-minishift](https://user-images.githubusercontent.com/3125299/34929510-55f82d0c-f9ea-11e7-9720-b88a423fa804.png)

**Comment by praveenkumar** [comment]
@LalatenduMohanty Is there any specific setting you have in your fork which shows you this warning? If yes, then better to add that setting to the minishift project also.

**Comment by LalatenduMohanty** [comment]
@praveenkumar Actually I was wondering about that too. But I did not do any extra settings. Not sure why it shows up there : https://github.com/LalatenduMohanty/minishift-future

**Comment by gbraad** [comment]
Where does this message get shown?

**Comment by budhrg** [comment]
Able to reproduce as:
1. Click on new repository button in Github
2. Give name (say `minishift-fork`) and click on create
3. In your local machine minishift repo, run 
   ```
   git remote add origin1 https://github.com/<your-username>/minishift-fork
   ```
4. Run `git push -u origin1 master`
5. Go to `https://github.com/<your-username>/minishift-fork` in Github UI and wait for sometime.

**Comment by anjannath** [comment]
I can also see the warning message after creating a new repo and pushing the minishift code.

**Comment by gbraad** [comment]
So, this only works with a new project... this feels like a setting

**Comment by gbraad** [comment]
aren't security fixes critical in general?

**Comment by anjannath** [comment]
@gbraad +1 this is critical, but this doesn't affect _minishift_ but the developers building the docs locally, also since `nokogiri-1.8.0` is pulled inside the docker container, its not affecting that much IMO.

**Comment by gbraad** [comment]
right, in that case it is not blocking anything or urges us to merge before the CDK release.

**Comment by budhrg** [comment]
> right, in that case it is not blocking anything or urges us to merge before the CDK release.

Yes, should be merge post CDK release.
