### ISSUE TITLE
You need to run 'minishift.exe setup-cdk' first to install required CDK components.

### ISSUE THREAD

**Issue by hdjur** [minishift/minishift#1916]
### General information

  * Minishift version: v1.7.0+204ce19
  * OS: Windows
  * Hypervisor: VirtualBox

### Steps to reproduce

C:\install>cdk-3.2.0-1-minishift-windows-amd64.exe version
minishift v1.7.0+204ce19
CDK v3.2.0-1

C:\install>cdk-3.2.0-1-minishift-windows-amd64.exe setup-cdk --force --default-vm-driver=virtualbox --minishift-home "c:\users\hradjh\minishift"
Setting up CDK 3 on host using 'c:\users\hradjh\minishift' as Minishift's home directory
Copying minishift-rhel7.iso to 'c:\users\hradjh\minishift/cache/iso/minishift-rhel7.iso'
Copying oc.exe to 'c:\users\hradjh\minishift/cache/oc/v3.6.173.0.21/oc.exe'
Creating configuration file 'c:\users\hradjh\minishift/config/config.json'
Creating marker file 'c:\users\hradjh\minishift/cdk'
Default add-ons anyuid, admin-user, xpaas, registry-route, che installed
Default add-ons anyuid, admin-user, xpaas enabled
CDK 3 setup complete.

C:\install>dir c:\users\hradjh\minishift\cache\oc\v3.6.173.0.21
 Volume in drive C is System
 Volume Serial Number is 6A41-613F

 Directory of c:\users\hradjh\minishift\cache\oc\v3.6.173.0.21

17.01.2018  10:25    <DIR>          .
17.01.2018  10:25    <DIR>          ..
17.01.2018  10:25       185,812,984 oc.exe
               1 File(s)    185,812,984 bytes
               2 Dir(s)  231,933,710,336 bytes free

C:\install>dir c:\users\hradjh\minishift\cache\iso
 Volume in drive C is System
 Volume Serial Number is 6A41-613F

 Directory of c:\users\hradjh\minishift\cache\iso

17.01.2018  10:25    <DIR>          .
17.01.2018  10:25    <DIR>          ..
17.01.2018  10:25       367,001,600 minishift-rhel7.iso
               1 File(s)    367,001,600 bytes
               2 Dir(s)  231,933,644,800 bytes free

C:\install>dir c:\users\hradjh\minishift\cdk
 Volume in drive C is System
 Volume Serial Number is 6A41-613F

 Directory of c:\users\hradjh\minishift

17.01.2018  10:25               116 cdk
               1 File(s)            116 bytes
               0 Dir(s)  231,933,644,800 bytes free

C:\install>more c:\users\hradjh\minishift\cdk
openshift.auth.scheme=basic
openshift.auth.username=developer
openshift.auth.password=developer
cdk.version=3.2.0-1

C:\install>dir c:\users\hradjh\minishift\config
 Volume in drive C is System
 Volume Serial Number is 6A41-613F

 Directory of c:\users\hradjh\minishift\config

17.01.2018  10:25    <DIR>          .
17.01.2018  10:25    <DIR>          ..
17.01.2018  10:25               136 config.json
               1 File(s)            136 bytes
               2 Dir(s)  231,933,624,320 bytes free

C:\install>more c:\users\hradjh\minishift\config\config.json
{
    "iso-url": "file://c:/users/hradjh/minishift/cache/iso/minishift-rhel7.iso",
    "memory": "4096",
    "vm-driver": "virtualbox"
}

C:\install>cdk-3.2.0-1-minishift-windows-amd64.exe status
You need to run 'minishift.exe setup-cdk' first to install required CDK componen
ts.

C:\install>cdk-3.2.0-1-minishift-windows-amd64.exe start
You need to run 'minishift.exe setup-cdk' first to install required CDK componen
ts.

C:\install>
### Expected
being able to start minishift

### Actual
not being able to start it

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

C:\install>cdk-3.2.0-1-minishift-windows-amd64.exe start --show-libmachine-logs -v5
You need to run 'minishift.exe setup-cdk' first to install required CDK components.

C:\install>

**Comment by praveenkumar** [comment]
@hdjur Hi, looks like you are trying CDK product and as command showing you need to first run the setup-cdk command and then start it.

```
> cdk-3.2.0-1-minishift-windows-amd64.exe setup-cdk
> cdk-3.2.0-1-minishift-windows-amd64.exe start
```

**Comment by hdjur** [comment]
@praveenkumar Hi, but I did it a lot of times, and I presented the output of execution of that command, as well as the other visible results, like the content of files that were produced, such as config.json, cdk, etc.

**Comment by hdjur** [comment]
I reported the same thing here:
https://issues.jboss.org/browse/CDK-243

**Comment by hdjur** [comment]
And it was solved there.
