### ISSUE TITLE
minishift update ignores MINISHIFT_GITHUB_API_TOKEN

### ISSUE THREAD

**Issue by eriknelson** [minishift/minishift#1920]
### General information

  * Minishift version: minishift v1.8.0+6455fc3
  * OS: Fedora 27
  * Hypervisor: KVM

### Steps to reproduce

  1. export MINISHIFT_GITHUB_API_TOKEN=`<token>`
  2. sudo minishift update

(obviously you'll need to be on a rate limited network)

### Expected
Should use the token to authenticate and update.

### Actual
Error from the github releases results: Update failed: GET https://api.github.com/repos/minishift/minishift/releases/latest: 403 API rate limit exceeded for `<IP>`. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 8m17.622796408s

### Logs
No relevant logs beyond the rate limit error.

**Comment by gbraad** [comment]
thanks for reporting this. probably a missed case...

**Comment by benjaminapetersen** [comment]
+1 to this issue:

```
$ minishift update
Update failed: GET https://api.github.com/repos/minishift/minishift/releases/latest: 403 API rate limit exceeded for 66.187.233.202. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 52m56.918251s
```

**Comment by anjannath** [comment]
@benjaminapetersen Which version of minishift are you using?

**Comment by anjannath** [comment]
I don't think `minishift update` ignores the `MINISHIFT_GITHUB_API_TOKEN`. In the update command we make one request to github api to get the latest release...

https://github.com/minishift/minishift/blob/d9a86c9a994cb52b350bf0390b3215ad36c56487/pkg/minishift/update/update.go#L127-L148

where we use `githubutils.Client()`, which puts the token in the request _if_ it is set..

https://github.com/minishift/minishift/blob/d9a86c9a994cb52b350bf0390b3215ad36c56487/pkg/util/github/github.go#L66-L79

**Comment by anjannath** [comment]
@benjaminapetersen It seems like the api token is not being used by minishift.. just to confirm did you do `export MINISHIFT_GITHUB_API_TOKEN=<your github api token>`?

**Comment by benjaminapetersen** [comment]
@anjannath nope, I haven't messed with any vars at all.  Are these documented?  If so, I must have missed.  If not, thats prob the correct resolution to my issue.  Thx!

**Comment by budhrg** [comment]
@benjaminapetersen , If I understood you correct here, with `nope` means you didn't export `MINISHIFT_GITHUB_API_TOKEN`, right?

Could you try exporting these variables and try update?

**Comment by benjaminapetersen** [comment]
Correct!

Just generated a token & gave `export MINISHIFT_GITHUB_API_TOKEN=<token> minishift start` a spin && seems to get around the problem. thx!

**Comment by anjannath** [comment]
Thanks @benjaminapetersen . We will print better error messages wherever github api is contacted in the code, to communicate if rate limit is hit or it is a 404.. will do this as a patch for #2307 

Closing this...

**Comment by benjaminapetersen** [comment]
Great sounds good, thx!
