### ISSUE TITLE
Unable to push images to the openshift registry as "developer"

### ISSUE THREAD

**Issue by eriknelson** [minishift/minishift#1921]
### General information

  * Minishift version: v1.11.0+4459917
  * openshift-version: v3.7.0
  * OS: Fedora 27
  * Hypervisor: KVM
  * Docker:
```
# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-42.git4402c09.fc27.x86_64
 Go version:      go1.9.1
 Git commit:      fbadd78-unsupported
 Built:           Fri Nov 17 15:24:49 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-42.git4402c09.fc27.x86_64
 Go version:      go1.9.1
 Git commit:      fbadd78-unsupported
 Built:           Fri Nov 17 15:24:49 2017
 OS/Arch:         linux/amd64
 Experimental:    false
```

I'm working on an addon for the [Ansible Service Broker](https://github.com/openshift/ansible-service-broker/). Alongside the broker, there is a [tool](https://github.com/ansibleplaybookbundle/ansible-playbook-bundle) that's used to interact with the broker. One of its features is the ability to push an APB image to the internal registry. This fails in minishift as the `developer` account out of the box, so I'm investigating the correct permission configuration to allow for that.

Addon: https://github.com/eriknelson/cdk-minishift-utils/tree/asb-update/addons/ansible-service-broker

The addon installs the upstream broker's template, as well as a WIP template I'm writing to apply the necessary permissions to the `developer` account.

Permission template: https://github.com/eriknelson/ansible-playbook-bundle/blob/openshift-perm-template/templates/openshift-permissions.template.yaml

### Steps to reproduce

  1. `export MINISHIFT_ENABLE_EXPERIMENTAL=y && export MINISHIFT_GITHUB_API_TOKEN=$TOKEN`
  2. Checkout, install, and enable the above `ansible-service-broker` addon.
  3. `minishift config set openshift-version v3.7.0`
  4. Start minishift: `minishift delete && minishift start --service-catalog --iso-url centos --show-libmachine-logs -v5` (Attached logs)
  5. Update `--insecure-registry` entry in `/etc/sysconfig/docker` and bounce the service: `sudo sed -i "s|192.168.42.[0-9][0-9]*|$(minishift ip)|g" /etc/sysconfig/docker && sudo systemctl restart docker`.
  6. Docker login: `docker login -u developer -p $(oc whoami -t) registry-access-default.$(minishift ip).nip.io:443`. I'm getting "Login Succeeded".
  7. Attempt to push an image: `docker push "registry-access-default.$(minishift ip).nip.io:443/openshift/my-apb02"`

### Expected
Image should be pushed to the registry and available.

### Actual
Docker perpetually retries pushing the layers with increasing backoff until it ultimately fails with `EOF`. See attached `docker-push.txt` logs.

### Logs
[minishift-start.txt](https://gist.github.com/eriknelson/837ee646fd6123ba3f4375f89f5d675e#file-minishift-start-txt)
[docker-push.txt](https://gist.github.com/eriknelson/837ee646fd6123ba3f4375f89f5d675e#file-docker-push-txt)

### Additional Questions

* Are the `system:registry` and `system:image-builder` ClusterRoles necessary for developer to be able to interact with that registry? The docs were a little vague on exactly when these are required.
* The docs suggested `admin` might be needed? Is that true, and if so, which namespace should that RoleBinding be applied to?
* The docs also use the service IP rather than a route. Is this possible?

**Comment by praveenkumar** [comment]
@eriknelson I am not able to follow steps which you listed, can you please elaborate what it do?

1. Which insecure registry you are trying to add here and this command you are executing on the host or Minishift VM?

- `Update --insecure-registry entry in /etc/sysconfig/docker and bounce the service: sudo sed -i "s|192.168.42.[0-9][0-9]*|$(minishift ip)|g" /etc/sysconfig/docker && sudo systemctl restart docker.`

2. How you are getting `registry-access-default.$(minishift ip).nip.io:443` below we don't provide it ourself, did you create it?

- `Docker login: docker login -u developer -p $(oc whoami -t) registry-access-default.$(minishift ip).nip.io:443. I'm getting "Login Succeeded".`


We have proper documention around how to consume internal registry https://docs.openshift.org/latest/minishift/openshift/openshift-docker-registry.html

**Comment by eriknelson** [comment]
> Which insecure registry you are trying to add here and this command you are executing on the host or Minishift VM?

Sorry, that was unclear, it's a script I use to update the ip after deleting and starting minishift. I'm adding the route to my host, for example: `registry-access-default.192.168.42.180.nip.io:443`

> How you are getting registry-access-default.$(minishift ip).nip.io:443 below we don't provide it ourself, did you create it?

I'm creating the route in [one of the templates](https://github.com/eriknelson/ansible-playbook-bundle/blob/openshift-perm-template/templates/openshift-permissions.template.yaml#L123) that gets deployed by the addon.

Mostly interested in the recommended way to expose the registry to the host however, thanks for the documentation link on this, I had not seen it previously. I will see if that changes things at all.

**Comment by eriknelson** [comment]
@praveenkumar Got things working I think; that dramatically simplified what I was doing! Thank you. I don't think this issue is relevant anymore.
