### ISSUE TITLE
Add support for unsupported VM drivers

### ISSUE THREAD

**Issue by marekjelen** [minishift/minishift#1926]
### General information

At this time, `minishift` only works with bundled drivers.

https://github.com/minishift/minishift/blob/eff0477aa242432aaba284febf9496ebe6cd2371/pkg/minikube/machine/client.go#L42

### Steps to reproduce

  1. brew install docker-machine-parallels
  2. minishift start --vm-driver=parallels

Fails, as `parallels` is not supported driver.

  1. ln -s /usr/local/bin/docker-machine-driver-parallels /usr/local/bin/docker-machine-driver-virtualbox
  2. minishift start --vm-driver=virtualbox

Fails, as `minishift` only works with bundled drivers.

### Expected

Minishift should default to driver available on `$PATH` in case the requested driver is not bundled.

To be sure people are aware that such configurations are unsupported, the plugins from `$PATH` could be only available with a special switch, e.g.

```
minishift start --vm-driver=parallels --enable-unsupported-drivers-on-path
```

### Actual

Minishift fails.

### Logs

```
$ minishift start --vm-driver=parallels                                                                                                                                                                          
-- Checking if requested hypervisor 'parallels' is supported on this platform ... FAIL
   See the 'Setting Up the Driver Plug-in' topic (https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html) for more information
```

```
$ ln -s /usr/local/bin/docker-machine-driver-parallels /usr/local/bin/docker-machine-driver-virtualbox
$ minishift start --vm-driver=virtualbox                                                                                                                                                                         
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Starting profile 'minishift'
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.2.0/minishift-b2d.iso'
 40.00 MiB / 40.00 MiB [====================================================================================================================================================================================================] 100.00% 0s
-- Starting Minishift VM ..... FAIL E0122 07:28:14.547221   66789 start.go:357] Error starting the VM: Error creating the VM. Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path". Retrying.
Error starting the VM: Error creating the VM. Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
```

**Comment by gbraad** [comment]
This at the moment is intentional due to a lack of testing option... when we have progressed more on machine-drivers, we will consider to enable and also have CI in-place

**Comment by gbraad** [comment]
you can cheat with using the xhyve or KVM driver and linking I guess? but surely NOT recommended!

**Comment by praveenkumar** [comment]
Closing this issue since this is not within the scope of minishift.
