### ISSUE TITLE
Unable to use "oc login https://192.168.99.100:8443" getting EOF on Windows 7

### ISSUE THREAD

**Issue by farbgeist** [minishift/minishift#1927]
### General information

  * Minishift version: minishift v1.10.0+10461c6
  * OS:  Windows 7
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. minishift start --vm-driver virtualbox
  2. login to https://192.168.99.100:8443
  3. Go to command line tools : https://192.168.99.100:8443/console/command-line
  4. oc login https://192.168.99.100:8443 --token=QXffXjM7n6Yczmle-HBAKsyTLkKc4ozUYN6xDvztbhQ

### Expected

Login successful

### Actual

"error: EOF"

### Logs

https://gist.github.com/farbgeist/4f07a00b3d7b34a475bd7a90c8e7e6d8

**Comment by farbgeist** [comment]
The error also occurs if I only try to use "oc login https://192.168.99.100:8443" without the token.

**Comment by farbgeist** [comment]
deleting oc from the cache and starting minishift again did not change the behaviour.

**Comment by farbgeist** [comment]
Trying a higher loglevel of oc yields the following:
```

./oc login https://192.168.99.100:8443 --loglevel=10

I0123 10:07:49.947896   10084 round_trippers.go:386] curl -k -v -XHEAD  https://192.168.99.100:8443/
I0123 10:07:49.951238   10084 round_trippers.go:405] HEAD https://192.168.99.100:8443/  in 3 milliseconds
I0123 10:07:49.951347   10084 round_trippers.go:411] Response Headers:
F0123 10:07:49.951386   10084 helpers.go:120] error: EOF
```

Then re-running curl with the parameters given in the logs gives the following output: 


```
curl -k -v -XHEAD https://192.168.99.100:8443/
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the 
Warning: way you want. Consider using -I/--head instead.
*   Trying 172.21.0.10...
* Connected to 172.21.0.10 (172.21.0.10) port 88 (#0)
* Establish HTTP proxy tunnel to 192.168.99.100:8443
> CONNECT 192.168.99.100:8443 HTTP/1.1
> Host: 192.168.99.100:8443
> User-Agent: curl/7.47.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< Proxy-Connection: keep-alive
< 
* Proxy replied OK to CONNECT request
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: The TLS connection was non-properly terminated.
* Closing connection 0
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.
```

It is a standard Windows 7 Minishift installation. I did not mess with the certificates...

**Comment by praveenkumar** [comment]
@farbgeist Can you do below and also let us know which tool for you are using?

```
 $ ./minishift start
[...]
   Version: v3.6.1
-- Checking `oc` support for startup flags ... 
   host-pv-dir ... OK
   host-volumes-dir ... OK
   routing-suffix ... OK
   host-config-dir ... OK
   host-data-dir ... OK
Starting OpenShift using openshift/origin:v3.6.1 ...
Pulling image openshift/origin:v3.6.1
Pulled 1/4 layers, 26% complete
[...]
The server is accessible via web console at:
    https://192.168.64.85:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin
[...]

$ eval $(./minishift oc-env)

$ oc login https://192.168.64.85:8443
Authentication required for https://192.168.64.85:8443 (openshift)
Username: developer
Password: 
Login successful.

You have one project on this server: "myproject"

Using project "myproject".
```

**Comment by farbgeist** [comment]
@praveenkumar: 
The problem occurs on Windows 7. You obviously did your example on a Linux box.
After "minishift start" and "oc login https://192.168.99.100:8443"   I just get "error: EOF".

**Comment by farbgeist** [comment]
Tried the exact same steps from my "Steps to reproduce" on a Windows 10 Box with Virtualbox as vm provider -> it worked without problems.

The Windows 10 machine is behind the same corporate firewall/proxy as my Windows 7 box.

**Comment by gbraad** [comment]
Can you verify if you might have software installed that intercept/verify network traffic, such as an application firewall or virus scanner?

If it is possible to share a list of installed applications on either of these machines, that would be great as we can do an intersection of them and see what is different. (assuming these are both corporate setups, I believe there might be additional security tools)

**Comment by farbgeist** [comment]
Verified that  minishift works with virtualbox on Windows 10 within out corporate network. So our team will upgrade to Windows 10. If no one else has this issue, we may as well close it.

**Comment by LalatenduMohanty** [comment]
Closing the issue as works on Win10 and @farbgeist mentioned the issue on Win7 mostlikely not related to `minishift`. @farbgeist you can always ask to re-open the issue if you think it is a bug with `minishift`.

**Comment by burtsevyg** [comment]
You should add your minishift host to no_proxy env variable.
