### ISSUE TITLE
Update CentOS ISO version to v1.5.0

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1928]
https://github.com/minishift/minishift-centos-iso/releases/tag/v1.5.0

**Comment by gbraad** [comment]
@LalatenduMohanty you tested this image to work on KVM?

**Comment by gbraad** [comment]
tested on Hyper-V, boots and works as expected.

**Comment by anjannath** [comment]
tested on kvm, can boot the minishift vm

**Comment by LalatenduMohanty** [comment]
Resolved by #1929
