### ISSUE TITLE
Fix the community section in Readme

### ISSUE THREAD

**Issue by syamgk** [minishift/minishift#1930]
### General information
Typo in Readme.md file
under https://github.com/minishift/minishift#community

### Expected

`Minishift is an open-source project dedicated to developing and supporting OpenShift. `

### Actual

`Minishift is an open-source project dedicated to developing and supporting Minishift.`

**Comment by LalatenduMohanty** [comment]
I think we can remove the line as it does not contribute to the section much.

**Comment by LalatenduMohanty** [comment]
Resolved via #1931
