### ISSUE TITLE
Provide backup option for Openshift Config

### ISSUE THREAD

**Issue by kameshsampath** [minishift/minishift#1934]
Right now the `minishift openshift config` command updates the `master-config.yaml` but without back up of the previously working version of `master-config.yaml`, it will be great if we can have option to back up the `master-config.yaml` before update to allow the users to rollback to last known good config , if the `minishift openshift config`  crashes the openshift.

**Comment by LalatenduMohanty** [comment]
@kameshsampath Where do you want to store the config? Does `minishift openshift config view` help? Do you want to store it as json or yml?

**Comment by kameshsampath** [comment]
@LalatenduMohanty 
> Where do you want to store the config? Does minishift openshift config view help?
how about the minishift profile directory  `config` folder ?
>Do you want to store it as json or yml?
prefer yml
