### ISSUE TITLE
Windows 10 FCU integrated ssh client fails

### ISSUE THREAD

**Issue by jahpola** [minishift/minishift#1943]
Starting minishift fails. Seems to be issue with built-in ssh in Windows 10 FCU and supported ssh key type.

Versions:
Windows 10 Pro, build 16299.192 with Hyper-V
minishift v1.12.0+daa0943

### Steps to reproduce

  1.   Setup Hyper-V as normal, add the Hyper-V  virtual switch variable etc
  2.   minishift.exe start --iso-url centos --show-libmachine-logs -v5
  
It never finishes. Logging shows it keeps looping around SSH. 
`Using SSH client type: external
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -
o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@10.0.1.58 -o IdentitiesOnly=yes -
i C:\Users\kermi\.minishift\machines\minishift\id_rsa -p 22] C:\WINDOWS\System32\OpenSSH\ssh.exe <nil>}
About to run SSH command:
exit 0
.SSH cmd err, output: exit status 255:
Error getting ssh command 'exit 0' : ssh command error:
command : exit 0
err     : exit status 255
output  :
Getting to WaitForSSH function...`

Checking the actual ssh command via:
`PS C:\Projektit> ssh.exe -o ControlPath=none docker@10.0.1.58 -o IdentitiesOnly=yes -i C:\
nishift\id_rsa -p 22 -o ControlMaster=no -o ConnectTimeout=10  -o PasswordAuthentication=n
serKnownHostsFile=/dev/null
key_load_public: invalid format
Warning: Permanently added '10.0.1.58' (ED25519) to the list of known hosts.
Load key "C:\\Users\\kermi\\.minishift\\machines\\minishift\\id_rsa": invalid format
docker@10.0.1.58: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).`

See the key_load_public error in the ssh command.  And I think the new integrated ssh client supports only ed25519 keys.
.

**Comment by gbraad** [comment]
Haven't seen this myself. Try to rename the executable and try with the embedded client or use the openssh-win32 release for now.

**Comment by jahpola** [comment]
Did not manage to rename the exe but I removed it which worked. I would say this is due to limitations in that ssh implementation i.e. only ed25519 supported atm.

**Comment by gbraad** [comment]
I am able to use thebbeta without issues to login. Which version of the OS do you run? I'll check later... but surely an insider

**Comment by jahpola** [comment]
Just normal Windows 10 Pro Fall Creators update with latest patches.  winver shows as Version 1709(OS build 16299.192).
