### ISSUE TITLE
Restarting a stopped minishift instance that uses --service-catalog fails

### ISSUE THREAD

**Issue by starksm64** [minishift/minishift#1945]
### General information

  * Minishift version: v1.12.0+daa0943
  * OS: macOS 10.13.2
  * Hypervisor:  VirtualBox

### Steps to reproduce

  1. git clone https://github.com/starksm64/wildfly-swarm-service-broker.git
  2. Run through README.md to deploy the jwt-service-broker
  3. minishift stop
  4. MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start

### Expected
The minishift instance is restored

### Actual
The instance fails to fully restore as shown in the linked log.

### Logs

https://gist.github.com/starksm64/5ea58f0473b6d5a1da764dc8ee3532f4

**Comment by gbraad** [comment]
i think this was reported recently

**Comment by gbraad** [comment]
dup of #1910
