### ISSUE TITLE
Investigate switch to Minikube image as default image

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#195]
See also minikube - https://github.com/kubernetes/minikube/tree/master/deploy/iso/minikube-iso

**Comment by r2d4** [comment]
an FYI - this isn't actually the CoreOS image.  Its a minimal custom ISO with rkt and docker support built with buildroot.  (However, it was contributed by a CoreOS employee)

**Comment by hferentschik** [comment]
> this isn't actually the CoreOS image. Its a minimal custom ISO with rkt and docker support built with buildroot.

Thanks for the heads up. We will look into this :-)

**Comment by praveenkumar** [comment]
Should we also now get rid of boot2docker iso and work with CoreOS iso? @hferentschik if you think this something need a milestone please add it. Mostly we might end up with `minishift-coreOS` repo.

**Comment by hferentschik** [comment]
> Should we also now get rid of boot2docker iso and work with CoreOS iso?

That was the initial idea. Minikube afaik use CoreOS image. I guess one would need to start with an investigation and see how much work it is and how it compares to the B2D ISO.

> Mostly we might end up with minishift-coreOS repo.

Right, that would be the result

**Comment by hferentschik** [comment]
Closing this as duplicate of #1058
