### ISSUE TITLE
oc new-app: how to set dockerfile path

### ISSUE THREAD

**Issue by robdaems** [minishift/minishift#1950]
I've a repo were my Dockerfile is called and located in `/docker/Dockerfile.x86_64`  (different architectures to build). 
It's possible to set the  [Dockfile path](https://docs.openshift.com/enterprise/3.1/dev_guide/builds.html#dockerfile-path)

Has anyone an idea how to give the dockerfile path when using `oc new-app`, since the context-dir is not an options because the source code itself is located at /

**Comment by praveenkumar** [comment]
@robdaems this is mostly related to OpenShift, not minishift. I think for this kind of queries you can use OpenShift user ML.

@jorgemoralespou you have any info about it?

**Comment by LalatenduMohanty** [comment]
@robdaems Which strategy you are using to build your application, refer https://docs.openshift.org/latest/dev_guide/application_lifecycle/new_app.html#specifying-source-code
I also feel this is an OpenShift question and should be asked in https://github.com/openshift/origin/

**Comment by robdaems** [comment]
Question asked in openshift:
https://github.com/openshift/origin/issues/18610
