### ISSUE TITLE
Logged out automatically

### ISSUE THREAD

**Issue by burrsutter** [minishift/minishift#1955]
### General information

  * Minishift version: v1.10.0+10461c6
  * OS: macOS 
  * Hypervisor: VirtualBox

### Steps to reproduce

  1.  bit.ly/istio-tutorial
  2. then minishift stop
  3. then minishift start
  4. oc login myip:8443 (admin,admin)
  5. oc project tutorial

### Expected
That the current project would switch to "tutorial"

### Actual
Yet it switches to "myproject" and seems to log me out.  I have also seen it switch me to "developer" and away from the admin account.

video: https://www.screencast.com/t/LYkNTDpQ

### Logs

no logs

**Comment by gbraad** [comment]
is this reproducible using an installed OpenShift cluster, or using an `oc cluster up` based cluster

**Comment by gbraad** [comment]
IS this the same as #1966 ?

**Comment by jorgemoralespou** [comment]
@gbraad should be the same.

**Comment by burrsutter** [comment]
Looks like the same issue as #1966 and upgraded to 1.12 and still see the same behavior.

**Comment by budhrg** [comment]
Closing it in favor of https://github.com/minishift/minishift/issues/1966 as latter has more discussion.
