### ISSUE TITLE
Documentation references potentially unavailable `sudo` command

### ISSUE THREAD

**Issue by robin-owen** [minishift/minishift#1957]
The documentation currently encourages the user to perform commands as root via `sudo`. Some systems (notably RHEL and CentOS) do not have `sudo` installed (or configured) by default.

Where applicable, I believe that we should use root directly in the documentation with a note that `sudo` can be used if available. This ensures that the documented procedures work on systems both with and without `sudo`.

Currently, these references exist in *_getting-started/setting-up-driver-plugin.adoc_* and *_troubleshooting/troubleshooting-driver-plugins.adoc_*.

Thoughts?

**Comment by LalatenduMohanty** [comment]
@robin-owen When a user tries to install driver plugins, we need root access in general as a normal user won't have write access to some of the filesystem locations. Maybe you can put the exact commands here so that we can investigate.

**Comment by robin-owen** [comment]
@LalatenduMohanty Correct, root access is required -- however, we don't always have access to the `sudo` command. As such, I suggest that we explicitly tell users which commands must be run as root.

For example, we currently have the following in our documentation:

```adoc
. Install the KVM binary as follows:
+
----
$ sudo curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.7.0/docker-machine-driver-kvm -o /usr/local/bin/docker-machine-driver-kvm
----

. Make the binary executable as follows:
+
----
$ sudo chmod +x /usr/local/bin/docker-machine-driver-kvm
----
```

I suggest the following instead:

```adoc
. As root, install the KVM binary and make it executable as follows:
+
----
# curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.7.0/docker-machine-driver-kvm -o /usr/local/bin/docker-machine-driver-kvm
# chmod +x /usr/local/bin/docker-machine-driver-kvm
----
```

We can always include a note that `sudo` can be used to run commands as root from a user account if necessary.

**Comment by gbraad** [comment]
So instead of describing `sudo`, we would have to write:

     As `root` perform the following commands

**Comment by robin-owen** [comment]
@gbraad Fair enough, and... yes, essentially. :)

**Comment by anjannath** [comment]
Is this fixed in the docs?

**Comment by robin-owen** [comment]
@anjannath Partially. PR #2025 addressed the use of `sudo` on Linux in the instructions for setting up the virtualization environment. There are still references to `sudo` which should be addressed in the troubleshooting documentation.

**Comment by anjannath** [comment]
I see.. so we keep this issue to track the changes needed for the trouble
shooting doc.. Right?
