### ISSUE TITLE
Documentation Request: Cygwin doesn't offer a TTY on Windows, breaks RHSM

### ISSUE THREAD

**Issue by wzzrd** [minishift/minishift#1959]
### General information

  * Minishift version: v1.11.0+d7f374a
  * OS: Windows
  * Hypervisor: Hyper-V / VirtualBox

The DevSuite installer installs Cygwin by default. It turns out, Cygwin has issues around providing a tty, which minishift needs (or at least, the CDK does) for registration on the RH customer portal.

Please document that cygwin is not supported and / or to use PowerShell instead.

**Comment by wzzrd** [comment]
Moved to https://issues.jboss.org/browse/CDK-247

**Comment by budhrg** [comment]
Thanks @wzzrd :smile:
