### ISSUE TITLE
Allow for interactive selection of the OpenShift version during 'minishift start'

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#197]
Following up on issue #68.

It would be nice, if the user by specifying a flag, could be interactively presented with the (compatible) OpenShift versions which can be used as part of 'minishift start'.

**Comment by LalatenduMohanty** [comment]
I think this is a must for CDK use case.

**Comment by praveenkumar** [comment]
@hferentschik Shouldn't we have it already now, I think we can close it?

**Comment by hferentschik** [comment]
No we have a way to list versions in a separate command, but no way to interactively chose a version. Whether this really is so important is another question.

**Comment by jeremyeder** [comment]
whats the command to list versions?

**Comment by jorgemoralespou** [comment]
@jeremyeder  

````
$ minishift openshift version list
The following OpenShift versions are available:
	- v1.5.1
	- v3.6.0-alpha.0
	- v3.6.0-alpha.1
	- v3.6.0-alpha.2
````

**Comment by budhrg** [comment]
Revisit during discussion of https://github.com/minishift/minishift/issues/1417.

**Comment by LalatenduMohanty** [comment]
@minishift/minishift-dev WDYT about this issue. I think we are pretty good with current user experience i.e. `minishift openshift version list` and we do not need change this.

**Comment by budhrg** [comment]
>  I think we are pretty good with current user experience i.e. minishift openshift version list and we do not need change this.

Yes. Better to close it instead of updating milestones each time.
