### ISSUE TITLE
minishift start prints password in clear text when RHSM connection fails

### ISSUE THREAD

**Issue by DuncanDoyle** [minishift/minishift#1972]
### General information

  * Minishift version: 
minishift v1.11.0+d7f374a
CDK v3.3.0-1

  * OS: Linux / macOS / Windows
macOS 10.12.6

  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox
xhyve

### Steps to reproduce
  1. Setup minishift: minishift setup-cdk
  2. Start minishift: minishift start
  3. Enter RHSM credentials
  4. If RHSM is not available, the command that failed is printed, which includes my password in clear text

### Expected
Password is not printed when RHSM subscription fails.

### Actual
Password is printed in clear text on failure.

### Logs
Startup logs (obviously replaced my real username and password with fake one):

Duncans-MacBook-Pro:loan-application-demo-client ddoyle$ minishift start
-- Starting profile 'minishift'
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ...................... OK
-- Registering machine using subscription-manager
   Red Hat Developers or Red Hat Subscription Management (RHSM) username: my-username
   Red Hat Developers or Red Hat Subscription Management (RHSM) password: [HIDDEN]
   Registration in progress ...................................... FAIL [2m10s]
Error to register VM: ssh command error:
command : sudo -E subscription-manager register --auto-attach --username my-username --password 'my-password1!'
err     : exit status 70
output  : Network error, unable to connect to server. Please see /var/log/rhsm/rhsm.log for more information.
Registering to: subscription.rhsm.redhat.com:443/subscription

**Comment by gbraad** [comment]
Known issue. Please file CDK specific issues at jira.jboss.org.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by anjannath** [comment]
https://issues.jboss.org/browse/CDK-248
