### ISSUE TITLE
Introduce 'Maintainer' as addon metadata field

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1976]
I think we an optional metadata field here for addon as `Maintainer` similar to Docker's MAINTAINER.

The reason is since the add-ons present in https://github.com/Minishift/minishift-addons are mostly community add-ons, at some point, we need to know who is maintaining which addon as part of [CI test](https://github.com/minishift/minishift-addons/issues/67) if any addon fails to install/apply, we should send the notification to the respective maintainer.

**Comment by anjannath** [comment]
This makes sense, but how are we going to contact the maintainer?  if the ci fails we notify the maintainer via mail? in that case the `Maintainer` field will also need to have the email besides github username... right?. 

But during development this would be very noisy as the ci is more likely to fail during development.

**Comment by budhrg** [comment]
> But during development this would be very noisy as the ci is more likely to fail during development.

We enable it only during nightly build after many successful iterations. That's my long-term idea.

**Comment by gbraad** [comment]
This has been on my mind for quite some time. This can help with offloading support and expectation from our side.

**Comment by praveenkumar** [comment]
Currently, if you have an addon below then it will not fail to parse at this moment. When you say it should be optional then this feature already their.  I am not sure what you want to implement as part of this?

```
 $ ./minishift addon list
- admin-user     : disabled   P(0)
- anyuid         : disabled   P(0)
- che            : disabled   P(0)
- istio          : disabled   P(0)
- registry-route : disabled   P(0)
- xpaas          : disabled   P(0)

12:08 $ cat ~/.minishift/addons/admin-user/admin-user.addon
# Name: admin-user
# Description: Create admin user and assign the cluster-admin role to it.
# Maintainer: kumarpraveen.nitdgp@gmail.com

oc create user admin --full-name=admin
oc adm policy add-cluster-role-to-user cluster-admin admin

12:09 $ ./minishift addon apply admin-user
-- Applying addon 'admin-user':..
```

**Comment by budhrg** [comment]
> At this moment you can have as many optional metadata as you want as part of an addon.

The only difference with currently available optional metadata fields like `Required-Vars` /`Var-Defaults` is these fields get verified.

> I am not sure what you want to implement as part of this?

Making `Maintainer` similar to `Required-Vars` optional field so that it can be verified during installation.

**Comment by praveenkumar** [comment]
> Making Maintainer similar to Required-Vars optional field so that it can be verified during installation

When you say verified, verified against what? Are you going to put a parser which will tell a valid email id/ Github username ...etc.?

**Comment by budhrg** [comment]
> When you say verified, verified against what? Are you going to put a parser which will tell a valid email id/ Github username ...etc.?

Yes, needed for notification through CI.

**Comment by jorgemoralespou** [comment]
-1 for this.
I agree with @praveenkumar that you can request addons maintainers to add that header if they wish. At the end, even if a maintainer get an email notification, he might not act on it ;-)

You can always use the name of the github user that contributed the addon, or all of those who have committed code to the addon.

**Comment by praveenkumar** [comment]
@budhrg I still think this is irrelevant for us atm and I am not sure if we put any effort on this front atm. Can we just close this issue or you still want to have a discussion around it?

**Comment by budhrg** [comment]
Closing it as looks like we have to properly document it in minishift-addons repo to add Maintainer field for addon developer.
