### ISSUE TITLE
Some unit tests do not use testify

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1980]
### General information
We still do not use `testify/assert` for assertions in some of the units tests. Maybe we missed it in the review. Refer the old issue for using testify https://github.com/minishift/minishift/issues/250 and the patch at https://github.com/minishift/minishift/commit/838f4d50ce96e022f4990d37ba56704869b2f250

  * Minishift version: Latest Master i.e.  acb558a890b0e3afb93304e57a418b355cbbda63 

### Actual
```
$ git grep 'Fatal'
cmd/minishift/cmd/delete_test.go:               t.Fatalf("Expected cache dir '%s' to be deleted", state.InstanceDirs.Cache)
cmd/minishift/cmd/delete_test.go:               t.Fatalf("Expected cache dir '%s' to still exist", state.InstanceDirs.Cache)
cmd/testing/cli/harness.go:             t.Fatal(err)
cmd/testing/cli/harness.go:             t.Fatalf("Unexpected error during setup: %s", err.Error())
cmd/testing/cli/harness.go:                     t.Fatalf("Expected error '%s'. Got '%s'.", expectedErrorMessage, tee.StderrBuffer.String())
cmd/testing/cli/harness.go:                     t.Fatalf("Expected exit code %d. Got %d.", expectedExitCode, code)
cmd/testing/cli/harness.go:             t.Fatal("The called method unexpectedly called atexit.")
cmd/testing/cli/harness.go:             t.Fatal(err)
cmd/testing/cli/harness.go:             t.Fatal(err)
cmd/testing/cli/harness.go:             t.Fatal(err)
cmd/testing/cli/viper.go:                       t.Fatalf("Config %s not read correctly: %v", testOption.ConfigValue, err)
pkg/minikube/kubeconfig/config_test.go:         t.Fatalf("Error delete file %s", testSystemConfigPath)
pkg/minikube/machine/client_test.go:            log.Fatal(err)
pkg/minishift/addon/manager/addon_manager_test.go:              t.Fatal(fmt.Sprintf("No error expected, but got: \"%s\"", err.Error()))
pkg/minishift/provisioner/minishift_detector_test.go:           t.Fatalf("Error starting ssh server: %s", err)
pkg/minishift/registration/redhat_test.go:              t.Fatalf("Error starting ssh server: %s", err)
pkg/testing/assert.go:          t.Fatalf("String slices do not match. Expected %v, got %v", expected, actual)
pkg/testing/assert.go:          t.Fatalf("String slices differ in length. Expected %v, got %v", expected, actual)
pkg/testing/assert.go:                  t.Fatalf("%s and %s differ. Expected %v, got %v", expected[i], actual[i], expected, actual)
pkg/testing/runner_mock.go:     t.Fatalf("Expected: %+v, Got: %+v\n", argStringOption, expectCommands[0].commandArgs)
pkg/testing/tee_test.go:                t.Fatalf("Unexpected error: %s", err.Error())
pkg/util/utils_test.go:         t.Fatal("Unpexpected OS")
pkg/util/utils_test.go:         t.Fatal("Unpexpected OS")
pkg/util/utils_test.go:         t.Fatal("Unpexpected OS")
```

**Comment by LalatenduMohanty** [comment]
I see below in delete_test.go
```

	if filehelper.Exists(state.InstanceDirs.Cache) {
		t.Fatalf("Expected cache dir '%s' to be deleted", state.InstanceDirs.Cache)
	}
``` 
Which can be fixed by using https://godoc.org/github.com/stretchr/testify/assert#DirExists

**Comment by budhrg** [comment]
```
$ git grep 'Fatal' -- '*_test.go'
cmd/minishift/cmd/delete_test.go:               t.Fatalf("Expected cache dir '%s' to be deleted", state.InstanceDirs.Cache)
cmd/minishift/cmd/delete_test.go:               t.Fatalf("Expected cache dir '%s' to still exist", state.InstanceDirs.Cache)
pkg/minikube/kubeconfig/config_test.go:         t.Fatalf("Error delete file %s", testSystemConfigPath)
pkg/minikube/machine/client_test.go:            log.Fatal(err)
pkg/minishift/addon/manager/addon_manager_test.go:              t.Fatal(fmt.Sprintf("No error expected, but got: \"%s\"", err.Error()))
pkg/minishift/provisioner/minishift_detector_test.go:           t.Fatalf("Error starting ssh server: %s", err)
pkg/minishift/registration/redhat_test.go:              t.Fatalf("Error starting ssh server: %s", err)
pkg/testing/tee_test.go:                t.Fatalf("Unexpected error: %s", err.Error())
pkg/util/utils_test.go:         t.Fatal("Unpexpected OS")
pkg/util/utils_test.go:         t.Fatal("Unpexpected OS")
pkg/util/utils_test.go:         t.Fatal("Unpexpected OS")
```

Out of above files, I see `cmd/minishift/cmd/delete_test.go` need to be updated. Rest it seems to be only setup and helper function which doesn't make sense in asserting.

**Comment by LalatenduMohanty** [comment]
@budhrg why can not we use https://godoc.org/github.com/stretchr/testify/assert#Assertions.FailNow in place of `Fatal` as it provides better assertions?

**Comment by budhrg** [comment]
What is better assertions here?

**Comment by anjannath** [comment]
The `delete_test.go` needs to be changed, the others are setup functions, In the original [PR#comment](https://github.com/minishift/minishift/pull/1755#discussion_r163815922) we decided to not use assertions in test setup, because we are not really asserting anything, and **if** conditions are more symatically correct in that context.

**Comment by LalatenduMohanty** [comment]
@budhrg @anjannath  I see this in pkg/minishift/addon/manager/addon_manager_test.go and this shoul dbe fixed. 
```
	if err != nil {
		t.Fatal(fmt.Sprintf("No error expected, but got: \"%s\"", err.Error()))
	}
```

**Comment by LalatenduMohanty** [comment]
> Rest it seems to be only setup and helper function which doesn't make sense in asserting.

@budhrg the setup functions also part of unit tests, we should fix it. Not sure why you think we should not fix them

**Comment by budhrg** [comment]
>  the setup functions also part of unit tests, we should fix it. Not sure why you think we should not fix them

Because we are not verifying there by expecting anything in the setUp by creating temporary directory or other. The error is unusual here.

**Comment by LalatenduMohanty** [comment]
> Because we are not verifying there by expecting anything in the setUp by creating temporary directory or other. The error is unusual here.

I do not agree. So you are fine if I create some setup functions and the failures in these functions we do not use testify. What about consistency?

**Comment by budhrg** [comment]
> What about consistency?

I think it's not about consistency here. There is the difference in the if being used in `setUp` and inside `Test*` function as in the later we are verifying something but not in the `setUp`. Seems overkill of using `assert` in `setUp`.

**Comment by LalatenduMohanty** [comment]
@budhrg -1 .If in the setup you are doing any `minishift` openration or running any `minishift` command then the rules for writting tests are also applicable. @minishift/minishift-dev comments?

**Comment by LalatenduMohanty** [comment]
@budhrg What is your opinion about https://github.com/minishift/minishift/issues/1980#issuecomment-363380707?

**Comment by anjannath** [comment]
I agree with @budhrg here, using `assert` in `setUp` seems like an overkill.

**Comment by LalatenduMohanty** [comment]
> I agree with @budhrg here, using assert in setUp seems like an overkill.

Can you give an example? Are you talking about https://github.com/minishift/minishift/issues/1980#issuecomment-363380707?

**Comment by anjannath** [comment]
about [#1980 (comment)](https://github.com/minishift/minishift/issues/1980#issuecomment-363380707)
in `pkg/minishift/provisioner/minishift_detector_test.go` needs change, but in case of `pkg/minishift/addon/manager/addon_manager_test.go` we don't need change IMO, as that is a helper function for the tests, not actually a test.

**Comment by budhrg** [comment]
> pkg/minishift/addon/manager/addon_manager_test.go

Here, it seems to be valid to assert as it is part of `Test*` functions.

> pkg/minishift/provisioner/minishift_detector_test.go

Here, it got missed I guess as in the next test functions, he used assert.

**Comment by LalatenduMohanty** [comment]
> pkg/minishift/addon/manager/addon_manager_test.go
> Here, it seems to be valid to assert as it is part of Test* functions.
+1. @anjannath function `getAddOnMetadata` is used in 4 unit tests so it is part of unit tests. The reason it is a separate function because other unit tests re-use the code.

**Comment by anjannath** [comment]
Exactly the reason it is called from 4 unit tests makes it a helper function. `setUp` finctions are also used in the unit tests.

If we want `getAddOnMetadat` also to be tested, we need to wrap this function inside a `Test*` function, or else it is not a unit test, we are testing more than one units inside one function. then we can run it as a unit test using `go test`

**Comment by budhrg** [comment]
`getAddOnMetadata` is not a proper helper function and should be removed. 
We should however use
```
addOnMeta, err := addon.NewAddOnMeta(testMap)
assert.NoError(t, err, "message")
```

IMO, the proper helper function is `getTestAddonMap`.

**Comment by LalatenduMohanty** [comment]
@budhrg works for me.
