### ISSUE TITLE
Use a user friendly error message when no *.addon.remove file available

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#1986]
### General information

  * Minishift version: master 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce
```
  1. ./minishift start
  2. ./minishift addons apply anyuid
  3. ./minishift addons remove anyuid
      No anyuid.addon.remove file found for 'anyuid' add-on.
  ```

### Expected
```
   $ ./minishift addons remove anyuid
      Unable to remove addon: 'anyuid'. No anyuid.addon.remove file is found.
```

Out put should be something like as mentioned above suggested by @gbraad 

### Actual
$ ./minishift addons remove anyuid
No anyuid.addon.remove file found for 'anyuid' add-on.

By seeing this output user can have a feeling of something went wrong in the addon remove process which is actually baseless. Moreover this addons can not be removed once applied, hence no .remove file is available.    

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
I added `good first issue` label, if we don't get a newbie contributor then will take it during '1.15.0` milestone.

**Comment by amitkrout** [comment]
@praveenkumar i want to take this. This way i get some more exposer to minishift addons and its work flow

**Comment by praveenkumar** [comment]
@amitkrout I set milestone `1.15.0` so if you want to do it now please adjust the milestone accordingly.

**Comment by LalatenduMohanty** [comment]
@anjannath @minishift/minishift-dev Usually for issues which are not planned for a milestone but it is getting fixed because it is easy or someone wants to fix it then we do not want to add the current milestone to it. But when the issue gets resolved we should add the correct milestone. Adding the current milestone means it needs to be fixed in this milestone because it is important.

**Comment by anjannath** [comment]
@LalatenduMohanty Ahh, I didn't know it was done like that, Thanks for making it clear, Will remember it.
