### ISSUE TITLE
Rethink about having vendor as part of repo

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1988]
Recently https://github.com/jteeuwen/go-bindata/ just vanished and all the minishift CI fails because of it. Since we are now consuming a lot of GitHub packages so might be it's good to have vendor as part of repo like other projects have. 

I know in past we didn't allow because it makes repo bulky but I think it's just a trade-off if something like this happens in future.

**Comment by gbraad** [comment]
On Wed, Feb 7, 2018 at 7:15 PM, Praveen Kumar <notifications@github.com>
wrote:

> I know in past we didn't allow because it makes repo bulky but I think
> it's just a trade-off if something like this happens in future.
>

We can consider using a git submodule which stores the vendor directory,
which is a separate repo called minishift/vendor

**Comment by LalatenduMohanty** [comment]
I was thinking about it too.  AFAIR the initial clone was taking a lot of time and it slowed the process somehow, but seeing the go-bindata issue it is worth exploring.

**Comment by LalatenduMohanty** [comment]
> We can consider using a git submodule which stores the vendor directory, which is a separate repo called minishift/vendor

I won't suggest this, because it needs code changes and would need extra steps to keep the vendor submodule up to date. Not sure if I understand it correctly.

**Comment by gbraad** [comment]
This would not need code changes, as the repo will pull the original
references


-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by gbraad** [comment]
https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree

**Comment by praveenkumar** [comment]
Let's explore any of those, my understanding most of go lang project always have `vendor` in the same repo instead of `subtree` or `submodule` but explore and see what makes more sense for us.

**Comment by praveenkumar** [comment]
@gbraad Are you still in favor of using git-subtree instead of making it part of default repo itself?

I went through the given tutorial but as it says there are few drawbacks. Do you think for new contributor this is not a bit blocker point if he has to add/remove some dependency?

- You must learn about a new merge strategy (i.e. git subtree).
- Contributing code back upstream for the sub-projects is slightly more complicated.
- The responsibility of not mixing super and sub-project code in commits lies with you.

**Comment by gbraad** [comment]
sure it is a little bit more troublesome, but not unknown...
the submodule is JUST a sha reference to a version inside that repo.

so, what is the alternative to use?

**Comment by praveenkumar** [comment]
> so, what is the alternative to use?

@gbraad have `vendor` directly to be part of this repo.

**Comment by LalatenduMohanty** [comment]
Resolved via #2405
