### ISSUE TITLE
Update `Makefile` to get `go-bindata` from minishift namespace

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#1989]
### General information

  * Minishift version:  master
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Expected
`go-bindata` to be pulled from `https://github.com/jteeuwen/go-bindata`
and CI to run

### Actual
the repo and user disappered from github, and CI is failing

**Comment by budhrg** [comment]
As per the comment on the issue created here https://github.com/jteeuwen/go-bindata/issues/5#issue-295358043

> I’m a friend of the repo owner. The current owner is not the original jteeuwen, and we have no relation with him, nor do we want to take any credit. We have no way to know what happened to jteeuwen.

> The intention of this account and repo was simply to fix the building of a private project. The current owner had no way to directly redirect the repo, so he made such work-around so that he could safely go home without being blamed by his supervisor. And of course, hoped this would also save someone else trapped in similar situation.

> Current status of this repo is the latest snapshot he has (and probably the latest snapshot). We do not intend to update this repo so far, since that is beyond our intention. There is some pretty good forks out there, well-maintained.

It seems that this repo https://github.com/jteeuwen/go-bindata will not go away randomly like the last time. Until, there is potential outcome comes from the community in the above issue, let's not do anything and keep https://github.com/jteeuwen/go-bindata only or else move to some well-maintained fork like https://github.com/kevinburke/go-bindata.

Using our own forked and then switch back to someone else fork seems like back and forth to me.

**Comment by LalatenduMohanty** [comment]
Closing the issue as we do not want to move to your own fork.
