### ISSUE TITLE
Show app builds logs during integration tests on failure

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1994]
As part of this PR https://github.com/minishift/minishift/pull/1951, we exposed logs of `stdout` and `stderr` which is not helping much IMO

![screenshot from 2018-02-08 12-24-32](https://user-images.githubusercontent.com/1132451/35959324-1ea78110-0ccb-11e8-94d0-6a8bfb2901e4.png)

It would be great if we get logs of origin container and application container logs on failure.
Really getting difficult to debug https://github.com/minishift/minishift/issues/1857 and https://github.com/minishift/minishift/issues/1993

**Comment by amitkrout** [comment]
@budhrg We logging the details in out/test-result/integration_*.log file. If we get that publish somewhere in the ci, i dont think this code change is required. Isn't is doable ?

**Comment by LalatenduMohanty** [comment]
@budhrg I am curious to know what extra information you will find in application container logs.

**Comment by budhrg** [comment]
> @budhrg I am curious to know what extra information you will find in application container logs.

@LalatenduMohanty See https://github.com/minishift/minishift/pull/2000#issue-168212051
which is telling reason of timeout.
