### ISSUE TITLE
Problem starting minishift on linux

### ISSUE THREAD

**Issue by cleberlira** [minishift/minishift#1998]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

I installed Minishift as described : 
https://docs.openshift.org/latest/minishift/getting-started/installing.html

But  i am with problem for to start  minishift on Ubuntu 16.04 lts.  

-- Starting profile 'minishift'
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... FAIL
   See the 'Setting Up the Driver Plug-in' topic (https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html) for more information
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM ........................ OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 7% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.1
-- Checking `oc` support for startup flags ... 
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   routing-suffix ... OK
Starting OpenShift using openshift/origin:v3.6.1 ...

I need help for solution this problem.

**Comment by praveenkumar** [comment]
@cleberlira as per your log I don't see any error message which fails minishift to start. Can you please share the complete log include error message?

**Comment by cleberlira** [comment]
@praveenkumar After line "Starting OpenShift using openshift/origin:v3.6.1 ..."  nothing else is executed.

 The server is not accessible via web console at:
       https://192.168.99.128:8443 as described in https://docs.openshift.org/latest/minishift/getting-started/quickstart.html.  

no message appears " OpenShift server started."

Do you understand now?

**Comment by praveenkumar** [comment]
@cleberlira Thanks for informing. Closing this issue now.

**Comment by mwaeckerlin** [comment]
@cleberlira, how did you solve the problem?

I have the same problem, but  `./minishift-1.14.0-linux-amd64/minishift start` aborts after the line `-- Checking if Libvirt default network is active ... FAIL`:
```
marc@jupiter:~/Downloads/openshift$ ./minishift-1.14.0-linux-amd64/minishift start-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.7.1' is valid ... OK
-- Checking if requested OpenShift version 'v3.7.1' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... FAIL
   See the 'Setting Up the Driver Plug-in' topic (https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html) for more information
```

What's wrong?
How to fix it?

The given URL does not help,I already follwed all steps mentioned there.

**Comment by gbraad** [comment]
He solved it by being patient and just wait...

... this is the issue I had with the console output changes that `oc cluster up` made. It is now TOO silent... I'd rather see them doing a progress dot... or we introduce it.

**Comment by gbraad** [comment]
@mwaeckerlin can you please file a new issue but this feels like you haven't defined the default network. More info is needed... so file a new issue...
