### ISSUE TITLE
validate_commits fails intermittently for some pull requests

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2001]
validate_commits failed for PR #1975.
Tried with commit messages: `Issue #1970 Moving integration test code to a separate go package` and also `Issue #1639 Switch to overlay2 as default storage driver for docker`, does not seem like a problem with regex check.

```bash
cd "../src/github.com/minishift/minishift"
make validate_commits

go get -u github.com/vbatts/git-validation/...
git-validation -q -run short-subject,message_regexp='^(Issue #[0-9]+ .*|cut v[0-9]+\.[0-9]+\.[0-9]+)$' -range 204ce1930e8a86d0c5b5eabd1d8b8dbf8d9edac3...
ERRO[0000] mm[git] cmd: "git --no-pager log --pretty=format:%H 204ce1930e8a86d0c5b5eabd1d8b8dbf8d9edac3..." 
2018/02/09 04:27:59 exit status 128
make: *** [validate_commits] Error 1

cd "../src/github.com/minishift/minishift"
make validate_commits
 returned exit code 2
```

Locally it works fine for me and @praveenkumar.

**Comment by LalatenduMohanty** [comment]
@agajdosi I guess we can close this issue as it was not an issue wiith the git validation but somehow the CI was picking a wrong commit to validate.

**Comment by agajdosi** [comment]
@LalatenduMohanty Agree, lets reopen if the issue appears again.
