### ISSUE TITLE
Print OpenShift restart message post its restart operation

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#2012]
### Expected

Right now we are printing message of `Restarting OpenShift` before running restart operation through commander.
https://github.com/minishift/minishift/blob/c5ad41134f490ff6d3c5ff9ae7cf5f7285bbf8c4/pkg/minishift/openshift/openshift.go#L71-L78

And with using this message in the `cmd-openshift.feature` 
https://github.com/minishift/minishift/blob/c5ad41134f490ff6d3c5ff9ae7cf5f7285bbf8c4/test/integration/features/cmd-openshift.feature#L34-L35

it is giving false assumption that at this point Openshift has been restarted.

### Actual

The message should be printed after restart operation.

**Comment by gbraad** [comment]
This would have been a good issue for a newcomer.

**Comment by praveenkumar** [comment]
resolved by #2013
