### ISSUE TITLE
Refactor download code for Github assets

### ISSUE THREAD

**Issue by coolbrg** [minishift/minishift#2015]
Lot of code duplication is there in the Github assets (ISO, binary)
See https://github.com/minishift/minishift/blob/master/pkg/util/github/github.go#L93
and 
https://github.com/minishift/minishift/blob/master/pkg/minikube/cluster/cluster.go#L188

**Comment by gbraad** [comment]
Task #2015 is technical debt... it is not a simple refactor effort anymore. And therefore, this needs to be 'planned'... or taking in small increments over time.
