### ISSUE TITLE
minishift openshift restart is causing regression for origin version > v3.7.0

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2016]
### General information
`minishift openshift restart` for Origin version > v3.7.0 needs extra time to make the OpenShift instance ready to use.

 For example `minishift openshift registry` or `oc new app` commands are failing after `minishift openshift restart`.

  * Minishift version:  v1.13.0
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

In order to update default Minishift version to v3.7.1 (in PR #1808) we have do modify the test as below in test/integration/features/cmd-openshift.feature

```diff 
  Scenario: User deploys nodejs example application from OpenShift repository
-      When executing "oc new-app https://github.com/openshift/nodejs-ex -l name=myapp" succeeds
+     Given Minishift has state "Running"
+      When executing "oc new-app https://github.com/openshift/nodejs-ex -l name=myapp" retrying 10 times with wait period of 2 seconds
       Then stdout should contain
```
### Steps to reproduce

```
$ minishift openshift restart;minishift openshift registry
Restarting OpenShift
No information found for 'service/docker-registry'

$ minishift openshift restart;sleep 2; minishift openshift registry
Restarting OpenShift
172.30.1.1:5000
```

**Comment by budhrg** [comment]
Similar experience here [minishift openshift restart can break router and Docker registry pods](https://github.com/minishift/minishift/issues/2169).

**Comment by praveenkumar** [comment]
@LalatenduMohanty @agajdosi doesn't this now fixed?

**Comment by praveenkumar** [comment]
@LalatenduMohanty @agajdosi any update on this?

**Comment by agajdosi** [comment]
@praveenkumar From logs on passing PRs it looks fine, no retries reported:
- https://ci.centos.org/job/minishift-pr/4677/consoleFull
- https://ci.centos.org/job/minishift-pr/4674/consoleFull
- https://ci.centos.org/job/minishift-pr/4669/consoleFull
- https://ci.centos.org/job/minishift-pr/4651/consoleFull
- https://ci.centos.org/job/minishift-pr/4648/consoleFull

Can create a PR to remove it, or we can wait for oc v3.10.x becoming default and then see how it goes, wdyt?

**Comment by LalatenduMohanty** [comment]
@agajdosi I think lets keep ot as it is as we are moving towards OpenShift 4.0
