### ISSUE TITLE
Investigate and document the various ways to control the minishift options using Viper

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#202]
Viper allows to take configuration from various sources (persistent config, env variables, CLI switches) and defines a hierarchy in which they apply. We need to write some tests to demonstrate that it works and how. Then we need some tutorial outlining these type of options to the user.

**Comment by Preeticp** [comment]
@hferentschik could you please help me understand if and how this issue is different from #178. Are they both related, if so would it be better if one person deals with both documentation tasks or can I pick this issue?

**Comment by hferentschik** [comment]
@Preeticp this is really a duplicate, so I am going to close it.
