### ISSUE TITLE
Unable to use underscore in profile name for centos iso

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#2020]
### General information

  * Minishift version: Version supporting profile 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox
  * ISO : CentOS

### Steps to reproduce

  1. `minishift start --profile centos1_5 --iso-url centos`

### Expected

We should error out saying invalid profile name.

### Actual

Getting error.

### Logs

```
$ minishift start --profile centos1_5 --iso-url https://github.com/minishift/minishift-centos-iso/releases/download/v1.5.0/minishift-centos7.iso
-- Starting profile 'centos1_5'
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.5.0/minishift-centos7.iso'
 66.25 MiB / 324.00 MiB [==============================>-----------------------------------------------------------------------------------------------------------------------]  20.45% 8m12s 324.00 MiB / 324.00 MiB [========================================================================================================================================================] 100.00% 0s
-- Starting Minishift VM ................ FAIL E0213 13:22:20.689553   18400 start.go:368] Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: ssh command error:
command : sudo hostname centos1_5 && echo "centos1_5" | sudo tee /etc/hostname
err     : exit status 1
output  : hostname: the specified hostname is invalid
. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: ssh command error:
command : sudo hostname centos1_5 && echo "centos1_5" | sudo tee /etc/hostname
err     : exit status 1
output  : hostname: the specified hostname is invalid
```

**Comment by LalatenduMohanty** [comment]
As @praveenkumar suggested, it seems like CentOS does not accept a  hostname with a `_`. 
```
$ hostname hello_bye
hostname: the specified hostname is invalid

[docker@minishift ~]$ cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core) 
```

**Comment by LalatenduMohanty** [comment]
It seems we have this issue from the beginning of profile feature. So, in that case, this needs to be communicated to the user along with documenting it.

**Comment by anjannath** [comment]
But `centos1_5` is a valid profile name, we should fix it somehow IMO. maybe avoid `_` when changing the hostname, but allow the profile to consist `_`.

**Comment by gbraad** [comment]
Pick an option?

1. Disallow the use of `_` in profilenames
2. Rewrite profilename when used as hostname, by substituting `_` to `-` or ``.

**Comment by LalatenduMohanty** [comment]
> But centos1_5 is a valid profile name, we should fix it somehow IMO. maybe avoid _ when changing the hostname, but allow the profile to consist _.

It is a valid name because we said so. The reason we agreed to `_` because we thought it would be fine by hypervisors as VM names. But now that CentOS has an issue with it I am not sure anymore. What about checking for profiles names in preflight check and communicate to the user if `_` and CentOS/RHEL is used together. Also adding in the documentation that `underscore` is not accepted when using CentOS/RHEL.

**Comment by praveenkumar** [comment]
> Pick an option?

I would go with option 1, instead of manipulating profile name and hostname differently. Easy to manage and do. The good thing is till now we didn't get this as a bug from users side, either everyone using `b2d` what comes default or nobody used `_` as a profile name.

**Comment by anjannath** [comment]
> What about checking for profiles names in preflight check and communicate to the user if _ and CentOS/RHEL is used together. 

This feels like a better option to me, this way we don't entirely loose `_` in profile names.

> Also adding in the documentation that underscore is not accepted when using CentOS/RHEL.

+1

**Comment by anjannath** [comment]
Since this is a minor issue and as @praveenkumar highlihted 
>The good thing is till now we didn't get this as a bug from users side, either everyone using b2d what comes default or nobody used _ as a profile name.

We decided to pick Option 1  and also update the docs to convey this message.

**Comment by budhrg** [comment]
> What about checking for profiles names in preflight check and communicate to the user if _ and CentOS/RHEL is used together. Also adding in the documentation that underscore is not accepted when using CentOS/RHEL

This will create inconsistent behavior across ISOs. If we are not supporting `_` for CentOS/RHEL, I don't see any point in supporting b2d/minikube too.
