### ISSUE TITLE
Revert docker storage driver and Centos ISO release

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2021]
### General information

  * Minishift version: 1.13.0
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. minishift start --iso-url centos
  2. eval $(minishift oc-env)
  3. oc new-app https://github.com/openshift/nodejs-ex -l name=myapp

```
$ oc logs -f bc/nodejs-ex
Cloning "https://github.com/openshift/nodejs-ex" ...
	Commit:	ef1b71a300b58a35f37acfa69f871fc18075669d (Merge pull request #160 from aliok/patch-1)
	Author:	Ben Parees <bparees@users.noreply.github.com>
	Date:	Fri Jan 12 10:16:26 2018 -0500
tar: /tmp: Cannot open: Permission denied
tar: Error is not recoverable: exiting now
error: build error: non-zero (13) exit code from centos/nodejs-6-centos7@sha256:c51779bbc13bc9f3bb871d14cf549090a1686942c1cb77228b39af02139d3167
```

### Expected
Application creation should be successful.

### Actual

```
tar: /tmp: Cannot open: Permission denied
tar: Error is not recoverable: exiting now
error: build error: non-zero (13) exit code from centos/nodejs-6-centos7@sha256:c51779bbc13bc9f3bb871d14cf549090a1686942c1cb77228b39af02139d3167
```

**Comment by LalatenduMohanty** [comment]
@praveenkumar I think we can close this as we found a fix to the issue in CentOS ISO.

**Comment by praveenkumar** [comment]
yes closing it now.

**Comment by LalatenduMohanty** [comment]
Minishift version v1.13.1 has the fixed CentOS ISO version. https://github.com/minishift/minishift/pull/2031

**Comment by vlaskovic** [comment]
On Windows 10, VirtualBox with minishift v1.16.1+d9a86c9

oc v3.7.14
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v3.9.0+8e3cb9b-8
kubernetes v1.9.1+a0ce1bc657

same error is received:
Receiving source from STDIN as archive ...
tar: /tmp: Cannot open: Permission denied
tar: Error is not recoverable: exiting now
ERROR: Error copying file "/tmp/upload/src/maven/xxx.jar" to tar: io: read/write on closed pipe
ERROR: Error writing tar: io: read/write on closed pipe
error: build error: write unix @->/var/run/docker.sock: write: broken pipe

Application status: failed.


Thank you.
