### ISSUE TITLE
Create intergration test suite binary to e2e test for ISO

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2023]
Since now we have the minishift integration test as part of a separate package, it would be nice if we can create test suite binary out of it and that we can use on the CI to test our ISO changes. 

1. We need to add required step in the Makefile to create that binary
2. need to publish it nightly from the master so that CI can pick it up and start testing.

**Comment by budhrg** [comment]
@praveenkumar , I think we are not going this way now right? Can we close it?

**Comment by praveenkumar** [comment]
@budhrg yes, for the ISO testing purpose we are taking a different approach, where we are going to pull down the minishift repo and then run the test against the ISO. I am closing this issue now.
