### ISSUE TITLE
--iso-url is not correct in cmd-config.feature file for a specified location

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2027]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Expected
| iso-url         | file:///home/me/Downloads/my_handmade_b2d.iso

### Actual
https://github.com/minishift/minishift/blob/master/test/integration/features/cmd-config.feature#L175

**Comment by LalatenduMohanty** [comment]
@amitkrout I do not think I understand the issue. It looks alright to me, can you please explain little more?

**Comment by amitkrout** [comment]
@LalatenduMohanty The protocol added to the file location is wrong. AFAIU it should be file:// then followed by the path for example  
```
| iso-url         | file:///home/me/Downloads/my_handmade_b2d.iso
```

**Comment by LalatenduMohanty** [comment]
@amitkrout  got it, it should be `///` instead of `//` on Linux or macOS https://docs.openshift.org/latest/minishift/using/basic-usage.html#choosing-iso-image

**Comment by amitkrout** [comment]
@LalatenduMohanty thanks for sharing the doc. It is more clear to me now. Will add the values in the pr, atleast anybody can distinguish the path protocol for linux/mac and windows.

**Comment by anjannath** [comment]
`minishift config set` for iso-url doesn't perform the same checks as the preflight check for iso-url.
But after #1897 is merged the validation will check all the cases.

**Comment by anjannath** [comment]
The validation for iso-url is not the same as the preflight check, So this did not lead to an error.
```
➜  ~ minishift config set iso-url file://home/anath/iso.iso
You currently have an existing Minishift instance. Changes to the 'iso-url' setting are only applied when a new Minishift instance is created.
To let the configuration changes take effect, you must delete the current instance with 'minishift delete' and then start a new one with 'minishift start'.
➜  ~ minishift config view
- image-caching        : true
- iso-url              : file://home/anath/iso.iso
```
------------------------------------------------------------------------------------------------------------------------
But thanks to @praveenkumar after #1997 is merged this will be fixed.
