### ISSUE TITLE
Improve installation documentation

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#203]
We should improve the documentation for installation section [1] . Here are some suggestion.

 * We should mention respective docker-machine-driver for respective virtualization driver e.g. KVM section should have link to install instruction for docker-machine-kvm driver
* Exact steps with example, user needs to do for installation of minishift.
* Example of minishift command  with `--vm-driver=xxx`

[1] https://github.com/minishift/minishift#installation
[2] https://github.com/minishift/minishift/blob/master/docs/docker-machine-drivers.md

**Comment by hferentschik** [comment]
Merged via pull request #245
