### ISSUE TITLE
Merge provision-earlier-version and provision-various-versions feature file

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2048]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Expected
IMO its invalid to keep ```provision-earlier-version.feature``` file where same usecase is covered in ```provision-various-versions.feature``` file. Also there are some scenario step in provision-earlier-version which can be tested on all combination of openshift and oc version if merging to provision-various-versions feature file. Moreover it will be cost effective for ci (ci time will be reduced by approximately one vm provision) 

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by LalatenduMohanty** [comment]
Resolved by #2061  https://github.com/minishift/minishift/commit/0ef2dec5065f6fb1b141630963bfec4c99a04042
