### ISSUE TITLE
Minishift 1.13 (Openshift 3.7.1) Unable to deploy applications MacOs/xhyve

### ISSUE THREAD

**Issue by jcperezamin** [minishift/minishift#2051]
### General information

  * Minishift version: minishift v1.13.1+75352e5
  * OS: Linux / macOS / Windows: MacOS
  * Hypervisor: xhyve 

### Steps to reproduce

  1.  When you need to create a deployment

### Expected
 Deployment Config and Running Application

### Actual
failed to open log file "/var/log/pods/b736af57-1645-11e8-806c-be5168be744f/git-clone_0.log": open /var/log/pods/b736af57-1645-11e8-806c-be5168be744f/git-clone_0.log: no such file or directory

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by jcperezamin** [comment]
Reason: cannot trigger a deployment for "apache" because it contains unresolved images

**Comment by praveenkumar** [comment]
@jcperezamin this is a known-issue if you used `1.13.0` with centos iso 1.6.0, We request you to do following and let us know if still you have same issue.

```
$ minishift version
minishift v1.13.1+<rel_hash>

$ minishift delete --force
$ minishift start
```

**Comment by jcperezamin** [comment]
Same error:
An error occurred while starting the deployment.
 Reason: cannot trigger a deployment for "nodejs" because it contains unresolved images

Creating nodejs app:
Cloning "https://github.com/openshift/nodejs-ex.git " ...
	Commit:	ef1b71a300b58a35f37acfa69f871fc18075669d (Merge pull request #160 from aliok/patch-1)
	Author:	Ben Parees <bparees@users.noreply.github.com>
	Date:	Fri Jan 12 10:16:26 2018 -0500
tar: /tmp: Cannot open: Permission denied
tar: Error is not recoverable: exiting now
error: build error: read unix @->/var/run/docker.sock: read: connection reset by peer

**Comment by anjannath** [comment]
@jcperezamin You need to update your version of minishift use `minishift update` or just use the [centOS iso v1.6.1](https://github.com/minishift/minishift-centos-iso/releases/tag/v1.6.1), please refer to #2029 and [minishift/minishift-centos-iso#216](https://github.com/minishift/minishift-centos-iso/issues/216) for more details.

**Comment by jcperezamin** [comment]
Fixed it, Thanks! a lot!
