### ISSUE TITLE
Document available Gherkin step definitions

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2053]
Right now the only way to get understanding about Gherkin steps available in Minishift is to read the feature files or dive into their Go implementation itself. As part of documentation we should provide curated overview of the steps which are available.

Proposed document will be also helpful for the contributors of https://github.com/minishift/minishift-addons/ repository once the addition of Minishift integration tests is merged there.

**Comment by budhram** [comment]
Resolved by https://github.com/minishift/minishift/pull/2619
