### ISSUE TITLE
'minishift update' should check write permissions before downloading

### ISSUE THREAD

**Issue by containscafeine** [minishift/minishift#2056]
### General information

  * Minishift version: 1.12.0
  * OS: Linux
  * Hypervisor: KVM

### Steps to reproduce

  1. Run `minishift update`

### Expected
`minishift update` should check if it has write permissions to the target directory for installation before downloading the latest release, not after. Once this fails, I need to run `sudo minishift update` again which again downloads the binary. This is a bit painful because downloads from GitHub are generally slow.

### Actual
```console
$ minishift update
A newer version of minishift is available.
Do you want to update from 1.12.0 to 1.13.1 now? [y/N]: y
Downloading https://github.com/minishift/minishift/releases/download/v1.13.1/minishift-1.13.1-linux-amd64.tgz
 5.19 MiB / 5.19 MiB [=============================================================================================] 100.00% 0s
 65 B / 65 B [=====================================================================================================] 100.00% 0s
Update failed: open /usr/local/bin/.minishift.new: permission denied
```

**Comment by budhrg** [comment]
> Once this fails, I need to run sudo minishift update again which again downloads the binary. This is a bit painful because downloads from GitHub are generally slow.

@containscafeine Are you expecting to get message like 
```
$ minishift update
A newer version of minishift is available.
Do you want to update from 1.12.0 to 1.13.1 now? [y/N]: y
Permission denied!
Please try running this command again as root or sudo permission.
```

Let me know if there is any changes needed in above texts.

**Comment by containscafeine** [comment]
nit: `You don't seem to have write permissions on the directory: <directory name>. Please try running the command again as root, or using sudo.`
But yeah LGTM :man_shrugging:

**Comment by budhrg** [comment]
@containscafeine On running `sudo minishift update` I get following error
```
$ sudo minishift update
sudo: minishift: command not found
```

I need to do 
```
$ sudo `which minishift` update
A newer version of minishift is available.
Do you want to update from 1.13.0 to 1.13.1 now? [y/N]: 
[...]
```
Any idea?

**Comment by containscafeine** [comment]
@budhrg I think that's because minishift is not there in root's $PATH. If you add it to $PATH in  your /root/.bashrc, it should work.

**Comment by gbraad** [comment]
sudo ./minishift update

Or make sure it is in your path. The user and sudo might have different
profiles and settings.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by LalatenduMohanty** [comment]
I do not think we should recommend users to run the update command using sudo as it will create the new minishift binary with root permissions.  We should tell the user fix the permission issue and then run the update command again. 

@budhrg did you test the scenario? and what is your findings?

**Comment by budhrg** [comment]
@LalatenduMohanty , you are right. The update binary is created with root permissions.

```
$ ls -l /usr/local/bin/minishift
-rwxrwxr-x. 1 budhram budhram 24638488 Mar  6 14:56 /usr/local/bin/minishift

$ sudo `which minishift` update
A newer version of minishift is available.
Do you want to update from 1.13.1 to 1.14.0 now? [y/N]: y
Downloading https://github.com/minishift/minishift/releases/download/v1.14.0/minishift-1.14.0-linux-amd64.tgz
 5.11 MiB / 5.11 MiB [============================================================================================================================================================] 100.00% 0s
 65 B / 65 B [====================================================================================================================================================================] 100.00% 0s

Updated successfully to Minishift version 1.14.0.

Do you want to update the default add-ons? [y/N]: y
Default add-ons will be updated the next time you run any 'minishift' command.

$ ls -l /usr/local/bin/minishift
-rwxr-xr-x. 1 root root 15071616 Mar  6 15:01 /usr/local/bin/minishift
```

> We should tell the user fix the permission issue and then run the update command again.

This seems to the defensive solution and looks fine to me.

WDYT @containscafeine ?

**Comment by containscafeine** [comment]
I agree with @LalatenduMohanty that this should not ask the users to update using root/sudo, instead it should ask them to fix the permissions in the installation path.
Another way is to actually recommend sudo, but explicitly setting the permissions to the binary to the user set in the env var $SUDO_USER.

**Comment by budhrg** [comment]
@LalatenduMohanty fixed the message.

**Comment by anjannath** [comment]
> Another way is to actually recommend sudo, but explicitly setting the permissions to the binary to the user set in the env var $SUDO_USER.

Hmm.. this feels like it will be less work for the user then fixing the permission.
