### ISSUE TITLE
Prometheus(APB) does not provision on minishift v.1.13.0/1.13.1

### ISSUE THREAD

**Issue by cunningt** [minishift/minishift#2059]
### General information

  * Minishift version: 1.13.1
  * OS: macOS
  * Hypervisor: xhyve

openshift version : v3.7.0

### Steps to reproduce

MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --memory=6000 --cpus=2 --openshift-version=v3.7.0 --service-catalog --iso-url centos

Create a new project

Try to provision Prometheus to the new project

### Expected
Prometheus instance to be provisioned

### Actual

Error, Prometheus is not provisioned

### Logs

https://gist.github.com/cunningt/f5cb7fa47ce827f26854665f90017bb1
You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by budhrg** [comment]
@cunningt , are you using prometheus addon - https://github.com/minishift/minishift-addons/tree/master/add-ons/prometheus ?

**Comment by cunningt** [comment]
@budhrg No, I'm not.    This is one of the APBs that I see in the catalog.

I have admin-user, anyuid, and ansible-service-broker addons configured.

**Comment by jparrill** [comment]
@cunningt Hey buddy, I got the problem, did you change the sandbox_role from "edit" to "admin" inside of asb DeploymentConfig and perform a Rollout latest? like in here:

- https://github.com/ansibleplaybookbundle/prometheus-apb/issues/5

I make it work without problems ;):

```
PLAY RECAP *********************************************************************
localhost                  : ok=21   changed=15   unreachable=0    failed=0   
```

**Comment by LalatenduMohanty** [comment]
@jparrill @cunningt So it is not an issue in Minishift. So can we close the issue in Minishift.

**Comment by budhrg** [comment]
Closing as the comment. Please feel free to reopen it if you have the different opinion.
