### ISSUE TITLE
Documents around openshift registry route

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2060]
Currently, we have https://docs.openshift.org/latest/minishift/openshift/openshift-docker-registry.html about how to access openshift docker registry but this document doesn't contain any information around `registry-route` add-on. 

Currently, if a user applies `registry-route` on running Openshift cluster then he gets an edge-terminated route something like `docker-registry-default.192.168.42.43.nip.io` but command which is specified in the doc `minishift openshift registry` will still going to return `172.30.1.1:5000`. When a user enable `registry-route` and then `minishift start` it will then provide the egde route with `minishift openshift registry` command. 

We need to put that in the documents to make sure user aware about same. Right now I am not sure what is the best location to put it. 

-  https://docs.openshift.org/latest/minishift/openshift/openshift-docker-registry.html
or
- https://docs.openshift.org/latest/minishift/using/addons.html#default-addons

@robin-owen Can you please put your views, let us know if you have any query regarding it.

**Comment by LalatenduMohanty** [comment]
IMO the information about the `registry-route` should be in https://docs.openshift.org/latest/minishift/openshift/openshift-docker-registry.html. 

We just need to add following information
* If user wants to use an edge-terminated route, then registry-route add-on should be used. 
* Just applying the add-on wont work properly with `minishift openshift registry` command, so user needs to enable it before `minishift start`.

**Comment by anjannath** [comment]
> Just applying the add-on wont work properly with minishift openshift registry command, so user needs to enable it before minishift start.

This information needs to be there in docs, i was wondering why the addons is not working after only applying.

**Comment by robin-owen** [comment]
I don't see any reason why we can't have the information in both places -- both are logical, and the reader is likely to look for information in either of those locations. We can create an AsciiDoc document to encapsulate this information and use an `include:[]` to insert the same information in both places.

If the information is written generically, it can fit appropriately in both documents.

**Comment by LalatenduMohanty** [comment]
@robin-owen We can not have same text in both the places, but it is fine to add the text in one document and refer it from another.

**Comment by LalatenduMohanty** [comment]
@robin-owen I think you are also saying the same thing and so we both are in agreement that we would maintain the document in one place.
