### ISSUE TITLE
Minishift tutorial

### ISSUE THREAD

**Issue by coolbrg** [minishift/minishift#2064]
We need a tutorial to give users a basic understanding of how one can effectively use Minishift for development purpose.

We can add sample workflow for application development in the tutorial.

---

  * [ ] basic commands
    * [ ] `start`
    * [ ] `stop`
    * [ ] `delete`
  * [ ] environment options
    * [ ] `oc-env`
    * [ ] `docker-env`
  * [ ] configuration settings
    * [ ] cpu
    * [ ] memory
  * etc.

**Comment by firemanxbr** [comment]
I'm contributing with some suggestions to reduce environment problems:

## Cleaning possible errors in a new deployment
Remove the old profile of Minishift:
`$ minishift delete --profile minishift --force`

Clean any old reference to 'minishift' or 'oc':
`$ sed -i".bak" '/minishift/d' ~/.bashrc
$ sed -i".bak" '/oc/d' ~/.bashrc`

Remove the configs and old deploys of Minishift:
`$ rm -rf ~/.minishift`

**Comment by gbraad** [comment]
@firemanxbr those sound more for a FAQ or inclusion on our Wiki-in-progress. This is not something you would expose a newcomer to (who does not have any previous profiles, leftovers or other artifacts)

**Comment by robin-owen** [comment]
@gbraad Common configuration options might also be worth explaining in a tutorial (vCPUs, memory, and so on). If a tutorial isn't the proper place for such commands, we should at least explore where to include this information -- it comes up quite frequently.

@firemanxbr I agree that we should document such things in more detail, but I'm also not convinced that a tutorial aimed at new users should include this information.

**Comment by gbraad** [comment]
@robin-owen completely agree, so...

I would propose to record the needs here... e.g. in a bullet-list, or todo notes, etc.

**Comment by budhrg** [comment]
@LalatenduMohanty Should we take it in 1.15.0 milestone?

**Comment by LalatenduMohanty** [comment]
@budhrg Lets take it in next release train. We have too much for this sprint.

**Comment by budhrg** [comment]
@minishift/minishift-dev I am thinking on first topic as below

1. Hello Minishift 
  - Getting Basic setup (Follow https://docs.openshift.org/latest/minishift/getting-started/index.html) 
  - Getting Customized setup (Using https://docs.openshift.org/latest/minishift/using/basic-usage.html#persistent-configuration)
  - Getting setup in Proxy Environment
  - Getting setup with multiple profiles

If agreed then will send the PR and then we can proceed from here.

**Comment by praveenkumar** [comment]
Check: http://blog.andyserver.com/ lot of post he did around minishit and those are very explanatory with a specific topic, it will give you some idea.

**Comment by budhram** [comment]
Just to update here, I am reading https://redhat-documentation.github.io/modular-docs/#introduction on how to do modularization of docs.

**Comment by budhram** [comment]
Just to give an update here.
We are blocked on modularization of docs.
The plan is to add tutorial as part of documentation.
