### ISSUE TITLE
"minishift openshift version list" should only display released bits from Origin

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2069]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. Find out all the listed openshift version available (```minishift openshift version list```) 
  2. minishift start --openshift-version v3.8.0-alpha.1
      -- Starting profile 'minishift'
      -- Checking if requested OpenShift version 'v3.8.0-alpha.1' is valid on GitHub ... FAIL
          v3.8.0-alpha.1 is not a valid OpenShift version on GitHub
 
### Expected
In the origin release page https://github.com/openshift/origin/releases, i can see those bits ```v3.9.0-alpha.2, v3.9.0-alpha.1 ...``` are not released however only the tags are created. There should be a proper check in the master that ```minishift openshift version list``` should not display the unreleased origin version.  
```
$ ./minishift openshift version list
The following OpenShift versions are available: 
	- v1.4.1
	- v1.5.0
	- v1.5.1
	- v3.6.0
	- v3.6.1
	- v3.7.0
	- v3.7.1
	- v3.8.0-alpha.0
	- v3.8.0-alpha.1
	- v3.9.0
	- v3.9.0-alpha.0
	- v3.9.0-alpha.1
	- v3.9.0-alpha.2
	- v3.9.0-alpha.3
	- v3.9.0-alpha.4
$ 
```
Only tags are created in release page 
<img width="868" alt="111" src="https://user-images.githubusercontent.com/19851115/36716341-12ee85ea-1bc0-11e8-8bcb-84195257dad7.png">

### Actual
m start failed

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
https://github.com/openshift/origin/releases/tag/v3.8.0-alpha.1 contains no published binaries. this is due to the async publishing of docker images and the client binaries,

**Comment by gbraad** [comment]
I suggest to change the error message to a slightly less technical approach:

> "The oc binaries for this release are not available"

**Comment by vmtyler** [comment]
isn't there a way to only list releases that have images and client binaries available?

**Comment by anjannath** [comment]
We could check both docker hub and github releses and then display the list, effectively performing an intersection between the two results.

**Comment by LalatenduMohanty** [comment]
@anjannath Basically we should only display versions which are common in both.
