### ISSUE TITLE
Migrate CirclCI to version 2.0

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#2072]
CircleCI is sunsetting its version 1.0 from Aug 31 and suggested to migrate to 2.0

https://circleci.com/blog/sunsetting-1-0/

**Comment by tylerauerbeck** [comment]
@budhrg @LalatenduMohanty I can take care of this. I've got most of this cleaned up and should have a PR ready within the next day or so.

**Comment by LalatenduMohanty** [comment]
@tylerauerbeck Awesome.

**Comment by budhrg** [comment]
Resolved by https://github.com/minishift/minishift/pull/2084
