### ISSUE TITLE
v3.7.1 is not a valid OpenShift version

### ISSUE THREAD

**Issue by pjos** [minishift/minishift#2083]
### General information

  * Minishift version:  v1.14.0+1ec5877
  * OS: Windows
  * Hypervisor: Hyper-V

### Steps to reproduce

  1.  Behind a corporate proxy, no access to internet at all (i.e. without http(s)_proxy configurations, Sonatype Nexus OSS edition 3.6.1 acts as proxy for docker images. 
  2.  minishift configuration is as follows
```
- check-network-http-host: http://nexus.corp.com:8081
- check-network-ping-host: nexus.corp.com
- disk-size            : 50G
- image-caching        : true
- insecure-registry    : [nexus.corp.com:5000]
- iso-url              : http://nexus.corp.com:8081/repository/binary/minishift-centos7-1.7.0.iso
- logging              : true
- memory               : 8G
- metrics              : true
- network-gateway      : 192.168.123.1
- network-ipaddress    : 192.168.123.123
- network-nameserver   : 123123.123.123
- public-hostname      : master.local.utv.corp.com
- registry-mirror      : [https://nexus.corp.com:5000]
- routing-suffix       : apps.local.utv.corp.com
- show-libmachine-logs : true
```

### Expected
minishift starts as it does with 1.13.1.

### Actual
```
$ minishift start --show-libmachine-logs -v5
-- minishift version: v1.14.0+1ec5877
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.7.1' is valid ... FAIL
   v3.7.1 is not a valid OpenShift version
```

### Logs
None available...
```
minishift start --show-libmachine-logs -v5
-- minishift version: v1.14.0+1ec5877
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.7.1' is valid ... FAIL
   v3.7.1 is not a valid OpenShift version
```

**Comment by LalatenduMohanty** [comment]
@pjos  looks like your proxy settings can not reach github, hence the issue. You can disable the prefilght check which is causing issue for you by `$ minishift config set skip-check-openshift-release true`.

**Comment by pjos** [comment]
Thanks @LalatenduMohanty,  turning of preflight check works fine letting minishift to continue with the startup sequence!
