### ISSUE TITLE
Document the use of --use-existing-config flag for 'minishift start'

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#209]
Currently, OpenShift gets re-provisioned on each start/stop cycle. This is how 'cluster up' works, unless one specifies the _--use-existing-config_ flag. This needs to be documented. 

In the long run, _minishift start_ should transparently take care of this.

**Comment by hferentschik** [comment]
See also issue #210

**Comment by thatdocslady** [comment]
Handling part of this in PR #198 but maybe there needs to be more info in the larger scope (end-to-end) context. Investigating.

**Comment by jorgemoralespou** [comment]
@hferentschik "cluster up" should no longer reprovision in 1.4.0.rc1. Are you testing against that version?

https://github.com/openshift/origin/pull/11146

**Comment by hferentschik** [comment]
> "cluster up" should no longer reprovision in 1.4.0.rc1. Are you testing against that version?

No, atm we use 1.3.1 per default. It would be nice, if this changes for 1.4. It need not make much sense to, but reading the discussions I see where this came from. If re-provisioning is really not needed anymore, we might not need to change anything here and instead just upgrade the default version for the next release.

@ jorgemoralespou  thanks a lot for this info. Very useful.

**Comment by jorgemoralespou** [comment]
@hferentschik keep in mind though how you would provide backward compatibility if at all from 1.4 and 1.3. My decision with ox-cluster-wrapper is to rely on the client 1.4 but support --version=1.3 so client don't make my behaviour too conditional.

**Comment by hferentschik** [comment]
I think this issue might become obsolete, if we get #210 implemented for the upcoming release. If so, we can just close this issue.

**Comment by hferentschik** [comment]
Closing this issue, since it will actually be addressed transparently via issue #210
