### ISSUE TITLE
Project name collision

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#21]
There is another minishift project in github: https://github.com/arachnidlabs/minishift

**Comment by rhuss** [comment]
Since it has a completely different focus and was last updated 2 years ago, I don't think its such a big issue. 

But that's only an opinion, of course ;-)

**Comment by jimmidyson** [comment]
Will keep this open but not going to change this yet.

**Comment by hferentschik** [comment]
I am going to close this now. I think we are beyond a point where a name change would make sense.
