### ISSUE TITLE
Deploy minishift on virtual box [windows 10 pro]

### ISSUE THREAD

**Issue by dgauda** [minishift/minishift#2103]
### General information

  * Minishift version: 1.7.0
  * OS: Windows 10 Pro
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. minishift start --vm-driver=virtualbox -v5 --show-libmachine-logs

### Logs
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | Searching for hostonly interface for IPv4: 192.168.99.1 and Mask: ffffff00
(minishift) Windows might ask for the permission to create a network adapter. Sometimes, such confirmation window is minimized in the taskbar.
(minishift) DBG | Not found
(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create
(minishift) DBG | STDOUT:
(minishift) Creating a new host-only adapter produced an error: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create failed:
(minishift) 0%...
(minishift) Progress state: E_FAIL
(minishift) VBoxManage.exe: error: Failed to create the host-only adapter
(minishift) VBoxManage.exe: error: SetupDiCreateDeviceInfo failed (0x00000005)
(minishift) DBG | {
(minishift) VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
(minishift) DBG | }
(minishift) VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp
(minishift) DBG | STDERR:
(minishift)
(minishift) This is a known VirtualBox bug. Let's try to recover anyway...
(minishift) DBG | {
(minishift) DBG | 0%...
(minishift) DBG | Progress state: E_FAIL
(minishift) DBG | VBoxManage.exe: error: Failed to create the host-only adapter
(minishift) DBG | VBoxManage.exe: error: SetupDiCreateDeviceInfo failed (0x00000005)
(minishift) DBG | VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
(minishift) DBG | VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp
(minishift) DBG | }
.(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | }
.(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | STDERR:

**Comment by amitkrout** [comment]
@dgauda  Can you please try the same on latest minishift release [v1.14.0](https://github.com/minishift/minishift/releases/tag/v1.14.0)

**Comment by dgauda** [comment]
Hi Amit,

I see below errors while deploying minishift 1.14.0 version on VirtualBox Version 5.1.22 r115126 (Qt5.6.2)

Thanks
Dinu
StackTrace:
(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | Searching for hostonly interface for IPv4: 192.168.99.1 and Mask: ffffff00
(minishift) Windows might ask for the permission to create a network adapter. Sometimes, such confirmation window is minimized in the taskbar.
(minishift) DBG | Not found
(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create
(minishift) DBG | STDOUT:
(minishift) Creating a new host-only adapter produced an error: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create failed:
(minishift) 0%...
(minishift) Progress state: E_FAIL
(minishift) DBG | {
(minishift) VBoxManage.exe: error: Failed to create the host-only adapter
(minishift) VBoxManage.exe: error: SetupDiCreateDeviceInfo failed (0x00000005)
(minishift) DBG | }
(minishift) VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
(minishift) VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp
(minishift) DBG | STDERR:
(minishift)
(minishift) This is a known VirtualBox bug. Let's try to recover anyway...
(minishift) DBG | {
(minishift) DBG | 0%...
(minishift) DBG | Progress state: E_FAIL
(minishift) DBG | VBoxManage.exe: error: Failed to create the host-only adapter
(minishift) DBG | VBoxManage.exe: error: SetupDiCreateDeviceInfo failed (0x00000005)
(minishift) DBG | VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
(minishift) DBG | VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp
(minishift) DBG | }

**Comment by dgauda** [comment]
I am now able to deploy minishift on latest VirtualBox 5.2.8 using powershell (Admin).
