### ISSUE TITLE
minishift oc-env: dial tcp: missing address

### ISSUE THREAD

**Issue by urzds** [minishift/minishift#2104]
### General information

  * Minishift version: v1.12.0+daa0943
  * OS: Linux
  * Hypervisor: KVM

### Steps to reproduce

  1. Install Fedora 27
  2. Copy over `$HOME` from an Ubuntu 16.04 installation, including `bin/minishift` and `~/.minishift`
  3. Execute `minishift oc-env`

### Expected

Some environment variables should be printed or a meaningful error message should be displayed.

### Actual

```
$ minishift oc-env
dial tcp: missing address
```

This error message gives no hint on what failed. It would be helpful if `minishift` would at least prefix the error message with the command that failed.

### Logs

```
$ minishift oc-env -v5
-- minishift version: v1.12.0+daa0943
dial tcp: missing address
```

strace: https://gist.github.com/urzds/6e08c298766a2254d759f71f722a08c8

### Additional information

`dnf install virt-manager` makes the error message go away, so I assume some command used by `minishift` uses one (or more) of the following packages: https://gist.github.com/urzds/831f5910ca514389cd51479607897ad3

**Comment by praveenkumar** [comment]
@urzds This is not how `minishift` can be ported from one system to another. you need to perform all the steps (installation and prerequisites) on your Fedora box also instead copy from the Ubuntu box. You can copy the binary and some of the config which is part of `~/.minishift` but not everything.

**Comment by urzds** [comment]
Please note that this issue is not about whether `minishift` can be ported like this from one machine to another, but about the bad error message it prints in case of failure.

**Comment by LalatenduMohanty** [comment]
@urzds We do not support this use case at all, so we are not planning to invest time to fix the error message. However we will welcome any contribution in fixing the error message.

**Comment by handmilkingsoftware** [comment]
I followed the documented installation instructions under linux mint and it seems to be working fine but when ever I try `oc-env` and other bunch of commands it returns `dial tcp: missing address` error as well.
