### ISSUE TITLE
Refactor all error messages to start with small letter

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#2106]
This piece in our code always poke me whenever I see the error messages like

https://github.com/minishift/minishift/blob/2b3e3a210089bf748730daf8fdd71ec44dde3bcc/pkg/minishift/clusterup/clusterup.go#L168-L170

in the code. This format is used across all the codebase.

Ideally, we should start error message with small letter unless proper nouns or acronyms
See https://github.com/golang/go/wiki/CodeReviewComments#error-strings.

### NOTE
There are few exceptions mostly in `cmd/` package like
https://github.com/minishift/minishift/blob/2b3e3a210089bf748730daf8fdd71ec44dde3bcc/cmd/minishift/cmd/root.go#L117-L119

**Comment by gbraad** [comment]
Sounds very needless to address, unless we have a consistent way to show message prefixed with `Error: `. Even then, we can solve this as part of the logging facade with a `firstToLower `

**Comment by gbraad** [comment]
This only makes sense with #169, and even then it pays off to solve this with a function to handle this at first.
