### ISSUE TITLE
Document use of setx for Hyper-V virtual switch

### ISSUE THREAD

**Issue by robin-owen** [minishift/minishift#2108]
The Hyper-V virtual switch documentation in **_getting-started/setting-up-driver-plugin.adoc_** uses `set` to set environment variables for Command Prompt and `$env` to set them for PowerShell. Both of these methods will change the environment for the current shell session, but will not persist. The `setx` utility can set environment variables in the registry to persist these settings, but will not affect the current shell. As such, both `set` and `setx` must be used for Command Prompt, and both `$env` and `setx` must be used for PowerShell.

**Comment by LalatenduMohanty** [comment]
Resolved by #2109
