### ISSUE TITLE
minishift --metrics fails to start for v3.7.1

### ISSUE THREAD

**Issue by paidhi** [minishift/minishift#2110]
### General information

  * Minishift version: v1.14.0+1ec5877
  * OS: macOS (10.13.3)
  * Hypervisor: xhyve

### Steps to reproduce

  1. minishift start --metrics --alsologtostderr

### Expected
Create and deploy pods for Hawkular

### Actual
Fails to run pod `openshift-ansible-metrics-job...`

### Logs

The log states a failure in pulling image "openshift/origin-ansible:v3.7.1". Tag v3.7.1 does not exist on DockerHub (https://hub.docker.com/r/openshift/origin-ansible/tags/). I assume the missing tag is the cause of this problem.
The described problem does not occur if minishift is told to run `--openshift-version=v3.7.0` since a tag `v3.7.0` does exist for openshift/origin-ansible on DockerHub.

**Comment by gbraad** [comment]
Please file this against OpenShift/origin

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by paidhi** [comment]
I have created an issue at https://github.com/openshift/openshift-ansible/issues/7487
