### ISSUE TITLE
minishift installation problem 

### ISSUE THREAD

**Issue by sherifkhedr** [minishift/minishift#2115]
### General information

  * Minishift version: 
  * OS: Linux (ubuntu 14.04 )
  * Hypervisor:  VirtualBox 5.2

wen i run this command : 

$ minishift start

 this problem appears to me :

-- Starting profile 'minishift' -- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK -- Checking if VirtualBox is installed ... FAIL See the 'Installing Prerequisites for Minishift' topic (https://docs.openshift.org/latest/minishift/getting-started/installing.html#install-prerequisites) for more information

and this my VirtualBox aspects : 
CPU : 2Cores 
RAM : 2G 
OS : Centos 7 
VirtualBox Version: 5.2

Kindly help

**Comment by sherifkhedr** [comment]
any update

**Comment by praveenkumar** [comment]
@sherifkhedr As per provided logs `Checking if VirtualBox is installed ...FAIL` which means virtualbox not installed or not in the PATH. Can you please check once if VirtualBox installed and in the path? 

This test try to run `VBoxManage -v` on the target platform so if it is not in the PATH then it will fail.

**Comment by budhrg** [comment]
@sherifkhedr , any update here on question raised above?
