### ISSUE TITLE
"template-service-broker-registration" not found 

### ISSUE THREAD

**Issue by felixbecker** [minishift/minishift#2116]
### General information
Hi, I have a hard time installing/enabling service-catalog on minishift. It looks like the template is not on board. Do I need to install something else? I basically try install it passing the `--service-catalog` flag. Do I miss something here?

  * Minishift version: 
    v.1.14.0 / openshift/origin:v3.7.0
  * OS: Linux / macOS / Windows
   Mac El Capitan
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox
    xhyve

### Steps to reproduce

  1.  install minishift
  2. `MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --service-catalog ` 
  

### Expected
Service Catalog should be installed

### Actual
Error-Message:
```
-- Registering template service broker with service catalog ... FAIL
   Error: cannot register the template service broker
   Caused By:
     Error: cannot retrieve template "template-service-broker-registration" from namespace "openshift-infra"
     Caused By:
       Error: templates.template.openshift.io "template-service-broker-registration" not found
Error during 'cluster up' execution: Error starting the cluster.
```

### Logs
https://gist.github.com/felixbecker/6b1b498f597bb584d9ed06077ceaad4a

Thanks for any help.

**Comment by praveenkumar** [comment]
@jorgemoralespou any idea around it?

**Comment by praveenkumar** [comment]
This is something broken in `oc cluster up` side. @felixbecker can you please file issue to https://github.com/openshift/origin/issues ?

**Comment by praveenkumar** [comment]
Did tried with `v3.7.2` and got same error.

```
[...]
Starting OpenShift using openshift/origin:v3.7.2 ...
Pulling image openshift/origin:v3.7.2
Pulled 1/4 layers, 27% complete
Pulled 2/4 layers, 83% complete
Pulled 3/4 layers, 90% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... 
   Deleted existing OpenShift container
-- Checking for openshift/origin:v3.7.2 image ... 
   Pulling image openshift/origin:v3.7.2
   Pulled 1/4 layers, 27% complete
   Pulled 2/4 layers, 83% complete
   Pulled 3/4 layers, 90% complete
   Pulled 4/4 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.42.38 as the server IP
-- Checking service catalog version requirements ... OK
-- Starting OpenShift container ... 
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Registering template service broker with service catalog ... FAIL
   Error: cannot register the template service broker
   Caused By:
     Error: cannot retrieve template "template-service-broker-registration" from namespace "openshift-infra"
     Caused By:
       Error: templates.template.openshift.io "template-service-broker-registration" not found
Error during 'cluster up' execution: Error starting the cluster.
```

**Comment by felixbecker** [comment]
Thx @praveenkumar for your feedback I will file an issue. Is there a way to link this issue or should I copy paste create a new on here: https://github.com/openshift/origin/issues ?

**Comment by praveenkumar** [comment]
@felixbecker you can copy paste the issue there and put the reference to this issue on the bottom.

**Comment by felixbecker** [comment]
And back to minishift. The folks from origin mentioned something that there might be an issue with minishift. Details here: 
https://github.com/openshift/origin/issues/19081#issuecomment-376566534

**Comment by LalatenduMohanty** [comment]
@felixbecker The steps to run service-catalog has changed in Minishift. Refer https://docs.okd.io/latest/minishift/using/experimental-features.html#enabling-experimental-oc-flags

I am closing the issue as `MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --service-catalog` is not a valid way of running service catalog

**Comment by LalatenduMohanty** [comment]
Let us know if you face the issue again
