### ISSUE TITLE
Minishift 1.14 will not start on Fedora with KVM

### ISSUE THREAD

**Issue by jberkus** [minishift/minishift#2117]
### General information

  * Minishift version: 1.14.0
  * OS: Fedora 27
  * Hypervisor: KVM

### Steps to reproduce

  1. Follow driver installation instructions at: https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html
  2. Follow installation instructions at: https://docs.openshift.org/latest/minishift/getting-started/installing.html
  3. Get:

```
[jberkus@ariolimax ~]$ minishift start
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.7.1' is valid ... OK
-- Checking if requested OpenShift version 'v3.7.1' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... FAIL
   See the 'Setting Up the Driver Plug-in' topic (https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html) for more information
```

### Expected

Minishift should have started

### Actual

See above.

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

--show-libmachine-logs fails to produce any logs.

**Comment by anjannath** [comment]
@jberkus This is strange, if you have followed the instructions on the links you gave, the check should not fail.

Can you check if creating and running a VM is working in your machine by using Virtmanager or qemu?

**Comment by jberkus** [comment]
Virtmanager runs, however, the Fedora cloud image won't complete boot-up.

Currently investigating whether this is an issue with the virt setup on this machine.

**Comment by gbraad** [comment]
@jberkus can you provide a startup log with `minishift start --show-libmachine-logs -v5` ?

**Comment by gbraad** [comment]
Since this test checks the inclusion of the driver on your path: https://github.com/minishift/minishift/blob/973bbfd90741ef129563f9a8eae4fa4f470eb250/cmd/minishift/cmd/start_preflight.go#L281 you might check if the driver is executable or really available at the correct location.

**Comment by jberkus** [comment]
No, something's defintely borked on my KVM setup, probably due to installing Katacontainers.  I'll re-open this if I get to the point of a clean KVM.

**Comment by rhnvrm** [comment]
@jberkus @gbraad, @anjannath same thing happens on my machine 

Tried to see if docker-machine-driver-kvm was found

```sh
$ where docker-machine-driver-kvm
docker-machine-driver-kvm not found
```

Also, here is the result of `minishift start --show-libmachine-logs -v5`
```sh
-- minishift version: v1.16.1+82886ed
-- Starting profile 'minishift'
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... FAIL
   See the 'Setting Up the Virtualization Environment' topic (https://docs.openshift.org/latest/minishift/getting-started/setting-up-virtualization-environment.html) for more information
```

**Comment by nirodg** [comment]
> 
> 
> Solved this for now using:
> https://fedoramagazine.org/minikube-kubernetes/
> 
> ```shell
> $ curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-centos7 >/tmp/docker-machine-driver-kvm
> $ chmod +x /tmp/docker-machine-driver-kvm
> $ sudo cp /tmp/docker-machine-driver-kvm /usr/local/bin/docker-machine-driver-kvm
> ```

I was running on the same issue and this solved my problem, many thanks! 👍

**Comment by gbraad** [comment]
Installation of the KVM driver is documented. Not sure why this issue
needed to be searched for... Can you explain?

**Comment by rhnvrm** [comment]
I think it would help to add explicit, **For Linux**, **For Windows** as H1 and **Setting Up the KVM Driver** as H2, as I recall for me atleast, I directly skipped to **On Fedora**.

**Comment by anjannath** [comment]
@rhnvrm I would suggest you to open a separate _docs improvement_ issue for this, and we can take it from there.

/cc @robin-owen

**Comment by rhdojun** [comment]
I think the problem is mostly a usability issue. In the documentation the important part, where the driver is moved ot the right directory and where it is RENAMED (at least on centos it's losing the (-centos) part of the name) is not visible without side scrolling. So usually people don't expect to miss key information because it's on the right side outside the visible frame of the text box. If you reformat this text you will see fewer people having the issue.
