### ISSUE TITLE
Add CircleCi for OS-X builds and unit tests

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#212]
As per https://circleci.com/pricing/#faq-section-os-x provide some free seed plan for open-source project. I sent mail to get one such plan and once we have then we should add configure circleci also for OS-X specific builds.

**Comment by praveenkumar** [comment]
@hferentschik I requested some admin access for this org so that circleci detect this repo, please approve those request.

**Comment by hferentschik** [comment]
@praveenkumar so what do you need at this stage do move this forward?

**Comment by praveenkumar** [comment]
@hferentschik I am still waiting from CircleCI team to provide me required resources, details which they asked I already provided.

**Comment by hferentschik** [comment]
Cool. Let's see what happens.

**Comment by hferentschik** [comment]
Merged via pull request #263
