### ISSUE TITLE
Make SSHFS host folders the default

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#2124]
Once we gained some experience with SSHFS host folders and iron out existing issues, it makes sense to make SSHFS the default, since it works w/o any requirements.

**Comment by gbraad** [comment]
I would like to set a expected timeframe to do this. Hopefully as short as possible... the longer we wait, the more problematic this might become.

**Comment by budhrg** [comment]
+1 for making sshfs host folers as default.

**Comment by anjannath** [comment]
Closed via #2494
