### ISSUE TITLE
Add port verification for hostfolders-sftp-port config option

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#2125]
SSHFS host-folders introduces `hostfolders-sftp-port` as a persistent config option to set the port for the sftp server. At the moment, there is only an `isPositive` validation configured in `config.go`.  We should create a port specific validation which verifies a that the option is in a valid port range.

**Comment by gbraad** [comment]
this should check a defined range of ports which are allowed, eg. 1024-65536 so that we can tell user at early stage about which port should be used for config.
