### ISSUE TITLE
Write integration test for SSHFS host folder 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#2126]
Something along the lines:

* minishift hostfolder list -> nothing there
* minishift hostfolder add ... -> host folder defined
* minishift hostfolder list -> host folder defined, but not mounted
* minishift hostfolder mount -> host folder gets mounted, runs some commands that the file system is mounted and writable, etc
* minishift hostfolder list -> host folder defined and mounted
* minishift hostfolder umount
* minishift hostfolder delete

**Comment by LalatenduMohanty** [comment]
Resolved #2497
