### ISSUE TITLE
Provide usage examples for host folders

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#2127]
The docs around host folders should add some actual use cases and go beyond the pure syntactical description of the commands. As part of this, we could also give some more insight on the layout if the VM filesystem.

**Comment by gbraad** [comment]
@robin-owen  It has been assigned for quite some time and has been postponed several releases. Is there anything you need or is information missing? Perhaps the issue is out of date?

**Comment by robin-owen** [comment]
@gbraad Apologies, this issue escaped my notice. I believe this issue is out of date at this point -- we currently have documented examples for SSHFS- and CIFS-based host folders.
