### ISSUE TITLE
Investigate whether there are better sshfs mount options we can use

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#2128]
Currently, we use:

```golang
		cmd := fmt.Sprintf(
			"sudo sshfs docker@%s:%s %s -o IdentityFile=%s -o 'StrictHostKeyChecking=no' -o reconnect -o allow_other -o idmap=none -p %d",
			ip,
			h.config.Option(config.Source),
			h.config.MountPoint(),
			keyFile,
			SftpPort)
```

There are many more options which might help to improve performance and or file permissions. Some investigation and experiments around this would be nice. 

We could also let the user specify his own options, amending or overriding the default mount options. Technically we should be able to use the `--options` flag of the `hostfolder add` command.

**Comment by anjannath** [comment]
I will do the required investigation about sshfs options.

**Comment by anjannath** [comment]
Still Todo..

**Comment by anjannath** [comment]
There are a couple of options we can use by default such as.. `Ciphers=arcfour`, `Compression=no`, `cache=yes` mostly these will improve performance.

**Comment by anjannath** [comment]
The `--options` flag work will be done as part of #2157

**Comment by anjannath** [comment]
I think we can just close this, WDYT @minishift/minishift-dev ?

**Comment by LalatenduMohanty** [comment]
@anjannath This issue was created to see if we want to add something to default experience of sshfs host folder. Even through users can use these options through `--options flag ` but it wont be part of default behavior. So the question do we want to add any option to the default user experience?

**Comment by anjannath** [comment]
@LalatenduMohanty I have tried other options like these `-o compression=no -o kernel_cache -o large_read -o`(from the manpage of sshfs) that you can see in this [commit](https://github.com/anjannath/minishift/commit/4754ef2e288e94bcd7fc988a3c509343f520788d), but not sure how they impact the performance/stability of sshfs mounts. I don't think we need any additional options for it by default.

**Comment by anjannath** [comment]
The other options were tried and there was no noticeable performance gains, so the current options works for our scenario with sshfs.
