### ISSUE TITLE
EAP 71 templates are not installed from xpaas add-on

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2135]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. ./minishift start
  2. ./minishift addons apply xpaas
  3. ./minishift console 
  4. Search for ```EAP 7.1``` template

### Expected
As we have ```EAP 7.1``` template available in xpaas [addons directory](https://github.com/minishift/minishift/tree/master/addons/xpaas/xpaas-templates), then it should be available for deployment

### Actual
File https://github.com/minishift/minishift/blob/master/addons/xpaas/xpaas.addon doesn't contain the ```EAP 7.1``` installation steps, hence no template items found for ```eap71``` after applying the xpaas addons.

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by LalatenduMohanty** [comment]
Resolved by #2166
