### ISSUE TITLE
Add a new verification method to test port range for sshfs

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2136]
Currently, we are testing port defined for sshfs as a positve value but this check should be defined a range of port which is allowed 1024-65536 so that we can tell user at early stage about which port should be used for config.

**Comment by anjannath** [comment]
Looks like this is a duplicate of #2125, as both has the same purpose of verifying the port number for sftp server. am i right @praveenkumar ?

**Comment by budhrg** [comment]
@anjannath @praveenkumar Yes it seems to be.

**Comment by gbraad** [comment]
Closing and adding comments to the other issue
