### ISSUE TITLE
Minishift avoid ip change

### ISSUE THREAD

**Issue by mshahat** [minishift/minishift#2138]
Hi, 

Very simple question please. 

On macOS, how could i start minishift ? and start it over again the next day without receiving all sorts of errors because of ip changes ? 

I've tried xhyve and virtualbox. 

Appreciate some direction please. 

`minishift start --memory 4GB --vm-driver virtualbox` is how i start it

Many thanks,

**Comment by praveenkumar** [comment]
@mshahat we have a PR #1513 in place which is currently under review, It would be great if you can also try out in your setup and provide us early feedback.

To test this PR you need below prerequisites.

- CentOS ISO => http://artifacts.ci.centos.org/minishift/minishift-centos-iso/pr/227/minishift-centos7.iso
- Minishift binary artifact => http://artifacts.ci.centos.org/minishift/minishift/pr/1849/

Then you can try https://github.com/minishift/minishift/pull/1849#issuecomment-373377377 and let us know if something break. We tested this on xhyve on OSx

**Comment by LalatenduMohanty** [comment]
@mshahat I am closing this as it is a duplicate issue of #1457 as @praveenkumar mentioned please try the PR and let us know.
