### ISSUE TITLE
Internationalization (i18n) of Minishift

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2139]
At this point we get issues when the local OS language is not English e.g. https://github.com/minishift/minishift/issues/2121 . We should look at this issue as whole make Minishift work in other languages too.

**Comment by gbraad** [comment]
This is already reported in other issues, and as #1584. Do we really need a general task like this? I do not think this helps without identifying the issues first. @agajdosi

**Comment by LalatenduMohanty** [comment]
@gbraad I think #1584 is fine, Some how I forgot about it. I will close this as duplicate.
