### ISSUE TITLE
Using Libvirt-go bindings for checking default network active state

### ISSUE THREAD

**Issue by alaypatel07** [minishift/minishift#2143]
Checking issues [#2121](https://github.com/minishift/minishift/issues/2121) and [this](https://github.com/minishift/minishift/pull/1593), I feel, if Libvirt-go bindings are used(hosted [here](https://github.com/libvirt/libvirt-go)), the code could look like:

```
//checkLibvirtDefaultNetworkActive returns true if the "default" network is active
func checkLibvirtDefaultNetworkActive() bool {
	con, _ := linbirt.Open("qemu:///system")
	network, _ := con.networkLookupByName("default")
	stdOutStdError, err := cmd.CombinedOutput()
	if network != nil {
		return network.IsActive();
	}
}
```
This might solve the language problem.

**Comment by anjannath** [comment]
Awesome @alaypatel07 .. :+1:
I guess you are planning to send a PR also.. :)

**Comment by gbraad** [comment]
the library is quite large dependency. But let's see what the PR does. If it solves part of our issue, sure...

... as long as it doesn't come with a side-effect.

**Comment by gbraad** [comment]
I do not believe we should introduce any binding directly into our code.
In future steps, we will move this pre-check into the drivers anyway
