### ISSUE TITLE
Can I upgrade to openshift 3.9.0

### ISSUE THREAD

**Issue by mhightower** [minishift/minishift#2145]
### General information

  * Minishift version: minishift v1.14.0+1ec5877
  * OS: macOS 10.11.6 
  * Hypervisor: VirtualBox 5.1.24 r117012
  * Docker for MacOS: 17.12.0

I create a Dockerfile based on version 3 which after a lot of work I got working with my docker-ompose and Docker for MacOS Version 17.12.0.
Now I want to build the image using minishift environment.

It looks I may need to downgrade the docker-composer and DockerFiles I created because the way it is docker-compose and docker are throwing errors.

Is there a way to upgrade the openshift the minishift uses? I see 3.9.0 is available :

    $ minishift openshift version list                                                                                                                          [11:05:25]
    The following OpenShift versions are available: 
        - v1.4.1
        - v1.5.0
        - v1.5.1
        - v3.10.0
        - v3.10.0-alpha.0
        - v3.6.0
        - v3.6.1
        - v3.7.0
        - v3.7.1
        - v3.7.2
        - v3.8.0
        - v3.8.0-alpha.0
        - v3.8.0-alpha.1
        - v3.9.0
        - v3.9.0-alpha.0
        - v3.9.0-alpha.1
        - v3.9.0-alpha.2
        - v3.9.0-alpha.3
        - v3.9.0-alpha.4

but I'm running by default 3.7.1:

    $ minishift status                                                                                                                                    [11:04:57]
    Minishift:  Running
    Profile:    minishift
    OpenShift:  Running (openshift v3.7.1+a8deba5-34)
    DiskUsage:  13% of 17.9G

How would I go about upgrading and maybe why does it default to 3.7.1?

**Comment by praveenkumar** [comment]
@mhightower there is an issue with the way we show the list of available version and this is going to fix soon (PR #2120). Regarding upgrading, you can use `--openshift-version` to provide whatever cluster version you want to provision.

**Comment by anjannath** [comment]
> How would I go about upgrading and maybe why does it default to 3.7.1

As @praveenkumar mentioned you can use the flage `--openshift-version` to mention the version you want to use. Minishift releases default to the latest available release of Origin, that's why v3.7.1 is the default version for minishift version v1.14.0.

**Comment by budhrg** [comment]
Closing as you can use `minishift start --openshift-version v3.9.0-alpha.3`.

**Comment by mhightower** [comment]
Thanks the problem #2120  is solving was the main issue.
