### ISSUE TITLE
Problem using/ restarting minishift from different user accounts

### ISSUE THREAD

**Issue by uvwild** [minishift/minishift#2151]
### General information

  * Minishift version: 3.7.1
  * OS: Linux / macOS / Windows
ubuntu 16.04
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox
kvm

### Steps to reproduce

  1. run minishift from one account
  2. run minishift from another account
  3. 
  4. 

### Expected
recognizing prior installation correctly

### Actual
failing to identify a different installation from another location/user

```
FAIL E0319 13:26:47.078604    7708 start.go:369] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: [Code-9] [Domain-20] operation failed: domain 'minishift' already exists with uuid 9b73bed2-51f6-42db-85db-6109c8b0a7c3. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: [Code-9] [Domain-20] operation failed: domain 'minishift' already exists with uuid 9b73bed2-51f6-42db-85db-6109c8b0a7c3

 start.go:369] Error starting the VM: Error configuring authorization on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
Error starting the VM: Error configuring authorization on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

```
### Logs
The 'minishift' VM is already running.

_______________________________________
So the restart scenario is fragile as the VM remembers which account it has been created on.
in particular the access key set.

However, the minishift start command does not recognize this and fails to restart.
Since this can be done by another independent user it is a very frustrating failure.
maybe not the most common use case but even though very misleading error messages.

**Proposal.**
Record the location of the controlling file set in the VM and verify.
This might solve a number of similar restart issues as well. 
just failed authentication is not helping alot.
It took me a while to understand the issue with the shared minishift VM, but using separate minishift control sets per user ~/.minishift. 
This detail is hidden behind powerful encapsulation, which complicates problem analysis.

**Comment by gbraad** [comment]
this is a limitation to how Docker machine and Libvirt works.

VM have to be uniquely identified, but since we always use `minishift` as profile, this will also be the identification of the VM within libvirt.

**Comment by uvwild** [comment]
I was supecting such a reason behind.
However, all this is hidden too well behind such a mighty CLI.

**There should be more information provided to troubleshoot this issue.**
Just saying its an authentication error is not helping. 

So my suggestion would be at least to provide the info of what is authenticated against what.
Having those references could be a start. 
(I know people might call this a security issue.But there has to be a compromise.)

That another user did the same thing before me is nothing I have a good chance to find out if the details are so well hidden away!

and you are saying it uses the same names. So how on earth am I supposed to figure that out without being an advanced user?

As minishift was a tool to kick off beginners for openshift if I understand it right?!?

I believe creating such a nice tool like minishift also brings **responsibilities**.
If the facade provided is hiding all the information required to resolve an issue there is a problem.

**Comment by gbraad** [comment]
Not following... this is not related to a choice of providing security. we generate a key to allow the local user to connect to the VM. this key is stored in the `~/.minishift` folder. This is not hidden away at all... The VM can only gte provisioned with one key as part of a userdata deployment... you could, if you want, just duplicate your key to the other user...

Out of the box, we support a single-user developer setup. The scenario you are describing of having two users on the same machine does not sound like the average scenario, but more like a server approach. We have created the tool accordingly... but are still finetuning. Note: this described scenario would also fail on minikube, and docker machine-based deployments.

**Comment by budhrg** [comment]
@uvwild , could you reply on above comment?
