### ISSUE TITLE
Update docker-machine version from 0.13.0 to 0.15.0

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2155]
Recently docker-machine released 0.15.0 which have some improvement around hyperV side. we need to update to latest version and check if there is any conflict.

- https://github.com/docker/machine/releases/tag/v0.15.0

**Comment by anjannath** [comment]
I guess this is still to do..

**Comment by praveenkumar** [comment]
1.14.0 have an issue with `hyperV` so either we use the revision which has a fix for this or waits for 1.14.1 release. check https://github.com/docker/machine/commit/c79bd4ad7404b3c17ff3fd14991dc3f4cddf792e

**Comment by gbraad** [comment]
Fix will never come as a release I guess:
https://github.com/docker/machine/issues/4424#issuecomment-393414375

**Comment by LalatenduMohanty** [comment]
Resolved via #2516
