### ISSUE TITLE
Improve startup message to include selected driver

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#216]
I think we should add the selected driver to the startup message to make it more explicit which driver is selected. See also question #215.

Currently we have:

> Starting local OpenShift cluster...

I suggest we have something like this

> Starting local OpenShift instance using \<driver\> hypervisor ...

**Comment by budhrg** [comment]
@hferentschik Agree with this instead of dropping automatic selection of driver based on OS #215

**Comment by praveenkumar** [comment]
@hferentschik I agree on improving message of cluster up which shows used driver also but explicit chose of driver might be little lack from user experience side. Right now it's simple `minishift start` but if we make driver explicit then it will be like `minishift start --vm-driver=<>`. 

From user debug side I think we also need to add troubleshoot guilde which can provide some basic info around this.

**Comment by jorgemoralespou** [comment]
I just answered in https://github.com/minishift/minishift/issues/215

Very much needed, and even more if #215 gets implemented

**Comment by hferentschik** [comment]
Resolved via pull request #256
