### ISSUE TITLE
Hyper link redirecting to wrong tab

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2167]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. Go to - https://docs.openshift.org/latest/minishift/troubleshooting/troubleshooting-misc.html#authentication-required-to-push-image
  2. Click on ISO hyperlink available there
  3. Its redirecting to the ```Basic Usage``` of same page instead of particular tab ```Choosing the ISO Image```
  4. 

### Expected
It should redirect to https://docs.openshift.org/latest/minishift/using/basic-usage.html#choosing-iso-image

### Actual
Its redirecting to https://docs.openshift.org/latest/minishift/using/basic-usage.html#choosing-iso-image#. Just removing ```#``` at the end of the source  ```xref:../using/basic-usage.adoc#choosing-iso-image#``` will resolve the problem

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by LalatenduMohanty** [comment]
Resolved via #2191
