### ISSUE TITLE
Bundle custom libmachine drivers into minishift

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#217]
If possible it would be great to bundle libmachine drivers which are not part of the library itself (xhyve, kvm) as part of minishift. This would improve the user experience for users of these hypervisors.

**Comment by praveenkumar** [comment]
@hferentschik using that we can use xhyve/kvm programmatic but then we might to run our minishift binary as root user or provide required access as we provide to xhyve/kvm to start a VM.

**Comment by hferentschik** [comment]
I gave bundling a try and I think it is not an option, at least not for now. There are several issues around the xhyve driver, the most prominent one that it uses some C code which will break our ability to cross compile. And as you say, having to execute the binary as root seems wrong as well. 

On the other hand, I found a way to just "cache" the driver and use it this way. It means you need to interactively ask the user for the root password in order to change the file permissions and set the suid flag. I think this might be the best option for now, if we want to automate the use of the xhyve driver. 

I will try to complete my prototype asap for some initial review.

**Comment by praveenkumar** [comment]
> On the other hand, I found a way to just "cache" the driver and use it this way.

Here you mean binary cache like minishift used to do it for `openshift` before or the way we do it right now for `oc` where we just download binary and put it to required location?

**Comment by hferentschik** [comment]
What I mean is the way we do it for _oc_.

**Comment by praveenkumar** [comment]
> What I mean is the way we do it for oc.

Thanks make sense and might be good user experience.

**Comment by bortels** [comment]
"... and set the suid flag"

Eep. This makes me uncomfortable, hopefully for obvious reasons. 

Is just running minishift as root a valid alternative?

**Comment by hferentschik** [comment]
It is not running minishift as root here, but xhyve, or better the xhyve driver. This is already the case now. The xhyve driver already needs the suid flag set, I am not suggesting a change here, but rather that we will do it for the user.

**Comment by gbraad** [comment]
As we discussed with minikube https://github.com/kubernetes/minikube/issues/1623, we are unable to bundle the drivers. This means we need to distribute the drivers alongside the release as part of a downloadable (+install step)... anyways, I think some of this will also need to be handled by the installer?

**Comment by hferentschik** [comment]
> This means we need to distribute the drivers alongside the release as part of a downloadable (+install step)... anyways,

I think we have to options. Either bundle them in a way we do already with add-ons, using go-bindata or do what we do with the ISO and oc as well and download on demand. For me the latter seems atm preferable. 

>  I think some of this will also need to be handled by the installer

Which installer?

**Comment by gbraad** [comment]
@hferentschik the DevSuite installer.

**Comment by LalatenduMohanty** [comment]
@minishift/minishift-dev  I do not think this relevant anymore. We know that we can not bundle all drivers in Minishift because of the c bindings some drivers have. WDYT?

**Comment by LalatenduMohanty** [comment]
@minishift/minishift-dev Closing this issue as we do not have plan to address this.
