### ISSUE TITLE
Minishift throwing error validating certs on Windows

### ISSUE THREAD

**Issue by jwlai** [minishift/minishift#2171]
### General information

  * Minishift version: minishift v1.14.0+1ec5877
  * OS: Windows
  * Hypervisor: Hyper-v

### Steps to reproduce

  1.  Download minishift
  2.  "minishift start"

### Expected
minishift up and running

### Actual
Minishift error,  

FAIL E0323 16:35:48.409263   11304 start.go:369] Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.86.57:2376": EOF

### Logs

https://gist.github.com/jwlai/14c82ac14b75788bb9a34a870f1df330

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
This is related to a faulty ISO. This should be fixed soon. Release is
expexted today

On Saturday, March 24, 2018, jwlai <notifications@github.com> wrote:
> General information
>
> Minishift version: minishift v1.14.0+1ec5877
> OS: Windows
> Hypervisor: Hyper-v
>
> Steps to reproduce
>
> Download minishift
> "minishift start"
>
> Expected
>
> minishift up and running
>
> Actual
>
> Minishift error,
>
> FAIL E0323 16:35:48.409263 11304 start.go:369] Error starting the VM:
Error creating the VM. Error creating machine: Error checking the host:
Error checking and/or regenerating the certs: There was an error validating
certificates for host "192.168.86.57:2376": EOF
>
> Logs
>
> https://gist.github.com/jwlai/14c82ac14b75788bb9a34a870f1df330
>
> You can start Minishift with minishift start --show-libmachine-logs -v5
to collect logs.
> Please consider posting this on http://gist.github.com/ and post the link
in the issue.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/T1YxrKmRef91_Ugyke7mVuNZccHYmgwymcwr1VCYJwjr9ec66iSQRnTP89qaalhS5nBRSrRVn0Hw5owZ1FTQZG744uEnxPA3rV9chMN_IzR03HxVklGKD05AIRbg68X723XKe-pQ8UeDoYIzn08rf7KkFyx4qA=s0-d-e1-ft#https://github.com/notifications/beacon/AAAHZtpScfXCqi79K-5_DPD5FF5JSTIRks5thV33gaJpZM4S5WLa.gif
>

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]
