### ISSUE TITLE
Remove direct dependency of hyperkit driver from the minishift codebase

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2185]
Currently, we have a direct dependency of hyperkit driver[0] which should be removed otherwise whenever there is any dep which are part of minishift and hyperkit driver (like libmachine) get updated then it need exact version update from both side which should not be case because there might be no change in hyperkit side about a dependency.

[0] https://github.com/minishift/minishift/blob/master/pkg/minikube/cluster/cluster_darwin.go#L22

and

[1] https://github.com/minishift/minishift/blob/master/pkg/minikube/cluster/cluster_darwin.go#L75

**Comment by LalatenduMohanty** [comment]
> Currently, we have a direct dependency of hyperkit driver[0] which should be removed otherwise whenever there is any dep which are part of minishift and hyperkit driver (like libmachine) get updated then it need exact version update from both side which should not be case because there might be no change in hyperkit side about a dependency.

@praveenkumar interesting problem. Did not think about it when we merged the PR. 
So we should rely on "github.com/docker/machine/libmachine/drivers" ?
How do you suggest to fix this?

**Comment by LalatenduMohanty** [comment]
Resolved via #2192
