### ISSUE TITLE
Usage message for `minishift hostfolder add` is incomplete

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#2187]
### General information

  * Minishift version: v1.15.0+e07e789
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. `minishift hostfolder add`

### Expected
`Usage: minishift hostfolder add --type TYPE --source SOURCE --target TARGET HOST_FOLDER_NAME HOSTFOLDER_NAME`

### Actual
`Usage: minishift hostfolder add --type TYPE --source SOURCE --target TARGET HOST_FOLDER_NAME`

HOSTFOLDER_NAME

**Comment by gbraad** [comment]
Label? Sorry, not following

The name is the ID. So what is label?

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by anjannath** [comment]
@gbraad I am sorry, i updated the comment now.. i was looking for a better word, yes it is the hostfolder name.

**Comment by LalatenduMohanty** [comment]
> HOSTFOLDER_NAME or any better name.

We have already discussed this and could not find any other name. I think `HOSTFOLDER_NAME` is ok.

**Comment by anjannath** [comment]
> I think HOSTFOLDER_NAME is ok.

yes, this is okay.. its just the absence of it on the Usage msg is what this issue is for.

**Comment by anjannath** [comment]
Sorry guys false alarm.. 
```
Usage: minishift hostfolder add --type TYPE --source SOURCE --target TARGET HOST_FOLDER_NAME
```
