### ISSUE TITLE
Improve usage message for adding hostfolder interactively

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#2188]
### General information

  * Minishift version: v1.15.0+e07e789
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. `minishift hostfolder add --interactive`
  2. `minishift hostfolder add --type sshfs --interactive`
  3. `minishift hostfolder add --type cifs --interactive`

### Expected
Should get prompt to enter required information (target folder, source, etc..)

### Actual
`Usage: minishift hostfolder add --type TYPE --source SOURCE --target TARGET HOST_FOLDER_NAME`

**Comment by gbraad** [comment]
you need to add a name... I had reported this on the initial PR... so it IS an issue now?!?

**Comment by LalatenduMohanty** [comment]
Resolved by #2193
