### ISSUE TITLE
Considering renaming Homebrew cask minishift-beta to minishift-unstable

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#219]
This would allow for example also for the cases of alpha, beta and cr releases. Unless the common practice would be to use minishift-alpha, etc.

**Comment by tenfourty** [comment]
I think according to the naming guidelines of `homebrew-versions` if we have an alpha release or a cr release it would be possible to add formulas for that, however for the #208 as the release version from minishift was called a beta they renamed my contribution from minishift-unstable to minishift-beta!
