### ISSUE TITLE
How to enable NetworkPolicy in minishift?

### ISSUE THREAD

**Issue by roshans416** [minishift/minishift#2196]
### General information

  * Minishift version: v1.14.0+1ec5877
  * OS: macOS 
  * Hypervisor: VirtualBox

How to change the minishift openshift config to use "redhat/openshift-ovs-networkpolicy" plugin? Is it supported.?

**Comment by anjannath** [comment]
@roshans416 What exactly do you want  to do? If this involves patching the master config file for the openshift cluster you can use `minishift openshift config set --patch` to patch the config file with your changes.

Minishift uses `oc cluster up` to provison a single node openshift cluster, i think network policy and other stuff belongs in the cluster administration space, where you have a multi-node openshift cluster. If you describe your usecase and what exactly you want to do we maybe able to help you better.
