### ISSUE TITLE
xpaas addon should use apply and not create

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#2206]
In openshift, expected/recommended way to create resources in the cluster is via apply and not create. Apply will create or update the resource, while create will fail if the resource already exists.

https://github.com/minishift/minishift/blob/master/addons/xpaas/xpaas.addon#L8 and following lines

**Comment by anjannath** [comment]
Will apply create objects which are not previously defined... like create makes an object ?

**Comment by jorgemoralespou** [comment]
Yes, as I say in the description of the issue.

**Comment by LalatenduMohanty** [comment]
Resolved via #2431
