### ISSUE TITLE
Install oc client for ansible playbook -> crash

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#2208]
### General information

  * Minishift version: v1.15.1  & Centos image
  * OS: macOS
  * Hypervisor: xhyve 
  * cpus                 : 4
  * image-caching        : true
  * iso-url              : centos
  * memory               : 4G
  * openshift-version    : v3.9.0-alpha.3

### Intro

We have developed some ansible playbooks in order to provision openshift running using either "oc cluster up", "systemctl services" or "minishift" to install developer features such as jenkins, ,nexus, jaeger, istio, launcher, ... or to create x projects/users to demo purpose

Unfortunately the way that the centos's vm used by minishift is designed/partitionned doesn' t allow us to run playbooks as vm crashes

#### Use case played

minishift will crash if we just install wget and oc client ....

https://gist.github.com/cmoulliard/8b617ddb3b57bcbc83d581536001277a

### Questions

What do you recommend to do to provision minishift using ansible ?
Do we plan to have some convergences between "oc cluster up and "minishift" to : 
  - use ansible -> Should we go as 'oc cluster up' to use internally the `Ansible.go` class
  - Create temporary folders to wget/install/untar applications such as htpassword
  - Deploy application such as `oc` client under default `/usr/local/bin`

**Comment by gbraad** [comment]
can you explain in short what you mean with "install wget and oc" ?
If you install using RPM (yum), we have to mark this as invalid.

We do not support installing additional packages inside the root filesystem.
If you need to install something, please do so under `/opt` as this is a
relocated location.
Also, make sure to relocate RPMs to use this location.

See https://github.com/minishift/minishift-centos-iso/issues/116 and
https://github.com/minishift/minishift/issues/355#issuecomment-310972408
for more information

**Comment by gbraad** [comment]
Also see: https://gist.github.com/cmoulliard/8b617ddb3b57bcbc83d581536001277a#file-gistfile1-txt-L38-L41 in your own gist for more information.

**Comment by cmoulliard** [comment]
> oc cluster up

oc go client uses internally an Ansible go class [1] [2] to by example install `metrics`, `logging` features using the corresponding `openshift-ansible` playbook [3].
As minishift uses internally `oc cluster` to alose bootstrap openshift, I'm wondering why we could not use same approach to create a developer's openshift instance provisioned with `jenkins`, `nexus`, `jaeger`, ... where all of us we use `ansible` playbook to install such additional features with `minishift` or `oc cluster up`

**Comment by gbraad** [comment]
> wondering why we could not use same approach to create a developer's openshift instance

this is part of the discussions we are going to have with the OpenShift team responsible for the rewrite of the `cluster up` bootstrap method. At the moment this is a big unknown... maybe it is better to continue this discussion on the mailinglist ;-) => https://lists.minishift.io/admin/lists/minishift.lists.minishift.io

/cc: @minishift/minishift-dev

**Comment by LalatenduMohanty** [comment]
> What do you recommend to do to provision minishift using ansible ?
> Do we plan to have some convergences between "oc cluster up and "minishift" to :
> 
>     use ansible -> Should we go as 'oc cluster up' to use internally the Ansible.go class
>     Create temporary folders to wget/install/untar applications such as htpassword
>     Deploy application such as oc client under default /usr/local/bin

@cmoulliard I am still trying to understand that what this will bring to the table which Minishift does not provide now? 

> oc go client uses internally an Ansible go class [1] [2] to by example install metrics, logging features using the corresponding openshift-ansible playbook [3].
> As minishift uses internally oc cluster to alose bootstrap openshift, I'm wondering why we could not use same approach to create a developer's openshift instance provisioned with jenkins, nexus, jaeger, ... where all of us we use ansible playbook to install such additional features with minishift or oc cluster up

If you are just trying to cover this then we should wait till the "oc cluster up" restructuring completes.
