### ISSUE TITLE
Allow DNS to start from a dedicated/management vm

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2213]
At the moment, the DNS is specific to a single instance. This allows to self-contain all of the settings for the instance, but it complicates when more than one instance is used.

With #2211 we can add addtional rules to an instance, which would also cover the settings needed for the other VM => `m start --network-nameservers` can help setting the DNS for the other instance

This allows to point to a dedicated VM for the DNS rules. While if #273 would be added, we can have a minimal management VM that runs the DNS server, and possible other services, that can be shared between multiple instances of Minishift. Imagine to start this with `m start --management-vm` or something similar. In that case, adding using #2211 would always create a global entry that will work for ALL instances.

@minishift/minishift-dev WDYT?

**Comment by gbraad** [comment]
Using #2217:
```
$ MINISHIFT_ENABLE_EXPERIMENTAL=true minishift start --iso-url b2d --no-provision --profile dns --disk-size 1G --memory 512M
```
Using #2076:
```
$ minishift dns start
```

**Comment by gbraad** [comment]
With https://github.com/gbraad/dockerfile-dnsmasq-alpine it is possible to run as a smaller disksize:

```
$ MINISHIFT_ENABLE_EXPERIMENTAL=true \
   minishift start \
   --iso-url b2d \
   --no-provision \
   --profile dns \
   --disk-size 64M \
   --memory 512M
```

it uses `gbraad/dnsmasq-alpine:latest` as container image at the moment. Might be a possiblity to make this configurable to allow custom containers to be used for system services.

**Comment by LalatenduMohanty** [comment]
@gbraad I am not enthusiastic about starting another VM for resolving  DNS routes. However we should solve the use case of multiple profiles. Will look in to this and see if we can take some other route.

**Comment by gbraad** [comment]
@LalatenduMohanty we do enable to deploy on a locally known Docker runtime if needed, which in most cases already exist in our userbase. Eventually #2233 is an option... The `local` Docker here is nothing else than the remote Docker we already need for #392

**Comment by gbraad** [comment]
Still relevant
