### ISSUE TITLE
Improve navigation of www.openshift.org/minishift

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2220]
We need to improve the landing page of Minishift [2] as it have not been updated from sometime now. Also we got some suggestion about it too [1].

The source of the landing page live at [3].

Created the issue in Minishift repository as it is easier to track it here. 

[1] https://github.com/minishift/minishift/issues/2121#issuecomment-373673728
[2] https://www.openshift.org/minishift/
[3]  https://github.com/openshift-cs/openshift.org/tree/master/source/minishift

**Comment by robin-owen** [comment]
The links that we currently have which guide the user to the documentation for setting up driver plug-ins also point to the wrong address now. This is a side-effect of #2025.

I'll start working on this issue as soon as possible.

**Comment by robin-owen** [comment]
@gbraad This was an oversight on my part while working on that PR. There's only one link under the Get Started heading (KVM) which attempts to guide the reader to a specific page of our documentation.

Honestly, I think it's better to have fewer links which have to be maintained. I'm not sure that the openshift.org/minishift page offers much more than a landing space. We can guide users to the more generalized documentation from that page and let them navigate through the documentation from there. This also mirrors some of what was said in the feedback provided by https://github.com/minishift/minishift/issues/2121#issuecomment-373673728.

**Comment by robin-owen** [comment]
@LalatenduMohanty I've opened https://github.com/openshift-cs/openshift.org/pull/94 to address this.

**Comment by LalatenduMohanty** [comment]
@robin-owen Awesome. I can see the PR is merged now and the page is live now. Thanks.
