### ISSUE TITLE
Openshift 3.9.0 fails with minikube ISO.

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2222]
Looks like new check introduced in 3.9.0 and also minikube ISO provide a wrong symlink to file :(

```
$ ./minishift start --iso-url minikube --show-libmachine-logs -v=5
[...]
Starting OpenShift using openshift/origin:v3.9.0 ...
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
FAIL
   Error: could not update OpenShift configuration
   Caused By:
     Error: cannot start container 8caa1895d8bda148b92d245faf3bec5a51488f2a144c7bb4f54aaf2b42e1a29e
     Caused By:
       Error: Error response from daemon: {"message":"open /etc/resolv.conf: no such file or directory"}

Error during 'cluster up' execution: Error starting the cluster.

$ ./minishift ssh
$ ls -l /etc
lrwxrwxrwx 1 root root         34 Jan 23 23:03 resolv.conf -> ../run/systemd/resolve/resolv.conf
$ cat ../run/systemd/resolve/resolv.conf
cat: ../run/systemd/resolve/resolv.conf: No such file or directory

$  cat /run/systemd/resolve/resolv.conf
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known DNS servers.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 192.168.101.1
nameserver 192.168.42.1
```

**Comment by gbraad** [comment]
minikube uses systemd-resolved to setup the DNS resolving.
This is kind of a caching DNS solution, much like dnsmasq.

It has a symlink pointing to the actual resolv.conf.
But this process completes asynchronous.

I have disabled the service with the DNS server #201 and resolve to my own
/etc/resolv.conf.

**Comment by gbraad** [comment]
disable `systemd-resolved` from the provisioner maybe?

**Comment by LalatenduMohanty** [comment]
Resolved via #2223

**Comment by tamalsaha** [comment]
@LalatenduMohanty, is it possible to try 3.9.0 with minishift v1.15.1 or do I need to wait for v.1.16.0 release?

**Comment by budhrg** [comment]
@tamalsaha I will take my words back. :) Got the question wrong here. So, yes, if you want to start minikube iso with 3.9.0 then try to use minishift binary from
http://artifacts.ci.centos.org/minishift/minishift/master/latest/

**Comment by tamalsaha** [comment]
I updated to latest minishift and tried the following command . It worked for me. Thanks!

```
$ rm -rf ~/.minishift/
$ minishift start --vm-driver=virtualbox --openshift-version v3.9.0
```

**Comment by gbraad** [comment]
Good to hear. but why the `rm -rf` ?

**Comment by tamalsaha** [comment]
I had old version of minishift . It seems to have some certs etc. So, after deleting the folder, there was no issue.

**Comment by gbraad** [comment]
certs should not be an issue. it is best to try first to use `minishift delete --force`. if that doesn't work, you use `minishift delete --clear-cache` to remove old ISO and clients. only use `rm -rf` as last resort, as in the worst case, the VM is still registered with the hypervisors.
