### ISSUE TITLE
Refactor/use of interfaces related to VmDockerCommander, VmSystemdCommander

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2227]
In code, we do not make good use of the defined interfaces. It can actually help us with the test implementation, but at the moment we directly instantiate and use VmDockerCommander instead.

**Comment by LalatenduMohanty** [comment]
> It can actually help us with the test implementation

you mean we would be able to mock it , right?

**Comment by gbraad** [comment]
right...
