### ISSUE TITLE
Improve code around virtual machine regsitration

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#223]
Follow up issue for issue #137 and pull request #222:

* Improve registrar detection algorithm. Don't use error (_ErrDetectionFailed_) for handling normal program flow
* Review _TestRedHatRegistratorRegister_ and _TestRedHatRegistratorUnregister_
   * Why are register resp. unregister called twice?
   * One seems to be still able to change the cmd string (at least the first time around, why?)
* Add test around providing credentials, either via flags or environment variables

**Comment by praveenkumar** [comment]
> Add test around providing credentials, either via flags or environment variables

Credentials are part of flag/env for viper and looks like that is already tested as part of `root_test` imo.

**Comment by hferentschik** [comment]
Resolved via pull request #231
