### ISSUE TITLE
Implement MINISHIFT_HOME env variable

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#224]
The idea is to have the same functionality as in Vagrant, where via _VAGRANT_HOME_ the base directory of Vagrant can be determined. The default would stay with _~/.minishift_.

This gives us:

* A way to run multiple minishift instances (without the need to change anything in the way we structure the content of _MINISHIFT_HOME_
* Better ability to test (unit + integration tests), since it allows to run tests isolated in their dedicated home directory
* Potential to have the minishift data directory outside of _~/.minishift_

**Comment by budhrg** [comment]
+1 make sense

**Comment by jimmidyson** [comment]
Should be configurable via flag as well as config file too (thanks to
viper).

**Comment by praveenkumar** [comment]
@hferentschik @jimmidyson we also have to take care of `minishift status` which suppose to tell how many instance of minishift running like vagrant have `vagrant global-status`.

**Comment by jorgemoralespou** [comment]
@hferentschik If you're going to implement the ability to run multiple instances, what I call profiles, they should live in the MINISHIFT-HOME by default. Making the user specify a different home per profile is not a good option. I would expect to be able to use the feature in an easy way. That means that probably I would rethink the .minishift structure and change it if required. 

If on the contrary this is to run concurrent instances, maybe it's an option, although I would still prefer not need to provide a different minishift home unless I want a different path than the default.

**Comment by hferentschik** [comment]
> Making the user specify a different home per profile is not a good option. I would expect to be able to use the feature in an easy way.

Why not. One way or the other the user needs to specify the "profile". But yes, having the profiles, as part of the same ~/.minishift directory has benefits, for example when listing and reporting on the various profiles and running VMs.

I actually think both might be required. A way to control the location of the minishift home directory and the ability to have multiple VMs as part of a single home directory. 

Controlling the home directory should be easy with very few code changes. In an initial step it will also offer multiple "profiles", even though maybe not in an optimal way. A next step could then be to re-structure the minishift directory and allow multiple profiles within.

**Comment by hferentschik** [comment]
> Should be configurable via flag as well as config file too 

+1

**Comment by jorgemoralespou** [comment]
@hferentschik 
> Why not. One way or the other the user needs to specify the "profile"

The experience of doing: 

minishift start PROFILE

Or 

MINISHIFT_HOME=xyz minishift start 

Is quite different. Also, if you bind profiles to different minishift homes you'll lose reusability of things that live in the minishift home, e.g the iso.

**Comment by hferentschik** [comment]
Merged via pull request #255
