### ISSUE TITLE
`minishift openshift version list` is broken

### ISSUE THREAD

**Issue by containscafeine** [minishift/minishift#2242]
```console
$ minishift openshift version list
Error while trying to get list of available Origin versions: *json.UnmarshalTypeError
json: cannot unmarshal object into Go value of type []version.releaseTags
&json.UnmarshalTypeError{Value:"object", Type:(*reflect.rtype)(0xc32600), Offset:1, Struct:"", Field:""}

$ minishift version
minishift v1.15.1+a5c47dd
```

**Comment by containscafeine** [comment]
This can only be reproduced when GitHub's rate limiting kicks in. Maybe there needs to be check in the code for that.

**Comment by anjannath** [comment]
We can add a check and print a message to set `MINISHIFT_GITHUB_API_TOKEN`, you can set this environment variable and _minishift_ will use the token, although `minishift update` does not seem to use it as reported in #1920 you can try and see if it works for `minishift openshift version list`

**Comment by LalatenduMohanty** [comment]
> $ minishift openshift version list Error while trying to get list of available Origin versions: *json.UnmarshalTypeError json: cannot unmarshal object into Go value of type []version.releaseTags &json.UnmarshalTypeError{Value:"object", Type:(*reflect.rtype)(0xc32600), Offset:1, Struct:"", Field:""}

The error is really bad and there is no way user can understand the root cause of the error. So we should better error handling here for sure.
