### ISSUE TITLE
Minishift and private registry

### ISSUE THREAD

**Issue by coelho-extremosistemas** [minishift/minishift#2246]
### General information

  * Minishift version: v1.15.1+a5c47dd 
  * OS: Linux 
  * Hypervisor: KVM 

Hi "personas"...
I am trying to use my private registry to pull images:
but I get importing images from registry "myInternal.registry.nexus:5000" is forbidden

### Steps to reproduce

```
$ minishift start
$ oc login -u system
$ oc new-project test1
$ docker login myInternal.registry.nexus:5000
$ oc secrets new mysecret666 .dockerconfigjson=~/.docker/config.json
$ oc secrets link default mysecret666 --for=pull
$ oc secrets link builder mysecret666 --for=pull
$ oc secrets link deployer mysecret666 --for=pull
$ oc new-app myInternal.registry.nexus:5000/myimage:1.0 --loglevel=5

```
###LOG

I0405 11:43:48.434514    8414 dockerimagelookup.go:79] checking remote registry for "myInternal.registry.nexus:5000/myimage:1.0"
I0405 11:43:48.487373    8414 dockerimagelookup.go:98] checking local Docker daemon for "myInternal.registry.nexus:5000/myimage:1.0."
I0405 11:43:48.488024    8414 componentresolvers.go:59] Error from resolver: [can't lookup images: ImageStreamImport.image.openshift.io "newapp" is invalid: spec.images[0].from.name: Invalid value: "myimage": importing images from registry "myInternal.registry.nexus:5000" is forbidden, only images from "172.30.1.1:5000,docker.io,*.docker.io,*.redhat.com,gcr.io,quay.io,*.amazonaws.com" are allowed]
F0405 11:43:48.488193    8414 helpers.go:116] error: can't lookup images: ImageStreamImport.image.openshift.io "newapp" is invalid: spec.images[0].from.name: Invalid value: "myimage": importing images from registry "myInternal.registry.nexus:5000" is forbidden, only images from "172.30.1.1:5000,docker.io,*.docker.io,*.redhat.com,gcr.io,quay.io,*.amazonaws.com" are allowed
error: no match for "myInternal.registry.nexus:5000/myimage:1.0"

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples

Is this a bug or did I forget something?

**Comment by praveenkumar** [comment]
@coelho-extremosistemas Have you specified this internal/private registry as insecure when started minishift? you can also check if your insecure registry is listed for docker daemon running inside the VM by using `minishift ssh -- docker info`.

Something like

```
./minishift start --insecure-registry myInternal.registry.nexus:5000
```

**Comment by coelho-extremosistemas** [comment]
Hi @praveenkumar. 
I repeat and test to start minishift with insecure-registry and without. But I get the same result.
with `minishift ssh -- docker info` I not see my registry listed.
```
$ minishift ssh -- docker info
Containers: 16
 Running: 5
 Paused: 0
 Stopped: 11
Images: 5
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 39
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.41-boot2docker
Operating System: Minishift Boot2Docker ISO Version: 1.2.0
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: minishift
ID: BGRB:G7I4:ASXD:C24Y:2WVX:W2H7:UQXX:RZYV:FPCK:AHAF:OFHI:2LNA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 45
 Goroutines: 48
 System Time: 2018-04-06T11:31:04.612131625Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=kvm
Insecure Registries:
 172.30.0.0/16
 127.0.0.0/8
```

Started with: `minishift start --insecure-registry myInternal.registry.nexus:5000`

**Comment by LalatenduMohanty** [comment]
@coelho-extremosistemas `minishift start --insecure-registry myInternal.registry.nexus:5000` needs fresh start (provisioning).  So please, perform `minishift delete` then `minishift start --insecure-registry myInternal.registry.nexus:5000`. 

I tried to reproduce it and I can see it in the output of `minishift ssh "docker info"
```
Insecure Registries:
 myInternal.registry.nexus:5000
 172.30.0.0/16
 127.0.0.0/8
```

**Comment by coelho-extremosistemas** [comment]
Hi...
I upgrade my OS to fedora 27, and now I can see Insecure Registries:
```
Insecure Registries:
 myInternal.registry.nexus:5000
 172.30.0.0/16
 127.0.0.0/8

```
But.. after create a new project, I am trying create new app from my registry, and I get a this msg:

`oc new-app myInternal.registry.nexus:5000/myimage --name=teste-app
coelho@ myInternal.registry.nexus's password: 
`
 
I recreate all secrets, like in the first post....

**Comment by GuilhermeCamposo** [comment]
There is a configuration on master-config.yaml that describes which registries are allowed. 

```
imagePolicyConfig:
  allowedRegistriesForImport:
  - domainName: localhost
```

The problem is that I don't know how to change this configuration on minishift

**Comment by budhrg** [comment]
HI @coelho-extremosistemas , 

Could you try the suggestion mentioned by @GuilhermeCamposo above?

**Comment by coelho-extremosistemas** [comment]
Hi @budhram.
The suggestion from @GuilhermeCamposo, help-me to find a solution.
At the beginning, the file "var/lib/minishift/openshift.local.config/master
/master-config.yaml" does not exist, but I use `./minishift openshift config set --patch` to change this conf and create this file.
I add my domain to the list of allowedRegistriesForImport.


Thanks for all

**Comment by oliver-data-science** [comment]
@coelho-extremosistemas  could you please provide your json for patching the allowedRegistriesForImport? I fail to get a working script

**Comment by t-hart** [comment]
Probably too late to help the poster above, but for anyone coming to this later, the full command to run to patch is: 
```
minishift openshift config set --patch '{"imagePolicyConfig": {"allowedRegistriesForImport": [{"domainName": "localhost"}]}}'
```
