### ISSUE TITLE
Docker auth error on RHEL with centos flag

### ISSUE THREAD

**Issue by doncorsean-private** [minishift/minishift#2247]
### General information

  * Minishift version: minishift v1.15.1+a5c47dd
  * OS: $ cat /etc/os-release
NAME="Red Hat Enterprise Linux Workstation"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Workstation"
VARIANT_ID="workstation"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:workstation"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"

  * Hypervisor: $ vboxmanage --version 
5.1.30r118389

### Steps to reproduce

  1. minishift start --iso-url=centos --vm-driver=virtualbox
  2. eval $(minishift oc-env)
  3. eval $(minishift docker-env)
  4. oc login
  5. docker login -u developer -p $(oc whoami -t) $(minishift openshift registry)
  6. docker push $(minishift openshift registry)/foo/bar

### Expected
Pushed image into minishift registry

### Actual
The push refers to a repository [172.30.1.1:5000/foo/bar]
b358b7e4ae86: Preparing 
a5f87d7fb92d: Preparing 
e4a7417a7408: Preparing 
edf10865c072: Preparing 
dc8e5651249f: Preparing 
2eb0bd75ad19: Waiting 
5381a6024cf1: Waiting 
3071c629261d: Waiting 
4602b8ddbd34: Waiting 
13fc2d3dabbc: Waiting 
c8049cc8db47: Waiting 
43ace3896256: Waiting 
69bd93b9db4e: Waiting 
unauthorized: authentication required

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
https://gist.github.com/doncorsean/919fb5a3695f11b95dc0e767fa03b73c

**Comment by praveenkumar** [comment]
@amitkrout @agajdosi Can you folks check this if this really an issue for RHEL7 host?

**Comment by agajdosi** [comment]
@praveenkumar @doncorsean Push to the registry works for me, tried with Minishift v1.15 with CentOS iso on RHEL7 with both KVM and VirtualBox.

**Comment by amitkrout** [comment]
@agajdosi Cool!! So you tag the image before pushing ?

**Comment by agajdosi** [comment]
@doncorsean No worries, thanks for the issue even though it was false alarm. Glad it works for you :)
