### ISSUE TITLE
Accept lower case proxy variables too

### ISSUE THREAD

**Issue by svenstaro** [minishift/minishift#2251]
Currently, only uppercase `HTTP_PROXY` and friends are accepted. Lowercase ones should also be accepted and take precedence over uppercase ones as curl also does it that way and it seems to be a sensible thing to do.

Also, this is already accepted for `NO_PROXY` and `no_proxy` in minishift so it only makes sense to accept it here, too.

**Comment by gbraad** [comment]
Thanks... just make sure both uppercase and lowercase are used, with correct precedence... I believe lowercase takes priority... right?

**Comment by svenstaro** [comment]
Yeah, that's right. I'll add a test for the precedence.

**Comment by svenstaro** [comment]
There's the test, @gbraad.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/2252
