### ISSUE TITLE
Update `github.com/google/go-github` vendor pkg

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#2254]
Currently we are using go-github pkg with `revision:30a21ee1a3839fb4a408efe331f226b73faac379`. which is pretty old..

It lacks implementation of some functions for the `RepositoryRelease` type, like the [`GetTagName`](https://godoc.org/github.com/google/go-github/github#RepositoryRelease) function, there could certainly be more.

Note: This might break our current implementation of `DownloadOpenshiftReleaseBinary()`

**Comment by LalatenduMohanty** [comment]
I think we should move to a higher version. Also in Gopkg.toml I do not see version which we should fix.

```
[[constraint]]
    name = "github.com/google/go-github"
    revision = "30a21ee1a3839fb4a408efe331f226b73faac379"
```

**Comment by praveenkumar** [comment]
@anjannath Do you want me to take a look into this?

**Comment by anjannath** [comment]
@praveenkumar Sure, go ahead!
