### ISSUE TITLE
Create new config option for Hyper-V virtual switch

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#2258]
Related to #2096 and #1622

**Comment by anjannath** [comment]
@budhrg There's issue with how windows expands environment variables, when they contains unicode characters, we are relying on the `HYPERV_VIRTUAL_SWITCH` env variable for the switch name to use with hyperv, but when it contains unicode characters (as in the case of international locales) windows strips them from the name we passed, and the switch cannot be found while creating the vm. so we need a config option to get the name of the virtual switch for hyperv.

More details are present in #2096

**Comment by gbraad** [comment]
if as a first issue, I would expect a little bit more hand-holding... as `start.go`, `config.go` and `start_preflight.go` would have to be modified.

**Comment by LalatenduMohanty** [comment]
@anjannath It is the followup issue for https://github.com/minishift/minishift/issues/1622#issuecomment-361563276,  right? The issue description is not clear about it.
