### ISSUE TITLE
Add tests for `m ip --set-static`

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2259]
We should be able to add tests for `m ip --set-static` for platform that use xhyve, VirtualBox and HyperV

Note: KVM is not supported ATM

**Comment by praveenkumar** [comment]
I hope this is integration test so may be put that in the issue description and also add label same.

**Comment by LalatenduMohanty** [comment]
I was also thinking about it. I agree that  we need to add integration tests for it even if it does not work for KVM.
