### ISSUE TITLE
Add build pipeline for our modifcations to the upstream Minikube ISO

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2260]
At the moment it is not very feasible to run a local build for the ISO, as this could last for 3+ hours. Maybe it is best to introduce a CI build pipeline that we can use to test our own modifications on, but only use this to stage our PRs for upstream.

We would prefer to consume to upstream ISO... so we need to consider how to approach this. do we have a cloned repo of minikube for the ISO? or do we split out part of the tree?

**Comment by praveenkumar** [comment]
This is for minikube ISO side?

**Comment by LalatenduMohanty** [comment]
@praveenkumar yes, this is for Minikube ISO. 

The idea is to test the changes we are doing/proposing in Minikube ISO through CI. Specially because the the local build of the ISO is slow and time consuming . But Minikube is not a separate repo hence I do not know how we will have the CI setup.
