### ISSUE TITLE
Add option to `m start` to skip/ignore preflight checks during startup

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2267]
Although we can configure the skip state of our pre-flight checks, it might be helpful to add a global option. Either ~~`--skip-preflight-checks`~~ `--skip-startup-checks` or ~~`--ignore-preflight-errors`~~ `--ignore-startup-errors`

This means `cmd/start.go` needs to be modified to take a new option. It can be considered to make this persistent by altering `cmd/config.go` too.

**Comment by gbraad** [comment]
To stay consistent with the documentation, these should be exposed to the outside world as "startup checks".

**Comment by piyush1594** [comment]
@budhrg We are good to close this now after merging #2325

**Comment by budhrg** [comment]
Yes @piyush1594 closing it now.

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift/pull/2325
