### ISSUE TITLE
Waiting for xx mins for pods in deployment xxx to become ready

### ISSUE THREAD

**Issue by PierrickI3** [minishift/minishift#227]
Hi,

(trying minishift for the first time)

OS: Windows 2012 R2
Hypervisor: Hyper-V

I have started minishift using the following command: `minishift start --cpus=4 --memory=8192 --vm-driver=hyperv`

```
Starting local OpenShift cluster...
 18.42 MB / 18.42 MB [=====================================================================================] 100.00% 0s
Provisioning OpenShift via 'C:\Users\Administrator\.minishift\cache\oc\v1.3.1\oc [cluster up]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.3.1 image ...
   Pulling image openshift/origin:v1.3.1
   Pulled 0/3 layers, 3% complete
   Pulled 0/3 layers, 20% complete
   Pulled 0/3 layers, 36% complete
   Pulled 0/3 layers, 49% complete
   Pulled 1/3 layers, 59% complete
   Pulled 1/3 layers, 73% complete
   Pulled 2/3 layers, 88% complete
   Pulled 2/3 layers, 99% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ...
   Using 192.168.0.43 as the server IP
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Server Information ...
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.0.43:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
```

I then logged in, created a project and used the following [yaml](https://gitlab.com/gitlab-org/omnibus-gitlab/raw/openshift-idea-to-production/docker/openshift/idea-2-prod-template.json) to start gitlab in minishift following this [tutorial](https://about.gitlab.com/handbook/sales/idea-to-production-demo/).

 However, all I get is this in the `gitlab-runner` pod:
```
--> Scaling gitlab-runner-1 to 1
--> Waiting up to 10m0s for pods in deployment gitlab-runner-1 to become ready
error: update acceptor rejected gitlab-runner-1: pods for deployment "gitlab-runner-1" took longer than 600 seconds to become ready
```
and it fails. I increased the timeout to 6000 seconds and got the same result.

I ran `minishift logs` but it does not return anything. How can I troubleshoot my issue?

**Comment by praveenkumar** [comment]
@PierrickI3 Thanks for trying out minishift, I am also able to reproduce same issue and added it as bug right now. We will try to find out what causing that and let you know our findings.

**Comment by PierrickI3** [comment]
@praveenkumar Thanks!

**Comment by jorgemoralespou** [comment]
@praveenkumar Note that gitlab requires anyuid to work. Actually openshift will not show an error and probably this is the problem.

**Comment by PierrickI3** [comment]
@jorgemoralespou Is this a limitation of Minishift? I can't find any mention of anyuid in the docs

**Comment by jimmidyson** [comment]
Gitlab doesn't require anyuid to work, just needs to be configured to run on non privileged ports (eg SSH on port 2222). You can then set up the service on port 22 to target port 2222.

**Comment by jorgemoralespou** [comment]
@jimmidyson depends which gitlab you install. Latest official gitlab templates for openshift requires anyuid for the gitlab-ce container. There's in the latest template a service account to just add the scc to that one service account.https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/docker/openshift-template.json#L271

I think here they are using the official templates so depending on the version they will require a anyuid serviceaccount (whether is the default or the specific for the latest template) and also 4 PVs. This might be the other issue @praveenkumar might be experiencing. 

This is a working plugin for oc-cluster-wrapper with all the needed steps. Sadly they haven't updated all their blogs to reflect all the changes they've done. 

https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/plugins/plugins.d/gitlab.local.plugin

**Comment by jorgemoralespou** [comment]
@praveenkumar @jimmidyson I rectify. Although the gitlab container needs anyuid, the experience in this case would be a pod erroring at startup. When the pod does not get scheduled probably is because not meeting one of the requirements for the pod, which in this case most probably is the persistence volumes not being available. 
This can be easily seen in the events.

**Comment by LalatenduMohanty** [comment]
@jimmidyson I think you are right. I added anyuid to OpenShift in minishift with the command `oc adm policy add-scc-to-user anyuid system:serviceaccount:ci:gitlab-ce-user --as=system:admin`. However deployment failed with below error. Which seems like the persistence volumes are not available.

```
Error creating: pods "gitlab-1-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used] 
```

**Comment by jorgemoralespou** [comment]
@LalatenduMohanty that issue you're referring is because it's trying to use
hostPath PV and for that you need a hostmount or hostaccess (don't remember
exact name) SCC.

I've looked at the used runner template and I would not use it since it
doesn't use PVC but direct hostPath which IMHO should not be used other
than for test.

hostPath requires the mentioned SCC and also can give problems with
permissions on the host at the specified path.

**Comment by LalatenduMohanty** [comment]
@jorgemoralespou Thanks, I deleted my original comment as I realized the error is not related the persistent volume issues. 
For others, To give context to @jorgemoralespou's comment,  I faced below error while setting up gitlab after fixing anyuid in Minishift. 

`$ ./oc adm policy add-scc-to-user anyuid system:serviceaccount:ci:gitlab-ce-user --as=system:admin`

```
Error creating: pods "gitlab-mattermost-1-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
```

**Comment by jimmidyson** [comment]
Host path provisioner is also really limited to running as root, limited on purpose by design in kubernetes. I wonder if it makes sense to change permissions to 0770 (pods run in root group regardless of uid iirc) - might be worth a PR upstream & to openshift to discuss that change?

**Comment by jorgemoralespou** [comment]
@jimmidyson I was talking with @csrwng last week regarding this feature in oc cluster up. I would consider using gluster as persistence driver (now that it works and is easy to set up) as it's a full featured persistence driver that also provides autoprovisioning.

**Comment by mazzy89** [comment]
`Error creating: pods "server-3-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]`

I have the above error when creating a deployment config where I specified an `hostPath` in my `DeploymentConfig`. any idea?

**Comment by jorgemoralespou** [comment]
You need to grant at least the hostaccess SCC to the user.

To check what Security Context Constrains you have do (as admin user):

````
oc get scc 
````

Review what capabilities does your container need, and grant the appropriate SCC. If none fits, create your own.

````
oc adm policy add-scc-to-user <SCC_name> <user>
````

Note that user will be the serviceaccount with which the pod gets deployed, if none specified, then the default serviceaccount will be used, so "system:serviceaccount:<PROJECT_NAME>:default"

Hope this helps,

**Comment by praveenkumar** [comment]
@hferentschik @jorgemoralespou Can we close this issue now?

**Comment by jorgemoralespou** [comment]
I guess, but you should ask the reporter. @mazzy89 @PierrickI3 Can we close this issue?

**Comment by mazzy89** [comment]
for me yes

**Comment by budhrg** [comment]
If @PierrickI3 also agrees, then we can close this one.

**Comment by PierrickI3** [comment]
I do not have the time to re-test this at the moment. Go ahead and close it and we can re-open if required.
