### ISSUE TITLE
Do we still need to suppport 1.4.1 version?

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2272]
Right now 3.9 is released and we are still listing `1.4.1` in our `openshift version-list`. I think we need to rethink what maximum we can support as backward compatibility. My suggestion is best we can support major 3 released version at any given point, not before that (ex. v3.6.1 should be our minimum supported version).

@jorgemoralespou what is your input on this?

@minishift/minishift-dev wdyt?

**Comment by LalatenduMohanty** [comment]
> My suggestion is best we can support major 3 released version at any given point, not before that (ex. v3.6.1 should be our minimum supported version).

I am also inclined towards it, but before we do that, can we get some feedback from our users? which will help us deciding that.

**Comment by gbraad** [comment]
If they need an older version, you can get an older version of minishift
from our releases page.

I do not see a real need to 'ask' them to how much support we will give
them... because we all know, when they say they use 1.4.1, we will likely
answer: 'sorry, can't help".

**Comment by praveenkumar** [comment]
@minishift/minishift-dev Since we already sent mail about it and no response for same, so I am going ahead and do the required modification.
