### ISSUE TITLE
Che addon test needs exported functions in testsuite package

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2275]
Allow execution of `oc` and `minishift` commands for external code in testsuite package by exporting appropriate functions and variables. Mostly: `ExecutingOcCommand`, `ExecutingMinishiftCommand`, `GetLatestCommandOutput`.

**Comment by anjannath** [comment]
@agajdosi Which external code is going to use the exported functions? Are you adding new step definitions?

**Comment by agajdosi** [comment]
@anjannath It is code for https://github.com/minishift/minishift-addons/issues/104. I am refactoring original code by JPinkney and migrating it from minishift/minishift to minishift/minishift-addons as requested. His code needs to run some commands directly, so there is a need to have those functions exported.

**Comment by LalatenduMohanty** [comment]
Resolved via #2295
