### ISSUE TITLE
admin-user addon is throwing an oc error on minishift start

### ISSUE THREAD

**Issue by eriknelson** [minishift/minishift#2278]
### General information

  * Minishift version: minishift v1.14.0+1ec5877
  * OS: Fedora 27
  * Hypervisor: KVM

### Steps to reproduce

  1. minishift start
  2. At the end of the run, the error is produced. It's also thrown during `openshift addons list`.

### Expected
If admin-user is part of minishift, expect it to work with the version of oc distributed.

### Actual
Error:

```
Skipping addon 'admin-user' in '/home/ernelson/.minishift/addons/admin-user' due to parse error: Unable to process command: '!oc create user admin --full-name=admin'
```

**Comment by praveenkumar** [comment]
@eriknelson you are using an older version of minishift which not able to handle the latest addons changes we did recently, can you update your minishift verison using `minishift update` command so this issue will be resolved.

**Comment by jorgemoralespou** [comment]
@praveenkumar Why would that addon be run if that is a core addon that should only be updated when you get the new release of minishift?

**Comment by LalatenduMohanty** [comment]
> Why would that addon be run if that is a core addon that should only be updated when you get the new release of minishift?

Not sure if I understand your question. It is obvious that the admin-user add-on is enabled prior to `minishift start`.

**Comment by praveenkumar** [comment]
> Why would that addon be run if that is a core addon that should only be updated when you get the new release of minishift?

@jorgemoralespou when you update/upgrade minishift it ask for update of the defaults addon (core one) if a user don't select it then there might be stale there. But even then higher version of minishift support for addon which are part of older one but not vice-versa if there is change in addon DSL.

**Comment by praveenkumar** [comment]
Closing this issue since now we have like more that 2-3 release after add-ons syntax changed.
