### ISSUE TITLE
Create make target `assets` to build static assets (default add-ons)

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#2281]
we have to do `make clean` and then `make` to rebuild those assets now, it'd be nice to have a target explicitly for this.

**Comment by LalatenduMohanty** [comment]
@anjannath Why do you want to build the assets specifically? What is the use case?

**Comment by anjannath** [comment]
@LalatenduMohanty When you are making changes to the default add-ons, and you want to install them running `minshift addons install --default`. 

So that we don't have to do `make clean` and `make` which takes a little bit of time..

**Comment by praveenkumar** [comment]
> So that we don't have to do make clean and make which takes a little bit of time.. also gives meaning you are building the assets not cleaning.

Doesn't `make clean` already clean the workspace before you hit make again? 

About the time it just the build time and most of the things like your vendor are already cached.

**Comment by anjannath** [comment]
> Doesn't make clean already clean the workspace before you hit make again?

That is what i am trying to avoid you want to build the assets not clean the workspace, so the target `make assets` before `make`
