### ISSUE TITLE
minishift start fails with proxy authentication and password containing special character(s)

### ISSUE THREAD

**Issue by PrimerFender** [minishift/minishift#2283]
### Description

Hello, I am new, and this is a new install of minishift, but wanted to share potential issue. I ran the command to show logs, but not sure where they are stored, if you can tell me I will upload. I think the problem is 1) We have a proxy which requires authentication and 2) my password contains a `#` symbol which is also the character for comments in `bash`. I believe that when minishift attempts to use the proxy, it use the correct environment variable, however the special character is not escaped and thus the proxy string is incomplete (username:password@server:port). The error message `invalid proxy URL port "HashTag"` indicates it sees the `username:password` interpreted as `server:port` instead.

### General information

  * Minishift version: v1.15.1+a5c47dd
  * OS: Linux (RHEL 7.4)
  * Hypervisor: KVM

### Steps to reproduce

  1. User info example: Username:`username` Password:`HashTag#Password`
  1. $ export http_proxy=http://username:HashTag#Password@proxy.company.com:8080
  2. $ echo $http_proxy
    http://username:HashTag#Password@proxy.company.com:8080
  3. $ minishift start --show-libmachine-logs -v5

### Expected

minishift starts like normal

### Actual

-- minishift version: v1.15.1+a5c47dd
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.7.2' is valid ... SKIP
github.com is not accessible over internet or host is not connected to internet
-- Checking if requested OpenShift version 'v3.7.2' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executablinvalid proxy URL port "HashTag"e ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
Error starting the cluster: Error attempting to download and cache 'oc': Cannot get the OpenShift release version v3.7.2: Get https://api.github.com/repos/openshift/origin/releases/tags/v3.7.2: invalid proxy URL port "HashTag"

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@PrimerFender Can you use the single quote when setting those proxy environment variables? minishift codebase should just get using `os.Getenv` those variable and not manipulate. Most likely it manipulated when you assigned it in the shell env.

something  like 

```
$  export http_proxy='http://username:HashTag#Password@proxy.company.com:8080'
```

**Comment by PrimerFender** [comment]
@praveenkumar Thank you for your response, I retried with your recommendation but get the same error. I don't think the value was manipulated, rather just read literally, and when it encountered the `#` symbol it processed it as a comment prefix and stopped reading the rest of the variable/string value.

```bash
$ export http_proxy='http://username:HashTag#Password@proxy.company.com:8080'
$ export https_proxy=$http_proxy
$ echo $http_proxy
http://username:HashTag#Password@proxy.company.com:8080
$ echo $https_proxy
http://username:HashTag#Password@proxy.company.com:8080
$ minishift start --show-libmachine-logs -v5
-- minishift version: v1.15.1+a5c47dd
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.7.2' is valid ... SKIP
github.com is not accessible over internet or host is not connected to internet
-- Checking if requested OpenShift version 'v3.7.2' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
Error starting the cluster: Error attempting to download and cache 'oc': Cannot get the OpenShift release version v3.7.2: Get https://api.github.com/repos/openshift/origin/releases/tags/v3.7.2: invalid proxy URL port "HashTag"
$ 
```

**Comment by praveenkumar** [comment]
@PrimerFender this is something not even bash handles so might need to convert the special characters to hex and the use it, Below is the list of some of the special char.

```
Char	: Hex
#	: %23
@	: @
!	: %21
$	: $
^	: %5E
*	: %2A
(	: %28
)	: %29
```

Assume you have a password as "foo#bar" which should be replaced by "foo%23bar" when you export the proxy or use it as an argument.


```
export http_proxy="http://user:F@oo!B#ar$@myserver:3128/"
```
replaced with
```
export http_proxy="http://user:F%40o%3Ao%21B%23ar%24@myserver:3128/"
```
If you have any other special char in the password then generate the hex code using
https://play.golang.org/p/XCdELVvShKA script (just need to add that char to  list and run in the browser)

Let us know if you still have same issue.

**Comment by PrimerFender** [comment]
@praveenkumar I was able to get through proxy when using the %hex value in my passphrase. I thought that only applied to the URL and wouldn't work for authentication but I confirmed it has. Thanks for the suggestion, I at least have a work around for now.

**Comment by praveenkumar** [comment]
@PrimerFender Good to know it worked for you, we will need to add this to our documentation.

**Comment by anjannath** [comment]
But we can also replace the special chars with their corresponding hex
codes in the password.
it's quite tedious to remember these codes and the user has to look
somewhere to find out the
codes for the characters they are using in their password.

Doing this in the code will be good experience on the user side.. WDYT?

**Comment by praveenkumar** [comment]
> Doing this in the code will be good experience on the user side.. WDYT? 

Yes it is, We need to find out how easy it would be to extract the details around `username` and `password` when provide the URI.

**Comment by praveenkumar** [comment]
@PrimerFender Hey, we did put some code to handle the special char instead user manually map it to hex values.Can you try artifact from https://ci.appveyor.com/project/minishift-bot/minishift/build/2847/artifacts here and let us know if that works for you.

To try out this artifact you don't need to manually put hex representation to special char.

```
- Download the artifact.
$ export http_proxy=http://username:HashTag#Password@proxy.company.com:8080
$ minishift start --show-libmachine-logs -v5
```
If downloaded artifact still fail then please paste the logs.

**Comment by LalatenduMohanty** [comment]
@praveenkumar @PrimerFender  Are we seeing the same issue if we use the `minishift start` flags i.e. `--http-proxy` and `--https-proxy`?

**Comment by LalatenduMohanty** [comment]
> @praveenkumar @PrimerFender Are we seeing the same issue if we use the minishift start flags i.e. --http-proxy and --https-proxy?

Nvm, I think it would be the same issue.

**Comment by PrimerFender** [comment]
@praveenkumar I tested the updated artifact and it worked! Ignore the part about the VM not starting, that's my own fault trying to run nested VM in Hyper-V; the fact that it downloaded OC and continued on is proof to me.

@LalatenduMohanty I had previously tried to use the start flags `--http-proxy` etc. and got the same results as before.

```bash
$ cd ~/minishift-1.16.0-linux-amd64/
$ ll
total 15176
-rw-r--r--. 1 username username    11374 Apr 17 07:58 LICENSE
-rwxrwxr-x. 1 username username 15520192 Apr 17 07:58 minishift
-rw-r--r--. 1 username username     3328 Apr 17 07:58 README.adoc
$ mv minishift minishift.bak
$ cp ~/Downloads/minishift minishift
$ ll
total 30320
-rw-r--r--. 1 username username    11374 Apr 17 07:58 LICENSE
-rw-rw-r--. 1 username username 15503808 Apr 26 15:24 minishift
-rwxrwxr-x. 1 username username 15520192 Apr 17 07:58 minishift.bak
-rw-r--r--. 1 username username     3328 Apr 17 07:58 README.adoc
$ chmod 775 minishift
$ ll
total 30320
-rw-r--r--. 1 username username    11374 Apr 17 07:58 LICENSE
-rwxrwxr-x. 1 username username 15503808 Apr 26 15:24 minishift
-rwxrwxr-x. 1 username username 15520192 Apr 17 07:58 minishift.bak
-rw-r--r--. 1 username username     3328 Apr 17 07:58 README.adoc
$ export http_proxy=http://username:HashTag#Password@proxy.company.com:8080
$ export https_proxy=$http_proxy
$ echo $https_proxy
http://username:HashTag#Password@proxy.company.com:8080
$ minishift start --show-libmachine-logs -v5
-- minishift version: v1.16.1+0b7b4ece
-- Starting profile 'minishift'
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:43096
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Failed to fetch machine
(minishift) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(minishift) DBG | [signal 0xb code=0x1 addr=0x0 pc=0x4d7167]
(minishift) DBG | 
(minishift) DBG | goroutine 25 [running]:
(minishift) DBG | panic(0x8c54a0, 0xc82000a160)
(minishift) DBG | 	/usr/local/go/src/runtime/panic.go:464 +0x3e6
(minishift) DBG | github.com/alexzorin/libvirt-go.(*VirDomain).GetState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/alexzorin/libvirt-go/domain.go:192 +0x87
(minishift) DBG | github.com/dhiltgen/docker-machine-kvm.(*Driver).GetState(0xc82014c0e0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/dhiltgen/docker-machine-kvm/kvm.go:450 +0x70
(minishift) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).GetState(0xc8200ff940, 0xe0d430, 0xc82005f978, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:191 +0x45
(minishift) DBG | reflect.Value.call(0x8858a0, 0x93fe88, 0x13, 0x959cd0, 0x4, 0xc820034ef8, 0x3, 0x3, 0x0, 0x0, ...)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:435 +0x120d
(minishift) DBG | reflect.Value.Call(0x8858a0, 0x93fe88, 0x13, 0xc820034ef8, 0x3, 0x3, 0x0, 0x0, 0x0)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:303 +0xb1
(minishift) DBG | net/rpc.(*service).call(0xc82007f6c0, 0xc820010380, 0xc82005f5f0, 0xc8200c1600, 0xc82000ea00, 0x7e14a0, 0xe0d430, 0x16, 0x89fca0, 0xc82005f978, ...)
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:383 +0x1c2
(minishift) DBG | created by net/rpc.(*Server).ServeCodec
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:477 +0x49d
Error getting machine state: unexpected EOF
-- Checking if https://github.com is reachable (using proxy: "http://username:HashTag#Password@proxy.company.com:8080") ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.9.0'
 2.46 MiB / 42.11 MiB [==>-----------------------------------------]   5.83% 48sWrapper Docker Machine process exiting due to closed plugin server (connection is shut down)
 42.11 MiB / 42.11 MiB [============================================] 100.00% 0s-- Downloading OpenShift v3.9.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM ...Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
.Plugin server listening at address 127.0.0.1:41865
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Failed to fetch machine
(minishift) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(minishift) DBG | [signal 0xb code=0x1 addr=0x0 pc=0x4d7167]
(minishift) DBG | 
(minishift) DBG | goroutine 20 [running]:
(minishift) DBG | panic(0x8c54a0, 0xc82000a160)
(minishift) DBG | 	/usr/local/go/src/runtime/panic.go:464 +0x3e6
(minishift) DBG | github.com/alexzorin/libvirt-go.(*VirDomain).GetState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/alexzorin/libvirt-go/domain.go:192 +0x87
(minishift) DBG | github.com/dhiltgen/docker-machine-kvm.(*Driver).GetState(0xc8200181c0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/dhiltgen/docker-machine-kvm/kvm.go:450 +0x70
(minishift) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).GetState(0xc8200e3d80, 0xe0d430, 0xc8201523b8, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:191 +0x45
(minishift) DBG | reflect.Value.call(0x8858a0, 0x93fe88, 0x13, 0x959cd0, 0x4, 0xc820035ef8, 0x3, 0x3, 0x0, 0x0, ...)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:435 +0x120d
(minishift) DBG | reflect.Value.Call(0x8858a0, 0x93fe88, 0x13, 0xc820035ef8, 0x3, 0x3, 0x0, 0x0, 0x0)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:303 +0xb1
(minishift) DBG | net/rpc.(*service).call(0xc820011c80, 0xc820011a40, 0xc82000b800, 0xc82001b700, 0xc820164400, 0x7e14a0, 0xe0d430, 0x16, 0x89fca0, 0xc8201523b8, ...)
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:383 +0x1c2
(minishift) DBG | created by net/rpc.(*Server).ServeCodec
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:477 +0x49d
 FAIL E0426 15:27:00.554383    3512 start.go:369] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
Error starting the VM: Error getting the state for host: unexpected EOF
```

**Comment by jeka** [comment]
I am sorry for commenting on closed bug but this is completely wrong.
I mean If one decides to use special characters in their username/password he should make sure to  escape them while exporting http[s]_proxy variables. It is not minishift's job to escape them. 
After all these variables are not minishift specific.
