### ISSUE TITLE
Update Docker version in boot2docker ISO

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#230]
Hi,

Currently, the boot2docker image version used to generate [`boot2docker.iso` is `1.12.3`](https://github.com/minishift/minishift/blob/master/deploy/iso/Dockerfile#L17).

However, Docker version is still lower than it i.e [`1.11.2`](https://github.com/minishift/minishift/blob/master/deploy/iso/Dockerfile#L20).

Upstream [boot2docker repo](https://github.com/boot2docker/boot2docker/releases/tag/v1.12.3) also maintain the same version for both.
One definite reason would be "less confusion".

Unless we have any issues with docker version `1.12.3`, we should update it.

Moreover, I found interesting facts today as:
```
#       Boot2docker version 1.12.3 boot2docker.iso 
Boot2Docker version 1.12.3, build HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
Docker version 1.12.3, build 6b644ec

#       Minishift master boot2docker.iso
Boot2Docker version 1.11.2, build HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
Docker version 1.11.2, build b9f10c9
```
Clearly, minishift master boot2docker.iso is showing wrong info of Boot2docker version for `build HEAD 7fc7575`.

**Comment by hferentschik** [comment]
Closing this issue here in favor of issue https://github.com/minishift/minishift-b2d-iso/issues/6.
