### ISSUE TITLE
Make DNS server work on minikube

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2303]
At the moment the configuration is pushed to the VM using `openssl` base64 decode. This was changed from `base64` to support B2d. but now it seems the minikube iso does not support `openssl` from the ISO. either we do a detection and decide which command to use, or add openssl to the image.

See `handleConfiguration` for details in the file `localdns_config.go`

The actual solutions are:

   * add `base64` to B2d
   * deprecate B2d and only rely on `base64`
   * do detection on command to use, either `base64` or `openssl` based on image
   * add `openssl` to Minikube ISO

**Comment by gbraad** [comment]
See https://github.com/minishift/minishift/pull/2076/commits/0c1794aef9eb12435242a44875678d5f9898a9ce for more details

**Comment by gbraad** [comment]
A single command with a test might work, whic tests for either base64 or openssl and sets a variable what to use when decoding.

**Comment by praveenkumar** [comment]
@gbraad Since b2d is what we control so I think we can add base64 command to it, instead going to add more code around detecting what iso is running.

**Comment by anjannath** [comment]
This can be closed now since #2294 merged.
