### ISSUE TITLE
Update documentation about service catalog  in minishift v1.16.0

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2309]
The experimental flags for `--service-catalog`, `--metrics` and `--logging` have been removed from the `m start`-options.

If you deploy a version that still supports these flags, use something like the following:

```
$ export MINISHIFT_ENABLE_EXPERIMENTAL=y
$ minishift start --extra-clusterup-flags "--service-catalog"
```

Note: these flags are unchecked by us and might not deploy or error `oc cluster up` during execution.

We are looking into a solution for future releases, that might map against the proposed `--add` option for `oc cluster up`.

**Comment by LalatenduMohanty** [comment]
For the time being, we need to update our documentation https://docs.openshift.org/latest/minishift/using/experimental-features.html#enabling-experimental-oc-flags 

Also some add-ons in add-ons repo e.g. [1] have documentation about the old way of using the flags which needs to be fixed 

[1] https://github.com/minishift/minishift-addons/tree/master/add-ons/ansible-service-broker

**Comment by gbraad** [comment]
Has an issue been created to follow-up on documenting this?

**Comment by LalatenduMohanty** [comment]
> Has an issue been created to follow-up on documenting this?

We should use this issue as the follow up issue to fix the documentation and create an follow up issue to add service-catalog to minishift post v3.10.0
