### ISSUE TITLE
Documentation uses already referenced anchor IDs

### ISSUE THREAD

**Issue by robin-owen** [minishift/minishift#2313]
The anchor IDs `installing-minishift` and `adding-cifs-hostfolder` are both used twice in the documentation where unique anchor IDs should be used instead. The `installing-minishift` anchor is used in both **_getting-started/preparing-to-install.adoc_** and **_getting-started/installing.adoc_**. Both uses of `adding-cifs-hostfolder` exist in **_using/host-folders.adoc_**.

**Comment by LalatenduMohanty** [comment]
Resolved via #2314
