### ISSUE TITLE
minishift version and completion shouldn't create MINISHIFT_HOME dir

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#2316]
```
$ ls ~/.minishift
ls: cannot access '/home/budhram/.minishift': No such file or directory

$ minishift version
minishift v1.15.1+f7bd44bd

$ ls ~/.minishift
addons  cache  certs  config  logs  machines  tmp
```
See https://issues.jboss.org/browse/CDK-281

**Comment by LalatenduMohanty** [comment]
I agree that `version` command should not create any artifacts i.e. should not leave files in the system.

**Comment by gbraad** [comment]
No side-effects for `m version`
But low priority

**Comment by gbraad** [comment]
![image](https://user-images.githubusercontent.com/1894/38995278-24943230-441b-11e8-8917-305cb4f9f742.png)
![image 1](https://user-images.githubusercontent.com/1894/38995296-2b58ae0c-441b-11e8-900d-65597c403ef4.png)
