### ISSUE TITLE
Fix the output of `$ minishift config view` 

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2321]
### General information

  * Minishift version: 1.16.0
  
The output of `$ minishift config view` is not formatted properly

### Steps to reproduce

  1. $ minishift config set skip-check-clusterup-flags true
  2. $ minishift config view

### Expected

```
$ minishift config view
- iso-url                        : centos
- skip-check-clusterup-flags     : true

```

### Actual

```
$ minishift config view
- iso-url              : centos
- skip-check-clusterup-flags: true

```

**Comment by rhnvrm** [comment]
The command runs `docker-exec cat <path to yaml file>` and displays the output of `cat` to the terminal for the config file. Is there any way we can edit this file?

To convert to the expected format, one solution I can think of would be to write a pretty-print tool that tabs the yaml string and then later performs Println on the formatted string.

**Comment by rhnvrm** [comment]
@anjannath - You are right, I might have got lost earlier when I went through the code. I now have sent a PR with the modification using tabwriter at #2372
