### ISSUE TITLE
Add integration test step to test experimental feature

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2322]
Currently we do not have any steps in integration test to test experimental features e.g. 
```
When executing "MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --extra-clusterup-flags '--service-catalog'" succeeds
```

Also adding below code will work in GNU/Linux but not in Windows powershell. 
```code
s.Step(`^executing "MINISHIFT_ENABLE_EXPERIMENTAL=y minishift (.*)" (succeeds|fails)$`,
        ExecutingMinishiftCommandSucceedsOrFails)
```

*We also need to add a test for service catalog. which could not be added in #2319 because of this issue.*

**Comment by amitkrout** [comment]
Thanks @LalatenduMohanty 
Will take it further and make the integration test run on supported terminals
