### ISSUE TITLE
Update Hyper-V static IP documentation as it is not an experimental feature

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2323]
Currently the docs are in experimental section of the documentation [1] but the feature is not an experimental feature. 
[1] https://docs.openshift.org/latest/minishift/using/experimental-features.html#hyperv-static-ip

**Comment by robin-owen** [comment]
Right, this feels like it belongs in its own dedicated section under **_using/_**, for example **_using/static-ip.adoc_** (or something along those lines). This is particularly true if the feature will be extended to other hypervisors in the future.

**Comment by gbraad** [comment]
I expect several network related topics to be discussed, like IP, DNS and
possibly how to setup port-forwarding. However, this is mostly future...

... although it does show "networking' is more close to the topic we look
for.

**Comment by robin-owen** [comment]
@gbraad Networking makes sense to me, especially with so many related topics.

**Comment by LalatenduMohanty** [comment]
> using/static-ip.adoc

+1 . We can move docs related to `--set-staic` to this too (in future).

**Comment by robin-owen** [comment]
@LalatenduMohanty @gbraad I think we can go ahead and create **_using/networking.adoc_** with a single topic (setting a static IP for Hyper-V) for the moment. I'd like to create this file early so that we don't have URL changes in the future if at all possible.

**Comment by LalatenduMohanty** [comment]
@gbraad @robin-owen I strongly feel that docs related to static IP and (--set-static in future together ) deserves a dedicated page because it is very important from Minishift users point of view similar to add-ons or profiles.

**Comment by LalatenduMohanty** [comment]
Resolved via #2341
