### ISSUE TITLE
Refactor `preflightCheckSucceedsOrFails` to receive an Error from the checking funcs instead of a Boolean

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#2327]
Now our preflight checks `checkOriginRelease`,`checkIsoUrl`, etc.. all return just a Boolean and based on that we decide if the check failed or passed and print FAIL or OK. But we cannot have much information as to why the check failed, in light of #2307, #2311 we need to provide information to the user as to why the check failed.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/2352

**Comment by anjannath** [comment]
This is not addressed yet, we want to return an error instead of bool from the checking funcs, so that it can be handled by `preflightCheckSucceedsOrFails`..
https://github.com/minishift/minishift/blob/a50f3df32d6b22d2e85c54b14e5a26ba192f0b58/cmd/minishift/cmd/start_preflight.go#L227-L230

This is to avoid printing `FAIL` at last after printing the error msg.. currently we pass the error msg as the last argument to `preflightCheckSucceedsOrFails`
https://github.com/minishift/minishift/blob/a50f3df32d6b22d2e85c54b14e5a26ba192f0b58/cmd/minishift/cmd/start_preflight.go#L195-L202

**Comment by LalatenduMohanty** [comment]
@anjannath My mistake , I should have closed #2307

**Comment by kishansagathiya** [comment]
@anjannath I am also facing GitHub rate limit error as described [here](https://github.com/minishift/minishift/pull/2352#issue-184927703). I believe that is being done as part of this issue. Is there any way or hack so that I can use minishift before this issue gets resolved?

@LalatenduMohanty I wonder why this is tagged `priority/minor` considering it clearly blocks a user from using minishift.

**Comment by kishansagathiya** [comment]
@anjannath 
Tried the same thing after some time. Worked this time.

@LalatenduMohanty Now I know why you tagged it `minor` :laughing:

**Comment by anjannath** [comment]
@kishansagathiya Better to use an api token. See: https://docs.openshift.org/latest/minishift/troubleshooting/troubleshooting-getting-started.html#github-api-rate-limit-exceeded
