### ISSUE TITLE
Automount hostfolders during minishift start

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#2328]
Will it helpful for a user to be able to auto mount some hostfolders they have already added, during the minishift start process.

@minishift/minishift-dev Thoughts on this?

**Comment by LalatenduMohanty** [comment]
@anjannath we have an option to auto mount all. 
```
Usage:
  minishift hostfolder mount HOST_FOLDER_NAME [flags]

Flags:
  -a, --all    Mounts all defined host folders into the Minishift VM.
```

Do you want to mount some of the hostfolders selectively?

**Comment by gbraad** [comment]
And this can also be toggled using a config option, but it is not turned on
byt default.

**Comment by gbraad** [comment]
Closing?

On Mon, Apr 23, 2018 at 4:05 PM, Gerard Braad <me@gbraad.nl> wrote:
> And this can also be toggled using a config option, but it is not turned on
> byt default.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by anjannath** [comment]
I was looking for something which can selectively mount.. like set a host-folder to auto mount. but for now we can mount all at start automatically by setting this: `minishift config hostfolders-automount`...

Thanks.. closing.. :-)
