### ISSUE TITLE
Add overlay as default storage driver for minishift provisioners

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#233]
Currently we are using `devicemapper` as default storage driver for our minishift provisioners which should be changed to `overlay` as it is now available to linux kernel by default and have better performance then devicemapper.

Refer: https://github.com/minishift/minishift-centos-iso/issues/73

**Comment by hferentschik** [comment]
> Currently we are using devicemapper as default storage driver for our minishift provisioners which should be changed to overlay 

why? I am not generally opposed to switch to another storage driver, but it needs to be backed up by some proper reasons.

> as it is now available to linux kernel by default 

hmm, devicemapper is a kernel tech as well right?

> and have better performance then devicemapper.

Is this relevant to us? Do have any performance data to back this up? Looking at 

* https://docs.docker.com/engine/userguide/storagedriver/selectadriver/
* https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/
* https://success.docker.com/Policies/Compatibility_Matrix

and in particular the compatibility matrix, devicemapper still seems to be the recommended drvier for CentOS/RHEL.

**Comment by praveenkumar** [comment]
> why? I am not generally opposed to switch to another storage driver, but it needs to be backed up by some proper reasons.

https://batmat.net/2015/08/26/docker-storage-driver-dont-use-devicemapper/ end of this post have lot of reference about not using devicemapper in loopback mode.

> devicemapper still seems to be the recommended driver for CentOS/RHEL.

I agree but we never tell our user to use devicemapper as loopback mode (which we have currently for iso) the way we recommend our users to create a lvm first and then use docker-stroage-setup for which use devicemapper but not as loopback. http://www.projectatomic.io/blog/2015/06/notes-on-fedora-centos-and-docker-storage-drivers/ have a good details around it. 

We are not able to use devicemapper currently as we used for our CDK-2.x/ADB because live image don't support partition for specific use case like https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/build_tools/kickstarts/centos-7-adb-vagrant.ks#L21-L25

**Comment by hferentschik** [comment]
@praveenkumar, thanks, that was the information I was looking for.

Looking at http://www.projectatomic.io/blog/2015/06/notes-on-fedora-centos-and-docker-storage-drivers/, I am wondering about the following:

* "so we have to disable SELinux support within our containers" - does that mean containers with SELinux won't work
* "Additionally, there’s a reported issue (with workaround) involving OverlayFS and use of yum within containers." -  that also sounds quite bad, especially in the light of CDK

> because live image don't support partition for specific use case like https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/build_tools/kickstarts/centos-7-adb-vagrant.ks#L21-L25

Why not? I guess I don't quite understand what's required here. What is "partition for a certain use case" and would the partitioning we need in this case not be handled in _handle-user-data_? What stops us to change this script? Or do we need to change something which is part of the ISO itself and cannot be controlled by _livecd-creator_?

Either way, we need to at least verify that we don't run into issues with the overlay driver. Also we need to look at SELinux. We said it would be nice to enable it, but switching to overaly might put some stones in our way in this regards.

Given that minishift is not a production environment I rather go with the potentially _lesser_ evil and use devicemapper over loopback.

**Comment by praveenkumar** [comment]
@hferentschik yes we need to do verification around it, might be get feedback from @vbatt or @rhatdan if it is good move.

> Why not? I guess I don't quite understand what's required here. What is "partition for a certain use case" and would the partitioning we need in this case not be handled in handle-user-data? 

Yes that is something we should try and create lvm partition for docker-stroage-setup.

**Comment by hferentschik** [comment]
>  Yes that is something we should try and create lvm partition for docker-stroage-setup.

+1 devicemapper + lvm (provisioned and created as part of our boot2docker scripts) seems to me the best option, if we want to have something more production grade like.

**Comment by jimmidyson** [comment]
That's an old blog post. Not sure if it's been backported to rhel/centos kernel but upstream kernels includes overlay support for selinux.

**Comment by jorgemoralespou** [comment]
@hferentschik overlayfs will be the default filesystem for containers really soon. It provides many benefits in term of speed, specially while building and most issues with SElinux should already be resolved. 
If not now, I think you should consider what will take to move to overlayfs soon. If I recall correctly,  RHEL 7.3 will support it and RHEL 7.4 will have it by default.

**Comment by hferentschik** [comment]
@praveenkumar any updates on this?

**Comment by budhrg** [comment]
@hferentschik No milestone for this issue yet.  As RHEL 7.4 has support with few restrictions.

Adding following notes from Release notes of RHEL 7.4

> Full support is available for OverlayFS when used with Docker under the following restrictions:
> - OverlayFS is only supported for use as a Docker graph driver. Its use can only be supported for container COW content, not for persistent storage. Any persistent storage must be placed on non-OverlayFS volumes to be supported. Only default Docker configuration can be used; that is, one level of overlay, one lowerdir, and both lower and upper levels are on the same file system.
> - Only XFS is currently supported for use as a lower layer file system.
> - SELinux must be enabled and in enforcing mode on the physical machine, but must be disabled in the container when performing container separation; that is, /etc/sysconfig/docker must not contain --selinux-enabled. SELinux support for OverlayFS is being worked on upstream, and is expected in a future release.
> - The OverlayFS kernel ABI and userspace behavior are not considered stable, and may see changes in future updates.
> - In order to make the yum and rpm utilities work properly inside the container, the user should be using the yum-plugin-ovl packages.

> Note that OverlayFS provides a restricted set of the POSIX standards. Test your application thoroughly before deploying it with OverlayFS.

Looks like we might need more investigation here.

**Comment by budhrg** [comment]
@praveenkumar @hferentschik Do we still want to keep it open?

**Comment by gbraad** [comment]
Still relevant

**Comment by praveenkumar** [comment]
This is now resolved.
