### ISSUE TITLE
Missing Web Console

### ISSUE THREAD

**Issue by cfchase** [minishift/minishift#2330]
### General information

  * Minishift version: minishift v1.16.1+d9a86c9
  * OS: Fedora 27
  * Hypervisor: KVM 

### Steps to reproduce

  1. Download the latest release
  2. ./minishift start
  3. Access web console at URL from command (for me the address was https://192.168.42.208:8443)

### Expected
OpenShift Web Console is displayed.  Usually this is the behavior of both minishift and `oc cluster up` up until now.   

### Actual
missing service (service "webconsole" not found)
missing route (service "webconsole" not found)

This looks very similar to https://github.com/openshift/origin/issues/18207, but I haven't seen any official docs saying to perform the [web console installation](https://github.com/openshift/origin-web-console-server#installing-the-console) if  you're using minishift.  

Is this intentional behavior?  If so, should it be documented at https://docs.openshift.org/latest/minishift/getting-started/quickstart.html?

**Comment by budhrg** [comment]
@cfchase , Could you start with clean installation: 
```
minishift delete --clear-cache
minishift start --show-libmachine-logs -v 5
```

This is really a weird issue. We haven't reproduced it in our dev (F27) machines.

**Comment by cfchase** [comment]
That fixed it.

Perhaps I was running into issues because I had done a `minishift update` from 1.15, but it seems to be working now.

Thanks for the help and sorry if it was a false alarm.
