### ISSUE TITLE
The --help flag should provide examples as part of the output

### ISSUE THREAD

**Issue by benjaminapetersen** [minishift/minishift#2332]
### General information

  * Minishift version: minishift v1.16.0+8abe845
  * OS: macOS (N/A)
  * Hypervisor: xhyve (N/A)

### Steps to reproduce

  1. minishift <any> --help

### Expected

Similar to `oc`, for example ` oc edit --help`,  output would include an `Examples:` heading:

```bash 
$ oc edit --help
Edit a resource from the default editor

The edit command allows you....

Usage:
    oc edit (RESOURCE/NAME | -f FILENAME) [flags]

Examples: 
   # Edit the service named 'docker-registry':
   oc edit svc/docker-registry
   # a more detailed example...
   # an even more detailed example...
Options:
   # etc
   # etc
```

### Actual

The `--help` flag provides a good bit of output, but it is not quite detailed enough to be completely clear.  For example, I'm looking at `minishift start --help` for a way to `oc cluster up --tag=<tag> --enable=service-catalog,template-service-broker,router,registry,web-console`, but cannot easily tell how to provide these flags from the output alone.  Reading, I'm going to take a stab at providing  `-e` or `--openshift-env`, but an examples block for use cases like this would be extremely helpful.

Thanks!

**Comment by benjaminapetersen** [comment]
Further clarification:

```
--openshift-env stringSlice        Specify key-value pairs of environment variables to set on the OpenShift container.
```
`stringSlice` is obvious it will split the string, but its not obvious what structure this would take.  For example, if passing `--openshift-env --service-catalog` or `--openshift-env --service-catalog=true` or `--openshift-env service-catalog`, or if you have multiple `service-catalog, template-service-broker` with dashes, commas, etc.

**Comment by gbraad** [comment]
@robin-owen maybe you also have an idea about this?

Note: I think we are also limited here to what the framework we use allows us to do... we already have the issue with the log flags being included, but also the object types like stringslice, etc.

**Comment by benjaminapetersen** [comment]
`stringSlice` sounds like `go` (but I'm not a `go` programmer).  Thats where it doesn't help me a ton, I'd typically be looking for something more consumable.

Thanks!

**Comment by benjaminapetersen** [comment]
Bump to avoid stale.
