### ISSUE TITLE
`make gen_docs` runs multiple times with unclean working directory

### ISSUE THREAD

**Issue by robin-owen** [minishift/minishift#2342]
I'm currently experiencing an issue with `make gen_docs` which I suspect is related to the changes made in #2282 to resolve #2281. Running `make gen_docs` with an unclean working directory (meaning `make clean` has not been run) results in `make gen_docs` repeating the same task for each Markdown file in **docs/source/_tmp**. If `make clean` is run prior to `make gen_docs`, the documentation builds as expected.

**Steps to reproduce:**

```sh
$ make clean
$ make gen_docs # This works.
$ make gen_docs # <-- This is where the issue occurs.
```

Running `make -d gen_docs` with a dirty working directory has interesting results, namely the following:

```
Considering target file 'gen_docs'.
 File 'gen_docs' does not exist.
  Considering target file 'synopsis_docs'.
   File 'synopsis_docs' does not exist.
    Considering target file 'docs/source/_tmp/minishift_version.md'.
      Considering target file 'vendor'.
       Finished prerequisites of target file 'vendor'.
      No need to remake target 'vendor'.
      Considering target file 'assets'.
       File 'assets' does not exist.
        Considering target file '/home/robin/src/go/bin/go-bindata'.
         Finished prerequisites of target file '/home/robin/src/go/bin/go-bindata'.
        No need to remake target '/home/robin/src/go/bin/go-bindata'.
       Finished prerequisites of target file 'assets'.
      Must remake target 'assets'.
```

A short while after this, the following appears in the output:

```
      Successfully remade target file 'assets'.
     Finished prerequisites of target file 'docs/source/_tmp/minishift_version.md'.
     Prerequisite 'vendor' is older than target 'docs/source/_tmp/minishift_version.md'.
     Prerequisite 'assets' of target 'docs/source/_tmp/minishift_version.md' does not exist.
    Must remake target 'docs/source/_tmp/minishift_version.md'.
```

This process seems to repeat for _each_ Markdown file in **docs/source/_tmp**, which includes the Minishift command reference files. This causes the task to run multiple times, each time spinning up a new `docker` process and consuming a lot of the available resources on my machine.

I'm not certain what is causing this, in particular, but the 'assets' target is a common occurrence in the output of `make -d gen_docs`.

**Comment by gbraad** [comment]
@anjannath any idea what coudl cause this?

**Comment by robin-owen** [comment]
Note for the future: this can be worked around by running `make clean gen_docs` instead of `make gen_docs`.

**Comment by LalatenduMohanty** [comment]
The issue is coming because `make` and make assets` running for each files in `minishift/docs/source/_tmp` i.e. `DOCS_SYNOPISIS_DIR`. 

```
$(DOCS_SYNOPISIS_DIR)/*.md: vendor assets
	@# https://github.com/golang/go/issues/15038#issuecomment-207631885 ( CGO_ENABLED=0 )
	DOCS_SYNOPISIS_DIR=$(DOCS_SYNOPISIS_DIR) CGO_ENABLED=0 go run -tags "$(BUILD_TAGS) gendocs" -ldflags="$(LDFLAGS)" gen_help_text.go

.PHONY: synopsis_docs
synopsis_docs: $(DOCS_SYNOPISIS_DIR)/*.md ## Builds the Markdown command synopsis
```

The reason we do not see the issue after `make clean` because `make clean` removes the files from `DOCS_SYNOPISIS_DIR) ` i.e . `rm -f  $(DOCS_SYNOPISIS_DIR)/*.md`

**Comment by LalatenduMohanty** [comment]
So this also creates issue when `make gen_docs` and `make serve_docs` are run one after another.
