### ISSUE TITLE
Need to be consistent with package name for pkg/minishift/config

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#2345]
Currently, we have two forms

- `minishiftConfig` - https://github.com/minishift/minishift/search?utf8=%E2%9C%93&q=minishiftConfig&type=

and

- `miniConfig` - https://github.com/minishift/minishift/search?utf8=%E2%9C%93&q=miniConfig&type=

**Comment by gbraad** [comment]
`miniConfig` as alias was introduced in the latest implementation of the hostfolders. But I am wondering what changing the alias to be consistent will bring us as value, as in general it should be able to use it without any alias (and in that case it is known as config).
