### ISSUE TITLE
Application deployment failing on Windows ISO with minishift v1.16.1+d9a86c9

### ISSUE THREAD

**Issue by vlaskovic** [minishift/minishift#2349]
### General information

  * Minishift version: minishift v1.16.1+d9a86c9
  * OS: Windows
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. mvn fabric8:deploy
  2. build failure logs as: point 1. from logs below
  3. console logs as: point 2. from logs below

### Expected
Build Success; application Status: running

### Actual
Build Failure: application Status: failed

### Logs
1. 
Receiving source from STDIN as archive ...
tar: /tmp: Cannot open: Permission denied
tar: Error is not recoverable: exiting now
ERROR: Error copying file "/tmp/upload/src/maven/xxx.jar" to tar: io: read/write on closed pipe
ERROR: Error writing tar: io: read/write on closed pipe
error: build error: write unix @->/var/run/docker.sock: write: broken pipe

2.
[ERROR] Caught exception in FS.readPipe()
java.io.IOException: Cannot run program "git" (in directory "\usr\bin"): CreateProcess error=2, The system cannot find the file specified

Thank you,
Slobodanka

**Comment by gbraad** [comment]
I am sorry, but we do not directly support issues resulting from fabric8. Please report these to their own issue tracker.
