### ISSUE TITLE
Some steps in addon-registry-route.feature doesn't work in windows terminal 

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2355]
### General information

  * Minishift version: minishift v1.16.1
  * OS: Windows
  * Hypervisor: Hyper-V / VirtualBox

### Steps to reproduce

  1. Download minishift v1.16.1 and open windows terminal like powershell or cmd prompt 
  2. Use minishift v1.16.1 binary to run addon-registry-route.feature file. 
```
make integration MINISHIFT_BINARY=$(BINARY_PATH)/minishift.exe GODOG_OPTS="-tags addon-registry-route"
```
  3. 
  4. 

### Expected
Should pass

### Actual
Fails in retrieving the container state [step](https://github.com/minishift/minishift/blob/master/test/integration/features/addon-registry-route.feature#L27) and also it will fail in docker login [step](https://github.com/minishift/minishift/blob/master/test/integration/features/addon-registry-route.feature#L29) as back tick is not supported in windows terminal. Issue #2243  

```
--- Failed steps:

  Scenario: As a user, I can login to OpenShift integrated docker registry # features\addon-registry-route.feature:21
    Then with up to "20" retries with wait period of "3" seconds container image "origin-docker-registry" should be "running" # features\addon-registry-route.feature:27
      Error: Container state did not match. Expected: running, Actual: .State.Status
```

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by agajdosi** [comment]
Seems that step `Then with up to "20" retries with wait period of "3" seconds container name "registry_docker-registry" should be "running"` no longer fails on Windows (tried in PS and cmd), from the integration tests log:
```
16:23:23.901238  stdout: CONTAINER ID        IMAGE                                                                                                                               COMMAND                  CREATED             STATUS              PORTS               NAMES
                         e4b60c490e45        registry.access.redhat.com/openshift3/ose-docker-registry@sha256:7e2b677ed2a402ac63cba7b86df195f5ab8ccbe275720cd7d51133dc710c8a2b   "/bin/sh -c '/usr/..."   4 seconds ago       Up 3 seconds                            k8s_registry_docker-registry-1-8zntq_default_2ba9cecf-cae8-11e8-920f-0800277e96cd_0
16:23:23.901238 command: C:/Users/CDKQE/cdk/minishift.exe ssh -- docker inspect -f '{{.State.Status}}' e4b60c490e45
16:23:24.884863  stdout: running
```
what I however see to fail is the step:
```
And with up to "60" retries with wait period of "1" second command "curl -ik https://docker-registry-default.$(minishift ip).nip.io" output should contain "200 OK"
```
And that is because the step implements execution of commands in shell and on some windows machines `curl` is not present. We should however not introduce using external commands, so the fix here will be to use scenario variables and https://github.com/minishift/minishift/blob/master/test/integration/testsuite/testsuite.go#L210-L211.

**Comment by agajdosi** [comment]
@LalatenduMohanty using the curl to get info if docker-registry is running resolved. I am now porting scenario variables support from normal commands to also support commands in shell so we `docker login` scenario will be platform/shell independent.
