### ISSUE TITLE
Disallow permission check to run when user is either root or administrator

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2362]
https://github.com/minishift/minishift/blob/7469ee34f5ee353e41df7ac7a5645b4ae0071af8/pkg/util/utils_test.go#L220-L222

Current test is skipped when platform is Windows, which seems too crude, as it should be based on the fact the user having administrartive rights; `uid==1 || username == "root" || username == "administrator"`.

**Comment by gbraad** [comment]
AppVeyor's documentation https://www.appveyor.com/docs/environment-variables/ does not work as expected `APPVEYOR` is not available, and specifying in `appveyor.yml` does not help either. Checking for username contains "appveyor" works.

**Comment by praveenkumar** [comment]
resolved.
