### ISSUE TITLE
wrong output for `which` command

### ISSUE THREAD

**Issue by surajnarwade** [minishift/minishift#2367]
Ideally which command shows full path of given command/binary, but I can see random minishift command 
instead of path
```
[snarwade@localhost ~]$ minishift version
minishift v1.16.1+d9a86c9
[snarwade@localhost ~]$ which minishift 
 minishift start --openshift-version=v3.7.1 --service-catalog'
```

**Comment by praveenkumar** [comment]
@surajnarwade Not sure if there is a different alias of which in your system for me below looks as expected. Can you check with any other command?

```
$ which minishift
/Users/prkumar/work/github/go_practice/bin/minishift
```

**Comment by anjannath** [comment]
@surajnarwade Even for me in Linux it shows correct path, here's the o/p..
```
[minishift]$ which minishift
~/work/bin/minishift
```

**Comment by surajnarwade** [comment]
sorry my fault, my bashrc had that string. Closing this issue

**Comment by surajnarwade** [comment]
Thanks @praveenkumar @anjannath

**Comment by gbraad** [comment]
`which` is always a local result, so it could never have been Minishift specific.

marking as invalid.
