### ISSUE TITLE
Deprecate use of gorillalabs/go-powershell

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2370]
When writing the pre-flight checks, a simple powershell library was needed to get this working quickly. But when times moves on we might have to reconsider using this. I have filed several issues for the gorillalabs/go-powershell library, but so far no response from the maintainers:
  * https://github.com/gorillalabs/go-powershell/issues/3
  * https://github.com/gorillalabs/go-powershell/issues/10

Also, when I added this library, it had to pull in juju/errors which is not ideal. Someone filed a PR to modify this to use a simple error wrap:
  * https://github.com/gorillalabs/go-powershell/pull/7

and also this PR has been unanswered for almost a month.

In light of this, it might be wise to move to using the docker/machine implementation. This would have to be extracted and publicly exposed. This would be an easy task from our end, as powershell has been abstracted anyway behind a

**Comment by gbraad** [comment]
This will be resolved with #2429

**Comment by gbraad** [comment]
Closing for this reason

**Comment by LalatenduMohanty** [comment]
Re-opening the issue as https://github.com/minishift/minishift/pull/2437 actually just fixes this. Will close after https://github.com/minishift/minishift/pull/2437 is merged.

**Comment by gbraad** [comment]
@LalatenduMohanty I'll modify #2437 to use this issue instead, and recreate an issue with docker/machine to track the remaining work (we already have one for machine-drivers/machine?).
