### ISSUE TITLE
Stop using oc binary from the host to provision openshift in VM

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2377]
Yesterday, we had a discussion with @mfojtik and @deads2k around future of `of cluster up` and looks like it has been very hard for them to maintain the remote docker daemon deployment. They are planning to support it till 3.10.x but surely get it removed by 3.11.x which will give us at least some time to rethink our strategy around how to do it.

I am planning to keep this issue updated with some of the experiment I will perform and get proper feedback before it lands it to our master branch without breaking our ecosystem around add-ons.

**Comment by LalatenduMohanty** [comment]
Also, they mentioned that keeping the code for remote docker daemon setup will make things fragile and it will make things very difficult for OpenShift features like logging and metrics almost impossible to work with `oc cluster up`.

**Comment by mfojtik** [comment]
The main problems for OpenShift are:

1) Synchronizing the files between local machine (where the oc cluster up runs) to remote machine (where the Docker/kubelet runs) is **very** fragile
2) Although we fixed the components we have now, future components (3.11.x++) will likely suffer from having to copy all artifacts they produce into remote VM
3) Static pods the cluster up now use to deploy the cluster rely on hostPath which have to be present in the VM (so we need to have nasty code that will copy the files...)
3) It is very hard to test the code

So moving to run the cluster up inside the VM where it can talk to Docker using the UNIX socket and having the files locally will greatly improve the minishift experience and make it long term sustainable.

**Comment by anjannath** [comment]
resolved via #2386
