### ISSUE TITLE
Issue template to guide users to quickly file issue/feature request

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#238]
Hi,
 
Issue template will help users to have the guidelines in place to file issue or feature request with proper details about the issue like affecting OS / version / how to repro / what is expected etc.

We can follow similar to [minikube way](https://github.com/kubernetes/minikube/issues/new).

**Comment by LalatenduMohanty** [comment]
@budhrg I think a template of guideline  is good way of getting all required information from the user. However I would suggest/ love to have a template which is very short in length, so that it should take few seconds to read.

**Comment by budhrg** [comment]
@LalatenduMohanty Removed unnecessary lines and updated PR.

**Comment by budhrg** [comment]
Looks like we didn't get the consensus on adding it ([PR closed](https://github.com/minishift/minishift/issues/239)). Hence, closing it.
