### ISSUE TITLE
Minishift fails with "cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string"

### ISSUE THREAD

**Issue by gnodet** [minishift/minishift#2380]
### General information

  * Minishift version: v1.17.0+f974f0c
  * OS: macOS
  * Hypervisor: xhyve

### Steps to reproduce

  1. Start minishift

### Expected

The cluster starts

### Actual

```
gnodet•~» minishift start --show-libmachine-logs -v5
-- minishift version: v1.17.0+f974f0c
-- Starting profile 'minishift'
Found binary path at /usr/local/bin/docker-machine-driver-xhyve
Launching plugin server for driver xhyve
() DBG | operation not supported by device
Plugin server listening at address 127.0.0.1:51413
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string
```

**Comment by gnodet** [comment]
It looks like https://github.com/kubernetes/minikube/issues/1942 which can be solved by running the following command to make sure the released versions of `docker-machine-driver-xhyve` is installed:
```
brew uninstall docker-machine-driver-xhyve && brew install docker-machine-driver-xhyve
```

**Comment by geerlingguy** [comment]
Newer issue in the queue for 0.4.0: https://github.com/minishift/minishift/issues/3279
