### ISSUE TITLE
Could not convert the UUID to MAC address: exit status 1

### ISSUE THREAD

**Issue by andreaneri** [minishift/minishift#2385]
### General information

  * Minishift version: v1.17.0+f974f0c
  * OS: macOS, 10.13.4
  * Hypervisor: xhyve

### Steps to reproduce

  1. rm -rf /Users/<user>/.minishift/
  2. minishift start
  3. 
  4. 

### Actual
```
-- Starting Minishift VM ....... FAIL E0514 14:45:22.353228   21629 start.go:376] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: Could not convert the UUID to MAC address: exit status 1. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: Could not convert the UUID to MAC address: exit status 1
```

**Comment by praveenkumar** [comment]
@andreaneri can you check https://github.com/machine-drivers/docker-machine-driver-xhyve/issues/156 make sure you installed latest version of xhyve driver from brew.

**Comment by andreaneri** [comment]
@praveenkumar i done:
brew update
brew install --HEAD xhyve
but i got the same error

**Comment by andreaneri** [comment]
what does indicate the label 'status/needs-info' ?

**Comment by praveenkumar** [comment]
@andreaneri It means we need information from the reporter if he/she tried provided steps and able to resolve the issue or issue still persist.

**Comment by gbraad** [comment]
Still need info for the steps and actions that were performed before the
report. Did a VM exist before removing the MINISHIFT_HOME? The current
issue report is not complete to reproduce this issue.

**Comment by praveenkumar** [comment]
@andreaneri https://github.com/machine-drivers/docker-machine-driver-xhyve/issues/156 have lot of different way to resolve this issue, I am hoping one of thing works for you also. Did you go through that issue and tried what different folks posted?

**Comment by andreaneri** [comment]
@praveenkumar maybe the problem is:
sysctl kern.hv_support
kern.hv_support: 0
:-(

**Comment by praveenkumar** [comment]
@andreaneri yes that mean your system doesn't support virtualization :( for my mac it's shows `kern.hv_suppport:1 ` Can you close this issue?

**Comment by praveenkumar** [comment]
@andreaneri If you still want to try out minishift then I think you need to install virtualbox and during the start provide `minishift start --vm-driver virtualbox`

**Comment by gbraad** [comment]
What is the model of the machine you tried this on?

**Comment by andreaneri** [comment]
@praveenkumar with virtualbox works fine, thanks

**Comment by andreaneri** [comment]
@gbraad the model is MacBookAir3,2
