### ISSUE TITLE
Always b2d iso is picked up if passing other isourl trough RUN_BEFORE_FEATURE parameter

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2388]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. clone minishift master
```
git clone https://github.com/minishift/minishift
```
  2. Run integration test for flags.feature with RUN_BEFORE_FEATURE="--iso-url .../minishift-centos7.iso"
```
make integration RUN_BEFORE_FEATURE="config set iso-url https://github.com/minishift/minishift-centos-iso/releases/download/v1.9.0/minishift-centos7.iso" GODOG_OPTS="-tags flags"
[...]
--- Failed steps:

  Scenario: User is able to get value of the docker environment variables # features/flags.feature:35
    When printing Docker daemon configuration to stdout # features/flags.feature:37
      Error: Command 'ssh -- cat /var/lib/boot2docker/profile' did not execute successfully. cmdExit: 1, cmdErr: cat: /var/lib/boot2docker/profile: No such file or directory
Command failed: exit status 1
 
 Scenario: User is able to get the value of docker optional parameters # features/flags.feature:41
    When printing Docker daemon configuration to stdout # features/flags.feature:43
      Error: Command 'ssh -- cat /var/lib/boot2docker/profile' did not execute successfully. cmdExit: 1, cmdErr: cat: /var/lib/boot2docker/profile: No such file or directory
Command failed: exit status 1
[...]
```
  3. 
  4. 

### Expected
Should check applied docker config in centos iso. For example ```/etc/systemd/system/docker.service.d/10-machine.conf```

### Actual
Checking docker config in b2d path 

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by agajdosi** [comment]
@amitkrout To test with different ISO you can use environmental variables, which are handled by ISO resolution function (https://github.com/minishift/minishift/blob/master/test/integration/testsuite/prepare.go#L69). The implementation for RUN_BEFORE_FEATURE is not needed IMHO as setting anything in config will break some steps which tests `minishift config`.

Easiest and tidiest way here is to stick to the env var. WDYT?

**Comment by amitkrout** [comment]
@agajdosi i have the same kind of feeling before creating the issue, then thought let's get some feedback from @minishift/minishift-dev on this to increase some flexibility around ```RUN_BEFORE_FEATURE```. I think you are right otherwise it will only increase the unnecessary complexity. LGTM with the environment variable option. 

So closing the issue. Will reopen if I get any hard requirement around it.
