### ISSUE TITLE
mini-che is failing on start of minishift

### ISSUE THREAD

**Issue by jarcher** [minishift/minishift#2391]
### General information

  * Minishift version: minishift v1.17.0+f974f0c
  * OS: macOS 
  * Hypervisor: VirtualBox

### Steps to reproduce

jraMBP@Johns-MacBook-Pro-5:~/_demo|⇒  minishift start --memory 8192
-- Starting profile 'minishift'
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    8 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ......................... OK
-- Registering machine using subscription-manager
   Red Hat Developers or Red Hat Subscription Management (RHSM) username: joarcher@redhat.com
   Red Hat Developers or Red Hat Subscription Management (RHSM) password: [HIDDEN]
   Registration in progress .......... OK [20s]
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
   Importing 'openshift/origin:v3.9.0' ............ OK
   Importing 'openshift/origin-docker-registry:v3.9.0' .. OK
   Importing 'openshift/origin-haproxy-router:v3.9.0' ... OK
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
Using nsenter mounter for OpenShift volumes
Using 192.168.99.100 as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.100:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

-- Waiting for persistent volumes to be created ... OK

-- Applying addon 'xpaas':.....................................................................................
XPaaS OpenShift imagestream and templates installed
See https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples/v3.7
-- Applying addon 'admin-user':..
-- Applying addon 'anyuid':.
 Add-on 'anyuid' changed the default security context constraints to allow pods to run as any user.
 Per default OpenShift runs containers using an arbitrarily assigned user ID.
 Refer to https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html#security-context-constraints and
 https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-origin-specific-guidelines for more information.
-- Applying addon 'che':
[CHE] Create Image Stream.
[CHE] Create the Che server Template.
[CHE] Creating mini-che project as developer..
[CHE] Deploying Che on minishift.
Please wait while the pods all startup!
You can watch in the OpenShift console via:
  minishift console
Then you should be able the open the Che dashboard here:
  http://che-mini-che.192.168.99.100.nip.io

then go to openshift console and access che

See crashed pod
![image](https://user-images.githubusercontent.com/190277/40192440-04796c3a-59ca-11e8-96bc-e42baaa12053.png)

### Expected

Working miniChe

### Actual

Non working miniChe

### Logs

Using embedded assembly...
ERROR: user root does OK have write permissions to /conf
Using embedded che.properties... Copying template to /conf/che.properties
cp: cannot stat ‘/home/user/eclipse-che//lib/*’: No such file or directory

![image](https://user-images.githubusercontent.com/190277/40192371-c0257c22-59c9-11e8-8ebe-472be9233112.png)

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by vap0rtranz** [comment]
@jarcher I've not seen this but am on KVM based CDK v 3.9.14.  Fresh start below.

Have you tried latest nightly Che image?  Since you aren't on latest OCP version tag.

`minishift addons apply     --addon-env CHE_DOCKER_IMAGE=eclipse/che-server:nightly     --addon-env OPENSHIFT_TOKEN=$(oc whoami -t)     che`

```
[jupittma@jupittma openshift]$ minishift start
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.9.14' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.14' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ..................... OK
-- Registering machine using subscription-manager
   Red Hat Developers or Red Hat Subscription Management (RHSM) username: [HIDDEN]
   Red Hat Developers or Red Hat Subscription Management (RHSM) password: [HIDDEN]
   Registration in progress .......... OK [20s]
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
   Importing 'registry.access.redhat.com/openshift3/ose:v3.9.14' . CACHE MISS
   Importing 'registry.access.redhat.com/openshift3/ose-docker-registry:v3.9.14'  CACHE MISS
   Importing 'registry.access.redhat.com/openshift3/ose-haproxy-router:v3.9.14'  CACHE MISS
-- OpenShift cluster will be configured with ...
   Version: v3.9.14
Pulling image registry.access.redhat.com/openshift3/ose:v3.9.14
Pulled 1/4 layers, 26% complete
Pulled 2/4 layers, 74% complete
Pulled 3/4 layers, 91% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
Using nsenter mounter for OpenShift volumes
Using 192.168.42.155 as the server IP
Starting OpenShift using registry.access.redhat.com/openshift3/ose:v3.9.14 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.155:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

-- Waiting for persistent volumes to be created ... OK

-- Applying addon 'xpaas':....................................................................................................
XPaaS OpenShift imagestream and templates installed
See https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples/v3.7
-- Applying addon 'admin-user':..
-- Applying addon 'anyuid':.
 Add-on 'anyuid' changed the default security context constraints to allow pods to run as any user.
 Per default OpenShift runs containers using an arbitrarily assigned user ID.
 Refer to https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html#security-context-constraints and
 https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-origin-specific-guidelines for more information.
-- Exporting of OpenShift images is occuring in background process with pid 8748.
[jupittma@jupittma openshift]$ oc login https://192.168.42.155:8443
Authentication required for https://192.168.42.155:8443 (openshift)
Username: admin
Password: 
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-public
    kube-system
  * myproject
    openshift
    openshift-infra
    openshift-node
    openshift-web-console

Using project "myproject".

[jupittma@jupittma openshift]$ minishift addons enable che
Add-on 'che' enabled
[jupittma@jupittma openshift]$ minishift addons apply \
>     --addon-env CHE_DOCKER_IMAGE=eclipse/che-server:nightly \
>     --addon-env OPENSHIFT_TOKEN=$(oc whoami -t) \
>     che
-- Applying addon 'che':
[CHE] Create the Che server Template.
[CHE] Creating mini-che project as developer..
[CHE] Deploying Che on minishift.
Please wait while the pods all startup!
You can watch in the OpenShift console via:
  minishift console
Then you should be able the open the Che dashboard here:
  http://che-mini-che.192.168.42.155.nip.io
```

**Comment by eivantsov** [comment]
@jarcher you must got a bad PV on MiniShit. Eclipse Che uses one PVC that is bound to a PV. And in your case this PV had a bad permissions (probably writable to an arbitrary user that originally owned it).

I'd do the following:

1. oc login -u system:admin
2. oc get pv
3. Find a PV bound to to che-data claim
4. Remove it
5. Delete mini che namespace
6. Redeploy

Hope it helps

**Comment by eivantsov** [comment]
@l0rd this is Che 5 by the way. How come it is available in the addon?

**Comment by eivantsov** [comment]
@LalatenduMohanty thanks for the pointer. It's weird that I see Che 5 logs while `che-server:latest` image used by default should point to the latets nightly Che 6 https://github.com/minishift/minishift-addons/blob/master/add-ons/che/che.addon#L5

**Comment by l0rd** [comment]
The version of the add-on used is outdated (it's still using this [imagestream](https://github.com/minishift/minishift-addons/blob/0d8299b16ead240edc14d8f2b7f5f7dc885ab0c6/add-ons/che/streams/che-server-streams.json#L47) that points to `eclipse/che-server:5.19.0-centos`)

**Comment by eivantsov** [comment]
@l0rd thanks. It explains it now.

**Comment by praveenkumar** [comment]
Closing this issue since the addon version which is used was outdated.
