### ISSUE TITLE
ImagePolicy plugin for local image lookup is not configured properly.

### ISSUE THREAD

**Issue by GrahamDumpleton** [minishift/minishift#2392]
### General information

  * Minishift version: 

```
OpenShift Master:
v3.9.0+46ff3a0-18
Kubernetes Master:
v1.9.1+a0ce1bc657
OpenShift Web Console:
v3.9.0+b600d46-dirty
```

  * OS: Linux / macOS / Windows

macOS

  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

xhyve

### Steps to reproduce

Create a deployment which doesn't use ``ImageStreamTag`` via an ``ImageChange`` trigger and instead relies on annotation:

```
alpha.image.policy.openshift.io/resolve-names: '*'
```

or uses ``lookupPolicy.local`` of ``true`` in ``ImageStream`` to have ``image`` field of ``containers`` in a pod template be updated.

  1. 

Run:

```
oc import-image jupyter/minimal-notebook:latest --confirm
```

No ``lookupPolicy`` set in this case.

  2. 

Run:

```
oc create -f https://raw.githubusercontent.com/jupyter/docker-stacks/master/examples/openshift/templates.json
```

This template uses the annotation:

```
alpha.image.policy.openshift.io/resolve-names: '*'
```

to have ``image`` name mapped to local ``ImageStream`` in project.

  3. 

Run:

```
oc new-app --template jupyter-notebook --param NOTEBOOK_IMAGE=minimal-notebook:latest
```

### Expected

Application should be deployed.

### Actual

Application isn't deployed and fails due to:

```
10m         12m          4         notebook-1-8hx82.152fa0636f1e6c27    Pod                     spec.containers{jupyter-notebook}   Warning   Failed                        kubelet, localhost            Failed to pull image "minimal-notebook:latest": rpc error: code = Unknown desc = Error: image library/minimal-notebook:latest not found
```

This is because the annotation wasn't honoured and assumed that should try and pull from Docker Hub as ``library/minimal-notebook:latest``.

This is because Minishift is missing a required global configuration to enable the ``ImagePolicy`` plugin. It got left out of OpenShift Online for a while as well until it was fixed. Issue for that was:

* https://bugzilla.redhat.com/show_bug.cgi?id=1506074

See comments in that issue about need to provide a config for ``ImagePolicy`` plugin.

* https://docs.openshift.org/latest/admin_guide/image_policy.html#image-policy-configuring-the-image-policy-admission-plug-in

If you don't have a config it will not be enabled as expected. If you have carried through a config from early OpenShift versions it will be missing, where as a new OpenShift deployment would have it.

### Logs

N/A

**Comment by GrahamDumpleton** [comment]
More specifically, is missing, ``resolutionRules`` entries in ``imagePolicyConfig`` section of ``master-config-yaml``.

```
        resolutionRules: 
        - targetResource:
            resource: pods
          localNames: true
        - targetResource: 
            group: batch
            resource: jobs
          localNames: true 
```

**Comment by GrahamDumpleton** [comment]
Attempting to update master config manually failed.

```
$ minishift openshift config set --patch '{"admissionConfig": {"pluginConfig": {"openshift.io/ImagePolicy": {"configuration": {"resolutionRules": [{"localNames": true, "targetResource": {"resource": "pods"}}, {"localNames": true, "targetResource": {"resource": "jobs", "group": "batch"}}], "kind": "ImagePolicyConfig", "executionRules": [{"skipOnResolutionFailure": true, "onResources": [{"resource": "pods"}, {"resource": "builds"}], "matchImageAnnotations": [{"value": "true", "key": "images.openshift.io/deny-execution"}], "name": "execution-denied", "reject": true}, {"onResources": [{"resource": "pods"}, {"resource": "builds"}], "matchIntegratedRegistry": true, "name": "allow-images-from-internal-registry"}, {"onResources": [{"resource": "pods"}, {"resource": "builds"}], "name": "allow-images-from-dockerhub", "matchRegistries": ["docker.io"]}], "apiVersion": "v1", "resolveImages": "AttemptRewrite"}}}}}'
Patching OpenShift configuration '/var/lib/origin/openshift.local.config/master/master-config.yaml' with '{"admissionConfig": {"pluginConfig": {"openshift.io/ImagePolicy": {"configuration": {"resolutionRules": [{"localNames": true, "targetResource": {"resource": "pods"}}, {"localNames": true, "targetResource": {"resource": "jobs", "group": "batch"}}], "kind": "ImagePolicyConfig", "executionRules": [{"skipOnResolutionFailure": true, "onResources": [{"resource": "pods"}, {"resource": "builds"}], "matchImageAnnotations": [{"value": "true", "key": "images.openshift.io/deny-execution"}], "name": "execution-denied", "reject": true}, {"onResources": [{"resource": "pods"}, {"resource": "builds"}], "matchIntegratedRegistry": true, "name": "allow-images-from-internal-registry"}, {"onResources": [{"resource": "pods"}, {"resource": "builds"}], "name": "allow-images-from-dockerhub", "matchRegistries": ["docker.io"]}], "apiVersion": "v1", "resolveImages": "AttemptRewrite"}}}}}'
Unable to restart OpenShift after patchting it. Rolling back.
```

No obvious explanation as to why it fails.

Also note the spelling error in the error message.

```
Unable to restart OpenShift after patchting it. Rolling back.
```

**Comment by GrahamDumpleton** [comment]
The missing attribute from docs is:

```
"policy":"AttemptRewrite"
```

Just adding that to example from docs doesn't result in a working config though and the deployment gets blocked for other reasons now related to the rules. :-(

**Comment by praveenkumar** [comment]
@GrahamDumpleton Thanks for observation the issue looks like same is https://github.com/minishift/minishift/issues/2379 and we can close it any one of those, problem is this is not coming from cluster up and there is already a origin issue for same :(

**Comment by praveenkumar** [comment]
> Also note the spelling error in the error message.

@GrahamDumpleton That's we can address in one of the PR soon.

**Comment by GrahamDumpleton** [comment]
But what is a working ``minishift openshift config set`` command to correct the problem. The other issues merely states "You should be able modify the config and restart cluster up reusing the existing config.", but if you use the example config from prior version in that issue it will not apply. Is there a workaround documented somewhere that works.

**Comment by GrahamDumpleton** [comment]
Okay, sorted out a config that will apply now. It was conflicting on existing ``GenericAdmissionWebhook`` entry.

**Comment by GrahamDumpleton** [comment]
Getting it to apply doesn't mean it is working. I still don't have a successful deployment, but then it could be due to slow local internet and image not being pulled down quick enough before it gets failed. If I can verify it works I will add command needed to correct the config.

**Comment by GrahamDumpleton** [comment]
Closing in deference to #2379.

The command to run to fix up the config in the interim is:

```
minishift openshift config set --patch '{"admissionConfig": {"pluginConfig": {"openshift.io/ImagePolicy": {"configuration": {"resolutionRules": null, "kind": "ImagePolicyConfig", "executionRules": [{"skipOnResolutionFailure": true, "invertMatch": false, "name": "execution-denied", "onResources": [{"resource": "pods", "group": ""}, {"resource": "builds", "group": ""}], "matchRegistries": null, "matchIntegratedRegistry": false, "matchImageLabels": null, "matchImageAnnotations": [{"set": false, "value": "true", "key": "images.openshift.io/deny-execution"}], "ignoreNamespaceOverride": false, "reject": true, "matchDockerImageLabels": null}], "apiVersion": "v1", "resolveImages": ""}, "location": ""}}}}'
```
