### ISSUE TITLE
 Minishift startup error: FAIL E0518 19:24:48.225517   12503 start.go:376] Error starting the VM:

### ISSUE THREAD

**Issue by ArjunSreepad** [minishift/minishift#2393]
### General information

  * Minishift version: minishift-1.17.0-linux-amd64
  * OS: Linux / macOS / Windows: Aws EC2 machine: Linux
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox: KVM

### Steps to reproduce

  1. Started minishift via "minishift start"

### Expected
Start of minshift

### Actual
Error as per log

### Logs

https://gist.github.com/ArjunSreepad/14fb60ef96e9ea85aaa67f6dce30902b#file-gistfile1-txt

**Comment by ArjunSreepad** [comment]
I tried but error remains the same
PFB link for the logs
https://gist.github.com/ArjunSreepad/01edfc3146e4b40f83220f6a5e6226da

**Comment by anjannath** [comment]
@ArjunSreepad Was minishift working for you before, or is it a new setup.. can you please double check if virtualization support (VT-X/AMD-V) is enabled in BIOS? Also are you trying to run it inside a VM?

----------------------------------------------------------------
https://stackoverflow.com/questions/11116704/check-if-vt-x-is-activated-without-having-to-reboot-in-linux#11118147

**Comment by anjannath** [comment]
@ArjunSreepad Any updates? Did you try to start it again?

**Comment by ArjunSreepad** [comment]
This is an aws EC2 machine

**Comment by gbraad** [comment]
Lee do not support AWS, and do not advice Nested Virtualization, unless you
know what you are doing.

In this case, check your config, as it is likely something with your
nested=1, or similar.

Siggest closing this

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by ArjunSreepad** [comment]
ok........
