### ISSUE TITLE
Web console can't be installed offline

### ISSUE THREAD

**Issue by TpSr52** [minishift/minishift#2394]
### General information

  * Minishift version: v1.17.0
  * OS: Windows
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. Put the OC binary in C:\Users\{Username}\.minishift\cache\oc\v3.9.0\windows
  3. Get offline (Disconnect intenet connection)
  2. Run minishift start --iso-url file://D:/Minishift/minishift-b2d.iso --vm-driver virtualbox
  3. Added minishift hostfolder and mounted it
  4. Added the registry, the router and the openshift origin v3.9.0 images into the directory
  5. "minishift ssh" into the minishift machine
  6. Load the images into the docker machine
  7. Run minishift stop
  8. run minishift start --show-libmachine-logs -v5 --iso-url file://D:/Minishift/minishift-b2d.iso --vm-driver virtualbox

### Expected

The web console is installed correctly and you can login into it.

### Actual

The web console isn't installed correctly and you cannot login into it

### Logs

[Log](https://gist.github.com/TpSr52/fef1aeccfc7589127278a37b1d6fcd87)

**Comment by gbraad** [comment]
The way to cache images is wrong as what I can see from the steps. Please
use the image caching feature as provided by Minishift. This is enabled by
default, but needs to cache once at least with connectivity. Please consult
the documentation.

**Comment by TpSr52** [comment]
@gbraad Thank you! It works

**Comment by praveenkumar** [comment]
Great, I am closing this issue then.
