### ISSUE TITLE
minishift start not work in VirtualBox 5.2

### ISSUE THREAD

**Issue by robyp1** [minishift/minishift#2395]
Hi, i have windows 10  with Virtual Box 5.2.12, S.O in virtual Box is
Linux version 3.10.0-862.2.3.el7.x86_64 (mockbuild@x86-041.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Mon Apr 30 12:37:51 EDT 2018

### General information

  * Minishift version: minishift v1.15.1+f19ac09 , CDK v3.4.0-2
  * OS:  Windows
  * Hypervisor:  VirtualBox 5.2.12

### Actual
 command:  minishift start --vm-driver virtualbox:
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.9.14' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.14' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- **Checking if VirtualBox is installed ... **FAIL****
   See the 'Installing Prerequisites for Minishift'  ...

### Logs
-- minishift version: v1.15.1+f19ac09
-- Starting profile 'minishift'
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:41426
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Failed to fetch machine
(minishift) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(minishift) DBG | [signal 0xb code=0x1 addr=0x0 pc=0x4d7167]
(minishift) DBG | 
(minishift) DBG | goroutine 13 [running]:
(minishift) DBG | panic(0x8c54a0, 0xc82000a130)
(minishift) DBG | 	/usr/local/go/src/runtime/panic.go:464 +0x3e6
(minishift) DBG | github.com/alexzorin/libvirt-go.(*VirDomain).GetState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/alexzorin/libvirt-go/domain.go:192 +0x87
(minishift) DBG | github.com/dhiltgen/docker-machine-kvm.(*Driver).GetState(0xc8201280e0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/dhiltgen/docker-machine-kvm/kvm.go:450 +0x70
(minishift) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).GetState(0xc8200d9b40, 0xe0d430, 0xc82014e0b0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:191 +0x45
(minishift) DBG | reflect.Value.call(0x8858a0, 0x93fe88, 0x13, 0x959cd0, 0x4, 0xc820036ef8, 0x3, 0x3, 0x0, 0x0, ...)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:435 +0x120d
(minishift) DBG | reflect.Value.Call(0x8858a0, 0x93fe88, 0x13, 0xc820036ef8, 0x3, 0x3, 0x0, 0x0, 0x0)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:303 +0xb1
(minishift) DBG | net/rpc.(*service).call(0xc820049ac0, 0xc820049880, 0xc82000b810, 0xc820015700, 0xc820146260, 0x7e14a0, 0xe0d430, 0x16, 0x89fca0, 0xc82014e0b0, ...)
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:383 +0x1c2
(minishift) DBG | created by net/rpc.(*Server).ServeCodec
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:477 +0x49d
Error getting machine state: unexpected EOF
-- Checking if requested OpenShift version 'v3.9.14' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.14' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM ...Found binary path at /usr/local/bin/docker-machine-driver-kvm
.Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:37271
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Failed to fetch machine
(minishift) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(minishift) DBG | [signal 0xb code=0x1 addr=0x0 pc=0x4d7167]
(minishift) DBG | 
(minishift) DBG | goroutine 13 [running]:
(minishift) DBG | panic(0x8c54a0, 0xc82000a130)
(minishift) DBG | 	/usr/local/go/src/runtime/panic.go:464 +0x3e6
(minishift) DBG | github.com/alexzorin/libvirt-go.(*VirDomain).GetState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/alexzorin/libvirt-go/domain.go:192 +0x87
(minishift) DBG | github.com/dhiltgen/docker-machine-kvm.(*Driver).GetState(0xc8201280e0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/dhiltgen/docker-machine-kvm/kvm.go:450 +0x70
(minishift) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).GetState(0xc8200d9b40, 0xe0d430, 0xc82014e0b0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:191 +0x45
(minishift) DBG | reflect.Value.call(0x8858a0, 0x93fe88, 0x13, 0x959cd0, 0x4, 0xc820036ef8, 0x3, 0x3, 0x0, 0x0, ...)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:435 +0x120d
(minishift) DBG | reflect.Value.Call(0x8858a0, 0x93fe88, 0x13, 0xc820036ef8, 0x3, 0x3, 0x0, 0x0, 0x0)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:303 +0xb1
(minishift) DBG | net/rpc.(*service).call(0xc820049ac0, 0xc820049880, 0xc82000b810, 0xc820015700, 0xc820146240, 0x7e14a0, 0xe0d430, 0x16, 0x89fca0, 0xc82014e0b0, ...)
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:383 +0x1c2
(minishift) DBG | created by net/rpc.(*Server).ServeCodec
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:477 +0x49d
 FAIL E0522 09:22:20.883798    3466 start.go:368] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
Error starting the VM: Error getting the state for host: unexpected EOF

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

Thanks!

**Comment by anjannath** [comment]
@robyp1 Can you please try it again with the latest release of _minishift_, also make sure you have disable Hyper-V.

**Comment by sadityalal** [comment]
hey, i had same issue, try to run the cmd with admin privileges..

**Comment by asuresh-quinnox** [comment]
![image](https://user-images.githubusercontent.com/63102865/79250502-9b99a580-7e76-11ea-8cbb-e0aa1f8e6b93.png)

Hi, trying to start minishift on WIndows 10 with virtualbox.

PS C:\windows\system32> minishift version
minishift v1.34.2+83ebaab

It is failing?

PS C:\windows\system32> minishift config set vm-driver virtualbox
No Minishift instance exists. New 'vm-driver' setting will be applied on next 'minishift start'
PS C:\windows\system32> minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... FAIL

**Comment by gbraad** [comment]
Make sure virtualbox is installed. Else, share debug output

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by asuresh-quinnox** [comment]
Thankyou, Got it after restarting the Windows machine. 
Finally able to install minishift with virtualbox on my PC and OKD is up and running. Need to create project and deploy few apps and search for dockerimages as well
THANKYOU. Typical windows restart.....
