### ISSUE TITLE
 Pulling image openshif/origin:v3.9.0 - FAIL

### ISSUE THREAD

**Issue by xytrams** [minishift/minishift#2397]
Hello,

Trying to start minishift in corporate environment, so, using proxy obviously.

1) The start log:

$ minishift start **--http-proxy=http://user:password@proxy.work.intra:8080 --https-proxy=http://user:password@proxy.cwork.intra:8080** --skip-registration
-- Starting profile 'minishift'
-- Using proxy for the setup
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM .............. OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ... 
   **Retrieving http://minishift.io/index.html ... FAIL**
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
**Pulling image openshift/origin:v3.9.0
error: FAIL**
   Error: error pulling Docker image openshift/origin:v3.9.0
   Caused By:
     Error: Error: No such image: openshift/origin:v3.9.0

2) I'm ssh to minishift, the log:

$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.41-boot2docker
Operating System: Minishift Boot2Docker ISO Version: 1.2.0
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: minishift
ID: C2DL:A3Z2:XYD5:JUGP:Q7CM:PBK6:MS3X:KDX4:FVOT:FU3U:JAIU:FCAB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 23
 System Time: 2018-05-22T13:48:16.407987127Z
 EventsListeners: 0
**Http Proxy: http://user:password@proxy.work.intra:8080
Https Proxy: https://user:password@proxy.work.intra:8080**
No Proxy: localhost,127.0.0.1,172.30.1.1,192.168.*
Registry: https://index.docker.io/v1/
Labels:
 provider=kvm
Insecure Registries:
 172.30.0.0/16
 127.0.0.0/8

3) environment variables:

 env
SSH_CLIENT=192.168.42.1 54266 22
MAIL=/var/mail/docker
USER=docker
SHLVL=1
HOME=/home/docker
SSH_TTY=/dev/pts/0
PAGER=less -EM
PS1=\u@\h:\w\$ 
ENV=/home/docker/.ashrc
BACKUP=1
LOGNAME=docker
TERM=xterm-256color
PATH=/home/docker/.local/bin:/usr/local/sbin:/usr/local/bin:/apps/bin:/usr/sbin:/usr/bin:/sbin:/bin
G_FILENAME_ENCODING=iso8859-1
LANG=C
MANPAGER=less -isR
SHELL=/bin/sh
FLWM_TITLEBAR_COLOR=58:7D:AA
PWD=/home/docker
SSH_CONNECTION=192.168.42.1 54266 192.168.42.72 22
EDITOR=vi

4) I'm trying to 
curl "http://minishift.io/index.html" - with no result

5) when I'm passing proxy settings to curl, I get this result:
curl -x user:password@proxy.work.intra:8080 "http://minishift.io/index.html"
<!DOCTYPE html>
<html>
  <head>
    <meta charset=utf-8>
    <title>Redirecting...</title>
    <link rel="canonical" href="https://www.openshift.org/minishift/">
    <meta http-equiv="refresh" content="1; url=https://www.openshift.org/minishift/">
  </head>
  <body>
    <h1>Redirecting...</h1>
    <a href="https://www.openshift.org/minishift/">Click here if you are not redirected.</a>
  </body>
</html>

According to this issue: https://github.com/minishift/minishift/issues/1628 proxy settings for curl should be honoured. Unfortunately it is still an issue in 3.9.0

Could you please confirm my path of thinking is correct (I'm not missing anything obvious) and please advise when this issue will be resolved, or in meantime please suggest some workaround.

Thanks!

**Comment by praveenkumar** [comment]
@xytrams Which version of minishift are you using?

I tried with latest one and checked if proxy is set in the env and looks like it does.

```
$ $ export MINISHIFT_ENABLE_EXPERIMENTAL=y
$ ./minishift start --http-proxy='http://foo:bar@10.x.4.x:3128' --no-provision
-- Starting profile 'minishift'
-- Using proxy for the setup
-- Checking if https://github.com is reachable ... FAIL
-- Checking if requested OpenShift version 'v3.9.0' is valid ... SKIP
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .....................-- Setting proxy information ... .OK
 OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK

[prkumar@local bin]$ ./minishift ssh
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.12.6, build HEAD : 5ab2289 - Wed Jan 11 03:20:40 UTC 2017
Docker version 1.12.6, build 78d1802

docker@minishift:~$ env
SSH_CLIENT=192.168.42.1 36542 22
MAIL=/var/mail/docker
USER=docker
SHLVL=1
HOME=/home/docker
NO_PROXY=localhost,127.0.0.1,172.30.1.1,localhost,127.0.0.0/8,::1
SSH_TTY=/dev/pts/0
PAGER=less -EM
PS1=\u@\h:\w\$ 
ENV=/home/docker/.ashrc
BACKUP=1
LOGNAME=docker
TERM=xterm-256color
PATH=/home/docker/.local/bin:/usr/local/sbin:/usr/local/bin:/apps/bin:/usr/sbin:/usr/bin:/sbin:/bin
G_FILENAME_ENCODING=iso8859-1
LANG=C
MANPAGER=less -isR
SHELL=/bin/sh
FLWM_TITLEBAR_COLOR=58:7D:AA
PWD=/home/docker
SSH_CONNECTION=192.168.42.1 36542 192.168.42.114 22
HTTP_PROXY=http://foo:bar@10.x.49.x:3128
EDITOR=vi
```

**Comment by xytrams** [comment]
$ minishift version
minishift v1.17.0+f974f0c

**Comment by xytrams** [comment]
OS:
centos-release-7-4.1708.el7.centos.x86_64

**Comment by praveenkumar** [comment]
@xytrams can you try what I mentioned and check if actually proxy setting is part of env?

**Comment by xytrams** [comment]
I believe I did it in my original post, but here we go again:

docker@minishift:~$ env
SSH_CLIENT=192.168.42.1 56074 22
MAIL=/var/mail/docker
USER=docker
SHLVL=1
HOME=/home/docker
SSH_TTY=/dev/pts/0
PAGER=less -EM
PS1=\u@\h:\w\$ 
ENV=/home/docker/.ashrc
BACKUP=1
LOGNAME=docker
TERM=xterm-256color
PATH=/home/docker/.local/bin:/usr/local/sbin:/usr/local/bin:/apps/bin:/usr/sbin:/usr/bin:/sbin:/bin
G_FILENAME_ENCODING=iso8859-1
LANG=C
MANPAGER=less -isR
SHELL=/bin/sh
FLWM_TITLEBAR_COLOR=58:7D:AA
PWD=/home/docker
SSH_CONNECTION=192.168.42.1 56074 192.168.42.72 22
EDITOR=vi

**Comment by xytrams** [comment]
Praveen, 

from you minishift start log:
`-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
`
Could you explain why? I would expect external hosts should be available.

**Comment by praveenkumar** [comment]
> Could you explain why? I would expect external hosts should be available.

@xytrams I was not connected to host just checked for a dummy proxy to make sure it is part of the `env` but you are saying it still not :(, not sure what you are missing here.

**Comment by xytrams** [comment]
@praveenkumar 

Tell me what I need to double check to make sure I'm not missing anything obvious. I'm kind of stuck here.

**Comment by praveenkumar** [comment]
@xytrams I am not sure what is missing here, Are you available for a video call where you can share your desktop and we can debug this further? (like bluejeans or hangout or Zoom) ?

**Comment by xytrams** [comment]
@praveenkumar zoom - yuliya.polyeno@gmail.com

**Comment by praveenkumar** [comment]
@xytrams sent you mail to join the bridge.

**Comment by praveenkumar** [comment]
@xytrams I am closing this issue as per our discussion and create a new one for exporting lower case variable for the proxy. I think it's not good to change the description of this issue where we had a different conversation.

**Comment by damianesteban** [comment]
So was this resolved? I'm having the same issue on macOS.

**Comment by gbraad** [comment]
Note: there is no use in setting `--skip-registration` when you use the
CentOS images. This is only used for te RHEL-based images.
