### ISSUE TITLE
lower case of proxy env also should be part of the VM

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2398]
As of now if you are working on proxy env then we only set the `HTTP_PROXY` and `HTTPS_PROXY` in the VM environment variable which doesn't work for each command. Interestingly it even not work with `curl` :(, looks like curl only respect the lower case of the variable so it is better to export both kinds of the variable instead depending on single one.

cc @xytrams

**Comment by LalatenduMohanty** [comment]
Resolved via #2402
