### ISSUE TITLE
problem connecting to a clusterIP service from the pod backing the service

### ISSUE THREAD

**Issue by ddsrupert** [minishift/minishift#2400]
### General information

  * Minishift version: v3.9.0
  * OS: macOS 
  * Hypervisor: xhyve 

### Steps to reproduce

  1. install the python app using the 'django-ex' sample repo
  2. open a terminal in the django-ex pod 
  3. `curl -v --head django-ex`

### Expected
This is what I see in our production cluster, or when I run the curl command from a *different* pod deployed in the same app:
```
(app-root) sh-4.2$ curl -v --head django-ex:8080
* About to connect() to django-ex port 8080 (#0)
*   Trying 172.30.10.3...
* Connected to django-ex (172.30.10.3) port 8080 (#0)
> HEAD / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: django-ex:8080
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Server: gunicorn/19.4.5
...

```

### Actual
```
(app-root) sh-4.2$ curl -v --head django-ex:8080
* About to connect() to django-ex port 8080 (#0)
*   Trying 172.30.14.211...
* Connection timed out
* Failed connect to django-ex:8080; Connection timed out
* Closing connection 0
curl: (7) Failed connect to django-ex:8080; Connection timed out
```

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@jorgemoralespou any idea about it?

**Comment by praveenkumar** [comment]
@ddsrupert I am not sure if that is the issue but I did a little experiment and looks like I can't able to curl service for a pod which itself is running. I used cakephp+mysql template and results are below. May be you send a mail to openshift-users ML and get more info around if this is expected behavior.

```
$ oc get pods
NAME                               READY     STATUS      RESTARTS   AGE
cakephp-mysql-persistent-1-build   0/1       Completed   0          7m
cakephp-mysql-persistent-1-vx27l   1/1       Running     0          1m
mysql-1-zkwms                      1/1       Running     0          7m

$ oc get service
NAME                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
cakephp-mysql-persistent   ClusterIP   172.30.92.66    <none>        8080/TCP   7m
mysql                      ClusterIP   172.30.97.138   <none>        3306/TCP   7m

$ oc rsh cakephp-mysql-persistent-1-vx27l

sh-4.2$ curl -v --head mysql:3306
* About to connect() to mysql port 3306 (#0)
*   Trying 172.30.97.138...
* Connected to mysql (172.30.97.138) port 3306 (#0)
> HEAD / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: mysql:3306
> Accept: */*

$ curl -v --head cakephp-mysql-persistent:8080 
* About to connect() to cakephp-mysql-persistent port 8080 (#0)
*   Trying 172.30.92.66...
* Connection timed out
* Failed connect to cakephp-mysql-persistent:8080; Connection timed out
* Closing connection 0
```

**Comment by jorgemoralespou** [comment]
@praveenkumar I've found this issue which sounds similar, although that one should not happen on minishift. https://github.com/openshift/origin/issues/14092

**Comment by praveenkumar** [comment]
@ddsrupert Can you please put about the workaround you used so in future if someone faces the same issue we can point them?

**Comment by ddsrupert** [comment]
I ran into this issue when using this ['all-in-one' development container for kafka/zookeeper,](https://github.com/Landoop/fast-data-dev) which runs kafka and several related services. (Obviously in deployment these services would be broken out into separate deployments, but it is convenient for development.) 

As the other services are running on the same pod as kafka, there were not able to connect using the advertised clusterIP service.

The workaround is register multiple kafka listeners, one for localhost access and one for clusterIP service. This is also the route to go down if you want to access kafka from outside the cluster as well via a nodePort [as discussed here](https://github.com/Yolean/kubernetes-kafka/issues/13)

**Comment by guattang** [comment]
I also had the same issue - also with Kafka. I assume the workaround described by @ddsrupert would also work in my use-case. However, deploying the exact same configuration in OpenShift Online or in Origin works, so I think this does need to be fixed in Minishift. 

The underlying issue can be easily reproduced without the need to deploy the full zookeeper/kafka stack. For example, deploy a nginx application and simply use the sample git repository. This creates the service nginx-ex (on port 8080). This service can be reached from all pods apart from within the nginx pod itself.

**Comment by anjannath** [comment]
https://github.com/openshift/origin/issues/20497

**Comment by GrahamDumpleton** [comment]
This should be re-opened as it is still a problem.

```
$ minishift version
minishift v1.29.0+72fa7b2

$ oc version
oc v3.11.62
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server https://192.168.64.34:8443
kubernetes v1.11.0+d4cacc0
```

The bot should be prevented from closing it.

That this still doesn't work can be a big problem, as it would always be possible to work around it if is a third party application/image you are using.

**Comment by gbraad** [comment]
This is actually an upstream issue
It can be marked as status/pinned but not really in favour of this...

**Comment by gbraad** [comment]
@Graham Dumpleton make sure the issue upstream has the right status;
as it has can stale there too:
https://github.com/openshift/origin/issues/20497

On Sun, Jan 6, 2019 at 6:12 PM Gerard Braad <me@gbraad.nl> wrote:
>
> This is actually an upstream issue
> It can be marked as status/pinned but not really in favour of this...
>


-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by ivandov** [comment]
This is still an issue in OKD v3.11 - no workarounds defined and this issue has gone stale... it should be re-opened.

**Comment by GrahamDumpleton** [comment]
At this point it is highly unlikely to be fixed. This is because Minishift is deprecated in favour of Code Ready Containers for future OpenShift versions.

**Comment by pgerv12** [comment]
For those that stumble across this issue, there is a workaround that works for me: https://github.com/kubernetes/minikube/issues/1568#issuecomment-308674617
