### ISSUE TITLE
minishift start issue

### ISSUE THREAD

**Issue by fmontaldo3** [minishift/minishift#2408]
### General information

  * Minishift version: minishift v1.15.1+f19ac09
  * OS: rhel 7.5
  * Hypervisor: KVM 

HI,

I want to run minishift under rhel 7.5 and I got the following issue:

 minishift start
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.9.14' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.14' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ...
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM ................ OK
-- Registering machine using subscription-manager
   Red Hat Developers or Red Hat Subscription Management (RHSM) username: fmontaldo3@gmail.com
   Red Hat Developers or Red Hat Subscription Management (RHSM) password: [HIDDEN]
   Registration in progress ...................................... FAIL [2m10s]
Error to register VM: ssh command error:
command : sudo -E subscription-manager register --auto-attach --username USER --password 'PASSWORD'
err     : exit status 70
output  : Registering to: subscription.rhsm.redhat.com:443/subscription
Network error, unable to connect to server. Please see /var/log/rhsm/rhsm.log for more information.

 minishift version
minishift v1.15.1+f19ac09
CDK v3.4.0-2

**Comment by praveenkumar** [comment]
@fmontaldo3 This looks like network issue, are you behind a proxy or VPN? Also can you try to use `--skip-registration` flag ?

**Comment by gbraad** [comment]
This might be a DNS issue? You can verify this with doing `minishift ssh --
ping subscription.rhsm.redhat.com
<http://subscription.rhsm.redhat.com:443/subscription>` after the failure.
This will perform a ping from inside the VM and the results will be shown.

**Comment by fmontaldo3** [comment]
Hi,

I just reinstall the entire rhel server and now is working

**Comment by gbraad** [comment]
Could you close the issue?

It seems to have been a misconfiguration. Likely due to DHCP or a failing
DNS lookup. Anyway, good to hear it works now

**Comment by praveenkumar** [comment]
Closing this issue since now it's working.
