### ISSUE TITLE
Fix `minishift oc-env --no-proxy` behavior on Windows

### ISSUE THREAD

**Issue by svenstaro** [minishift/minishift#2413]
### General information

  * Minishift version: v1.17.0+c741cbdd
  * OS: Windows
  * Hypervisor: VirtualBox

### Steps to reproduce

1.

    echo $NO_PROXY:
    127.0.0.1,localhost,.company.tld

2.

    echo $no_proxy
    <empty output>

3.

    eval $(minishift oc-env --no-proxy)

### Expected

    echo $NO_PROXY
    127.0.0.1,localhost,.company.tld,192.168.99.101
    echo $no_proxy
    <empty output>

If `NO_PROXY` is already set while `no_proxy` is NOT set then I'd expect `NO_PROXY` to be extended and `no_proxy` shall remain unset. This makes sense since if the user is already using `NO_PROXY` but not `no_proxy`, there's probably a good reason for that.

### Actual

    echo $NO_PROXY
    127.0.0.1,localhost,.company.tld
    echo $no_proxy
    127.0.0.1,localhost,.company.tld,192.168.99.101

**Comment by svenstaro** [comment]
Turns out that this is an issue only on Windows due to its case-insensitivity in regards to env vars.

**Comment by LalatenduMohanty** [comment]
Resolved via #2419
