### ISSUE TITLE
cannot configure gitlab on minishift

### ISSUE THREAD

**Issue by fmontaldo3** [minishift/minishift#2420]
### General information

  * Minishift version: 
     minishift v1.15.1+f19ac09
     CDK v3.4.0-2

  * OS: Linux  rhel 7.4
  * Hypervisor: KVM 

Hi,

I want to configure gitlab under my minishift environment but fails.

as developer user 

oc new-project gitlab
oc new-app --template=postgresql-persistent -p POSTGRESQL_USER=admin POSTGRESQL_PASSWORD=redhat POSTGRESQL_DATABASE=gitlab

as admin
oc edit scc anyuid
add
users:
- system:serviceaccount:gitlab:default

oc new-app  sameersbn/redis

oc new-app gitlab-ce:latest --name=gitlab \
	-p GITLAB_HOST=http://gitlab.apps.mycompany.com \
	-p DB_TYPE=postgres \
	-p DB_HOST=172.30.100.235 \
	-p DB_PORT=5432 \
	-p DB_NAME=gitlab \
	-p DB_USER=admin \
	-p DB_PASS=admin \
	-p REDIS_HOST=172.30.95.146 \
	-p REDIS_PORT=6379 \
	-p GITLAB_SECRETS_DB_KEY_BASE=1234567890

When I finishf the process the gitlab cannot connect to redis. There is a way to implement gitlab ?
I tried to follow the gitlab minishfit template but also fails. The pods restart all the time. 

Regards

**Comment by LalatenduMohanty** [comment]
@fmontaldo3 for any uid we have an add-on named "anyuid" which you can use, check https://docs.openshift.org/latest/minishift/using/addons.html#default-addons

**Comment by LalatenduMohanty** [comment]
@fmontaldo3 I never tried gitlab on OpenShift. But have you seen https://about.gitlab.com/2016/06/28/get-started-with-openshift-origin-3-and-gitlab/ ?

**Comment by fmontaldo3** [comment]
I already did the instructions of that page and it didn't work. Do you know a way to debug the deployment?.

**Comment by fmontaldo3** [comment]
the deploy shows me this:

Readiness probe failed: Get http://172.17.0.7:80/help: dial tcp 172.17.0.7:80: getsockopt: connection refused
 Unhealthy 
Readiness probe failed: HTTP probe failed with statuscode: 502

**Comment by anjannath** [comment]
The gitlab template for openshift is at fault here.

**Comment by budhram** [comment]
Closing this as we cannot do much from our side.
