### ISSUE TITLE
Config option `hyperv-virtual-switch` has issues when non-ascii characters are present in the name

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#2429]
### General information

  * Minishift version: master
  * OS: Windows
  * Hypervisor: Hyper-V

### Steps to reproduce

  1. `minishift config set hyper-virtual-switch <some name with non-ascii chars>`
  2.  `minishift start`

**Comment by gbraad** [comment]
I seems the cmdlets do not even honor the non-ASCII characters:

```
PS C:\work\src\github.com\minishift\minishift> .\out\windows-amd64\minishift.exe config set hyperv-virtual-switch Przełąś

Internal use of get-VMSwitch returns: 
Name    SwitchType NetAdapterInterfaceDescription
----    ---------- ------------------------------
Przelas Private





Name    SwitchType NetAdapterInterfaceDescription
----    ---------- ------------------------------
Przelas Private


```

**Comment by gbraad** [comment]
this makes the function `chooseVirtualSwitch` to behave wrongly, as it tries to return all switches using `	stdout, err := cmdOut("(Get-VMSwitch).Name")`. This means the returned name will be `Przelas`, instead of our expected and requested: `Przełąś`.

**Comment by gbraad** [comment]
Dropped use of https://github.com/gorillalabs/go-powershell/ due to https://github.com/gorillalabs/go-powershell/issues/10

**Comment by acerto** [comment]
This may be related to an issue I resolved. 

My computer name contained multiple hyphens, the second hyphen was causing Hyper-V to trim what it was recognising as my computer name. Renamed my computer and was able to set config options.

An easy check was that the incorrect computer name was reflected in the Hyper-V GUI.
