### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by jeusdi** [minishift/minishift#2434]
### General information

  * Minishift version: v1.17.0+f974f0c
  * OS: Linux / Windows
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. minishift start --openshift-version v3.7.0 --vm-driver=virtualbox --http-proxy=http://<user>:<passwd>@<ip>:<port>/ --https-proxy=http://<user>:<passwd>@<ip>:<port>/ --docker-env HTTP_PROXY=<user>:<passwd>@<ip>:<port> --docker-env HTTPS_PROXY=<user>:<passwd>@<ip>:<port>

### Expected
I need to be able to set three kind of proxy:

  * docker proxy: docker proxy used in order to download images and so on...
  * minishift proxy: proxy in order to download isos and other artifcats minishift needs to set up openshift.
  * guest so proxy: I don't know whether it's possible but, I'd like to be able to set guest SO proxy.

Currently, I'm getting this message when I perform `oc logout` once openshift instance is just launched.

> Unable to connect to the server: Proxy Authentication Required

**Comment by praveenkumar** [comment]
@jeusdi you put what you expected for all the proxy settings but did you get all the settings in place?

Also when you says `oc logout` need proxy auth did you use `minishift oc-env --no-proxy` to set the oc binary to path?

**Comment by praveenkumar** [comment]
@jeusdi does your problem solved or do you mind sharing some info?

**Comment by gbraad** [comment]
At the moment we are looking into proxy related issues. Is the one reported here still reproducible?

Also, take note that `minishift start --openshift-version v3.7.0 --vm-driver=virtualbox --http-proxy=http://:@:/ --https-proxy=http://:@:/` should have been enough, as the docker environment variables will be applied by us.

**Comment by gbraad** [comment]
No update... I'm closing this issue.
