### ISSUE TITLE
minishift 3.9 ansible broker issue

### ISSUE THREAD

**Issue by fmontaldo3** [minishift/minishift#2438]
### General information

  * Minishift version: 
    minishift v1.15.1+f19ac09
CDK v3.4.0-2

  * OS: Linux
  * Hypervisor: KVM 

### Steps to reproduce

  Hi,

I tried to configure ansible broker on the following way.

oc cluster up --version=latest --service-catalog=true --routing-suffix=172.17.0.1.nip.io --public-hostname=172.17.0.1.nip.io

oc new-project ansible-service-broker
curl -s https://raw.githubusercontent.com/openshift/ansible-service-broker/master/templates/simple-broker-template.yaml | oc process -n "ansible-service-broker" -f - | oc create -f -

I can deploy the APB 
oc get clusterserviceclasses --all-namespaces -o custom-columns=NAME:.metadata.name,DISPLAYNAME:spec.externalMetadata.displayName | grep APB

apb list
Contacting the ansible-service-broker at: https://asb-1338-ansible-service-broker.172.17.0.1.nip.io/openshift-automation-service-broker/v2/catalog
ERROR: Failed broker request (get) https://asb-1338-ansible-service-broker.172.17.0.1.nip.io/openshift-automation-service-broker/v2/catalog
Exception occurred! local variable 'InsecureRequestWarning' referenced before assignment

How can I resolve this issue?

### Expected
apb list show the APB list of images

### Actual
apb list
Contacting the ansible-service-broker at: https://asb-1338-ansible-service-broker.172.17.0.1.nip.io/openshift-automation-service-broker/v2/catalog
ERROR: Failed broker request (get) https://asb-1338-ansible-service-broker.172.17.0.1.nip.io/openshift-automation-service-broker/v2/catalog
Exception occurred! local variable 'InsecureRequestWarning' referenced before assignment

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@fmontaldo3 looks like you are missing some steps on the issue. Following command, you executed on the minishift VM or on the host because as part of minishift we also use `oc cluster up` and this should not be executed in the VM.

```
oc cluster up --version=latest --service-catalog=true --routing-suffix=172.17.0.1.nip.io --public-hostname=172.17.0.1.nip.io
```

**Comment by fmontaldo** [comment]
You are right.


I tried to configure ansible broker on the following way.

oc cluster up --version=latest --service-catalog=true --routing-suffix=172.17.0.1.nip.io --public-hostname=172.17.0.1.nip.io

oc new-project ansible-service-broker
curl -s https://raw.githubusercontent.com/openshift/ansible-service-broker/master/templates/simple-broker-template.yaml | oc process -n &quot;ansible-service-broker&quot; -f - | oc create -f -

I can deploy the APB 
oc get clusterserviceclasses --all-namespaces -o custom-columns=NAME:.metadata.name,DISPLAYNAME:spec.externalMetadata.displayName | grep APB

apb list
Contacting the ansible-service-broker at: https://asb-1338-ansible-service-broker.172.17.0.1.nip.io/openshift-automation-service-broker/v2/catalog
ERROR: Failed broker request (get) https://asb-1338-ansible-service-broker.172.17.0.1.nip.io/openshift-automation-service-broker/v2/catalog
Exception occurred! local variable 'InsecureRequestWarning' referenced before assignment

How can I resolve this issue?

**Comment by praveenkumar** [comment]
@fmontaldo3 This is `oc cluster up` issue so best you can create an issue to https://github.com/openshift/origin/issues or send a mail to openshift-users ML, from minishift point of view we can't have this as support.

Another thing is why you are using `172.17.0.1` as routing suffix on your host, `oc cluster up` automatic create the `127.0.0.1` for local development and that should be worked.

**Comment by fmontaldo3** [comment]
I can reprosuce it with minishift start is the same to me. I
