### ISSUE TITLE
How to install metrics on minishift cluster

### ISSUE THREAD

**Issue by codependent** [minishift/minishift#2447]
### General information

  * Minishift version: minishift v1.16.1+d9a86c9
  * OS: macOS
  * Hypervisor: xhyve

I haven´t found any information about how to install metrics on minishift. Apparently there used to be a flag `--metrics` that you could use at cluster start to provision the necessary pods, but it is not valid anymore.

### Steps to reproduce

`minishift start`

```
oc get pod -n openshift-infra
No resources found.
```

### Expected
Metrics pods running

### Actual
No metrics pods

### Logs

```
-- Starting profile 'minishift'
-- Checking if https://github.com is reachable (using proxy: "No") ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB


```

**Comment by LalatenduMohanty** [comment]
@codependent We found that the `metrics` support in `oc cluster up` (which Minishift also uses) is broken from many releases and hence we removed it from Minishift. It was also experimental in Minishift. You can directly pass required flag to "oc lcuster up" as mentioned below. 

`$ MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --extra-clusterup-flags "--metrics" ` [1] 

[1] https://docs.openshift.org/latest/minishift/using/experimental-features.html#enabling-experimental-oc-flags

**Comment by codependent** [comment]
@LalatenduMohanty Thanks for your quick answer. I have tried that command and the cluster starts after a while. However as you say the metrics infrastructure is broken, there isn't any pod in the openshift-infra namespace.

Do you know if there's any open issue in which someone is taking care of it? Any hope we'll have this fixed any time soon?

**Comment by gbraad** [comment]
What more do we need to do here? This is documented...
I suggest closing

**Comment by gbraad** [comment]
@codependent issues related to this should be filed on openshift/origin. Many issues are known and filed in their issue tracker.

**Comment by anjannath** [comment]
Closing this as nothing can be done from our side.

**Comment by acarr-work** [comment]
As of minishift version v1.23.0+91235ee:
https://docs.okd.io/latest/install_config/cluster_metrics.html

**Comment by everflux** [comment]
As reference, this ticket might provide an answer for minishift deployments: https://github.com/openshift/origin-metrics/issues/408
