### ISSUE TITLE
Nightly tests failing as xpaas applications fail to deploy on CentOS ISO

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2450]
### General information

  * Minishift version: latest master
  * OS: Linux
  * Hypervisor: KVM

### Steps to reproduce

  1. minishift start --iso-url centos 
2. minishift addon apply xpaas
  2. eval $(minishift oc-env)
  3. oc new-app eap70-basic-s2i
  4. oc logs -f bc/eap-app

### Expected

Template eap70-basic-s2i being deployed successfully.

### Actual

```
Cloning "https://github.com/jboss-developer/jboss-eap-quickstarts" ...
        Commit: d9281fa6c7ca7a498bdf95049c64bbbe41b989cf (Update POM versions for EAP 7.0.0.GA release)
        Author: Paul Gier <pgier@redhat.com>
        Date:   Thu May 19 13:36:55 2016 -0500
Pulling image "registry.access.redhat.com/jboss-eap-7/eap70-openshift@sha256:7a3acb825766a00fd865d9616bbd129fd747dd38b340704c835e47b9071de1d4" ...
pulling image error : open /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt: no such file or directory
error: build error: unable to get registry.access.redhat.com/jboss-eap-7/eap70-openshift@sha256:7a3acb825766a00fd865d9616bbd129fd747dd38b340704c835e47b9071de1d4
```

**Comment by LalatenduMohanty** [comment]
Root cause for the issue https://lists.centos.org/pipermail/centos-devel/2018-June/016749.html

**Comment by budhrg** [comment]
> Root cause for the issue https://lists.centos.org/pipermail/centos-devel/2018-June/016749.html

@LalatenduMohanty  No response it seems.

**Comment by LalatenduMohanty** [comment]
This is fixed as part of https://github.com/minishift/minishift-centos-iso/issues/251
