### ISSUE TITLE
Correct the code for default switch check for HyperV

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2454]
The environment variable does not exist anymore

https://github.com/minishift/minishift/blob/1426bddcbf7aae0b8fab29dbe28b667a9ae218cb/pkg/minishift/network/settings_windows.go#L43

**Comment by gbraad** [comment]
This needs to be addressed to be correct, however the implementation might even be altered.

**Comment by LalatenduMohanty** [comment]
@gbraad Can you please add some more context?

**Comment by gbraad** [comment]
In the current implementation there is a check for the environment
variable, this has since been removed. This check needs to be updated to
use the config variables...

TBH, this check is actually questionable at the moment as the default
switch should work as expected in the current release of Windows 10 (1803).

**Comment by gbraad** [comment]
Merged

**Comment by gbraad** [comment]
> should work as expected in the current release of Windows 10 (1803).

This is still not the case with the current release of Windows. the "Default Switch" still stops traffic when the DHCPRequest wasn't given.
