### ISSUE TITLE
Add a script to perform prerequisites for remote machine in case of generic driver

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2459]
As of now, we have prerequisites from remote machine side before provision it with minishift, such as install Docker, net-tools, and firewalld packages then open required port from firewall those can be easily automated either by ansible or by a script which can run before the provisioner even start.

**Comment by gbraad** [comment]
There is a difference between 'checking pre-requisites' and 'installing pre-requisites'. We need to be careful about what we provision from minishift. As we need to instruct the user we will install packages on the remote machine. In some cases they might not want this. In that case, a check and a fail/warn would be more appropriate?

**Comment by agajdosi** [comment]
@gbraad I am not sure if I got @praveenkumar's issue correctly, but I understand it that we could provide an Ansible playbook as part of Minishift, but it will be the user who will need to execute it. And plus Minishift should check for the packages and configuration needed in beginning of `m start --vm-driver generic`.

**Comment by cmoulliard** [comment]
> who will need to execute it

Ansible playbook (packaged as a docker image) could also be executed using a k8s job included in an minishift addon ;-)

**Comment by gbraad** [comment]
That is the point. We do need to check for pre-requisites, but when
mentioned to install this as part of the provisioner; we have a problem.

Pre-flight checks happen BEFORE the start or before the provisioning. So we
have the be clear what we need to do. I do not think a k8s job would help
here ;-), as this is before standing up OpenShift, but having the user do
it might not be the expected approach either.

**Comment by praveenkumar** [comment]
> Ansible playbook (packaged as a docker image) could also be executed using a k8s job included in an minishift addon ;-)

@cmoulliard But that addon will only be executed once minishift up and running, In our case, this should be part of before even minishift start.

**Comment by praveenkumar** [comment]
> There is a difference between 'checking pre-requisites' and 'installing pre-requisites'. We need to be careful about what we provision from minishift. As we need to instruct the user we will install packages on the remote machine. In some cases, they might not want this. In that case, a check and a fail/warn would be more appropriate?

@gbraad I agree but if a user really wants to provision single node cluster using minishift then those packages are must and should be installed, now we can tell users that these packages are going to install on that remote system and ask for confirmation (one way) or just do it. This is not done by provisioner part because provisioner (as of now) we are consuming is working for both our minishift iso (where those packages already part of our ISO) and Fedora/CentOS/RHEL side. What we can do in case of the generic driver before we hit the provisioner we should have some prerequisites code which should handle it.

**Comment by gbraad** [comment]
If we need to install packages, we might want to inform the user with a
prompt?

**Comment by LalatenduMohanty** [comment]
Resolved via #2613
