### ISSUE TITLE
Disable automatic update checks

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#246]
We are getting various bug reports around the fact that people see errors related to hitting the rate limit of the GitHub API. Minishift regularly checks against GitHub for an updated version of the binary or the VM. If one executes a lot of commands in succession you easily hit this limit. There is a config option to disable the checks or limit its rate, but per default checks are enabled.

Several options:

* Keep the checks, but make them silently fail (or at least provide a message which is more user friendly
* Invert the logic and make update checks a opt in (turning it off per default)
* Introduce a explicit 'update' command which does the checks when the user requests it

**Comment by jimmidyson** [comment]
I vote for a more user friendly error message - it was the plan all along - including details of how to disable.

Alternatively, on first use you could prompt the user for confirmation they want to do automatic update checks & walk them through how to create a github api key & how to use it with minishift. This first use interactive step could also be used to opt-in to anonymous usage data collection (perhaps using google analytics) which would be a good thing to add in to track numbers of users.

**Comment by agajdosi** [comment]
One thing to consider is that when limit is full, minishift is unable to download oc binary. This can be annoying when you want to clean old data, so you delete .minishift and then find minishift unable to start.
`E0104 16:27:43.701719   12700 start.go:216] Error starting 'cluster up':  Error attempting to download and cache oc: Could not get OpenShift release version v1.3.1 : GET https://api.github.com/repos/openshift/origin/releases/tags/v1.3.1: 403 API rate limit of 60 still exceeded until 2017-01-04 17:05:24 +0100 CET, not making remote request.; rate reset in 37m40.298271202s`

**Comment by jimmidyson** [comment]
Another reason to ask users if they want to set up a Github token & talk them through how to do it on start up. FYI the reason for using the Github API is because download file names are not consistent across OpenShift releases for every platform so minishift has to query the Github API for tagged release, then work out what the correct artifact containing `oc` to download is, depending on platform minishift is running on. Pretty important.

**Comment by forkbomber** [comment]
@jimmidyson homebrew added hint on setting up a token right into rate-limited error:
https://github.com/Homebrew/brew/blob/c3f959d6af36f075600aac63f208d59c30cd602c/Library/Homebrew/utils/github.rb#L23
That small cosmetic improvement alone would makes significant contribution to user experience.

**Comment by hferentschik** [comment]
This is also related to issue #204, #178, #112 and #192:

* the automatic update of the binary itself is broken due to the fact that we are now releasing archives (zip/tar)
* the persistent config flags to configure updates are not documented
* error messages are confusing the user

I think we have several options to solve this, but it needs a bit of planning and development. We are close to do another beta and I don't think we will have time to tackle properly before that. So I suggest to literally disable the update checks for the next beta. Just temporarily. We then look at this problem at a whole for the next milestone and fix all this related issues. How does that sound?

**Comment by LalatenduMohanty** [comment]
+1 for disabling the automatic update for the next beta release and fix the automatic update in the subsequent release.

**Comment by hferentschik** [comment]
merged via pull request #246
