### ISSUE TITLE
[Generic] minishift delete hangs when remote machine is deleted (manually) which provisioned by minishift  

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2460]
As of now if you have a remote machine on a cloud provider and before executing `minishift delete` to stop the cluster if you delete that machine first manually then try to execute `minishift delete` from the host will hang because it tries to do `oc cluster down` and machine not available.

We either need to set a timeout for those ssh command or at least put that behind the `force` so that it deleted with force.

**Comment by gbraad** [comment]
> if you delete that machine first manually then try to execute `minishift delete` from the host will hang because it tries to do `oc cluster down` and machine not available.

Isn't this as expected? I do think we should try to perform a reachability check first before attempting to communicate.

  * `IsIPReachable` should probably be done
    * before `start`
    * before `delete`
    * before `ssh`
    * etc.

I believe this issue is more generic. In the case of `unreachable` the user can decide themselves to use `--force` or not.
