### ISSUE TITLE
Modularize documentation

### ISSUE THREAD

**Issue by robin-owen** [minishift/minishift#2462]
This will involve reworking how the documentation is written and arranged while preserving the overall structure of the assembled documentation. This effort should allow us to create documentation which is easier to expand, modify, and maintain.

From a high level, we need to start breaking the larger documentation sections into small, modular pieces which can be assembled to create the necessary pages. Portions of the documentation will be broken down into one of the following categories:

* Concept/Overview
* Procedure/Task
* Reference

Individual modules will be prefixed as **_con_**, **_proc_**, or **_ref_** accordingly so that we can quickly identify the type of module written. Examples: **_con_getting-started-overview.adoc_**, **_proc_set-up-kvm-driver.adoc_**, **_ref_default-add-ons.adoc_**.

These small modules will be combined into assemblies (which correspond to the AsciiDoc files we currently have) using the AsciiDoc `include` directive. Working this way, we can keep the exact same structure for the generated **_*.html_** files while using a modular, maintainable approach to writing.

Note that to create the desired structure, we will be using symbolic links in the documentation. This is likely to have adverse effects for Windows builds of the documentation, but should _only_ affect the documentation build. I believe that the benefits of modularizing the documentation outweigh the potential effect on documentation builds under Windows, but I am open to suggestions which would alleviate this issue. :)

**Comment by robin-owen** [comment]
After experimenting with symbolic links, it seems that Middleman cannot work with them when serving the documentation locally (at least on Linux). Generating the documentation with symbolic links to directories works via `make gen_docs` works, but `make serve_docs` does not. As such, using symbolic links causes adverse effects that I did not expect even on platforms which explicitly support them.

Due to this, I'll be reevaluating the strategy of copying the **_common_content_** directory into each section of the documentation.

**Comment by gbraad** [comment]
the copying action would also have it's own issues. Would hardlinks work, or what about a bindmount for the folder? This would also not work on other platforms... :-s

**Comment by robin-owen** [comment]
@gbraad I didn't have any success using hard links, but I haven't tried a bindmount. I'll try that today and see if that works -- thanks for the suggestion. :)

**Comment by budhrg** [comment]
> These small modules will be combined into assemblies (which correspond to the AsciiDoc files we currently have) using the AsciiDoc include directive. Working this way, we can keep the exact same structure for the generated *.html files while using a modular, maintainable approach to writing.

:+1:  Good point.

> This is likely to have adverse effects for Windows builds of the documentation, 

Nothing to worry. Majority of users don't care.
Similar to our old issue [Unable to compile/build binary in Windows without cygwin](https://github.com/minishift/minishift/issues/1037).

**Comment by robin-owen** [comment]
> the copying action would also have it's own issues.

@gbraad Do you mind elaborating on this? This is the current strategy we already use with **_variables.adoc_**. Are there issues related to this that I'm unaware of?

**Comment by gbraad** [comment]
> @gbraad Do you mind elaborating on this? 

if only done as part of the CI, I see no problem. But if you start doing this for more places, and also in the general make, you start to introduce a possible confusion to which file needs to be edited (unless after make all duplication/copies are removed).

But I actually fear that the documentation this way becomes harder to navigate in an unrendered view. I do not see an added value at the moment. You do say:

> This effort should allow us to create documentation which is easier to expand, modify, and maintain.

can you elaborate a little bit more? Especially seen the disadvantage that is mentioned:

> Note that to create the desired structure, we will be using symbolic links in the documentation. 

I am not sure if this will create a better overview. Can you provide an example of how things will look?

**Comment by robin-owen** [comment]
Work on this issue in ongoing. Updates and a WIP PR should be submitted in the near future.

**Comment by budhram** [comment]
Thanks @robin-owen :smile: 

> Updates and a WIP PR should be submitted in the near future.

Waiting for quite sometime :wink:

**Comment by robin-owen** [comment]
@budhram I'm aware -- unfortunately, I've been busier than expected lately. ;)

**Comment by robin-owen** [comment]
Closing this issue, as it's too broad in scope. More targeted issues will be opened in the future to modularize sections of the documentation.
