### ISSUE TITLE
Architecture diagram in documentation refers to b2d ISO

### ISSUE THREAD

**Issue by robin-owen** [minishift/minishift#2463]
The Minishift architecture diagram in **_docs/source/using/basic-usage.adoc_** refers to the **_minishift_b2d.iso_** file instead of the **_minishift-centos7.iso_** file.

**Comment by robin-owen** [comment]
In that case, we could also use a generic version for `oc` in the diagram as well. At the moment, we have to do a fair bit of maintenance to ensure that the architecture diagram remains up-to-date -- it would be nice if we can replace each bit of specific information with something more generic.

**Comment by LalatenduMohanty** [comment]
@robin-owen +1 for generic information. However I think the actual version for cached `oc` version is not causing any confusion for users.

**Comment by budhram** [comment]
Resolved via https://github.com/minishift/minishift/pull/2820
