### ISSUE TITLE
Implement a way to specify an empty value for the variable using Var-Defaults for addon

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2464]
As of now, we don't have any capability to specify the empty value for `Var-Defaults` and if I look closely to https://github.com/minishift/minishift-addons/pull/124#pullrequestreview-128642538 conversation looks like it a valid use case and we should have a way to do it. 

I am thinking to define a keyword `NULL` or `null` to do it so during the variable parse we check the value and set it as empty in case of NULL/null/Null.

@minishift/minishift-dev any better idea?

**Comment by LalatenduMohanty** [comment]
> looks like it a valid use case and we should have a way to do it.

+1. Wondering how we have not see this till now.  I think if `# Var-Defaults: PROJECT_USER=`  has no value it should be considered no value.

**Comment by praveenkumar** [comment]
> I think if # Var-Defaults: PROJECT_USER= has no value it should be considered no value.

@LalatenduMohanty We have a `varDefaultsCheck` function which actually there to make sure user put correct convention about the var defaults which will be `key=value` if we disable that check that means if a user misses specifying the value which he should've then his addon might configure something which not intended to do. I think it good to be explicit instead of implicit about the value of variable.

**Comment by LalatenduMohanty** [comment]
Resolved via #2505
