### ISSUE TITLE
Use 1.1.1.1 instead of 8.8.8.8

### ISSUE THREAD

**Issue by fabiand** [minishift/minishift#2473]
1.1.1.1 might be a little more neutral than 8.8.8.8.

This addr is used in the pre-flight checks.

**Comment by gbraad** [comment]
1.1.1.1 does not work for China, however 1.0.0.1 would

**Comment by gbraad** [comment]
besides `--network-nameserver 1.1.1.1` can be used

**Comment by fabiand** [comment]
Yes, override works - I mainly wondered about the (praivacy respectig)
default.

Thanks for the note about China. 1.0.0.1 then looks better.

**Comment by gbraad** [comment]
I do not think we populate the VM with a DNS per default (only DHCP
values), ... right?

**Comment by fabiand** [comment]
Not sure, at least the pre-flight checks do mention that addres:

```
$ ~/Downloads/minishift start
-- Starting profile 'minishift'
-- Check if depereccated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... SKIP
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ...
OK
-- Checking if KVM driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ...
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .................. OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK                  # HERE HERE HERE
…
```

**Comment by gbraad** [comment]
This value can be changed and is described in the documentation.
It is purely an endpoint we know that can be reached bij the majority of
people.
However, in an enterprise environment this will certainly/mostly fail.

**Comment by fabiand** [comment]
Alright, I merely proposed to use a more pivacy respecting endpoint.

That beeing said, feel free toclose this issue.

**Comment by gbraad** [comment]
@minishift/minishift-dev WDYT?

**Comment by praveenkumar** [comment]
> This value can be changed and is described in the documentation. It is purely an endpoint we know that can be reached bij the majority of people.

@gbraad That's right, And since we already have to option to put as user required, I would say we can just close it. Also ` Pinging 8.8.8.8 ... OK` this is only for checking the connectivity not setting anything as part of a nameserver.

**Comment by LalatenduMohanty** [comment]
+1 for closing it as we are not using 8.8.8.8 for real. It is a cosmetic check to see if we can reach it.  Hence closing it cc @fabiand

**Comment by gbraad** [comment]
OK.

In future we might consider pinging a local address we determine to be part
of the host's network. Till then, this is not an issue.
