### ISSUE TITLE
Any other image is deleted if exported earlier before any default images

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2474]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. minishift start
```
$ ./minishift start
--
-- Starting profile 'minishift'
-- Check if depereccated options are used ... OK
[...]
-- Applying addon 'admin-user':..
-- Exporting of OpenShift images is occuring in background process with pid 9687.
```
  2. minishift image list
```
$ ./minishift image list
--
$
```
  3. minishift image export alpine:latest
```
$ ./minishift image export alpine:latest
--
Exporting 'alpine:latest'..... OK
```
  4. minishift image list
```
$ ./minishift image list
--
alpine:latest
```
  5. Wait till all the default images to be exported
  6. Then image list should contain "alpine:latest" but the image is no more in the list
  7. minishift image list
```
$ ./minishift image list
--
registry.access.redhat.com/openshift3/ose-docker-registry:v3.9.30
registry.access.redhat.com/openshift3/ose-haproxy-router:v3.9.30
registry.access.redhat.com/openshift3/ose:v3.9.30
```

### Expected
Exported image should be listed out

### Actual
Exported images is deleted 

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
what is the value of the list after a `minishift stop` and `minishift start` ?

**Comment by praveenkumar** [comment]
This looks like the background process which starts the image caching by default overwrite the `index.json` since this file is not present and it creates this and keeps it open until those images are cached.

if you look closely the blobs still have data about the alpine images. I will dig it bit deeper.

Here you can see shasum `41229c767e78913442ba2d57886137898ae5b7b968360d0c05c021d9f48626d0` blob is present just entry from the index.json got removed.

```
$ ./minishift image export alpine
Exporting 'alpine:latest'...... OK

Once backgroud process complete
$ ./minishift images list
openshift/origin-docker-registry:v3.9.0
openshift/origin-haproxy-router:v3.9.0
openshift/origin:v3.9.0

$ ls ~/.minishift/cache/images/blobs/sha256/
40db23e999d6b3bb76a5d216db90ee95cf25ddbb2fb962b6fa9ab1ddadac7c8a  a30329e8a43b10886a267ce59648c7e0adaad2285ea1ad34499cab23a29f1c67
41229c767e78913442ba2d57886137898ae5b7b968360d0c05c021d9f48626d0  b1a7f144ece0194921befe57ab30ed1fd98c5950db7996719429020986092058
631176df215a42279e1324209161cfc6f7e09e5917e24d3804fc003246a4c535  b80d202db162f3a2bacd2c73634eb96599a95627ea3db9183c4bfaec1c346f20
6eb0374dba9ab5362c835489a2a7bc24c3b63fb0e945f1812899358d716960ec  d18f10a65f0b0817bc73a427f6701425f3e2804c3480db40683e0d73f10095d8
7dc0dca2b1516961d6b3200564049db0a6e0410b370bb2189e2efae0d368616f  f14c9be6afe82e7e85e49203cea0f95356d300eecb587c76ff70196c0a620068
8479ac13acfc45d9aeff37ab2566710e4d7181b878d612dae61ec69d10deba88  fc5b37ec0b0d194ee7af560df70ce3218f55f0f1fbdb6ad03a058c845124f31c
902735699a076b6637bd5f991dda9d6cb2c093cbf3c01c191b540873edb6e9d5  ff3a5c916c92643ff77519ffa742d3ec61b7f591b6b7504599d95a4a41134e28
9a88c2195afed279da6e0069bc3a15637d7ee97c597155e3bccda7136b20b6a5

$ python -mjson.tool ~/.minishift/cache/images/index.json
{
       {
            "annotations": {
                "org.opencontainers.image.ref.name": "alpine:latest"
            },
            "digest": "sha256:41229c767e78913442ba2d57886137898ae5b7b968360d0c05c021d9f48626d0",
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            },
            "size": 348
        }
    ],
    "schemaVersion": 0
}
```

**Comment by praveenkumar** [comment]
Alright found the root cause and this is something we can't even able to fix. Every time

**Comment by gbraad** [comment]
What I thought, a race condition as it caches the contents of the file inside the forked process. It should only open the write at the moment it actually starts writing the new values.

**Comment by gbraad** [comment]
If not in our scope, at least report upstream.

**Comment by LalatenduMohanty** [comment]
Looks like upstream needs to fix it in their code.  +1 for opening an upstream issue. However I was wondering the way we create a child process for exporting the images after `minishift start` if it has a loop hole too.

**Comment by praveenkumar** [comment]
There is no hope hole in the backend process we do. I am not even sure what to file on the upstream for this, we are consuming that a module and for a single process it works as expected, the problem only happen when you run 2 processes and both read the `index.json` at its initial state but once it finished both write back to it. Whichever process finish later will overwrite again that index.json file.

containers/image codebase can't append to that index.json but actually, before the start, it sees if index.json exist then get an object after unmarshaling and once the pull complete add new image object back to it and marshal + write, which is expected and done this way only.

**Comment by gbraad** [comment]
Upstream they should check for the file. Unmarshal to verify contents, but
they should do this again after completion, with an exclusive write lock.
Else this will happen even between two processes that use this structure
(this is not isolated to our use).

**Comment by LalatenduMohanty** [comment]
@praveenkumar @gbraad I agree that the index.json should have a write lock and it should be done from upstream or Minishift. Upstream might deny that they do not have this issue and in that can we fix that in Minishift?

**Comment by LalatenduMohanty** [comment]
Upstream (containers/image) issue https://github.com/containers/image/issues/513
