### ISSUE TITLE
Protocol-less proxies are accepted by the command line parser but are not used

### ISSUE THREAD

**Issue by svenstaro** [minishift/minishift#2475]
### General information

  * Minishift version: 1.19.0
  * OS: Linux
  * Hypervisor: VirtualBox

### Steps to reproduce

    HTTP_PROXY=1.1.1.1 ./minishift start --vm-driver virtualbox

### Expected

Should use the proxy and output

    -- Using proxy for the setup

### Actual

Doesn't use the proxy and doesn't output

    -- Using proxy for the setup

It works when you provide the proxy like 

    HTTP_PROXY=http://1.1.1.1 ./minishift start --vm-driver virtualbox

I can post a full log but I don't think it's necessary as this appears to be a parsing error of some kind. Same thing happens with --http-proxy and respective HTTPS versions.

I believe that 1.1.1.1 should be parsed as http://1.1.1.1 or alternatively throw an error. It should not silently fail, however.

**Comment by LalatenduMohanty** [comment]
Interesting , I thought it would work because `NewProxyConfig` called in `handleProxies()` in start.go handles this. But it seems to be not working. 

```code
// NewProxyConfig creates a proxy configuration with the specified parameters. If a empty string is passed
// the corresponding environment variable is checked.
func NewProxyConfig(httpProxy string, httpsProxy string, noProxy string) (*ProxyConfig, error) {
	if httpProxy == "" {
		httpProxy = os.Getenv("http_proxy")
		if httpProxy == "" {
			httpProxy = os.Getenv("HTTP_PROXY")
		}
	}
	err := ValidateProxyURL(httpProxy)
	if err != nil {
		return nil, err
	}
	httpProxy = parseProxySpecialChar(httpProxy)

	if httpsProxy == "" {
		httpsProxy = os.Getenv("https_proxy")
		if httpsProxy == "" {
			httpsProxy = os.Getenv("HTTPS_PROXY")
		}
	}
```

**Comment by LalatenduMohanty** [comment]
@svenstaro Can you please check if this is still an issue?

**Comment by svenstaro** [comment]
Still an issue, yes.

Parsing error: `1.1.1.1:8080`
Silent ignore: `1.1.1.1`

**Comment by gbraad** [comment]
The validation would need to be refactored to a single implementation. I do think the scheme is needed to avoid confusion with a possible SOCKS option. @minishift/minishift-dev WDYT?

**Comment by gbraad** [comment]
The problem is with `parseProxySpecialChar`, which uses a wrong `sheme` when none is given.

**Comment by gbraad** [comment]
Found an issue with the PR. Will send a patch...

**Comment by gbraad** [comment]
I will create a new issue...
