### ISSUE TITLE
Add the host interface's IP to the noProxy list

### ISSUE THREAD

**Issue by svenstaro** [minishift/minishift#2476]
[Currently, minishift only adds the VM's IP to the noProxy list](https://github.com/minishift/minishift/blob/a039d37ef5e84364a976f3b4b7a07185d202a933/cmd/minishift/cmd/start.go#L205). However, it would also be useful if the machine's host interface IP would be added. We already talked about this on IRC and the minishift team seemed to agree.

**Comment by gbraad** [comment]
You might need:

https://github.com/minishift/minishift/blob/17507025610e89fce899a3fe49d3df5aecbd4d37/pkg/minishift/network/settings.go#L200-L208

**Comment by gbraad** [comment]
Right, there was a single-line implementation for this: https://github.com/minishift/minishift/blob/17507025610e89fce899a3fe49d3df5aecbd4d37/pkg/minishift/hostfolder/cifs_hostfolder.go#L46

**Comment by gbraad** [comment]
OK... been a while since I wrote it.
