### ISSUE TITLE
Update Xpaas image streams and templates for OpenShift 3.11

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2483]
We need to check if we need to update any image streams and templates for OpenShift v3.10.0

**Comment by jorgemoralespou** [comment]
@LalatenduMohanty in 3.10 there is a component that installs rhel-imagestreams instead of  the centos imagestreams. These includes xPaaS, but also changes the scl ones from centos based to rhel based. Maybe worth looking into it or talking with David.

**Comment by praveenkumar** [comment]
@jorgemoralespou That's good to know and if this is the case we can even deprecate this addon, even our addon we have rhel based imagestream.

**Comment by jorgemoralespou** [comment]
@praveenkumar what I meant is that currently, the oc cluster feature also changes the "mongodb, mariadb, perl, python,...." to be RHEL based and not Centos based, so not exactly a fit.

**Comment by LalatenduMohanty** [comment]
@jorgemoralespou  if `oc cluster up` in Origin by default have RHEL based images in image stream we can not do anything about it. We are fine to have RHEL based images as long as they can be downloaded without any subscription. 

> These includes xPaaS, but also changes the scl ones from centos based to rhel based. Maybe worth looking into it or talking with David.

+1 we will check.

**Comment by jorgemoralespou** [comment]
@LalatenduMohanty it's not by default. If you enable rhel-imagestreams then they will be installed instead of the centos. And just verified it's only for the SCL imagestreams and not xPaaS, so the addon is still required.
