### ISSUE TITLE
Unexpected output of command "minishift image list --vm" on minishift running on the remote host

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2484]
### General information

  * Minishift version: master
  * OS: Linux (Red Hat Enterprise Linux Server release 7.5 (Maipo))
  * Hypervisor: generic

### Steps to reproduce

  1. Start a remote machine (RHEL Server) with all these [configurations](https://github.com/minishift/minishift/blob/master/docs/source/using/experimental-features.adoc#run-against-an-existing-machine)
  2. start minishift from the host machine
```
$ export MINISHIFT_ENABLE_EXPERIMENTAL=y
$ ./minishift start --vm-driver generic --remote-ipaddress <ip address of the remote machine> --remote-ssh-user root --remote-ssh-key ~/.ssh/id_rsa
```
  3. export alpine image after successful m start and all the three default images are exported successfully
```
./minishift image export alpine:latest
```
  4. check image list 
```
$ ./minishift image list
alpine:latest
openshift/origin-docker-registry:v3.9.0
openshift/origin-haproxy-router:v3.9.0
openshift/origin:v3.9.0
```
  5. Do minishift delete followed by start
```
$ ./minishift delete --force
$ ./minishift start --vm-driver generic --remote-ipaddress 10.70.45.10 --remote-ssh-user root --remote-ssh-key ~/.ssh/id_rsa
```
  6. Then check available images in the Docker daemon
```
$ ./minishift image list --vm
<none>:<none>
docker.io/alpine:latest
docker.io/openshift/origin-deployer:v3.9.0
docker.io/openshift/origin-docker-registry:<none>
docker.io/openshift/origin-docker-registry:v3.9.0
docker.io/openshift/origin-haproxy-router:<none>
docker.io/openshift/origin-haproxy-router:v3.9.0
docker.io/openshift/origin-pod:v3.9.0
docker.io/openshift/origin-web-console:v3.9.0
docker.io/openshift/origin:<none>
docker.io/openshift/origin:v3.9.0
```

### Expected
$ ./minishift image list --vm
docker.io/openshift/origin-deployer:v3.9.0
docker.io/openshift/origin-docker-registry:v3.9.0
docker.io/openshift/origin-haproxy-router:v3.9.0
docker.io/openshift/origin-pod:v3.9.0
docker.io/openshift/origin-web-console:v3.9.0
docker.io/openshift/origin:v3.9.0

### Actual
Mentioned as above. Also, I wonder how image ```alpine:latest``` is auto-imported. 

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@amitkrout As we discussed over bjn, we can close this if you are ok with the output now.

**Comment by amitkrout** [comment]
@praveenkumar Usecae took much longer time than expected due to bad bandwidth, sorry for the delay. As discussed i cleaned up the the docker images from the remote machine. Now ```minishift image list --vm```  looks fine. 

However observing wired behavior while applying ```minishift image export alpine:latest```. Wondering how image ```alpine:latest``` automatically get imported in the remote host where as i have not executed the ```minishift image import ...``` command.

Steps to reproduce:
1. m start and wait till all the default images are exported
2. minishift image export alpine:latest
3. minishift image list --vm will list out alpine:latest which should not be 
```
$ ./minishift image list --vm
docker.io/openshift/origin-deployer:v3.9.0
docker.io/openshift/origin-docker-registry:v3.9.0
docker.io/openshift/origin-haproxy-router:v3.9.0
docker.io/openshift/origin-pod:v3.9.0
docker.io/openshift/origin-web-console:v3.9.0
docker.io/openshift/origin:v3.9.0
$ ./minishift image export alpine:latest
Exporting 'alpine:latest'.............. OK
$ ./minishift image list --vm
docker.io/alpine:latest
docker.io/openshift/origin-deployer:v3.9.0
docker.io/openshift/origin-docker-registry:v3.9.0
docker.io/openshift/origin-haproxy-router:v3.9.0
docker.io/openshift/origin-pod:v3.9.0
docker.io/openshift/origin-web-console:v3.9.0
docker.io/openshift/origin:v3.9.0
```

**Comment by praveenkumar** [comment]
@amitkrout That's a expected behavior, why you think it shouldn't show alpine image to `vm` list? When you export an image then it always first pull in the VM using docker pull and then only export happens so when you list the images from the `vm` it will be there, This is not generic specific use case but even without a generic driver, you can check that. Once you confirm please close this issue.

**Comment by amitkrout** [comment]
@praveenkumar i spent some time closely to understand the terminology ```export``` and ```import``` w.r.t minishift. I think the assumption I had was wrong. So this is an expected behavior irrespective of driver use. hence closing it.
