### ISSUE TITLE
Fails to download the ISO : Error caching the ISO

### ISSUE THREAD

**Issue by hrishin** [minishift/minishift#2490]
### General information
Sometimes Minishift is not able to download ISO image. It fails in between. It could be nice to resume the download from the last checkpoint upon retrying. 
Also, note that in profile name in log `-- Starting profile 'tutorial'` different from given name `--profile=istio-demo`.  Is it desired behavior? (apologies for mixing two things here)

  * Minishift version: minishift v1.19.0+1750702
  * OS: Linux 
  * Hypervisor: KVM 

### Steps to reproduce

  1.  minishift start

### Logs
```
[hshinde@localhost bin]$ minishift start --profile=istio-demo --vm-driver=kvm --memory=8192 --cpus=3 --disk-size=50g  --openshift-version=v3.9.0
-- Starting profile 'tutorial'
-- Check if depereccated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.9.0'
 42.11 MiB / 42.11 MiB [==============================================================================================================] 100.00% 0s-- Downloading OpenShift v3.9.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    8 GB
   vCPUs :    3
   Disk size: 50 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.10.0/minishift-centos7.iso'
 165.33 MiB / 344.00 MiB [=================================================>------------------------------------------------------]  48.06% 23m43s



Error caching the ISO: read tcp 192.168.0.104:45810->52.216.98.211:443: read: connection reset by peer

```

**Comment by praveenkumar** [comment]
@hrishin At this moment, minishift doesn't resume an incomplete download (we might take a look into it when time permits). Meanwhile you can do following.

```
$ wget -c https://github.com/minishift/minishift-centos-iso/releases/download/v1.10.0/minishift-centos7.iso 
$ mkdir ~/.minishift/cache/iso/centos/v1.10.0/
$ mv minishift-centos7.iso ~/.minishift/cache/iso/centos/v1.10.0/
```
Profile issue will have a look but it would be better to have 2 separate issues.

**Comment by amitkrout** [comment]
@hrishin  I have seen this issue sometimes with oc download and iso download as well. This happens mostly due to some network glitch while I use my home network, however never seen this in the office network. I would say please try the same operation after some time and meanwhile check your network connectivity.

**Comment by hrishin** [comment]
@amitkrout do agree here. I think @praveenkumar has given an alternative for such issues.
I think its good to close now.

Thanks, team.

**Comment by rez20004** [comment]
@hrishin Hello, the solution given, I have tried it but does not work. It keeps trying to download from source i.e github.com
