### ISSUE TITLE
Investigate and use unit test framework

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#250]
Hi,

While writing one of the unit test, I found that the buit-in `testing` package lacks good asserting methods.
I need to use `if` patter to check equality of test data. 
```
	if driver.SSHUser != "docker" {
		t.Fatalf("Expected SSH User : docker")
	}
```
It would have been good if above can be done in one line as:
```
assert(driver.SSHUser, "docker", "Error message")
```

With initial investigation, I found there are few unit test libraries in Golang.
- https://github.com/stretchr/testify ( Easy assertions, Mocking, HTTP response trapping, Testing suite interfaces and functions ) (Github stars - 2500+)
- https://github.com/go-check/check ( Suite-based grouping of tests, Fixtures, assertions) ( Github stars - 250+)

Feel free to investigate more on other options too.

**Comment by praveenkumar** [comment]
For me it just add a one more dependency. Make sure we also have to package it in downstream so in package world it always better to have less dependency. But features it  provide vs adding a new dependency trade off we can have.

**Comment by jimmidyson** [comment]
FYI github.com/stretchr/testify is already packaged up for OpenShift & Kubernetes productised versions.

**Comment by hferentschik** [comment]
What I am looking for in the test framework is also a nice set to handle test suites and things like set up and tear down. I am interested to know how _testify_ compares against _check_ in this case.

**Comment by jimmidyson** [comment]
https://github.com/stretchr/testify#suite-package

**Comment by hferentschik** [comment]
> https://github.com/stretchr/testify#suite-package

Thanks for the pointer

**Comment by praveenkumar** [comment]
So all are we agree on that now or we need some more investigation regarding it?

**Comment by jimmidyson** [comment]
:+1: from me.

**Comment by gbraad** [comment]
@LalatenduMohanty @anjannath Consider this task as a spike. This means that you investigate and describe the conclusion here. But it does not have to result in a working solution (or mergable code) just yet.

**Comment by budhrg** [comment]
@gbraad , I think we have come into agreement here https://github.com/minishift/minishift/issues/250#issuecomment-270896266 that we are using testify

**Comment by gbraad** [comment]
OK... in that case it should still be a spike using testify. I do not expect this will result in a complete solution in the time allocated.

**Comment by LalatenduMohanty** [comment]
I would suggest that @anjannath modify unit tests (using testify) of any command or package first and get it reviewed and then go ahead with changing other unit testing files one by one.

**Comment by budhrg** [comment]
> I would suggest that @anjannath modify unit tests (using testify) of any command or package first

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift/pull/1755
