### ISSUE TITLE
Unable to start minishift with --iso-url flag on RHEL7 machine in OpenStack

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#251]
**Environment informations:**
```
Host HW: 8gb ram, 4 vcpus, 80gb drive
Host OS: Red Hat Enterprise Linux Server release 7.3 (Maipo)
Minishift: v1.0.0-beta.1 
ISO version: minishift-centos-iso v1.0.0-alpha.1
OC: v1.3.1
Docker version: 1.10.3
```
**Problem:**
I am using minishift in RHEL7 machine from OpenStack directly via ssh or from Jenkins job. Minishift seems to work fine, I am able to run start, ssh etc, access OpenShift... But I am unable to start Minishift with --iso-url flag and minishift-centos-iso. Command ends on this:
```
Provisioning OpenShift via '/home/hudson/.minishift/cache/oc/v1.3.1/oc [cluster up]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.3.1 image ... 
   Pulling image openshift/origin:v1.3.1
   Pulled 0/3 layers, 3% complete
   Pulled 1/3 layers, 47% complete
   Pulled 2/3 layers, 70% complete
   Pulled 3/3 layers, 100% complete
   Extracting
FAIL
   Error: error pulling Docker image openshift/origin:v1.3.1
   Caused By:
     Error: failed to register layer: open /mnt/sda1/var/lib/docker/image/devicemapper/layerdb/tmp/layer-889687015/diff: read-only file system
E0105 03:45:41.451978   11042 start.go:232] Error starting 'cluster up':  exit status 1
```
which is only sometimes replaced with this:
```
Error: error pulling Docker image openshift/origin:v1.3.1
   Caused By:
     Error: failed to register layer: devmapper: Error saving transaction metadata: devmapper: Error syncing metadata file /mnt/sda1/var/lib/docker/devicemapper/metadata/.tmp072093795: fsync: input/output error
```
**More findings:**
- This seems not to be directly related to RHEL - tried minishift start --iso-url in RHEL7 workstation on local VM and it went fine.
- This fails both when machine is used  by Jenkins and when used manually via ssh.
- This is not occasional - I've run it at least 20 times on 6 fresh VM machines, no success at all.
- When url to boot2docker iso is used, minishift start ends fine.

**Comment by hferentschik** [comment]
I don't think this issue belongs here. It sounds more like an environmental issue or if it is on our side, it would be most likely belong to https://github.com/minishift/minishift-centos-iso which is the repository containing the code for building the CentOS / RHEL based image. Let's keep this here for now, but we might want to move this as soon as we understand the issue.

**Comment by hferentschik** [comment]
BTW, how much disk space does the Jenkins slave get? I am wondering whether there is a disk space problem? See also https://github.com/docker/docker/issues/7105

**Comment by agajdosi** [comment]
Ok, I was unsure where to put this, so I am for moving if needed.
To answer your question jenkins slave gets normally 80gb, so it should be enough. Now I tried it on 160gb slave with 16gb of ram with same result.

**Comment by agajdosi** [comment]
This is still a thing with minishift v1.0.0-beta.2 and minishift-centos-iso v1.0.0-beta.1.

**Comment by agajdosi** [comment]
Process gets stuck on extracting of OpenShift image, so it looks like this is same issue as I am facing with RHEL host in OpenStack which is problem of badly configured NFS on actual host OS, not problem of Minishift.

**Comment by gbraad** [comment]
The persistent image gets attached to the machine, but can not be configured in the handle-user-data. after inspection, it is concluded that the diskimage did not get created properly. it was not a valid qcow2 image. recreating the file on the local disk worked and made Minishift start.

**Comment by praveenkumar** [comment]
@agajdosi why it worked with b2d that something we need to debug and let you know but creating persistent disk image is not iso dependent but it's driver dependent.

**Comment by praveenkumar** [comment]
After inspecting why b2d worked is it doesn't have restriction on file size and lot of discussion already happen #355 as per this issue it's nfs which is mounted to user path.

```
$ sudo df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                     1.8G    918.0M    883.9M  51% /
tmpfs                  1001.1M    244.0K   1000.8M   0% /dev/shm
cgroup                 1001.1M         0   1001.1M   0% /sys/fs/cgroup
tmpfs                     1.8G    918.0M    883.9M  51% /mnt/sda1/var/lib/docker/aufs
tmpfs                     1.8G    918.0M    883.9M  51% /mnt/var/lib/minishift/openshift.local.volumes
none                      1.8G    918.0M    883.9M  51% /mnt/sda1/var/lib/docker/aufs/mnt/6a5aed1888a1712de7e27e5e8f3d31faa74360399511373461b7f496a3ab1a91
shm                      64.0M         0     64.0M   0% /mnt/sda1/var/lib/docker/containers/ee5f5de5c34aeb32f3bae782b4a1ca68280f0b6a3d6eec287a5b93019eebbe69/shm
tmpfs                  1001.1M     16.0K   1001.1M   0% /mnt/var/lib/minishift/openshift.local.volumes/pods/8c726857-057f-11e7-8cf5-7eedf678a831/volumes/kubernetes.io~secret/registry-token-jwagt
none                      1.8G    918.0M    883.9M  51% /mnt/sda1/var/lib/docker/aufs/mnt/669cd1945de5a581d57e6930c2e3e31ceeb293e60ed8867e15b9406edbd2df3d
shm                      64.0M         0     64.0M   0% /mnt/sda1/var/lib/docker/containers/4f8d9cbe7d99cd357449aa4d4cd3e46d893176a7a681bc465b613d8052a31746/shm
tmpfs                  1001.1M     16.0K   1001.1M   0% /mnt/var/lib/minishift/openshift.local.volumes/pods/8c8e42f2-057f-11e7-8cf5-7eedf678a831/volumes/kubernetes.io~secret/router-token-fo60n
tmpfs                  1001.1M     12.0K   1001.1M   0% /mnt/var/lib/minishift/openshift.local.volumes/pods/8c8e42f2-057f-11e7-8cf5-7eedf678a831/volumes/kubernetes.io~secret/server-certificate
none                      1.8G    918.0M    883.9M  51% /mnt/sda1/var/lib/docker/aufs/mnt/de89e37fca10d33fd2c3dd623b7609b61e792a12cc5c974880482b5f4e4dced5
shm                      64.0M         0     64.0M   0% /mnt/sda1/var/lib/docker/containers/f5b47dad626cb45b21f4623e1a510c516533c989a12d37443739d1ce54404b24/shm
none                      1.8G    918.0M    883.9M  51% /mnt/sda1/var/lib/docker/aufs/mnt/9396c799e33049c3c53252d85110901d4d51e73dd77b5c23ea213bdebce1ba02
none                      1.8G    918.0M    883.9M  51% /mnt/sda1/var/lib/docker/aufs/mnt/a66501daa3ec79a0db6b3b076e8964e95b36b72ce0f581976d10a088830675a1
```

**Comment by gbraad** [comment]
In short; the b2d image does not regard storage limits at all... is becomes
a black hole after exhausting the actual storage.

**Comment by praveenkumar** [comment]
@agajdosi I am closing this issue because now we have known facts around ISO
