### ISSUE TITLE
Disconnect from minishift on fedora

### ISSUE THREAD

**Issue by gadieichhorn** [minishift/minishift#2513]
### General information

  * Minishift version: 3.7.1
  * OS: Linux  Fedora 28

I connected to minishift but now I want to disconnect and return to work on my local docker client/daemon

I dont see docker "default" in my docker-machine ls

is there a minishift command to reset the docker ENV to the defualt?

printenv | grep DOCKER
DOCKER_CERT_PATH=/home/geichhorn/.minishift/certs
DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://192.168.42.106:2376

**Comment by praveenkumar** [comment]
@gadieichhorn below is what you need.

**Comment by gadieichhorn** [comment]
thanks @praveenkumar ... didnt work

[geichhorn@com dcb]$ minishift docker-env -u
unset DOCKER_TLS_VERIFY
unset DOCKER_HOST
unset DOCKER_CERT_PATH
# Run this command to configure your shell:
# eval $(minishift docker-env --unset)
[geichhorn@com dcb]$ eval $(minishift docker-env --unset)

[geichhorn@com dcb]$ docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

[geichhorn@com dcb]$ unset DOCKER_TLS_VERIFY
[geichhorn@com dcb]$ unset DOCKER_HOST
[geichhorn@com dcb]$ unset DOCKER_CERT_PATH
[geichhorn@com dcb]$ docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[geichhorn@com dcb]$ 

any idea?

**Comment by praveenkumar** [comment]
@gadieichhorn I am confuse here are, do you want to connect your system docker daemon (fedora host) or something else :(

For you, fedora host you make sure run the docker service up and running. `systemctl start docker` and then try `sudo docker images`. If you want something else then you need to add the specific environment.

**Comment by gadieichhorn** [comment]
@praveenkumar  I had all this working, once I connected to minishift I cannot go back to my local daemon.

I reinstalled docker so now I have this running, shame tere is no ieasy way to connect to local docker...

**Comment by praveenkumar** [comment]
@gadiechhorn you don't need to reinstall, if you open a different tab in your terminal or a new terminal then your default docker env is set as expected. minishift do correctly what it suppose to do as part of unset.

**Comment by gadieichhorn** [comment]
@praveenkumar will try it next time, I even rebooted and this didnt work.

**Comment by gbraad** [comment]
This sounds like an issue in your own setup. This is unrelated to minishift.
Docker on your local host is/was likely misconfigured or not available,
especially since you needed a re-install.

Minishift runs isolated from your local Docker and we do not modify any
settings for that Docker.

**Comment by gadieichhorn** [comment]
1. I use docker all day long on local or using docker-machine remote builds. Never had any issue like this on Fedora before.
2. When connected to docker machine after I close the terminal my local docker is accessible again.
3. after closing minishift terminal I could not access local docker again.

maybe I am using minishift wrong ? ;)

@gbraad  How would you subggest I connect to minishift after running minishift start in a new terminal?
