### ISSUE TITLE
minishift image export and export all have different behaviour

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2524]
As part of the export individual or multiple images, we should append the registry details as part of the image name.

```
$ ./minishift image list

$ ./minishift image export busybox:latest
Exporting 'busybox:latest'.... OK

$ ./minishift image list
busybox:latest  <= here you will not see registry appended as part of the list

$ ./minishift image delete busybox:latest
Deleting 'busybox:latest' from the local cache. OK

$ ./minishift image export --all
Exporting 'docker.io/busybox:latest'. OK

$ ./minishift image list
docker.io/busybox:latest <= This looks like a correct form of the image.

```

**Comment by gbraad** [comment]
This is actually as expected? This is related to how the image is stored
using tags/alias. What do you expect?

**Comment by praveenkumar** [comment]
> What do you expect?

I would expect that it should have the registry as a prefix even user doesn't define it.

**Comment by gbraad** [comment]
On docker a locally created image does not need to have the registry
address. Why does the image not have any prefix?

Also, what happens on import? Are all aliases/tags preserved?
