### ISSUE TITLE
Cannot connect to service from within the pod hosting the service

### ISSUE THREAD

**Issue by guattang** [minishift/minishift#2528]
### General information

  * Minishift version: 1.20.0 (openshift v3.9.0+71543b2-33)
  * OS: Linux (Ubuntu 18.04)
  * Hypervisor: KVM

Note: this is the same issue as #2400, however this issue was closed without the root cause being fixed.

### Steps to reproduce

  1. Deploy any application (eg. nginx with the sample git repository).
  2. Start a terminal in the pod hosting this application.
  3. Attempt to connect to the application locally, using the assigned hostname and service port (eg. `curl -v --head nginx:8080`).

### Expected

Application service should be reachable (it is on OpenShift Online, and in Origin).

### Actual

Service is not reachable.

### Logs

Within the local pod:

```
$ curl -v --head nginx-ex:8080
* About to connect() to nginx-ex port 8080 (#0)
*   Trying 172.30.129.165...
* Connection timed out
* Failed connect to nginx-ex:8080; Connection timed out
* Closing connection 0
curl: (7) Failed connect to nginx-ex:8080; Connection timed out
```

From any other pod:

```
$ curl -v --head nginx-ex:8080
* About to connect() to nginx-ex port 8080 (#0)
*   Trying 172.30.129.165...
* Connected to nginx-ex (172.30.129.165) port 8080 (#0)
> HEAD / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: nginx-ex:8080
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Server: nginx/1.12.1
Server: nginx/1.12.1
< Date: Fri, 29 Jun 2018 09:33:14 GMT
Date: Fri, 29 Jun 2018 09:33:14 GMT
< Content-Type: text/html
Content-Type: text/html
< Content-Length: 37451
Content-Length: 37451
< Last-Modified: Fri, 29 Jun 2018 09:10:02 GMT
Last-Modified: Fri, 29 Jun 2018 09:10:02 GMT
< Connection: keep-alive
Connection: keep-alive
< ETag: "5b35f76a-924b"
ETag: "5b35f76a-924b"
< Accept-Ranges: bytes
Accept-Ranges: bytes

<
* Connection #0 to host nginx-ex left intact
```

**Comment by guattang** [comment]
By 'local pod' I meant the pod running the service to which I am trying to connect to. So, in this case I started a terminal to the Nginx pod and then attempted a curl to the nginx service - which times out (but works from all other pods).

**Comment by gbraad** [comment]
How are you curling the pod? using localhost or the IP assigned to the pod?

**Comment by praveenkumar** [comment]
>  why was this #2400 closed?

Closed by the reporter, we didn't do it.

**Comment by gbraad** [comment]
I reopened; as this needs to be described or resolved.
Mark this one as a duplicate?

**Comment by guattang** [comment]
I close this issue as #2400 is now reopened.

**Comment by gbraad** [comment]
@guattang please add a comment to that issue

This is a duplicate
