### ISSUE TITLE
Need a way to cache all required images from host 

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2530]
Usecase:

An user running an application and she wants to cache all the required images, so that she doesn't have to download those from internet again. 

At this point this is a spike to see how we can do it.

**Comment by LalatenduMohanty** [comment]
@gbraad we had discussed this long ago, please add your comments.

**Comment by jorgemoralespou** [comment]
I think this is needed, as I sometimes have my images locally on my docker daemon and would like to store them in the minishift cache.Sadly I can't use skopeo as I'm on mac.

**Comment by praveenkumar** [comment]
> An user running an application and she wants to cache all the required images, so that she doesn't have to download those from internet again.

@LalatenduMohanty This running application is in the minishift or in the local docker daemon? because it if is in minishift then the user need to do export before stop/delete the VM or if it is local docker daemon then this is a different game.

**Comment by jorgemoralespou** [comment]
@praveenkumar, this is to populate the cache before you start minishift so image can be retrieved from cache and not from network.

**Comment by praveenkumar** [comment]
> this is to populate the cache before you start minishift so image can be retrieved from cache and not from network.

@jorgemoralespou Right that I understood but my question is populate the cache from local docker daemon or something else?

**Comment by jorgemoralespou** [comment]
Both would be awesome, from local docker demon if available and if not pull
directly to cache. I might not have docker locally.

**Comment by LalatenduMohanty** [comment]
@praveenkumar @jorgemoralespou  Here is the workflow I was thinking

1.  Caching images from the Minsihift VM with respect to a running application. For example I am running two applications in Minishift, but I want to save images for one application so that I do not have to download those again next time I do `minishift delete; minishift start`. 

However we should address the usecase @jorgemoralespou mentioned. Ability to cache to Minishift' cache from host's docker daemon which can be run in Minishift.

**Comment by jorgemoralespou** [comment]
@LalatenduMohanty don't understand. Isn't that currently possible with:

```
$ minishift image export my-image
$ minishift image cache-config set my-image
```

That would do what you say. As long as the image(s) is in the VM this is already possible. What would be required is to cache images that are not on the VM, most likely so that first run of the VM will not pull them but have them provided from cache. So what we would need to do new is to "populate the cache" before a profile/VM is run.

**Comment by LalatenduMohanty** [comment]
> That would do what you say. As long as the image(s) is in the VM this is already possible.

IMO that process is cumbersome when you have few images for one or multiple application and I was suggesting that we automate the process for multiple images at one go. Interesting to know that you do not think it is an issue till now.  So if you do not see the need for this now, we can drop the use case. 


> So what we would need to do new is to "populate the cache" before a profile/VM is run.

Sure.

**Comment by praveenkumar** [comment]
> That would do what you say. As long as the image(s) is in the VM this is already possible. 

Right, that's the reason I asked what different implementation we need to do.

>  So what we would need to do new is to "populate the cache" before a profile/VM is run.

@jorgemoralespou To do that we have to use local docker daemon or any other tool which can cache the images before even VM run. That is something completely different from what we have currently.

**Comment by jorgemoralespou** [comment]
I thought that was what was asked in this issue.
With skopeo you can do this as long as we're using one of the supported
storage options, but since skopeo is general purpose and minishift use
cases are limited and we don't really use skopeo but containers/storage
lib, we should do this from within the tool.
