### ISSUE TITLE
Improve speed of caching during export and import

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#2532]
This is a feature request asking for:

- Improve startup time of a VM when images are cached (import)
- Improve time to export images into a cache

I have recently done some tests on my local laptop I get similar performance pulling the 3 images minishift pre-pulls from the internet (200MB Internet connection) than when copying them from the cache on the local filesystem, which is about 4:20 minutes.

When I set to export an image to the local file system, every image takes a long time to be saved on the cache. Also, the images, even if they share layers or is the same image with different tags are saved as different images in the cache. We should improve how the images are stored so we can reuse layers, improving disk space and exporting/importing times.

We can involve @runcom to help us understand what are the best ways to do this currently. This feature was implemented a year ago and the limitations back then can potentially have been removed, or other strategies for storing images might exist.

**Comment by praveenkumar** [comment]
@jorgemoralespou Import always considers layers so I am hoping that is quite fast once the base images are present, the issue with export as of now or you think even import is also misbehaving?

**Comment by jorgemoralespou** [comment]
I wouldn't say misbehaving but probably under performing.

**Comment by LalatenduMohanty** [comment]
Resolved via #2564
