### ISSUE TITLE
Message "Pulling the Openshift Container Image . EXISTS" not required when OpenShift image exists

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2537]
### General information
I feel `-- Pulling the Openshift Container Image . EXISTS` is not required in the console output when the image already exists. 

### Steps to reproduce

  1.  $ minishift start

### Expected

```
$ minishift start
xxxx
   Importing 'openshift/origin:v3.9.0' .......... OK
   Importing 'openshift/origin-docker-registry:v3.9.0' .. OK
   Importing 'openshift/origin-haproxy-router:v3.9.0' .. OK
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
-- Copying oc binary from the OpenShift container image to VM .... OK
```

### Actual
```
$ minishift start
xxxxx
   Importing 'openshift/origin:v3.9.0' .......... OK
   Importing 'openshift/origin-docker-registry:v3.9.0' .. OK
   Importing 'openshift/origin-haproxy-router:v3.9.0' .. OK
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
-- Pulling the Openshift Container Image . EXISTS
-- Copying oc binary from the OpenShift container image to VM .... OK
```

**Comment by praveenkumar** [comment]
@LalatenduMohanty That was specifically what @gbraad asked when I put the PR so I am not sure removing it now make sense?

**Comment by gbraad** [comment]
Why not? This is debug information...

So, in a sense you want to remove the message, but when I do not use image-caching, I would still need a form of debug to determine the right thing happened ... else the following statement (copy) will fail, which brings us back to the original issue.
