### ISSUE TITLE
When generic driver is used, minishift should start the docker if it is not running

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2548]
When remote deployment using the generic driver failed, it can get stuck on `sudo docker version`. A simple `sudo systemctl start docker` will resolve this, but is never executed.

**Comment by LalatenduMohanty** [comment]
@gbraad You mean `minishift` should start teh docker daemon if not running.

**Comment by gbraad** [comment]
This can happen easily when you want to deploy on a remote instance of CentOS, but you used `/etc/docker/daemon.json` to specify `insecure-registries`, our provisioner will fail... you fix the issue (by removing the file perhaps), but do not restart Docker.
When you redploy/start minishift again it will continually try to use `sudo docker version`, and fails after about 30 times this command (2+ minutes)
If you would do `systemctl start docker` and do a `minishift start` all is OK

**Comment by praveenkumar** [comment]
@gbraad FYI if you use anything as part of `insecure-registries` to `/etc/docker/daemon.json` and then it is not going to consume it for sure because our current provisioner creates `/etc/systemd/system/docker.service.d/10-machine.conf` which is used for execution.

**Comment by gbraad** [comment]
Note: the config actually conflicts and prevents to start

**Comment by LalatenduMohanty** [comment]
Resolved via #2608
