### ISSUE TITLE
RFE: Add a tail option for minishift logs

### ISSUE THREAD

**Issue by chmouel** [minishift/minishift#2555]
`minishift logs` spew the whole logs when you want to look at them.

If you want to look at only the last lines (and for example follows it) you have to go over the whole shebang.

It would be nice if we have a `tail` option like we have on `oc logs` or `docker logs`

**Comment by LalatenduMohanty** [comment]
@chmouel  Do you mean `minishift logs --follow` ?

**Comment by LalatenduMohanty** [comment]
Got this from oc usage
`--tail=-1: Lines of recent log file to display. Defaults to -1 with no selector, showing all log lines otherwise
10, if a selector is provided.`

**Comment by chmouel** [comment]
Humm hello activity?

**Comment by budhram** [comment]
@chmouel  Can you try `minishift logs -f` ?

**Comment by chmouel** [comment]
This is not the same, -f would show all the logs and then follow (refresh)
them, --tail=N would show only the last N lines withouth showing the other
messages,

**Comment by budhram** [comment]
@chmouel I got you now :)

**Comment by budhram** [comment]
/cc @chmouel Here we go the test binaries https://ci.appveyor.com/project/minishift-bot/minishift/build/3813/artifacts :) 

PR sent! should be there in next version. Thanks for prompt reply. :+1:
