### ISSUE TITLE
Enable CORS by default?

### ISSUE THREAD

**Issue by jstrachan** [minishift/minishift#257]
So fabric8 has always worked great on minikube and minishift. Though the new 1.x minishift using `oc cluster up` now seems to break the login of the fabric8 console.

I think the reason is probably that we no longer enable CORS on the API server?
e.g. we used to enable CORS
https://github.com/minishift/minishift/blob/6b83d570d5f3c4b5f1680dc436f236c018146344/pkg/minikube/cluster/commands.go#L32

this is so that other consoles (on different ports or domains) can then access the API server to then do OAuth logins etc

e.g. right now trying to login in the fabric8 console on the new minishift we get:
```
XMLHttpRequest cannot load https://192.168.64.82:8443/oapi/v1/users/~. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.64.82:32329' is therefore not allowed access. The response had HTTP status code 403.
```

Any chance we can bring back the `--cors-allowed-origins=.*` flag or at least provide some way to pass it in from the CLI when running `minishift start`?

**Comment by jstrachan** [comment]
here's a related issue https://github.com/fabric8io/gofabric8/issues/322

**Comment by hferentschik** [comment]
Sounds reasonable to me. We have a look at it and either enable it per default or provide some flag.

**Comment by jstrachan** [comment]
thanks @hferentschik

**Comment by hferentschik** [comment]
I guess this might relate to issue #177 and a generic mechanism to apply OpenShift config.

**Comment by hferentschik** [comment]
We implemented #276 now and one can now "patch" the master config after the bootstrap. In the case of CORS it would like this:

    $ minishift start 
    $ minishift openshift config set --patch '{"corsAllowedOrigins": [".*"]}'

This allows for applying any patch you want to the master config. Moving forward we are also discussing to maintain certain types of configurations or setups for the user as form of 'configuration bundles' (see issue #177). This way the user can do something along these lines 

    $ minishift openshift bundle --enable fabric8

Whether this is possible with Fabric8 or not, I am not sure. Basically the idea is to let the user provide some file which encapsulates the execution of various oc commands and potentially openshift patch commands. WDYT?

In the context of this issue, I tried to figure out, how I would bootstrap Fabric8 when I already have a running Minishift instance. I did not find anything directly. Is this possible? I would be looking for some sort of templates/scripts to run.

There seems to be gofabric8. It seems to be able to detect a running OpenShift instance and use it, right? However, looking at the code which provisions Fabric8 it seems to be very spread out. Would there be a way to extract the provisioning into some sort of oc/oadm/openshift script or is there really more needed?

**Comment by rawlingsj** [comment]
Yes `gofabric8 deploy` installs fabric8 on minishift, minikube and remote openshift / kubernetes clusters.  Having said that there has also been some work to generate a single YAML file that we can use to:
```
oc apply -f http://central.maven.org/maven2/io/fabric8/platform/packages/fabric8-platform/2.4.24/fabric8-platform-2.4.24-openshift.yml
```
I think there's still some SCC and openshift roles that need to be figured out with this mind.  I think we we're close to this working so perhaps we take another look this week?

BTW @hferentschik the patch feature looks good - myself or someone else will try it out with fabric8.

**Comment by hferentschik** [comment]
>  Having said that there has also been some work to generate a single YAML file that we can use to

+1 that would be awesome. I think this is much more generic and portable.

> I think there's still some SCC and openshift roles that need to be figured out with this mind. I think we we're close to this working so perhaps we take another look this week?

+1 That would be great. With something like this we can also try to set up some tests to make sure that we can provision Fabric8.

> the patch feature looks good - myself or someone else will try it out with fabric8.

Awesome. Try it out and let us know how it goes.

**Comment by jstrachan** [comment]
I think minishift should enable CORS OOTB - as its the only way to deploy additional consoles inside OpenShift with OAuth & we should assume developers may want to deploy other things without manually patching openshift.

Sure operations may disable CORS in production clusters; but developers should be free to install other consoles

**Comment by hferentschik** [comment]
> Sure operations may disable CORS in production clusters; but developers should be free to install other consoles

They are right? They just have enable CORS. I guess there are pro and cons for both sides. It might be initially more convenient for user to have this enabled per default, but then when he takes it into production, he suddenly hits a wall. If it is, however, simple to do (for example one additional command), then it becomes explicit and the user/developer becomes aware of the problem from the start? What's the better approach here? There is a reason why CORS is not enabled from all domains per default right? Is the whole devops thing not also about that the devs learn operations and understand what the requirements are in a production environment? 

I agree, it needs to be easy to enable it and preferably the error should be easy for the user to detect (aka CORS needs to be configured). That does not mean, imo, that it needs to be enabled per default. The same applies for the runas any discussion. It definitely needs to be easy to change this, but I am not convinced it is the best strategy to enable it per default. 

We have been discussing the concept of configuration bundles, in particular the ability to provide custom configuration which gets applied on each start of the VM, for example by adding a certain config bundle file somewhere, or maybe adding it via the command line, eg

    $ minishift openshift config install <file>

One could add customization like CORS or running containers as root into something like this. Once installed, they get applied for each start of the VM. One does not have to think about this anymore. On the other hand, it is still explicit and one has to think about things like security at least once. WDYT?

**Comment by hferentschik** [comment]
@jstrachan Aside of this, does `minishift openshift config set` solve your problem for now? At least you should be able to provision Fabric8 now, right? Whether '{"corsAllowedOrigins": [".*"]}' becomes a default is something which imo we should take some time to decide.

**Comment by jstrachan** [comment]
While fabric8 is still quite broken on the new minishift; if I use the latest release, run `minishift start`; manually enable CORS then login as `system:admin` I can now login with the fabric8-console thanks!

So the reason I want minishift to enable CORS by default is that minishift is a developer tool; it should default to open security wise & for things to run as its focus is for use by developers. Operators setting up real shared clusters will prefer the default to closed by default where nothing is enabled until they choose to open things on a case by case basis. The opposite should be true of developer tools. 

e.g. without CORS enabled you can't deploy any web console on minishift which uses OAuth. Things will just fail - the developer will be confused; will try all kinds of things to try figure out why their browser can't login to the app on their minishift and will tend to give up and walk away from openshift thinking its flaky; hopefully just to minikube but worse to something else entirely.

Its a balancing act; but developers wanna try things out and get things done; not have to spend a few days figuring out how to tweak all the flags inside openshift and to work closely with its RBAC, SCC, RoleBindings just to run some docker image or run a web app.

**Comment by jstrachan** [comment]
BTW if CORS was a trivial thing we could just check for in all apps on the internet; I'd agree we could just go out and patch all apps on the internet to check for CORS, check if they are on minishift and if not tell the user in a nice way "this app won't work right now as you are running on minishift without CORS - please type these commands on the console to fix it...".

The problem is we're talking lots of apps here (e.g. gitlab + gogs + jenkins + nexus + artifactory + apiman + gerrit + farbic8 + sonarqube + fabric8 + grafana + kibana etc - just from the kinds of things I run never mind the rest of the internet) and detecting the presence of CORS or not on the OAuth URLs isn't a trivial thing to patch - along with detecting if you are on minishift. e.g. just detecting you are on minishift is actually pretty much impossible from inside a web app!

So the simple solution for a _developer tool_ is to make things actually work OOTB for developers trying apps on minishift. When they come to run things on real clusters, the operators will by definition been on training courses, read the admin/config guides closely and will know the configuration options and RBAC models in openshift well so will be able to get things configured just so. 

Having things work for developers but not on the curated operations cluster will also help move things forward. "Works on minishift, but not on operations cluster; what is it thats locked down on the operations cluster we need to enable to get it working..." and gives folks a chance to figure out how to move forward. Rather than "hmm, nothing seems to work on minishift, never mind - lemme try the next tech tool in my twitter feed..."

**Comment by jorgemoralespou** [comment]
@hferentschik I agree with @jstrachan in that minishift should provide some developer friendly defaults, and make clear in the documentation what these are and how to disable them, in case the developer want to test things in an scenario closer to their real production. 

The developer should interact with the environment in the most easier way, but we can fall in the trap that then he hands of an application to a clustered installation of openshift and then the application no longer works, where we will hear the common disclaimer of "it works on my minishift".

I think minishift needs to evolve to abstract the developers of the complexities of the openshift platform, providing commands to make development easier. 

So I totally support @jstrachan request.

**Comment by hferentschik** [comment]
@jorgemoralespou, out of interest, then - why do you think that is would be Minishift enabling CORS for all domains and not _cluster up_? Same for running containers as root. Why are they not enabled per default in _cluster up_? Do you think _cluster up_ has a different use case / audience? 

> I think minishift needs to evolve to abstract the developers of the complexities of the openshift platform, providing commands to make development easier.

+1 I agree. I think we can make this very easy in the end. Whether one needs to run one additional command to enable all this explicitly or whether it will be per default enabled (with some clear feedback to the user during bootstrap), that it a different question. However, in both cases it ties into how we are going to implement this whole concept of "configuration bundles". Once we have this, we can see what we do per default and what not. But the core is this "configuration bundle" concept.

**Comment by hferentschik** [comment]
What I did is that I made this issue a feature request. We need to build the foundation for this first. Once we have this we can discuss what and what not should be enabled via this mechanism per default. 

At least one can configure CORS now using the 'config set' command, even though this is a manual extra step for now.

**Comment by jorgemoralespou** [comment]
> Do you think cluster up has a different use case / audience?

Totally. If you see that I haven't pushed all the requirements/features we've implemented in the cluster-wrappers into oc cluster is mainly because openshift engineers identify the tools for different audiences. I'm in the process of writing a blog post to summarize this, but mainly "oc cluster" gets you a raw/default openshift cluster. They struggle with adding some developer friendly capabilities into the tool, so I understand that the goal has to be moved into minishift (and the wrappers as a way for experimentation).

I agree with you bundles is the way to go, but even with that, I agree that there should be a minimum default tweaks to make the cluster usable. E.g. provide some persistence volumes, configure proxies if running in a proxied environment and probably a few more, of which CORS could be one of them. To be honest I've deployed tons of software in OpenShift and never struggled with CORS not allowing me to work. I understand that for fabric8 this is mainly for allowing OAuth integration between apps, and in this case, I agree that maybe the bundle should do the enablement of the feature in the bundle. 

If there's discussion already on how bundles should work, maybe we can move this discussion there and make sure bundles makes us all happy.

**Comment by hferentschik** [comment]
> I'm in the process of writing a blog post to summarize this,


+1 Nice. Maybe there will be something we can use for our docs.


> but mainly "oc cluster" gets you a raw/default openshift cluster. They struggle with adding some developer friendly capabilities into the tool, so I understand that the goal has to be moved into minishift (and the wrappers as a way for experimentation).


Sure. I am all for making life easier. However, it needs to stay transparent as well. Magic black box changes are not helping imo. I think we will be able to strike a pretty good balance here, once we have the required underpinnings. 

> I agree with you bundles is the way to go, but even with that, I agree that there should be a minimum default tweaks to make the cluster usable. 

Ok

> E.g. provide some persistence volumes,

+1 this is a scheduled task

> configure proxies if running in a proxied environment

+1 we have that. Obviously you need to pass the proxy settings, but other than that we will do the rest

> of which CORS could be one of them. To be honest I've deployed tons of software in OpenShift and never struggled with CORS not allowing me to work. 

Same here. I understand CORS is important for Fabric8, but I would not go so far as to call this the default use case. I think many/most apps can be developed without changing the CORS setting.  

> If there's discussion already on how bundles should work, maybe we can move this discussion there and make sure bundles makes us all happy.

Have a look at issue #177

**Comment by hferentschik** [comment]
With #177 implemented, you can now also write your own add-on which will configure CORS as part of the startup. So there are two ways now to achieve what you are after, explicit command line via _minishift openshift patch_ or add-on.

Moving forward, I would be interested in creating an add-on for provisioning Fabric8. Did you guys not start with some sort of OpenShift YAML thingy?

**Comment by hferentschik** [comment]
See also issue #860
