### ISSUE TITLE
Cover more scenario in addon-registry-route.feature file

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2572]
### General information
Split the 5th scenario in addon-registry-route.feature file to avail fixes from both iso and addon side.

  * Minishift version: master
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

 
### Steps to reproduce

  1. ```make integrtion GODOG_OPTS="-tags addons-registry-route"```
  2. 
  3. 
  4. 

### Expected

Split [this scenario](https://github.com/minishift/minishift/blob/master/test/integration/features/addons/addon-registry-route.feature#L46) into two as noted down 
```
//iso side fix
Scenario: As a user, I can login to OpenShift integrated docker registry after restart minishift
    Given Minishift has state "Running"
     When executing "minishift stop" succeeds
     Then executing "minishift start" succeeds
      And Minishift should have state "Running"
     Then with up to "60" retries with wait period of "3" seconds container name "registry_docker-registry" should be "running"
      And with up to "60" retries with wait period of "1" second command "curl -ik https://docker-registry-default.$(minishift ip).nip.io" output should contain "200 OK"
      And executing "docker login -u developer -p `oc whoami -t` docker-registry-default.$(minishift ip).nip.io" in host shell succeeds
      And stdout of host shell should contain "Login Succeeded"
```

```
//addon side fix
Scenario: As a user, I can reapply registry-route addon and login to OpenShift integrated docker registry
    Given Minishift has state "Running"
     When executing "minishift addon apply registry-route" succeeds
     Then with up to "60" retries with wait period of "3" seconds container name "registry_docker-registry" should be "running"
      And with up to "60" retries with wait period of "1" second command "curl -ik https://docker-registry-default.$(minishift ip).nip.io" output should contain "200 OK"
      And executing "docker login -u developer -p `oc whoami -t` docker-registry-default.$(minishift ip).nip.io" in host shell succeeds
      And stdout of host shell should contain "Login Succeeded"
```
### Actual
Only addons side fix is added in the feature file. No scenario for iso side fix
### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by agajdosi** [comment]
Hi @amitkrout, what is the problem here, I have quite hard time understanding the description of the issue.

**Comment by amitkrout** [comment]
@agajdosi Somehow I forgot to mention the issue reference #2545 in the description. The issue was laying between the two fixes i.e form iso and minishift side iirc.  

So the plan was to test the scenario for both side in same file

**Comment by LalatenduMohanty** [comment]
@amitkrout basically you want to cover the steps to reproduce for https://github.com/minishift/minishift/issues/2545#issuecomment-402124814

* $ minishift addon enable registry-route
* $ minishift start 
* $ eval $(minishift docker-env)
* $ eval $(minishift oc-env)
*  $ docker login
*  $ minishift stop
* $ minishift start
* $ docker login

**Comment by amitkrout** [comment]
@LalatenduMohanty yes
