### ISSUE TITLE
Inconsistent use of hostIP

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2574]
SSH hostfolder functionality uses it's own hostIP() function: https://github.com/minishift/minishift/blob/a1927e0329339f0b2b1e085578a19953780bfbbf/pkg/minishift/hostfolder/sshfs_hostfolder.go#L115, while other parts of the code use `DetermineHostIP`

ame probably for console.go using `cluster.GetHostIP`

**Comment by anjannath** [comment]
Still need to be done, Reopening..
