### ISSUE TITLE
Remove minikube iso support completely

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2578]
We added depreciation message for this log time back but didn't removed it completely, we should now remove this ISO and it's usuage completely.

**Comment by tylerauerbeck** [comment]
@praveenkumar So I just did a quick search through the files on minikube*iso*, which returned a number of files. I see a number (and probably some of the harder ones to untangle) lie in pkg/minikube/cluster/cluster.go (and cluster_test.go). With the minikube iso going away, does that actually mean that everything underneath pkg/minikube/* is going away? Or is minikube still used for other components outside of just the ISO?

**Comment by LalatenduMohanty** [comment]
Resolved via #2650 .
