### ISSUE TITLE
Docs issues in "Run against an Existing Machine"

### ISSUE THREAD

**Issue by rkratky** [minishift/minishift#2579]
Minishift docs at https://docs.openshift.org/latest/minishift/using/experimental-features.html#run-against-an-existing-machine

There are a number of language issues in that section:

* running 'against' a machine sounds unnatural; consider 'using a remote instance' or similar
* "To use an existing machine with Minishift , it needs to be configured as follows" -- space before comma
* "CentOS7/RHEL7/Fedora(>26)"
  * don't use slash to separate alternatives
  * put space between OS and version number
  * don't use the 'RHEL' acronym (expand)
* "Lets assume" -- missing apostrophe; consider different wording (why are we using an example IP address but no example username? It looks inconsistent; either there should be `<user>@<IP_address>` or `joesmith@10.1.1.1`)
* "the IP of remote machine which you want to run against Minishift." -- s/which/that/
* "from the host to existing remote machine:" --> "to the existing..."
* "Make sure user have sudo access without password or use root" -- s/have/has/
* "Make sure this login without password" --> "...this login works without a password"
* "You also need to allow 2376, 8443, 80 tcp port" --> "...allow the 2376, 8443, 80 TCP ports" (dtto for UDP ports)
* "Above command provide you subnet like: 172.17.0.0/16" --> "The above command displays a subnet, such as `172.17.0.0/16`."
* "Use the following to run Minishift..." --> "Use the following commands to run Minishift..."

**Comment by LalatenduMohanty** [comment]
@rkratky @robin-owen  Are you planning to fix the issues ?

**Comment by rkratky** [comment]
@LalatenduMohanty I think it's not a priority issue, so I expect @robin-owen to pick this up some time post downstream GA. I just wanted to file it while it was fresh in my mind.

**Comment by robin-owen** [comment]
@LalatenduMohanty @rkratky I'm happy to fix these when I can. Unfortunately, I wasn't aware of the PR that got these changes merged into the documentation.

**Comment by LalatenduMohanty** [comment]
@robin-owen somehow missed the review from you. May be you were on vacation that time.  If you fixing it for downstream them you can send the PR with the same changes to the upstream.

**Comment by rkratky** [comment]
> Unfortunately, I wasn't aware of the PR that got these changes merged into the documentation.

@LalatenduMohanty Perhaps we could prevent this from happening in the future if @robin-owen was automatically tagged for a review & approval of PRs that fix 'documentation'-labelled issues? I believe he has proved his expertise in the docs area by now.

**Comment by LalatenduMohanty** [comment]
@rkratky We do not have a bot to assign people for PR review. But yes, auto assignment would be great.

**Comment by rkratky** [comment]
@LalatenduMohanty You can enable automatic requiring of PR reviews from specific people by:

* Creating a `CODEOWNERS` file: https://help.github.com/articles/about-codeowners/ (make @robin-owen  the owner of the contents of the `docs/source/` directory)
* Configuring 'master' as a protected branch: https://help.github.com/articles/configuring-protected-branches/
* Enabling required reviews for pull requests: https://help.github.com/articles/enabling-required-reviews-for-pull-requests/

**Comment by praveenkumar** [comment]
resolved by #2584
