### ISSUE TITLE
Error during 'cluster up' execution: Error starting the cluster.

### ISSUE THREAD

**Issue by dischello** [minishift/minishift#2580]
### General information

  * Minishift version: minishift v1.17.0+f974f0c
  * OS: Windows 10
  * Hypervisor: VirtualBox 5.2.12 r122591 (Qt5.6.2)

### Steps to reproduce

  1. ./minishift.exe start --profile ${HOSTNAME} --vm-driver virtualbox --iso-url centos -v6 --public-hostname ${HOSTNAME}.kyiv.epam.com --routing-suffix ${LAN_IP}.nip.io --show-libmachine-logs -v 5

### Expected
Ability to get access to minishift UI from external machine in the same LAN.

### Actual
Cluster does not started up.

### Logs
-- Login to server ... FAIL
   Error: dial tcp [fe80::24ce:779d:ebb2:c7c7%VirtualBox Host-Only Network #2]:8443: connectex: No connection could be made because the target machine actively refused it.
Error during 'cluster up' execution: Error starting the cluster.

Full log trace: https://gist.github.com/dischello/fd1b2ac67958bdc0a43f685fab32c660

**Comment by gbraad** [comment]
Not sure why the startup would fail, but might be related to the setup as I see IPv6 being used. Currently this is not supported.

Also, accessing the machine from the same network is not possible without additional changes. This is related to how the virtual networking stack is setup. See #1287.

**Comment by dischello** [comment]
@gbraad 
>Is this reproducible? Or did this happen once?
Yes, also i managed to setup minishift correctly(got access to minishift UI from external machine in the same LAN.) for once, but after recreating minisgift vm this issue occur. @gbraad

**Comment by gbraad** [comment]
Can you explain more about the used network setup (also you mention an external machine accesses the web console), and about other programs on the machine, like vpn or firewall tools

**Comment by dischello** [comment]
@gbraad 
Yeah sure.
My workstation connected to corporate network. Every machine in this network have access to each other(There is no restricting for inboud or outbound traffic). 
Also on my machine installed symantec endpoint protection, there is no VPN configured.
