### ISSUE TITLE
proxy.feature integration test shows false positives

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2588]
### General information

  * Minishift version: minishift v1.20.0+1bd6d5c
  * OS: Linux / macOS / Windows
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. make integration MINISHIFT_BINARY=```<path to minishift binary>``` RUN_BEFORE_FEATURE="config set vm-driver virtualbox" GODOG_OPTS="-tags proxy"
  2. 
  3. 
  4. 

### Expected
Should fail on virualbox driver

### Actual
Passing

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by amitkrout** [comment]
Seems fix of #2587 will resolve this issue

**Comment by gbraad** [comment]
@amitkrout I am not sure how this would resolve it...
you mean it is because of the actual proxy does not work as expected?

this is not clear from the issue

**Comment by amitkrout** [comment]
@gbraad TBH i thought (without primary investigation) if actual proxy does not work as expected then there might be a chance in wrong integration test behavior. However later i did a basic investigation and found that the integration test proxy code nowhere related to #2587. Unfortunately i forgot to update here.

In this sprint i am going to take this. Sorry for the inconvenience

**Comment by amitkrout** [comment]
Now it is no more a issue of false positive after the fix of #2587. Got the expected behavior after testing it thoroughly on the affected bits of 3.5 (rc.1 and rc.2) + VirtualBox + Win10. 

So closing the issue.
