### ISSUE TITLE
Add file comparison step into integration testsuite

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2591]
**Proposal**
Step will be able to check whether two files - one local and the second probably online (raw file on GitHub) are the same, for example:

`Then file "<path>" is same as "<url>"`

**Usecase**
With the step we will be then able to use this step at several places:
- in **minishift** to check whether templates in xpaas addon are up to date with templates at respective branch (currently 3.9) at https://github.com/openshift/openshift-ansible/tree/release-3.9/roles/openshift_examples/files/examples/v3.9/xpaas-templates
- in **minishift-addons** to check whether eap-cd addon files are up to date with files at https://github.com/jboss-container-images/jboss-eap-7-openshift-image/tree/eap-cd/templates
- in **CDK** to check whether che addon is in sync with che addon at minishift-addons repository
- in **CDK** to check whether xpaas addon is in sync with xpaas addon in minishift repo (we can find much more cases I think)

**Optional**
As xpaas contains huge amount of files, upgraded step which could iterate over files at directory and compare with their online counterparts would be also handy, something like:

```
Then all files in directory "<path-to-directory>" are the same as files at location "<url>"
Then all files in directory ".minishift/addons/xpaas/xpaas-templates/" are the same as their respective counterparts at location "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.9/roles/openshift_examples/files/examples/v3.9/xpaas-templates/"
```

Note that the URL `https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.9/roles/openshift_examples/files/examples/v3.9/xpaas-templates/` does not exist, the step would however add respective file name to the end, which exists.

**Comment by amitkrout** [comment]
I think this will increase the code integration test code maintenance overhead. I am good with the suggestion made by @praveenkumar  that any addons which are part of default cdk should be in minishift repo instead of the community so that these can be validated through nightly cc_ @minishift/minishift-dev

**Comment by agajdosi** [comment]
Will be resolved in separate project.
