### ISSUE TITLE
Correctly deal with defaultScheme for proxy validation check

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2594]
The current check assumes https is required for https-proxy, which is not the case as it is merely the method of the proxy for communication.

**Comment by LalatenduMohanty** [comment]
@gbraad you are right, missed that in the review.

**Comment by gbraad** [comment]
Bad mistake from my side... was sure the previous check was OK, but still
changed it. Shouldn't do this without feedback. Anyway, I would say this is
very important... justify a new release?

**Comment by praveenkumar** [comment]
We all make mistake.

@gbraad so this only affect if a user doesn't use the scheme when defining the proxy right, and this is something we recently added. If you think a lot of users don't use scheme then I am all in for a minor release (1.21.1).

**Comment by gbraad** [comment]
It does not pass the validation on startup if you had set it before or use
the environment variables.
