### ISSUE TITLE
oc login -u system:admin password? 

### ISSUE THREAD

**Issue by philips** [minishift/minishift#2601]
### General information

  * Minishift version: minishift v1.21.0+a8c8b37
  * OS: macOS
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. `minishift start --vm-driver virtualbox`
  2. See start message with login instructions. 

```
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.100:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin
```
 
  3.  `oc login -u system:admin` with a random password returns `error: username system:admin is invalid for basic auth - verify you have provided the correct host and port and that the server is currently running. error: username system:admin is invalid for basic auth`

  4. Done

### Expected

Login

### Actual

Not logged in.

### Logs

https://gist.github.com/philips/11dba1f75c7ee24c3f2ca3d19968d136

**Comment by praveenkumar** [comment]
@philips for user `system:admin` you don't need any password.

It should work as below.

```
$ oc login -u system:admin
```

**Comment by budhram** [comment]
@philips I hope you @praveenkumar helped you to resolve your query. Let us know if you still face any issue.

Please feel free to close the issue. :smile:

**Comment by philips** [comment]
I am getting this:

```
$     oc login -u system:admin
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

Authentication required for https://192.168.99.100:8443 (openshift)
Username: system:admin
Password:
error: username system:admin is invalid for basic auth
```

**Comment by philips** [comment]
Hrm, I started and stopped minishift and got this:

```
-- Starting OpenShift cluster ......
Deleted existing OpenShift container
Using nsenter mounter for OpenShift volumes
Using public hostname IP 192.168.99.100 as the host IP
Using 192.168.99.100 as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.100:8443


error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: Unable to login to cluster
```

**Comment by philips** [comment]
Weird... I tried to delete and start again and got:

```
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.100:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin


Error during post cluster up configuration: unable to view kubeconfig file
```

**Comment by philips** [comment]
Ok, I dug through the code and found the error. Why is the oc command trying to open cert files... it shouldn't matter

```
$ oc config view --flatten
error: open /Users/philips/.kube/aws/apiserver.crt: no such file or directory
```

Fixed this by doing

```
touch /Users/philips/.kube/aws/apiserver.crt
```

I would strongly argue we shouldn't be doing `--flatten` as the code does. https://github.com/minishift/minishift/blob/781349690090db8711a30d0f5fd3d84accc27732/pkg/minishift/oc/oc.go#L115 

We should drop that flag, right? Like we shouldn't rewrite people's kubeconfigs if they have external file certs, right?

**Comment by gbraad** [comment]
good question... @praveenkumar @jorgemoralespou WDYT?

**Comment by jorgemoralespou** [comment]
@gbraad AFAIK, system:admin is not a user but a service account, so it has no password but a token. What oc cluster do is get the token and write it in kubeconfig for so you can directly access.
What your asking is probably a better question for @liggitt.

Remember that I oppose to how we (origin) manage the kubeconfig for entirely.
https://github.com/openshift/origin/issues/18645

**Comment by philips** [comment]
@jorgemoralespou I think my issue with system:admin is entirely because minishift failed to setup my kubeconfig. I just hadn't noticed the error before on `minishift start` of `Error during post cluster up configuration: unable to view kubeconfig file`

**Comment by budhram** [comment]
> I think my issue with system:admin is entirely because minishift failed to setup my kubeconfig. I just hadn't noticed the error before on minishift start of Error during post cluster up configuration: unable to view kubeconfig file

Yes @philips  mostly, it is related to kubeconfig file. We haven't able to get such error at our end (macOS) till yet.

We would like to explore more here.

**Comment by gbraad** [comment]
> `error: open /Users/philips/.kube/aws/apiserver.crt: no such file or directory`

this looks like a leftover from a previous run eg. with minikube perhaps? something referenced this file ...

**Comment by jorgemoralespou** [comment]
@philips, I would think that because how we manage the kubeconfig file, and how IPs are reused by minishift you're hitting a race condition where you have information in that kubefile that belonged to a different previous cluster.

I think that in order to prevent this, minishift should provide an option that guarantees you use the profile specific kubeconfig file, like we do for docker-env.

I'm any case, I'm pretty sure the source of the problem comes from what I mentioned, even if in this specific case there's something else.

**Comment by amitkrout** [comment]
> We haven't able to get such error at our end (macOS) till yet.

@budhram Even me either 
```
$ oc login -u system:admin
Logged into "https://192.168.99.100:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-public
    kube-system
  * myproject
    openshift
    openshift-infra
    openshift-node
    openshift-web-console

Using project "myproject".
```

**Comment by gbraad** [comment]
@amitkrout this is related to previous configs inside the .kube config file. this might be due to using multiple runs of minikube and minishift

but as mentioned, we should try to isolate the .kube files used for a profile.

**Comment by praveenkumar** [comment]
> I would strongly argue we shouldn't be doing --flatten as the code does. 

@philips I used this because of that what best way to merge the kube config file as kubernetes documents. We needed to do it to make sure `system:admin` service account set properly with the user `kube` config file without the extra step.

> I think that in order to prevent this, minishift should provide an option that guarantees you use the profile specific kubeconfig file, like we do for docker-env.

@jorgemoralespou we can actually do that easily and when a user does `oc-env` then it also set the kubeconfig file which is minishift specific but then if a user has to do it every time before using any commands.

**Comment by philips** [comment]
@praveenkumar `--flatten` is not necessary and changes how I want to use kubeconfig for my existing clusters by moving my x509 certs from files into the kubeconfig embedded.

See this upstream example of merging using `kubectl config view` which is essentially what minikube does.

https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#set-the-kubeconfig-environment-variable

Instead of shelling out can we just use the code from minikube? https://github.com/kubernetes/minikube/blob/1c06d18e7da2f9e6c4fc62c3e584ca6eebc8fd88/pkg/util/kubeconfig/config.go#L69

**Comment by jorgemoralespou** [comment]
@philips,
Have you used oc?
Can you do:
```
mkdir -p /tmp/.kube
export KUBECONFIG=/TMP/.kube
oc cluster up
oc login  -u user1 -p password
oc new-project test
oc new--project test2
oc cluster down
```

And look into the generated kubeconfig and see if that's what you would expect?

Minishift uses internally OC cluster up and OC command and some context management is fine by this tools

**Comment by praveenkumar** [comment]
> --flatten is not necessary and changes how I want to use kubeconfig for my existing clusters by moving my x509 certs from files into the kubeconfig embedded. See this upstream example of merging using kubectl config view which is essentially what minikube does.

@philips for our case it is required as you go through the codebase you know what we are doing is setting the KUBECONFIG as ~/.kube/config:~/.minishift/machine/minishift_kubeconifg and then after view, we are writing back to the `~/.kube/config` but if we don't use the `--flatten` then the certs will not be part of this :(

> Instead of shelling out can we just use the code from minikube?

We can take a look at this code and see if we directly can consume it.

**Comment by philips** [comment]
_why_ do the certs need to be part of it?

**Comment by LalatenduMohanty** [comment]
> _why_ do the certs need to be part of it?

The challenge is with how  "oc cluster up" generates the config inside the VM and then we need to copy the relevant config to ~/.kube on the host (as  we run "oc cluster up" to provision the OpenShift). We are looking in to this.

**Comment by praveenkumar** [comment]
> As a quick hack run `flatten` over just the minishift config. Then run it a second time with the users config without `flatten`.

@philips it will not solve the issue which we are trying to solve what we want is something like append functionality for kube config file so that we don't modify existing one but add the content of minishift kube config to it. As of now with flatten we merge 2 config file and rewrite the kube config file :( so instead merge we need to append but last time I checked it is something not possible by oc/kubectl command tools so we might to look programmatically like minikube does.

**Comment by gbraad** [comment]
what is the action we should take here?

**Comment by praveenkumar** [comment]
I am still looking how this can be done cleanly. Will update to it soon.

**Comment by praveenkumar** [comment]
@philips hey, if you have some time can you try https://ci.appveyor.com/project/minishift-bot/minishift/build/3749/artifacts artifact now we are not merging the PR but adding it the way minikube suppose to add. Let us know if that still not works for you.

**Comment by LalatenduMohanty** [comment]
Resolved via #2807

**Comment by rosscdh** [comment]
still a problem with 

```
minishift start --openshift-version v3.10.0
ross:oc-projects $ minishift version
minishift v1.26.1+1e20f27
[16:46:00] ross:oc-projects $ oc login -u system:admin
Authentication required for https://192.168.99.100:8443 (openshift)
Username: system:admin
Password:
```

**Comment by jozefizso** [comment]
I have issue with logging in as **system:admin** from a remote client machine (**server1** runs at 10.16.34.230)

```
server1> minishift version
minishift v1.29.0+72fa7b2

client1> oc login -u system:admin
Authentication required for https://10.16.34.230:8443 (openshift)
Username: system:admin
Password:
error: username system:admin is invalid for basic auth
```

`oc config view --flatten` on **client1**
```yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.16.34.230:8443
  name: 10-16-34-230:8443
contexts:
- context:
    cluster: 10-16-34-230:8443
    user: system/10-16-34-230:8443
  name: /10-16-34-230:8443/system
- context:
    cluster: 10-16-34-230:8443
    namespace: dotnet
    user: system/10-16-34-230:8443
  name: dotnet/10-16-34-230:8443/system
- context:
    cluster: 10-16-34-230:8443
    namespace: myproject
    user: developer/10-16-34-230:8443
  name: myproject/10-16-34-230:8443/developer
current-context: myproject/10-16-34-230:8443/developer
kind: Config
preferences: {}
users:
- name: developer/10-16-34-230:8443
  user:
    token: q_lbmS_ZB6BE0Pr2LNFOTsiCugXpz3HK_1ypGNbPqko
- name: system/10-16-34-230:8443
  user:
    token: _t20LtedsbSoO-GDdOB11Q1cEtBTW6YdzBzryHnF-nE
```

**Comment by rkratky** [comment]
This is still a problem. A pre-existing (Minikube) config that contains same logins (`system:admin`, `admin`) screws up the cluster deployment. It is then impossible to log in as `system:admin`, and the **admin-user** add-on doesn't create a user with a `cluster-admin` role.

**Comment by co-de** [comment]
I have installed CentOS7 on VirtualBox on MacOS. I followed all the instructions here: https://github.com/openshift/origin/blob/release-3.11/docs/cluster_up_down.md and oc cluster up successfully runs my cluster. When I try to "oc login -u system:admin" I get this message: **error: username system:admin is invalid for basci auth**.

**Comment by picorealm** [comment]
I am also having the same problem.  After setting up MiniCube and running `minicube start`.  Output from that command stated to log in as administrator use: `oc login -u system:admin`   However I encountered the same exact issue as others above when doing this.
I then ran `minicube stop` and then `minicube start` again and this time the output was: 
`Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to the kube config '/home/foobar/.minishift/machines/minishift_kubeconfig' does not exist`

Prior to all this, I also had to run `minicube start`, `minicube stop`, `minicube start` multiple times to get the setup process to complete successfully, because each successive time it would give and error.  It seems that minicube is too brittle and error-prone at this stage of development.

**Comment by huongdanjavacom** [comment]
It should be "oc login -u system". Then enter the password as admin.

**Comment by walidshaari** [comment]
@huongdanjavacom for minishift your solution will work, but that will work for any user test, test1, mynewuser, and any password, the user in question is not system but system:admin

**Comment by ualter** [comment]
Have you tried this?

`oc login https://192.168.64.4:8443 --token=tZ_l8i9ME7ItWrN6ugLtc4yRyb59kkqRg99VG88mQes`

generated by: https://192.168.64.4:8443/console/command-line

**Comment by abdennour** [comment]
Thank you @walidshaari . 
While `oc login -u system:admin` works, I preferred to maintain the same experience of the real cluster where this user (system:admin) should be used only by **root user** of **master node**.
To comply with this, this is the sequence of commands that i am using:

```sh
minishift ssh
[docker@example ~]$ sudo su -
[root@example ~]# export KUBECONFIG=/var/lib/minishift/base/openshift-apiserver/admin.kubeconfig PATH="$PATH:/var/lib/minishift/bin"
[root@example ~]# oc whoami
[root@example ~]# oc adm policy add-cluster-role-to-user cluster-admin admin
[root@example ~]# exit
[docker@example ~]$ exit
# ......
eval $(minishift oc-env)
oc login -u admin -p admin
oc whoami
# admin
```

For OCP 4.1 and above, CRC is another solution like minishift

**Comment by bsergean** [comment]
```$ ./minishift version
minishift v1.34.2+83ebaab
```

I'm also running into this problem. I have setup minikube on my machine previously.

**Comment by bsergean** [comment]
What worked for me is *oc login -u system*, and then typing *admin* at the prompt for the password.

```
$ oc login -u system https://192.168.64.132:8443     
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

Authentication required for https://192.168.64.132:8443 (openshift)
Username: system
Password: 
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>

```

**Comment by cankush625** [comment]
> What worked for me is _oc login -u system_, and then typing _admin_ at the prompt for the password.
> 
> ```
> $ oc login -u system https://192.168.64.132:8443     
> The server uses a certificate signed by an unknown authority.
> You can bypass the certificate check, but any data you send to the server could be intercepted by others.
> Use insecure connections? (y/n): y
> 
> Authentication required for https://192.168.64.132:8443 (openshift)
> Username: system
> Password: 
> Login successful.
> 
> You don't have any projects. You can try to create a new project, by running
> 
>     oc new-project <projectname>
> ```

This worked fine for me also. Thanks

**Comment by rickydjohn** [comment]
@bsergean that isn't really you logging in as a system:admin user. its just you logging as a random user because minishift does not really authenticate..you can validate this by passing any username and it will show a prompt and the password you pass will be accepted as a valid password as well
