### ISSUE TITLE
Add section to setting-up-virtualization-environment.adoc to start libvirt service

### ISSUE THREAD

**Issue by claudio4j** [minishift/minishift#2606]
I started reading minishift doc on https://github.com/minishift/minishift/blob/master/docs/source/getting-started/setting-up-virtualization-environment.adoc#configure-libvirt-networking

The section to check the libvirt networking, it results in the following error
```
$ sudo virsh net-list --all
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
```
But, after some search, I see the libvirtd service must be running. So I suggest to add to that doc, the user must start the libvirtd service.

**Comment by praveenkumar** [comment]
@LalatenduMohanty if it is resolved then we should close it right?

**Comment by LalatenduMohanty** [comment]
@praveenkumar yes, I forgot to close it.
