### ISSUE TITLE
Update minishift architecture to reflect new changes

### ISSUE THREAD

**Issue by budhram** [minishift/minishift#2610]
The current minishift architecture seems to be quite old.

![minishift_architecture](https://user-images.githubusercontent.com/1132451/42814555-35946732-89e2-11e8-8f8f-eea9f9e0ab54.png)

We have new changes now.
```
...
├── [budhram   4.0K]  iso
│   └── [budhram   4.0K]  centos
│       └── [budhram   4.0K]  v1.12.0
│           └── [budhram   344M]  minishift-centos7.iso
└── [budhram   4.0K]  oc
    └── [budhram   4.0K]  v3.9.0
        └── [budhram   4.0K]  linux
            └── [budhram   208M]  oc
```

**Comment by LalatenduMohanty** [comment]
@budhram As you mentioned we need to mention container images in cache.

**Comment by robin-owen** [comment]
@budhram Personally, I don't think that we should be listing explicit version numbers in the diagram at all. Having the version numbers causes the need to continually update this diagram. I think we need to make it more generic so that the need to update it isn't quite so frequent.

**Comment by praveenkumar** [comment]
Right, we should just use `v3.x.x` instead hard code the complete version, which should be much better. Also regarding the file structure change we can add it with addition of image cache (as lala mentioned).

**Comment by budhram** [comment]
> Right, we should just use v3.x.x

I think the first no can also change later on, so `vX.X.X` ?

**Comment by gbraad** [comment]
what is the use of specifying the version anyway?

**Comment by robin-owen** [comment]
@gbraad Personally, I'm not convinced that it adds any value.

**Comment by gbraad** [comment]
Me neither...

**Comment by robin-owen** [comment]
It's worth noting that #2463 is related to this, as well.
