### ISSUE TITLE
Some integration step definition does not report ssh failure if any

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2617]
### General information

  * Minishift version: master
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

Some integration step definition are prone to ssh failure catch 
### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Expected
Code like https://github.com/minishift/minishift/blob/master/test/integration/util/util.go#L250 and https://github.com/minishift/minishift/blob/master/test/integration/util/util.go#L255 should catch ssh failure if any

### Actual
No ssh error will be reported if it fails due to problem in ssh connection. This misleads the integration test debug process.

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
when no response comes back, or fails, the scenario will conclude something is wrong anyway.
has something happened that this comes up?

**Comment by amitkrout** [comment]
Right, However this is to make the test step error message precise if any failure in case of ssh connection.

> has something happened that this comes up?

This is review comment https://github.com/minishift/minishift/pull/2614#discussion_r203646358  from @agajdosi on #2614.
