### ISSUE TITLE
How to create a SPAN port on the ovs bridge ?

### ISSUE THREAD

**Issue by kripskroll** [minishift/minishift#2620]
### General information

  * Minishift version: 1.21 on CentOS 7
  * OS: Windows 2012 Server
  * VirtualBox : 5.1.28

### Steps to reproduce

  1.  I would like to be able to use OVS SPAN capabilities using ovs-vsctl command and as explained in OVS documentation at http://docs.openvswitch.org/en/latest/faq/configuration/?highlight=promiscuous 

### Expected

Send traffic to a POD with a tcpdump or wireshark container

Thanks

**Comment by gbraad** [comment]
The minishift VM does not come with openvswitch. Although OpenShift SDN is configured using openvswitch, https://docs.openshift.com/enterprise/3.0/architecture/additional_concepts/sdn.html#overview we are running an all-in-one setup (master and node) on one machine. I think it is best to ask #openshift about your needs.

**Comment by budhram** [comment]
Closing as the issue is not related to Minishift.
