### ISSUE TITLE
Minishift date desynced during host standby?

### ISSUE THREAD

**Issue by Antibrumm** [minishift/minishift#2621]
### General information

  * Minishift version: minishift v1.20.0+53c500a / openshift 3.9.0
  * OS: macOS 
  * Hypervisor: xhyve

Hi
I don't know if this relates to minishift only or if this is a general issue on openshift.
It seems that when the host is on standby and minishift is started we will see an increasing amount of time desynchronization.
**The longer the standby the bigger the time difference between host and minishift vm.**

I discovered this first by trying to use Prometheus, which after each standby started to complain about "Browser-Server Time Differences":

_Warning! Detected 75.00 seconds time difference between your browser and the server. Prometheus relies on accurate time and time drift might cause unexpected query results._

### Steps to reproduce

  1. minishift start
  2. exec date on host         -> 08:00 CEST
  3. minishift ssh
  4. exec date in minishift   -> 02:00 EDT
  5. standby machine (f.e. 1h)
  6. exec date on host         -> 09:00 CEST
  7. exec date in minishift    -> 02:00 EDT

### Expected

Time still in sync

### Actual

Time starts to differ 

### Logs
laptop:openshift user$ minishift start
-- Starting profile 'minishift'
...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.3:8443

laptop:openshift user$ date
Mon Jul 23 07:57:31 CEST 2018

laptop:openshift user$ minishift ssh

[docker@minishift ~]$ date
Mon Jul 23 01:57:46 EDT 2018

[docker@minishift ~]$ echo 'Closing laptop for 2-3 min'
Closing laptop for 2-3 min

[docker@minishift ~]$ date
**Mon Jul 23 01:59:17 EDT 2018**

[docker@minishift ~]$ exit
logout

laptop:openshift user$ date
**Mon Jul 23 08:01:27 CEST 2018**

**Comment by gbraad** [comment]
This is a problem caused by the hypervisor. There are workarounds ... like running a NTP query from the VM.

**Comment by gbraad** [comment]
Similar reports are here with xhyve: https://github.com/docker/for-mac/issues/1260#issuecomment-278733016

**Comment by Antibrumm** [comment]
Thanks gbraad for that finding! I was searching in the wrong place and did not think that this has an underlying issue.
