### ISSUE TITLE
Minishift should not use HOMEBREW_GITHUB_API_TOKEN to access api.github.com

### ISSUE THREAD

**Issue by vertexvaar** [minishift/minishift#2625]
### General information

  * Minishift version: minishift v1.21.0+a8c8b37
  * OS: Linux VerteXUbun2 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. Donwload minishift from releases page
  2. copy minshift to ~/.local/bin (which is in $PATH)
  3. run `minishift openshift version list`

### Expected

I expect a list of versions

### Actual

i get
> Error while trying to get list of available Origin versions: GET https://api.github.com/repos/openshift/origin/releases: 401 Bad credentials []

### Logs

```
~$ minishift -v5 openshift version list
-- minishift version: v1.21.0+a8c8b37
Error while trying to get list of available Origin versions: GET https://api.github.com/repos/openshift/origin/releases: 401 Bad credentials []
```
### Info

I can not reproduce this if i encapsulate minishift in a docker container and it works on any other machine. minishift must use some environment variable or other information source from my local machine, which is passed to github as authorization header or something like that. I tried to set GH_TOKEN to a valid token but it didn't change anything (See #3564).
I can successfully curl, wget and open the URL in my Browser with an authorized session and incognito tab.

**Comment by gbraad** [comment]
Please provide

```
minishift config view
minishift openshift version list -v5 --show-libmachine-logs
minishift ssh -- environment
```

**Comment by gbraad** [comment]
> encapsulate minishift in a docker container

Not sure what you mean with this ...

**Comment by vertexvaar** [comment]
```
~$ minishift config view
~$ minishift openshift version list -v5 --show-libmachine-logs
-- minishift version: v1.21.0+a8c8b37
Error while trying to get list of available Origin versions: GET https://api.github.com/repos/openshift/origin/releases: 401 Bad credentials []
~$ minishift ssh -- env
Command failed: Machine 'minishift' does not exist. You need to run 'minishift start' first
```

>> encapsulate minishift in a docker container
> Not sure what you mean with this ...
I created a Dockerfile
```
FROM ubuntu:18.04

ADD minishift /usr/bin/minishift
```
and executed `docker build . -t minishift`, `docker run -it minishift bash` and `minishift -v5 openshift version list` which worked perfectly fine.

**Comment by gbraad** [comment]
Ah, this is the very first test... this seems like a local proxy setting maybe?

```
env
```

and check what is set for `_PROXY` or `_proxy`
?

**Comment by LalatenduMohanty** [comment]
This issue seems very odd as AFAIK `GET https://api.github.com/repos/openshift/origin/releases: 401 Bad credentials` should not need any credentials. I had faced similar issue when I had an invalid GH token https://github.com/minishift/minishift/issues/564

**Comment by LalatenduMohanty** [comment]
@vertexvaar can you give us the out put of `env` command.

**Comment by vertexvaar** [comment]
Here you go. (Token values are censored)

```
CLUTTER_IM_MODULE=xim
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LC_MEASUREMENT=de_DE.UTF-8
LESSCLOSE=/usr/bin/lesspipe %s %s
LC_PAPER=de_DE.UTF-8
LC_MONETARY=de_DE.UTF-8
XDG_MENU_PREFIX=gnome-
LANG=en_US.UTF-8
DISPLAY=:0
GNOME_SHELL_SESSION_MODE=ubuntu
EDITOR=/bin/nano
GPG_TTY=/dev/pts/3
COLORTERM=truecolor
DESKTOP_AUTOSTART_ID=1043b46a518828b1ff153216850527011900000037500007
USERNAME=oeglseder
JAVA_HOME=/usr/lib/jvm/java-8-oracle
J2SDKDIR=/usr/lib/jvm/java-8-oracle
XDG_VTNR=2
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
LC_NAME=de_DE.UTF-8
XDG_SESSION_ID=3
DERBY_HOME=/usr/lib/jvm/java-8-oracle/db
USER=oeglseder
DESKTOP_SESSION=ubuntu
QT4_IM_MODULE=xim
TEXTDOMAINDIR=/usr/share/locale/
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/320d5e40_d900_4c88_878a_1cd8d47238ec
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
PWD=/home/oeglseder
HOME=/home/oeglseder
TEXTDOMAIN=im-config
J2REDIR=/usr/lib/jvm/java-8-oracle/jre
SSH_AGENT_PID=3841
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop
TYPO3_CONTEXT=Development/Local
XDG_SESSION_DESKTOP=ubuntu
LC_ADDRESS=de_DE.UTF-8
LC_NUMERIC=de_DE.UTF-8
GTK_MODULES=gail:atk-bridge
WINDOWPATH=2
TERM=xterm-256color
VTE_VERSION=5202
SHELL=/bin/bash
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
IM_CONFIG_PHASE=2
XDG_CURRENT_DESKTOP=ubuntu:GNOME
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GNOME_TERMINAL_SERVICE=:1.6221
SHLVL=1
XDG_SEAT=seat0
LC_TELEPHONE=de_DE.UTF-8
GDMSESSION=ubuntu
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=oeglseder
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
GH_TOKEN=[censored]
XAUTHORITY=/run/user/1000/gdm/Xauthority
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
PATH=/home/oeglseder/.config/composer/vendor/bin:/home/oeglseder/.local/bin:/home/oeglseder/.config/composer/vendor/bin:/home/oeglseder/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
LC_IDENTIFICATION=de_DE.UTF-8
SESSION_MANAGER=local/VerteXUbun2:@/tmp/.ICE-unix/3750,unix/VerteXUbun2:/tmp/.ICE-unix/3750
HOMEBREW_GITHUB_API_TOKEN=[censored]
LESSOPEN=| /usr/bin/lesspipe %s
GTK_IM_MODULE=ibus
LC_TIME=de_DE.UTF-8
_=/usr/bin/env

```

**Comment by LalatenduMohanty** [comment]
@vertexvaar can you remove the `GH_TOKEN` from the env variables and try `minishift start` again?

```
$ unset GH_TOKEN 
```

**Comment by gbraad** [comment]
the same goes for the `HOMEBREW_` one, as in the github.go file we do: 

https://github.com/minishift/minishift/blob/dfccef22f5e6abcaae9b6b842486c3b4fee8945e/pkg/util/github/github.go#L82

**Comment by vertexvaar** [comment]
After `unset`ing the `HOMEBREW_GITHUB_API_TOKEN` it works, seems that this token was outdated (i don't use linuxbrew anymore).
Thank you for your guidance.
I'd never guess minishift uses a Homebrew specific env variable,  this feels really odd to be honest :sweat_smile:

**Comment by gbraad** [comment]
> this feels really odd to be honest

and for this reason I would like to reopen this. It would be better to remove this from the code...

**Comment by cboggs** [comment]
For what it's worth, this happens even without an Github token env vars set at all. When working from my main office, given the number of people hitting Github at any given time, we hit the rate limit frequently.

I can't reliably use minishift, as it relies on an external list of valid OpenShift versions, and it would appear that those calls to Github's API don't take into account the MINISHIFT_GITHUB_API_TOKEN env var. With that var set to a valid token, and with that var removed entirely, `minishift openshift version list` fails exactly as described in the original issue description.

**Comment by gbraad** [comment]
The variable needs to be set in an environment where many people share the
same IP address. Github else denies service. Not sure what you meant that
even setting MINISHIFT_ fails? If so, make sure the value is correct. Even
for our own CI this is necessary, wo it gets tested on a continuous basis.
Can you provide more details about your setup?

**Comment by gbraad** [comment]
@cboggs can you file an issue for this? Let's investigate ...

**Comment by LalatenduMohanty** [comment]
@cboggs You can disable the startup checks if these creating problem for you https://docs.openshift.org/latest/minishift/troubleshooting/troubleshooting-getting-started.html#minshift-startup-check-failed

**Comment by cboggs** [comment]
@gbraad, my apologies for being unclear, I'll open a new issue and will explain it better there. :-)

@LalatenduMohanty I'll give that a shot, though based on that doc it didn't seem that the OS version check was one of those to be skipped by that flag. Thanks for the pointer and I'll see what it does for me. :-)
