### ISSUE TITLE
minishift image export docker.io/openshift/jenkins-2-centos7:<none>

### ISSUE THREAD

**Issue by burrsutter** [minishift/minishift#2630]
### General information

  * Minishift version: minishift v1.21.0+a8c8b37
  * OS: MacOS
  * Hypervisor: VirtualBox

### Steps to reproduce

  1.  minishift image export docker.io/openshift/jenkins-2-centos7:\<none\>

### Expected
that it would export the image

### Actual
-bash: syntax error near unexpected token `newline'
it dislikes <none>, it should just handle that more gracefully

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by LalatenduMohanty** [comment]
@burrsutter  Are you suggesting that Minishift should ignore the last `:` character and you are seeing the below error
 
```
$ minishift image export docker.io/openshift/jenkins-2-centos7:
[docker.io/openshift/jenkins-2-centos7:] contains an invalid image names:
Error parsing image name 'docker.io/openshift/jenkins-2-centos7:': invalid reference format
```

After I remove the `:` everything works fine. 

```
$ minishift image export docker.io/openshift/jenkins-2-centos7
Exporting 'docker.io/openshift/jenkins-2-centos7:latest'.......................................... OK
```

**Comment by gbraad** [comment]
Did you type the name including the redirect symbols `<none>` as suggested
see in the title? If so, this gets interprete by the shell and we can't do
much about it.

**Comment by LalatenduMohanty** [comment]
> minishift image export docker.io/openshift/jenkins-2-centos7:\<none\>

Fixed @burrsutter 's description where \<none\> was not visible

**Comment by gbraad** [comment]
how about specifying as:

minishift image export "docker.io/openshift/jenkins-2-centos7:<none>"


On Wed, Jul 25, 2018 at 12:28 PM, Lalatendu Mohanty
<notifications@github.com> wrote:
> I could reproduce @burrsutter 's issue. However I think it is a non issue
> because the docker image name: tag format is universal and we should not
> provide extra formats.
>
> @minishift/minishift-dev @burrsutter I am inclined to close this issue as
> not a bug.
>
> $ minishift image export docker.io/openshift/jenkins-2-centos7:<none>
> -bash: syntax error near unexpected token `newline'
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by gbraad** [comment]
how about specifying as:
```
minishift image export "docker.io/openshift/jenkins-2-centos7:<none>"
```

**Comment by gbraad** [comment]
This would result in:
```
$ minishift image export "docker.io/openshift/jenkins-2-centos7:<none>"
[docker.io/openshift/jenkins-2-centos7:<none>] contains an invalid image names:
Error parsing image name 'docker.io/openshift/jenkins-2-centos7:<none>': invalid reference format
```

so, we can close as it is a shell issue and specification without `<none>` works.

```
$  minishift image export "docker.io/openshift/jenkins-2-centos7"                                                         Exporting 'docker.io/openshift/jenkins-2-centos7:latest'......
```
