### ISSUE TITLE
Deprecated env variable HYPERV_VIRTUAL_SWITCH need to be replaced with MINISHIFT_HYPERV_VIRTUAL_SWITCH

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2635]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Expected
We have reference of deprecated env variable  ```HYPERV_VIRTUAL_SWITCH``` in doc [1] of ```Assign IP Address to Hyper-V``` need to be replaced with ```MINISHIFT_HYPERV_VIRTUAL_SWITCH```. Also the flag ```--iso-url centos``` is unnecessary because it is now default iso for minishift.
 
[1] https://github.com/minishift/minishift/blob/master/docs/source/using/static-ip.adoc#assign-ip-address-to-hyper-v

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by amitkrout** [comment]
I think ```Assign IP Address to Hyper-V``` is no more an experimental feature iirc or is it still an experimental feature if I am wrong ? Perhaps something is wrong in the doc. I can see this as experimental features [1] and in the same doc reference its being listed as a full feature [2]

[1] https://docs.openshift.org/latest/minishift/using/experimental-features.html#hyperv-static-ip

[2] https://github.com/minishift/minishift/blob/master/docs/source/using/static-ip.adoc#assign-ip-address-to-hyper-v

cc_ @LalatenduMohanty

**Comment by robin-owen** [comment]
@amitkrout You're right, as far as I know, the ability to set a static IP address for Hyper-V is not an experimental feature anymore.

**Comment by LalatenduMohanty** [comment]
Resolved via #2640
