### ISSUE TITLE
Is it right to list team members in minishift.io page?

### ISSUE THREAD

**Issue by budhram** [minishift/minishift#2637]
Hi, 

I am just wondering whether it is fine to have team members listed as this https://dgplug.org/team/ in our OpenShift page https://www.openshift.org/minishift/ or not.

/cc @gbraad  @praveenkumar  @LalatenduMohanty 

So, people can directly get to know through https://www.openshift.org/minishift/team page who are ones behind Minishift and can get contact us via IRC or social media.

Just a thought.

If we get it then it would be easy to link above team url here https://github.com/praveenkumar/devconf-in.

**Comment by LalatenduMohanty** [comment]
IMO we do not this. The contributors page anyway have information around active contributors.

**Comment by gbraad** [comment]
hard to maintain going forward... it will ALWAYS lag behind the actual contributors list on Github

**Comment by budhram** [comment]
Closing as it is not needed.
