### ISSUE TITLE
Remove CI for b2d and minikube as we are not maintaining

### ISSUE THREAD

**Issue by budhram** [minishift/minishift#2643]
I think its time to completely remove the CI parts related to b2d and minikube ISO as it is creating more confusion than proving useful.

The one which we care about i.e CentOS iso nightly is working fine https://ci.centos.org/job/minishift-nightly-centos/.

**Comment by gbraad** [comment]
right, so please go ahead. the sooner the better

**Comment by LalatenduMohanty** [comment]
Lets check how much downloads we are getting from these ISOs.

**Comment by anjannath** [comment]
@budhram If this is for removing the jobs, then maybe a issue should be created in the https://github.com/minishift/minishift-ci-jobs repo?

**Comment by LalatenduMohanty** [comment]
Today the download numbers for b2d is `4,739` lets see if it changes after couple of week. 

[1] https://www.somsubhra.com/github-release-stats/?username=minishift&repository=minishift-b2d-iso

**Comment by LalatenduMohanty** [comment]
We can remove CI for minikube ISO image for sure as we have removed the code from Minishift.

**Comment by LalatenduMohanty** [comment]
I checked the download numbers again and it is 4,936

**Comment by LalatenduMohanty** [comment]
200 downloads in 3 weeks  is very less compared to CentOS ISO (as CentOS downloads numbers are around 10K in the same time frame). I think we are pretty good to remove the remove the CI for B2D.

**Comment by gbraad** [comment]
> 4936

Total, or last month?
Compared to?

But no matter what, we have decided to move ahead and deprecate B2d.

**Comment by gbraad** [comment]
Please move ahead ;-)

**Comment by LalatenduMohanty** [comment]
> But no matter what, we have decided to move ahead and deprecate B2d. 

Right, I was wanted to validate that users have moved away from B2D too.

**Comment by praveenkumar** [comment]
As per @budhram this is done so I am closing this issue now. This was for the nightly test.
