### ISSUE TITLE
Move htpasswd-identity-provider add-on to Minishift repository

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2647]
Move htpasswd-identity-provider add-on to Minishift repository because we expect users need to use it with generic driver. 

https://github.com/minishift/minishift-addons/tree/master/add-ons/htpasswd-identity-provider

**Comment by amitkrout** [comment]
@LalatenduMohanty Would you please add some more clarification to this such as why we need this ? What benefit it brings to minishift ?

**Comment by LalatenduMohanty** [comment]
@amitkrout  When generic driver is used for used for machines available through public IPs (example virtual machines in public cloud ) then using minishift to provision OpenShift in it can be a security issue as the user name name password to login to the openshift instance is constant. This add-on will help user to custom create user/password, so going to be useful to the user.

**Comment by budhram** [comment]
Resolved by https://github.com/minishift/minishift/pull/2691
