### ISSUE TITLE
Replace Origin as OKD in Minishift documentation

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2667]
https://blog.openshift.com/okd310release/

**Comment by agajdosi** [comment]
Should Minishift now be Miniokd?

**Comment by budhram** [comment]
> Should Minishift now be Miniokd?

Ha haa :) What about downstream?

**Comment by robin-owen** [comment]
Most of the references to Origin in the documentation are related to image names, file paths, and URLs. There's only one reference explicitly to OpenShift Origin (in **_contributing/writing_docs.adoc_**).

**Comment by LalatenduMohanty** [comment]
> Should Minishift now be Miniokd?

Nope because OpenShift means the same thing as before. As @robin-owen mentioned we should change to OKD where it meant OpenShift Origin.

**Comment by LalatenduMohanty** [comment]
We need to change some log, console messages too. e.g. `cmd/minishift/cmd/openshift/list_versions.go:           atexit.ExitWithMessage(1, fmt.Sprintf("Error while trying to get list of available Origin versions: %s", err.Error()))` should be `cmd/minishift/cmd/openshift/list_versions.go:           atexit.ExitWithMessage(1, fmt.Sprintf("Error while trying to get list of available Origin OKD versions: %s", err.Error()))` 

I will create another issue to do the code related changes.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/2693
