### ISSUE TITLE
docker doesn't start in boot2docker image

### ISSUE THREAD

**Issue by radekvokal** [minishift/minishift#2668]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

minishift v1.22.0+7163416
libvirt + KVM
Fedora release 28 (Twenty Eight)

### Steps to reproduce

  1.  minishift start
  2.  VM fails to start
  3. 

```
   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.12.0/minishift-centos7.iso'
 344.00 MiB / 344.00 MiB [=======================================================================================================================] 100.00% 0s
-- Starting Minishift VM ...................................................... FAIL E0806 09:01:37.832742   15747 start.go:428] Error starting the VM: Error configuring authorization on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
Error starting the VM: Error configuring authorization on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```
4. ssh to boot2docker image
5. docker ps - doesn't work
6.  /etc/init.d/docker start doesn't start
7. docker daemon
```
Error starting daemon: layer does not exist
```

**Comment by amitkrout** [comment]
@radekvokal centos has replaced b2d as default image for minishift. It seems the failure is caused by some old configuration in ```.minishift``` being used by m start. I would suggest first clean the environment, i mean delete ```~\.minishift``` dir then try again.

**Comment by LalatenduMohanty** [comment]
@radekvokal  Are you sure you are running boot2docker ISO because from https://github.com/minishift/minishift/releases/tag/v1.19.0 CentOS has been the default ISO with Minishift.  

Please provide output of `minishift config view ` and the debug logs i.e. you can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs. Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by radekvokal** [comment]
Removing configuration file really helped. Thanks folks!
