### ISSUE TITLE
Default username password does not work in virtual machine login, minishift could not setup OpenShift

### ISSUE THREAD

**Issue by bahadurbaniya** [minishift/minishift#2671]
### General information

  * Minishift version: minishift v1.22.0+7163416
  * OS:  Windows 10 version 1607
  * Hypervisor: Hyper-V 
  * Virtual machine : CentOS LInux 7 (Core) Kernel 3.10.0-862.6.3.el7.x86_64 on an x86_64

**HyperV Virtual switch "hyperv"** 
![hyperv virtual switch](https://user-images.githubusercontent.com/1377938/43752707-9ea7002c-9a45-11e8-8ed2-63fa926b86c3.png)

`minishift start` command and I could run CentOS VM  but I don't know the username and password to log-in.

![centos 7 virtual machine configs](https://user-images.githubusercontent.com/1377938/43752323-e3070a2a-9a43-11e8-9a06-dd982678da01.png)

I could start CentOS vm successfully with the command 'minishift start hyperv-virtual-switch "hyperv"`  however could not see final logs with Openshift URL, oc credentials as displayed in https://docs.okd.io/latest/minishift/getting-started/quickstart.html#starting-minishift .

 

#### Short minishift start log 
Output from `minishift start hyperv-virtual-switch "hyperv"`
https://gist.github.com/bahadurbaniya/9f93ac88eff2ed657e043b76a35eec0b

#### Detailed debug log 
Output from `minishift start --show-libmachine-logs -v5 hyperv-virtual-switch "hyperv"`
https://gist.github.com/bahadurbaniya/6e3188122ecf5035296585ed56a0cc88

#### Manual VM start and  login in Hyper-V
  1. Start virtual machine CentOS/RHEL in Hyper-V
  2.  username - developer, password - developer does not work as specified in documentation https://docs.okd.io/latest/minishift/getting-started/quickstart.html#starting-minishift . What is working username and password for centos image. 
  

####  Minishift start
 
1. Run `minishift start hyperv-virtual-switch "hyperv"`
2. Don't see  Openshift URL, oc credentials as displayed in https://docs.okd.io/latest/minishift/getting-started/quickstart.html#starting-minishift  and failure in output (gist logs above)

**Comment by anjannath** [comment]
@bahadurbaniya The credetials you referred to are for logging into the OpenShift console not the CentOS VM, so they won't work.

However looking at the logs, OpenShift should have started properly. To get the openshift console url you can use the command `minishift console --url`.

I would suggest to start clean, first delete any existing VMs you have using `minishift delete -f` then start again using `minishift start --hyperv-virtual-switch hyperv`

**Comment by bahadurbaniya** [comment]
Line from the  `minishift start` log: 

`-- Checking for IP address ... FAIL
   Error determining IP address`

`>minishift console --url`
Cannot access the OpenShift console. Verify that Minishift is running. Error: IP not found

**Comment by bahadurbaniya** [comment]
If I want to see ethernet configs of VM when OpenShift console is not working, VM username and password would  be helpful

**Comment by bahadurbaniya** [comment]
First, second, third `minishift start` failed  with error `-- Checking for IP address ... FAIL Error determining IP address` 

Fourth 'minishift start` gave me ipv6 address to login. 

Fifth which is my last attempt, now I am able to login to OpenShift  with ipv4 address. 

Thanks for helping out.

**Comment by praveenbommali** [comment]
> First, second, third `minishift start` failed with error `-- Checking for IP address ... FAIL Error determining IP address`
> 
> Fourth `minishift start` gave me ipv6 address to login.
> 
> Fifth which is my last attempt, now I am able to login to OpenShift with ipv4 address.
> 
> Thanks for helping out.

Hi ,  
I'm trying installing minishif using Hyper-V, it always  failing to start  at final stage  
. VM created successfully, but log wise i'm not finding any success

**Comment by MisiekBest** [comment]
Looks like the default login and password is just the same as it is on minikube...
login: docker
pass: tcuser

switch to root:
sudo su

hope this will help anyone who is looking for default login and pass to minishift console directly in VM

**Comment by jacobbder** [comment]
What's the password for oc login -u system:admin?

**Comment by mohammedah** [comment]
I configured the the network manually for minishift V 2.6 as I was having issues starting it from the CMD. I could see the IP address but do not know what port number to use for https access. how do I find that out. I tried 8443 to no avail. appreacita your help.

thanks,
Kerim

**Comment by LungeloSikobi** [comment]
> 
> 
> Looks like the default login and password is just the same as it is on minikube...
> login: docker
> pass: tcuser
> 
> switch to root:
> sudo su
> 
> hope this will help anyone who is looking for default login and pass to minishift console directly in VM

Worked for me

**Comment by omkarphadke84** [comment]
> Looks like the default login and password is just the same as it is on minikube...
> login: docker
> pass: tcuser
> 
> switch to root:
> sudo su
> 
> hope this will help anyone who is looking for default login and pass to minishift console directly in VM

thank you so much.

**Comment by DieGit0** [comment]
> Looks like the default login and password is just the same as it is on minikube...
> login: docker
> pass: tcuser
> 
> switch to root:
> sudo su
> 
> hope this will help anyone who is looking for default login and pass to minishift console directly in VM

I was seaching for that and it works to me. Thanks!

**Comment by sureshrajuvetukuri** [comment]
login: docker
pass: tcuser
