### ISSUE TITLE
command "addons list" fails when Minishift home directory is empty

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2673]
### General information

  * Minishift version: master
  * OS: Linux
  * Hypervisor: KVM

### Steps to reproduce

  1. delete Minishift home 
  2. run `minishift addons list`

### Expected

Prints out all installed addons.

### Actual

```
[agajdosi@dhcp-24-156 bin]$ rm -fr ~/.minishift
[agajdosi@dhcp-24-156 bin]$ ./minishift addons list
Error installing default add-ons : Asset che not found
```

**Comment by LalatenduMohanty** [comment]
I can not reproduce this on macOS

```
 $ rm -rf ~/.minishift
 $ $ minishift addon list
- admin-user	 : disabled	P(0)
- anyuid	 : disabled	P(0)
- che		 : disabled	P(0)
- registry-route : disabled	P(0)
- xpaas		 : disabled	P(0)
```

**Comment by anjannath** [comment]
@agajdosi Most probably this is because go-bindata not packing che, try a `make clean` and then `make`.

**Comment by agajdosi** [comment]
@anjannath that fixes it, thanks.
