### ISSUE TITLE
Add pr template for minishift

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2674]
Fix of issue(s): 

How to test:

1.
2.
3.
4.

**Comment by amitkrout** [comment]
As per one of the retro item this is the pr template that me and @agajdosi have agreed upon. @minishift/minishift-dev please provide your valuable feedback

**Comment by LalatenduMohanty** [comment]
Is there a way in github to add a template for PR similar to issue template?

**Comment by amitkrout** [comment]
@LalatenduMohanty [1] is the current template we are using for Issue. Probably we need similar kind of mechanism for pr also.

[1] https://github.com/minishift/minishift/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by agajdosi** [comment]
@LalatenduMohanty @amitkrout Seems it should be possible: https://blog.github.com/2016-02-17-issue-and-pull-request-templates/
