### ISSUE TITLE
Cluster up fails with getsockopt: connection refused ()

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2675]
### General information

  * Minishift version: 1.22
  * OS: RHEL 7.5
  * Hypervisor: KVM

### Steps to reproduce

```
[hudson@agajdosi-test1 ~]$ minishift start
-- Starting profile 'minishift'
[...]
   Version: v3.9.0
-- Pulling the Openshift Container Image ........................................ OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ...........................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/lib/minishift/openshift.local.volumes --host-pv-dir /var/lib/minishift/openshift.local.pv --public-hostname 192.168.42.206 --routing-suffix 192.168.42.206.nip.io
err     : exit status 1
output  : Using nsenter mounter for OpenShift volumes
Using public hostname IP 192.168.42.206 as the host IP
Using 192.168.42.206 as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
FAIL
   Error: timed out waiting for OpenShift container "origin" 
   WARNING: 192.168.42.206:8443 may be blocked by firewall rules
   Details:
     Last 10 lines of "origin" container log:
     E0807 13:04:13.932270    2468 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: Get https://127.0.0.1:8443/api/v1/namespaces/kube-system/configmaps/kube-controller-manager: net/http: TLS handshake timeout
     E0807 13:04:15.511476    2468 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/kubernetes/plugin/cmd/kube-scheduler/app/server.go:594: Failed to list *v1.Pod: Get https://127.0.0.1:8443/api/v1/pods?fieldSelector=spec.schedulerName%3Ddefault-scheduler%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&limit=500&resourceVersion=0: net/http: TLS handshake timeout
     E0807 13:04:15.713451    2468 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1beta1.ReplicaSet: Get https://127.0.0.1:8443/apis/extensions/v1beta1/replicasets?limit=500&resourceVersion=0: net/http: TLS handshake timeout
     E0807 13:04:15.784421    2468 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Node: Get https://127.0.0.1:8443/api/v1/nodes?limit=500&resourceVersion=0: net/http: TLS handshake timeout
     E0807 13:04:15.787247    2468 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1beta1.StatefulSet: Get https://127.0.0.1:8443/apis/apps/v1beta1/statefulsets?limit=500&resourceVersion=0: net/http: TLS handshake timeout
     E0807 13:04:15.793474    2468 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1beta1.PodDisruptionBudget: Get https://127.0.0.1:8443/apis/policy/v1beta1/poddisruptionbudgets?limit=500&resourceVersion=0: net/http: TLS handshake timeout
     E0807 13:04:15.795902    2468 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.PersistentVolume: Get https://127.0.0.1:8443/api/v1/persistentvolumes?limit=500&resourceVersion=0: net/http: TLS handshake timeout
     E0807 13:04:15.798232    2468 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Service: Get https://127.0.0.1:8443/api/v1/services?limit=500&resourceVersion=0: net/http: TLS handshake timeout
     E0807 13:04:15.802930    2468 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.PersistentVolumeClaim: Get https://127.0.0.1:8443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0: net/http: TLS handshake timeout
     E0807 13:04:15.805170    2468 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.ReplicationController: Get https://127.0.0.1:8443/api/v1/replicationcontrollers?limit=500&resourceVersion=0: net/http: TLS handshake timeout


   Solution:
     Ensure that you can access 192.168.42.206:8443 from your machine

```

Any ideas what to try?

### Logs

Full log here: https://gist.github.com/agajdosi/11008377248500a4dd6e9c01607d65f0

**Comment by praveenkumar** [comment]
@agajdosi In the message it says `Error: timed out waiting for OpenShift container "origin" 
   WARNING: 192.168.42.206:8443 may be blocked by firewall rules` this mean you might have check the firewall setting or if you are using the central CI then might be enable that port from the UI.

**Comment by agajdosi** [comment]
@praveenkumar Joke is I am using same image on multiple instances and on some it runs fine, on some it just can't start.

**Comment by agajdosi** [comment]
@praveenkumar Also, if I am not mistaken, this is problem of `oc cluster up` which is called in the VM Minishift creates. So the rules on host should not play a role, is this right?

**Comment by agajdosi** [comment]
When using OKD v3.10, the result has a little bit different look:

```
-- Starting OpenShift cluster ..................................................................................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --public-hostname 192.168.42.18 --routing-suffix 192.168.42.18.nip.io --base-dir /var/lib/minishift/base
err     : exit status 1
output  : Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Pulling image openshift/origin-control-plane:v3.10
Image pull complete
Pulling image openshift/origin-cli:v3.10
Pulled 1/4 layers, 32% complete
Pulled 2/4 layers, 51% complete
Pulled 3/4 layers, 94% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
Pulling image openshift/origin-node:v3.10
Pulled 5/6 layers, 85% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.42.18 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.10 ...
I0809 07:34:08.277022    2024 config.go:42] Running "create-master-config"
I0809 07:34:34.990393    2024 config.go:46] Running "create-node-config"
I0809 07:34:38.233104    2024 flags.go:30] Running "create-kubelet-flags"
I0809 07:34:40.487997    2024 run_kubelet.go:48] Running "start-kubelet"
I0809 07:34:41.401100    2024 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
E0809 07:39:42.208988    2024 run_self_hosted.go:542] API server error: Get https://192.168.42.18:8443/healthz?timeout=32s: dial tcp 192.168.42.18:8443: getsockopt: connection refused ()
Error: timed out waiting for the condition
```

**Comment by pjos** [comment]
Running into, what looks like, the same  symptom but with CDK 3.5.0-1. 

- CDK v3.5.0-1 (minishift v1.20.0+1bd6d5c)
- OS Windows 10 (1709)
- Hypervisor: Hyper-V

```
About to run SSH command:
/var/lib/minishift/bin/oc cluster up --public-hostname 192.168.10.10 --routing-suffix apps.local.domain.com --base-dir /var/lib/minishift/base
................................................................SSH cmd err, output: exit status 1: Getting a Docker client ...
Checking if image registry.access.redhat.com/openshift3/ose-control-plane:v3.10 is available ...
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.10.10 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image registry.access.redhat.com/openshift3/ose-control-plane:v3.10 is available ...
Starting OpenShift using registry.access.redhat.com/openshift3/ose-control-plane:v3.10 ...
I0814 05:53:28.142732    3055 config.go:42] Running "create-master-config"
I0814 05:53:31.467132    3055 config.go:46] Running "create-node-config"
I0814 05:53:32.464421    3055 flags.go:30] Running "create-kubelet-flags"
I0814 05:53:33.282728    3055 run_kubelet.go:48] Running "start-kubelet"
I0814 05:53:33.539952    3055 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
E0814 05:58:33.553325    3055 run_self_hosted.go:542] API server error: Get https://192.168.10.10:8443/healthz?timeout=32s: dial tcp 192.168.10.10:8443: getsock                    opt: connection refused ()
Error: timed out waiting for the condition

Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --public-hostname 192.168.10.10 --routing-suffix apps.local.domain.com --base-dir /var/lib/minishift/base
err     : exit status 1
output  : Getting a Docker client ...
Checking if image registry.access.redhat.com/openshift3/ose-control-plane:v3.10 is available ...
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.10.10 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image registry.access.redhat.com/openshift3/ose-control-plane:v3.10 is available ...
Starting OpenShift using registry.access.redhat.com/openshift3/ose-control-plane:v3.10 ...
I0814 05:53:28.142732    3055 config.go:42] Running "create-master-config"
I0814 05:53:31.467132    3055 config.go:46] Running "create-node-config"
I0814 05:53:32.464421    3055 flags.go:30] Running "create-kubelet-flags"
I0814 05:53:33.282728    3055 run_kubelet.go:48] Running "start-kubelet"
I0814 05:53:33.539952    3055 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
E0814 05:58:33.553325    3055 run_self_hosted.go:542] API server error: Get https://192.168.10.10:8443/healthz?timeout=32s: dial tcp 192.168.10.10:8443: getsock                    opt: connection refused ()
Error: timed out waiting for the condition
```

**Comment by amitkrout** [comment]
I am also seeing the same error with similar setup + ```VirtualBox + ocp 3.10.14 + proxy```

```
Checking if image registry.access.redhat.com/openshift3/ose-control-plane:v3.10 is available ...
Starting OpenShift using registry.access.redhat.com/openshift3/ose-control-plane:v3.10 ...
I0803 11:20:14.491381    2222 config.go:42] Running "create-master-config"
I0803 11:20:16.967769    2222 config.go:46] Running "create-node-config"
I0803 11:20:18.048340    2222 flags.go:30] Running "create-kubelet-flags"
I0803 11:20:18.521645    2222 run_kubelet.go:48] Running "start-kubelet"
I0803 11:20:18.685218    2222 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
E0803 11:25:18.688572    2222 run_self_hosted.go:542] API server error: Get https://192.168.64.5:8443/healthz?timeout=32s: dial tcp 192.168.64.5:8443: getsockopt: connection refused ()
Error: timed out waiting for the condition
```

**Comment by pjos** [comment]
@agajdosi. CDK 3.5.0-1 with OCP 3.10.14 fails every time for me on my corporate laptop which is connected behind a corp-proxy, Hyper-V with static IP on the VM.  Our previous configuration running CDK 3.4.0-2 hosting OCP 3.9.14 has been working perfectly. I will have to make some more test with different OCP versions to see if this problem affects only OCP 3.10.14 . 

And here comes the interesting part... on my sandbox laptop, CDK 3.5.0 (OCP 3.10.14) is working perfectly.. without any issues :-o !

**Comment by agajdosi** [comment]
@pjos Does your sandbox laptop work on the same network as your corporate one? I am facing this issue on servers where I can't change network, so if you could try that on different networks, that would be great...

**Comment by pjos** [comment]
@agajdosi, sandbox is located outside the corporate network so it could explain why it works.

**Comment by amitkrout** [comment]
Reproducible on 3.6 alpha.1 darwin bits without proxy, but this is not consistent. After the first failure, in the next 3 consecutive run did not see the issue.

**Comment by praveenkumar** [comment]
@agajdosi @amitkrout  I am in favor to close this issue since in proxied environment v3.10 is the known to us which @pjos experienced. Once that fix on origin side it automatic will be work for us also.

 - https://github.com/openshift/origin/issues/20496

**Comment by agajdosi** [comment]
@praveenkumar Sure, lets close. We can reopen if openshift/origin#20496 does not fix it.

**Comment by amitkrout** [comment]
@praveenkumar Right, However the issue is being reported on both the version of ```v3.9.0``` and ```3.10.0``` without proxy too and being tracked in OKD. https://github.com/openshift/origin/issues/20617

Until and unless this is fixed from okd side we cannot do anything. I am in the favor of closing the issue @agajdosi WDYT ?

**Comment by amitkrout** [comment]
@agajdosi Thanks for closing it :) 
Will track it in OKD

**Comment by agajdosi** [comment]
So the frequency of this issue got higher with v3.10.45 and by that I mean to the point where over half of the start fails with:
```
14:27:04 I0925 10:22:02.539395    2741 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
14:27:04 E0925 10:27:02.544217    2741 run_self_hosted.go:542] API server error: Get https://192.168.99.100:8443/healthz?timeout=32s: dial tcp 192.168.99.100:8443: getsockopt: connection refused ()
14:27:04 Error: timed out waiting for the condition
```
It happens on bare metal nodes in Lab in BLR, also it happens on Central-CI nodes, on all of them any proxy is set as no proxy ever before was needed there. So **this error happens with no proxy set at all**.

**Comment by amitkrout** [comment]
Now i am hitting this issue more frequently on our internal CDK 3.7 release bits

**Comment by LalatenduMohanty** [comment]
@agajdosi @amitkrout can you check failure rate has changed between openshift 3.10 and 3.11.

**Comment by sudhirverma** [comment]
I am also seeing the same error on Win7&Win10+minishift v1.26.1+VirtualBox consistently

**Comment by agajdosi** [comment]
@LalatenduMohanty With 3.11.0 it started to happen even on machines which were not affected by this issues in 3.10.0. There is workaround proposed on the original issue, I need to try that after 3.7.0 testing is done.

**Comment by anjannath** [comment]
@agajdosi Can you please provide link to the work around, i am seeing this in win10+hyperv with latest minishift.

**Comment by agajdosi** [comment]
@anjannath That is great! So slowly the issue affects more and more machines, it started on weak VMs, now it is spreading through laptops, even my 8 core 19gb laptop sees it sometimes. And so the cluster up and Minishift slowly becomes unusable. Luckily the oc team just ignores us, which is great. </sarcasm> 

Workaround is here https://github.com/openshift/origin/issues/20617#issuecomment-433254181, however @amitkrout reported it does not work for him, so probably the only solution right now is to sto using the affected machine and get another one. Sadly.

**Comment by anjannath** [comment]
@agajdosi Thanks i will try the workaround in the issue. Also i saw the issue in a windows VM, not bare metal but it has decent config, 8gb ram and 4 cores.

**Comment by praveenkumar** [comment]
@amitkrout @agajdosi @anjannath  you can test https://github.com/openshift/origin/issues/20617#issuecomment-433254181 using https://github.com/minishift/minishift/pull/2903 on the same environment to see if that workaround working for you. That PR is actually that purpose only where we need to make the change first on the config before cluster start.

**Comment by amitkrout** [comment]
@praveenkumar It was really a nice tip but could not help. I checked with ```initialDelaySeconds: 120``` too hoping bit increase in delay will fix the issue but facing the same error as it was reported earlier. 

No of try - 3

```
I1114 11:59:09.679673    3972 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
E1114 12:04:09.686420    3972 run_self_hosted.go:571] API server error: Get https://192.168.99.102:8443/healthz?timeout=32s: dial tcp 192.168.99.102:8443: connect: connection refused ()
Error: timed out waiting for the condition
```

**Comment by niconiew** [comment]
I'm experiencing similar issue, CDK v3.6.0-1, minishift v1.24.0+aa3dd4c on Windows10/Virtualbox 

ERROR:,
_Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --image 'registry.access.redhat.com/openshift3/ose-${component}:v3.10.45' --public-hostname 192.168.99.101 --routing-suffix 192.168.99.101.nip.io --base-dir /var/lib/minishift/base
err     : exit status 1_

_E1122 05:29:24.669690    2426 run_self_hosted.go:542] API server error: Get https://192.168.99.101:8443/healthz?timeout=32s: dial tcp 192.168.99.101:8443: getsockopt: connection refused ()_

Followed this thread and similar ones, but could not find a solution. 
Any solution to get pass this problem?

**Comment by diasCr** [comment]
I've the same problem.

-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 50 GB

Versions:
minishift v1.31.0+d06603e
CDK v3.8.0-2

-- Starting OpenShift cluster .....................................................................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --routing-suffix 192.168.99.106.nip.io --base-dir /var/lib/minishift/base --image 'registry.access.redhat.com/openshift3/ose-${component}:v3.11.82' --public-hostname 192.168.99.106
err     : exit status 1
output  : Getting a Docker client ...
...
E0615 22:11:13.658769    5200 run_self_hosted.go:571] API server error: Get https://192.168.99.106:8443/healthz?timeout=32s: dial tcp 192.168.99.106:8443: connect: connection refused ()
Error: timed out waiting for the condition

I'm working without a Proxy. Just a simple private network. Could that also be a resource problem maybe? On my Laptop in the same network it's working perfect with the same version.

**Comment by sudheej** [comment]
Still face the issue
```

Starting OpenShift using registry.access.redhat.com/openshift3/ose-control-plane:v3.11.141 ...
I1201 23:56:22.836712    2198 flags.go:30] Running "create-kubelet-flags"
I1201 23:56:23.385778    2198 run_kubelet.go:49] Running "start-kubelet"
I1201 23:56:23.750775    2198 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
E1202 00:01:23.757432    2198 run_self_hosted.go:571] API server error: Get https://192.168.42.177:8443/healthz?timeout=32s: dial tcp 192.168.42.177:8443: connect: connection refused ()
Error: timed out waiting for the condition

```
