### ISSUE TITLE
Enable mutating and validating webhooks by default

### ISSUE THREAD

**Issue by pmorie** [minishift/minishift#2676]
Mutating and validating webhooks are central to the story of extending Kubernetes. We should ensure the experience of evaluating or running Kubernetes extensions that use these features is as painless as possible in minishift.

When getting [Knative](https://github.com/knative) to run with OpenShift, we found this to be the formula to use to get webhooks enabled:

https://github.com/knative/docs/blob/master/install/Knative-with-OpenShift.md#creating-a-new-openshift-cluster

I'd like to re-write the linked instructions to use minishift instead of oc cluster up; in order to do that we need validating and mutating webhooks to be enabled by default.  See also: https://github.com/openshift/origin/issues/20530

**Comment by praveenkumar** [comment]
@pmorie As I can see https://github.com/openshift/origin/issues/20530 is already taken into consideration so once it's part of `oc cluster up`, it will become part of minishift also.

As per documentation, I think you can use `minishift openshift config set --patch` command which will make required changes. 

[0] https://docs.okd.io/latest/minishift/openshift/openshift-client-binary.html#example-config-cors

**Comment by LalatenduMohanty** [comment]
I think this should an add-on and should be enabled by default.

**Comment by LalatenduMohanty** [comment]
We need to test and see if `oc cluster up` in 3.11 has it enabled by default.

**Comment by anjannath** [comment]
@LalatenduMohanty Checked in v3.11 and they are not enabled by default.

**Comment by anjannath** [comment]
Creating an addon for patching the config file is not necessary, as after 3.11 it is not going to change anymore. #3019 directly does the modification after cluster up is run, now these will be enabled by default with minishift.

**Comment by LalatenduMohanty** [comment]
Resolved by #3044
