### ISSUE TITLE
Provide a way to modify the kube-apiserver config same as openshift-apiserver.

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2677]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

With 3.10 now there is now 2 different config one for openshift-apiserver which you can modify with the `minishift config set` command and other one is for kube-apiserver for which we don't have any straightforward way to modify.

We might need to add flag to `openshift config command` which also take `kube-apiserver` changes and then restart the respective container.

**Comment by amitkrout** [comment]
Pasting the exact lines of **Veer Muchandi**

I tried that option. It seems to bring up the ValidationAdmissionWebhook and MutatingAdmissionWebhook per the logs here:

$ oc logs -f master-api-localhost  -n kube-system | more
..
..
I0808 00:18:11.861983       1 plugins.go:149] Loaded 1 admission controller(s) successfully in the following order: MutatingAdmissionWebhook.
I0808 00:18:11.862037       1 plugins.go:149] Loaded 1 admission controller(s) successfully in the following order: ValidatingAdmissionWebhook.

However, the behavior is not same as doing this with “oc cluster up”. The instructions for oc cluster up are here https://github.com/knative/docs/blob/master/install/Knative-with-OpenShift.md
Knative deployments are not going through inspite of these webhooks being active on minishift. Perhaps this has to be tested in parallel with “oc cluster up” to figure out why it works with “oc cluster up” and not with minishift. 

Here is what we have to do to test:
1. Follow instructions here https://github.com/knative/docs/blob/master/install/Knative-with-OpenShift.md and deploy native on minishift
2. Deploy an application this way https://github.com/knative/docs/blob/master/install/getting-started-knative-app.md and test


Also one more question-

Is there an easy way to provide extra-config to minishift like for qinikube
```
minikube start --memory=8192 --cpus=4 \
  --kubernetes-version=v1.10.5 \
  --vm-driver=hyperkit \
  --bootstrapper=kubeadm \
  --extra-config=controller-manager.cluster-signing-cert-file="/var/lib/localkube/certs/ca.crt" \
  --extra-config=controller-manager.cluster-signing-key-file="/var/lib/localkube/certs/ca.key" \
  --extra-config=apiserver.admission-control="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook"
```

**Comment by praveenkumar** [comment]
@amitkrout Thanks for putting it here :100:

**Comment by VeerMuchandi** [comment]
@amitkrout Thanks for posting here. 
@praveenkumar Any next steps for me to figure out?

**Comment by VeerMuchandi** [comment]
@praveenkumar can we expedite this on minishift?

This is holding knative work.

**Comment by literalice** [comment]
How about using a addon?

I've tried to use knative on [the addon](https://github.com/minishift/minishift-addons/pull/158) and It seems to work correctly.
