### ISSUE TITLE
minishift : could not set oc CLI context for 'minishift' profile : path to oc does not exist when stop => start

### ISSUE THREAD

**Issue by cunningt** [minishift/minishift#2679]
### General information

  * Minishift version: minishift v1.22.0+7163416
  * OS: Mac OS X
  * Hypervisor: xhyve

### Steps to reproduce

  1. minishift delete; minishift start

lilguylaptop:~ cunningt$ minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'xhyve' hypervisor ...
-- Starting Minishift VM .................. OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 10% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ...........
Deleted existing OpenShift container
Using nsenter mounter for OpenShift volumes
Using public hostname IP 192.168.64.47 as the host IP
Using 192.168.64.47 as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.47:8443

Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to oc '' does not exist

**Comment by praveenkumar** [comment]
@cunningt Thanks for bug report, @amitkrout can you try it on the Mac OSx and see if that is something reproducible?

**Comment by amitkrout** [comment]
@praveenkumar @cunningt I am unable to reproduce this. Did a fresh start -> delete -> start
```
Amits-MacBook-Pro:minishift-1.22.0-darwin-amd64 amit$ ./minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.9.0'
 40.58 MiB / 40.58 MiB [==============================================================================================================================================] 100.00% 0s-- Downloading OpenShift v3.9.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.12.0/minishift-centos7.iso'
 344.00 MiB / 344.00 MiB [============================================================================================================================================] 100.00% 0s
-- Starting Minishift VM ............... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
   Importing 'openshift/origin:v3.9.0' . CACHE MISS
   Importing 'openshift/origin-docker-registry:v3.9.0'  CACHE MISS
   Importing 'openshift/origin-haproxy-router:v3.9.0'  CACHE MISS
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
-- Pulling the Openshift Container Image ............................ OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ......................
Using nsenter mounter for OpenShift volumes
Using public hostname IP 192.168.64.2 as the host IP
Using 192.168.64.2 as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.2:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin


-- Exporting of OpenShift images is occuring in background process with pid 29787.
```
```
Amits-MacBook-Pro:minishift-1.22.0-darwin-amd64 amit$ ./minishift delete --force
Deleting the Minishift VM...
Minishift VM deleted.
```
```
Amits-MacBook-Pro:minishift-1.22.0-darwin-amd64 amit$ ./minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .................. OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
   Importing 'openshift/origin:v3.9.0' ................. OK
   Importing 'openshift/origin-docker-registry:v3.9.0' ...... OK
   Importing 'openshift/origin-haproxy-router:v3.9.0' ............ OK
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ..................................
Using nsenter mounter for OpenShift volumes
Using public hostname IP 192.168.64.15 as the host IP
Using 192.168.64.15 as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.15:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin


Amits-MacBook-Pro:minishift-1.22.0-darwin-amd64 amit$
```

**Comment by LalatenduMohanty** [comment]
I can not reproduce this too. My guess is something gone wrong in the setup. we need to uninstall Minishift and start fresh.

**Comment by pipinet** [comment]
same error. 
```bash
$minishift start --show-libmachine-logs -v2
-- minishift version: v1.22.0+7163416
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Set the following network settings to VM ... Not supported on this platform or hypervisor
-- Starting Minishift VM ....(minishift) Check network to re-create if needed...
(minishift) Waiting for an IP...
................Waiting for SSH to be available...
.Detecting the provisioner...

   Setting hostname ...
...OK
...Copying certs to the local machine directory...
....Copying certs to the remote machine...
...Setting Docker configuration on the remote daemon...
..
   Feature detection ...
OK
 OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 10% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
-- OpenShift container image exists ...-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster .-- Running 'oc' with: 'cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/lib/minishift/openshift.local.volumes --host-pv-dir /var/lib/minishift/openshift.local.pv --public-hostname 192.168.99.100 --routing-suffix 192.168.99.100.nip.io'
......
Deleted existing OpenShift container
Using nsenter mounter for OpenShift volumes
Using public hostname IP 192.168.99.100 as the host IP
Using 192.168.99.100 as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.100:8443


Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to oc '' does not exist
```

**Comment by pipinet** [comment]
try it will fix this error.
```bash
$ minishift delete --force 
$ rm -rf ~/.minishift/machines/minishift-state.json
$ minishift start
```
because ~/.minishift/machines/minishift-state.json   OcPath is empty.

**Comment by cunningt** [comment]
Running the steps above that @pipinet mentioned fixed it for me as well, although I removed my entire .minishift and started fresh.    

Is there a way to specify the path to oc with minishift config so I wouldn't have to blow away my minishift installation if I ran into this again?

**Comment by praveenkumar** [comment]
@cunningt @pipinet it should automatically create that config file and put the path to that location but looks like something not behaved as expected but if you again hit the same issue then might be you can put what inside ~/.minishift/machine/ directory.

**Comment by cunningt** [comment]
@praveenkumar I'm hitting it repeatedly and have it reproduced currently - what can I put in ~/.minishift/machine/?    Or did you want the contents of something in ~/.minishift/machine for debugging?

**Comment by praveenkumar** [comment]
@cunningt Can you put the content of `ls -al ~/.minishift/machine` and also put conent of whatever present on the `minishift-state.json` or `minishift.json`?

**Comment by cunningt** [comment]
`lilguylaptop:machines cunningt$ pwd
/Users/cunningt/.minishift/machines
lilguylaptop:machines cunningt$ ls -al
total 40
drwxr-xr-x   7 cunningt  staff   224 Aug  8 17:52 .
drwxr-xr-x  12 cunningt  staff   384 Aug  8 17:48 ..
drwx------  10 cunningt  staff   320 Aug 10 10:12 minishift
-rw-r--r--   1 cunningt  staff   258 Aug 10 10:13 minishift-state.json
-rw-r--r--   1 cunningt  staff  5704 Aug  8 17:52 minishift_kubeconfig
-rw-------   1 cunningt  staff  1679 Aug 10 10:12 server-key.pem
-rw-r--r--   1 cunningt  staff  1119 Aug 10 10:12 server.pem`


[minishift-state.json.txt](https://github.com/minishift/minishift/files/2278415/minishift-state.json.txt)

**Comment by praveenkumar** [comment]
@cunningt your oc path is already in `minishift-state.json` which it makes use for CLI context, from our end we are not able to reproduce it. I tried deleting everything and started fresh or even with the profile :(

**Comment by vbusch** [comment]
I have been hitting this issue repeatedly for the last 1/2 a week.

$ minishift start --cpus 2   --insecure-registry=docker-registry.engineering.redhat.com --memory=8192 --openshift-version v3.10.0
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.10.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.10.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM .....r.
.
........... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 54% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.10.0
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster .....................
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.42.184 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.10 ...
I0815 12:27:41.315358    2054 flags.go:30] Running "create-kubelet-flags"
I0815 12:27:41.963415    2054 run_kubelet.go:48] Running "start-kubelet"
I0815 12:27:42.197169    2054 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
I0815 12:27:58.223940    2054 interface.go:26] Installing "kube-proxy" ...
I0815 12:27:58.224445    2054 interface.go:26] Installing "kube-dns" ...
I0815 12:27:58.224454    2054 interface.go:26] Installing "openshift-apiserver" ...
I0815 12:27:58.224487    2054 apply_template.go:83] Installing "openshift-apiserver"
I0815 12:27:58.226182    2054 apply_template.go:83] Installing "kube-proxy"
I0815 12:27:58.227267    2054 apply_template.go:83] Installing "kube-dns"
I0815 12:28:08.017870    2054 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-apiserver"
I0815 12:28:20.147538    2054 run_self_hosted.go:224] openshift-apiserver available
I0815 12:28:20.148010    2054 interface.go:26] Installing "openshift-controller-manager" ...
I0815 12:28:20.148029    2054 apply_template.go:83] Installing "openshift-controller-manager"
I0815 12:28:22.032609    2054 interface.go:41] Finished installing "openshift-controller-manager"
Adding default OAuthClient redirect URIs ...
Adding centos-imagestreams ...
Adding router ...
Adding web-console ...
Adding registry ...
Adding sample-templates ...
Adding persistent-volumes ...
I0815 12:28:22.072039    2054 interface.go:26] Installing "centos-imagestreams" ...
I0815 12:28:22.072048    2054 interface.go:26] Installing "openshift-router" ...
I0815 12:28:22.072057    2054 interface.go:26] Installing "openshift-web-console-operator" ...
I0815 12:28:22.072063    2054 interface.go:26] Installing "openshift-image-registry" ...
I0815 12:28:22.072069    2054 interface.go:26] Installing "sample-templates" ...
I0815 12:28:22.072074    2054 interface.go:26] Installing "persistent-volumes" ...
I0815 12:28:22.072405    2054 apply_list.go:68] Installing "centos-imagestreams"
I0815 12:28:22.072945    2054 apply_template.go:83] Installing "openshift-web-console-operator"
I0815 12:28:22.073394    2054 interface.go:26] Installing "sample-templates/postgresql" ...
I0815 12:28:22.073402    2054 interface.go:26] Installing "sample-templates/dancer quickstart" ...
I0815 12:28:22.073409    2054 interface.go:26] Installing "sample-templates/django quickstart" ...
I0815 12:28:22.073415    2054 interface.go:26] Installing "sample-templates/rails quickstart" ...
I0815 12:28:22.073421    2054 interface.go:26] Installing "sample-templates/jenkins pipeline ephemeral" ...
I0815 12:28:22.073426    2054 interface.go:26] Installing "sample-templates/sample pipeline" ...
I0815 12:28:22.073432    2054 interface.go:26] Installing "sample-templates/mysql" ...
I0815 12:28:22.073437    2054 interface.go:26] Installing "sample-templates/mariadb" ...
I0815 12:28:22.073443    2054 interface.go:26] Installing "sample-templates/cakephp quickstart" ...
I0815 12:28:22.073449    2054 interface.go:26] Installing "sample-templates/nodejs quickstart" ...
I0815 12:28:22.073454    2054 interface.go:26] Installing "sample-templates/mongodb" ...
I0815 12:28:22.073493    2054 apply_list.go:68] Installing "sample-templates/mongodb"
I0815 12:28:22.073655    2054 apply_list.go:68] Installing "sample-templates/postgresql"
I0815 12:28:22.073772    2054 apply_list.go:68] Installing "sample-templates/dancer quickstart"
I0815 12:28:22.073869    2054 apply_list.go:68] Installing "sample-templates/django quickstart"
I0815 12:28:22.073965    2054 apply_list.go:68] Installing "sample-templates/rails quickstart"
I0815 12:28:22.074069    2054 apply_list.go:68] Installing "sample-templates/jenkins pipeline ephemeral"
I0815 12:28:22.074161    2054 apply_list.go:68] Installing "sample-templates/sample pipeline"
I0815 12:28:22.074253    2054 apply_list.go:68] Installing "sample-templates/mysql"
I0815 12:28:22.074342    2054 apply_list.go:68] Installing "sample-templates/mariadb"
I0815 12:28:22.074436    2054 apply_list.go:68] Installing "sample-templates/cakephp quickstart"
I0815 12:28:22.074525    2054 apply_list.go:68] Installing "sample-templates/nodejs quickstart"
I0815 12:28:29.124295    2054 interface.go:41] Finished installing "sample-templates/postgresql" "sample-templates/dancer quickstart" "sample-templates/django quickstart" "sample-templates/rails quickstart" "sample-templates/jenkins pipeline ephemeral" "sample-templates/sample pipeline" "sample-templates/mysql" "sample-templates/mariadb" "sample-templates/cakephp quickstart" "sample-templates/nodejs quickstart" "sample-templates/mongodb"
I0815 12:28:29.848028    2054 interface.go:41] Finished installing "centos-imagestreams" "openshift-router" "openshift-web-console-operator" "openshift-image-registry" "sample-templates" "persistent-volumes"
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.184:8443


Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to oc '' does not exist
-----
$ pwd
/home/vbusch/.minishift/machines
-----
$ ls -l
total 20
drwx-----x. 2 vbusch vbusch  101 Aug 15 12:27 minishift
-rw-r--r--. 1 vbusch vbusch 5699 Aug 13 21:17 minishift_kubeconfig
-rw-r--r--. 1 vbusch vbusch  254 Aug 15 12:27 minishift-state.json
-rw-------. 1 vbusch vbusch 1675 Aug 15 12:27 server-key.pem
-rw-rw-r--. 1 vbusch vbusch 1111 Aug 15 12:27 server.pem
-----
$ more minishift-state.json 
{
	"OcPath": "/home/vbusch/.minishift/cache/oc/v3.10.0/linux/oc",
	"IsRegistered": false,
	"IsRHELBased": true,
	"SupportsNetworkAssignment": true,
	"SupportsDnsmasqServer": true,
	"OpenshiftVersion": "v3.10.0",
	"HostFolders": null,
	"VMDriver": "kvm"
}
-----
$ /home/vbusch/.minishift/cache/oc/v3.10.0/linux/oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
-----
If I 'rm -rf ~/.minishift', and do 'minishift --cpus 2 --insecure-registry=${REGISTRY} --memory=8192 --openshift-version v3.10.0', it will work, until I do 'minishift stop', and/or restart my machine.

**Comment by praveenkumar** [comment]
I can now reproduce this when stop and start minishift.

```
 $ ./minishift start && ./minishift stop && ./minishift start
```

**Comment by amitkrout** [comment]
I am also able reproduce it with the same sequence of ```start -> stop -> strat```

**Comment by paul-snively** [comment]
@praveenkumar @amitkrout Glad you were both able to reproduce it! Please let me know if I can help further diagnoses in any way.

**Comment by praveenkumar** [comment]
@cunningt @paul-snively @vbusch can you folks try the following artifact and let us know if that solves it for you without any workaround.

- http://artifacts.ci.centos.org/minishift/minishift/pr/2704/

**Comment by paul-snively** [comment]
On Darwin, that build resolves this issue for me. I've successfully switched between two profiles, `minishift` and another, both with not specifying the profile to `minishift start` (i.e. defaulting to the last profile) and with `--profile`, all without issues.

Thanks so much!

**Comment by LalatenduMohanty** [comment]
Created #2708

**Comment by AkashSolankle** [comment]
Actually when i am tryping to get switch from one to other account it showing an error as well when i am trying to get pod detail it showing an error oc not found

**Comment by JakesIV** [comment]
I have version 1.27.0 which was recently released and the same error re-occurs. I downloaded the file supplied by praveenkumar and its marked by AVAST antivirus as containing and virus.

**Comment by anjannath** [comment]
Can you try to start minishift on a clean env, (delete ~/.minishift and also ~/.kube/config if you can) that might solve the issue, i am not able to reproduce it in win10, haven't seen this for quite some time now.

@JakesIV AFAICT this is a false alarm, we have seen other reports of anitvirus software reporting as malware/ransomware see #2914. Is the latest minishfit (v1.27.0) is found to be OK by AVAST? Anyway since @praveenkumar commit is already part of master the latest minishift will have those changes.

**Comment by donghwicha** [comment]
@anjannath  to reproduce, you can create a new profile and will be able to see this error.

**Comment by dchucks** [comment]
I am getting the same error while starting minishift:
`Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to the kube config 'C:\Users\me.myself\.minishift\machines\minishift_kubeconfig' does not exist`

although it seems minishift and oc cluster both are up, and I am able to access the console as well. 
```
$ minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Running (openshift v3.11.0+7f5d53b-195)
DiskUsage:  15% of 19G (Mounted On: /mnt/sda1)
CacheUsage: 491.9 MB (used by oc binary, ISO or cached images)
```

Is this error not going to impact anything? I checked that indeed minishift_kubeconfig folder does not exist on the said path.

**Comment by remkohdev** [comment]
```
$ minishift delete --force 
$ rm -rf ~/.minishift/machines/minishift-state.json
```
got me halfway, then I had to downgrade my VirtualBox from v6.0 to v5.2

**Comment by ramkunwarmeghwal** [comment]
copy  `minishift_kubeconfig` (from`  ~/.minishift/machine/minishift_kubeconfig`) file in ` /.minishift`   folder and rename as config
