### ISSUE TITLE
Use PersistentPreRun to stop version, completion commands from creating instance dirs

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#2683]
Right now we are doing a check in `root.go` to stop PersistentPreRun from executing for the two commands, Instead we should use `cobra.Command.PersistentPreRun` to achieve the same.

https://github.com/minishift/minishift/blob/a9f8d156fdb5864fba88baeac98bdce78ac84bf6/cmd/minishift/cmd/root.go#L65-L68
--------------------------------------------------------------------------
https://github.com/minishift/minishift/blob/a9f8d156fdb5864fba88baeac98bdce78ac84bf6/cmd/minishift/cmd/root.go#L81-L85

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/commit/8ca303ac99a28038b2d606d55df3bc5c5d6fbf4f
