### ISSUE TITLE
minishift cannot start on centos in Virtualbox 5.2.16

### ISSUE THREAD

**Issue by ywliow** [minishift/minishift#2686]
### General information

  * Minishift version: 1.22
  * OS: Linux - Centos 7
  * Hypervisor: VirtualBox

### Steps to reproduce

[root@Minishift bin]# ./minishift start --vm-driver=virtualbox
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... FAIL
   See the 'Installing Prerequisites for Minishift' topic (https://docs.openshift.org/latest/minishift/getting-started/installing.html#install-prerequisites) for more information

### Expected
Start minishift

### Actual
-- Checking if VirtualBox is installed ... FAIL

### Logs

N.A

**Comment by praveenkumar** [comment]
@ywliow As per documents `VirtualBox version 5.1.12 or later is required. Ensure that you download and install VirtualBox before using the embedded drivers`, so this should be good. @amitkrout @agajdosi Can you please check this once?

**Comment by agajdosi** [comment]
@ywliow I am not able to reproduce on RHEL7 with minishift 1.22 and VirtualBox 5.2.16. What is your version of VB, is it on PATH?

**Comment by amitkrout** [comment]
@ywliow I am unable to reproduce it. ```minishift start --vm-driver virtualbox`` went fine on ```centos + VirtualBox (5.2.16r123759)```. 

Form the console log i am sure that your VirtualBox installation is not correct. Can you run ```VirtualBox``` in your terminal and check if it reports any error. If yes fix them first else reinstall VirtualBox and try again.

**Comment by ywliow** [comment]
Hi,
OS verion: CentOS Linux release 7.5.1804 (Core)
Minishift path "/usr/local/bin"
Virtualbox: 5.2.16 r123759

I'm able to install Openshift origin 3.9 on the same host and running on different guest/VM. 
Please where to get the error log.
Please advise any setting I need to configure in virtualbox and where to get the error log. Thank you

Regards

**Comment by amitkrout** [comment]
@ywliow I am using the same versions what you mentioned above. 

> I'm able to install Openshift origin 3.9 on the same host and running on different guest/VM.

This is fine because Origin installation does not need any virtualization layer on the host. But Minishift creates a VM and inside the VM ```oc cluster up``` is invoked as part of the installation process.   

> Please where to get the error log.

Use ```--show-libmachine-logs``` with verbose level  5 to get the installation log. For example ```minishift start --vm-driver virtualbox --show-libmachine-logs -v 5```. However this won't help you much here because preflight check starts before libmachine start logging.   

> Please advise any setting I need to configure in virtualbox and where to get the error log.

Follow this link [1]. After step 3 make sure that the dependency like ```kernel-headers``` and ```kernel-devel``` and some dependency packages should be installed. Then continue as instructed in the link
```
$ yum install binutils qt gcc make patch libgomp glibc-headers glibc-devel kernel-headers kernel-devel dkms
```

[1] https://www.if-not-true-then-false.com/2010/install-virtualbox-with-yum-on-fedora-centos-red-hat-rhel/

**Comment by ywliow** [comment]
Hi @praveenkumar @amitkrout @LalatenduMohanty @agajdosi 

Here is my System configuration:
Host OS: MacOS 10.13
Virtualization: Virtualbox 5.2.16
Guest OS: CentOS Linux release 7.5.1804 (Core)

Is the error due to Virtualbox on MacOS 10.13 that does not have virtualbox VM driver?

**Comment by ywliow** [comment]
@amitkrout 
Where you want to start minishift (on host or on guest) ? i think you are trying it on guest right ? if yes can you try it on host OS ?
Minishift on guest OS.

@praveenkumar @amitkrout @LalatenduMohanty @agajdosi
I performed another installation on the following platform;
Host OS: Windows 10
Virtualization: Virtualbox 5.2.16
Guest OS: CentOS Linux release 7.5.1804 (Core)
I get the same error (See below)
How can i check whether vm driver of virtualbox is installed?

[root@Minishift` bin]# ./minishift start --vm-driver virtualbox                  -- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... FAIL
   See the 'Installing Prerequisites for Minishift' topic (https://docs.openshift.org/latest/minishift/getting-started/installing.html#install-prerequisites) for more information

**Comment by amitkrout** [comment]
@ywliow You are doing wrong. I would suggest follow the doc [1] properly. 

However i am writing the steps to run minishift on your MacOS
```
1. Install VirtualBox on your host  - I think you have done this successfully
2. Install the bits Manually or With Homebrew. See [2] for how to do - Also you have done it successfully i guess
2. Then run ```minishift start --vm-driver virtualbox```
```
**NOTE : you don't need a ```CentOS``` guest OS because by default ```minishift starts --vm-driver virtualbox``` download and provision ```CentOS``` iso for you and runs a single node cluster inside the ```CentOS``` VM**   

[1] https://docs.okd.io/latest/minishift/getting-started/preparing-to-install.html
[2] https://docs.okd.io/latest/minishift/getting-started/installing.html

**Comment by ywliow** [comment]
@gbraad @amitkrout 

I managed to install minishift successfully on; 
Host OS: Windows 10
Virtualization: Virtualbox
Guest OS: Pull from Github when run minishift on Window 10  

My initial setup was;
Host OS: Windows 10
Virtualization: Virtualbox
Guest OS: Centos. (I thought of installing minishift in Guest OS. I guest it not supported option)

I will try homebrew for MacOS.

Thank you all.

**Comment by amitkrout** [comment]
> Guest OS: Centos. (I thought of installing minishift in Guest OS. I guess it not supported option)

Still you can run minishift on guest VM running on host those supports nested virtualization like linux, macOS. If you want to use VirtualBox driver inside the guest OS then you need to install VirtualBox again inside the guest OS. See the above comment https://github.com/minishift/minishift/issues/2686#issuecomment-412587771. Then you can run ```minishift start --vm-driver virtualbox``` inside the guest.
