### ISSUE TITLE
Download of large files like ISO and OC should resume

### ISSUE THREAD

**Issue by vorburger** [minishift/minishift#2687]
### General information

  * Minishift version: v1.22.0+7163416
  * OS: Linux
  * Hypervisor: KVM

### Steps to reproduce

due to https://github.com/minishift/minishift-centos-iso/issues/259, I have to run minishift multiple times.

### Expected

In an ideal world, it could perhaps resume download for already partially grabbed OC and ISO binaries.

Safely of course, with some checksum.

### Actual

It tries to re-download the ISO from scratch.

### Logs

Doubt `minishift start --show-libmachine-logs -v5` to collect logs is useful here; let me know if needed.

**Comment by praveenkumar** [comment]
@vorburger Thanks for the bug report but as the workaround I can provide a hack, we will look the resume part. :)

```
$ wget -c https://github.com/minishift/minishift-centos-iso/releases/download/v1.12.0/minishift-centos7.iso
$ mkdir ~/.minishift/cache/iso/centos/v1.12.0/
$ mv minishift-centos7.iso ~/.minishift/cache/iso/centos/v1.12.0/
```

**Comment by vorburger** [comment]
@praveenkumar yeah I figured, that's what I do every time I hit DL issues in minishift.

**Comment by praveenkumar** [comment]
I am planning to use `grab` library but right now it has some issue https://github.com/cavaliercoder/grab/issues/43 . This is something not trivial to implement.

**Comment by braykov** [comment]
Actually, do not download oc if the same verision of the file is already in the folder.
