### ISSUE TITLE
CentOS nightly jobs are failing always post #2582

### ISSUE THREAD

**Issue by budhram** [minishift/minishift#2692]
After doing #2582 , our centos nightly has started to continuously failing, not a single success. See https://ci.centos.org/job/minishift-nightly-centos/.

First job which failed https://ci.centos.org/job/minishift-nightly-centos/234/.

We should try to find why our jobs https://ci.centos.org/job/minishift-nightly-centos/246/console (or similar) are failing. These are failing mostly in `eap-app` deployment with error
```
- StdErr: error: replication controller "eap-app-1" has failed progressing
```

And let's revert #2582  till the app deployment is working.

/cc @minishift/minishift-dev

**Comment by amitkrout** [comment]
@budhram Already we have a pr #2680.

**Comment by budhram** [comment]
Will close only tomorrow once our nightly job starts passing :)

**Comment by LalatenduMohanty** [comment]
@budhram It is a duplicate of https://github.com/minishift/minishift/issues/2644

**Comment by LalatenduMohanty** [comment]
> And let's revert #2582 till the app deployment is working.

We should not revert but should fix the actual issue.

**Comment by budhram** [comment]
@LalatenduMohanty and @amitkrout , looks the #2680 has fixed our nightly job. 
It started passing now. https://ci.centos.org/job/minishift-nightly-centos/247/
I am closing it now.
