### ISSUE TITLE
Che integration tests needs timeouts on individual steps

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2696]
Migrated minishift-addons issue: https://github.com/minishift/minishift-addons/issues/127

> Currently when something goes wrong durring Che tests, the whole testsuite stops at the failing step and waits until whole test run timeouts (2 hours). Instead the steps for creation and starting of workspaces should have its own timeouts (10 minutes) and if that time is exceeded, step should fail and tests continue...

**Comment by amitkrout** [comment]
Failed due to timeout - https://ci.centos.org/job/minishift-nightly-centos/322/console
