### ISSUE TITLE
Addons apply error message does not display the range of OpenShift-Version metadata

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2701]
### General information

  * Minishift version: master
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. Create a addon file ```test-addon.addon``` and put it in ```test-addon``` directory
```
# Name: test-addon
# Description: Demo add-on for checking minimum Minishift version to execute addons.
# Url: https://minishift.io
# OpenShift-Version: >=3.5.0, <3.8.0

echo "Success"
```
  2. Run m start and then apply test-addon
```
$ ./minishift start
$ ./minishift addons apply test-addon
```
  3. Reported error message won't display the range of OpenShift-Version
```
$ ./minishift addons apply test-addon
-- Applying addon 'test-addon':Error applying the add-on: 
Add-on does not support OpenShift version 3.9.0. You need to use a version <3.8.0
```
  4. 

### Expected
$ ./minishift addons apply test-addon
-- Applying addon 'test-addon':Error applying the add-on: 
Add-on does not support OpenShift version 3.9.0. You need to use a version >=3.5.0, <3.8.0

### Actual
No range is displayed

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by amitkrout** [comment]
@praveenkumar Fix of this can go along with pr #2678

**Comment by praveenkumar** [comment]
@amitkrout that I already did, since now it's a separate function so it handle for both minishift and openshift version range. I am closing this issue.

**Comment by amitkrout** [comment]
Cool!!!
Thanks
