### ISSUE TITLE
Remove anyuid Add-on from docs and put a generic example Add-on definition that can show all the add-on features

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#2703]
### General information

  * Minishift version: master
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Expected
A generic add-on definition file that showcases all the add-on commands and meta data that can be
used write a minishift add-on.

/cc @robin-owen

**Comment by anjannath** [comment]
Reopening, this is still to be addressed!

**Comment by robin-owen** [comment]
Reopening once again. I'll get to work on this soon. :)
