### ISSUE TITLE
Some text message is out of frame due to bad indentation in SSHFS documentation

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2707]
### General information

  * Minishift version: master
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. Check - https://docs.okd.io/latest/minishift/using/host-folders.html#sshfs-2
  2. 
  3. 
  4. 

### Expected
``Tip``` message should come inside the frame

### Actual
Currently some part of tip message is out of frame

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@amitkrout that's expected I think because `Tip` also have the Image which take some space and after that only message come. I don't think it out of frame. @robin-owen Can you please confirm and close this issue if that is true.

**Comment by amitkrout** [comment]
<img width="1027" alt="screen shot 2018-08-20 at 12 47 26 pm" src="https://user-images.githubusercontent.com/19851115/44325747-28455380-a449-11e8-8c1e-f8e614af2c7b.png">

cc_ @praveenkumar @robin-owen

**Comment by praveenkumar** [comment]
@amitkrout yes that's what I am saying is expected from my side :)

**Comment by budhram** [comment]
@amitkrout @praveenkumar @robin-owen  Two more options

### First Option 
![screenshot from 2018-08-20 13-41-31](https://user-images.githubusercontent.com/1132451/44328318-e20ae700-a47e-11e8-84a2-31bcbca4015e.png)

### Second Option 
![screenshot from 2018-08-20 13-41-55](https://user-images.githubusercontent.com/1132451/44328322-e6370480-a47e-11e8-8939-33d954b02883.png)

### Keep it as it is

**Comment by LalatenduMohanty** [comment]
I find the current docs acceptable and IMO does not need any change.
![sshfs_minishift](https://user-images.githubusercontent.com/3125299/46458327-07577880-c7d3-11e8-968d-bac32eb21320.png)

**Comment by budhram** [comment]
Closing as per @LalatenduMohanty comment.
