### ISSUE TITLE
Integration test for start->stop->start scenario test

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2708]
We got an issue which was only reproducible only after `minishift start -> stop -> start`. This is an important workflow for users and we need to add an integration test  in basic.feature for this workflow. 

### update

We have https://github.com/minishift/minishift/blob/master/test/integration/features/addon-registry-route.feature#L46-L50 but it is resulting in to a false positive because of #2712 

However the above test only covers restart scenario with registry-route add-on and when it will fail it will give the idea that restart is failing with the add-on , so we need a restart scenario in basic.feature too.

**Comment by LalatenduMohanty** [comment]
Looks like we have https://github.com/minishift/minishift/blob/master/test/integration/features/addon-registry-route.feature#L46-L50 but it is resulting in to a false positive because of #2712

**Comment by amitkrout** [comment]
I think it is no more applicable atm. BTW we are going to cover the scenario somehow in registry-route feature file through thsi pr #2868 and will be executed in each nightly. IMO lets not duplicate the same scenario by putting it in basic feature file. @LalatenduMohanty WDYT ?

**Comment by agajdosi** [comment]
> I think it is no more applicable atm.

@amitkrout I do not agree here. `start-stop-start` procedure is something our users do quite often and we should be pretty sure that it works. Right now we have coverage for this in one feature (if not mistaken) which does not even focus on restart.

What I think we should probably do is to add a specialized feature for `start-stop-start`, named maybe ?`restart.feature`?, which would test scenarios close to the restart - for example we have now flags being saved to config and we might find more.
