### ISSUE TITLE
Increase memory resource from 2GB to 4GB

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2709]
At this moment we have only 2GB memory as default but need to put 4GB to make CI and app developer happy.

**Comment by budhram** [comment]
@praveenkumar I didn't get what 4GB will make CI happy?

**Comment by gbraad** [comment]
Since we use the CentOS iso and have quite a heavy load for testing.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/2702/
