### ISSUE TITLE
Mistake in basic.feature file

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2718]
### General information

Basic.feature contains an undefined step. The step uses time in seconds, however the implementation and matching accepts only values in ms.

### Expected

`And with up to "10" retries with wait period of "100ms" the "status code" of HTTP request to "/console" of OpenShift instance is equal to "200"`

### Actual

`And with up to "10" retries with wait period of "1s" the "status code" of HTTP request to "/console" of OpenShift instance is equal to "200"`

**Comment by praveenkumar** [comment]
That is something I change recently, didn't know it only matching the `ms` :(

**Comment by anjannath** [comment]
1s would be 1000ms right?

**Comment by agajdosi** [comment]
@anjannath yes

**Comment by agajdosi** [comment]
@gbraad Agree. In some cases however milliseconds are also practical. I have created https://github.com/minishift/minishift/issues/2723 to provide support for both units.
