### ISSUE TITLE
Separate tests into core/primary and extra/secondary to be run in CI 

### ISSUE THREAD

**Issue by budhram** [minishift/minishift#2720]
I think its time now that we need to start thinking on categorizing which tests are our core or primary ones and which are secondary or extra which we care less.

By core tests means
- Unit tests, 
- Fmtcheck
- Basic Integration tests 
- Those integration tests cases which we really care and should be part of PR job as well

By non-core / extra / secondary means
- Those integration tests which we can run in nightly

I would also suggest, we can skip testing core tests during nightly as these are tested regularly during PR or master jobs.

**Comment by praveenkumar** [comment]
@budhram which test as of now you think shouldn't be part of the PR and only part of nightly? That is something you should add in the issue and then we can have a discussion around it.

**Comment by agajdosi** [comment]
IMO we can move from PR testing and test **only on nightly basis** all scenarios which test external applications. For example, deployment of application to OpenShift or similar, like:

- addon-che.feature - deploy and test all workspaces
- addon-xpaas.feature - deploy and test the applications

However into the **PR testing**, probably cmd-addons.feature I would add check that those addons can be applied and removed, so we know they can be deployed, however we do not care about its deeper functionality.

- addon apply che
- addon apply xpaas

----
What could also help us on PR checks it to move the scenarios which does not need running VM to separate feature files, which we can run first (and fail and end tests if anything fails) and then run the VM requiring features.

**Comment by agajdosi** [comment]
Added to 1.24 milestone as this issue was requested on #2695 and needs to be implemented before its merge.

**Comment by LalatenduMohanty** [comment]
> I would also suggest, we can skip testing core tests during nightly as these are tested regularly during PR or master jobs.

IMO we should not do this as when we run more tests in nightly the previous tests which passed during PR can still fail. This is rare but one test failing because some other test induced some behavior is a fair probability.  

>experimental-flags.feature

We should still test this as part of the PR testing as experimental features important too from each PR point of view.
