### ISSUE TITLE
xpaas addon version doesn't match OpenShift version

### ISSUE THREAD

**Issue by siamaksade** [minishift/minishift#2721]
Starting minishift with:
```
minishift start --vm-driver=virtualbox --openshift-version=v3.10.0
```

And apply the xpaas addon, installs the imagestreams from v3.9:
```
$ minishift addons apply xpaas
-- Applying addon 'xpaas':.........................................................................................................................
XPaaS OpenShift imagestream and templates installed
See https://github.com/openshift/openshift-ansible/tree/release-3.9/roles/openshift_examples/files/examples/v3.9
```

**Comment by siamaksade** [comment]
Agree with your points. A short-term solution (1) for quick implementation and then a long-term one for new vars (2) makes sense. Adding the new vars is a good practice since other add-ons might also need it for the same reason.

**Comment by LalatenduMohanty** [comment]
> My proposal is that I can fix with option 1 quite fast and then if there is will we can improve friendliness if built-in variables are introduced. In both cases would look quite similar / the same:

@agajdosi your suggestions sound good but I am against downloading templates on the fly as the default behavior because it would make minishift more dependent on internet and we can control if some faulty templates gets downloaded. So I guess we need to provide option to user to download on the fly but it should not be the default behavior.

**Comment by agajdosi** [comment]
@LalatenduMohanty It is not going to be downloaded on the fly, take a look on #2721.

**Comment by LalatenduMohanty** [comment]
@agajdosi Ack. We also have https://github.com/minishift/minishift/issues/2483 . I am going to close that issue in favor for this issue.
