### ISSUE TITLE
Add tcpdump to Minishift VM

### ISSUE THREAD

**Issue by DuncanDoyle** [minishift/minishift#2724]
### General information

  * Minishift version: v1.15.1+f19ac09
  * OS: macOS:
  * Hypervisor: xhyve

I often have a use-case where I want to monitor the HTTP traffic between pods to debug problems in my RESTful service calls between my Pods. There is a neat little trick (https://access.redhat.com/solutions/3480421) which uses "nsenter" and "tcpdump" to dump the network traffic of a particular pod, which allows me to analyse it Wireshark. 

However, "tcpdump is not available on the Minishift VM, which requires me to register the VM, add yum repo's and manually install tcpdump on every boot.

It would be really convenient if we could ship "tcpdump" ootb with Minishift, especially since the platform is targeted at local development.

### Steps to reproduce

  1. Try to run "tcpdump" inside Minishift VM.
  2. 
  3. 
  4. 

### Expected
tcpdump is available

### Actual
tcpdump is not installed

**Comment by gbraad** [comment]
this seems like a very exceptional usecase. You can modify the iso from the repo at https://github.com/minishift/minishift-centos-iso

**Comment by gbraad** [comment]
since tcpdump is quite small, you might even get away by forcing the install: `minishift ssh -- yum install -y tcpdump` (but this can lead to a lockup of the VM).

**Comment by praveenkumar** [comment]
@DuncanDoyle does https://github.com/minishift/minishift/issues/2724#issuecomment-415017123 works for you.

**Comment by gbraad** [comment]
The reasoning is that I also like to add `pcp` (as for #2728, but it seems it is OK to do so using a series of install commands and `--no-provision` if needed. I'd rather not bloat the image unnecesarily.

**Comment by DuncanDoyle** [comment]
I wouldn't say the use-case is very exceptional. During development I inspect my network traffic a lot, which is pretty hard to do in a container environment without the proper tools installed.

Adding the tools to the RHEL iso (which is the default I'm using) is quite cumbersome due to the registration requirements, adding repo's, etc.. So, it's not as easy as doing a `minishift ssh -- yum install -y tcpdump`. If this would be possible to automate in an add-on, that would be great, but having looked at the current minishift addons, they seem to focus on installing components on the OpenShift deployment, not the underlying OS. And again, the repo-registration part makes the installation a bit annoying.

Second, I started having issues with my VM after adding the tcpdump package manually (not entirely sure anymore what it was, need to try again), which made my VM inoperable.

Given that the tcpdump tool is quite small, I figured it would be a helpful component to add to a OpenShift dev environment like Minishift.

I'll try to switch to the CentOS ISO and see whether that makes my life a bit easier.

**Comment by RHodzelmans** [comment]
Honestly I feel 2 things about this: 1) one this is not an exceptional use case. Debugging my calls locally is quite logical. It can make facts from assumptions. 2) I rather not have to hack stuff. Having it run frictionless on minishift with RHEL should be a given. I should not have to switch to the community distro.

**Comment by gbraad** [comment]
No one suggested to use a community distro. There is a limitation to
what we can include in the image as it is alread a hefty download,
plus the fact of #355.

You can install application inside a privileged container without
issues, the same way as you would do with yum install, without locking
the VM up when the root filesystem is exhausted.

On Wed, Oct 24, 2018 at 9:05 PM Roel Hodzelmans
<notifications@github.com> wrote:
>
> Honestly I feel 2 things about this: 1) one this is not an exceptional use case. Debugging my calls locally is quite logical. It can make facts from assumptions. 2) I rather not have to hack stuff. Having it run frictionless on minishift with RHEL should be a given. I should not have to switch to the community distro.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by gbraad** [comment]
>  Patches welcome ;-)

FYI, the CentOS repo also contains the kickstart definition file for our RHEL7 image.
