### ISSUE TITLE
Minikube Feature: config option --vm-driver=none (no VMs, run directly on the host)

### ISSUE THREAD

**Issue by ryanj** [minishift/minishift#2739]
### General information

  * Minishift version: unscheduled
  * OS: Linux only
  * Hypervisor: none; use the host machine's container engine

### Steps to reproduce

  1. This feature is not currently supported in minishift, but it is available in minikube:

     minishift start --vm-driver=none

### Expected
1. I want the openshift instance and it's apps to be accessible from other machines. I should probably just use the openshift-ansible single machine install instead.

**Comment by LalatenduMohanty** [comment]
@ryanj you can do that using `--vmdriver generic` in Minishift. Check https://docs.okd.io/latest/minishift/using/run-against-an-existing-machine.html

**Comment by LalatenduMohanty** [comment]
@ryanj I am closing this issue as we have what you are looking for. Let us know if you want to re-open this issue.
