### ISSUE TITLE
Verify and update documentation around host folders and persistent volumes 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#274]
The docs are partly out of date. Also we need to verify whether it works with the most interesting hypervisors - VirtualBox, xhyve, Hyper-V

**Comment by budhrg** [comment]
I think we have verified here that it doesn't work. Now, as a part of the issue documentation is remaining right ?

**Comment by budhrg** [comment]
I saw documentation for host folder here https://github.com/minishift/minishift/blob/master/docs/managing-minishift.md#mounted-host-folders.

and track persistent volumes here https://github.com/minishift/minishift/issues/389 and close this issue.

@hferentschik WDYT ?

**Comment by hferentschik** [comment]
@budhrg - let's close it
