### ISSUE TITLE
Apply of default addon htpasswd-identity-provider on running minishift instance throws error

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2742]
### General information

  * Minishift version: v1.23.0
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. minishift start
```
$ ./minishift start
```
  2. minishift addon apply htpasswd-identity-provider --addon-env USER_PASSWORD=test123
```
$ ./minishift addon apply htpasswd-identity-provider --addon-env USER_PASSWORD=test123
-- Applying addon 'htpasswd-identity-provider':..Error applying the add-on: Error executing command 'ssh command error:
command : sudo cp -fp /var/lib/minishift/openshift.local.config/master/master-config.yaml /var/lib/minishift/openshift.local.config/master/master-config-htpasswd.yaml
err     : exit status 1
output  : cp: cannot stat '/var/lib/minishift/openshift.local.config/master/master-config.yaml': No such file or directory
':
```
  3. 
  4. 

### Expected
Should be applied 

### Actual
Throws error

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by amitkrout** [comment]
@LalatenduMohanty quick attention needed as its failing on minishift default addon htpasswd-identity-provider

**Comment by praveenkumar** [comment]
@amitkrout can you try below

```
./minishift addon apply htpasswd-identity-provider --addon-env USER_PASSWORD=test123 CONFIG_LOCATION=base/master
```

**Comment by amitkrout** [comment]
Now the config path problem is resolved with config location ```base/openshift-apiserver``` but it fails while adding the default developer user to file
```
$ ./minishift addon apply htpasswd-identity-provider --addon-env CONFIG_LOCATION=base/openshift-apiserver
-- Applying addon 'htpasswd-identity-provider':....Error applying the add-on: Error executing command 'ssh command error:
command : docker exec -t origin /usr/bin/bash -c "htpasswd -b /var/lib/origin/base/openshift-apiserver/users.htpasswd developer developer"
err     : exit status 1
output  : htpasswd: cannot modify file /var/lib/origin/base/openshift-apiserver/users.htpasswd; use '-c' to create it
':
```
