### ISSUE TITLE
openshift restart command is broken 

### ISSUE THREAD

**Issue by sudhirverma** [minishift/minishift#2745]
### General information

  * Minishift version:  minishift v1.23.0+91235ee
  * OS:  Windows 7
  * Hypervisor: VirtualBox

### Steps to reproduce

  1.  minishift start
  2.  minishift openshift restart

### Expected

openshift cluster is restarted 

### Actual

```
PS C:\windows\system32> minishift.exe status
Minishift:  Running
Profile:    minishift
OpenShift:  Stopped
DiskUsage:  1% of 19G (Mounted On: /mnt/sda1)
CacheUsage: 670.4 MB (used by oc binary, ISO or cached images)
RHSM:       Not Registered
PS C:\windows\system32> minishift.exe openshift restart
Error restarting the OpenShift cluster: ssh command error:
command : docker stop
err     : exit status 1
output  : "docker stop" requires at least 1 argument(s).
See 'docker stop --help'.

Usage:  docker stop [OPTIONS] CONTAINER [CONTAINER...]

Stop one or more running containers
```

@LalatenduMohanty  please take a look in this issue

**Comment by amitkrout** [comment]
@sudhirverma Are you able to start minishift successfully ?

**Comment by LalatenduMohanty** [comment]
Tested this on macOS and can not reproduce the issue, need to check with Virtualbox.
```
$ minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Running (openshift v3.10.0+ddf284b-16)
DiskUsage:  20% of 19G (Mounted On: /mnt/vda1)
CacheUsage: 3.009 GB (used by oc binary, ISO or cached images)

$ minishift openshift restart
OpenShift restarted successfully

$ minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Running (openshift v3.10.0+ddf284b-16)
DiskUsage:  21% of 19G (Mounted On: /mnt/vda1)
CacheUsage: 3.009 GB (used by oc binary, ISO or cached images)
```

**Comment by gbraad** [comment]
Can you check your setup?

As I am not supposed to see "RHSM: Not Registered " on Minishift. This is
CDK-only.

**Comment by LalatenduMohanty** [comment]
Not able to reproduce it on macOS+Virtualbox 
```
$ minishift openshift restart
OpenShift restarted successfully

$ minishift status
Minishift:  Running
Profile:    test
OpenShift:  Running (openshift v3.10.0+8e19bad-29)
DiskUsage:  20% of 19G (Mounted On: /mnt/sda1)
CacheUsage: 3.009 GB (used by oc binary, ISO or cached images)
```

**Comment by sudhirverma** [comment]
@LalatenduMohanty on windows 7 I am still getting the error 
```
PS C:\windows\system32> minishift openshift restart
Error restarting the OpenShift cluster: ssh command error:
command : docker stop
err     : exit status 1
output  : "docker stop" requires at least 1 argument(s).
See 'docker stop --help'.

Usage:  docker stop [OPTIONS] CONTAINER [CONTAINER...]

Stop one or more running containers

PS C:\windows\system32> minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Stopped
DiskUsage:  20% of 19G (Mounted On: /mnt/sda1)
CacheUsage: 670.4 MB (used by oc binary, ISO or cached images)
RHSM:       Not Registered
```

**Comment by amitkrout** [comment]
Works fine on Win10+VirtualBox.

**Comment by agajdosi** [comment]
I would expect this to happen with `CDK 3.5.0` with `OCP 3.10.x`.

**Comment by sudhirverma** [comment]
@gbraad 
> You should not get "RHSM: Not Registered" on a normal Minishift
installation.

Probably I was using the old cdk config file hence was seeing the problem

> Can you explain how you installed? Can you provide steps?

I did fresh setup then everything went fine
Steps:
1. minishift start --vm-driver virtualbox
2. Restarted the win7 host
3. minishift start --vm-driver virtualbox

my bad seems in the first run I missed some useful minishift start log which might be reporting the error in minishift start.

Sorry for the inconvenience caused. Closing the issue

**Comment by gbraad** [comment]
Right, as @agajdosi points out. This might have been a remainder of the
Minishift (default) profile from CDK with 3.10 that got called on
Minishift. Anyway, this should not be a normal situation.


-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]
