### ISSUE TITLE
Create and maintain roadmap/plan for documentation 

### ISSUE THREAD

**Issue by thatdocslady** [minishift/minishift#275]
As a part of rolling out the 1.0 release we need to triage the different documentation tasks and plan ahead for the different stages of release.

Following discussions, at the moment this breakdown is the starting point, feel free to suggest more/less/different tasks or priorities as needed.

### Before 1.0 release
- Clean up and strengthen existing doc set
- Compile known issues and release notes 
- Prepare publication workflow (coordinated with downstream docs)
- No new/expanded content will be added
- Separate installation and getting started from README to enable publication

### After 1.0 release
- Fix doc bugs and improve doc set based on whatever issues are opened as needed
- Determine top major use-cases or scenarios that we want to document end-to-end tutorials for. We can/should consult with users who are implementing the project to see which scenarios rise up to the surface
- Collaborate with OpenShift to improve integration of docs with their getting started docs as needed

**Comment by budhrg** [comment]
@thatdocslady , Since we have added [ROADMAP.md](https://github.com/minishift/minishift/blob/master/ROADMAP.md) , is this issue being used as tracking changes or we can close it?

**Comment by thatdocslady** [comment]
@budhrg this issue is for a documentation roadmap, which isn't related to the development roadmap. In fact, it's more like a documentatio plan than roadmap, but we have no other place to track it for now so please keep this issue open.

**Comment by budhrg** [comment]
@thatdocslady , title is bit confusing to me on first read :)

**Comment by hferentschik** [comment]
@thatdocslady what's about putting the "roadmap" onto the Mojo and create  actionable issues for the things we already know needs to be done?

**Comment by thatdocslady** [comment]
@hferentschik sure that makes sense, I'll do that and then close this issue

**Comment by hferentschik** [comment]
@thatdocslady, +1, thanks

**Comment by praveenkumar** [comment]
@hferentschik shouldn't we have this now in place already?

**Comment by thatdocslady** [comment]
@praveenkumar I was in the process of creating this document in Mojo and then CDK planning came in and we got a little stuck, but hopefully this/next week I should be able to finalize this and socialize internally.

**Comment by thatdocslady** [comment]
@praveenkumar @hferentschik following a discussion in the upstream/downstream doc team, we realize that the GH issue queue should be sufficient for upstream tracking, and the CDK downstream plan is managed by the downstream writers and is meant to address different stakeholder requirements. 

Recommending to close this issue.

**Comment by praveenkumar** [comment]
@thatdocslady Ack, closing the issue.
