### ISSUE TITLE
Error during post cluster up configuration: Unable to login to cluster

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2755]
### General information

  * Minishift version: v1.23.0
  * OS: Windows
  * Hypervisor: VirtualBox

Minishift fails to start properly on Windows 7 laptop. 

### Steps to reproduce

  1. make integration MINISHIFT_BINARY=<path-to-bin>
  2. see results

### Expected

Minishift start is ok.

### Actual

Minishift fails to start. However this is reproducible only when used with integration tests.

### Logs
```
                         Login to server ...
                         Creating initial project "myproject" ...
                         Server Information ...
                         OpenShift server started.
                         
                         The server is accessible via web console at:
                             https://192.168.99.100:8443
                         
                         You are logged in as:
                             User:     developer
                             Password: <any value>
                         
                         To login as administrator:
                             oc login -u system:admin

09:34:09.892084  stderr: error: net/http: TLS handshake timeout
                         Error during post cluster up configuration: Unable to login to cluster

09:34:09.894585    info: ----- Scenario: OpenShift is ready after startup -----
09:34:09.894585 command: C:/Users/CDK/minishift/minishift.exe status
09:34:15.108747  stdout: Minishift:  Running
                         Profile:    minishift
                         OpenShift:  Running (openshift v3.10.0+2fddd08-32)
                         DiskUsage:  16% of 19G (Mounted On: /mnt/sda1)
                         CacheUsage: 470.5 MB (used by oc binary, ISO or cached images)
```

**Comment by praveenkumar** [comment]
@agajdosi  is it on some slave or happening on the test machine? This kind of behavior should be replicated across the platform as per my understanding.

**Comment by agajdosi** [comment]
@praveenkumar It is only replicable on 1 laptop in minilab, on both Minishift and CDK. It worked fine before, will try on previous versions.

**Comment by praveenkumar** [comment]
@agajdosi have you tried it with the older version and does that work?

**Comment by agajdosi** [comment]
@praveenkumar mmm, so it is reproducible on that machine also with CDK 3.5.0 which few weeks ago passed there just fine. Going to try that on different network with the same machine.
