### ISSUE TITLE
Report error as using minishift

### ISSUE THREAD

**Issue by xiaoyan1985** [minishift/minishift#2756]
### General information

  * Minishift version: minishift-1.15.0-windows-amd64
  * OS: Windows7
  * Hypervisor: VirtualBox

### Steps to reproduce

   run the command "minishift start --openshift-version v3.9.0 --iso-url centos --cpus 4 --memory 4GB --disk-size 40GB --vm-driver virtualbox"

### Expected
Start minishift VM successfully

### Actual
Report error as followings:

-- Starting Minishift VM ......... FAIL E0904 17:02:09.725074    3268 start.go:3
68] Error starting the VM: Error creating new host: Error attempting to get plug
in server address for RPC: Failed to dial the plugin server in 10s. Retrying.
Error starting the VM: Error creating new host: Error attempting to get plugin s
erver address for RPC: Failed to dial the plugin server in 10s

### Log 
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform .
.. OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    4
   Disk size: 40 GB
-- Starting Minishift VM ......... FAIL E0904 17:02:09.725074    3268 start.go:3
68] Error starting the VM: Error creating new host: Error attempting to get plug
in server address for RPC: Failed to dial the plugin server in 10s. Retrying.
Error starting the VM: Error creating new host: Error attempting to get plugin s
erver address for RPC: Failed to dial the plugin server in 10s

Can you tell me how to resolve it? Thanks.

**Comment by LalatenduMohanty** [comment]
@xiaoyan1985 Can you please give us debug logs? 
`You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.`

**Comment by xiaoyan1985** [comment]
Thanks. It is OK as I using the latest one.

**Comment by praveenkumar** [comment]
> It is OK as I using the latest one.

@xiaoyan1985 you mean your issue is resolved now when using the latest version?

**Comment by xiaoyan1985** [comment]
Sorry, I didn't make myself clear.
 
It is ok, as I tried again with minishift-1.15.0-windows-amd64 after unloading a lot of things from my machine. The second time I tried to use the latest version, there was no problem.

So it's certainly not the latest version that solves the problem.

**Comment by praveenkumar** [comment]
@xiaoyan1985 Can we close this issue if your problem is solved now?

**Comment by xiaoyan1985** [comment]
Yes, thanks
