### ISSUE TITLE
Provide command to customize OpenShift master configuration

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#276]
This will allow a generic solution for issue #257 as well

**Comment by hferentschik** [comment]
My current thinking around this is to utilise the 'openshift ex config patch' - https://github.com/openshift/origin/pull/9165/files. Basically we pass the ability to use this out to the user via a

    $ minishift openshift patch -f <patch-file>

Internally we will then use the SSH communicator to communicate with the VM and execute appropriate docker commands to apply the patch and potentially restart all required containers.

For that we probably need a bit of infrastructure to make this docker command execution easy to use and re-usable for other use cases.

**Comment by jorgemoralespou** [comment]
@hferentschick this is what we do in the wrapper script. Please take a look
for example at blob/master/plugins.d/pipelines.local.plugin at the install
method.

**Comment by hferentschik** [comment]
See also issue #25

**Comment by jorgemoralespou** [comment]
@hferentschik I would try to encapsulate that configuration that a
developer would do and possibly provide a way for them to apply any config.

In the following example, set would have a set of well known
customizations, and patch would apply any (which could potentially break
the config).

E.g
minishift config set oauth=htpasswd
minishift config patch --file=mycustomconfig.json

**Comment by hferentschik** [comment]
> I would try to encapsulate that configuration that a
developer would do and possibly provide a way for them to apply any config.

But that puts us into the position of knowing all the possible customisation and keeping in sync with whatever OpenShift does. We then can end up in situations where the user ask why customisation xyz is not supported yet. In the end one would need the generic approach as well as a "power user" feature.

I think, I'd prefer the generic approach first and then maybe add on on this and provide common known customisations as sort of "alias" where we keep/maintain the required patch under the hoods.

> which could potentially break the config

true, I think we can alleviate this a bit by providing a rollback function of sorts. I have seen the code in your wrapper scripts. Something along these lines, but with the ability to revert a applied patch by rolling back the modified config file. WDYT?

**Comment by hferentschik** [comment]
from https://github.com/minishift/minishift/issues/207#issuecomment-274168431
> My testing also seems to have uncovered an issue with openshift ex config patch command run 
> inside of a container. If MiniShift was going to use that to patch the master config file, there is a 
> chance could trip the same problem depending on what you are doing. The issue appears to be in > upstream code, so don't know at this point when/if might be fixed or whether need to start doing > yaml parsing in the wrapper to make changes to master config file.

**Comment by hferentschik** [comment]
from https://github.com/minishift/minishift/issues/207#issuecomment-274177021

@hferentschik so the issue is that openshift ex config patch fails if you're trying to patch the BuildConfigDefaults after it has been added to the master-config.yaml. The reason this happens is because the BuildDefaults config, like any other plugin config is of type RawExtension (https://github.com/openshift/origin/blob/master/pkg/cmd/server/api/v1/types.go#L1235). This means that for the patch code, this looks like a blob of stuff. It can set it the first time, but it can't modify it afterwards.

Here's @GrahamDumpleton's example. If you start from this config:

    admissionConfig:
     pluginConfig:
       BuildDefaults:
         configuration:
           apiVersion: v1
           env:
           - name: https_proxy
             value: http://localhost:8080
           - name: NO_PROXY
             value: 0.0.0.0/0,127.0.0.1,localhost,172.30.1.1,172.30.0.0/8,192.1
    68.65.2
           - name: no_proxy
             value: 0.0.0.0/0,127.0.0.1,localhost,172.30.1.1,172.30.0.0/8,192.1
    68.65.2
           - name: HTTP_PROXY
             value: http://localhost:8080
           - name: http_proxy
             value: http://localhost:8080
           - name: HTTPS_PROXY
             value: http://localhost:8080
           gitHTTPProxy: http://localhost:8080
           gitHTTPSProxy: http://localhost:8080
           gitNoProxy: 0.0.0.0/0,127.0.0.1,localhost,172.30.1.1,172.30.0.0/8,19
    2.168.65.2
           kind: BuildDefaultsConfig
           resources: {}
         location: “"
    
    And try to apply a patch:
    
    #!/bin/bash
    PATCH=`cat <<EOF
    {
       "admissionConfig": {
           "pluginConfig": {
               "BuildDefaults": {
                   "configuration": {
                       "apiVersion": "v1",
                       "kind": "BuildDefaultsConfig",
                       "imageLabels": [
                           {
                               "name": "powershift-profile",
                               "value": "proxy"
                           }
                       ]
                   }
               }
           }
       }
    }
    EOF`

    cp /var/lib/origin/openshift.local.config/master/master-config.yaml /tmp/master-config.yaml

    openshift ex config patch /tmp/master-config.yaml     --patch "$PATCH" > /var/lib/origin/openshift.local.config/master/master-config.yaml

The patch operation fails. This will be the case with any admission plugin config.

**Comment by hferentschik** [comment]
@csrwng 

> The patch operation fails. This will be the case with any admission plugin config.

So is this a bug in the patch command which will eventually be fixed or are you saying, that this will never work?

**Comment by csrwng** [comment]
@hferentschik my understanding is that it is a bug and should be fixed in kubernetes. If an issue hasn't been opened, I'll create one.

**Comment by hferentschik** [comment]
> my understanding is that it is a bug and should be fixed in kubernetes. If an issue hasn't been opened, I'll create one.

cool, thanks

**Comment by hferentschik** [comment]
@csrwng, the patch command has this format:

    openshift ex config patch FILENAME -p PATCH [options]

So it implies I can path and type of yaml configuration file. Is that correct? And is there a practical use? The examples I have seen are all patching _master-config.yaml_.

**Comment by csrwng** [comment]
@hferentschik my understanding is that it can be used to patch config files (master-config.yaml and node-config.yaml). The purpose of the filename parameter is to point it to the path of the file you want to patch. I don't think it can be used to patch any yaml file. (You can try it of course)

**Comment by hferentschik** [comment]
Merged via pull request #379
