### ISSUE TITLE
Create an feature equivalent of `oc cluster add` functionalility

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2767]
oc 3.10.0 have a capability to add a component to running cluster using `oc cluster add`. From the minishift point of view, we don't have any such capability and this will be there for 3.11 also. I propose to put an `add` flag behind the experiment in the meantime because from 3.12 (4.0) this might not be available or change completely but the minishift user can consume it till 3.11 release.

```
$ oc cluster -h
[...]
Usage:
  oc cluster ACTION [flags]

Available Commands:
  add         Add components to an 'oc cluster up' cluster
  down        Stop OpenShift on Docker
  status      Show OpenShift on Docker status
  up          Start OpenShift on Docker with reasonable defaults
```

```
$ export MINISHIFT_ENABLE_EXPERIMENTAL=y
$ minishift openshift add <component_name>
```

**Comment by praveenkumar** [comment]
@LalatenduMohanty if you think this would be the benefit for our downstream user then I would like to put PR for this sprint itself so it can make it to downstream.

**Comment by praveenkumar** [comment]
CC @surajnarwade I hope this is what you wanted to make other components start without compromise the minishift start.

**Comment by surajnarwade** [comment]
@praveenkumar Yeah, waiting for this feature :)

**Comment by LalatenduMohanty** [comment]
```
$ ./oc cluster add --help
Adds a component to an 'oc cluster up' cluster.

Usage:
  oc cluster add [flags]

Examples:
  # Add service catalog
  oc cluster add service-catalog

  # Add template service broker to a different basedir
  oc cluster add --base-dir=other/path template-service-broker

Options:
      --base-dir='': Directory on Docker host for cluster up configuration
      --image='openshift/origin-${component}:${version}': Specify the images to use for OpenShift
      --server-loglevel=0: Log level for OpenShift server

Use "oc options" for a list of global command-line options (applies to all commands).
```

**Comment by LalatenduMohanty** [comment]
@praveenkumar @surajnarwade   I think `minishift openshift add` will be useful as it will enable users to add components to a running instance. 

However regarding enabling a component during start vs adding them later, I think the only difference is doing something during start vs on the fly. Is there anything else?

```
 ./oc cluster up --help
xxxxxxxxxxxxx
Options:
      --base-dir='': Directory on Docker host for cluster up configuration
      --enable=[*]: A list of components to enable.  '*' enables all on-by-default components, 'foo' enables the
component named 'foo', '-foo' disables the component named 'foo'.
All components: automation-service-broker, centos-imagestreams, persistent-volumes, registry, rhel-imagestreams, router,
sample-templates, service-catalog, template-service-broker, web-console
Disabled-by-default components: automation-service-broker, rhel-imagestreams, service-catalog, template-service-broker
     
```

```
$ ./oc cluster add --help
Adds a component to an 'oc cluster up' cluster.

Usage:
  oc cluster add [flags]

Examples:
  # Add service catalog
  oc cluster add service-catalog

  # Add template service broker to a different basedir
  oc cluster add --base-dir=other/path template-service-broker

Options:
      --base-dir='': Directory on Docker host for cluster up configuration
      --image='openshift/origin-${component}:${version}': Specify the images to use for OpenShift
      --server-loglevel=0: Log level for OpenShift server

Use "oc options" for a list of global command-line options (applies to all commands).
```

**Comment by praveenkumar** [comment]
> I think the only difference is doing something during start vs on the fly. Is there anything else?

@LalatenduMohanty  No there is no other difference but right now what happens if any of the components fail during the start then `minishift start` process fail but if you provide a way to add a component on fly then user can do `minishift start` as usual and try the component without breaking the start process.

**Comment by praveenkumar** [comment]
> isn't this duplicated with an earlier issue filed by @LalatenduMohanty 

@gbraad which one it is, issue number?

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/2776
