### ISSUE TITLE
Reproduce issue exposing OpenShift registry

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#277]
This is a investigation task for issue #254.

**Comment by praveenkumar** [comment]
Below is the steps which need to added in the doc if we want to access openshift registry.

# On the Host

```
$ ~/.minishift/cache/oc/v1.3.1/oc login -u system:admin
$ ~/.minishift/cache/oc/v1.3.1/oc expose service docker-registry -n default
$ ~/.minishift/cache/oc/v1.3.1/oc get routes -n default
NAME              HOST/PORT                                     PATH      SERVICES          PORT       TERMINATION
docker-registry   docker-registry-default.192.168.64.2.xip.io             docker-registry   5000-tcp   
$ ~/.minishift/cache/oc/v1.3.1/oc adm policy add-cluster-role-to-user cluster-admin developer
```

# On the VM

```
$ minishift ssh

# Add insecure registry *docker-registry-default.192.168.64.2.xip.io:80* to docker service file

$ cat /etc/systemd/system/docker.service 
[Unit]
Description=Docker Application Container Engine
After=network.target rc-local.service

[Service]
Type=notify
ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock            --selinux-enabled            --storage-driver devicemapper --tlsverify --tlscacert /etc/docker/ca.pem            --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem            --label provider=xhyve --insecure-registry 172.30.0.0/16 --insecure-registry docker-registry-default.192.168.64.2.xip.io:80
ExecReload=/bin/kill -s HUP 
MountFlags=slave
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TimeoutStartSec=0
Delegate=yes
KillMode=process
Environment=

[Install]
WantedBy=multi-user.target

$ sudo systemctl daemon-reload
$ docker stop origin
$ sudo systemctl restart docker
```

On the Host

```
# eval $(minishift docker-env)
# ~/.minishift/cache/oc/v1.3.1/oc whoami -t (for developer user)
dCaacg8sCisQQq0Uc1eXO6NNsb-xFMZNPQ-mv9lCWkI
$ docker login docker-registry-default.192.168.64.2.xip.io:80
Username: developer
Password: <put token here>
Email: abc@gmail.com
WARNING: login credentials saved in /home/docker/.docker/config.json
Login Succeeded
```

**Comment by hferentschik** [comment]
@praveenkumar, great. So let's say we want to boils this down a bit, something like this should work as well, right?

     $ oc login -u system:admin
     $ oc expose service docker-registry -n default
     $ minishift ssh -c <single command to be determined which updated docker's service file>
     $ minishift stop
     $ minishift start

That said, say we add 'docker-registry-default.\<ip\>.xip.io:80' per default to the Docker service file as part of provisioning, then the user literally only had to:

      $ oc login -u system:admin
      $ oc expose service docker-registry -n default

**Comment by hferentschik** [comment]
Well, to refine this a bit, one would need to add the default or configured public hostname (see also available start flags)

**Comment by praveenkumar** [comment]
@hferentschik we can't do `minishift stop` and then `minishift start` because restart again change docker service file (that is not persistent across reboot atleast for CentOS).

**Comment by hferentschik** [comment]
> we can't do minishift stop and then minishift start because restart again change docker service file (that is not persistent across reboot atleast for CentOS).

What!? If that's the case let's fix this. What's about b2d? Exposing the registry seems pointless, if I have to re-do this every time I re-start. Is this because the provisioner runs again? The data itself is persistent, right?

**Comment by praveenkumar** [comment]
> What's about b2d? Exposing the registry seems pointless, if I have to re-do this every time I re-start. Is this because the provisioner runs again?

I have to check if b2d have persistent around docker options and update. For CentOS I created issue and will check if symlink a service file handle properly by systemd.

**Comment by hferentschik** [comment]
+1

**Comment by praveenkumar** [comment]
@hferentschik I had a quick look and https://github.com/boot2docker/boot2docker/blob/master/rootfs/rootfs/usr/local/etc/init.d/docker#L6 is what store the options for docker daemon and this is not persistent across restart :( . 

- https://github.com/boot2docker/boot2docker/issues/667

**Comment by hferentschik** [comment]
> I had a quick look and https://github.com/boot2docker/boot2docker/blob/master/rootfs/rootfs/usr/local/etc/init.d/docker#L6 is what store the options for docker daemon and this is not persistent across restart :( .

Can we fix this from our build?

**Comment by budhrg** [comment]
Instructions provided in [above comment](https://github.com/minishift/minishift/issues/277#issuecomment-272689327) seems to be not working from me in host side.

```
$ sudo systemctl status docker
Active: active (running)
...

$ oc whoami -t
_u7KJ9qYEMUlHChb7rsZ6iPWh_HtNCHesN4GTLrbGxw

$ docker login docker-registry-default.192.168.99.100.xip.io
Username: developer
Password: 
Email: foo@foo.com
Error response from daemon: invalid registry endpoint https://docker-registry-default.192.168.99.100.xip.io/v0/: unable to ping registry endpoint https://docker-registry-default.192.168.99.100.xip.io/v0/
v2 ping attempt failed with error: Get https://docker-registry-default.192.168.99.100.xip.io/v2/: x509: certificate is valid for 192.168.99.100.xip.io, not docker-registry-default.192.168.99.100.xip.io
 v1 ping attempt failed with error: Get https://docker-registry-default.192.168.99.100.xip.io/v1/_ping: x509: certificate is valid for 192.168.99.100.xip.io, not docker-registry-default.192.168.99.100.xip.io. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry docker-registry-default.192.168.99.100.xip.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/docker-registry-default.192.168.99.100.xip.io/ca.crt
```

#### Trying to connect Docker client
```
$ sudo systemctl status docker
   Active: inactive (dead) 
...

# eval "$(minishift docker-env)"
$ export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/home/budhram/.minishift/certs"
export DOCKER_API_VERSION="1.22"

$ echo $DOCKER_CERT_PATH      
/home/budhram/.minishift/certs

$ docker login docker-registry-default.192.168.99.100.xip.io
Could not read CA certificate "/etc/docker/ca.pem": open /etc/docker/ca.pem: no such file or directory
```

**Comment by hferentschik** [comment]
> I had a quick look and https://github.com/boot2docker/boot2docker/blob/master/rootfs/rootfs/usr/local/etc/init.d/docker#L6 is what store the options for docker daemon and this is not persistent across restart :( .

@praveenkumar Do we have an issue in our repo to track this? What does it take to fix it and what are our options here in general?

**Comment by hferentschik** [comment]
@budhrg So you are saying the instructions above don't work? Is this still the case?

**Comment by budhrg** [comment]
> @budhrg So you are saying the instructions above don't work? Is this still the case?

No @hferentschik , not working from host side. @praveenkumar acknowledged it and working I guess.

**Comment by hferentschik** [comment]
@praveenkumar and to be clear, the instructions apply for the CentOS ISO. For the B2D ISO (persistence aside), things look differently. So, if we were to document manual steps, we would need two sets of instructions. TBH, given that this would not even persist, I am reluctant to go down this path.

**Comment by hferentschik** [comment]
I think to sum this up

* Issue #254 is reproducible 
* To expose the registry one needs to
  * Expose the registry route 
  * Change some policy rules for he developer account 
  * Add the route as insecure registry to the Docker options
* There might be changes required to ISOs to make the registry route per default part of the insecure registry options. Alternatively, we could make sure the appropriate env variable gets set.

Right now, it does not seem to make sense to add any documentation around this into the docs, since they would differ depending on the ISO and also need re-applying on each restart. 

Last but not least, we also need to provide a command for the user to get the registry host and port. So we probably need to add something like _minishift registry_.

**Comment by LalatenduMohanty** [comment]
Just to add  

```
 $ minishift stop
 $ minishift start
```
Will not work after adding insecure registry "docker-registry-default.192.168.64.2.xip.io:80" to docker service file in /etc/systemd/system/docker.service as /etc/systemd/system/docker.service will be over written for each minishift start

**Comment by hferentschik** [comment]
> Will not work after adding insecure registry "docker-registry-default.192.168.64.2.xip.io:80" to docker service file in /etc/systemd/system/docker.service as /etc/systemd/system/docker.service will be over written for each minishift start

FYI, that's why https://github.com/minishift/minishift-centos-iso/issues/83 was created. We were not sure whether this is still required? I guess technically we could add the registry to dockerEnv in start.go. This was it gets re-added every time. @praveenkumar wdyt?

**Comment by gbraad** [comment]
The docker service file is located in the live-rw filesystem and does not survive a reboot, and even if we do, the provisioner overwrites them: https://github.com/minishift/minishift/blob/master/pkg/minishift/provisioner/utils.go#L58 is the template for CentOS, and we also have one for RHEL.

**Comment by jorgemoralespou** [comment]
Why do you add the insecure-registry to /etc/systemd/system/docker.service and not to /etc/sysconfig/docker?
In any case, not sure that /etc/sysconfig/docker will not be overwritten, but definitely it's the place to add it.

**Comment by gbraad** [comment]
@jorgemoralespou `/etc/sysconfig/docker` is not persisted either (actually nothing in `/etc` survives a reboot). but I do believe this more closely matches what really happens.

**Comment by jorgemoralespou** [comment]
I guess you'll have to implement a mechanism that will persist this type of information on a "persistable" space, and reapply on every VM restart.
Think about the insecure-registry, proxy config and certificates for docker. Although I guess you should already have a solution for the proxy, so probably you just need to extend it to other relevant configuration.

**Comment by hferentschik** [comment]
> Although I guess you should already have a solution for the proxy, so probably you just need to extend it to other relevant configuration.

Right, that's what I am thinking atm. We do it the same way as we apply the proxy settings. That's what I meant with _dockerEnv_ in _start.go_.
