### ISSUE TITLE
Nightly failed because of XPaaS addon's echo command.

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2782]
We made changes to xpaas addon echo command from `XPaaS OpenShift imagestream and templates installed` to `XPaaS imagestream and templates for OpenShift 3.10 installed` and nightly failed because of it https://ci.centos.org/job/minishift-nightly-centos/274/console. I would say that instead of include version info in the echo we should simply put `XPaaS imagestream and templates for OpenShift installed` so we don't need to change the test senario everytime.

**Comment by LalatenduMohanty** [comment]
Error from the CI 
```
  Error: Output did not match. Expected: 'XPaaS OpenShift imagestream and templates installed', Actual: '-- Starting profile 'minishift'
```
