### ISSUE TITLE
addon htpasswd-identity-provider breaks while applying

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2784]
### General information

  * Minishift version: master
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. ```minishift addon enable htpasswd-identity-provider```
  2. ```minishift start```
  3. 
  4. 
Using http://artifacts.ci.centos.org/minishift/minishift/pr/2764/ darwin bit

### Expected
```
$ ./minishift addons apply htpasswd-identity-provider
-- Applying addon 'htpasswd-identity-provider':..........
-- Restarting Openshift API server ...
-- Restarting Kube API server ......
-- Successfully installed addon htpasswd identity provider ... OK
```
### Actual
```
$ ./minishift addons apply htpasswd-identity-provider
-- Applying addon 'htpasswd-identity-provider':Error during post cluster up configuration: Invalid character(s) found in major number "=3"
```

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@amitkrout try to compile from master and check, this should work.

```
$ ./minishift addon apply htpasswd-identity-provider
-- Applying addon 'htpasswd-identity-provider':..........
-- Restarting Openshift API server ...
-- Restarting Kube API server ......
-- Successfully installed addon htpasswd identity provider ... OK

```

**Comment by amitkrout** [comment]
I picked the wrong bit to test. Works fine on master
