### ISSUE TITLE
Create a test to install Knative on Minishft

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2787]
Knative is going to be important from OpenShift point of view. We are (Kamesh) is planning to send  a PR to Knative repository around the steps to start Knative on Minishift and we need a test to make sure it always work.  We should be able to add the test to nightly CI. 

Refer https://github.com/minishift/minishift/issues/2676

**Comment by amitkrout** [comment]
@agajdosi If you have already done some investigation then feel free to reassign to your name or else i will keep continue on this ;)

**Comment by amitkrout** [comment]
Creating an addons file will be helpful immensely. Is anybody working on creating addons as filed in Issue #2904
