### ISSUE TITLE
Improve command reference docs

### ISSUE THREAD

**Issue by thatdocslady** [minishift/minishift#279]
(to handle after 1.0 release)

This issue is a catch-all bucket for now (unless we determine that some issues are bigger and require separate issues) for questions that came up while editing the cobra doc strings. 

The questions are organized under each command and mainly originated from the NEEDINFO comments that were included in PR #198 a while ago.

#### General

- Can we ever have more than one VM or cluster? If yes, can we run commands on multiple clusters?

#### config.go

- Can we run this command any time? Runtime too? 
- How many config files can we have? 
- Some of the options correspond to options in the minishift start command, do the other options correspond to something else or is this the only place to set them? If we set the options in the start command, are they saved in the config file?
- If we set --use-existing-config to true, does it invoke the config file? Can we create a config file and select it during start?

#### config/set.go

- Can we set multiple properties in one command or do we need to run separate commands for that? How do we separate multiple properties?

#### config/view.go
- Need to investigate how Go templates behave and document examples

#### service.go
- Can we run the command on multiple services? How do we separate them?

#### start.go

- DefaultIsoUrl option: Default value is still jdyson, need to change to minishift
- How do you separate multiple env vars? Comma? Space + comma? etc.. 

#### stop.go
- Is this a graceful stop? What about force stop in case something is preventing from stopping gracefully?

**Comment by hferentschik** [comment]
> Can we ever have more than one VM or cluster?

Yes. right now you can even do this via the _MINISHIFT_HOME_ variable. You can have multiple Minishift instances running. However, switching between them means changing the env variable.
Long term, we are looking for a way to have multiple instances running from the same MINISHIFT_HOME directory. In this case, many commands will need same way to identify the VM/instance the command applies to. 

Having multiple instances running at the same time, is, however, questionable due to the high runtime requirements. 

 > If yes, can we run commands on multiple clusters?

Not for now

**Comment by hferentschik** [comment]
Regarding the _config_ command:

> Can we run this command any time? Runtime too?

Yes, but in some cases the changes won't apply after the machine gets re-started or even re-created, eg setting a new default VM driver. The config change will be made, but won't take effect until you do a 'minishift delete && minishift start'

> How many config files can we have?

One which we control - _config.json_

> Some of the options correspond to options in the minishift start command, do the other options correspond to something else or is this the only place to set them? 

They apply to various commands. 

> If we set the options in the start command, are they saved in the config file?

Yes

> If we set --use-existing-config to true, does it invoke the config file?

No, completely unrelated things. Also _use-existing-config_ does not exist anymore in the context of Minishift.

> Can we create a config file 

Yes

> and select it during start?

There is no way to "select" the config file. It is expected to be under $MINISHIFT_HOME/config/config.json

**Comment by praveenkumar** [comment]
@hferentschik Does this issue still make sense to us? Can you please add a milestone to it.

**Comment by thatdocslady** [comment]
@praveenkumar these are open issues that were raised while I was doing a general doc string edit, so I guess we need to investigate some of these and see whether they're still valid.

**Comment by hferentschik** [comment]
I think this is @thatdocslady issue. I am not sure what the action is we should take here. IMO we can close it, but let's see what @thatdocslady thinks.

**Comment by thatdocslady** [comment]
@hferentschik see my comment above, I can see some of the questions were answered already but things may have changed since then in functionality. If you assign this to a milestone I can go over it in the next sprint and see what can be done and what is obsolete.

**Comment by thatdocslady** [comment]
@hferentschik I agree that we can close this issue, some of these are obsolete and most can be extrapolated from the commands. Closing for now, if anyone wants to reopen then let's discuss.
