### ISSUE TITLE
Starting Minishift VM ..... FAIL E0912

### ISSUE THREAD

**Issue by naveenmajumdar** [minishift/minishift#2798]
### General information

  * Minishift version:  v1.23.0+91235ee
  * OS: Linux / macOS / Windows : Linux/Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox : KVM/Hyper-V/VirtualBox

### Steps to reproduce

  1. curl https://github.com/minishift/minishift/releases/download/v1.23.0/minishift-1.23.0-linux-amd64.tgz
  2. minishift start

### Expected
should be started but not working 

### Logs
[root@localhost ~]# minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.10.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.10.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ...
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.10.0'
 24.08 MiB / 24.08 MiB [=========================================================================================================================] 100.00% 0s-- Downloading OpenShift v3.10.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.12.0/minishift-centos7.iso'
 344.00 MiB / 344.00 MiB [=======================================================================================================================] 100.00% 0s
-- Starting Minishift VM ..... FAIL E0912 11:04:32.348855   26386 start.go:433] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: [Code-8] [Domain-44] invalid argument: could not find capabilities for domaintype=kvm . Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: [Code-8] [Domain-44] invalid argument: could not find capabilities for domaintype=kvm
You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by naveenmajumdar** [comment]
[log.txt](https://github.com/minishift/minishift/files/2375871/log.txt)

Here is the windows logs

**Comment by naveenmajumdar** [comment]
-- minishift version: v1.21.0+a8c8b37
-- Starting profile 'minishift'
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:44540
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Failed to fetch machine
(minishift) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(minishift) DBG | [signal 0xb code=0x1 addr=0x0 pc=0x4d7167]
(minishift) DBG |
(minishift) DBG | goroutine 13 [running]:
(minishift) DBG | panic(0x8c54a0, 0xc82000a100)
(minishift) DBG |       /usr/local/go/src/runtime/panic.go:464 +0x3e6
(minishift) DBG | github.com/alexzorin/libvirt-go.(*VirDomain).GetState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
(minishift) DBG |       /home/daniel/go/src/github.com/alexzorin/libvirt-go/domain.go:192 +0x87
(minishift) DBG | github.com/dhiltgen/docker-machine-kvm.(*Driver).GetState(0xc82012c0e0, 0x0, 0x0, 0x0)
(minishift) DBG |       /home/daniel/go/src/github.com/dhiltgen/docker-machine-kvm/kvm.go:450 +0x70
(minishift) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).GetState(0xc8200ddba0, 0xe0d430, 0xc820152080, 0x0, 0x0)
(minishift) DBG |       /home/daniel/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:191 +0x45
(minishift) DBG | reflect.Value.call(0x8858a0, 0x93fe88, 0x13, 0x959cd0, 0x4, 0xc820034ef8, 0x3, 0x3, 0x0, 0x0, ...)
(minishift) DBG |       /usr/local/go/src/reflect/value.go:435 +0x120d
(minishift) DBG | reflect.Value.Call(0x8858a0, 0x93fe88, 0x13, 0xc820034ef8, 0x3, 0x3, 0x0, 0x0, 0x0)
(minishift) DBG |       /usr/local/go/src/reflect/value.go:303 +0xb1
(minishift) DBG | net/rpc.(*service).call(0xc820013b00, 0xc8200138c0, 0xc82000b7e0, 0xc8200a3680, 0xc82014a2a0, 0x7e14a0, 0xe0d430, 0x16, 0x89fca0, 0xc820152080, ...)
(minishift) DBG |       /usr/local/go/src/net/rpc/server.go:383 +0x1c2
(minishift) DBG | created by net/rpc.(*Server).ServeCodec
(minishift) DBG |       /usr/local/go/src/net/rpc/server.go:477 +0x49d
Error getting machine state: unexpected EOF
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ...
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM ...Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
.Plugin server listening at address 127.0.0.1:38819
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Failed to fetch machine
(minishift) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(minishift) DBG | [signal 0xb code=0x1 addr=0x0 pc=0x4d7167]
(minishift) DBG |
(minishift) DBG | goroutine 13 [running]:
(minishift) DBG | panic(0x8c54a0, 0xc82000a100)
(minishift) DBG |       /usr/local/go/src/runtime/panic.go:464 +0x3e6
(minishift) DBG | github.com/alexzorin/libvirt-go.(*VirDomain).GetState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
(minishift) DBG |       /home/daniel/go/src/github.com/alexzorin/libvirt-go/domain.go:192 +0x87
(minishift) DBG | github.com/dhiltgen/docker-machine-kvm.(*Driver).GetState(0xc82012c0e0, 0x0, 0x0, 0x0)
(minishift) DBG |       /home/daniel/go/src/github.com/dhiltgen/docker-machine-kvm/kvm.go:450 +0x70
(minishift) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).GetState(0xc8200ddba0, 0xe0d430, 0xc820152080, 0x0, 0x0)
(minishift) DBG |       /home/daniel/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:191 +0x45
(minishift) DBG | reflect.Value.call(0x8858a0, 0x93fe88, 0x13, 0x959cd0, 0x4, 0xc820034ef8, 0x3, 0x3, 0x0, 0x0, ...)
(minishift) DBG |       /usr/local/go/src/reflect/value.go:435 +0x120d
(minishift) DBG | reflect.Value.Call(0x8858a0, 0x93fe88, 0x13, 0xc820034ef8, 0x3, 0x3, 0x0, 0x0, 0x0)
(minishift) DBG |       /usr/local/go/src/reflect/value.go:303 +0xb1
(minishift) DBG | net/rpc.(*service).call(0xc820013b00, 0xc8200138c0, 0xc82000b7e0, 0xc8200a3680, 0xc8201462a0, 0x7e14a0, 0xe0d430, 0x16, 0x89fca0, 0xc820152080, ...)
(minishift) DBG |       /usr/local/go/src/net/rpc/server.go:383 +0x1c2
(minishift) DBG | created by net/rpc.(*Server).ServeCodec
(minishift) DBG |       /usr/local/go/src/net/rpc/server.go:477 +0x49d
 FAIL E0912 12:34:53.304319    2385 start.go:416] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
Error starting the VM: Error getting the state for host: unexpected EOF

**Comment by anjannath** [comment]
Have you turned on virtualization support from the BIOS, It looks like that
is the issue here, that's why minishift is not able to create the VM. hth

**Comment by praveenkumar** [comment]
@naveenmajumdar have a look to https://github.com/minishift/minishift/issues/1630 and comments, looks quite similar.

**Comment by naveenmajumdar** [comment]
Hello Praveen 

u right KVM not supported msg showing on dmesg.

i am using VT enable hardware win10 loaded and i have configured coco to install minishift over hyper-v but that not working so i have uninstall the hyper-v and install VirtualBox and still facing the issue to install minishift. 


![image](https://user-images.githubusercontent.com/15050158/45542565-e339f480-b82f-11e8-80e7-f8946fbdfb81.png)

**Comment by praveenkumar** [comment]
@naveenmajumdar If I am not wrong here you want to try the minishift inside a virtualmachine which is running the Linux system so this is not supported since this need nested virtualization. why don't you try minishift directly on your host?

**Comment by gbraad** [comment]
You are attempting to run nested virtualization? this is not supported from us... you might be able to get this to work on Hyper-V or KVM, but for VirtualBox you would have to look at their forums.

I suggest closing this issue.

**Comment by gbraad** [comment]
As suggested, use directly on your host as we are able to interface with `vbox` as a driver. This will create a new VM alongside of the one you tried this on. Or you can use to run on the existing VM with the `generic` driver; which is explained in the documentation on the heading "existing machine".

Closing as this is not an issue

**Comment by habeebimbola** [comment]
Hi everyone.
My name is Habeeb.
I have been trying to set up Minishift on Machine for a while now and unsuccessful. I have tried a couple of suggestions to get it up and running but unsuccessful. I will be glad if anyone can assist me.
Attached to this message are ScreenShots from installations and set up.
![Screenshot from 2021-09-09 13-44-54](https://user-images.githubusercontent.com/18697937/132689924-963803bf-3a9a-41db-98a4-51bbc4f9e6cf.png)
![Screenshot from 2021-09-09 13-45-32](https://user-images.githubusercontent.com/18697937/132689935-2449472c-4969-4d18-a348-58754292ff1f.png)
![Screenshot from 2021-09-09 13-53-14](https://user-images.githubusercontent.com/18697937/132689942-cfc9990f-74d2-4952-9914-cb72741d93ab.png)

**Comment by habeebimbola** [comment]
![Screenshot from 2021-09-09 14-06-49](https://user-images.githubusercontent.com/18697937/132691399-fd7aa6ae-7b92-4646-8059-cdab71648de8.png)
My Machine Model ^^
