### ISSUE TITLE
Jenkins image openshift/jenkins is deprecated

### ISSUE THREAD

**Issue by lioramilbaum** [minishift/minishift#2806]
### General information

  * Minishift version: 
minishift v1.24.0+8a904d0
  * OS: Linux / macOS / Windows
LInux
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox
KVM

### Steps to reproduce

Deployed Jenkins from the service catalog

### Expected

Expected to see the jenkins LTS deployed

### Actual

Jenkins version 2.107.3, which is far behind.

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@lioramilbaum This templates and image stream is coming from okd side so might be this you should file in the openshift/origin issue. These templates are part of `oc cluster up`

**Comment by lioramilbaum** [comment]
@praveenkumar ok. I will.
