### ISSUE TITLE
Record installs of OpenShift on the persistent disk

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2810]
Several of our issues are related to upgrade that are performed by people, while they are even unaware of this. I would suggest to keep a log on the persistent disk that records the attempts of installing, and possible successes inside the persistent disk `/var/minishift/...`, that executes `before` and `after` deployment. This could aid in pinpointing issues before the deployment happens (indicating that a previous run was performed, and maybe even indicating an upgrade, and if multiple failing attempts were tried).

**Comment by LalatenduMohanty** [comment]
@gbraad It is an interesting proposal. Maybe we can alter users what wrong they did and why the start failed.

**Comment by LalatenduMohanty** [comment]
Keeping it as closed because the change in the scope of Minishift project. We are more focused now to make OpenShift 4.0 working for Minishift usecase.
