### ISSUE TITLE
$KUBECONFIG points to nonexistent file with OS 3.10.0

### ISSUE THREAD

**Issue by amisevsk** [minishift/minishift#2825]
### General information
If minishift is started with OpenShift 3.10.0, the `$KUBECONFIG` env var in the origin container appears to be set incorrectly.

Background: For the [rh-che minishift addon](https://github.com/redhat-developer/rh-che/blob/d3573c5336be4610e0cadf6848b4fe62eb1ce76d/openshift/minishift-addons/rhche-prerequisites/rhche-prerequisites.addon#L16) we have a line `ssh docker exec origin /bin/bash -c 'oc create [...]'`. This command will fail with the error 

```
Error applying the add-on: Error executing command 'ssh command error:
command : docker exec origin /bin/bash -c 'oc create secret generic openshift-identity-provider -n rhche --from-literal=username='-' --from-literal=password='-' --from-file=ca-cert=./openshift.local.config/master/ca.crt --type=kubernetes.io/basic-auth'
err     : exit status 1
output  : error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
```
Adding `export KUBECONFIG=/var/lib/origin/openshift.local.config/master/admin.kubeconfig` to the `docker exec` command seems to work, although I haven't fully tested it. 

### Version

  * Minishift `minishift v1.24.0+8a904d0`
  * OS: Linux (Fedora 29)
  * Hypervisor: KVM

### Steps to reproduce

  1. `minishift start --openshift-version 3.10.0`
  2. `eval $(minishift docker-env)`
  3. `docker exec origin /bin/bash -c 'ls ${KUBECONFIG}'`

### Expected
`$KUBECONFIG` points to a file that exists. e.g. with OpenShift 3.9.0, 
```
KUBECONFIG==/var/lib/origin/openshift.local.config/master/admin.kubeconfig
``` 
(note this file is present in 3.10 as well).

### Actual
File does not exist.

**Comment by praveenkumar** [comment]
@amisevsk Due to lot of refactoring on the origin side and also the images side now that files are not present as it should be (like older release 3.9.0) and that is the reason you are seeing this. Also, I am not sure why you want to `exec` to the `origin` container.

```
ssh docker exec origin /bin/bash -c 'oc -n rhche secret new-basicauth openshift-identity-provider --username='-' --password='-' --ca-cert=./openshift.local.config/master/ca.crt'
```

can be replaced by following. If you don't want to use the replacement then you need to pass the kubeconfig file explicitly as you experiment. 

```
ssh /var/lib/minishift/bin/oc -n rhche secret new-basicauth openshift-identity-provider --username='-' --password='-' --ca-cert=/var/lib/minishift/base/openshift-apiserver/ca.crt
```

**Comment by LalatenduMohanty** [comment]
@praveenkumar in 3.10 the oc binary is in `openshift/origin-control-plane` instead of `origin` image isn't it?

**Comment by praveenkumar** [comment]
> in 3.10 the oc binary is in openshift/origin-control-plane instead of origin image isn't it?

oc binary is part of both the images but `origin-control-plane`  contains the latest bits and `origin`  image is no more maintained.

**Comment by amisevsk** [comment]
@praveenkumar Thanks for the advice, the command you provided works for 3.10. However, when I tried it on 3.9, it fails with `error: open /var/lib/minishift/base/openshift-apiserver/ca.crt: no such file or directory`. Is there a consistent path to the cert between openshift versions?

**Comment by amisevsk** [comment]
@praveenkumar Thanks for the advice, the command you provided works for 3.10. However, when I tried it on 3.9, it fails with `error: open /var/lib/minishift/base/openshift-apiserver/ca.crt: no such file or directory`. Is there a consistent path to the cert between openshift versions?

**Comment by praveenkumar** [comment]
@amisevsk that's what I afraid of the path from 3.9 to 3.10 changes so if you really want to make it work for both versions then try below. why it worked for 3.9 because that time oc was logged in with system:admin for that container but now it's not so explicit kubeconfig file required.

```
ssh docker exec origin /bin/bash -c 'oc --config=/var/lib/origin/openshift.local.config/master/admin.kubeconfig -n rhche secret new-basicauth openshift-identity-provider --username='-' --password='-' --ca-cert=./openshift.local.config/master/ca.crt'
```

**Comment by praveenkumar** [comment]
@amisevsk if you tried the https://github.com/minishift/minishift/issues/2825#issuecomment-424953888 then we can close this issue, we can't do much here in this case.

**Comment by amisevsk** [comment]
@praveenkumar Sorry about the delayed responses -- yeah I'll work something out on our end; this issue can be closed. Likely it'll have to be the last one, pointing directly at the cert in the command.
