### ISSUE TITLE
Create a cat command for addon

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2827]
As of now, we don't have any way to copy a file from host to minishift VM as part of addon. The best what we can have a scp command implemented and that can be used as parent command for minishift and in the addon also. But as of now atleast `cat` command give bit fexibility for addon user/developer. `scp` can be done separately.

```
# Name: admin-user
# Description: Create admin user and assign the cluster-admin role to it.

content := cat test.json
oc patch -f #{content}
```

**Comment by budhram** [comment]
Resolved by https://github.com/minishift/minishift/pull/2831
