### ISSUE TITLE
Create a release job in circle ci for minishift with systemtray

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#2837]
Since we can't build minishift with systemtray in a linux machine, we cannot do the release from centos-ci.

The plan is to have a job in circle ci and the minishift bits with systemtray released as a separate artifact along with the regular bits. This job can be triggered from centos-ci  at the end of the release job(so that `make ci_release` still works), and will edit/update the already made release to also include the bits with systemtray.

/cc @minishift/minishift-dev 

related: #2446

**Comment by budhram** [comment]
@anjannath why priority is `major` here?

**Comment by anjannath** [comment]
@budhram We want to be able to do automated release as soon as possible, and we have until the next release to do it.
Do you think it should have less priority?

**Comment by LalatenduMohanty** [comment]
I agree that the impact is major as it would change the release process for Minishift project.

**Comment by anjannath** [comment]
> @anjannath <https://github.com/anjannath> so for next release onwards we
are going to put minishift binary (with systray stuff in) for windows and
mac and linux would be as it is? or we are planning to have 5 binary (3 as
usual + 2 for systray one mac + win) ?

Five binaries is the plan, at least till we fix all the issues and
implement the other features, but eventually will have to release in a
single binary.

**Comment by LalatenduMohanty** [comment]
Resolved via #2975.
