### ISSUE TITLE
Minishift prerequisite installer for macOS

### ISSUE THREAD

**Issue by coolbrg** [minishift/minishift#2840]
Enhance `minishift setup` command to work in macOS.

**Comment by anjannath** [comment]
Setting up the Virtualization environment in mac for minishift means:
1. We need the xhyve driver binary in PATH, with proper permissions.
2. That's it!

The challenge right now is that the xhyve driver needs to be compiled on the host's version of macOS for it to work. which means we need a working golang dev env setup in the users machine. 

Or we could use machine-drivers org, and release the binary ourselves for every version of macOS (which is not very often) , and use that for this purpose.
