### ISSUE TITLE
Create native Minishift installers for Windows or macOS

### ISSUE THREAD

**Issue by coolbrg** [minishift/minishift#2841]
We need to have a native installers to install Minishift and possibly handle the virtualizaton setup as well

- [ ] Windows Installer - https://github.com/minishift/minishift/issues/907
- [ ] macOS Installer - https://github.com/minishift/minishift/issues/2840

**Comment by budhram** [comment]
@minishift/minishift-dev  I think the command `minishift setup` will work along the line of CDK as well.
Then, we can merge the effort of `minishift setup-cdk` into `minishift setup`.

WDYT?

**Comment by budhram** [comment]
Demo video of OpenShift connector for VS Code https://vimeo.com/293013737

**Comment by praveenkumar** [comment]
https://github.com/redhat-developer-tooling/developer-platform-install/blob/f7e90e4c0dafcf5cbf21e15c4ffb0837ccba4836/browser/model/virtualbox.js#L171-L180 is the block which have detail about how devsuite installer used to run virtualbox installation.

**Comment by LalatenduMohanty** [comment]
> @minishift/minishift-dev I think the command `minishift setup` will work along the line of CDK as well.
> Then, we can merge the effort of `minishift setup-cdk` into `minishift setup`.

+1

**Comment by budhram** [comment]
@LalatenduMohanty @gbraad @praveenkumar , @anjannath A quick flow diagram

![screenshot from 2018-10-15 16-15-29](https://user-images.githubusercontent.com/1132451/46946526-a020aa80-d095-11e8-85b8-ebebb8b8b897.png)

Please review.

**Comment by anjannath** [comment]
A step is missing, after the check for OS there should be a step to check if HyperV is supported, if yes then enable it from Windows Features.. and reboot.. and use that. 

If HyperV is not supported then go for VBox Installation.

**Comment by budhram** [comment]
> A step is missing, after the check for OS there should be a step to check if HyperV is supported then if it is enabled, if not then enable it from Windows Features.. and reboot.. and use that.

`Reboot` might not be good in terms of VS Code adapter scenario. I would like to keep this off at the moment and consider it later.

WDYT @LalatenduMohanty @praveenkumar @gbraad ?

**Comment by coolbrg** [comment]
I think this can be closed as the initial two issues are closed.

**Comment by gbraad** [comment]
The original issue talks about NATIVE installers.
This might still be an issue going ahead... depending on possible
needed dependencies.

I will however close it as it is an old issue and related issue have
been addressed.
If this need arises, we will create new issues.
