### ISSUE TITLE
Minishift with proxy - Error checking and/or regenerating the certs

### ISSUE THREAD

**Issue by simoelmou** [minishift/minishift#2843]
### General information

  * Minishift version: v1.20.0+53c500a
  * OS:  Windows 7
  * Hypervisor:  VirtualBox

### Steps to reproduce
1. minishift delete -f --clear-cache
2. minishift start -v2 --show-libmachine-logs --vm-driver virtualbox --http-proxy http://proxy:3128 --https-proxy http://proxy:3128 --no-proxy localhost,.proxy.fr,127.0.0.1,.proxy.net,192.168.99.100

### Expected
Cluster deployed and to be able to use the console.

### Actual

After configuring proxy information, minishift fails when trying to start openshift.

**When** it fails I stop the VM and start again, then minishift doesn't fail but it gives an error at the end where it doesn't find kube_config file

### Logs

https://gist.github.com/simoelmou/9c7b2a16d86de746e83b3f1aea566971

**Comment by praveenkumar** [comment]
@simoelmou you are using an older version of minishift, there has been lot of improvement around proxy, can you try to use the latest version of minishift and do the following?

Also I am not sure why `192.168.99.100` IP is part of no proxy list, `localhost, 127.0.0.1` always part of default no proxy list when proxy is used?

```
$ minishift delete -f 
minishift start -v5 --show-libmachine-logs --vm-driver virtualbox --http-proxy http://proxy:3128 --https-proxy http://proxy:3128 --no-proxy .proxy.fr,.proxy.net
```

**Comment by simoelmou** [comment]
Always the same error, here are the logs: https://gist.github.com/simoelmou/7a6265f148a6a187174f498111138213

I tested with Openshift v3.10.0 and v3.9.0

**Comment by praveenkumar** [comment]
@simoelmou can you paste the end to end logs which also include the command which you run and till it is error out? Something we are not able to reproduce atm :(

**Comment by praveenkumar** [comment]
@simoelmou even it is failed can you do the following and let us know the result?

```
$ minishift ssh
$ cat /etc/os-release
$ systemctl status docker
```

**Comment by simoelmou** [comment]
**[docker@minishift ~]$** cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

VARIANT="minishift"
VARIANT_VERSION="1.12.0"
BUILD_ID="cf9f525-10072018102759-local"

**[docker@minishift ~]$** systemctl status docker
\* docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           `-10-machine.conf
   Active: active (running) since Wed 2018-10-03 07:38:19 EDT; 1min 59s ago
     Docs: http://docs.docker.com
  Process: 1749 ExecStartPre=/usr/local/bin/minishift-cert-gen (code=exited, status=0/SUCCESS)
 Main PID: 1751 (dockerd-current)
   CGroup: /system.slice/docker.service
           |-1751 /usr/bin/dockerd-current -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --selinux-enabled --log-driver=journald --signature-verification=fals...

           `-1757 /usr/bin/docker-containerd-current -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-d...

**Comment by praveenkumar** [comment]
@simoelmou everything as per logs looks good, Can you tell which version of virtualbox are you using?

@amitkrout @agajdosi which version of virtual box we test our bits?

**Comment by simoelmou** [comment]
I'm using virtualbox 5.1.28

**Comment by praveenkumar** [comment]
@simoelmou Can you clean up virtualbox 5.1.28 and try to install VB-5.2.18? Also are you using the VPN? if yes then first can you try to disconnect from the VPN and then try again?

@amitkrout Can you test this with proxy + VBox and see if reproducible?

**Comment by amitkrout** [comment]
@praveenkumar We always verify out bits on latest VirtualBox release. So bits are tested on VirtualBox Version 5.2.18.

Sure will verify it

**Comment by amitkrout** [comment]
@simoelmou @praveenkumar i am not able to reproduce it on win10+VirtualBox 5.2.18+minishift 1.20.0+proxy. @agajdosi can you please check it on win7

@simoelmou can you also check it with latest minishift release

**Comment by simoelmou** [comment]
@amitkrout I'm using Windows 7 + VirtualBox 5.2.18 + minishift 1.24.0 + Company proxy + Openshift 3.10.0 / 3.9.0

**Comment by simoelmou** [comment]
@amitkrout @praveenkumar I tested with that config and always the same error and logs

**Comment by simoelmou** [comment]
@praveenkumar I'm not using a VPN

**Comment by simoelmou** [comment]
@praveenkumar is there any fix ? I don't know if the proxy is causing the issue or it's coming from minishift...

**Comment by praveenkumar** [comment]
@agajdosi @amitkrout Can you folks try Windows 7 + VirtualBox 5.2.18 + minishift 1.24.0 + proxy + Openshift 3.10.0 combination and see it that works?

@simoelmou also if you have any personal laptop can you try on that without the proxy and see if that works. I didn't able to find out why this error is occurring. I did check on minikube side but there also no resolution for this.

@gbraad got any idea here?

**Comment by agajdosi** [comment]
Was not able to reproduce the issue on Win7 machine with VirtualBox 5.2.18 + minishift 1.24.0 + proxy + Openshift 3.10.0

**Comment by gbraad** [comment]
can you verify the content of your `.minishift` folder.

like 


`ls -al `/.minishift` and `ls -al ~/.minishift/certs`

**Comment by simoelmou** [comment]
**ls -al ~/.minishift :** 
total 48
drwxr-xr-x 1 USER 1049089    0 Oct  5 09:33 ./
drwxr-xr-x 1 USER 1049089    0 Oct  3 10:57 ../
drwxr-xr-x 1 USER 1049089    0 Oct  2 11:51 addons/
-rw-r--r-- 1 USER 1049089 1038 Oct  8 10:00 ca.pem
drwxr-xr-x 1 USER 1049089    0 Oct  5 09:33 cache/
-rw-r--r-- 1 USER 1049089 1078 Oct  8 10:00 cert.pem
drwxr-xr-x 1 USER 1049089    0 Oct  2 12:08 certs/
drwxr-xr-x 1 USER 1049089    0 Oct  2 11:51 config/
-rw-r--r-- 1 USER 1049089 1675 Oct  8 10:00 key.pem
drwxr-xr-x 1 USER 1049089    0 Oct  2 16:34 logs/
drwxr-xr-x 1 USER 1049089    0 Oct  8 09:58 machines/
drwxr-xr-x 1 USER 1049089    0 Oct  2 16:34 profiles/
drwxr-xr-x 1 USER 1049089    0 Oct  2 11:51 tmp/

**ls -al ~/.minishift/certs :** 
total 20
drwxr-xr-x 1 USER 1049089    0 Oct  2 12:08 ./
drwxr-xr-x 1 USER 1049089    0 Oct  5 09:33 ../
-rw-r--r-- 1 USER 1049089 1679 Oct  2 12:08 ca-key.pem
-rw-r--r-- 1 USER 1049089 1038 Oct  2 12:08 ca.pem
-rw-r--r-- 1 USER 1049089 1078 Oct  2 12:08 cert.pem
-rw-r--r-- 1 USER 1049089 1675 Oct  2 12:08 key.pem

**Comment by praveenkumar** [comment]
@simoelmou can you try below and let us know the result?

```
$ minishift delete -f
$ rm -fr ~/.minishift/*.pem ~/.minishift/certs
$ ls -al ~/.minishift => shouldn't have any *.pem file and certs directory
$ minishift start
```

**Comment by simoelmou** [comment]
@praveenkumar I have tried that and it's the same error.
logs: https://gist.github.com/simoelmou/149d4a44b5470d316a987171d0026471
**Using OCP 3.9.0 after stop > start it shows :** 
`Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to the kube config 'C:\Utilisateurs\user\.minishift\machines\minishift_kubeconfig' does not exist`
**Using OCP 3.10.0 after stop > start it shows :** 
```
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Pulling image openshift/origin-control-plane:v3.10
Image pull complete
Pulling image openshift/origin-cli:v3.10
Pulled 1/4 layers, 28% complete
Pulled 2/4 layers, 51% complete
Pulled 3/4 layers, 80% complete
Pulled 4/4 layers, 100% complete
[...]
I0801 17:31:31.838764    3644 interface.go:41] Finished installing "sample-templates/mariadb" "sample-templates/postgresql" "sample-templates/cakephp quickstart" "sample-templates/dancer quickstart" "sample-templates/sample pipeline" "sample-templates/mongodb" "sample-templates/django quickstart" "sample-templates/nodejs quickstart" "sample-templates/rails quickstart" "sample-templates/jenkins pipeline ephemeral" "sample-templates/mysql"
E0801 17:36:30.854286    3644 interface.go:34] Failed to install "openshift-web-console-operator": timed out waiting for the condition
I0801 17:36:30.854328    3644 interface.go:41] Finished installing "openshift-web-console-operator" "centos-imagestreams" "openshift-image-registry" "openshift-router" "sample-templates" "persistent-volumes
```

**Comment by rdepke** [comment]
I have the same issue, when I try to start minishift, while connected to our corporate VPN
**My Setup:**
Windows 10 1709
VirtualBox 5.2.18
minishift 1.25
I have to use a corporate proxy server which is configured via windows env vars
VPN: Juniper Networks \ Network Connect 8.1

*Log*
Here a two log files. One is the working case, when I am not connected via VPN. The second is the error case, when I use VPN.
[minishift_working.txt](https://github.com/minishift/minishift/files/2455958/minishift_intern_v8.txt)
[minishift_error.txt](https://github.com/minishift/minishift/files/2455959/minishift_vpn_v8.txt)

**Comment by praveenkumar** [comment]
> I have tried that and it's the same error.

@simoelmou This is no the same what you were getting at the beginning, now atleast your first start is working as expected and failure only happen when you are doing stop => start. why do you think it is the same error?

**Comment by praveenkumar** [comment]
@rdepke In case of VPN we do have some known issue but can you also try https://github.com/minishift/minishift/issues/2843#issuecomment-427777097 with VPN and let us know if first start successful for you?

**Comment by simoelmou** [comment]
@praveenkumar I said in both cases it fails, just not the same error. For the first start the error is with Regenerating certs, and after stop > start the error changes depending on the version of Openshift.

**Comment by praveenkumar** [comment]
> I said in both cases it fails, just not the same error. For the first start the error is with Regenerating certs, and after stop > start the error changes depending on the version of Openshift.

@simoelmou That is complete wired because if during the fresh start error happen with regenerating the certs, that shouldn't be fix automatic by stopping it and starting again :( , something surely we are missing here. So your first start again failed with regenerate certs even after you removed the certs  as I mentioned in https://github.com/minishift/minishift/issues/2843#issuecomment-427777097 here?

**Comment by LalatenduMohanty** [comment]
@simoelmou Which time zone you are in? Maybe we can do a desktop sharing session and try to debug your setup. Please join the #minishift IRC on Freenode.

**Comment by simoelmou** [comment]
@praveenkumar Yes even after minishift delete -f and I removed the certs folder and *.pem files in .minishift, the same error shows up.

**Comment by simoelmou** [comment]
@LalatenduMohanty Okay I'll ping you there.

**Comment by rdepke** [comment]
@praveenkumar I deleted the certs, as described, but the error stays the same.

**Comment by rdepke** [comment]
I changed the directory where minishift looks for the certs. 
libmachine.go 70-73
With that change minishifts starts, while connected to vpn. So my guess is right now, that windows directory access rights, are kinda messed up because of the vpn.

**Comment by gbraad** [comment]
Can you link to the lines here ? 

Would wonder how the VPN can influence this... Or the response from the pluginserver is maybe not as expected (a missed error state?)

**Comment by rdepke** [comment]
I just hardcoded a path. I also wondering, how the VPN influences this. I tried to find any hints, with "Process Monitor" but I did not come to any result yet.
`				CaCertPath:       filepath.Join("C:\\Data\\minishift-certs", "ca.pem"),
				CaPrivateKeyPath: filepath.Join("C:\\Data\\minishift-certs", "ca-key.pem"),
				ClientCertPath:   filepath.Join("C:\\Data\\minishift-certs", "cert.pem"),
				ClientKeyPath:    filepath.Join("C:\\Data\\minishift-certs", "key.pem"),
	`

**Comment by svenstaro** [comment]
This isn't solved.

**Comment by gbraad** [comment]
See https://github.com/minishift/minishift/issues/2843#issuecomment-428111800. did this work for you? If so, please consider creating a PR for this.

**Comment by svenstaro** [comment]
We stopped using minishift as part of our solution so I'm unlikely to test this particular issue soon.
