### ISSUE TITLE
Run minishift outside a local VM

### ISSUE THREAD

**Issue by jayunit100** [minishift/minishift#2845]
### General information

  * Minishift version:  any 

### Issue

I know this has been discussed, but not sure what the conclusion was.  It would be great for red hat compatibility testing to run minishift on GCE or AWS.  

- Many folks need to confirm all their microservices (some of which may bbe root, need hostPaths, etc...) are runnable on minishift.  For a team with a large app, a cloud VM might neeeded .

- Macs and many other standard laptop style hardware is limited to 4 to 8 cores and 1G to 16G of memory, meaning that unless your apps have < 14G of ram required (and < 4 cores), you tyipcally cant run minishift at all. 

- Virtualbox and other hypervisors Are very difficult to setup and kind of sane CI against, so it would help in evolving minishift over time with  automation tests.

- Minikube actually supports a 'linux only' mode, which runs minikube on linux w/o making a VM, this might be the most fundamentally valueable thing to have, to start with.

**Comment by LalatenduMohanty** [comment]
@jayunit100 we have already implemented this using `--vm-driver generic` https://docs.okd.io/latest/minishift/using/run-against-an-existing-machine.html

Please give it a spin and let us know.

**Comment by LalatenduMohanty** [comment]
@jayunit100 I am going close this as this feature is available already. Please put a comment to reopen if you disagree and open new issues if you encounter any new ones.
