### ISSUE TITLE
Start/Stop of profile from the tray does not work as expected in windows

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#2848]
Some time after the tray has started, trying to start or stop a profile from it in windows opens up cmd prompt showing the localhost ip address with some random port number.

https://github.com/minishift/minishift/wiki/Known-issues#windows
Ref: https://github.com/minishift/minishift/pull/2633#issuecomment-425339621

![image](https://user-images.githubusercontent.com/8885742/46394269-3c49c980-c706-11e8-8720-70e16aa0706c.png)

**Comment by LalatenduMohanty** [comment]
Removed the critical tag because this feature(system tray) is not available to users yet.
