### ISSUE TITLE
Enhancements/features list for the system tray

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#2849]
This issue is for tracking enhancement related issues for the tray...

For starters:
- [ ] An option to restart the running openshift deployment [equivalent to `minishift openshift restart`].
- [ ] Open the OpenShift web console (#3055)
- [ ] Way to start tray without starting the cluster (#3054)
- [ ] The awareness that an update is available and perform an update
- [ ] Open a terminal window with right env setup for oc and working with openshift
- [ ] About (version, link to website/issues/support/help)

 
Please add more or provide comments and suggestions @minishift/minishift-dev

**Comment by LalatenduMohanty** [comment]
@anjannath This has less priority as compared to making systemtray a GA feature is of more priority. So we should think about this post GA of systemtray.

**Comment by anjannath** [comment]
@LalatenduMohanty Right, need to fix #2848 before this.

**Comment by sspeiche** [comment]
I think having a restart option and a way to launch the web console are great initial options.

Some other things that would be useful:

* The awareness that an update is available and perform an update
* Open a terminal window with right env setup for oc and working with openshift
* About (version, link to website/issues/support/help)
