### ISSUE TITLE
--iso-url is not used to bootstrap the VM with minishift create

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#285]
Using minishift 1.0.0-beta.2 

When I create a new vm using this command

````
minishift start --iso-url=https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-beta.1/minishift-centos.iso --memory=6000 --openshift-version=v1.4.0-rc1 --docker-env=[storage-driver=devicemapper] --vm-driver=virtualbox
````
the VM created still relies on boot2docker.iso

![screenshot 2017-01-12 18 59 30](https://cloud.githubusercontent.com/assets/463790/21901795/74847360-d8f9-11e6-9e5d-d14ebcea948b.png)

**Comment by agajdosi** [comment]
Can verify this with minishift beta2, centos beta1 and kvm on Fedora 24. However this is my case "only" a bad naming - I am able to run "minishft ssh" and see that it is running CentoOS not boot2docker. I think this can be also your case.

**Comment by hferentschik** [comment]
@cmoulliard, I think @agajdosi is right. Can you verify the VM the way @agajdosi describes. It think it comes down to how Minishift stores the ISO in the _~/.minishift/cache/iso_ directory. I know this code is not quite right yet, especially since we are having multiple ISOs to chose from now. Definitely something I want to address asap.

**Comment by cmoulliard** [comment]
Centos ISO is used

```
more /proc/version
Linux version 3.10.0-514.2.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Dec 6 23:06:41 UTC 2016
```

**Comment by LalatenduMohanty** [comment]
I observed two things. 
1. The `isoPath` when VMs are created using the ISO name as boot2docker.iso. So irrespective of the ISO you will see boot2docker attached to the VM. Which we need to fix.

2. Looks like some issue in the code when I am using --iso-url to point to a https:// location in `minishift start` it is not caching in ~/.minishift/iso directory.

```
│   ├── iso
│   ├── oc
│   │   └── v1.4.0-rc1
│   │       └── oc
│   └── openshift
```

**Comment by praveenkumar** [comment]
I did bit of digging around it and some of observations are below.

1. https://github.com/docker/machine/blob/master/libmachine/mcnutils/b2d.go#L25 is main reason why it always boot2docker.iso and currently we don't have any provision from minishift side.

2. Minishift will not cache iso if you use `file://<iso_path>` as value for `--iso-url` parameter check https://github.com/minishift/minishift/blob/master/pkg/minikube/cluster/cluster.go#L234 but if you use `http://` uri then it does cache with the expected image name.

I will try to find a way how we can manipulate that `defaultISOFilename`

**Comment by hferentschik** [comment]
@praveenkumar what's the state on this?

**Comment by cmoulliard** [comment]
Using minishift v1.2.0, I get these errors if I try to create a VM on Virtualbox VM. As you can see minishift still wants to use boot2docker

```
minishift start --iso-url https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0/minishift-centos7.iso --vm-driver virtualbox
Starting local OpenShift cluster using 'virtualbox' hypervisor...
E0628 08:24:57.516184    3748 start.go:275] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: /usr/local/bin/VBoxManage storageattach minishift --storagectl SATA --port 0 --device 0 --type dvddrive --medium /Users/dabou/.minishift/machines/minishift/boot2docker.iso failed:
VBoxManage: error: Could not get the storage format of the medium '/Users/dabou/.minishift/machines/minishift/boot2docker.iso' (VERR_NOT_SUPPORTED)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 179 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/Users/dabou/.minishift/machines/minishift/boot2docker.iso"
. Retrying.
E0628 08:38:00.636805    3748 start.go:275] Error starting the VM: Error starting stopped host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
```

**Comment by praveenkumar** [comment]
@cmoulliard I think in your case you started a stoped `minishift` VM not a clean one. Can you please do `minishift delete` and then `minishift start --iso-url https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0/minishift-centos7.iso --vm-driver virtualbox` so that it will start clean?

**Comment by praveenkumar** [comment]
> @praveenkumar what's the state on this?

@hferentschik we can't do much because variable name is not something we can modify. I did check with minikube and have same iso naming. I would suggest to close this issue.

**Comment by hferentschik** [comment]
@praveenkumar fair enough then. +1 for closing this issue.

**Comment by cmoulliard** [comment]
Same error even if the VM is deleted

```
minishift delete
The execution of this command requires an existing 'minishift' VM. However, there is currently none defined.

minishift start --iso-url https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0/minishift-centos7.iso --vm-driver virtualbox
Starting local OpenShift cluster using 'virtualbox' hypervisor...
E0628 10:12:45.937958    5002 start.go:275] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: /usr/local/bin/VBoxManage storageattach minishift --storagectl SATA --port 0 --device 0 --type dvddrive --medium /Users/dabou/.minishift/machines/minishift/boot2docker.iso failed:
VBoxManage: error: Could not get the storage format of the medium '/Users/dabou/.minishift/machines/minishift/boot2docker.iso' (VERR_NOT_SUPPORTED)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 179 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/Users/dabou/.minishift/machines/minishift/boot2docker.iso"
. Retrying.
```

**Comment by cmoulliard** [comment]
gist available : https://gist.github.com/cmoulliard/c439a909b713545d111b7b3b6a19df4b

**Comment by praveenkumar** [comment]
As per chat we found out that @cmoulliard using a corrupted iso image and with  `minishift delete --clean-cache` he is able to start minishift with provided iso. Closing this issue now.
