### ISSUE TITLE
Automatically set minshift VM timezone to Host timezone

### ISSUE THREAD

**Issue by kameshsampath** [minishift/minishift#2854]
### General information

Setting Timezone of minishift vm and host becomes very important, especially applications are time sensitive.

  * Minishift version: any
  * OS: any
  * Hypervisor: any

### Steps to reproduce

  1.  minishift start
  2. minishift ssh `timectl` 

### Expected

Timezone of minishift VM should be same as that of host  

### Actual

Timezone of minishift vm is not same as that of host

**Comment by LalatenduMohanty** [comment]
Also we have https://github.com/minishift/minishift/issues/1906 related to timezone in the VM

**Comment by praveenkumar** [comment]
@kameshsampath All we care about syncing the time between host and VM not the timezone right. I mean in the VM if the time is not as expected to the zone but it is in sync with host, would that be any problem?

**Comment by kameshsampath** [comment]
@praveenkumar few doubts
-  just wondering if we need to add the `--list` sub-option as well to this command that will list the timezone names available from guest vm ??
- also when do e.g. `minishift start --timezone "Asia/Kolkatta" ` will this be set to the VM before it starts  so that oc cluster up and other pods be in synch with timezone setting ?

**Comment by praveenkumar** [comment]
> just wondering if we need to add the --list sub-option as well to this command that will list the timezone names available from guest vm ??

@kameshsampath yes this something you can check when your VM is up and running.

> also when do e.g. minishift start --timezone "Asia/Kolkatta" will this be set to the VM before it starts so that oc cluster up and other pods be in synch with timezone setting ?

@kameshsampath right this is what we have, try out artifact from https://ci.appveyor.com/project/budhrg/minishift/build/1994/artifacts which have option for timezone and let me know that what you expected/wanted.

**Comment by gbraad** [comment]
as mentioned before, we can have custom commands defined that can be executed from the ISO on boot (by either using rc.local or our own systemd unit). These commands will be stored in a file that lives on the persistent disk... and when exists, will be parsed/executed. this could include some setup commands like timezones or even adding specific configs all over the place as the user sees fit in that case.

Also, why not use the Zulu time or UTC timezone as default?

**Comment by praveenkumar** [comment]
> as mentioned before, we can have custom commands defined that can be executed from the ISO on boot (by either using rc.local or our own systemd unit). These commands will be stored in a file that lives on the persistent disk... and when exists, will be parsed/executed. this could include some setup commands like timezones or even adding specific configs all over the place as the user sees fit in that case.

@gbraad how the running commands in the VM get to know what the timezone host have? My understanding about this issue is user suppose to get the similar timezone as his/her host.

> Also, why not use the Zulu time or UTC timezone as default?

What does that resolve for user?

**Comment by kameshsampath** [comment]
@gbraad 

> Also, why not use the Zulu time or UTC timezone as default?
When deploying applications and using some cloud services of specific zone in my case say from India and the service being time sensitive then having alternate timezone other than host timezone will cause issue.
