### ISSUE TITLE
Choosing ISO document is still show b2d as default.

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2865]
We need to fix https://docs.okd.io/latest/minishift/using/basic-usage.html#choosing-iso-image

**Comment by anjannath** [comment]
This got fixed with https://github.com/minishift/minishift/commit/8af2a4cb97fcffb53f2b9d76f896f296e277dff1 the docs site isn't updated yet though!

Issue https://github.com/minishift/minishift/issues/2857 PR https://github.com/minishift/minishift/pull/2856
