### ISSUE TITLE
Reorganize Documentation getting-started/setting-up-virtualization-environment for Linux

### ISSUE THREAD

**Issue by rhnvrm** [minishift/minishift#2866]
As per the discussion in #2117, it would help new comers if the organization of the doc page could be made smoother by adding separate heads for the OS and under them list the driver followed by steps for each distro.

Link: https://docs.openshift.org/latest/minishift/getting-started/setting-up-virtualization-environment.html

I would be up for contributing, if this seems useful to others.

Thanks

**Comment by praveenkumar** [comment]
@rhnvrm go ahead and put a PR for same. cc @robin-owen
