### ISSUE TITLE
Implement proxy support for VM registration 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#287]
As a preparation for issue #90 which is about enabling proxies for Docker/OpenShift, we also need to be able to register a VM via a proxy. Adding this, will provide the Minishift flags and infrastructure needed for enabling proxies for Docker/OpenShift.

**Comment by jorgemoralespou** [comment]
@praveenkumar @hferentschik please, align with minikube to the options/commands that are implemented in minikube, as we need to have the same experience, even if the code would not be shared.

https://github.com/kubernetes/minikube#using-minikube-with-an-http-proxy

**Comment by praveenkumar** [comment]
@jorgemoralespou In minikube it just set docker proxy variable not VM specific which we need for registration and for oc binary. Now if we want to align it then we need to extract docker env and iterate to get proxy key then set it for oc and registration I think we should send a patch for minikube to allign with minishift for proxy stuff wdyt?

**Comment by hferentschik** [comment]
> In minikube it just set docker proxy variable not VM specific which we need for registration and for oc binary

Right in Minikube they use the already existing 'docker-env' command. That won't cut it for us. We do actually a fair bit more here.

>  I think we should send a patch for minikube to allign with minishift for proxy stuff wdyt?

+1 Let's at least create an issue and discuss. Makes sense to share this code and having the explicit global proxy flags makes sense for Minikube as well.

**Comment by jorgemoralespou** [comment]
@praveenkumar @hferentschik I think that as closer we get the experience with minishift, the easier will be for people to adopt minishift. Many people will hate having some switches for minikube and totally different for minishift.
If we can alter minikube, then it's awesome, but if not I would consider maybe looking into how to best provide the proxy experience with the current minikube experience. Maybe it's not optimal and for this one specific we shouldn't go further, but in the future I would love to see alignment in usage, which means that users would be able to move back and forth between both tools easily. That might mean we need to monitor more minikube and possibly get more involved in that community moving forward.

My 2 cents.

**Comment by hferentschik** [comment]
Resolved via pull request #365
