### ISSUE TITLE
Minishift needs to honour KUBECONFIG 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#2870]
ATM `minishift start` does not honour the _KUBECONFIG_ environment variable. For example,

```
$ export KUBECONFIG=/Users/john/tmp/minishift-kube-config
$ minsihift start
```

The certificate data as well as context for system:admin gets still written into _~/.kube/config_. This prevents me from better controlling my various OpenShift configurations.

**Comment by praveenkumar** [comment]
@hferentschik Right on time :) something @burrsutter was also facing that one. we will try to resolve it soon.
