### ISSUE TITLE
Deleting a Minishift instance should cleanup kubeconfg

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#2872]
Currently when the Minishift instance gets deleted its state as kept in MINISHIFT_HOME gets deleted. However, the kubeconfig under _~/.kube_ stays untouched. This over time clutters the configuration. 

I think it makes sense to clean the kubeconfig the moment the Minishift instance gets deleted.

**Comment by hferentschik** [comment]
Relates to #2870 and #2871.

**Comment by gbraad** [comment]
This is a tricky one, and prefers a solution in which a dedicated
kubeconfig is used for Minishift only. Suggest to only resolve this after
related tasks are handled.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by LalatenduMohanty** [comment]
I think we have looked in to this before and there was no easy way to do it. We should look in to this again.

**Comment by hferentschik** [comment]
> I think we have looked in to this before and there was no easy way to do it. We should look in to this again.

Why should there be no easy way to do it? You know the OpenShift server address you are going to destroy, right? You then access the kubeconfig (potentially taking KUBECONFIG) into account and remove relevant entries from there. 

I've done this now manually multiple times, I don't see why Minishift should not be able to do this.

> This is a tricky one,

How so?

> and prefers a solution in which a dedicated kubeconfig is used for Minishift only

Well, that's #2871. I agree that an option to manage kubeconfig from the start via Minishift is a nice to have. However, imo that's an independent feature.

One can make the config cleanup also an option so that one can introduce this w/o breaking anything:

```
$ minishift delete --cleanup-config
```

**Comment by praveenkumar** [comment]
I think since now we are actually using the kubenetes go-client, it would be easy to do that.

I like to have `--cleanup-config` or any dedicated flag and not having it as part of default. We can put those issues in the next sprint and put effort.

**Comment by gbraad** [comment]
> > This is a tricky one,

> How so?

for the same fact as you have used; you need to strip entries from the
kubeconfig.

On Wed, Oct 10, 2018 at 4:16 PM Hardy Ferentschik
<notifications@github.com> wrote:
>
> I think we have looked in to this before and there was no easy way to do it. We should look in to this again.
>
> Why should there be no easy way to do it? You know the OpenShift server address you are going to destroy, right? You then access the kubeconfig (potentially taking KUBECONFIG) into account and remove relevant entries from there.
>
> I've done this now manually multiple times, I don't see why Minishift should not be able to do this.
>
> This is a tricky one,
>
> How so?
>
> and prefers a solution in which a dedicated kubeconfig is used for Minishift only
>
> Well, that's #2871. I agree that an option to manage kubeconfig from the start via Minishift is a nice to have. However, imo that's an independent feature.
>
> One can make the config cleanup also an option so that one can introduce this w/o breaking anything:
>
> $ minishift delete --cleanup-config
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by hferentschik** [comment]
> I think since now we are actually using the kubenetes go-client, it would be easy to do that.

Sure, that probably helps. However, in the end, this is a quite simple YAML file and all entries are linked together.

> I like to have --cleanup-config or any dedicated flag and not having it as part of default. We can put those issues in the next sprint and put effort.

+1

**Comment by hferentschik** [comment]
>>  This is a tricky one,

> for the same fact as you have used; you need to strip entries from the kubeconfig.

Sure, but what's tricky about this?

**Comment by praveenkumar** [comment]
Resolved by #3088
