### ISSUE TITLE
User should be able to use registry.redhat.io in image streams

### ISSUE THREAD

**Issue by apupier** [minishift/minishift#2875]
### General information

see  https://access.redhat.com/articles/3399531 

for instance here https://github.com/minishift/minishift/blob/58aff7e80b83b291e06b35b423511c1eab50ce69/addons/xpaas/v3.9/xpaas-streams/fis-image-streams.json#L30

be cautious that another authentication is required, it might impact the way to use it.

cc @bparees

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by bparees** [comment]
yeah when minishift makes this change, it needs to also setup credentials in the openshift namespace.  oc cluster up handles this for you as of v3.11 (it will turn your current user's .docker/config.json into credentials in the openshift namespace, so your .docker/config.json needs to contain valid credentials).

**Comment by agajdosi** [comment]
The `registry.redhat.io` starts to appear in newer xpaas templates, we can probably expect it in `eap-cd` and other templates Minishift consumes. Support for login to `registry.redhat.io` should be added.

**Comment by agajdosi** [comment]
As workaround how to get registry.redhat.io to work on OpenShift one can follow these instructions: https://docs.okd.io/latest/dev_guide/managing_images.html#allowing-pods-to-reference-images-from-other-secured-registries

**Comment by apupier** [comment]
> Support for login to `registry.redhat.io` should be added.

Do you want that I open a new issue or you will handle it within this issue?
What I don't get is that we will then put a secret on all OpenShift instances installed with minishift to be able to access the "private" registry.redhat.io. What is the purpose of having a private registry then?

**Comment by agajdosi** [comment]
> Do you want that I open a new issue or you will handle it within this issue?

I think we can handle in this issue.

> What I don't get is that we will then put a secret on all OpenShift instances installed with minishift to be able to access the "private" registry.redhat.io. What is the purpose of having a "private" registry then?

@apupier I am not sure if I understand that correctly. If implemented one could then pull from private registry, however she will still need to log in into the registry before.

ping @LalatenduMohanty I think we should plan this issue for next sprint as templates using registry.redhat.io registry are coming. Increasing prio to critical.

**Comment by apupier** [comment]
> If implemented one could then pull from private registry, however she will still need to log in into the registry before.

having to be logged before seems to be the problem for me.
The best is to not have to log in otherwise it should at least be in the normal flow, ask credentials when they are needed.

**Comment by LalatenduMohanty** [comment]
> having to be logged before seems to be the problem for me.
> The best is to not have to log in otherwise it should at least be in the normal flow, ask credentials when they are needed.

You mean after you are logged in to the registry.redhat.io works for you right?  (logging in will update the ` current user's .docker/config.json` )

``` 
# docker login https://registry.redhat.io
Username: myrhusername
Password:  xxxxxxxxxxx
```

@agajdosi we can try to find out how we can improve the user experience or document this for now. But things are not changing (both the registries will co-exist for few months now ).

**Comment by agajdosi** [comment]
@LalatenduMohanty @praveenkumar I am suggesting to raise the priority of this issue from major to blocker as this issue blocks any template update. For now it blocks: https://github.com/minishift/minishift-addons/issues/176 and https://github.com/minishift/minishift/issues/2879.

**Comment by siamaksade** [comment]
+1 on raising the priority

**Comment by LalatenduMohanty** [comment]
@agajdosi Yes, we will fix it in this sprint.  cc @praveenkumar

**Comment by anjannath** [comment]
Closing this in favour of #3050
