### ISSUE TITLE
Include Fuse 7 images in addon-xpaas

### ISSUE THREAD

**Issue by apupier** [minishift/minishift#2876]
### General information

see https://issues.jboss.org/browse/ENTESB-9557

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by anjannath** [comment]
@agajdosi @LalatenduMohanty Is this still relevant, we have updated xPaaS add-on for many times since then.

**Comment by agajdosi** [comment]
@anjannath Issue seems outdated: we have 6.x, 7.0, 7.1 and 7.2 image streams in xpaas addon right now, thus I am closing this issue. @apupier please feel free to reopen if there is still anything missing in xpaas addon.
