### ISSUE TITLE
Check and improve language of step definitions in Minishift testsuite

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2878]
### General information

On the PR #2869 there were several concerns around language used in step definitions in the Minishift testsuite. I was however not sure whether my fix of current definitions we use would be correct and helpful. As we extract several parameters from the steps/sentences, the language of the steps can be quite strange on some places and harder to be fixed without great knowledge of English...

It would be great if native speaker could get through all of those steps and check whether those can be shortened or made readable more easily, and also whether those are grammatically and logically correct.

**Comment by agajdosi** [comment]
Hi @robin-owen, if you have some time in future and could take a look on this issue it would help us. But it is nothing critical, just nice improvement.

**Comment by LalatenduMohanty** [comment]
@agajdosi Do you want to reopen this ? IMO it is fine to close this issue with respect to the current scope of the project.

**Comment by agajdosi** [comment]
@LalatenduMohanty I agree this can stay closed as it is not necessary.
