### ISSUE TITLE
Update Xpaas addon

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2879]
### General information

Recently there were 2 commits to xpaas, which we should include into xpaas addon:
- https://github.com/openshift/openshift-ansible/commit/f369cf5074bb27d8569b5fe59e974b12430fb351
- https://github.com/openshift/openshift-ansible/commit/55454dd89b0e704ac91abceb6e3936404f0199ad

**Comment by anjannath** [comment]
@agajdosi Also there is #2876

**Comment by LalatenduMohanty** [comment]
@agajdosi I think this is duplicate of https://github.com/minishift/minishift/issues/2483
