### ISSUE TITLE
Inject certificate and host information into openshift containers for https proxy

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2880]
This is related to #2587 and a follow up task. This will allow to inject certificate and (https) proxy information into the containers.

Upon start of a container, an external application will insert the relevant information. For this gbraad/dockerwatch will be used.

**Comment by rdepke** [comment]
@gbraad I would like to test this, as soon as you have it ready

**Comment by gbraad** [comment]
Experience am issue with the filtering I need to perform. Early in the deployment it works as expected, but any other filtering process fails. This means I expect this tomorrow or on Monday.

**Comment by gbraad** [comment]
@jjwallaby this would handle the certificate option

**Comment by gbraad** [comment]
@rdepke I have finished some of the work, but unable to fully test it.

You will need the ISO as mentioned in the first post, and start the PR artifact with `m start --custom-ca-certifcate "/path/to/file/on/disk"`

I will add the artifact location after the build finished

**Comment by yomommais** [comment]
As I have to work behind a corporate proxy, I'm looking forward to using the "--custom-ca-certificate" flag.  I successfully built the branch and I can see the addition in the source code, but it doesn't seem to be an optional flag:

git clone https://github.com/gbraad/minishift.git
cd minishift
git checkout customca
make clean
make
Successfully builds to: $GOPATH/bin

$GOPATH/bin/minishift version
minishift v1.30.0+94a27c82

find . -type f | xargs grep custom-ca-certificate
./cmd/minishift/cmd/config/config.go:	CustomCACertificate = createConfigSetting("custom-ca-certificate", SetString, []setFn{validations.IsValidCertificate}, nil, true, nil)

$GOPATH/bin/minishift start --vm-driver=virtualbox --custom-ca-certificate=/Users/gary/certs/my.pem
...
Error: unknown flag: --custom-ca-certificate

Is this not fully enabled yet on this branch or am I missing something?

Thanks!

**Comment by gbraad** [comment]
You need to enable MINISHIFT_ENABLE_EXPERIMENTAL=true to support this

**Comment by yomommais** [comment]
Seems to still not be aware of it, I tried:

MINISHIFT_ENABLE_EXPERIMENTAL=y $GOPATH/bin/minishift start --extra-clusterup-flags "--enable=*,service-catalog" --vm-driver=virtualbox --custom-ca-certificate="/Users/gar/certs/my.pem" 
...
unknown flag: --custom-ca-certificate

Tried MINISHIFT_ENABLE_EXPERIMENTAL=true as well

Also tried listing as a help option (should it list it?):

MINISHIFT_ENABLE_EXPERIMENTAL=y $GOPATH/bin/minishift start -h | grep custom
Nothing returned...

Thanks.

**Comment by salzs26** [comment]
Hi,

Would it be possible to confirm when the fix for custom ca certificate will be released?

Regards

**Comment by gbraad** [comment]
We are currently working on a new solution aimed towards OpenShift 4.0. Due
to this, not much time has been assigned to work on Minishift; we can only
reserve time for issues that cause deployment to fail from the current
released flow. No new functionality will be added, unfortunately
'experimental features' are therefore not a priority.

You can however test a build with the custom ca options and see if this
fixes your issue. Patches to the PR will be reviewed and merged when
possible.

**Comment by salzs26** [comment]
Thanks! @gbraad for your response.
