### ISSUE TITLE
minishift 1.25 / oc 3.11, web console doesn't come up on Mac OS X

### ISSUE THREAD

**Issue by cunningt** [minishift/minishift#2888]
### General information

  * Minishift version: minishift v1.25.0+90fb23e
  * OS: Mac OS X 10.13.6
  * Hypervisor: xhyve 
 
Using oc 3.11

tcunning@ovpn-123-211:~/src/cunningt/application-templates$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

### Steps to reproduce

  1. minishift start --openshift-version=v3.11.0
  2. minishift console to bring up the web console in a browser
  3. For me, https://192.168.64.145:8443 redirected to https://127.0.0.1:8443/console/, and I got a Unable to connect error

### Expected

The console to load

### Actual

Unable to connect error

### Logs

https://gist.github.com/cunningt/66e92244acad5ee79237031e7e33cbdb

**Comment by anjannath** [comment]
This is an origin issue and has been reported in https://github.com/openshift/origin/issues/21153 and https://github.com/openshift/origin-web-console/issues/3072

We have one more issue for this #2892 @cunningt I am going to close this, we can use #2892 to track this bug.
