### ISSUE TITLE
Remove duplicate message of cluster up during minishift start

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#289]
With PR https://github.com/minishift/minishift/pull/272, there has been duplication of message during `minishift start` for cluster by mistake.

See here https://gist.github.com/budhrg/7734e1310e7046f822db525db700d061#file-rhel_iso_minishift_selinux-sh-L2-L3

**Comment by hferentschik** [comment]
@budhrg Bugger, you are right. Can you take core of this. Was a merge issue. Just a one line change.

**Comment by hferentschik** [comment]
Merged via pull request #290
