### ISSUE TITLE
Minishift ip should print to stderr and exit 1 on error

### ISSUE THREAD

**Issue by chmouel** [minishift/minishift#2893]
It currently exit 0 (i.e: no issues) and print to STDOUT :

```
% minishift ip;echo $?
Running this command requires a running 'local' VM, but no VM is running.
0
```

This would be helpful when scripting,

**Comment by anjannath** [comment]
`minishift ip` command exit with `1` when it is not able to get the IP address provided the VM exists and running.

`ExitIfUndefined` and `ExitIfNotRunning` methods exits with `0`

**Comment by chmouel** [comment]
and why would it exit 0 (i.e: good) if the VM doesn't exist ?

**Comment by gbraad** [comment]
This is actually a duplicate of an earlier issue. I'll look for the issue.

however, when no IP is available ot VM is not running, an error should followed, without the output being `0`

**Comment by chmouel** [comment]
this is still happening, this should exit 1 here,



```bash
% minishift ip ;echo $?
Running this command requires a running 'knative' VM, but no VM is running.
0
```

**Comment by praveenkumar** [comment]
@chmouel it is closed by bot, let me reopen it again and we put that in a sprint.
