### ISSUE TITLE
Break cluster up to write-config and then cluster-up

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2900]
At this moment after VM is provisioned we directly execute `oc cluster up`. I want to add some flags and following flow.

```
$ minishift start --no-provision => exist and does it very well
$ minishift start --write-config => This will just write the cluster up config with whatever parameter user provide as part of start and configs are present in the /var/lib/minishift/base
$ minishift openshift start => this will just do the cluster up using the /var/lib/minishift/base directory as config.
```

All the flags will be behind the experimenting flags and our day to day users are not going to see any change to their flow. This will be helpful for mostly advance users and our own testing purpose. 

We can leverage this to do some other experiment before even implementing.

**Comment by praveenkumar** [comment]
> What will be these parameters (are they oc cluster up config parameters?) and how are we going to pass them?

@anjannath we pass it as expected and just add --write-config flag.

**Comment by anjannath** [comment]
@praveenkumar Where will the config file be written? can we edit this config file to make further modifications to the cluster

**Comment by LalatenduMohanty** [comment]
@praveenkumar I am inclined to close this issue as we moving toward OpenShift 4.0.
