### ISSUE TITLE
Checking if Libvirt default network is present ... FAIL

### ISSUE THREAD

**Issue by magick93** [minishift/minishift#2901]
### General information

  * Minishift version:  minishift v1.25.0+90fb23e

  * OS: Linux  - Ubuntu 18.04
  * Hypervisor: Libvirt

### Steps to reproduce

  1. Download latest release of minishift
  2. Follow instructions as specified on https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#setting-up-kvm-driver
  3. Run `minishift start`

### Expected

Minishift should be running

### Actual

Fails with `-- Checking if Libvirt default network is present ... FAIL`

### Logs

```
sudo virsh net-list --all       
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes

```

```
minishift start --show-libmachine-logs -v5
-- minishift version: v1.25.0+90fb23e
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.10.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.10.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... FAIL
   See the 'Setting Up the Virtualization Environment' topic (https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html) for more information
```

**Comment by gbraad** [comment]
Any update ?

**Comment by gbraad** [comment]
Might there be a way to check if the user has enough permissions?

**Comment by Rajpratik71** [comment]
> 
> 
> @magick93 we don't execute `virsh net-list` as sudo but expect user is part of libvirtd group. You can check https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#setting-up-kvm-driver it does have Ubuntu/Debian section.

This Solution work , as running "minishift" as sudo doesn't throw "Checking if Libvirt default network is present ... FAIL" error.

**Comment by vincenzodnp** [comment]
I solved with `virsh net-start default`
Check before if `default` network is somehow not active with `virsh net-list --all`

**Comment by yogenderPalChandra** [comment]
`sudo minishift start` worked for me.
