### ISSUE TITLE
Put post VM provision to a separate package.

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2902]
Right now we do all the following bits in the start.go or cluster.go but these steps required VM to be up and running.

- proxy setup => putting the proxy in the VM bash
- timezone => if set the execute respective command just after VM creation
- static-ip => if hypervisor support then again we execute some command after VM creation.
- Subscription => This is again executed just after the VM is started.
- Registry Login => Login to registry.redhat.io just after start.

**Comment by gbraad** [comment]
We need a general `post-create`, `post-start` hook. this would make it a lot easier to maintain, however... proxy is also done before the VM start.
