### ISSUE TITLE
Creating an add-on for Knative

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2904]
Evaluating Knative on Minishift involves a lot of steps. Refer https://github.com/knative/docs/blob/44ec5c54080a1e238ab227289219c0daa62ec4ea/install/Knative-with-Minishift.md

We should create a add-on for Knative as it will improve the user experience a lot. 

Related issues #2676 #2787

**Comment by amitkrout** [comment]
@LalatenduMohanty Will it be default addon for minishift ?
