### ISSUE TITLE
Start fails with: Cannot access master readiness URL https://ip:port/healthz/ready

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#291]
**Environment**
OS: RHEL 7.2 Server
Minishift: 1.0.0-beta.2
oc: v1.3.1
CPUs: 16x, RAM: 16GB

**Problem description**
I am unable to do minishift start using boot2docker on RHEL7.2. Start command ends every time on `Error: cannot access master readiness URL https://192.168.42.187:8443/healthz/ready`, also tried it with more cpus and memory with same result. However right after this failure I am able to curl this url which gives me: "ok". Minishift status command gives me: "running". oc command then uses bad ip in configuration - from previous successful minishift start so I am unable to verify if I can log in or deploy something on OpenShift cluster.
For full console log please scroll down.

**Some more notes:**
- I am able to do minishift ssh, seems that boot2docker machine is running fine.
- Tried start - start sequence with same result.
- Sequence start - stop - start is working.
- Minishift start with minishift-centos-iso beta1 works fine.
- This problems appears on quite powerful machine with Xeon E5-2620 with 16cpus, 16GB of ram.

**Failure log:**
```
[hudson@dell-r430-1-cdkqe v1.3.1]$ minishift start --show-libmachine-logs -v 5
...
Plugin server listening at address 127.0.0.1:32871
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetIP
(minishift) DBG | GetIP called for minishift
(minishift) DBG | Fetching VM...
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) DBG | IP address: 192.168.42.187
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:c7:6a:f5
Provisioning OpenShift via '/home/hudson/.minishift/cache/oc/v1.3.1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.3.1 image ... 
   Pulling image openshift/origin:v1.3.1
   Pulled 0/3 layers, 3% complete
   Pulled 1/3 layers, 70% complete
   Pulled 2/3 layers, 90% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.42.187 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
FAIL
   Error: cannot access master readiness URL https://192.168.42.187:8443/healthz/ready
   Details:
     Last 10 lines of "origin" container log:
     I0113 08:49:43.092800    2717 ensure.go:209] Created default security context constraint restricted
     I0113 08:49:43.094688    2717 ensure.go:209] Created default security context constraint anyuid
     I0113 08:49:43.097394    2717 ensure.go:209] Created default security context constraint hostnetwork
     I0113 08:49:43.957820    2717 trace.go:61] Trace "Create /oapi/v1/namespaces/default/rolebindings" (started 2017-01-13 08:49:43.100045201 +0000 UTC):
     [10.232µs] [10.232µs] About to convert to expected version
     [27.242µs] [17.01µs] Conversion done
     [854.489359ms] [854.462117ms] About to store object in database
     [857.722311ms] [3.232952ms] Object stored in database
     [857.727751ms] [5.44µs] Self-link added
     [857.750332ms] [22.581µs] END

E0113 14:18:05.277878    9260 start.go:246] Error starting 'cluster up':  exit status 1
[hudson@dell-r430-1-cdkqe v1.3.1]$ curl https://192.168.42.187:8443/healthz/ready --insecure
ok[hudson@dell-r430-1-cdkqe v1.3.1]$ curl https://192.168.42.187:8443/console/ --insecure
<!doctype html>
...
<title>OpenShift Web Console</title>
...
</html>
[hudson@dell-r430-1-cdkqe v1.3.1]$ minishift ssh
Boot2Docker version 1.11.2, build HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
Docker version 1.11.2, build b9f10c9
docker@minishift:~$ exit
[hudson@dell-r430-1-cdkqe v1.3.1]$ minishift status
Running
```

**Comment by hferentschik** [comment]
Have you checked the OpenShift issue tracker? This looks very much like an OpenShift 'cluster up' issue to me. Not sure what causes it, could be a timing issue.

Regarding, the issue report itself. I know you just want to give all context information possible, but it is really hard to go through all this to even see where the error is. Maybe you could condense this a bit the next time? I don't think for example that a full verbose log '--show-libmachine-logs -v 5' is required at all times, especially since the interesting part lies in the 'cluster up' output. I would have been fine with that and if we need more we can always add more.

**Comment by agajdosi** [comment]
You are right, @hferentschik, edited now.
I tried to search a little bit at OpenShift issues, but did not have enough time. Going to search more on Tuesday, hopefully it is in cluster up.

**Comment by praveenkumar** [comment]
@agajdosi I did a quick look from cluster up side and got 2 issue listed below and both seems to happen because of cert generation. Can you remove ~/.minishift and then try again so that it generate new certs?

- https://github.com/openshift/origin/issues/12337
- https://github.com/openshift/origin/issues/12133

**Comment by jorgemoralespou** [comment]
@praveenkumar Certificate issues should be avoided by having the KUBECONFIG context be properly created for each and every install/start of the cluster. I would not recommend to delete ~/.minishift as a workaround for every action, since eventually there will be too much information in that directory that doing so will break some other clusters (if multi profile get implemented).

**Comment by praveenkumar** [comment]
@jorgemoralespou Thanks to pointing out this. I agree we shouldn't do that and handle it with KUBECONFIG context.  I just want to be sure if that the cert issue or something else.

**Comment by agajdosi** [comment]
@praveenkumar I am deleting ~/.minishift at the beginning of every Jenkins job run. However I tried it manually once more to be sure and it does not help in this case. However last few lines of log are changing sometimes, for this time it is:
```
FAIL
   Error: cannot access master readiness URL https://192.168.42.238:8443/healthz/ready
   Details:
     Last 10 lines of "origin" container log:
     E0118 08:32:44.028793    2798 reflector.go:203] github.com/openshift/origin/vendor/k8s.io/kubernetes/plugin/pkg/admission/limitranger/admission.go:154: Failed to list *api.LimitRange: User "system:openshift-master" cannot list all limitranges in the cluster
     E0118 08:32:44.028802    2798 reflector.go:214] github.com/openshift/origin/vendor/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/resource_access.go:83: Failed to list *api.ResourceQuota: User "system:openshift-master" cannot list all resourcequotas in the cluster
     E0118 08:32:44.036423    2798 reflector.go:214] github.com/openshift/origin/pkg/controller/shared/shared_informer.go:99: Failed to list *api.ClusterResourceQuota: User "system:openshift-master" cannot list all clusterresourcequotas in the cluster
     I0118 08:32:44.464697    2798 ensure.go:209] Created default security context constraint privileged
     I0118 08:32:44.466454    2798 ensure.go:209] Created default security context constraint nonroot
     I0118 08:32:44.468831    2798 ensure.go:209] Created default security context constraint hostmount-anyuid
     I0118 08:32:44.470828    2798 ensure.go:209] Created default security context constraint hostaccess
     I0118 08:32:44.472655    2798 ensure.go:209] Created default security context constraint restricted
     I0118 08:32:44.474448    2798 ensure.go:209] Created default security context constraint anyuid
     I0118 08:32:44.476658    2798 ensure.go:209] Created default security context constraint hostnetwork

E0118 14:01:05.170304   26871 start.go:246] Error starting 'cluster up':  exit status 1
```
I also tried rhel alpha1 image and it has same problem as boot2docker. However it is strange that centos iso is working well.

**Comment by agajdosi** [comment]
@praveenkumar I have updated system to RHEL 7.3. Boot2docker is still unable to start, centos is still fine, but RHEL iso is now working.

**Comment by praveenkumar** [comment]
@agajdosi Let we defer boo2docker as of now and concentrate on RHEL one. We will keep this issue opened until we have a fix for b2d also.

**Comment by budhrg** [comment]
@agajdosi Could you also verify the existence of this issue? Thanks

**Comment by agajdosi** [comment]
@budhrg Sorry for late reply, unfortunately I do not have this environment anymore, after upgrade to RHEL 7.3 this issue disappeared.

**Comment by agajdosi** [comment]
@budhrg I have tried it today with RC1 and this is still an issue. I am not able to reproduce it in VM RHEL 7.3 on my local setup, just with that one particular quite strong machine.
```
   Waiting for API server to start listening
FAIL
   Error: cannot access master readiness URL https://192.168.42.58:8443/healthz/ready
   Details:
     Last 10 lines of "origin" container log:
     I0407 07:50:35.426554    2830 manager.go:288] Starting recovery of all containers
     E0407 07:50:35.435387    2830 kubelet.go:1635] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /
     E0407 07:50:35.435416    2830 kubelet.go:1643] Failed to check if disk space is available on the root partition: failed to get fs info for "root": unable to find data for container /
     I0407 07:50:35.435460    2830 kubelet_node_status.go:74] Attempting to register node 192.168.42.58
     I0407 07:50:35.465401    2830 kubelet_node_status.go:77] Successfully registered node 192.168.42.58
     I0407 07:50:35.475503    2830 manager.go:293] Recovery completed
     E0407 07:50:35.576071    2830 summary.go:70] Partial failure issuing GetContainerInfoV2: partial failures: ["/docker/5ff80473f7ec13508bb83467c24dd631a5170188e5f8651eeeedbda079455973": RecentStats: unable to find data for container /docker/5ff80473f7ec13508bb83467c24dd631a5170188e5f8651eeeedbda079455973]
     I0407 07:50:35.582365    2830 node.go:359] Starting DNS on 0.0.0.0:53
     I0407 07:50:35.582878    2830 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
     I0407 07:50:35.582929    2830 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]

E0407 13:18:29.850946  150903 start.go:410] Error starting the cluster.
[hudson@dell-r430-1-cdkqe ~]$ curl https://192.168.42.58:8443/healthz/ready --insecure
ok
```
BTW this machine is running nightly tests on CDK, so with RHEL iso it has no problem, tested today also again with Centos iso which is still ok.

**Comment by agajdosi** [comment]
Reproducible on another machine with Xeon E5-2650 (25cpus), 16GB ram.

**Comment by jorgemoralespou** [comment]
Adding @csrwng as this seems a problem with oc cluster.

**Comment by praveenkumar** [comment]
@agajdosi Since we latest releases we already have this fixed so closing it now.
