### ISSUE TITLE
Latest minishift detected as malware

### ISSUE THREAD

**Issue by sobkowiak** [minishift/minishift#2911]
### General information

  * Minishift version: 1.25.0
  * OS:  Windows
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. Invoke any command with minishift.exe
  
### Expected

The command is invoked successfully

### Actual

Symantec Anypoint Protection dialog is opened before executing the command

![grafik](https://user-images.githubusercontent.com/803814/47278022-dc886500-d5c5-11e8-9980-b57a610449bc.png)

The previous versions were signed by Red Hat

![grafik](https://user-images.githubusercontent.com/803814/47278048-0cd00380-d5c6-11e8-91d4-a078f639647b.png)

But the latest is not signed 

![grafik](https://user-images.githubusercontent.com/803814/47278062-23765a80-d5c6-11e8-9489-d9388bec7b9e.png)

And the executable is detected as malware. I have got following info from my security department

``` 
SOC team noticed Command and Control domain ummydownloader.com detected for user : ksobkowi and last ip address of system is 10.42.16.43

PFB details of malicious connection.

Endpoint : CE16231

Malicious Files
File Name : minishift.exe
Path : c:\trainings\ocp
Certificate : Not Available
Blocked : No

SOC recommendations:

Kindly contact onsite support team to delete the malicious file and perform below actions:

- Make sure  system has updated with latest Antivirus Signature and Version  
- Make sure system has updated with latest Microsoft patches.
- Remove malicious software’s from system if any.
- Run full system scan and make sure there is no infection.
```

Was it intended that the executable is no more signed?

**Comment by praveenkumar** [comment]
closed in favor of #2914
