### ISSUE TITLE
Add check for up-to-dateness of adopted files

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2919]
### General information

There are few places in Minishift where we adopt external code by copying it into Minishift, for example templates in the xpaas addon. While it is true that we check time to time (mostly with every minor release of OKD) whether templates are up-to-date it is also possible that smaller fixes happens in between the releases of OKD. We should be able to get info about that and react quickly.

**Comment by agajdosi** [comment]
Ideally we should also check whether the drivers we recommend in the docs are latest, or if there are any newer versions released.

**Comment by agajdosi** [comment]
@LalatenduMohanty +1 I even think it probably could only warn, not fail the build. There are some files which can't be updated due to blockers, for example xpaas now, so it would spam us hard then. Warning and taking a look time to time on the results seems fine to me right now.

**Comment by agajdosi** [comment]
I have some work in progress on tool which is made to help us with this issue https://github.com/agajdosi/goard. Right now it can can compare files in local location with remote files, all can be set via YAML config. It needs some polishing and also readme. Will add that if there is some free time next weeks.

**Comment by agajdosi** [comment]
@LalatenduMohanty It is possible some folks could use it as CLI tool. It is however question whether that will really happen. I think that once it is implemented fully we could at least add it under Minishift organization. That way we would have control over it.

Also @LalatenduMohanty I need to add label `quality` to the issue. It is needed by Karel Piwko, who is manager of QE for middleware, to aggregate info about issues planned for K-train. I would not normally introduce new label but it is required to keep consistence across multiple products Karel looks for. Thus I am adding the label now, please let me know if it is a problem.

**Comment by LalatenduMohanty** [comment]
@agajdosi I am against adding label to upstream repository for tracking required for RH.  That tracking needs to be handled differently. Lets talk about it offline.
