### ISSUE TITLE
The latest compatible default ISO should be downloaded automatically

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#292]
ATM a fixed version of the default b2d ISO is downloaded at startup. It would make more sense to determine the latest compatible version using semantic versioning. This way the default ISO can be released independently by Minishift and directly consumed.

**Comment by gbraad** [comment]
We could provide a version tag by publishing a JSON document on github-pages for instance, which can be retrieved as http://minishift.github.io/version Several projects use something similar, such as glide: https://glide.sh/version which is used from the http://glide.sh/get script to retrieve the latest stable version.

**Comment by budhrg** [comment]
We have used a python script to achieve similar thing in [b2d-iso](https://github.com/minishift/minishift-b2d-iso/blob/master/Makefile#L10).

> We could provide a version tag by publishing a JSON document on github-pages for instance, which can be retrieved as http://minishift.github.io/version

I like the this idea too 👍

**Comment by hferentschik** [comment]
The way it is done so far is via the GitHub API accessing the releases and using semantic versioning. Once we reach Minishift 1.0.0, we will anyways drop the alpha,beta,etc part (unless needed in some cases) and do "pure" semantic versioning.

**Comment by praveenkumar** [comment]
Since now we reached the 1.0.0 milestone I think now we can think to fetch latest available iso for b2d ISO. let we adjust the milestone if we think 1.2.0 timeline is not good enough.

**Comment by praveenkumar** [comment]
I am going to change milestone for this issue since PR closed and need more discussion around it.

**Comment by gbraad** [comment]
We will also need to check from the provisioner based on the `os-release` as we need to be backwards compatible and warn if a version of a previously cached ISO could cause problems.

**Comment by praveenkumar** [comment]
@minishift/minishift-dev If you go through the PR discussion which got closed because the way we want to implement this feature then you will find we are better off with this feature then putting effort. Please let me know if you think same or still agree to implement this feature as it supposes to be.

**Comment by LalatenduMohanty** [comment]
@praveenkumar yes, lets go ahead with the plan.

**Comment by LalatenduMohanty** [comment]
Not planning to fix this as we are going for a new solution for OpenShift 4.0
