### ISSUE TITLE
Investigate mounted host directory behavior on Windows + Hyper-V

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#293]
To determine how much work it will be to fully support the various combinations, we need to start determining what and what not works. Let's start with finding out what's currently happening with Minishift on Windows + Hyper-V.

If it works we can also update https://github.com/minishift/minishift/blob/master/docs/using.md#mounted-host-folders

**Comment by hferentschik** [comment]
Seems nothing is mounted and it might be that it is not supported/working at all. See also http://stackoverflow.com/questions/38261392/cant-mount-windows-host-directory-to-docker-container. There is a workaround which allows you to mount a shared folder, but would something like this be enough?

**Comment by budhrg** [comment]
@hferentschik The link does mention few workarounds and the comments also mention few others.

One need to go through these instructions to see if it actually works or not. 
I will start investigation and will post my findings here.

**Comment by hferentschik** [comment]
This works, I already verified.

**Comment by hferentschik** [comment]
Closing this issue. I think we have a basic understanding what needs/can be done. Potential implementation can be tracked via issue #316
