### ISSUE TITLE
Mount error (SELinux) when running `buildah` inside a `knative/build`

### ISSUE THREAD

**Issue by vdemeester** [minishift/minishift#2932]
### General information

  * Minishift version: 1.25.0
  * OS: Linux 
  * Hypervisor: KVM

### Steps to reproduce

  1. Install `knative` on Minishift (see https://github.com/knative/docs/blob/master/install/Knative-with-Minishift.md)
  2. `wget https://raw.githubusercontent.com/vdemeester/ocf-sandbox/master/auth.template.yml -O auth.yaml`, modify it with your login info, `oc apply -f auth.yaml`
  3. `oc apply -f https://raw.githubusercontent.com/vdemeester/ocf-sandbox/master/ocf-230/s2i.template.yaml`
  4. `oc apply -f https://raw.githubusercontent.com/vdemeester/ocf-sandbox/master/ocf-230/s2i.build.yaml`
  5. Wait for the build to fail (at some point)

### Expected

Build success

### Actual

The error would looks like : 

```
error running subprocess: error bind mounting "/tmp/buildah019197800/hosts" from host to "/etc/hosts" in mount namespace ("/tmp/buildah019197800/mnt/rootfs/etc/hosts"): permission denied
```

Looking in the `audit` log, we can see `SELinux` is disallowing this mount : 

```
type=AVC msg=audit(1540386825.073:5158): avc:  denied  { mounton } for  pid=29873 comm="exe" path="/tmp/buildah019197800/mnt/rootfs/etc/hosts" dev="sda1" ino=18575118 scontext=system_u:system_r:container_t:s0:c4,c12 tcontext=system_u:object_r:container_file_t:s0:c4,c12 tclass=file
```

**Comment by praveenkumar** [comment]
@vdemeester can you put the `audit` logs from `SELinux`? @kameshsampath can you take a look what is happen here?

**Comment by vdemeester** [comment]
@praveenkumar oups the formatting ate the audit log 🤣

**Comment by praveenkumar** [comment]
@vdemeester can you try something following and let us know if still issue? Also did you check if you make selinux permissive in the VM than it works?

```console
$ minishift delete

--- just after https://github.com/knative/docs/blob/master/install/Knative-with-Minishift.md#configure-and-start-minishift ---

$ minishift ssh -- sudo restorecon -R /tmp

-- carry on with remaining steps ---
```

**Comment by praveenkumar** [comment]
@vdemeester any update on this?

**Comment by vdemeester** [comment]
@praveenkumar so, making selinux permission (`setenforce 0` right ?) make it works.. I'll try doing the restorecon command :wink:
