### ISSUE TITLE
Minishift fails to start on virtualbox driver with error "Not able to populate hyperv-virtual-switch flag with Default Switch value" 

### ISSUE THREAD

**Issue by lovoni** [minishift/minishift#2937]
### General information

  * Minishift version: v1.26.0
  * OS: Windows 8
  * Hypervisor:  VirtualBox

### Steps to reproduce

  1. Install minishift v1.26.0
  2. Run command _**minishift start --vm-driver=virtualbox**_ 
  3. 
  4. 

### Expected
Minishift successfully booted up.

### Actual
**C:\WINDOWS\system32>minishift start --vm-driver=virtualbox**
-- Starting profile 'swad'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... SKIP
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
_Not able to populate hyperv-virtual-switch flag with Default Switch value_

### Logs
No logs

**Comment by lovoni** [comment]
Switching to v1.25.0 works fine.

**Comment by praveenkumar** [comment]
@lovoni this is a known issue and discussion going on #2933 we will do a patch release to fix it.
