### ISSUE TITLE
Fix command to enable service catalog in experimental features doc 

### ISSUE THREAD

**Issue by dgolovin** [minishift/minishift#2938]
### General information
Command to enable service catalog in [Experimental Features](https://github.com/minishift/minishift/blob/master/docs/source/using/experimental-features.adoc#enabling-experimental-oc-cluster-up-flags) doc fails with error:
```
- Starting OpenShift cluster -- Extra 'oc' cluster up flags (experimental) ... 
   '--enable=*,service-catalog''
.Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --routing-suffix 192.168.42.250.nip.io --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0' --public-hostname 192.168.42.250 --enable=*,service-catalog'
err     : exit status 1
output  : bash: -c: line 0: unexpected EOF while looking for matching `''
bash: -c: line 1: syntax error: unexpected end of file
```

**Comment by praveenkumar** [comment]
@dgolovin there is another way also you can enable those components.

```console
$ ./minishift openshift component list
The following OpenShift components are available: 
	- automation-service-broker
	- service-catalog
	- template-service-broker
$ ./minishift openshift component add service-catalog
```

**Comment by LalatenduMohanty** [comment]
> @dgolovin there is another way also you can enable those components.

For service-catalog `minishift openshift component add service-catalog` is the recomended method.

**Comment by dgolovin** [comment]
@LalatenduMohanty @praveenkumar thank you for comments! The reason I created this issue is it is in documentation which I followed and it did not work. I am also aware of second way do that with `minishift openshift component add service-catalog`, but it is not documented yet. I am not sure what is preferred way though. I think both should be documented.
