### ISSUE TITLE
How to configure correctly minishift to work behind a proxy.  Vagrant has no issues.

### ISSUE THREAD

**Issue by jjwallaby** [minishift/minishift#2941]
### General information

  * Minishift version: 
  * OS: Windows
  * Guest OS: Centos 7
  * Hypervisor:  VirtualBox

How to configure correctly minishift to work behind a proxy.  Vagrant has no issues.
It seems that minishift can ssh.  BUT the OS certificates are not valid.  how to copy files
like in Vagrant ?  How to copy corporate CA perm to OS ?

-- Starting profile 'minishift'
-- Using proxy for the setup
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.9.0'
 40.81 MiB / 40.81 MiB [===================================================================================] 100.00% 0s-- Downloading OpenShift v3.9.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ......................................... FAIL E1026 15:02:02.488252   15304 start.go:391] Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.103:2376": dial tcp 192.168.99.103:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.
. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.103:2376": dial tcp 192.168.99.103:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
Just reading the title I am confused about the argument; Vagrant is a virtualization deployment solution, which starts a 'configured' VM, based on a setup script. Minishift also starts a VM, but will deploy and run several containers inside of this. While we are able to deploy needed certificates inside this VM, the containers would have no knowledge of this. This would have been no different when Vagrant would have been used. We are limited to what Libmachine and `oc cluster up` does.  However, we are working on a workaround for this that injects the certificates inside the containers #2880.

Closing as duplicate

**Comment by gbraad** [comment]
Note: the startup command did not show use of `--http-proxy` and `--htps-proxy`
