### ISSUE TITLE
How do you force to make the browser look at local PC virtual network and not go outside.

### ISSUE THREAD

**Issue by jjwallaby** [minishift/minishift#2942]
### General information

  * Minishift version: v1.18.0+756b128
  * OS:  Windows
  * Hypervisor:  VirtualBox

Could not set oc CLI context for: 'minishift'

**It seems that the the port forwarding from 127.0.0.1 is not working.  How do you set port forwarding
it seems that it is going outside the network to search public hostname IP 192.168.99.103 .  Should this
not be a PRIVATE network ?**

-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
-- Copying oc binary from the OpenShift container image to VM ................................... OK
-- Starting OpenShift cluster .........................
Using nsenter mounter for OpenShift volumes
Using public hostname IP 192.168.99.103 as the host IP
Using 192.168.99.103 as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.103:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

C:\NotBackedUp\dev\anzminishift>oc login -u system:admin
Server [https://localhost:8443]: https://192.168.99.103:8443/
error: Gateway Timeout

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
liekly caused by old information, as the oc login command assumed to
use 127.0.0.1 instead.
Has `oc cluster up` been used on this machine directly? like
tarrgeting docker for Windows?

**Comment by jjwallaby** [comment]
No, As far as I know minishift uses VirtualBox.  I did not use any oc command.  My question how come minishift ssh  works.  But if do normally ssh...it tries to go outside the external network to find address when it is clearly a local IP address.

**Comment by gbraad** [comment]
> My question how come minishift ssh works. But if do normally ssh...it tries to go outside the external network to find address when it is clearly a local IP address.

I am sorry, but I am not following this.

```
$ minishift ssh
```

works. But how does `if do normally ssh` related to this? I do not see this being mentioned in the OP (original post)

**Comment by gbraad** [comment]
From the title: 

> How do you force to make the browser look at local PC virtual network and not go outside. 

I am not following what this has to do with Minishift. Is your browser configured to use a corporate proxy? If so, you would need to add an exception or ask your local admins to modify the rules to allow to use a DIRECT connection to the class-address networks, like 192.168.x.x, 172.16.x.x., 10.x.x.x, etc. However, I am confused about the title and now mentioning ssh.

**Comment by jjwallaby** [comment]
Correct.  Your above assumption is correct.
how come minishift ssh works,  but from the browser or another standard dos ssh does not work ?
As you mentioned to the question,  How to use minishift behind a proxy.  There are no clear instructions.

**Comment by gbraad** [comment]
Althought this describes some aout CDK, it is basically the same for Minishift with the exception of the RHN username/password combination: https://blog.openshift.com/minishift-and-the-enterprise-proxies/

But as mentioned, you can NOT use a CA certificate at the moment due to #2880
