### ISSUE TITLE
Document deployment of a sample Hello-World application using Wildfly

### ISSUE THREAD

**Issue by Preeticp** [minishift/minishift#295]
Currently we have deployment of a sample node.js application in the Readme. We need documentation for deployment of a sample Wildfly application on Minishift keeping in mind our end user.

**Comment by jorgemoralespou** [comment]
@Preeticp Please note that on the origin version, wildfly might be installed while on the OCP version (CDK) it will not be installed by default, hence the recommendation to add the wildfly imagestream to the sample project as a word of safety.

**Comment by Preeticp** [comment]
Thanks @jorgemoralespou, I will keep this in mind. @praveenkumar too informed me about this. This documentation would focus on Origin since it is upstream, but this is something we will have to take a note of while documenting for the downstream.
