### ISSUE TITLE
Unable to create Hyper-V VM

### ISSUE THREAD

**Issue by putz612** [minishift/minishift#2950]
### General information

  * Minishift version: 1.25.0 and 1.26.1
  * OS: Windows 10 x64
  * Hypervisor:  Hyper-V 

### Steps to reproduce

  1. run minishift start to begin the vm creation

### Expected
minishift awesomeness!

### Actual
no awesomeness

### Logs
I know I am in the small percentage where I have a corporate system and my user home is a mapped drive which already makes this harder.  Minishift is in c:\minishift and I have the minishfit_home environment variable set to the same folder to help with the network home directory.
```
PS H:\> get-childitem env:MINISHIFT_HOME
Name                           Value
----                           -----
MINISHIFT_HOME                 C:\minishift\
```
When I start ```PS H:\> C:\minishift\minishift.exe start``` it fails on creating the VM.
```FAIL E1026 15:16:52.082001   25636 start.go:491] Error starting the VM: Error creating the VM.```

Bumping up the logs gives me a bit more but its very confusing,  I am not sure why it dropped off the c:/ in the path for the ISO.
```
-- Starting Minishift VM ...... FAIL E1026 15:06:56.866527   28832 start.go:491] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: open /minishift/cache/iso/centos/v1.13.0/minishift-centos7.iso: The system cannot find the path specified.. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: open /minishift/cache/iso/centos/v1.13.0/minishift-centos7.iso: The system cannot find the path specified.
```
Looking in the machine config.json it has the proper path.
```"Boot2DockerURL": "file://C:/minishift/cache/iso/centos/v1.13.0/minishift-centos7.iso",```

**Comment by praveenkumar** [comment]
@putz612 can you try following and let us know if still same issue?

```console
$minishift start --iso-url file://C:/minishift/cache/iso/centos/v1.13.0/minishift-centos7.iso --show-libmachine-logs --v=5
```

**Comment by putz612** [comment]
Same thing with the --iso-url parameter 
```
(minishift) Calling .GetConfigRaw
Creating machine...
(minishift) Calling .Create
(minishift) Downloading C:\minishift\cache\boot2docker.iso from file://C:/minishift/cache/iso/centos/v1.13.0/minishift-centos7.iso...
. FAIL E1030 09:51:32.260560   16844 start.go:491] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: open /minishift/cache/iso/centos/v1.13.0/minishift-centos7.iso: The system cannot find the path specified.. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: open /minishift/cache/iso/centos/v1.13.0/minishift-centos7.iso: The system cannot find the path specified.
```
Just for giggles I also tried swapping around the /\ in the MINISHIFT_HOME environment as I saw it using the other slash in the output and no change.
```
PS H:\> get-childitem env:MINISHIFT_HOME
Name                           Value
----                           -----
MINISHIFT_HOME                 C:/minishift/
###################
(minishift) Calling .Create
(minishift) Downloading C:\minishift\cache\boot2docker.iso from file://C:/minishift/cache/iso/centos/v1.13.0/minishift-centos7.iso...
. FAIL E1030 09:52:24.785713    9284 start.go:491] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: open /minishift/cache/iso/centos/v1.13.0/minishift-centos7.iso: The system cannot find the path specified.. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: open /minishift/cache/iso/centos/v1.13.0/minishift-centos7.iso: The system cannot find the path specified.
```

**Comment by gbraad** [comment]
Before this start, please make sure you run `minishift delete -f`
And can you post the whole output somewhere?

**Comment by putz612** [comment]
Sure, here is test from today with full log output in a gist.  Please let me know what else I can provide

https://gist.github.com/putz612/6a0031b9be51103e9e48792d31832d07

**Comment by putz612** [comment]
So this is odd, I ran it again but instead of being on the H: drive I ran the same command with my current working dir on C: and it got farther.  Which is really odd as I have been careful to use absolute pathing on all everything.  All I did was type in 
```
PS H:\> c:
PS C:\>
```
and run the same command as before and the VM is created.  I can see it in the Hyper-V manager but the start has yet to finish.  It keeps erroring out on some SSH part, below is a subset of the messages.
```
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@10.220.9.161 -o IdentitiesOnly=yes -i C:\minishift\machines\minishift\id_rsa -p 22] C:\WINDOWS\System32\OpenSSH\ssh.exe <nil>}
About to run SSH command:
exit 0
..SSH cmd err, output: exit status 255:
Error getting ssh command 'exit 0' : ssh command error:
command : exit 0
err     : exit status 255
output  :
Getting to WaitForSSH function...
(minishift) Calling .GetSSHHostname
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
.(minishift) DBG | [stdout =====>] : 10.220.9.161
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
```
That block is repeating over and over again.  Has for over an hour.  New log is available here
https://gist.github.com/putz612/a0b9d704ee017b57d1f72f2fe8e8e102

**Comment by gbraad** [comment]
right... this was my follow suggestion. Make sure you run from `WINDRIVE` (C:), since this is an issue with libmachine.

If this keeps repeating, there is an issue with the ssh client or the actual IP assignment.

Can you delete the VM again and try? If it remains, can you let me know which ssh client you are using?
