### ISSUE TITLE
Escape codes are shown on Windows when using ssh+vi

### ISSUE THREAD

**Issue by jjwallaby** [minishift/minishift#2953]
### General information

  * Minishift version: 
  * OS: Windows
  * Hypervisor:  VirtualBox

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Expected

minishift ssh
]0;docker@minishift:~[?1034h[docker@minishift ~]$ pwed
-bash: pwed: command not found
]0;docker@minishift:~[docker@minishift ~]$ pwd
/home/docker
]0;docker@minishift:~[docker@minishift ~]$

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by jjwallaby** [comment]
example vi
 vi /tmp/jjw.txt
[?1049h[?1h=[1;24r[?12;25h[?12l[?25h[27m[m[H[2J[?25l[24;1H"/tmp/jjw.txt" [New File][2;1H[1m[34m~                                                                               [3;1H~                                                                               [4;1H~                                                                               [5;1H~                                                                               [6;1H~                                                                               [7;1H~                                                                               [8;1H~                                                                               [9;1H~                                                                               [10;1H~                                                                               [11;1H~                                                                               [12;1H~                                                                               [13;1H~                                                                               [14;1H~                                                                               [15;1H~                                                                               [16;1H~                                                                               [17;1H~                                                                               [18;1H~                                                                               [19;1H~                                                                               [20;1H~                                                                               [21;1H~                                                                               [22;1H~                                                                               [23;1H~                                                                               [1;1H[?12l[?25h

**Comment by gbraad** [comment]
What shell are you using? We have tested cygwin, posh (+openssh-win32) and git-bash. You could use cmd, but for this you need to use the console2 (new generation on Windows 10) and use a recent ssh client.

This is likely related to how your ssh client handles the term implementation. The funny characters are ESCape codes and are used for controlling the terminal output.

**Comment by gbraad** [comment]
You should also not use the VM as a work environment... as this will result in #355. When the `/` (root) filesystem fills up, it might lock-up the virtual environment. You can however use `/var/sda1/` and container images for this.

**Comment by jjwallaby** [comment]
There is no container images.  This is just a fresh launch install of minishift.  As you are aware the Instance of the VM can be accessed via VirtualBox.  So the launch was done from standard windows command prompt.   minishift ssh. This  problem does not appear, if I assume docker has been launched successfully ?
Since I am unable to start minishift behind a proxy, even though proxy environments  are set.
In this case.  the CA cert file on the virtual guest VM (minishift Centos 7) seems need to be installed  ?
minishift start  --vm-driver=virtualbox  --iso-url=file://c:/NotBackedup/dev/minishift/minishift-centos7_v1_13.iso  --https-proxy=XXXX --http-proxy=XXXX
-- Starting profile 'minishift'
-- Using proxy for the setup
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ..........................-- Setting proxy information ... .OK
...... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... OK
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Pulling the Openshift Container Image .Error pulling the openshift container image: ssh command error:
command : docker pull openshift/origin-control-plane:v3.11.0
err     : Process exited with status 1
output  : Trying to pull repository docker.io/openshift/origin-control-plane ...
Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority

**THIS problem does not occur on a LAPTOP if not behind a proxy.**

C:\NotBackedUp\dev\minishift>minishift ssh
]0;docker@minishift:~[?1034h[docker@minishift ~]$ ps

**Comment by gbraad** [comment]
proxy has nothing to do with this...

you are using the standard command prompt? If so, this does not
support escape codes properly.
On Tue, Oct 30, 2018 at 9:03 AM Justin W <notifications@github.com> wrote:
>
> There is no container images. This is just a fresh launch install of minishift. As you are aware the Instance of the VM can be accessed via VirtualBox. So the launch was done from standard windows command prompt. minishift ssh. This problem does not appear, if I assume docker has been launched successfully ?
> Since I am unable to start minishift behind a proxy, even though proxy environments are set.
> In this case. the CA cert file on the virtual guest VM (minishift Centos 7) seems need to be installed ?
> minishift start --vm-driver=virtualbox --iso-url=file://c:/NotBackedup/dev/minishift/minishift-centos7_v1_13.iso --https-proxy=XXXX --http-proxy=XXXX
> -- Starting profile 'minishift'
> -- Using proxy for the setup
> -- Check if deprecated options are used ... OK
> -- Checking if https://github.com is reachable ... OK
> -- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
> -- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
> -- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
> -- Checking if VirtualBox is installed ... OK
> -- Checking the ISO URL ... OK
> -- Checking if provided oc flags are supported ... OK
> -- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
> -- Starting Minishift VM ..........................-- Setting proxy information ... .OK
> ...... OK
> -- Checking for IP address ... OK
> -- Checking for nameservers ... OK
> -- Checking if external host is reachable from the Minishift VM ...
> Pinging 8.8.8.8 ... FAIL
> VM is unable to ping external host
> -- Checking HTTP connectivity from the VM ...
> Retrieving http://minishift.io/index.html ... OK
> -- Checking if persistent storage volume is mounted ... OK
> -- Checking available disk space ... 1% used OK
> -- Writing current configuration for static assignment of IP address ... OK
> -- OpenShift cluster will be configured with ...
> Version: v3.11.0
> -- Pulling the Openshift Container Image .Error pulling the openshift container image: ssh command error:
> command : docker pull openshift/origin-control-plane:v3.11.0
> err : Process exited with status 1
> output : Trying to pull repository docker.io/openshift/origin-control-plane ...
> Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority
>
> THIS problem does not occur on a LAPTOP if not behind a proxy.
>
> C:\NotBackedUp\dev\minishift>minishift ssh
> �]0;docker@minishift:~�[?1034h[docker@minishift ~]$ ps
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by gbraad** [comment]
> THIS problem does not occur on a LAPTOP if not behind a proxy.

I doubt these laptops are identically configured.
running `minishift ssh --show-libmachine-logs -v5` will reveal which client is used.

Note: as stated 'proxy' does not interfere or change the ssh behaviour

**Comment by jjwallaby** [comment]
Yes agree.  I just using 2 laptops.  1 that is open is connected to an open network.  No PROXY.
the other going via a proxy and has firewall ie in corporation which has alot of security controls and disallow many services...etc.    Correct use git-bash shell no issues.  Anyhow will ignore this error. Just wondered why it occurs on different behaviour.  What causes this funny characters..

**Comment by gbraad** [comment]
Read https://github.com/minishift/minishift/issues/2953#issuecomment-433807531 as the answer had been given. This is related to missing functionality for the shell you are using. Some SSH clients do not support pseudo TTY support or pass the wrong terminal type, and combined with the underlying console, this might get correctly interpreted or not. On Windows this will always be somehow messy. As mentioned, we have tested cygwin and powershell + openssh+win32 to work correctly. Some others might work, but are outisde of our scope to handle as there are hundreds of different compiled versions and offerings of even the same version of some of these files, and they have no guarantee that they even include the needed support.

> Anyhow will ignore this error. 
OK, so closing this issue
