### ISSUE TITLE
Nightly stuck in addon-che.feature file on Java CentOS stack 

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2958]
### General information

  * Minishift version: master
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. make integration GODOG_OPTS="-tags addon-che"
  2. 
  3. 
  4. 

Place where it stuck - https://github.com/minishift/minishift/blob/master/test/integration/features/addons/addon-che.feature#L50
Reported in CI - https://ci.centos.org/job/minishift-nightly-centos/323/console

NOTE: anyuid.addon is not enabled during the feature run

**Comment by amitkrout** [comment]
Not sure if any changes has done from che java stack side causing the issue

**Comment by agajdosi** [comment]
@amitkrout I think we could be fine with just issue #2824 here. Lets close this if you agree.
