### ISSUE TITLE
how to share a folder from windows to an virtualbox guest OS centos.  Like vagrant does ?

### ISSUE THREAD

**Issue by jjwallaby** [minishift/minishift#2959]
### General information

  * Minishift version: v1.26.1+1e20f27
  * OS:  Windows
  * Hypervisor:  VirtualBox

In vagrant you can add a Windows folder to a VM (virtualbox) guest OS like centos
using the tool 

**vagrant plugin install vagrant-sbguest**

And you can mount easily and folder on your windows to the guest OS in the VagrantFile

**config.vm.synced_folder '.', '/mnt/windows'**

This DOES not use sshd which is not a security issue.  So how can you simple share folders
as simply as vagrant works.

**We are unable to use sshd as it is disabled.**

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@jjwallaby https://docs.okd.io/latest/minishift/using/host-folders.html here you can find around it.

**Comment by gbraad** [comment]
Please, read the documentation at: https://docs.okd.io/latest/minishift/ as many of the reported issues have been addressed here.

Closing this issue

**Comment by jjwallaby** [comment]
We are not allowed to use sshfs. or cifs within a corporation.  Actually vagrant supports windows folder shared called vboxfs.  We request minishift to support vboxfs.  As minishift is using unnecessary security breaches.

**Comment by gbraad** [comment]
sshfs in our case starts a local client to mimic the same behaviour
and is secured with a local certificate.
cifs is a common solution that is almost any corporation allows due to
the well supported and described nature. (note, v2 that is)
vboxfs is NOT possible in our image due to legal reasons as we can not
embed the needed drivers.
