### ISSUE TITLE
Run only features which are not part of PR one during nightly job

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2960]
I think it would be nice to remove all the `core` feature file from the nightly job since each PR run those, it will help us to trim down some of the timing issues we are having and debug what breaking.

**Comment by LalatenduMohanty** [comment]
@praveenkumar Are you suggesting this as a temporary solution to fix the issues in nightly?

**Comment by praveenkumar** [comment]
@LalatenduMohanty not temporary but this will help us in long term also because running same features from PR and nightly doesn't make sense since all features are independent.
