### ISSUE TITLE
minishift console redirect issue

### ISSUE THREAD

**Issue by odra** [minishift/minishift#2967]
### General information

  * Minishift version: minishift v1.25.0+90fb23e
  * OS: Linux 
  * Hypervisor: KVM

### Steps to reproduce

  1. start a minishift instance
  2. run `minishift console`
  3. accept custom cert
  4. redirects to localhost instead of using minishift ip

### Expected

To be redirected to the minishift web console (using minishift ip address).

### Actual

The browser redirects the request to localhost (https://127.0.0.1:8443/console) instead of using the correct minishift ip url (https://$minishift_ip:8443/console)

**Comment by LalatenduMohanty** [comment]
@odra This issue is fixed in 1.26.0 version of Minishift. Please use the latest version of Minishift i.e. 1.26.1  as it contains some critical bug fix on top of 1.26.0 version.

**Comment by LalatenduMohanty** [comment]
Closing this issue as we have fixed it already. Please comment if you face any issue.

**Comment by odra** [comment]
Thanks, I just updated it and it is working as expected now :+1:
