### ISSUE TITLE
logging project empty

### ISSUE THREAD

**Issue by wael216** [minishift/minishift#2968]
### General information

  * Minishift version: v1.13.1+75352e5
  * OS: ubuntu 16.04
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. install minishift
  2. minishift start with options :  **minishift start --metrics --logging**
  3.  oc login admin
  4. oc project logging
  5. oc get pods

### Expected
EFK stack pods 

### Actual
No resources found.
even on the web console there are no pods, no deployments (nothing actually). 

### Logs
no trace of logging project in logs, just regular ending logs : 
Making call to close driver server
(minishift) Calling .Close
Successfully made call to close driver server
(minishift) DBG | Closing plugin on server side
Making call to close connection to plugin binary
Making call to close driver server
(minishift) Calling .Close
Successfully made call to close driver server
Making call to close connection to plugin binary
(minishift) DBG | Closing plugin on server side
Making call to close driver server
(minishift) Calling .Close
Successfully made call to close driver server
Making call to close connection to plugin binary
(minishift) DBG | Closing plugin on server side
Making call to close driver server
(minishift) Calling .Close
Successfully made call to close driver server
Making call to close connection to plugin binary
Making call to close driver server
(minishift) Calling .Close
Successfully made call to close driver server
Making call to close connection to plugin binary
(minishift) DBG | Closing plugin on server side

**Comment by agajdosi** [comment]
Hi @sylva91, thank you for the report. Metrics and Logging had both problems in `oc cluster up` which Minishift uses under the hood for the provisioning of the VM. Both thus got removed from Minishift as these were not functional fully.

I would suggest to update to latest Minishift. Then you can try to enable the metrics and logging using custom flags for `oc cluster up`.

To get more information, you can take a look here:
- how to enable and set cluster up flags directly: https://docs.okd.io/latest/minishift/using/experimental-features.html#enabling-experimental-oc-flags
- issue for enabling Metrics: https://github.com/minishift/minishift/issues/2447

Let us know how it works for you.

**Comment by sylva91** [comment]
thank you for your response. 

Using the last version of minishift i get both : 

**MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --extra-clusterup-flags "--metrics"** 

.Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0' --public-hostname 192.168.99.100 --routing-suffix 192.168.99.100.nip.io --metrics
err     : exit status 1
output  : Error: unknown flag: --metrics


**MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --extra-clusterup-flags "--metrics"** 

.Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0' --public-hostname 192.168.99.100 --routing-suffix 192.168.99.100.nip.io --metrics
err     : exit status 1
output  : Error: unknown flag: --logging

**Comment by VincentG85** [comment]
@praveenkumar Following the guide you mentionned, we seem to need an 'inventory' and an 'OPENSHIFT_ANSIBLE_DIR'.
Where are those ?
