### ISSUE TITLE
Ubuntu/Xubuntu 18.10 libvrt installlation issue solution

### ISSUE THREAD

**Issue by nikita-karatun** [minishift/minishift#2970]
### General information

  * Minishift version: 1.26.1-linux-amd64
  * OS: Xubuntu 18.10 
  * Hypervisor: KVM

I'm not sure where it is better to post that, if it is wrong place, please let me know.
I had an issue with [Setting Up the Virtualization Environment](https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html).
libvirt install instructions does not work for Ubuntu/Xubuntu 18.10, since libvirt-bin package is no longer there. 

### Steps to reproduce

  1. As instruction says, run `sudo apt install libvirt-bin qemu-kvm`

### Expected
Virtualization Environment is installed.

### Actual
Package libvirt-bin is not found.
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libvirt-bin is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libvirt-bin' has no installation candidate
```

### Solution
I was able to install the Virtualization Environment on my Xubuntu 18.10 running following.
`sudo apt install qemu qemu-kvm virt-manager`
Since other Ubuntu/Xubuntu 18.10 users may face same issue, should not it be added to the instrucitons?

**Comment by praveenkumar** [comment]
@nikita-karatun sure please create a PR with updated instruction which work with ubuntu 18.10, also after installing those dependencies are you able to run the minishift on top of it?

**Comment by nikita-karatun** [comment]
@praveenkumar, yes, I am able to run minishift, sure, I'll create the PR, though I'm going to rerun the installation on clean system first to double check that I have not missed any other required packages, thanks!

**Comment by gbraad** [comment]
Wouldn't:

```
$ sudo apt install virt-manager
```

be enough?

Also, `virt-manager` is not a bad choiuce, but it is a UI/tool instead of the actual needed `libvirt` daemon. I wonder what other dependencies came with it that caused `libvirt` to work as daemon.

**Comment by gbraad** [comment]
The needed dependency can be found here:
https://salsa.debian.org/libvirt-team/virt-manager/blob/debian/sid/debian/control#L21

Please use `libvirt-daemon` instead.

**Comment by AyanC1** [comment]
`sudo apt-get install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils`

use this i got it from 

[here](https://help.ubuntu.com/community/KVM/Installation)

**Comment by Vr3n** [comment]
` sudo apt install qemu qemu-utils qemu-kvm  bridge-utils  virt-manager`

I had the same problem.. this worked for me!

**Comment by shuvasisdatta** [comment]
> `sudo apt-get install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils`
> 
> use this i got it from
> 
> [here](https://help.ubuntu.com/community/KVM/Installation)

Thank You this help me

**Comment by codesuperstarr** [comment]
This helped me. Thanks for sharing.

**Comment by mcontoor** [comment]
> `sudo apt-get install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils`
> 
> use this i got it from
> 
> [here](https://help.ubuntu.com/community/KVM/Installation)

Worked for ubuntu 20.04 as well! Thanks!

**Comment by jectcaleb** [comment]
No candidate version found for libvirt-bin
Unable to apply some actions, aborting

_how about that issue_

**Comment by maiman-1** [comment]
> `sudo apt-get install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils`
> 
> use this i got it from
> 
> [here](https://help.ubuntu.com/community/KVM/Installation)

I tried this and it told me it was selecting libvirt-bin instead of libvirt-daemon-system XD
