### ISSUE TITLE
minishift install/start problem on windows 10 

### ISSUE THREAD

**Issue by danseo-reisys** [minishift/minishift#2997]
### General information

  * Minishift version: 1.26.1
  * Windows 10
  * VirtualBox

### Steps to reproduce

  PS C:\minishift> .\minishift.exe start --vm-driver=virtualbox -v 5 --show-libmachine-logs

### Expected
complete install

### Logs
(minishift) DBG | Checking vm logs: C:\Users\dan.seo\.minishift\machines\minishift\minishift\Logs\VBox.log
(minishift) Waiting for an IP...
(minishift) DBG | Getting to WaitForSSH function...
(minishift) DBG | SSH binary not found, using native Go implementation
(minishift) DBG | &{{{<nil> 0 [] [] []} docker [0x7aed70] 0x7aed40 <nil>  [] 0s} 127.0.0.1 54012 <nil> <nil>}
(minishift) DBG | About to run SSH command:
(minishift) DBG | exit 0
........................(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:54018->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
................(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:54110->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
............(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:54198->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
...(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:54279->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:54359->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:54427->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:54481->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:54530->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:54619->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:54689->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:54755->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:54819->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:54889->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
..(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:54934->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
.........(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:55018->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
.........(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:55089->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
........(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:55166->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.
.......(minishift) DBG | Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:55241->127.0.0.1:54012: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by anjannath** [comment]
@danseo-reisys The IP address does not look right, the VM that gets created should be getting a proper IP and from the logs it looks like it is trying to ssh into you localhost.

You should do a `minishift delete -f` and then start again. Also are you able to create VMs using virtualbox? the `wsarecv` error i can't tell much @gbraad will be able to provide more information.

**Comment by danseo-reisys** [comment]
in case of using virtualbox, what is the flag to enforce it to use NAT/dhcp?

**Comment by gbraad** [comment]
> proper IP

That IP is correct for VirtualBox. VB uses port forwarding to map the VM's port 22 to a local port. This means that `minishift ssh` or the internal commands are issues over a local endpoint.

However, the 'forcibly closed' looks like another issue... like a firewall or antivirus. What other software is on this machine?

> NAT/dhcp

not sure what you mean... DHCP is used on start and NAT is handled by the host-only bridge created by VirtualBox.
