### ISSUE TITLE
Make start/stop menu contextual

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#2999]
Right now in the tray the start/stop menu items do not reflect the state of the machine.
When minishift is running the `start` option should be greyed out/disabled, likewise for `stop`.

**Comment by zeenix** [comment]
From UX POV, it's best to not show disabled controls. Can we not just hide the irrelevant button instead?

**Comment by anjannath** [comment]
@zeenix Is is a menu not a button, i like the idea of hiding the menu item, but usually don't see people make it that way, in a menu if something is not disabled then it is greyed out.

In the following screenshot, we want to disable start if the vm is running and stop to be disabled if the vm is already stopped.

<img width="525" alt="screenshot 2019-02-05 at 1 52 34 pm" src="https://user-images.githubusercontent.com/3125299/52260875-742f7a80-294d-11e9-9571-b930a1607d2e.png">

**Comment by zeenix** [comment]
> @zeenix Is is a menu not a button

I'm talking about the 'start' and 'stop' buttons here.

> but usually don't see people make it that way, in a menu if something is not disabled then it is greyed out.

Actually in this case there should be just one button. There is a lot of badly designed UIs out there, we shouldn't follow the trend when possible. :)

Try e.g the bluetooth option in the GNOME shell. It says "Turn on" when it's turned off and "Turn off" when it's turned on (probably the same on Mac too). This is the same case.

**Comment by anjannath** [comment]
@zeenix Got it, just wanted to be clear about what you meant when you said button.

**Comment by zeenix** [comment]
> @zeenix Got it, just wanted to be clear about what you meant when you said button.

Sure, no worries. :)
