### ISSUE TITLE
Build and release single minishift binaries with systemtray

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#3001]
In this release (v1.27.0), there are two sets of binaries one with systemtray for windows & macOS and the normal minishift binaries for all the platforms.

Going forward we should release single set of binaries with systemtray for all the supported platforms.

**Comment by gbraad** [comment]
I question this at the moment. It would be ideal to do so... but since we have a setup command, we can go the route of having this being pulled for the platform. It allows us to prevent bloating the regular (CLI-only) binary. WDYT?

**Comment by anjannath** [comment]
@gbraad I think doing it with setup would be ideal! but right now we do not have only systemtray binaries, the code lives together with minishift, it'd be possible to do that if we had a lightweight systemtray-only binary, but now the situation is we have minishift+systemtray in a single binary.

Can you put some details about how you think we can do this going the setup route?

**Comment by anjannath** [comment]
Also, having two binaries breaks the `minishift update` command, when you run the command it'll always download the default (CLI only) binary.
