### ISSUE TITLE
Preflight check returns false negative through systemtray minishift start

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#3002]
### General information

  * Minishift version: minishift-systemtray-1.27.0-windows-amd64
  * OS: Windows10
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. Use minishift tray bit
  2. minishift start --vm-driver virtualbox
  3. Stop minishift from tray icon
  4. Then start it from tray icon

### Expected
minishift should run

### Actual
Preflight checks fails on virtualbox installation status

<img width="1054" alt="screen shot 2018-11-14 at 3 23 30 pm" src="https://user-images.githubusercontent.com/19851115/48476331-c6687000-e824-11e8-93ed-16d0ce41fae1.png">

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by agajdosi** [comment]
Reproducible on Windows 7 machine.
