### ISSUE TITLE
Profile stays shown in system tray after it is deleted

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#3003]
### General information

  * Minishift version: minishift v1.27.0+707887e
  * OS: Windows 7
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. minishift profile new coolprofile
  2. minishift start
  3. see it is shown in the systray
  4. minishift profile delete coolprofile
  5. profile stays listed in systray

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by anjannath** [comment]
@agajdosi I checked this, and the profiles do get removed from the tray, but there's delay. 

There's no synchronous communication between the delete operation and the tray, we have to pool for the list of profiles, and then update it on the tray. so once the profile is deleted it only gets reflected in the tray when we query for the list of profiles again, that happens after a time interval.

We can increase the pooling frequency, right now there's more delay..

**Comment by anjannath** [comment]
@agajdosi actually don't close it yet.

I am looking at alternatives to get the status reflected in the tray
instantaneously or at least within a few seconds.

>
