### ISSUE TITLE
minishift vm - create ovf 

### ISSUE THREAD

**Issue by danseo-reisys** [minishift/minishift#3004]
### General information

  * Minishift version: 1.27.1
  * Windows
  * Hypervisor: VirtualBox

### Steps to reproduce

install was successful.
however, I was hoping to be able to export the working version using Oracle Virtual Box UI ==> export appliance but I don't see minishift in Oracle Virtual Box UI.  

what we are trying to do is create a working VM and have our developers simply import the appliance on their Oracle Virtualbox either on windows or macOS.  is this feasible approach?  

thanks

**Comment by gbraad** [comment]
After creation with `minishift start --vm-driver virtualbox` it should show up in the management UI for VirtualBox. 

I would not know why this would not be possible... howeverm be aware that we use an ISO to start the machine with. So it is not just a persistent disk. Also, make sure the IP address does not modify between runs... we have some workaround in place for this, but not sure how this will behave when importing as an appliance. It should work...

**Comment by gbraad** [comment]
This might have to do with permissions. I do not have this issue, but I am also a member of the local Administrator group.

**Comment by danseo-reisys** [comment]
so, you can see 'minishift' in your virtualbox ui??

**Comment by gbraad** [comment]
yep...

**Comment by gbraad** [comment]
As an example, a [random hit](https://blog.dbi-services.com/testing-edb-containers-with-minishift/) from a search that is NOT anyone of the developers of Minishift

![](https://blog.dbi-services.com/wp-insides/uploads/sites/2/2018/04/Selection_040.png)

Although this is on Linux, it is no different on Windows. As mentioned, this might be a permissions issue...

**Comment by danseo-reisys** [comment]
it is different on windows with oracle virtualbox version 5.2.22. 
it does not get registered on UI.  

when I stop and try to restart I get the following error.  

PS C:\minishift> minishift.exe status
Minishift:  Running
Profile:    minishift
OpenShift:  Running (openshift v3.11.0+314d321-53)
DiskUsage:  29% of 19G (Mounted On: /mnt/sda1)
CacheUsage: 1.444 GB (used by oc binary, ISO or cached images)
PS C:\minishift> minishift.exe stop
Stopping the OpenShift cluster...
Cluster stopped.
PS C:\minishift> minishift.exe start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM .... FAIL E1114 14:28:34.619600   15624 start.go:491] Error starting the VM: Error getting the state for host: machine does not exist. Retrying.
Error starting the VM: Error getting the state for host: machine does not exist
PS C:\minishift>

**Comment by gbraad** [comment]
Communication with the driver from:

```
PS C:\minishift> minishift.exe status
Minishift: Running
Profile: minishift
OpenShift: Running (openshift v3.11.0+314d321-53)
DiskUsage: 29% of 19G (Mounted On: /mnt/sda1)
CacheUsage: 1.444 GB (used by oc binary, ISO or cached images)
```

to

```
PS C:\minishift> minishift.exe stop
Stopping the OpenShift cluster...
Cluster stopped.
```

is all based on the name `minishift`. It should exist, especially in the `status` and `stop` path else these commands would fail. As mentioned, use the `VboxManage` command to verify.

@amitkrout @agajdosi any thoughts on this?

**Comment by gbraad** [comment]
Can you also try to use `minishift start --vm-driver virtualbox` for the second time you start it (after the stop).

**Comment by amitkrout** [comment]
@danseo-reisys Can you please start VirtualBox manager UI as administrator and check if the minishift vm is seen in the UI ?
