### ISSUE TITLE
minishift install as 'administrator' but used by another user 

### ISSUE THREAD

**Issue by danseo-reisys** [minishift/minishift#3006]
### General information

  * Minishift version: 1.27.1
  * OS: Windows
  * Hypervisor: VirtualBox

### Steps to reproduce
installed minishift as local ADMINISTRATOR user
but
when a different window user (with local admin access) try to start the minishift, the user gets an error (failed to find the vm status)

is this supported?  is minishift tied to a window user profile?  it can't be shared with multiple users on the same window OS? 

Thanks,

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by danseo-reisys** [comment]
Also, is there a way to auto start the minishift on reboot as the original user who installed?

**Comment by LalatenduMohanty** [comment]
Ideally when you install something as administrator, then users will not have enough privilege to run it. 

>  is minishift tied to a window user profile? it can't be shared with multiple users on the same window OS?

The general rule of windows for a normal binary is applicable here. For Windows `minishift` is a binary and all the OS rules applicable to `minishift` as a normal binary.  

I have never tried this scenario so cannot comment without testing it first.
