### ISSUE TITLE
minishift start log on ubuntu vm behind proxy

### ISSUE THREAD

**Issue by onderson** [minishift/minishift#3008]
### General information

  * Minishift version: minishift v1.27.0+707887e
  * OS: Linux - Ubuntu
  * Hypervisor: KVM 

### Steps to reproduce

  1. behind enterprise proxy
  2. start minishift

### Expected
starts normally

### Actual
does not start

### Logs

https://gist.github.com/onderson/948e8bd685be1b6f04eddde7d157fed7

**Comment by gbraad** [comment]
Can't open the gist at the moment, but do you perhaps need a CA certificate
as part of the proxy configuration? If so, this is a known issue and a
duplicate... Therr is a PR that handles this, but needs more testing.

**Comment by onderson** [comment]
Not sure, i suspect if this is related to issues listed below;

https://issues.jboss.org/browse/CDK-329
https://github.com/openshift/origin/issues/20496
https://github.com/docker/machine/issues/2740

I know get the same result in windows (either in corporate network or VPN connection) as mentioned here.. 
https://github.com/minishift/minishift/issues/2972

**Comment by onderson** [comment]
@gbraad ,this does not happen with   `--openshift-version v3.10.0` option.

**Comment by gbraad** [comment]
not related to 2740 for docker machine, but there is an issue with proxy-based deployment. at the moment both 3.10 and 3.11 are impeded...

**Comment by onderson** [comment]
@LalatenduMohanty @gbraad , i can confirm this does not happen in two different platforms which are windows and ubuntu vm with --openshift-version v3.10.0

**Comment by gbraad** [comment]
To summarize; this does not happen with:

  *  with `--openshift-version v3.10.0` option (Ubuntu) https://github.com/minishift/minishift/issues/3008#issuecomment-441127904
  *  does not happen in two different platforms (Windows, Ubuntu) with `--openshift-version v3.10.0` https://github.com/minishift/minishift/issues/3008#issuecomment-442290275

Right, as this issue impedes newer releases as mentioned: https://github.com/minishift/minishift/issues/3008#issuecomment-441145362 At the moment, a fix has not been released yet.

**Comment by agajdosi** [comment]
@LalatenduMohanty Thanks to the fact that OKD uses just major and minor and ignores patch versioning on images I cannot confirm that there was a problem previously on my setup, however with current v3.11.0 and v3.10.0 I can start with the proxy without a problem.

@onderson How it goes for you, is it fixed with the latest images?

**Comment by onderson** [comment]
@agajdosi sorry for the delay, minishift starts OK. I think the issue is resolved but in this case console access is not working for me :/ not sure yet why. i will explore, you can close the issue. thanks.

**Comment by onderson** [comment]
@agajdosi ... aah, it was due to my browser's no proxy settings. sorry about that. closing. thanks. looks like resolved.
