### ISSUE TITLE
Minishift selfsigned root-cert should be in .minishift dir

### ISSUE THREAD

**Issue by KurtStam** [minishift/minishift#3009]
This is a feature request.

I use minishift a lot for development and reinstall fresh maybe once a day. So very day I need to click thru the self-signed warnings in the openshift UI. Wouldn't it be possible to store the root-cert in the .minishift dir so that if I re-install the root-cert remains the same?

That way I could import  the root cert in my browser once and be done with it.

Somewhat the same as #1031 but less ambitious.

--Kurt

**Comment by gbraad** [comment]
the certificate creation is done why `oc cluster up`. there is not much control we have over this step. We would have liked to even be able to force recreation of the certificates, but hasn't happened either. I doubt this regarded as important from their end. :-s

**Comment by gbraad** [comment]
@praveenkumar @LalatenduMohanty I am inclined to make this a 'WONTFIX' as this is not something we can do from Minishift, without modifying the `oc cluster up` bootstrap code.

**Comment by KurtStam** [comment]
@gbraad isn't cluster up being deprecated? If so where would this functionality then end up?

**Comment by praveenkumar** [comment]
@KurtStam for 3.11 `oc cluster up` still there so we need to maintain current state of minishift around 3.11 lifecycle. What come next is still not sure atm and we sent mail to minishift user ML about it https://lists.minishift.io/archives/list/minishift@lists.minishift.io/thread/BNSSBI2KYCWHJSEUUBIW4LNXG3N3TLJS/

**Comment by KurtStam** [comment]
So you are saying I should bring this up the openshift team who are maintaining `oc`?

**Comment by gbraad** [comment]
`oc` will not be used for cluster bring up. The new installer is a completely different thing and handles certificate in a controlled manner, unlike how clusterup generated it's own every time.

**Comment by gbraad** [comment]
In other words, as you mentioned this is deprecated going forward, although 3.11 will still be maintained. With emphasize on maintained, not enhanced... So this will unlikely be considered to be changed. We have requested similar functionality for more than a year.

**Comment by LalatenduMohanty** [comment]
@KurtStam I also do not see this getting fixed in 3.11. However we can see how minishift usecase for OpenShift 4.0 handles this.
