### ISSUE TITLE
cmd-config.feature file fails on windows powershell terminal 

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#3018]
### General information

  * Minishift version: master
  * OS: Windows
  * Hypervisor: Hyper-V / VirtualBox

### Steps to reproduce

  1. Use powershell terminal and run
  2. make integration MINISHIFT_BINARY=/path/to/minishift.exe GODOG_OPTS="-tags cmd-config"
```
--- Failed steps:

  Scenario: Setting iso-url key to a non existing path # features\cmd-config.feature:181
    Then stderr should contain # features\cmd-config.feature:183
      Error: Output did not match. Expected: ''file:///home/Downloads/my_handmade_centos.iso' file is not present', Actual: '['file:///home/Downloads/my_handmade_centos.iso' url is not valid]
```
  3. 
  4. 

### Actual
Failing due to file protocol is not defined as per documentation [1] for windows system

[1] https://docs.okd.io/latest/minishift/using/basic-usage.html#choosing-iso-image
### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
resolved by #3061
