### ISSUE TITLE
Command "minishift docker-env" doesn't report docker unavailability on host

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#3021]
### General information

  * Minishift version: v1.27.0
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. Take a fresh setup or uninstall docker 
  2. minishift start
  3. minishift docker-env
  4. 

### Expected
Should notify to the user that something like ```Docker is not available on the host```

### Actual
No such statement of docker's availability/status is reported 

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
That is expected, `minishift docker-env` is something just put the docker daemon info which is running to VM to the host console. It doesn't have to anything to host docker installation. I am not sure if we should also add this check.

**Comment by LalatenduMohanty** [comment]
Agree with @praveenkumar . If docker is not available then `minishift start with fail as `oc cluster up` is dependent on it. I going to close this issue. Let me know if you disagree and want to reopen this.
