### ISSUE TITLE
minishift fails to start with message: Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases

### ISSUE THREAD

**Issue by tunggad** [minishift/minishift#3028]
### General information

  * Minishift version: minishift-1.27.0-linux-amd64
  * OS: Linux / archlinux
  * Hypervisor: KVM / libvirt

```
[cryto@archserver ~]$ virsh version
Compiled against library: libvirt 4.8.0
Using library: libvirt 4.8.0
Using API: QEMU 4.8.0
Running hypervisor: QEMU 3.0.0

[cryto@archserver ~]$ dnsmasq --version
Dnsmasq version 2.80 Copyright (c) 2000-2018 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN2 DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.

[cryto@archserver ~]$ docker-machine --version
docker-machine version 0.16.0, build HEAD

[cryto@archserver ~]$ virsh --connect qemu:///system net-list
Name State Autostart Persistent
----------------------------------------------------
default active yes yes
docker-machines active yes yes
```

### Steps to reproduce

  1.  minishift start --show-libmachine-logs --v 5
  2. 
  3. 
  4. 

### Expected
minishift starts properly and i can log into the web console

### Actual
minishift fails to start

### Logs

```
(minishift) DBG | GetIP called for minishift
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) Failed to decode dnsmasq lease status: unexpected end of JSON input
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:0b:29:f3
(minishift) DBG | Waiting for the VM to come up... 0
```
[Full log](https://gist.github.com/tunggad/1a15295641c7ceb50686d5c131c93e43)

There is actually no file under /var/lib/libvirt/dnsmasq/docker-machines.leases, but why isn't  it there or how to create one properly?

**Comment by tunggad** [comment]
I found this issue in Fedora Bugzilla reported back in June 2015: https://bugzilla.redhat.com/show_bug.cgi?id=1228631

It states that libvirt for some reasons from particular version does not use the dnsmasq managed lease database (the .leases files) anymore, that's why for the libvirt-managed networks there is also no .leases file -> no file under /var/lib/libvirt/dnsmasq/docker-machines.leases for docker-machines network -> kvm driver gets the above error

So i wonder, how could the kvm driver of @dhiltgen work since then?

**Comment by tunggad** [comment]
For the network docker-machines, i also tried to add this following line to /var/lib/libvirt/dnsmasq/docker-machines.conf (the configuration file of the dnsmasq instance created by libvirt for the network)

`dhcp-leasefile=/var/lib/libvirt/dnsmasq/docker-machines.leases`

But it does not make any effect, still get the error when starting minishift

**Comment by anjannath** [comment]
@tunggad Just wondering, do you have another instance of dnsmasq running other than the one started by libvirt? I have used minishift on ArchLinux not very long ago, without any issues.

**Comment by tunggad** [comment]
@anjannath: hi, no, the default instance of the dnsmasq systemd deamon is not running because i have disabled the systemd dnsmasqd.service immediatelly after installing dnsmasq package

**Comment by gbraad** [comment]
we are at a fixed version of the driver at the moment. are you using the binary as stated or do you compile your own version?

also, we do not use docker-machine as external binary... so I beg to question, are you maybe using the driver as a dependency from the docker-machine installation/recipe?

**Comment by tunggad** [comment]
@gbraad: Hi, i installed the driver as required by the [minishift installation guide](https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html) for arch linux, as root i executed these two commands:

```
# curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-centos7 -o /usr/local/bin/docker-machine-driver-kvm
# chmod +x /usr/local/bin/docker-machine-driver-kvm
```

**Comment by tunggad** [comment]
@mwiens: hi Max, how did you solve this issue https://github.com/kubernetes/minikube/issues/906 2 years ago? Two years later i stuck with same problem.

**Comment by tunggad** [comment]
i think i come closer to the problem, but it's still not a solution. Somehow the VM started by kvm driver can't get/lease an IP from the dnsmasq instances started by libvirtd for the two networks: default and docker-machines. That's why both functions `getIPByMACFromLeaseFile()` and `getIPByMacFromSettings()` in `GetIP()` can't get the IP of the VM.

libvirt shows the the same, no IP has been leased to any VM in both networks: docker-machines and default

```
[root@archserver ~]# virsh net-dhcp-leases docker-machines
 Expiry Time   MAC address   Protocol   IP address   Hostname   Client ID or DUID
-----------------------------------------------------------------------------------

[root@archserver ~]# virsh net-dhcp-leases default
 Expiry Time   MAC address   Protocol   IP address   Hostname   Client ID or DUID
-----------------------------------------------------------------------------------
```

I really dont know why dnsmasq didn't lease IP to the VM (boot2docker.iso) started by the kvm driver. I'm sure that the both dnsmasq instances for the two networks are there and active:

```
[root@archserver ~]# systemctl status libvirtd.service
● libvirtd.service - Virtualization daemon
   Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2018-11-25 15:38:41 UTC; 4h 36min ago
     Docs: man:libvirtd(8)
           https://libvirt.org
 Main PID: 6686 (libvirtd)
    Tasks: 21 (limit: 32768)
   Memory: 51.7M
   CGroup: /system.slice/libvirtd.service
           ├─ 755 /usr/bin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-s>
           ├─ 756 /usr/bin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-s>
           ├─ 785 /usr/bin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/docker-machines.conf --leasefile-ro >
           ├─ 786 /usr/bin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/docker-machines.conf --leasefile-ro >
           └─6686 /usr/bin/libvirtd

```

**Comment by aakarshg** [comment]
I've hit this issue as well @tunggad were you able to find a workaround?
