### ISSUE TITLE
Failed to retrieve dnsmasq leases

### ISSUE THREAD

**Issue by surajnarwade** [minishift/minishift#303]
while I did: 

    $ minishift start --show-libmachine-logs --v=5

I am getting following error:

    Getting to WaitForSSH function...
    (minishift) Calling .GetSSHHostname
    (minishift) DBG | GetIP called for minishift
    (minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
    (minishift) DBG | Failed to decode dnsmasq lease status: unexpected end of JSON input
    (minishift) DBG | Unable to locate IP address for MAC 52:54:00:52:15:33
    Error getting ssh command 'exit 0' : unexpected end of JSON input

**Comment by hferentschik** [comment]
What OS are you using and which hypervisor? Also which version of Minishift?

**Comment by surajnarwade** [comment]
OS is fedora and hypervisor is KVM, minishift version is latest (v1.0.0-beta.2)

**Comment by surajnarwade** [comment]
since I am not able to reproduce the error today, I am closing this issue, as of now, minishift is working fine for me
