### ISSUE TITLE
Minishift on Windows initial start up failing due to non-recursive DNS server response

### ISSUE THREAD

**Issue by Talisen** [minishift/minishift#3030]
### General information

  * Minishift version: 1.27.0 (using Centos 7 ISO)
  * OS: Windows
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. Have a DNS server defined in Windows settings where the DNS server is configured to not allow recursion on requests
  2. Attempt to run minishift startup with **minishift start --vm-driver=virtualbox**

### Expected

The minishift start process / docker pull should ignore any responses from DNS servers that fail in the lookup.

### Actual

The minishift start process sees the failed lookup first (due to no recursion) and completely fails the install process before waiting for another response from a different (secondary) server.

This is similar to the issue found in https://github.com/docker/for-mac/issues/1025

### Logs

$ minishift start --vm-driver=virtualbox
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ......................... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... OK
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Pulling the OpenShift Container Image .Error pulling the OpenShift container image: ssh command error:
command : docker pull openshift/origin-control-plane:v3.11.0
err     : exit status 1
output  : Trying to pull repository docker.io/openshift/origin-control-plane ...
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: server misbehaving

**Comment by gbraad** [comment]
There is likely no secondary defined... can you check `minishist ssh -- cat
/etc/resolv.conf`... you can start `minishift start --network-nameserver
8.8.8.8` to force additional nameservers.

**Comment by Talisen** [comment]
Hi @gbraad,

Once I removed the local non-recursive DNS server from my Windows networking settings, the installation worked. 

If I delete the minishift, re-add my non-recursive DNS server to my Windows network settings, it fails again. I ran your command with the following output:

```
# Generated by NetworkManager
nameserver 10.0.2.3
```

If you add that --network-nameserver flag, then it works properly. My thought was that the minishift start script should wait until all responses are retrieved from the nameservers available, rather than failing on the first response. That would make it more robust.

Cheers!

**Comment by anjannath** [comment]
Closing this as the issue can be solved using the `--network-nameserver` flag
