### ISSUE TITLE
Checkpoint vpn interferes with minishift start

### ISSUE THREAD

**Issue by lycollicott** [minishift/minishift#3032]
### General information

  * Minishift version:  v1.27.0+707887e
  * OS:  Windows
  * Hypervisor:  VirtualBox

I have to run Checkpoint VP, but it causes this error on "minishift start"....

-- Starting Minishift VM .... FAIL E1126 09:11:10.844730   16764 start.go:491] Error starting the VM: Error starting stopped host: Error setting up host only network on machine start: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm minishift --nic2 hostonly --nictype2 82540EM --nicpromisc2 deny --hostonlyadapter2 VirtualBox Host-Only Ethernet Adapter #2 --cableconnected2 on failed:
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 529 of file VBoxManageModifyVM.cpp
. Retrying.
Error starting the VM: Error starting stopped host: Error setting up host only network on machine start: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm minishift --nic2 hostonly --nictype2 82540EM --nicpromisc2 deny --hostonlyadapter2 VirtualBox Host-Only Ethernet Adapter #2 --cableconnected2 on failed:
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 529 of file VBoxManageModifyVM.cpp

### Steps to reproduce

  1. Uninstall Checkpoint VPN & reboot
  2. minishift delete --clear-cache
  3. minishift start
  4. Re-install Checkpoint VPN & reboot
  5. minishift start

### Expected

The host-only adapter exists, so I expected it to be used.

### Actual

minishift tries to create another host-only adapter which fails

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5
[minishift_logs.txt](https://github.com/minishift/minishift/files/2615687/minishift_logs.txt)
` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
This is a known issue and is documented in the troubleshooting segment.
See #1309

**Comment by gbraad** [comment]
This behaviour is part of the driver. You could create the VM without being attached to the VPN and from the Virtualbox management console modify to use the host-only adapter. However, you would still run into issues that the VPN software will use `0/0` route all, which prevents traffic to reach the VM correctly
