### ISSUE TITLE
adding template-service-broker fails repeatedly on macOS

### ISSUE THREAD

**Issue by mohitsuman** [minishift/minishift#3040]
### General information

  * Minishift version: `minishift v1.27.0+707887e`
  * OS: `macOS`
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox : `Default`

### Steps to reproduce

  1. Run: `./minishift openshift component add template-service-broker`

### Expected
The command should execute without errors and be consistent on macOS

### Logs
https://pastebin.com/q7UQgbKC

Can you please have a look at this ?

**Comment by anjannath** [comment]
@amitkrout Can you try to reproduce this on your mac?

**Comment by amitkrout** [comment]
@anjannath Checking

**Comment by amitkrout** [comment]
@anjannath I am not able to reproduce it 
```
$ ./minishift openshift component list
The following OpenShift components are available: 
	- automation-service-broker
	- service-catalog
	- template-service-broker
Amits-MacBook-Pro:minishift-1.27.0-darwin-amd64 amit$ ./minishift openshift component add template-service-broker
Adding template-service-broker ...
I1203 10:01:19.709940   10483 interface.go:26] Installing "openshift-template-service-broker" ...
I1203 10:01:19.711398   10483 apply_template.go:81] Installing "template-service-broker-apiserver"
I1203 10:01:39.099601   10483 apply_template.go:81] Installing "tsb-registration"
I1203 10:02:12.682823   10483 interface.go:41] Finished installing "openshift-template-service-broker"
```
@mohitsuman It seems the component add command executed much earlier before the ```apiserver``` is responsive. Can please try it again on a clean setup.
