### ISSUE TITLE
Document the known behavior related to pre-requisite installer

### ISSUE THREAD

**Issue by coolbrg** [minishift/minishift#3045]
Taking the reference of this PR description https://github.com/minishift/minishift/pull/3027#issue-232942367

One known behavior is following
`
If there exists an external switch in HyperVisor, then, it is being observed that it is not able to created new external switch(Default behavior, only one switch is bound to one network adapter).
`

I think this should be added as `Note` in the documentation.

**Comment by LalatenduMohanty** [comment]
I do not think only having this information in documentation is enough, we should communicate the same through the command output.
