### ISSUE TITLE
Only some images are cached when image caching is true

### ISSUE THREAD

**Issue by jroper** [minishift/minishift#3048]
On minishift v1.26.1+1e20f27:

```
$ minishift version
minishift v1.26.1+1e20f27
```

When image-caching is true:

```
$ minishift config view
- image-caching                      : true
- memory                             : 6GB
```

Only some images get cached:

```
$ minishift image list
openshift/origin-control-plane:v3.11.0
openshift/origin-docker-registry:v3.11.0
openshift/origin-haproxy-router:v3.11.0
```

The rest of the images:

```
$ minishift image list --vm
docker.io/openshift/origin-cli:v3.11.0
docker.io/openshift/origin-control-plane:v3.11.0
docker.io/openshift/origin-deployer:v3.11.0
docker.io/openshift/origin-docker-registry:v3.11.0
docker.io/openshift/origin-haproxy-router:v3.11.0
docker.io/openshift/origin-hyperkube:v3.11.0
docker.io/openshift/origin-hypershift:v3.11.0
docker.io/openshift/origin-node:v3.11.0
docker.io/openshift/origin-pod:v3.11.0
docker.io/openshift/origin-service-serving-cert-signer:v3.11
docker.io/openshift/origin-web-console:v3.11.0
```

Are not cached. For me this is a big problem, my home internet connection is terrible, so slow in fact that most of the time, minishift fails to start due to timeouts.

**Comment by gbraad** [comment]
You can add images to cache by configuration.
We have only selected a subset to get the environment running.

**Comment by LalatenduMohanty** [comment]
I think OpenShift used to require the images we cache by default, but with recent changes in OpenShift it needs more images. So we need to revisit this and update the list of default images for caching.

**Comment by jroper** [comment]
I found where the list is and am happy to submit a PR to fix, except one thing that I don't understand - the list currently has images such as `openshift/origin-control-plane:v3.11.0`, but the images I found in the docker registry are `docker.io/openshift/origin-control-plane:v3.11.0`, ie, prefixed with `docker.io/`. I don't know if that's significant or not, and also should the list contain only `docker.io/` prefixed images?

**Comment by gbraad** [comment]
you do not need to prefix them. The prefix is not relevant... and actually gets added due to the `docker.io` registry offering them. If the images would be pulled from a registry mirror, or an alternative repository, you would have this a prefix. this way this also applies and works correctly when the Red Hat registry is used.

**Comment by gbraad** [comment]
For v3.9.0 you need to configure:
```
{
        "cache-images": [
                "openshift/origin:v3.9.0",
                "openshift/origin-deployer:v3.9.0",
                "openshift/origin-docker-registry:v3.9.0",
                "openshift/origin-haproxy-router:v3.9.0",
                "openshift/origin-pod:v3.9.0",
                "openshift/origin-web-console:v3.9.0"
        ],
        "HostFolders": [],
        "addons": {
                "anyuid": {
                        "Name": "anyuid",
                        "Enabled": false,
                        "Priority": 0
                }
        }
}
```

**Comment by gbraad** [comment]
For v3.10.0 you need to configure:
```
```

**Comment by jroper** [comment]
I've been looking into this a little more, and it seems for some of the images, the cache has no effect. Here's minishift telling me which images it is loading:

```
   Importing 'openshift/origin-cli:v3.11.0' ....... OK
   Importing 'openshift/origin-control-plane:v3.11.0' .......... OK
   Importing 'openshift/origin-deployer:v3.11.0' .... OK
   Importing 'openshift/origin-hyperkube:v3.11.0' ....... OK
   Importing 'openshift/origin-hypershift:v3.11.0' ........ OK
   Importing 'openshift/origin-node:v3.11.0' .............. OK
   Importing 'openshift/origin-web-console:v3.11.0' ...... OK
   Importing 'openshift/origin-pod:v3.11.0' ... OK
```

And then I can see those images loaded:

```
~$ docker image ls
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
openshift/origin-node            v3.11.0             1ee32f0f1358        11 days ago         1.17GB
openshift/origin-control-plane   v3.11.0             42c2b8502db5        11 days ago         826MB
openshift/origin-deployer        v3.11.0             37bb9ae58884        11 days ago         381MB
openshift/origin-hypershift      v3.11.0             8a7cdb9dbb4d        11 days ago         546MB
openshift/origin-hyperkube       v3.11.0             ec9f996a4924        11 days ago         506MB
openshift/origin-cli             v3.11.0             845c96386aa3        11 days ago         381MB
openshift/origin-pod             v3.11.0             46578bcb563c        11 days ago         258MB
openshift/origin-web-console     v3.11.0             4a50a201bfa2        4 months ago        339MB
```

But then later, this changes:

```
$ docker image ls
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
openshift/origin-node            v3.11.0             1ee32f0f1358        11 days ago         1.17GB
openshift/origin-control-plane   v3.11.0             edf09f393863        11 days ago         826MB
<none>                           <none>              42c2b8502db5        11 days ago         826MB
openshift/origin-deployer        v3.11.0             37bb9ae58884        11 days ago         381MB
<none>                           <none>              8a7cdb9dbb4d        11 days ago         546MB
openshift/origin-hypershift      v3.11.0             cd11c2683cd8        11 days ago         546MB
openshift/origin-hyperkube       v3.11.0             aee304af3ce9        11 days ago         506MB
<none>                           <none>              ec9f996a4924        11 days ago         506MB
openshift/origin-cli             v3.11.0             845c96386aa3        11 days ago         381MB
openshift/origin-pod             v3.11.0             46578bcb563c        11 days ago         258MB
openshift/origin-web-console     v3.11.0             4a50a201bfa2        4 months ago        339MB
```

What you can see there is that control-plane, hypershift and hypekube have been redownloaded and replaced. But I had only just exported those from a previous start of minishift. The result is that on my 3mb internet connection, minishift can never start because it always has to redownload gigabytes of artifacts, which is impossible in the 5 minute timeout that it uses.

**Comment by praveenkumar** [comment]
@jroper I understand your pain here but this is not what minishift is doing but the Openshift. All the deployment which have `imagepolicy` to `alwaysPull` are going to pull those images and not going to use the cached one.

**Comment by jroper** [comment]
Ok, makes sense.

**Comment by jroper** [comment]
That said, isn't this a Minishift issue? What's the point in Minishift offering a caching feature if it doesn't work? And, aren't Minishift and OpenShift made by the same company? You can't pass blame off for the problem onto your own company, when you do that it makes it sound like RedHat is a dysfunctional company whose own employees can't or won't talk to each other.
