### ISSUE TITLE
Minishift Start Failed: The Minishift VM does not support network assignment

### ISSUE THREAD

**Issue by eliu** [minishift/minishift#3049]
### General information

  * Minishift version: `v1.28.0+48e89ed`
  * OS: macOS
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. Run `minishift config set iso-url b2d`
  2. Run `minishift start`

### Expected
Minishift started up and running.

### Actual
Start failed with the following messages:
```
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ............................... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- Writing current configuration for static assignment of IP address ... The Minishift VM does not support network assignment
```

**Comment by gbraad** [comment]
B2D is not a supported ISO type anymore...
Also, B2D never can support network assignment...

So yes, the message is therefore very right...

WONTFIX -> invalid
On Wed, Dec 5, 2018 at 2:29 PM Liu Hongyu <notifications@github.com> wrote:
>
> General information
>
> Minishift version: v1.28.0+48e89ed
> OS: macOS
> Hypervisor: VirtualBox
>
> Steps to reproduce
>
> Run minishift config set iso-url b2d
> Run minishift start
>
> Expected
>
> Minishift started up and running.
>
> Actual
>
> Start failed with the following messages:
>
> -- Starting profile 'minishift'
> -- Check if deprecated options are used ... OK
> -- Checking if https://github.com is reachable ... OK
> -- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
> -- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
> -- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
> -- Checking if VirtualBox is installed ... OK
> -- Checking the ISO URL ... OK
> -- Checking if provided oc flags are supported ... OK
> -- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
> -- Minishift VM will be configured with ...
>    Memory:    4 GB
>    vCPUs :    2
>    Disk size: 20 GB
> -- Starting Minishift VM ............................... OK
> -- Checking for IP address ... OK
> -- Checking for nameservers ... OK
> -- Checking if external host is reachable from the Minishift VM ...
>    Pinging 8.8.8.8 ... OK
> -- Checking HTTP connectivity from the VM ...
>    Retrieving http://minishift.io/index.html ... OK
> -- Checking if persistent storage volume is mounted ... OK
> -- Checking available disk space ... 0% used OK
> -- Writing current configuration for static assignment of IP address ... The Minishift VM does not support network assignment
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by gbraad** [comment]
@praveenkumar @LalatenduMohanty maybe the message should add "WARN" instead.
But also when started with b2d we should fail...

**Comment by eliu** [comment]
i see. i wonder if the b2d way should be removed from documentation since it is not suppoerted anymore.

**Comment by gbraad** [comment]
The documentation should not mention this (or state it is not supported anymore)... where did you find it?

**Comment by gbraad** [comment]
https://docs.okd.io/latest/minishift/using/basic-usage.html

Hmmmm, @LalatenduMohanty @robin-owen ?

**Comment by robin-owen** [comment]
@gbraad I wasn't aware that b2d was unsupported and could result in failure. If that's the case, removing it from our documentation is absolutely the right thing to do. As far as I know, b2d is still listed in the help text for `minishift start`, as well.

**Comment by gbraad** [comment]
I just noticed this... but we dropped it actually quite a while ago due to
the persistent issues it caused.

**Comment by robin-owen** [comment]
That makes sense to me, and I have no problem removing b2d from our documentation. What should we use as an alternative example for the "Choosing the ISO Image" section in that case? The Fedora ISO?

**Comment by LalatenduMohanty** [comment]
Follow up issues created #3051 and #3053

**Comment by sberyozkin** [comment]
Hi, I've updated to minishift v1.30.0+186b034.
After running  `minishift start --vm-driver virtualbox --iso-url centos` I'm getting the same error, 

Any hints will be appreciated, thanks

**Comment by sberyozkin** [comment]
I've deleted ~/.minishift/config and ~/.kube/config on the advice from my colleague and it started working, thanks

**Comment by fxgx99** [comment]
Hi @sberyozkin did you delete the entire .minishift/config or just the config folder? I am having the same issue. Just making sure I am clear on what to remove

**Comment by VAMDIEGO** [comment]
[Hi](https://github.com/minishift/minishift/issues/3049#issuecomment-456777308) @sberyozkin, this works for me, thanks a lot, well I deleted all .minishift folder, this on windows 10
