### ISSUE TITLE
Add-on to create imagesecret for registry.redhat.io

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#3050]
Ref: #2875

**Comment by LalatenduMohanty** [comment]
@anjannath  Why do we need an add-on for this, We are fixing this with a extra flag in https://github.com/minishift/minishift/pull/3016

**Comment by anjannath** [comment]
@LalatenduMohanty It seems that login to docker is not necessary, creating the secret is enough. I asked @praveenkumar on IRC yesterday, he can confirm!
