### ISSUE TITLE
Replace <username> with $(whoami) for easy copy/pasting

### ISSUE THREAD

**Issue by gastaldi** [minishift/minishift#3056]
### General information

  * Minishift version: Latest
  * OS: Linux
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. Go to https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#kvm-driver-fedora
  2.  Copy/paste the command in there
  3. See it fail because the `<username>` token needs to be replaced

### Expected
Copy/paste and the command works

### Actual
It does not

**Comment by LalatenduMohanty** [comment]
resolved via #3057
