### ISSUE TITLE
Creation of config file fails when there is no existing Minishift home directory

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#306]
Due to https://github.com/minishift/minishift/blob/master/cmd/minikube/cmd/root.go#L131 inclusion minishift now break if we build from master because initconfig try to create config file to a uninitialized directory location.

```
$ ./minishift delete
F0118 12:09:05.549463   16996 root.go:164] Cannot create file /home/prkumar/.minishift/config/config.json: open /home/prkumar/.minishift/config/config.json: no such file or directory
```

**Comment by hferentschik** [comment]
Merged. Thanks. Good catch.
