### ISSUE TITLE
Add command to close systemtray

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#3062]
### General information

  * OS: macOS / Windows

### Expected

Subcommand for closing system tray from CLI.

### Actual

System tray cannot be closed via CLI.

**Comment by gbraad** [comment]
We need not just a command to close the systray, but also to stop the background process of the sshfs hostfolder. They work according to the same way... so any issue that exists in the systemtray related to lifecycle, applies to 3 other components; proxy, sshfs, systray.

I would suggest to have a general kill/quit function that performs stop ob all these services and have the systray handle this when it is requested to stop.

**Comment by anjannath** [comment]
If we add a command to kill services, we need to expose the service command, i mean not keep it hidden any more. And what about the subcommands of services, like systemtray, proxy, etc.. i guess we can make those visible as well.

**Comment by LalatenduMohanty** [comment]
Resolved via #3118
