### ISSUE TITLE
An already installed minishift instance does not start without internet connection

### ISSUE THREAD

**Issue by aldettinger** [minishift/minishift#3065]
### General information

  * Minishift version: minishift v1.27.0+707887e
  * OS: Linux
  * Hypervisor: KVM

### Steps to reproduce

  1. minishift start (without internet connection)
  
### Expected
  Minishift starts with an internet connection for installation.
  After the installation, I would like to be able to start without internet connection.

### Logs
  Logs with an without internet connection could be found there:
  https://gist.github.com/aldettinger/ca2d87548a7e45468328688850bee410

**Comment by anjannath** [comment]
@aldettinger From the attached logs, you are hitting the issue #2675 which happens irrespective of the network connection. You should keep an eye on #2675 and put your findings there.

**Comment by aldettinger** [comment]
Thanks for answering @anjannath.

I had a try with the workaround described in #2675 without success. Actually, I doubt that this is the same issue. Users in #2675 are reporting an intermittent issue, while on my laptop minishift consistently start with an internet connection. And conversely, minishift consistently does not start without an internet connection.

I try to go further, invoking oc cluster up from within the vm:
`minishift ssh`
`/var/lib/minishift/bin/oc cluster up --routing-suffix 192.168.42.82.nip.io --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0' --public-hostname 192.168.42.8`
But same result, the kubelet-api is not started.

I then tried to access the liveness url manually:
`[docker@minishift /]$ curl https://192.168.42.8:8443/healthz?timeout=32scurl: (7) Failed connect to192.168.42.8:8443;` **No route to host**

Last, I tried route -n:
`[docker@minishift /]$ route -n`
`Kernel IP routing table`
`Destination     Gateway         Genmask         Flags Metric Ref    Use Iface`
`0.0.0.0         192.168.122.1   0.0.0.0         UG    100    0        0 eth0`
`172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0`
`192.168.42.0    0.0.0.0         255.255.255.0   U     101    0        0 eth1`
`192.168.122.0   0.0.0.0         255.255.255.0   U     100    0        0 eth0`

Any idea why the host is not reachable ? Does it look to be the right track ?

**Comment by gbraad** [comment]
Minishift needs an internet connection for the initial start, as it tries to pull container images that are needed for the chosen OpenShift version. After a succesful deployment, the instance can be restarted. However, a redeployment needs to pull images again, as at the moment not all of them are correctly cached.

The issue described in #2675 has happened for other users that had too little memory assigned as of version 3.11 it is recommended to use more than 4GB as usable memory.

However, have you been able to actually deploy a working instance? If so, can you assist in comparing the route tables? I have not been able to reproduce this... I usually travel around the city and deploy OpenShift from the images and from a repository mirror. (I disallow internet connection on the notebook to be used by the VMs while travelling)

**Comment by aldettinger** [comment]
I've reinstalled from scratch just in case, but still the same issue. At this stage my current understanding is that minishift needs an internet connection at ***each*** startup, not only when installing.

I propose to remove the ***resolution/duplicate*** tag on this issue and wait few weeks in case someone as an idea.

**Comment by gbraad** [comment]
I will have to look into this. This doesn't sounds like it is supposed to be. It could very well be that v3.11 is th cause of a regression. We were able to deploy without a connectivity before... and I always test like this (v3.10), but have to admit that since v3.11 had proxy issues, I haven't deploy this as often as I would have liked.

**Comment by praveenkumar** [comment]
From the logs which @aldettinger share, looks like with 3.11 it always polls some of the images from outside and not use what might be inside in the VM.

```
1213 16:42:33.243803 5114 pod_workers.go:186] Error syncing pod dfcadfa6552711112062fbf1121a691c ("kube-controller-manager-localhost_kube-system(dfcadfa6552711112062fbf1121a691c)"), skipping: failed to "StartContainer" for "controllers" with ErrImagePull: "rpc error: code = Unknown desc = Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.42.1:53: server misbehaving"
```
