### ISSUE TITLE
Minishift Start Failed: The Minishift VM does not support dns server assignment on windows

### ISSUE THREAD

**Issue by karthiklabs** [minishift/minishift#3068]
### General information

  * Minishift version:  3.11.0
  * OS: Windows 10
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. Install minishift on Windows 10
  2. Run the below command
  3. minishift start --network-nameserver 8.8.8.8 --vm-driver=virtualbox --memory=2GB
  

### Expected
Minishift should be started

### Actual
Minishift was not started with below message.

Writing current configuration for static assignment of IP address ... The Minishift VM does not support network assignment

### Logs
https://gist.github.com/karthiklabs/20c7c3a2334365a7246450115a463158

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
can you share:

```
$ minishift config view
```

and start with:

```
$ minishift start --show-libmachinelogs -v5 --network-nameserver 8.8.8.8 --vm-driver=virtualbox --memory=2GB
```

**Comment by gbraad** [comment]
@anjannath you changed the title. Is there an issue with assigning a DNS server and the network assignment?
