### ISSUE TITLE
minishift start: "invalid argument: could not find capabilities for domaintype=kvm"

### ISSUE THREAD

**Issue by leonidaxx90** [minishift/minishift#3075]
### General information

  * Minishift version: v1.28.0+48e89ed
  * OS: Linux (ubuntu 18.10)
  * Hypervisor: KVM

### Steps to reproduce

  1. sudo apt install qemu-kvm libvirt-daemon libvirt-daemon-system
  2. sudo usermod -a -G libvirt root
  3. newgrp libvirt
  4. curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-ubuntu16.04 -o /usr/local/bin/docker-machine-driver-kvm 
  5. chmod +x /usr/local/bin/docker-machine-driver-kvm
  6 systemctl is-active libvirtd ---> return active
  7. sudo virsh net-list --all ---> return Name=Default | State=active | Autostart=yes | Persistent=yes
  8. cp /path/to/minishift/executable /usr/bin
  9. minishift start --show-libmachine-logs -v5

### Expected
Minishift start

### Actual
Minishift return this error:

Failed to create the VM: virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for domaintype=kvm ')
. FAIL E1214 07:34:09.398740    9185 start.go:493] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for domaintype=kvm ')

### Logs
[Log start minishift](https://gist.github.com/leonidaxx90/59b58a2350329e0ebce3ee446fc8bae7)

**Comment by leonidaxx90** [comment]
I solved the issue. The problem is the nested virtualization. In virtual box I'm not able to enable this feature.
Then I used VmWare. In properties tab on my vm ubuntu I set processor as image below

![vmw](https://user-images.githubusercontent.com/6053465/50005625-4102e780-ffab-11e8-8312-aefffe6de0ac.PNG)

**Comment by erikerikson** [comment]
this error can be resolved as explained in https://superuser.com/questions/1330271/configuring-kvm-inside-ubuntu-hyper-v-client for hyper-v
