### ISSUE TITLE
How to pull container images from an alternative registry (when docker.io is not available)

### ISSUE THREAD

**Issue by Foroughi** [minishift/minishift#3080]
### General information

  * Minishift version: 1.28
  * OS: Windows
  * Hypervisor: Hyper-V

### Steps to reproduce without

  1. minishift start
 
### Actual
As my current location is banned by docker.io, minishift can't download the container image and it faces with Error 503 which is obvious why.So I started to use a proxy with openshift v3.10 (also v3.11). But after reading previous threats i noticed pulling up the openshift is kinda buggy under proxied env.(it gets a time our error and the kube folder is not being created) So if I don't use a proxy the minishift can't download the docker. if I use proxy pulling up the openshift will face with a time out error. 

I tried to use v3.9 but it returns this error, so I can't use this version as well

"Minishift does not support OpenShift version v3.9.0. You need to use a version >= v3.10.0"

Whats the solution now? ill appreciate if you can help me.

**Comment by Foroughi** [comment]
I found this switch in the docs. how i can use it ? is there any other resources online so i can fill it up this switch and prevent the minishift to download the docker from docker.io?

**Comment by gbraad** [comment]
you have to use

```
$ minishift start --openshift-version v3.10
```

to begin with, but when docker.io is unavailable, you have to look for a registry mirror. For more details see: https://docs.docker.com/registry/recipes/mirror/ . You can specify this option with a config option `registry-mirror`. You could actually try to use the Chinese mirror (whcih is one I sometimes test with).

If this does not work, you would have to resort to using a VPN, although this can introduce other issues when a route all is used/forced. 

Proxy is not really buggy... at least not for v3.10. The implementation provided by v3.11 is not correct and can cause issues during and after deployment. But yes, some proxy options have been removed and might cause some additional settings to be performed on your end. Have you tried this?

**Comment by gbraad** [comment]
We can not distribute the images by alternative means. If the aformentioned functionality does not work for you there is not much we can do.
