### ISSUE TITLE
'minishift start' fails at the end with an error Error: Get https://apis/apiregistration.k8s.io/v1beta1/apiservices: dial tcp :8443: connect: connection refused

### ISSUE THREAD

**Issue by PoojaChirp** [minishift/minishift#3081]
### General information

  * Minishift version: 1.28.0
  * OS: Linux / macOS / Windows: Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox: Hyper-V

### Steps to reproduce

minishift start

### Logs

C:\Users\user>minishift delete
You are deleting the Minishift VM: 'minishift'. Do you want to continue [y/N]?: y
Deleting the Minishift VM...
Error deleting the Minishift VM: exit status 1

C:\Users\user>minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ...
   Use of HYPERV_VIRTUAL_SWITCH has been deprecated
   Please use: minishift config set hyperv-virtual-switch External VM Switch
FAIL

-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... OK
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ...
   'Default Switch' ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    1 GB
   vCPUs :    2
   Disk size: 5 GB
-- Starting Minishift VM ................................. OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... WARN
   Importing 'openshift/origin-control-plane:v3.11.0' . CACHE MISS
   Importing 'openshift/origin-docker-registry:v3.11.0' . CACHE MISS
   Importing 'openshift/origin-haproxy-router:v3.11.0' . CACHE MISS
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Pulling the OpenShift Container Image ............ OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ........................................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0' --public-hostname 172.22.95.218 --routing-suffix 172.22.95.218.nip.io
err     : Process exited with status 1
output  : Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
E1215 03:36:00.278584    3417 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11.0 anonymously
Pulling image openshift/origin-cli:v3.11.0
Image pull complete
Pulling image openshift/origin-node:v3.11.0
E1215 03:36:00.905001    3417 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-node:v3.11.0 anonymously
Pulled 5/6 layers, 89% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 172.22.95.218 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I1215 03:36:14.200610    3417 config.go:40] Running "create-master-config"
I1215 03:36:20.598674    3417 config.go:46] Running "create-node-config"
I1215 03:36:22.014627    3417 flags.go:30] Running "create-kubelet-flags"
I1215 03:36:23.071086    3417 run_kubelet.go:49] Running "start-kubelet"
I1215 03:36:23.769236    3417 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I1215 03:36:56.868622    3417 interface.go:26] Installing "kube-proxy" ...
I1215 03:36:56.869200    3417 interface.go:26] Installing "kube-dns" ...
I1215 03:36:56.869209    3417 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I1215 03:36:56.869216    3417 interface.go:26] Installing "openshift-apiserver" ...
I1215 03:36:56.871965    3417 apply_template.go:81] Installing "kube-dns"
I1215 03:36:56.872456    3417 apply_template.go:81] Installing "openshift-apiserver"
I1215 03:36:56.880823    3417 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I1215 03:36:56.881706    3417 apply_template.go:81] Installing "kube-proxy"
I1215 03:37:02.176736    3417 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: Get https://172.22.95.218:8443/apis/apiregistration.k8s.io/v1beta1/apiservices: dial tcp 172.22.95.218:8443: connect: connection refused

**Comment by grugrugrunpa** [comment]
- Minishift version: 1.28.0
- OS: Windows 10
- Hypervisor: VirtualBox

i changed /var/lib/minishift/networking-eth1

> DEVICE=eth0
> IPADDR=192.168.99.100
> NETMASK=24
> GATEWAY=10.0.2.2
> DNS1=10.0.2.3
> DNS2=
to
> DEVICE=eth1
> IPADDR=192.168.99.100
> NETMASK=24

it seems to work.

**Comment by praveenkumar** [comment]
@PoojaChirp As per your logs look like you didn't delete the previous instance completely and had the error.

```console
> C:\Users\user>minishift delete
You are deleting the Minishift VM: 'minishift'. Do you want to continue [y/N]?: y
Deleting the Minishift VM...
**Error deleting the Minishift VM: exit status 1**
```

Can you try to delete it with logging option and see why it is failed?

```console
> C:\Users\user>minishift delete --show-libmachine-logs --v=5
```

**Comment by mmgil** [comment]
I received this error when i removed the vm manually

You removed manually the VM from your Hyper-V?

In powershell execute Get-VM and see if VM of the minishift appears

**Comment by jithinsha** [comment]
I too find the same error. Did any find the fix.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.13.0/minishift-centos7.iso'
 346.00 MiB / 346.00 MiB [================================] 100.00% 0s
-- Starting Minishift VM ................. OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... WARN
   Importing 'openshift/origin-control-plane:v3.11.0'  CACHE MISS
   Importing 'openshift/origin-docker-registry:v3.11.0'  CACHE MISS
   Importing 'openshift/origin-haproxy-router:v3.11.0'  CACHE MISS
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Pulling the OpenShift Container Image ................................................................................................................................ OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ..........................................................................................................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0' --public-hostname 192.168.42.136 --routing-suffix 192.168.42.136.nip.io
err     : exit status 1
output  : Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Pulling image openshift/origin-cli:v3.11.0
E0201 14:54:16.156999    2157 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11.0 anonymously
Image pull complete
Pulling image openshift/origin-node:v3.11.0
E0201 14:54:21.891018    2157 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-node:v3.11.0 anonymously
Pulled 5/6 layers, 85% complete
Pulled 5/6 layers, 86% complete
Pulled 5/6 layers, 88% complete
Pulled 5/6 layers, 89% complete
Pulled 5/6 layers, 90% complete
Pulled 5/6 layers, 91% complete
Pulled 5/6 layers, 93% complete
Pulled 5/6 layers, 94% complete
Pulled 5/6 layers, 95% complete
Pulled 5/6 layers, 96% complete
Pulled 5/6 layers, 98% complete
Pulled 5/6 layers, 100% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.42.136 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0201 15:01:06.172688    2157 config.go:40] Running "create-master-config"
I0201 15:01:09.715952    2157 config.go:46] Running "create-node-config"
I0201 15:01:11.585104    2157 flags.go:30] Running "create-kubelet-flags"
I0201 15:01:12.585733    2157 run_kubelet.go:49] Running "start-kubelet"
I0201 15:01:13.124502    2157 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
E0201 15:06:13.130219    2157 run_self_hosted.go:571] API server error: Get https://192.168.42.136:8443/healthz?timeout=32s: dial tcp 192.168.42.136:8443: connect: connection refused ()
Error: timed out waiting for the condition
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by gbraad** [comment]
I am sorry, but this is not the same error:You get the error on the
webconsole; 192.168.42.136:8443: connect: connection refused () for
the websconsole check (one of the last steps).

Check if you are running a firewall, or VPN... and also, check if you
enabled the anyuid add-on (do not enabled, but apply instead)
Check the issue tracker for issues related to the webconsole.
