### ISSUE TITLE
Xpaas add-on should be dependent on `redhat-registry-login` add-on

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#3083]
https://github.com/minishift/minishift/tree/master/addons/xpaas add-on should have a dependency on `redhat-registry-login` add-on as the iimage streams in the add-on is dependent on red hat registry secret.

**Comment by LalatenduMohanty** [comment]
@agajdosi @anjannath WDYT?

**Comment by anjannath** [comment]
@LalatenduMohanty Yes this is needed, I think @agajdosi is going to handle this also in PR #3034

**Comment by LalatenduMohanty** [comment]
Resolved by #3034
