### ISSUE TITLE
Error during setting 'minishift' as active profile: The specified path to the kube config '/home/laurence/.minishift/machines/minishift_kubeconfig' does not exist

### ISSUE THREAD

**Issue by magicluo0755** [minishift/minishift#3084]
### General information

  * Minishift version:  minishift v1.28.0+48e89ed
  * OS: Ubunut 16.04 LTS
  * Hypervisor:  Virtualbox-5.2_5.2.22-126460~Ubuntu~xenial_amd64.deb
  * Path  env variable config:
        export MINISHIFT=/opt/minishift
        export PATH=$PATH:$MINISHIFT

### Steps to reproduce

  1.  minishift start --vm-driver virtualbox --show-libmachine-logs -v5

### Expected
minishift start succesfully and running well

### Logs

Console show logs:
Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to the kube config '/home/laurence/.minishift/machines/minishift_kubeconfig' does not exist

for the error ,check folder  ~/.kube doesn't exist，and not found  ~/.minishift/machines/minishift_kubeconfig files too.

More log  details:
https://gist.github.com/magicluo0755/dd44e47eda36fc61f88616ddc21b8047

**Comment by anjannath** [comment]
@magicluo0755 You might want to try out the work around mentioned here: https://github.com/minishift/minishift/issues/3023#issue-382863194

But, that won't work for you as you do not have a `~/.kube` folder. Have you try deleting the minishift instance and trying to start again?

**Comment by magicluo0755** [comment]
minishift delete  && minishift start  try  many times, the error still exists，but win10/virtualbox running OK.  
no idea about this problem...

> @magicluo0755 We have received other reports of this happening, See #3023 the problem is this is not consistently reproducible.
> 
> You might want to try out the work around mentioned here: [#3023 (comment)](https://github.com/minishift/minishift/issues/3023#issue-382863194)
> 
> But, that won't work for you as you do not have a `~/.kube` folder. Have you tried if deleting the minishift instance and trying to start again fixes the issues?

**Comment by b0wser** [comment]
Having same issue. Helped following steps:

1. minishift delete -f
2. minishift startv --profile minishift

**Comment by vap0rtranz** [comment]
This is a duplicated of https://github.com/minishift/minishift/issues/3023, though the fix there hasn't worked for me.

**Comment by ethanhunt80** [comment]
> Having same issue. Helped following steps:
> 
> 1. minishift delete -f
> 2. minishift start --profile minishift

This one helped me working the issue around.

Thanks!

**Comment by yossishm** [comment]
> Having same issue. Helped following steps:
> 
> 1. minishift delete -f
> 2. minishift start --profile minishift

did the trick!

**Comment by sudharsanomprakash** [comment]
> Having same issue. Helped following steps:
> 
> 1. minishift delete -f
> 2. minishift start --profile minishift

This work helped me to fix the issue. Thanks
