### ISSUE TITLE
RBAC role creation step for etcd-operator failed

### ISSUE THREAD

**Issue by samuzzal-choudhury** [minishift/minishift#3089]
### General information

  * Minishift version: v1.27.0+707887e
  * OS: macOS
  * Hypervisor: xhyve and VirtualBox

### Steps to reproduce

  1. `oc login https://<ip address>:8443 -u system`
  2. `minishift addons enable admin-user`
  3. `curl https://raw.githubusercontent.com/coreos/etcd-operator/master/example/rbac/cluster-role-template.yaml | sed -e 's/<ROLE_NAME>/etcd-operator/' | oc apply -f -`

### Expected
No error in role creation

### Actual
```
Error from server (Forbidden): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io is forbidden: User "system" cannot create clusterroles.rbac.authorization.k8s.io at the cluster scope: no RBAC policy matched
```

Any help on this is appreciated.

**Comment by anjannath** [comment]
To use the `admin-user` add-on, you have to apply it `minishift addons apply admin-user`.
Enabling an add-on applies it automatically after minishift start.

Follow these steps:
```
$ minishift start
$ minishift addons apply admin-user
$ eval $(minishift oc-env)
$ oc login -u admin (Enter any passwd)
$ curl https://raw.githubusercontent.com/coreos/etcd-operator/master/example/rbac/cluster-role-template.yaml | sed -e 's/<ROLE_NAME>/etcd-operator/' | oc apply -f -
```

**Comment by praveenkumar** [comment]
@samuzzal-choudhury Have a look to https://docs.okd.io/latest/minishift/troubleshooting/troubleshooting-getting-started.html#github-api-rate-limit-exceeded to resolve that Rate limit error and try again.
