### ISSUE TITLE
Github Rate Limiting interferes with user-modeled testing

### ISSUE THREAD

**Issue by markllama** [minishift/minishift#3090]
### General information

  * Minishift version: v3.11.0
  * OS: Linux CentOS
  * Hypervisor: KVM 

### Description

A user can get an apparent failure when trying to run minishift if enough users from their network are pulling information from Github.  The current solution is to offer users a troubleshooting option to create and use a Github API token.

This is an undo burden on the user.  Will see an apparently intermittent failure. They must then actively find the troubleshooting page.  They must create a Github API token and then supply it in an environment variable.  This API token potentially can be lost or accidentally shared.  Users may choose not to create one and stop trying minishift.

A better solution is to place the initial resource that minishift needs from the API in a location that is not subject to rate limiting that is out of the control of the user. 

### Steps to reproduce

  1. unset MINISHIFT_GITHUB_API_TOKEN
  2. minishift start
  3. repeat or load github API to failure
  4. 

### Expected

```
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.172:8443/console

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin


-- Exporting of OpenShift images is occuring in background process with pid 20869.
```

### Actual

```
mlamouri@hp-blade13 minikube]$ minishift start 
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... 
   Hit github rate limit: GET https://api.github.com/repos/openshift/origin/releases/tags/v3.11.0: 403 API rate limit exceeded for 66.187.233.206. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 44m59s]
FAIL
```

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by fabiand** [comment]
+1 

We are recommending to use minishift for testing kubevirt on Openshift. Issues like this can easily disturb the first steps of newcomers. And are actually hard to fix for a user.

For us devs it would be easy enough to store the binary in a non-ratelimited location. ... For such an key demo component

**Comment by anjannath** [comment]
By default, we fail when this preflight check does not go as expected (like hitting the rate limiting issue), Maybe we should change this to just WARN and continue? @minishift/minishift-dev WDYT?

**Comment by markllama** [comment]
The problem is that any block due to API rate limiting will frustrate a potential customer.  I suspect there are ways to get the same information without using a potentially blocking data source.

**Comment by praveenkumar** [comment]
> Maybe we should change this to just WARN and continue? 

@anjannath If we change it to `WARN` then a user who is going to execute `minishift start` and hit with this API rate limit then how would he/she get to know what is the issue. For a restart (stop-start) I am OK because then mostly user have cached binaries.

**Comment by anjannath** [comment]
@praveenkumar He'll know that he hit the Github rate limit issue, when he/she sees the `WARN` appear after the Github check happens, we don't use the API to download `oc` binaries.we use the API to check if a version is valid.

If the user does `minishift start` he won't be providing a custom version... and if he does provide a version and sees `WARN` because of rate limiting, he'd still be able to download the `oc` binaries (provided he gave a valid version to the flag `--openshift-version`, if not the download will fail)

**Comment by gbraad** [comment]
> A better solution is to place the initial resource that minishift needs from the API in a location that is not subject to rate limiting that is out of the control of the user.

place the OpenShift version file as a static resource on GitHub pages. However, this would still fail as 'unknown version' when the proxy does not function properly... which means this function needs better error handling.
