### ISSUE TITLE
curl: (56) Received HTTP code 403 from proxy after CONNECT

### ISSUE THREAD

**Issue by birajdarabhishek1** [minishift/minishift#3094]
I have installed Minishift with Proxy setting.
The server is accessible via web console at:
https://192.168.42.76:8443/console

You are logged in as:
User: developer
Password:

To login as administrator:
oc login -u system:admin

Issue:
[root@minishift ~]# oc status
Unable to connect to the server: Forbidden

[root@minishift ~]# oc login -u system:admin
error: Forbidden

[root@minishift ~]# curl https://192.168.42.76:8443/console
curl: (56) Received HTTP code 403 from proxy after CONNECT

How can I connect console from my VM, or Outside Network.

**Comment by praveenkumar** [comment]
@birajdarabhishek1 Can you export `192.168.42.76` as `no-proxy` env variable and then try again?

**Comment by gbraad** [comment]
right, can you provide the given proxy information from your shell
(please obfuscate)?
since minishift is hosted inside a VM on your host, the company proxy
should not be used to access it.
For this purpose, add the IP address of the instance to your NO_PROXY
(and no_proxy) variables

On Wed, Dec 26, 2018 at 1:16 PM Praveen Kumar <notifications@github.com> wrote:
>
> @birajdarabhishek1 Can you export 192.168.42.76 as no-proxy env variable and then try again?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by birajdarabhishek1** [comment]
docker@minishift:~$ env | grep proxy
no_proxy=localhost,127.0.0.1,172.30.1.1,192.168.42.100,192.168.42.1
https_proxy=http://10.115.27.54:3128
http_proxy=http://10.115.27.54:3128
docker@minishift:~$
docker@minishift:~$ export no_proxy=192.168.42.100
docker@minishift:~$ env | grep proxy
no_proxy=192.168.42.100
https_proxy=http://10.115.27.54:3128
http_proxy=http://10.115.27.54:3128

Not Working: 
[root@minishift ~]# oc status
Unable to connect to the server: Forbidden

[root@minishift ~]# oc new-app https://github.com/sclorg/nodejs-ex -l name=myapp
warning: Cannot check if git requires authentication.
error: Unable to connect to the server: Forbidden
error: Unable to connect to the server: Forbidden
error: Unable to connect to the server: Forbidden
error: Unable to connect to the server: Forbidden
error: can't lookup images: Post https://192.168.42.100:8443/apis/image.openshift.io/v1/namespaces/myproject/imagestreamimports: Forbidden
error: unable to locate any images in image streams, image stream images with a 'supports' annotation, local docker images with name "nodejs"

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.


Also Please let me know how can I access the console URL  from my laptop?

**Comment by birajdarabhishek1** [comment]
minishift config set no-proxy <My Instance IP> 

I used this command , but it is not working.

Also please let me know how can I access the console url from my laptop ?

**Comment by gbraad** [comment]
your `no_proxy` contained `.100`, but not `.76` ?
Also, `Forbidden` indicates another issue... authentication fails.

> how can I access

Use your browser?
