### ISSUE TITLE
minishift 1.28.x doesn't work with service catalog

### ISSUE THREAD

**Issue by shahtab** [minishift/minishift#3095]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

MINISHIFT_ENABLE_EXPERIMENTAL=y  ./minishift start --openshift-version v3.11.0 --memory 2048 --cpus 2 --vm-driver=virtualbox --extra-clusterup-flags "--enable=*,service-catalog"
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ..................... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 14% used OK
-- Writing current configuration for static assignment of IP address ... OK
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster .-- Extra 'oc' cluster up flags (experimental) ...
   '--enable=*,service-catalog'
Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0' --public-hostname 192.168.64.4 --routing-suffix 192.168.64.4.nip.io --enable=*,service-catalog
err     : exit status 1
output  : error: cannot use --enable when the cluster is already initialized, use cluster add instead
### Actual
Should bring up the cluster.  If i don't enable service-catalog them it comes up without issues

### Logs
➜  OKD ./minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Stopped
DiskUsage:  14% of 19G (Mounted On: /mnt/vda1)
CacheUsage: 1.659 GB (used by oc binary, ISO or cached images)
➜  OKD ./minishift version
minishift v1.28.0+48e89ed

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
Can you try to first deploy openshift and then use `oc cluster add` to enable Service Catalog on a working OpenShift?

We do not provide support for Service Catalog from the side of Minishift. If it fails, they need to be reported upstream at openshift/origin.

**Comment by LalatenduMohanty** [comment]
Can you try `$ minishift openshift  component add service-catalog` command. You can list the components using `$ minishift openshift  component list`.
