### ISSUE TITLE
Can't install minishift on Ubuntu 18.04

### ISSUE THREAD

**Issue by jhahn1234** [minishift/minishift#3096]
Trying to install minishift on Ubuntu on AWS but getting the following error. Any help would be greatly appreciated.

### General information

  * Minishift 1.29.0: 
  * OS: Linux 
  * Hypervisor: KVM

### Steps to reproduce

  1. Downloaded minishift 1.29.0
  2. sudo ./minishift start --show-libmachine-logs -v5
  3. 
  4. 

### Expected

minishift to start

### Actual

received an error

### Logs
root@ip-172-31-30-169:/usr/local/bin# sudo ./minishift start --show-libmachine-logs -v5
-- minishift version: v1.29.0+72fa7b2
-- Starting profile 'minishift'
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:33321
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Failed to fetch machine
(minishift) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(minishift) DBG | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x585606]
(minishift) DBG |
(minishift) DBG | goroutine 11 [running]:
(minishift) DBG | github.com/libvirt/libvirt-go.(*Domain).GetState(0x0, 0x0, 0x0, 0x0, 0x0)
(minishift) DBG |       /go/src/github.com/libvirt/libvirt-go/domain.go:1021 +0x66
(minishift) DBG | github.com/dhiltgen/docker-machine-kvm.(*Driver).GetState(0xc4200f21c0, 0x0, 0x0, 0x0)
(minishift) DBG |       /go/src/github.com/dhiltgen/docker-machine-kvm/kvm.go:498 +0x8b
(minishift) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).GetState(0xc4200d77c0, 0xd559b0, 0xc420011858, 0x0, 0x0)
(minishift) DBG |       /go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:191 +0x33
(minishift) DBG | reflect.Value.call(0xc42005c7e0, 0xc42000e280, 0x13, 0x8e76f6, 0x4, 0xc420038f20, 0x3, 0x3, 0x2, 0x41ef04, ...)
(minishift) DBG |       /usr/local/go/src/reflect/value.go:434 +0x91f
(minishift) DBG | reflect.Value.Call(0xc42005c7e0, 0xc42000e280, 0x13, 0xc420027720, 0x3, 0x3, 0xc420027718, 0x44dda1, 0xc4200eb520)
(minishift) DBG |       /usr/local/go/src/reflect/value.go:302 +0xa4
(minishift) DBG | net/rpc.(*service).call(0xc420019e00, 0xc420019940, 0xc420011850, 0xc420065880, 0xc42011c680, 0x8391e0, 0xd559b0, 0x16, 0x864320, 0xc420011858, ...)
(minishift) DBG |       /usr/local/go/src/net/rpc/server.go:387 +0x144
(minishift) DBG | created by net/rpc.(*Server).ServeCodec
(minishift) DBG |       /usr/local/go/src/net/rpc/server.go:481 +0x404
Error getting machine state: unexpected EOF
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ...
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM ....Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:40953
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Failed to fetch machine
(minishift) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(minishift) DBG | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x585606]
(minishift) DBG |
(minishift) DBG | goroutine 7 [running]:
(minishift) DBG | github.com/libvirt/libvirt-go.(*Domain).GetState(0x0, 0x0, 0x0, 0x0, 0x0)
(minishift) DBG |       /go/src/github.com/libvirt/libvirt-go/domain.go:1021 +0x66
(minishift) DBG | github.com/dhiltgen/docker-machine-kvm.(*Driver).GetState(0xc4201041c0, 0x0, 0x0, 0x0)
(minishift) DBG |       /go/src/github.com/dhiltgen/docker-machine-kvm/kvm.go:498 +0x8b
(minishift) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).GetState(0xc4200e97a0, 0xd559b0, 0xc4200109a0, 0x0, 0x0)
(minishift) DBG |       /go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:191 +0x33
(minishift) DBG | reflect.Value.call(0xc42005c7e0, 0xc42006e298, 0x13, 0x8e76f6, 0x4, 0xc420033f20, 0x3, 0x3, 0x0, 0x0, ...)
(minishift) DBG |       /usr/local/go/src/reflect/value.go:434 +0x91f
(minishift) DBG | reflect.Value.Call(0xc42005c7e0, 0xc42006e298, 0x13, 0xc420025720, 0x3, 0x3, 0x0, 0x0, 0x0)
(minishift) DBG |       /usr/local/go/src/reflect/value.go:302 +0xa4
(minishift) DBG | net/rpc.(*service).call(0xc420067ec0, 0xc420067a00, 0xc42005f8d0, 0xc42006d980, 0xc42000c680, 0x8391e0, 0xd559b0, 0x16, 0x864320, 0xc4200109a0, ...)
(minishift) DBG |       /usr/local/go/src/net/rpc/server.go:387 +0x144
(minishift) DBG | created by net/rpc.(*Server).ServeCodec
(minishift) DBG |       /usr/local/go/src/net/rpc/server.go:481 +0x404
 FAIL E1228 07:15:22.129733   22279 start.go:494] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
Error starting the VM: Error getting the state for host: unexpected EOF

**Comment by anjannath** [comment]
@jhahn1234 Looks like you have a stale VM from previous runs, please delete it using `minishift delete -f` and start afresh. 

Also, please follow the guide to add yourself to libvirt group: https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#kvm-driver-ubuntu, and possibly don't run with sudo.

**Comment by Linuxinode** [comment]
> @jhahn1234 Looks like you have a stale VM from previous runs, please delete it using `minishift delete -f` and start afresh.
> 
> Also, please follow the guide to add yourself to libvirt group: https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#kvm-driver-ubuntu, and possibly don't run with sudo.

bro save the day
