### ISSUE TITLE
Minishift and LDAP Provider

### ISSUE THREAD

**Issue by mmgil** [minishift/minishift#3099]
### General information

  * Minishift version: 
  * OS:  Windows
  * Hypervisor: Hyper-V

### Steps to reproduce

  1. In a prompt of the Powershell i configurated a hastable with all configurations for the LDAP:

```
$i = @{
    oauthConfig = @{
        alwaysShowProviderSelection = "false";
        assetPublicURL = 'https://app.mmgil.com.br:8443/console/';
        grantConfig = @{
            method = "auto";
            serviceAccountMethod = "prompt";
        }
        identityProviders = @(@{
            name = "ADProvider";
            challenge = "true";
            login = "true";
            mappingMethod = "add";
            provider = @(@{
                apiVersion = "v1";
                kind = "LDAPPasswordIdentityProvider";
                attributes = @(@{
                    email = @("mail");
                    id = @("dn");
                    name = @("displayname");
                    preferredUsername = @("sAMAccountName");
                    bindDN = "CN=Administrador do Sistema Openshift,OU=OPENSHIFT,OU=INFRAESTRUTURA,OU=RIBEIRAO-PIRES,OU=_SistemasMMGIL,DC=mmgil,DC=com,DC=br";
                    bindPassword = "Passw0rd!";
                    insecure = "true";
                    url = "ldap://mmgil.com.br:389/OU=OPENSHIFT,OU=INFRAESTRUTURA,OU=RIBEIRAO-PIRES,OU=_SistemasMMGIL,DC=mmgil,DC=com,DC=br?cn?sub?(enabled=true)";
                })
            })
        })
        masterPublicURL = 'https://app.mmgil.com.br:8443';
        masterURL = 'https://app.mmgil.com.br:8443';
        sessionConfig = @{ sessionMaxAgeSeconds = 300; sessionName = "ssn"; sessionSecretsFile = "null"; }
        templates = "null";
        tokenConfig = @{ accessTokenMaxAgeSeconds = 86400; authorizeTokenMaxAgeSeconds = 300; }
    }
}

$i = $i | ConvertTo-Json -Depth 7

$i = $i -replace '\r\n',''
$i = $i -replace '\s',''
$i = $i -replace '"','\"'
```
  2. With this procedure i get the following JSON:

`
{\"oauthConfig\":{\"tokenConfig\":{\"accessTokenMaxAgeSeconds\":86400,\"authorizeTokenMaxAgeSeconds\":300},\"grantConfig\":{\"serviceAccountMethod\":\"prompt\",\"method\":\"auto\"},\"assetPublicURL\":\"https://app.mmgil.com.br:8443/console/\",\"alwaysShowProviderSelection\":false,\"identityProviders\":[{\"provider\":[{\"attributes\":[{\"id\":\"dn\",\"url\":\"ldap://mmgil.com.br:389/OU=OPENSHIFT,OU=INFRAESTRUTURA,OU=RIBEIRAO-PIRES,OU=_SistemasMMGIL,DC=mmgil,DC=com,DC=br?cn?sub?(enabled=true)\",\"name\":\"displayname\",\"bindPassword\":\"Passw0rd!\",\"insecure\":true,\"bindDN\":\"CN=AdministradordoSistemaOpenshift,OU=OPENSHIFT,OU=INFRAESTRUTURA,OU=RIBEIRAO-PIRES,OU=_SistemasMMGIL,DC=mmgil,DC=com,DC=br\",\"preferredUsername\":\"sAMAccountName\",\"email\":\"mail\"}],\"apiVersion\":\"v1\",\"kind\":\"LDAPPasswordIdentityProvider\"}],\"name\":\"ADProvider\",\"mappingMethod\":\"add\",\"login\":true,\"challenge\":true}],\"sessionConfig\":{\"sessionSecretsFile\":null,\"sessionMaxAgeSeconds\":300,\"sessionName\":\"ssn\"},\"templates\":null,\"masterPublicURL\":\"https://app.mmgil.com.br:8443\",\"masterURL\":\"https://app.mmgil.com.br:8443\"}}`

  3. All right, with this JSON i execute the followin command:

```
minishift.exe openshift config set --patch $i;
minishift.exe openshift config set --target kube --patch $i 
```
This command is executed with success.

  4. But, in the test, everything goes wrong ='(

Containers of the minishift dont start. When i execute the command:

`minishift.exe openshift config view`

I received this error:

```
Cannot display the OpenShift configuration: ssh command error:
command : docker exec -t 0804d1338303 cat /etc/origin/master/master-config.yaml
err     : exit status 1
output  : Error response from daemon: Container 0804d13383033b0d7997096b21b1a622dd724d5a9213ff7117072d12b7fc1146 is not running
```

So I went to investigate the container logs, and:

> 
> [docker@openshift ~]$ docker logs 0804d1338303
> Invalid MasterConfig master-config.yaml
>   oauthConfig.identityProvider[0].provider: Invalid value: runtime.Unknown{TypeMeta:runtime.TypeMeta{APIVersion:"", Kind:""}, Raw:[]uint8{0x5b, 0x7b, 0x22, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3a, 0x22, 0x76, 0x31, 0x22, 0x2c, 0x22, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x22, 0x3a, 0x5b, 0x7b, 0x22, 0x62, 0x69, 0x6e, 0x64, 0x44, 0x4e, 0x22, 0x3a, 0x22, 0x43, 0x4e, 0x3d, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x64, 0x6f, 0x53, 0x69, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x4f, 0x70, 0x65, 0x6e, 0x73, 0x68, 0x69, 0x66, 0x74, 0x2c, 0x4f, 0x55, 0x3d, 0x4f, 0x50, 0x45, 0x4e, 0x53, 0x48, 0x49, 0x46, 0x54, 0x2c, 0x4f, 0x55, 0x3d, 0x49, 0x4e, 0x46, 0x52, 0x41, 0x45, 0x53, 0x54, 0x52, 0x55, 0x54, 0x55, 0x52, 0x41, 0x2c, 0x4f, 0x55, 0x3d, 0x52, 0x49, 0x42, 0x45, 0x49, 0x52, 0x41, 0x4f, 0x2d, 0x50, 0x49, 0x52, 0x45, 0x53, 0x2c, 0x4f, 0x55, 0x3d, 0x5f, 0x53, 0x69, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x73, 0x4d, 0x4d, 0x47, 0x49, 0x4c, 0x2c, 0x44, 0x43, 0x3d, 0x6d, 0x6d, 0x67, 0x69, 0x6c, 0x2c, 0x44, 0x43, 0x3d, 0x63, 0x6f, 0x6d, 0x2c, 0x44, 0x43, 0x3d, 0x62, 0x72, 0x22, 0x2c, 0x22, 0x62, 0x69, 0x6e, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x3a, 0x22, 0x31, 0x34, 0x74, 0x77, 0x63, 0x74, 0x79, 0x68, 0x21, 0x30, 0x31, 0x22, 0x2c, 0x22, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x3a, 0x22, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x2c, 0x22, 0x69, 0x64, 0x22, 0x3a, 0x22, 0x64, 0x6e, 0x22, 0x2c, 0x22, 0x69, 0x6e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x22, 0x3a, 0x74, 0x72, 0x75, 0x65, 0x2c, 0x22, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x22, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2c, 0x22, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x22, 0x73, 0x41, 0x4d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2c, 0x22, 0x75, 0x72, 0x6c, 0x22, 0x3a, 0x22, 0x6c, 0x64, 0x61, 0x70, 0x3a, 0x2f, 0x2f, 0x6d, 0x6d, 0x67, 0x69, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x72, 0x3a, 0x33, 0x38, 0x39, 0x2f, 0x4f, 0x55, 0x3d, 0x4f, 0x50, 0x45, 0x4e, 0x53, 0x48, 0x49, 0x46, 0x54, 0x2c, 0x4f, 0x55, 0x3d, 0x49, 0x4e, 0x46, 0x52, 0x41, 0x45, 0x53, 0x54, 0x52, 0x55, 0x54, 0x55, 0x52, 0x41, 0x2c, 0x4f, 0x55, 0x3d, 0x52, 0x49, 0x42, 0x45, 0x49, 0x52, 0x41, 0x4f, 0x2d, 0x50, 0x49, 0x52, 0x45, 0x53, 0x2c, 0x4f, 0x55, 0x3d, 0x5f, 0x53, 0x69, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x73, 0x4d, 0x4d, 0x47, 0x49, 0x4c, 0x2c, 0x44, 0x43, 0x3d, 0x6d, 0x6d, 0x67, 0x69, 0x6c, 0x2c, 0x44, 0x43, 0x3d, 0x63, 0x6f, 0x6d, 0x2c, 0x44, 0x43, 0x3d, 0x62, 0x72, 0x3f, 0x63, 0x6e, 0x3f, 0x73, 0x75, 0x62, 0x3f, 0x28, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x3d, 0x74, 0x72, 0x75, 0x65, 0x29, 0x22, 0x7d, 0x5d, 0x2c, 0x22, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x3a, 0x22, 0x4c, 0x44, 0x41, 0x50, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0x7d, 0x5d}, ContentEncoding:"", ContentType:""}: &Unknown{TypeMeta:TypeMeta{APIVersion:,Kind:,},Raw:*[91 123 34 97 112 105 86 101 114 115 105 111 110 34 58 34 118 49 34 44 34 97 116 116 114 105 98 117 116 101 115 34 58 91 123 34 98 105 110 100 68 78 34 58 34 67 78 61 65 100 109 105 110 105 115 116 114 97 100 111 114 100 111 83 105 115 116 101 109 97 79 112 101 110 115 104 105 102 116 44 79 85 61 79 80 69 78 83 72 73 70 84 44 79 85 61 73 78 70 82 65 69 83 84 82 85 84 85 82 65 44 79 85 61 82 73 66 69 73 82 65 79 45 80 73 82 69 83 44 79 85 61 95 83 105 115 116 101 109 97 115 77 77 71 73 76 44 68 67 61 109 109 103 105 108 44 68 67 61 99 111 109 44 68 67 61 98 114 34 44 34 98 105 110 100 80 97 115 115 119 111 114 100 34 58 34 49 52 116 119 99 116 121 104 33 48 49 34 44 34 101 109 97 105 108 34 58 34 109 97 105 108 34 44 34 105 100 34 58 34 100 110 34 44 34 105 110 115 101 99 117 114 101 34 58 116 114 117 101 44 34 110 97 109 101 34 58 34 100 105 115 112 108 97 121 110 97 109 101 34 44 34 112 114 101 102 101 114 114 101 100 85 115 101 114 110 97 109 101 34 58 34 115 65 77 65 99 99 111 117 110 116 78 97 109 101 34 44 34 117 114 108 34 58 34 108 100 97 112 58 47 47 109 109 103 105 108 46 99 111 109 46 98 114 58 51 56 57 47 79 85 61 79 80 69 78 83 72 73 70 84 44 79 85 61 73 78 70 82 65 69 83 84 82 85 84 85 82 65 44 79 85 61 82 73 66 69 73 82 65 79 45 80 73 82 69 83 44 79 85 61 95 83 105 115 116 101 109 97 115 77 77 71 73 76 44 68 67 61 109 109 103 105 108 44 68 67 61 99 111 109 44 68 67 61 98 114 63 99 110 63 115 117 98 63 40 101 110 97 98 108 101 100 61 116 114 117 101 41 34 125 93 44 34 107 105 110 100 34 58 34 76 68 65 80 80 97 115 115 119 111 114 100 73 100 101 110 116 105 116 121 80 114 111 118 105 100 101 114 34 125 93],ContentEncoding:,ContentType:,} is invalid in this context
> 
> 
> 
> 

is LDAP not supported with Minishift?

### Expected

Minishift using my Active Directory for validate user, password and RBAC.

**Comment by praveenkumar** [comment]
@mmgil we never tested the LDAP with minishift but since it just the openshift confit, it should've have worked, another thing is why the patch command didn't complain about wrong patch file but then pods fails :( @anjannath can you take a look to this?

**Comment by mmgil** [comment]
@praveenkumar Thank's for participate.

Yeah! The command accepted the JSON sent. Before I saw in other threads how to send the JSON.

I just combined this with Powershell for a more user-friendly visualization and better administration for me.

**Comment by anjannath** [comment]
@mmgil @praveenkumar Sorry guys, somehow i missed this issue, will take a look today.
