### ISSUE TITLE
CentosCI builds fails because of missing artifact at artifacts.ci.centos.org/minishift/minishift/master

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#3102]
### General information

CentOS CI fails on htmlproofer finding http://artifacts.ci.centos.org/minishift/minishift/master to be a dead link, we should upload the artifacts to that location to fix the problem.

### Logs

```
09:21:26 - build/contributing/ci.html
09:21:26   *  External link http://artifacts.ci.centos.org/minishift/minishift/master failed: 404 No error
09:21:26 htmlproofer 3.7.2 | Error:  HTML-Proofer found 1 failure!
```

**Comment by LalatenduMohanty** [comment]
> I think there is a clean up job runs which cleans old builds (not sure where is the code but remember this as per some changes we had done in the past to handle the storage capacity in http://artifacts.ci.centos.org/minishift/minishift)

We need to check with CentOS CI folks to keep the http://artifacts.ci.centos.org/minishift/minishift/master available, even if we do not have any build

**Comment by LalatenduMohanty** [comment]
I have sent an email to CI users mailing list.  https://lists.centos.org/pipermail/ci-users/2019-January/000930.html
