### ISSUE TITLE
Missing documentation for hyperkit installation

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#3106]
We do not mention in the documentation [1] that user need to have the `hyperkit` binary for the docker-machine-driver-hyperkit to work.  

User can get the `hyperkit` binary by running `$ brew install hyperkit` or `docker for mac`. 

[1] https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#setting-up-hyperkit-driver

**Comment by LalatenduMohanty** [comment]
https://github.com/machine-drivers/docker-machine-driver-hyperkit/issues/1

**Comment by robin-owen** [comment]
@LalatenduMohanty, is there a particular method here that we prefer over the other? Should we recommend `brew install hyperkit` or installing Docker for Mac? We can always document both (although I think it's better to advocate for a single solution), but one will need to be featured before the other in the docs.

Similarly, do we have a particular preference between the `hyperkit` and `xhyve` driver plug-ins that we want to convey to the reader?

**Comment by jozefizso** [comment]
The minikube prefers the hyperkit, as it replaces the xhyve.

**Comment by LalatenduMohanty** [comment]
> @LalatenduMohanty, is there a particular method here that we prefer over the other? Should we recommend `brew install hyperkit` or installing Docker for Mac? We can always document both (although I think it's better to advocate for a single solution), but one will need to be featured before the other in the docs.

IMO `brew install hyperkit` should be first preference. 


> Similarly, do we have a particular preference between the `hyperkit` and `xhyve` driver plug-ins that we want to convey to the reader?
Not really, Though technically hyperkit supposed to be a better solution than Xhyve, one of the minishift features have issues for hyperkit. So we still suggest Xhyve.

**Comment by LalatenduMohanty** [comment]
@robin-owen I am planning to fix this issue. Have you started working on this? or is it ok if I send the PR.

**Comment by robin-owen** [comment]
@LalatenduMohanty I was just waiting on more information, which you've provided. If you'd like to create a PR yourself, please feel free -- just make sure to tag me in it so I can look it over. :)

Thank you!
