### ISSUE TITLE
Can't do docker login to minishift docker registry.

### ISSUE THREAD

**Issue by ivekpi** [minishift/minishift#3107]
I can't login to minishift docker registry on widows host. 

### General information

  * Minishift version: v1.17.0+f974f0c
  * OS: Windows 10 Pro
  * Hypervisor: Hyper-V 
  * Docker engine: 18.09.0

### Steps to reproduce
  1. minishift start --openshift-version v3.9.0 --cpus=2 --memory=8192
  2. docker login -u admin
  3. oc adm policy add-cluster-role-to-user cluster-admin developer
  4. minishift console, login as user developer
  5. create secure route in default project for docker-registry application
  6. get password hash from Command Line Tools
  7. docker login -u developer -p <cli_tool_hash> docker-registry-default.172.19.45.110.nip.io

### Expected
User is logged in to docker 

### Actual
```
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://docker-registry-default.172.19.45.110.nip.io/v2/: dial tcp 172.19.45.110:443: connect: no route to host
```

### Additional info

λ oc get route
```
NAME              HOST/PORT                                     PATH      SERVICES          PORT       TERMINATION   WILDCARD
docker-registry   docker-registry-default.172.19.45.110.nip.io             docker-registry   5000-tcp   passthrough   None
```

λ oc get route/docker-registry -o yaml
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: 2019-01-06T13:45:13Z
  labels:
    docker-registry: default
  name: docker-registry
  namespace: default
  resourceVersion: "2226"
  selfLink: /apis/route.openshift.io/v1/namespaces/default/routes/docker-registry
  uid: 4b02f002-11b9-11e9-8a1b-4697feddb8f3
spec:
  host: docker-registry-default.172.19.45.110.nip.io
  port:
    targetPort: 5000-tcp
  tls:
    termination: passthrough
  to:
    kind: Service
    name: docker-registry
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2019-01-06T13:45:13Z
      status: "True"
      type: Admitted
    host: docker-registry-default.172.19.45.110.nip.io
    routerName: router
    wildcardPolicy: None
```

**Comment by anjannath** [comment]
@ivekpi If you want to have a route for the docker registry then please use the add-on `registry-route`
```
PS> minishift.exe addons apply registry-route
PS> & minishift.exe oc-env | Invoke-Expression
PS> & minishift.exe docker-env | Invoke-Expression
```
The route url will be printed along with the above instructions when the `registry-route` addon finishes execution.
