### ISSUE TITLE
rvm installation failing in centos ci

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#3111]
https://ci.centos.org/job/minishift/806/console
The issue is likely on the following line

https://github.com/minishift/minishift/blob/42afb63013a8d2f39e5da7db46a8220cacdd8b7a/centos_ci.sh#L167

**Comment by LalatenduMohanty** [comment]
Logs from docs CI https://ci.centos.org/job/minishift-docs/65/consoleFull

**Comment by LalatenduMohanty** [comment]
Looks like an upstream issue https://github.com/rvm/rvm/issues/4465 as @anjannath foundout.

**Comment by anjannath** [comment]
The issue in upstream indicates that the bug got introduced recently, and as a fix we are going to temporarily disable exit at error `set +e` for the `install_docs_prerequisite_packages()` function.
https://github.com/minishift/minishift/blob/42afb63013a8d2f39e5da7db46a8220cacdd8b7a/centos_ci.sh#L153-L175
