### ISSUE TITLE
minishift fails to start up

### ISSUE THREAD

**Issue by danseo-reisys** [minishift/minishift#3113]
### General information

  * Minishift version: 3.11
  * OS: Windows
  * Hypervisor:  VirtualBox

### Steps to reproduce

  1. minishift start   (at home using fios, works fine at work )
  2. 
  3. 
  4. 

### Actual

Error to register VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
Are you on a VPN or using antivirus software?
Please search the issue tracker for similar reports, as this is a duplicate.

**Comment by gbraad** [comment]
This seems to be related to your network settings. Can you explain a little bitm ore detail what the configuration looks like?
