### ISSUE TITLE
minishift and cri-o runtime does not work

### ISSUE THREAD

**Issue by tosin2013** [minishift/minishift#3120]
### General information

  * Minishift version: 3.11
  * OS:  macOS 
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. minishift config set static-ip false
  2. minishift start  --iso-url https://storage.googleapis.com/minikube/iso/minikube-v0.32.0.iso --vm-driver=virtualbox

### Expected
cri-o runtime running on the underlining VM

### Actual
it looks like it is running the docker service as seen below 
```
# oc describe pods/httpd-1-cj84w
Container ID:   docker://dd4cbe3251ef2565be4b3679e0b927bc575cc14cccd7d69bedbd38e6c5d01222
```

### Logs
```
# minishift logs | grep cri
I0114 18:38:24.795823    3437 docker_service.go:253] Docker cri networking managed by kubernetes.io/no-op
minishift logs | grep cri-o -> no results
```
You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
We used to support the minikube iso, but this has been removed/deprecated due to unpredictible results with the `oc cluster up` deployment method.

**Comment by gbraad** [comment]
and why the `minishift config set static-ip false` ?
This is essential to prevent issue with restarts

**Comment by gbraad** [comment]
We decided this is a WONTFIX
