### ISSUE TITLE
helm/tiller/pod issue

### ISSUE THREAD

**Issue by danseo-reisys** [minishift/minishift#3123]
### General information

  * Minishift version: 3.11
  * Windows
  * VirtualBox

### Steps to reproduce

installed sonarqube using helm.  'helm install stable/sonarqube'
'helm list' shows the following on my local minishift 
NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
exiled-tiger    1               Tue Jan 15 15:42:51 2019        DEPLOYED        sonarqube-0.13.1        7.4             local-iac

However, minishift can not create the pod with the following error.
Error creating: pods "exiled-tiger-sonarqube-65d9447f7d-" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{999}: 999 is not an allowed group]  
it probably has something to do with the service account used by tiller called tiller.

I would appreciate any pointer.  Thanks.

**Comment by gbraad** [comment]
how did you setup minishift? did you enable any addons?

**Comment by anjannath** [comment]
@danseo-reisys Have you tried this on any other OpenShift (like OpenShift Online), as this might not be minishift specific issue?
