### ISSUE TITLE
RemoteHost install fails due to unprivileged docker version command

### ISSUE THREAD

**Issue by dmesser** [minishift/minishift#3124]
### General information

  * Minishift version: v1.29.0+72fa7b2
  * OS: Linux
  * Hypervisor: n/a (remote machine on AWS)

### Steps to reproduce

  1. Set up remote machine according to https://docs.okd.io/latest/minishift/using/run-against-an-existing-machine.html#configuring-existing-remote-machine
  2. Ensure passwordless SSH using <user>
  3. Ensure <user> has passwordless SUDO rights on remote machine
  4. Run `minishift start --vm-driver generic --remote-ipaddress <remote_IP_address> --remote-ssh-user <username> --remote-ssh-key <private_ssh_key>`

### Expected

Minishift deploys OpenShift successfully remote machine. Specifically uses `sudo` when trying to run `docker version --format '{{.Server.APIVersion}}'`

### Actual

Minishift fails with an error received when trying to run `docker version --format '{{.Server.APIVersion}}'` on the remote host: 

```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.26/version: dial unix /var/run/docker.sock: connect: permission denied
```

This is due to the fact that /var/run/docker.sock is owned by root:root. It's group is not docker nor wheel. Hence any calls to the docker CLI tool should be run via sudo. (see https://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/)
Minishift attempts to run this command without `sudo`

### Logs

```
-- Starting profile 'minishift'
-- Starting the OpenShift cluster using 'generic' hypervisor ...
-- Preparing Remote Machine ..... OK
-- Starting to provision the remote machine .......... OK
Error determining Docker settings: ssh command error:
command : docker version --format '{{.Server.APIVersion}}'
err     : exit status 1
output  : 
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.26/version: dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by gbraad** [comment]
Minishift will not use `sudo`, right. Can you create a group, like `docker` and `chgrp docker /var/run/docker.sock` with `chmod 770` as permissions?

**Comment by gbraad** [comment]
BTW, what is the target OS on AWS you are using?

**Comment by gbraad** [comment]
Why do we need to use `sudo`? We require you to prepare the node... and I am not use why you say it gets reverted?

@praveenkumar WDYT?

**Comment by gbraad** [comment]
Is the user part of the `wheel` group?

**Comment by dmesser** [comment]
> Why do we need to use `sudo`? 

Because a non-root user should not be able to run the docker command. The reasoning is outlined by the article from Dan Walsh I referenced.

> We require you to prepare the node... 

Yup, I followed all the instructions outlined here: https://docs.okd.io/latest/minishift/using/run-against-an-existing-machine.html#configuring-existing-remote-machine - at the very least they are incomplete giving the expectation is to run privileged docker commands without root permissions. But I suggest to use `sudo` to follow proper security practices - as minishift depends on sudo anyways it should not break anything.

> and I am not sure why you say it gets reverted?

Me neither to be honest, but that's what happens:

```
$ ssh -l centos <redacted>
Last login: Wed Jan 16 23:17:56 2019 from <redacted>

[centos@minishift ~]$ sudo ls -ahl /var/run/docker.sock 
srw-rw----. 1 root root 0 Jan 17 15:44 /var/run/docker.sock
[centos@minishift ~]$ sudo chgrp wheel /var/run/docker.sock 
[centos@minishift ~]$ sudo ls -ahl /var/run/docker.sock 
srw-rw----. 1 root wheel 0 Jan 17 15:44 /var/run/docker.sock
[centos@minishift ~]$ exit

$ minishift start --profile aws --vm-driver generic --remote-ipaddress <redacted> --remote-ssh-user centos --remote-ssh-key ~/.ssh/id_rsa 
-- Starting profile 'aws'
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'generic' hypervisor ...
-- Preparing Remote Machine ..... OK
-- Starting to provision the remote machine .......... OK
-- Switching active profile to 'aws'
Error determining Docker settings: ssh command error:
command : docker version --format '{{.Server.APIVersion}}'
err     : exit status 1
output  : 
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.26/version: dial unix /var/run/docker.sock: connect: permission denied

ssh -l centos <redacted> -- ls -ahl /var/run/docker.sock
srw-rw----. 1 root root 0 Jan 17 15:47 /var/run/docker.sock

ssh -l centos <redacted> -- id
uid=1000(centos) gid=1000(centos) groups=1000(centos),4(adm),10(wheel),190(systemd-journal) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```

**Comment by gbraad** [comment]
As written in the documentation:

> Ensure that the user has sudo access without a password or use root

**Comment by gbraad** [comment]
> > and I am not sure why you say it gets reverted?

> Me neither to be honest, but that's what happens:

I would suggest you look into this as part of the actual issue. We expect the user to be able to login as a root user or sudo without password. Perhaps a certain check does not have the `sudo` command... and it feels like this is from the provisioner. I'll have a look, and also ping @praveenkumar for this...

... but reverting settings do not sound OK

**Comment by gbraad** [comment]
This might possibly be the cause:

https://github.com/minishift/minishift/blob/bd59f32efc7f6b6d36d1e0de8c5261b8eb862169/pkg/minikube/cluster/cluster.go#L393

**Comment by dmesser** [comment]
Yes, I've found this as well - hence my suggestion to run this command with `sudo`. 
My system has passwordless SSH and passwordless sudo set up correctly. The problem is not the system config - not being able to run `docker version` without `sudo` is a conscious default on CentOS. I can test this with contemporary Fedora later, but that setting makes sense to me.

**Comment by gbraad** [comment]
We never run this command with sudo (this is kind of dating back to minikube), but AFAIR `sudo` should be triggered from the less privilged docker user on a regular instance, to a sudo session. And yes, by default we do NOT allow this access without sudo. so wondering why you run into this... :-s. need to run some tests, just haven't able to reserve the time yet.

**Comment by praveenkumar** [comment]
We need to check on our end since our created CentOS iso also have only `docker` user with passwordless sudo access, which we use to perform all the operation, will check what is the permission on that side to make sure there is no redundancy.

**Comment by praveenkumar** [comment]
Alright so I spend decent amount of time to figure out the root case for this issue. I do know now from where it is coming from but I am still not able to figure it out that then how come the centos ISO we create sets the correct `group` to `/var/run/docker.sock` :(

On the ISO which we create have `docker` as group and that explain why in our case why we don't need `sudo` but I tried to look in our iso build repo (https://github.com/minishift/minishift-centos-iso) and didn't find where we set this info :(

This happen on the `start.go` when we setup the dockerEnv to current process.

https://github.com/minishift/minishift/blob/b21ac83199910adf24a3a27f14e2ae9494f2a183/cmd/minishift/cmd/start.go#L248

```console
[docker@minishift ~]$ sudo ls -ahl /var/run/docker.sock 
srw-rw----. 1 root docker 0 Jan 18 05:50 /var/run/docker.sock
```

**Comment by gbraad** [comment]
in the provisioner we actually use `sudo` for the responding check.

**Comment by gbraad** [comment]
the official AMI, as in my region there are several others...  :-s

On Fri, Jan 18, 2019 at 5:30 PM Daniel Messer <notifications@github.com> wrote:
>
> FWIW I am on the CentOS 7 Marketplace AMI.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by dmesser** [comment]
Yup, the one maintained by centos.org and comes with a marketplace subscription.

**Comment by gbraad** [comment]
It does not happen during the provisioner or deployment phase, so this either baked into the image or part of the way the daemon sets this up (we do have a startup script inherited from minikube).

**Comment by gbraad** [comment]
> marketplace subscription

Not having this... will inquire about this also.

**Comment by dmesser** [comment]
I just tried this with the Fedora 29 Cloud Base AMI - same behaviour.

**Comment by gbraad** [comment]
there seems to be something that changes the group ownership in our base image that we have not bee nable to track down.

We can be sure that the group ownership needs to be set. So yes, we do not allow access with `sudo`, biut for the ISO this gets set as `docker` group... which is why in some cases the use of `sudo` isn't needed.

**Comment by dmesser** [comment]
Why not properly call out the docker commands using `sudo` ? Seems like the proper solution to me and requires one less configuration step on your side.

**Comment by praveenkumar** [comment]
@dmesser sure that also can be done, and we need to move all our docker commands behind the `sudo`.

**Comment by gbraad** [comment]
I would rather see an abstraction to use either a group, or detect to use sudo.
but this is gonna take a lot of work... just as reviewing all commands.

This is VERY specific to our remote/existing usecas, which in my
opinion SHOULD be security controlled by `sudo` OR a group owenership.
To stay consistent with the actual minishift flow on the ISO image, I
think we should go for the group ownership.


On Fri, Jan 18, 2019 at 8:25 PM Praveen Kumar <notifications@github.com> wrote:
>
> @dmesser sure that also can be done, and we need to move all our docker commands behind the sudo.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by praveenkumar** [comment]
@dmesser Hey there, we put a PR for this and want you to give a try of the produced artifacts ( https://ci.appveyor.com/project/budhrg/minishift/builds/22330195/artifacts ), let us know if that works for you.
