### ISSUE TITLE
How to get it working on Arch Linux?

### ISSUE THREAD

**Issue by vonpupp** [minishift/minishift#3126]
### General information

  * Minishift version: 1.30.0
  * OS: Arch Linux
  * Hypervisor: KVM

### Steps to reproduce

  1. `sudo pacman -S libvirt qemu dnsmasq ebtables`
  2. `pacaur -S docker-machine-kvm`
  3. Manually changed `#group = "root"` with `group = "kvm"` (same as step 3 on the setting-up-virtualization-environment.adoc guide)
  4. `sudo usermod -a -G kvm,libvirt $(whoami)` (same as step 2 on guide)
  5. `newgrp libvirt` (same as step 4 on guide)
  6. `sudo virsh net-start default` (step 2 on guide, section configure libvirt networking)
  7. `sudo virsh net-autostart default` (step 3 on guide, section configure libvirt networking)
  8. `wget https://github.com/minishift/minishift/releases/download/v1.30.0/minishift-1.30.0-linux-amd64.tgz; tar zxvf minishift-1.30.0-linux-amd64.tgz`
  9. `chmod +x minishift-1.30.0-linux-amd64/minishift`
  10. `minishift-1.30.0-linux-amd64/minishift start`
  11.  `minishift-1.30.0-linux-amd64/minishift openshift version`

Here I get:
```
Error getting the OpenShift cluster version: ssh command error:
command : docker exec   origin openshift version
err     : exit status 1
output  : Error response from daemon: No such container: origin
```

When I try to `oc cluster up` I get:
```
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... FAIL
   Error: Minor number must not contain leading zeroes "09"
```

So it seems to be related to [#13249].

I also noticed that when I do `oc status` the `.kube/config` file is not created, maybe due to the previous error, I don't know. It seems to be related to [#2829]. Herewith the output:
```
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
```

### Expected

I would expect `oc status` to work.

### Actual

It is not working, see above.

### Logs

```
-- minishift version: v1.30.0+186b034
-- Starting profile 'minishift'
Found binary path at /usr/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:46161
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
The 'minishift' VM is already running.
```

[#13249]: https://github.com/openshift/origin/issues/13249
[#2829]: https://github.com/minishift/minishift/issues/2829

**Comment by vonpupp** [comment]
Thank you for your reply. I am still learning openshift/minishift

$ minishift delete -f

```
Unable to delete entries from kube config: open /home/av/.kube/config: no such file or directory
Deleting the Minishift VM...
Minishift VM deleted.
```


$ minishift start --show-libmachine-logs --v=5

This is a long log, please see it [here]


$ minishift openshift version

```
Error getting the OpenShift cluster version: ssh command error:
command : docker exec   origin openshift version
err     : exit status 1
output  : Error response from daemon: No such container: origin
```


$ eval $(minishift oc-env)
$ oc whoami --show-server
```
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
```

[here]: https://gist.github.com/vonpupp/2db7d24a7f433e63465d4637bec53cea

**Comment by praveenkumar** [comment]
Going through the logs which you shared.

```
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.42.1:53: server misbehaving ..
```

Your minishift start command actually failed because of the DNS issue. Can you try following and see if that works?

```
$ minishift delete -f
$ minishift start --network-nameserver 8.8.8.8 --show-libmachine-logs --v=5
---- Wait till this complete ----
$ echo $? => this should be 0 to make sure minishift start actually passed.
$ minishift openshift version
$ eval $(minishift oc-env)
$ oc whoami --show-server

```

**Comment by vonpupp** [comment]
Hello Praveen,

Thank you very much for your help. A couple of days ago the `minishift` aur package got updated, so I decided to start fresh. Herewith a summary of everything I did for the sake of others that might have issues also in the future:

  1. `sudo pacman -S libvirt qemu dnsmasq ebtables`
  1. `pacaur -S docker-machine-kvm`
  1. Manually changed `#group = "root"` with `group = "kvm"`
  1. `sudo usermod -a -G kvm,libvirt $(whoami)`
  1. `newgrp libvirt`
  1. `sudo virsh net-start default`
  1. `sudo virsh net-autostart default`
  1. `pacaur -S minishift`
  1. (optional) to make sure verything was fresh, I removed the `.minishift` folder

This will install minishift. Start minishift with
  1. `minishift start --network-nameserver 8.8.8.8 --show-libmachine-logs --v=5`

This will take some time, herewith the [startup log].

Verify that everything went ok
  1. `echo $status` (I am using fish, `echo $0` otherwise)
```
0
```

Check the version:
  1. `minishift openshift version`
```
openshift v3.11.0+1c3e643-87
```

Check the url:
  1. `eval (minishift oc-env)` (I am using fish, `eval $(minishift oc-env)` otherwise)
  1. `oc whoami --show-server`
```
https://192.168.42.251:8443
```

So far, everything looks great. My only current issue is when I try to access that url, I get prompted to accept a self signed certificate and when I do, I get forwarded to `https://127.0.0.1:8443/console/`, but then nothing happens. I can confirm that the port is opened with a stablished connection on port 8443.

[startup log]: https://gist.github.com/vonpupp/42ed5891550ddfdcb05584aead9b5d67

**Comment by gbraad** [comment]
It seems the packaged version is using an older version of our
software; we had to fix this by forcing you to open

  https://192.168.42.251:8443/console

instead as the bare URL will always redirect to localhost. Can you
check the version?

**Comment by vonpupp** [comment]
It works, thank you very much to you both. I am closing the issue.
