### ISSUE TITLE
Check for VirtualBox version fails with version 6 while xhyve is installed on macOS

### ISSUE THREAD

**Issue by maff** [minishift/minishift#3128]
Seems as if the version check for VirtualBox 4+ can't handle a version greater than 5.

### General information

  * Minishift version: 1.28.0
  * OS: macOS Mojave 10.14.2
  * Hypervisor: xhyve, but VirtualBox 6 is also installed

### Steps to reproduce

  1. Install Minishift with xhyve on macOS while having VirtualBox 6 installed
  2. Start Minishift. It will use the xhyve hypervisor as expected, but the version check for VirtualBox 4+ fails with version 6

### Actual

```
$ minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.11.0'
 53.27 MiB / 53.27 MiB [====================================================================================] 100.00% 0s-- Downloading OpenShift v3.11.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.13.0/minishift-centos7.iso'
 346.00 MiB / 346.00 MiB [==================================================================================] 100.00% 0s
-- Starting Minishift VM ..... FAIL E0118 11:10:54.678307   19721 start.go:493] Error starting the VM: Error creating the VM. Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.2r128162\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads". Retrying.
Error starting the VM: Error creating the VM. Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.2r128162\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads"
```

**Comment by maff** [comment]
The error comes from xhyve - see https://github.com/machine-drivers/docker-machine-driver-xhyve/issues/213.

**Comment by LucianoAdonis** [comment]
For anyone else that is having this issue with Virtual Box, install Hyperkit and run `minishift start --vm-driver hyperkit`

**Comment by JayBeale** [comment]
> For anyone else that is having this issue with Virtual Box, install Hyperkit and run `minishift start --vm-driver hyperkit`

I want to mention that this works. I very much hope that the default installation instructions for minishift on OSX work at some point.  I wonder if @maff would be willing to help get this workaround into the installation instructions for minishift on OSX that are at https://docs.okd.io/latest/minishift/getting-started/preparing-to-install.html?
