### ISSUE TITLE
Minishift will not start on OSX - unable to find file /boot/bzimage

### ISSUE THREAD

**Issue by jskii** [minishift/minishift#3130]
### General information

  * Minishift version: minishift v1.28.0+48e89ed
  * OS: Linux / **macOS** / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox / **hyperkit**

### Steps to reproduce

  1. Install prerequisites through homebrew - `cask/minishift` and `docker-machine-driver-hyperkit`.
  2. `minishift start`
  3. `rm -rf ~/.minishift/machines` and attempt `minishift start` again. No change.

### Expected

Minishift boots.

### Actual

Minishift does not boot.

### Logs

https://gist.github.com/jskii/fc61fd2b9330b100c6441fc16aa41a0e

**Comment by gbraad** [comment]
Can you remove the ISO that is cached on ~/.minishift/cache/iso/ and
redownload? I guess the file did not download completely

On Fri, Jan 18, 2019 at 10:47 PM Daniel Black <notifications@github.com> wrote:
>
> General information
>
> Minishift version: minishift v1.28.0+48e89ed
> OS: Linux / macOS / Windows
> Hypervisor: KVM / xhyve / Hyper-V / VirtualBox / hyperkit
>
> Steps to reproduce
>
> Install prerequisites through homebrew - cask/minishift and docker-machine-driver-hyperkit.
> minishift start
> rm -rf ~/.minishift and attempt minishift start again. No change.
>
> Expected
>
> Minishift boots.
>
> Actual
>
> Minishift does not boot.
>
> Logs
>
> https://gist.github.com/jskii/fc61fd2b9330b100c6441fc16aa41a0e
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by praveenkumar** [comment]
@jskii Thanks for bug report, we will check it from our end meanwhile can you try with `xhyve` driver which is also supported. 

- https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#setting-up-xhyve-driver

**Comment by praveenkumar** [comment]
@jskii I tried in my mac and didn't see this issue, it might be you are using an older version of `hyperkit` driver?

```console
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54

$ ./minishift version
minishift v1.30.0+xxxxx

$ hyperkit -v
hyperkit: v0.20180403-17-g3e954c

Homepage: https://github.com/docker/hyperkit
License: BSD

$ ./minishift start --vm-driver hyperkit
-- Starting profile 'bar'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperkit' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperkit' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.14.0/minishift-centos7.iso'
 355.00 MiB / 355.00 MiB [=======================================================================================================] 100.00% 0s
-- Starting Minishift VM ................... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... OK
[...]
```

**Comment by jskii** [comment]
Hey @praveenkumar, here's the output of those commands.

```
~
❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54

~
❯ minishift version
minishift v1.28.0+48e89ed

~
❯ hyperkit -v
hyperkit: v0.20180403-17-g3e954c

Homepage: https://github.com/docker/hyperkit
License: BSD

~
❯ minishift start --logtostderr --v=3 --vm-driver hyperkit
-- minishift version: v1.28.0+48e89ed
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperkit' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperkit' hypervisor ...
-- Starting Minishift VM ....I0119 15:08:14.996342   10775 cluster.go:78] Machine exists!
I0119 15:08:15.039206   10775 cluster.go:86] Machine state:  Stopped
 FAIL E0119 15:08:15.408477   10775 start.go:493] Error starting the VM: Error starting stopped host: starting with cmd line: : Kernel /Users/xx/.minishift/machines/minishift/bzimage does not exist. Retrying.
Error starting the VM: Error starting stopped host: starting with cmd line: : Kernel /Users/xx/.minishift/machines/minishift/bzimage does not exist
```

**Comment by jskii** [comment]
Small note: I noticed your minishift was a newer version (which interestingly wasn't caught by an update to the latest homebrew cask version), so I ran `minishift update` per documentation. Same results on the latest version:

~ 6s
❯ minishift update
Do you want to update from 1.28.0 to 1.30.0 now? [y/N]: y
Downloading https://github.com/minishift/minishift/releases/download/v1.30.0/minishift-1.30.0-darwin-amd64.tgz
 9.15 MiB / 9.15 MiB [==============================================] 100.00% 0s
 65 B / 65 B [======================================================] 100.00% 0s

Updated successfully to Minishift version 1.30.0.

Current Installed add-ons are locally present at: /Users/h243048/.minishift/addons
The add-ons for 1.30.0 available at: https://github.com/minishift/minishift/tree/v1.30.0/addons

Do you want to update the default add-ons? [y/N]: y
Default add-ons will be updated the next time you run any 'minishift' command.

```
~
❯ minishift start --logtostderr --v=3 --vm-driver hyperkit
Minishift was upgraded from v1.28.0 to v1.30.0. Running post update actions.
--- Updating default add-ons ... OK
Default add-ons 'anyuid, admin-user, xpaas, registry-route, che, htpasswd-identity-provider, admissions-webhook, redhat-registry-login' installed
-- minishift version: v1.30.0+186b034
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperkit' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperkit' hypervisor ...

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.14.0/minishift-centos7.iso'
 355.00 MiB / 355.00 MiB [==========================================] 100.00% 0s
-- Starting Minishift VM ....I0119 15:11:35.810221   13986 cluster.go:78] Machine exists!
I0119 15:11:35.846391   13986 cluster.go:86] Machine state:  Stopped
 FAIL E0119 15:11:36.093082   13986 start.go:494] Error starting the VM: Error starting stopped host: starting with cmd line: : Kernel /Users/xx/.minishift/machines/minishift/bzimage does not exist. Retrying.
Error starting the VM: Error starting stopped host: starting with cmd line: : Kernel /Users/xx/.minishift/machines/minishift/bzimage does not exist
```

**Comment by gbraad** [comment]
Can you try to install a newer version of the hyperkit driver?
Also, as mentioned, try the xhyve driver...

**Comment by jskii** [comment]
@gbraad it does startup fine on the xhyve driver, so that's a temporary workaround. Thanks for the suggestion.

According to their Github release page, I'm already on the latest version of the hyperkit driver: https://github.com/moby/hyperkit/releases

**Comment by praveenkumar** [comment]
@jskii Thanks for all the details, now the only thing I can think of is `docker-machine-driver-hyperkit` can you try following and see if that resolve your issue? 

```console
$ which docker-machine-driver-hyperkit
/usr/local/bin/docker-machine-driver-hyperkit

$ rm -fr <Path_of_docker-machine-driver-hyperkit>
$ sudo curl -L  https://github.com/machine-drivers/docker-machine-driver-hyperkit/releases/download/v1.0.0/docker-machine-driver-hyperkit -o /usr/local/bin/docker-machine-driver-hyperkit
$ sudo chown root:wheel /usr/local/bin/docker-machine-driver-hyperkit
$ sudo chmod u+s,+x /usr/local/bin/docker-machine-driver-hyperkit
$ minishift start --vm-driver hyperkit
```

**Comment by jskii** [comment]
@praveenkumar I've tried that and it did resolve the issue. It's a curiosity as that's one of the first things I tried last week, but I appreciate your help and am glad it's working now. Closing.

**Comment by devops-abhi** [comment]
> @jskii Thanks for all the details, now the only thing I can think of is `docker-machine-driver-hyperkit` can you try following and see if that resolve your issue?
> 
> ```
> $ which docker-machine-driver-hyperkit
> /usr/local/bin/docker-machine-driver-hyperkit
> 
> $ rm -fr <Path_of_docker-machine-driver-hyperkit>
> $ sudo curl -L  https://github.com/machine-drivers/docker-machine-driver-hyperkit/releases/download/v1.0.0/docker-machine-driver-hyperkit -o /usr/local/bin/docker-machine-driver-hyperkit
> $ sudo chown root:wheel /usr/local/bin/docker-machine-driver-hyperkit
> $ sudo chmod u+s,+x /usr/local/bin/docker-machine-driver-hyperkit
> $ minishift start --vm-driver hyperkit
> ```

Thank you so much for your help
