### ISSUE TITLE
Minishift doesn't start: " Too many retries waiting for SSH to be available"

### ISSUE THREAD

**Issue by 11ert** [minishift/minishift#3132]
### General information
Receive following error message after starting minishift:

-- Starting Minishift VM .......................................................................................................................... FAIL E0118 21:34:22.036863    5904 start.go:494] Error starting the VM: Error configuring authorization on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
Error starting the VM: Error configuring authorization on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

  * Minishift version: minishift v1.30.0+186b034
  * OS: Windows 10
  * Hypervisor: Hyper-V 

### Steps to reproduce

  1. minishift start

### Expected
Minishift starts without any issues

### Actual
Error starting the VM: Error configuring authorization on host: Too many retries waiting for SSH to be available.

### Logs

Log attached written with `minishift start --show-libmachine-logs -v5` 

[log.txt](https://github.com/minishift/minishift/files/2774482/log.txt)

**Comment by lhein** [comment]
I've got the same error on Arch Linux but with a bit different log output. (see attached log file)


[minishift.log](https://github.com/minishift/minishift/files/2781706/minishift.log)

**Comment by 11ert** [comment]
> 
> 
> It seems you are using the Windows provided SSH client... and exits with an error. Can you try to use an alternatove client or try to provide more information why it fails?

Yes, I use the Windows 10 internal ssh client:
%SYSTEMROOT%\System32\OpenSSH\
Well, I just updated to a newer version of minishift - not changing any settings in regards of ssh or anything else. Beforehand, it was working. Unfortunately, I do not remember which version of minishift I used beforehand.
Could you suggest any other ssh client ? Which more information shall I provide ?

**Comment by 11ert** [comment]
Tried git as ssh client:
```
C:\WINDOWS\system32>where git
J:\Program Files\Git\cmd\git.exe
```
Does not work either. This is the output with log switched on:
```
C:\WINDOWS\system32>minishift start --show-libmachine-logs -v5 > logs.txt
Found binary path at J:\dev\minishift\minishift.exe
Launching plugin server for driver hyperv
Plugin server listening at address 127.0.0.1:61233
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
(minishift) DBG | [stdout =====>] : Off
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
Found binary path at J:\dev\minishift\minishift.exe
Launching plugin server for driver hyperv
Plugin server listening at address 127.0.0.1:61237
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
(minishift) DBG | [stdout =====>] : Off
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) Calling .Start
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Start-VM minishift
(minishift) DBG | [stdout =====>] :
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
(minishift) DBG | [stdout =====>] :
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
```
(The last entries remain the same again and again - I just cut the log output)

**Comment by gbraad** [comment]
this is a different message, as in the previous log your VM got an IP address, however this message you show is what happens when it waits to get an IP address.

I am not sure how you are expecting the `git` command to be used for `ssh` functionality. We are looking for an executable on `%PATH%` matching `ssh`. Use either cygwin's version of openssh-win32 as from chocolatey.

**Comment by 11ert** [comment]
I switched to the OpenSSH rom chocolatey, but it seems to be that the VM does not get an IP:

```
C:\WINDOWS\system32>minishift start --show-libmachine-logs -v5
-- minishift version: v1.30.0+186b034
-- Starting profile 'minishift'
Found binary path at J:\dev\minishift\minishift.exe
Launching plugin server for driver hyperv
Plugin server listening at address 127.0.0.1:59927
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
(minishift) DBG | [stdout =====>] : Off
(minishift) DBG |
-- Check if deprecated options are used ... (minishift) DBG | [stderr =====>] :
OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... OK
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ...
   'External_VM_Switch' ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperv' hypervisor ...
-- Starting Minishift VM ....Found binary path at J:\dev\minishift\minishift.exe
Launching plugin server for driver hyperv
Plugin server listening at address 127.0.0.1:59931
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
(minishift) DBG | [stdout =====>] : Off
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) Calling .Start
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Start-VM minishift
.(minishift) DBG | [stdout =====>] :
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
(minishift) Waiting for host to start...
(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
.(minishift) DBG | [stdout =====>] :
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
.(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
(minishift) DBG | [stdout =====>] :
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
.(minishift) DBG | [stdout =====>] : Running
....
.(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
..
```

**Comment by p0hamala** [comment]
I'll experience this problem as well. I've fresh install of Win10, Virtualbox 6.0.4 and minishift.
ssh is the following - OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4

The error log in question is the following:
.(minishift) DBG | Getting to WaitForSSH function...
(minishift) DBG | Using SSH client type: external
(minishift) DBG | &{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@127.0.0.1 -o IdentitiesOnly=yes -i c:\minishift\machines\minishift\id_rsa -p 63975] C:\WINDOWS\System32\OpenSSH\ssh.exe <nil>}
(minishift) DBG | About to run SSH command:
(minishift) DBG | exit 0
(minishift) DBG | SSH cmd err, output: exit status 255:
(minishift) DBG | Error getting ssh command 'exit 0' : ssh command error:
(minishift) DBG | command : exit 0
(minishift) DBG | err     : exit status 255
(minishift) DBG | output  :
The above repeats itself until start is aborted.

Then when using exactly the same ssh command manually from above, on powershell promt (excluding log suppression):
 ssh -F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@127.0.0.1 -o IdentitiesOnly=yes -i c:\minishift\machines\minishift\id_rsa -p 63975
Warning: Permanently added '[127.0.0.1]:63975' (ECDSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'c:\\minishift\\machines\\minishift\\id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "c:\\minishift\\machines\\minishift\\id_rsa": bad permissions
docker@127.0.0.1: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password). 

So, it seems to me that the default security settings in Win10 are prohibiting the ssh connection. id_rsa is generated by minishift during initial start command. The user used to run minishift is normal (not privileged) user.

**Comment by andregs** [comment]
The problem comes from: https://github.com/openssh/openssh-portable/blob/b5e412a8993ad17b9e1141c78408df15d3d987e1/authfile.c#L156

In the comments, we see that
```
	 * if a key owned by the user is accessed, then we check the
	 * permissions of the file. if the key owned by a different user,
	 * then we don't care.
```

So we can either change the file owner or restrict its permissions. I choose option B:

![image](https://user-images.githubusercontent.com/712092/53286023-f63de280-3746-11e9-96c3-3548007e68d2.png)

And now I can start minishift:

```
PS C:\Users\andre> minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Running (openshift v3.11.0+d0c29df-98)
DiskUsage:  15% of 19G (Mounted On: /mnt/sda1)
CacheUsage: 491.9 MB (used by oc binary, ISO or cached images)
PS C:\Users\andre> minishift oc-env
$Env:PATH = "C:\Apps\minishift-1.31.0-windows-amd64\cache\oc\v3.11.0\windows;$Env:PATH"
# Run this command to configure your shell:
# & minishift oc-env | Invoke-Expression
PS C:\Users\andre>
```

**Comment by 11ert** [comment]
@andregs I tried the same. Unfortunately, in my case it does not help.

when executing `minishift start --show-libmachine-logs -v5` 
output is now:

...
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
(minishift) DBG | [stdout =====>] : 192.168.1.10
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@192.168.1.10 -o IdentitiesOnly=yes -i C:\Users\User\.minishift\machines\minishift\id_rsa -p 22] C:\Program Files\OpenSSH-Win64\ssh.exe <nil>}
About to run SSH command:
exit 0
.....SSH cmd err, output: exit status 255:
Error getting ssh command 'exit 0' : ssh command error:
command : exit 0
err     : exit status 255
output  :
Getting to WaitForSSH function...
(minishift) Calling .GetSSHHostname
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
(minishift) DBG | [stdout =====>] : 192.168.1.10
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@192.168.1.10 -o IdentitiesOnly=yes -i C:\Users\User\.minishift\machines\minishift\id_rsa -p 22] C:\Program Files\OpenSSH-Win64\ssh.exe <nil>}
About to run SSH command:
exit 0
...

**Comment by 11ert** [comment]
Following this order, it finally worked:

`minishift delete --force --clear-cache`
delete .minishift folder

`minishift start`

check permissions of **private key** as described by @andregs 
e.g. C:\Users\<username>\.minishift\machines\minishift\id_rsa
Remove all principals besides the one you start minishift with. Only set the permissions "Read & Execute"

Finally, it works! 

I still receive another error after minishift has started....:
`Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to the kube config 'C:\Users\Thorsten\.minishift\machines\minishift_kubeconfig' does not exist`
... but I cannot see any limitations in usage of the cluster:

`minishift status`

 Minishift:  Running 
 Profile:    minishift
 OpenShift:  Running (openshift v3.11.0+d0c29df-98)
 DiskUsage:  14% of 19G (Mounted On: /mnt/sda1)
 CacheUsage: 491.9 MB (used by oc binary, ISO or cached images)

**Comment by stamatisl** [comment]
I have done some reverse engineering to OpenSSH v7.9.0.0p1-Beta executable because I'm running into windows domain and I can't change the permissions of the id_rsa file.

You can use "Tiny Hexer" and open ssh.exe. Find string: **74** 63 48 8D 0D F5 2E 08 (line: **0x038790**) and change it to: **EB** 63 48 8D 0D F5 2E 08 

Save your changes and ...you are done!

[ssh.zip](https://github.com/minishift/minishift/files/3068111/ssh.zip)

**Comment by eduardocerqueira** [comment]
It worked for me!
```
sudo ./minishift delete --force --clear-cache
sudo ./minishift start
```
as described at https://github.com/minishift/minishift/issues/3132#issuecomment-469796775
thanks @11ert

**Comment by Avielyo10** [comment]
This worked for me:
```bash
sudo dnf -y remove openssh-server
sudo dnf -y install openssh-server
```

**Comment by stheralves** [comment]
> This worked for me (Fedora 31):
> 
> ```shell
> minishift stop
> sudo service libvirtd restart
> minishift start
> ```

it worked for me too in Fedora 31
