### ISSUE TITLE
Unable to create new app behind corporate proxy

### ISSUE THREAD

**Issue by shockogit** [minishift/minishift#3134]
When running the following command to create a test app after setup I get the following:
```
oc new-app https://github.com/sclorg/nodejs-ex -l name=myapp
warning: Cannot find git. Ensure that it is installed and in your path. Git is required to work with git repositories.
error: unable to load template file "https://github.com/sclorg/nodejs-ex": Get https://github.com/sclorg/nodejs-ex: dial tcp 140.
2.118.3:443: i/o timeout
error: git ls-remote failed with: git binary not available; local file access failed with: CreateFile https://github.com/sclorg/
odejs-ex: The filename, directory name, or volume label syntax is incorrect.
error: unable to locate any images in image streams, templates loaded in accessible projects, template files, local docker images
with name "https://github.com/sclorg/nodejs-ex"
```

*Version*
minishift v1.29.0+72fa7b2

*Steps To Reproduce*
Windows 10 Machine behind corporate proxy (with or without proxy auth)
Deploy minishift to Oracle Virtual box with the following:
```
.\minishift.exe start --http-proxy=http://10.112.64.203:8080 --https-proxy=http://10.112.64.203:8080 --docker-env HTTPS_PROXY=http://10.112.64.203:8080 --docker-env HTTP_PROXY=http://10.112.64.203:8080
```

The try and deploy an app with:
```
oc new-app https://github.com/sclorg/nodejs-ex -l name=myapp
```

*Current Result*
```
**error: unable to load template file "https://github.com/sclorg/nodejs-ex": Get https://github.com/sclorg/nodejs-ex: dial tcp 140.
```

*Expected Result*
Successful pull of app image from repository

**Comment by anjannath** [comment]
@shockogit Continue discussion on #3125

**Comment by shockogit** [comment]
> @shockogit Continue discussion on #3125

I'm not sure this is the same issue though is it? In my case the app does not build as it tries to pull it directly and does not use my corporate proxy. #3125 seems to show the app building but not having the proxy in the container environment which is a different issue,. I cannot build any app using oc new-app as my windows machine on which i'm using oc.exe uses a proxy and the pull initiated with oc.exe ignores it.

**Comment by LalatenduMohanty** [comment]
This issue looks different than #3125 because of following error 
```
oc new-app https://github.com/sclorg/nodejs-ex -l name=myapp
warning: Cannot find git. Ensure that it is installed and in your path. Git is required to work with git repositories.
error: unable to load template file "https://github.com/sclorg/nodejs-ex": Get https://github.com/sclorg/nodejs-ex: dial tcp 140.
```
Specially `Cannot find git. Ensure that it is installed and in your path. ` looks really odd. @shockogit are you able to reproduce this everytime ?

**Comment by shockogit** [comment]
OK, so according to [this ](https://docs.okd.io/latest/cli_reference/get_started_cli.html )I need GIT installed on my windows client also. I was not aware of that. I have it installed now. So if git for windows in use and being called by oc.exe I assume it will need a proxy defined also so that's defined:

**_c:\minishift>git config --global --get http.proxy
http://10.201.2.134:3128_**

I can now successfully clone a public repo from git CLI or clone this repo I'm trying to use:

**_c:\minishift>git clone https://gitlab.com/gitlab-org/gitlab-ce.git
Cloning into 'gitlab-ce'...
remote: Enumerating objects: 1365452, done.
remote: Counting objects:  77% (1051399/1365452)
c:\minishift>git clone https://github.com/sclorg/nodejs-ex
Cloning into 'nodejs-ex'...
remote: Enumerating objects: 631, done.
remote: Total 631 (delta 0), reused 0 (delta 0), pack-reused 631R
Receiving objects: 100% (631/631), 233.73 KiB | 1.56 MiB/s, done._**

Now returning to oc.exe this time I got this message:

**_c:\minishift>oc new-app https://github.com/sclorg/nodejs-ex -l name=myapp
warning: Cannot check if git requires authentication.
W0308 17:16:09.906477   36764 dockerimagelookup.go:233] Docker registry lookup failed: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exc
eeded while awaiting headers)
error: only a partial match was found for "nodejs": "openshift/nodejs"

The argument "nodejs" only partially matched the following Docker image, OpenShift image stream, or template:

Image stream "nodejs" in project "openshift"
  Use --image-stream="openshift/nodejs" --allow-missing-imagestream-tags to specify this image or template_**

More problems. So I run a windows ETW trace and see this is whats being called:

**_git-remote-https https://github.com/sclorg/nodejs-ex - https://github.com/sclorg/nodejs-ex_**

This exe (C:\Program Files\Git\mingw64\libexec\git-core\git-remote-https.exe) is actually in the core of git and seems to ignore the proxy defined in my .gitconfig file :(

**Comment by shockogit** [comment]
Hi guys, can anyone comment on my latest findings? This is a blocker to us using minishift in our organisation.

**Comment by gbraad** [comment]
OpenShift would not know about proxy settings you have defined for
your client computer.
You would have to set proxy settings specifically for the application,
based on the server environment it will run in.

If you are using s2i, you would need to set it on the project itself:
https://docs.openshift.com/container-platform/3.5/install_config/http_proxies.html

On Thu, Mar 21, 2019 at 6:48 AM shockogit <notifications@github.com> wrote:
>
> Hi guys, can anyone comment on my latest findings? This is a blocker to us using minishift in our organisation.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by shockogit** [comment]
Thanks gbraad. So I just want to confirm my understanding (limited albeit!) here. Why when I run the oc new-app and point to a GIT repo does it use/need GIt for windows?

**Comment by shockogit** [comment]
Can anyone comment on the GIT piece?

**Comment by shockogit** [comment]
boo

**Comment by 62mkv** [comment]
HI @gbraad I am having the exact same issue when just following the Minishift Quick Start giude:

```
>oc new-app https://github.com/sclorg/nodejs-ex -l name=myapp --image-stream="openshift/nodejs" --allow-missing-imagestream-tags
warning: Cannot check if git requires authentication.
--> Found tag :latest in image stream "openshift/nodejs" for "openshift/nodejs"

    * The source repository appears to match: nodejs
    * A source build using source code from https://github.com/sclorg/nodejs-ex will be created
      * The resulting image will be pushed to image stream tag "nodejs-ex:latest"
      * Use 'start-build' to trigger a new build
      * WARNING: this source repository may require credentials.
                 Create a secret with your git credentials and use 'set build-secret' to assign it to the build config.
    * This image will be deployed in deployment config "nodejs-ex"

--> Creating resources with label name=myapp ...
    error: imagestreamtags.image.openshift.io is forbidden: User "developer" cannot create imagestreamtags.image.openshift.io in the namespace "openshift": no RBAC policy matched
    error: imagestreamtag.image.openshift.io "nodejs-ex:latest" already exists
    error: buildconfigs.build.openshift.io "nodejs-ex" already exists
    error: deploymentconfigs.apps.openshift.io "nodejs-ex" already exists
--> Failed
```

I *do* have NO_PROXY, HTTP_PROXY, HTTPS_PROXY configured properly (at least most of the other stuff seems to be fine with those) on my host machine (Win10) 

I am using VirtualBox provider. As this is just a regular flow which is described in the Quick Start, I think this should be at least considered as an issue, or shouldn't it ? 

Thanks for any suggestions
