### ISSUE TITLE
Test Minishift with VirtualBox 6

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#3135]
### General information

On 18 Dec 2018 new major version of VirtualBox got released. We should test Minishift with it.

**Comment by gbraad** [comment]
We have briefly tested VirtualBox 6 and compared to 5, and have not found any issues or even compelling reasons to recommend this new version as the default. I do agree we need systematic tests for this release, but I do not think this will change the situation for CDK (as most corporate users might remain for a slightly longer period on 5.x)

**Comment by agajdosi** [comment]
@gbraad I can confirm VirtualBox 6 works just fine with minishift. I've run full integration test suite yesterday with VB6 and it passed fine.

Maybe we should just mention in docs that also VB6 can be also used. Pinging @robin-owen.

**Comment by gbraad** [comment]
@agajdosi not sure if we really need to change recommendation, but good to know.

**Comment by robin-owen** [comment]
@agajdosi @gbraad I don't think we need to change the recommendation we currently have. As a user, I'd be surprised if a newer version of VirtualBox did *not* work -- if that was the case, I'd recommend adding docs around it.

If it works as expected, I think we're okay on the docs side already. :)

**Comment by agajdosi** [comment]
@robin-owen Thank you for confirmation. I am then closing this as VB6 was tested and confirmed to be OK and thus we do not have any more agenda connected to VB6.
