### ISSUE TITLE
Homebrew has old version

### ISSUE THREAD

**Issue by kadel** [minishift/minishift#3142]
### General information

  * OS: macOS

Homebrew has a version that is now two versions old :-(

```
▶ brew cask install minishift
==> Satisfying dependencies
==> Downloading https://github.com/minishift/minishift/releases/download/v1.28.0/minishift-1.28.0-darwin-amd64.tgz
Already downloaded: /Users/tkral/Library/Caches/Homebrew/downloads/65030dfea2bb1f45aebf1ffa53747c86b5caff05fe5010f581e0bdf4c6ff9058--minishift-1.28.0-darwin-amd64.tgz
==> Verifying SHA-256 checksum for Cask 'minishift'.
==> Installing Cask minishift
==> Linking Binary 'minishift' to '/usr/local/bin/minishift'.
🍺  minishift was successfully installed!

minishift version
minishift v1.28.0+48e89ed
```

**Comment by gbraad** [comment]
We do not maintain the Homebrew version. They have an automated process (or manual perhaps?) for this... if this did not work, file an issue against their repo.

**Comment by kadel** [comment]
Official installation guide for minishift is using homebrew. Updating the homebrew package should be part of minishift release process. Is there any reason why you don't do that?
It looks bad when docs refer to the installation process that is outdated.

**Comment by praveenkumar** [comment]
It is already updated to `1.30.0` => https://github.com/Homebrew/homebrew-cask/blob/master/Casks/minishift.rb
