### ISSUE TITLE
Persistent Volumes cannot be recycled after deleting PersistentVolumeClaims

### ISSUE THREAD

**Issue by miguelsorianod** [minishift/minishift#3144]
### General information

  * Minishift version: minishift v1.27.0+707887e
  * OS: Linux (Fedora 29)
  * Hypervisor: VirtualBox 5.2.26
  * OpenShift and Kubernetes version:
```
localhost:~$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.99.100:8443
kubernetes v1.11.0+d4cacc0
```

### Steps to reproduce

1 - Create a PersistentVolumeClaim as part of an application deployment. After performing the deploy with 'oc new-app ...' the VolumeClaims and their associated volumes are:
```
$ oc get pvc
NAME                    STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
backend-redis-storage   Bound     pv0086    100Gi      RWO,ROX,RWX                   40s
mysql-storage           Bound     pv0006    100Gi      RWO,ROX,RWX                   37s
system-redis-storage    Bound     pv0013    100Gi      RWO,ROX,RWX                   39s
system-storage          Bound     pv0035    100Gi      RWO,ROX,RWX                   36s
```

2 - Delete the Persistent Volume Claims. I've done this deleting a project that contains them.
3 - Checking that all the PVs associated with the previous PVCs are in status failed. For example:
```
localhost:~$ oc get pv pv0086
NAME      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                 STORAGECLASS   REASON    AGE
pv0086    100Gi      RWO,ROX,RWX    Recycle          Failed    operator-test/backend-redis-storage                            7d
```
By describing the PV I observe the following error:

```
msoriano@localhost:~$ oc describe pv pv0086
Name:            pv0086
Labels:          volume=pv0086
Annotations:     pv.kubernetes.io/bound-by-controller=yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    
Status:          Failed
Claim:           operator-test/backend-redis-storage
Reclaim Policy:  Recycle
Access Modes:    RWO,ROX,RWX
Capacity:        100Gi
Node Affinity:   <none>
Message:         Recycle failed: unexpected error creating recycler pod:  pods "recycler-for-pv0086" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/minishift/base/openshift.local.pv/pv0086
    HostPathType:  
Events:
  Type     Reason               Age   From                         Message
  ----     ------               ----  ----                         -------
  Warning  VolumeFailedRecycle  12m   persistentvolume-controller  Recycle failed: unexpected error creating recycler pod:  pods "recycler-for-pv0086" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
```

### Expected

The persistent volume used by the Persistent Volume Claim should be available again.

### Actual

The persistent volume is marked in status "Failed" after deleting the PersistentVolumeClaim.

**Comment by praveenkumar** [comment]
Have a look to https://bugzilla.redhat.com/show_bug.cgi?id=1664262 and also workaround would be `oc adm policy add-scc-to-group hostmount-anyuid system:serviceaccounts` atm as per https://bugzilla.redhat.com/show_bug.cgi?id=1664262#c4

**Comment by miguelsorianod** [comment]
Hi @praveenkumar ,

It seems that after applying the workaround it is working when I repeat the provided steps initially. I still see the previous volumes in failed status but I guess when they are tried to be reused it will recycle them correctly.

Do you want me to report this somewhere else?

Thank you,

Miguel

**Comment by LalatenduMohanty** [comment]
@miguelsorianod I am closing this issue as this is not a minishift issue and you found the workaround. Feel free to put a comment if you disagree.
