### ISSUE TITLE
Add entry for image openjdk18-openshift:1.5 to the redhat-openjdk18-openshift imagestream

### ISSUE THREAD

**Issue by vcottagiri** [minishift/minishift#3145]
### General information

  * Minishift version: minishift v1.30.0+186b034
  * OS: Windows 10
  * Hypervisor: Hyper-V

### Description

The redhat-openjdk18-openshift imagestream in the xpaas addon has entries for openjdk18-openshift versions 1.0 to 1.4. The image for [openjdk18-openshift:1.5](https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift) is available since Oct '18.

Please add an entry for openjdk18-openshift:1.5 in [openjdk18-image-stream.json](https://github.com/minishift/minishift/blob/v1.30.0/addons/xpaas/v3.11/xpaas-streams/openjdk18-image-stream.json) so that the image is available when the xpaas addon is installed/applied.

**Comment by anjannath** [comment]
We need to update the xPaaS addons.

**Comment by anjannath** [comment]
@vcottagiri Hi, We get these imagestreams https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/latest/xpaas-streams/openjdk18-image-stream.json from [openshift/openshift-ansible](https://github.com/openshift/openshift-ansible) repo, It is better if they include it.

**Comment by vcottagiri** [comment]
Ok, sounds good - will raise it with them.
