### ISSUE TITLE
golang should be installed from virt7-container-common-candidate repo in cento ci

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#3147]
While looking at the cenos_ci.sh script, it seems like golang is not installed from the `virt7-container-common-candidate` repo even if it is enabled, but it is always installed from epel.  So the version of go is similar to what is released from fedora side where as we want to get same version as RHEL. 
```
18:18:19 Dependencies Resolved
18:18:19 
18:18:19 ================================================================================
18:18:19  Package                Arch          Version                 Repository   Size
18:18:19 ================================================================================
18:18:19 Installing:
18:18:19  golang                 x86_64        1.11.4-1.el7            epel        631 k
18:18:19 Installing for dependencies:
18:18:19  apr                    x86_64        1.4.8-3.el7_4.1         base        103 k
18:18:19  apr-util               x86_64        1.5.2-6.el7             base         92 k
18:18:19  golang-bin             x86_64        1.11.4-1.el7            epel         90 M
18:18:19  golang-src             noarch        1.11.4-1.el7            epel        6.4 M
18:18:19  mercurial              x86_64        2.6.2-8.el7_4           base        2.6 M
18:18:19  neon                   x86_64        0.30.0-3.el7            base        165 k
18:18:19  pakchois               x86_64        0.4-10.el7              base         14 k
18:18:19  subversion             x86_64        1.7.14-14.el7           base        1.0 M
18:18:19  subversion-libs        x86_64        1.7.14-14.el7           base        922 k
18:18:19 
18:18:19 Transaction Summary
18:18:19 ================================================================================
18:18:19 Install  1 Package (+9 Dependent packages)
```

**Comment by praveenkumar** [comment]
We use `yum install` to install the golang so whatever repo have latest version of it, will be picked. If we are sure that we don't need `epel` repo at all for any other packages then we should remove it from repolist.

**Comment by anjannath** [comment]
we can temporarily disable the epel repo while installing golang

**Comment by gbraad** [comment]
disable epel

**Comment by LalatenduMohanty** [comment]
+1 for disabling the EPEL repo

**Comment by anjannath** [comment]
So, golang was removed from upstream core repositories[1], so it is only available through the `virt7-container-common` and `epel` repos, the version in virt7-container-common` in `go-1.10.2`, which is giving some `gofmt` errors, which if we fix, will throw errors on `go-v.1.11.4`. So, it looks like we have to stick with `epel` for now.

[1] https://www.centos.org/forums/viewtopic.php?t=68990

**Comment by gbraad** [comment]
Travis CI passes, which runs a debian-based image with go 1.11.4...
In EPEL we have which version?

BTW: I think we should start using a custom image for the Travis CI builds (just like with I use for builds on GitLab CI) which is CentOS-based. This means we can find these issues earlier (and easier).

**Comment by anjannath** [comment]
@Gerard EPEL has the same version, go-1.11.4

**Comment by gbraad** [comment]
So I am a little confused now. We actually want the EPEL version, right?

**Comment by anjannath** [comment]
Okay, let me try to clear this up, so initially i thought we are getting
golang from `virt7-container-common-candidate` and it was supposed to be
the same version as what RHEL ships.

So when i found out it was actually downloading from epel, i wanted to
change it back. reasoning behind this was to make it the same version as
downstream ci (which is on go-1.9.4). otherwise we get surprises like the
gofmt errors.

But since, that didn't work out now we just keep it this way (use golang
from epel), and hopefully update the downstream ci machine to go-1.11.4

**Comment by gbraad** [comment]
OK. Note: Fedora currently is on Go 1.11.2

**Comment by anjannath** [comment]
Will create issue in downstream JIRA to install golang from red hat developers channel
