### ISSUE TITLE
unable to start minishift on OSX (xhyve, virtualbox)

### ISSUE THREAD

**Issue by alfredodeza** [minishift/minishift#3153]
### General information

  * Minishift version: minishift v1.30.0+186b034
  * OS: macOS
  * Hypervisor: xhyve / VirtualBox

### Steps to reproduce

  1. brew install docker-machine-driver-xhyve 
     - version 0.3.3 is installed
  2. sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
  3. sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
  4. brew cask install minishift

### Expected
    $ minishift start
    -- Starting local OpenShift cluster using 'xhyve' hypervisor...
    ...
       OpenShift server started.

### Actual
    $ minishift start --show-libmachine-logs -v5
    -- minishift version: v1.30.0+186b034
    -- Starting profile 'minishift'
    ...
    (minishift) DBG | Not there yet 60/60, error: IP not found for MAC  in DHCP leases
    . FAIL E0204 13:59:53.703067   14431 start.go:494] Error starting the VM: Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting. Retrying.
    Error starting the VM: Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting

Full log at https://gist.github.com/alfredodeza/f1ead105ba06e6c7ae24ddf2312849d3

This behavior is found both with virtualbox and xhyve. [This comment](https://github.com/machine-drivers/docker-machine-driver-xhyve/issues/9#issuecomment-320725845) makes me think that because I installed `minikube` before, my system might not be in a good state to accept minishift? I already removed the minikube machine from virtualbox but I still experience the same fatal behavior with minishift

**Comment by gbraad** [comment]
This usually sounds like a networking issue, for instance due to VPN. Are
you running this? The other reason might be a misconfiguration. Minikube is
often tested alongside and does not pose issues for us (we share a lot in
common). If minikube starts , minishift likely will...

**Comment by alfredodeza** [comment]
No VPN connections configured. However, I just did:

    $ minikube delete
    $ minishift delete

And now `minishift start` works. 

Would you prefer for me to debug this further? Since this is working for me now I would be fine if this issue gets closed

**Comment by gbraad** [comment]
Please close
