### ISSUE TITLE
Spike around notification library beeep

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#3165]
This issue is for a spike around the library https://github.com/gen2brain/beeep for implementing notifications in systemtray. There's also another library for dialogs and popups which might be worth looking at https://github.com/gen2brain/dlgs

Ref: #3154

**Comment by gbraad** [comment]
While we can make a toast appear with this library, we need to make sure in
this spike that the an error is shown when an error occurs (and possibly
link to a file that contains the full log).

So perhaps you need to split the work into two parts: 1. make sure we can
have a toast appear on all platforms (when possible), 2. show error in a
concise and detailed format.

**Comment by gbraad** [comment]
https://github.com/gen2brain/beeep/issues/18

**Comment by anjannath** [comment]
So the library will work for us in case of windows, but for that we can directly use the https://github.com/go-toast/toast.

In case of macOS it cannot show an application icon on the notification (unless we make the binary an app bundle) also, upon clicking on the notification it opens up a _File Pick_ windows (finder like) which seems to be the default and cannot be changed.

@gbraad Yes, in macOS it does not support opening a related application, by default it opens that file picker window i mentioned.

**Comment by gbraad** [comment]
I think we can conclude the spike. It feels like this library will not help us much...
