### ISSUE TITLE
Run Against Existing Machine:[RHEL-8][EC2] Error installing package firewalld: Process exited with status 1

### ISSUE THREAD

**Issue by davdunc** [minishift/minishift#3166]
Attempting to install Minishift on EC2 instance and found that firewalld is not available for RHEL-8 Beta. I assume that the firewalld is not included in the Red Hat Update Infrastructure. 

  * Minishift version:  v1.31.0+cfc599c
  * OS: Linux 
  *  KVM (t3.small) 

### Steps to reproduce

  1. Launch t3.small or any other instance type with RHEL-8.0_HVM_BETA-20181113-x86_64-1-Hourly2-GP2 (ami-0ae10902655ba4447 in us-east-2).
  2. Issue remote command:  minishift start --vm-driver generic --remote-ipaddress <ip-address>  --remote-ssh-user ec2-user --remote-ssh-key <your_ssh_key>  -v 5 --show-libmachine-logs *from local laptop*
  
### Expected
Succesful install of minishift

### Actual
Error installing package firewalld and exit. 

### Logs
https://gist.github.com/davdunc/59c93ae273d3665471d76307adf27f6a

**Comment by praveenkumar** [comment]
Hey David, Thanks for the bug report, we didn't test out minishift on the RHEL-8 side and that might not even be supported atm. Right now we use `docker` for provision the openshift cluster but as of now there is no `docker` by default for RHEL-8. We will keep this bug as a spike and see what can be possible from minishift side to support the RHEL-8.

**Comment by davdunc** [comment]
Thanks Praveen I'll focus on earlier versions for now.
