### ISSUE TITLE
Implement host folder mounts using sshfs

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#317]
To have a consistent hypervisor independent solution for host folder mounts, we could implement a vagrant-sshfs equivalent for Minishift. This would come down to:

* [x] Prepare our ISOs with sshfs
* [ ] Use Golang's sftp server functionality to create a sftp daemon process on the host
  * [ ] As with vagrant-sshfs, the tricky part is to be able to properly spawn daemon processes on on all OS types. For Windows in particular it means we will have to make Win32 API calls. 
  * [ ] Expose commands within the CLI to start/stop the sftp server
* [ ] Write the glue code which wires up the sftp server on host with sshfs in the VM

**Comment by praveenkumar** [comment]
+ SELinux context should be set accordingly for mounted folders.

**Comment by gbraad** [comment]
https://github.com/docker/machine/pull/4018

**Comment by gbraad** [comment]
On PR #1528 the question is raised how to solve the non-interactive adding of a hostfolder using in a cross-type manner.

Probably for this, we can not rely on the viper/cobra to read the flags, but need to parse passed options ourselves (as done with the `--profile` option).

The question is how to rescribe the mandatory and optional fields that are passed as options to the HostFolder type. I would suggest to add a little bit of metadata for this in the HostFolders.go file and describe them by `type` specifier.

**Comment by LalatenduMohanty** [comment]
@hferentschik looks like libmachine added some support for SSHFS [1] . Have you checked it out. 

`Added new docker-machine mount command for mounting machine directories over SSHFS`
[1] https://github.com/docker/machine/releases/tag/v0.13.0

**Comment by gbraad** [comment]
This implementation has been discussed before (even with the Minikube guys), but it seems it got finally released in 0.13.0. Good, as #1685 pulls this in as dependency (https://github.com/minishift/minishift/pull/1685/commits/119a9104d5f3d261940fa770d34938b39838f21c) so nothing prevents us from using this implementation, or being compatible with. This has to be decided on short notice.

**Comment by gbraad** [comment]
Please consider the comment: https://github.com/minishift/minishift/issues/1024#issuecomment-351619634 Is the sftp-server binary for OpenSSH-Win32 still considered? Be aware, that the developer mode, or enabling the new #1836 functionality claims ports on the host we might need for the SSHFS functionality.

**Comment by praveenkumar** [comment]
@hferentschik you are still owner for this task :)

**Comment by praveenkumar** [comment]
@gbraad https://github.com/hferentschik/minishift/tree/issue-317 there is the current code.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/2093
