### ISSUE TITLE
Documentation - Basic usage - content update

### ISSUE THREAD

**Issue by tsedmik** [minishift/minishift#3178]
I found some issues with the text in Basic Usage guide - https://docs.okd.io/latest/minishift/using/basic-usage.html

* Not needed bracket
  https://docs.okd.io/latest/minishift/using/basic-usage.html#persistent-configuration
> {The global configuration file is maintained at $MINISHIFT_HOME/config/global.json.
* Misleading information. If I use start flags, they are not set to persistent configuration
> By Default minishift persist start flags to peristent configuration, to disable it, use `minishift config set save-start-flags false`.
* Duplicate information about priorities of runtime options
  https://docs.okd.io/latest/minishift/using/basic-usage.html#unsetting-persistent-configuration-values

**Comment by LalatenduMohanty** [comment]
>     * Misleading information. If I use start flags, they are not set to persistent configuration

@tsedmik The way it works is if you start `minishift` with default flags it will not save it to persistent configuration but if you start it with non-default configuration it will save it e.g. `minishift start --memory 5GB ` will save it
```
$ minishift config view
- memory                             : 5GB

```

**Comment by LalatenduMohanty** [comment]
>     * Duplicate information about priorities of runtime options
>       https://docs.okd.io/latest/minishift/using/basic-usage.html#unsetting-persistent-configuration-values

I could not find where it is mentioned again. Can you please point me?

**Comment by tsedmik** [comment]
@LalatenduMohanty thank you for your check. You are right about flags - I used default value in a flag, therefore I've got no entry in persistent configuration.

Regarding duplicate information about priorities of runtime options. I've double check it and I didn't find the replica.

I'll update the PR accordingly
