### ISSUE TITLE
Centos CI  command on issue comments does not work

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#3183]
`retest this please` is not triggering centos CI pr test job anymore. see #3182

**Comment by gbraad** [comment]
This might be a temporary issue with the CI integration. We have seen this before... if this remains we can reach out to the admins.

**Comment by praveenkumar** [comment]
@anjannath for centos-ci issues we should send mail to ci-users@centos.org and find out if that issue from ci infra side.
