### ISSUE TITLE
Docker Machine process exiting due to closed plugin server (unexpected EOF) & Error copying the oc binary to /var/lib/minishift/bin: connection is shut down

### ISSUE THREAD

**Issue by onderson** [minishift/minishift#3185]
### General information

  * Minishift version: minishift v1.30.0+186b034
  * OS: Linux Ubuntu
  * Hypervisor: KVM 

### Steps to reproduce

  1. minishift start

### Expected
Success

### Actual

-- OpenShift cluster will be configured with ...
   Version: v3.11.0
(minishift) Calling .GetSSHHostname
(minishift) DBG | GetIP called for minishift
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) Calling .GetSSHPort
(minishift) DBG | IP address: 192.168.42.125
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:22:d6:b4
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) DBG | AK: resolvestorepath: /home/onders/.minishift
(minishift) DBG | AK: resolvestorepath: /home/onders/.minishift
(minishift) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /home/onders/.minishift/machines/minishift/id_rsa (-rw-------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@192.168.42.125 -o IdentitiesOnly=yes -i /home/onders/.minishift/machines/minishift/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
docker images -q openshift/origin-control-plane:v3.11.0
SSH cmd err, output: <nil>: 
-- Pulling the OpenShift Container Image (minishift) Calling .GetSSHHostname
.(minishift) DBG | GetIP called for minishift
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) DBG | IP address: 192.168.42.125
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:22:d6:b4
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) DBG | AK: resolvestorepath: /home/onders/.minishift
(minishift) Calling .GetSSHKeyPath
(minishift) DBG | AK: resolvestorepath: /home/onders/.minishift
(minishift) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /home/onders/.minishift/machines/minishift/id_rsa (-rw-------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@192.168.42.125 -o IdentitiesOnly=yes -i /home/onders/.minishift/machines/minishift/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
docker pull openshift/origin-control-plane:v3.11.0
...................................................................................................................

....................................................................................................................................................................................Wrapper Docker Machine process exiting due to closed plugin server (unexpected EOF)
Wrapper Docker Machine process exiting due to closed plugin server (unexpected EOF)
Wrapper Docker Machine process exiting due to closed plugin server (unexpected EOF)
Wrapper Docker Machine process exiting due to closed plugin server (unexpected EOF)
.................SSH cmd err, output: <nil>: Trying to pull repository docker.io/openshift/origin-control-plane ... 
v3.11.0: Pulling from docker.io/openshift/origin-control-plane
a02a4930cb5d: Pulling fs layer
9371245e9e1b: Pulling fs layer
c55969dc4ace: Pulling fs layer
064568f6d56f: Pulling fs layer
348b74f71ecb: Pulling fs layer
064568f6d56f: Waiting
348b74f71ecb: Waiting
c55969dc4ace: Verifying Checksum
c55969dc4ace: Download complete
064568f6d56f: Retrying in 5 seconds
064568f6d56f: Retrying in 4 seconds
064568f6d56f: Retrying in 3 seconds
064568f6d56f: Retrying in 2 seconds
064568f6d56f: Retrying in 1 second
064568f6d56f: Retrying in 10 seconds
064568f6d56f: Retrying in 9 seconds
064568f6d56f: Retrying in 8 seconds
064568f6d56f: Retrying in 7 seconds
064568f6d56f: Retrying in 6 seconds
064568f6d56f: Retrying in 5 seconds
064568f6d56f: Retrying in 4 seconds
064568f6d56f: Retrying in 3 seconds
064568f6d56f: Retrying in 2 seconds
064568f6d56f: Retrying in 1 second
9371245e9e1b: Retrying in 5 seconds
9371245e9e1b: Retrying in 4 seconds
9371245e9e1b: Retrying in 3 seconds
9371245e9e1b: Retrying in 2 seconds
9371245e9e1b: Retrying in 1 second
9371245e9e1b: Verifying Checksum
9371245e9e1b: Download complete
a02a4930cb5d: Retrying in 5 seconds
a02a4930cb5d: Retrying in 4 seconds
a02a4930cb5d: Retrying in 3 seconds
a02a4930cb5d: Retrying in 2 seconds
a02a4930cb5d: Retrying in 1 second
348b74f71ecb: Retrying in 5 seconds
348b74f71ecb: Retrying in 4 seconds
348b74f71ecb: Retrying in 3 seconds
348b74f71ecb: Retrying in 2 seconds
348b74f71ecb: Retrying in 1 second
064568f6d56f: Retrying in 15 seconds
064568f6d56f: Retrying in 14 seconds
064568f6d56f: Retrying in 13 seconds
064568f6d56f: Retrying in 12 seconds
064568f6d56f: Retrying in 11 seconds
064568f6d56f: Retrying in 10 seconds
064568f6d56f: Retrying in 9 seconds
064568f6d56f: Retrying in 8 seconds
064568f6d56f: Retrying in 7 seconds
064568f6d56f: Retrying in 6 seconds
064568f6d56f: Retrying in 5 seconds
064568f6d56f: Retrying in 4 seconds
064568f6d56f: Retrying in 3 seconds
064568f6d56f: Retrying in 2 seconds
064568f6d56f: Retrying in 1 second
a02a4930cb5d: Retrying in 10 seconds
a02a4930cb5d: Retrying in 9 seconds
a02a4930cb5d: Retrying in 8 seconds
a02a4930cb5d: Retrying in 7 seconds
a02a4930cb5d: Retrying in 6 seconds
a02a4930cb5d: Retrying in 5 seconds
a02a4930cb5d: Retrying in 4 seconds
a02a4930cb5d: Retrying in 3 seconds
a02a4930cb5d: Retrying in 2 seconds
a02a4930cb5d: Retrying in 1 second
a02a4930cb5d: Retrying in 15 seconds
a02a4930cb5d: Retrying in 14 seconds
a02a4930cb5d: Retrying in 13 seconds
a02a4930cb5d: Retrying in 12 seconds
a02a4930cb5d: Retrying in 11 seconds
a02a4930cb5d: Retrying in 10 seconds
a02a4930cb5d: Retrying in 9 seconds
a02a4930cb5d: Retrying in 8 seconds
a02a4930cb5d: Retrying in 7 seconds
a02a4930cb5d: Retrying in 6 seconds
a02a4930cb5d: Retrying in 5 seconds
a02a4930cb5d: Retrying in 4 seconds
a02a4930cb5d: Retrying in 3 seconds
a02a4930cb5d: Retrying in 2 seconds
a02a4930cb5d: Retrying in 1 second
348b74f71ecb: Verifying Checksum
348b74f71ecb: Download complete
a02a4930cb5d: Retrying in 20 seconds
a02a4930cb5d: Retrying in 19 seconds
a02a4930cb5d: Retrying in 18 seconds
a02a4930cb5d: Retrying in 17 seconds
a02a4930cb5d: Retrying in 16 seconds
a02a4930cb5d: Retrying in 15 seconds
a02a4930cb5d: Retrying in 14 seconds
a02a4930cb5d: Retrying in 13 seconds
a02a4930cb5d: Retrying in 12 seconds
a02a4930cb5d: Retrying in 11 seconds
a02a4930cb5d: Retrying in 10 seconds
a02a4930cb5d: Retrying in 9 seconds
a02a4930cb5d: Retrying in 8 seconds
a02a4930cb5d: Retrying in 7 seconds
a02a4930cb5d: Retrying in 6 seconds
a02a4930cb5d: Retrying in 5 seconds
a02a4930cb5d: Retrying in 4 seconds
a02a4930cb5d: Retrying in 3 seconds
a02a4930cb5d: Retrying in 2 seconds
a02a4930cb5d: Retrying in 1 second
a02a4930cb5d: Download complete
a02a4930cb5d: Pull complete
9371245e9e1b: Pull complete
c55969dc4ace: Pull complete
064568f6d56f: Retrying in 20 seconds
064568f6d56f: Retrying in 19 seconds
064568f6d56f: Retrying in 18 seconds
064568f6d56f: Retrying in 17 seconds
064568f6d56f: Retrying in 16 seconds
064568f6d56f: Retrying in 15 seconds
064568f6d56f: Retrying in 14 seconds
064568f6d56f: Retrying in 13 seconds
064568f6d56f: Retrying in 12 seconds
064568f6d56f: Retrying in 11 seconds
064568f6d56f: Retrying in 10 seconds
064568f6d56f: Retrying in 9 seconds
064568f6d56f: Retrying in 8 seconds
064568f6d56f: Retrying in 7 seconds
064568f6d56f: Retrying in 6 seconds
064568f6d56f: Retrying in 5 seconds
064568f6d56f: Retrying in 4 seconds
064568f6d56f: Retrying in 3 seconds
064568f6d56f: Retrying in 2 seconds
064568f6d56f: Retrying in 1 second
064568f6d56f: Verifying Checksum
064568f6d56f: Download complete
064568f6d56f: Pull complete
348b74f71ecb: Pull complete
Digest: sha256:a105d39438e74c58f95116e672dda0812ce0b8d4050174903d3cd77d8819226d
Status: Downloaded newer image for docker.io/openshift/origin-control-plane:v3.11.0

 OK
-- Copying oc binary from the OpenShift container image to VM ...(minishift) Calling .GetSSHHostname
Error copying the oc binary to /var/lib/minishift/bin: connection is shut down

### Logs

https://gist.github.com/onderson/5dcfb438c61a7901d8f399a8cd598fb9

**Comment by gbraad** [comment]
This looks like an issue with pulling the image. Can you make sure the network connection is stable?

**Comment by onderson** [comment]
yes i can confirm, it is quite stable.
btw, it is a bit out of discussion but i still suspect, minishift can not deal with proxy settings very well. because recently after rebooting my vm, it mostly fails to start due to proxy setting. I tried using cntlm over corporate proxy, the proxy error i get vanishes but this image pulling issue still stands.

**Comment by onderson** [comment]
@praveenkumar, this issue has side effects due to proxy requiring authentication.

**Comment by onderson** [comment]
Closing.. The root of the issue is proxy
