### ISSUE TITLE
On fresh Linux Minishift suggests to use VirtualBox instead of KVM

### ISSUE THREAD

**Issue by scela** [minishift/minishift#3195]
Fresh laptop, I try to 'minishift start':

[sopot@localhost crw]$ minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... FAIL
   See the 'Installing Prerequisites for Minishift' topic (https://docs.okd.io/latest/minishift/getting-started/installing.html#install-prerequisites) for more information

**Comment by LalatenduMohanty** [comment]
On Linux Minishift should check for KVM not Virtualbox, so need to check why it is checking for Virtualbox.

**Comment by gbraad** [comment]
This might be due to the fact that the driver for KVM does not exist and/or you have modified the config to use `vm-driver` `virtualbox`.

can you provide more details around this?

**Comment by LalatenduMohanty** [comment]
@gbraad You are right, I forgot to update the issue. @scela had Virtualbox as the `vm-driver` in the config. Closing the issue.
