### ISSUE TITLE
minishift start fails with errors saying at last "Closing plugin on server side" and it start though

### ISSUE THREAD

**Issue by onderson** [minishift/minishift#3196]
### General information

  * Minishift version: minishift v1.32.0+009893b
  * OS: Ubuntu 18.04
  * Hypervisor: KVM 

### Steps to reproduce
minishift start --show-libmachine-logs -v5

### Expected
minishift start command ends successfully

### Actual
Using Kubeconfig Path:  /home/onders/.kube/config
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:41965
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetSSHHostname
(minishift) DBG | GetIP called for minishift
(minishift) DBG | Fetching VM...
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) DBG | IP address: 192.168.42.216
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:8b:86:fb
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) DBG | AK: resolvestorepath: /home/onders/.minishift
(minishift) DBG | AK: resolvestorepath: /home/onders/.minishift
(minishift) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /home/onders/.minishift/machines/minishift/id_rsa (-rw-------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@192.168.42.216 -o IdentitiesOnly=yes -i /home/onders/.minishift/machines/minishift/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
docker version --format '{{.Server.APIVersion}}'
SSH cmd err, output: <nil>: 1.26

(minishift) Calling .GetIP
(minishift) DBG | GetIP called for minishift
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) DBG | IP address: 192.168.42.216
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:8b:86:fb
-- Exporting of OpenShift images is occuring in background process with pid 17479.
Making call to close driver server
(minishift) Calling .Close
(minishift) DBG | Closing plugin on server side
Successfully made call to close driver server
Making call to close connection to plugin binary
Making call to close driver server
(minishift) Calling .Close
(minishift) DBG | Closing plugin on server side
Successfully made call to close driver server
Making call to close connection to plugin binary
Making call to close driver server
(minishift) Calling .Close
(minishift) DBG | Closing plugin on server side
Successfully made call to close driver server
Making call to close connection to plugin binary
Making call to close driver server
(minishift) Calling .Close
Successfully made call to close driver server
Making call to close connection to plugin binary
Making call to close driver server
(minishift) Calling .Close
(minishift) DBG | Closing plugin on server side
Successfully made call to close driver server
Making call to close connection to plugin binary

Even though it gives errors, i can log into minishift web console in https://192.168.42.216:8443/console

### Logs

https://gist.github.com/onderson/ccf687bdf09ad03ddfd295edba1d677a#file-minishift-start-fails-with-errors-saying-at-last-closing-plugin-on-server-side-and-it-start-though

**Comment by onderson** [comment]
by looking at;

/var/log/libvirt/qemu

onders@ondersvbvm:~$ sudo tail -f /var/log/libvirt/qemu/minishift.log


i can see;

2019-03-07T09:33:42.059669Z qemu-system-x86_64: terminating on signal 15 from pid 2518 (/usr/sbin/libvirtd)
2019-03-07 09:33:43.176+0000: shutting down, reason=destroyed
2019-03-07 09:34:05.881+0000: starting up libvirt version: 4.0.0, package: 1ubuntu8.6 (Christian Ehrhardt <christian.ehrhardt@canonical.com> Fri, 09 Nov 2018 07:42:01 +0100), qemu version: 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.10), hostname: ondersvbvm
LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin QEMU_AUDIO_DRV=none /usr/bin/kvm-spice -name guest=minishift,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-3-minishift/master-key.aes -machine pc-i440fx-bionic,accel=kvm,usb=off,dump-guest-core=off -m 4096 -realtime mlock=off -smp 2,sockets=2,cores=1,threads=1 -uuid 48d8f3ea-381b-43a1-a051-30f1c636595b -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-3-minishift/monitor.sock,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-shutdown -boot menu=off,strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -drive file=/home/onders/.minishift/machines/minishift/minishift.img,format=raw,if=none,id=drive-ide0-0-0,aio=threads -device ide-hd,bus=ide.0,unit=0,drive=drive-ide0-0-0,id=ide0-0-0,bootindex=2 -drive file=/home/onders/.minishift/machines/minishift/boot2docker.iso,format=raw,if=none,id=drive-ide0-1-0,readonly=on -device ide-cd,bus=ide.1,unit=0,drive=drive-ide0-1-0,id=ide0-1-0,bootindex=1 -netdev tap,fd=26,id=hostnet0 -device rtl8139,netdev=hostnet0,id=net0,mac=52:54:00:2e:b1:a8,bus=pci.0,addr=0x3 -netdev tap,fd=28,id=hostnet1 -device rtl8139,netdev=hostnet1,id=net1,mac=52:54:00:8b:86:fb,bus=pci.0,addr=0x4 -vnc 127.0.0.1:0 -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x5 -msg timestamp=on
2019-03-07T09:34:05.957802Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
2019-03-07T09:34:05.960195Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]

Not sure if it related somehow..

I can not start minishift. Any guidance is appreciated. 
Cheers

**Comment by anjannath** [comment]
@onderson The initial issue comment https://github.com/minishift/minishift/issues/3196#issue-418189654 there are no errors, minishift has started, and you see those messages because you have enabled logs from libmachine side and also more verbose logs from minishift.

> I can not start minishift. Any guidance is appreciated.

What is the error that you get now when you start minishift [`minishift start`]?

**Comment by onderson** [comment]
@anjannath , yes you are right. closing. thanks
