### ISSUE TITLE
Add --follow option to `minishift logs` subcommand

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#320]
Currently we can't follow up logs of `origin` container but only able to dump it to `stdout`. Docker provide a way to follow running container logs using `--follow` and it would be good UX if we can have it for minishift.

**Comment by hferentschik** [comment]
This follows up on issue #302

**Comment by hferentschik** [comment]
@budhrg do you still have you feature branch? Maybe we can dust it off a bit in a spare minute?

**Comment by budhrg** [comment]
@hferentschik , yes. its here https://github.com/budhrg/minishift/commit/f19b66e8cc3f4300bd9fe7d5881526487071b54a.

**Comment by hferentschik** [comment]
Merged via pull request #1061
