### ISSUE TITLE
Fail to use minishift with registry.redhat.io

### ISSUE THREAD

**Issue by heiko-braun** [minishift/minishift#3202]
### General information

  * Minishift version: v1.32.0+009893b
  * OS: macOS
  * Hypervisor: xhyve 

I have tried the registry-login addon, and other means to configure the pull secret, but it doesn't work for me. Any ideas?

### Steps to reproduce

  1. 
```
minishift addons apply redhat-registry-login --addon-env REGISTRY_USERNAME=$REGISTRY_USERNAME --addon-env REGISTRY_PASSWORD=$REGISTRY_PASSWORD
```

  2.

```
minishift ssh -- docker pull registry.redhat.io/rhel:latest
``` 

### Expected
Successful image pull 

### Actual

```
Trying to pull repository registry.redhat.io/rhel ... 
Get https://registry.redhat.io/v2/rhel/manifests/latest: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531
```

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by heiko-braun** [comment]
`docker pull registry.redhat.io/rhel7/rhel-atomic` works fine with the same credentials

**Comment by LalatenduMohanty** [comment]
> `docker pull registry.redhat.io/rhel7/rhel-atomic` works fine with the same credentials

Not sure how it is working in upstream Minishift by default. If you are using Red Hat CDK it will work by default. 

Can you try the `minishift addon apply redhat-registry-login`. We have created this add-on as it needs a secret which automatically does not get created in CentOS ISO. 

```
$ 'minishift' addon list
- admin-user			 : disabled	P(0)
- admissions-webhook		 : disabled	P(0)
- anyuid			 : disabled	P(0)
- che				 : disabled	P(0)
- htpasswd-identity-provider	 : disabled	P(0)
- redhat-registry-login		 : disabled	P(0)
- registry-route		 : disabled	P(0)
- xpaas				 : disabled	P(0)
```

**Comment by heiko-braun** [comment]
Thanks @LalatenduMohanty that's what I did (see inital description)

**Comment by agajdosi** [comment]
Hi @heiko-braun, the addon is not meant to create docker credentials directly in the docker. Instead it adds a secret into OpenShift cluster so the OpenShift can pull the images from the registry. As result when you run `minishift ssh -- docker pull registry.redhat.io/rhel:latest` it fails.

If you just want to use OpenShift with images from `registry.redhat.io` then the correct way to test whether all has been set up fine is to deploy some application which uses the images from the registry. Could you please try and let us know?

However if you need to use docker directly, you can run `minishift ssh -- docker login --username xyz --password abc` and then pull, but that should not be needed normally and is not supported really - probably you have quite specific usecase?

**Comment by heiko-braun** [comment]
Thanks @agajdosi, I see what you mean. I have tested it and it works as expected. Closing this.
