### ISSUE TITLE
Issue with oAuth  token in POST request

### ISSUE THREAD

**Issue by fmarchioni** [minishift/minishift#3205]
### General information
I'm hitting a 401 Unauthorized error when executing a POST request using an Auth Token.
  * Minishift version: minishift v1.32.0+009893b
  * OS: Linux Fedora 29
  * Hypervisor: KVM 

### Steps to reproduce

  1. Download EAP XPaas Test suite: https://gitlab.cee.redhat.com/xpaas-qe/test-eap/

  2. Include a test.properties file with Minishift cluster address:
xtf.openshift.url=https://192.168.42.44:8443
xtf.openshift.namespace=projectname
xtf.openshift.admin.username=admin
xtf.openshift.admin.password=admin
xtf.openshift.master.username=developer
xtf.openshift.master.password=developer
xtf.eap.72.image=registry.access.redhat.com/jboss-eap-7/eap72-openshift:1.0
xtf.eap.72.properties.previous.image=registry.access.redhat.com/jboss-eap-7/eap72-openshift:1.0
xtf.eap.72.properties.eap.imagestream.name=jboss-eap72-openshift
xtf.eap.72.version=7.2.0.GA
xtf.eap.72.templates.repo=git://github.com/jboss-container-images/jboss-eap-7-openshift-image.git,git://github.com/jboss-container-images/redhat-sso-7-openshift-image.git
xtf.eap.72.templates.branch=eap72,v7.3.0.GA
xtf.maven.proxy.url=http://maven.devel.xpaas/nexus/content/groups/public/
xtf.maven.central.proxy.url=http://maven.devel.xpaas/nexus/content/repositories/central/
xtf.openshift.route_domain=192.168.42.44.nip.io

  3. Run: mvn clean test -Ptest-eap,72 -Dtest=EEDefaultsTest#defaultAmqTest

### Expected
This test executes with success against an OCP Cluster.

### Actual
Test Failure.
Once that the test is executed, a Pod with Amq image is deployed. Then you can also verify the issue using any REST client (see attached picture):

POST URL:
https://192.168.42.44:8443/api/v1/namespaces/[NAMESPACE]/pods/https:[POD-NAME]:8778/proxy/jolokia/?maxDepth=7&maxCollectionSize=500

Data:
[{"type":"read","mbean":"org.apache.activemq:type=Broker,brokerName=[[POD-NAME]],destinationType=Queue,destinationName=queue/fooBar","config":{}}]

Include in the Authorization "Bearer [Token]" using a token generated with "whoami -t"

### Logs

https://gist.github.com/fmarchioni/2a19ed741015cfe7ae76011169538888
![token](https://user-images.githubusercontent.com/1316493/54344760-e0368a00-4641-11e9-906d-90e73f1c5652.png)

**Comment by LalatenduMohanty** [comment]
@fmarchioni Have you successfully ran the test on Minishift in the past? Or this is the first time you are trying this?

**Comment by fmarchioni** [comment]
@LalatenduMohanty I've never been able to run this test successfully on Minishift.
In the test suite I have observed some occasional failures for other tests (I assume the cluster health was critical) but for this one I only see failures.
