### ISSUE TITLE
Specified path to kubeconfig does not exist

### ISSUE THREAD

**Issue by jgammon612** [minishift/minishift#3206]
### General information
Related to: minishift stop -> start returns error : could not set oc CLI context for 'minishift' profile #2679

  * Minishift version: 3.11.43
  * OS:  macOS
  * Hypervisor:  VirtualBox

### Steps to reproduce

  1. minishift start or minishit --profile base-demo1 start
  2. related to minishift stop -> start returns error : could not set oc CLI context for 'minishift' profile #2679
  4. 

### Expected
No error expected

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5
[minishift_v5.log](https://github.com/minishift/minishift/files/2975889/minishift_v5.log)
` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by LalatenduMohanty** [comment]
Looks like somehow the profile `base-demo1` is corrupted.  Can you create a new profile `minishift profile set new-base-demo1` and try the `minishift start` again?

**Comment by jgammon612** [comment]
This idea failed

Johns-MacBook-Pro:~ jgammon$ minisihft config view
-bash: minisihft: command not found
Johns-MacBook-Pro:~ jgammon$ minishift config view
- cpus                               : 4
- disk-size                          : 40GB
- iso-url                            : file:///Users/jgammon/.minishift/cache/iso/minishift-rhel7.iso
- memory                             : 8196
- skip-check-openshift-release       : true
- vm-driver                          : virtualbox
Johns-MacBook-Pro:~ jgammon$  minishift stop
Stopping the OpenShift cluster...
Cluster stopped.
Johns-MacBook-Pro:~ jgammon$  minishift start --skip-registration
-- Starting profile 'new-demo-profile'
-- Check if deprecated options are used ... OK
-- Checking if https://mirror.openshift.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.43' is valid ... SKIP
-- Checking if requested OpenShift version 'v3.11.43' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM .................................................................. OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... OK
-- OpenShift cluster will be configured with ...
   Version: v3.11.43
-- Pulling the OpenShift Container Image ............................................ OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ...............................................................................................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --base-dir /var/lib/minishift/base --image 'registry.access.redhat.com/openshift3/ose-${component}:v3.11.43' --public-hostname 192.168.99.100 --routing-suffix 192.168.99.100.nip.io
err     : exit status 1
output  : Getting a Docker client ...
Checking if image registry.access.redhat.com/openshift3/ose-control-plane:v3.11.43 is available ...
Pulling image registry.access.redhat.com/openshift3/ose-cli:v3.11.43
E0318 15:09:33.116209    6361 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image registry.access.redhat.com/openshift3/ose-cli:v3.11.43 anonymously
Image pull complete
Pulling image registry.access.redhat.com/openshift3/ose-node:v3.11.43
E0318 15:09:44.338481    6361 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image registry.access.redhat.com/openshift3/ose-node:v3.11.43 anonymously
Pulled 5/6 layers, 84% complete
Pulled 5/6 layers, 92% complete
Pulled 5/6 layers, 98% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.99.100 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image registry.access.redhat.com/openshift3/ose-control-plane:v3.11.43 is available ...
Starting OpenShift using registry.access.redhat.com/openshift3/ose-control-plane:v3.11.43 ...
I0318 15:11:09.208457    6361 config.go:40] Running "create-master-config"
I0318 15:11:11.088957    6361 config.go:46] Running "create-node-config"
I0318 15:11:11.982554    6361 flags.go:30] Running "create-kubelet-flags"
I0318 15:11:12.403314    6361 run_kubelet.go:49] Running "start-kubelet"
I0318 15:11:12.617135    6361 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I0318 15:14:11.641029    6361 interface.go:26] Installing "kube-proxy" ...
I0318 15:14:11.641914    6361 interface.go:26] Installing "kube-dns" ...
I0318 15:14:11.641925    6361 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I0318 15:14:11.641932    6361 interface.go:26] Installing "openshift-apiserver" ...
I0318 15:14:11.641971    6361 apply_template.go:81] Installing "openshift-apiserver"
I0318 15:14:11.642279    6361 apply_template.go:81] Installing "kube-dns"
I0318 15:14:11.643489    6361 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I0318 15:14:11.646069    6361 apply_template.go:81] Installing "kube-proxy"
I0318 15:14:15.409902    6361 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: timed out waiting for the condition

Johns-MacBook-Pro:~ jgammon$
