### ISSUE TITLE
use own fork of go-bindata in makefile

### ISSUE THREAD

**Issue by jsliacan** [minishift/minishift#3207]
### General information

  * Minishift version: 
  * OS: Linux 
  * Hypervisor: KVM

Makefile using jteeuwen's go-bindata (line 122-123). Can use our own fork of this.

**Comment by LalatenduMohanty** [comment]
Community folks created the `https://github.com/jteeuwen/go-bindata` after the original repository was deleted. So we decided to use it. Hence this is not an issue anymore.

**Comment by agajdosi** [comment]
@jsliacan Sorry for false alarm. Seems https://github.com/jteeuwen/go-bindata can be trusted.
