### ISSUE TITLE
Cannot access Web Console on chrome after minishift start

### ISSUE THREAD

**Issue by rajatsingh25aug** [minishift/minishift#3208]
### General information

  * Minishift version: minishift v1.31.0+cfc599c
  * OS: Linux (Fedora 29)
  * Hypervisor: KVM

### Steps to reproduce

  1. Type  `minishift console` on the terminal
### Expected
Opening the OpenShift Web console in the default browser...(should open the web console)

### Actual
[13387:13387:0319/011230.700100:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
### Logs
[https://gist.github.com/rajatsingh25aug/db0af21fa15f1cd4f2a480f6a44ad1f4](Here!)

After doing several `minisift start/stop`, I'll be able to access the minishift console.

**Comment by gbraad** [comment]
Why did you close this?

**Comment by rajatsingh25aug** [comment]
@gbraad Got it working by doing `minishift delete` and then `minishift start`
