### ISSUE TITLE
mages

### ISSUE THREAD

**Issue by tjaeschke** [minishift/minishift#3209]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
?

**Comment by tjaeschke** [comment]
Sorry, opened the thread accidently
