### ISSUE TITLE
Can't start minishift on Ubuntu 18.04: "qemu-system-x86_64: error: failed to set MSR 0x38d to 0x0"

### ISSUE THREAD

**Issue by mydockergit** [minishift/minishift#3210]
### General information
I am running Ubuntu 18.04 on my VMware workstation.  
Virtualization is enabled (`Virtualize Intel VT-x/EPT or AMD-V/RVI` is checked).

  * Minishift version: minishift v1.33.0+ba29431
  * OS: Linux Ubuntu 18.04
```
root@ubuntu:~# uname -a && lsb_release -a
Linux ubuntu 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```
  * Hypervisor: KVM 

### Steps to reproduce
Make sure minikube is running with `minikube start --vm-driver=none`. and then `minikube status` and `kubectl get pods`.  
  1. Follow the [instructions ](https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html)to prepare virtualization environment
  2. Download `minishift-1.33.0-linux-amd64.tgz`
  3. Extracted it and ran `minishift start -
  4. 

### Expected
minishift to start

### Logs
```
root@ubuntu:~# minishift start --show-libmachine-logs -v5
-- minishift version: v1.33.0+ba29431
-- Starting profile 'minishift'
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:38563
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM ....Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:44151
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Calling .Start
(minishift) DBG | Starting VM minishift
(minishift) Failed to start: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2019-03-20T08:24:27.738295Z qemu-system-x86_64: error: failed to set MSR 0x38d to 0x0
(minishift) qemu-system-x86_64: /build/qemu-dVNw8t/qemu-2.11+dfsg/target/i386/kvm.c:1807: kvm_put_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.')
 FAIL E0320 01:24:28.148969   33192 start.go:494] Error starting the VM: Error starting stopped host: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2019-03-20T08:24:27.738295Z qemu-system-x86_64: error: failed to set MSR 0x38d to 0x0
qemu-system-x86_64: /build/qemu-dVNw8t/qemu-2.11+dfsg/target/i386/kvm.c:1807: kvm_put_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.'). Retrying.
Error starting the VM: Error starting stopped host: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2019-03-20T08:24:27.738295Z qemu-system-x86_64: error: failed to set MSR 0x38d to 0x0
qemu-system-x86_64: /build/qemu-dVNw8t/qemu-2.11+dfsg/target/i386/kvm.c:1807: kvm_put_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.')

```

**Comment by mydockergit** [comment]
After enabling the `Virtualize CPU performance counters` I was able to start minishift.  
![image](https://user-images.githubusercontent.com/37586216/54670829-36517480-4afd-11e9-8c9d-7741f6bdf06b.png)

I used this solution after I saw similar issue [here](https://github.com/kubernetes/minikube/issues/2968).

**Comment by VitalyVo** [comment]
Thanks!

**Comment by eyvindx** [comment]
thaks

**Comment by dkarakas1** [comment]
This isn't actually resolved.  All that's offered is a workaround.

Minishift shouldn't impose cpu performance counters if that's what's happening here.  The workaround is insufficient for some users.  Specifically, when an ESXi cluster is configured for Enhanced vMotion Compatibility (aka EVC), CPU performance counters are not supported. As such, the _workaround_ offered above is insufficient and Minishift is unable to start.

While its unlikely I'll be able to convince my organization to stop using EVC as its a useful and necessary feature for our environment, I might be able to convince this project (you) to make cpu counters more forgiving.  Bottom line is that ESXi + vMotion customers are unable to install minishift guests, which makes me sad.

Please consider reopening this issue and addressing it more completely.

**Comment by tallos673** [comment]
@grossmj

Same problem with Proxmox and qemu-system-x86-64.
I have KGPE-D16 and 2x6276 Opteron's 

I can't run well any Arista veOS images on EVE-NG or GNS3.
```
qemu-system-x86_64 error failed to set msr 0xe1 to 0x0
and this
kvm_buf_set_msrs
```
Its sad...

**Comment by Gamerios** [comment]
Hello,


Ubuntut 20.04 and QEMU Virt-Manager - Nested virtualization suddenly doesnt work

Since Yesterday when i want start Windows 10 VM in Ubuntu 20.04 and QEMU 4.2.1 also tryed 5.2 and 6.2 and latest

i get this error:

Code:

qemu-system-x86_64: error: failed to set MSR 0x48f to 0xffffff00036dfb
qemu-system-x86_64: /home/user/qemu-4.2.1/target/i386/kvm.c:2691: kvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.




i have kvm ignore_msrs=1 and so on tryed ON and OFF like before it worked in XML

Code:

<cpu mode="host-passthrough" check="none" migratable="on">
    <topology sockets="1" dies="1" cores="11" threads="2"/>
    <cache mode="passthrough"/>
    <feature policy="require" name="hypervisor"/>
    <feature policy="disable" name="mpx"/>
    <feature policy="require" name="ibpb"/>
    <feature policy="require" name="md-clear"/>
    <feature policy="require" name="spec-ctrl"/>
    <feature policy="require" name="ssbd"/>
    <feature policy="require" name="invtsc"/>
  </cpu>



Anyone can help it worked now for years but now not anymore since apt update and apt upgrade need downgrade Ubuntu Linux Kernel?


i need CPU Host-Passthrough otherwise Windows 10 has no good performance like in all Windows 10 Gaming VM GPU Passthrough Tutorials stand and also i tested

Hope any one can help here also GRUB


Code:

 GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_iommu=on kvm.ignore_msrs=1 video=efifb:off vfio-pci.ids=10de:2486,10de:228b,10de:2503,10de:228e isolcpus=3-13,17-27 nohz_full=3-13,17-27 rcu_nocbs=3-13,17-27 msr.allow_writes=on kvm.intel_nested=1"



A and
Ubuntu Linux Kernel
5.11.0-43-generic



and when start MacOS VM also with CPU Host-Passthrough it work witout an Error hmm

Thank ya
Kind Regards
