### ISSUE TITLE
Che addon timeout when trying to run a workspace

### ISSUE THREAD

**Issue by jsliacan** [minishift/minishift#3216]
### General information

  * Minishift version: v1.33.0+ba29431
  * OS: Linux
  * Hypervisor: KVM

### Steps to reproduce

  1. Start minishift
  2. Apply addon che `minishift addon apply che`
  3. Go to Che dashboard
  4. Choose e.g. Java workspace (but fails with Python, Nodejs, ...)
  5. Wait ~10mins.

It works fine with Che versions 6.x and with 7.0.0-beta-1.0. Does not work with latest, nightly, 7.0.0-beta-2.0 and 7.0.0-beta-3.0 (some of these are the same). 

### Actual

`pulling image "eclipse/ubuntu_jdk8"`
`Successfully pulled image "eclipse/ubuntu_jdk8"`
`Created container`
`Started container`
`Error: Failed to run the workspace: "Waiting for Kubernetes environment 'default' of the workspace'workspacexwikidqvvhifiumq' reached timeout"`

**Comment by agajdosi** [comment]
Hi @l0rd, as the Che version is not fixed in Minishift addon (is set to tag `latest` in docker hub) the Che addon stopped working when `Che 7.0.0-beta-2.0` has come as `latest`. It starts just fine, but the deployment of workspaces fails with timeout. Could you please take a look when you have some time?

**Comment by agajdosi** [comment]
Adding some extra logs from inside of the workspace pod (/workspace_logs/bootstrapper/bootstrapper.log):

```
$ cat bootstrapper.log
2019/03/26 11:42:21 Bootstrapper configuration
2019/03/26 11:42:21   Push endpoint: ws://che-mini-che.192.168.42.238.nip.io/api/websocket
2019/03/26 11:42:21   Push logs endpoint: ws://che-.192.168.42.238.nip.io:8080/api/websocket-minor
2019/03/26 11:42:21   Auth enabled: true
2019/03/26 11:42:21   Runtime ID:
2019/03/26 11:42:21     Workspace: workspacep1tge68y1oerr1kb
2019/03/26 11:42:21     Environment: default
2019/03/26 11:42:21     OwnerId: che
2019/03/26 11:42:21   Machine name: dev-machine
2019/03/26 11:42:21   Installer timeout: 180seconds
2019/03/26 11:42:21   Check servers period: 3seconds
2019/03/26 11:42:21   Push logs endpoint reconnect period: 10seconds
2019/03/26 11:42:21 Couldn't connect to endpoint 'ws://che-.192.168.42.238.nip.io:8080/api/websocket-minor', due to error 'dial tcp: lookup che-.192.168.42.238.nip.io: no such host'
```

**Comment by l0rd** [comment]
@agajdosi I will have a look. We may need to update the template default values.

**Comment by l0rd** [comment]
@agajdosi @LalatenduMohanty I have provided a [PR](https://github.com/minishift/minishift/pull/3222) to fix that. I would like to take this opportunity to discuss 2 things:

1) The fix consisted simply in copying [che-server-template.yaml](https://github.com/eclipse/che/blob/master/deploy/openshift/templates/che-server-template.yaml) and [che-workspace-service-account.yaml](https://github.com/eclipse/che/blob/master/deploy/openshift/templates/che-workspace-service-account.yaml) to the addon template repos. For consistency we should probably do it every time we release Che (every 3 week). Do you have any idea about how we could automate this process?
2) The examples you are using in you tests will be broken in a few weeks as we are transitioning from Che 6 based workspaces to Che 7 based. This means that part of your tests should be rewritten. I would like to help with that but I am afraid that we won't have time/resources do it until Che 7 is GA (late may). How do

**Comment by agajdosi** [comment]
Hi @l0rd, good to know the location. I will add the file to my PR which adds check for up-to-dateness of addon templated (#3212). It does not have functionality to automatically update the templates, but at least we will know.
