### ISSUE TITLE
Minishift status says: 'openshift stopped'

### ISSUE THREAD

**Issue by jonalv** [minishift/minishift#3218]
### General information

  * Minishift version: minishift v1.32.0+009893b
  * OS: macOS
  * Hypervisor: xhyve

### Steps to reproduce

  1. $ minishift start
  2. $ minishift status
  3. 
  4. 

### Expected
Minishift:  Running
Profile:    minishift
OpenShift:  Not Stopped?? / Running??
DiskUsage:  17% of 17.9G (Mounted On: /mnt/sda1)
CacheUsage: 805.3 MB (used by oc binary, ISO or cached images)

### Actual
Minishift:  Running
Profile:    minishift
OpenShift:  Stopped
DiskUsage:  17% of 17.9G (Mounted On: /mnt/sda1)
CacheUsage: 805.3 MB (used by oc binary, ISO or cached images)

### Logs
https://gist.github.com/jonalv/d77412f727ff060ebb388863c01d0708

**Comment by trotro** [comment]
Same here on Windows

- minishift v1.34.0+f5db7cb
- Windows 10 Pro 1809 (v17763.503)
- virtualbox 6.0.8

```
> minishift.exe status
Minishift:  Running
Profile:    minishift
OpenShift:  Stopped
DiskUsage:  1% of 18G (Mounted On: /mnt/sda1)
CacheUsage: 665.3 MB (used by oc binary, ISO or cached images)
RHSM:       Registered
```

The minishift VM seems ok,  Docker engine is up & running and I can manually run containers.
Any intel ?

**Comment by fxgx99** [comment]
Another ongoing problem that is been closed without solution. This should be unacceptable.
