### ISSUE TITLE
Can't access the deployed app

### ISSUE THREAD

**Issue by helio-frota** [minishift/minishift#3219]
### General information

Weeks ago I was able to access and test an example app on minishift, but yesterday I decided to play again with the example app, but I can't access anymore:

```console
12:55 $ curl -v http://express-prometheus-minishift-myproject.192.168.99.101.nip.io/
*   Trying 192.168.99.101...
* TCP_NODELAY set
* connect to 192.168.99.101 port 80 failed: Connection refused
* Failed to connect to express-prometheus-minishift-myproject.192.168.99.101.nip.io port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to express-prometheus-minishift-myproject.192.168.99.101.nip.io port 80: Connection refused
```

Inside the web console I see this message:

```
The route is not accepting traffic yet because it has not been admitted by a router.
```

The unique thing that changed was accept the automatic updates from Ubuntu 18.04. Which 
also updated the Docker version from 18.09.2 to 18.09.3.

  * Minishift version: minishift v1.33.0+ba29431
  * OS: Linux Ubutu 18.04
  * VirtualBox

### Steps to reproduce

  1. start minishift
  2. deploy app
  3. try to access the app
  4. Or follow the [Example App](https://github.com/helio-frota/express-prometheus-minishift#how-to-setup-and-run)

### Expected

Able to access the app.

### Actual

`port 80: Connection refused`

`The route is not accepting traffic yet because it has not been admitted by a router.`

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by helio-frota** [comment]
I decided to install fedora 29 and now I can access the app again.
That not sounds good IMO.

On fedora 29 was not required to run two extra commands:

```console
minishift addon install --defaults
minishift addon apply registry-route
```

More details about the error on ubuntu 18.04 here:
https://github.com/helio-frota/express-prometheus-minishift/issues/1#issuecomment-467843150

Anyway I'm going to close this issue but keep that note in case other user try to search for similar situation.

**Comment by omiozil** [comment]
Hey Can you look into this #3261
