### ISSUE TITLE
Nightly build fails on dead link

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#3220]
### General information

  * Minishift version: master

Nightly build of Minishift fails on dead link to https://blogs.msdn.microsoft.com/virtual_pc_guy/2010/09/28/creating-a-hyper-v-administrators-local-group-through-powershell. We need to find where the doc moved or find another equivalent document.

### Logs

```
02:01:30 - build/troubleshooting/troubleshooting-driver-plugins.html
02:01:30   *  External link https://blogs.msdn.microsoft.com/virtual_pc_guy/2010/09/28/creating-a-hyper-v-administrators-local-group-through-powershell failed: 410 No error
02:01:30 htmlproofer 3.7.2 | Error:  HTML-Proofer found 1 failure!
02:01:30 rake aborted!
```

**Comment by apupier** [comment]
seems the page has been completely removed, even in archive there is nothing at the 28/09/2010:
![image](https://user-images.githubusercontent.com/1105127/55167945-30e5d100-5172-11e9-8f9d-404f9fef1ec7.png)

**Comment by tsedmik** [comment]
It was on a personal blog (Virtual PC Guy). The entire blog is gone. The blog post is accessible via web archive: https://web.archive.org/web/20190110115556/https://blogs.msdn.microsoft.com/virtual_pc_guy/2010/09/28/creating-a-hyper-v-administrators-local-group-through-powershell/. But reference it from there is not a good solution :-(.

**Comment by tsedmik** [comment]
Since the blog post is from 2010 and Windows has _Hyper--V Administrators_ group build-in, I opt for removing the mention on the blog post.

**Comment by gbraad** [comment]
It has the group ONLY after the creator's edition and when HyperV is installed
