### ISSUE TITLE
Fail E0329 - Error starting the VM: Error getting the state for host: machine does not exist

### ISSUE THREAD

**Issue by TechFanDan** [minishift/minishift#3225]
### General information

  * Minishift version: 1.33
  * OS: Windows 10 Pro
  * Hypervisor: VirtualBox 6

### Steps to reproduce

  1. .\minishift.exe start --vm-driver virtualbox --show-libmachine-logs -v5
  2. I tried using both user and administrator PS/cmd shells 
  3. I started minishift from C:\ per issue #236
  4. I started with --vm-driver parameter to ensure Virtualbox to be used

### Logs

PS C:\> .\minishift.exe start --vm-driver virtualbox --show-libmachine-logs -v5
-- minishift version: v1.33.0+ba29431
-- Starting profile 'minishift'
Found binary path at C:\minishift.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:4379
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minishift --machinereadable
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | VBoxManage.exe: error: Could not find a registered machine named 'minishift'
Error getting machine state: machine does not exist
(minishift) DBG | VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
(minishift) DBG | VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2621 of file VBoxManageInfo.cpp
(minishift) DBG | }
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ....Found binary path at C:\minishift.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:4383
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minishift --machinereadable
(minishift) DBG | STDOUT:
 FAIL (minishift) DBG | {
(minishift) DBG | }
E0329 11:59:51.955059   12176 start.go:494] Error starting the VM: Error getting the state for host: machine does not exist. Retrying.
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | VBoxManage.exe: error: Could not find a registered machine named 'minishift'
(minishift) DBG | VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
(minishift) DBG | VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2621 of file VBoxManageInfo.cpp
(minishift) DBG | }
Error starting the VM: Error getting the state for host: machine does not exist

**Comment by TechFanDan** [comment]
I figured it out.

1. I moved the binary under C:
2. I ran minishift delete (to clean cache)
3. I ran minishift start  

The console interface came up after that.

**Comment by pazlle07** [comment]
> I figured it out.
> 
> 1. I moved the binary under C:
> 2. I ran minishift delete (to clean cache)
> 3. I ran minishift start
> 
> The console interface came up after that.

It's work.Thanks!
