### ISSUE TITLE
Minishift fails to start when VirtualBox present on Mac OSX 10.14

### ISSUE THREAD

**Issue by jsliacan** [minishift/minishift#3231]
### General information

  * Minishift version: v1.33.0+ba29431
  * OS: macOS 10.14
  * Hypervisor: xhyve / VirtualBox

### Steps to reproduce

  1. Follow steps here: https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#for-macos
  2. Install VirtualBox (go to virtualbox.org, download, and install)
  3. `minishift start`

### Expected
Minishift starts without complaints.

### Actual
```
-- Starting Minishift VM ..... FAIL E0408 12:22:39.836361   14329 start.go:494] Error starting the VM: Error creating the VM. Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.4r128413\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads". Retrying.

Error starting the VM: Error creating the VM. Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.4r128413\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads"
```
### Note
I can start minishift with VirtualBox specified explicitly: `minishift start --vm-driver virtualbox`. But when I omit --vm-driver flag, it fails as described above. The error message is esp. confusing: complains about VB version 4 but knows that I have version 6.

**Comment by MikePadge** [comment]
Tested on 10.14.13 with no issues
Fails on 10.14.14

On 10.14.14 
Upgrade virtualbox to v6 resolves the issue @jsliacan
