### ISSUE TITLE
Poor user experience with the Red Hat logins

### ISSUE THREAD

**Issue by acdha** [minishift/minishift#3241]
### General information

  * Minishift version: minishift v1.33.0+ba29431
  * OS: macOS
  * Hypervisor: hyperkit

### Steps to reproduce

  1. `minishift start`

### Expected

The cluster is started and ready to use

### Actual

The cluster fails to in an indeterminate state which requires running `minishift stop` and `minishift start` to correct.

1. The username isn't saved, so it has to be entered every time.
1. The login prompt doesn't accept an email address, as the web page does
1. Needing to accept the new terms of service update caused an otherwise valid login to fail

```
-- Registering machine using subscription-manager
   Red Hat Developers or Red Hat Subscription Management (RHSM) username: …
   Retriving password from keychain ... FAIL 
   Red Hat Developers or Red Hat Subscription Management (RHSM) password: [HIDDEN]
   Storing password in keychain ... OK 
   Login to registry.redhat.io in progress . FAIL 
   Registration in progress . FAIL [2s]
```

It seems like any path which leads to registration failing should either shut down the system automatically _or_ have some faster way to resume since it takes a noticeable period of time for it to start up normally. 

There'd also be some benefit in having it (preferably) accept email addresses or at least having a smoother fallback to re-prompt for the username with an explanation. Right now if anything goes wrong in that process it takes several minutes to recover.

**Comment by anjannath** [comment]
>1. The username isn't saved, so it has to be entered every time.

This is by design we need the username to retrive the password from key-chain.
>2. The login prompt doesn't accept an email address, as the web page does

It should, i mean i can use my email address to login

The failure you see are mostly due to network issues, if you have a flakey connection the logins fail, we have also seen this in our testing, this is an issue with the underlying `subscription-manager` tool, which is used for the login/registering the VM.

**Comment by acdha** [comment]
> This is by design we need the username to retrive the password from key-chain.

Couldn't that be stored in the config file?
