### ISSUE TITLE
In correct documentation for component list 

### ISSUE THREAD

**Issue by gorkem** [minishift/minishift#3247]
The description for ` minishift openshift component add` and ` minishift openshift component list ` are the same. It looks like a copy paste error.  
![image](https://user-images.githubusercontent.com/82738/56910478-a944f800-6a78-11e9-93af-b3c2ce00b373.png)

**Comment by anjannath** [comment]
Fixed via https://github.com/minishift/minishift/commit/22359480246cec3a116c6d9d7201c6d48bba0f43
