### ISSUE TITLE
Error in creating machine when trying to start minishift.

### ISSUE THREAD

**Issue by ramakrishna578** [minishift/minishift#3248]
Hi guys,
I am new to minishft and I got a problem while installing minishift. Can someone please guide me through this.
Thanks in advance.

### General information

  * Minishift version: 1.33.0
  * Windows 10 64bit
VirtualBox 6.0.4

Starting Minishift VM ..... FAIL E0501 19:00:39.820043    4264 start.go:494] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: open /Users/user/.minishift/cache/iso/centos/v1.15.0/minishift-centos7.iso: The system cannot find the path specified.. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: open /Users/user/.minishift/cache/iso/centos/v1.15.0/minishift-centos7.iso: The system cannot find the path specified.

### Logs
D:\minishift-1.33.0-windows-amd64>minishift start --show-libmachine-logs -v5
-- minishift version: v1.33.0+ba29431
-- Starting profile 'minishift'
Found binary path at minishift.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:59631
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minishift --machinereadable
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | }
Error getting machine state: machine does not exist
(minishift) DBG | STDERR:
-- Check if deprecated options are used ... (minishift) DBG | {
OK
(minishift) DBG | VBoxManage.exe: error: Could not find a registered machine named 'minishift'
-- Checking if https://github.com is reachable ... (minishift) DBG | VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
(minishift) DBG | VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2621 of file VBoxManageInfo.cpp
(minishift) DBG | }
OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ....Found binary path at minishift.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:59635
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minishift --machinereadable
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | }
 FAIL (minishift) DBG | STDERR:
E0501 19:13:23.918835    5620 start.go:494] Error starting the VM: Error getting the state for host: machine does not exist. Retrying.
(minishift) DBG | {
(minishift) DBG | VBoxManage.exe: error: Could not find a registered machine named 'minishift'
(minishift) DBG | VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
(minishift) DBG | VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2621 of file VBoxManageInfo.cpp
(minishift) DBG | }
Error starting the VM: Error getting the state for host: machine does not exist

**Comment by praveenkumar** [comment]
Since you are already on Windows-10 what is the reason behind not using the `hyperV` then `virtualbox` ?

**Comment by toastbrotch** [comment]
is your minishift.exe on c: ? i had lots of troubles when it was not...

**Comment by willianba** [comment]
Solved almost as @toastbrotch said. As you can see minishift tries to open `/Users/user/.minishift/...`. As **/Users** is under **C:** you need to be in this working path. Just do a `cd C:/` then `minishift start`. This worked fine for me 😄
