### ISSUE TITLE
Could not set oc CLI context: Missing kubeconfig file on minishift start 

### ISSUE THREAD

**Issue by StuartArnell** [minishift/minishift#3250]
### General information

  * Minishift version: 
  * OS: macOS
  * Hypervisor: VirtualBox 

### Steps to reproduce

  minishift start --vm-driver virtualbox
also
  minishift start --profile NewMini --vm-driver virtualbox

All seems OK until the end of the startup where I get messages ...

OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.107:8443/console

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to the kube config '/Users/xxxxxxxx/.minishift/machines/minishift_kubeconfig' does not exist

oc commands to interact with the cluster fail as there is no config.
I guess its related - but I cannot get to the minishift console after this (always times out).

As directed, that file does not exist.
~/.kube does not exist either

 
There seem to be similar problems around, but none of the workarounds that I have found seem to work.

Tried deleting (and with force), and clearing the cache
Tried re-installing minishift

It is a 'hard' problem ..... happens every time.
   

### Logs

-- Starting profile 'NewMini'
-- Check if deprecated options are used ... OK
-- Checking if https://mirror.openshift.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.82' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.82' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ................................ OK
-- Registering machine using subscription-manager
   Login to registry.redhat.io in progress .. OK 
   Registration in progress ............ OK [26s]
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... OK
-- OpenShift cluster will be configured with ...
   Version: v3.11.82
-- Pulling the OpenShift Container Image .............................. OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ....................................................................................
Getting a Docker client ...
Checking if image registry.access.redhat.com/openshift3/ose-control-plane:v3.11.82 is available ...
Pulling image registry.access.redhat.com/openshift3/ose-cli:v3.11.82
Image pull complete
Pulling image registry.access.redhat.com/openshift3/ose-node:v3.11.82
Pulled 5/6 layers, 84% complete
Pulled 5/6 layers, 100% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.99.108 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image registry.access.redhat.com/openshift3/ose-control-plane:v3.11.82 is available ...
Starting OpenShift using registry.access.redhat.com/openshift3/ose-control-plane:v3.11.82 ...
I0503 20:45:36.127212    5419 config.go:40] Running "create-master-config"
I0503 20:45:42.235274    5419 config.go:46] Running "create-node-config"
I0503 20:45:44.691638    5419 flags.go:30] Running "create-kubelet-flags"
I0503 20:45:45.352317    5419 run_kubelet.go:49] Running "start-kubelet"
I0503 20:45:45.689828    5419 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I0503 20:47:06.720360    5419 interface.go:26] Installing "kube-proxy" ...
I0503 20:47:06.721359    5419 interface.go:26] Installing "kube-dns" ...
I0503 20:47:06.721370    5419 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I0503 20:47:06.721375    5419 interface.go:26] Installing "openshift-apiserver" ...
I0503 20:47:06.721408    5419 apply_template.go:81] Installing "openshift-apiserver"
I0503 20:47:06.721681    5419 apply_template.go:81] Installing "kube-proxy"
I0503 20:47:06.723387    5419 apply_template.go:81] Installing "kube-dns"
I0503 20:47:06.723710    5419 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I0503 20:47:18.504902    5419 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
I0503 20:51:07.550198    5419 run_self_hosted.go:242] openshift-apiserver available
I0503 20:51:07.551215    5419 interface.go:26] Installing "openshift-controller-manager" ...
I0503 20:51:07.551244    5419 apply_template.go:81] Installing "openshift-controller-manager"
I0503 20:51:14.085455    5419 interface.go:41] Finished installing "openshift-controller-manager"
Adding default OAuthClient redirect URIs ...
Adding registry ...
Adding router ...
Adding sample-templates ...
Adding persistent-volumes ...
Adding rhel-imagestreams ...
Adding web-console ...
I0503 20:51:14.176696    5419 interface.go:26] Installing "openshift-image-registry" ...
I0503 20:51:14.176708    5419 interface.go:26] Installing "openshift-router" ...
I0503 20:51:14.176714    5419 interface.go:26] Installing "sample-templates" ...
I0503 20:51:14.176828    5419 interface.go:26] Installing "persistent-volumes" ...
I0503 20:51:14.176843    5419 interface.go:26] Installing "rhel-imagestreams" ...
I0503 20:51:14.176851    5419 interface.go:26] Installing "openshift-web-console-operator" ...
I0503 20:51:14.177145    5419 apply_template.go:81] Installing "openshift-web-console-operator"
I0503 20:51:14.178653    5419 interface.go:26] Installing "sample-templates/mariadb" ...
I0503 20:51:14.178680    5419 interface.go:26] Installing "sample-templates/mysql" ...
I0503 20:51:14.178693    5419 interface.go:26] Installing "sample-templates/cakephp quickstart" ...
I0503 20:51:14.178704    5419 interface.go:26] Installing "sample-templates/jenkins pipeline ephemeral" ...
I0503 20:51:14.178715    5419 interface.go:26] Installing "sample-templates/sample pipeline" ...
I0503 20:51:14.178890    5419 interface.go:26] Installing "sample-templates/mongodb" ...
I0503 20:51:14.178906    5419 interface.go:26] Installing "sample-templates/dancer quickstart" ...
I0503 20:51:14.178917    5419 interface.go:26] Installing "sample-templates/django quickstart" ...
I0503 20:51:14.178930    5419 interface.go:26] Installing "sample-templates/nodejs quickstart" ...
I0503 20:51:14.178940    5419 interface.go:26] Installing "sample-templates/rails quickstart" ...
I0503 20:51:14.178949    5419 interface.go:26] Installing "sample-templates/postgresql" ...
I0503 20:51:14.179048    5419 apply_list.go:67] Installing "sample-templates/postgresql"
I0503 20:51:14.182375    5419 create_secret.go:82] Installing "imagestreamsecret"
I0503 20:51:14.182747    5419 apply_list.go:67] Installing "sample-templates/mariadb"
I0503 20:51:14.182892    5419 apply_list.go:67] Installing "sample-templates/mysql"
I0503 20:51:14.183003    5419 apply_list.go:67] Installing "sample-templates/cakephp quickstart"
I0503 20:51:14.183333    5419 apply_list.go:67] Installing "sample-templates/jenkins pipeline ephemeral"
I0503 20:51:14.183747    5419 apply_list.go:67] Installing "sample-templates/sample pipeline"
I0503 20:51:14.183925    5419 apply_list.go:67] Installing "sample-templates/mongodb"
I0503 20:51:14.184040    5419 apply_list.go:67] Installing "sample-templates/dancer quickstart"
I0503 20:51:14.185162    5419 apply_list.go:67] Installing "sample-templates/nodejs quickstart"
I0503 20:51:14.186586    5419 apply_list.go:67] Installing "sample-templates/rails quickstart"
I0503 20:51:14.203138    5419 apply_list.go:67] Installing "sample-templates/django quickstart"
I0503 20:51:40.074339    5419 apply_list.go:67] Installing "rhel-imagestreams"
I0503 20:51:43.035233    5419 interface.go:41] Finished installing "sample-templates/mariadb" "sample-templates/mysql" "sample-templates/cakephp quickstart" "sample-templates/jenkins pipeline ephemeral" "sample-templates/sample pipeline" "sample-templates/mongodb" "sample-templates/dancer quickstart" "sample-templates/django quickstart" "sample-templates/nodejs quickstart" "sample-templates/rails quickstart" "sample-templates/postgresql"
I0503 20:52:38.331380    5419 interface.go:41] Finished installing "openshift-image-registry" "openshift-router" "sample-templates" "persistent-volumes" "rhel-imagestreams" "openshift-web-console-operator"
Login to server ...
Creating initial project "myproject" ...
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.108:8443/console

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

Could not set oc CLI context for 'NewMini' profile: Error during setting 'NewMini' as active profile: The specified path to the kube config '/Users/stuartarnell/.minishift/profiles/NewMini/machines/NewMini_kubeconfig' does not exist

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by Sunmx** [comment]
I met this error also...
