### ISSUE TITLE
unknown flag: --remote-ip-address

### ISSUE THREAD

**Issue by theRemix** [minishift/minishift#3255]
### General information

  * Minishift versions : `minishift v1.33.0+ba29431` on Linux and Windows
  * Remote OS: CentOS 7

### Steps to reproduce

  1. Setup CentOS 7 on AWS EC2 instance
  2. [Configure an Existing Remote Machine](https://docs.okd.io/latest/minishift/using/run-against-an-existing-machine.html)
  3. Locally running `minishift start --vm-driver generic --remote-ipaddress 1.2.3.4 --remote-ssh-user username --remote-ssh-key ~/.ssh/id_ecdsa`

### Expected

Minishift would install on remote Ubuntu instance

### Actual

Error:
```
unknown flag: --remote-ip-address
```

### Logs

none

**Comment by gbraad** [comment]
@tsedmik can you verify this?

**Comment by danielhelfand** [comment]
@theRemix Apologies, I now see you have already asked in that pr.

**Comment by tsedmik** [comment]
I'm unable to reproduce this issue. I tried `minishift v1.33.0+ba29431` on Fedora 30 and Window 10 and it works.

Notice that the correct flag is `--remote-ipaddress` not `--remote-ip-address`

**Comment by gbraad** [comment]
You can check for the existing parameters/start flags with `minishift start
--help` (See:
https://docs.okd.io/latest/minishift/command-ref/minishift_start.html)
