### ISSUE TITLE
Minishift loses all Che workspaces after restart

### ISSUE THREAD

**Issue by mmorhun** [minishift/minishift#3259]
### General information

  * Minishift version: v1.33.0+ba29431
  * OS: Fedora 29 (Workstation Edition)
  * Hypervisor: VirtualBox 6.0.4

### Steps to reproduce

  1. Start minishift: `minishift start --vm-driver=virtualbox --cpus=4 --memory=16192 --disk-size=50GB --docker-opt userland-proxy=false`
  2. Deplay Che with `chectl`
  3. Create workspace, start it, clone a project
  4. Stop minishift with `minishift stop` command
  5. Start minishift again with `minishift start` command

### Expected
Che workspace is in place

### Actual
All Che workspaces with all the data are gone

**Comment by sleshchenko** [comment]
It happens because of missing PVC in che-server template https://github.com/minishift/minishift/blob/master/addons/che/templates/che-server-template.yaml
