### ISSUE TITLE
Unable to Acces Deployed App on Minishift

### ISSUE THREAD

**Issue by omiozil** [minishift/minishift#3261]
I have deployed app on minishift. but not able to process request to the deployed app.
I have Expose the service using oc expose Command

  * Minishift version:  minishift v1.33.0+ba29431
  * OS: Linux / macOS / Windows : ubuntu
  * Hypervisor: KVM 

### Steps to reproduce

  1. Fetch Image from docker Hub through new app command.
  2. OC expose Command
  3. Accessing api through below post command:

 http -v POST http://holidays-myproject.192.168.42.215.nip.io/api/holidays '{parameters}'
 

### Actual
POST /wsdl/example HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 0
Host: holidays-myproject.192.168.42.215.nip.io
User-Agent: HTTPie/0.9.8

HTTP/1.0 503 Service Unavailable
Cache-Control: private, max-age=0, no-cache, no-store
Connection: close
Content-Type: text/html
Pragma: no-cache

**Comment by gbraad** [comment]
> Fetch Image from docker Hub through new app command.

Can you provide the whole command you are using? There is not enough information to conclude what is happening. it might well be the container is not correctly cofigured.

**Comment by omiozil** [comment]
Hey gbraad, Below Are the Commands I have Used to deploy image on minishift.

1) oc new-app --docker-image username/dockerhubrepository:tagname.
2) oc expose svc service name.

**Comment by gbraad** [comment]
Which image is being deployed. Without this information I can only conclude
that the image is faulty.

**Comment by omiozil** [comment]
docker image omkar/mini:soap343  basically i have developed rest API in Apache camel and converted this into a docker image using a docker file .

This API takes below as request Parameters:
{
	"cellularPhone": "8787898788",
	"firstName": "asddasdsa",
	"lastName": "LJJJFF",
	"personUId": "12ui10"
}







soap343
