### ISSUE TITLE
completions for fish shell

### ISSUE THREAD

**Issue by XenGi** [minishift/minishift#3264]
### General information

  * Minishift version: v1.33.0+f585d55
  * OS: Linux (5.0.7-arch1-1-ARCH)
  * Hypervisor: KVM (libvirt 5.2.0-1, qemu 4.0.0-2)

### Steps to reproduce

  1. install minishift
  2. run `minishift completion fish`
  3. get the error: `Only bash and zsh are supported for minishift completion`

### Expected

I would like to have completions for my shell.

### Actual

Completions are only available for bash and zsh.

**Comment by gbraad** [comment]
Patches are welcome...

Note: we used to support fish, but this was unmaintainable as none of
the team members uses this shell. If you are willing to look at this,
we might reconsider ...

On Tue, May 14, 2019 at 7:13 PM Ricardo Band <notifications@github.com> wrote:
>
> General information
>
> Minishift version: v1.33.0+f585d55
> OS: Linux (5.0.7-arch1-1-ARCH)
> Hypervisor: KVM (libvirt 5.2.0-1, qemu 4.0.0-2)
>
> Steps to reproduce
>
> install minishift
> run minishift completion fish
> get the error: Only bash and zsh are supported for minishift completion
>
> Expected
>
> I would like to have completions for my shell.
>
> Actual
>
> Completions are only available for bash and zsh.
>
> Logs
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by XenGi** [comment]
I'll try to find some time to add it. It's not a deal breaker, just nice to have.

**Comment by XenGi** [comment]
Can you point me to an old commit or branch where fish support was still in place? Maybe I could reuse some code.
