### ISSUE TITLE
Can I run OpenShift 4?

### ISSUE THREAD

**Issue by rgov** [minishift/minishift#3267]
### General information

  * Minishift version: minishift v1.33.0+ba29431
  * OS: macOS
  * Hypervisor: hyperkit

### Steps to reproduce

```
$ minishift start --vm-driver hyperkit --openshift-version v4.1.0
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v4.1.0' is valid ... v4.1.0 is not a valid OpenShift versionFAIL
```

Squinting at the code, it looks like it checks whether there is a corresponding tag of openshift/origin. [There is](https://github.com/openshift/origin/releases/tag/v4.1.0), but there aren't binaries available.

**Comment by gbraad** [comment]
Minishift can only support 3.x releases (and will never be able to support 4.x as the way they are installed are very different). For 4.x we are developing CodeReady Containers, which is available from https://github.com/code-ready/crc/.

**Comment by jfmatth** [comment]
Check this too https://github.com/code-ready/crc/

**Comment by gbraad** [comment]
Minishift is 3.x only and will never support installing 4.x based
OpenShift clusters. As mentioned before, the solution you are looking
for is called CRC. At the moment we can not provide public images for
the cluster as they are based on OCP. Hopefully this will be resolved
soon... in the meantime you can follow instructions in the `snc` repo
to reproduce what we deliver.

On Sun, Jun 2, 2019 at 9:26 AM John Flynn Matthew
<notifications@github.com> wrote:
>
> Check this too https://github.com/code-ready/crc/
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by AkihiroSuda** [comment]
> Minishift is 3.x only and will never support installing 4.x based
OpenShift clusters. As mentioned before, the solution you are looking
for is called CRC.

Any chance to add this to README.md for clarity?

**Comment by praveenkumar** [comment]
> Any chance to add this to README.md for clarity?

Yes we will add it to README soon.
