### ISSUE TITLE
Cluster fails to start, "timed out waiting for the condition"

### ISSUE THREAD

**Issue by rgov** [minishift/minishift#3268]
### General information

  * Minishift version: minishift v1.33.0+ba29431
  * OS: macOS 11.14.4
  * Hypervisor: xhyve and hyperkit

### Steps to reproduce

`minishift start`

### Expected

An OpenShift cluster is created and I can connect to it.

### Actual

Startup takes a very long time, eventually failing with this message:

```
I0515 04:13:08.415680    4160 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: timed out waiting for the condition
```

This has happened repeatedly, but I have successfully run Minishift on another Mac in a very similar configuration.

### Logs

[minishift.log](https://github.com/minishift/minishift/files/3180873/minishift.log)

**Comment by gbraad** [comment]
Do these machines have the same specifications, like memory and CPU?

**Comment by rgov** [comment]
Indeed the machine that was failing has a slower CPU (half as many cores), about ~2 years old and not a low-end laptop to begin with. However, I'll try again with some resources freed up.
