### ISSUE TITLE
Unable to install Minishift with the latest version of docker-machine-driver-xhyve

### ISSUE THREAD

**Issue by camilamacedo86** [minishift/minishift#3271]
### General information

3 days ago was release a new version see: https://github.com/machine-drivers/docker-machine-driver-xhyve/releases/tag/v0.4.0.

Then, is no longer possible to install the Minishift following the docs.  

  * Minishift version: 
  * OS: macOS
  * Hypervisor: xhyve 

### Steps to reproduce
Following the [Minishift doc](https://docs.okd.io/latest/minishift/getting-started/installing.html) to install Minishift with this drive.

  1. brew install docker-machine-driver-xhyve
  2. brew cask install minishift
  3. minishift start

### Expected
Work well was it works for the previous version `v0.3.0`

### Actual

```shell
$ minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .... FAIL E0519 18:30:25.411015   28125 start.go:494] Error starting the VM: Error creating new host: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string. Retrying.
Error starting the VM: Error creating new host: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string
camilamacedo@Camilas-MacBook-Pro ~ $ brew uninstall docker-machine-driver-xhyve
Uninstalling /usr/local/Cellar/docker-machine-driver-xhyve/0.4.0... (6 files, 9.9MB)
```

**Comment by jordancodeshub** [comment]
Same issue with this version. I have MacOS 10.14.5 and minishift v1.33.0+ba29431:

minishift start --memory=2GB                                                                                                                        

-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .... FAIL E0522 00:54:05.188126    5065 start.go:494] Error starting the VM: Error creating new host: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string. Retrying.
Error starting the VM: Error creating new host: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string

**Comment by camilamacedo86** [comment]
Following how I solved it. 

1. Uninstall all and delete all config files 
- minishift delete
- brew uninstall docker-machine-driver-xhyve
- rm -rf <docker-machine-driver-xhyve paths> (E.g /usr/local/bin/docker-machine-driver-xhyve)
- rm -rf  config files .docker .kube .minishift .minikube
- remove docker
- ensure that you have not other drive installed as virtualbox and/or hyper

2. Install  docker-machine-driver-xhyve using the version 0.3.1

```
$ curl -L https://github.com/zchee/docker-machine-driver-xhyve/releases/download/v0.3.1/docker-machine-driver-xhyve > /usr/local/bin/docker-machine-driver-xhyve
$ chmod +x /usr/local/bin/docker-machine-driver-xhyve
$ sudo chown root:wheel /usr/local/bin/docker-machine-driver-xhyve
$ sudo chmod u+s /usr/local/bin/docker-machine-driver-xhyve
```
  
3. Download and install Minishift 
- `$ brew cask install --force minishift` - Use --force to ensure that the images will be re-downloaded 

4. Start your minshift with `minishift start`

**Comment by MoSehsah** [comment]
@camilamacedo86 I suggest that you can replace v0.3.1 with v0.3.3 , it'll continue to work

**Comment by popsonebz** [comment]
i'm also having the same issue. i have to use @camilamacedo86 method. still testing.

**Comment by kareemjeiroudi** [comment]
Following the steps of @camilamacedo86 I've been able to work around the problem.

**Comment by hugocueva** [comment]
camilamacedo86  comment did solve my issue as well

**Comment by frankper** [comment]
@camilamacedo86  Thank you so much !

**Comment by suulperi** [comment]
This issue still exists. Will there be support for version 0.4.0 ?

**Comment by laurent-martin** [comment]
instead of using xhyve, I used hyperkit amd started minishift with:
minishift start --vm-driver=hyperkit

**Comment by bsunders** [comment]
I followed @camilamacedo86 but then got : 
Starting Minishift VM ..... FAIL E0912 10:07:13.211323   35488 start.go:494] Error starting the VM: Error creating the VM. Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.4r128413\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads". Retrying.
Error starting the VM: Error creating the VM. Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.4r128413\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads"

So I'm updating VirtualBox..

Jeez this install is full of traps . ...

**Comment by seanow** [comment]
> 2\. Install  docker-machine-driver-xhyve using the version 0.3.1

This step @camilamacedo86 mentioned solve my case

**Comment by ralgozino** [comment]
Same problem here, neither of the `brew` versions of `xhyve` and `hyperkit` worked for me. 

With `xhyve` I got:
```shell
Error starting the VM: Error creating new host: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string
```

and with `hyperkit`
```shell
Error starting the VM: Error starting stopped host: starting with cmd line: : Kernel /Users/xxxx/.minishift/machines/minishift/bzimage does not exist
```

I'm using the latest Docker Desktop for MacOS:
Engine: 19.03.2
Machine: 0.16.2

Based on the @camilamacedo86 's workaround I got minishift to start doing the following steps:
```shell
minishift delete
> run step 3 of @camilamacedo86's workaround
minishift start --vm-driver=xhyve
```

**Comment by Lone1567** [comment]
Just verified @ralgozino's suggestion and I can successfully start my minishift VM. Thanks!

**Comment by tomdwp** [comment]
Here's what worked for me when started getting this error:
`(...other stuff...)
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .... FAIL E1019 13:41:41.471159    8532 start.go:494] Error starting the VM: Error creating new host: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string. Retrying.
Error starting the VM: Error creating new host: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string`

I didn't need to uninstall Docker Desktop for Mac.

I just ran the following on MacOS Catalina:
`minishift delete
brew uninstall minishift
rm -rf ~/.minishift

brew uninstall docker-machine-driver-xhyve

#NOTE the most recent 0.3.x version xhyve is 0.3.3
curl -L https://github.com/zchee/docker-machine-driver-xhyve/releases/download/v0.3.3/docker-machine-driver-xhyve > /usr/local/bin/docker-machine-driver-xhyve

chmod +x /usr/local/bin/docker-machine-driver-xhyve

sudo chown root:wheel /usr/local/bin/docker-machine-driver-xhyve
sudo chmod u+s /usr/local/bin/docker-machine-driver-xhyve

brew cask install --force minishift`

after that then running `minishift start` worked without error.

**Comment by xjtustt** [comment]
> I followed @camilamacedo86 but then got :
> Starting Minishift VM ..... FAIL E0912 10:07:13.211323 35488 start.go:494] Error starting the VM: Error creating the VM. Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.4r128413\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads". Retrying.
> Error starting the VM: Error creating the VM. Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.4r128413\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads"
> 
> So I'm updating VirtualBox..
> 
> Jeez this install is full of traps . ...

Also encountered this problem, but this problem is disappeared after I install virtualBox 5.2.
Hope this is helpful for you.

**Comment by codepedia** [comment]
What worked for me, is using virtula box as  as the --vm-driver. 


$ minishift start --vm-driver=virtualbox

**Comment by sanjeevkumarrao** [comment]
> What worked for me, is using virtula box as as the --vm-driver.
> 
> $ minishift start --vm-driver=virtualbox

This solved my issue! Thanks!
