### ISSUE TITLE
Unable to connect to the server: x509: cannot validate certificate for 192.168.64.2 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by anmolbabu** [minishift/minishift#3272]
### General information

 * Minishift version: v1.33.0+ba29431
 * OS: Linux / macOS / Windows: macOS
 * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox / hyperkit: VirtualBox

### Steps to reproduce

 1. Install minishift using brew - brew cask install minishift
 2. To update the binary, run following command: brew cask install --force minishift
 3. Run the minishift start command: minishift start
 4. Run this command to configure your shell:  eval $(minishift oc-env)
 5. Run any oc command: oc status

### Expected
1) Access the minishift web console using https:<<minishift ip>>:8443/console on chrome
2) oc command should be successful

### Actual
1)  I am able to access the minishift web console using https:<<minishift ip>>:8443/console on chrome,though I get not secured and invalid certificate error , but still page loads.
2) when I tried to access through terminal, I get follwing error. " C02Y80M2JG5J:~ sharinar$ oc get users
Unable to connect to the server: x509: cannot validate certificate for 192.168.64.2 because it doesn't contain any IP SANs "

Please see the errors I am getting for other oc commands.
C02Y80M2JG5J:certs sharinar$ oc login $(minishift ip):8443 -u admin -p admin
The server is using a certificate that does not match its hostname: x509: cannot validate certificate for 192.168.99.100 because it doesn't contain any IP SANs
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

error: couldn't get https://192.168.99.100:8443/.well-known/oauth-authorization-server: unexpected response status 403
C02Y80M2JG5J:certs sharinar$
C02Y80M2JG5J:certs sharinar$ oc login $(minishift ip):8443 --insecure-skip-tls-verify=true
error: couldn't get https://192.168.99.100:8443/.well-known/oauth-authorization-server: unexpected response status 403

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by anmolbabu** [comment]
Cc: @shashikanthah

**Comment by anmolbabu** [comment]
ping @anjannath @praveenkumar @amitkrout 

Please feel free to route this through appropriate channels

**Comment by gbraad** [comment]
The certificate for Minishift will always be self-signed and therefore some
tools might complain about it is 'insecure'.
Not sure where the 'IP SAN' error comes from...

Likely the issue lies with you getting a `403`. Did you have to enter any
credentials or that response was returned?
Have you checked if you might have previous login information in your
kubeconfig?

**Comment by anmolbabu** [comment]
> The certificate for Minishift will always be self-signed and therefore some tools might complain about it is 'insecure'. Not sure where the 'IP SAN' error comes from... Likely the issue lies with you getting a `403`. Did you have to enter any credentials or that response was returned? Have you checked if you might have previous login information in your kubeconfig?

Hi @gbraad 

> Did you have to enter any credentials or that response was returned?

No the credentials were not asked for. The error was just returned

> Have you checked if you might have previous login information in your
kubeconfig?

After hitting this error we did :
1. `minishift delete`
2. `rm -fr ~/.minishift`
3. `rm -fr ~/.kube/config`
4. `minishift start`
5. `eval $(minishift oc-env)`
6. `oc status`

And the error still persists.
@shashikanthah can you please confirm

**Comment by gbraad** [comment]
Note: please do not at-reply people that aren't part of the discussion, such as former project members. Or if your colleagues, make sure they are actually correctly typed, as the reply you added does not exist.

**Comment by shashikantha** [comment]
Yes, the credentials were never asked, the error just came over.

**Comment by thezhili** [comment]
bump
