### ISSUE TITLE
Minishift becomes inoperable if a pod uses a lot of resources

### ISSUE THREAD

**Issue by mmorhun** [minishift/minishift#3274]
### General information

  * Minishift version: v1.34.0+f5db7cb
  * OS: Fedora 29
  * Hypervisor: VirtualBox
  * VM resources: 4 vcpus (of 8 total), 16Gb RAM (of 32 total), 50GB of disk space.

### Steps to reproduce

I have Eclipse Che deployed on minishift and a running workspace in which I do some development. Inside that workspace (pod) I have a container for building Che Theia. The build is very resource consuming and uses all cores by default and high disk IO. 
Sometimes during the build minishift becomes inoperable: API is not responding. Even minishift console doesn't load properly.
![minishift error](https://user-images.githubusercontent.com/15607393/58564858-6d977c80-8236-11e9-9049-776feb14a390.png)
I run into it several times during last two days, but there are no clear steps to reproduce. It just happens sometimes.

### Expected

Everything works: Minishift & my build

### Actual

Minishift is broken from within a pod.

### Notes

When such thing happened a half of VM RAM was free. 
Plenty of disk space are available.

**Comment by mmorhun** [comment]
I think it is still actual

**Comment by gbraad** [comment]
If the poid consumes disk space, it might cause the cluster to lock up. The
same could occur for memory consumption. If the latter, assign more memory
to the VM.

**Comment by mmorhun** [comment]
I do not think the problem is in memory or disk limit. I have a lot of free disk space and ~8 Gb RAM free (out of 16 Gb total).
But this happens on 100% CPU load from pod (all cores available in the VM) and active disk IO (compilation in parallel).

**Comment by mmorhun** [comment]
Still actual...

**Comment by mmorhun** [comment]
The problem is still there

**Comment by mmorhun** [comment]
Not fixed...
