### ISSUE TITLE
Could not set oc CLI context for 'minishift' profile; specified path to the kube config does not exist

### ISSUE THREAD

**Issue by dchucks** [minishift/minishift#3276]
### General information

  * Minishift version: v1.34.0+f5db7cb
  * OS:  Windows 10
  * Hypervisor: VirtualBox 

### Steps to reproduce

I am an OpenShift and minishift newbie and learning OpenShift. Am getting the following error while starting minishift:
`Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to the kube config 'C:\Users\me.myself\.minishift\machines\minishift_kubeconfig' does not exist`

although it seems minishift and oc cluster both are up, and I am able to access the console as well.

```
$ minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Running (openshift v3.11.0+7f5d53b-195)
DiskUsage:  15% of 19G (Mounted On: /mnt/sda1)
CacheUsage: 491.9 MB (used by oc binary, ISO or cached images)
```
But when I try to deploy an app via CLI I get an error:
```
$ oc new-app https://github.com/sclorg/nodejs-ex -l name=myapp
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
```
Unable to deploy anything from console also, (was trying tod eploy a Jenkins pipeline sample app from catalog), getting following error:

```
--> Scaling mongodb-1 to 1
--
  | error: update acceptor rejected mongodb-1: pods for rc 'first-test/mongodb-1' took longer than 600 seconds to become available
```

**Comment by Git-Jiro** [comment]
Hi,
I have the same issue on OSX. Here is my version:

`
Martins_MacBook_Pro:~/development/openshift martin$ ./minishift version
minishift v1.34.0+f5db7cb
Martins_MacBook_Pro:~/development/openshift martin$ ./minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Running (openshift v3.11.0+3a34b96-217)
DiskUsage:  19% of 18G (Mounted On: /mnt/vda1)
CacheUsage: 1.802 GB (used by oc binary, ISO or cached images)
RHSM: 	    Registered
`

**Comment by Git-Jiro** [comment]
Hi, I solved the problem for me the following way:
I delete minishift version 1.34 and installed minishift version 1.33. (this has probably nothing to do with me getting this working)
And I also did this:
`minishift config set openshift-version v3.10.0`
then `minishift delete` and `minishift start`

So, my assumption is this:
Minishift has issues with Openshift version 3.11 and none with Openshift version 3.10

**Comment by dchucks** [comment]
@Git-Jiro When I tried this, got the following:
> -- Checking if requested OpenShift version 'v3.10.0' is valid ... FAIL

**Comment by Git-Jiro** [comment]
Hm.. minishift version 1.34.0 on OSX seems to be happy with v3.10.0

**Comment by jesperperl** [comment]
> Hm.. minishift version 1.34.0 on OSX seems to be happy with v3.10.0 (i upgraded from 1.33.0 to 1.34.0 to verify this)

Same experience here. Downgraded OpenShift to v3.10 from v3.11 (still using minishift v1.33) and no longer getting the oc CLI context error.

**Comment by Fierozen** [comment]
I am still getting this.

**Comment by m2f0** [comment]
Same error here.

**Comment by m2f0** [comment]
Solved here using:
$ minishift delete --force
$ rm -rf ~/.minishift
$ minishift setup-cdk
$ minishift config set vm-driver virtualbox
$ minishift start

**Comment by jerkjoe** [comment]
> Solved here using:
> $ minishift delete --force
> $ rm -rf ~/.minishift
> $ minishift setup-cdk
> $ minishift config set vm-driver virtualbox
> $ minishift start

Problem solved after repeating the steps above.
Thank you!  @m2f0

**Comment by titiag01** [comment]
Thank you @m2f0 this worked for me also. Can you tell me what exactly the problem was, that your solution  was the answer to?  I don't understand the error i had.

**Comment by lmorse** [comment]
I am experiencing the same problem.  I want to do your workaround but this step does not work for me ...
$ minishift setup-cdk
Error: unknown command "setup-cdk" for "minishift"
Run 'minishift --help' for usage.
unknown command "setup-cdk" for "minishift"

Is this possibly a typo?

**Comment by titiag01** [comment]
Hi Imorse:, i'm just a beginner myself but i hope this helps for you. It looks like the command cannot be found so steps below must have been done..........  Maybe you have not edited your PATH variable?

For Microsoft Windows  
1. Download the Red Hat Container Development Kit 3 for Windows from  https://developers.redhat.com/products/cdk/overview​.  
2. Rename the downloaded file to ​minishift.exe​. Copy the ​minishift.exe​ file to a suitable  folder on your system and ensure the path does not have any spaces (for example, create  a folder called ​“minishift” ​under the ​C:\​ drive and copy the ​minishift.exe​ binary to this  location).  
3. **Edit your ​PATH​ environment variable and add the folder created in the previous step to  it. This will ensure that the ​minishift.exe​ is available in the system path, and can be  invoked from the command line terminal.**   
4. Open a Powershell window.  
5. Execute the following commands in the Powershell window:     
minishift setup-cdk  
minishift config set vm-driver virtualbox    
The ​minishift config​ command may issue a warning message, "No Minishift instance exists…".  This message can safely be ignored.

**Comment by lmorse** [comment]
HI titiag01, Thanks for your response.  I actually recreated this on MacOS.  I downloaded the CDK for Mac and installed it.  I can now run "minishift setup-cdk", but I am still seeing the same thing.  I did have to workaround 
$ minishift version
minishift v1.34.1+21103616
CDK v3.10.0-1
$ rm -rf ~/.minishift
$ minishift setup-cdk
$ minishift config set vm-driver virtualbox
$ minishift start
I get an error here validating certificates for host IP so I workaround with this ...
$ minishift stop
$ minishift ip --set-static
$ minishift start
.
.
.
I1120 00:32:06.041806    2841 interface.go:41] Finished installing "sample-templates/postgresql" "sample-templates/cakephp quickstart" "sample-templates/django quickstart" "sample-templates/rails quickstart" "sample-templates/jenkins pipeline ephemeral" "sample-templates/mysql" "sample-templates/mariadb" "sample-templates/dancer quickstart" "sample-templates/nodejs quickstart" "sample-templates/sample pipeline" "sample-templates/mongodb"
I1120 00:33:10.362373    2841 interface.go:41] Finished installing "openshift-web-console-operator" "openshift-image-registry" "persistent-volumes" "openshift-router" "sample-templates" "rhel-imagestreams"
Login to server ...
Creating initial project "myproject" ...
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.125:8443/console

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin


Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to the kube config '/Users/lmorse/.minishift/machines/minishift_kubeconfig' does not exist

**Comment by titiag01** [comment]
Hi Laurie,

I used the attached document for setting up my environment on windows but there are also instructions for mac and linux as well. Maybe it can help you?

It still looks like your path is wrong, maybe you can take a look at that first.

 

C:\Users\titia\.minishift\machines>dir

Volume in drive C is OS

Volume Serial Number is F0CB-C00A

 

Directory of C:\Users\titia\.minishift\machines

 

10/11/2019  21:10    <DIR>          .

10/11/2019  21:10    <DIR>          ..

20/11/2019  10:02    <DIR>          minishift

20/11/2019  10:03               300 minishift-state.json

10/11/2019  21:10             5.711 minishift_kubeconfig

20/11/2019  10:02             1.679 server-key.pem

20/11/2019  10:02             1.107 server.pem

               4 File(s)          8.797 bytes

               3 Dir(s)  153.710.198.784 bytes free

 

C:\Users\titia\.minishift\machines>path

PATH=C:\Users\titia\.minishift\cache\oc\v3.11.141\windows;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\ibm\gsk8\lib64;C:\Program Files (x86)\ibm\gsk8\lib;C:\PROGRA~1\IBM\SQLLIB~1\BIN;C:\PROGRA~1\IBM\SQLLIB~1\FUNCTION;C:\PROGRA~1\IBM\SQLLIB~1\SAMPLES\REPL;C:\Program Files\PuTTY\;C:\Users\titia\AppData\Local\Microsoft\WindowsApps;C:\Users\titia\bin;C:\.minishift;

 

 

With kind regards/Met vriendelijke groet,

 

Titia P.M. Gerritzen

 

 

Van: Laurie Morse <notifications@github.com> 
Verzonden: Wednesday, 20 November 2019 01:53
Aan: minishift/minishift <minishift@noreply.github.com>
CC: titiag01 <titiagerritzen@gmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [minishift/minishift] Could not set oc CLI context for 'minishift' profile; specified path to the kube config does not exist (#3276)

 

HI titiag01, Thanks for your response. I actually recreated this on MacOS. I downloaded the CDK for Mac and installed it. I can now run "minishift setup-cdk", but I am still seeing the same thing. I did have to workaround
$ minishift version
minishift v1.34.1+21103616
CDK v3.10.0-1
$ rm -rf ~/.minishift
$ minishift setup-cdk
$ minishift config set vm-driver virtualbox
$ minishift start
I get an error here validating certificates for host IP so I workaround with this ...
$ minishift stop
$ minishift ip --set-static
$ minishift start
.
.
.
I1120 00:32:06.041806 2841 interface.go:41] Finished installing "sample-templates/postgresql" "sample-templates/cakephp quickstart" "sample-templates/django quickstart" "sample-templates/rails quickstart" "sample-templates/jenkins pipeline ephemeral" "sample-templates/mysql" "sample-templates/mariadb" "sample-templates/dancer quickstart" "sample-templates/nodejs quickstart" "sample-templates/sample pipeline" "sample-templates/mongodb"
I1120 00:33:10.362373 2841 interface.go:41] Finished installing "openshift-web-console-operator" "openshift-image-registry" "persistent-volumes" "openshift-router" "sample-templates" "rhel-imagestreams"
Login to server ...
Creating initial project "myproject" ...
Server Information ...
OpenShift server started.

The server is accessible via web console at:
https://192.168.99.125:8443/console

You are logged in as:
User: developer
Password: 

To login as administrator:
oc login -u system:admin

Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to the kube config '/Users/lmorse/.minishift/machines/minishift_kubeconfig' does not exist

**Comment by lmorse** [comment]
Is it just the minishift executable that needs to be in the path?  I see you have these in your path ...
C:\Users\titia\.minishift\cache\oc\v3.11.141
C:\.minishift

I don't see the file /Users/lmorse/.minishift/machines/minishift_kubeconfig

Do you think my path should include the .minishift directory?

Here is my path ...
Lauries-MBP:~ lmorse$ pwd
/Users/lmorse
Lauries-MBP:~ lmorse$ echo $PATH
/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/lmorse/Desktop/My_Stuff_Mac/Downloads/Maven/apache-maven-3.5.0/bin:.:/Users/lmorse/Desktop/My_Stuff_Mac/Downloads/Zookeeper/zookeeper/zkadmin/tools/bin:/usr/local/bin/mongodb/bin:/usr/local/packer:/usr/local/go/bin:/Users/lmorse/Desktop/My_Stuff_Mac/GoProjects/gocode/bin:/opt/gradle/gradle-4.6/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/lib
Lauries-MBP:~ lmorse$ ls -al /Users/lmorse/.minishift/machines
total 24
drwxr-xr-x   6 lmorse  staff   192 Nov 19 15:37 .
drwxr-xr-x  14 lmorse  staff   448 Nov 19 15:37 ..
drwx------   8 lmorse  staff   256 Nov 19 17:44 minishift
-rw-r--r--   1 lmorse  staff   283 Nov 19 18:30 minishift-state.json
-rw-------   1 lmorse  staff  1679 Nov 19 17:44 server-key.pem
-rw-r--r--   1 lmorse  staff  1111 Nov 19 17:44 server.pem

**Comment by titiag01** [comment]
Yes, i’m sure your path should include .minishift. 
It’s described as one the steps for building an environment in the attachement from my previous note as well.

Good luck! 

Kind regards, Titia.

**Comment by 1154046** [comment]
> 
> 
> Hi, I solved the problem for me the following way:
> I delete minishift version 1.34 and installed minishift version 1.33. (this has probably nothing to do with me getting this working)
> And I also did this:
> `minishift config set openshift-version v3.10.0`
> then `minishift delete` and `minishift start`
> 
> So, my assumption is this:
> Minishift has issues with Openshift version 3.11 and none with Openshift version 3.10

wanted to fix CLI issue, ended up not being able to run start minishift altogether. How do you undo this ? :( :'(

**Comment by Roymprog** [comment]
For me(running Ubuntu 18.04) this was caused by an old interfering installation of (mini)kube, as described in https://github.com/minishift/minishift/issues/3023. Hence, I had configuration stored in ~/.kube and ~/.minikube. After removing both folders, removing the ~/.minishift folder and restarting the minishift cluster, all ran as expected.

**Comment by AmanM13** [comment]
> Hi, I solved the problem for me the following way:
> I delete minishift version 1.34 and installed minishift version 1.33. (this has probably nothing to do with me getting this working)
> And I also did this:
> `minishift config set openshift-version v3.10.0`
> then `minishift delete` and `minishift start`
> 
> So, my assumption is this:
> Minishift has issues with Openshift version 3.11 and none with Openshift version 3.10

Could you please tell me how can I downgrade or remove Openshift 3.11 and switch to 3.10?

**Comment by AmanM13** [comment]
> `minishift config set openshift-version v3.10.0`

got it :)

**Comment by AmanM13** [comment]
Still oc cluster up and error timeout issue isn't solved :")

**Comment by akhilfrancischirayath** [comment]
Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to the kube config 'C:\Users\username\.minishift\machines\minishift_kubeconfig' does not exist

**Comment by ramkunwarmeghwal** [comment]
copy  `minishift_kubeconfig` file from /.minishift/machines folder to desired folder(in error asked, generally location is ~/.minishift)
also rename as `config` if in error is related config folder invalid function
