### ISSUE TITLE
Documentation links in README.rst leads to 404

### ISSUE THREAD

**Issue by ricco386** [minishift/minishift#3277]
### General information

Documentation at https://docs.okd.io/ seems to be missing whole minishift section.

I have tried to open the latest documentation on the website and search for minishift and all the results are leading to 404s.

### Steps to reproduce

  1. Click on link Getting started with Minishift
  2. Click on link Using Minishift
  3. Click on link Developing and contributing to Minishift
  4. Click on link Command Reference

### Expected

I would see the documentation in the browser and see the information what to do once I would like to start using minishift.

### Actual

Browser shows 404 error

**Comment by dchucks** [comment]
This seem to be a very recent event, as I was able to access the links till few hours ago, suddenly all of them went missing.

**Comment by kelleyblackmore** [comment]
Seems to be anything related to minishift? most google searches come up with 404 errors

**Comment by dchucks** [comment]
Looks like its fixed now, documentation is back online at https://docs.okd.io/latest/minishift

**Comment by ricco386** [comment]
Looks good, closing the issue.
Thanks.

**Comment by MrException** [comment]
This appears to be happening again. Have been unable to access the documentation all day. @dchucks
