### ISSUE TITLE
Upgrade iso image / docker daemon to a more current version

### ISSUE THREAD

**Issue by wstrange** [minishift/minishift#3278]
### General information

  * Minishift version:  minishift v1.34.0+f5db7cb

Trying to run `skaffold` and building the docker image fails because the docker daemon on the ISO image is too old (1.13.1). The command that fails is `COPY --chmod`

minikube uses docker 18.09.6 - which works OK with this command.

**Comment by t-hart** [comment]
I'd like to add that this also seems to break multi-stage docker files, which were introduced in Docker 17.05. 

This is currently causing some headaches as the team I'm on is working on trying to create a dev environment similar to prod, but with Minishift not supporting multi-stage builds, everything would have to be rewritten.

**Comment by DizzyThermal** [comment]
Running into the same issue - unable to build multi-stage docker files (i.e., nexus-repository-conan)

**Comment by t-hart** [comment]
I wonder if there's an easy way to fix this? Superficially, it sounds like a simple thing to update the Docker version, but I'm sure there's some hidden complications somewhere. 

In my case, we ended up exploring the creation of single-stage builds, and while it's not perfect, it's not as much hassle as we had thought, so it'll work for now. That said, though, we only have a small number of containers to do this for and can do it in an incremental fashion.

While the new [Code Ready Containers](https://github.com/code-ready/crc) will probably fix this, there doesn't seem to be any estimation for when they'll be ready. Further, for anyone stuck on version 3.x, it might not be appropriate; so it really would be useful to update this.

**Comment by akosma** [comment]
This issue is still relevant and a major headache.

**Comment by malcolm061990** [comment]
Why was this ticket closed?
