### ISSUE TITLE
Error starting the VM on macos  xhyve

### ISSUE THREAD

**Issue by jainmnsh** [minishift/minishift#3279]
### General information

  * Minishift version: v1.33.0+ba29431
  * OS: macOS 
  * Hypervisor:  xhyve 

### Steps to reproduce
The minishift start is not working on macos

### Expected

Minishift should start.

### Actual
failure

### Logs
 ~/ minishift start --v 5                 
-- minishift version: v1.33.0+ba29431
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.11.0'
 53.27 MiB / 53.27 MiB [============================================================================================================================================================================================] 100.00% 0s-- Downloading OpenShift v3.11.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.15.0/minishift-centos7.iso'
 355.00 MiB / 355.00 MiB [==========================================================================================================================================================================================] 100.00% 0s
-- Starting Minishift VM .... FAIL E0606 15:41:24.144140    6352 start.go:494] Error starting the VM: Error creating new host: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string. Retrying.
Error starting the VM: Error creating new host: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string

**Comment by souhaiebtar** [comment]
@jainmnsh it seem that there is a regression with version 0.40 of docker xhyve plugin, 
temporary workaround:
1. remove latest version of docker-machine-driver-xhyve and install older version
```SHELL
brew unlink docker-machine-driver-xhyve
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/7310c563d662ddbe094f46f9600cad30ad3551a6/Formula/docker-machine-driver-xhyve.rb
```
2. remove virtualbox and install a virtualbox version 5.\*.\* ( for me i installed version 5.2.22,126460)
```SHELL
brew cask uninstall virtualbox
brew cask install https://raw.githubusercontent.com/Homebrew/homebrew-cask/eabf6ef195fcc22b08c4260b7d16b466bfdc2e7d/Casks/virtualbox.rb
```

now it should work

**Comment by t-hart** [comment]
Just wanted to say that I ran into issues with this as well, and that using an older version of xhyve and virtualbox didn't work (maybe I messed it up). Anyway, what I found is that you can use hyperkit, as mentioned in [this issue](https://github.com/minishift/minishift/issues/3128):

```sh
  brew install docker-machine-driver-hyperkit hyperkit
```
(I'm not actually sure whether you need both of those packages, or just the one, but this works).

```sh
     minishift start --vm-driver hyperkit
```

**Comment by souhaiebtar** [comment]
@t-hart thanks, recently i was testing minikube and it seem that xhyve is deprecated, hyperkit is used instead

**Comment by geerlingguy** [comment]
I can confirm that the installation directions in the docs (installing `xhyve`) results in a plethora of errors and misdirection. Installing hyperkit and using it as the `--vm-driver` solved all the issues I was having.

Maybe we need to switch to a docs issue: change documentation (and defaults?) to use `hyperkit` instead of `xhyve`.

**Comment by jainmnsh** [comment]
thanks all, I was able to run mini shift by specifying the vm-driver VirtualBox so my command is
minishift start  --vm-driver virtualbox

**Comment by fxgx99** [comment]
I am having a similar issue. For a while I used minishift without a problem, but as various recent updates that I can't keep up with with I am unfortunately unable to even create a host. This is happening both on RHEL 7 and on my mac. Below is the error message I am getting on a RHEL machine: 
`-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ...
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ........ FAIL E1202 12:25:19.831780   16377 start.go:494] Error starting the VM: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s. Retrying.
Error starting the VM: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
[chrisrhel@rhel ~]$`

I read that the compatibility between certain docker drivers and minishift can also be a factor. But I am totally lost in this case. I am posting my mac configuration as well as the error message I am getting on the Mac: 
`Docker : 
Docker version 2.1.0.5(40693)
engine: 19.03.5
compose: 1.34.1
Kubernetes: v1.14.8

Minishift: minishift v1.34.1+c2ff9cb
Minishift start error message: minishift start                                                                                                                                                                       12:23:53
-- Starting profile 'minishift'
json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string`
