### ISSUE TITLE
Error checking and/or regenerating the  certs: There was an error validating certificates for host "192.168.99.113:2376": dial tcp 192.168.99.113:2376: i/o time out

### ISSUE THREAD

**Issue by tko85** [minishift/minishift#3282]
### General information

  * Minishift version: v3.11.82
  * OS: macOS 10.14.5
  * Hypervisor: VirtualBox

I have been unable to successfully install RedHat CDK on my Mac.  I keep receiving a "Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.112:2376": dial tcp 192.168.99.112:2376: i/o timeout" error message.

I have repeatedly tried minishift delete and then minishift start.  I have removed the .ministart folder and all contents and started from scratch multiple times.  I have restarted my Mac.   Nothing is working. 

### Steps to reproduce

  1. minishift setup-cdk
  2. minishift config set vm-driver virtualbox
  3. minishift start
  4. 

### Expected
Successful creation of Minishift VM

### Actual
Tims-MacBook-Pro-8:bin tko$ minishift setup-cdk --force
Setting up CDK 3 on host using '/Users/tko/.minishift' as Minishift's home directory
Copying minishift-rhel7.iso to '/Users/tko/.minishift/cache/iso/minishift-rhel7.iso'
Copying oc to '/Users/tko/.minishift/cache/oc/v3.11.82/darwin/oc'
Creating configuration file '/Users/tko/.minishift/config/config.json'
Creating marker file '/Users/tko/.minishift/cdk'
Default add-ons anyuid, admin-user, xpaas, registry-route, che, htpasswd-identity-provider, eap-cd installed
Default add-ons anyuid, admin-user, xpaas enabled
CDK 3 setup complete.
Tims-MacBook-Pro-8:bin tko$ minishift config set vm-driver virtualbox
No Minishift instance exists. New 'vm-driver' setting will be applied on next 'minishift start'

Tims-MacBook-Pro-8:bin tko$ minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://mirror.openshift.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.82' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.82' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .................................. FAIL E0611 14:39:25.415164    8017 start.go:494] Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.112:2376": dial tcp 192.168.99.112:2376: i/o time
out You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.
. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.112:2376": dial tcp 192.168.99.112:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
Are you behind the VPN by any chance also on the Mac better to use the hyperkit driver?

**Comment by tko85** [comment]
I disconnected my VPN and still had problem.
I uninstalled VirtualBox and installed xhyve hypervisor and restarted machine.
Now I get this:
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://mirror.openshift.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.82' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.82' is supported ... OK

-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ..... FAIL E0613 11:07:17.224869    1738 start.go:494] Error starting the VM: Error creating the
 VM. Error with pre-create check: "Error detecting VBox version: exit status 126".

**Comment by tko85** [comment]
Because of the VBox error message, I re-installed VirtualBox (I'm assuming VBox means VirtualBox).  Now I get this message:
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://mirror.openshift.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.82' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.82' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...

   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ..... FAIL E0613 11:27:36.854097   26513 start.go:494] Error starting the VM: Error creating the
 VM. Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are
 running version: 6.0.8r130520\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads".

**Comment by praveenkumar** [comment]
@tko85 this is known for xhyve side better to use hyperkit or downgrade the VB to 5.x
