### ISSUE TITLE
Minishift installed on Azure VM. minishift console is not accessible from browser

### ISSUE THREAD

**Issue by getkavya** [minishift/minishift#3289]
### General information

  * Minishift version:  v1.34
* OS: Linux / macOS / Windows:- Ubuntu 18.04 LTS inside Azure cloud
* Hypervisor: KVM / xhyve / Hyper-V / VirtualBox / hyperkit :-  KVM

Minishift console is not displaying in browser
I have installed minishift on Azure VM. To access minishift console from browser, I have done port forwarding with following commands.

### Steps to reproduce

1. minishift start 
2. firewall-cmd --add-masquerade --permanent 
2. firewall-cmd --permanent --add-forward-port=port=8443:proto=tcp:toport=8443:toaddr=192.168.42.90 
3. firewall-cmd --reload
Azure VM public address is :- 23.99.65.77 
minishift VM address :- 192.168.42.90
If i am accessing it through curl command from other machine, I am getting response html page from below command 
 curl -k https://23.99.65.77:8443/console/catalog 
If I am accessing it from browser(Chrome), I am not getting minishift console. Console is loading and after that getting below error of Oauth.

https://192.168.42.90:8443/oauth/authorize?client_id=openshift-web-console&response_type=code&state=eyJ0aGVuIjoiLyIsIm5vbmNlIjoiMTU2MDMzODcyMjUxNS0xODU5OTIzNjQyNDQ3OTczNjQ0MTExNzU0MDM4MDI2NzUxMjkyNDgxMTcxNzc2MTMxMzc5NDAwMzEwNDYwMTE2OTM1OTM5NzE5MTY5In0&redirect_uri=https%3A%2F%2F192.168.42.90%3A8443%2Fconsole%2Foauth is unreachable.
ERR_ADDRESS_UNREACHABLE

  

### Expected

Openshift console should be accessible from browser outside azure cloud.

### Actual

Openshit console is not accessible

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by getkavya** [comment]
Any help on above issue

**Comment by Azadehkhojandi** [comment]
any update on this issue?

**Comment by radvym** [comment]
any updates please?
