### ISSUE TITLE
Error When Creating VM Centos7 GCP

### ISSUE THREAD

**Issue by faizakbar18** [minishift/minishift#3291]
### General information

  * Minishift version: minishift-1.34.0
  * OS: Centos 7
  * Hypervisor: KVM

### About
 i Used Cloud Machine from GCP (google Cloud Platform), i was try ubuntu and centos version but still have same problem

### Logs
This is the [Log](https://gist.github.com/faizakbar18/b914492c6357ec8c979d37ad9ef4fedc)

**Comment by jdoss** [comment]
You need to make sure you have nested virtualization enabled on your instance for this to work:

https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances

It still might not work fully.

**Comment by gbraad** [comment]
as mentioned by @jdoss you either need nested virtualization.... OR

,,, have you tried to use the `generic` driver? See https://docs.okd.io/latest/minishift/using/run-against-an-existing-machine.html

**Comment by gbraad** [comment]
> i was try ubuntu and centos version but still have same problem

can you explain what you have tried?

**Comment by faizakbar18** [comment]
> You need to make sure you have nested virtualization enabled on your instance for this to work:
> 
> https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances
> 
> It still might not work fully.

this tutorial truly work, but minishift run to local ip address, how to make it run on public ip ?
