### ISSUE TITLE
Minishift uses 65% of my CPU

### ISSUE THREAD

**Issue by KurtStam** [minishift/minishift#3295]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox / hyperkit

### Steps to reproduce

  1. Install XHyve and Minishift

After install the CPU goes down to 65% and stays there. My machine starts to warm up and it eats my battery.

### Expected
A system at rest should not be using this much CPU. Maybe 5% in rest would be acceptable.

### Actual
Using 65%

This is normal? In comparison Minikube uses 25%. Still high, but lower. Just to be clear, no apps are installed.

**Comment by gbraad** [comment]
This is because you are running a full OpenShift cluster which uses many background tasks to keep state of the cluster in order, like creating and maintaining containers/pods

**Comment by KurtStam** [comment]
It's been 2 days and I'm still waiting for it to settle down :(. Anyway I will open an issue with OpenShift as I think this is unacceptable behavior for a system that is at rest.

**Comment by gbraad** [comment]
Thanks ... let's keep an eye on this.
