### ISSUE TITLE
Getting started documentation shows error 404 - I don´t know how to start

### ISSUE THREAD

**Issue by PKrause79** [minishift/minishift#3297]
### General information

I want to try Minishift, but I don´t know how, because there is no getting started documentation available. 

### Steps to reproduce

go directly to https://docs.okd.io/latest/minishift/getting-started/index.html and see that there is a error shown. Also all other links pointing to this page are showing the same results. 

### Expected
no error, instead showing getting started documentation

### Actual
404 Not found
"Sorry, but the page you were trying to view does not exist.
It looks like this was the result of either:
a mistyped address
an out-of-date link"

**Comment by gbraad** [comment]
we are looking into this

**Comment by gbraad** [comment]
Temporaily you can use the source of the documents to look for the info you need: https://github.com/minishift/minishift/tree/master/docs/source

**Comment by anjannath** [comment]
The Docs page is online again: https://docs.okd.io/latest/minishift/getting-started/index.html :tada:

**Comment by PKrause79** [comment]
Great, thx!

**Comment by Jaffar-Vali** [comment]
The URL is not working again.
