### ISSUE TITLE
Compile release notes

### ISSUE THREAD

**Issue by thatdocslady** [minishift/minishift#330]
Typically release notes include:

- List of main features (i.e. what's good)
- Super-quick-start with links to install and setup
- Known issues (with/without links to GitHub issue numbers), with the format problem/workaround (if workaround exists). 

The release note file will be added to the /docs/ folder so that it can be published to html and uploaded to openshift docs site.

I suggest we write in the comments of this issue links or descriptions of known issues so that closer to the actual release date we can compile the list and break it down, depending on how many issues we decide to include and which components/stages they belong to.

**Comment by hferentschik** [comment]
I think it makes more sense to add the same content we send in the email release announcements to the GitHub release page. We already generate release notes as part of a release page - https://github.com/minishift/minishift/releases/tag/v1.0.0-beta.2. What's needed is to add few lines of summary.

**Comment by hferentschik** [comment]
Here is for example the release announcement of beta2:

> We are happy to announce the second Minishift beta release - Minishift 1.0.0-beta.2 [1].
> 
> While the previous release focused on the initial switch to ‘oc cluster up’ for provisioning, we worked hard in this > beta.2 release fixing some of the issues this switch introduced.
> Most importantly, we broke persistence of the OpenShift configuration. This meant each time you stopped and then > re-started Minishift, OpenShift got re-provisioned.
> This issue [2] is now resolved. OpenShift configuration will persist until ‘minishift delete’ is called.
> 
> On a side note, if you are using ‘minishift start’ with explicit flags for ‘--iso-url’ and ‘--vm-driver’, you will need > to specify the same parameters on each re-start.
> If parameters don’t match, the virtual machine won’t start. This is a usability issue and we are discussing various > solutions as part of issue #179 [3].
> Feel free to weigh in, if you have a preference for any of the discussed solutions.
> 
> In the meantime, you can set the environment variables MINISHIFT_ISO_URL and MINISHIFT_VM_DRIVER ensuring that the > respective command line flags are set on each call to ‘minishift start’.
> You can read more about environment variables in the documentation [4].
> 
> Two other important issues #206 [5] and #221 [6] affected Windows users. In both cases the intended caching mechanism > failed and is now fixed.
> 
> Last but not least, we disabled any automatic updates of Minishift and its default ISO. Automatic updates have been > broken by Minishift 1.0.0-beta.1 due to the fact that we are now fixed.
> 
> Last but not least, we disabled any automatic updates of Minishift and its default ISO. Automatic updates have been > broken by Minishift 1.0.0-beta.1 due to the fact that we are now
> releasing archive bundles instead of single binaries [7]. This resulted in the creation of issue #204 [8]. Since we in > parallel got various bug reports indicating that the automatic
> update algorithm was causing issues hitting the GitHub API rate limit, we decided for now to completely disable any > automatic updates [9] and rethink the current approach in an upcoming release.
> Please follow the manual installation instructions as provided by the documentation [10] in the meantime.
> 
> If you are interested to use the CentOS based ISO, there is a new release as well - minishift-centos-iso 1.0.0-beta.1 > [11]. You will need to use this ISO if you want to make sure your
> OpenShift configuration is persistent with the CentOS VM.
> 
> Enjoy the new release and please keep the feedback flowing,
> Hardy
> 
> [1] https://github.com/minishift/minishift/releases/tag/v1.0.0-beta.2
> [2] https://github.com/minishift/minishift/issues/210
> [3] https://github.com/minishift/minishift/issues/179
> [4] https://github.com/minishift/minishift/blob/master/docs/using.md#environment-variables
> [5] https://github.com/minishift/minishift/issues/206
> [6] https://github.com/minishift/minishift/issues/221
> [7] https://github.com/minishift/minishift/issues/171
> [8] https://github.com/minishift/minishift/issues/204
> [9] https://github.com/minishift/minishift/issues/246
> [10] https://github.com/minishift/minishift#installing-minishift
> [11] https://github.com/minishift/minishift-centos-iso/releases/tag/v1.0.0-beta.1

**Comment by hferentschik** [comment]
Also, OpenShift themselves refer on https://docs.openshift.org/latest/welcome/index.html to the GitHub release page.

**Comment by LalatenduMohanty** [comment]
+1 to add known issues to the release page e.g. https://github.com/minishift/minishift/releases/tag/v1.0.0-beta.2

**Comment by thatdocslady** [comment]
@hferentschik @LalatenduMohanty if we have infrastructure to document release notes somewhere like this then I'll be happy to support and contribute to it. However, I don't actually see right now in the beta2 release page any content other than the list of commits. How do we add manual content to this page?

Also, the list of commits reflects a list of fixed issues, but I'm mainly thinking how to document known issues (= unresolved), which naturally won't have PRs associated with them. If you look at the OpenShift release notes you'll see that there's manual content there that addresses bugs that weren't fixed yet, etc https://github.com/openshift/origin/releases

**Comment by thatdocslady** [comment]
Aha, interesting development - I noticed that when I click "edit release" I see the text that @hferentschik wrote for the announcement, but in order for it to show up you have to use the URL for the specific release tag like this: https://github.com/minishift/minishift/releases/tag/v1.0.0-beta.3

Does anyone know how to make it so that the release notes will show up for the latest release when you just go to /releases/ root URL?

**Comment by hferentschik** [comment]
@thatdocslady I think we can close this, wdyt? The last view releases followed the same principles and I think this should be sufficient. Also https://github.com/minishift/minishift/releases does show the release note of all releases.

**Comment by thatdocslady** [comment]
The main reason I wanted to have this tracking was so that we remember to list known issues clearly, I don't think we did this up to now because the releases were all beta. Maybe we can rename this issue to "Compile known issues and limitations" or something similar? The rest of the tasks are indeed covered by our regular review process.

**Comment by hferentschik** [comment]
So of we rename it to "Compile known issues and limitation", what would the purpose of the task? If this is supposed to be an issue, what is the actionable thing? If you are talking about some ongoing process thing, then the Mojo might be the place?

**Comment by thatdocslady** [comment]
Not exactly, I mean compile them for the GA release notes, which means it's a one-off task per release. This issue would track things like unresolved bugs that we defer to the next release, but that might create unexpected behavior for the users.

**Comment by hferentschik** [comment]
Given that Minishift 1.0.0, it feels this task is not out of date.
