### ISSUE TITLE
Arch and minishift on libvirt: filesystem layer verification failed for digest

### ISSUE THREAD

**Issue by wyvie** [minishift/minishift#3307]
### General information

  * Minishift version: 1.34.1
  * OS: Arch Linux
  * Hypervisor: KVM

Whenever I try to run minishift on kvm (libvirt), I get the error shown in logs

If i go into the virtual machine with `minishift ssh`, and try to manually `docker pull openshift/origin-control-plane`, I get the same error.
Meanwhile on the host system, and also on the `virtualbox` hypervisor everything works just fine.

### Logs

https://gist.github.com/wyvie/457ebd29c835ab0e72cbfa39cf42a45c

**Comment by wyvie** [comment]
does anybody at least have any idea what i might try or where to look at?
would really like to evade system reinstall again (since it always works for me on other distros)

**Comment by anjannath** [comment]
@wyvie I don't have my Arch linux machine with me RN, but i'll try to reproduce this and report back, in the meanwhile are there any specific changes you made that you want to point out so that i can reproduce this?

**Comment by wyvie** [comment]
@anjannath it's a frest install of Arch. Been using it for about a week so far.
It might be a network issue, indeed, but it's an issue in libvirt in that case, because minishift in virtualbox works just fine, without any issues.
