### ISSUE TITLE
Return of the -u system:admin always asking for a password :-(

### ISSUE THREAD

**Issue by stevef1uk** [minishift/minishift#3309]
### General information

  * Minishift version: minishift v1.34.1+c2ff9cb
  * OS: macOs: Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
  * Hypervisor: VirtualBox ?
oc version: oc v3.11.0+0cbc58b
                    kubernetes v1.11.0+d4cacc0
                   features: Basic-Auth

### Steps to reproduce

  0. rm -rf ~/.kube ~/.minishift ~/openshift.local.clusterup/
  1. minishift start --cpus=7 --memory=12000 —vm-driver=virtualbox  --logtostderr   --addon-env=“apiserver.enable-admission-plugins="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook"
  

### Expected

Normal startup & being able to login with:

oc login https://192.168.64.63:8443 -u system:admin

succeeds

### Actual

OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.63:8443/console

error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: Unable to login to cluster

$oc login https://192.168.64.63:8443 -u system:admin
Authentication required for https://192.168.64.63:8443 (openshift)
Username: system:admin
Password: 

I have tried this more than twice with the same result so I am clearly insane!

### Logs

Stevens-MacBook-Pro-3:codeready-workspaces-operator-installer stevef$ minishift start --cpus=7 --memory=12000 —vm-driver=virtualbox  --logtostderr   --addon-env=“apiserver.enable-admission-plugins="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook"
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'xhyve' hypervisor ...
-- Starting Minishift VM ....I0730 08:11:08.688572   65484 cluster.go:78] Machine exists!
I0730 08:11:08.705863   65484 cluster.go:86] Machine state:  Stopped
............... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 15% used OK
-- Writing current configuration for static assignment of IP address ... OK
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ......................
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.64.63 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0730 07:11:56.642201    4680 flags.go:30] Running "create-kubelet-flags"
I0730 07:11:57.136944    4680 run_kubelet.go:49] Running "start-kubelet"
I0730 07:11:57.405556    4680 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I0730 07:12:13.439893    4680 interface.go:26] Installing "kube-proxy" ...
I0730 07:12:13.439973    4680 interface.go:26] Installing "kube-dns" ...
I0730 07:12:13.439992    4680 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I0730 07:12:13.440019    4680 interface.go:26] Installing "openshift-apiserver" ...
I0730 07:12:13.440064    4680 apply_template.go:81] Installing "kube-proxy"
I0730 07:12:13.440071    4680 apply_template.go:81] Installing "openshift-apiserver"
I0730 07:12:13.440409    4680 apply_template.go:81] Installing "kube-dns"
I0730 07:12:13.440462    4680 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I0730 07:12:45.745144    4680 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
I0730 07:12:45.773938    4680 run_self_hosted.go:242] openshift-apiserver available
I0730 07:12:45.774009    4680 interface.go:26] Installing "openshift-controller-manager" ...
I0730 07:12:45.774070    4680 apply_template.go:81] Installing "openshift-controller-manager"
I0730 07:12:47.350784    4680 interface.go:41] Finished installing "openshift-controller-manager"
Adding default OAuthClient redirect URIs ...
Adding registry ...
Adding router ...
Adding web-console ...
Adding centos-imagestreams ...
Adding sample-templates ...
Adding persistent-volumes ...
I0730 07:12:47.366289    4680 interface.go:26] Installing "openshift-image-registry" ...
I0730 07:12:47.366298    4680 interface.go:26] Installing "openshift-router" ...
I0730 07:12:47.366303    4680 interface.go:26] Installing "openshift-web-console-operator" ...
I0730 07:12:47.366308    4680 interface.go:26] Installing "centos-imagestreams" ...
I0730 07:12:47.366313    4680 interface.go:26] Installing "sample-templates" ...
I0730 07:12:47.366317    4680 interface.go:26] Installing "persistent-volumes" ...
I0730 07:12:47.367075    4680 apply_list.go:67] Installing "centos-imagestreams"
I0730 07:12:47.367245    4680 apply_template.go:81] Installing "openshift-web-console-operator"
I0730 07:12:47.368083    4680 interface.go:26] Installing "sample-templates/mongodb" ...
I0730 07:12:47.368178    4680 interface.go:26] Installing "sample-templates/cakephp quickstart" ...
I0730 07:12:47.368190    4680 interface.go:26] Installing "sample-templates/dancer quickstart" ...
I0730 07:12:47.368194    4680 interface.go:26] Installing "sample-templates/django quickstart" ...
I0730 07:12:47.368198    4680 interface.go:26] Installing "sample-templates/nodejs quickstart" ...
I0730 07:12:47.368202    4680 interface.go:26] Installing "sample-templates/rails quickstart" ...
I0730 07:12:47.368231    4680 interface.go:26] Installing "sample-templates/jenkins pipeline ephemeral" ...
I0730 07:12:47.368237    4680 interface.go:26] Installing "sample-templates/mariadb" ...
I0730 07:12:47.368241    4680 interface.go:26] Installing "sample-templates/mysql" ...
I0730 07:12:47.368249    4680 interface.go:26] Installing "sample-templates/postgresql" ...
I0730 07:12:47.368327    4680 interface.go:26] Installing "sample-templates/sample pipeline" ...
I0730 07:12:47.368425    4680 apply_list.go:67] Installing "sample-templates/sample pipeline"
I0730 07:12:47.368662    4680 apply_list.go:67] Installing "sample-templates/mongodb"
I0730 07:12:47.368827    4680 apply_list.go:67] Installing "sample-templates/cakephp quickstart"
I0730 07:12:47.368969    4680 apply_list.go:67] Installing "sample-templates/dancer quickstart"
I0730 07:12:47.369168    4680 apply_list.go:67] Installing "sample-templates/django quickstart"
I0730 07:12:47.369314    4680 apply_list.go:67] Installing "sample-templates/nodejs quickstart"
I0730 07:12:47.369417    4680 apply_list.go:67] Installing "sample-templates/rails quickstart"
I0730 07:12:47.369513    4680 apply_list.go:67] Installing "sample-templates/jenkins pipeline ephemeral"
I0730 07:12:47.369637    4680 apply_list.go:67] Installing "sample-templates/mariadb"
I0730 07:12:47.369745    4680 apply_list.go:67] Installing "sample-templates/mysql"
I0730 07:12:47.369859    4680 apply_list.go:67] Installing "sample-templates/postgresql"
I0730 07:12:51.174956    4680 interface.go:41] Finished installing "sample-templates/mongodb" "sample-templates/cakephp quickstart" "sample-templates/dancer quickstart" "sample-templates/django quickstart" "sample-templates/nodejs quickstart" "sample-templates/rails quickstart" "sample-templates/jenkins pipeline ephemeral" "sample-templates/mariadb" "sample-templates/mysql" "sample-templates/postgresql" "sample-templates/sample pipeline"
I0730 07:12:51.585414    4680 interface.go:41] Finished installing "openshift-image-registry" "openshift-router" "openshift-web-console-operator" "centos-imagestreams" "sample-templates" "persistent-volumes"
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.63:8443/console

error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: Unable to login to cluster

**Comment by nickboldt** [comment]
Try this:

```
# enable cluster admin user
minishift addons install --defaults
minishift addons enable admin-user
```

then

```
oc adm policy --as=system:admin add-cluster-role-to-user cluster-admin admin # for admin user
oc adm policy --as=system:admin add-cluster-role-to-user cluster-admin developer # for developer user
```

(as seen on https://github.com/redhat-developer/codeready-workspaces/blob/master/devdoc/building/building-crw.adoc#start-up-minishift and https://divby0.blogspot.com/2019/07/configuring-minishift-for-use-with.html )

You could also try logging in with `-u system -p admin` instead of the `-u system:admin` format.

**Comment by sleshchenko** [comment]
I'm facing the same issue.
Looks like everything works fine when I run minishift with 
```
  minishift start --memory=8000 \
    --disk-size=40GB \
    --vm-driver=virtualbox \
    --docker-opt userland-proxy=false
```
<details>
<summary>Minishift start log and try oc login -u system:admin</summary>

```
serg@sergpad:~/tls/aws$   minishift start --memory=8000 \
>     --disk-size=40GB \
>     --vm-driver=virtualbox \
>     --docker-opt userland-proxy=false
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.11.0'
 53.89 MiB / 53.89 MiB [==============================================================================================================================================================================] 100.00% 0s-- Downloading OpenShift v3.11.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    7 GB
   vCPUs :    2
   Disk size: 40 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.15.0/minishift-centos7.iso'
 355.00 MiB / 355.00 MiB [============================================================================================================================================================================] 100.00% 0s
-- Starting Minishift VM .................................... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... 
OK
   Importing 'openshift/origin-control-plane:v3.11.0'  CACHE MISS
   Importing 'openshift/origin-docker-registry:v3.11.0'  CACHE MISS
   Importing 'openshift/origin-haproxy-router:v3.11.0'  CACHE MISS
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Pulling the OpenShift Container Image ................... OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ..........................................................
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Pulling image openshift/origin-cli:v3.11.0
E0801 11:22:22.997927    5443 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11.0 anonymously
Image pull complete
Pulling image openshift/origin-node:v3.11.0
E0801 11:22:28.807681    5443 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-node:v3.11.0 anonymously
Pulled 5/6 layers, 86% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.99.100 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0801 11:22:47.166486    5443 config.go:40] Running "create-master-config"
I0801 11:22:49.666390    5443 config.go:46] Running "create-node-config"
I0801 11:22:50.392607    5443 flags.go:30] Running "create-kubelet-flags"
I0801 11:22:51.021570    5443 run_kubelet.go:49] Running "start-kubelet"
I0801 11:22:51.282562    5443 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I0801 11:23:38.335507    5443 interface.go:26] Installing "kube-proxy" ...
I0801 11:23:38.335610    5443 interface.go:26] Installing "kube-dns" ...
I0801 11:23:38.335627    5443 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I0801 11:23:38.335638    5443 interface.go:26] Installing "openshift-apiserver" ...
I0801 11:23:38.335784    5443 apply_template.go:81] Installing "openshift-apiserver"
I0801 11:23:38.335792    5443 apply_template.go:81] Installing "kube-dns"
I0801 11:23:38.337954    5443 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I0801 11:23:38.340665    5443 apply_template.go:81] Installing "kube-proxy"
I0801 11:23:43.196569    5443 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
I0801 11:25:47.226377    5443 run_self_hosted.go:242] openshift-apiserver available
I0801 11:25:47.227157    5443 interface.go:26] Installing "openshift-controller-manager" ...
I0801 11:25:47.227179    5443 apply_template.go:81] Installing "openshift-controller-manager"
I0801 11:25:50.445351    5443 interface.go:41] Finished installing "openshift-controller-manager"
Adding default OAuthClient redirect URIs ...
Adding centos-imagestreams ...
Adding web-console ...
Adding registry ...
Adding router ...
Adding sample-templates ...
Adding persistent-volumes ...
I0801 11:25:50.464189    5443 interface.go:26] Installing "centos-imagestreams" ...
I0801 11:25:50.464197    5443 interface.go:26] Installing "openshift-web-console-operator" ...
I0801 11:25:50.464204    5443 interface.go:26] Installing "openshift-image-registry" ...
I0801 11:25:50.464210    5443 interface.go:26] Installing "openshift-router" ...
I0801 11:25:50.464213    5443 interface.go:26] Installing "sample-templates" ...
I0801 11:25:50.464217    5443 interface.go:26] Installing "persistent-volumes" ...
I0801 11:25:50.464564    5443 apply_list.go:67] Installing "centos-imagestreams"
I0801 11:25:50.464824    5443 apply_template.go:81] Installing "openshift-web-console-operator"
I0801 11:25:50.465383    5443 interface.go:26] Installing "sample-templates/mongodb" ...
I0801 11:25:50.465389    5443 interface.go:26] Installing "sample-templates/postgresql" ...
I0801 11:25:50.465393    5443 interface.go:26] Installing "sample-templates/rails quickstart" ...
I0801 11:25:50.465397    5443 interface.go:26] Installing "sample-templates/sample pipeline" ...
I0801 11:25:50.465401    5443 interface.go:26] Installing "sample-templates/jenkins pipeline ephemeral" ...
I0801 11:25:50.465405    5443 interface.go:26] Installing "sample-templates/mariadb" ...
I0801 11:25:50.465408    5443 interface.go:26] Installing "sample-templates/mysql" ...
I0801 11:25:50.465412    5443 interface.go:26] Installing "sample-templates/cakephp quickstart" ...
I0801 11:25:50.465416    5443 interface.go:26] Installing "sample-templates/dancer quickstart" ...
I0801 11:25:50.465420    5443 interface.go:26] Installing "sample-templates/django quickstart" ...
I0801 11:25:50.465424    5443 interface.go:26] Installing "sample-templates/nodejs quickstart" ...
I0801 11:25:50.465454    5443 apply_list.go:67] Installing "sample-templates/nodejs quickstart"
I0801 11:25:50.465596    5443 apply_list.go:67] Installing "sample-templates/mongodb"
I0801 11:25:50.465676    5443 apply_list.go:67] Installing "sample-templates/postgresql"
I0801 11:25:50.465752    5443 apply_list.go:67] Installing "sample-templates/rails quickstart"
I0801 11:25:50.465822    5443 apply_list.go:67] Installing "sample-templates/sample pipeline"
I0801 11:25:50.465894    5443 apply_list.go:67] Installing "sample-templates/jenkins pipeline ephemeral"
I0801 11:25:50.465960    5443 apply_list.go:67] Installing "sample-templates/mariadb"
I0801 11:25:50.466031    5443 apply_list.go:67] Installing "sample-templates/mysql"
I0801 11:25:50.466099    5443 apply_list.go:67] Installing "sample-templates/cakephp quickstart"
I0801 11:25:50.466167    5443 apply_list.go:67] Installing "sample-templates/dancer quickstart"
I0801 11:25:50.466242    5443 apply_list.go:67] Installing "sample-templates/django quickstart"
I0801 11:26:03.207875    5443 interface.go:41] Finished installing "sample-templates/mongodb" "sample-templates/postgresql" "sample-templates/rails quickstart" "sample-templates/sample pipeline" "sample-templates/jenkins pipeline ephemeral" "sample-templates/mariadb" "sample-templates/mysql" "sample-templates/cakephp quickstart" "sample-templates/dancer quickstart" "sample-templates/django quickstart" "sample-templates/nodejs quickstart"
I0801 11:26:31.168520    5443 interface.go:41] Finished installing "centos-imagestreams" "openshift-web-console-operator" "openshift-image-registry" "openshift-router" "sample-templates" "persistent-volumes"
Login to server ...
Creating initial project "myproject" ...
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.100:8443/console

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin


-- Exporting of OpenShift images is occuring in background process with pid 28438.
serg@sergpad:~/tls/aws$ 
serg@sergpad:~/tls/aws$ oc login -u system:admin
Logged into "https://192.168.99.100:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-dns
    kube-proxy
    kube-public
    kube-system
  * myproject
    openshift
    openshift-apiserver
    openshift-controller-manager
    openshift-core-operators
    openshift-infra
    openshift-node
    openshift-service-cert-signer
    openshift-web-console

Using project "myproject".
```

</details>

But when I specify `routing-suffix` and `public-hostname`:
```
  minishift start --memory=8000 \
    --disk-size=40GB \
    --vm-driver=virtualbox \
    --docker-opt userland-proxy=false \
    --public-hostname=local.aws-serg.codenvy-dev.com \
    --routing-suffix=local.aws-serg.codenvy-dev.com
```
 I have the following error in the minishift start output
```
Error during post cluster up configuration: Unable to add sudoer role: The connection to the server 127.0.0.1:8443 was refused - did you specify the right host or port?
```
<details>
<summary>Full minishift start log</summary>

```
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.11.0'
 53.89 MiB / 53.89 MiB [==============================================================================================================================================================================] 100.00% 0s-- Downloading OpenShift v3.11.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    7 GB
   vCPUs :    2
   Disk size: 40 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.15.0/minishift-centos7.iso'
 355.00 MiB / 355.00 MiB [============================================================================================================================================================================] 100.00% 0s
-- Starting Minishift VM .................................... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... OK
   Importing 'openshift/origin-control-plane:v3.11.0'  CACHE MISS
   Importing 'openshift/origin-docker-registry:v3.11.0' . CACHE MISS
   Importing 'openshift/origin-haproxy-router:v3.11.0'  CACHE MISS
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Pulling the OpenShift Container Image ................. OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ...........................................................
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Pulling image openshift/origin-cli:v3.11.0
E0801 11:06:52.576889    5422 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11.0 anonymously
Image pull complete
Pulling image openshift/origin-node:v3.11.0
E0801 11:06:55.904879    5422 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-node:v3.11.0 anonymously
Pulled 5/6 layers, 86% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0801 11:07:13.870661    5422 config.go:40] Running "create-master-config"
I0801 11:07:15.784694    5422 config.go:46] Running "create-node-config"
I0801 11:07:16.595718    5422 flags.go:30] Running "create-kubelet-flags"
I0801 11:07:16.953754    5422 run_kubelet.go:49] Running "start-kubelet"
I0801 11:07:17.151952    5422 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I0801 11:08:06.201957    5422 interface.go:26] Installing "kube-proxy" ...
I0801 11:08:06.203426    5422 interface.go:26] Installing "kube-dns" ...
I0801 11:08:06.203444    5422 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I0801 11:08:06.203455    5422 interface.go:26] Installing "openshift-apiserver" ...
I0801 11:08:06.203582    5422 apply_template.go:81] Installing "openshift-apiserver"
I0801 11:08:06.203873    5422 apply_template.go:81] Installing "kube-proxy"
I0801 11:08:06.206069    5422 apply_template.go:81] Installing "kube-dns"
I0801 11:08:06.206410    5422 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I0801 11:08:10.193495    5422 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
I0801 11:10:14.213360    5422 run_self_hosted.go:242] openshift-apiserver available
I0801 11:10:14.213999    5422 interface.go:26] Installing "openshift-controller-manager" ...
I0801 11:10:14.214029    5422 apply_template.go:81] Installing "openshift-controller-manager"
I0801 11:10:17.062669    5422 interface.go:41] Finished installing "openshift-controller-manager"
Adding default OAuthClient redirect URIs ...
Adding web-console ...
Adding persistent-volumes ...
Adding registry ...
Adding router ...
Adding sample-templates ...
Adding centos-imagestreams ...
I0801 11:10:17.079361    5422 interface.go:26] Installing "openshift-web-console-operator" ...
I0801 11:10:17.079371    5422 interface.go:26] Installing "persistent-volumes" ...
I0801 11:10:17.079376    5422 interface.go:26] Installing "openshift-image-registry" ...
I0801 11:10:17.079380    5422 interface.go:26] Installing "openshift-router" ...
I0801 11:10:17.079385    5422 interface.go:26] Installing "sample-templates" ...
I0801 11:10:17.079389    5422 interface.go:26] Installing "centos-imagestreams" ...
I0801 11:10:17.079443    5422 apply_list.go:67] Installing "centos-imagestreams"
I0801 11:10:17.079706    5422 apply_template.go:81] Installing "openshift-web-console-operator"
I0801 11:10:17.082438    5422 interface.go:26] Installing "sample-templates/cakephp quickstart" ...
I0801 11:10:17.082471    5422 interface.go:26] Installing "sample-templates/nodejs quickstart" ...
I0801 11:10:17.082476    5422 interface.go:26] Installing "sample-templates/rails quickstart" ...
I0801 11:10:17.082482    5422 interface.go:26] Installing "sample-templates/jenkins pipeline ephemeral" ...
I0801 11:10:17.082486    5422 interface.go:26] Installing "sample-templates/mongodb" ...
I0801 11:10:17.082490    5422 interface.go:26] Installing "sample-templates/mysql" ...
I0801 11:10:17.082494    5422 interface.go:26] Installing "sample-templates/dancer quickstart" ...
I0801 11:10:17.082499    5422 interface.go:26] Installing "sample-templates/django quickstart" ...
I0801 11:10:17.082503    5422 interface.go:26] Installing "sample-templates/sample pipeline" ...
I0801 11:10:17.082507    5422 interface.go:26] Installing "sample-templates/mariadb" ...
I0801 11:10:17.082511    5422 interface.go:26] Installing "sample-templates/postgresql" ...
I0801 11:10:17.082557    5422 apply_list.go:67] Installing "sample-templates/postgresql"
I0801 11:10:17.082789    5422 apply_list.go:67] Installing "sample-templates/cakephp quickstart"
I0801 11:10:17.082906    5422 apply_list.go:67] Installing "sample-templates/nodejs quickstart"
I0801 11:10:17.082989    5422 apply_list.go:67] Installing "sample-templates/rails quickstart"
I0801 11:10:17.083066    5422 apply_list.go:67] Installing "sample-templates/jenkins pipeline ephemeral"
I0801 11:10:17.083164    5422 apply_list.go:67] Installing "sample-templates/mongodb"
I0801 11:10:17.083245    5422 apply_list.go:67] Installing "sample-templates/mysql"
I0801 11:10:17.083327    5422 apply_list.go:67] Installing "sample-templates/dancer quickstart"
I0801 11:10:17.083401    5422 apply_list.go:67] Installing "sample-templates/django quickstart"
I0801 11:10:17.083482    5422 apply_list.go:67] Installing "sample-templates/sample pipeline"
I0801 11:10:17.083556    5422 apply_list.go:67] Installing "sample-templates/mariadb"
I0801 11:10:31.427123    5422 interface.go:41] Finished installing "sample-templates/cakephp quickstart" "sample-templates/nodejs quickstart" "sample-templates/rails quickstart" "sample-templates/jenkins pipeline ephemeral" "sample-templates/mongodb" "sample-templates/mysql" "sample-templates/dancer quickstart" "sample-templates/django quickstart" "sample-templates/sample pipeline" "sample-templates/mariadb" "sample-templates/postgresql"
I0801 11:11:06.829149    5422 interface.go:41] Finished installing "openshift-web-console-operator" "persistent-volumes" "openshift-image-registry" "openshift-router" "sample-templates" "centos-imagestreams"
Login to server ...
Creating initial project "myproject" ...
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://local.aws-serg.codenvy-dev.com:8443/console

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin


Error during post cluster up configuration: Unable to add sudoer role: The connection to the server 127.0.0.1:8443 was refused - did you specify the right host or port
```
</details>
Note that I configured public DNS server to point `local.aws-serg.codenvy-dev.com` to my minishift ip (192.168.99.100)

**Comment by stevef1uk** [comment]
Ok I haver sorted my MacBook by looking at my iMac that was able to run minishift, basically I needed to delete Virtualbox and use xhyve.

Then to get this to progress I added a Secret of type Image Secret with my RedHat login details and associated it to the Code Ready Operator service account. Now the heat on my legs tells me something is being installed ;-) Next problem was having to manually add my Image Secret to the YAML of the che service account.

It now works!

**Comment by stevef1uk** [comment]
Ok, spoke too soon. I am getting the following area when trying to create a workspace:
ulling image "registry.redhat.io/codeready-workspaces/stacks-java-rhel8"
Failed to pull image "registry.redhat.io/codeready-workspaces/stacks-java-rhel8": rpc error: code = Unknown desc = Get https://registry.redhat.io/v2/codeready-workspaces/stacks-java-rhel8/manifests/latest: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531
Error: ErrImagePull
Error: Failed to run the workspace: "Unrecoverable event occurred: 'Failed', 'Failed to pull image "registry.redhat.io/codeready-workspaces/stacks-java-rhel8": rpc error: code = Unknown desc = Get https://registry.redhat.io/v2/codeready-workspaces/stacks-java-rhel8/manifests/latest: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531', 'workspacenbzcy0fm3ua86un2.dockerimage-5fc6bcc9bc-hl24f'"

To fix this I added manually my Image Secret to the che-workspace service account
