### ISSUE TITLE
minishift install or start fails

### ISSUE THREAD

**Issue by jovanallhimal** [minishift/minishift#3310]
my minishift fails to start

root@lubuntu-pc:/# minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://mirror.openshift.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.104' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.104' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ...... FAIL E0730 16:17:25.732275   19434 start.go:494] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for domaintype=kvm '). Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for domaintype=kvm ')
root@lubuntu-pc:/# 

any idea or suggestions  ?

Rgds
US East Coast

**Comment by jovanallhimal** [comment]
I was able to bring up

root@lubuntu-pc:/home/lubuntu# minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Stopped
DiskUsage:  1% of 19G (Mounted On: /mnt/sda1)
CacheUsage: 503.2 MB (used by oc binary, ISO or cached images)
RHSM:       Not Registered


root@lubuntu-pc:/home/lubuntu# minishift config view
- iso-url                            : file:///root/.minishift/cache/iso/minishift-rhel7.iso
- memory                             : 4096
- vm-driver                          : kvm



root@lubuntu-pc:/home/lubuntu# minishift profile list
- minishift     Running         (Active)


root@lubuntu-pc:/home/lubuntu# minishift console
Opening the OpenShift Web console in the default browser...
Running Firefox as root in a regular user's session is not supported.  ($XDG_RUNTIME_DIR is /run/user/1000 which is owned by lubuntu.)
Running Firefox as root in a regular user's session is not supported.  ($XDG_RUNTIME_DIR is /run/user/1000 which is owned by lubuntu.)
Running Firefox as root in a regular user's session is not supported.  ($XDG_RUNTIME_DIR is /run/user/1000 which is owned by lubuntu.)
xdg-open: no method available for opening 'https://192.168.42.121:8443/console'
root@lubuntu-pc:/home/lubuntu# ping 192.168.42.121
PING 192.168.42.121 (192.168.42.121) 56(84) bytes of data.
64 bytes from 192.168.42.121: icmp_seq=1 ttl=64 time=4.40 ms
64 bytes from 192.168.42.121: icmp_seq=2 ttl=64 time=2.18 ms
64 bytes from 192.168.42.121: icmp_seq=3 ttl=64 time=2.25 ms
64 bytes from 192.168.42.121: icmp_seq=4 ttl=64 time=2.19 ms
64 bytes from 192.168.42.121: icmp_seq=5 ttl=64 time=2.31 ms
^C
--- 192.168.42.121 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 12ms
rtt min/avg/max/mdev = 2.180/2.665/4.401/0.870 ms


still not able to get to the web access

**Comment by rvandepoel** [comment]
Hi, first I am puzzled about the status: 
`OpenShift: Stopped`
it should have an ouptut similar to:
`OpenShift:  Running (openshift v3.11.0+82a43f6-231)`
does the following gives any output
`minishift openshift config view`
After fixing the kvm module issue, did you redo the install? or at least and do minishift stop/start?
What is the result if you start firefox with your user (not root) and copy/paste the URL?
Cheers,
Rom;)

**Comment by gbraad** [comment]
Make sure you enable VT from your BIOS, install the needed KVM packages and start the daemon.

Then do:
```
$ minishift delete
$ minishift start
```

to make sure you do not run an instance that ended in an invalid state.
