### ISSUE TITLE
oc version doesn't return servers's openshift version for minishift

### ISSUE THREAD

**Issue by vema87** [minishift/minishift#3313]
### General information

  * Minishift version: v1.34.1+c2ff9cb
  * OS: Windows
  * Hypervisor: VirtualBox 

Hi. I can't to get server 's version openshift from minishift

### Steps to reproduce

  1. minishift start
  2. oc version

### Expected

oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://my_minishift_ip:8443
openshift v3.11.0+e5dbec2-186
kubernetes v1.11.0+d4cacc0

### Actual

oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

Server https://my_minishift_ip:8443
kubernetes v1.11.0+d4cacc0

### Logs
oc version --loglevel=8
I0802 11:49:21.519413   16556 loader.go:359] Config loaded from file C:\Users\my_user/.kube/config
I0802 11:49:21.611160   16556 loader.go:359] Config loaded from file C:\Users\my_user/.kube/config
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO
I0802 11:49:21.619941   16556 round_trippers.go:383] GET https://my_minishift_ip/version
I0802 11:49:21.619941   16556 round_trippers.go:390] Request Headers:
I0802 11:49:21.620917   16556 round_trippers.go:393]     Accept: application/json, */*
I0802 11:49:21.627757   16556 round_trippers.go:393]     User-Agent: oc/v1.11.0+d4cacc0 (windows/amd64) kubernetes/d4cacc0
I0802 11:49:21.640447   16556 round_trippers.go:408] Response Status: 200 OK in 11 milliseconds
I0802 11:49:21.640447   16556 round_trippers.go:411] Response Headers:
I0802 11:49:21.641412   16556 round_trippers.go:414]     Content-Type: application/json
I0802 11:49:21.641412   16556 round_trippers.go:414]     Content-Length: 239
I0802 11:49:21.642389   16556 round_trippers.go:414]     Date: Fri, 02 Aug 2019 08:49:21 GMT
I0802 11:49:21.642389   16556 round_trippers.go:414]     Cache-Control: no-store
I0802 11:49:21.643364   16556 request.go:897] Response Body: {
  "major": "1",
  "minor": "11+",
  "gitVersion": "v1.11.0+d4cacc0",
  "gitCommit": "d4cacc0",
  "gitTreeState": "clean",
  "buildDate": "2019-07-30T12:44:55Z",
  "goVersion": "go1.10.8",
  "compiler": "gc",
  "platform": "linux/amd64"
}
I0802 11:49:21.646292   16556 round_trippers.go:383] GET https://my_minishift_ip:8443/version/openshift?timeout=32s
I0802 11:49:21.646292   16556 round_trippers.go:390] Request Headers:
I0802 11:49:21.647268   16556 round_trippers.go:393]     Accept: application/json, */*
I0802 11:49:21.648244   16556 round_trippers.go:393]     User-Agent: oc/v1.11.0+d4cacc0 (windows/amd64) kubernetes/d4cacc0
I0802 11:49:21.652150   16556 round_trippers.go:408] Response Status: 404 Not Found in 0 milliseconds
I0802 11:49:21.655107   16556 round_trippers.go:411] Response Headers:
I0802 11:49:21.657074   16556 round_trippers.go:414]     Cache-Control: no-store
I0802 11:49:21.657074   16556 round_trippers.go:414]     Content-Type: application/json
I0802 11:49:21.658044   16556 round_trippers.go:414]     Content-Length: 84
I0802 11:49:21.658044   16556 round_trippers.go:414]     Date: Fri, 02 Aug 2019 08:49:21 GMT
I0802 11:49:21.659019   16556 request.go:897] Response Body: {
  "paths": [
    "/apis",
    "/metrics",
    "/swagger-ui/",
    "/version"
  ]
}

Server https://my_minishift_ip:8443
kubernetes v1.11.0+d4cacc0

**Comment by gbraad** [comment]
Not sure why this is not returned, and looks like an issue with how `cluster up` maybe sets up the server. You can use `m status` or `m openshift version` instead.
