### ISSUE TITLE
Virtualbox can not use/create the Host-Only Ethernet interface

### ISSUE THREAD

**Issue by mohammedah** [minishift/minishift#3316]
### General information

  * Minishift version: 2.6
  * OS: Windows
  * Hypervisor: VirtualBox 

the below is the issue i see when trying to start minishift:

C:\minishift-1.34.1-windows-amd64>minishift start --vm-driver virtualbox
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ........... FAIL E0811 20:47:21.799530   14212 start.go:494] Error starting the VM: Error starting stopped host: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minishift --type headless failed:
VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:01.851803 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E_FAIL (0X80004005)). Retrying.
Error starting the VM: Error starting stopped host: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minishift --type headless failed:
VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:01.851803 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E_FAIL (0X80004005))

C:\minishift-1.34.1-windows-amd64>

any suggestion?

thanks,
Kerim

**Comment by gbraad** [comment]
> Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)

an issue with your virtual network setup. Please use the configuration tool to modify or reinstall virtualbox.

**Comment by guycrets** [comment]
Experienced exactly same issue on Win10 with VirtualBox 6.0.10 and Minishift v1.34.1. Upgraded to VirtualBox 6.0.14 and issue disappeared.
