### ISSUE TITLE
Please update docu on setting up virtualization 

### ISSUE THREAD

**Issue by LeoUfimtsev** [minishift/minishift#3319]
If someone has time:

Over here:
https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#setting-up-hyperkit-driver

Could you add a line that mentions if you want to use hyperkit as vm-driver, you can use: "--vm-driver hyperkit" as explained here:
https://github.com/minishift/minishift/issues/3266

Otherwise minshift usually tries to use xhyve.

It took me quite a while to find this. Having a note about it somewhere would help.

**Comment by gbraad** [comment]
You can propose a change here: https://github.com/minishift/minishift/blob/master/docs/source/getting-started/setting-up-virtualization-environment.adoc#setting-up-the-hyperkit-driver
