### ISSUE TITLE
Minishift documentation site is broken.

### ISSUE THREAD

**Issue by bryonbaker** [minishift/minishift#3323]
### General information

  * Minishift version: N/A
  * OS: N/A
  * Hypervisor: N/A

### Steps to reproduce

  1. Click on the Getting Started with Minishift link in the README.MD (https://docs.okd.io/latest/minishift/using/index.html) and the site is down.

### Expected
A web site to be displayed

**Comment by anjannath** [comment]
Docs are back up now! Thanks for reporting this!
