### ISSUE TITLE
Minishift v 1.34.1 still do not start up

### ISSUE THREAD

**Issue by MrMic** [minishift/minishift#3326]
It refuses to start either with:
- Ubuntu 18.04 LTS / Kvm
- Mas OSX Mojavve 10.14.6 / VirtualBox

Here is the output:

===== 8< --------------------------------- >8 ======

$> minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ........................ OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 11% used OK
-- Writing current configuration for static assignment of IP address ... OK
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ....................................................................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0' --public-hostname 192.168.99.116 --routing-suffix 192.168.99.116.nip.io
err     : exit status 1
output  : Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.99.116 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0822 09:32:19.590812    5180 flags.go:30] Running "create-kubelet-flags"
I0822 09:32:20.255910    5180 run_kubelet.go:49] Running "start-kubelet"
I0822 09:32:20.535136    5180 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I0822 09:32:41.567071    5180 interface.go:26] Installing "kube-proxy" ...
I0822 09:32:41.567928    5180 interface.go:26] Installing "kube-dns" ...
I0822 09:32:41.567936    5180 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I0822 09:32:41.567941    5180 interface.go:26] Installing "openshift-apiserver" ...
I0822 09:32:41.568012    5180 apply_template.go:81] Installing "openshift-apiserver"
I0822 09:32:41.568012    5180 apply_template.go:81] Installing "kube-dns"
I0822 09:32:41.568136    5180 apply_template.go:81] Installing "kube-proxy"
I0822 09:32:41.568189    5180 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I0822 09:32:45.931908    5180 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: timed out waiting for the condition

===== 8< --------------------------------- >8 ======

**Comment by gbraad** [comment]
Timeouts can occur by constrained resources or slow network connectivity. this is an issue with `oc cluster up` and not per se Minishift

**Comment by MrMic** [comment]
Seems I got more chance now, Minishift start better.
I close.
