### ISSUE TITLE
Release binaries for ppc64le

### ISSUE THREAD

**Issue by Pensu** [minishift/minishift#3334]
Hi all,

This is a request to generate ppc64le binaries for minishift. As `make` can create platform-specific binaries and there is travis support already available for ppc64le. What else would be required to achieve this? Please let me know how can I help to get this done.

Thanks.

**Comment by gbraad** [comment]
This will not happen. No new features will be added to Minishift.

Essentially, Minishift depends on virtualization... but you can use a remote host option: To make this work, you would need to find a way that target the remote machine (like SSH) but also making sure `oc cluster up` CAN install the cluster. At the moment I am not aware of this.

**Comment by jbastian** [comment]
ppc64le supports virtualization.  I have a [Raptor Blackbird](https://www.raptorcs.com/content/BK1B01/intro.html) system locally running RHEL8 and virt works fine:

```
[root@raven ~]# rpm -q qemu-kvm
qemu-kvm-2.12.0-85.module+el8.1.0+4010+d6842f29.ppc64le

[root@raven ~]# virsh nodeinfo
CPU model:           ppc64le
CPU(s):              16
CPU frequency:       3783 MHz
CPU socket(s):       1
Core(s) per socket:  4
Thread(s) per core:  4
NUMA cell(s):        1
Memory size:         32399552 KiB
```
