### ISSUE TITLE
Issues when starting Minishift with xhyve and the 0.4.0 driver; cannot unmarshal bool into Go struct field Driver.Virtio9p

### ISSUE THREAD

**Issue by tdiesler** [minishift/minishift#3338]
### General information

  * Minishift version: 1.34.1
  * OS: macOS
  * Hypervisor: xhyve

```
[tdiesler@MacBook3 ~]$ brew cask install minishift
==> Satisfying dependencies
==> Downloading https://github.com/minishift/minishift/releases/download/v1.34.1/minishift-1.34.1-darwin-amd64.tgz
Already downloaded: /Users/tdiesler/Library/Caches/Homebrew/downloads/7362af234507051182bb4184053f181ea8e516446c5b2bb6bd470358b061a945--minishift-1.34.1-darwin-amd64.tgz
==> Verifying SHA-256 checksum for Cask 'minishift'.
==> Installing Cask minishift
==> Linking Binary 'minishift' to '/usr/local/bin/minishift'.
🍺  minishift was successfully installed!

[tdiesler@MacBook3 ~]$ minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .... FAIL E0906 11:57:49.931011    2288 start.go:494] Error starting the VM: Error creating new host: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string. Retrying.
Error starting the VM: Error creating new host: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string
```

**Comment by gbraad** [comment]
Please use the version as specified in the documentation.

@praveenkumar WDYT?

**Comment by tdiesler** [comment]
I believe the versions are defined by

```
brew cask install minishift
```

**Comment by nani2ratna** [comment]
I had the same issue when I installed minishift without installing kvm. After I installed Kvm this error is disappeared. As you are using mac, may be install virtualbox if kvm is not available. And then start minishift.

**Comment by EfraimLA** [comment]
Same, in fact did update driver & used other versions but keeps without can start host, also got error with MAC & ips

**Comment by pnasrat** [comment]
I think xhyve is known broken eg it has been removed in minikube kubernetes/minikube#4291 and the minishift docs probably need to be updated to reflect that. 

Can you try using `minikube start --vm-driver=virtualbox` rather than xhyve.

**Comment by daimor** [comment]
Suppose the issue in wrong version of xhyve Driver. [Minishift documentation](https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#setting-up-xhyve-driver) offers to use brew to install version 0.3.3. But brew does not have this version anymore, only [0.4.0 version](https://formulae.brew.sh/formula/docker-machine-driver-xhyve#default) is available there. Looks like it's time to update minishift documentation.

**Comment by ssbarnea** [comment]
Am I wrong or this does translate to "minishift currently cannot be installed on macos"? 

Even attempt to use VirtualBox goes into funny errors:
```
Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.12r133076nnt Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads
```

Aparently 5 > 6 for some.

**Comment by gbraad** [comment]
You can use xhyve with an older driver or the improved hyperkit driver.
Virtualbox works with the `--vm-driver` workaround.

**Comment by gbraad** [comment]
> But brew does not have this version anymore

`brew install xhyve@0.3.3`

**Comment by gbraad** [comment]
@minishift/minishift-dev Since we support hyperkit, and support after catalina is questionable, it might be best to remove the xhyve driver.
