### ISSUE TITLE
Permission denied error while creating workspaces in che

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#3342]
### General information

  * Minishift version: master
  * OS: Linux
  * Hypervisor: KVM

While creating a new che workspace, the following error appears:
```
Starting Init Plugin Broker

Cleaning /plugins dir

Unified Che Plugin Broker

List of plugins and editors to install
- che-incubator/typescript/latest - Typescript language features
- eclipse/che-machine-exec-plugin/7.1.0 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace containers.
- eclipse/che-theia/7.1.0 - Eclipse Theia, get the latest release each day.

Starting Che plugins and editor processing

Downloading VS Code extension for plugin 'che-incubator/typescript/latest'

Starting VS Code and Theia plugins processing

mkdir /plugins/sidecars: permission denied

Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspace4aosa9xw85sfy9vv failed with error: mkdir /plugins/sidecars: permission denied"

```

/cc @l0rd @sleshchenko

**Comment by l0rd** [comment]
Thanks @AndrienkoAleksandr yes you are right. We need to find another reason why this is happening.

@gbraad it looks like folks in che team are not able to reproduce the problem, do you have any idea about why this can happen? Maybe the volumes existed already? 

@amisevsk is there some difference in the way we mount `/projects` and `/plugins`?

**Comment by amisevsk** [comment]
> is there some difference in the way we mount `/projects` and `/plugins`?

AFAIK, it's the same as `/projects`. Can someone facing the issue list PVs on their cluster? I'm at a loss here.

**Comment by anjannath** [comment]
@amisevsk pvc from the mini-che namespace in my machine, where i am seeing the permission issue.
```
$oc get pvc -n mini-che
NAME                          STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
che-data-volume               Bound     pv0078    100Gi      RWO,ROX,RWX                   5m
claim-che-workspace9izuy6mg   Bound     pv0028    100Gi      RWO,ROX,RWX                   1m
claim-che-workspaceiksxlsar   Bound     pv0052    100Gi      RWO,ROX,RWX                   1m
```

**Comment by amisevsk** [comment]
@anjannath Could you also post `oc get pv` as `system:admin`?

Actually, testing it now I see a *ton* of PVs bound to che workspaces with status "failed" -- maybe the issue is related to how Che frees claims when workspaces are deleted?

**Comment by pnadon** [comment]
Has anyone found a manual fix for this? I am trying to deploy Eclipse Che on my Windows 10 machine, let me know if you need any log files etc., I am somewhat unfamiliar with how Che works.

**Comment by sleshchenko** [comment]
@amisevsk I guess the issue you faced is in forbidden hostPath volume. I've reported in https://github.com/minishift/minishift/issues/3349 and I believe it's not Che related issue.
Could you check `oc describe pv pvXXXX`  to make sure that you have the same issue?

**Comment by amisevsk** [comment]
@sleshchenko good catch, that is the issue I'm seeing here. 

@pnadon if you have a cluster up and running, could you please share the output of
```
oc login -u system:admin
oc get pv
```
from a terminal?

**Comment by pnadon** [comment]
> @sleshchenko good catch, that is the issue I'm seeing here.
> 
> @pnadon if you have a cluster up and running, could you please share the output of
> 
> ```
> oc login -u system:admin
> oc get pv
> ```
> 
> from a terminal?

Is `oc` a command associated with minishift? This issue was referenced in [an issue on the eclipse/che respository](https://github.com/eclipse/che/issues/14330) which was related to k8s, and I posted here because there was far more activity here.

I'm running Eclipse Che from Docker and not Minishift, but I am still getting the error `mkdir /plugins/sidecars: permission denied`, please let me know if my issue is relevant here or not.

**Comment by Rucadi** [comment]
> > @sleshchenko good catch, that is the issue I'm seeing here.
> > @pnadon if you have a cluster up and running, could you please share the output of
> > ```
> > oc login -u system:admin
> > oc get pv
> > ```
> > 
> > 
> > from a terminal?
> 
> Is `oc` a command associated with minishift? This issue was referenced in [an issue on the eclipse/che respository](https://github.com/eclipse/che/issues/14330) which was related to k8s, and I posted here because there was far more activity here.
> 
> I'm running Eclipse Che from Docker and not Minishift, but I am still getting the error `mkdir /plugins/sidecars: permission denied`, please let me know if my issue is relevant here or not.

I'm running eclipse che from minikube (vm none) and I'm getting the same error.
