### ISSUE TITLE
`--openshift-version` validation should work the same way for '3.9' and '3.9.0' or warn to use X.X.X version format

### ISSUE THREAD

**Issue by dgolovin** [minishift/minishift#3343]
### General information

  * Minishift version: minishift v1.34.1+c2ff9cb
  * OS: Windows
  * Hypervisor: Hyper-V

### Steps to reproduce

  1. Run minishift command
```
C:\Users\dgolo\bin>minishift start --openshift-version 3.9 --memory=16Gb --cpus=6
```
### Expected
To behave the same way as it is with `--openshift-version 3.9.0`
```
C:\Users\dgolo\bin>minishift start --openshift-version 3.9.0 --memory=16Gb --cpus=6
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... FAIL
   Minishift does not support OpenShift version v3.9.0. You need to use a version >= v3.10.0
```

### Actual
```
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9' is valid ... v3.9 is not a valid OpenShift versionFAIL
```

### Logs
N/A

**Comment by gbraad** [comment]
@anjannath WDYT?

**Comment by anjannath** [comment]
@gbraad `3.9` is not a valid version, as per the tags on mirror.openshift.com i am not sure we should modify the check, however as you mentioned we can add a check to see if the version provided is a valid one in the format `x.x.x`.

**Comment by dgolovin** [comment]
@gbraad yes, validation should be fixed/syncronized on left side.  It looks bad when you say it is valid and then fail saying opposite. The same BTW for 3.9.0. First it says supported, then opposite.
