### ISSUE TITLE
Minishift does not start due to SSH , dnsmasq issues

### ISSUE THREAD

**Issue by jonathanvila** [minishift/minishift#3353]
### General information

  * Minishift version: 1.34.1
  * OS: Linux Fedora 30
  * Hypervisor: KVM 

### Steps to reproduce

  1. ./minishift start --v=10 --show-libmachine-logs

even tested with 
  1. ./minishift delete --force --clear-cache 
  2. rm -rf ~/.minishift
  3. ./minishift start --v=10 --show-libmachine-logs

### Expected

Minishift starts

### Actual

Error complaining about SSH

### Logs

-- minishift version: v1.34.1+c2ff9cb
-- Starting profile 'minishift'
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:34979
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ....Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:33529
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Calling .Start
(minishift) DBG | Starting VM minishift
...(minishift) DBG | GetIP called for minishift
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:54:7e:3a
(minishift) DBG | Waiting for the VM to come up... 0
(minishift) DBG | GetIP called for minishift
......repeating last 3 outputs 89 times ....
(minishift) DBG | Waiting for the VM to come up... 89
(minishift) Unable to determine VM's IP address, did it fail to boot?
(minishift) Calling .GetConfigRaw
Waiting for SSH to be available...
Getting to WaitForSSH function...
(minishift) Calling .GetSSHHostname
(minishift) DBG | GetIP called for minishift
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:54:7e:3a
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /home/jonathan/.minishift/machines/minishift/id_rsa (-rwx------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@ -o IdentitiesOnly=yes -i /home/jonathan/.minishift/machines/minishift/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
exit 0
SSH cmd err, output: exit status 255: 
Error getting ssh command 'exit 0' : ssh command error:
command : exit 0
err     : exit status 255
output  : 
...... repeating this block several times until I cancel with ^C .......

**Comment by Kallenm** [comment]
Im getting this same error on Windows.

C:\Users\???????\Documents\minishift-1.34.1-windows-amd64>minishift delete --force --clear-cache
Removed cache content at: 'C:\Users\kallenm\.minishift\cache'
Removing entries from kubeconfig for cluster: :8443
Deleting the Minishift VM...
Minishift VM deleted.

C:\Users\???????\Documents\minishift-1.34.1-windows-amd64>minishift start --show-libmachine-logs
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... OK                                       
-- Checking if Powershell is available ... OK                                                                           
-- Checking if Hyper-V driver is installed ... OK                                                                       
-- Checking if Hyper-V driver is configured to use a Virtual Switch ...                                                    
'New Virtual Switch' ... OK                                                                                          
-- Checking if user is a member of the Hyper-V Administrators group ... OK                                              
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.11.0'
 53.59 MiB / 53.59 MiB [===================================================================================] 100.00% 0s
-- Downloading OpenShift v3.11.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.15.0/minishift-centos7.iso'
 355.00 MiB / 355.00 MiB [=================================================================================] 100.00% 0s
-- Starting Minishift VM ....Running pre-create checks...
..Creating machine...
(minishift) Downloading C:\Users\??????\.minishift\cache\boot2docker.iso from file://C:/Users/??????/.minishift/cache/iso/centos/v1.15.0/minishift-centos7.iso...
(minishift) Creating SSH key...
(minishift) Creating VM...
.(minishift) Using switch "New Virtual Switch"
.(minishift) Creating VHD
.......(minishift) Starting VM...
.....(minishift) Waiting for host to start...
.........Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
......Detecting the provisioner...
Provisioning with minishift...

   Setting hostname ...
......OK
........Copying certs to the local machine directory...
....Copying certs to the remote machine...
.......Setting Docker configuration on the remote daemon...
..... FAIL E1016 15:20:24.409806     136 start.go:494] Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: ssh command error:
command : sudo mkdir -p /etc/systemd/system/docker.service.d && printf %s "[Service]
ExecStart=
ExecStart=/usr/bin/dockerd-current -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock \
           --selinux-enabled \
           --log-driver=journald \
           --signature-verification=false \
           --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current \
           --default-runtime=docker-runc \
           --exec-opt native.cgroupdriver=systemd \
           --userland-proxy-path=/usr/libexec/docker/docker-proxy-current \
           --storage-driver overlay2 --tlsverify --tlscacert /etc/docker/ca.pem \
           --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem \
           --label provider=hyperv --insecure-registry 172.30.0.0/16
Environment=
" | sudo tee /etc/systemd/system/docker.service.d/10-machine.conf
err     : exit status 255
output  : . Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: ssh command error:
command : sudo mkdir -p /etc/systemd/system/docker.service.d && printf %!s(MISSING) "[Service]
ExecStart=
ExecStart=/usr/bin/dockerd-current -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock \
           --selinux-enabled \
           --log-driver=journald \
           --signature-verification=false \
           --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current \
           --default-runtime=docker-runc \
           --exec-opt native.cgroupdriver=systemd \
           --userland-proxy-path=/usr/libexec/docker/docker-proxy-current \
           --storage-driver overlay2 --tlsverify --tlscacert /etc/docker/ca.pem \
           --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem \
           --label provider=hyperv --insecure-registry 172.30.0.0/16
Environment=
" | sudo tee /etc/systemd/system/docker.service.d/10-machine.conf
err     : exit status 255
output  :

**Comment by Kallenm** [comment]
Seems my problem was the Windows OpenSSH.  Once I removed it from the path I was able to get past my problem as shown in #2811
