### ISSUE TITLE
switch to go modules?

### ISSUE THREAD

**Issue by yeya24** [minishift/minishift#3354]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox / hyperkit

As described in title.

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by micwoj92** [comment]
unstale
