### ISSUE TITLE
uild error: Failed to push image: After retrying 6 times, Push image still failed due to error: Put http://172.30.1.1:5000/ connection refused

### ISSUE THREAD

**Issue by cleberlira** [minishift/minishift#3355]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox / hyperkit

Hello everyone,

Someone can i help me? i already update all these files mas dont worked:

daemon.json

{
  "insecure-registries" : ["docker-registry.default.svc:5000", "172.30.1.1:5000", "172.17.0.6:5000"]
}

DOCKER_OPTS="--insecure-registry 172.30.1.1:5000 --insecure-registry 172.17.0.6:5000"

Hosts
172.30.1.1	docker-registry.default.svc

### Actual
Starting S2I Java Build .....
[INFO] F8: S2I binary build from fabric8-maven-plugin detected
[INFO] F8: Copying binaries from /tmp/src/maven to /deployments ...
[INFO] F8: Checking for SpringBoot archive...
[INFO] Current reconnect backoff is 4000 milliseconds (T2)
[INFO] F8: Found iot-reactive-application-1.0-SNAPSHOT.jar...
[INFO] F8: ... done
[INFO] Current reconnect backoff is 8000 milliseconds (T3)
[INFO] F8: Pushing image 172.30.1.1:5000/microservices-exemplo/reactive-application:latest ...
[INFO] F8: Warning: Push failed, retrying in 5s ...
[INFO] Current reconnect backoff is 16000 milliseconds (T4)
[INFO] F8: Warning: Push failed, retrying in 5s ...
[INFO] F8: Warning: Push failed, retrying in 5s ...
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] F8: Warning: Push failed, retrying in 5s ...
[INFO] F8: Warning: Push failed, retrying in 5s ...
[INFO] F8: Warning: Push failed, retrying in 5s ...
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] F8: Warning: Push failed, retrying in 5s ...
[INFO] F8: Registry server Address: 
[INFO] F8: Registry server User Name: serviceaccount
[INFO] F8: Registry server Email: serviceaccount@example.org
[INFO] F8: Registry server Password: <<non-empty>>
[INFO] F8: error: build error: Failed to push image: After retrying 6 times, Push image still failed due to error: Put http://172.30.1.1:5000/v1/repositories/microservices-exemplo/reactive-application/: dial tcp 172.30.1.1:5000: connect: connection refused

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by olivermg** [comment]
The cause for this could be the one described in #3357 . You can also find a workaround there, maybe you want to try if that helps for now.

**Comment by cleberlira** [comment]
i solved using: minishift delete
