### ISSUE TITLE
Minishift does not start

### ISSUE THREAD

**Issue by EfraimLA** [minishift/minishift#3359]
### General information

  * Minishift version: minishift v1.34.1+c2ff9cb
  * OS: macOS
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. To start minikube i use:
`minikube start --vm-driver=virtualbox`
  2. To start minishift used:
`minishift start --vm-driver=virtualbox`

### Expected
Minikube starts satisfactorily with Virtualbox hypervisor

> ➜  ~ minikube start --vm-driver=virtualbox
😄  minikube v1.4.0 on Darwin 10.15
💿  Downloading VM boot image ...
    > minikube-v1.4.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.4.0.iso: 135.73 MiB / 135.73 MiB [-] 100.00% 7.14 MiB p/s 20s
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.16.0 on Docker 18.09.9 ...
💾  Downloading kubelet v1.16.0
💾  Downloading kubeadm v1.16.0
🚜  Pulling images ...
🚀  Launching Kubernetes ...
⌛  Waiting for: apiserver proxy etcd scheduler controller dns
🏄  Done! kubectl is now configured to use "minikube"

### Actual
Can start minikube with no problems but minishift doesn't start

> ➜  ~ minishift start --vm-driver=virtualbox
[1]    14050 killed     minishift start --vm-driver=virtualbox
➜  ~ minishift start --vm-driver=virtualbox
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.11.0'
 53.05 MiB / 53.27 MiB [===============================================================================================================]  99.59% 0s 53.27 MiB / 53.27 MiB [===============================================================================================================] 100.00% 0sOK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.15.0/minishift-centos7.iso'
 355.00 MiB / 355.00 MiB [=============================================================================================================] 100.00% 0s
-- Starting Minishift VM ..... FAIL E1012 12:02:20.879420   14079 start.go:494] Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory". Retrying.
Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"

### Logs
Here are my `minishift start --show-libmachine-logs -v5` logs: 

>➜  ~ minishift start --show-libmachine-logs -v5
-- minishift version: v1.34.1+c2ff9cb
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....Found binary path at /usr/local/bin/minishift
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:50854
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetMachineName
(minishift) Calling .DriverName
Reading certificate data from /Users/efraim/.minishift/certs/ca.pem
Decoding PEM data...
Parsing certificate...
Reading certificate data from /Users/efraim/.minishift/certs/cert.pem
Decoding PEM data...
Parsing certificate...
Running pre-create checks...
(minishift) Calling .PreCreateCheck
(minishift) DBG | COMMAND: /usr/local/bin/VBoxManage --version
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | 6.0.12r133076
(minishift) DBG | }
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | }
. FAIL E1012 12:15:20.627130   14263 start.go:494] Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory". Retrying.
Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"

**Comment by olivermg** [comment]
> > . FAIL E1012 12:15:20.627130   14263 start.go:494] Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory". Retrying.
> > Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"

This is an error coming from Virtualbox, not Minishift. It suggests that you currently have hardware virtualization disabled on your system.

You can usually enable it in your machine's BIOS/Firmware (if your CPU and Motherboard supports that, which depends on the hardware).

**Comment by EfraimLA** [comment]
Yes in fact i've virtualization activated in UEFI, but i could run the VM (minikube in my case) using noVTXCheck so i think could apply same parameter to minishift VM

**Comment by yaroze** [comment]
Hi guys, I'm having the exact same issue on a Ryzen 3500U laptop  (Win10 Enterprise).
Could it be related to AMD processors or could it have something to do with the path having spaces on Windows?

`> minishift start --show-libmachine-logs -v5
-- minishift version: v1.34.3+4b58f89
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....Found binary path at C:\Users\z0049b1n\bin\minishift.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:50893
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetMachineName
(minishift) Calling .DriverName
Reading certificate data from C:\Users\z0049b1n\.minishift\certs\ca.pem
Decoding PEM data...
Parsing certificate...
Reading certificate data from C:\Users\z0049b1n\.minishift\certs\cert.pem
Decoding PEM data...
Parsing certificate...
Running pre-create checks...
(minishift) Calling .PreCreateCheck
(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | 6.1.22r144080
(minishift) DBG | }
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | Hyper-V is not installed.
. FAIL E0525 16:14:07.928504   15764 start.go:499] Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory". Retrying.
Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"`

As you can see, VBox exists:
```
>"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" --version
6.1.22r144080

>
```

Cheers.

**Comment by yaroze** [comment]
Hi guys, I'm having the exact same issue on a Ryzen 3500U laptop  (Win10 Enterprise).
Could it be related to AMD processors or could it have something to do with the path having spaces on Windows?

```
> minishift start --show-libmachine-logs -v5
-- minishift version: v1.34.3+4b58f89
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....Found binary path at C:\Users\XXXX\bin\minishift.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:50893
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetMachineName
(minishift) Calling .DriverName
Reading certificate data from C:\Users\XXXX\.minishift\certs\ca.pem
Decoding PEM data...
Parsing certificate...
Reading certificate data from C:\Users\XXXX\.minishift\certs\cert.pem
Decoding PEM data...
Parsing certificate...
Running pre-create checks...
(minishift) Calling .PreCreateCheck
(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | 6.1.22r144080
(minishift) DBG | }
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | Hyper-V is not installed.
. FAIL E0525 16:14:07.928504   15764 start.go:499] Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory". Retrying.
Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"
```
As you can see, VBox exists:
```
>"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" --version
6.1.22r144080

>
```

Cheers.
