### ISSUE TITLE
minishift - oc cluster up - error creating node config

### ISSUE THREAD

**Issue by get2arun** [minishift/minishift#3360]
### General information

  * Minishift version: **minishift v1.34.1+c2ff9cb**
  * OS:  **Linux desktop-arun 4.18.0-21-generic #22~18.04.1-Ubuntu SMP Thu May 16 15:07:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux**
  * Hypervisor: **VirtualBox Graphical User Interface Version 5.2.18_Ubuntu r123745**

### Steps to reproduce

  1. start the minishift, copied the installation output in the path. While installing it could not import the images and it shows "CACHE MISS". The output is copied to below url.
https://gist.github.com/get2arun/220741a50111c2009d994af669cee02f
  2. The images are available in the openshift console, so deployment was not running any pods.
  3. The tried to login to openshift registry but end up with error. so moved to step 4.
  4. Then did a "oc cluster down" and "oc cluster up". but cluster up is throwing the error.

### Expected
In minishift vm, the command "oc cluster up" should bring the openshift cluster up and running.

### Actual
docker login to openshift registry error:
desktop-arun:~# docker login -u developer 172.30.1.1:5000
Password: 

> Error response from daemon: Get http://172.30.1.1:5000/v1/users/: dial tcp 172.30.1.1:5000: connect: connection refused

oc cluster up error:

> I1017 12:00:50.455363    8182 run.go:337] Stdout:
> Error: unable to read node config: open /var/lib/origin/openshift.local.config/node/node-config.yaml: no such file or directory
> I1017 12:00:50.455398    8182 run.go:338] Stderr:
> I1017 12:00:50.455433    8182 run.go:293] Deleting container "c2ad0a0b5486b87cf8215187cff59022c22b8b95ca5cf66cec41be1701d8f722"
> Error: error creating node config: could not run "create-kubelet-flags": Docker run error rc=1; caused by: Docker run error rc=1

### Logs
The logs are posted in the link below. https://gist.github.com/get2arun/4b32855f188721462474951a529ad9ff

**Comment by olivermg** [comment]
Sounds like the issue described in #3357 . You can also find a workaround there. Maybe you want to try if that "solves" your problem until someone fixes the issue for real.

**Comment by get2arun** [comment]
Thanks olivermg. 
This solved the issue of deploying the the pods for the registry. Earlier there were pending deployment due to unresolved image.
