### ISSUE TITLE
docker push to minishift docker registry fails

### ISSUE THREAD

**Issue by get2arun** [minishift/minishift#3361]
### General information

Minishift version: minishift v1.34.1+c2ff9cb
OS: Linux desktop-arun 4.18.0-21-generic #22~18.04.1-Ubuntu SMP Thu May 16 15:07:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Hypervisor: VirtualBox Graphical User Interface Version 5.2.18_Ubuntu r123745

### Steps to reproduce

  1. started the minishift using virtualbox
  2. docker-registry is exposed and pod is running in the oc console
  3. created the tag and docker login is working for developer user account
  4. While pushing to openshift docker registry, seeing the below error. 

### Expected
Expecting to push the image to Openshift docker registry 

### Actual (with and without 443)

root@arun-desktop-e470:~# docker push docker-registry-default.127.0.0.1.nip.io:443/myproject/ghost:latest
The push refers to repository [docker-registry-default.127.0.0.1.nip.io:443/myproject/ghost]
6545fabd1db4: Retrying in 5 seconds 
e1b5357c9029: Retrying in 5 seconds 
2f546e8c419e: Retrying in 5 seconds 
2f5caec27732: Retrying in 5 seconds 
da4dc4c42b60: Retrying in 5 seconds 
24ad92b56299: Waiting 
4eab4d25c303: Waiting 
e2dd6cf79115: Waiting 
67ecfc9591c8: Waiting 

root@arun-desktop-e470:~# docker push docker-registry-default.127.0.0.1.nip.io/myproject/ghost:latest
The push refers to repository [docker-registry-default.127.0.0.1.nip.io/myproject/ghost]
6545fabd1db4: Pushing [==================================================>]  4.096kB
e1b5357c9029: Pushing [==================================================>]  205.2MB/205.2MB
2f546e8c419e: Pushing [>                                                  ]  253.4kB/25.33MB
2f5caec27732: Pushing [==================================================>]   1.32MB
da4dc4c42b60: Pushing [==================================================>]  3.584kB
24ad92b56299: Waiting 
4eab4d25c303: Waiting 
e2dd6cf79115: Waiting 
67ecfc9591c8: Waiting 
unauthorized: authentication required

The docker-registry is not running in the minishift VM. But "oc get pods,svc,deployments -n default" show the docker service and route are running.

Additional docker info.
root@desktop:~ cat /etc/docker/daemon.json 
{
        "insecure-registries": ["172.30.0.0/16", "docker-registry-default.127.0.0.1.nip.io"]
}
{
    "dns": ["8.8.4.4", "8.8.8.8"]
}
root@desktop:~# cat ~/.docker/config.json 
{
	"auths": {
		"docker-registry-default.127.0.0.1.nip.io": {
			"auth": "ZGV2ZWxvcGVyOl90cktacjhBQ2pLSmRXNGxUTkdJbE5ic01hbXJXV2pMWjBWV0pNOG5peXc="
		},
		"docker-registry-default.127.0.0.1.nip.io:443": {
			"auth": "ZGV2ZWxvcGVyOl90cktacjhBQ2pLSmRXNGxUTkdJbE5ic01hbXJXV2pMWjBWV0pNOG5peXc="
		},
		"https://index.docker.io/v1/": {
			"auth": "Z2V0MmFydW46YWRtaW5AMTIz"
		},
		"registry-1.docker.io": {
			"auth": "Z2V0MmFydW46YWRtaW5AMTIz"
		}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.09.6 (linux)"
	}
}
### questions
What are steps to figure out what is happening in the oc cluster to identify this issue?
How to remove authentication for the openshift docker registry for pull and push without any user authentication?

**Comment by olivermg** [comment]
You might want to see if the workaround mentioned in #3357 helps with this until this gets fixed permanently.

**Comment by get2arun** [comment]
Followed the #3357 and rolled out the new pods but still seeing the same error. The logs are at https://gist.github.com/get2arun/335ef19cb2cb529d1907139f2fabd833 
The registry container is not running inside the minishift vm. is this okay?

**Comment by olivermg** [comment]
The registry pod needs to be running if you want to push docker images to it.

However, it was just a good guess to point you to #3357 . I thought creating the rolebinding as mentioned there might help to start the registry pod, as that's what I've experienced (as described in #3357).

If that's not the case then you're probably facing a different root cause and I'm afraid I cannot help you any further with that, as I'm not an expert in Minishift myself - I was just debugging my issues with it.
