### ISSUE TITLE
Can't start minishift

### ISSUE THREAD

**Issue by anthonma** [minishift/minishift#3362]
### General information

  * Minishift version:  v1.34.1
  * OS: Ubuntu 18.04
  * Hypervisor: KVM

I'm trying to start minishift on my ubuntu vm. When I try to do so, I get the following error:

![minishiftError](https://user-images.githubusercontent.com/55550413/67487389-1fb06480-f66e-11e9-96fa-986cae73ceeb.PNG)

I'm starting with minishift start --memory=5120
### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Expected
Minishift starts

### Actual
An Error occurs

### Logs
![miniShiftLog](https://user-images.githubusercontent.com/55550413/67487597-846bbf00-f66e-11e9-95bc-b2c736cd4009.PNG)

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by anthonma** [comment]
I will close the issue for now, because my environment will probably change, so I hope the problem will be gone than. If it shouldn't I'll reopen that issue or create another one.

**Comment by gbraad** [comment]
Looks like a networking issue, like running a VPN at the same time

**Comment by gbraad** [comment]
Correction: `exec format error`

remove the driver and redownload. This looks like an issue with the driver not being correctly downloaded, hence the issue with the driver not starting
