### ISSUE TITLE
Minishift - oc stops responding to commands after a period of inactivity or sleep on Mac OSX

### ISSUE THREAD

**Issue by boomkap** [minishift/minishift#3363]
### General information

  * Minishift version: v1.34.1+c2ff9cb
  * OS:  macOS 
  * Hypervisor:  hyperkit

### Steps to reproduce

After a period of inactivity or machine going to sleep, oc cannot communicate with the cluster. 

oc get pods

Unable to connect to the server: net/http: TLS handshake timeout

Trying to gracefully stop minishift fails. 

minishift stop
Stopping the OpenShift cluster...
Error stopping cluster: Maximum number of retries (60) exceeded

Minishift:  Running
Profile:    minishift
OpenShift:  Stopped
DiskUsage:  ERR of  (Mounted On: )
CacheUsage: 1.68 GB (used by oc binary, ISO or cached images)

Trying to start minishift again shows an error with ssh 

minishift start --v=5 --show-libmachine-logs
-- minishift version: v1.34.1+c2ff9cb
-- Starting profile 'minishift'
Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:62327
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperkit' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperkit' hypervisor ...
-- Starting Minishift VM ....Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:62335
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) Calling .Start
(minishift) Using UUID 55dab86e-f9be-11e9-a73c-8c859073ac8b
(minishift) Generated MAC b6:88:c3:aa:43:30
(minishift) Starting with cmdline: initrd=initrd0.img root=live:CDLABEL=minishift-centos7 rootfstype=auto ro rd.live.image quiet no_timer_check console=ttyS0 console=tty0 net.ifnames=0 biosdevname=0 rhgb rd.luks=0 rd.md=0 rd.dm=0 
(minishift) Calling .GetConfigRaw
Waiting for SSH to be available...
Getting to WaitForSSH function...
(minishift) Calling .GetSSHHostname
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/kapilkhanna/.minishift/machines/minishift/id_rsa (-rw-------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@192.168.64.5 -o IdentitiesOnly=yes -i /Users/kapilkhanna/.minishift/machines/minishift/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
exit 0
SSH cmd err, output: exit status 255: 
Error getting ssh command 'exit 0' : ssh command error:
command : exit 0
err     : exit status 255

**Comment by graphadvantage** [comment]
seeing this as well.  Any ideas?

**Comment by porteusconf** [comment]
Using hyperkit may fix it. Please let us know! Try ```minishift start --vm-driver=hyperkit ``` after doing all steps at [https://chrisphillips-cminion.github.io/openshift/2019/10/04/NotesMiniShift.html](https://chrisphillips-cminion.github.io/openshift/2019/10/04/NotesMiniShift.html)

 Hyperkit is based on xhyve, but hyperkit fixed the sleep issue per last line at link below:  **We also fixed a bunch of issues around waking up after sleep etc.** 

 [the-difference-between-xhyve-and-hyperkit](https://medium.com/@hintcnuie/the-difference-between-xhyve-and-hyperkit-67a9f378ab97) 
> HyperKit is a toolkit for embedding hypervisor capabilities in your application. It includes a complete hypervisor, based on xhyve/bhyve, which is optimized for lightweight virtual machines and container deployment. It is designed to be interfaced with higher-level components such as the VPNKit and DataKit.
HyperKit currently only supports macOS using the Hypervisor.framework. It is a core component of Docker Desktop For Mac.
HyperKit was originally derived from xhyve but we have extended it with a number of features and fixes to stability. New features include things like being able to run it with networking not requiring root (via VPNKit), support for virtio socket devices, support for qcow2 disk images (with trim support) etc. We also fixed a bunch of issues around waking up after sleep etc. 
>
