### ISSUE TITLE
latest minishift documentation not found

### ISSUE THREAD

**Issue by tmds** [minishift/minishift#3365]
Reproducer:

```
$ minishift version
minishift v1.34.1+c2ff9cb
$ minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... FAIL
   See the 'Setting Up the Virtualization Environment' topic (https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html) for more information
```

-> the url https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html does not work.

**Comment by djungowski** [comment]
Same applies for all the links in Readme.md. I also tried all the previous versions available on https://docs.okd.io/ and could not find any docs for minishift whatsoever

**Comment by gbraad** [comment]
@anjannath again something with the documentation? Perhaps Vikram can help or explain this?

**Comment by anjannath** [comment]
The artifacts were once again cleared, triggered the job which should upload them again to the artifacts location. https://ci.centos.org/job/minishift-pr/5819/

**Comment by gbraad** [comment]
Docs should work again

**Comment by tmds** [comment]
Thanks!
