### ISSUE TITLE
Integrate changelog generation into Makefile

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#337]
The script to generate the changelog (extracted from the milestones, categorising by issue type, etc) should be part of the _release_ target.

**Comment by praveenkumar** [comment]
@hferentschik Do we still need it I think we have now a script for release already right?

**Comment by hferentschik** [comment]
Not sure whether we need the changelog generation in the Makefile in the end, but the end game is to have a full automated release via a Jenkins job. See also #786.

**Comment by budhrg** [comment]
@hferentschik , I think we can close this issue as we have now fully automated release job which uses the `issue_list.sh` script to generate the changelog content and update the release notes.

Closing it now. Feel free to reopen it if you feel more action is needed here.

**Comment by hferentschik** [comment]
+1
