### ISSUE TITLE
Removal of the xhyve driver implementation

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#3375]
We have decided to remove the xhyve driver support from Minishift. There are several motivations behind this; we have limited time to work on fixes, so we prefer to work on native and current hypervisors. In the case of xhyve, we have a replacement available to works without issues, namely hyperkit. The current implementation would need a fix to work with the latest version as can be seen in https://github.com/minishift/minishift/issues/3338. In the upcoming release we will add a deprecation notice with a link to instructions in the documentation on how to proceed (upgrade path to hyperkit), after which the subsequent release will remove support for xhyve.

**Comment by cricket007** [comment]
@gbraad Any news on when docs will be updated? 

https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#for-macos

**Comment by cricket007** [comment]
Whoops, nevermind. See it now. Would still be nice to add a warning box after the xhyve section header

**Comment by gbraad** [comment]
@anjannath WDYT?
