### ISSUE TITLE
-- Checking if requested OpenShift version 'v3.11.0' is valid ... v3.11.0 is not a valid OpenShift versionFAIL

### ISSUE THREAD

**Issue by hippo00** [minishift/minishift#3376]
### General information

  * Minishift version: 
  * OS: Linux 
  * Hypervisor: KVM 

### Steps to reproduce

  1. minishift start

### Logs
![image](https://user-images.githubusercontent.com/42257545/69404292-ebe16100-0d37-11ea-8442-de6c9a19d818.png)

**Comment by karlssone** [comment]
I get the same error. What was the solution?

**Comment by hippo00** [comment]
google the issue,you can have a solution.

**Comment by itcloudy** [comment]
minishift config set skip-check-openshift-release true

**Comment by djnotes** [comment]
Why is the version not valid after all?
