### ISSUE TITLE
issue in minishift setup on windows

### ISSUE THREAD

**Issue by prhinge1** [minishift/minishift#3377]
### General information

  * Minishift version: 1.34.1-windows-amd64
  * OS: Windows 10
  * Hypervisor: Oracle VirtualBox 6.0

### Steps to reproduce

 PS C:\Users\PrasannaHinge\Minishift> minishift start --vm-driver virtualbox                                             -- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .................................. OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... OK
   Importing 'openshift/origin-control-plane:v3.11.0' . CACHE MISS
   Importing 'openshift/origin-docker-registry:v3.11.0' . CACHE MISS
   Importing 'openshift/origin-haproxy-router:v3.11.0' . CACHE MISS
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Pulling the OpenShift Container Image ........Error pulling the OpenShift container image: ssh command error:
command : docker pull openshift/origin-control-plane:v3.11.0
err     : exit status 1
output  : Trying to pull repository docker.io/openshift/origin-control-plane ...
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

PS C:\Users\PrasannaHinge\Minishift> 

This is fail to retrieve nishift openshift image from git hub using ssh.

### Expected

It should install successfully.

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
-- minishift version: v1.34.1+c2ff9cb
-- Starting profile 'minishift'
Found binary path at C:\Users\PrasannaHinge\Minishift\minishift.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:57333
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minishift --machinereadable
(minishift) DBG | STDOUT:
(minishift) DBG | {
The 'minishift' VM is already running.
(minishift) DBG | name="minishift"

**Comment by anjannath** [comment]
@prhinge1 Are you on a VPN/Proxy setup, from the logs, it seems minishift is not able to pull the required openshift images.
You could try to delete any existing minishift instances by `minishift delete -f` and start again `minishift start --vm-driver virtualbox`, and see if that helps.
