### ISSUE TITLE
Passwords with special characters need workaround

### ISSUE THREAD

**Issue by RickJWagner** [minishift/minishift#338]
Working with CDK-3.0_alpha2, I notice that my RHN password (which contains a non-numeric, non-alpha character) is not accepted.
A workaround is avialable, using single quotes.
   --password 'some%password'  

Minishift looks great so far!

**Comment by LalatenduMohanty** [comment]
@RickJWagner for me non alphanumeric character i.e. "@" works for me in the password.  We need to check with `%` etc.

**Comment by hferentschik** [comment]
This is a shell issue. Depending on your shell you might get variable interpolation to occur or if you have spaces in your password it might be split up. It really has very little if anything to do with minishift itself. Using single quotes will work, because it stops variable interpolation. When it comes to passwords, you usually always want to "protect" them with single quotes.

**Comment by hferentschik** [comment]
I don't think we need to do anything in the code, but we maybe want to be a bit more explicit in the docs.

**Comment by budhrg** [comment]
@hferentschik @thatdocslady   I believe we can document it as part of this doc https://github.com/minishift/minishift/blob/master/docs/minishift.md. 

WDYT ?

**Comment by hferentschik** [comment]
You want to edit the help string "Password for the virtual machine registration." in root.go? I don't think this is very common, but why not. What exactly do you want to add. Remember this is supposed to be a short message. It cannot become too long.

**Comment by hferentschik** [comment]
An other alternative would be to add something to the troubleshooting guide.

**Comment by thatdocslady** [comment]
I vote putting this in the troubleshooting guide, assuming what @hferentschik said about this problem occuring sometimes on some shells. Does this problem happen with other passwords?

**Comment by praveenkumar** [comment]
@thatdocslady It's about some of special shell variable which cause this issue and let's put that to troubleshoot guide.

**Comment by thatdocslady** [comment]
@praveenkumar makes sense :) so @budhrg are you planning to document this and send a PR for review? I'll be happy to help if you're slammed.

**Comment by budhrg** [comment]
@thatdocslady Please do the honour :smile:

**Comment by gbraad** [comment]
I have the same issue with using a `!` inside passwords. Often this gets replaced with the command from history. I expect escaping characters, like `\` to cause similar problems...

**Comment by hferentschik** [comment]
Merged via pull request #438.
