### ISSUE TITLE
Unable to start minishift with VirtualBox driver in Windows

### ISSUE THREAD

**Issue by dileep-dev** [minishift/minishift#3381]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox / hyperkit

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by anjannath** [comment]
@dileep-dev start Minishift with `minishift start --vm-driver virtualbox --show-libmachine-logs -v5` and post the logs.
