### ISSUE TITLE
json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string

### ISSUE THREAD

**Issue by fxgx99** [minishift/minishift#3382]
I am having a similar issue. For a while I used minishift without a problem, but as various recent updates that I can't keep up with with I am unfortunately unable to even create a host. This is happening both on RHEL 7 and on my mac. Below is the error message I am getting on a RHEL machine: 
`-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ...
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ........ FAIL E1202 12:25:19.831780   16377 start.go:494] Error starting the VM: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s. Retrying.
Error starting the VM: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
[chrisrhel@rhel ~]$`

I read that the compatibility between certain docker drivers and minishift can also be a factor. But I am totally lost in this case. I am posting my mac configuration as well as the error message I am getting on the Mac: 
`Docker : 
Docker version 2.1.0.5(40693)
engine: 19.03.5
compose: 1.34.1
Kubernetes: v1.14.8

Minishift: minishift v1.34.1+c2ff9cb
Minishift start error message: minishift start                                                                                                                                                                       12:23:53
-- Starting profile 'minishift'
json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string`  I have tried also installing and uninstalling minishift with `brew install ` and `brew uninstall ` still no luck.

**Comment by lmorse** [comment]
I was seeing the same thing with docker-machine-driver-xhyve
Switched to use hyperkit, but seeing other problems.

**Comment by anjannath** [comment]
@fxgx99 the xhyve driver has been deprecated, and will be removed in the next release cut. Please use the hyperkit driver.

@lmorse Feel free to create a new issue if you are facing issues with the `Hyperkit` driver
