### ISSUE TITLE
Error starting the VM: Error creating new host: dial tcp: missing address. Retrying.

### ISSUE THREAD

**Issue by sunnyguohua** [minishift/minishift#3383]
### General information

  * Minishift version: 
  * OS: VM CentOS Linux release 7.6.1810 (Core) on Windows Hyper-V 10.0.18362.1
  * Hypervisor: KVM

### Steps to reproduce

  1.  minishift start --iso-url file:///root/minishift-centos7.iso

### Logs
[root@localhost bin]# minishift start --show-libmachine-logs -v5
-- minishift version: v1.34.1+c2ff9cb
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ...
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ...Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
.Plugin server listening at address
 FAIL E1203 05:40:52.514468   32139 start.go:494] Error starting the VM: Error creating new host: dial tcp: missing address. Retrying.
Error starting the VM: Error creating new host: dial tcp: missing address

**Comment by anjannath** [comment]
Can you check the CentOS vm you are running this on has network interfaces?
(You seem to be running inside a nested virt environment, which is not supported)

**Comment by alanjiang** [comment]
In my mac, it occurs ,  minishift-1.34.3, 
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperkit' is supported on this platform ... OK
-- Checking if hyperkit is installed ... 
   Hyperkit is available at /usr/local/bin/hyperkit
   Checking for setuid bit ... OK
-- Checking if hyperkit driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-hyperkit
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperkit' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .... FAIL E1118 17:29:34.590917   24370 start.go:499] Error starting the VM: Error creating new host: dial tcp: missing address. Retrying.
Error starting the VM: Error creating new host: dial tcp: missing address
