### ISSUE TITLE
Minishift start login to registry.redhat.io fails

### ISSUE THREAD

**Issue by lmorse** [minishift/minishift#3395]
### General information

  * Minishift version: 
$ minishift version
minishift v1.34.1+21103616
CDK v3.10.0-1
  * OS: Linux / macOS / Windows
macOS Mojave
Version 10.14.6 (18G87)
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox / hyperkit
hyperkit

### Steps to reproduce
  1. Removed keychain password files for minishift.
  2. Remove previous existing minishift config.
      $ rm -rf ~/.minishift
  3. $ minishift setup-cdk
  4. $ minishift config set vm-driver hyperkit
  5. $ minishift start

### Expected
Expected login success and minishift successfully started
### Actual
```
$ rm -rf ~/.minishift
$ minishift setup-cdk
Setting up CDK 3 on host using '/Users/lmorse/.minishift' as Minishift's home directory
Copying minishift-rhel7.iso to '/Users/lmorse/.minishift/cache/iso/minishift-rhel7.iso'
Copying oc to '/Users/lmorse/.minishift/cache/oc/v3.11.141/darwin/oc'
Creating configuration file '/Users/lmorse/.minishift/config/config.json'
Creating marker file '/Users/lmorse/.minishift/cdk'
Default add-ons anyuid, admin-user, xpaas, registry-route, che, htpasswd-identity-provider, eap-cd installed
Default add-ons anyuid, admin-user, xpaas enabled
CDK 3 setup complete.
$ minishift config set vm-driver hyperkit
No Minishift instance exists. New 'vm-driver' setting will be applied on next 'minishift start'
$ minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://mirror.openshift.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.141' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.141' is supported ... OK
-- Checking if requested hypervisor 'hyperkit' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperkit' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .................. OK
-- Registering machine using subscription-manager
   Red Hat Developers or Red Hat Subscription Management (RHSM) username: lmorse@us.ibm.com
   Retrieving password from keychain ... FAIL 
   Red Hat Developers or Red Hat Subscription Management (RHSM) password: [HIDDEN]
   Storing password in keychain ... OK 
   Login to registry.redhat.io in progress ................... FAIL 
   Registration in progress ...................................... FAIL [2m10.1s]
Error to register VM: ssh command error:
command : sudo -E subscription-manager register --auto-attach --username lmorse@us.ibm.com --password ********
err     : exit status 70
output  : Registering to: subscription.rhsm.redhat.com:443/subscription
Network error, unable to connect to server. Please see /var/log/rhsm/rhsm.log for more information.
```

Note:
I have repeatedly cleared my keychain and started from scratch.
I have repeatedly tried both my Red Hat long ID lmorse@us.ibm.com and short ID lmorse.
I have verified my ID and password by logging in to the Red Hat Customer Portal.
I have also verified my ID and password by docker login and pulling an image from the registry.

```
$ docker login -u lmorse -p ******** registry.redhat.io
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
Lauries-MBP:~ lmorse$ docker pull registry.redhat.io/ubi8/ubi-minimal
Using default tag: latest
latest: Pulling from ubi8/ubi-minimal
645c2831c08a: Already exists 
5e98065763a5: Already exists 
Digest: sha256:32fb8bae553bfba2891f535fa9238f79aafefb7eff603789ba8920f505654607
Status: Downloaded newer image for registry.redhat.io/ubi8/ubi-minimal:latest
registry.redhat.io/ubi8/ubi-minimal:latest
```

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

I copied stdout to a logfile.  Is that all you need?  Are there other logs produced on the system that I should collect?  If so, where are they?

[minishift_start.log](https://github.com/minishift/minishift/files/3947186/minishift_start.log)

**Comment by anjannath** [comment]
You can ssh into the minishift VM with (`minishift ssh`) and check if you have network connectivity from inside the VM or not since in the error it says: 
```
Network error, unable to connect to server. Please see /var/log/rhsm/rhsm.log for more information.
```
Also share `rhsm.log` file here.

**Comment by lmorse** [comment]
I upgraded my MacOS and now it is working!

macOS Catalina
Version 10.15.2 (19C57)

Not clear on the underlying cause.  I will close this issue for now and reopen if I see this again.

Thanks @anjannath for your help!

**Comment by lmorse** [comment]
Actually, it may have been as simple as a reboot.
