### ISSUE TITLE
minishift start SSH cmd err, output: exit status 255

### ISSUE THREAD

**Issue by get2arun** [minishift/minishift#3404]
### General information
I have to create minishift vm everyday and perform the setup that I did previous day inorder to continue. I believe minishift is not made that way. 
Minishift is not working or I am not doing right way inorder to use the exising minishift vm.

  * Minishift version: 
 minishift v1.34.1+c2ff9cb
  * OS: Linux / macOS / Windows
 Linux arun-e470 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox / hyperkit
  using kvm

### Steps to reproduce

  1. create the oc cluster using "minishift start --iso-url file:///home/arun/pkgs/minishift-centos7.iso --memory 3072 --vm-driver kvm"
  2. after using the cluster, then using minishift stop
  3. start the stopped minishift vm, using minishift start
  

### Expected
In the minishift status, minishift says it is running. But logging in to the openshift is not working. I am expecting to use the same openshift cluster using oc login. 
ALL i need is, I want to use the previously created openshift cluster by starting minishift start without errors.

### Actual
Everytime I had to delete the vm and create the fresh one since after minishift stop or restart of the machine or next day, the old minishift stopped vm is not working after start.

arun-e470:~$ oc login -u system:admin
error: dial tcp 192.168.42.225:8443: connect: connection refused - verify you have provided the correct host and port and that the server is currently running.
arun-e470:~$ minishift ip
192.168.42.225
arun-e470:~$ oc login -u system:admin https://192.168.42.225:8443/
error: dial tcp 192.168.42.225:8443: connect: connection refused - verify you have provided the correct host and port and that the server is currently running.

### Logs

arun-e470:~$ minishift start
-- Starting profile 'test'
-- Using proxy for the setup
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM ........-- Setting proxy information ... .....FAIL
 FAIL E1218 09:58:02.981756   14018 start.go:494] Error starting the VM: Error setting proxy to VM: ssh command error:
command : export HTTP_PROXY=http://myproxy:8080 http_proxy=http://myproxy:8080 HTTPS_PROXY=http://myproxy:8080 https_proxy=http://myproxy:8080 NO_PROXY=localhost,127.0.0.1,172.30.1.1,192.168.99.1/16,192.168.42.0/16,127.0.0.1,localhost,::1,docker-registry-default.127.0.0.1.nip.io,docker-registry-default.192.168.99.101.nip.io,192.168.99.1/24,192.168.42.127,192.168.42.225,192.168.42.1 no_proxy=localhost,127.0.0.1,172.30.1.1,192.168.99.1/16,192.168.42.0/16,127.0.0.1,localhost,::1,docker-registry-default.127.0.0.1.nip.io,docker-registry-default.192.168.99.101.nip.io,192.168.99.1/24,192.168.42.127,192.168.42.225,192.168.42.1
err     : exit status 255
output  : . Retrying.
Error starting the VM: Error setting proxy to VM: ssh command error:
command : export HTTP_PROXY=http://myproxy:8080 http_proxy=http://myproxy:8080 HTTPS_PROXY=http://myproxy:8080 https_proxy=http://myproxy:8080 NO_PROXY=localhost,127.0.0.1,172.30.1.1,192.168.99.1/16,192.168.42.0/16,127.0.0.1,localhost,::1,docker-registry-default.127.0.0.1.nip.io,docker-registry-default.192.168.99.101.nip.io,192.168.99.1/24,192.168.42.127,192.168.42.225,192.168.42.1 no_proxy=localhost,127.0.0.1,172.30.1.1,192.168.99.1/16,192.168.42.0/16,127.0.0.1,localhost,::1,docker-registry-default.127.0.0.1.nip.io,docker-registry-default.192.168.99.101.nip.io,192.168.99.1/24,192.168.42.127,192.168.42.225,192.168.42.1
err     : exit status 255
output  : 

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

minishift start --show-libmachine-logs -v5
-- minishift version: v1.34.1+c2ff9cb
-- Starting profile 'test'
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:39515
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(test) Calling .GetState
(test) DBG | Getting current state...
(test) DBG | Fetching VM...
-- Using proxy for the setup
	Using http proxy: http://myproxy:8080
	Using https proxy: http://myproxy:8080
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM ....Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:38775
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(test) Calling .GetState
(test) DBG | Getting current state...
(test) DBG | Fetching VM...
(test) Calling .Start
(test) DBG | Starting VM test
...(test) DBG | GetIP called for test
(test) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(test) DBG | IP address: 192.168.42.225
(test) DBG | Unable to locate IP address for MAC 52:54:00:91:f5:6a
.(test) Calling .GetConfigRaw
-- Setting proxy information ... (test) Calling .GetIP
(test) DBG | GetIP called for test
(test) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(test) DBG | IP address: 192.168.42.225
(test) DBG | Unable to locate IP address for MAC 52:54:00:91:f5:6a
(test) Calling .DriverName
(test) Calling .GetIP
(test) DBG | GetIP called for test
(test) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(test) DBG | IP address: 192.168.42.225
(test) DBG | Unable to locate IP address for MAC 52:54:00:91:f5:6a
(test) Calling .GetSSHHostname
(test) DBG | GetIP called for test
(test) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(test) DBG | IP address: 192.168.42.225
(test) DBG | Unable to locate IP address for MAC 52:54:00:91:f5:6a
(test) Calling .GetSSHPort
(test) Calling .GetSSHKeyPath
(test) Calling .GetSSHKeyPath
(test) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /home/apurb/.minishift/profiles/test/machines/test/id_rsa (-rw-------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@192.168.42.225 -o IdentitiesOnly=yes -i /home/apurb/.minishift/profiles/test/machines/test/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:

FAIL
 FAIL E1218 10:17:54.501679   29184 start.go:494] Error starting the VM: Error setting proxy to VM: ssh command error:
command : export HTTP_PROXY=http://myproxy:8080 http_proxy=http://myproxy:8080 HTTPS_PROXY=http://myproxy:8080 https_proxy=http://myproxy:8080 NO_PROXY=localhost,127.0.0.1,172.30.1.1,192.168.99.1/16,192.168.42.0/16,127.0.0.1,localhost,::1,docker-registry-default.127.0.0.1.nip.io,docker-registry-default.192.168.99.101.nip.io,192.168.99.1/24,192.168.42.127,192.168Search Results.42.225,192.168.42.1 no_proxy=localhost,127.0.0.1,172.30.1.1,192.168.99.1/16,192.168.42.0/16,127.0.0.1,localhost,::1,docker-registry-default.127.0.0.1.nip.io,docker-registry-default.192.168.99.101.nip.io,192.168.99.1/24,192.168.42.127,192.168.42.225,192.168.42.1
err     : exit status 255
output  : . Retrying.
Error starting the VM: Error setting proxy to VM: ssh command error:
command : export HTTP_PROXY=http://myproxy:8080 http_proxy=http://myproxy:8080 HTTPS_PROXY=http://myproxy:8080 https_proxy=http://myproxy:8080 NO_PROXY=localhost,127.0.0.1,172.30.1.1,192.168.99.1/16,192.168.42.0/16,127.0.0.1,localhost,::1,docker-registry-default.127.0.0.1.nip.io,docker-registry-default.192.168.99.101.nip.io,192.168.99.1/24,192.168.42.127,192.168.42.225,192.168.42.1 no_proxy=localhost,127.0.0.1,172.30.1.1,192.168.99.1/16,192.168.42.0/16,127.0.0.1,localhost,::1,docker-registry-default.127.0.0.1.nip.io,docker-registry-default.192.168.99.101.nip.io,192.168.99.1/24,192.168.42.127,192.168.42.225,192.168.42.1
err     : exit status 255
output  :

**Comment by samimb** [comment]
Same issue here but `minishift delete` does not resolve it.

**Comment by mshaposhnik** [comment]
Having the same problem
```
$ minishift version
minishift v1.34.2+83ebaab
```
```
$ minishift config view
- memory                             : 10240
- vm-driver                          : virtualbox
```
```
$ uname -ro
5.5.13-200.fc31.x86_64 GNU/Linux (Fedora 31)
```


Each and every SSH call duing startup lasts for abt. 1 minute printing dots and ends with `SSH cmd err, output: <nil>` :

```
(minishift) DBG | About to run SSH command:
(minishift) DBG | exit 0
................................(minishift) DBG | SSH cmd err, output: <nil>:
```
then
```
(minishift) DBG | About to run SSH command:
(minishift) DBG | ip addr show
.............(minishift) DBG | SSH cmd err, output: <nil>: 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
(minishift) DBG |     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
(minishift) DBG |     inet 127.0.0.1/8 scope host lo
(minishift) DBG |        valid_lft forever preferred_lft forever
.....(output from command)
````
then again
```
(minishift) DBG | About to run SSH command:
(minishift) DBG | exit 0
................................(minishift) DBG | SSH cmd err, output: <nil>:
```
and the startup may last for way over 30 mins...
Please help to elaborate the problem, thanks in advance.

**Comment by agomez79-lab** [comment]
ALguno tiene la solucion para esto en centos 7?
