### ISSUE TITLE
Minishift does not start if I change the Wireless Network on which the VM and External Switch were created

### ISSUE THREAD

**Issue by pranavgaba11** [minishift/minishift#3408]
### General information

  * Minishift version: v1.34.1+c2ff9cb
  * OS: Windows
  * Hypervisor: Hyper-V 

### Steps to reproduce

  1. Create an External Switch and start minishift (Suppose on network A)
  2. Connect to some other Wireless network and try to do a minishift start (Suppose on network B)
  3. It will get stuck at Starting minishift VM stage

**NOTE: It works fine if I connect back to the same network on which I created the VM and External Switch**
### Expected
Minishift should start and Openshift console should be up

### Actual
Minishift stuck at Starting Minishift VM stage

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.
(minishift) DBG | [executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
.(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
(minishift) DBG | [stdout =====>] :
(minishift) DBG | [stderr =====>] :
.(minishift) DBG | [executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
(minishift) DBG | [stdout =====>] : 10.61.182.158
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) Calling .GetConfigRaw
Waiting for SSH to be available...
Getting to WaitForSSH function...
(minishift) Calling .GetSSHHostname
(minishift) DBG | [executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
.(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
(minishift) DBG | [stdout =====>] : 10.61.182.158
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
SSH binary not found, using native Go implementation
&{{{<nil> 0 [] [] []} docker [0x7cb810] 0x7cb7e0 <nil>  [] 0s} 10.61.182.158 22 <nil> <nil>}
About to run SSH command:
exit 0
......Error dialing TCP: dial tcp 10.61.182.158:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
......Error dialing TCP: dial tcp 10.61.182.158:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
.....Error dialing TCP: dial tcp 10.61.182.158:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
.....Error dialing TCP: dial tcp 10.61.182.158:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
....Error dialing TCP: dial tcp 10.61.182.158:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
....Error dialing TCP: dial tcp 10.61.182.158:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
....Error dialing TCP: dial tcp 10.61.182.158:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
....Error dialing TCP: dial tcp 10.61.182.158:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
...Error dialing TCP: dial tcp 10.61.182.158:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
...Error dialing TCP: dial tcp 10.61.182.158:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
.

**Comment by gbraad** [comment]
Invalid. This is a known issue that is clealy documented. Certificates for OpenShift, deployed using oc cluster up/minisihift, are bound to a single IP address. Either use an internal switch and the static IP address option foir Hyper-V, or create two difference instances.
