### ISSUE TITLE
Error attempting to download and cache 'oc': Failed to validate hash on macOS

### ISSUE THREAD

**Issue by bellhop** [minishift/minishift#3416]
### General information

  * Minishift version: v1.34.2+83ebaab
  * OS: macOS
  * Hypervisor: xhyve

### Steps to reproduce

  1. minishift start --show-libmachine-logs -v5

### Expected
Expected has should be: 75d58500aec1a2cee9473dfa826c81199669dbc0f49806e31a13626b5e4cfcf0

### Actual
minishift start --show-libmachine-logs -v5
-- minishift version: v1.34.2+83ebaab
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.11.0'
-- Downloading OpenShift v3.11.0 checksums ... OKError starting the cluster: Error attempting to download and cache 'oc': Failed to validate hash - expected: 252be97fc39eed1002fb509e2d25217718498b8bc8b77f5788e090aa6847fa3c, actual: 75d58500aec1a2cee9473dfa826c81199669dbc0f49806e31a13626b5e4cfcf0

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

Unable to run as the download fails.

**Comment by dineshchandar** [comment]
I am also facing this issue. Is there a fix for this?

**Comment by mhoffmeyerDC** [comment]
The path for macOS is `.minishift/cache/oc/v3.11.0/darwin/oc` for the `oc` binary.
