### ISSUE TITLE
Fail start minishift 1.34.2

### ISSUE THREAD

**Issue by pendolsp** [minishift/minishift#3424]
### General information

  * Minishift version: 1.34.2
  * OS: Fedora 31
  * Hypervisor: KVM

### Steps to reproduce

  1. Followed install instructions on https://docs.okd.io/latest/minishift/getting-started/
  2. minishift start
  3. 
  4. 

### Expected

Success

### Actual

Error starting plugin binary: fork/exec /usr/local/bin/docker-machine-driver-kvm: exec format error
.... FAIL E0304 10:33:40.228284    3579 start.go:494] Error starting the VM: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s.

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by nitsmrinal** [comment]
Failed to start in windows 10 too,

 Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.16.0/minishift-centos7.iso'
 370.00 MiB / 370.00 MiB [=================================================================================] 100.00% 0s
-- Starting Minishift VM ..... FAIL E0311 21:10:47.838668   13788 start.go:494] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: open /Users/nitsm/.minishift/cache/iso/centos/v1.16.0/minishift-centos7.iso: The system cannot find the path specified.. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: open /Users/nitsm/.minishift/cache/iso/centos/v1.16.0/minishift-centos7.iso: The system cannot find the path specified.

**Comment by anjannath** [comment]
@nitsmrinal Please provide the full logs from `minishift start --show-libmachine-logs -v5`

> open /Users/nitsm/.minishift/cache/iso/centos/v1.16.0/minishift-centos7.iso:

This does not look like a windows path..

**Comment by mindej** [comment]
It does not work with Mac OS as well.

**Comment by arcmop** [comment]
It does not work with Windows OS as well.
Attach:
- Log
- Screenshoot, file exist, tested with curl

[log.txt](https://github.com/minishift/minishift/files/4487552/log.txt)
![image](https://user-images.githubusercontent.com/7807338/79465065-80d34800-7fc0-11ea-827f-e74fcb1d7d9d.png)
