### ISSUE TITLE
Minishift wipes SELinux and other host settings on restart

### ISSUE THREAD

**Issue by PhillipDowney** [minishift/minishift#3428]
### General information

  * Minishift version: 
  * OS: Linux 
  * Hypervisor: KVM 

for containers that require persistent Host storage and setsebool -P container_manage_group settings... it seems these settings get totally wiped when you shut down then restart Minishift.

e.g. minishift ssh  setsebool -P container_manage_group D

Is there any way to make them survive a stop / start of the server ..

**Comment by anjannath** [comment]
@PhillipDowney IIRC except `/var/minishift` everything else is non-persistent in the crc vm. @praveenkumar would know for sure if that is the case.

As a workaround you can create an addon with the particular command and enable it, that'll run this command for every minishift start.

**Comment by PhillipDowney** [comment]
I have created the addon with command "sudossh setsebool -P container_manage_group D"

if I use apply when the system is started it runs, but it does not seem to get applied at startup... cannot find in documentation any reason why this is happing... is there a step to ensure adding are executed on startup ?

**Comment by gbraad** [comment]
check using `--log-level debug` is the commands are sent to the VM.

**Comment by PhillipDowney** [comment]
that level of trace does not work, I did --show-libmachine-logs - v5 and did not show up

**Comment by anjannath** [comment]
> is there a step to ensure add-ons are executed on startup ?

Yes, `minishift addons enable <addon-name>`

**Comment by PhillipDowney** [comment]
I do this  by default... it does not execute startup

**Comment by praveenkumar** [comment]
@PhillipDowney Can you provide an example for a pod/deploy template which you are using and hitting this issue? we are relabel the selinux context when as part of user-data handle script https://github.com/minishift/minishift-centos-iso/blob/master/scripts/handle-user-data#L44 but may be something else is required.

**Comment by PhillipDowney** [comment]
I simply installed Minishift on Kvm applied the add-on to do the above.... it did not work.

I then tried getting it to make a directory /test and that did not work


then I simply ran in the default project the add-on apply and it worked..

**Comment by praveenkumar** [comment]
@PhillipDowney Can you share the content of addon (on a gist) so we can see if something is missing?

**Comment by PhillipDowney** [comment]
# Name: db-config
# Description: enables container permissions for Db
# Set Container groups permissive
ssh sudo setsebool -P container_manage_cgroup true
ssh sudo mkdir test1
echo Db Environment Set

**Comment by anjannath** [comment]
I think you are missing an equal in here.. 
sudo setsebool -P container_manage_cgroup true => `sudo setsebool -P container_manage_cgroup=true`

**Comment by PhillipDowney** [comment]
[dbaddon.txt](https://github.com/minishift/minishift/files/4316485/dbaddon.txt)

**Comment by PhillipDowney** [comment]
see above, this is the text from the add-on

**Comment by anjannath** [comment]
@PhillipDowney The add-on is working as expected.. do you get any errors when applying it?

```
$ minishift ssh
[docker@minishift ~]$ getsebool container_manage_cgroup
container_manage_cgroup --> off
[docker@minishift ~]$ logout
$ minishift addons apply test-addon
-- Applying addon 'test-addon':..
Db Environment Set
$ minishift ssh -- getsebool container_manage_cgroup
container_manage_cgroup --> on
```

**Comment by PhillipDowney** [comment]
no errors when applying it, works fine on the apply
... just not called on startup

**Comment by anjannath** [comment]
@PhillipDowney Apologies, i wrongly stated that `minishift addons enable` would apply the addon _always_ after `minishift start` it seems it only applies it when a new minishift instance is created not for stop=>start :(

you could maybe have a wrapper script that applies the addon for you, after `minishift start`.

**Comment by PhillipDowney** [comment]
ok, that makes sense now... the problem I face is if you restart Minishift with a service that needs privileges on cgroup...   you have to let it fail, apply the group privileges then either reinstall the service or in my case I can delete the pod to make it restart... would be good to be able to apply privileges like this when needed for restarts
