### ISSUE TITLE
Can't access exposed services from host machine (macOS)

### ISSUE THREAD

**Issue by sqshq** [minishift/minishift#3432]
### General information

  * Minishift version: v1.34.2+83ebaab
  * OS: macOS Catalina 10.15.3
  * Hypervisor: Hyper-V, VirtualBox, hyperkit (tried all of them)

### Steps to reproduce

I am using the following guide:
https://medium.com/ibm-cloud/autoscaling-applications-on-openshift-container-platform-3-11-with-custom-metrics-6e9c14474de3

  1. Create deployment
  2. Create service
  3. Perform `oc expose service sample-app`
  5. Make sure that everything looks correct in UI and I can do `curl localhost:8080` from console on NGINX pod:
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/6069066/76695051-8ac7fb00-6650-11ea-9e5a-4e26ff336eb8.png">
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/6069066/76695066-b1863180-6650-11ea-8603-d811519b5347.png">

  4. Click the route link to navigate to `http://sample-app-default.192.168.64.3.nip.io `

### Expected
Nginx welcome page

### Actual
Hanging for 10 seconds, and then shows "Safari can't find the server" page

**Comment by sqshq** [comment]
In the same time, I was able to access Nginx welcome page using port-forwarding:
`oc port-forward sample-app-674b6d4b6c-m4zx4 8888:8080`

**Comment by kefniark** [comment]
yes, nip.io seem to be down since few hours already (like ~6 hours)

if possible, using another service like xip.io should solve the problem

**Comment by sqshq** [comment]
oh, I see
Thank you, and looks like nip.io is up again, now it works.
