### ISSUE TITLE
FAIL E0324 12:17:31.074615   13452 start.go:494] Error starting the VM: Error configuring authorization on host: IP not found. Retrying.

### ISSUE THREAD

**Issue by vinayjapa** [minishift/minishift#3435]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / Hyper-V / VirtualBox / hyperkit

### Steps to reproduce

  1. minishift start

### Expected
Displaying the admin console ip address

### Actual

IP not found

### Logs
(minishift) Calling .GetSSHHostname
.(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
.(minishift) DBG | [stdout =====>] : fe80::215:5dff:fe38:139
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@fe80::215:5dff:fe38:139 -o IdentitiesOnly=yes -i C:\Users\****\.minishift\machines\minishift\id_rsa -p 22] C:\WINDOWS\System32\OpenSSH\ssh.exe <nil>}
About to run SSH command:
sudo mkdir -p /etc/docker
.SSH cmd err, output: <nil>:
(minishift) Calling .GetMachineName
(minishift) Calling .GetIP
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
.(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
(minishift) DBG | [stdout =====>] : fe80::215:5dff:fe38:139
(minishift) DBG |
Copying certs to the local machine directory...
(minishift) DBG | [stderr =====>] :
generating server cert: C:\Users\*****\.minishift\machines\server.pem ca-key=C:\Users\******\.minishift\certs\ca.pem private-key=C:\Users\*****\.minishift\certs\ca-key.pem org=******.minishift san=[fe80::215:5dff:fe38:139 localhost]
(minishift) Calling .GetSSHHostname
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
.(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
(minishift) DBG | [stdout =====>] : fe80::215:5dff:fe38:139
(minishift) DBG |
(minishift) Calling .GetSSHPort
(minishift) DBG | [stderr =====>] :
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@fe80::215:5dff:fe38:139 -o IdentitiesOnly=yes -i C:\Users\****\.minishift\machines\minishift\id_rsa -p 22] C:\WINDOWS\System32\OpenSSH\ssh.exe <nil>}
About to run SSH command:
sudo systemctl -f stop docker
..SSH cmd err, output: <nil>:
(minishift) Calling .GetSSHHostname
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
.(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
(minishift) DBG | [stdout =====>] : fe80::215:5dff:fe38:139
(minishift) DBG |
(minishift) Calling .GetSSHPort
(minishift) DBG | [stderr =====>] :
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@fe80::215:5dff:fe38:139 -o IdentitiesOnly=yes -i C:\Users\*****\.minishift\machines\minishift\id_rsa -p 22] C:\WINDOWS\System32\OpenSSH\ssh.exe <nil>}
About to run SSH command:
if [ ! -z "$(ip link show docker0)" ]; then sudo ip link delete docker0; fi
..SSH cmd err, output: <nil>:
Copying certs to the remote machine...
(minishift) Calling .GetSSHHostname
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
.(minishift) DBG | [stdout =====>] : fe80::215:5dff:fe38:139
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@fe80::215:5dff:fe38:139 -o IdentitiesOnly=yes -i C:\Users\****\.minishift\machines\minishift\id_rsa -p 22] C:\WINDOWS\System32\OpenSSH\ssh.exe <nil>}
About to run SSH command:
printf '%s' '-----BEGIN CERTIFICATE-----
MIIC3jCCAcagAwIBAgIRAMPIgZTtsMlBjoq/koF9cw8wDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEChMNSmFwYVZpbmF5VGVqYTAeFw0yMDAxMDIwOTQxMDBaFw0yMjEy
MTcwOTQxMDBaMBgxFjAUBgNVBAoTDUphcGFWaW5heVRlamEwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQCzAKMMhF/abu41E0yiX1My/k+AHiwsebzs4MXK
2t7t4QZownJ2bu0npB6kNsw0Znq+XQQxUNkmHf3Q+HWIy3iKXkGV585vQYJjVkEH
e0vQmGGPTeiFnhQkGmDF0IJzIM9V76a5vjgoiu/98K3HwFw5i4F/W2V/CphKkBVv
2Rd4VOarJ7tXqIUMpy+VEOg9GdfNFtRO6Jbvvnw01LsY7nnREDve6R9j1T3azrBz
MqBw08k19S/fNqlTQZuglV1Y9BgihGrkcf12Vj4SYXCvoXGA5rhPx93wEQipZtI2
WanC03F3F2u8XmMtALtyhiG4HQYC1m6w030aUVKfe/gQ/McjAgMBAAGjIzAhMA4G
A1UdDwEB/wQEAwICrDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IB
AQAQDK4DPwaXgefzy4iGZ0uKWsCLDJsu440wXctPCGaoGyL+dMKPwBpDnO/G+XPL
Zcj0RLDSQmU1aHmWeoLhfZxNVRnNwkSSsRYhdEwAI8WAorAhSSF/KfG0iHth19sc
dhO1dQhvSstDQKRiRQy3s7jMq3nI/UuCqCzlGV4hRAwe2HJZrO71RrYX1NeoagIV
aRvFoheSdjTDHL4SfcRBHBySZrjR8Ae2SXoOXhlxheWJlgo3TAgFs485FIBEVeS7
SifZoWAksp4w3zYfDYXSvaEPbLAQb5XsUfz8JZoCEcw4xEGeBt7WloJG9T+wTHy2
5Y+AzFtWd5oRuTEDod531Aar
-----END CERTIFICATE-----
' | sudo tee /etc/docker/ca.pem
.SSH cmd err, output: <nil>: -----BEGIN CERTIFICATE-----
MIIC3jCCAcagAwIBAgIRAMPIgZTtsMlBjoq/koF9cw8wDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEChMNSmFwYVZpbmF5VGVqYTAeFw0yMDAxMDIwOTQxMDBaFw0yMjEy
MTcwOTQxMDBaMBgxFjAUBgNVBAoTDUphcGFWaW5heVRlamEwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQCzAKMMhF/abu41E0yiX1My/k+AHiwsebzs4MXK
2t7t4QZownJ2bu0npB6kNsw0Znq+XQQxUNkmHf3Q+HWIy3iKXkGV585vQYJjVkEH
e0vQmGGPTeiFnhQkGmDF0IJzIM9V76a5vjgoiu/98K3HwFw5i4F/W2V/CphKkBVv
2Rd4VOarJ7tXqIUMpy+VEOg9GdfNFtRO6Jbvvnw01LsY7nnREDve6R9j1T3azrBz
MqBw08k19S/fNqlTQZuglV1Y9BgihGrkcf12Vj4SYXCvoXGA5rhPx93wEQipZtI2
WanC03F3F2u8XmMtALtyhiG4HQYC1m6w030aUVKfe/gQ/McjAgMBAAGjIzAhMA4G
A1UdDwEB/wQEAwICrDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IB
AQAQDK4DPwaXgefzy4iGZ0uKWsCLDJsu440wXctPCGaoGyL+dMKPwBpDnO/G+XPL
Zcj0RLDSQmU1aHmWeoLhfZxNVRnNwkSSsRYhdEwAI8WAorAhSSF/KfG0iHth19sc
dhO1dQhvSstDQKRiRQy3s7jMq3nI/UuCqCzlGV4hRAwe2HJZrO71RrYX1NeoagIV
aRvFoheSdjTDHL4SfcRBHBySZrjR8Ae2SXoOXhlxheWJlgo3TAgFs485FIBEVeS7
SifZoWAksp4w3zYfDYXSvaEPbLAQb5XsUfz8JZoCEcw4xEGeBt7WloJG9T+wTHy2
5Y+AzFtWd5oRuTEDod531Aar
-----END CERTIFICATE-----

(minishift) Calling .GetSSHHostname
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minishift ).state
(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minishift ).networkadapters[0]).ipaddresses[0]
.(minishift) DBG | [stdout =====>] :
(minishift) DBG | [stderr =====>] :
 FAIL E0324 12:17:31.074615   13452 start.go:494] Error starting the VM: Error configuring authorization on host: IP not found. Retrying.
Error starting the VM: Error configuring authorization on host: IP not found
You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.

Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by theDeployinator** [comment]
I had a very similar problem that I was finally able to resolve yesterday by doing the following.

1. Delete the broken cluster. On my successful run, I ran with --clear-cache flag, but I'm not sure it was required

   ```
   minishift delete --clear-cache
   ```

1. Use the "Default Switch" for Hyper-V. 
   ```
   minishift start --hyperv-virtual-switch "Default Switch"
   ```
   This may be specific to my use case, but I noticed there is a policy on my laptop that disables "Internet Connection Sharing". I believe that interfered with the "External" Hyper-V switch I was attempting to use previously.
   ![image](https://user-images.githubusercontent.com/27974655/77654287-e0e54a00-6f3e-11ea-9d41-2e66be7d768b.png)

1. Check that the Hyper-V daemons are running
After the machine has booted but before the "No IP Address" error, connect to the "minishift" machine using the Hyper-V manager. 
When the machine has finished booting, you should be at a log-in prompt. 
Log-in as the user `root` with password `centos`.

   You can confirm that the Hyper-V daemons are running.

   ```
   systemctl --all | grep -i hyperv
   ```
   ![image](https://user-images.githubusercontent.com/27974655/77661160-438f1380-6f48-11ea-9d3c-bfb9719ef8e2.png)

   If they are not running, enable and start the Hyper-V daemons. Unfortunately, I did not check to see if the hyperv services were running before attempting to start them, so I'm not sure if this step had any impact.

   ```
   systemctl enable  hypervkvpd.service
   systemctl start  hypervkvpd.service
   systemctl enable  hypervvssd.service
   systemctl start  hypervvssd.service
   ```

After this startup ran for a while longer until eventually completing successfully.

I'd be interested to know if these steps were able to help!

**Comment by vinayjapa** [comment]
@theDeployinator I tried with default switch, it worked...Thanks a ton !!
