### ISSUE TITLE
minishift 1.34.2 starting failed(Error:- Checking if KVM driver is installed ... FAIL)

### ISSUE THREAD

**Issue by veera2019** [minishift/minishift#3436]
Hi Team,
I am installing Minishit in redhat 7.7 AWS Ec2 instance , i did KVM driver installation still it's failing in that step only.
minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... FAIL
   See the 'Setting Up the Virtualization Environment' topic (https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html) for more information

any suggestions on this issue?

**Comment by thegaintserver** [comment]
I have the same issue, I can't figure it out.
Tried many things but doesn't work. 
Not sure if it is OS related or any version or any package related but I tried install quem, kvm , libvirtd but still same issue
Please help

**Comment by dfr0** [comment]
I have the same issue :(

**Comment by akha666** [comment]
You need to install docker-machine-kvm
