### ISSUE TITLE
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:

### ISSUE THREAD

**Issue by ehmusman** [minishift/minishift#3440]
### General information
i am installing kubernetese in ubuntu 18.04. first i installed kubect, then virtual box than minikube. when i check the version of kubectl it gives the following error..

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / Hyper-V / VirtualBox / hyperkit

error: Missing or incomplete configuration info.  Please point to an existing, complete config file:

  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by Achiria** [comment]
You might not have the minikube setup. Try `minikube start`. After running, you should see something like `Done! kubectl is now configured to use "minikube"`. Then try `kubectl version`. 

If you only want the version of the client, run `kubectl version --client`.

**Comment by Ruimingwang** [comment]
you can run this command : export KUBERNETES_MASTER=http://127.0.0.1:8080    on master node
