### ISSUE TITLE
Minishift - unable to loging to cluster: installation error "certificate signed by unknown authority"

### ISSUE THREAD

**Issue by MoonCricket** [minishift/minishift#3442]
Hi team, I am facing this installation error on Minishift. It always shows the "**error: **The** server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
Error during post cluster up configuration: Unable to login to cluster**"

I tired some solutions provided in similar post as below: 
$ minishift delete --clear-cache
$rm -r C:\Users\<User_name>\.kube

However, this problem still exist. Could you please help on that? Thank you very much!

### General information
  * Minishift version: 1.34.2 windows
  * OS:  Windows
  * Hypervisor: VirtualBox 

### Steps to reproduce

  1.minishift.exe start --vm-driver virtualbox 

### Expected
no errors

### Actual
c:\minishift-1.34.2-windows-amd64>minishift.exe start --vm-driver virtualbox
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.11.0'
 53.59 MiB / 53.59 MiB [===================================================================================] 100.00% 0s-- Downloading OpenShift v3.11.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.16.0/minishift-centos7.iso'
 370.00 MiB / 370.00 MiB [=================================================================================] 100.00% 0s
-- Starting Minishift VM .............................. OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... OK
   Importing 'openshift/origin-control-plane:v3.11.0' . CACHE MISS
   Importing 'openshift/origin-docker-registry:v3.11.0' . CACHE MISS
   Importing 'openshift/origin-haproxy-router:v3.11.0' . CACHE MISS
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Pulling the OpenShift Container Image ....................... OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ..............................................................................
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Pulling image openshift/origin-cli:v3.11.0
E0425 08:44:45.443081    2667 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11.0 anonymously
Image pull complete
Pulling image openshift/origin-node:v3.11.0
E0425 08:44:50.755557    2667 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-node:v3.11.0 anonymously
Pulled 5/6 layers, 85% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.99.103 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0425 08:45:17.799233    2667 config.go:40] Running "create-master-config"
I0425 08:45:20.659495    2667 config.go:46] Running "create-node-config"
I0425 08:45:22.271979    2667 flags.go:30] Running "create-kubelet-flags"
I0425 08:45:22.679099    2667 run_kubelet.go:49] Running "start-kubelet"
I0425 08:45:22.886147    2667 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I0425 08:46:40.906622    2667 interface.go:26] Installing "kube-proxy" ...
I0425 08:46:40.907598    2667 interface.go:26] Installing "kube-dns" ...
I0425 08:46:40.907628    2667 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I0425 08:46:40.907635    2667 interface.go:26] Installing "openshift-apiserver" ...
I0425 08:46:40.907726    2667 apply_template.go:81] Installing "openshift-apiserver"
I0425 08:46:40.908557    2667 apply_template.go:81] Installing "kube-proxy"
I0425 08:46:40.908965    2667 apply_template.go:81] Installing "kube-dns"
I0425 08:46:40.909162    2667 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I0425 08:46:47.765427    2667 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
I0425 08:49:42.816909    2667 run_self_hosted.go:242] openshift-apiserver available
I0425 08:49:42.817658    2667 interface.go:26] Installing "openshift-controller-manager" ...
I0425 08:49:42.817679    2667 apply_template.go:81] Installing "openshift-controller-manager"
I0425 08:49:47.335121    2667 interface.go:41] Finished installing "openshift-controller-manager"
Adding default OAuthClient redirect URIs ...
Adding centos-imagestreams ...
Adding router ...
Adding sample-templates ...
Adding registry ...
Adding persistent-volumes ...
Adding web-console ...
I0425 08:49:47.357414    2667 interface.go:26] Installing "centos-imagestreams" ...
I0425 08:49:47.357423    2667 interface.go:26] Installing "openshift-router" ...
I0425 08:49:47.357430    2667 interface.go:26] Installing "sample-templates" ...
I0425 08:49:47.357436    2667 interface.go:26] Installing "openshift-image-registry" ...
I0425 08:49:47.357441    2667 interface.go:26] Installing "persistent-volumes" ...
I0425 08:49:47.357450    2667 interface.go:26] Installing "openshift-web-console-operator" ...
I0425 08:49:47.357747    2667 apply_template.go:81] Installing "openshift-web-console-operator"
I0425 08:49:47.357903    2667 apply_list.go:67] Installing "centos-imagestreams"
I0425 08:49:47.358513    2667 interface.go:26] Installing "sample-templates/mariadb" ...
I0425 08:49:47.358523    2667 interface.go:26] Installing "sample-templates/postgresql" ...
I0425 08:49:47.358530    2667 interface.go:26] Installing "sample-templates/rails quickstart" ...
I0425 08:49:47.358539    2667 interface.go:26] Installing "sample-templates/jenkins pipeline ephemeral" ...
I0425 08:49:47.358546    2667 interface.go:26] Installing "sample-templates/sample pipeline" ...
I0425 08:49:47.358552    2667 interface.go:26] Installing "sample-templates/mongodb" ...
I0425 08:49:47.358558    2667 interface.go:26] Installing "sample-templates/mysql" ...
I0425 08:49:47.358564    2667 interface.go:26] Installing "sample-templates/cakephp quickstart" ...
I0425 08:49:47.358571    2667 interface.go:26] Installing "sample-templates/dancer quickstart" ...
I0425 08:49:47.358578    2667 interface.go:26] Installing "sample-templates/django quickstart" ...
I0425 08:49:47.358584    2667 interface.go:26] Installing "sample-templates/nodejs quickstart" ...
I0425 08:49:47.358625    2667 apply_list.go:67] Installing "sample-templates/nodejs quickstart"
I0425 08:49:47.359476    2667 apply_list.go:67] Installing "sample-templates/mariadb"
I0425 08:49:47.359595    2667 apply_list.go:67] Installing "sample-templates/postgresql"
I0425 08:49:47.359695    2667 apply_list.go:67] Installing "sample-templates/rails quickstart"
I0425 08:49:47.359833    2667 apply_list.go:67] Installing "sample-templates/jenkins pipeline ephemeral"
I0425 08:49:47.359960    2667 apply_list.go:67] Installing "sample-templates/sample pipeline"
I0425 08:49:47.360055    2667 apply_list.go:67] Installing "sample-templates/mongodb"
I0425 08:49:47.360148    2667 apply_list.go:67] Installing "sample-templates/mysql"
I0425 08:49:47.360241    2667 apply_list.go:67] Installing "sample-templates/cakephp quickstart"
I0425 08:49:47.360339    2667 apply_list.go:67] Installing "sample-templates/dancer quickstart"
I0425 08:49:47.360459    2667 apply_list.go:67] Installing "sample-templates/django quickstart"
I0425 08:50:07.141810    2667 interface.go:41] Finished installing "sample-templates/mariadb" "sample-templates/postgresql" "sample-templates/rails quickstart" "sample-templates/jenkins pipeline ephemeral" "sample-templates/sample pipeline" "sample-templates/mongodb" "sample-templates/mysql" "sample-templates/cakephp quickstart" "sample-templates/dancer quickstart" "sample-templates/django quickstart" "sample-templates/nodejs quickstart"
I0425 08:51:37.789193    2667 interface.go:41] Finished installing "centos-imagestreams" "openshift-router" "sample-templates" "openshift-image-registry" "persistent-volumes" "openshift-web-console-operator"
Login to server ...
Creating initial project "myproject" ...
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.103:8443/console

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

error: **The** server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
Error during post cluster up configuration: Unable to login to cluster

c:\minishift-1.34.2-windows-amd64>

### Logs

c:\minishift-1.34.2-windows-amd64>minishift start --show-libmachine-logs -v5
-- minishift version: v1.34.2+83ebaab
-- Starting profile 'minishift'
Found binary path at minishift.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:50868
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minishift --machinereadable
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | name="minishift"
(minishift) DBG | groups="/"
(minishift) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
(minishift) DBG | UUID="f317ff6b-6496-48a5-b8bd-2a3bcd3b071e"
The 'minishift' VM is already running.
(minishift) DBG | CfgFile="C:\\Users\\YUCHEN\\.minishift\\machines\\minishift\\minishift\\minishift.vbox"

（You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.）

**Comment by AvinashSingh299** [comment]
Hello Team,

I am facing same issue on MAC but I am able to login to the OKD cluster

**Error**: error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.

General information
* Minishift version:  v1.34.2+83ebaab
* OS: Mac
* Hypervisor: hyperkit

**Steps to reproduce:** sudo minishift start --vm-driver hyperkit --network-nameserver 8.8.8.8

**Expected**
no errors

**Actual:**
`bash-3.2$ sudo minishift start --vm-driver hyperkit --network-nameserver 8.8.8.8
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperkit' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperkit' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .............. OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... OK
   Importing 'openshift/origin-control-plane:v3.11.0'  CACHE MISS
   Importing 'openshift/origin-docker-registry:v3.11.0' . CACHE MISS
   Importing 'openshift/origin-haproxy-router:v3.11.0' . CACHE MISS
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Pulling the OpenShift Container Image ........... OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ..........................................................
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Pulling image openshift/origin-cli:v3.11.0
E0425 18:37:17.104664    2388 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11.0 anonymously
Image pull complete
Pulling image openshift/origin-node:v3.11.0
E0425 18:37:17.869640    2388 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-node:v3.11.0 anonymously
Pulled 5/6 layers, 89% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.64.4 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0425 18:37:28.056792    2388 config.go:40] Running "create-master-config"
I0425 18:37:30.772831    2388 config.go:46] Running "create-node-config"
I0425 18:37:31.968482    2388 flags.go:30] Running "create-kubelet-flags"
I0425 18:37:32.323622    2388 run_kubelet.go:49] Running "start-kubelet"
I0425 18:37:32.482393    2388 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I0425 18:37:55.507185    2388 interface.go:26] Installing "kube-proxy" ...
I0425 18:37:55.507849    2388 interface.go:26] Installing "kube-dns" ...
I0425 18:37:55.507856    2388 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I0425 18:37:55.507861    2388 interface.go:26] Installing "openshift-apiserver" ...
I0425 18:37:55.507920    2388 apply_template.go:81] Installing "openshift-apiserver"
I0425 18:37:55.507922    2388 apply_template.go:81] Installing "kube-dns"
I0425 18:37:55.508192    2388 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I0425 18:37:55.509048    2388 apply_template.go:81] Installing "kube-proxy"
I0425 18:37:59.478234    2388 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
I0425 18:40:34.501315    2388 run_self_hosted.go:242] openshift-apiserver available
I0425 18:40:34.502136    2388 interface.go:26] Installing "openshift-controller-manager" ...
I0425 18:40:34.502155    2388 apply_template.go:81] Installing "openshift-controller-manager"
I0425 18:40:37.619656    2388 interface.go:41] Finished installing "openshift-controller-manager"
Adding default OAuthClient redirect URIs ...
Adding web-console ...
Adding sample-templates ...
Adding persistent-volumes ...
Adding centos-imagestreams ...
Adding registry ...
Adding router ...
I0425 18:40:37.636072    2388 interface.go:26] Installing "openshift-web-console-operator" ...
I0425 18:40:37.636081    2388 interface.go:26] Installing "sample-templates" ...
I0425 18:40:37.636085    2388 interface.go:26] Installing "persistent-volumes" ...
I0425 18:40:37.636091    2388 interface.go:26] Installing "centos-imagestreams" ...
I0425 18:40:37.636096    2388 interface.go:26] Installing "openshift-image-registry" ...
I0425 18:40:37.636100    2388 interface.go:26] Installing "openshift-router" ...
I0425 18:40:37.640702    2388 apply_template.go:81] Installing "openshift-web-console-operator"
I0425 18:40:37.642176    2388 interface.go:26] Installing "sample-templates/jenkins pipeline ephemeral" ...
I0425 18:40:37.642216    2388 interface.go:26] Installing "sample-templates/sample pipeline" ...
I0425 18:40:37.642222    2388 interface.go:26] Installing "sample-templates/mariadb" ...
I0425 18:40:37.642227    2388 interface.go:26] Installing "sample-templates/postgresql" ...
I0425 18:40:37.642232    2388 interface.go:26] Installing "sample-templates/django quickstart" ...
I0425 18:40:37.642237    2388 interface.go:26] Installing "sample-templates/rails quickstart" ...
I0425 18:40:37.642246    2388 interface.go:26] Installing "sample-templates/nodejs quickstart" ...
I0425 18:40:37.642250    2388 interface.go:26] Installing "sample-templates/mongodb" ...
I0425 18:40:37.642255    2388 interface.go:26] Installing "sample-templates/mysql" ...
I0425 18:40:37.642259    2388 interface.go:26] Installing "sample-templates/cakephp quickstart" ...
I0425 18:40:37.642264    2388 interface.go:26] Installing "sample-templates/dancer quickstart" ...
I0425 18:40:37.642321    2388 apply_list.go:67] Installing "sample-templates/dancer quickstart"
I0425 18:40:37.644194    2388 apply_list.go:67] Installing "centos-imagestreams"
I0425 18:40:37.645535    2388 apply_list.go:67] Installing "sample-templates/jenkins pipeline ephemeral"
I0425 18:40:37.647771    2388 apply_list.go:67] Installing "sample-templates/mysql"
I0425 18:40:37.647938    2388 apply_list.go:67] Installing "sample-templates/sample pipeline"
I0425 18:40:37.648061    2388 apply_list.go:67] Installing "sample-templates/mariadb"
I0425 18:40:37.648191    2388 apply_list.go:67] Installing "sample-templates/postgresql"
I0425 18:40:37.648371    2388 apply_list.go:67] Installing "sample-templates/django quickstart"
I0425 18:40:37.648542    2388 apply_list.go:67] Installing "sample-templates/rails quickstart"
I0425 18:40:37.648725    2388 apply_list.go:67] Installing "sample-templates/nodejs quickstart"
I0425 18:40:37.648834    2388 apply_list.go:67] Installing "sample-templates/mongodb"
I0425 18:40:37.651448    2388 apply_list.go:67] Installing "sample-templates/cakephp quickstart"
I0425 18:40:52.832948    2388 interface.go:41] Finished installing "sample-templates/jenkins pipeline ephemeral" "sample-templates/sample pipeline" "sample-templates/mariadb" "sample-templates/postgresql" "sample-templates/django quickstart" "sample-templates/rails quickstart" "sample-templates/nodejs quickstart" "sample-templates/mongodb" "sample-templates/mysql" "sample-templates/cakephp quickstart" "sample-templates/dancer quickstart"
I0425 18:41:29.458509    2388 interface.go:41] Finished installing "openshift-web-console-operator" "sample-templates" "persistent-volumes" "centos-imagestreams" "openshift-image-registry" "openshift-router"
Login to server ...
Creating initial project "myproject" ...
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.4:8443/console

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin


error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
Error during post cluster up configuration: Unable to login to cluster`
