### ISSUE TITLE
E0529 while starting minishift

### ISSUE THREAD

**Issue by PaioGZ** [minishift/minishift#3449]
Hi,

I'm getting this message when I start minishift. Do anyone had same issue? Any help will appreciate.

:~/minishift$ minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM .... FAIL E0529 15:33:02.727461   15145 start.go:494] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
Error starting the VM: Error getting the state for host: unexpected EO

### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / Hyper-V / VirtualBox / hyperkit

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by anjannath** [comment]
It could be an issue with the hypervisor, make sure virtualization is working and you can create VMs
