### ISSUE TITLE
Unable to run minishift on windows 10 using virtual box

### ISSUE THREAD

**Issue by surensinghkhatana** [minishift/minishift#3455]
### General information

  * Minishift version: 1.34.2
  * OS: Windows
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. Enabled the virtualization in windows and disabled Hyper-V since I am using virtual box
  2.  Downloaded the minishift exe
  3.  Ran minishift start --show-libmachine-logs -v5 and also tried minishift start --vm-driver virtualbox with admin permissions
 
Please note that I don't have docker toolbox installed on the host windows , is that needed ?
I have read other posts about the similar issue but none helped.
### Expected
Openshift cluster to be up and running.

### Actual
. FAIL E0614 09:13:21.654685   21316 start.go:494] **Error starting the VM:** Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.110:2376": dial tcp 192.168.99.110:2376: connectex: **An attempt was made to access a socket in a way forbidden by its access permissions**.
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.
. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.110:2376": dial tcp 192.168.99.110:2376: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.

### Logs
Detailed logs available here : https://gist.github.com/surensinghkhatana/791f5f0f7284b0c5398841b578483e75

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by surensinghkhatana** [comment]
After setting the static ip _minishift ip --set-static_  , I am able to move forward but now getting the following error :

> $ ./minishift.exe start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ......................... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 15% used OK
-- Writing current configuration for static assignment of IP address ... OK
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster .....................................
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.99.113 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0614 08:32:30.498729    2559 flags.go:30] Running "create-kubelet-flags"
I0614 08:32:30.912117    2559 run_kubelet.go:49] Running "start-kubelet"
I0614 08:32:31.212166    2559 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I0614 08:32:52.228462    2559 interface.go:26] Installing "kube-proxy" ...
I0614 08:32:52.228473    2559 interface.go:26] Installing "kube-dns" ...
I0614 08:32:52.228479    2559 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I0614 08:32:52.228484    2559 interface.go:26] Installing "openshift-apiserver" ...
I0614 08:32:52.228514    2559 apply_template.go:81] Installing "openshift-apiserver"
I0614 08:32:52.229214    2559 apply_template.go:81] Installing "kube-proxy"
I0614 08:32:52.230013    2559 apply_template.go:81] Installing "kube-dns"
I0614 08:32:52.230123    2559 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I0614 08:33:29.350545    2559 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
I0614 08:34:17.384449    2559 run_self_hosted.go:242] openshift-apiserver available
I0614 08:34:17.385050    2559 interface.go:26] Installing "openshift-controller-manager" ...
I0614 08:34:17.385076    2559 apply_template.go:81] Installing "openshift-controller-manager"
I0614 08:34:20.442089    2559 interface.go:41] Finished installing "openshift-controller-manager"
Adding default OAuthClient redirect URIs ...
Adding registry ...
Adding router ...
Adding web-console ...
Adding centos-imagestreams ...
Adding sample-templates ...
Adding persistent-volumes ...
I0614 08:34:20.454159    2559 interface.go:26] Installing "openshift-image-registry" ...
I0614 08:34:20.454167    2559 interface.go:26] Installing "openshift-router" ...
I0614 08:34:20.454173    2559 interface.go:26] Installing "openshift-web-console-operator" ...
I0614 08:34:20.454178    2559 interface.go:26] Installing "centos-imagestreams" ...
I0614 08:34:20.454184    2559 interface.go:26] Installing "sample-templates" ...
I0614 08:34:20.454188    2559 interface.go:26] Installing "persistent-volumes" ...
I0614 08:34:20.455329    2559 apply_template.go:81] Installing "openshift-web-console-operator"
I0614 08:34:20.455505    2559 apply_list.go:67] Installing "centos-imagestreams"
I0614 08:34:20.455630    2559 interface.go:26] Installing "sample-templates/postgresql" ...
I0614 08:34:20.455637    2559 interface.go:26] Installing "sample-templates/cakephp quickstart" ...
I0614 08:34:20.455643    2559 interface.go:26] Installing "sample-templates/nodejs quickstart" ...
I0614 08:34:20.455649    2559 interface.go:26] Installing "sample-templates/jenkins pipeline ephemeral" ...
I0614 08:34:20.455655    2559 interface.go:26] Installing "sample-templates/sample pipeline" ...
I0614 08:34:20.455660    2559 interface.go:26] Installing "sample-templates/mongodb" ...
I0614 08:34:20.455665    2559 interface.go:26] Installing "sample-templates/mysql" ...
I0614 08:34:20.455670    2559 interface.go:26] Installing "sample-templates/django quickstart" ...
I0614 08:34:20.455676    2559 interface.go:26] Installing "sample-templates/rails quickstart" ...
I0614 08:34:20.455683    2559 interface.go:26] Installing "sample-templates/mariadb" ...
I0614 08:34:20.455688    2559 interface.go:26] Installing "sample-templates/dancer quickstart" ...
I0614 08:34:20.455723    2559 apply_list.go:67] Installing "sample-templates/dancer quickstart"
I0614 08:34:20.455869    2559 apply_list.go:67] Installing "sample-templates/postgresql"
I0614 08:34:20.455992    2559 apply_list.go:67] Installing "sample-templates/cakephp quickstart"
I0614 08:34:20.456080    2559 apply_list.go:67] Installing "sample-templates/nodejs quickstart"
I0614 08:34:20.456159    2559 apply_list.go:67] Installing "sample-templates/jenkins pipeline ephemeral"
I0614 08:34:20.456250    2559 apply_list.go:67] Installing "sample-templates/sample pipeline"
I0614 08:34:20.456334    2559 apply_list.go:67] Installing "sample-templates/mongodb"
I0614 08:34:20.456472    2559 apply_list.go:67] Installing "sample-templates/mysql"
I0614 08:34:20.456566    2559 apply_list.go:67] Installing "sample-templates/django quickstart"
I0614 08:34:20.456648    2559 apply_list.go:67] Installing "sample-templates/rails quickstart"
I0614 08:34:20.456726    2559 apply_list.go:67] Installing "sample-templates/mariadb"
I0614 08:34:31.297024    2559 interface.go:41] Finished installing "sample-templates/postgresql" "sample-templates/cakephp quickstart" "sample-templates/nodejs quickstart" "sample-templates/jenkins pipeline ephemeral" "sample-templates/sample pipeline" "sample-templates/mongodb" "sample-templates/mysql" "sample-templates/django quickstart" "sample-templates/rails quickstart" "sample-templates/mariadb" "sample-templates/dancer quickstart"
I0614 08:34:32.257009    2559 interface.go:41] Finished installing "openshift-image-registry" "openshift-router" "openshift-web-console-operator" "centos-imagestreams" "sample-templates" "persistent-volumes"
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.113:8443/console


Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to the kube config 'C:\Users\surendra.khatana\.minishift\machines\minishift_kubeconfig' does not exist

**Comment by surensinghkhatana** [comment]
Tried the following but it didn't help.
```
minishift stop
minishift delete --force --clear-cache
mv ~/.kube ~/.kube.old
minishift start
```

**Comment by veenarm** [comment]
I was getting this too, i removed all configs
```
rm -rf ~/.kube
rm -rf ~/.minishift
minishift start --vm-driver virtualbox
```
seemed to fix it

**Comment by surensinghkhatana** [comment]
Unfortunately , that didn't help me at all. I continue to get the same error ...
