### ISSUE TITLE
Che add-on update

### ISSUE THREAD

**Issue by anjannath** [minishift/minishift#3457]
This issue is to track if we need to update the che add-on? The current che server image is 7.7.0 however there are tags available for more recent versions at https://quay.io/repository/eclipse/che-server?tab=tags

/cc @sleshchenko

**Comment by sleshchenko** [comment]
I believe minishift-add is deprecated in favor of Che Operator that is available as an installer in chectl[1]. So, there are no any plans to update Che Minishift Addon.

[1] https://github.com/che-incubator/chectl

cc @tolusha @l0rd

**Comment by anjannath** [comment]
Okay, thanks @sleshchenko for the information, but if the Che add-on is deprecated in favor of the operator, maybe we should communicated this to the user and ask them to try to install the operator or we put up instructions on how to do that?

**Comment by sleshchenko** [comment]
^^ @tolusha
