### ISSUE TITLE
Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"

### ISSUE THREAD

**Issue by richardgohcr** [minishift/minishift#3474]
I am currently trying to set up minishift on my Dell XPS 15 laptop running Windows 10 home. I have also previously installed Docker desktop for windows with no problems. However, I am facing the error message "Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"

I have tried disabling and re-enabling virtualisation on my system BIOS, but to no avail. Anyone facing this issue on Windows 10 Home as well?
### General information

  * Minishift version:  v1.34.2
  * OS: Windows 10 Home 2004
  * Hypervisor:  VirtualBox

`PS C:\Users\Richard> minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://mirror.openshift.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.232' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.232' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ..... FAIL E0831 23:15:47.758000   20152 start.go:494] Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory". Retrying.
Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"`

**Comment by anjannath** [comment]
On windows, enabling hyperv along with virtualbox may cause issues, are you sure that hyperv is also not enabled in the same time?

**Comment by miroslav-beranic** [comment]
I was looking for this for days. I only have VBox installed and Minishift fails to start, with same error as reported. On same workstation, in dual boot I have Fedora, where Minishift works as expected.

I have VT-X enabled in BIOS ( in can not be disabled 🍔 ) and I have VBox 6.1.

**Comment by bintegra** [comment]
Hi all,

it turned out Minishift is complaining about missing Hyper-V, regardless configuration to use VBox.

```
 minishift.exe start  --show-libmachine-logs --logtostderr -v5 --vm-driver virtualbox
-- minishift version: v1.34.3+4b58f89
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....Found binary path at C:\Minishift\bin\minishift.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:64675
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetMachineName
(minishift) Calling .DriverName
Reading certificate data from C:\Minishift\certs\ca.pem
Decoding PEM data...
Parsing certificate...
Reading certificate data from C:\Minishift\certs\cert.pem
Decoding PEM data...
Parsing certificate...
Running pre-create checks...
(minishift) Calling .PreCreateCheck
(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | 6.1.14r140239
(minishift) DBG | }
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | Hyper-V is not installed.
. FAIL E1020 13:03:19.726727    3972 start.go:499] Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory". Retrying.
Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"
```

**Comment by p4qu1t0** [comment]
1.-C:\Program Files\Oracle\VirtualBox
2.-VBoxManage list vms
3.-VBoxManage modifyvm "{VM-Name} or {ID-VM}" --nested-hw-virt on

**Comment by CallisteH** [comment]
Same issue there. 
I'm on Windows10 home, so I do not have Hyper-V installed, according to this [doc](https://docs.microsoft.com/fr-fr/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v)

VirtualBox is installed and can run VM, but Minishift stills wants hyper-v
```$ minishift start --show-libmachine-logs --logtostderr -v5 --vm-driver virtualbox
-- minishift version: v1.34.3+cb967be
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://mirror.openshift.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.286' is valid ... SKIP
-- Checking if requested OpenShift version 'v3.11.286' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....Found binary path at C:\Users\calli\minishift\minishift.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:64693
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetMachineName
(minishift) Calling .DriverName
Reading certificate data from C:\Users\calli\.minishift\certs\ca.pem
Decoding PEM data...
Parsing certificate...
Reading certificate data from C:\Users\calli\.minishift\certs\cert.pem
Decoding PEM data...
Parsing certificate...
Running pre-create checks...
(minishift) Calling .PreCreateCheck
(minishift) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | 6.1.18r142142
(minishift) DBG | }
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | Hyper-V is not installed.
. FAIL E0127 10:08:01.569914   10892 start.go:499] Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory". Retrying.
Error starting the VM: Error creating the VM. Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"```
`

@p4qu1t0 Minishift seems to instanciate himself the VM on virtualbox so I do not have any VM in my list after running `VBoxManage list vms`

**Comment by mrballcb** [comment]
I struggled with this same error while trying to get minishift to create VM's in my freshly installed VirtualBox (and rebooted).  I created a test linux VM,, and saw the nested VT-x setting was grayed out for me in VirtualBox.  All of the instructions say to make sure that Hyper-V is turned off because it puts some kind of lock on on the VT-X such that VirtualBox can't share it.  I did not have Hyper-V enabled on my Win10 Home machine, however I did have "Virtual Machine Platform" enabled.

![both-features-off-in-win10](https://user-images.githubusercontent.com/194079/106324594-47598980-622e-11eb-9604-24b2ae402d2b.png)

After turning off both of them, minishift start began working.  (It didn't succeed all the way, but I'm still researching.)

**Comment by gbraad** [comment]
Make sure virtualization is enabled from the BIOS and that the hypervisor has exclusive access to the VTX estension; don't mix hypervisors on the same machine.

**Comment by gbraad** [comment]
> it turned out Minishift is complaining about missing Hyper-V, regardless configuration to use VBox.

make sure to remove any previous VMs, and use the driver option to force the selection on start

**Comment by mihailmanoli** [comment]
> I did not have Hyper-V enabled on my Win10 Home machine, however I did have "Virtual Machine Platform" enabled.

This saved my day

**Comment by adarshvyas99** [comment]
![image](https://user-images.githubusercontent.com/44130568/125998193-89498218-c9d6-43d9-afa3-a6ff7ca48a11.png)

**Comment by adarshvyas99** [comment]
I am getting the same

**Comment by gbraad** [comment]
This issue is all over the place with virtualbox, hyperv, and no extensions
enabled.

Please check your bios before you try minishift/CDK. After this, see if you
have enabled or installed the hypervisor and it works outside the use of
minishift. If you can start a demo VM, there is no need to try minishift.

If your hypervisor works, try a delete and make sure the hypervisor is
correct set as config. On start, collecta log. Check the issue tracker for
the same platform and hypervisor... And I'd this does not yield any
results. File a new issue.

**Comment by mahmud255** [comment]
> I struggled with this same error while trying to get minishift to create VM's in my freshly installed VirtualBox (and rebooted). I created a test linux VM,, and saw the nested VT-x setting was grayed out for me in VirtualBox. All of the instructions say to make sure that Hyper-V is turned off because it puts some kind of lock on on the VT-X such that VirtualBox can't share it. I did not have Hyper-V enabled on my Win10 Home machine, however I did have "Virtual Machine Platform" enabled.
> 
> ![both-features-off-in-win10](https://user-images.githubusercontent.com/194079/106324594-47598980-622e-11eb-9604-24b2ae402d2b.png)
> 
> After turning off both of them, minishift start began working. (It didn't succeed all the way, but I'm still researching.) EDIT: Yes it did succeed all the way - I mistook some of the debug output as failures, when it actually is "keep trying to connect to do something until it succeeds".

Thanks a lot. It works for me :)
