### ISSUE TITLE
Issue 3232 closed without resolution

### ISSUE THREAD

**Issue by nhojpatrick** [minishift/minishift#3476]
See #3232, or reopen #3232 as it's stable because the people reporting the issue don't know the correct documentation. So the people that know minishift need to correct the documentation. Issue was created April 2019, does redhat not care if minishift works on a mac using homebrew as per their own documentation.

Documentation still produces errors, so still can't install minishift and install docker-machine-driver-xhyve as per the documentation.

Did anyone test the minishift commands before documenting them?

**Comment by anjannath** [comment]
Closing this #3232 is reopened
