### ISSUE TITLE
minishift install failed on macOS big sur

### ISSUE THREAD

**Issue by sunnypandas** [minishift/minishift#3494]
### General information

  * Minishift version: v1.34.3+4b58f89
  * OS: macOS big sur
  * Hypervisor: hyperkit

### Steps to reproduce

  1. minishift delete 
  2. minishift start --show-libmachine-logs -v5

### Expected
minishift starting successfully.

### Actual
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary Error: open /var/db/dhcpd_leases: no such file or directory

### Logs

-- minishift version: v1.34.3+4b58f89
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperkit' is supported on this platform ... OK
-- Checking if hyperkit is installed ... 
   Hyperkit is available at /usr/local/bin/hyperkit
   Checking for setuid bit ... OK
-- Checking if hyperkit driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-hyperkit
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperkit' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:60951
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetMachineName
(minishift) Calling .DriverName
Reading certificate data from /Users/sunpanpan/.minishift/certs/ca.pem
Decoding PEM data...
Parsing certificate...
Reading certificate data from /Users/sunpanpan/.minishift/certs/cert.pem
Decoding PEM data...
Parsing certificate...
Running pre-create checks...
(minishift) Calling .PreCreateCheck
(minishift) Calling .GetConfigRaw
Creating machine...
(minishift) Calling .Create
(minishift) Downloading /Users/sunpanpan/.minishift/cache/boot2docker.iso from file:///Users/sunpanpan/.minishift/cache/iso/centos/v1.17.0/minishift-centos7.iso...
(minishift) DBG | 2020/11/30 22:16:07 [INFO] Creating ssh key...
(minishift) DBG | 2020/11/30 22:16:07 [INFO] Creating raw disk image...
(minishift) DBG | Writing magic tar header
(minishift) DBG | Writing SSH key tar header
(minishift) DBG | Mounting boot2docker.iso
(minishift) DBG | executing: &{/usr/bin/hdiutil [hdiutil attach /Users/sunpanpan/.minishift/machines/minishift/boot2docker.iso -mountpoint /Users/sunpanpan/.minishift/machines/minishift/b2d-image] []  <nil> 0xc42000e018 0xc42000e020 [] <nil> <nil> <nil> <nil> <nil> false [] [] [] [] <nil> <nil>} attach /Users/sunpanpan/.minishift/machines/minishift/boot2docker.iso -mountpoint /Users/sunpanpan/.minishift/machines/minishift/b2d-image
(minishift) /dev/disk3                                                  /Users/sunpanpan/.minishift/machines/minishift/b2d-image
(minishift) DBG | Extracting Kernel Options...
(minishift) DBG | Extracted Options "initrd=initrd0.img root=live:CDLABEL=minishift-centos7 rootfstype=auto ro rd.live.image quiet no_timer_check console=ttyS0 console=tty0 net.ifnames=0 biosdevname=0 rhgb rd.luks=0 rd.md=0 rd.dm=0 "
(minishift) DBG | Extracting /Users/sunpanpan/.minishift/machines/minishift/b2d-image/isolinux/vmlinuz0 into /Users/sunpanpan/.minishift/machines/minishift/vmlinuz0
(minishift) DBG | Extracting /Users/sunpanpan/.minishift/machines/minishift/b2d-image/isolinux/initrd0.img into /Users/sunpanpan/.minishift/machines/minishift/initrd0.img
(minishift) DBG | Unmounting boot2docker.iso
(minishift) DBG | executing: &{/usr/bin/hdiutil [hdiutil detach /Users/sunpanpan/.minishift/machines/minishift/b2d-image] []  <nil> 0xc42000e018 0xc42000e020 [] <nil> <nil> <nil> <nil> <nil> false [] [] [] [] <nil> <nil>} detach /Users/sunpanpan/.minishift/machines/minishift/b2d-image
(minishift) "disk3" ejected.
(minishift) Using UUID 348d2c5c-330e-11eb-ad37-acde48001122
(minishift) Generated MAC de:47:cc:df:8:9e
(minishift) Starting with cmdline: initrd=initrd0.img root=live:CDLABEL=minishift-centos7 rootfstype=auto ro rd.live.image quiet no_timer_check console=ttyS0 console=tty0 net.ifnames=0 biosdevname=0 rhgb rd.luks=0 rd.md=0 rd.dm=0 
....................... FAIL E1130 22:17:10.527168   13444 start.go:499] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory

**Comment by ppedrozzi** [comment]
I'm experiencing the same problem

**Comment by angelosanramon** [comment]
same here

**Comment by ppedrozzi** [comment]
At the end I installed openshift 4 on the laptop using the CodeReady Containers instead of Minishift.

**Comment by mar1u50** [comment]
Same here.
Unfortunately i was not able to use virtualbox ....

I will give a try to CodeReady Containers.

**Comment by mar1u50** [comment]
I solved my problem temporarily by using crc. But crc is really resource hungry .... I hope the minishift bug will be fixed .... or we find a workaround to still use it in Big Sur

**Comment by georgettica** [comment]
actually the solution you brough @angelosanramon worked (needed to reboot and allow permission thingy, but seems fine)

**Comment by georgettica** [comment]
PS, this made docker on my machine stop working.. needed to reinstall docker to fix
(Not sure if more development is required here, but wanted to surface my issues)

**Comment by anjannath** [comment]
@sunnypandas @georgettica Can you guys try to use the hyperkit binary from https://github.com/code-ready/machine-driver-hyperkit/releases/download/v0.15.0/hyperkit i was able to fix this issue by using this hyperkit binary

**Comment by sunnypandas** [comment]
> @sunnypandas @georgettica Can you guys try to use the hyperkit binary from https://github.com/code-ready/machine-driver-hyperkit/releases/download/v0.15.0/hyperkit i was able to fix this issue by using this hyperkit binary

Thank you, I will try.

**Comment by nhojpatrick** [comment]
Any update? Code Ready Containers requires more resources, takes longer to book and is unstable when it finally get running.

**Comment by anjannath** [comment]
@nhojpatrick we are aware of the high resource requirements and working towards providing a leaner [crc](https://github.com/crc-org/crc), unfortunately `minishift` is only capable of creating OpenShift 3.x env and is not actively developed anymore.

**Comment by nhojpatrick** [comment]
@anjannath I'm after it being maintained, red hat is a multi billion pound organisation but appears to be releasing stuff under the cover of opensource so it doesn't need to give support.
when this was raised from what i'm aware openshift/minishift 3.11 was still within support, so was in active development.

**Comment by anjannath** [comment]
> @anjannath I'm after it being maintained, red hat is a multi billion pound organisation but appears to be releasing stuff under the cover of opensource so it doesn't need to give support.

You seem to be misunderstanding here, this is not a product for which you can buy support, so i don't understand why someone would create something as open source just to avoid supporting it.

> when this was raised from what i'm aware openshift/minishift 3.11 was still within support, so was in active development.

try to use the workaround: https://github.com/minishift/minishift/issues/3494#issuecomment-798622411
