### ISSUE TITLE
Is a new boot2docker.iso required for each minishift update 

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#35]
The first thing that happens after every minishift update is that a new boot2docker is is pulled down. Is this .iso required to be versioned with minishift, or could just reference a concrete boot2docker version and maybe be split into 2 repositories?

**Comment by jimmidyson** [comment]
Yeah that makes much more sense.

**Comment by LalatenduMohanty** [comment]
We are trying to do this as part of https://github.com/minishift/minishift/issues/134.

**Comment by LalatenduMohanty** [comment]
This is fixed now with https://github.com/minishift/minishift/commit/87aace40f322224a76fc39b606b94aeb23bb7b59
