### ISSUE TITLE
Unable to run minishift on windows 10 (hyper-v)

### ISSUE THREAD

**Issue by rhopp** [minishift/minishift#351]
I've downloaded internal build of CDK (CDK 3.0.alpha2.0) and I'm unable to start it. 
What I've done:
```
minishift.exe setup-ckd
```
```
minishift.exe start --username <my-rh-username> --password <my-rh-password> --show-libmachine-logs -v=5
```
here is output: https://paste.fedoraproject.org/541427/86064514/
From the output it seems that something's wrong with ssh. But I can also see there, that "ssh cat /etc/os-release" run without any problem.
Trying
```
minishift.exe ssh "cat /etc/os-release"
```
was indeed OK.

I've also tried to run the command which went wrong:
```
minishift.exe ssh "sudo hostname minishift && echo \"minishift\" | sudo tee /etc/hostname" --show-libmachine-logs --v=5
```
Output is here: https://paste.fedoraproject.org/541428/14858608/
From the output it seems to me that it was also run successfully. 

I wanted to look inside the machine what's happening, but 
```
minishift.exe ssh --show-libmachine-logs --v=5
```
does not open ssh connection, but kicks me right back into windows cli: https://paste.fedoraproject.org/541433/14858612/

**Comment by budhrg** [comment]
Closing as we are tracking it here https://issues.jboss.org/browse/CDK-70.
