### ISSUE TITLE
Minishift failing with VirtualBox hypervisor.

### ISSUE THREAD

**Issue by karankumar29feb** [minishift/minishift#3525]
### General information

  * Minishift version: 1.34.3
  * OS: Linux / macOS / Windows: Windows
  * Hypervisor: KVM / Hyper-V / VirtualBox / hyperkit:  VirtualBox v6.1.22

### Steps to reproduce

  1. VirtualBox already installed
  2. Downloaded minishift.exe and copied to a folder in C:\.
  3. Starting minishift using command:  .\minishift.exe start --vm-driver virtualbox

### Expected
minishift should start the cluster.

### Actual

PS C:\minishift-1.34.3-windows-amd64> .\minishift.exe start --vm-driver virtualbox
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... FAIL
   See the 'Setting Up the Virtualization Environment' topic (https://docs.okd.io/latest/minishift/getting-started/setti
ng-up-virtualization-environment.html) for more information
PS C:\minishift-1.34.3-windows-amd64>

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

PS C:\minishift-1.34.3-windows-amd64> .\minishift.exe start --vm-driver virtualbox --show-libmachine-logs -v5
-- minishift version: v1.34.3+4b58f89
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... FAIL
   See the 'Setting Up the Virtualization Environment' topic (https://docs.okd.io/latest/minishift/getting-started/setti
ng-up-virtualization-environment.html) for more information

===========================================================

1. I tried using multiple versions of minishift i.e. 1.34, 1.33 etc but facing the same issue.
2. Reinstalled the virtualbox as well but issue persists.
3. I can start the new VM's as well on VirtualBox.

**Comment by gbraad** [comment]
insufficient debug log provided. this does not show any indication of what fails.
Also make sure to test this with the skip option:

https://github.com/minishift/minishift/blob/580ebddc0bea7e718fa9900d73cebc0a4167378f/cmd/minishift/cmd/config/config.go#L122

**Comment by karankumar29feb** [comment]
@gbraad , i used the skip check config as shown below and then "--show-libmachine-logs -v5" for the logs but couldn't get any detailed logs, as shown below. Please suggest if there any specific command required.

===================================================================

PS C:\minishift-1.34.3-windows-amd64> .\minishift.exe config set skip-check-vbox-installed true
PS C:\minishift-1.34.3-windows-amd64>
PS C:\minishift-1.34.3-windows-amd64> .\minishift.exe start --vm-driver virtualbox --show-libmachine-logs -v5
-- minishift version: v1.34.3+4b58f89
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... FAIL
   See the 'Setting Up the Virtualization Environment' topic (https://docs.okd.io/latest/minishift/getting-started/setti
ng-up-virtualization-environment.html) for more information

**Comment by gbraad** [comment]
It might be that this fails:

https://github.com/minishift/minishift/blob/0381375335880a9f825a7a30266b03d493cd221c/cmd/minishift/cmd/start_preflight.go#L97-L102

```
$ minishift config set skip-check-vm-driver true
```

**Comment by karankumar29feb** [comment]
This time it skipped but stuck populating flag.

============================================================

PS C:\minishift-1.34.3-windows-amd64> .\minishift.exe  config set skip-check-vm-driver true
PS C:\minishift-1.34.3-windows-amd64>
PS C:\minishift-1.34.3-windows-amd64>
PS C:\minishift-1.34.3-windows-amd64> .\minishift.exe start --vm-driver virtualbox --show-libmachine-logs -v5
-- minishift version: v1.34.3+4b58f89
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... SKIP
-- Checking if VirtualBox is installed ... SKIP
-- Checking the ISO URL ... OK
Not able to populate vm-driver flag with virtualbox value

**Comment by gbraad** [comment]
For some reason the published version 1.34.3 is not usable. Perhaps use CDK instead as this saw a recent release.

I am not sure what is happening. If you do not want to use CDK all I can suggest is to either use the `generic` driver with a self created VM or use Hyper-V instead.
