### ISSUE TITLE
Document Glide workflow

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#353]
We should document few steps as part of glide workflow.

- Creation of our `glide.yaml` file from the scratch
- Update a version and how it affect to it dependency
- Recommend glide version
- In case of failure what wrong (kind of troubleshooting step)

**Comment by gbraad** [comment]
Might be helpful to describe the following commands in short:

  * `glide install`
  * `glide update`
  * `glide cc`

and that the cache exists in `~/.glide/cache`

**Comment by thatdocslady** [comment]
Hah, normally I'm in favor of spelling things our for users but in this case I recommend to keep the info minishift-specific and link to the glide usage doc: https://github.com/Masterminds/glide#usage

Regarding the cache location, is this something that the users would need later for minishift operations? If we don't need the user to "pay attention" to this, then I'd leave it out (it's also described in the glide install instructions and since we don't manage glide it might change and potentially cause our docs to be outdated, maintenance headache, etc....) 

WDYT?

**Comment by hferentschik** [comment]
We have more to consider than a Minishift "user". We are talking about https://github.com/minishift/minishift/blob/master/docs/developing.md here. Glide is irrelevant from a users respective, but very important for us developers and potential contributors. It becomes especially important in the context of Glide showing at times odd behaviour when required to reset some dependencies. Really when updating/adding a dependency we should require/recommend a 'glide cc' or make it somehow even part of the Makefile. 'make clean-cache'. So there might in fact even more needed than pure documentation.

**Comment by thatdocslady** [comment]
@hferentschik ok I understand although I remember you made a similar comment about giving too much third party info to developers as well, but I'll give it a shot. Can you and @praveenkumar please provide a bit more info on what topic you want this content to cover? Right now there is a good "why" case but other than bullet points on which tasks we need to cover, it'll be helpful to have more details. Thanks!

**Comment by hferentschik** [comment]
@thatdocslady, I think there is no point in you doing it right now. This is something which really needs to come from the devs. Also we need to actually test and verify a few things.

**Comment by thatdocslady** [comment]
@hferentschik I'm wondering if there's a way to hijack github labels to indicate issues that are deferred to a later time so that they're not bugging our (my) peripheral vision and result in premature discussions...

**Comment by gbraad** [comment]
This is what I miss on GitHub, but have on GitLab, a kanban board. You have outside tools for this...

but the simplest solution is to add a `backlog` label to an item. WDYT @hferentschik ? maybe even the `doing`, `in QA`, etc. this makes the flow of items more visual.

**Comment by hferentschik** [comment]
>  I'm wondering if there's a way to hijack github labels to indicate issues that are deferred to a later time so that they're not bugging our (my) peripheral vision and result in premature discussion

why don't you look at the milestones?

**Comment by thatdocslady** [comment]
@hferentschik not sure milestones would be helpful here, and this discussion I think is bigger than just for doc tasks but beyond (like @gbraad suggests state/status tags can be helpful for all issues). Maybe we should realtime-talk about this, to the docs team milestones are too arbitrary (and this v1.1.0 milsetone doesn't even have a due date on it so how can I plan ahead to know what's coming, etc etc).

**Comment by praveenkumar** [comment]
@thatdocslady Let spend some time on it and get it fixed, this shouldn't take much time though.

**Comment by thatdocslady** [comment]
@praveenkumar sure, I guess I need to figure out when in the sprint to get started with this since it has a further milestone than some other tasks but I'd like to add this to my queue for sure!

**Comment by hferentschik** [comment]
I am actually not sure what's still missing. I think issues we have seen where at times where we still had a dependency to Kubernetes and OpenShift. I think the documented process works fine now.

**Comment by praveenkumar** [comment]
@hferentschik right, but I think we do need to add a step to clear glide cache `glide cc`

**Comment by gbraad** [comment]
I also believe this is mostly resolved and maybe saying `make clean` is a
better option now...

the use of `glide cc` hasn't been needed in the recent months.

**Comment by hferentschik** [comment]
> the use of `glide cc` hasn't been needed in the recent months.

Right. I think the problem was with the Kube dependencies. The preferred way should be 'make clean' which affect is working fine now. If anything we can add a note, that if the Glide cache is corrupted it can be cleaned with a 'glide cc'

**Comment by praveenkumar** [comment]
>  If anything we can add a note, that if the Glide cache is corrupted it can be cleaned with a 'glide cc'

That works for me so @thatdocslady I think you have all info now.

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift/pull/1032
