### ISSUE TITLE
Even with administrator privileges Hyper-V complains about insufficient privileges

### ISSUE THREAD

**Issue by thesteve0** [minishift/minishift#356]
I cam across the error above when using Hyper-V. I have since fixed it so I can not show a screen shot of it not working. 

Basically it comes down to the fact that being administrator on the machine is not enough permission to use the Hyper-V commands from a console or non GUI interface (basically any automation). The fix is to add the current user to the Hyper-V group. 

Here is a command you can use to run it
https://blogs.msdn.microsoft.com/virtual_pc_guy/2016/05/30/adding-yourself-to-the-hyper-v-administrators-group-with-powershell/
https://blogs.msdn.microsoft.com/virtual_pc_guy/2010/09/28/creating-a-hyper-v-administrators-local-group-through-powershell/

But they can also go into the GUI and do this. Steps:
1) Windows key and then Computer Management
2) Local Users And Groups -> Groups
3) Double click on the Hyper-V admin group
4) Add their account to that group. 
The user then has to log out and log in before the changes will take affect. 

There also seems to be problems with a missing Hyper-V Admin group in windows 10 before the "Winter Update" patch (which basically re-installed windows). 

I am not sure if this affects other versions of windows and I only have windows 10 pro.

**Comment by thesteve0** [comment]
@hferentschik I am not sure about labels but this is not minor. Without this I couldn't get Minishift to install AT ALL on windows. It was only after doing this that I could actually even get minishift to get past the stage where is first tries to make the VM.

**Comment by budhrg** [comment]
@thesteve0 , I don't know but I always need to start PowerShell or CMD as "Run as Administrator".

I hope after gone through above instructions I needn't to run it that way.

**Comment by hferentschik** [comment]
@thesteve0, can we clarify what we mean here? You want to execute minishift in non elevated mode? And your workaround allows you to do that? Or is your workaround needed to make even running Minishift in elevated mode possible?

Personally I always start Minishift from an elevated Powershell terminal, similar to @budhrg.  That has always been my understanding based on the docs for the Hyper-V driver - https://docs.docker.com/machine/drivers/hyper-v/

I also never worked with Hyper-V group so far. Not sure how much this is a bug in Minishift or how much we should and can "automate". AFAIU you need to run these commands in elevated mode, so you would have to run Minishift at least once in this mode, right?

**Comment by thesteve0** [comment]
So I normally just open a powershell as my user - who is in the administrator group. When I run minishift start it fails with the privileges error. If I add myself to that Hyper-V admin group then it works fine. 

I normally do NOT right click on powershell and say "run as administrator". I am not sure if that fixes the permissions issue if I run it once. 

I think Docker gets away with it because they make an MSI and the installer can prompt for admin privileges.

**Comment by hferentschik** [comment]
> So I normally just open a powershell as my user - who is in the administrator group. 
> When I run minishift start it fails with the privileges error. If I add myself to that Hyper-V admin group then it works fine.

Got you

> I normally do NOT right click on powershell and say "run as administrator". I am not sure if that fixes the permissions issue if I run it once.

I would think so. At least I never had this problem before. I need to try your approach and see whether I can re-produce this.

**Comment by thatdocslady** [comment]
@thesteve0 @hferentschik so if I understand the issue correctly, on Windows OS you must not only have regular/global admin privileges for your user, but you also need to add yourself to an admin group called "Hyper-V"? Is this group created when you install hyper-v? Is the name of the group like you wrote here? I use Linux so I can't test this unfortunately.

**Comment by LalatenduMohanty** [comment]
Here is the gist of the issue.
In Windows when run any application through CMD.exe or Powershell  , user has choice start those as adminstrators, so that any command run inside it will be run as administrator.

Here are the option for users:

If you are running Minishift with HyperV on Windows then either 

1. User can open the cmd/powershell as administrator then run the minishift start command in it. It will work fine as HyperV needs administrator privilege. 

2. In case user wants to run it as an user but not as an administrator then the user needs to be added to to HyperV administrators group.

**Comment by hferentschik** [comment]
> User can open the cmd/powershell as administrator then run the minishift start command in it. It will work fine as HyperV needs administrator privilege.

this is really not a good option. Think about the user experience here. In the end a user should be able to work for example with his code/project in a default shell and execute minishift commands from there. You don't want/need an elevated shell for that. Also there is the issue with tooling, which w/o the right setup needs to keep elevating. 

So imo the recommended approach for users should be via HyperV admin group.

**Comment by LalatenduMohanty** [comment]
> So imo the recommended approach for users should be via HyperV admin group.

+1. Usually enterprise developers do not get Admin access to their workstations (from what I have experienced with CDK 2.x)

**Comment by budhrg** [comment]
Will do the investigation part and let @Preeticp  do the writing of docs.

**Comment by Preeticp** [comment]
@budhrg, investigation is done, I have the info and draft is ready. I will be sending a PR for this anytime now.

**Comment by hferentschik** [comment]
Merged via pull request #797
