### ISSUE TITLE
Linking to Install and running instructions from openshift.org

### ISSUE THREAD

**Issue by thesteve0** [minishift/minishift#357]
This is a placeholder to help remind whomever is in charge of doc to please notify me if the location of the install instructions or "how to run" minishift documents move locations. I am rewriting openshift.org/vm to point to minishift and currently I am telling developers to go to:

https://github.com/minishift/minishift/blob/master/README.md#installation

to get started. Just let me know if you change things so I can update my URLs.

Thanks!

**Comment by Preeticp** [comment]
Sure thing @thesteve0

**Comment by thatdocslady** [comment]
@thesteve0 @Preeticp we already have an issue to link to generic openshift content https://github.com/minishift/minishift/issues/249 

I'm working on it this week and will add links not just in the install docs. IMO we can close this issue and add your info to the original issue.

**Comment by thatdocslady** [comment]
@thesteve0 I have a running issue to track the new Minishift page on openshift.org #372 so once that's up you can adjust the VM page accordingly.

**Comment by gbraad** [comment]
FYI, There is also https://www.openshift.com/devpreview/register.html that refers to the the All-in-One VM:

"
NO DOCKER? NO PROBLEM!

Simply download and run the All-in-One Virtual Machine with Vagrant. The full instructions are available at openshift.org/vm/.
“

**Comment by thatdocslady** [comment]
@gbraad I don't see this in the link you provided...

**Comment by gbraad** [comment]
@thatdocslady it is still in the step AFTER having signed up for the dev-preview account.

**Comment by thatdocslady** [comment]
Fixed in the openshift.org repository as a part of PR https://github.com/openshift/openshift.org/pull/69
Links are live in: https://www.openshift.org/minishift/

**Comment by praveenkumar** [comment]
@thatdocslady I am closing this issue since everything is now in place.
