### ISSUE TITLE
Investigate host folder mounts via sshfs

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#358]
An investigation task for #317

**Comment by gbraad** [comment]
You might need something to get the host IP addresses? I needed something similar: https://github.com/gbraad/minishift/commit/164c0ae61a8a4724d39ae9f50c0e017dd9743234

**Comment by hferentschik** [comment]
> You might need something to get the host IP addresses? 

Indeed I do :-) 

In fact now that I get a better grasp of this, I think there is a lot of overlap with the Windows shares stuff. I definitely see how windows shares vs sshfs are two different types of host folders we want to somehow offer under a unified ux. We need to sync on this asap.

I am a bit surprised that you expose the host IP via a command though. Is this not something you would need internally?

**Comment by gbraad** [comment]
> a bit surprised that you expose the host IP via a command

testing purposes

**Comment by hferentschik** [comment]
The aim was to establish whether we can use an sshfs based solution as a (default) for host folder mounts. The short answer is, yes. In fact it might be the most generic solution we can provide. 

To implement a fully automated solution we should wait for the CIFS support to be merged - see issue #480. The idea is then to align cifs and sshfs in terms of ux and allow the user to select the technology which he prefers. 

As a first step, we already enabled the CentOS ISO (see https://github.com/minishift/minishift-centos-iso/issues/107)  as well as the B2D ISO (see https://github.com/minishift/minishift-b2d-iso/issues/35) with the required sshfs packages. As part of this issue we will also document manual steps on how to use sshfs provided one has a ssh daemon running on the host.

Then as part of #317, we implement a fully automated solution. We can do this in various forms:

* Require ssh daemon to be installed - in this case we are closest to the CIFS support. A user would have to specify username and password for the mount. This has the least amount of changes for us
* The second alternative is to run our own ssh server. As part of the investigation I was running a native sftp server which I added to the Minishift code base. While this server was running, I could use sshfs connecting to this embedded ssh daemon. The benefit in this case is that we can control the whole environment and effectively can make it password free.

**Comment by budhrg** [comment]
> Then as part of #317, we implement a fully automated solution.

Sounds good plan :+1: .

> The second alternative is to run our own ssh server. As part of the investigation I was running a native sftp server which I added to the Minishift code base. While this server was running, I could use sshfs connecting to this embedded ssh daemon. The benefit in this case is that we can control the whole environment and effectively can make it password free.

I am more aligned to it then having ssh daemon installed :smile:

**Comment by LalatenduMohanty** [comment]
> The second alternative is to run our own ssh server. As part of the investigation I was running a native sftp server which I added to the Minishift code base. While this server was running, I could use sshfs connecting to this embedded ssh daemon. The benefit in this case is that we can control the whole environment and effectively can make it password free.

+1, sounds good to me. I am assuming this does not cost significant increase in resources (CPU and memory).

**Comment by LalatenduMohanty** [comment]
Closing the issue as we are done with the investigation and #317 will be used to implement the solution.

**Comment by hferentschik** [comment]
I am re-opening this task. I want to add some docs as a result of this task:

> As part of this issue we will also document manual steps on how to use sshfs provided one has a ssh daemon running on the host.

**Comment by LalatenduMohanty** [comment]
Closing this as the documentation PR #542  is merged now.
