### ISSUE TITLE
Introduce context "minishift"

### ISSUE THREAD

**Issue by rhuss** [minishift/minishift#359]
It would be awesome if minishift would name its context "minishift" so that one can easily switch back to the minishift instance with

```
oc set-config use-context minishift
```

`minikube` does it that way.

**Comment by praveenkumar** [comment]
@rhuss I checked with v1.4.1 origin and seems like oc binary doesn't have set-config option in this version, is it something which will come later version?

```
$ ./.minishift/cache/oc/v1.4.1/oc version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

$ ./.minishift/cache/oc/v1.4.1/oc set-config
Error: unknown command "set-config" for "oc
```

**Comment by rhuss** [comment]
@praveenkumar  Sorry, I meant

```
oc config use-context minishift
```

The context themselves are defined in `~/.kube/config` and you can use this command to switch between different K8s / OpenShift installations (this file is shared between K8s and OpenShift)

**Comment by rhuss** [comment]
Minishift adds a context but it is named like `/192-168-64-3:8443/admin` which is not very intuitive and changing per new installation.

**Comment by jorgemoralespou** [comment]
@praveenkumar Look here for a sample of how we do it:
https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/master/oc-cluster#L285-L289

2017-02-03 11:59 GMT+01:00 Roland Huß <notifications@github.com>:

**Comment by praveenkumar** [comment]
@jorgemoralespou @rhuss Thanks for quick note and code-snip.

**Comment by praveenkumar** [comment]
I spent some time before this PR and tried to understand why we can't use same approach as kubernetes do for context - https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/start.go#L175-L194  here you can see that before it set the context it have kubernetes up and running and then they create the config file. 

Since we are using oc cluser up approach `oc` itself create config file for us so we need to modify it with available options to get the context right (which I did as part of PR).

**Comment by jorgemoralespou** [comment]
@praveenkumar @hferentschik I would request you to think about profiles (if you have already thought on how to implement them) as the context setting will be very relevant to when that happens.

**Comment by hferentschik** [comment]
> I would request you to think about profiles

What do you mean with profiles in this case? The ability to have multiple Minishift instances and switch between them? Or the ability to bootstrap OpenShift instances with different configurations (more or less secure for example). Profiles has been used recently for both of this.

I assume you mean the former. I would think that 'minishift' is the context for now, but effectively the context will eventually be the name of the minishift instance (profile) you create/manage.

**Comment by jorgemoralespou** [comment]
@hferentschik Yes, the former, since the later I guess you're not contemplating keeping all the configured instances and being able to switch between them (which is a poor's man version of the former).

And yes, what I mean is that you shouldn't make it too hardcoded to the context name, as in the future I envision the context name mapping to the profile (e.g. minishift-test, minishift-ocp34, ... or without the minishift)

**Comment by hferentschik** [comment]
> And yes, what I mean is that you shouldn't make it too hardcoded to the context name, as in the future I envision the context name mapping to the profile (e.g. minishift-test, minishift-ocp34, ... or without the minishift)

+1 Same here

**Comment by hferentschik** [comment]
Merged via pull request #543

**Comment by rhuss** [comment]
@hferentschik since which version is this feature available? I'm using 1.1.0

but still, it does not know about a context `minishift`:  

```
$ oc config use-context minishift
error: no context exists with the name: "minishift".

$ oc config use-context myproject/$(minishift ip | sed -e s/\\./-/g):8443/developer
Switched to context "myproject/192-168-64-3:8443/developer".

$ oc get pods
NAME                                 READY     STATUS      RESTARTS   AGE
camel-karaf-servicenow-s2i-1-build   0/1       Completed   0          1h
syndesis-datamapper-1-89zb0          1/1       Running     0          5h
syndesis-db-1-w20kr                  1/1       Running     0          5h
syndesis-github-proxy-1-3tkpl        1/1       Running     0          5h
syndesis-keycloak-2-p5g09            1/1       Running     0          5h
syndesis-openshift-proxy-1-m6998     1/1       Running     0          5h
syndesis-rest-1-vm073                1/1       Running     3          5h
syndesis-ui-1-nmxtj                  1/1       Running     0          5h
syndesis-verifier-3-cdv20            1/1       Running     0          5h
```

**Comment by hferentschik** [comment]
Since v1.0.0-rc.1.

Using 1.1.0, I get:

    $ oc config use-context minishift
     switched to context "minishift".

The context gets created in some post provisioning we run, once the initial OpenShift cluster is up. Did you upgrade Minishift, but try to keep an old Minishift VM around? That would explain it. You need to provision a new Minishift instance using a Minishift version post 1.0.0-rc.1.

**Comment by hferentschik** [comment]
Since v1.0.0-rc.1.

Using 1.1.0, I get:

    $ oc config use-context minishift
     switched to context "minishift".

The context gets created in some post provisioning we run, once the initial OpenShift cluster is up. Did you upgrade Minishift, but try to keep an old Minishift VM around? That would explain it. You need to provision a new Minishift instance using a Minishift version post 1.0.0-rc.1.

**Comment by rhuss** [comment]
```
$ minishift version
minishift v1.1.0

$minishift delete
Deleting the Minishift VM...
Minishift VM deleted.

$ minishift start
Starting local OpenShift cluster using 'xhyve' hypervisor...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.1 image ...
   Pulling image openshift/origin:v1.5.1
   Pulled 0/3 layers, 3% complete
   Pulled 0/3 layers, 57% complete
   Pulled 1/3 layers, 75% complete
   Pulled 2/3 layers, 99% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ...
   Using 192.168.64.3 as the server IP
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Checking container networking ... OK
-- Server Information ...
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.64.3:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

Error during post cluster up configuration: Error reading config file /Users/roland/.minishift/machines/minishift_kubeconfig

$ oc config use-context minishift
error: no context exists with the name: "minishift".
```

So, that's not working for me. (BTW, since 1.0.0 I always get this `Error during post cluster up configuration: Error reading config file /Users/roland/.minishift/machines/minishift_kubeconfig`).

**Comment by rhuss** [comment]
After removing ~/.kube/config and ~/.minishift it worked for me, too.

thanks ...

**Comment by donghwicha** [comment]
any one who can guide how KUBECONFIG works? if we remove ~/.minishift, then the existing profile will be gone.
