### ISSUE TITLE
Adjust help messages for glog flags added to the root commands

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#364]
The current output is not really consistent in the use of upper and lower casing:

      --alsologtostderr                  log to standard error as well as files
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory (default "")
      --logtostderr                      log to standard error instead of files
      --password string                  Password for the virtual machine.
      --show-libmachine-logs             Show logs from libmachine.
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
      --username string                  User name for the virtual machine.
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered loggin

**Comment by thatdocslady** [comment]
@hferentschik I already commented about these messages while I was editing all doc strings, they are actually not stored in any of our code but get pulled in from dependencies somewhere in the ether (we had this discussion with @gbraad a little while ago). I don't know where all of these come from but it's not something we can control unless we submit PRs to the 3rd party repos.

**Comment by praveenkumar** [comment]
@hferentschik with our current master we have it below so we just need to adjust `show-libmachine-logs` message to lower case and good to go.

```
Flags:
      --alsologtostderr                  log to standard error as well as files
  -h, --help                             help for minishift
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory (default "")
      --logtostderr                      log to standard error instead of files
      --show-libmachine-logs             Show logs from libmachine.
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
```

**Comment by thatdocslady** [comment]
@praveenkumar please also tag me in these questions. There are more fixes that need to be done to the descriptions of these messages, capitalizationa and grammar.

**Comment by praveenkumar** [comment]
@thatdocslady Problem is that except `-show-libmachine-logs` we don't have any thing in our control because other part come from a different module that's the reason I didn't tag you but if you think ` Show logs from libmachine.` also need improvement then let me know.

**Comment by hferentschik** [comment]
Right, I have some deeper going plans there. This ties into the overdue logging re-work. @thatdocslady, we are not talking about just some wording changes.

**Comment by thatdocslady** [comment]
@hferentschik ok so I understand that the strings come from external components, was wondering if we can use a foss-first method and maybe contribute edits to the components so it also helps others who use them.

If you have different plans for these or think that they'll become obsolete in the near future then we can close this task and accept the icky strings for now :)

**Comment by hferentschik** [comment]
>  so I understand that the strings come from external components, was wondering if we can use a foss-first method and maybe contribute edits to the components so it also helps others who use them.

I don't think that there is something inherently wrong with the messages. It just does not quite fit our style. Also, I would like to be able to control all this our own logging facade. 

To answer your question, no, in this case I was not planning to contribute anything into a library.

**Comment by LalatenduMohanty** [comment]
@minishift/minishift-dev  What should we do with this issue? Can we close this? It is a very old issue and it depends on libmachine code.
