### ISSUE TITLE
Virtualbox as default on macOS

### ISSUE THREAD

**Issue by marekjelen** [minishift/minishift#368]
Is there a reason to have `xhyve` as default on macOS?

IMHO there is more people who already have VirtualBox installed and the driver is packed as part of the binary without the need to install it manually.

**Comment by hferentschik** [comment]
> Is there a reason to have xhyve as default on macOS?

The idea is that xhyve is the "native" hypervisor on OS X. You actually don't have to install it. On the other hand, you need to install the libmachine xhyve driver. The idea, however, would be to bundle the xhyve driver with Minishift - see issue #217 

That said, there are other reasons why I don't think it makes sense to default to xhyve. This is an ongoing discussion. See https://github.com/minishift/minishift/issues/215. Chip in, if you feel for it.

IMO, it makes more sense to have VirtualBox as the default (so to say as least common denominator) and let it be an active choice of the user to use a different hypervisor.

> IMHO there is more people who already have VirtualBox installed and the driver is packed as part of the binary without the need to install it manually.

+1

**Comment by budhrg** [comment]
@hferentschik Look like minikube had `virtualbox` as default driver https://github.com/kubernetes/minikube/blob/master/docs/minikube_start.md

**Comment by praveenkumar** [comment]
@budhrg @hferentschik I think we should close this issue now because most of folks who are on mac are happy with what we have as default.

**Comment by budhrg** [comment]
Agree @praveenkumar

**Comment by hferentschik** [comment]
+1, also relates to #215.
