### ISSUE TITLE
Create Minishift landing page

### ISSUE THREAD

**Issue by thatdocslady** [minishift/minishift#372]
We need a landing page with basic overview about Minishift. The page needs to be aligned with the OpenShift brand and contain quickstart info and links to further details.

I already forked openshift.org repo and have a working branch with the content of the Minishift page:
https://github.com/thatdocslady/openshift.org/tree/minishift-landing-page

We still need to determine whether to store the site in a standalone repo or submit it as a sub-page of openshift.org.

**Comment by gbraad** [comment]
> We still need to determine whether to store the site in a standalone repo or submit it as a sub-page of openshift.org.

sub-page avoids the needs of possible additional artwork, etc. I believe minishift should be seen as part of openshift, instead of a separate project. WDYT?

**Comment by thatdocslady** [comment]
@gbraad the impact on design work isn't big actually because I just forked the openshift site so all the info is in there already. It's more of a question of whether the page is included in the openshift site similar to the all-in-one-vm page (https://www.openshift.org/vm/) or is shown in a standalone URL like minishift.io. Technically it's easy either way and most of that work is already done, it's more of a business decision than a technical one. @hferentschik is in favor of standalone URL but @LalatenduMohanty at the time deferred the decision, so I'm still waiting for an official instruction.

**Comment by thatdocslady** [comment]
Following discussion today, it is decided that we will create the minishift page as a sub-page of openshift.org and use a redirect from minishift.io to point to openshift.org/minishift. I will submit a PR later today after resolving some build errors and link to it from this issue.

**Comment by hferentschik** [comment]
> Following discussion today, it is decided that we will create the minishift page as a sub-page of openshift.org and use a redirect from minishift.io to point to openshift.org/minishift

+1

**Comment by hferentschik** [comment]
We need to take https://www.openshift.org/vm/ into account as well. This page has changed after the Vagrant approach has been deprecated. Once we have https://www.openshift.org/minishift the /vm page should just mention how the Vagrant approach is deprecated and then link to /minishift. 
We might then also take some of the things mentioned on /vm into /minishift.

**Comment by hferentschik** [comment]
Also, how does one navigate to https://www.openshift.org/minishift? I mean as a visitor of https://www.openshift.org?

**Comment by LalatenduMohanty** [comment]
@hferentschik The home page of https://www.openshift.org/ would mention Minishift. Similar way "oc cluster up" is mentioned currenltly. I remember asking the question and got this as answer.

**Comment by thatdocslady** [comment]
@hferentschik @LalatenduMohanty yes, this was going to be my next step after I resolve the local build errors, I will adjust the section that discusses the all-in-one-vm in the main openshift page to link to both options.

**Comment by thatdocslady** [comment]
Everyone, please review PR in the openshift.org repo: https://github.com/openshift/openshift.org/pull/60

**Comment by jorgemoralespou** [comment]
cc/ @thesteve0 Read this thread. Since we changed openshift.org/vm, I guess
you should synchronize with the minishift team.

Cheers,

**Comment by thatdocslady** [comment]
@jorgemoralespou thanks for this, I also tagged him in the PR itself :)

**Comment by thesteve0** [comment]
Commented in the other thread for pr on openshift.org

**Comment by hferentschik** [comment]
Merged and available under https://www.openshift.org/minishift/

**Comment by thatdocslady** [comment]
PR merged and landing page is live at: https://www.openshift.org/minishift/

Closing this issue as resolved.
