### ISSUE TITLE
Add validation for minimal supported OpenShift version in start command 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#375]
We should add some simple validation to the start command for the _openshift-version_ flag. We need to determine the minimum version required and validate that no earlier version is selected.

**Comment by hferentschik** [comment]
@praveenkumar do you want to take care of this while you are on this?

**Comment by hferentschik** [comment]
While on it, I would like to get rid of the _get-openshift-versions_ command (not the underlying functionality, just the command). There is no value in this for a minishift user in this form. I'd rather use this in conjunction with the idea of interactive selection of the OpenShift version to run, but one needs to apply some filters in this case. Printing all releases does not make much sense.

**Comment by praveenkumar** [comment]
@hferentschik which version we should chose for validation (after 1.3.0 ? )

**Comment by praveenkumar** [comment]
> . I'd rather use this in conjunction with the idea of interactive selection of the OpenShift version to run, but one needs to apply some filters in this case. Printing all releases does not make much sense.

Can we just show the version info which we support using minishift? I mean if we go with > v1.3.1 then show only those versions which are greater than 1.3.1 ?

**Comment by hferentschik** [comment]
Merged via pull request #398. 

Created follow up issues #410 and #411
