### ISSUE TITLE
Ability to change the OpenShift DNS server

### ISSUE THREAD

**Issue by sglebs** [minishift/minishift#376]
I am running OpenShift under MacOS. Right now minishift is getting IP 192.168.64.2 from this Mac network interface:

```
bridge100: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=3<RXCSUM,TXCSUM>
	ether 7a:4f:43:c4:d1:64 
	inet 192.168.64.1 netmask 0xffffff00 broadcast 192.168.64.255
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en10 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 31 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```

Unfortunately I need OpenShift to use as name server 10.9.15.2 . Is there a safe and permanent way to do so? Editing /etc/resolv.conf does not do it. What service do I need to restart? It seems to be a CentOS distro, but many attempts failed:

  * sudo service network-manager restart
  * https://www.cyberciti.biz/faq/unix-network-service-restart-stop/

Ideally I want this to be permanent, to survive a reboot. Thanks.

**Comment by praveenkumar** [comment]
@sglebs If you are using `xhyve` driver then I am afraid you don't able to map which network bridge you want to use for you VM to get IP. I don't find anything from https://github.com/zchee/docker-machine-driver-xhyve :( but If you use Virtualbox then --virtualbox-hostonly-cidr "192.168.99.1/24" Specify the Host Only CIDR [$VIRTUALBOX_HOSTONLY_CIDR] can be used. Let us know if that something works for you.

**Comment by budhrg** [comment]
@sglebs Have you tried with Virtualbox as mentioned by @praveenkumar . Let us know your feedback.
