### ISSUE TITLE
Enable TravisCI IRC notifications

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#380]

**Comment by budhrg** [comment]
We are getting Travis CI notifications now 
![screenshot from 2017-03-09 18-55-28](https://cloud.githubusercontent.com/assets/1132451/23752142/1f273b82-04fa-11e7-9d1b-757e17b4774e.png)

Any other notifications we are expecting here @hferentschik  or can we close this issue?

**Comment by hferentschik** [comment]
> Any other notifications we are expecting here @hferentschik or can we close this issue?

Yes, but not for Travis :-) Also we need to see whether we want to change the message itself, but this will be a different issue. 

I think this is really just a duplicate of issue #495 which got properly resolved. 

Thanks for pointing this out.
