### ISSUE TITLE
Minishift start fails on a host with Docker for Windows installed

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#385]
On a Windows 10 host, with Hyper-V and Docker for Windows installed, I have set the following environment variables:

`$env:path="C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Go\bin;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\ZeroTier\One\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Users\gbraad\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin"`

Running `minishift start` will fail as follows:

```
PS C:\Users\gbraad\Downloads\minishift-1.0.0-beta.3-windows-amd64> .\minishift.exe start
Starting local OpenShift cluster using 'hyperv' hypervisor...
Provisioning OpenShift via 'C:\Users\gbraad\.minishift\cache\oc\v1.4.1\oc.exe [cluster up --use-existing-config --host-c
onfig-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... FAIL
   Error: cannot obtain a Docker client
   Solution:

     Please install Docker tools by following instructions at:

        https://docs.docker.com/windows/

     Once installed, run this command with the --create-machine argument to create a
     new Docker machine that will run OpenShift.

   Caused By:
     Error: invalid endpoint
E0209 20:41:27.289482    5840 start.go:246] Error starting the cluster:  exit status 1
```

When adding `C:\Program Files\Docker\Docker\Resources\bin;` to the path, the error is as follows:

```
PS C:\Users\gbraad\Downloads\minishift-1.0.0-beta.3-windows-amd64> .\minishift.exe start
Starting local OpenShift cluster using 'hyperv' hypervisor...
Provisioning OpenShift via 'C:\Users\gbraad\.minishift\cache\oc\v1.4.1\oc.exe [cluster up --use-existing-config --host-c
onfig-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... FAIL
   Error: cannot obtain a Docker client
   Solution:

     To create a new Docker machine to run OpenShift, run this command again with
     the --create-machine argument. This will create a Docker machine named
     'openshift'.

     To use a different machine name, specify the --machine-name=NAME argument.

     If you wish to use an existing Docker machine, enable it before running this
     command by executing:

        docker-machine env

     where NAME is the name of your Docker machine.

   Caused By:
     Error: invalid endpoint
E0209 20:47:52.918218    9816 start.go:246] Error starting the cluster:  exit status 1
```

Missing something?

**Comment by hferentschik** [comment]
Hmm, do you have _DOCKER_HOST_ set persistently? Does this happen when no  Docker for Windows is installed as well? There might be a conflict somewhere.

Personally I don't have Docker installed at all.

**Comment by gbraad** [comment]
Yes, environment variables get set

**Comment by gbraad** [comment]
Haven't been able to reproduce it after system restore; installed Hyper-V, Docker for Windows and performed a `minishift start`. It could that some of these results could have been related to network issues (virtual switch setup created a non working network setup)... eventually the reason of the System restore.
