### ISSUE TITLE
Document default user credentials and un-install instructions

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#387]
The documentation should mention the default users and their credentials. Also a word about privileges and which user to use for what would be good.

Should be added to the Usage guide - https://github.com/minishift/minishift/blob/master/docs/using.md

**Comment by BrunoVernay** [comment]
I can write something if you want

**Comment by budhrg** [comment]
@BrunoVernay We would love to review the PR :smile:

**Comment by hferentschik** [comment]
Merged. See pull request #400 and #401
