### ISSUE TITLE
Review setup tips and tricks info and possibly incorporate into docs

### ISSUE THREAD

**Issue by thatdocslady** [minishift/minishift#388]
When @thesteve0 created the previous minishift/vm page[1] he added some initial setup and config info that could be useful for our docs. @hferentschik @LalatenduMohanty we should review this info to see what is "permanent" (as in always relevant), "temporary" (as in due to bugs or future support of something), etc. and then we can determine if/where to add it to our docs.

[1] https://www.openshift.org/vm/

**Comment by thatdocslady** [comment]
@hferentschik WDYT? If you don't have time to review this, maybe recommend someone?

**Comment by thatdocslady** [comment]
@hferentschik I marked this as needs-investigation (new label, looks good), please let me know when I can pick this up

**Comment by praveenkumar** [comment]
@thatdocslady I think whatever listed to https://www.openshift.org/vm/ already in place in our document or you have something else in mind?

**Comment by hferentschik** [comment]
I think this could be closed.

**Comment by praveenkumar** [comment]
Closed :)
