### ISSUE TITLE
Abilty to use persistent volumes 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#389]
See also https://github.com/minishift/minishift/issues/207#issuecomment-274310292

**Comment by Preeticp** [comment]
Adding this note to track required documentation. We will need to update documentation and add an example, on the lines of the example we had for the /data host directory earlier, in the Interacting with your local OpenShift>Persistent volumes section.

**Comment by jorgemoralespou** [comment]
@hferentschik For this issue, it should be pretty simple to create the volumes in versions pre 1.5 using same approach as "oc cluster does", it's running a Job creating a sufficient number of persistent volumes.

https://github.com/openshift/origin/blob/master/pkg/bootstrap/docker/openshift/pvsetup.go

Although, oc versions pre-1.5 will not have the registry configured as persistent.

The goal here, being able to provide consistent behavior for different versions of "openshift" from the minishift side. Same could apply to proxy, so you provide the ability to users of minishift using "oc pre 1.4" with the possibility to configure proxies.

**Comment by hferentschik** [comment]
Merged via pull request #754
