### ISSUE TITLE
Implement ability to run Minishift against an existing VM (can be remote)

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#392]

**Comment by LalatenduMohanty** [comment]
This will also unlock an use case where developer can reuse a VM running in public cloud to run Minishift.

**Comment by jayunit100** [comment]
Testing apps specifically and continuously on openshift is always important due to the default UIDs and security defaults, so for vendors supportings (swarm/kube/openshift) container deployments for their apps - this is a hugely liberating feature.

**Comment by anjannath** [comment]
@minishift/minishift-dev What about this, looks like minibot closed this, this should be pinned i guess.

**Comment by anjannath** [comment]
@minishift/minishift-dev What about this, looks like minibot closed this, this should be pinned i guess.

**Comment by gbraad** [comment]
Need a break down..

**Comment by LalatenduMohanty** [comment]
Current user exeperience 

`minishift start --vm-driver remote-host --ip <IP>` (At this point I am using host where we do not need password to login)

1. Configure docker as per  required by Minishift (We expect the docker to be installed at this point. We can automate this later)
2. Provision OpenShift
3. Fix `minishift` commands which are not applicable for this use case e.g. minishift delete.

**Comment by LalatenduMohanty** [comment]
Resolved via #2422

**Comment by jralmaraz** [comment]
I wonder if anyone has faced a similar issue:

minishift start --vm-driver generic --remote-ipaddress 10.0.0.186 --remote-ssh-user ec2-user --remote-ssh-key ~/.ssh/id_rsa 
-- Starting profile 'minishift'
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'generic' hypervisor ...
-- Preparing Remote Machine ...... OK
-- Starting to provision the remote machine .... FAIL E0612 22:58:15.192527    3433 start.go:494] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
Error starting the VM: Error getting the state for host: unexpected EOF

**Comment by ghassen1khalil** [comment]
@jralmaraz I succeeded to launch minishift on a remote address but in the local console I got https://192.168.64.3:8443/console (a local IpAddress)
