### ISSUE TITLE
Enable LVM usage on CentOS/RHEL images

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#394]
While trying to resolve #355 we have tried to implement LVM for Docker storage. Although device mapper was not the cause of the issue we were having, the investigation has resulted in useful information. With some minor modification it should be possible to conclude this implementation.

**Comment by gbraad** [comment]
* https://github.com/gbraad/minishift/commit/6ab25465487b1f415950f6e73f67d05e5a1a51b0
  * https://github.com/gbraad/minishift-centos-iso/commit/2ad2d7ea01cdf17ee8b33477e9c9581dd34c836d

**Comment by gbraad** [comment]
@praveenkumar @budhrg @LalatenduMohanty @hferentschik 
The current layout for the data disk is as follows:

Full disk (20G)
  * LVM (19G): minishift_vg
    * ext4 (10G) data: lv
    * remainig: docker-pool
  * swap (1G)

Also, the disk is mounted as /mnt/data (instead of /mnt/sda1).

Note: in this change, I have not included the fixes to the swap handling: https://github.com/minishift/minishift-centos-iso/pull/97

**Comment by LalatenduMohanty** [comment]
@gbraad Thanks. The only concern is 10G for docker thin pool is less. Previously in ADB we had around 30GB but still enterprise users complained that they need bigger space. If we can findout a way where advance users can extend the disk or use a higher sized disk e.g. 100GB that will be good.

**Comment by gbraad** [comment]
@LalatenduMohanty the problem here is of course how to strike a balance between the persistent storage and the docker-pool. In a developer situation I hope they do not need 10G of storage for the containers, but also 10G for persistent storage... is it enough, or too little?

**Comment by gbraad** [comment]
> If we can findout a way where advance users can extend the disk or use a higher sized disk

we could offer an extend command for the disk (depends on the VM provider if they allow resizing), or allow them to specify the size up-front. The last option could be achieved by using a fractional space allocation instead ? persistent data always 40%, 50% for docker-pool and the remaining 10% for swap space?

**Comment by LalatenduMohanty** [comment]
> In a developer situation I hope they do not need 10G of storage for the containers, but also 10G for persistent storage... is it enough, or too little?

Actually some need more than 10G of storage for containers. But I think 10GB for persistent storage should be fine. 




> we could offer an extend command for the disk (depends on the VM provider if they allow resizing), or allow them to specify the size up-front.

+1 to the idea. I think it can be part of minishift command line some how. may be it can be part of the `minishift create` command we discussed while back.

**Comment by gbraad** [comment]
Currently running into the following issue: https://github.com/docker/docker/issues/16092

Unable to take ownership of thin-pool (%s) that already has used data blocks

**Comment by praveenkumar** [comment]
@gbraad Can we close this because moving forward we are looking for `overlay` as default.

**Comment by gbraad** [comment]
closing is OK with me, Also close: https://github.com/minishift/minishift-centos-iso/pull/100 and https://github.com/minishift/minishift-centos-iso/pull/74, WDYT?

**Comment by gbraad** [comment]
Closing as we will likely go with overlay
