### ISSUE TITLE
Write flag whether VM is registered into persistent config

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#396]
#At the moment when stopping/deleting the VM, we cannot warn/inform the user whether un-registration was required, but did not occur. The problem is that atm we need a running VM to determine whether the VM is registered. If the VM is in an error state, we don't know whether un-registration should or should not occur. This can potentially lead to dangling subscription which the user does not know about. 

If we instead during registration write a flag into persistent config, we can check this falg during stop/delete and inform/warn the user accordingly.

Follows up on issue #318

**Comment by praveenkumar** [comment]
> Basically I thought we read the config file as in root.go (we already do as part of the Viper config) and keep the landed config in memory behind some Config interface. 

Yes, we can use same config file which used for --iso-url and --vm-driver.

> When we modify the config we flush. For this particulate case we would write a isRegisteredVM flag. Maybe we put this into a nested currentVM context. 

I think we modify config file using set/unset param currently and not completely flush it but what we should do is make Registered as false initially and then change according to provioner.

> We will also need the current oc to be used persistent in there. This is required for the oc env command as well as for the registry exposure (issue #254). WDYT?

I didn't get it how it is relevant to our registration side of changes?

**Comment by hferentschik** [comment]
> I didn't get it how it is relevant to our registration side of changes?

What I meant is, that the ability to read/write custom config entries is required for these tasks as well. So whichever tasks gets implemented first needs to put something into place which the other task can use.

**Comment by hferentschik** [comment]
Merged via pull request #988
