### ISSUE TITLE
Enhance documentation with diagrams

### ISSUE THREAD

**Issue by BrunoVernay** [minishift/minishift#403]
Some visual could help to grasp the beast.
Does it looks like a good idea?  
Does it belongs elsewhere and we only provide link? 

I started some simple  [diagram](https://www.planttext.com/?text=RL8zJyCm49tnhpYP1OOaweggg0As4e64b8d5E4vgDJb7zgL2eFBRkQIqRWE3Xxoll3jx5KXv6hfM2BBK6YWish2nDK42ZrOrNdL2eAiCFAcUN0zVGW2mnzPA4tH7-JaeIykPghMVYgp3DxnPbqNs2zwxZonDqri9Ai2kyhinhtPjPJp8RyZIxV1k9Fy6u2nIEwnjmzYUpynmwZ15TZZtsk0k0QTZa3UQ53Oy-NDly7MQVBaiYppdcAl8oXTNmJKNbqm_E2HbqNXM_HKjvX9krIykT6kUqQCX4y1vlJ61_BIgVvpRuLYMZzEGfddSHkmymeT1MPCaEVlW3lo0Z7JnJfaOTtwYfeyHZKa7Iko5M1ci-6dy0000) that could benefits some review

**Comment by hferentschik** [comment]
> Some visual could help to grasp the beast.

+1

> Does it looks like a good idea?

Sure

> Does it belongs elsewhere and we only provide link?

For the rendered docs one would add a actual png/gif/jpg to the docs. Of course if this diagram is creates from some sort of text based tools, one would also check in the source for that. What are you using there? 

The one concern I have is that we end up with all sort of diagram languages. Moving forward the docs will most likely use Asciidoctor which supports various type of diagrams - http://asciidoctor.org/docs/asciidoctor-diagram/. So whatever we use should be supported there as well. I can see _plantuml_ in the asciidoctor supported  diagram tools. Is this what you were using?

**Comment by budhrg** [comment]
This seems to be interesting. :+1:  for idea.

**Comment by BrunoVernay** [comment]
Indeed, I used PlantUML as it
- seems easier to collaborate on text.
- focus on the content rather than colors and styles

About collaboration, you should be able to clic on the link (in the first post) to see the diagram and comment. I am sure the diagram is missing some containers.
There might be better ways to proceed, I am open.

Also I did not find recognized "icon" or shapes for Container and VM. So I used the UML stereotype:  <<...>>.

**Comment by hferentschik** [comment]
@Preeticp, @thatdocslady can we start with finding out what docs.openshift.org use and allow to use?

**Comment by Preeticp** [comment]
@hferentschik, OpenShift follows these guidelines for adding images: https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#images
One of the links mentioned there seems most relevant: http://asciidoctor.org/docs/asciidoctor-diagram/

**Comment by hferentschik** [comment]
Seems ditto is the preferred option. I guess that's going to work.

**Comment by BrunoVernay** [comment]
AsciiDoctor supports PlantUML, which is, as mentioned, one of the most used tool.
We are talking about 20 lines of diagram code ... But there has been no remarks on the diagram itself. ?

**Comment by LalatenduMohanty** [comment]
@BrunoVernay This is getting fixed in https://github.com/minishift/minishift/pull/1590/ . Let us know what you think.

**Comment by BrunoVernay** [comment]
Besides re-doing the diagram on your side instead of commenting mine, 
it looks like the master and the node are in the same Docker container 
and the arrows meaning is not ultra clear.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1590

**Comment by LalatenduMohanty** [comment]
> Besides re-doing the diagram on your side instead of commenting mine,

Sorry about it. We actually looked at your diagram and tried to suggest improvements but we were not sure how we want to do it (at least me). Also it was hard communicating via github  about some contexts. 

@hferentschik took a fresh stab when he was preparing for a presentation (as he needed it anyway for teh slides) and we had something to start with. 

> it looks like the master and the node are in the same Docker container
> and the arrows meaning is not ultra clear.

If you can open an issue for the improvement and send a PR, that would be great. 
You are welcome
