### ISSUE TITLE
Refactor start.go

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#409]
More and more functionality is pushed into _start.go_, especially the 'oc cluster up' startup. Similar to _cluster.go_ which contains the VM management functionality, the 'cluster up' functionality should move into its own place. 

This is to enforce the separation between command and actual functionality. Also it will make testing easier.

**Comment by budhrg** [comment]
To add one which I came across recently is the [`clusterUp`](https://github.com/minishift/minishift/blob/master/cmd/minishift/cmd/start.go#L311) function is downloading and caching 'oc' binary (or oc installation) and then performing oc cluster up command which IMO are two separate and individual operations.

This is also making the testing a bit harder.

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/commit/4b9ddbf40f525d63a86eac087b1406997b1a5ce9
