### ISSUE TITLE
Specify the IP of the cluster

### ISSUE THREAD

**Issue by sbadakhc** [minishift/minishift#41]
It would be good to specify the IP address of the cluster rather than having one assigned from the pool and then having to query it to find out what it is.

**Comment by gbraad** [comment]
I would suggest closing this issue in favor of the more detailed implementation tasks: #1316, #1457, etc

**Comment by budhrg** [comment]
@minishift/minishift-dev WDYT about closing this issue in favor of #1457  where most of details exists.

**Comment by gbraad** [comment]
Closing, as this issue is too general in scope. We do not actually assign the IP to the cluster, but to the VM first ;-).
