### ISSUE TITLE
Unable to build minishift in Windows without Cygwin

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#412]
Hi,

It looks like cygwin or related piece of software is needed to build minishift binary in windows.
We might want to add more to this ['developing' doc](https://github.com/minishift/minishift/blob/master/docs/developing.md) around Windows specifics.

```
C:\gowork\src\github.com\minishift\minishift>make
FIND: Parameter format not correct
glide --tmp C:\tmp install -v              #####  Modified Makefile
[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Found desired version locally github.com/asaskevich/govalidator 7b3beb6df3c42abd3509abfc3bcacc0fbfb7c877!
.....
[INFO]  --> Exporting github.com/pelletier/go-buffruneio
[INFO]  --> Exporting github.com/openshift/source-to-image
[INFO]  --> Exporting github.com/pkg/browser
[INFO]  --> Exporting github.com/pelletier/go-toml
[INFO]  --> Exporting github.com/russross/blackfriday
[INFO]  --> Exporting github.com/pkg/errors
[INFO]  --> Exporting github.com/pborman/uuid
[INFO]  --> Exporting github.com/spf13/cobra
[INFO]  --> Exporting github.com/spf13/cast
[INFO]  --> Exporting github.com/spf13/viper
[INFO]  --> Exporting github.com/samalba/dockerclient
[INFO]  --> Exporting github.com/ugorji/go
[INFO]  --> Exporting github.com/shurcooL/sanitized_anchor_name
[INFO]  --> Exporting github.com/spf13/afero
[INFO]  --> Exporting github.com/Sirupsen/logrus
[INFO]  --> Exporting github.com/spf13/pflag
[INFO]  --> Exporting github.com/spf13/jwalterweatherman
[INFO]  --> Exporting github.com/xeipuuv/gojsonschema
[INFO]  --> Exporting golang.org/x/net
[INFO]  --> Exporting golang.org/x/sys
[INFO]  --> Exporting golang.org/x/text
[INFO]  --> Exporting golang.org/x/crypto
[INFO]  --> Exporting golang.org/x/oauth2
[INFO]  --> Exporting google.golang.org/cloud
[INFO]  --> Exporting k8s.io/kubernetes
[INFO]  --> Exporting google.golang.org/appengine
[INFO]  --> Exporting k8s.io/client-go
[INFO]  --> Exporting gopkg.in/cheggaaa/pb.v1
[INFO]  --> Exporting gopkg.in/inf.v0
[INFO]  --> Exporting gopkg.in/yaml.v2
[INFO]  Replacing existing vendor dependencies
[INFO]  Removing nested vendor and Godeps/_workspace directories...
[INFO]  Removing: C:\gowork\src\github.com\minishift\minishift\vendor\github.com\cpuguy83\go-md2man\vendor
[INFO]  Removing: C:\gowork\src\github.com\minishift\minishift\vendor\github.com\docker\distribution\vendor
[INFO]  Removing: C:\gowork\src\github.com\minishift\minishift\vendor\github.com\docker\docker\vendor
[INFO]  Removing: C:\gowork\src\github.com\minishift\minishift\vendor\github.com\docker\machine\vendor
[INFO]  Removing: C:\gowork\src\github.com\minishift\minishift\vendor\github.com\google\cadvisor\vendor
[INFO]  Removing: C:\gowork\src\github.com\minishift\minishift\vendor\github.com\opencontainers\runc\Godeps\_workspace\src\github.com\docker\docker\vendor
[INFO]  Removing: C:\gowork\src\github.com\minishift\minishift\vendor\github.com\openshift\imagebuilder\vendor
[INFO]  Removing: C:\gowork\src\github.com\minishift\minishift\vendor\github.com\openshift\origin\vendor
[INFO]  Removing: C:\gowork\src\github.com\minishift\minishift\vendor\github.com\openshift\source-to-image\vendor
[INFO]  Removing: C:\gowork\src\github.com\minishift\minishift\vendor\k8s.io\client-go\1.4\vendor
[INFO]  Removing: C:\gowork\src\github.com\minishift\minishift\vendor\k8s.io\client-go\1.5\vendor
[INFO]  Removing: C:\gowork\src\github.com\minishift\minishift\vendor\k8s.io\kubernetes\vendor
[INFO]  Removing: C:\gowork\src\github.com\minishift\minishift\vendor\github.com\opencontainers\runc\Godeps\_workspace
[INFO]  Removing Godep rewrites for C:\gowork\src\github.com\minishift\minishift\vendor\github.com\opencontainers\runc
mkdir -p ./out/windows-amd64
process_begin: CreateProcess(NULL, mkdir -p ./out/windows-amd64, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [out/windows-amd64] Error 2

C:\gowork\src\github.com\minishift\minishift>mkdir -p ./out/windows-amd64
The syntax of the command is incorrect.

C:\gowork\src\github.com\minishift\minishift>
C:\gowork\src\github.com\minishift\minishift>rm
'rm' is not recognized as an internal or external command,
operable program or batch file.

C:\gowork\src\github.com\minishift\minishift>grep
'grep' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by praveenkumar** [comment]
@budhrg Doesn't we use app-veyor for clean build on windows which doesn't have cygwin stuff?

**Comment by budhrg** [comment]
> @budhrg Doesn't we use app-veyor for clean build on windows which doesn't have cygwin stuff?

Need to understand the appveyor environment. @hferentschik  might know.

**Comment by hferentschik** [comment]
I also don't think that Cygwin gets installed really. But something does provide grep and xargs, otherwise it would not work. My guess would be that _choco install make_  does it - https://github.com/minishift/minishift/blob/master/appveyor.yml#L22

Really the only place were we still use these Unix tools is to determine the _GOFILES_. This is quite convoluted as is. From a Unix perspective a simple _find_ would be best. Maybe we can split this into two cases where on non Windows we use _find_ and on Windows we do the equivalent with some cmdlet or so.

**Comment by gbraad** [comment]
`choco install make` did not provide `grep` or `xargs`. maybe they do provide some tools on the command line from a mingw-based install?

in PowerShell you can use `Get-ChildItem -recurse -include *.go` or `Get-ChildItem -recurse | Where-Object {$_.Name -eq "*.go" }` or similar. However, a solution that works on both is preferred

**Comment by gbraad** [comment]
@budhrg @hferentschik Seems AppVeyor comes installed with a bunch of tools: https://www.appveyor.com/docs/installed-software/#mingw-msys-cygwin

**Comment by hferentschik** [comment]
>  Seems AppVeyor comes installed with a bunch of tools

Got you

**Comment by budhrg** [comment]
> @budhrg @hferentschik Seems AppVeyor comes installed with a bunch of tools: https://www.appveyor.com/docs/installed-software/#mingw-msys-cygwin

I was about to look for it but you got it first :+1:

**Comment by gbraad** [comment]
What concerns me, is that they are not mentioned to be in PATH, So? Which
version is actually running?

**Comment by gbraad** [comment]
I kept a record of my instructions to compile on Windows from `PowerShell` in a gist: https://gist.github.com/gbraad/f95e3d7cc746957b073d659ff620c0fd


Run `powershell` or `CMD` as Administator and start:

```
> powershell -ExecutionPolicy unrestricted
```

This starts a new instance of `powershell` which allowss execution of scripts that are downloaded with a signature.
```powershell
$ iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
$ choco install make
$ choco install git
$ $env:PATH += ";C:\Program Files\Git\bin\"
```

Install go from setup

```
$ $env:GOPATH = "C:\Workspaces\minishift\"
$ $env:PATH += ";$env:GOPATH\bin"
$ go env
$ go get github.com/Masterminds/glide
```

Install cygwin (for `find` and `grep`) in `c:\cygwin`

```
$ $env:PATH += ";c:\cygwin\bin\"
```

The goal has to be to find a way to not have to use `cygwin`, but at the moment to above instructions should work.

**Comment by thatdocslady** [comment]
@gbraad are these instructions a part of "expected behavior" or should they be presented as troubleshooting for Windows devs? also, at which stage of development is this needed (i.e. before/during/after development)?

**Comment by gbraad** [comment]
@thatdocslady At the moment we have not resolved the issue about eliminating Cygwin from the development flow. This is related to before and during development. We will have to come up with solution that either uses cygwin completely (without the chocolatey install) or not using cygwin and only powershell. for now, let's postpone documenting this. WDYT?

**Comment by budhrg** [comment]
> We will have to come up with solution that either uses cygwin completely (without the chocolatey install) or not using cygwin and only powershell. for now, let's postpone documenting this. 

Make sense :+1:

**Comment by hferentschik** [comment]
> for now, let's postpone documenting this.

+1

**Comment by budhrg** [comment]
Although, this PR https://github.com/minishift/minishift/pull/566 fixes the binary building in Windows, let's keep it open to investigate other Makefile operations like `clean` etc

**Comment by hferentschik** [comment]
> Although, this PR #566 fixes the binary building in Windows, let's keep it open to investigate other Makefile operations like clean etc

+1

**Comment by budhrg** [comment]
Closing this issue since it has been fix via https://github.com/minishift/minishift/pull/566

**Comment by budhrg** [comment]
Reopening it as I am unable to compile/clean without cygwin: 

### make
```
PS C:\gowork\src\github.com\minishift\minishift> make
go get -u github.com/jteeuwen/go-bindata/...
process_begin: CreateProcess(NULL, mkdir -p C:/gowork/src/github.com/minishift/minishift/out/bindata, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [C:/gowork/src/github.com/minishift/minishift/out/bindata/addon_assets.go] Error 2
```

### clean
```
PS C:\gowork\src\github.com\minishift\minishift> make clean
rm -rf C:\gowork/pkg/windows_amd64/github.com/minishift
process_begin: CreateProcess(NULL, rm -rf C:\gowork/pkg/windows_amd64/github.com/minishift, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [clean] Error 2
```

**Comment by hferentschik** [comment]
Hmm, probably better to open new issue.

**Comment by budhrg** [comment]
> Hmm, probably better to open new issue.

@hferentschik , I think this is the same issue also error seems to be same too.

**Comment by gbraad** [comment]
Rather open a new issue

**Comment by gbraad** [comment]
And I guess this is actually related to the fact you do not have the path set to $GOPATH/bin, right?

**Comment by budhrg** [comment]
@gbraad I don't think so. 

```
PS C:\gowork\src\github.com\minishift\minishift> $env:GOPATH
C:\gowork

PS C:\gowork\src\github.com\minishift\minishift> $env:GOBIN
C:\gowork\bin\

PS C:\gowork\src\github.com\minishift\minishift> make
go get -u github.com/jteeuwen/go-bindata/...
process_begin: CreateProcess(NULL, mkdir -p C:/gowork/src/github.com/minishift/minishift/out/bindata, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [C:/gowork/src/github.com/minishift/minishift/out/bindata/addon_assets.go] Error 2

PS C:\gowork\src\github.com\minishift\minishift> make clean
rm -rf C:\gowork/pkg/windows_amd64/github.com/minishift
process_begin: CreateProcess(NULL, rm -rf C:\gowork/pkg/windows_amd64/github.com/minishift, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [clean] Error 2
```

Also, `$env:PATH` contains path `$GOPATH/bin`.

**Comment by budhrg** [comment]
Closing in favor of https://github.com/minishift/minishift/issues/1037
