### ISSUE TITLE
Hyper-V virtual networking; NAT and IPv6

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#418]
When a VM is started on Hyper-V, connected to a virtual switch that is configured for NAT, the virtual machine will not receive an IPv4 address (as no DHCP server runs), but gets assigned a IPv6 address. Eg. when using 'DockerNAT'.

However, this leads to unexpected behaviour. The VM is 'Running', but SSH can not connect (and the process seems to be hanging). On a separate cmd prompt the following can be seen:
```
C:\Users\gbraad\Downloads>minishift ip
fe80::215:5dff:fe15:7804
```

Related to: #417

**Comment by lucastheisen** [comment]
I think this may be related to my problem as well... Th only difference is that when i run start it never gets past this:
```
PS C:\Tools\minishift> minishift start
Starting local OpenShift cluster using 'hyperv' hypervisor...
```
Using hyperv manager, i can _Connect..._ to the vm and watch it boot all the way to the root prompt:
```
![image](https://user-images.githubusercontent.com/1952786/27358025-b23c2188-55e2-11e7-85b8-982d44d0f8b0.png)
```
Also, inside of hyperv manager i can see an IPV6 address assigned under the network tab...  But then it just hangs.

**Comment by gbraad** [comment]
@lucastheisen we have since provided a way to select the networking switch https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html#hyper-v hopefully this helps. Do you have Docker for Windows installed?

**Comment by lucastheisen** [comment]
@gbraad, I did set up my network switch in that fashion.  Created one according to the instructions you linked to on the Microsoft page...  The only difference being that I created it as an internal Network with NAT...

**Comment by gbraad** [comment]
@lalatenduM @hferentschik one of the things we can do on startup is to throw an error when the host has two (or no) virtual switches, and of course report which one is used

**Comment by gbraad** [comment]
@lucastheisen The text mentions "set the environment variable HYPERV_VIRTUAL_SWITCH to the name of the **external** virtual switch"

At the moment we do not support NAT or Internal, as they do not provide the necessary DHCP functionality.

**Comment by lucastheisen** [comment]
@gbraad, I did see that, but thought this issue was about getting NAT support, so I hoped that little please was outdated (given that docker for Windows has this feature).  Without NAT, my team is out of luck, as corporate won't assign ips to non-corporate managed images.  If I keep watch on this ticket will it let us know when NAT is supported?

**Comment by carljmosca** [comment]
Is NAT support expected for v1.4.0?

**Comment by gbraad** [comment]
It is currently not on the roadmap to be solved. At the moment we detect
it. The solution is also related to the virtual network stack of HyperV and
improvements to this is expected (although not confirmed).

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by carljmosca** [comment]
Ok thank you for the update.

**Comment by gbraad** [comment]
@LalatenduMohanty @praveenkumar @hferentschik @budhrg 

I think we need to consider including this to the current milestone... Even though I might not be able to work on it instantly, we need to do something about this ASAP.

**Comment by gbraad** [comment]
Easy way to setup for testing:

Note: I assume you have Docker for Windows installed
```
C:\Users\gbraad>set HYPERV_VIRTUAL_SWITCH=DockerNAT

C:\Users\gbraad>minishift start --iso-url centos
-- Checking if Hyper-V driver is configured ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ... -
```

After a short while, open another command prompt:
```
C:\Users\gbraad>minishift status
Running

C:\Users\gbraad>minishift ip
fe80::215:5dff:fe15:7883
```

**Comment by lucastheisen** [comment]
@gbraad , are you saying _I_ should try setting the eth0 in the minishift instance to match the docker config as a workaround?  Or are you commenting so that the other members of the project have a way to begin to work on NAT support?

**Comment by gbraad** [comment]
You can assign an IP address to the VM in the Docker NAT range, and this will work. It might however clash with the IP addresses that are handed out already to a container, but generally you can do this. As one of the solutions we are working on #1316, and coordinate with Minikube to get a general solution.

We are still looking into other solutions.

**Comment by gbraad** [comment]
@lucastheisen We have worked on a static IP option which allows you to use the NAT functionality. Please see https://github.com/minishift/minishift/issues/1316#issuecomment-331946998 for more information.

Closing this issue

**Comment by gbraad** [comment]
Added #1500 to look into the IPv6 support, as this needs to be addressed in general (across all hypervisors)
