### ISSUE TITLE
Hyper-V virtual networking: no IP address issued

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#419]
When a VM is started on Hyper-V, attached to a non-external network, the instance will not be assigned an IPv4 address in time. Virtual networking on Hyper-V does not have a built-in DHCP server, and will therefore eventually get a link-local address.

What will happen is that `minishift start` never continues. In a different cmd prompt the following can be seen:

```
C:\Users\gbraad\Downloads>minishift status
Running

C:\Users\gbraad\Downloads>minishift ip
E0216 19:44:20.408094     860 ip.go:45] Error getting IP:  IP not found
```

Also, `minishift ssh` will error with the same `IP not found` error`. This will cause the startup to hang.

Related to: #417

**Comment by LalatenduMohanty** [comment]
@gbraad We have seen this in ADB/CDK.  The virtual switch needs be external type to be able to connect to external network  and get IP address.

**Comment by gbraad** [comment]
@LalatenduMohanty we might have to implement something like IP reachability checks and report these as part of #485. Have implemented something similar for #480 to detect the IP of the host.

**Comment by gbraad** [comment]
Will self-assign, but part of this can be resolved with #485

**Comment by budhrg** [comment]
Hi @gbraad , #485 has been resolved now. How much left on this issue now?

**Comment by gbraad** [comment]
Since #1316 it is possible to assign an IP address to an interface connected to an internal switch.

Closing
