### ISSUE TITLE
Fix boilerplate check to accept year 2017 

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#420]
It seems the boilerplate.py returns an error if the copyright year is 2017. It is called through https://github.com/minishift/minishift/blob/master/prerelease.sh. We should fix to accept year 2017.

[1] https://github.com/minishift/minishift/blob/master/hack/boilerplate/boilerplate.py

**Comment by gbraad** [comment]
The pull request doesn't contain an issue reference...

**Comment by hferentschik** [comment]
Merged via pull request #424.

Moving forward I suggest to apply a more minimalistic licence header which in particular does not have any date fields.
