### ISSUE TITLE
Introduce short names for our maintained ISOs

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#428]
ATM, only the default Boot2Docker ISO gets automatically downloaded when nothing is cached. If someone wants to use the CentOS ISO he needs to specify the URL and he also has to be aware of any compatibility issues. 

It should be possible for the user to just specify that he wants to use the CentOS / RHEL image and it gets downloaded automatically. For this reason I suggest to introduce short names for our maintained images. Something along these lines

* `minishift start --iso-url=b2d` - that the same as our current default
* `minishift start --iso-url=centos` - will 'expand' to the latest compatible CentOS ISO
* `minishift start --iso-url=rhel` - get the latest RHEL image (if possible, would probably need to ask for credentials)

**Comment by budhrg** [comment]
IMO, chosing `--iso-url` flag is not appropriate here. Now, the flexibility of chosing iso url is lost.

And, I also don't like to mix the values of `--iso-url` as :
```
- file://<iso-path>
- https://<iso-url>
-b2d / centos /rhel
```
Quite unclear and weird to me.

I would be happy if we have flag like `--iso-type` which IMO provide more clarity.
Now, lines are
```
minishift start --iso-type=b2d
minishift start --iso-type=centos
minishift start --iso-type=rhel

# And if user want to specify URL (most of the case it is always non-default one)
minishift start --iso-url=<url>
```

**Comment by hferentschik** [comment]
The problem is with --iso-type and --iso-url, that you end up with conflicting settings. I have no problem with short names, after all they stand in for actual URLs. Interested to know how others think about it.

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift/pull/1033
