### ISSUE TITLE
Enable CI to get triggered when a push to master occurs

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#435]
Currently, CI only get triggered when PR is sent.

We need to trigger it when PR get merged with master.

It should also store the generated artifacts as well.

See https://github.com/minishift/minishift/issues/415#issuecomment-280584915

**Comment by hferentschik** [comment]
> We need to trigger it when PR get merged with master.

Not just after pull request merges. Any push to master (which adds a commit) should trigger the build.

**Comment by budhrg** [comment]
Not working at the moment.

**Comment by hferentschik** [comment]
Resolved.

**Comment by budhrg** [comment]
Reopening again since found not working from this build https://ci.centos.org/job/minishift-build-master/12/console.

Error message :
```
00:16:55.105 + set +x
00:16:55.199 rsync: mkdir "/minishift/master/12" (in minishift) failed: No such file or directory (2)
00:16:55.199 rsync error: error in file IO (code 11) at main.c(587) [Receiver=3.0.9]
00:16:55.299 rsync: read error: Connection reset by peer (104)
00:16:55.299 rsync error: error in rsync protocol data stream (code 12) at io.c(764) [sender=3.0.9]
00:16:55.305 Connection to 172.19.3.68 closed.
```
shows that the *rsync* command to archive server is not working as I used rsync command as ([source](https://github.com/budhrg/minishift/blob/35d6aee77ae9a55de9739b783ea06dc7b61365d9/centos_ci.sh#L91))
```
rsync -a --rsync-path="mkdir -p minishift/master/$BUILD_NUMBER/ && rsync" <source> <destination>
```
as per this suggestion http://stackoverflow.com/a/22908437/1120530. 

Found that ` --relative` one is working from this build https://ci.centos.org/job/minishift-b2d-iso/36.

**Comment by hferentschik** [comment]
Let's not re-open when a issue is is part of a closed milestones. That makes the changelog and everything around inconsistent. Re-opening is ok while the release has not happened yet. After that we need a new issue.
