### ISSUE TITLE
Developer should be allowed to create Persistent Volumes OOTB

### ISSUE THREAD

**Issue by jstrachan** [minishift/minishift#458]
lets make the OOTB security in minishift so that developers can create PVs on their own laptop

**Comment by hferentschik** [comment]
yes, it is on the roadmap to let the user configure persistence volumes. See also issue #389. We will piggy back on what _cluster up_ is going to offer and wrap some utility commands around this.

**Comment by budhrg** [comment]
Isn't this should be closed when we have marked it as `duplicate`, @hferentschik ?

**Comment by praveenkumar** [comment]
@hferentschik should we close it now?

**Comment by hferentschik** [comment]
I think this is about actually creating new persistent volumes. @jstrachan, can you elaborate on what you had in mind?

**Comment by budhrg** [comment]
@jstrachan , please add your opinion here.

**Comment by jstrachan** [comment]
having lots of PVs available OOTB sounds fine to me TBH

**Comment by jorgemoralespou** [comment]
With minishift you get now 100 PVs OOTB

**Comment by hferentschik** [comment]
So maybe we can close this issue then. You get 100 PVs out of the box and if you want more you have all the means to configure that. Either ad-hoc or by creating (and contributing ;-)) and add-on.
