### ISSUE TITLE
Add GitLab CI runner build defintion

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#460]
Although not essential, it is something I use myself, and runs on my own instance of GitLab. It however, can also run public as can be seen on: https://gitlab.com/gbraad/minishift-build and an example build: https://gitlab.com/gbraad/minishift-build/builds/10847637

However, the current setup relies on webhooks to have a build triggered, as the definition lives outside the archive. If a slightly modified .gitlab-ci.yml could live inside the minishift archive, the builds get triggered on each commit. It will so allow the community to easily take the archive and produce a completely automated pipeline using GitLab and the CI runners for themselves.

**Comment by LalatenduMohanty** [comment]
@gbraad I think it would be useful for community developers who want to contribute to minishift project, right?

**Comment by gbraad** [comment]
yes... as they easily replicate an environment that can build, and eventually even test.

**Comment by praveenkumar** [comment]
@gbraad you still want to look into it or we can close it right now and reopen when have some time?

**Comment by budhrg** [comment]
I am happy to keep it if it provide consistent results, easy configuration over Travis CI. 
If the infrastructure provides nested virt, then its worth to try.

**Comment by gbraad** [comment]
Alreayd have this working for myself... can contribute this. just didn't take the time to adjust it for consistency with the current `centos_ci.sh` to prevent duplication.

**Comment by hferentschik** [comment]
What would it give us? We have quite a few CI systems already? Is there any feature we would get which we don't have. If you say it supported nested virt, I am in. If not, I am not sure whether it really adds value at this stage.

**Comment by LalatenduMohanty** [comment]
Fixed via https://github.com/minishift/minishift/pull/1239
