### ISSUE TITLE
After restart minishift, the pod can not run

### ISSUE THREAD

**Issue by warmchang** [minishift/minishift#461]
Host OS: Microsoft Windows 2012
Minishift version: minishift-1.0.0-beta.4-windows-amd64
vm-driver: virtualbox

1. Run the minishift start and setup nodejs sample project, all of the pod is ok:

> NAME                   READY     STATUS      RESTARTS   AGE
> po/nodejs-ex-1-b8txq   1/1       Running     0          3m
> po/nodejs-ex-1-build   0/1       Completed   0          14m

2. Run minishift stop.

3. Rerun minishift start, the status of pod is ImagePullBackOff:

> NAME                READY     STATUS             RESTARTS   AGE       IP           NODE
> nodejs-ex-1-b8txq   0/1       ImagePullBackOff   0          56m       172.17.0.3   192.168.99.100
> nodejs-ex-1-build   0/1       Completed          0          1h        172.17.0.2   192.168.99.100

4. describe pod Events:

>   FirstSeen     LastSeen        Count   From                            SubObjectPath                   Type            Reason          Message
>   ---------     --------        -----   ----                            -------------                   --------        ------          -------
>   55m           55m             1       {default-scheduler }                                            Normal          Scheduled       Successfully assigned nodejs-ex-1-b8txq to 192.168.99.100
>   55m           55m             1       {kubelet 192.168.99.100}        spec.containers{nodejs-ex}      Normal          Pulling         pulling image "172.30.1.1:5000/myproject/nodejs-ex@sha256:cdff521d5d9a98724c336389f8e92b0a8b591db0c3fad830f06540e0ed02176d"
>   55m           55m             1       {kubelet 192.168.99.100}        spec.containers{nodejs-ex}      Normal          Pulled          Successfully pulled image "172.30.1.1:5000/myproject/nodejs-ex@sha256:cdff521d5d9a98724c336389f8e92b0a8b591db0c3fad830f06540e0ed02176d"
>   55m           55m             1       {kubelet 192.168.99.100}        spec.containers{nodejs-ex}      Normal          Created         Created container with docker id 4f399d3ce563; Security:[seccomp=unconfined]
>   55m           55m             1       {kubelet 192.168.99.100}        spec.containers{nodejs-ex}      Normal          Started         Started container with docker id 4f399d3ce563
>   48m           48m             1       {kubelet 192.168.99.100}        spec.containers{nodejs-ex}      Warning         Failed          Failed to pull image "172.30.1.1:5000/myproject/nodejs-ex@sha256:cdff521d5d9a98724c336389f8e92b0a8b591db0c3fad830f06540e0ed02176d": Error response from daemon: {"message":"Get http://172.30.1.1:5000/v2/: dial tcp 172.30.1.1:5000: getsockopt: connection refused"}
>   48m           48m             1       {kubelet 192.168.99.100}                                        Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "nodejs-ex" with ErrImagePull: "Error response from daemon: {\"message\":\"Get http://172.30.1.1:5000/v2/: dial tcp 172.30.1.1:5000: getsockopt: connection refused\"}"
> 
>   47m   46m     5       {kubelet 192.168.99.100}                Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "nodejs-ex" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=nodejs-ex pod=nodejs-ex-1-b8txq_myproject(49acbade-f8ca-11e6-a22e-7e3e63f2b997)"
> 
>   47m   46m     5       {kubelet 192.168.99.100}        spec.containers{nodejs-ex}      Warning BackOff         Back-off restarting failed docker container
>   48m   33s     13      {kubelet 192.168.99.100}        spec.containers{nodejs-ex}      Warning Failed          Failed to pull image "172.30.1.1:5000/myproject/nodejs-ex@sha256:cdff521d5d9a98724c336389f8e92b0a8b591db0c3fad830f06540e0ed02176d": Error response from daemon: {"message":"manifest unknown: manifest unknown"}
>   48m   33s     13      {kubelet 192.168.99.100}                                        Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "nodejs-ex" with ErrImagePull: "Error response from daemon: {\"message\":\"manifest unknown: manifest unknown\"}"
> 
>   48m   33s     14      {kubelet 192.168.99.100}        spec.containers{nodejs-ex}      Normal  Pulling         pulling image "172.30.1.1:5000/myproject/nodejs-ex@sha256:cdff521d5d9a98724c336389f8e92b0a8b591db0c3fad830f06540e0ed02176d"
>   48m   3s      200     {kubelet 192.168.99.100}        spec.containers{nodejs-ex}      Normal  BackOff         Back-off pulling image "172.30.1.1:5000/myproject/nodejs-ex@sha256:cdff521d5d9a98724c336389f8e92b0a8b591db0c3fad830f06540e0ed02176d"
>   48m   3s      200     {kubelet 192.168.99.100}                                        Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "nodejs-ex" with ImagePullBackOff: "Back-off pulling image \"172.30.1.1:5000/myproject/nodejs-ex@sha256:cdff521d5d9a98724c336389f8e92b0a8b591db0c3fad830f06540e0ed02176d\""

5. Check the default project, the status of docker-registry pod&service is running:

> NAME                            READY     STATUS      RESTARTS   AGE       IP               NODE
> docker-registry-1-gjc03         1/1       Running     1          1h        172.17.0.4       192.168.99.100
> persistent-volume-setup-47gz0   0/1       Completed   0          1h        172.17.0.3       192.168.99.100
> router-1-6npk4                  1/1       Running     1          1h        192.168.99.100   192.168.99.100

> NAME              CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE       SELECTOR
> docker-registry   172.30.1.1       <none>        5000/TCP                  1h        docker-registry=default
> kubernetes        172.30.0.1       <none>        443/TCP,53/UDP,53/TCP     1h        <none>
> router            172.30.197.230   <none>        80/TCP,443/TCP,1936/TCP   1h        router=router

**Comment by jorgemoralespou** [comment]
@hferentschik I kind of recall that in oc 1.4.1 the registry is not persistent and that might introduce this type of problems, where you have the metadata in etcd pointing to the registry but there is no layers.

https://github.com/openshift/origin/pull/12456/files#diff-289dd62730ab075b34eb10a03a9687e6R735

Adding @csrwong so he can chime in on the correctness of my assessment

**Comment by hferentschik** [comment]
@warmchang is this still something you are experiencing? Could you maybe try the latest release - https://github.com/minishift/minishift/releases/tag/v1.0.0-rc.1 - and see whether you still can reproduce the problem. This latest version of Minishift aligns with OpenShift 1.5, so the issue might be gone.

**Comment by warmchang** [comment]
@hferentschik thank you for your answer. I'll try the fresh v1.0.0-rc.1 version to check this issue.

**Comment by warmchang** [comment]
Fixed.

**Comment by budhrg** [comment]
👍
