### ISSUE TITLE
Improve the manual install steps for xhyve driver

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#466]
Currently we document to compile the driver from source. Instead we should document to download version x.y.z from the release page. Then we need to document the two main approaches to actually use the driver:

* Modify PATH
* Add to docker-machine default location

**Comment by LalatenduMohanty** [comment]
The manual installation section for Xhyve drive [1] now has steps to compile the code i.e. we expect the user to compile and build the driver Which is not user friendly. 
As @hferentschik suggested , we should change the steps similar to KVM driver i.e. we should be able to take the released binary , keep it in the right location of the OSX and then give required access permission.

[1] https://github.com/minishift/minishift/blob/master/docs/docker-machine-drivers.md#manual-install
[2] https://github.com/minishift/minishift/blob/master/docs/docker-machine-drivers.md#kvm-driver

**Comment by praveenkumar** [comment]
There is only one down-fall of using xhyve docker driver directly from binary - if user is using latest version of OSx then binary may or may not work and in that case it's always good  to compile it manually before consume. So what we should do is put a note around same so when user hit a not working driver binary then manually compile and install it.

**Comment by hferentschik** [comment]
> So what we should do is put a note around same so when user hit a not working driver binary then manually compile and install it.

+1

**Comment by hferentschik** [comment]
Merged via pull request #604
