### ISSUE TITLE
Registration code never called for non proxy use cases

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#468]
Because of the below code change the "registration code moved behind the if loop of proxy information .So it is only called when proxy is provided. 
[1] https://github.com/minishift/minishift/commit/60b8ddcc504113313d81bd6e32e4b66053a02530

**Comment by LalatenduMohanty** [comment]
During testing I manually checked if the VM is registered only for proxy use cases. For non proxy use cases I just checked if "minishift start" is working fine and I missed this.

**Comment by budhrg** [comment]
I just now feel how important it is to have negative test case too.

**Comment by gbraad** [comment]
Please create a PR, so a test build will be created in CI.

**Comment by hferentschik** [comment]
Merged via pull request #469

**Comment by LalatenduMohanty** [comment]
@budhrg The unit test actually do not run the command on the VM,  So we need to discuss and plan it.
