### ISSUE TITLE
Restore Kubernetes copyright notices

### ISSUE THREAD

**Issue by richardfontana** [minishift/minishift#472]
This commit https://github.com/minishift/minishift/commit/6abc7d6b73aa903b8d542f311e72d528a7a27e32
and anything similar need to be reverted to the extent that any code from Minikube remains in a source file from which the Kubernetes copyright notice was removed. It would be okay for such files to have, for example:

> Copyright 2016 The Kubernetes Authors All rights reserved.
> Copyright 2016 Red Hat, Inc.

But you can't delete the earlier copyright notice.

**Comment by hferentschik** [comment]
@LalatenduMohanty can you please hold off in this one?

**Comment by hferentschik** [comment]
Merged via pull request #488
