### ISSUE TITLE
Error when oc get cs

### ISSUE THREAD

**Issue by hoeghh** [minishift/minishift#481]
I get an error when running this command right after minishift start has finished.

```
oc get cs
NAME                 STATUS      MESSAGE                                                                                        ERROR
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: getsockopt: connection refused   
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: getsockopt: connection refused   
etcd-0               Unhealthy   Get https://192.168.42.34:4001/health: remote error: tls: bad certificate   
```

I don't know if its supposed to be this way?

**Comment by hferentschik** [comment]
> I don't know if its supposed to be this way?

Well, no I guess. However, this is not really a Minishift issue in this case, but rather an OpenShift one -
https://github.com/openshift/origin/issues/3667

I am going to close this issue, since everything related to this should go there.
