### ISSUE TITLE
Starting minishift on OS X fails

### ISSUE THREAD

**Issue by asghar62** [minishift/minishift#482]
$ minishift start --vm-driver xhyve
E0224 14:34:14.175766    8230 start.go:98] Error starting host:  Error starting stopped host: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
Error starting stopped host: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

$xhyve -v
xhyve: 0.2.0

xhyve is a port of FreeBSD's bhyve hypervisor to OS X that
works entirely in userspace and has no other dependencies.

Homepage: https://github.com/mist64/xhyve
License: BSD

$ minishift version
minishift version: 0.9.0

$ echo $PATH
/Users/ariahi/Downloads/google-cloud-sdk/bin:/Users/ariahi/Downloads/google-cloud-sdk/bin:/Users/ariahi/Downloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/xhyve

**Comment by budhrg** [comment]
Hi @asghar62 ,

I can notice that you are using quite old version of minishift `0.9.0` which was based on minikube.
From 1.0.0-beta onwards, we have migrated into `oc cluster up` approach.

Could you try with latest version of minishift - https://github.com/minishift/minishift/releases/tag/v1.0.0-beta.4 ?

**Comment by praveenkumar** [comment]
@asghar62 also xhyve driver is not the latest one so you do need to update it along with minishift version.

**Comment by praveenkumar** [comment]
@asghar62 Ping, Can you provide info if this issue solved for you now?

**Comment by ryanj** [comment]
I'm seeing this issue with 1.0.0-rc1

**Comment by hferentschik** [comment]
$ minishift start --vm-driver xhyve
    E0224 14:34:14.175766 8230 start.go:98] Error starting host: Error starting stopped host: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

In this case, you start or better try to start a VM using the xhyve driver, even though you still have an existing/stopped VirtualBox managed VM. This is not going to work. You will need to run _minishift delete_ first. 

This is a problem we are planning to address from a ux point of view with issue #179

**Comment by hferentschik** [comment]
I am going to close this issue, since I don't think there is anything we need to to in this particular case.
