### ISSUE TITLE
Add support for NFS volumes

### ISSUE THREAD

**Issue by bronhaim** [minishift/minishift#484]
mounted folder is set with /nfsshare/pgdata  *(rw,sync,no_root_squash) in remote host (which is accessible from within the vm by fqdn)

the pod definition is as follow:

    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        app: test
      name: test
    spec:
      containers:
        - image: training/webapp:latest
          name: test
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/buga
              name: test
      volumes:
        - name: test
          nfs:
            path: "/nfsshare/pgdata"
            server: dhcp-0-174.tlv.redhat.com

starting it gives the following and fail to start:

    MountVolume.SetUp failed for volume "kubernetes.io/nfs/ca23647b-fcd3-11e6-9f17-bee993a77bd2-buga" (spec.Name: "test") pod "ca23647b-fcd3-11e6-9f17-bee993a77bd2" (UID: "ca23647b-fcd3-11e6-9f17-bee993a77bd2") with: mount failed: exit status 32 Mounting arguments: dhcp-0-174.tlv.redhat.com:/nfsshare/pgdata /var/lib/origin/openshift.local.volumes/pods/ca23647b-fcd3-11e6-9f17-bee993a77bd2/volumes/kubernetes.io~nfs/buga nfs [] Output: mount: wrong fs type, bad option, bad superblock on dhcp-0-174.tlv.redhat.com:/nfsshare/pgdata, missing codepage or helper program, or other error (for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program) In some cases useful info is found in syslog - try dmesg | tail or so. 

Unable to mount volumes for pod "test_aa(ca23647b-fcd3-11e6-9f17-bee993a77bd2)": timeout expired waiting for volumes to attach/mount for pod "test"/"aa". list of unattached/unmounted volumes=[test]

**Comment by fabiand** [comment]
This is eventually similar to kubernetes/minikube#1174 where iSCSI volumes can not be used because of missing iscsiadm and kmods.

**Comment by hferentschik** [comment]
@bronhaim which version of Minishift are you using and which ISO image? The default boot2docker or the CentOS ISO?

**Comment by bronhaim** [comment]
default b2d image, and the issue was that it doesn't include nfs-utils
package

**Comment by gbraad** [comment]
Both CentOS and B2D image do not include nfs-utils at the moment. We need to determine when this will be part of our roadmap.

**Comment by praveenkumar** [comment]
@gbraad do we have this similar issue on iso repo side also I think that where we need it right?

**Comment by gbraad** [comment]
* https://github.com/minishift/minishift-centos-iso/issues/118
 * https://github.com/minishift/minishift-b2d-iso/issues/44

**Comment by gbraad** [comment]
Created the following PRs: 

  * https://github.com/minishift/minishift-centos-iso/pull/120
  * https://github.com/minishift/minishift-b2d-iso/pull/45

**Comment by hferentschik** [comment]
What's the next step here? Anything we need to do on the Minshift side? I don't think so, right?

**Comment by fabiand** [comment]
Correct, it just needs to be verified that the new isos contain evrything that is needed.

**Comment by hferentschik** [comment]
Actually there is one more thing at least we need to do as part of this issue. We added the NFS utils to the B2D and CentOS ISOs, but only released the latter. We need to do a release of the B2D ISO as well and update the default B2D ISO version in the Makefile.

**Comment by gbraad** [comment]
@fabiand components are verified to be installed in the tests of the ISO images, however, as Hardy mentioned, we did not bump the version of the images.

New version has been cut, and we expect to release this soon.

**Comment by praveenkumar** [comment]
Closed by #1233
