### ISSUE TITLE
Invalid startup specification is only logged 

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#486]
On `minishift start` it seems values are logged, but not regarded as startup errors.
```
glog.Errorf("Disk size is not valid: %s", err)
```

For invalid values (eg. wrong unit, or too little) we need to fail startup.

Providing user feedback to indicate the other values can be part of #485.

**Comment by hferentschik** [comment]
I think this is obsolete by now - https://github.com/minishift/minishift/blob/3b82cbed7eba3ee6890621e5e966ea4515b19fa0/cmd/minishift/cmd/config/validations.go#L60-L60

@gbraad WDYT?

**Comment by budhrg** [comment]
Ya it seems so.
