### ISSUE TITLE
Investigate if nested virtualization is possible for Windows-based CI

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#491]
Currently we are using AppVeyor to provide builds (and tests) on Windows. However, since Docker Machine (libmachine) needs a hypervisor, the CI would need to support nested virtualization to support running integration tests.

**Comment by gbraad** [comment]
We have been granted access to the 'Windows Server 2016` [ref](https://github.com/appveyor/ci/issues/1150#issuecomment-283103564).

**Comment by gbraad** [comment]
https://ci.appveyor.com/project/gbraad/appveyor-test/build/1.0.8

```
./out/minishift.exe start --vm-driver hyperv
Starting local OpenShift cluster using 'hyperv' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.1/minishift-b2d.iso'

./out/minishift.exe : E0301 04:17:49.981641    3676 start.go:150] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: exit status 1. Retrying.
At line:1 char:1
+ ./out/minishift.exe start --vm-driver hyperv
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (E0301 04:17:49....us 1. Retrying.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
E0301 04:17:51.353694    3676 start.go:150] Error starting the VM: Error starting stopped host: exit status 1. Retrying.
E0301 04:17:52.685699    3676 start.go:150] Error starting the VM: Error starting stopped host: exit status 1. Retrying.
E0301 04:17:52.685699    3676 start.go:156] Error starting the VM:  Error creating the VM. Error creating machine: Error in driver during machine creation: exit status 1
Error starting stopped host: exit status 1
Error starting stopped host: exit status 1
Command executed with exception: E0301 04:17:52.685699    3676 start.go:156] Error starting the VM:  Error creating the VM. Error creating machine: Error in driver during machine creation: exit status 1
Error starting stopped host: exit status 1
Error starting stopped host: exit status 1
```

**Comment by hferentschik** [comment]
:-(

**Comment by praveenkumar** [comment]
@gbraad so looks like we don't have any option. Good thing is our downstream bits now run all integration tests for each platform. Do you need more time to investigate it?

**Comment by hferentschik** [comment]
I think we should keep it open. We should keep looking for a solution for this.

**Comment by gbraad** [comment]
I agree to keep it open...

**Comment by budhrg** [comment]
Same here. +1 for to keep it open.

**Comment by hferentschik** [comment]
Issue within AppVeyor to track enabling nested virtualisation https://github.com/appveyor/ci/issues/1642

**Comment by gbraad** [comment]
Azure provides nested virtualization: https://azurestack.blog/2017/07/deploy-azure-stack-development-kit-on-an-azure-vm/

**Comment by budhrg** [comment]
@hferentschik 

> Issue within AppVeyor to track enabling nested virtualisation appveyor/ci#1642

It's for "custom" private build clouds, not for public hosted build cloud. See https://github.com/appveyor/ci/issues/1642#issuecomment-314871952

> Azure provides nested virtualization: https://azurestack.blog/2017/07/deploy-azure-stack-development-kit-on-an-azure-vm/

https://azure.microsoft.com/en-us/blog/nested-virtualization-in-azure/ also it seems not free for any Open source project.

**Comment by hferentschik** [comment]
We are currently investigating a different approach with AppVeyor. At the moment nested virt is not possible with any of the AppVeyor provided images / offerings.

**Comment by budhrg** [comment]
@hferentschik , @gbraad Should we keep it open still after our findings?
