### ISSUE TITLE
How to connect to database on host from container in minishift?

### ISSUE THREAD

**Issue by magick93** [minishift/minishift#494]
Im trying to connect to a postgres database, from a springboot application deployed in minishift.

The postgres server is running on the same host that minishift is running on.

I've tried setting the postgres serve to listen on a specific IP address, and use this same address in the springboot jdbc connection url but I still get `org.postgresql.util.PSQLException: Connection to 172.99.0.1:5432 refused`

I've also tried using `10.0.2.2`

Also tried, in `/etc/postgresql/9.5/main/postgresql.conf`, setting:

`listen_addresses = '*'  `
How can I connect to a database external to minishift, running on same host?

**Comment by jorgemoralespou** [comment]
https://docs.openshift.org/latest/dev_guide/integrating_external_services.html#external-mysql-database

This means that the host IP is accessible from the guest minishift VM.

**Comment by hferentschik** [comment]
Closing this, since it is not really an issue.
