### ISSUE TITLE
Travis CI builds keep hitting GitHub rate limit for unit tests

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#502]
Despite having set _MINISHIFT_GITHUB_API_TOKEN_ as an environment variable in the Travis CI settings,  builds still regularly hit the GitHub API rate limit during unit tests.

It seems the environment variable is not set/available for the process running the unit tests.

The reason might be, that Travis CI only sets the variable for the main build process. Make in turn starts a sub process for each line of a recipe. It does in this case not pass on all environment variables, but only the one set in the Makefile (https://www.gnu.org/software/make/manual/make.html#Environment). For that reason the process running the unit tests would not have _MINISHIFT_GITHUB_API_TOKEN_ set and hence uses the GitHub API unauthenticated.

**Comment by hferentschik** [comment]
Actually all wrong ;-) Sub process do get the env variable set as well. In fact all is working fine on master. 

The issue is that pull requests from forked repositories don't get the environment variable applied out of security reasons - https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions. This means pull request builds won't have the GitHub token variable injected. 

The issue will arise if there are many pull requests being build in a short timeframe. Then some of them can hit the rate limit.

If we wanted to work around this, we would need to put something into our code which skips the affected unit tests when building Travis CI pull requests. Not sure whether we want to go down this route.

**Comment by budhrg** [comment]
I also see following in their security reason page - 

> Travis CI makes encrypted variables and data available only to pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them.

I think they should at least allow Pull requests from forked repositories that belongs to members with write access to the repository.

Can we query them about it?

**Comment by hferentschik** [comment]
Merged via pull request #505
