### ISSUE TITLE
Give the developer sudoers role

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#509]
Recently @hferentschik pointed a nice article about how we can implement same linux philosophy of having sudo to perform admin tasks and I think this will helpful for us and for users.

- https://bierkowski.com/openshift-cli-morsels-sudo-and-user-impersonation/

**Comment by jorgemoralespou** [comment]
Agree.

https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/master/oc-cluster#L475-L478

**Comment by hferentschik** [comment]
Merged via pull request #527
