### ISSUE TITLE
Add a version command as openshift subcommand

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#511]
Currently user doesn't know which version of OpenShift they are using/running, adding version command will help in that sense.

**Comment by hferentschik** [comment]
If we add the version command _minishift openshift version_ reporting the version of the currently running OpenShift cluster, we could add the _list_versions_ command as subcommand: _minishift openshift version list_. This would align with _minishift openshift service_ and _minishift openshift service list_.

**Comment by praveenkumar** [comment]
We might to look into to get tags from the docker hub for the released so that in downstream we can just change the url to internal registry and everything works.

**Comment by gbraad** [comment]
#515

**Comment by hferentschik** [comment]
Merged via pull request #628
