### ISSUE TITLE
CDK refuses OpenShift Container Platform versions

### ISSUE THREAD

**Issue by wkulhanek** [minishift/minishift#513]
I downloaded the Minishift as part of the CDK 3 Beta. It downloads OCP 3.4.1.2 oc client binary. Current is 3.4.1.7.

So I tried to start it with "minishift start --openshift-version v3.4.1.7"

which results in:

Minishift does not support Openshift version v3.4.1.7. You need to use a version >= 1.3.1.

There seem to be some remnants of the Origin stuff still there. Also in my book 3.4 is bigger than 1.3. :-)

**Comment by hferentschik** [comment]
> I downloaded the Minishift as part of the CDK 3 Beta.

Nice.

> It downloads OCP 3.4.1.2 oc client binary. 

Well technically it is the _oc_ binary bundled with the _minishift_ binary and extracted via the _setup-cdk_ command.

> So I tried to start it with "minishift start --openshift-version v3.4.1.7"

That's not working atm. This is an outstanding issue of the CDK 3 (it's still beta) - https://issues.jboss.org/browse/CDK-51

The next version of the CDK will allow you to switch the image to a later version. As you say, right now there is still some Origin logic in place.

**Comment by LalatenduMohanty** [comment]
You have to just stick to the packaged OCP version now till we fix it i.e. no `--openshift-version`

**Comment by hferentschik** [comment]
I am going to close this issue here, since it is tracked in CDK-51 and all CDK related issues should go there - https://issues.jboss.org/projects/CDK
