### ISSUE TITLE
Exposing internal services for development

### ISSUE THREAD

**Issue by lulf** [minishift/minishift#514]
When using minishift for local development, it is sometimes useful to be able to connect to 'internal' services in the openshift application for debugging.

This is possible when using 'oc cluster up', because all services are accessible from the host. With minishift, these services are now hidden inside the VM. For HTTP it is possible to work around this by exposing a route. 

However, for non-HTTP this is not a viable alternative unless you can use TLS passthrough to connect to the service.

It would be nice if minishift could support some way to expose the services to the host environment.

**Comment by hferentschik** [comment]
> It would be nice if minishift could support some way to expose the services to the host environment.

So what exactly would you have in mind there?

**Comment by lulf** [comment]
Not sure what the best approach is, but one way would be to be able to specify some kind of port forwarding or mapping from VM to host, or in some way setup routing on the host to forward packets to the VM for the service IP addresses.

**Comment by hferentschik** [comment]
You can always expose the service as a NodePort - https://docs.openshift.org/latest/minishift/openshift/exposing-services.html. Is this not enough? Is there anything more you have in mind?

**Comment by budhrg** [comment]
@lulf Any update?

**Comment by lulf** [comment]
@budhrg NodePort works - but the problem is that now I need to add that whenever i'm running on minishift. For local development, it's nice if the services matches what you'd deploy in production.

**Comment by praveenkumar** [comment]
@lulf right because service is part of VM and it not accessible directly until you expose it using nodeport or create route for the service. In `oc cluster up` it works because it directly run on your host. I don't think we can do anything more. Let us know if you have some idea around it or we can close it.

**Comment by lulf** [comment]
@praveenkumar Feel free to close this if you don't feel its a use case for minishift. My idea is something along the lines of my earlier comment: If minishift could set up port forwarding rules within the minishift VM, this would allow you to use the minishift vm IP and connect to services running on those ports. It would allow minishift to be used for this in the same way as you can with 'oc cluster up' 'natively' today.

**Comment by gbraad** [comment]
I believe this is unwanted, as this would prevent the user from having multiple instances of Minishift on the same host #126, as each would like to claim the port on the host.

Closing the issue.
