### ISSUE TITLE
Minishift reports 'virtual' as 'virutal'

### ISSUE THREAD

**Issue by utherp0** [minishift/minishift#516]
Just cosmetic - if Minishift fails on startup due to lack of --vm-driver it reports all errors with the word 'virutal' instead of 'virtual'

Example:

E0302 08:53:29.141736   15907 start.go:150] Error starting the VM: Error registering the VM: This virutal machine requires registration. Credentials must either be passed via the environment variables MINISHIFT_USERNAME and MINISHIFT_PASSWORD  or the --username and --password flags

**Comment by praveenkumar** [comment]
@utherp0 Thanks for report it just a typo, we are happy if you can send patch for it otherwise we will take care.

**Comment by LalatenduMohanty** [comment]
Here is the wrong spelling https://github.com/minishift/minishift/blob/master/pkg/minishift/registration/utils.go#L48

**Comment by hferentschik** [comment]
Merged via pull request #517
