### ISSUE TITLE
Can not redirect kibana view from web console

### ISSUE THREAD

**Issue by hagishun** [minishift/minishift#518]
Hi,I'm new member, so apologies if providing too much detail or not enough.

According to the method written on this page, I deploy log-deployer 
 * https://docs.openshift.org/latest/install_config/aggregate_logging.html *

Now deploy successed.
But I can't see Kibana web console view.

Step:
1.Log in Open shift web console.
2.select logging project.
3.I access this URL(https://kibana-ops.example.com)
4.I was redirected this url (https://kibana.example.com:8443/login?then=%2Foauth%2Fauthorize%3Fresponse_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fkibana.example.com%252Fauth%252Fopenshift%252Fcallback%26client_id%3Dkibana-proxy)
And then login screen displayed.
5.I enter system/admin then error displayed.
URL:https://kibana.example.com/auth/openshift/callback?error=access_denied&error_description=scope+denied%3A+user%3Afull
Screen:Unauthorized

What should I do?
Please tell me.

**Comment by hagishun** [comment]
If need more detail or informatin, please tell me.
I will add.

**Comment by jorgemoralespou** [comment]
Can you enable CORS, by doing:

minishift openshift config set --patch '{"corsAllowedOrigins": [".*"]}'

Not sure if it will require openshift instance to be restarted or if the
patch process restarts the origin container (I guess the later), but if it
don't work, just restart minishift.

**Comment by hferentschik** [comment]
> Not sure if it will require openshift instance to be restarted

The restart is implicit by the patch command.

**Comment by hferentschik** [comment]
See also https://github.com/minishift/minishift/blob/master/docs/interacting-with-openshift.md#updating-openshift-configuration

**Comment by hagishun** [comment]
Thanks. I tried it.
But not changed.

Step:
1. set config 
PS C:\Users\XXXXX> $command='{"corsAllowedOrigins" : [".*"]}'
PS C:\Users\XXXXX> echo $command
{"corsAllowedOrigins" : [".*"]}

2.reboot minishift
minishift stop
minishift start

3.Access web console 
URL:https://kibana.example.com/
display string : Unauthorized
And under the log display to kibana-proxy

172.17.0.1 - - [07/Mar/2017:03:39:53 +0000] "GET /auth/openshift/callback?error=access_denied&error_description=scope+denied%3A+user%3Afull HTTP/1.1" 401 - "https://192.168.99.100:8443/login?then=%2Foauth%2Fauthorize%3Fresponse_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fkibana.example.com%252Fauth%252Fopenshift%252Fcallback%26client_id%3Dkibana-proxy" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; Trident/7.0; rv:11.0) like Gecko"

**Comment by jorgemoralespou** [comment]
@hagishun You're missing an asterisk after the dot (.*) so that any domain is allowed as corsOrigin.

I'm not sure what is the syntax for windows, as I've seen some issues by setting the config on windows, but if you set the right corsAllowedOrigin it should work.

**Comment by hferentschik** [comment]
> I'm not sure what is the syntax for windows,

The syntax for Windows is tricky, since it depends on the type of shell (cmd vs powershell) and the versions thereof. For Windows 10 and Powershell, this works for me:

    $ .\minishift.exe --% openshift config set --patch "{\"corsAllowedOrigins\": [\".*\"]}"

The key is to understand that JSON needs to be passed in the end to the command. The valid JSON is in this case {"corsAllowedOrigins": [".*"]}. Depending on the OS and shell type, the tricky bit is then to know how to escape this so that it is going to work. See also issue #493

I think eventually we should offer a switch as well which allows you to provide the patch in a file. This way one does not have to worry about all this escaping business.

**Comment by hagishun** [comment]
Thank you for your response.

I tried below your suggestino and I seccessed changing minishift-conf.

---------------------------------------------------------------------------------------------------------------
PS C:\Users\XXXXX> .\minishift openshift config set --patch '{\"corsAllowedOrigins\": [\".*\"]}'
Patching OpenShift configuration /var/lib/origin/openshift.local.config/master/master-config.yaml with {"corsAllowedOrigins": [".*"]}
Restarting OpenShift
---------------------------------------------------------------------------------------------------------------

But kibana-view doesn't work.
---------------------------------------------------------------------------------------------------------------
172.17.0.1 - - [08/Mar/2017:11:36:49 +0000] "GET / HTTP/1.1" 302 0 "https://192.168.99.101:8443/console/project/logging/overview" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
https://kibana.example.com/auth/openshift/callback?error=access_denied&error_description=scope+denied%3A+user%3Afull
---------------------------------------------------------------------------------------------------------------
I think there are another reasons.

I'll continue to research.

**Comment by jorgemoralespou** [comment]
Kibana is not properly configured. Unless you have kibana installed in that domain kibana.example.com, and if you have it there you will need to add that url to the url_redirects of the oauthclient.

How did you install Kibana?

**Comment by hagishun** [comment]
Thanks.

I installed under the below
# Sorry to long...


c:\Users\XXXXXXXX>minishift start --vm-driver="virtualbox"
Starting local OpenShift cluster using 'virtualbox' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.1/minishift-b2d.iso'

   To login as administrator:
       oc login -u system:admin


c:\Users\XXXXXXXX>oc login -u system:admin
Logged into "https://192.168.99.101:8443" as "system:admin" using existing crede
ntials.

You have access to the following projects and can switch between them with 'oc p
roject <projectname>':

    default
    kube-system
  * myproject
    openshift
    openshift-infra

Using project "myproject".

c:\Users\XXXXXXXX>oc adm policy add-cluster-role-to-user cluster-admin system
cluster role "cluster-admin" added: "system"


c:\Users\XXXXXXXX>oc apply -n openshift -f https://raw.githubusercontent.com/openshift/origin-aggregated-logging/master/deployer/deployer.yaml
template "logging-deployer-account-template" configured
template "logging-deployer-template" configured

c:\Users\XXXXXXXX>oc adm new-project logging


c:\Users\XXXXXXXX>oc project logging
Now using project "logging" on server "https://192.168.99.101:8443".



c:\Users\XXXXXXXX>oc new-app logging-deployer-account-template
--> Deploying template "openshift/logging-deployer-account-template" to projectlogging

     logging-deployer-account-template
     ---------
     Template for creating the deployer account and roles needed for the aggregated logging deployer. Create as cluster-admin.


--> Creating resources ...
    serviceaccount "logging-deployer" created
    serviceaccount "aggregated-logging-kibana" created
    serviceaccount "aggregated-logging-elasticsearch" created
    serviceaccount "aggregated-logging-fluentd" created
    serviceaccount "aggregated-logging-curator" created
    clusterrole "oauth-editor" created
    clusterrole "daemonset-admin" created
    clusterrole "rolebinding-reader" created
    rolebinding "logging-deployer-edit-role" created
    rolebinding "logging-deployer-dsadmin-role" created
    rolebinding "logging-elasticsearch-view-role" created
--> Success
    Run 'oc status' to view your app.



c:\Users\XXXXXXXX>oc adm policy add-cluster-role-to-user oauth-editor system:serviceaccount:logging:logging-deployer
cluster role "oauth-editor" added: "system:serviceaccount:logging:logging-deployer"



oc adm policy add-scc-to-user privileged system:serviceaccount:logging:aggregated-logging-fluentd

c:\Users\XXXXXXXX>oc adm policy add-cluster-role-to-user cluster-reader system:serviceaccount:logging:aggregated-logging-fluentd
cluster role "cluster-reader" added: "system:serviceaccount:logging:aggregated-logging-fluentd"



c:\Users\XXXXXXXX>oc adm policy add-cluster-role-to-user rolebinding-reader system:serviceaccount:logging:aggregated-logging-elasticsearch
cluster role "rolebinding-reader" added: "system:serviceaccount:logging:aggregated-logging-elasticsearch"





c:\Users\XXXXXXXX>oc create configmap logging-deployer --from-literal kibana-hostname=kibana.example.com --from-literal public-master-url=https://192.168.99.101:8443 --from-literal es-cluster-size=1 --from-literal es-instance-ram=8G
configmap "logging-deployer" created



c:\Users\XXXXXXXX>oc edit configmap logging-deployer
apiVersion: v1
data:
  es-cluster-size: "1"
  es-instance-ram: 8G
  kibana-hostname: kibana.example.com
  public-master-url: https://192.168.99.101:8443
kind: ConfigMap
metadata:
  creationTimestamp: 2017-03-09T13:33:29Z
  name: logging-deployer
  namespace: logging
  resourceVersion: "904"
  selfLink: /api/v1/namespaces/logging/configmaps/logging-deployer
  uid: fb209dd6-04cc-11e7-9b57-6278d4a0917e




c:\Users\XXXXXXXX>oc new-app logging-deployer-template
--> Deploying template "openshift/logging-deployer-template" to project logging

     logging-deployer-template
     ---------
     Template for running the aggregated logging deployer in a pod. Requires emp
owered 'logging-deployer' service account.


     * With parameters:
        * MODE=install
        * IMAGE_PREFIX=docker.io/openshift/origin-
        * IMAGE_VERSION=latest
        * IMAGE_PULL_SECRET=
        * INSECURE_REGISTRY=false
        * ENABLE_OPS_CLUSTER=false
        * KIBANA_HOSTNAME=kibana.example.com
        * KIBANA_OPS_HOSTNAME=kibana-ops.example.com
        * PUBLIC_MASTER_URL=https://localhost:8443
        * MASTER_URL=https://kubernetes.default.svc.cluster.local
        * ES_CLUSTER_SIZE=1
        * ES_INSTANCE_RAM=8G
        * ES_PVC_SIZE=
        * ES_PVC_PREFIX=logging-es-
        * ES_PVC_DYNAMIC=
        * ES_NODE_QUORUM=
        * ES_RECOVER_AFTER_NODES=
        * ES_RECOVER_EXPECTED_NODES=
        * ES_RECOVER_AFTER_TIME=5m
        * ES_OPS_CLUSTER_SIZE=
        * ES_OPS_INSTANCE_RAM=8G
        * ES_OPS_PVC_SIZE=
        * ES_OPS_PVC_PREFIX=logging-es-ops-
        * ES_OPS_PVC_DYNAMIC=
        * ES_OPS_NODE_QUORUM=
        * ES_OPS_RECOVER_AFTER_NODES=
        * ES_OPS_RECOVER_EXPECTED_NODES=
        * ES_OPS_RECOVER_AFTER_TIME=5m
        * FLUENTD_NODESELECTOR=logging-infra-fluentd=true
        * ES_NODESELECTOR=
        * ES_OPS_NODESELECTOR=
        * KIBANA_NODESELECTOR=
        * KIBANA_OPS_NODESELECTOR=
        * CURATOR_NODESELECTOR=
        * CURATOR_OPS_NODESELECTOR=

--> Creating resources ...
    pod "logging-deployer-g0b6a" created
--> Success
    Run 'oc status' to view your app.

PS C:\Users\XXXXXXXX> .\minishift openshift config set --patch '{\"corsAllowedOrigins\": [\".*\"]}'
Patching OpenShift configuration /var/lib/origin/openshift.local.config/master/master-config.yaml with {"corsAllowedOrigins": [".*"]}
Restarting OpenShift

**Comment by hagishun** [comment]
And I tied to create oauthclient.

(in test.txt)
kind: OAuthClient
apiVersion: v1
metadata:
 name: kibana-proxy
secret: "..." 
redirectURIs:
 - "https://kibana.example.com" 
grantMethod: prompt 

after I do.
oc create -f test.txt

And then
c:\Users\XXXXXXXX>oc delete oauthclient/kibana-proxy
oauthclient "kibana-proxy" deleted

c:\Users\XXXXXXXX>oc new-app logging-support-template

but not changed...

**Comment by praveenkumar** [comment]
@hagishun latest version of minishift expose `logging` flag which can be used for kibana. Can you try that once and let us know if that works?

**Comment by agajdosi** [comment]
Hi @hagishun, is this issue still actual for you? As @praveenkumar mentioned, you can try `minishift start --logging` with latest Minishift release, it is currently experimental and can have some issues, but it could help you to save some time.

**Comment by agajdosi** [comment]
Hi @hagishun have you tried newer releases? Is the issue still present?

**Comment by hagishun** [comment]
Sorry.
I could solved this problem.

I used latest version of minishift and I could start minishift.

I did't know the root cause.
