### ISSUE TITLE
Include bashcompletion for Minishift

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#522]
At this point we have to type the complete command for minishift, but we should find out a way to have bash completion for the commands.
[1] http://freecode.com/projects/bashcompletion

**Comment by praveenkumar** [comment]
@LalatenduMohanty how it feasible for windows binary? I think right now what we have as part of viper is good enough which suggest command if you put some wrong one.

**Comment by LalatenduMohanty** [comment]
@praveenkumar May be not much for Windows CMD and Powershell. Not sure if it will be applicable to the new Windows bash shell. However it will be still useful to OS X and Linux users.

**Comment by jorgemoralespou** [comment]
And should be easy to implement, like "oc completion bash|zsh" provides
output that can be directly source as bash_completion. Also "oc-cluster"
does it.

**Comment by gbraad** [comment]
*Windows?*
This is not possible for Windows WSL, as the application would likely not be able to communicate with the hypervisor (it is a picoprocess). And for PowerShell? Hmmmm... haven't investigate this, as normally the cmdlets can be inspected/introspected by the runtime, but for a regular binary this is not possible.

**Comment by LalatenduMohanty** [comment]
Looks like cobra provides an fuction for generating bash completion. https://godoc.org/github.com/spf13/cobra#Command.GenBashCompletion. 

Minikube already using it.

**Comment by praveenkumar** [comment]
@LalatenduMohanty @hferentschik we need a milestone for it if we want to implement it.

**Comment by boeboe** [comment]
+1 

also looking forward for this functionality ;)

**Comment by gbraad** [comment]
See: https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/completion.go

**Comment by anjannath** [comment]
+1

This is a must needed feature, looking forward to having it soon.

**Comment by praveenkumar** [comment]
resolved by #1887
