### ISSUE TITLE
Separate out oc installation implementation from clusterUp function

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#524]
Currently, the [`clusterUp`](https://github.com/minishift/minishift/blob/master/cmd/minishift/cmd/start.go#L311) function is downloading and caching 'oc' binary (or oc installation) and then performing `oc cluster up` command which IMO are two separate and individual operations.

This is also making the testing a bit harder.

I am not doing it as part of the PR #487 since it need heady refactoring and test update which is out of scope of the PR.

**Comment by praveenkumar** [comment]
@budhrg shouldn't we close it to mark it as duplicate of #409 ?

**Comment by budhrg** [comment]
> @budhrg shouldn't we close it to mark it as duplicate of #409 ?

@praveenkumar , Ya we can. Will add the issue details in #409 .

**Comment by budhrg** [comment]
Commented https://github.com/minishift/minishift/issues/409#issuecomment-284764280
