### ISSUE TITLE
Slow communication when using Minishift+Hyper-V

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#529]
Issuing commands on Windows take a considerable amount of time. This happens for communicating with the libmachine API, but becomes especially noticeable when running command using SSH on the instance.

  * `minishift ip` only communicates with the API
  * `minshift hostip` communicates with the API and issue a command on the instance for a connectivity check

#### Windows

```powershell
PS C: > Measure-Command {
minishift.exe ip } | select TotalSeconds

TotalSeconds
------------
   1.9039228

PS C: > Measure-Command {
minishift.exe hostip } | select TotalSeconds
10.0.21.124

TotalSeconds
------------
    4.105378
```

#### Linux
The same commands take considerable less amount of time on Linux+KVM/Libvirt
```bash
$ time minishift ip
192.168.42.69
minishift ip  0.02s user 0.01s system 52% cpu 0.053 total
$ time minishift hostip
192.168.42.1
minishift hostip  0.02s user 0.01s system 20% cpu 0.145 total
```

#### Note
I have suspicions that this is related to invoking a new command to perform actions. On Windows an application start (non-fork) is really slow...

**Comment by hferentschik** [comment]
I can confirm that I also often have the feeling that things are more sluggish on Windows. We could start with a simple timing harness. Just boot up and some basic operations and then compare the timings across OS / driver / ...

**Comment by budhrg** [comment]
For me it is under 1 seconds. This is CDK 3 beta2 build.

```
PS C:\Users\budhram> Measure-Command { minishift.exe ip } | select TotalSeconds
TotalSeconds
------------
   0.1170691

PS C:\Users\budhram> Measure-Command { minishift.exe ip } | select TotalSeconds
TotalSeconds
------------
   0.0887991

PS C:\Users\budhram> Measure-Command { minishift.exe ip } | select TotalSeconds
TotalSeconds
------------
   0.0793204

PS C:\Users\budhram> Measure-Command { minishift.exe ip } | select TotalSeconds
TotalSeconds
------------
   0.0892224

PS C:\Users\budhram> Measure-Command { minishift.exe ip } | select TotalSeconds
TotalSeconds
------------
   0.1138931
```

**Comment by budhrg** [comment]
Interestingly, from `mingw` shell, it is relatively higher for same build:

```
budhram@DESKTOP-8MV1CPM /c
$ time minishift.exe ip
10.65.193.75
real    0m3.000s
user    0m0.015s
sys     0m0.031s

budhram@DESKTOP-8MV1CPM /c
$ time minishift.exe ip
10.65.193.75
real    0m2.790s
user    0m0.000s
sys     0m0.046s

budhram@DESKTOP-8MV1CPM /c
$ time minishift.exe ip
10.65.193.75
real    0m3.109s
user    0m0.000s
sys     0m0.047s
```

**Comment by praveenkumar** [comment]
@gbraad Can we again check this pattern since now we are going to use native ssh go implementation?

**Comment by LalatenduMohanty** [comment]
Re-opening this again as this is not fixed yet.

**Comment by hferentschik** [comment]
> Re-opening this again as this is not fixed yet.

I think we could have closed this (at least for now).
