### ISSUE TITLE
Split scenario in basic.feature into several smaller scenarios

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#532]
basic.feature currently uses one big scenario which covers whole process of using Minishift - it goes from starting minishift, checking ssh functionality, checking docker environmental variables, stopping to deleting minishift. Splitting it into smaller scenarios gives us the possibility to finish other scenarios when one of them fails, currently all steps are skipped when something fails. But more importantly we will be able to tag scenarios, so only part of basic.feature can be run e.g. tag `@fast` for quick developer tests, `@full` for automated or QE use.

Smaller scenarios are currently pre-indicated by blank lines between groups of scenario steps.

**Comment by hferentschik** [comment]
Merged via pull request #540
