### ISSUE TITLE
Create Jenkins job to build docs

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#535]

**Comment by budhrg** [comment]
Cool thinking of the same too :+1:

**Comment by hferentschik** [comment]
I this case I am after a dedicated build which gets triggered manually. On completion is should upload the html and potentially the doc files to the archive area. I'd like to make this the default way of handing over our docs to doc.openshift.org.

**Comment by budhrg** [comment]
@hferentschik 
> I this case I am after a dedicated build which gets triggered manually.

You, mean we can comment like "build the documentation" and then this job will trigger. 

> should upload the html 
where ?

 > I'd like to make this the default way of handing over our docs to doc.openshift.org.
That's future and final plan right?

**Comment by hferentschik** [comment]
> You, mean we can comment like "build the documentation" and then this job will trigger.

No, I would expect to go the Jenkins instance, login and trigger the build, potentially adding some parameters (for example branch name). Similar to what we do with the CDK or RHEL ISO builds.

> where ?

CentOS CI archive area. So I would expect a https://ci.centos.org/job/minishift-docs job with a matching artifacts.ci.centos.org/minishift/minishift/docs/[latest|\<version\>]

**Comment by budhrg** [comment]
> No, I would expect to go the Jenkins instance, login and trigger the build, 

As per last communication, we are not suppose to login to jenkins and most things should be done with JJB.

**Comment by hferentschik** [comment]
> As per last communication, we are not suppose to login to jenkins and most things should be done with JJB.

Not sure exactly how JJB works, is this not just a way to define the job? Regarding triggering, how would I trigger a manual job? I guess one could expose a web hook, but that seems overkill.

**Comment by budhrg** [comment]
> Regarding triggering, how would I trigger a manual job? I guess one could expose a web hook, but that seems overkill.

Will try to see how we can do this scenario in JJB.

**Comment by hferentschik** [comment]
Once pull request #565 is merged, the target to call is _gen_adoc_tar_. This creates a tar ball in the _docs/build_ directory. This tarball needs to be copied to the archive server.

**Comment by hferentschik** [comment]
What I would like to end up is, is the following:

    docs
    ├── 1.0.0-beta.5
    │   └── minishift-adoc.tar
    └── latest

The tarball gets uploaded into a directory which matches the Minishift version as per Makefile. _latest_ is a symbolic link to this version.

Assuming we create a job https://ci.centos.org/job/minishift-docs/, then I would expect this to land under http://artifacts.ci.centos.org/minishift/minishift/docs

**Comment by budhrg** [comment]
You mean http://artifacts.ci.centos.org/minishift/minishift/docs/1.0.0-beta.5/minishift-adoc.tar right?

I think it is doable with the current JJB configurations.

Created issue in respective repo - https://github.com/minishift/minishift-ci-jobs/issues/20

**Comment by hferentschik** [comment]
> You mean http://artifacts.ci.centos.org/minishift/minishift/docs/1.0.0-beta.5/minishift-adoc.tar right?

+1

> I think it is doable with the current JJB configurations.

+1

**Comment by hferentschik** [comment]
Merged via pull request #626
