### ISSUE TITLE
Add Minishift version into docs

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#536]
The docs should clearly indicate the version they cover. The version needs to be compiled into the site at build time.

**Comment by thatdocslady** [comment]
This can be handled with variables in the docs level, to show latest/previous versions. Asciidoc is good with this :)

**Comment by hferentschik** [comment]
> This can be handled with variables in the docs level, to show latest/previous versions. Asciidoc is good with this :)

Sure, it will be a variable in the asciidoc, but this variable has to come from somewhere? We don't want to have this hard coded in the asciidoc. It should be injected ultimately originating from the Make build. Are you sure, you want to do that?

**Comment by budhrg** [comment]
Merged via https://github.com/minishift/minishift/pull/565
