### ISSUE TITLE
Weird problem on Fedora 25

### ISSUE THREAD

**Issue by jfclere** [minishift/minishift#545]
I had minishift running some weeks ago and guess I probably broke some configuration in my box:
+++
   Image pull complete
-- Checking Docker daemon configuration ... FAIL
   Error: Error response from daemon: {"message":"page not found"}
E0314 09:30:02.575007   21003 start.go:364] Error starting the cluster:  exit status 1
++++
More on https://paste.fedoraproject.org/paste/WUKi1kQTVGwvvvTlbxjci15M1UNdIGYhyRLivL9gydE=
Note that I don't think that the warnings are the problem

OS: Fedora 25
Hypervisor: KVM

**Comment by LalatenduMohanty** [comment]
Copying the error from the pastebin as pastebin tend to get removed
```
[jfclere@jfcpc MINI]$ ./minishift start --show-libmachine-logs
Starting local OpenShift cluster using 'kvm' hypervisor...
Running pre-create checks...
Creating machine...
(minishift) Downloading /home/jfclere/.minishift/cache/boot2docker.iso from file:///home/jfclere/.minishift/cache/iso/minishift-b2d.iso...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Warning: got an invalid line error parsing /etc/os-release: Expected dummy_init: Refcount now 1 to split by '=' char into two strings, instead got 1 strings
Waiting for SSH to be available...
Detecting the provisioner...
Warning: got an invalid line error parsing /etc/os-release: Expected dummy_init: Refcount now 1 to split by '=' char into two strings, instead got 1 strings
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
Warning: got an invalid line error parsing /etc/os-release: Expected dummy_init: Refcount now 1 to split by '=' char into two strings, instead got 1 strings
Provisioning OpenShift via '/home/jfclere/.minishift/cache/oc/v1.4.1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/lib/minishift/openshift.local.volumes --routing-suffix 192.168.42.236.nip.io]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.4.1 image ... 
   Pulling image openshift/origin:v1.4.1
   Pulled 0/3 layers, 3% complete
   Pulled 1/3 layers, 47% complete
   Pulled 2/3 layers, 84% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... FAIL
   Error: Error response from daemon: {"message":"page not found"}
E0314 08:39:45.570065   16692 start.go:364] Error starting the cluster:  exit status 1
[jfclere@jfcpc MINI]$ 
```

**Comment by jfclere** [comment]
note that rm -rf ~/.minishift didn't help.

**Comment by LalatenduMohanty** [comment]
@jfclere have you tried to start with (CentOS ISO)[https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.3/minishift-centos7.iso]

I am not able to reproduce this on an updated Fedora 25 machine
```
$ uname -a
Linux LalatenduM-laptop 4.9.13-201.fc25.x86_64 #1 SMP Tue Mar 7 23:47:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ minishift start
Starting local OpenShift cluster using 'kvm' hypervisor...
Provisioning OpenShift via '/home/lmohanty/.minishift/cache/oc/v1.4.1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/lib/minishift/openshift.local.volumes --routing-suffix 192.168.42.31.nip.io]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.4.1 image ... 
   Pulling image openshift/origin:v1.4.1
   Pulled 0/3 layers, 2% complete
   Pulled 1/3 layers, 45% complete
   Pulled 1/3 layers, 70% complete
   Pulled 1/3 layers, 75% complete
   Pulled 1/3 layers, 78% complete
   Pulled 1/3 layers, 81% complete
   Pulled 2/3 layers, 84% complete
   Pulled 2/3 layers, 86% complete
   Pulled 2/3 layers, 92% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.42.31 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.31:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
```

**Comment by jfclere** [comment]
Same problem with CentOS ISO see https://paste.fedoraproject.org/paste/nSSfWLlHU~1OHrKo6quXgl5M1UNdIGYhyRLivL9gydE=

I am sure it something wrong in the box... Is there a way to have log/debug from oc cluster up?

**Comment by gbraad** [comment]
During the analysis with @jfclere I noticed that
```
-- Checking Docker daemon configuration ... FAIL
Error: Error response from daemon: {"message":"page not found"}
```
which happens in openShift at: https://github.com/openshift/origin/blob/8eafb3dc7a5ae983c8f9b1aeec4363045dfca186/pkg/bootstrap/docker/up.go#L320

This refers to the use of the insecure registries. If an API-call happens at this point, this might explain that a 404 might occur. Just the reasons of the actual 404 is unclear. It might suggest that the wrong node gets targeted. However, i have verified network settings with the reported.

**Comment by gbraad** [comment]
The strange thing for this issue is:
```
Warning: got an invalid line error parsing /etc/os-release: Expected dummy_init: Refcount now 1 to split by '=' char into two strings, instead got 1 strings
```
which is part of our provisioner_detector code? https://github.com/minishift/minishift/blob/master/pkg/minishift/provisioner/minishift_detector.go#L43

The user has a fully updated Fedora installation, and recently a new `openssh` package got pushed. Could there be something wrong with the communication between the host and cluster instance?

**Comment by jfclere** [comment]
OK so the problem comes from openshift when it tries to check that  -insecure-registry x.y.0.0/16.
Any way to trace/debug  openshift from minishift (--server-loglevel nn doesn't seem to work)?

**Comment by gbraad** [comment]
@jfclere I am trying something, but this is not easy... Trying to get some additional assistance for this...

**Comment by gbraad** [comment]
Do you still experience this problem?

**Comment by jfclere** [comment]
Yep I tried 1.0.0 same problem :-(

**Comment by praveenkumar** [comment]
@jfclere can you make sure there is not docker specific environment variable set? Also we are all mostly use f25 and didn't face this issue :(

**Comment by jfclere** [comment]
You are right I have also used docker with my laptop for other stuff, there is a chance that there is a bad interaction, I will try to clean an reinstall.

**Comment by praveenkumar** [comment]
@jfclere Does clean installation works for you?

**Comment by jfclere** [comment]
I haven't tried yet :-(

**Comment by gbraad** [comment]
Any update on this?

**Comment by jfclere** [comment]
I have updated to fedora 26 I will retest... I guess it is something related with the default network configuration in libvirt

**Comment by gbraad** [comment]
You can always restore the default configuration with:
```
$ sudo -i
$ virsh net-undefine default
$ virsh net-destroy default
$ virsh net-define /usr/share/libvirt/networks/default.xml
$ virsh net-start default
$ virsh net-autostart default
```

**Comment by jfclere** [comment]
I still have something wrong:
+++
[root@jfcpc TMP]# virsh net-define /usr/share/libvirt/networks/default.xml
error: Failed to define network from /usr/share/libvirt/networks/default.xml
error: internal error: bridge name 'virbr0' already in use.
+++

**Comment by gbraad** [comment]
This does indicate your network configuration has been changed. can you show the following?

```
$ brctl show
$ virsh net-list
```

**Comment by jfclere** [comment]
[root@jfcpc src]# brctl show
bridge name	bridge id		STP enabled	interfaces
virbr0		8000.525400a01f9b	yes		virbr0-nic
[root@jfcpc src]# virsh net-list
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 docker-machines      active     yes           yes

**Comment by gbraad** [comment]
the setup looks as follows on my end:

```
$ sudo virsh net-list
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes
 docker-machines      active     yes           yes

$ brctl show
bridge name     bridge id               STP enabled     interfaces
br-00b74bd0a105         8000.0242345a488a       no
br0             8000.001b2112786a       no              enp2s0
docker0         8000.02429022de69       no              vethb3bbbf8
                                                        vethc17ac63
virbr0          8000.525400c4dfde       yes             virbr0-nic
                                                        vnet2
                                                        vnet4
virbr1          8000.5254001149b6       yes             virbr1-nic
                                                        vnet3
                                                        vnet5
```

So most definitely a networking issue. After you have rebooted, can you try to define the `default` network again?

**Comment by jfclere** [comment]
Ok reboot + brctl delbr virbr0 + destroying and stopping helped.
