### ISSUE TITLE
Is there any URL we can query to find the OAuth URL inside minishift?

### ISSUE THREAD

**Issue by jstrachan** [minishift/minishift#550]
OpenShift can support a URL to expose the OAuth URL by querying: `https://openshift.default.svc/.well-known/oauth-authorization-server`

When running on minishift 1.0.0.beta-5 we get:
```
Failed to load url https://openshift.default.svc/.well-known/oauth-authorization-server got: Get https://openshift.default.svc/.well-known/oauth-authorization-server: x509: failed to load system roots and no roots provided
```
Is there another URL we could try inside minishift to discover the OAuth authorisation URL (e.g. something like "https://192.168.64.82:8443/oauth/authorize") which we need for OAuthClients to authorize (e.g. custom consoles).

**Comment by jstrachan** [comment]
a workaround is to add ClusterRole / ClusterRoleBinding to your app to be able to list nodes to be able to get the IP address to then default an OAuth URL - but it'd be nice to avoid cluster roles for web consoles if we can avoid it

**Comment by hferentschik** [comment]
> OpenShift can support a URL to expose the OAuth

Do you have a pointer to some docs around this? I am wondering whether this is another use-case for an addon as being developed as part of issue #177

**Comment by jstrachan** [comment]
@hferentschik this is about all I could find: https://github.com/openshift/origin/issues/11486#issuecomment-255403817

I tested this on minishift 1.0.0.Beta5 which is 1.4.1 of openshift?

**Comment by hferentschik** [comment]
> I tested this on minishift 1.0.0.Beta5 which is 1.4.1 of openshift?

That's the default atm, yes. You can also do something like this to get a later version:

    $ minishift start --openshift-version v1.5.0-alpha.3

**Comment by hferentschik** [comment]
> When running on minishift 1.0.0.beta-5 we get:

So what exactly do you mean with that? Where or how to you try to access this url. This URL won't be accessible on your host. To start with the hostname would not resolve. Even within the VM this hostname does not resolve. 

As the issue you are referring to indicates, this allows you to discover the OAuth URL from within a pod. So when I do the following with a running NodeJS app (using Openshift 1.5.0-alpha.3), all seems to be as it should:

    $ oc exec -it nodejs-ex-1-9cw7f bash
    $ curl --insecure https://openshift.default.svc/.well-known/oauth-authorization-server
    {
      "issuer": "https://192.168.99.110:8443",
      "authorization_endpoint": "https://192.168.99.110:8443/oauth/authorize",
      "token_endpoint": "https://192.168.99.110:8443/oauth/token",
      "scopes_supported": [
        "user:full",
        "user:info",
        "user:check-access",
        "user:list-scoped-projects",
        "user:list-projects"
      ],
      "response_types_supported": [
        "code",
        "token"
      ],
      "grant_types_supported": [
        "authorization_code",
        "implicit"
      ],
      "code_challenge_methods_supported": [
        "plain",
        "S256"
      ]
    }

So what do you expect? You want this information returned from within the pod from a minishift specific command? 

In the case of Minishift would it not always be https://\<IP\>:8443/oauth/authorize? At least atm? 

I guess I am also not sure whether you are looking for a general solution here which will work with any OpenShift instance (independent of Minishift) or whether you basically are making a Minishift feature request here?

**Comment by jstrachan** [comment]
On 16 March 2017 at 11:24, Hardy Ferentschik <notifications@github.com>
wrote:

> When running on minishift 1.0.0.beta-5 we get:
>
> So what exactly do you mean with that? Where or how to you try to access
> this url.
>

from inside a pod deployed on minishift



> This URL won't be accessible on your host. To start with the hostname
> would not resolve. Even within the VM this hostname does not resolve.
>
> As the issue you are referring to indicates, this allows you to discover
> the OAuth URL from within a pod. So when I do the following with a running
> NodeJS app (using Openshift 1.5.0-alpha.3), all seems to be as it should:
>
> $ oc exec -it nodejs-ex-1-9cw7f bash
> $ curl --insecure https://openshift.default.svc/.well-known/oauth-authorization-server
> {
>   "issuer": "https://192.168.99.110:8443",
>   "authorization_endpoint": "https://192.168.99.110:8443/oauth/authorize",
>   "token_endpoint": "https://192.168.99.110:8443/oauth/token",
>   "scopes_supported": [
>     "user:full",
>     "user:info",
>     "user:check-access",
>     "user:list-scoped-projects",
>     "user:list-projects"
>   ],
>   "response_types_supported": [
>     "code",
>     "token"
>   ],
>   "grant_types_supported": [
>     "authorization_code",
>     "implicit"
>   ],
>   "code_challenge_methods_supported": [
>     "plain",
>     "S256"
>   ]
> }
>
> So what do you expect?
>

seems the curl equivalent inside golang code barfs though. I wonder if its
the --insecure made it look like the URL wasn't here? Here's the code:
https://github.com/fabric8io/exposecontroller/blob/master/controller/controller.go#L300

**Comment by jstrachan** [comment]
lemme close this issue as it certainly looks like your nodejs container is working fine
