### ISSUE TITLE
Potentially missing docs about docker client prerequisite

### ISSUE THREAD

**Issue by thatdocslady** [minishift/minishift#551]
While trying to reuse the docker daemon (for make gen_docs) I ran into this error:

https://paste.fedoraproject.org/paste/Tr6MGw6aAET24o5iwltrOl5M1UNdIGYhyRLivL9gydE=

It turns out that the docker client is needed in order to reuse the docker daemon from minishift. But our docs right now don't specify this prerequisite:

https://github.com/minishift/minishift#reusing-the-docker-daemon

@gbraad pointed out that this prerequisite might be an assumption that we make (as in we assume that people will already have it), but I think it's better to have it there than to risk people getting stuck (especially since this is required for *any* docker daemon reuse, and not just for doc builds).

**Comment by hferentschik** [comment]
>  pointed out that this prerequisite might be an assumption that we make

IMO, it is very unlikely that anyone working in this space would not have the docker client. Also, for anyone working with containers it is clear that if there is a daemon and a client. So yes, there are assumptions here, but personally I don't think we need to be more explicit here. Where do you stop?

**Comment by LalatenduMohanty** [comment]
@hferentschik @thatdocslady I think we should add this to documentation as we expect the user to get the docker client and minishift does not take care of downloading and putting the docker client in to the path.

**Comment by thatdocslady** [comment]
Exactly, we specifically say that our developers can reuse the docker daemon so it makes it seem like they don't have to do anything, but similar to the hypervisor requirements and extra steps, for first-time users or people who want to try minishift this step is important and shouldn't be assumed.

**Comment by hferentschik** [comment]
Two things : "say that our developers can reuse the docker daemon":

* "our developers" - exactly, imo we are targeting developers. Minishift is not a consumer tool, it is for developers. I think one can expect a minimal understanding of containers, Docker, etc from developers starting to think about container orchestration  
* "reuse the docker daemon" - I think for anyone working with containers it is clear what this means. Docker being a client server architecture, if one can re-use the daemon, that does not make the client go away

>  first-time users or people who want to try minishift this step is important

not at all. For them it is most likely irrelevant. This has really no tie to what Minishift otherwise offers.

**Comment by thatdocslady** [comment]
Well if you feel so strongly about this then I won't fight about it, but let's see if we get any ricochets from not stating this once we start having users who need to use this.

**Comment by gbraad** [comment]
> Where do you stop?

You try to be inclusive as possible, as new developers are likely to pop up. We had them on chat yesterday... so, the basic tools you need (and how to install) can be described... we do the same for libvirt+kvm. We are not explaining how to install Linux here...

**Comment by gbraad** [comment]
It is not only the re-use case we deal with...

"I run Minishift, but my Docker does not show the container running"
It is because they issue the command on their local instance...

**Comment by gbraad** [comment]
Actually, we should not forget, that the usecase of 'Re-using the Docker daemon' is quite relevant for a Windows (and macOS) developers. This way, we provide an alternative to having Docker for Windows installed. Therefore installing the Docker client is almost a necessity... and is as simple as:

```
$ choco install docker
```

**Comment by gbraad** [comment]
>  if you feel so strongly about this then I won't fight about it

Please add the instructions, because so far 3 people believe this is valuable. I'd rather have added too much information than too little...

**Comment by gbraad** [comment]
>  if you feel so strongly about this then I won't fight about it

Please add the instructions, because so far 3 people believe this is valuable. I'd rather have added too much information than too little...

**Comment by LalatenduMohanty** [comment]
I strongly feel we should add the documentation. I will send the PR if required.

**Comment by thatdocslady** [comment]
@LalatenduMohanty I'll take care of it today, now that I finished the asciidoc editing

**Comment by hferentschik** [comment]
Merged via pull request #595
