### ISSUE TITLE
Example documentation

### ISSUE THREAD

**Issue by pollosp** [minishift/minishift#553]
Hi,
The section `Deploying a sample application` in the main Readme.md can be confusing at least I miss an hour trying to connect to `curl http://myproject.192.168.99.128.nip.io` because I didn't know anything about the `router` (minishift start --deploy-registry --deploy-router), it is not clearly explained in the example.
Also `https://github.com/openshift/nodejs-ex` requieres a nodejs template and minishift starts the service without templates.

```
$ oc new-app https://github.com/openshift/nodejs-ex -l name=myapp
error: no match for "nodejs"

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.
```

Thanks guys :)

**Comment by hferentschik** [comment]
>  because I didn't know anything about the router (minishift start --deploy-registry --deploy-router), it is not clearly explained in the example.

This is happening per default, you should not have to specify anything explicitly. Are you sure the start completed successfully. Here is how a successful start should look like:

    minishift start --openshift-version v1.5.0-alpha.3
    Starting local OpenShift cluster using 'virtualbox' hypervisor...
    Provisioning OpenShift via '/Users/hardy/.minishift/cache/oc/v1.5.0-alpha.3/oc [cluster up --use-existing-config     --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/    lib/minishift/openshift.local.volumes --routing-suffix 192.168.99.108.nip.io]'
    ....
    -- Installing registry ... OK
    -- Installing router ... OK
    -- Importing image streams ... OK
    -- Importing templates ... OK
    ....
    
       You are logged in as:
           User:     developer
           Password: developer
    
       To login as administrator:
           oc login -u system:admin 

As you can see in the output - router, registry and default image streams should get creates/imported. If the startup completes successfully, the following will also work:

      $ oc new-app https://github.com/openshift/nodejs-ex -l name=myapp
      --> Found image e8f9f96 (3 weeks old) in image stream "nodejs" in project "openshift" under tag "4

Can you please confirm that your startup works? Run _minishift delete_ and start over. If you still experience problems, please post the exact commands you are running and their output.

**Comment by hferentschik** [comment]
> I didn't know anything about --openshift-version v1.5.0-alpha.3 in your in the readme.md it is not specified as mandatory :(

It is not required, I somehow thought you did want to use a 1.5.x version as well. That was just my bad. Regarding router, registry, and templates the same applies for the default (OpenShift 1.4.1) as for 1.5.

That said, you seem to be trying to upgrade from an existing 0.9 version. The auto-update feature is currently broken. Could you try to delete the _minishift_ binary and download the latest release manually. Also for good measure, delete the content of ~/.minishift.

**Comment by LalatenduMohanty** [comment]
@pollosp good to know that your issue is resolved. We have a note in about it too i.e. `Automatic update of the Minishift binary and the virtual machine ISO is currently disabled. See also issue #204` [1]. 

Should we close the issue now?

[1] https://github.com/minishift/minishift#installing-minishift
