### ISSUE TITLE
Missing instructions in "Deploying a sample application" 

### ISSUE THREAD

**Issue by thatdocslady** [minishift/minishift#554]
Per @gbraad feedcack on IRC, the current steps are missing the following instructions:

Step 1: Need to add  --allow-missing-imagestream-tags
Step 4: Need to change to `curl http://nodejs-ex-myproject.<cluster_ip>.nip.io` and add a previous step where you retrieve the IP address with `minishift ip` 

I can handle this as a part of the README refactoring or separately. Thoughts?

**Comment by gbraad** [comment]
* Step 4 is certainly correct. Just re-ran the and this works.
* Step 1 I am not sure. I had to do this, but I just noticed my `oc version` is 1.5.0.

**Comment by thatdocslady** [comment]
@gbraad is there anyone who can confirm step 1? Do we need some testing on this against different oc versions?

**Comment by gbraad** [comment]
We should probably mention that this is for `minishift start` with OpenShift 1.4.1 maybe? WDYT

**Comment by thatdocslady** [comment]
If the step/limitation is "temporary" (meaning not a general thing but related to a specific version) then the best practice is either to list is as a note (i.e. "if you use xyz version x or later/earlier, then do this").

**Comment by gbraad** [comment]
@thatdocslady I ran it again with `oc` v1.4.1 and step 1 is OK as-is. No need to add the `--allow...`, but this is needed for future versions. We will add this when we are ready for this I guess...

**Comment by gbraad** [comment]
@lalatenduM, how did you perform the tests for release?

**Comment by LalatenduMohanty** [comment]
@gbraad good catch. I sometimes use OC , sometime console to deploy a new app. The nodejs example example is present in Readme from beginning of the project I think and I did not test it for release. I usually deploy the cakephp one to test. I can test this and confirm cc @thatdocslady

**Comment by gbraad** [comment]
I believe the following statement in the README is also wrong:

```
$ export PATH=$PATH:~/.minishift/cache/oc/v1.4.1
```

this adds the cache to `$PATH`, to allow people to run `oc`, BUT... the search order is wrong. This will resolve a possible executable/binary that is places in `/usr/bin`, `/usr/sbin`, `/usr/local/bin`, etc. first. Therefore they might not be using the cached version, but their own version which might be a different version.

**Comment by hferentschik** [comment]
> Step 4 is certainly correct. Just re-ran and this works.

Once issue #342 is resolved, this _curl_ command should be replaced. In fact this should happen as part of the #342 work. The line will become

    $ minishift openshift service myapp

> Step 1 I am not sure. I had to do this, but I just noticed my oc version is 1.5.0.

regarding _ --allow-missing-imagestream-tags_, I don't see why this should be required. Not for the NodeJS demo app. Why do you want to add this.

**Comment by gbraad** [comment]
> regarding --allow-missing-imagestream-tags, I don't see why this should be required. Not for the NodeJS demo app. Why do you want to add this.

Read the whole discussion... this is something that happened due to using `oc version` v1.5.0. In newer versions forward, this is likely needed. But yes, it was wrong for these changes.

> `minishift openshift service myapp`

Nice to have, but this would still hide intent at the moment. too many nifty commands do not really explain what is happening.

**Comment by hferentschik** [comment]
Regarding the path, you are probably right, you want to add the oc binary to the beginning of the PATH. That said, I am hoping to get rid of this asap via `minishift oc env`. Latest for next sprint.

**Comment by gbraad** [comment]
> `minishift oc env`

or `minishift oc-env` ? it is off-topic, but inconsistent with `minishift docker-env`

**Comment by budhrg** [comment]
> minishift openshift service myapp

This command actually, open the application URL in the default browser. If one need to extract url then he need to specify `--url` flag.

Now, the flow would be 
1. deploy application : `oc new-app https://github.com/openshift/nodejs-ex -l name=myapp`
1. check logs: `oc logs -f bc/nodejs-ex` (I don't get any imagestream issue if I run this command after few seconds like 10 or 20 seconds)
1. expose the route: `oc expose svc/nodejs-ex`
1.  open the application: `minishift openshift service nodejs-ex -n myproject` 

Note: I need to give 'myproject' namespace on step 4 as `default` is the default namespace being set (this can be change), and instead of appname `myapp` as set in step 1 that, I need to specify service name `nodejs-ex`.
 
@thatdocslady @hferentschik  any comment here?

**Comment by gbraad** [comment]
> open the application: `minishift openshift service nodejs-ex -n myproject`

Is this currently available or integrated? if not, we can not add this to the README. If else, we can use `xdg-url http://nodejs-ex-myproject.$(minishift ip).nip.io` to trigger the browser to open...

**Comment by hferentschik** [comment]
> Read the whole discussion... this is something that happened due to using oc version v1.5.0. In newer versions forward, this is likely needed

I got this part. In fact I just started a Minishift instance with 1.5.0-alpha.3 and it worked as expected. If this fall were required, I'd see that as a regression in cluster up and we should take it up there. Hence my question, if you guys are saying this flag is needed, I was wondering where this is coming from, e.g. a change in cluster up?

>> minishift openshift service myapp
> Nice to have, but this would still hide intent at the moment. too many nifty commands do not really explain what is happening.

Why does it hide the intend? It will open the app in your default browser. That's even better right? It also avoids the issue with documenting the dynamic IP part. Also, I want to start using as much of the commands Minishift offers. So if I can access the app via a Minishift command, I prefer that over a curl command. Also it is more portable. The minishift command will work on Windows as well, curl not so much.

**Comment by gbraad** [comment]
> > xdg-url

> Available for windows?

curl also not... ;-). but on Windows `start http://` would work.

**Comment by gbraad** [comment]
> a change in cluster up?

No idea... maybe we should ask @jorgemoralespou . It could be this example is not up-to-date.

**Comment by budhrg** [comment]
> Also, I want to start using as much of the commands Minishift offers. 

:+1: , that the intend here I guess. We should provide more functionalities through minishift CLI then using other ways like curl etc.

**Comment by hferentschik** [comment]
> Note: I need to give 'myproject' namespace on step 4 as default is the default namespace being set (this can be change),

It depends. If the default namespace is hard coded, then yes. If not and we are just calling out to the oc binary, it should use the current namespace automatically. If not,
yes you are right and the namespace needs to be specified. If this is the case we should dynamically determine the current namespace and apply it (in a follow up issue). 

> and instead of appname myapp as set in step 1 that, I need to specify service name nodejs-ex.

Right, right, my wrong. My main point is that we should use the _service_ command.

**Comment by gbraad** [comment]
> Why does it hide the intend? 

I try to step in the shoes of a developer and having to learn a new tool... If we use the new command, you also need to explain them at the same time. I am just scared of an information overload or resulting in information hiding, so the developer does not actually know what is happening...

**Comment by hferentschik** [comment]
@gbraad 
> Is this currently available or integrated? i

Sure, this is how `minishift console` works as well. This is cross platform.

**Comment by gbraad** [comment]
> Is this currently available or integrated? i

I mean, is the service command done and merged now? if so, sure go ahead... but I believe the task is still open as #342

**Comment by hferentschik** [comment]
@gbraad
> or minishift oc-env ? it is off-topic, but inconsistent with minishift docker-env

Yes and no, read the original issue #142. It started with _oc_env_ and it might end up being just that. However, I think there might be more useful _oc_ commands we can offer and in this case it would make sense to have `oc env` where env is a subcommand. This allows to add other subcommands. Also it aligns with `minishift openshift` as well. But the exact name of the command can be discussed when we implement it.

**Comment by budhrg** [comment]
namespace is hardcode here - https://github.com/minishift/minishift/blob/master/cmd/minishift/cmd/openshift/service.go#L88 to `default`. 

I think we can change it to `myproject`. WDYT ?

> If not, yes you are right and the namespace needs to be specified. If this is the case we should dynamically determine the current namespace and apply it (in a follow up issue)

Yes, better to track in separate issue.

**Comment by hferentschik** [comment]
> namespace is hardcode here - https://github.com/minishift/minishift/blob/master/cmd/minishift/cmd/openshift/service.go#L88 to default.

hmm, bugger. I wonder what happens if you don't specify it, aka leave it empty

> I think we can change it to myproject. WDYT ?

-1, that's in turn not a good idea.

BTW, we should have this discussion on #342

**Comment by budhrg** [comment]
The documentation for accessing app has been added via `minishift openshift service nodejs-ex` in deploying app section.

Unsure about `--allow-missing-imagestream-tags`. It is reproducible sometime.

Probably, this can be added in troubleshooting guide instead of README ?

WDYT ? @thatdocslady @hferentschik

**Comment by thatdocslady** [comment]
@budhrg if the --allow-missing-imagestream-tags step is required only when deplying a sample app (and not applicable to other use-cases) then it should be documented in the actual sample app section. If it's only reproducible sometimes, we should probably make it as a note, and explain when is it required (sometimes = certain conditions are met?).

**Comment by hferentschik** [comment]
I think we can close this issue. There is no issue to take for us on this. '--allow-missing-imagestream-tags' is not needed and I don't think it is really needed. Also as @budhrg is saying the _curl_ command got replaced by _minishift openshift serivce_.

**Comment by thatdocslady** [comment]
@hferentschik ok should I close it?

**Comment by hferentschik** [comment]
> ok should I close it?

Yes, please do.

**Comment by thatdocslady** [comment]
Ok closing per discussion.
