### ISSUE TITLE
Error adding developer user to sudoers

### ISSUE THREAD

**Issue by starksm64** [minishift/minishift#555]
I'm trying the Minishift version: 1.0.0-beta.5 release for OS X(10.11.6 (15G1217)) and I'm seeing an error about not being able to add developer user to sudoers:

[Keycloak 556]$ minishift start --memory=4000 --vm-driver=vmwarefusion --iso-url=https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.2/minishift-centos7.iso --docker-env=[storage-driver=devicemapper]
Starting local OpenShift cluster using 'vmwarefusion' hypervisor...
Provisioning OpenShift via '/Users/starksm/.minishift/cache/oc/v1.4.1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/lib/minishift/openshift.local.volumes --routing-suffix 172.16.156.152.nip.io]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... 
   Deleted existing OpenShift container
-- Checking for openshift/origin:v1.4.1 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 172.16.156.152 as the server IP
-- Starting OpenShift container ... 
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Removing temporary directory ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://172.16.156.152:8443

   To login as administrator:
       oc login -u system:admin

E0315 10:05:20.928446   44926 start.go:192] Error adding developer user to sudoers exit status 1
[Keycloak 557]$

**Comment by cmoulliard** [comment]
@starksm64 You are using the old centos image and not rc3.

**Comment by gbraad** [comment]
This is not dependent on the actual image. I have seen this fail on my end too, but during development.
@starksm64, please do a clean install and see if it persists (`rm -rf ~/.minishift`).

**Comment by gbraad** [comment]
@praveenkumar is something else needed?

**Comment by starksm64** [comment]
If I throw away ~/.minishift and retry the command it appears to be hanging:
[~ 516]$ minishift start --memory=4000 --vm-driver=vmwarefusion --iso-url=https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.3/minishift-centos7.iso --docker-env=[storage-driver=devicemapper]
Starting local OpenShift cluster using 'vmwarefusion' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.3/minishift-centos7.iso'
 335.00 MB / 335.00 MB [============================================] 100.00% 0s



[~ 735]$ tail -f ~/.minishift//machines/minishift/vmware.log 
2017-03-15T11:34:48.846-08:00| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2017-03-15T11:37:23.143-08:00| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2017-03-15T11:37:23.143-08:00| vmx| I125: Vix: [1295 guestCommands.c:1937]: Error VIX_E_TOOLS_NOT_RUNNING in VMAutomationTranslateGuestRpcError(): VMware Tools are not running in the guest
2017-03-15T11:39:23.140-08:00| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2017-03-15T11:39:23.140-08:00| vmx| I125: Vix: [1295 guestCommands.c:1937]: Error VIX_E_TOOLS_NOT_RUNNING in VMAutomationTranslateGuestRpcError(): VMware Tools are not running in the guest
2017-03-15T11:39:23.140-08:00| vmx| I125: Vix: [1295 guestCommands.c:481]: Error VIX_E_TIMEOUT_WAITING_FOR_TOOLS in VMAutomationOnWaitForToolsReturns(): A timeout error occurred while waiting for VMware Tools to start in the guest OS
2017-03-15T11:39:23.337-08:00| vmx| I125: SOCKET 3 (180) recv detected client closed connection
2017-03-15T11:39:23.337-08:00| vmx| I125: Vix: [1295 mainDispatch.c:2826]: VMAutomation: Connection Error (4) on connection 1.
2017-03-15T11:42:23.501-08:00| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2017-03-15T11:42:23.501-08:00| vmx| I125: Vix: [1295 guestCommands.c:1937]: Error VIX_E_TOOLS_NOT_RUNNING in VMAutomationTranslateGuestRpcError(): VMware Tools are not running in the guest

If I start over again and just use the default image it is working and I don't see the error:
[~ 518]$ minishift start --memory=4000 --vm-driver=vmwarefusion
Starting local OpenShift cluster using 'vmwarefusion' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
 40.00 MB / 40.00 MB [==============================================] 100.00% 0s
 21.34 MB / 21.34 MB [==============================================] 100.00% 0s
Provisioning OpenShift via '/Users/starksm/.minishift/cache/oc/v1.4.1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/lib/minishift/openshift.local.volumes --routing-suffix 172.16.156.152.nip.io]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.4.1 image ... 
   Pulling image openshift/origin:v1.4.1
   Pulled 0/3 layers, 4% complete
   Pulled 1/3 layers, 40% complete
   Pulled 2/3 layers, 97% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 172.16.156.152 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://172.16.156.152:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

[~ 519]$ 

I'll raise another issue for the minishift-centos7.iso problem.

**Comment by ALRubinger** [comment]
I've removed `~/.minishift` as well and this appeared to clear the issue temporarily, but it pops up again on subsequent reboots of Beta5.  My original clone of this in #556

**Comment by gbraad** [comment]
@ALRubinger are you seeing #561 maybe?

**Comment by praveenkumar** [comment]
@gbraad I am not sure if we need to add something but will try to reproduce it and let you folks know.
