### ISSUE TITLE
Starting with v1.0.0-rc.3 minishift-centos7.iso hangs with vmwarefusion driver

### ISSUE THREAD

**Issue by starksm64** [minishift/minishift#557]
I'm needing to use the v1.0.0-rc.3/minishift-centos7.iso image, and when I try this after removing my existing ~/.minishift directory, the start simply hangs:

```
[~ 528]$ minishift start --memory=4000 --vm-driver=vmwarefusion --iso-url=https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.3/minishift-centos7.iso --docker-env=[storage-driver=devicemapper]
Starting local OpenShift cluster using 'vmwarefusion' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.3/minishift-centos7.iso'
 335.00 MB / 335.00 MB [============================================] 100.00% 0s

The vmware.log seems to indicate a timeout. The full log is attached.

2017-03-15T12:12:33.322-08:00| vcpu-0| I125: CDROM: Emulate GET CONFIGURATION RT 0 starting feature 0
2017-03-15T12:12:33.433-08:00| vcpu-0| I125: DISKUTIL: scsi0:0 : capacity=40960000 logical sector size=512
2017-03-15T12:12:33.433-08:00| vcpu-0| I125: SCSI DEVICE (scsi0:0): MODE SENSE(6) for unsupported page 0x8
2017-03-15T12:12:33.438-08:00| vcpu-0| I125: DISKUTIL: scsi0:0 : capacity=40960000 logical sector size=512
2017-03-15T12:12:33.438-08:00| vcpu-0| I125: SCSI DEVICE (scsi0:0): MODE SENSE(6) for unsupported page 0x8
2017-03-15T12:12:33.439-08:00| vcpu-0| I125: DISKUTIL: scsi0:0 : capacity=40960000 logical sector size=512
2017-03-15T12:12:33.439-08:00| vcpu-0| I125: SCSI DEVICE (scsi0:0): MODE SENSE(6) for unsupported page 0x8
2017-03-15T12:12:35.165-08:00| vcpu-1| I125: VMXNET3 user: Ethernet0 Driver Info: version = 17041152 gosBits = 2 gosType = 1, gosVer = 0, gosMisc = 0
2017-03-15T12:12:39.880-08:00| vcpu-1| I125: CDROM: Emulate GET CONFIGURATION RT 0 starting feature 0
2017-03-15T12:13:06.170-08:00| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
```

[vmware.log.zip](https://github.com/minishift/minishift/files/845744/vmware.log.zip)

**Comment by hferentschik** [comment]
Just to make sure, you are saying "Starting with v1.0.0-rc.3 ...", so I assume you used the exact same command with earlier versions and it worked? It works for example with v1.0.0-rc.2.

Also, have you tried with a different driver? For example virtualbox or xhyve? We don't really test against vmwarefusion atm, so we have very little experience with it. 

Last, but not least I am not sure whether something like "[storage-driver=devicemapper]" would be working? Did this work for you before?

**Comment by starksm64** [comment]
No, I mean that trying to use a centos based iso when starting minishift is failing. I tried v1.0.0-rc.2 and it failed as well. I cannot try another driver on this particular host because both xhyve and virtualbox cause kernel panics that reboot the host. Using the default iso with the vmwarefusion driver does seem to work fine.

I have used the [storage-driver=devicemapper] option on a rhel system using the virtualbox driver and it does work. I'm simply using that option based on this issue and writeup on how to use minishift for the obssidian middleware quick starts:

https://issues.jboss.org/browse/OBST-19
https://github.com/obsidian-toaster/platform/blob/master/tooling/openshift/openshift-vm.adoc#1-using-minishift

**Comment by gbraad** [comment]
> 2017-03-15T12:13:06.170-08:00| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.

This is not related to our code, as this is the communication channel between VMWare and the Tools inside the virtual machine.

What actually hangs? `minishift` also hang for me due to #555 and #556. You need to use Ctrl+C to break out after openshift got deployed.

I need more information to be able to understand what is wrong as the log is not indicative enough. Can you start `minishift start --show-libmachine-logs` ?

**Comment by starksm64** [comment]
This is the output from the minishift command. It has been waiting for the VM to come online for 20 minutes.

[authz 757]$ minishift start --show-libmachine-logs --memory=4000 --vm-driver=vmwarefusion --iso-url=https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.3/minishift-centos7.iso --docker-env=[storage-driver=devicemapper]
Starting local OpenShift cluster using 'vmwarefusion' hypervisor...
Creating CA: /Users/starksm/.minishift/certs/ca.pem
Creating client certificate: /Users/starksm/.minishift/certs/cert.pem
Running pre-create checks...
Creating machine...
(minishift) Downloading /Users/starksm/.minishift/cache/boot2docker.iso from file:///Users/starksm/.minishift/cache/iso/minishift-centos7.iso...
(minishift) Creating SSH key...
(minishift) Creating VM...
(minishift) Creating disk '/Users/starksm/.minishift/machines/minishift/minishift.vmdk'
(minishift) Virtual disk creation successful.
(minishift) Starting minishift...
(minishift) Waiting for VM to come online...

**Comment by gbraad** [comment]
can you open the VMware interface and open the console of the virtual machine?

**Comment by starksm64** [comment]
Yes, but I don't know the login. It is not admin/admin.

**Comment by gbraad** [comment]
It is defined at: https://github.com/minishift/minishift-centos-iso/blob/master/centos-7.template#L1 => `root`:`centos`

It is probably an issue with networking?
Did `minishift status` return a different state... and what about `minishift ip` ?

**Comment by starksm64** [comment]
[Obsidian 771]$ minishift status
Running
[Obsidian 772]$ minishift ip
172.16.156.152
[Obsidian 773]$ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=3<RXCSUM,TXCSUM>
	inet6 ::1 prefixlen 128 
	inet 127.0.0.1 netmask 0xff000000 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=1<PERFORMNUD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=10b<RXCSUM,TXCSUM,VLAN_HWTAGGING,AV>
	ether 68:5b:35:94:35:80 
	inet6 fe80::6a5b:35ff:fe94:3580%en0 prefixlen 64 scopeid 0x4 
	inet 192.168.1.107 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=1<PERFORMNUD>
	media: autoselect (1000baseT <full-duplex,flow-control,energy-efficient-ethernet>)
	status: active
en1: flags=8823<UP,BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
	ether c8:e0:eb:3c:69:19 
	nd6 options=1<PERFORMNUD>
	media: autoselect (<unknown type>)
	status: inactive
p2p0: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 2304
	ether 0a:e0:eb:3c:69:19 
	media: autoselect
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 6a:5b:35:49:d3:00 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	nd6 options=1<PERFORMNUD>
	media: <unknown type>
	status: inactive
awdl0: flags=8903<UP,BROADCAST,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	ether 5a:08:c3:e3:6c:ca 
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: inactive
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1360
	inet 10.3.116.179 --> 10.3.116.179 netmask 0xfffffc00 
vmnet1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 00:50:56:c0:00:01 
	inet 192.168.19.1 netmask 0xffffff00 broadcast 192.168.19.255
vmnet2: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 00:50:56:c0:00:02 
	inet 10.1.2.1 netmask 0xffffff00 broadcast 10.1.2.255
vmnet3: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 00:50:56:c0:00:03 
	inet 172.28.128.1 netmask 0xffffff00 broadcast 172.28.128.255
vmnet8: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 00:50:56:c0:00:08 
	inet 172.16.156.1 netmask 0xffffff00 broadcast 172.16.156.255

Ok, what info do you want from the centos image?

**Comment by gbraad** [comment]
Are you able to ping 172.16.156.1 from the minishift instance?
And so, does `minishift ssh` actually work?

**Comment by starksm64** [comment]
[Obsidian 774]$ ping $(minishift ip)
PING 172.16.156.152 (172.16.156.152): 56 data bytes
64 bytes from 172.16.156.152: icmp_seq=0 ttl=64 time=0.470 ms
64 bytes from 172.16.156.152: icmp_seq=1 ttl=64 time=0.292 ms
64 bytes from 172.16.156.152: icmp_seq=2 ttl=64 time=0.324 ms
64 bytes from 172.16.156.152: icmp_seq=3 ttl=64 time=0.264 ms
^C
--- 172.16.156.152 ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.264/0.338/0.470/0.079 ms
[Obsidian 775]$ minishift ssh
E0315 23:59:15.643838    6398 ssh.go:38] Cannot establish SSH connection to the VM:  exit status 255
[Obsidian 776]$

**Comment by gbraad** [comment]
Inside the minishift instance, 

Can you try to:
  * `ping 172.16.156.1`    # please ping the opposite way... I know, just to make sure...
  * `ip a`
  * `sudo journalctl -u rc-local`
  * `mount`

**Comment by starksm64** [comment]
Note that I can ssh into the mini shift instance without using the mini shift ssh command:

[Obsidian 782]$ ssh root@172.16.156.152
root@172.16.156.152's password: 
Last login: Wed Mar 15 19:55:29 2017
[root@localhost ~]# ping 172.16.156.1
PING 172.16.156.1 (172.16.156.1) 56(84) bytes of data.
64 bytes from 172.16.156.1: icmp_seq=1 ttl=64 time=0.206 ms
64 bytes from 172.16.156.1: icmp_seq=2 ttl=64 time=0.263 ms
^C
--- 172.16.156.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.206/0.234/0.263/0.032 ms

[root@localhost ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:0c:29:28:f9:f0 brd ff:ff:ff:ff:ff:ff
    inet 172.16.156.152/24 brd 172.16.156.255 scope global dynamic eth0
       valid_lft 1162sec preferred_lft 1162sec
    inet6 fe80::20c:29ff:fe28:f9f0/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    link/ether 02:42:5d:89:eb:ab brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever

[root@localhost ~]# sudo journalctl -u rc-local
-- Logs begin at Wed 2017-03-15 19:30:15 EDT, end at Wed 2017-03-15 20:10:32 EDT
Mar 15 19:30:28 localhost.localdomain systemd[1]: Starting /etc/rc.d/rc.local Co
Mar 15 19:30:28 localhost.localdomain systemd[1]: Started /etc/rc.d/rc.local Com

[root@localhost ~]# mount
sysfs on /sys type sysfs (rw,relatime,seclabel)
proc on /proc type proc (rw,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,seclabel,size=1952556k,nr_inodes=488139,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,relatime,seclabel)
devpts on /dev/pts type devpts (rw,relatime,seclabel,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,seclabel,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_prio,net_cls)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/sr0 on /run/initramfs/live type iso9660 (ro,relatime)
/dev/mapper/live-rw on / type ext4 (rw,noatime,seclabel,data=ordered)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=24,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
mqueue on /dev/mqueue type mqueue (rw,relatime,seclabel)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,seclabel)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=394884k,mode=700)

**Comment by gbraad** [comment]
Inside the instance, please do

  * `cat /proc/partitions`

It seems the provisioning is not running...

**Comment by starksm64** [comment]
[root@localhost ~]# cat /proc/partitions
major minor  #blocks  name

  11        0     343040 sr0
   7        0         16 loop0
   7        1       4216 loop1
   7        2     265160 loop2
   7        3   10485760 loop3
   7        4     524288 loop4
 253        0   10485760 dm-0
 253        1   10485760 dm-1
 253        2   10485760 dm-2
   2        0          4 fd0
   8        0   20480000 sda
   7        5  104857600 loop5
   7        6    2097152 loop6
 253        3  104857600 dm-3

**Comment by gbraad** [comment]
Try inside the instance

  * `sudo fdisk /dev/sda`  [p]

**Comment by starksm64** [comment]
`[root@localhost ~]# sudo fdisk /dev/sda    
Welcome to fdisk (util-linux 2.23.2).

Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Device does not contain a recognized partition table
Building a new DOS disklabel with disk identifier 0xfaf8dd39.

Command (m for help): p

Disk /dev/sda: 21.0 GB, 20971520000 bytes, 40960000 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0xfaf8dd39

   Device Boot      Start         End      Blocks   Id  System
`

**Comment by gbraad** [comment]
The geometry of the disk is correct... but for some reason the provisioning did not run... ?

**Comment by gbraad** [comment]
Inside the instance

  * `dd if=$UNPARTITIONED_HD bs=1 count=29 2>/dev/null`

**Comment by starksm64** [comment]
```
[root@localhost ~]# dd if=$UNPARTITIONED_HD bs=1 count=29 2>/dev/null
[root@localhost ~]# echo $?
1
```

**Comment by gbraad** [comment]
very weird... can you do a `minishift stop && minishift delete` (and it fails, rm -rf ~/.minishift/machines), and start the instance again.

after some time, just open the console and do in the instance

  * `sudo journalctl -u rc-local`

**Comment by gbraad** [comment]
it might be helpful to drop by in #minishift on freenode. but also let's keep updating this issue...

**Comment by starksm64** [comment]
```
[Obsidian 783]$ minishift stop && minishift delete
Stopping local OpenShift cluster...
Error stopping cluster:  Error unregistring the VM: ssh command error:
command : sudo cat /etc/os-release
err     : exit status 255
output  : 
Deleting the Minishift VM...
Error deleting the VM:  Error unregistring the VM: ssh command error:
command : sudo cat /etc/os-release
err     : exit status 255
output  : 
[Obsidian 784]$ rm -rf ~/.minishift/machines/
[Obsidian 785]$ minishift start --show-libmachine-logs --memory=4000 --vm-driver=vmwarefusion --iso-url=https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.3/minishift-centos7.iso --docker-env=[storage-driver=devicemapper]
Starting local OpenShift cluster using 'vmwarefusion' hypervisor...
Running pre-create checks...
Creating machine...
(minishift) Downloading /Users/starksm/.minishift/cache/boot2docker.iso from file:///Users/starksm/.minishift/cache/iso/minishift-centos7.iso...
(minishift) Creating SSH key...
(minishift) Creating VM...
(minishift) Creating disk '/Users/starksm/.minishift/machines/minishift/minishift.vmdk'
(minishift) Virtual disk creation successful.
(minishift) Starting minishift...
(minishift) Waiting for VM to come online...
E0316 00:33:45.515144    6638 start.go:160] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting. Retrying.
Waiting for SSH to be available...
```

instance
```
[redhat-sso 654]$ ssh root@172.16.156.152
root@172.16.156.152's password: 
Last login: Wed Mar 15 20:07:32 2017 from 172.16.156.1
[root@localhost ~]# sudo journalctl -u rc-local
-- Logs begin at Wed 2017-03-15 19:30:15 EDT, end at Wed 2017-03-15 20:35:43 EDT
Mar 15 19:30:28 localhost.localdomain systemd[1]: Starting /etc/rc.d/rc.local Co
Mar 15 19:30:28 localhost.localdomain systemd[1]: Started /etc/rc.d/rc.local Com
lines 1-3/3 (END)
```

**Comment by starksm64** [comment]
Ok, I'll do that tomorrow. It's 12:30 am here and I'll be signing off soon.

**Comment by starksm64** [comment]
Here is a new message from the mini shift console:

```
E0316 00:36:55.601726    6638 start.go:160] Error starting the VM: Error configuring authorization on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
Waiting for SSH to be available..
```

**Comment by gbraad** [comment]
In short, the provisioning does not run, so the SSH keys also do not get set correctly... Not sure why yet.

**Comment by gbraad** [comment]
@starksm64 

I made a mistake in one of the commands. I left a variable unassigned...
```
$ dd if=/dev/sda bs=1 count=29 2>/dev/null
```

**Comment by gbraad** [comment]
If not mistaken, you mentioned this worked for an older release? Would it be possible to run the same setup, but with beta4 and centos rc3 as image? If that fails, centos rc2?

If it starts, send me the output of `sudo journalctl -u rc-local` from the Minishift instance.

Any information that can help in comparing would be appreciated.

**Comment by starksm64** [comment]
I had only tried beta5 and centos rc2, and that did not work, but I will take a look at beta4.

**Comment by praveenkumar** [comment]
@starksm64 we have 1.0.1 latest release can you try that out and let us know if you still face same issue?

**Comment by agajdosi** [comment]
Hello @starksm64, time flies, are you still around Minishift? If so, had newer releases resolved this issue or you are still facing it?

**Comment by gbraad** [comment]
I will close the issue.

As per comment: https://github.com/minishift/minishift/issues/557#issuecomment-286973672 and https://github.com/minishift/minishift/issues/557#issuecomment-286975396 it feels like this is SSH related. There were issues in the underying Docker machine codebase, which has since been fixed. This could have caused issues when using the centos image. 

> Note that I can ssh into the mini shift instance without using the mini shift ssh command:

Based on this, I can assume the issue has since been resolved. However, if not it is by now also better to file a new issue as too many things have changed for which new information is needed anyway.

**Comment by gbraad** [comment]
We are in the process of deprecating the VMware drivers.
Closing this issue...
