### ISSUE TITLE
Improve build time by using 'go install' over 'go build'

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#559]

**Comment by LalatenduMohanty** [comment]
@hferentschik Can you please give more context. I am not sure if I understand. Is this Windows specific?

**Comment by budhrg** [comment]
:+1:   `go install` does caching. Nice!

Found following answer in internet :
```
Go build just compile the executable file and move it to destination. 

Go install do a little more. It move the executable file to $GOPATH/bin and cache all non-main packages which imported to $GOPATH/pkg. The cache will be use in the next compile if it not changed yet. 
```

**Comment by hferentschik** [comment]
Compilation is a lot faster this way. Much faster turn around times when developing.

**Comment by budhrg** [comment]
Closed via https://github.com/minishift/minishift/pull/566
