### ISSUE TITLE
Add flag or make new target to avoid compiling binary while running integration test 

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#562]
Right now `make integration` compiles the binary and use it to verify integration test.

One might need to test the local binary or download from URL for integration tests.

This IMO can be achieved by two ways:
- create flag like URL=`some url` to use url, like `make integration URL=<url>`
- create flag like BINARY=`path to binary`, `make integration BINARY=<path to binary>`
- new target altogether

Any thoughts?

**Comment by agajdosi** [comment]
New target would save some typing only if there is predefined path for binary location e.g. in ~/minishift/minishift, in cases where one specifies her own path there would be flag still needed in this new target. So flag seems better to me.

**Comment by agajdosi** [comment]
I went for solution with flag, but this can be changed quite fast, if we need. To run on specific binary, one can use URL argument with make integration, e.g. `make integration URL=/home/agajdosi/minishift/minishift`. For this case target is blank so code will not compile extra (and it his case useless) binary if there is any in "/out" folder.
URL argument is in make passed further as --binary flag, which was present in code before. I can unify naming of both when we agree on some flag name.

**Comment by hferentschik** [comment]
Merged via pull request #576
