### ISSUE TITLE
During OpenShift provisioning 'oc login' takes a long time 

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#563]
On KVM+Libvirt, Fedora 25, using current master and centos-rc3. After OpenShift is deployed it takes about an additional 30+ seconds before the prompt returns to be active. In this time, sudoers for OpenShift is set.

This has also been observed on Hyper-V (but slow command issuing was known here).

**Comment by LalatenduMohanty** [comment]
@gbraad How did you reach to conclusion that its the suders command that takes time?

**Comment by gbraad** [comment]
@LalatenduMohanty adding print output
```
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.231:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

AddSudoersRoleForUser("developer") took: 48.402254308s
```

**Comment by jorgemoralespou** [comment]
@gbraad note that although the last thing that happens is the sudoers in oc 1.5 there is a job launched creating 100 PVs and that this might also impact in this face somehow for this provider. 

Adding @csrwng for validation.

**Comment by csrwng** [comment]
@jorgemoralespou all that happens on startup is that the job is created. The creation of pods by the job controller and completion of that is all done asynchronously and doesn't affect when cluster up actually finishes.

**Comment by gbraad** [comment]
@jorgemoralespou @csrwng How can I find out what causes `oc login` to behave slow as mentioned above? This is pretty consistent... :-s

**Comment by csrwng** [comment]
@gbraad you can add `--loglevel=10` to the `oc login` command to see where it's taking the time. If it's in a REST call, then it would need to be further debugged by increasing the loglevel on the server side (`--server-loglevel` flag on `cluster up`)

**Comment by praveenkumar** [comment]
@gbraad do we need more debug for this issue or can be closed?

**Comment by gbraad** [comment]
yes... this is a general problem, and still occurs

**Comment by jorgemoralespou** [comment]
I recall that as part of a bug fix @csrwng fixed some networking checks that was taking long time.

@gbraad could you add some output with --loglevel=10 to help @csrwng identify the source of the problem?

**Comment by csrwng** [comment]
My understanding is that this issue is with login rather than the pod network test. But I agree, it'd be good to run the login command with a higher loglevel to see where the problem is occurring. 

There is definitely something wrong with login when it takes > 20 sec (as mentioned above):
```
Running command: 'oc login -u system:admin' took: 23.207808285s
```

**Comment by gbraad** [comment]
Still an issue... currently this takes 2+ mins for me during startup

**Comment by gbraad** [comment]
This happens to .kube/config containing many entries: https://gist.github.com/gbraad/607e88772340eec49988a2dd1be4960b
