### ISSUE TITLE
rpm packages for fedora/centos

### ISSUE THREAD

**Issue by dustymabe** [minishift/minishift#569]
Would be great if we can get `docker-machine-driver-kvm` and `minishift` packages for Fedora and CentOS. I believe `docker-machine` is already packaged for Fedora, but not EPEL yet.

**Comment by gbraad** [comment]
@dustymabe what do we need to do to get `docker-machine` into EPEL?

```
$ dnf search docker-machine
Last metadata expiration check: 6 days, 2:14:50 ago on Thu Mar 16 11:33:17 2017.
Error: No matches found.
```
**?**

**Comment by hferentschik** [comment]
I am confused, why docker-machine? docker-machine bundles some drivers, but them we have built-in into the Minishift binary. The KVM and xhyve drivers are separate projects.

**Comment by gbraad** [comment]
@hferentschik I believe @dustymabe referred to these drivers, but none of this exists at all in the repos. The search should have returned everything matching the name... but nothing exists at the moment...

**Comment by dustymabe** [comment]
@gbraad 
> @dustymabe what do we need to do to get docker-machine into EPEL?

convince the maintainers to add a new branch and support it. It's usually easier to convince them if you volunteer to help out. Here are the current owners: https://admin.fedoraproject.org/pkgdb/package/rpms/docker-machine/

@hferentschik 
> I am confused, why docker-machine? docker-machine bundles some drivers, but them we have built-in into the Minishift binary.

@hferentschik mainly because the minishift docs say "if you want to use kvm go install docker-machine-driver-kvm" and the [install docs](https://github.com/dhiltgen/docker-machine-kvm/blame/master/README.md#L11) for docker-machine-driver-kvm say to install docker-machine first. Please let me know if docker-machine is not needed even with the docker-machine-driver-kvm (would need to update our docs probably).

**Comment by gbraad** [comment]
@dustymabe the driver is a separate project: https://github.com/dhiltgen/docker-machine-kvm

You do not need docker-machine to work with minishift, as this functionality is actually handled by the binary (embedded).

**Comment by dustymabe** [comment]
@gbraad please detail to me what all I need installed on my machine in order to use minishift with kvm.

**Comment by gbraad** [comment]
@dustymabe https://github.com/minishift/minishift/blob/master/docs/source/using/docker-machine-drivers.adoc

**Comment by dustymabe** [comment]
and that says `For further information refer to: https://github.com/dhiltgen/docker-machine-kvm#quick-start-instructions` where it clearly says you need to install docker-machine. I think if that is not a requirement then we should state that explicitly.

**Comment by dustymabe** [comment]
also, why would be "embed docker-machine functionality" but choose to not embed "docker-machine-driver-kvm" functionality? would it make the binary that much larger?

**Comment by gbraad** [comment]
docker machine is general, while the drivers are platform specific. but this could be a consideration. The same would apply to xhyve (but this is specific to the platform you run on, so impossible).

The documentation is wrong in the sense of install instructions. I believe 'refer' would mean here if you wanna know more details I guess. /cc: @thatdocslady

**Comment by hferentschik** [comment]
> also, why would be "embed docker-machine functionality" but choose to not embed "docker-machine-driver-kvm" functionality?

because docker-machine or better libmachine is a dependency we consume. Minikube and Minishift build upon it. As it happens to be it provides a set of drivers - https://github.com/docker/machine/tree/master/drivers. KVM and xhyve are not part of them and are maintained as separate projects. libmachine offers an API for driver implementation and that's what the KVM and xhyve driver use. Embedding the KVM or xhyve driver is not so easy as it sounds. There is an issue - #217 where this is discussed. There are ways of doing this, but it won't happen in the near future.

> would it make the binary that much larger?

It is not an issue of binary size. At least not primarily.

**Comment by gbraad** [comment]
@hferentschik to follow-up. this seems mostly related to the xyve driver, as I mentioned earlier. But how about the KVM driver? this drivers seems to rely on that fact that the libvirt(d) group is able to communicate with the actual backend. this would mean that bundling/embedding for this driver would be possible.

However, I'd rather consider an RPM package called `docker-machine-drivers-kvm` or `docker-machine-kvm` in that case. Which could be a dependency for a `minishift` package.

**Comment by dustymabe** [comment]
@gbraad yep. having it get pulled in as an rpm dependency makes sense. 

sorry I didn't mean to derail the discussion. I really didn't mean to suggest that we embed `docker-machine-drivers-kvm`, but once you said that we do basically pick up the docker-machine functionality, my logical next question was "why that and not this".

**Comment by thatdocslady** [comment]
@gbraad the documentation for this section is being updated as a part of #591 so there's already some improvement, but to be extra explicit I would recommend rephrasing to "For general information about Docker machine, see <xyz> link" and move that sentence to the end of the KVM driver install section, so it's not sending users somewhere else before they even started.

**Comment by marcindulak** [comment]
Currently trying to package the minishift binary https://github.com/minishift/minishift/issues/828

**Comment by praveenkumar** [comment]
So documents around driver section already in place and rpm packaging effort is part of #828 so I am going to close this issue.

**Comment by dustymabe** [comment]
so all the rpm tickets got closed. no interest in providing this as an rpm ?

**Comment by gbraad** [comment]
@dustymabe it would not provide any benefits, as the binary is statically compiled. The RPM would just be a wrapper to place it somewhere in path. It would even conflict with the provided functionality like `m update`. Unless we have a more compelling reason, we do not really see a benefit at this point.

**Comment by dustymabe** [comment]
mainly that on linux you then are up and running in two commands:
```
sudo dnf install -y minishift
minishift start
```

Also means that users automatically gets updates when they update their system

**Comment by gbraad** [comment]
> linux

Fedora.

If someone is willing to do so, go ahead. Just be warned that de-bundling the build process (by using shared libraries), will result in an unsupported binary.
