### ISSUE TITLE
Pods failed to load with this error "FailedSync Error syncing pod..."

### ISSUE THREAD

**Issue by johnreytanquinco** [minishift/minishift#575]
After creating a local OpenShift instance by installing and running minishift following this [chouseknecht/minishift-up-role](https://github.com/chouseknecht/minishift-up-role), and running the playbook, I encountered this error during deployments.

`FailedSync Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError...
`

Pods were created but failed to start.

This is the custom yaml code I used and pasted as the new project on the default application.
https://github.com/jubicoy/drupal8-docker/blob/master/drupal8-mysql-webdav.json

The code should create two pods, the Drupal web and db.
Please refer these images:

![web](https://lh3.googleusercontent.com/-lpn8Qy5_16M/WMwTLLfOtKI/AAAAAAAABzk/YpCRS3kOToMgVG4i1evvxcKTSWz7RI6AACL0B/h275/Screen%2BShot%2B2017-03-18%2Bat%2B12.47.07%2BAM.png)
![db](https://lh3.googleusercontent.com/-qhBjDGkPeI8/WMwSdLH91SI/AAAAAAAABzU/v_aTRFkgg6oMA0-ZYVMkHjx27leelaHmwCL0B/h277/Screen%2BShot%2B2017-03-18%2Bat%2B12.44.14%2BAM.png)

*gbraad: edited the issue; links, images, etc*: minishift-up-role was only used to deploy minishift, with an initial 5G PV.

**Comment by budhrg** [comment]
@johnreytanquinco , looks like some mishap here. Could you update the issue title and description properly?

**Comment by johnreytanquinco** [comment]
@budhrg I think we have have the same issue encountered, and have you found any solution to [this](https://github.com/minishift/minishift/issues/218)?

**Comment by budhrg** [comment]
@johnreytanquinco this seems to Openshift issue for us. Check commente here https://github.com/minishift/minishift/issues/218#issuecomment-269002416.

@johnreytanquinco , have you found any application failing due to it?

**Comment by johnreytanquinco** [comment]
One thing I thought it was a version issue, but I'm already running the latest Minishift version: 1.0.0-beta.5.

If the deployment is successful, it should generates the running Drupal 8 site and the database but unfortunately it not.

**Comment by budhrg** [comment]
@johnreytanquinco , would you like to join us in #minishift in irc.freenode.net? This seems to be different issue. Our application deployed successfully in spite of having those warning messages.

**Comment by johnreytanquinco** [comment]
Yes, sure. I'm on it thanks!

**Comment by gbraad** [comment]
Please provide exact steps on how to reproduce the issue. Deployment using ansible is not something we support directly, as this is still part of the https://github.com/chouseknecht/minishift-up-role project. However, we are more than willing to see if this is an issue on our end, or something that is missing in the ansible-role.

**Comment by johnreytanquinco** [comment]
As a newbie to this processes, these are the steps I followed to reproduce this issue:

1. I refer to this [document](https://github.com/chouseknecht/minishift-up-role). I'm using Mac device for this.

2. Installed the latest ansible version from its official site.

3. Installed minishift from [this](https://github.com/minishift/minishift#with-homebrew).

4. Role installation
   4.1 Installed the role from chouseknecht repo.
   4.2 Copy the playbook from your roles path to the current working directory. Im on the local root directory.
   4.3 Create a localhost inventory file
   4.4 Run the playbook

9. After accessing the console browser, I added a project from the default selection, pasted the [yaml file](https://github.com/jubicoy/drupal8-docker/blob/master/drupal8-mysql-webdav.json) and run the process.

NOTE: I don't modified anything. Everything is on its default values.

**Comment by gbraad** [comment]
As can be seen in the file `drupal8-mysql-webdav.json`, the persistent volume claim is made using the variable `VOLUME_CAPACITY` [ref](https://github.com/jubicoy/drupal8-docker/blob/master/drupal8-mysql-webdav.json#L330), for the size of 10Gi [ref](https://github.com/jubicoy/drupal8-docker/blob/master/drupal8-mysql-webdav.json#L345). If you have used an unmodified yaml, you will likely run into issues, as the `minishift-up-role` only create a PV for 5G [ref](https://github.com/chouseknecht/minishift-up-role/blob/master/files/minishift-up.yml#L16)

**Comment by johnreytanquinco** [comment]
Cool, I'll try to narrow down Drupal8 size to 5Gi to make them identical. I'll update afterwards.

**Comment by gbraad** [comment]
@johnreytanquinco any update?

**Comment by johnreytanquinco** [comment]
I tried to edit the size of the volume in Drupal8 file but doesn't solve the issue. Also did: oc create -f my-custom-pv-creation.yml, redeploy the application, still the same.

So what solves the issue is by installing the [fabric8](https://fabric8.io/guide/getStarted/gofabric8.html) and issue this command: gofabric8 volumes

It auto-creates the needed pvc and corrected pvc path.
