### ISSUE TITLE
Add multiple feature files to make integration

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#583]
Now the current suite is growing bigger where more test scenario will be added to smoke, sanity, docker and many more. As multiple feature file is supported by godog test framework so it's a good idea to keep the test specific scenario in respective feature file rather putting it in a single feature file and making it big and complicated. 

For example:
For sanity check put all the sanity scenario in sanity.feature. Similarly
```
Sanity check -> sanity.feature
smoke check -> smoke.feature
openshift check -> openshift.feature
docker check -> docker.feature
...
```

By using specific tags such as ```make integration tags="sanity smoke"``` specific feature test can be run. This can be achievable by putting the tag ```@sanity``` at the top of the feature file. These tags can be manipulated as per the requirement #578

**Comment by agajdosi** [comment]
Seems like we can keep code just at `basic_test.go` for now and then if some functions will be too specific, we can move them into `<name-of-feature>_test.go` to keep `basic_test.go` not extremely long. WDYT @gbraad @hferentschik?

I agree that it is possible to rename `basic.feature` to more exact `smoke.feature` with tag `@smoke`. What do you mean by sanity.feature, what should be there, @amitkrout? For me it feels maybe like a tag: `@smoke` is short, `@sanity` runs all features but skips some repetetive scenarios - e.g. it would not deploy all OpenShift examples, but just few of them, and then we can have `@full` to run just everything - usable for automation.

**Comment by hferentschik** [comment]
I for sure get the step definition into their own file to start with. Really we want to build some sort of re-usable step definition library here.

**Comment by LalatenduMohanty** [comment]
@hferentschik Sorry did not understood your point.  Can you please elaborate? 

Categorization of tests is a good thing.  Is there any way we can put the tag (or tags) in individual tests. So that we can manage them in a better way.

**Comment by amitkrout** [comment]
@agajdosi smoke is subset of sanity. Mostly it has the basic scenario such as start, stop, ssh, console access and delete. This is for a quicker validation check on binary file. Where as sanity would be smoke plus basic functionality check such as config check , services check ... and image deployment. Its true that scenario will be repeated, so i think putting scenarios in one file ```?.feature``` and adding the tags to avoid multiple feature file for same scenario.

@LalatenduMohanty yes godog supports tag/tags on individual scenario

```
@minishift docker OpenShift
  Scenario: Starting Minishift
    Given Minishift has state "Does Not Exist"
    When executing "minishift start --docker-env=FOO=BAR --docker-env=BAZ=BAT"
    Then Minishift should have state "Running"
     And Minishift should have a valid IP address
```

**Comment by agajdosi** [comment]
@amitkrout I see, I was just unsure if we need it, but if we go for having both in one feature file and specifying just a subset of scenarios as `@smoke`, then it looks just good +1.

**Comment by hferentschik** [comment]
As agreed, I am going to close this issue. There is no real actionable item and other already started tasks are adding new feature files.
