### ISSUE TITLE
Put oadm on the host machine

### ISSUE THREAD

**Issue by dustymabe** [minishift/minishift#587]
If you need to run `oadm` we need that executable on the host machine somewhere. I think we can get by with just running `oc adm` but maybe a file called `oadm` that just calls `oc adm` would be good enough.

**Comment by thesteve0** [comment]
problem is that oadm is in the server download and there is actual no install for minishift. So there is no way to make a ln and not even sure how you would do that on windows. This seems like either it should be added to the vm so people can minishift ssh in and use it OR needs doc somewhere

**Comment by dustymabe** [comment]
like I said `oc adm` worked fine for me. so we simply create a script:

```
#!/bin/bash
oc adm $@
```

if we couldn't rely on bash being there then we could make a statically compiled very simple c program (binary) that does the same thing.

**Comment by gbraad** [comment]
the `minishift ssh` approach is not really preferred, as you will pay a penalty for the command invocation (slowness #529). an alias would be a possible approach... also for powershell

**Comment by hferentschik** [comment]
I don't really see the point of putting another binary on the host when one can just as well do a 'oc adm'. I guess we can discuss whether we create a symbolic link transparently. That might be an issue on Windows though.

**Comment by dustymabe** [comment]
> I don't really see the point of putting another binary on the host when one can just as well do a 'oc adm'.

The problem is that all the openshift docs say `oadm`. Making that jump from `oadm` to `oc adm` for a new user is not going to be easy. It's not a hard logical leap, but knowing it exists is the bigger problem.

**Comment by hferentschik** [comment]
As @thesteve0 is saying, oadm is not even cross compiled. So we would not even have a binary for use on OS X or Windows. 

I think the best we can do is to add a note to the docs somewhere that having the _oc_ binary on the host allows you to run _oadm_ commands via _oc adm_.

**Comment by dustymabe** [comment]
what about an executable called `oadm` that just calls `oc adm` as I suggested in https://github.com/minishift/minishift/issues/587#issuecomment-288296862

**Comment by gbraad** [comment]
why not copy the executable and call it `oadm` ?

**Comment by hferentschik** [comment]
> what about an executable called oadm that just calls oc adm as I suggested

given that it would need to be cross platform, we would be down to compile another binary as you suggest. We need to do this cross platform. We also need to get it onto the host, which means we either host it somewhere or we bundle it into the minishift binary in order to then extract. A lot of effort imo for very little benefit.

Also there is a risk then that this _oadm_ binary gets mixed up or considered to be the actual _oadm_ binary. I really think we should not go down this route.

**Comment by dustymabe** [comment]
which executable? `oc`? That would be a waste of disk space, right?

What I'm suggesting wouldn't require a link I don't think.

**Comment by hferentschik** [comment]
> why not copy the executable and call it oadm

that's not enough. _oadm_ commands are as part of _oc_ under  _oc adm_

**Comment by gbraad** [comment]
I believe the executables pick this up...

**Comment by gbraad** [comment]
Ah, seems not... I was under the impression they did an invocation check... so links would also not work.
(Maybe something we should suggest to implement)

**Comment by hferentschik** [comment]
For me this is still a big -1. We don't do us or the user a favor here. The right thing to do is to use 'oc adm'.

**Comment by dustymabe** [comment]
we had a discussion in #minishift . I summarized my feelings about this into 3 points:

- minishift actually doesn't *have* to do anything related to this issue. I was just trying to document a user trap
- if we can get openshift guys to state that `oc adm` is the way of the future and `oadm` is deprecated, then I'm happy and minishift doesn't need to do anything
- if `oadm` is going to be around and what is used in future docs, then I'd like to have an `oadm` command available to minishift users (this issue)

**Comment by dustymabe** [comment]
sent [a message](http://lists.openshift.redhat.com/openshift-archives/dev/2017-May/msg00009.html) to openshift devel list about point number 2

**Comment by jorgemoralespou** [comment]
oadm is a symlink to oc, since long time back, and should be removed from the documentation.

Clayton already replied to the message you sent. I would not consider even having it symlinked by minishift.

**Comment by praveenkumar** [comment]
Closing this since we (as part of minishift) doesn't need to change anything.
