### ISSUE TITLE
Add a section for Hyper-v in the docker-machine-drivers doc.

### ISSUE THREAD

**Issue by Preeticp** [minishift/minishift#589]
Currently only KVM and Xhyve instructions are documented we need to add instructions for Hyper-V too, especially in the context of this comment: https://github.com/minishift/minishift/pull/573#issuecomment-288355091

**Comment by Preeticp** [comment]
For reference: https://msdn.microsoft.com/en-us/virtualization/hyperv_on_windows/quick_start/walkthrough_virtual_switch

**Comment by gbraad** [comment]
https://docs.docker.com/machine/drivers/hyper-v/#environment-variables-and-default-values

I have quickly tested it, but it seems `$env:HYPERV_VIRTUAL_SWITCH` gets ignored. When starting as `minishift.exe --show-libmachine-logs` I still see the first that gets chosen is the first one. (this value is `(Get-VMSwitch)[0].Name`)

**Comment by budhrg** [comment]
> I have quickly tested it, but it seems $env:HYPERV_VIRTUAL_SWITCH gets ignored. When starting as minishift.exe --show-libmachine-logs I still see the first that gets chosen is the first one. (this value is (Get-VMSwitch)[0].Name)

Getting same behavior for me too

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift/pull/779
