### ISSUE TITLE
Allow selection of virtual switch for use with Hyper-V

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#590]
Related to: #589

Allow selection of the Virtual Switch to use for deployment with Hyper-V. Needs to be compatible with the behavior with Docker Machine ([environment variables](https://docs.docker.com/machine/drivers/hyper-v/#environment-variables-and-default-values)) and the possible passthrough #305 

At this point there are no way to choose a virtual switch in HyperV for Minishift . Minishift uses the first virtual switch in the list for the Minishift VM. This will result in to failure if the virtual switch is not the intended switch for Minishift (e.g. not an external switch, not connected to external dhcp server etc).  So user who have multiple virtual switch are most likely to face this issue.

**Comment by hferentschik** [comment]
I think you can already do that - https://docs.docker.com/machine/drivers/hyper-v/#usage. Have you tried setting the environment variable HYPERV_VIRTUAL_SWITCH?

**Comment by gbraad** [comment]
@hferentschik see #589, Both I and @budhrg have tested this to not work as expected. Either we miss a necessary call, or something else needs to be done...

**Comment by hferentschik** [comment]
>  Both I and @budhrg have tested this does not work as expected. Either we miss a necessary call, or something else needs to be done...

I see. Might need some investigation.

**Comment by gbraad** [comment]
@budhrg can you have a quick look at the following?

https://github.com/docker/machine/blob/fcef6c18f4ead8445bcd93e7f3557369425a653c/drivers/hyperv/hyperv.go#L62

**Comment by gbraad** [comment]
@budhrg can you verify the behaviour on upstream's `minkube` ?

**Comment by budhrg** [comment]
> can you verify the behaviour on upstream's minkube ?

Yes, good to check that. thanks

**Comment by gbraad** [comment]
@budhrg I just did... gets ignored too...

**Comment by budhrg** [comment]
> I just did... gets ignored too...

Ah

**Comment by gbraad** [comment]
Minikube does allow for prefixed use:

```powershell
PS C:\Users\gbraad\Downloads> $env:MINIKUBE_HYPERV_VIRTUAL_SWITCH="External (Wireless)"
PS C:\Users\gbraad\Downloads> .\minikube-windows-amd64.exe start --vm-driver hyperv --v=3
========================================
kubectl could not be found on your path.  kubectl is a requirement for using minikube
To install kubectl, please do the following:

download kubectl from:
https://storage.googleapis.com/kubernetes-release/release/v1.5.3/bin/windows/amd64/kubectl.exe
Add kubectl to your system PATH

To disable this message, run the following:

minikube config set WantKubectlDownloadMsg false
========================================
Starting local Kubernetes cluster...
Starting VM...
Running pre-create checks...
Creating machine...
(minikube) Downloading C:\Users\gbraad\.minikube\cache\boot2docker.iso from file://C:/Users/gbraa
o/minikube-v1.0.7.iso...
(minikube) Creating SSH key...
(minikube) Creating VM...
(minikube) Using switch "External (Wireless)"
(minikube) Creating VHD
```

However, this does not work on Minishift:
```powershell
PS C:\Users\gbraad\Downloads> $env:MINISHIFT_HYPERV_VIRTUAL_SWITCH="External (Wireless)"
PS C:\Users\gbraad\Downloads> .\minishift\minishift.exe start --show-libmachine-logs
Starting local OpenShift cluster using 'hyperv' hypervisor...
Running pre-create checks...
Creating machine...
(minishift) Downloading C:\Users\gbraad\.minishift\cache\boot2docker.iso from file://C:/Users/gbraad/.minishift/cache
/iso/minishift-cifs.iso...
(minishift) Creating SSH key...
(minishift) Creating VM...
(minishift) Using switch "External (Ethernet)"
(minishift) Creating VHD
PS C:\Users\gbraad\Downloads>
```

**Comment by gbraad** [comment]
We would need to restore/add the option `hyperv-virtual-switch` for the start command:
https://github.com/kubernetes/minikube/blob/4b3459ed5baefb6d94f174f0e2d790c4f3eb3985/cmd/minikube/cmd/config/config.go#L157, this then gets set properly when prefixed and specified as `MINISHIFT_HYPERV_VIRTUAL_SWITCH`

**Comment by LalatenduMohanty** [comment]
Setting the hyperv-virtual-switch name though `minishift config` command to set it in `~/.minishift/config/config.json` sounds like a good idea to me.

**Comment by hferentschik** [comment]
config.json might work, but can anyone explain to me why the environment variable does not work. I see it it is defined in the in _GetCreateFlags_ of _hyperv.go_. Has anyone debugged this to checked why this would not pick up the variable and whether this is a generic issue? Here is the thing. adding something specifically to _config.json_ might work (even though you still need to pass it on the driver which might actually get hacky), but if there is a general issue with the env variable approach, then I'd rather look at that and fix that. After all, there are other drivers and they take parameters as well. AFAIU the intended mechanism to so this, is via environment variables. So before we do something else, I'd like to know why env variables are not working.

**Comment by gbraad** [comment]
@hferentschik the GetCreateFlags never gets called, as this is part of Docker Machine. In https://github.com/kubernetes/minikube/issues/1326 you can see how they solved it for minikube.

**Comment by budhrg** [comment]
AFAIU the intended mechanism to so this, is via environment variables. So before we do something else, I'd like to know why env variables are not working.

@hferentschik Assigned issue to myself to investigate it properly and to know what's going on. However, we have workaround as mentioned above by @gbraad

**Comment by hferentschik** [comment]
>  the GetCreateFlags never gets called, as this is part of Docker Machine

It is part of the Driver API and we do call it - https://github.com/minishift/minishift/blob/eff0477aa242432aaba284febf9496ebe6cd2371/pkg/minikube/machine/client.go#L40-L40. Apparently though we only call _NewDriver_. So I guess we need to make the call to _ GetCreateFlags_ here as well to make sure the driver initialisation can pick up any env variables. Same for the other drivers. This way we solve several issues in one go (I would hope)

**Comment by budhrg** [comment]
>  So I guess we need to make the call to _ GetCreateFlags_ here as well to make sure the driver initialisation can pick up any env variables. Same for the other drivers. This way we solve several issues in one go (I would hope)

Yes, that is the plan we discussed.

**Comment by budhrg** [comment]
The Minikube way to provide enviornment variable as `MINIKUBE_HYPERV_VIRTUAL_SWITCH` is working for minishift.  For minishift, it will be same as specified here https://minishift.io/docs/managing-minishift.html#environment-variables.

We need to explicitly set virtual switch for hyper here in [`cluster/cluster_windows.go`](https://github.com/minishift/minishift/blob/master/pkg/minikube/cluster/cluster_windows.go#L25) after from config and start options changes. 

`$env:MINISHIFT_HYPERV_VIRTUAL_SWITCH=<switch name>`.

The PR is ready except tests in my local repo. 

Right now investigating why docker environment variable `HYPERV_VIRTUAL_SWITCH` is not working as part of @hferentschik [comment](https://github.com/Minishift/minishift/issues/590#issuecomment-291805276).
For initial, I tried by calling `GetCreateFlags` right after NewDriver but didn't work. Didn't work too when tried calling even after host creation in `cluster.go#StartHost`.

Need more time to investigate in depth IMO.

**Comment by budhrg** [comment]
@hferentschik , I did the debugging today.

> It is part of the Driver API and we do call it - https://github.com/minishift/minishift/blob/eff0477aa242432aaba284febf9496ebe6cd2371/pkg/minikube/machine/client.go#L40-L40. Apparently though we only call NewDriver. So I guess we need to make the call to _ GetCreateFlags_ here as well to make sure the driver initialisation can pick up any env variables. 

The lines you mentioned about call to `NewDriver` never get executed in a normal case since the if condition doesn't pass. To make it pass, we specify _MACHINE_PLUGIN_TOKEN_ and _MACHINE_PLUGIN_DRIVER_NAME_ which results in failure. Honestly, don't know why it is required here.
So, we don't have control over flags here IMO.

> Same for the other drivers. This way we solve several issues in one go (I would hope)

Yes, found VIRTUAL_MEMORY_SIZE listed here https://docs.docker.com/machine/drivers/virtualbox/#options is not working.

The other flags seems be already part of `minishift start` command options.

Let me know what are you think here more. Hope you have seen my above comment too.

**Comment by hferentschik** [comment]
@budhrg, the code in _client.go_ is moot. I should not have pointed to it. It was just the first reference I found. This particular code can partly be removed. Anyways, where we have to look is _cluster.go_. There the various drivers are created. Looking at the Driver struct, it defines two methods, _GetCreateFlags_ and _SetConfigFromFlags_. The first tells you which flags a driver supports and the second updates a driver config from a flag set. So applying this to _createVirtualboxHost_ in _cluster.go_, this looks roughly like this:

     func createVirtualboxHost(config MachineConfig) drivers.Driver {
     	d := virtualbox.NewDriver(constants.MachineName, constants.Minipath)
     
     	// find out which flags a driver supports
     	supportedFlags := d.GetCreateFlags()
     
     	// get hold of a concrete implementation of DriverOption
     	checkFlags := &drivers.CheckDriverOptions{
     		FlagsValues: map[string]interface{}{},
     		CreateFlags: supportedFlags,
     	}
     
     	// TODO:
     	// Now we need to iterate the CreateFlags for the supported ENV options.
     	// For each env options, we need to check the environment whether it is set
     	// If set we upate FlagsValues in checkFlags
     
     	// the populated checkFlags can now be passed to the driver which will update its configuration
     	err := d.SetConfigFromFlags(checkFlags)
     	if err != nil {
     		// need to handle error
     	}
     
     	d.Boot2DockerURL = config.GetISOFileURI()
     	d.Memory = config.Memory
     	d.CPU = config.CPUs
     	d.DiskSize = int(config.DiskSize)
     	return d
     }     

I am pretty sure this is going to work. Also this code can is generic for all drivers, so can be extracted into some methods and used by the various driver creation methods of _cluster.go_.

**Comment by hferentschik** [comment]
So really the generic approach solves issue #305 and should be used to put the basic code in place. We can still keep this issue open. If we implement #305 as outlined in https://github.com/minishift/minishift/issues/590#issuecomment-293397120, then we can, as part of this issue, make sure that we add an explicit note for Hyper-V.

**Comment by budhrg** [comment]
@hferentschik ,

> make sure that we add an explicit note for Hyper-V.

Didn't get by what explicit note you are mentioning here. As if we fix #305 as per your comment, then this issue will be fixed as part of that. 
Are you saying here to have readme updates?

**Comment by hferentschik** [comment]
> As if we fix #305 as per your comment, then this issue will be fixed as part of that

From an implementation point of view yes. What I am saying is that we might still want to then add an explicit note or troubleshooting entry somewhere. AFAIU, the need to specify the switch originates for example from having also Docker for Windows installed. In this case there primary switch will be taken by Docker for Windows and one needs to define another one and then also select it. Issue #305 is about putting the mechanics in place to do this. This issue would be about making sure that a user having Docker for Windows installed and running into problems can easily find this information. 

So a troubleshooting entry might make most sense!?

**Comment by hferentschik** [comment]
Merged via pull request #779

**Comment by gbraad** [comment]
@hferentschik the issue exists anytime someone has more than one Virtual Switch. With Docker4Windows this is always the case, but someone who uses Windows Containers, might also have this already... or just someone who has two interfaces (wireless and wired). So yes, a troubleshooting entry makes sense!? I am actually looking for it, as at the moment I am not sure what the actual solution is without having to look at code ? or... ah, I see... it is in the `installing.adoc` ? Doesn't feel like the correct location. This is not a 'prerequisite' kind of thing, but rather a 'using' kind of thing.

**Comment by LalatenduMohanty** [comment]
@gbraad I think it is better tell about this to user when he is trying to install minishift on HyperV. So thtat is user is aware of it and might choose to make it full proof.

**Comment by gbraad** [comment]
I kind of disagree... I do not believe that a user who wants to try this is a jiffy, will read the install. As you know, the install is mostly just an extraction action. Since it fails, he might look at the troubleshooting, and this is not found there:

Also, an example for `cmd` and/or `powershell` is preferred:

cmd:
```cmd
C:\ > set HYPERV_VIRTUAL_SWITCH=External (Wireless)
... and not
C:\ > set HYPERV_VIRTUAL_SWITCH="External (Wireless)" 
```
note: using quotes results in errors of not finding the virtual switch

      Error creating the VM. Error with pre-create check: "vswitch \"\\\"External (Wireless)\\\"\" not found"

powershell
```powershell
PS> $env:MINISHIFT_HYPERV_VIRTUAL_SWITCH="External (Wireless)"
```

**Comment by LalatenduMohanty** [comment]
@gbraad  I still feel it should be part of installation doc. But I would suggest lets create a new issue about this and discuss.

**Comment by reza-ebrahimi** [comment]
I have used following command and its doesn't work:
`minikube.exe start --vm-driver="hyperv" --hyperv-virtual-switch="Primary Virtual Switch"`

and also I have to change `DriverName`  in config.json file in path `.minikube\machines\minikube`, and `minikube` give me following error:

![1](https://cloud.githubusercontent.com/assets/11276982/26443498/e339b812-414d-11e7-9016-beae84ea3382.png)
![3](https://cloud.githubusercontent.com/assets/11276982/26443547/1b394e76-414e-11e7-9439-d59891c42d38.png)
![2](https://cloud.githubusercontent.com/assets/11276982/26443555/236f9d52-414e-11e7-9931-ac9642218b5a.png)

![4](https://cloud.githubusercontent.com/assets/11276982/26443561/30d40a5a-414e-11e7-8346-aa478c301d7a.png)

**Comment by gbraad** [comment]
Please see #843

**Comment by reza-ebrahimi** [comment]
@gbraad I cannot understand how resolve that,

But I have found another problem, if you set `--vm-driver hyperv` argument to `minikube`, it doesnot override config file value and still assume `virtualbox` driver.

**Comment by gbraad** [comment]
@reza-ebrahimi You have reported the issue to the Minishuft project. This is a fork of the Minikube project. Seeing your issue, you probably filed it in the wrong place...

**Comment by reza-ebrahimi** [comment]
@gbraad  I know it, so I hope to have a solution to this here, but thanks...

**Comment by gbraad** [comment]
@reza-ebrahimi please file the issue at minikube

**Comment by reza-ebrahimi** [comment]
https://github.com/kubernetes/minikube/issues/1523

**Comment by gbraad** [comment]
Removing unrelated comments. The user is unnecessarily spamming multiple issues which are unrelated:
![ref](https://cloud.githubusercontent.com/assets/1894/26446821/4d9a8900-4178-11e7-9eeb-4b635dc0e824.png)
