### ISSUE TITLE
Permission denied error on `make clean` for `docs/build` dir content

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#594]
Hi,

On performing `make clean`, I am getting permission denied error for content of `docs/build` dir:
```
$ make clean
rm -rf /home/budhram/gowork/pkg/linux_amd64/github.com/minishift
rm -rf ./out
rm -rf release
rm -rf vendor
rm -rf ./docs/build
rm: cannot remove './docs/build/minishift-adoc.tar': Permission denied
rm: cannot remove './docs/build/_topic_map.yml': Permission denied
rm: cannot remove './docs/build/variables.adoc': Permission denied
Makefile:107: recipe for target 'clean' failed
make: *** [clean] Error 1


#### ls info of docs/build
$ ls docs/build -l
total 120
-rw-r--r--. 1 root root 112640 Mar 20 20:04 minishift-adoc.tar
-rw-r--r--. 1 root root   2297 Mar 20 20:04 _topic_map.yml
-rw-r--r--. 1 root root     32 Mar 20 20:04 variables.adoc
```
It seems those content are created with `root` user permission.

Interestingly, I thought `rake clean` inside `docs` folder should clean it up but it seems to be not working too
```
$ pwd
/home/budhram/gowork/src/github.com/minishift/minishift/docs

$ ls
build  config.rb  Dockerfile  Gemfile  Gemfile.lock  Rakefile  source

$ tree build 
build
├── minishift-adoc.tar
├── _topic_map.yml
└── variables.adoc

0 directories, 3 files

$ rake clean
rm -f 
rm -rf build

$ tree build 
build
├── minishift-adoc.tar
├── _topic_map.yml
└── variables.adoc

0 directories, 3 files
```

At the end, I need to `sudo rm -rf docs/build`

**Comment by gbraad** [comment]
I haven't checked the docs container, but it likely runs as a root-container. An improvement would be to use `USER` for the actual process of generating the documents.

**Comment by hferentschik** [comment]
There are a couple of things here. First of all we should add a container based _clean_ target for the docs. I will address this as part of this issue. 

I also agree with @gbraad that using USER makes sense and might help. Question is what USER to use.

The thing which gets me is that I cannot reproduce this. If I start with no _build_directory and use 'make gen_docs' to generate the docs via the Docker container, I don't end up with root owned files. 'make clean' works also just fine. Should permissions problems not be the same for OS X and Linux. Is Docker doing different things here? @budhrg is this re-producable for you?

**Comment by gbraad** [comment]
This causes very bad behaviour on Windows now:
```
drwxrwxrwx+ 1 gbraad       gbraad            0 Feb 21 13:44 cmd
drwxr-x---  1 Unknown+User Unknown+Group     0 Mar 24 15:18 docs
-rwxrwxrwx+ 1 gbraad       gbraad          826 Mar 23 12:51 gen_help_text.go
```
even as Administrator you aren't allowed to remove the folder.

Anyways, you can use
```
USER UID
```
as environment variable and pin initially to UID=1000. this is not ideal, but works better than the current root behaviour. I could have a look at this later... ex. [gbraad/devenv](http://github.com/gbraad/devenv/)

**Comment by hferentschik** [comment]
>  I never run this on Windows, but I do have the error... and, this causes very bad behaviour on Windows now:

Interesting. I guess we need to do something about it then ;-) I guess we will do multiple things here. Still intrigued why OS X seems to behave differently.

**Comment by gbraad** [comment]
@hferentschik I wonder if you pull master, what the permissions on the `docs/` folder is with `ls -al` on macOS

**Comment by hferentschik** [comment]
I'll check. About to look into this anyways....

**Comment by budhrg** [comment]
Closed via https://github.com/minishift/minishift/pull/602
