### ISSUE TITLE
Generated asciidoc files need header tags 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#596]
The generated adoc files for the command reference need some generic header information:

    :icons:
    :toc: macro
    :toc-title:
    :toclevels: 1

(even though only :icons: seems relevant here)

On top of this, we need to adjust the heading level. It start with H2, but should start with H1.

**Comment by thatdocslady** [comment]
Just to clarify, we need to have more than what is in the description. According to the openshift doc guidelines this is what we need:

`[[topic-id]]`
`= Document/Topic Title
`:data-uri:
`:icons:
`:toc: macro
`:toc-title:
`-----------intentional blank line--------------
`toc::[]

And the Document/Topic Title needs to be the H1. 
The [[topic-id]] is already auto-generated from what I can see, but is currently attached to an H2, which should be moved to be H1 and placed in the top of the metadata section.

Reference: https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#topic-metadata

**Comment by hferentschik** [comment]
@thatdocslady, so why would you like to add a table of content toc::[] in this case? And if you don't add one, what's the point in adding :doc: and :toc: marco, if we are not going to insert a table of content. :data-url: and :icons: are related to images, also something which is not relevant for these pages. 

> The [[topic-id]] is already auto-generated from what I can see, but is currently attached to an H2, which should be moved to be H1

The problem is that there is no H1. Neither in the markdown, nor in the generated adoc file. Hence we need to adjust all existing headers and reduce one level.

**Comment by thatdocslady** [comment]
>  so why would you like to add a table of content toc::[] in this case?

It's not my personal desire to add this, I'm only referring to the requirement from openshift. If you want we can have a discussion with them to verify whether this is really needed and what it means, but I'm not in a position to answer this question.

> The problem is that there is no H1. Neither in the markdown, nor in the generated adoc file. Hence we need to adjust all existing headers and reduce one level.

Yes, this is one of the steps that Robert suggested we do. I believe the syntax he gave as an example is `sed 's/^=\(=\{1,4\}\) \(.\+\)$/\1 \2/'`, but I can't confirm or deny whether this is exactly what we need.

**Comment by hferentschik** [comment]
> It's not my personal desire to add this, I'm only referring to the requirement from openshift.

Surely one needs to understand what's happening here, right? As said, only 'toc::[]' is doing anything here, since this the command which inserts a table of contents. The rest of the header are variables controlling toc and images.  

In our case  a table of content is not useful, since it actually breaks the intended look and feel. The generated command ref pages are mimicking manages and adding a table of content really does not help for these short pages. For example, with TOC

![command-ref-with_toc](https://cloud.githubusercontent.com/assets/296354/24315859/0da55082-10ea-11e7-8f7b-40c011ffaf98.png)

without toc

![command-ref-without_toc](https://cloud.githubusercontent.com/assets/296354/24315866/191e6f52-10ea-11e7-8f66-0214195dc395.png)

IMO, the latter looks much better. Would you agree?

**Comment by hferentschik** [comment]
Regarding the header levels, that was not a problem to adjust. So I suggest we go for adjusting the headers, but no TOC.

**Comment by LalatenduMohanty** [comment]
@hferentschik TOC is helpful when we have a long page. I agree that at this point adding TOC does not add to the aesthetic of the page but IMO it as a necessary evil for long term point of view.

**Comment by hferentschik** [comment]
> necessary evil for long term point of view.

I don't get it. Why is it a necessary evil? The current docs.openshift.org also have pages without table of content. As you say, whether or not you want to add a table of content is a question of content (does a table of content help navigating the content? is it required due to the length of the content, ...) and aesthetic. You say yourself that aesthetically we don't need one and affect the pages are short. So where is the necessary evil?

**Comment by hferentschik** [comment]
@LalatenduMohanty @thatdocslady - for the record, the overview pages in docs.openshift.org do not contain a TOC either - https://docs.openshift.org/latest/whats_new/index.html. Or this is https://docs.openshift.org/latest/whats_new/applications.html, also without no TOC.

**Comment by LalatenduMohanty** [comment]
> So where is the necessary evil?

Because we might have some pages short today but we do not know how long it will be in future. Hence my suggestion of keeping a TOC so that in future we do not have to deal with question about whether we want to add a TOC or not.

**Comment by thatdocslady** [comment]
I don't know if it's a matter of a necessary evil, but IIRC some elements in this metadata header affect topic navigation so they are needed. Also, the :toc: macro: and toc::[] tags must be included together to influence the TOC position. Either way, I still hold my opinion that if the openshift folks specifically requested this metadata, we should either ask them if every element is necessary or give them what they ask for, as they are the ones who are ultimately parsing the docs for publication.

As far as the openshift docs not having this everywhere, I propose that nobody is perfect and they have such a huge doc set that maybe they didn't get to do an overall sweep on all their topics? Similar to the discussion we had about naming where Kubernetes was being held as an example, I feel that we should pay attention to the general rule and not to the exceptions and make sure that we are consistent in our formatting and structure.

**Comment by LalatenduMohanty** [comment]
As per discussion with @hferentschik I am fine with both TOC or no TOC. @thatdocslady Sure lets check if it is requirement but as per my understanding  it should not be .

**Comment by hferentschik** [comment]
Merged via pull request #627
