### ISSUE TITLE
minishift should install a storage class so that PVC's get resolved to persistent volumes (say, HostPath?) by default

### ISSUE THREAD

**Issue by jstrachan** [minishift/minishift#599]
if you run any apps with `PersistentVolumeClaim` resources in them on minishift then the PVC's never bind. 

The user has to manually create PVs by hand which isn't aweome. So it'd be nice if minishift came with an OOTB storage class setup to do this for you.
https://docs.openshift.org/latest/install_config/persistent_storage/dynamically_provisioning_pvs.html

**Comment by jorgemoralespou** [comment]
oc 1.5 provided 100 PV by default, so if you use that version in minishift you'll get the Persistent Volumes created. They are created with a job that runs after "oc cluster up" has finished.

Dynamic provision only works with a set of Persistent Drivers, and hostPath is not one of them, which would be the default and easiest for minishift. That is the one used by the mentioned job.

Use "minishift start --openshift-version=1.5.0-rc.0" and you'll have PV available that you can claim.

**Comment by jstrachan** [comment]
@jorgemoralespou ah awesome thanks! Yay! :)

Lemme close this as once we're on 1.5 OOTB for MiniShift then its effectively fixed

**Comment by rhuss** [comment]
> Use "minishift start --openshift-version=1.5.0-rc.0" and you'll have PV available that you can claim.

should be `minishift start --openshift-version=v1.5.0-rc.0` ...

**Comment by jorgemoralespou** [comment]
@hferentschik didn't you also accept versions without the v prefix?

**Comment by dcdh** [comment]
I have reached the limit (pv0100). When I want to create a new storage I get this event message "no volume plugin matched".
I've removed all pv (except one).

How can I **reset** PV generator to have a new one dynamicaly generated (as pvXXXX) ?

**Comment by alwinmark** [comment]
I really don't get, why Openshift is such a crap and why anyone should use openshift rather than plain kubernetes. If one is not forced to use those crappy Openshift Templates or other stupid openshift interfaces:

```
kubectl get sc
NAME                 PROVISIONER                AGE
standard (default)   k8s.io/minikube-hostpath   79s
```

One really have problems with openshift that are already years ago solved in the normal kubernetes world.
