### ISSUE TITLE
Extend 'executing' step to make sure that command exists successfully 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#608]
We should add another condition to the 'executing' step in our GoDog tests. Something like
"When successfully executing "oc new-app https://github.com/openshift/nodejs-ex"". This would execute the command and throw an error when it does not complete successfully. 

Right now, when executing commands as part of preconditions the test continues and will most likely fail on the final assertion step, effectively hiding the original cause.

**Comment by agajdosi** [comment]
@hferentschik Seems like this was resolved by #820 and could be closed.
