### ISSUE TITLE
Integration tests should not use 'minishift' as VM name

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#611]
At the moment the integration tests run in a temporary directory using MINISHIFT_HOME to separate it from the default setup in ~/.minishift. However, it uses still the name 'minishift' as name for the VM which conflicts when the tests are creating the VM and another one is already running. 

The integration test should use a name like 'minishift-integration' instead. For that to work we need to make the name constant _minishift_ dynamic, similar to how we dealt with the Minishift home directory.

**Comment by LalatenduMohanty** [comment]
We still need to fix this.

**Comment by agajdosi** [comment]
@LalatenduMohanty, @hferentschik Seems to me that we have newer duplicate issue here: #1680. As this newer issue has more activity, I am suggesting to close this one. WDYT?

**Comment by praveenkumar** [comment]
I agree, closing this issue now.
