### ISSUE TITLE
Use the new command to list the OpenShift versions.

### ISSUE THREAD

**Issue by warmchang** [minishift/minishift#614]
The "minishift get-openshift-versions" command is droped, and instead of "minishift openshift list-versions".

So we should modify the description in the [managing-minishift](https://github.com/minishift/minishift/blob/master/docs/source/using/managing-minishift.adoc).

![image](https://cloud.githubusercontent.com/assets/13084624/24393753/deefaf3c-13cb-11e7-83d7-098db75124e7.png)

Pls triage this issure and then I will fix it.

**Comment by thatdocslady** [comment]
Hi @warmchang thanks for opening this issue! Are you planning to submit a PR with the updated docs? Please tag myself and/or @Preeticp when you do, we are doc writers for this project and would love to help with reviews or questions :)

**Comment by hferentschik** [comment]
Merged via pull request #615

**Comment by warmchang** [comment]
You are welcome, I have submited a PR for this, Pls check it. @thatdocslady @Preeticp 
https://github.com/minishift/minishift/pull/615
