### ISSUE TITLE
Update the "Writing and Publishing documentation" topic

### ISSUE THREAD

**Issue by thatdocslady** [minishift/minishift#618]
The following information is missing from this topic:

- Authoring guidelines: Should include basic topic structure, links to OpenShift docs guidelines, etc
- Deploying docs: How to trigger job to stage and tarball the docs after local testing, what happens on the OpenShift side, etc

**Comment by thatdocslady** [comment]
TODO: Include instruction on updating topic map in case of adding new topics.

**Comment by hferentschik** [comment]
Merged via pull request #1030.
