### ISSUE TITLE
Extract install, quickstart, and docker daemon info into new topics

### ISSUE THREAD

**Issue by thatdocslady** [minishift/minishift#623]
Following discussion on issue #533 and PR #621 it was decided to split the work on the README as follows:

This issue will address: Copy (not move) the "Installation", "Quickstart", and "Reusing the Docker daemon" sections from the README to new topics and place them in their final destinations as asciidoc files in the appropriate sub-directories. 

This is an interim step on the way to getting our docs published, since we cannot remove the information from the readme yet, but we also need to have a complete doc set to test in the coming days and to publish ASAP.

After the docs are published, the original issue #533 will address converting the README to asciidoc and removing the duplicate sections, replacing them with a general high-level getting started section and appropriate links to the documentation.

**Comment by hferentschik** [comment]
Merged via pull request #624
