### ISSUE TITLE
Addon application should be less verbose

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#634]
Currently, during addon application each command executed gets printed to screen, like so:

    Applying addon anyuid:
    -- adm policy add-scc-to-group anyuid system:authenticated
    ...

This is too verbose. We should either:

- Don't print the commands and add a _--verbose_ switch in order to have a more verbose output
- Use the logger to log the executed commands and the user can set the right logging level to get more detailed information about the addon application. This relates to issue #169 as well.

**Comment by jorgemoralespou** [comment]
@hferentschik I would use the logger, as that seems more an aligned strategy.

Also, I would possibly add in the addon a success and failure message (or at least success) in the metadata, so the addon developer can define a message that would be printed giving some bare information.

Like:
Applying addon anyuid:
-- Anyuid scc has been granted to every user. (WARN: You can now run docker images as root)

**Comment by hferentschik** [comment]
Sure, so here is what I think we should do. 

* The actual execution and timing of the commands should use the logger (glog for now) and only become visible when setting a specific log level
* The beginning of the addon application is as we have it now - "Applying addon anyuid:"
* When a command fails execution stops and the failed command gets logged/printed to the console
* On competition we can imo go two ways
  * Applying addon anyuid: success (23s) - So we just print "success" and the total execution time once complete
  * The more advanced option is to add some new meta tags "Success Message" and print that message on success

Sounds good?

**Comment by budhrg** [comment]
> The actual execution and timing of the commands should use the logger (glog for now) and only become visible when setting a specific log level

+1. _Timing_ seems to unnecessary to general users and should be shown on demand

> When a command fails execution stops and the failed command gets logged/printed to the console

Also, found failure of one addons stops other addons installation. See https://github.com/minishift/minishift/issues/666

**Comment by hferentschik** [comment]
This has actually been addressed. Output is less verbose now. Further improvements will happen in another issue.
