### ISSUE TITLE
Add 'available' addon command

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#636]
`minishift addons install --defaults` installs the bundled Minishift addons. Prior to executing this command, it might be nice to have something like `minishift addons available` to list the available addons. 

This makes, however, most likely only sense if we have something like a remote addon repository as well. Just for the purpose of listing available addons bundled within the binary, this command seems an overkill. Also moving forward we most likely install default addons per default.

**Comment by jorgemoralespou** [comment]
Maybe you can do:

minishift addons list --installed=true --available=false [DIR|URL]

So you can list the addons that are either available (not installed) or installed, and potentially you could provide a dir or url to list the available remotely.

**Comment by hferentschik** [comment]
+1, something along these lines.

**Comment by budhrg** [comment]
Closing this issue as this can be achieved by `minishift addons list`
