### ISSUE TITLE
Add explicit command to apply add-on

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#637]
At the moment addons are only applied during `minishift start`. There is no explicit way to run a given addon. 

There are two suggestions:

- An explicit `minishift addons run [ADDON-NAME]`
- Implicit use of `minishift addons enable  [ADDON-NAME]`

The reuse of the _enable_ command tries to avoid command proliferation. The idea is that if the VM is not running, the addon just gets enabled in the config (current behaviour). If the VM is running, however, it also gets run directly.

**Comment by jorgemoralespou** [comment]
@hferentschik as you know I'm in favour of option 2 (whenever you enable the addon, it will install it if there is a VM running). But I just realized a race condition you should be aware, if you have a VM already created but stopped, and then enable an addon, it will not be applied, as install only happens at bootstrapping (or at command execution if this get implemented and the VM is running). Maybe there needs to be a mark, whether the addon was installed, so if it was enabled with the VM in stop mode, it will be applied on first next boot.

**Comment by hferentschik** [comment]
I think an explicit _run_ is the better option. For example I could image a addon which I want to run multiple times. This is not really "enabling", but rather "execute"/"run". I think semantically a explicit "run" is needed. 

I am also not convinced yet, whether this implicit enable or enable and run/apply is really so intuitive.

**Comment by LalatenduMohanty** [comment]
> think an explicit run is the better option. For example I could image a addon which I want to run multiple times. This is not really "enabling", but rather "execute"/"run". I think semantically a explicit "run" is needed.

+1

minishift addons enable is fine when the VM is not running and it automatically runs when minishift is started. However I think we need an explicit run command. It is similar to how `systemctl enable` and `systemctl start` work.

**Comment by hferentschik** [comment]
Merged via pull request #958
