### ISSUE TITLE
Investigate performance of Minishift under load

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#640]
There have been several reports on performance regressions of Minishift under load, for example when using the MSA demo or when provisioning Fabric8. 

In particular the CPU/RAM footprint has increased to say Minishift 0.9

**Comment by gbraad** [comment]
https://cdn.rawgit.com/redhat-helloworld-msa/helloworld-msa/master/readme.html#_access_openshift_console

**Comment by jorgemoralespou** [comment]
Remember that the defaults for cpu and memory do not allow to run these.

**Comment by gbraad** [comment]
@jorgemoralespou This is based on a thread started by Burr, in which he reports that since Minishift 0.9 memory usage has jumped. Actually, we also switched OpenShift versions during that time, ... this more likely could mean that OpenShift consumes more than in previous versions.

I will first see what the memory footprint is of each image in idle mode... after this with deployed minimum set... and then try to create load.

**Comment by hferentschik** [comment]
> I will first see what the memory footprint is of each image in idle mode... after this with deployed minimum set... and then try to create load.

+1 We should look at memory for print as well as CPU load. I thought we could take samples of these key numbers at regular intervals during the test and then plot/compare the data across versions.

**Comment by jorgemoralespou** [comment]
I think you should just measure minishift and not any application deployed
on top. There could have been changes to those apps and that could distract
your attention.

In any case when requests come from application specifics I would ask for
more evidences. Your time is valuable to diagnose application specifics.
IMHO

**Comment by hferentschik** [comment]
> I think you should just measure minishift and not any application deployed on top.

Sure, the idea is make some statements about Minishift, but you need some sort of application right. Some baseline. We don't want to compare absolute numbers for MSA or fine tune MSA. I just want to compare between Minishift versions and potentially detect issues there. Does that make sense?

**Comment by jorgemoralespou** [comment]
How do you know cpu and memory used by minishift OOTB if you deploy an app?

**Comment by gbraad** [comment]
idle on 1.5.0
```
              total        used        free      shared  buff/cache   available
Mem:        6094932     2453068     1906988       17572     1734876     3086312
Swap:       1023996         152     1023844

              total        used        free      shared  buff/cache   available
Mem:        6094932     2983484      618724       17708     2492724     2774904
Swap:       1023996           0     1023996
```

idle on 1.4.1
```
              total        used        free      shared  buff/cache   available
Mem:        6094932     3172596     1240548       17756     1681788     2382048
Swap:       1023996          28     1023968
```

**Comment by gbraad** [comment]
Using 1.5.1
```
              total        used        free      shared  buff/cache   available
Mem:        2048476      436336       72880       17572     1539260     1326144
Swap:       1023996         100     1023896

top - 15:08:37 up 7 days, 55 min,  2 users,  load average: 0.02, 0.11, 0.14
Tasks: 188 total,   1 running, 187 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.5 us,  0.1 sy,  0.0 ni, 99.3 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 32817340 total, 21948644 free,   375020 used, 10493676 buff/cache
KiB Swap:  8175612 total,  8175612 free,        0 used. 30745516 avail Mem
```

**Comment by gbraad** [comment]
![minishift-idle2](https://cloud.githubusercontent.com/assets/1894/26236912/608f43ac-3ca5-11e7-9c16-f3bef23d6521.png)

![minishift-idle](https://cloud.githubusercontent.com/assets/1894/26236920/6ab17cc4-3ca5-11e7-89d8-39d25c31b62a.png)
![minishift-idle3](https://cloud.githubusercontent.com/assets/1894/26236919/6aae551c-3ca5-11e7-8b9e-c829317666db.png)

**Comment by gbraad** [comment]
didn't want to use any invasive tooling, as they can affect the results, but I have seen ANY process that goes astray so far. Not during deployment, or during idle usage.

**Comment by gbraad** [comment]
![minishift-idle-141-2](https://cloud.githubusercontent.com/assets/1894/26237988/ce7ebc22-3ca9-11e7-865f-daaf64193ac7.png)
![minishift-idle-141-1](https://cloud.githubusercontent.com/assets/1894/26237987/ce7a66b8-3ca9-11e7-9d1c-d966173b0e61.png)
![minishift-idle-141-3](https://cloud.githubusercontent.com/assets/1894/26237989/ce801be4-3ca9-11e7-93df-61bbf9cbab4b.png)

**Comment by gbraad** [comment]
Deployment:
```
$ oc new-app https://github.com/openshift/nodejs-ex -l name=myapp
```

On 1.5.1:
![minishift-qs-1](https://cloud.githubusercontent.com/assets/1894/26292051/8f09fcda-3ee5-11e7-8345-40e6ede0664c.png)
![minishift-qs-2](https://cloud.githubusercontent.com/assets/1894/26292052/8f0cad22-3ee5-11e7-95cb-2c38d8da4cc7.png)

On 1.4.1
![minishift-qs-3](https://cloud.githubusercontent.com/assets/1894/26292053/8f0d8bac-3ee5-11e7-99f9-191c9c1a6292.png)
![minishift-qs-4](https://cloud.githubusercontent.com/assets/1894/26292050/8f09d7b4-3ee5-11e7-93bf-663ac90ef25d.png)

**Comment by gbraad** [comment]
it seems I forgot to include the findings of minishift 0.9.0. This probably happened as it is a very unfair comparision. I'll get to this later.

First of all, this is run on a CentOS7 based image, and NOT on the b2d, using default settings. After `openshift` started in the native method, the idle footprint looks as follows:
```
$ free
              total        used        free      shared  buff/cache   available
Mem:        2048476      359168       69184       16784     1620124     1355592
Swap:       1023996          56     1023940
```

```
$ free
              total        used        free      shared  buff/cache   available
Mem:        2048476      301412       75488       16796     1671576     1408780
Swap:       1023996           4     1023992
```

![minishift-native-1](https://cloud.githubusercontent.com/assets/1894/26337828/38758b68-3fae-11e7-8098-7cf49163165e.png)

And this is also where the problems start. Earlier versions of minishift do not properly relocate all the persistence and config in the data disk. This means that the liverw mount will run out of space, which renders the image useless, see #355. Just a simple install of diagnostic tools can already trigger it in this case.

Comparing the performance of b2d against the CentOS based image is not appropriate. With the b2d image, more is actually run from memory directly and there is no SELinux in place.

**Comment by gbraad** [comment]
minishift 0.9.0 - openshift 1.3.1 - **b2d**:
```
docker@minishift:~$ free
              total        used        free      shared  buff/cache   available
Mem:        2050204      319532      698192      378424     1032480     1200876
Swap:       1450740           0     1450740
```

after deployment of `nodejs-ex`:
```
              total        used        free      shared  buff/cache   available
Mem:        2050204      475260      447148      336532     1127796     1065436
Swap:       1450740       42220     1408520
```

```
top - 06:50:34 up 12 min,  2 users,  load average: 1.30, 0.61, 0.29
Tasks: 107 total,   1 running, 106 sleeping,   0 stopped,   0 zombie
%Cpu0  :   0.0/0.0     0[                                                                                             ]
%Cpu1  :   1.3/0.7     2[||                                                                                           ]
GiB Mem : 47.9/1.955    [                                                                                             ]
GiB Swap:  2.9/1.384    [                                                                                             ]

  PID USER      PR  NI    VIRT    RES  %CPU %MEM     TIME+ S COMMAND
    1 root      20   0    9.5m   1.8m   0.0  0.1   0:04.84 S init
  123 root      20   0    8.8m   2.4m   0.0  0.1   0:00.09 S  `- udevd
  873 root      20   0    8.8m   2.2m   0.0  0.1   0:00.00 S      `- udevd
  874 root      20   0    8.8m   2.1m   0.0  0.1   0:00.00 S      `- udevd
 2129 root      20   0    9.5m   1.9m   0.0  0.1   0:00.00 S  `- crond
 2154 root      20   0   23.0m   2.9m   0.0  0.1   0:00.01 S  `- sshd
 3228 root      20   0   25.5m   4.1m   0.0  0.2   0:00.00 S      `- sshd
 3230 docker    20   0   25.5m   2.4m   0.0  0.1   0:00.55 S          `- sshd
 3231 docker    20   0   11.6m   2.3m   0.0  0.1   0:00.01 S              `- sh
 3754 docker    20   0   15.2m   2.1m   0.7  0.1   0:00.38 R                  `- top
 2158 root      20   0    6.0m   1.3m   0.0  0.1   0:00.00 S  `- acpid
 2167 root      20   0    9.5m   0.1m   0.0  0.0   0:00.00 S  `- udhcpc
 2179 root      20   0    9.5m   0.1m   0.0  0.0   0:00.00 S  `- udhcpc
 2218 root      20   0   15.7m   2.3m   0.0  0.1   0:00.02 S  `- ntpd
 2290 root      20   0   11.6m   2.1m   0.0  0.1   0:00.00 S  `- sh
 2449 root      20   0  755.8m  75.7m   0.7  3.8   1:50.88 S  `- docker
 2456 root      20   0   83.3m  16.7m   0.0  0.8   0:00.13 S      `- docker-containe
 2934 root      20   0  190.8m   7.6m   0.0  0.4   0:00.01 S          `- docker-containe
 2949 tc        20   0    2.9m   1.0m   0.0  0.0   0:00.01 S              `- pod
 3009 root      20   0  126.8m   4.4m   0.0  0.2   0:00.07 S          `- docker-containe
 3024 1000010+  20   0   53.9m  37.7m   0.0  1.9   0:02.16 S              `- dockerregistry
17412 root      20   0  134.8m   7.3m   0.0  0.4   0:00.00 S          `- docker-containe
17428 tc        20   0    2.9m   1.0m   0.0  0.0   0:00.00 S              `- pod
17447 root      20   0  199.8m   2.6m   0.0  0.1   0:00.00 S          `- docker-containe
17463 1000010+  20   0 1053.2m  51.7m   0.0  2.6   0:00.33 S              `- npm
17494 1000010+  20   0  888.8m  34.6m   0.0  1.7   0:00.19 S                  `- node
 2577 root      20   0 10.738g 363.8m   2.0 18.2   0:26.43 S  `- openshift
17519 root      20   0    9.5m   2.0m   0.0  0.1   0:00.00 S  `- getty
17544 root      20   0    9.5m   1.9m   0.0  0.1   0:00.00 S  `- getty
    2 root      20   0    0.0m   0.0m   0.0  0.0   0:00.00 S kthreadd
    3 root      20   0    0.0m   0.0m   0.0  0.0   0:00.14 S  `- ksoftirqd/0
    5 root       0 -20    0.0m   0.0m   0.0  0.0   0:00.00 S  `- kworker/0:0H
    7 root      20   0    0.0m   0.0m   0.0  0.0   0:00.29 S  `- rcu_sched
    8 root      20   0    0.0m   0.0m   0.0  0.0   0:00.00 S  `- rcu_bh
    9 root      rt   0    0.0m   0.0m   0.0  0.0   0:00.08 S  `- migration/0
   10 root      rt   0    0.0m   0.0m   0.0  0.0   0:00.11 S  `- migration/1
   11 root      20   0    0.0m   0.0m   0.0  0.0   0:00.79 S  `- ksoftirqd/1
   13 root       0 -20    0.0m   0.0m   0.0  0.0   0:00.00 S  `- kworker/1:0H
   14 root       0 -20    0.0m   0.0m   0.0  0.0   0:00.00 S  `- netns
   15 root       0 -20    0.0m   0.0m   0.0  0.0   0:00.00 S  `- perf
   16 root       0 -20    0.0m   0.0m   0.0  0.0   0:00.00 S  `- writeback
   17 root      20   0    0.0m   0.0m   0.0  0.0   0:00.02 S  `- kworker/0:1
   18 root      25   5    0.0m   0.0m   0.0  0.0   0:00.00 S  `- ksmd
   19 root      39  19    0.0m   0.0m   0.0  0.0   0:00.14 S  `- khugepaged
   20 root       0 -20    0.0m   0.0m   0.0  0.0   0:00.00 S  `- crypto
   21 root       0 -20    0.0m   0.0m   0.0  0.0   0:00.00 S  `- kintegrityd
   22 root       0 -20    0.0m   0.0m   0.0  0.0   0:00.00 S  `- bioset
   23 root       0 -20    0.0m   0.0m   0.0  0.0   0:00.00 S  `- kblockd
   24 root       0 -20    0.0m   0.0m   0.0  0.0   0:00.00 S  `- ata_sff
   25 root       0 -20    0.0m   0.0m   0.0  0.0   0:00.00 S  `- devfreq_wq
   26 root       0 -20    0.0m   0.0m   0.0  0.0   0:00.00 S  `- rpciod
   27 root      20   0    0.0m   0.0m   0.0  0.0   0:00.11 S  `- kworker/1:1
   30 root      20   0    0.0m   0.0m   0.0  0.0   0:00.20 S  `- kswapd0
   31 root       0 -20    0.0m   0.0m   0.0  0.0   0:00.00 S  `- vmstat
   32 root      20   0    0.0m   0.0m   0.0  0.0   0:00.00 S  `- fsnotify_mark
   33 root       0 -20    0.0m   0.0m   0.0  0.0   0:00.00 S  `- nfsiod
   53 root       0 -20    0.0m   0.0m   0.0  0.0   0:00.00 S  `- kthrotld
```

**Comment by gbraad** [comment]
... [summary will follow] ...

**Comment by gbraad** [comment]
Will refocus on providing a test script. With the idea to measure for several minutes before doing a deployment (see how stable the services are), after this doing a deployment and measure again for a trend in idle. After this try to issue calls to a service to generate traffic and again measure trend over some time. to see if memory bubbles ore gets reclaimed, if services keep requesting resources or have errors, CPU/load usage, etc.

The solution will look at `oc cluster up` scenario only as used by us, but allows to be used on all the platforms we have (to also take the hypervisor into the equation).

**Comment by hferentschik** [comment]
>  From the graphs above you can see how the container and the openshift process behave; they consume between 18-21% of the available memory on the host with default settings.

interesting

> Finding are not conclusive, but indicative that minishift did not introduce a substantial overhead. In the tests performed, performance under load has not been considered yet, but this will be done in follow-up as mentioned below.

Still this is already much better than the gut feeling statements we heard before

**Comment by hferentschik** [comment]
> Will refocus on providing a test script.

+1, something which can be used moving forward and allow comparisons between various Minishift versions would be great.

**Comment by gbraad** [comment]
Deploying the coolstore on Minishift with the following script:

```
#!/bin/sh
oc login -u system:admin
oc create -n openshift -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/jboss-image-streams.json
oc create -n openshift -f https://raw.githubusercontent.com/jboss-fuse/application-templates/master/fis-image-streams.json
oc login -u developer -p developer
oc new-project coolstore
oc process -f https://raw.githubusercontent.com/jbossdemocentral/coolstore-microservice/1.0.x/openshift/coolstore-template.yaml | oc create -f -
```

## b2d - 2G
```
$ minishift start --openshift-version=v1.5.1
```
### Result
   * failing deploy of the cart service. retrigger solved this


## CentOS 7 - default 
```
$ minishift start --iso-url file:///home/gbraad/minishift-centos7.iso --openshift-version=v1.5.1
```
### Result
   * multiple builds failing, retrigger solved most of them until openshift stopped respondng


## CentOS 7 - 4G
```
$ minishift start --iso-url file:///home/gbraad/minishift-centos7.iso --openshift-version=v1.5.1 --memory 4096
```

**Comment by gbraad** [comment]
During deployment, the following can be observed

```bash
oc rollout status deploymentconfig cart --watch

oc logs bc/coolstore-gw --follow
oc rollout status deploymentconfig coolstore-gw --watch
```

Note: issues with deployment of svc/cart has been observed before. And build failures have happened for the gateway (maven repository unreachable)

**Comment by gbraad** [comment]
Deployment of Cool Store: #964

**Comment by gbraad** [comment]
When running from `godog`, I am unable to run the test successfully with the same settings: CentOS + 4G fails to deploy locally. However the build runs well in CentOS CI. However, I can run the same test locally when I use the b2d image: #964

**Comment by gbraad** [comment]
Waiting for feedback from the performance team.

**Comment by praveenkumar** [comment]
@minishift/minishift-dev Do you folks still think this is relevant since we didn't get any kind of communication with perf team?

**Comment by budhrg** [comment]
@gbraad  Did we remind the perf team here?  Let's discuss this in F2F.

Also, assigned you since you have already done most of the testing so far.

**Comment by LalatenduMohanty** [comment]
I do not see much happening in this area. I would suggest we close this issue.

**Comment by gbraad** [comment]
Same here. I'd rather close now and discussing the f2f if able, as some of
the infrastructure for this is missing.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]
