### ISSUE TITLE
Add script to generate release notes to version control

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#645]
We can either integrate it into the Makefile or have some release scripts somewhere. The long term goal is to trigger a release via CI.

**Comment by hferentschik** [comment]
The current script is based on jq:

    curl -s https://api.github.com/repos/minishift/minishift/issues?milestone=8\&state=closed | \
    jq '.[] | "- Issue [#" + (.number|tostring) + "](" + .url + ") - " +  (reduce .labels[] as $item (""; (if    $item.color == "84b6eb" then (. + $item.name[5:]) else . end))) + " - " + .title' | \
    sort  -k5,5 -k2n | \
    tr -d \" | \
    sed -e s/api.github.com.repos/github.com/g

**Comment by hferentschik** [comment]
It might be nicer to put this into Go code!?

**Comment by budhrg** [comment]
Good idea 👍

**Comment by hferentschik** [comment]
We also should add the spring planning script at the same time.

**Comment by budhrg** [comment]
Merged via https://github.com/minishift/minishift/pull/673
