### ISSUE TITLE
Allow variable substitution to work for local as well as publication site build

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#647]
Our adoc sources for the documentation, include some files in order to inject some variables. Due to this issue in Asciibinder - https://github.com/redhataccess/ascii_binder/issues/60 - we need to use an import relative to the root of the publication (opposed to a proper relative link). This breaks the rendering of the site during development, leading to asciidoc warnings. 

To remedy this issue, we can change to import to be relative. This will make the site work for local development as well. Then as part of the Rake task for creating the tarball for publication under docs.openshift.org we adjust the include path.

**Comment by budhrg** [comment]
Merged via https://github.com/minishift/minishift/pull/715
