### ISSUE TITLE
Items to address as part of host folders

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#654]
As  #480 got merged, some things need to be addressed in follow-ups:

1) the hostfolder type is currently only `cifs`. this means that adding defaults to this type. this will likely not be the case for `sshfs`. introduce a `--type`
2) related to 1, when `sshfs` is added, using `--users-share` has to use `cifs` to work. will this fail when `--type` is set to `sshfs`? (more of a question).
3) config for allistances and instance now uses copied implementations. this will need to use an embedding approach (maybe with interface) to allow the function to exist on the struct, but being forwarded to an implementation that excepts `interface{}` instead.
4) documentation, separate issue.
5) moving the interactive input for `Add` into the cmd level, as to allow arguments to provide/specify the value instead. this also make the actual `Add` command in pkg a lot cleaner and free from input logic.

**Comment by hferentschik** [comment]
> the hostfolder type is currently only cifs. this means that adding defaults to this type. this will likely not be the case for sshfs. introduce a --type

this can be handled as part of the work for issue #317. Some refactoring to align sshfs and cifs will be required anyways.

> related to 1, when sshfs is added, using --users-share will allows have to use cifs. will this fail when --type is set to sshfs?

Not quite sure I understand this one. What do you mean?

> config for allistances and instance now uses copied implementations. this will need to use an embedding approach (maybe with interface) to allow the function to exist on the struct, but being forwarded to an implementation that excepts interface{} instead.

Right, I was wondering how this allinstances come into play. It feels odd imo. Also is the intended location $MINISHIFT_HOME/config/allinstances.json?

> documentation, separate issue.

See issue #648

**Comment by hferentschik** [comment]
@gbraad what remains really as part of this issue? Can we maybe created dedicated tasks for the issues which are not tracked otherwise?

**Comment by gbraad** [comment]
@hferentschik only 3 would be, and 4 (#655). The rest is part of either #317 or are small improvements. It works as currently merged...

rephrased 2, as this is more of a question when adding sshfs functionality.

**Comment by hferentschik** [comment]
> only 3 would be

right, let's create a issue for this then 

> rephrased 2, as this is more of a question when adding sshfs functionality.

Got you now. Need to look at the impl of user-share first and see how this all can be put together

> Note: I post it here, as we currently still lack a mailinglist. The information needs to be public...

sure

BTW, we also need to discuss password management. I guess we need a separate issue for that as well.

**Comment by gbraad** [comment]
@hferentschik can sshfs mount using a credentials file?

**Comment by hferentschik** [comment]
> can sshfs mount using a credentials file?

There are several ways of doing this. I am hoping to do it completely password free. What type of "credentials file" do you mean exactly?

**Comment by gbraad** [comment]
@hferentschik for `mount.cfs` you can use the option `-o credentials=[file]` that specifies a file containing:

```
username=dfd
password=fdf
domain=fff
```

pretty much like a certificate file... but remains the same for all situations. This allows to mount the folder instead of specifying the credentials from the commandline. This makes it possible to not store the credentials for a cifs hostfolder on the host, but inside the VM. (however, allinstances would complicate this, as each time a new instance is created, we would need to push a credentials file).

**Comment by gbraad** [comment]
> 3)

I rather not create issues for refactoring or technical debt, but in this case it can be a task for anybody to have a look at.

**Comment by hferentschik** [comment]
@gbraad can we close this?
