### ISSUE TITLE
Documentation for host folders

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#655]
After the merge of #480, we currently have the following commands to deal with host folders, but they are not documented.

`minishift hostfolder [subcommand]`

  * `add [sharename]`  
     * Adding a share using the specified name, using an interactive prompt. defaults to CIFS for now.
     * Defaults to defining a share for all instances. This can be overriden using `--instance-only`
     * When mountpath is specified, this overrides the default of `/mnt/sda1/[sharename]`.
  * `add --users-share`  
     adding the Users share on a Windows system. it stores credentials, Windows only, CIFS only.
  * `mount [sharename]`  
     mounts the share to a running instance,
  * `umount [sharename]`  
     unmounts the share from a running instance,
  * `list`  
     shows an overview of available hostfolders and when running, also the mount state
  * `remove [sharename]`  
     removes the hostfolder defintion

`minishift config set hostfolders-automount true`  
This will allow the hostfolders to be mounted when the cluster is started using `minishift start`.

`minishift config set hostfolders-mountpath [path]`  
This overrides the path that is used for a hostfolder when not overriden by the hostfolder. default value is `/mnt/sda1`.

**Comment by gbraad** [comment]
@thatdocslady Please have a look

**Comment by hferentschik** [comment]
That's a duplicate of #648. Since you already added more info here, I am going to close #648.

**Comment by thatdocslady** [comment]
Thanks @gbraad for the great starting info, will pick this up now and submit a PR

**Comment by thatdocslady** [comment]
We should extract the docs from the Managing Minishift topic and create a separate topic in the Using section: https://github.com/minishift/minishift/issues/664#issuecomment-291600762

**Comment by hferentschik** [comment]
Merged via pull request #823
