### ISSUE TITLE
Edit the add-ons docs

### ISSUE THREAD

**Issue by thatdocslady** [minishift/minishift#664]
Following the merge of the add-ons functionality, the docs still need some proofreading:

- Propose to change "Addons" to "Add-ons" to follow grammatical conventions.
- Propose to move the whole section into its own topic, currently it's a part of "managing minishift" and it's making the page run really long. IMO it deserves its own topic.
- Some minor grammar/formatting fixes

**Comment by thatdocslady** [comment]
@LalatenduMohanty @hferentschik @Preeticp WDYT?

**Comment by hferentschik** [comment]
> Propose to change "Addons" to "Add-ons" to follow grammatical conventions.

+1

> Propose to move the whole section into its own topic, currently it's a part of "managing minishift" and it's making the page run really long. IMO it deserves its own topic.

+1, in fact we should move host folder out as well, especially since it gets updated now as well. The rest can stay I guess.

We might want to think about a better way of "Managing" for the remaining content in the chapter. It's ok, but somehow also not quite hard. I cannot put a finger on a proper title. Any ideas?

> Some minor grammar/formatting fixes

Sure.

Added this issue to the next milestone.

**Comment by thatdocslady** [comment]
@hferentschik 

> We might want to think about a better way of "Managing" for the remaining content in the chapter. It's ok, but somehow also not quite hard. I cannot put a finger on a proper title. Any ideas?

Looking at the different sections in this topic, I agree that it seems a little bit like a "catch-all" bucket for now. I have some ideas, let me know what you think:

1. Remove the minishift start/stop/delete sections. TBH they basically repeat what's in the command reference, and the quickstart also has the start command in more details. Alternatively we can move those sections to the quickstart section itself, above the example procedure, and label them as "common commands". It makes more sense to have them there IMO.

2. Assuming that we are extracting the host folders and add-ons content into their own topics, we're basically left with a bunch of configuration sections, so maybe we can rename the topic to "Configuring Minishift", and then it's more accurately reflective of the content.

3. If we proceed with no.2 here, would it make sense to keep the proxy information here? Or should we extract it to some separate topic and call it "Networking" or something? Are we planning to document other aspects of networking in the future? Could be more useful for the modular docs approach.

**Comment by thatdocslady** [comment]
@hferentschik in addition to the doc updates, I see that we also need to proofread the doc strings in the actual addon commands. Should I open a separate issue for that or can I submit it all in a single PR?

**Comment by thatdocslady** [comment]
For the sake of clarity and sanity, I created a separate issue #734 to address the additional questions about the "Managing Minishift" topic, and will focus only on extracting the add-ons docs for this issue.

**Comment by hferentschik** [comment]
Merged via pull request #735
