### ISSUE TITLE
Subsequent add-ons fails when one addon fails in the middle

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#666]
Here is what I found when testing and seems to be bit interesting and need opinions.

I had three addons enabled at the moment and this can be more as expected:
```
$ minishift addons list                                    
- anyuid         : enabled    P(0)
- cluster-admin  : enabled    P(0)              
- registry       : enabled    P(0)
```

#### To make the addon `cluster-admin` fail, I made a type error as `add-role-to-user1`

I perform `minishift start`:
```
$ minishift start
Starting local OpenShift cluster using 'kvm' hypervisor...
....
   To login as administrator:
       oc login -u system:admin

Applying addon anyuid:
-- adm policy add-scc-to-group anyuid system:authenticated
  [144.014806ms]
Applying addon cluster-admin:
-- adm policy add-role-to-user1 cluster-admin developer
error: unknown command "add-role-to-user1 cluster-admin developer"
See 'oc adm policy -h' for help and examples.
E0405 10:50:33.560212   11975 start.go:232] Error executing addon commands Error executing command oc adm policy add-role-to-user1 cluster-admin developer.
```

Notice that the execution of addon  `registry` failed. The error message could be more user friendly here.

I had following thoughts in my mind now:
1. We continue installation of addons giving proper error message to failed one in the middle
2. We stop the execution with proper error message here
3. We set some policy in the `config.json` to this behavior with default being 1st and 2nd can be enabled by flag.

Like to know what other think too.

**Comment by praveenkumar** [comment]
> Notice that the execution of addon registry failed. The error message could be more user friendly here.

Not addon `registry` but `cluster-admin` failed. Execution of `registry` not even started in this case. We need to make a decision about what action we should take in case an intermediate addon fails from enabled addons list. According to current action we exit the process as soon as any on addon fail to execute and for interdependent addons it does make sense.

**Comment by budhrg** [comment]
> Not addon registry but cluster-admin failed. Execution of registry not even started in this case.

Didn't add the clear wordings here. Might be bit lack in coffee ☕️ . I mean the same. Addon `registry` also not installed/started. 

> We need to make a decision about what action we should take in case an intermediate addon fails from enabled addons list

👍

**Comment by hferentschik** [comment]
> We continue installation of addons giving proper error message to failed one in the middle

-1, that makes no sense

> We stop the execution with proper error message here

+1, I think the error message is not too bad. It looks for sure still ugly, but this is partly due to our "misuse" of glog. Here is a more general problem we need to fix.

**Comment by jorgemoralespou** [comment]
@hferentschik as long as you can enable an addon to an already running cluster, user can decide if they will manually execute all the other addons, else, with current behaviour, you would need to disable the addon and recreate the VM for the addon to re install.

**Comment by hferentschik** [comment]
So we have `minishift addons apply` now, which allows you to apply add-ons manually. In this case a user has a way to manually add add-ons. @budhrg, so does this work for you? This is basically offering what @jorgemoralespou describes in https://github.com/minishift/minishift/issues/666#issuecomment-292269493.

**Comment by hferentschik** [comment]
Closing this issue.
