### ISSUE TITLE
wrong URL of minishift start command reference in file "README.md".

### ISSUE THREAD

**Issue by warmchang** [minishift/minishift#668]
It's "https://minishift.io/docs/minishift_start.md", should be "https://minishift.io/docs/minishift_start.html".

I'll fix it.

![image](https://cloud.githubusercontent.com/assets/13084624/24693727/87639fa2-1a11-11e7-8752-d4b8b494b3f3.png)

**Comment by budhrg** [comment]
Nice catch @warmchang ! Thanks for taking care of it too 👍

**Comment by warmchang** [comment]
@budhrg Welcome!
