### ISSUE TITLE
`restartPolicy: Never` isn't using Terminating scope quota

### ISSUE THREAD

**Issue by rawlingsj** [minishift/minishift#670]
We have two namespace quota that work on openshift clusters but when running on minishift the pods are using the wrong ones. 

We should be able to use `restartPolicy: Never` on a pod and when terminating quotas have been applied, this means rather than use the NonTerminating quota it will use the short time bound quota.

Steps to recreate:
```
oc login -u developer
oc new-project james-test
oc login -u system:admin
oc apply -f https://gist.githubusercontent.com/rawlingsj/0924c7c3901cb36ac4eddf1d976e1bfe/raw/44a1bb58e021addbb2250fe77743ae995f4ed93c/compute-resources-timebound.yml
oc apply -f https://gist.githubusercontent.com/rawlingsj/bbe612afacbaf1ebbca5a6c5d70ad153/raw/4489aefc987a75ccee61a2e0a314f9850ff17dc2/compute-resources.yml
oc login -u developer
oc apply -f https://gist.githubusercontent.com/rawlingsj/6fdb7db4bdb20b971ed361448280400a/raw/fc20ab36da1dcc52393c8add7c96e37de2838e12/pod.yml
```
Look in the openshift console at the project quota and you can see the pod is using the NonTerminating scope rather than the Terminating
![screenshot 2017-04-05 10 48 24](https://cloud.githubusercontent.com/assets/1457180/24699880/70358436-19ed-11e7-8335-22651317399d.png)

**Comment by jorgemoralespou** [comment]
@rawlingsj This is an openshift issue.

What minishift and openshift versions are you using? Also what's the version of the cluster where this is working?

**Comment by rawlingsj** [comment]
@jorgemoralespou ah I see.  Does newer versions of minishift  come with openshift v3.5.5.5?

Failing on Minishift version: 1.0.0-beta.3:
```
Server https://192.168.64.151:8443
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994
```

Working on:
```
Server https://api.free-int.openshift.com:443
openshift v3.5.5.5
kubernetes v1.5.2+43a9be4
```

**Comment by hferentschik** [comment]
You can also bootstrap a "newer" version using the "--openshift-version" flag of the _start_ command. Btw, are you using the CDK or Minishift community?

**Comment by rawlingsj** [comment]
@hferentschik ok thanks - lemme give that a go

**Comment by praveenkumar** [comment]
@rawlingsj I hope your issue is resolved, I am closing this issue now if you think there is still a issue we will reopen same.
