### ISSUE TITLE
Create addon for persistence volume creation

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#671]
This might be temporary and be replaced/changed when we get persistence volumes as part of _cluster up_

**Comment by jorgemoralespou** [comment]
@hferentschik look into how oc-cluster sets up PV. It's as easy as running a job. Or you can explore how I do it in the oc-cluster which don't require jobs.

**Comment by hferentschik** [comment]
+1

**Comment by LalatenduMohanty** [comment]
So seems like we can just point `--host-pv-dir = /var/lib/minishift/openshift.local.pv` for `oc cluster up` and it will create the directories which can be used for PV. Refer [1]

[1] https://github.com/openshift/origin/pull/12456

**Comment by jorgemoralespou** [comment]
@LalatenduMohanty still I think an addon can provide benefit as this are the default 100 PVs that get created with "oc cluster".
There might be cases where you want to create the PVs in the host folder you share with the VM, or with a different type of options. I would not discard still adding some user experience, as if I could, I would just not create those 100 PVs by default, which takes some time to process.

**Comment by csrwng** [comment]
@jorgemoralespou the pv provisioning happens entirely in the background, but you can start using them as soon as the first pv is created. What's the downside?

**Comment by jorgemoralespou** [comment]
@csrwng as I mentioned before, this creates 100 directories in my host for each cluster I start, which although in the background is something it don't make me happy. I would rather prefer to control the amount or have less (max 20). Also, I can't modify any of the options for these (e.g. annotate with a service class, prebound volume,...) so I need to have the ability to set these. I still need a command that let's me be more expressive with the volumes I create.

**Comment by praveenkumar** [comment]
@hferentschik Can we close this issue now?

**Comment by hferentschik** [comment]
Let's close it for now. We have been talking about being able to skip the 'cluster up' persistence volume creation and doing it more explicitly in an add-on. However, as long as 'cluster up' dies create the persistent volumes regardless, we should be using them. We can create a new issue in case we want to look into this later again.
