### ISSUE TITLE
The ROADMAP filename should be update.

### ISSUE THREAD

**Issue by warmchang** [minishift/minishift#674]
After PR #663, the ROADMAP filename should be changed to ROADMAP.adoc.

**Comment by LalatenduMohanty** [comment]
@warmchang Thanks.  The link to CONTRIBUTING.adoc  i.e. link "contribution guidelines" is also broken in [1]. Can you please take care of this in your PR too. 

[1] https://github.com/minishift/minishift#community

**Comment by hferentschik** [comment]
Merged via pull request #675
