### ISSUE TITLE
Regression on "service list" 

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#677]
It seems the code which I added to make `minishift openshift service list` work for showing all routes available to user is not working.

I see the changes I added as part of my [PR here](https://github.com/budhrg/minishift/blob/d91a72f506efc62f4e70c45a7039fd6312c3134c/cmd/minishift/cmd/openshift/service_list.go).

This seems to be lost in rebase.

**Comment by LalatenduMohanty** [comment]
@budhrg @hferentschik Things are fine as it is. Hence closing it.
