### ISSUE TITLE
What can we do with option get-openshift-versions?

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#68]
The command `minishift get-openshift-versions` lists all the OpenShift versions which are available :

```
 - v1.3.0-rc1
- v1.3.0-alpha.3
- v1.2.1
- v1.3.0-alpha.2
- v1.3.0-alpha.1
...
```

But what can we do ? Is it possible to select the version that we want to deploy when we create a minishift instance ?

**Comment by jimmidyson** [comment]
Not yet, but soon... Contributions welcome.

**Comment by hferentschik** [comment]
When starting Minishift you get the option to specify the version of OpenShift you want to run (_--openshift-version_). The output of this command helps you to determine available versions you can use. The caveat here is, that the command outputs all versions, but not all versions are really compatible. Now with minishift based on 'oc cluster up', one need to specify a version >=1.3.0. 

From that perspective I also wonder whether an un-filtered output of all OpenShift releases make a lot of sense. 

What would make sense so, is the possibility for the user to interactively select the OpenShift version during start. I think that's where this ties in. However, if we have interactive selection of the OpenShift version during _start_, _ get-openshift-versions_ might become obsolete.

**Comment by hferentschik** [comment]
I think as question we can resolve this issue. I created issue #197 as sort of concrete follow up task.
