### ISSUE TITLE
.tar.gz contents should be in a subdirectory

### ISSUE THREAD

**Issue by bobmcwhirter** [minishift/minishift#680]
It's extraordinarily bad-mannered to expand a .tar.gz directly into $PWD without a subdirectory of some sort containing the contents.

    melvin:launchpad-addon bob$ tar ztf ~/Downloads/minishift-1.0.0-rc.1-darwin-amd64.tgz
    LICENSE
    README.md
    minishift

/me goes to clean up his $HOME.

**Comment by hferentschik** [comment]
Depends on #1217

**Comment by LalatenduMohanty** [comment]
Resolved by #1418
