### ISSUE TITLE
Allow to add any start parameter as part of config.json

### ISSUE THREAD

**Issue by kameshsampath** [minishift/minishift#687]
it will be nice to have the `routing-prefix` and `public-host-name` as part of the config properties so that user can set it once like other stuff `vm-driver` for their minishift. Right now its need that we add it every time during the minishift start

**Comment by hferentschik** [comment]
This applies probably to most of the start options.

**Comment by hferentschik** [comment]
I adjusted the title of this issue to make it clear that we need a generic solution here.

**Comment by hferentschik** [comment]
Merged via pull request #953
