### ISSUE TITLE
Clean up documentation set

### ISSUE THREAD

**Issue by thatdocslady** [minishift/minishift#691]
Now that we have the docs published (YAY!) there are a few things that need to be handled:

- Global pass on internal relative links to make sure they work and fix where needed
- Check for old GitHub links and replace them with openshift.org links or relative links as needed
- Sanity check on formatting and asciidoc behavior (i.e. making sure code blocks, tables, etc look ok)
- Verify that each index.adoc topic contains the correct links in the correct order (found already an instance where it's outdated)
- Verify that the topic map reflects the updated doc set
- AOB

There are a few issues that need to be resolved before this is done, i.e. #664 and #655, so putting needs-investigation on this to prevent confusion (hopefully).

**Comment by thatdocslady** [comment]
TODO: Adjust the navigation so that the getting started section goes Installation > Quickstart > Docker Machine drivers

**Comment by thatdocslady** [comment]
TODO: make sure "docker" is lowercase

**Comment by hferentschik** [comment]
Merged via pull request #1048
