### ISSUE TITLE
How to set the disk size of the VM?

### ISSUE THREAD

**Issue by burrsutter** [minishift/minishift#697]
How do I set the Minishift CDK's disk size?

**Comment by budhrg** [comment]
Hi @burrsutter ,

It can be set with `--disk-size` option in `minishift start` command.

See here - https://docs.openshift.org/latest/minishift/command-ref/minishift_start.html

**Comment by jorgemoralespou** [comment]
@burrsutter did you read the documentation or the "minishift start -h"? 
If you didn't, and the solution as @budhrg mentions is in the docs it would be nice if you close this issue.

If you did and still didn't know how to do it, could you provide what steps did you follow and what documentation is not clear?

**Comment by LalatenduMohanty** [comment]
Example `$ minishift start --vm-driver=virtualbox --disk-size 40g`

**Comment by LalatenduMohanty** [comment]
@burrsutter Here is the config set command `minishift config set disk-size 40g`
