### ISSUE TITLE
--metrics true does not work

### ISSUE THREAD

**Issue by burrsutter** [minishift/minishift#698]
./minishift version
    Minishift version: 1.0.0-beta.5
    CDK Version: 3.0.0-beta.3

    ./minishift --metrics true start

https://screencast.com/t/9qnyUIyak
https://screencast.com/t/mrfOjxr7IfF

**Comment by jorgemoralespou** [comment]
In minishift 1.0.0.rc.1 is working fine:

![image](https://cloud.githubusercontent.com/assets/78350/24767312/dee1e9bc-1afe-11e7-9a09-45bc42f842f0.png)

![image](https://cloud.githubusercontent.com/assets/78350/24767330/eaa2764a-1afe-11e7-8993-bcfc14c70f3d.png)

**Comment by LalatenduMohanty** [comment]
@burrsutter Can you please give  1.0.0.rc.1  a try and let us know if it does not work for you?

**Comment by hferentschik** [comment]
How long did you wait until you tried to access Hawkular. It takes some time until the required pods are running. You can for example:

    $ eval $(minishift docker-env)
    $ docker ps

Now you should see the running running pods/applications. In particular you should see the Origin container running OpenShift, as well as the router and registry pods. Most likely you will see also the metrics related pods. Is there is nothing at all, something during the provisioning went wrong, but my guess is that you will see pods related to metrics, just that they are not running yet.

**Comment by jorgemoralespou** [comment]
In 1.0.0.rc.1 with the sudoer capability, you can monitor the openshift-infra namespace:

````
 oc get pods -n openshift-infra --as=system:admin
NAME                         READY     STATUS      RESTARTS   AGE
hawkular-cassandra-1-rk7k6   1/1       Running     0          1h
hawkular-metrics-djvq7       1/1       Running     0          1h
heapster-1s7mh               1/1       Running     0          1h
metrics-deployer-pod-4vm9l   0/1       Completed   0          1h
````

**Comment by hferentschik** [comment]
Thanks @jorgemoralespou, I did not know out of the top of my head which pod to monitor. I just remembered that there are multiple.

**Comment by hferentschik** [comment]
@budhrg, metrics have been confirmed working by various people. I am going to close this issue. If you can provide something which re-producabily fails to provision metrics, we can reopen.

**Comment by budhrg** [comment]
Hi @burrsutter ,

Above comment by @hferentschik was for you 😄 Thanks.

**Comment by hferentschik** [comment]
Indeed ;-)
