### ISSUE TITLE
No installation instructions are provided

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#7]
The readme.md file refers to installation instructions part of the releases section which are not there

Additional point: 

Is this file part of a release (minishift-darwin-amd64) a go binary, .... ?

**Comment by jimmidyson** [comment]
Yeah I haven't got the install docs in line yet, but it's pretty simple: it's a single binary you download depending on your architecture (I know you're an OS X user to minishift-darwin-amd64 will be for you). Rename it to minishift (if you want) & either move it into your PATH or run with `./minishift`. If you haven't already used Docker Machine, then take a look at https://github.com/jimmidyson/minishift/blob/master/DRIVERS.md#xhyve-driver for xhyve driver installation instructions.

I'll try to write this up as proper docs soon, or a PR would be very welcome :)

**Comment by jamesbuckett** [comment]
curl https://github.com/jimmidyson/minishift/releases/v0.2.1/minishift-linux-amd64

mv minishift-linux-amd64 minishift

chmod +x minishift  

sudo mv minishift /usr/local/bin/

minishift start --vm-driver=virtualbox

**Comment by jstrachan** [comment]
agreed. There's instructions on minishift and fabric8 here: http://fabric8.io/guide/getStarted/minishift.html

**Comment by hferentschik** [comment]
The  basic install (install archive bundle and unpack) is not documented - https://github.com/minishift/minishift#instructions. We can refine this moving forward.

**Comment by LalatenduMohanty** [comment]
@thatdocslady @Preeticp  you might want to fix the installation documentation :)

**Comment by thatdocslady** [comment]
@LalatenduMohanty @hferentschik currently the instructions section describes what @jimmidyson mentioned in his previous comments. Is there anything else that we need to tell the users? If so, then we should either reopen this issue or create a new issue to expand the installation instructions.

**Comment by hferentschik** [comment]
>  If so, then we should either reopen this issue or create a new issue to expand the installation instructions.

We are fine for now.

**Comment by Preeticp** [comment]
The basic install (install archive bundle and unpack) is not documented - https://github.com/minishift/minishift#instructions. We can refine this moving forward.
I believe @hferentschik meant 'now' instead of 'not' in his previous comment.

**Comment by LalatenduMohanty** [comment]
@cmoulliard  @thatdocslady With recent release there is no need for change of the binary/executable name and it has already executable permission. 

@thatdocslady So we need to just put the extract the tar ball and run it. So lets create a new issue and track it there.

**Comment by LalatenduMohanty** [comment]
I have raised https://github.com/minishift/minishift/issues/203
