### ISSUE TITLE
version command should be available prior to setup-cdk

### ISSUE THREAD

**Issue by burrsutter** [minishift/minishift#700]
$ ./minishift version
    You need to run 'minishift setup-cdk' first to install required CDK components.
    $ ./minishift setup-cdk

I use version to verify that I have the right binary in the right place of the PATH, it is easy to have put the wrong version at the wrong place and totally "get off on the wrong foot".

**Comment by hferentschik** [comment]
This is really a CDK issue for which JIRA is used. I created https://issues.jboss.org/browse/CDK-111 for you.
