### ISSUE TITLE
Downloading initial ISO's should support HTTP proxy

### ISSUE THREAD

**Issue by donovanmuller** [minishift/minishift#718]
While `minishift start` does support providing a http/https proxy for OpenShift itself, it should also be able to provide a (or use the same) proxy when `minishift` downloads the initial ISO's.

```console
$ minishift start \
  --http-proxy http://22.151.94.51:3128 \
  --https-proxy http://22.151.94.51:3128
Starting local OpenShift cluster using 'xhyve' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
E0410 09:13:49.693645   21752 start.go:160] Error starting the VM: Get https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso: dial tcp 192.30.253.113:443: i/o timeout. Retrying.
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
```

**Comment by Sabartius** [comment]
As a Workaround, is it possible to trick Minishift, that theses ISO-Files are already downloaded?
I downloaded the iso with my browser and put it next to the minishift binary, but it still tries to download it.

**Comment by donovanmuller** [comment]
@Sabartius I haven't tried this but you might be able to copy the ISO into the `.minishift/cache/iso` folder:

```console
$ ll ~/.minishift/cache/iso
...
-rw-r--r--  1 donovan  staff    40M May  1 21:35 minishift-b2d.iso
```
as deleting the `minishift-b2d.iso` file will force a re-download.
I'm not too sure what else would need to be downloaded as there are other `.iso`'s in the `~/.minishift/machines/minishift` directory which I'm assuming also need to be downloaded...

**Comment by hferentschik** [comment]
Basically two things need to be downloaded, the ISO as @donovanmuller mentioned, but also the _oc_ binary. If you download both manually and put them at their appropriate places in the cache directory, things should be fine.

**Comment by donovanmuller** [comment]
@hferentschik I also noticed that the OpenShift Docker image will have to be pulled (e.g. `openshift/origin:v1.5.0`) initially on start.

```console
Starting local OpenShift cluster using 'xhyve' hypervisor...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ...
   WARNING: Cannot verify Docker version
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.0 image ...
   Pulling image openshift/origin:v1.5.0
   Pulled 0/3 layers, 3% complete
   Pulled 1/3 layers, 75% complete
   Pulled 2/3 layers, 98% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
```

Would the current proxy settings kick in before that pull happened? I.e. would the Docker daemon have the proxy settings configured when booting the VM for the first time?

**Comment by hferentschik** [comment]
Yes, that  Docker daemon would be properly configured, this is covered by the proxy flags of the start command - https://docs.openshift.org/latest/minishift/using/managing-minishift.html#http-s-proxies. Is is the downloads of the iso and _oc_ which is not covered atm.

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/commit/05854b49ab97c29df752f536f9b8b59e451418b8
