### ISSUE TITLE
Use topic map to dynamically generate navigation in Middleman site

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#721]
Following up with issue #711, the output of the Middleman generated site mimics now the output of the AsciiBinder build of docs.openshift.org. The missing piece is to incorporate the topic map and generate the links for the left side navigation dynamically. 

For this we need to add some Middleman helper generating the navigation bar dynamically from the topic map.

**Comment by budhrg** [comment]
Closed via https://github.com/minishift/minishift/pull/810
