### ISSUE TITLE
Create separate page for uninstalling instructions

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#722]
We are seeing that some users re-installing Minishift after the setup is gone bad and reinstalling steps is mostly about how to uninstall minishift and then try minishift again. So the uninstall steps are important for users.
At this point it is part of installing docs and misses the attention what it deserve.  
[1] https://docs.openshift.org/latest/minishift/getting-started/installing.html#uninstall-instructions

**Comment by hferentschik** [comment]
Merged via pull request #857
