### ISSUE TITLE
RH SSO will not start under default ISO

### ISSUE THREAD

**Issue by starksm64** [minishift/minishift#726]
If I try to deploy the registry.access.redhat.com/redhat-sso-7/sso70-openshift:1.3 using minishift and the default iso using `minishift start --memory=4096 --vm-driver=virtualbox` the server fails to start due to this exception:

```
14:32:29,470 ERROR [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0055: Caught exception during boot: java.lang.IllegalStateException: WFLYCTL0056: Could not rename /opt/eap/standalone/configuration/standalone_xml_history/current to /opt/eap/standalone/configuration/standalone_xml_history/20170410-143229469
	at org.jboss.as.controller.persistence.ConfigurationFile.createHistoryDirectory(ConfigurationFile.java:638)
	at org.jboss.as.controller.persistence.ConfigurationFile.successfulBoot(ConfigurationFile.java:470)
	at org.jboss.as.controller.persistence.BackupXmlConfigurationPersister.successfulBoot(BackupXmlConfigurationPersister.java:94)
	at org.jboss.as.controller.AbstractControllerService.finishBoot(AbstractControllerService.java:451)
	at org.jboss.as.server.ServerService.boot(ServerService.java:373)
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:301)
	at java.lang.Thread.run(Thread.java:745)
```

I have been unable to keep the pod alive long enough to inspect why the copy is failing, and I have tried both the v1.0.0-rc.1 and v1.0.0-beta.5 minishift releases.

If I use the --iso-url=https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.4/minishift-centos7.iso option, the RH SSO server starts file and is able to copy the current configuration to the 20170410... directory:

```
sh-4.2$ ls -l standalone_xml_history/
total 160
drwxrwxrwx. 2 jboss      jboss  4096 Mar 17 10:05 20170410-144313261
drwxr-xr-x. 2 1000040000 root      6 Apr 10 14:43 current
drwxrwxrwx. 2 jboss      jboss     6 Mar 17 10:05 snapshot
-rw-rw-rw-. 1 1000040000 root  24902 Apr 10 14:42 standalone-openshift.boot.xml
-rw-rw-rw-. 1 1000040000 root  24902 Apr 10 14:42 standalone-openshift.initial.xml
-rw-rw-rw-. 1 1000040000 root  24902 Apr 10 14:42 standalone-openshift.last.xml
-rw-rw-rw-. 1 jboss      jboss 20827 Apr 18  2016 standalone.boot.xml
-rw-rw-rw-. 1 jboss      jboss 20827 Apr 18  2016 standalone.initial.xml
-rw-rw-rw-. 1 jboss      jboss 21923 Mar 17 10:05 standalone.last.xml
```

I'm running this on a RHEL 7.2 laptop:
[sstark@sstark redhat-sso]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.2 (Maipo)

Steps to reproduce:

1. start minishift
minishift start --memory=4096 --vm-driver=virtualbox

2. Get the https://github.com/starksm64/redhat-sso repo
git clone https://github.com/starksm64/redhat-sso

3. Use mvn to deploy the RH SSO server
cd redhat-sso
mvn fabric8:deploy

4. Get the pod name. It will be the non-sso-1-deploy pod, e.g., sso-1-fqvh1

5. Watch the logs of that pod
oc logs sso-1-fqvh1
...

**Comment by hferentschik** [comment]
@starksm64, Is this the full stack trace? Is _opt/eap_ a directory in the EAP image? Any chance persistence volume are used for this application?

**Comment by starksm64** [comment]
That is the full stack trace.  

Yes, /opt/eap is coming from the EAP/RH SSO image.

I don't see any persistent volumes. Here are the mounts and output from oc get pvc for the centos iso that works:

[sstark@sstark redhat-sso]$ oc rsh sso-1-fqvh1
sh-4.2$ cat /proc/mounts 
rootfs / rootfs rw 0 0
/dev/mapper/docker-8:1-2091022-d8a017742edbf5cba5de3c630b18acda2dae1d8513ec803249d67af2a4c7f526 / xfs rw,context="system_u:object_r:svirt_sandbox_file_t:s0:c5,c6",relatime,nouuid,attr2,inode64,logbsize=64k,sunit=128,swidth=128,noquota 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev tmpfs rw,context="system_u:object_r:svirt_sandbox_file_t:s0:c5,c6",nosuid,mode=755 0 0
devpts /dev/pts devpts rw,context="system_u:object_r:svirt_sandbox_file_t:s0:c5,c6",nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666 0 0
sysfs /sys sysfs ro,seclabel,nosuid,nodev,noexec,relatime 0 0
tmpfs /sys/fs/cgroup tmpfs ro,context="system_u:object_r:svirt_sandbox_file_t:s0:c5,c6",nosuid,nodev,noexec,relatime,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
cgroup /sys/fs/cgroup/perf_event cgroup ro,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/pids cgroup ro,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/cpuacct,cpu cgroup ro,nosuid,nodev,noexec,relatime,cpuacct,cpu 0 0
cgroup /sys/fs/cgroup/net_prio,net_cls cgroup ro,nosuid,nodev,noexec,relatime,net_prio,net_cls 0 0
cgroup /sys/fs/cgroup/memory cgroup ro,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/devices cgroup ro,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/blkio cgroup ro,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpuset cgroup ro,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup ro,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/freezer cgroup ro,nosuid,nodev,noexec,relatime,freezer 0 0
mqueue /dev/mqueue mqueue rw,seclabel,nosuid,nodev,noexec,relatime 0 0
tmpfs /opt/sso-demo tmpfs ro,rootcontext="system_u:object_r:svirt_sandbox_file_t:s0:c5,c6",seclabel,relatime 0 0
tmpfs /etc/eap-secret-volume tmpfs ro,rootcontext="system_u:object_r:svirt_sandbox_file_t:s0:c5,c6",seclabel,relatime 0 0
tmpfs /etc/jgroups-encrypt-secret-volume tmpfs ro,rootcontext="system_u:object_r:svirt_sandbox_file_t:s0:c5,c6",seclabel,relatime 0 0
tmpfs /etc/sso-secret-volume tmpfs ro,rootcontext="system_u:object_r:svirt_sandbox_file_t:s0:c5,c6",seclabel,relatime 0 0
/dev/sda1 /dev/termination-log ext4 rw,seclabel,relatime,data=ordered 0 0
/dev/sda1 /etc/resolv.conf ext4 rw,seclabel,relatime,data=ordered 0 0
/dev/sda1 /etc/hostname ext4 rw,seclabel,relatime,data=ordered 0 0
/dev/sda1 /etc/hosts ext4 rw,seclabel,relatime,data=ordered 0 0
shm /dev/shm tmpfs rw,context="system_u:object_r:svirt_sandbox_file_t:s0:c5,c6",nosuid,nodev,noexec,relatime,size=65536k 0 0
/dev/sda1 /run/secrets ext4 rw,seclabel,relatime,data=ordered 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs ro,rootcontext="system_u:object_r:svirt_sandbox_file_t:s0:c5,c6",seclabel,relatime 0 0
proc /proc/asound proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/bus proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/fs proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/irq proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/sys proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/sysrq-trigger proc ro,nosuid,nodev,noexec,relatime 0 0
tmpfs /proc/kcore tmpfs rw,context="system_u:object_r:svirt_sandbox_file_t:s0:c5,c6",nosuid,mode=755 0 0
tmpfs /proc/timer_list tmpfs rw,context="system_u:object_r:svirt_sandbox_file_t:s0:c5,c6",nosuid,mode=755 0 0
tmpfs /proc/timer_stats tmpfs rw,context="system_u:object_r:svirt_sandbox_file_t:s0:c5,c6",nosuid,mode=755 0 0
tmpfs /proc/sched_debug tmpfs rw,context="system_u:object_r:svirt_sandbox_file_t:s0:c5,c6",nosuid,mode=755 0 0

[sstark@sstark redhat-sso]$ oc get pvc
No resources found.
[sstark@sstark redhat-sso]$

**Comment by praveenkumar** [comment]
@starksm64 As you said this is working with CentOS but not with b2d iso does it require anything specific to RHEL/CentOS? Since as per ISO concern we do have base packages as default for CentOS which might not be in b2d iso.

**Comment by starksm64** [comment]
No, as it is just a java based server, and the error is related to copying a directory within the /opt/eap directory structure. It would seem to be some kind of permission problem, but I have not been able to inspect the state of the pod before it is taken down. 

To aide in debugging this, is there a way to indicate that a pod that goes into failure state not be taken down so it can be inspected?

**Comment by praveenkumar** [comment]
> To aide in debugging this, is there a way to indicate that a pod that goes into failure state not be taken down so it can be inspected?

I am not sure, @jimmidyson ^^ any idea?

**Comment by jimmidyson** [comment]
You can run `oc debug <podName>` to start the pod up with a shell rather than the main process - you should then be able to dig about.

**Comment by praveenkumar** [comment]
@starksm64 Any update here?

**Comment by agajdosi** [comment]
Hello @starksm64, is this issue still relevant or did it disappeared since then?

**Comment by budhrg** [comment]
@starksm64 , Any update here?

**Comment by praveenkumar** [comment]
Closing this, since no more interaction with the reporter.
