### ISSUE TITLE
Specify the config json file to be used as file parameter

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#727]
The `minishift config` command allows to specify different parameters to be customized but it doesn't allow to pass using by example the attribute `--file` an existing json config file.

So we can do that 

```
minishift config set iso-url https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.4/minishift-centos7.iso
```

but we can't pass such info like this

```
minishift config --file myconfig.json

where myconfig.json is

{
    "iso-url": "https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.4/minishift-centos7.iso",
   "docker-env":"[storage-driver=devicemapper]" 
   ...
}
```

**Comment by hferentschik** [comment]
This imo against the original intend. So if you don't want to use the set command, why don't you edit the config.json directly? That works as well.

**Comment by hferentschik** [comment]
This has also a potential conflict with add-ons and hostfolders.

**Comment by starksm64** [comment]
The issue is to aid in specifying minishift startup commands so that user's don't have to copy/type long command lines when going through documentation.

So your recommendation would be to copy a config.json into the user's ~/.minishift/config/config.json?

**Comment by cmoulliard** [comment]
> So your recommendation would be to copy a config.json into the user's

That could be an option. We backup any existing config file and add our file.

There is still another problem as some of the parameters that you pass to the `start` command as the  docker-env parameter aren't supported by `config set`

**Comment by agajdosi** [comment]
@cmoulliard Good point. Those who run bash can use `minishift start $(< flags.txt)` as a workaround - at least I did it few times and it worked well for me. There could be similar solution for Windows, but I am not really a friend of cmd or PowerShell.

**Comment by hferentschik** [comment]
> So your recommendation would be to copy a config.json into the user's ~/.minishift/config/config.json?

That's one way. Not sure whether I am entirely happy about it.

> There is still another problem as some of the parameters that you pass to the start command as the docker-env parameter aren't supported by config set

That we will fix asap. We need to indeed allow to set any parameters, including some which are not part of the visible command line switches. I think we will loosen up on the validation logic being in place there. We might keep it for the "popular" setting, like cpus, memory, etc, but otherwise allow to set any type of key value pair. Details need to be discussed.

>  Those who run bash can use minishift start $(< flags.txt) 

I like that ;-)

Another think which might be useful could be a way to set multiple variables via a single _config set_.

**Comment by praveenkumar** [comment]
@cmoulliard now we have most of start flags as part of config so now `config set` can be use to put most of flags. @hferentschik do we need any other action for this issue?
