### ISSUE TITLE
Refactor "Managing Minishift" topic

### ISSUE THREAD

**Issue by thatdocslady** [minishift/minishift#734]
Following discussiong in #664, we should consider how to restructure the Managing Minishift topic to have easier flow and more accurate purpose.

My recommendations:

1. Delete or move the minishift start/stop/delete sections. TBH they basically repeat what's in the command reference, and the quickstart also has the start command in more details. Alternatively we can move those sections to the quickstart section itself, above the example procedure, and label them as "common commands". It makes more sense to have them there IMO.

2. Assuming that we are extracting the host folders and add-ons content into their own topics, we're basically left with a bunch of configuration sections, so maybe we can rename the topic to "Configuring Minishift", and then it's more accurately reflective of the content.

3. If we proceed with no.2 here, would it make sense to keep the proxy information here? Or should we extract it to some separate topic and call it "Networking" or something? Are we planning to document other aspects of networking in the future? Could be more useful for the modular docs approach.

Original comment in https://github.com/minishift/minishift/issues/664#issuecomment-291885952

**Comment by LalatenduMohanty** [comment]
> Alternatively we can move those sections to the quickstart section itself, above the example procedure, and label them as "common commands". It makes more sense to have them there IMO.

+1


> Assuming that we are extracting the host folders and add-ons content into their own topics, we're basically left with a bunch of configuration sections, so maybe we can rename the topic to "Configuring Minishift", and then it's more accurately reflective of the content.

I would suggest to keep the name "Managing Minishift" as we might want to add more documentation here. So keeping a generic name might help. 



> Would it make sense to keep the proxy information here? Or should we extract it to some separate topic and call it "Networking" or something?

I do not have strong opinions on this. But I think we should create a separate page for proxy as it is a very important feature. But we should not name it as "Networking"

**Comment by thatdocslady** [comment]
@hferentschik @LalatenduMohanty now it seems that there is some disagreement as to whether to extract the proxies information. Please discuss, I have no strong opinion either way but it's better if we reach an agreement here so that I can fix the PR that I already submitted based on this request.

**Comment by hferentschik** [comment]
> TBH they basically repeat what's in the command reference, and the quickstart also has the start command in more details. 

I fail to see the repetition here. The quickstart just executes _start_ once. As will be required to get started. It does not mention anything else really. Start/stop/delete in the managing Minishift section is going into more detail and explaining what's going on. If anything I think we should expand there and this is probably a good space to add some diagrams as well. Last but not least, there is the command ref, which is just the start/stop/delete commands with all there options. I think all these three things are different and serve their purpose.

I am not 100% sure about some of the headings and titles, but the structure overall works imo. I don't believe we need to do anything here atm.

**Comment by LalatenduMohanty** [comment]
As per the discussion here and in the PR closing the issue.
