### ISSUE TITLE
Running the container build pod failed

### ISSUE THREAD

**Issue by johnreytanquinco** [minishift/minishift#737]
Minishift version: 1.0.0-beta.5
Docker version: Client version: 1.5.0, Client API version: 1.17

While trying to setup the git repo https://github.com/goalgorilla/open_social on the server,
I am getting this error on the build pod that failed to proceed and create the application pod.

```
error: Execution of post execute step failed
error: build error: building myproject/opensocial-1:284314ba failed when committing the image due to error: Cannot connect to the Docker daemon. Is the docker daemon running on this host?

```

This are the steps to follow to reproduce:
1. Create the mysqlsocial container.. and its running fine.
`$ oc new-app mysql -e MYSQL_USER=drupal -e MYSQL_PASSWORD=drupal -e MYSQL_DATABASE=drupal --name=mysqlsocial`

2. Create the pvc and run `$ gofabric8 volumes`.

3. Create the drupal web app
`$ oc new-app https://github.com/goalgorilla/open_social -l name=social`

Anyone familiar with this error and can share the possible cause and solution for this, is greatly appreciated! Thanks in advance!

**Comment by LalatenduMohanty** [comment]
Not sure if it is related to fabric8. In case it is copying @jimmidyson @jstrachan

**Comment by jstrachan** [comment]
not sure there's any fabric8 being used to do the build though. all `gofabric8 volumes` does is create PVs for unbound PVCs - but thats not even required in the latest greatest minishift and latest greatest openshift as there's lots of PVs OOTB so they should bind

**Comment by jstrachan** [comment]
the error looks like your builder can't talk to docker

**Comment by LalatenduMohanty** [comment]
@johnreytanquinco Are you still facing the issue? This seems not to be an minishift issue. Also recently we have made a change to Minishift which setup 100PVs by default. You might want to try the next release or minishift compiled from master.

**Comment by johnreytanquinco** [comment]
Yes, I did a fresh install of everything...and this error disappeared. Thanks again. Will be cling this issue.
