### ISSUE TITLE
In case of expired login then maybe make it easy to login from minishift

### ISSUE THREAD

**Issue by davsclaus** [minishift/minishift#74]
I left my laptop the night over and now when I get back to minishift to open the web console with

```
davsclaus:/Users/davsclaus/Documents/workspace/client/$ minishift service fabric8
Error getting fabric8 service: the server has asked for the client to provide credentials (get services fabric8)
Check that minishift is running and that you have specified the correct namespace (-n flag).
davsclaus:/Users/davsclaus/Documents/workspace/client/$ minishift status
Running
```

If I do an `oc login` and then afterwards the `minishift service` command works for opening the web console.

I wonder if minishift can report something about expired login, or even allow to login?

**Comment by hferentschik** [comment]
I guess it could at least provide a better message.

**Comment by jorgemoralespou** [comment]
@hferentschik I would probably think that the best way is to include a minishift serviceaccount in the cluster, that will never expire and use that service account when interacting with minishift. This will avoid these kind of issues, where the tool interacts with the openshift cluster in it.

As a regular user you will always use "oc" command line and will need to log in explicitly. As a "plus" option, one could provide a minishift login that would just ask for username and password as the cluster identity would be the one of the one active cluster. Avoiding the need of the "oc login" to know which cluster needs to connect. This minishift login command would update the KUBECONFIG file accordingly. (Just a thought)

**Comment by hferentschik** [comment]
> I would probably think that the best way is to include a minishift serviceaccount in the cluster, that will never expire and use that service account when interacting with minishift. This will avoid these kind of issues, where the tool interacts with the openshift cluster in it.

+1 Interesting idea. For the cases where minishift has to interact with the cluster, this sounds like a good idea.

> As a "plus" option, one could provide a minishift login that would just ask for username and password

hmm, not sure about this one. Maybe

**Comment by praveenkumar** [comment]
This is already fixed now since we are now making copy of kubeconfig and run all oc command using it which doesn't require any oc session info.

```
$ ./minishift openshift service list
|-----------|-----------------|----------|------------------------------------------------------|--------|
| NAMESPACE |      NAME       | NODEPORT |                      ROUTE-URL                       | WEIGHT |
|-----------|-----------------|----------|------------------------------------------------------|--------|
| default   | kubernetes      |          |                                                      |        |
|           | router          |          |                                                      |        |
|           | docker-registry |          | http://docker-registry-default.192.168.42.198.nip.io |        |
|-----------|-----------------|----------|------------------------------------------------------|--------|

[prkumar@dhcp193-13 bin]$ oc logout
Logged "developer" out on "https://192.168.42.198:8443"

[prkumar@dhcp193-13 bin]$ ./minishift openshift service list
|-----------|-----------------|----------|------------------------------------------------------|--------|
| NAMESPACE |      NAME       | NODEPORT |                      ROUTE-URL                       | WEIGHT |
|-----------|-----------------|----------|------------------------------------------------------|--------|
| default   | kubernetes      |          |                                                      |        |
|           | router          |          |                                                      |        |
|           | docker-registry |          | http://docker-registry-default.192.168.42.198.nip.io |        |
|-----------|-----------------|----------|------------------------------------------------------|--------|
````

Closing this now.
