### ISSUE TITLE
Introduce an addon command "echo"

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#749]
It will be helpful for printing meaningful messages to the console when an addon executes.

**Comment by hferentschik** [comment]
_echo_ or _print_?

**Comment by LalatenduMohanty** [comment]
@hferentschik If we want to keep it simple and stupid I would suggest echo as it will just echo the string from the addon file.

**Comment by LalatenduMohanty** [comment]
@jorgemoralespou Any suggestion?

**Comment by budhrg** [comment]
Closed via https://github.com/minishift/minishift/issues/766.
