### ISSUE TITLE
Unable to start minishift in Windows 7

### ISSUE THREAD

**Issue by stour** [minishift/minishift#755]
I'm working on Windows 7 with VirtualBox 5.1.18, Minishift version is:
```
$ minishift version
Minishift version: 1.0.0-rc.1
```

I'm not able to get the minishift VM starting properly.  
When executing command `minishift start --vm-driver=virtualbox -v 5 --show-libmachine-logs` I'm getting following error:
```
(minishift) DBG | VBoxManage.exe: error: The virtual machine 'minishift' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'd:\Profiles\stournie\.minishift\machines\minishift\minishift\Logs\VBoxHardening.log'
(minishift) DBG | VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine
(minishift) DBG | }
```

Here are the complete trace and log files:
[`minishift start`](https://gist.githubusercontent.com/stour/305e4506ff21c16c9c859c028103d2c5/raw/b691441ca82df16ea238fc0ec4450ebf760fb462/log)  
[VBoxHardening.log](https://gist.githubusercontent.com/stour/17ec77f0c19aa1aeaf54d522d50e4a10/raw/fd82d793b35466234cc311154dbe4796684f106f/VBoxHardening.log)
[VBox.log](https://gist.githubusercontent.com/stour/70f2d0df9842f259116879bc109c2410/raw/d1465a00e64886d6c8711b9639fed40dbd7510e9/VBox.log)

I tried executing the same command in a console as administrator but I get the same.

**Comment by LalatenduMohanty** [comment]
@stour Can you please try Virtualbox 5.1.12 as prior version Virtualbox seems to have an issue with Minishift as mentioned in the documentation [1] .

[1] https://docs.openshift.org/latest/minishift/getting-started/installing.html

**Comment by stour** [comment]
Yes I read this information in Minishift documentation. That's why I upgraded to latest Virtualbox version which is 5.1.18. Is it better to downgrade to 5.1.12 ?

**Comment by LalatenduMohanty** [comment]
@stour  sorry, I thought you are using an older version. My bad. You should be fine with 5.1.18.

**Comment by LalatenduMohanty** [comment]
@stour Can you please check if your Virtualbox installation is working fine? Are you able to boot any other ISO with Virtualbox?

**Comment by stour** [comment]
@LalatenduMohanty I just tested and directly in Virtualbox I'm able to boot any ISO including minishift.

So I start minishift in Virtualbox then in command line in run `minishift start --vm-driver=virtualbox` but it hangs. I get `Starting local OpenShift cluster using 'virtualbox' hypervisor...` and nothing more.

**Comment by praveenkumar** [comment]
@stour lot of folks actually reported these issue with libmachine which `docker-machine` uses and best way is to clean up minishift and then try again.  To clean up first run `minishift delete` and then remove `.minishift` folder which should be under `C:\Users\<your_username>\.minishift` hope that will fix.

From Virtualbox logs it seems you also faced same issue.
```
0:00:48.679402 supR3HardenedErrorV: supR3HardenedScreenImage/LdrLoadDll: cached rc=VERR_LDRVI_UNSUPPORTED_ARCH fImage=1 fProtect=0x0 fAccess=0x0 cHits=3 \Device\HarddiskVolume1\Windows\System32\LavasoftTcpService64.dll
00:00:48.679581 supR3HardenedErrorV: supR3HardenedMonitor_LdrLoadDll: rejecting 'C:\WINDOWS\system32\LavasoftTcpService64.dll' (C:\WINDOWS\system32\LavasoftTcpService64.dll): rcNt=0xc0000190
00:00:48.680556 supR3HardenedErrorV: supR3HardenedScreenImage/LdrLoadDll: cached rc=VERR_LDRVI_UNSUPPORTED_ARCH fImage=1 fProtect=0x0 fAccess=0x0 cHits=4 \Device\HarddiskVolume1\Windows\System32\LavasoftTcpService64.dll
00:00:48.680712 supR3HardenedErrorV: supR3HardenedMonitor_LdrLoadDll: rejecting 'C:\WINDOWS\system32\LavasoftTcpService64.dll' (C:\WINDOWS\system32\LavasoftTcpService64.dll): rcNt=0xc0000190
00:00:48.700811 VMMDev: Guest Log: 00:00:05.012623 vminfo   Error: Unable to connect to system D-Bus (2/3): D-Bus not installed
```

- https://github.com/docker/toolbox/issues/585
- https://github.com/docker/toolbox/issues/229
- https://superuser.com/questions/996785/docker-toolbox-error-creating-machine-error-in-driver-during-machine-creation

**Comment by praveenkumar** [comment]
@stour you got any workaround for issue or still same? I am closing it right now if still same then will reopen.
