### ISSUE TITLE
Add new command 'openshift registry'

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#758]
We need to add a command which provides the host+port information for login and use of the OpenShift registry.

    $ minishift openshift registry
    172.30.1.1:5000

We can also add a _login_ flag or subcommand:

    $ minishift openshift registry --login
   
This print and executes the docker login command. This way he user does not have to retrieve the login token. We can handle this transparently. Obviously we need to check whether the _docker_ binary is available and if not return an appropriate errors message.

**Comment by LalatenduMohanty** [comment]
@hferentschik couple of things.  If we are adding a sub command then it can not depend on the registry addon which going to expose the  route. So in this case we need to do the required for exposing the registry in the command itself. 

Also I am not sure how to retrieve the registry information i.e. `172.30.1.1:5000` other than hard coding it.

**Comment by hferentschik** [comment]
>  couple of things. If we are adding a sub command then it can not depend on the registry addon which going to expose the route. 

What do you mean with "depend".  The command does not have to know whether the add-on ran or not. We can dynamically check whether the route is exposed or not. If so it can print the route host+port, otherwise the internal host and port. We can fully abstract the user from all the issues around the routes. See also  https://github.com/minishift/minishift/pull/704#issuecomment-293925484.

> Also I am not sure how to retrieve the registry information i.e. 172.30.1.1:5000 other than hard coding it.

https://github.com/minishift/minishift/pull/704#issuecomment-293925484

     $ oc --as system:admin get -o "jsonpath={.spec.clusterIP}:{.spec.ports[*].port}" service/docker-registry -n default

We know that the docker-registry service exists. Using _oc_ we can query it and extract what we want. We can also use _oc_ to check whether the route exist. If so, we can use it's details.

**Comment by LalatenduMohanty** [comment]
> #704 (comment)
> 
>  $ oc --as system:admin get -o "jsonpath={.spec.clusterIP}:{.spec.ports[*].port}" service/docker-registry -n default

Right, this will be helpful.

**Comment by hferentschik** [comment]
Merged via pull request #767
