### ISSUE TITLE
Discuss usage of tags for code blocks and other things which contributes to look and feel of the published documentation

### ISSUE THREAD

**Issue by Preeticp** [minishift/minishift#768]
Follow up issue for the discussion we had in https://github.com/minishift/minishift/pull/743#discussion_r111150458
We should discuss about tags we should use , other things which contributes to look and feel of the published documentation and then update https://github.com/minishift/minishift/blob/master/docs/source/developing/writing-docs.adoc accordingly.

**Comment by thatdocslady** [comment]
I think this discussion is more than just one tag, it's a general process/workflow about conventions, styles, and standards. This tag is only one example of several issues that came up, and we should reach an agreement as to how we manage and implement conventions while keeping a transparent decision process as a team.

**Comment by Preeticp** [comment]
Discussion started with [listing.console] tags for code blocks. I also see changes to inline commands for example, `minishift start` is now [`minishift start`]. So this issue can be used to list the conventions we want to follow, discuss the whys and hows and once agreed on, this will be documented as part of #618 .

**Comment by hferentschik** [comment]
I think we can close this. Discussions have started in context of issue #618 and resp. pull request #836
