### ISSUE TITLE
Error in deploying second app when first one is successfully deployed

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#770]
I have checked this with four combinations ```php nodejs``` ```python nodejs```  ```php python``` and  ```perl ruby```. In all the cases the second template deployment failed. 

Enviornment : 
```
os : fedora 23
Minishift : MiniShift-1.0.0-rc.1
iso image : centos v1.0.0-rc.4
vm-driver : kvm
```
Steps to reproduce : 
```
1. Download minishift v1.0.0-rc.1
2. Then execute the command "minishift start --iso-url https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.4/minishift-centos7.iso"
3. Open web console and deploy any template (ruby, perl or python) and wait till successfully deployed (Don't delete this)
4. Start deploying any second template. 
5. Deployment will fail.
```

**Comment by LalatenduMohanty** [comment]
@amitkrout Can you please let us know which templates (exact names) you tried to execute?

**Comment by amitkrout** [comment]
@LalatenduMohanty i used these templates through web console 
 ```1st template              2nd template
      PHP 7.0                   nodejs 4
      Python 3.5               nodejs 4
      PHP 7.0                   Python 3.5
      Perl 5.24                  Ruby 2.3
```

**Comment by gbraad** [comment]
tried to reproduce on Minishift 1.0.0, but have now deployed 5 applications and do not experience this issue. Are you deploying a project with specifying a source repository (with runtime), or really deploying a template which includes PV for something like a database?

**Comment by gbraad** [comment]
@LalatenduMohanty I'd rather close this report... if it occurs again, please re-open or file a new issue.
