### ISSUE TITLE
Integration test for persistence volumes failing intermittently 

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#774]
Integration test for persistence volumes [1]  failing intermittently , mostly because of a timing issue. As the directories for the PV are being created in the background and needs some time to complete. 

[1] https://github.com/minishift/minishift/blob/master/test/integration/features/basic.feature#L47-L54

**Comment by LalatenduMohanty** [comment]
@gbraad @hferentschik any suggestion for how we can retry the failed command after a small sleep. 
i.e.
Execute command -> if failed -> sleep 10 seconds -> retry.

**Comment by hferentschik** [comment]
@LalatenduMohanty I am already working on a patch...

**Comment by hferentschik** [comment]
Merged via pull request #773

**Comment by LalatenduMohanty** [comment]
The test is still failing intermittently. Refer https://github.com/minishift/minishift/pull/800.  May be we need to increase  retry steps with little more sleep in between.

**Comment by budhrg** [comment]
The feature file says `retrying 5 times with wait period of 3 seconds` which is 15 secs.

IMO, it is too small .

I think increasing this to 1/2 minutes will have better chance of passing test. 
Anyhow, the command will pass as soon as it succeeds.

**Comment by hferentschik** [comment]
> I think increasing this to 1/2 minutes will have better chance of passing test.

If this is re-appearing, the issue might not even be due to timeouts. We might need to have another look. 

> Anyhow, the command will pass as soon as it succeeds.

There is also a time expectation here. You would expect OpenShift to be ready almost immediately after startup finishes.

**Comment by hferentschik** [comment]
Let's not reopen issues which were part of a release. In this case we should open new issues.
