### ISSUE TITLE
oc command execution should make use of OcRunner

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#777]
_OcRunner_ provides additional abstraction for running _oc_ commands. We should use it for all _oc_ needs. This is for example not the case in _registry_ and _service_ sub-commands of _openshift_ command.

To make the experience smooth we need to add another helper to _OcRunner_.

**Comment by anjannath** [comment]
@hferentschik I need help/more context around this issue.

**Comment by hferentschik** [comment]
I think we can actually close this issue. The last time I looked there were reasons why in some cases no OcRunner was used. The negative aspects of using OcRunner would outweigh the shared used. 

I think one part was that semantically OcRunner works a bit different than calling _oc_ directly. 

We can check once more the code for usages of plain _oc_, but from my part I am fine with closing this issue.

**Comment by LalatenduMohanty** [comment]
Closing this issue as it is not planned to be fixed.
