### ISSUE TITLE
Minishift setup error, CLI failure, Fedora 24 + KVM

### ISSUE THREAD

**Issue by jberkus** [minishift/minishift#781]
Platform: Fedora 24, KVM.
Minishift 1.0, OpenShift 1.5.0rc2

I got the following error at the end of minishift installation:

```
E0407 11:53:31.520005    9621 start.go:205] Error creating Minishift kubeconfig Error reading config file /home/josh/.minishift/machines/minishift_kubeconfig
```

This error did not affect starting minishift, nor did it break the Web UI.  However, it appears to be related to breakage of using the minishift commands on the command line:

```
[josh@redhat bin]$ minishift openshift service nodejs-ex -n myproject
Namespace myproject doesn't exits
[josh@redhat bin]$ minishift openshift service nodejs-ex
Namespace default doesn't exits
```

Note that, according to the Web UI, both myproject and default namespaces do exist.

Possibly relevant to this is that I've tested several releases of minikube on the same laptop previously.

**Comment by praveenkumar** [comment]
> Minishift 1.0, OpenShift 1.5.0rc2

You mean minishift-1.0-rc.1 right or you compiled it by yourself from master?

**Comment by LalatenduMohanty** [comment]
@jberkus I fell might be some issue with your setup. May be it is conflicting it with your earlier minishift installations. Can you please uninstall Minishift [1] and start from fresh.



[1] https://docs.openshift.org/latest/minishift/getting-started/installing.html#uninstall-instructions

**Comment by hferentschik** [comment]
@jberkus - do you have an update on this? Do you still have issues or can we close this issue?

**Comment by jberkus** [comment]
Because of the earlier failure, "minishift delete" errored.  So I uninstalled by removing the .minishift and .kube directories per the docs.

Re-install included this error:

```
E0425 11:54:01.316739   18985 start.go:164] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: [Code-9] [Domain-20] operation failed: domain 'minishift' already exists with uuid 53a78577-f6f1-446f-b304-64b708e8962c. Retrying.
```

This seems likely to be because of the failed "delete".    Install also required me to type in my sudo password 4 separate times; is that normal?

However, the original error did not repeat in this issue did not repeat.

Hypothesis: the original error was caused by a pre-existing .kube directory, placed there by minikube.  We should add a FAQ item, and then close this.

**Comment by hferentschik** [comment]
This looks very much like this error - https://docs.openshift.org/latest/minishift/using/troubleshooting.html#domain-minishift-already-exists

Basically you got into an inconsistent state and even so you ran _minishift delete_, there are still VM state defined in KVM. Can you follow the steps outline in the linked troubleshooting item and see whether it resolves your issue?

**Comment by jberkus** [comment]
Well, I have a working system despite that error.

**Comment by hferentschik** [comment]
Ok, closing the issue in this case.
