### ISSUE TITLE
Documentation about how users can upgrade Minishift

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#783]
We should add documentation about how users can upgrade minishift to a new release when they are running an older version. 

Need to come up with the steps, it might me trivial but will confirm after my testing.

**Comment by hferentschik** [comment]
Given that we have a pull request for #72 almost ready, I recommend to not do anything specific for now. Once the pull request is merged, the upgrade path is 'minishift update'. Documentation should come via the pull request.

**Comment by budhrg** [comment]
Agree :+1:

**Comment by hferentschik** [comment]
Merged via pull request #930
