### ISSUE TITLE
Create release job on CentOS CI

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#786]
The whole release process should be automated and releases should be happening on the CI server.

Outlining the tasks to perform here:

- [x] Investigate on triggering the CI build with URL passing custom parameters
- [x] Create a job in minishift-ci-jobs repo to handle release job
- [x] Add changes to `centos_ci.sh` to perform release operations including `make release`
- [x] Create the changelog for GitHub release page
- [x] Add changes to `centos_ci.sh` to trigger the docs build.
- [ ] Add new target to trigger the release job
- [ ] Send notifications to minibot (by sending some JSON payload to a specified URL).

**Comment by gbraad** [comment]
it should be possible to trigger the release from the command line, pretty much like is done for the documentation. as this is the only guarantee that the release is cleanly built and had an integration run on at least one platform.

**Comment by hferentschik** [comment]
> it should be possible to trigger the release from the command line

+1, in fact it should be the only option.

**Comment by hferentschik** [comment]
Apart of the obvious (building the artefacts) and placing them on the GitHub release page (basically `make release`), the job should also:

* Create the changelog for the GitHub Release page
* Trigger the docs build
* Create pull request for brew (optional)

**Comment by budhrg** [comment]
Outlining the tasks to perform here:

- [ ] Investigate on triggering the CI build with URL passing custom parameters
- [ ] Create a job in minishift-ci-jobs repo to handle release job
- [ ] Add changes to `centos_ci.sh` to perform release operations including `make release`
- [ ] Create the changelog for GitHub release page
- [ ] Add changes to `centos_ci.sh` to trigger the docs build.

**Comment by hferentschik** [comment]
sounds good for a start :-)

**Comment by budhrg** [comment]
@hferentschik , any idea what kind of custom parameters we need to pass to job?

I believe, `commit_id` is one. Tag might not since tag will be created as part of make release. 
Even, not sure with branch where need to create separate branch then.

**Comment by LalatenduMohanty** [comment]
We need to take in to account that which github profile we will use to do the  the release. For example if I do the release I have to pass my GH_TOKEN. Others might say that we can use `minishift-team` profile to do the release. I am ok with either of this.

**Comment by budhrg** [comment]
> We need to take in to account that which github profile we will use to do the the release. For example if I do the release I have to pass my GH_TOKEN. Others might say that we can use minishift-team profile to do the release. I am ok with either of this.

Right now, I am continuing with my GH_TOKEN which is currently in use. I will migrate the ownership t o 'minishift-team' profile after this issue into separate one. 
Right now, don't want to break the working CI at a time where I can go leave anytime ;)

**Comment by hferentschik** [comment]
> I believe, commit_id is one.

Why? The release is on top of master, right? Which commit sha would you pass? 

> Tag might not since tag will be created as part of make release.

But how would the release job know which tag to use? So yes, that is the part you need to pass. Or more precisely you pass the version you want to release, aka v.1.3.0.
This is enough for updating the version in the Makefile, create the release commit, do the release, ...

On top of this we need to pass the GitHub milestone ID for this release. Even though we could derive this from the version as well.

> Even, not sure with branch where then we need to create separate branch.

Release if of master, right?

**Comment by hferentschik** [comment]
>  I will migrate the ownership t o 'minishift-team' profile

+1 for using minishift-team 

>  after this issue with creating a separate issue for that purpose.

-1, I think at the moment we start using this script, it should use the proper setup. So I consider setting this part up part of this issue.

**Comment by budhrg** [comment]
>  Investigate on triggering the CI build with URL passing custom parameters

Done. Triggered job https://ci.centos.org/job/minishift-test-job/2/console through URL with parameters via command line.

**Comment by hferentschik** [comment]
merged via pull request #1109
