### ISSUE TITLE
Docs build upload is creating unwanted directories

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#789]
It seems the upload of _minishift-adoc.tar_ into the latest directory does not work as expected. There are directories created recursively - http://artifacts.ci.centos.org/minishift/minishift/docs/latest/latest/latest/latest/latest/latest/latest/

Also there are by now plenty of unwanted artefacts in http://artifacts.ci.centos.org/minishift/minishift/docs

* latest-alpha 
* latest-released	 
* minishift-adoc.tar

Let's clean this up, including the _latest_ directory which should only contain the latest _minishift-adoc.tar_.

**Comment by hferentschik** [comment]
We should be able to get this sorted, but creating locally the directory and file structure we want and then rsyncing to the server using the --delete flag, deleting files on the server which are not local.

**Comment by budhrg** [comment]
Manually I have fixed the http://artifacts.ci.centos.org/minishift/minishift/docs/ directory content.

I will fix the script as well.

**Comment by hferentschik** [comment]
> Manually I have fixed the http://artifacts.ci.centos.org/minishift/minishift/docs/ directory content.

+1

> I will fix the script as well.

+1

**Comment by hferentschik** [comment]
Merged via pull request #803
