### ISSUE TITLE
Sync the order of links in 'Getting Started' page

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#799]
![order](https://cloud.githubusercontent.com/assets/1132451/25273330/f77d5776-26a8-11e7-8fbd-1541c99ea3d6.png)

IMO, it is : 
- Installing 
- Quickstart (has link to Machine driver installation)
- Machine driver installation

WDYT @LalatenduMohanty @Preeticp @thatdocslady

**Comment by LalatenduMohanty** [comment]
Logically it should be 
1. Minishift Quickstart (because it is quickstart) 
2. Installing Docker Machine drivers (As this is required for Minishift installation)
3. Installing Minishift

Lets wait for others opinion on this too.

**Comment by budhrg** [comment]
> 3. Installing Minishift

At least, I cannot think installation being the last part here. How, can I do `minishift start` if I don't have the binary.

**Comment by LalatenduMohanty** [comment]
> At least, I cannot think installation being the last part here. How, can I do minishift start if I don't have the binary.

But if you don't have the driver then you can not start Minishift.  The tricky thing is we not need drivers for all the hypervisors.

**Comment by LalatenduMohanty** [comment]
This is a duplicate for #691

**Comment by LalatenduMohanty** [comment]
Looks like the sequence has been discussed and the sequence agreed is

1. Installation of Minishift
2. Quick start (as it need Minishift installation)
3. Installation of docker-machine drivers
