### ISSUE TITLE
Wrong path for .minishift folder when I am behind proxy

### ISSUE THREAD

**Issue by GolanTrevize10** [minishift/minishift#801]
Hi, I managed to install and start minishift (although I had to do id with direct connection to internet because it doesn't work behind a proxy). However after starting minishift I connected to my company's network again and I tried to run minishift console but I get this error

```
E0421 15:29:34.170657   26352 console.go:68] Cannot access the OpenShift console
. Verify that Minishift is running. Error:  Error getting config for native Go S
SH: open H:\.minishift\machines\minishift\id_rsa: The system cannot find the fil
e specified.
```
 Similar error if I run minishift stop. It looks like minishift is trying to look for my .minishift folder in the wrong place. If I run it with direct internet connection then it works. I'm using minishift 1.0.0rc1 and virtualbox 5.1.18 in Windows 7

**Comment by hferentschik** [comment]
>  I managed to install and start minishift (although I had to do id with direct connection to internet because it doesn't work behind a proxy)

For the very first start you will need an internet connection, since it need to download the ISO and _oc_. This is issue #718. This should indeed be fixed. Once you have these things in your cache, you should also be able to start Minishfift behind the proxy. 

> however after starting minishift I connected to my company's network again and I tried to run minishift console but I get this error

This one is odd. I don't think the issues are related. What is your usual home directory on the computer and does it change when you connect to the company network?

**Comment by GolanTrevize10** [comment]
Home directory is the same. How minishift gets the home directory?

**Comment by hferentschik** [comment]
> How minishift gets the home directory?

https://github.com/minishift/minishift/blob/6de4350215611e999a92d6da2571a5bd938c2e4d/pkg/util/homedir.go#L25-L25

**Comment by GolanTrevize10** [comment]
Thanks, I checked it and it looks like my HOMEDRIVE and HOMEPATH variable it is pointing to H:, that it is a network drive. That is why when I am not connected to my company network it stops working. Is there any way to override the home directory?

**Comment by praveenkumar** [comment]
> Is there any way to override the home directory?

Using `MINISHIFT_HOME` environment variable check https://docs.openshift.org/latest/minishift/using/managing-minishift.html#environment-variables

**Comment by hferentschik** [comment]
> Thanks, I checked it and it looks like my HOMEDRIVE and HOMEPATH variable it is pointing to H

Yeah, in some corporate environments, when connecting to the network other customisations take place. As @praveenkumar is pointing out, the best option is probably to use _MINISHIFT_HOME_. 
Please let us know whether this resolves your issue. 

Otherwise I suggest we close this issue.

**Comment by GolanTrevize10** [comment]
Thanks, with MINISHIFT_HOME it works

**Comment by hferentschik** [comment]
Awesome, thanks.
