### ISSUE TITLE
Cannot pull docker images from local unsecured docker registry.

### ISSUE THREAD

**Issue by bnanda** [minishift/minishift#804]
Hi All,

I am new to OpenShift/minishift and I have issues in pulling dockerimages from my local unsecured docker registry. I am running docker and minishift on Mac OS Sierra and my minishift is started using virtualbox provider.

**$ minishift version**
_Minishift version: 1.0.0-rc.2_

**Steps to reproduce:**

1. Install native docker on Mac and start docker.
**$ docker version**
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true

2. Run Docker Registry:
**$ docker run -d -p 5000:5000 --restart always --name registry registry:2**
_833ee9ef191f2717fcf3e2c54b66d52d0bc9969e42ef602b1f9547fd173c986c_

3. Tag an application dockerimage.
**$ docker tag bwce/apps:HTTPServerSample IP:5000/bwce/apps:HTTPServerSample**

4. Push the docker image to Local Docker Registry.
**$ docker push IP:5000/bwce/apps:HTTPServerSample**
_The push refers to a repository [IP:5000/bwce/apps]
1e6a6e570444: Pushed
4b7434a454e1: Pushed
02b7376b5729: Pushed
5d6cbe0dbcf9: Pushed
HTTPServerSample: digest: sha256:97d8592fa72da26648b9fc922f56d39efb76cc168191da047e460d91a396bc34 size: 1162_

5. Start minishift.
**$ minishift start --vm-driver virtualbox --insecure-registry IP:5000 --insecure-registry 172.30.0.0/16**
_****
-- Server Information ...
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.99.103:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
****_

6. Login to the minishift webconsole and create a new project. Click on "Add to Project" button. go to "Deploy Image" tab and select "Image Name" option. Enter the name as IP:5000/bwce/apps:HTTPServerSample.

7. Click on the browse button. You'll see the following error message:
 Could not load image metadata.
Internal error occurred: Get https://IP:5000/v2/: http: server gave HTTP response to HTTPS client

It looks like even after using the --insecure-registry option for minishift startup, it is still trying to connect to my unsecured local docker repo via https.

I logged in to the minishift VM via ssh and checked the contents of /var/lib/boot2docker/profile file. I can see that my my docker repo has been added as an insecure registry.

$ minishift ssh
Boot2Docker version 1.12.3, build HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
Docker version 1.12.3, build 6b644ec
docker@minishift:~$ cat /var/lib/boot2docker/profile
EXTRA_ARGS='
--label provider=virtualbox
--insecure-registry IP:5000
--insecure-registry 172.30.0.0/16

'
CACERT=/var/lib/boot2docker/ca.pem
DOCKER_HOST='-H tcp://0.0.0.0:2376'
DOCKER_STORAGE=aufs
DOCKER_TLS=auto
SERVERKEY=/var/lib/boot2docker/server-key.pem
SERVERCERT=/var/lib/boot2docker/server.pem

I do not have any clue on how to make this work at this point of time. Can someone please help?

**Comment by hferentschik** [comment]
What do you really want to achieve? Why do you run a separate registry. If you just need a registry to push the image to for use with OpenShift, have a look at https://docs.openshift.org/latest/minishift/using/accessing-the-openshift-docker-registry.html

You can re-use the Docker daemon as of Minishift as well as the OpenShift registry. If you do that, you can push any images into Minishift's Docker daemon and from there into the OpenShift registry. Then you can create an app from these images.

Would that solve your use-case?

**Comment by bnanda** [comment]
Hello @hferentschik,

Thanks for your kind reply. Yes, I can push the application successfully from the command line when I use the minishift docker daemon. That'll solve my use-case.

Thanks,
Biswajit
