### ISSUE TITLE
Update OpenShift origin to 1.5.0

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#805]
OpenShift origin has released its 1.5.0 version https://github.com/openshift/origin/releases/tag/v1.5.0.

It's better to update to this version.

**Comment by budhrg** [comment]
Significate routing issue reported for 1.5 
- https://github.com/openshift/origin/issues/13862

I believe let's wait for some time to see if 1.5 build is stable enough for minishift or not.

**Comment by hferentschik** [comment]
Hmm, I did not see the comment until late. Right now I already merged pull request #807. Not sure whether it makes sense to downgrade again. Tricky. 1.5.0 would be nice and it fixes several bugs as well.
