### ISSUE TITLE
Introduce --short flag to minishift openshift version 

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#806]
The motivation behind the `--short` flag is to only get the current openshift version number. 
Currently, `minishift openshift version` shows: 
```
$ minishift openshift version
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
etcd 3.1.0
```

Expecting as : 
```
$ minishift openshift version --short
1.5.0-rc.0
```
This can be used in the quick start guide as : 
```
$ export PATH=~/.minishift/cache/oc/v$(minishift openshift version --short):$PATH
```
I can see this will come handy.

**Comment by praveenkumar** [comment]
@budhrg since we are already evaluating that `oc` binary path as part of #142 then why we need it this `short` option? Also from user point of view `--short` will not make much sense because it will not provide other details like which base k8s version openshift using.

**Comment by budhrg** [comment]
> since we are already evaluating that oc binary path as part of #142

That's path and not version. 
Also, the openshift version is giving too much details like etcd, kubernetes then openshift itself. 
```
$ minishift openshift version
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
etcd 3.1.0
```

**Comment by hferentschik** [comment]
> This can be used in the quick start guide as :

Well, this really will be obsolete with the _oc-env_ command, right?

Personally, I am not a big fan of adding a flag to the version command. Then I would be more inclined to per default only display the OpenShift version only.

Also, what you are suggesting is more than just a "short" version, you are also modifying the OpenShift version, since you want to remove the sha part.

**Comment by praveenkumar** [comment]
@budhrg if you are agree with us can please close it?

**Comment by budhrg** [comment]
Closing this as it is not needed now and served by other commands.

**Comment by hferentschik** [comment]
+1
