### ISSUE TITLE
Fix the layout of Getting Started page served locally

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#808]
Fix : 
- Unwanted square boxes
- Sync the order with Overview page

![layout](https://cloud.githubusercontent.com/assets/1132451/25311113/87b29546-2815-11e7-8e57-ad99bb3fe2ee.png)

**Comment by hferentschik** [comment]
I think we really should look at #721 here. Even though the order in the index files is of course maintained manually. 

Not sure what you mean with "square boxes"

**Comment by budhrg** [comment]
> Not sure what you mean with "square boxes"

Check the left most red marked box.

Seems this PR #810 is fixing it.

**Comment by hferentschik** [comment]
> Check the left most red marked box.

That's because the title "Installing Docker Machine Drivers" wraps. IMO that's expected.

**Comment by budhrg** [comment]
> IMO that's expected.

No, it is fixed by your PR now.

**Comment by hferentschik** [comment]
Fair enough

**Comment by budhrg** [comment]
Fixed via https://github.com/minishift/minishift/pull/810
