### ISSUE TITLE
Set explicit version for jteeuwen/go-bindata

### ISSUE THREAD

**Issue by marcindulak** [minishift/minishift#814]
I'm parsing glide.yaml in order to retrieve the url to github tarballs, but there is no "3.0" release of 
https://github.com/jteeuwen/go-bindata/releases - please use e.g. the latest "3.0.7"

This is the line in glide.yaml
https://github.com/minishift/minishift/blob/fd33efc0d76e3f21f170ea113c42f42135c9a374/glide.yaml#L47

**Comment by hferentschik** [comment]
Merged via pull request #894

**Comment by hferentschik** [comment]
> I'm parsing glide.yaml in order to retrieve the url to github tarball

As I mentioned before, one needs to parse glide.lock for what you are trying to do

> but there is no "3.0" release of
https://github.com/jteeuwen/go-bindata/releases - please use e.g. the latest "3.0.7"

It is not version 3.0 which was specified, but rather ~3.0, which is a version range, ranging from 3.0.0 to 3.1.0

**Comment by hferentschik** [comment]
For now we set a fixed version of 3.0.7
