### ISSUE TITLE
Extending go-dog execute step with 'succeed'

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#820]
We are having a lot of tests of the form:

    When executing "oc config current-context"
    Then stderr should be empty
     And exitcode should equal 0
     And stdout should contain
    """
    minishift
    """"

There is a lot of reception and the feature file gets unnecessarily long. 

We should introduce something like:

    When executing "oc config current-context" succeeds 
    Then stdout should contain
    """
    minishift
    """"

The 'succeeds' parameter in the step, will ensure that internally the command has an exit code of 0 and no output to standard out. This way we can reduce a lot of repetition in the feature file.

**Comment by budhrg** [comment]
> The 'succeeds' parameter in the step, will ensure that internally the command has an exit code of 0 and no output to standard out. This way we can reduce a lot of repetition in the feature file.

:+1:   Good one , we did something similar for service-manager 
`When I successfully run <cmd>`

https://github.com/projectatomic/vagrant-service-manager/blob/master/features/cdk-openshift.feature#L29

**Comment by hferentschik** [comment]
> Good one , we did something similar for service-manager

exactly

**Comment by hferentschik** [comment]
Merged via pull request #864
