### ISSUE TITLE
Error: containers cannot communicate with the OpenShift master

### ISSUE THREAD

**Issue by sriram18981** [minishift/minishift#825]
Environment:
OS: macOS Sierra v 10.12.4
Hardware : MacBook Pro (Retina, 15-inch, Mid 2015)
Processor 2.2 Ghz Inter core i7
Memory 16GB 1600 MHz DDR3

---
Docker : Community Edition 17.03.1-ce-mac5
$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

---
minishift start not working, failing with docker networking issues

---
$ oc version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://192.168.64.2:8443
openshift v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4

---

$ minishift start
Starting local OpenShift cluster using 'xhyve' hypervisor...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... 
   Deleted existing OpenShift container
-- Checking for openshift/origin:v1.5.0-rc.0 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.64.2 as the server IP
-- Starting OpenShift container ... 
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Checking container networking ... FAIL
   Error: containers cannot communicate with the OpenShift master
   Details:
     The cluster was started. However, the container networking test failed.
   Solution:
     Ensure that access to ports tcp/8443 and udp/53 is allowed on 192.168.64.2.
     You may need to open these ports on your machine's firewall.
   Caused By:
     Error: Docker run error rc=1
     Details:
       Image: openshift/origin:v1.5.0-rc.0
       Entrypoint: [/bin/bash]
       Command: [-c echo 'Testing connectivity to master API' && curl -s -S -k https://192.168.64.2:8443 && echo 'Testing connectivity to master DNS server' && for i in {1..10}; do    if curl -s -S -k https://kubernetes.default.svc.cluster.local; then       exit 0;   fi;    sleep 1; done; exit 1]
       Output:
         Testing connectivity to master API
         {
           "paths": [
             "/api",
             "/api/v1",
             "/apis",
             "/apis/apps",
             "/apis/apps/v1beta1",
             "/apis/authentication.k8s.io",
             "/apis/authentication.k8s.io/v1beta1",
             "/apis/autoscaling",
             "/apis/autoscaling/v1",
             "/apis/batch",
             "/apis/batch/v1",
             "/apis/batch/v2alpha1",
             "/apis/certificates.k8s.io",
             "/apis/certificates.k8s.io/v1alpha1",
             "/apis/extensions",
             "/apis/extensions/v1beta1",
             "/apis/policy",
             "/apis/policy/v1beta1",
             "/apis/storage.k8s.io",
             "/apis/storage.k8s.io/v1beta1",
             "/controllers",
             "/healthz",
             "/healthz/ping",
             "/healthz/poststarthook/bootstrap-controller",
             "/healthz/poststarthook/extensions/third-party-resources",
             "/healthz/ready",
             "/metrics",
             "/oapi",
             "/oapi/v1",
             "/osapi",
             "/swaggerapi/",
             "/version",
             "/version/openshift"
           ]
         }Testing connectivity to master DNS server
       Error Output:
         curl: (6) Could not resolve host: kubernetes.default.svc.cluster.local; Unknown error
         curl: (6) Could not resolve host: kubernetes.default.svc.cluster.local; Unknown error
         curl: (6) Could not resolve host: kubernetes.default.svc.cluster.local; Unknown error
         curl: (6) Could not resolve host: kubernetes.default.svc.cluster.local; Unknown error
         curl: (6) Could not resolve host: kubernetes.default.svc.cluster.local; Unknown error
         curl: (6) Could not resolve host: kubernetes.default.svc.cluster.local; Unknown error
         curl: (6) Could not resolve host: kubernetes.default.svc.cluster.local; Unknown error
         curl: (6) Could not resolve host: kubernetes.default.svc.cluster.local; Unknown error
         curl: (6) Could not resolve host: kubernetes.default.svc.cluster.local; Unknown error
         curl: (6) Could not resolve host: kubernetes.default.svc.cluster.local; Unknown error

Error starting the cluster.

**Comment by amitkrout** [comment]
@sriram18981 Unable to reproduce it. 
```
$ docker version
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
```
$ oc version
oc v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://192.168.64.2:8443
openshift v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4
dhcp-0-176:v1.0.0-rc.2 amit$
```
```
System Version: macOS 10.12.3 (16D32)
Kernel Version: Darwin 16.4.0
Processor Name : Intel Core i7
Processor Speed : 2.2 Ghz
```
>-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Checking container networking ... FAIL

I my case here it waits for some time probably 30 sec then went forward without any error.

**Comment by praveenkumar** [comment]
@sriram18981 Can you scan your port without running minishift first if already running then do `minishift delete`. If you are already consuming those port than you might face issue.

`$ sudo lsof -iTCP -sTCP:LISTEN -n -P`

**Comment by sriram18981** [comment]
@praveenkumar thanks a lot!! I did `minishift delete` and tried to start again. This time it worked. 
```
$ minishift delete
Deleting the Minishift VM...
Minishift VM deleted.
```

```
$ minishift start
Starting local OpenShift cluster using 'xhyve' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
 40.00 MB / 40.00 MB [===============================================================================================================] 100.00% 0s
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.0-rc.0 image ... 
   Pulling image openshift/origin:v1.5.0-rc.0
   Pulled 0/3 layers, 3% complete
   Pulled 0/3 layers, 59% complete
   Pulled 1/3 layers, 79% complete
   Pulled 2/3 layers, 93% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.64.2 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Checking container networking ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.64.2:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

```
