### ISSUE TITLE
Update docker-machine dependency to latest released

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#826]
Currently we are consuming `0.9.0` version which is quite older and `0.11.0` is what right now latest and have quite of fixes/enhancement from driver and provisioner side. This is not going to be just a version change in the glide.yaml but also we need to work around our provisioner to make sure to use systemd drop-in files instead of over-writing the system units which changed during `0.10.0` release of docker machine code.

**Comment by hferentschik** [comment]
Merged via pull request #969
