### ISSUE TITLE
minishift uses lowercase jwalterweatherman while the upsteam name is jWalterWeatherman

### ISSUE THREAD

**Issue by marcindulak** [minishift/minishift#827]
The package is called https://github.com/spf13/jWalterWeatherman and this is how Fedora packages it:

    $ cat /etc/redhat-release 
    Fedora release 25 (Twenty Five)
    $ rpm -q --provides golang-github-spf13-jWalterWeatherman-devel
    golang(github.com/spf13/jWalterWeatherman) = 0-0.4.git3d60171.fc25
    golang-github-spf13-jWalterWeatherman-devel = 0-0.4.git3d60171.fc25

minishift refers to the packages all in lowercase.

**Comment by LalatenduMohanty** [comment]
@marcindulak minishift i.e. glide.yaml does not have a dependency on  github.com/spf13/jWalterWeatherman. Not sure how you got it.  I am working on the packaging on https://github.com/LalatenduMohanty/minishift-rpm-centos7/tree/minishift-rpm-fedora25 and planning to send you a PR once it is ready.

**Comment by marcindulak** [comment]
@LalatenduMohanty - it looks I got jwalterweatherman (lower-case) from https://github.com/minishift/minishift/blob/ebcc3ee84489a71a710a54890c646a38b48f6dcf/glide.lock#L134

**Comment by hferentschik** [comment]
jwalterweatherman is a transitive dependency to Viper. See https://github.com/spf13/viper/blob/master/util.go#L28. As seen in the import, lowercase is used. Even though URL should be treated case sensitive, it often does not matter (as in this case, try accessing the URL all lower cased). Also remember that on some operating systems (OS X for example), there would be no difference either. 

So for all I can tell, jwalterweatherman is needed atm and Glide does the right thing to detect and record the dependency.

**Comment by marcindulak** [comment]
Fedora (Rawhide, 27) provides now jWalterWeatherman as lowercase https://bugzilla.redhat.com/show_bug.cgi?id=1427336
