### ISSUE TITLE
Set fixed versions for all dependencies

### ISSUE THREAD

**Issue by marcindulak** [minishift/minishift#828]
This is in relation to https://github.com/marcindulak/minishift-rpm-centos7
I'm not sure whether the title of the ticket is appropriate.

When packaging minishift  https://github.com/minishift/minishift/tree/cebec68fcf03ae5b5a9c0b808178b542c17215a7 as RPM I took the following approach:

1. since it should be possible to use any version of an unversioned go package as a dependency I parse minishift's glide.yaml to extract all versioned dependencies.

2. I follow the standard way of packaging RPMS by adding the dependencies extracted above as additional Source's.

Then, on Fedora 25, I'm getting from `make`:

```
go-bindata  -prefix /usr/share/gocode/src/github.com/minishift/minishift/addons -o /usr/share/gocode/src/github.com/minishift/minishift/out/bindata/addon_assets.go -pkg bindata /usr/share/gocode/src/github.com/minishift/minishift/addons/...
go install -pkgdir=/usr/share/gocode/src/github.com/minishift/minishift/out/bindata -ldflags="-X github.com/minishift/minishift/pkg/version.version=1.0.0-rc.2 -X github.com/minishift/minishift/pkg/version.isoVersion=v1.0.2 -X github.com/minishift/minishift/pkg/version.openshiftVersion=v1.5.0" ./cmd/minishift
# github.com/minishift/minishift/pkg/minikube/cluster
pkg/minikube/cluster/cluster.go:232: cannot use bar.NewProxyReader(iso) (type *pb.Reader) as type io.ReadCloser in assignment:
        *pb.Reader does not implement io.ReadCloser (missing Close method)
# github.com/minishift/minishift/vendor/github.com/spf13/viper
vendor/github.com/spf13/viper/viper.go:563: undefined: cast.ToInt64
vendor/github.com/spf13/viper/viper.go:605: undefined: cast.ToStringMapStringSlice
# github.com/minishift/minishift/pkg/util/github
pkg/util/github/github.go:101: not enough arguments in call to client.Repositories.GetReleaseByTag
pkg/util/github/github.go:104: not enough arguments in call to client.Repositories.GetLatestRelease
pkg/util/github/github.go:123: not enough arguments in call to client.Repositories.DownloadReleaseAsset
pkg/util/github/github.go:309: not enough arguments in call to client.Repositories.DownloadReleaseAsset

```

I must say that I had to perform some hacks inside of the spec file (to be reported separately).
If the problem is due to the fact that I use the Fedora's RPMS instead of the packages downloaded by  `make vendor`, then the supported versions should be listed in glide.yaml.

In order to package an RPM I need the versions of bundled go packages to list them as additional sources, otherwise I'll use the RPMS packaged already on Fedora.

**Comment by hferentschik** [comment]
> since it should be possible to use any version of an unversioned go package as a dependency I parse minishift's glide.yaml to extract all versioned dependencies.

The aim is to have fixed versions for all dependencies, but that is work in progress. Also for some dependencies one needs to set a sha as version. It is not true, however, that you can use any version in this case. The versions are very much resolved. That's the glide.lock file. The lock file locks each dependency to a specific version. It is not the glide.yaml file you should be looking at, but the lock file. 

Also by looking at _glide.yaml_ you will not get all transitive dependencies either. If you want to re=produce the build at a given time, you need to process _glide.lock_ not _glide.yaml_.

**Comment by budhrg** [comment]
> pkg/util/github/github.go:101: not enough arguments in call to client.Repositories.GetReleaseByTag
pkg/util/github/github.go:104: not enough arguments in call to client.Repositories.GetLatestRelease
pkg/util/github/github.go:123: not enough arguments in call to client.Repositories.DownloadReleaseAsset
pkg/util/github/github.go:309: not enough arguments in call to client.Repositories.DownloadReleaseAsset

This error is due to change in API of [`google/go-github`](https://github.com/google/go-github) in latest sha. Note that there is release tag here.

**Comment by budhrg** [comment]
@marcindulak , We have now pinned the `go-github` package to sha id . See 
https://github.com/minishift/minishift/blob/master/glide.yaml#L27-L28
```
- package: github.com/google/go-github
  version: 30a21ee1a3839fb4a408efe331f226b73faac379
```

Also, it has been quite a while for this issue. Could you retest this and let us know its status?

**Comment by marcindulak** [comment]
With minishift 1.4.1, go-github 30a21ee1a3839fb4a408efe331f226b73faac379 does not result in any errors, however it looks like it's tarball is no longer directly available https://github.com/google/go-github/issues/705

Any plans for making minishift compatible with the latest go-github?

**Comment by hferentschik** [comment]
I don't understand why you say Minishift is not compatible with go-github. We use it right? Golang does not work with released versions of dependencies. Golang uses vendors dependencies and then compiles everything into a static library. So even if you set a tag or version as dependency, it does not download a binary or similar, but it checks out the source and sets the repo to the specified tag or sha. @marcindulak, so what is your actual issue?

**Comment by marcindulak** [comment]
Not compatible with the latest go-github. The https://github.com/google/go-github/commit/30a21ee1a3839fb4a408efe331f226b73faac379 hash (from February 2017) works with minishift as you said.

This is an old ticket, from the time when we were trying to package minishift as RPM.
Since then I think the conclusion was that without bundling all vendor dependencies inside of the minishift repo (like https://github.com/kubernetes/kompose/tree/master/vendor does) RPM of minishift is not maintainable.
