### ISSUE TITLE
Makefile does not handle multiple paths in GOPATH

### ISSUE THREAD

**Issue by marcindulak** [minishift/minishift#829]
```
cat /etc/redhat-release 
Fedora release 25 (Twenty Five)

mkdir -p /tmp/work/{bin,pkg,src}
export GOPATH=/tmp/work
export PATH=$PATH:$GOPATH/bin
cd $GOPATH/src
wget https://github.com/minishift/minishift/archive/v1.0.0-rc.2.tar.gz
tar zxf v1.0.0-rc.2.tar.gz
mkdir -p github.com/minishift/minishift
mv minishift-1.0.0-rc.2/* github.com/minishift/minishift
cd github.com/minishift/minishift
sudo su - -c 'yum -y install "compiler(go-compiler)"'
export GOPATH=/tmp/work:/usr/share/gocode/

go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/work:/usr/share/gocode/"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build037411541=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

go version
go version go1.7.5 linux/amd64

make vendor
Makefile:56: *** target pattern contains no '%'.  Stop.
```

GOPATH is used in Makefile for both path to go packages and the path to the directory structure used for building the minishift binary.

**Comment by marcindulak** [comment]
Relevant for https://github.com/minishift/minishift/issues/828

**Comment by LalatenduMohanty** [comment]
@marcindulak  Can you please check your out put of `$ go env` . I need to cross check if I can reproduce this.

**Comment by marcindulak** [comment]
I have reproduced the problem also with 99bf360b038693fd1ffd50fcb3e0b03738f6152d
On the other hand if one uses the go packages fetched by `make vendor` exclusively, then multiple paths in GOPATH is not an issue. The problem is only if one tries to debundle the vendor packages.

**Comment by hferentschik** [comment]
This is not only a problem for the _vendor_ target, but for other targets as well. For example, the default or clean target. Changing this would require a fair bit of effort.
