### ISSUE TITLE
Provide a way to skip downloading and installing of go-bindata in the Makefile

### ISSUE THREAD

**Issue by marcindulak** [minishift/minishift#830]
go-bindata is available e.g., as RPM on Fedora and deb on latest Debian/Ubuntu.

**Comment by LalatenduMohanty** [comment]
@marcindulak  We do that in the `Makefile` so that a contributor can compile Minishift in any operating systems without any OS specific dependency (think about Windows and OS X)

**Comment by LalatenduMohanty** [comment]
I do not think we can do anything from Minishift project point of view here.

**Comment by marcindulak** [comment]
Wouldn't something like this work on all platforms?

```
--- Makefile.orig       2017-04-26 20:46:52.185291492 +0000
+++ Makefile    2017-04-26 20:50:35.137210958 +0000
@@ -31,6 +31,11 @@
 GODOG_OPTS ?= ""
 PACKAGES := go list ./... | grep -v /vendor
 SOURCE_DIRS = cmd pkg test
+ifeq ($(GO_BINDATA),)
+       GO_BINDATA_PATH := $(GOPATH)/bin/go-bindata
+else
+       GO_BINDATA_PATH := $(GO_BINDATA)
+endif
 
 # Linker flags
 VERSION_VARIABLES := -X $(REPOPATH)/pkg/version.version=$(MINISHIFT_VERSION) \
@@ -59,7 +64,7 @@
 vendor:
        glide install -v
 
-$(ADDON_ASSET_FILE): $(GOPATH)/bin/go-bindata vendor
+$(ADDON_ASSET_FILE): $(GO_BINDATA_PATH) vendor
        @mkdir -p $(ADDON_BINDATA_DIR)
        go-bindata $(GO_BINDATA_DEBUG) -prefix $(ADDON_ASSETS) -o $(ADDON_ASSET_FILE) -pkg bindata $(ADDON_ASSETS)/...
```
and on Linux: `GO_BINDATA=/usr/bin/go-bindata make`

**Comment by praveenkumar** [comment]
@marcindulak @LalatenduMohanty why don't we can add patch from RPM side. I am sure that this is not the best way but for time being we can do and see if we can fix here later. This shouldn't be blocker from RPM side.
