### ISSUE TITLE
Minishift+xhyve on OS X needs Virtualbox to be installed

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#831]
I installed minishift on a new machine using brew:

Something along the lines of
```
$ brew install minishift
$ brew install --HEAD xhyve
$ brew install docker-machine-driver-xhyve
$ sudo chown ...
```

But when starting `minishift` I get the following errors:

```
macbook:~ gbraad$ minishift start --vm-driver=xhyve
Starting local OpenShift cluster using 'xhyve' hypervisor...
E0427 10:20:40.377876    4438 start.go:171] Error starting the VM: Error creating the VM. Error with pre-create check: "Error detecting VBox version: exit status 126". Retrying.
E0427 10:20:42.412816    4438 start.go:171] Error starting the VM: Error creating the VM. Error with pre-create check: "Error detecting VBox version: exit status 126". Retrying.
E0427 10:20:44.447666    4438 start.go:171] Error starting the VM: Error creating the VM. Error with pre-create check: "Error detecting VBox version: exit status 126". Retrying.
Error starting the VM:  Error creating the VM. Error with pre-create check: "Error detecting VBox version: exit status 126"
Error creating the VM. Error with pre-create check: "Error detecting VBox version: exit status 126"
Error creating the VM. Error with pre-create check: "Error detecting VBox version: exit status 126"
```

After installing  VirtualBox, these errors disappear:
```
macbook:~ gbraad$ minishift start --vm-driver=xhyve
Starting local OpenShift cluster using 'xhyve' hypervisor...
Downloading OpenShift binary 'oc' version 'v1.5.0-rc.0'
...
```

**Comment by gbraad** [comment]
@budhrg I think you noticed the same?

**Comment by praveenkumar** [comment]
@gbraad Can you verify same with docker-machine? So we just to be sure if something from our side is messy or coming from our dependencies.

**Comment by gbraad** [comment]
It might have been due to previous usage of the operating system... 
unable to reproduce after using the official `VirtualBox_Uninstall.tool` to remove vbox.

Currently, `docker-machine create --driver xhyve test` created a machine as expected

**Comment by gbraad** [comment]
Not sure if this should be part of the troubleshooting guide. /cc: @hferentschik @LalatenduMohanty @budhrg WDYT?

**Comment by hferentschik** [comment]
For what it's worth, the _pre-create_ checks are part of the libmachine to driver communication. This happens when a driver is selected and started. Not sure how how a VirtualBox pre-create check could have occurred without virtual box driver being selected. Odd.

**Comment by gbraad** [comment]
It is an issue in how docker-machine/libmachine works. Since VirtualBox is installed as a yellow package, it is not obvious how to uninstall it and this can therefore happen to someone else. It is worth to report this for libmachine... troubleshooting or not?

**Comment by Wicht1** [comment]
I have this Problem without having vBox installed.

Maybe I did it years ago and forget about it. So I will try the deinstallation routine from vBox again. But when I search my Mac I can't find any files related to vBox.

**Comment by gbraad** [comment]
You did not uninstall virtualbox using the provided uninstaller from the
VirtualBox disk image.
Please download a recent version and perform the uninstall.

Note: it will try to start VBoxManage as it finds some left over commands.
This is something that needs to be fixed my docker/machine, but didn't have
the time yet.

**Comment by Wicht1** [comment]
I will try! 

And yes, I did not install vBox (as far as I know) but I can install it and remove it after that. When this will fix the problem I make a post here.

**Comment by Wicht1** [comment]
Ok, i did not install, but run the VirtualBox.Uninstall.tool. That fixed the Error!

But it still does not work :( 

`fuckup:~ jonathaninnig$ minishift start
Starting local OpenShift cluster using 'xhyve' hypervisor...
E0731 21:40:59.235526   10199 start.go:282] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: Could not convert the UUID to MAC address: exit status 1. Retrying.
E0731 21:43:00.747769   10199 start.go:282] Error starting the VM: Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting. Retrying.

E0731 21:45:02.280110   10199 start.go:282] Error starting the VM: Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: Could not convert the UUID to MAC address: exit status 1
Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting
Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting
`

**Comment by Wicht1** [comment]
Ok, i did not install, but run the VirtualBox.Uninstall.tool. That fixed the Error!

But it still does not work :(

> fuckup:~ USERNAME$ minishift start
> Starting local OpenShift cluster using 'xhyve' hypervisor...
> E0731 21:40:59.235526 10199 start.go:282] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: Could not convert the UUID to MAC address: exit status 1. Retrying.
> E0731 21:43:00.747769 10199 start.go:282] Error starting the VM: Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting. Retrying.
> 
> E0731 21:45:02.280110 10199 start.go:282] Error starting the VM: Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting. Retrying.
> Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: Could not convert the UUID to MAC address: exit status 1
> Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting
> Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting

**Comment by gbraad** [comment]
>  Could not convert the UUID to MAC address

This is an issue with xhyve. it is best to remove our Minishift machines
directory, reboot the machine and try again. This can happen due to an
inconsistent state.

$ rm -rf ~/.minishift/machines

If further errors, please file new issues, as these reports are now
unrelated to the original (closed) report

**Comment by HazCod** [comment]
I am having the same issue, why was this closed?

**Comment by gbraad** [comment]
You need to uninstall VirtualBox

**Comment by gbraad** [comment]
https://github.com/minishift/minishift/issues/831#issuecomment-319040583

**Comment by gbraad** [comment]
From a discussion on IRC:

You might NEED virtualbox as you did not properly uninstall it. This is a known issue (see previous comments)

Use the DMG and use the removal script in the root of that disk image
most people just remove the `/Applications` entry for virtualbox
but this leaves stuff around that got installed with the yellow package
Then the driver thinks you still have virtualbox (as it detects some components)

You want the driver to detect `ver=""` here:

https://github.com/machine-drivers/docker-machine-driver-xhyve/blob/58f598617475ed98f8c344bc6ea73ad8f6738805/xhyve/xhyve.go#L410-L413

https://github.com/machine-drivers/docker-machine-driver-xhyve/blob/58f598617475ed98f8c344bc6ea73ad8f6738805/xhyve/utils.go#L139-L148

unfortunately, it looks for the VboxManage command, but when NOT uninstalled, this is left around

**Comment by HazCod** [comment]
Update: I removed Virtualbox via `brew`, which triggered this issue. Using the uninstaller from the DMG seems to fix it!
