### ISSUE TITLE
host-only-cidr option is not working except the default value of specific host addresses

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#845]
Enviornment : 
```
os : OS X, win7
hypervisor : virtualbox
Minishift rc2, cdk 3.0 rc1
```
Steps to reproduce : 
```
1. Use minishift rc2 binary
2. Set vm driver to virtualbox
minishift config set vm-driver virtualbox
3. Run the command "minishift start --host-only-cidr 192.168.99.10/24"

$ minishift start --host-only-cidr 192.168.99.10/24
Starting local OpenShift cluster using 'virtualbox' hypervisor...
E0428 13:46:29.802695   12000 start.go:171] Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: connect: no route to host
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.
. Retrying.
-- Checking OpenShift client ... OK
-- Checking Docker client ... FAIL
   Error: cannot communicate with Docker
   Solution:

     To create a new Docker machine to run OpenShift, run this command again with
     the --create-machine argument. This will create a Docker machine named
     'openshift'.

     To use a different machine name, specify the --machine-name=NAME argument.

     If you wish to use an existing Docker machine, enable it before running this
     command by executing:

        eval $(docker-machine env NAME)

     where NAME is the name of your Docker machine.

   Caused By:
     Error: Get https://192.168.99.100:2376/_ping: dial tcp 192.168.99.100:2376: connect: host is down
Error starting the cluster.
```

**Comment by hferentschik** [comment]
I don't think you are supposed to use '192.168.99.10/24', in particular .10. You should use something like 'minishift start --host-only-cidr 192.168.99.1/24' which works fine. 

Check also the docker-machine docs https://docs.docker.com/machine/drivers/virtualbox/#usage

I case you think that you can set the IP explicitly to 192.168.99.10, that's not the case. The IP will be still dynamic in the range of 192.168.99.100 to 192.168.99.254.

**Comment by praveenkumar** [comment]
@amitkrout Can you verify what @hferentschik told and let us know if that also causing issue for you. We also get same kind of issue from another person when tried to use specific cidr.

**Comment by amitkrout** [comment]
@praveenkumar will check it now

**Comment by amitkrout** [comment]
>
I don't think you are supposed to use '192.168.99.10/24', in particular .10. You should use something like 'minishift start --host-only-cidr 192.168.99.1/24' which works fine.

@praveenkumar minishift start with ```--host-only-cidir 192.168.99.1/24``` works fine. 

>
I guess you think that you can set the IP explicitly to 192.168.99.10, that's not the case. The IP will be still dynamic in the range of 192.168.99.100 to 192.168.99.254.

Yes. form the doc [https://docs.openshift.org/latest/minishift/command-ref/minishift_start.html](url) when i see ```--host-only-cidr string   The CIDR to be used for the minishift VM. (Only supported with VirtualBox driver.) (default "192.168.99.1/24")```, then my first thing comes to my mind is instead of the default value i can use other ip explicitly. 

>
Check also the docker-machine docs https://docs.docker.com/machine/drivers/virtualbox/#usage

Agree that the CIDR of ```192.168.24.10/24``` not valid use case. It should be like ```192.168.99.1/24```

**Comment by hferentschik** [comment]
@amitkrout, so can we close this issue in this case?

**Comment by amitkrout** [comment]
@hferentschik ahh..i forgot to close this. Closing it now :)
