### ISSUE TITLE
Add reference to minishift-centos-iso in Minishift documentation

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#849]
We have not mentioned about minishift=centos ISO in Minishift documentation. We need documentation which will communicate user that apart form the default minishift -b2d ISO user has choice to run minishift with CentOS ISO.  We should also mention that CentOS ISO is of higher size as compared to minishift-b2d but it is an enterprise GNU/Linux distribution where as boot2docker is not. 

[1] https://github.com/minishift/minishift-centos-iso/

**Comment by hferentschik** [comment]
Merged via pull request #973
