### ISSUE TITLE
Question: Why the ROADMAP same as that of minikube?

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#85]
Hi,

I found that the roadmap of minishift is exactly same as minkube. 
Isn't it the roadmap of minishift should/will be different that minikube?

Although, I understand minishift is being build on top of minikube but the goal is obviously different IMO which might make the roadmap different too.

Let me know if I am missing anything here.

Thanks.

**Comment by jimmidyson** [comment]
No you're not missing anything, it's just laziness on my part - this is a minikube fork & as the sole part-time maintainer of minishift I've not found time to tidy up docs, roadmap, etc.

All help is appreciated :)

**Comment by budhrg** [comment]
@jimmidyson also I was looking for you in the irc :smile: but couldn't find you. What is your nick name?

**Comment by jimmidyson** [comment]
jdyson on freenode, not on VPN currently.

**Comment by thatdocslady** [comment]
This file is considered for deletion as a part of #138, if a minishift roadmap doc is needed we can create it but there's no point IMO to keep the minikube file.

**Comment by thatdocslady** [comment]
The file was deleted as a part of PR #165, recommend to close this issue as resolved.
