### ISSUE TITLE
Edit the doc strings for newly added commands

### ISSUE THREAD

**Issue by thatdocslady** [minishift/minishift#850]
Since the first round of doc string edits, some new commands were added to minishift and therefore need to be reviewed. For example minishift openshift, addon-apply, update.

**Comment by thatdocslady** [comment]
@hferentschik I can see a few new commands that haven't gone thru a doc string edit yet (i.e. update, addon-apply, etc). Should I rephrase this issue to cover all new commands, or is it better to handle each command set in a separate issue?

**Comment by hferentschik** [comment]
Please all in one :-)

**Comment by hferentschik** [comment]
Merged via pull request #1088
