### ISSUE TITLE
minishift not compatible with version of windows

### ISSUE THREAD

**Issue by umar86** [minishift/minishift#851]
v1.0.0-rc.2
Windows 10

    C:\Users\Umar>minishift start
    This version of C:\Users\Umar\Documents\minishift-1.0.0-rc.2-windows-amd64\minishift.exe is not
    compatible with the version of Windows you're running. Check your computer's system information
    and then contact the software publisher.

**Comment by hferentschik** [comment]
Any chance you are running a 32bit version of Windows 10?

**Comment by umar86** [comment]
yes.

**Comment by umar86** [comment]
oops. thats the problem.
