### ISSUE TITLE
Fix links in documentations

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#854]
Found few outdated links
- [Uninstalling Minishift -> persistent configuration](https://github.com/minishift/minishift/blob/master/docs/source/getting-started/installing.adoc#uninstalling-minishift) still using minishift.io
- [Quick start -> Note on cmd ref](https://github.com/minishift/minishift/blob/master/docs/source/getting-started/quickstart.adoc#starting-minishift) still using minishift.io
- [Persistent configuration -> Note on `minishift config`](https://github.com/minishift/minishift/blob/master/docs/source/using/managing-minishift.adoc#persistent-configuration) is broken
- [Using -> Deleting host folder -> hostfolder delete link](https://github.com/minishift/minishift/blob/master/docs/source/using/host-folders.adoc#deleting-host-folders) is broken
- [Interacting with Openshift -> Using the OpenShift client binary (oc)](https://github.com/minishift/minishift/blob/master/docs/source/using/interacting-with-openshift.adoc#using-the-openshift-client-binary-oc) uses closed issue #142.
- [Interacting with Openshift -> Persistent Volumes](https://github.com/minishift/minishift/blob/master/docs/source/using/interacting-with-openshift.adoc#persistent-volumes) has typo on `persistent` on 2nd line. Also used closed issue. I doubt we are missing some documentation on out of box persistent volume here.
- [Developing -> Deploying minishift doc](https://github.com/minishift/minishift/blob/master/docs/source/developing/writing-docs.adoc#deploying-minishift-documentation) has broken link for docs.openshift.org.

**Comment by budhrg** [comment]
@hferentschik We need to fix these issues and push before next sync.

**Comment by thatdocslady** [comment]
@budhrg this issue will be handled as a part of #691, I will go through the doc set and clean up all the links.

**Comment by hferentschik** [comment]
Merged via pull request #855
