### ISSUE TITLE
Document the more value of minishift

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#86]
Hi,

I think it would be valuable to have a document which explains what 'minishift' great features is and what are the limitations it has as oppose to OpenShift.

Few of the features and limitations are listed in [`README#features`](https://github.com/jimmidyson/minishift#features) and [`README#known-issues`](https://github.com/jimmidyson/minishift#known-issues) respectively.

Thanks

**Comment by hferentschik** [comment]
@budhrg Are you still missing something in the current docs? Can you be a bit more specific on where and what you would like to add?

**Comment by praveenkumar** [comment]
@budhrg I think now we have most of stuff in place, do you still think some info missing?

**Comment by hferentschik** [comment]
I feel the same way. Not sure what we add specifically for this issue right now.

**Comment by budhrg** [comment]
> I think now we have most of stuff in place, do you still think some info missing?

Agree, we have come a long way :+1:  Closing now.
