### ISSUE TITLE
Create add-on to provision Fabric8

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#860]

**Comment by praveenkumar** [comment]
@hferentschik so what we need here, templates and images streams?

**Comment by hferentschik** [comment]
A bit of both.

@jstrachan, we have been talking at some stage about you guys trying to create a YAML file with image streams, templates, etc to bootstrap Fabric8 onto OpenShift. Did you make any progress on this?

**Comment by rawlingsj** [comment]
@hferentschik we're close to getting this sorted, hopefully by next week we might be in a position to try this.

**Comment by jstrachan** [comment]
One challenge is after the template is run as 'developer' we need to switch to 'system:admin' to create an 'OAuthClient' using the newly created Route host name as it's required for KeyCloak. 

Am sure we can figure something out; it's just not gonna just be one static Template.

**Comment by hferentschik** [comment]
@rawlingsj Let's sync next week. Happy to help to get this sorted or look into what's missing to get this to work.

**Comment by hferentschik** [comment]
Closing this issue in favour of #1034
