### ISSUE TITLE
Add a "Further Reading" page

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#861]

**Comment by budhrg** [comment]
@hferentschik , could you add bit more details what is expected from this page?

**Comment by budhrg** [comment]
@hferentschik , Could you update the description of the issue?

**Comment by gbraad** [comment]
Not sure what this is about... further reading as in: "Check OpenShift documentation and trainings", to link to http://learn.openshift.com ?

**Comment by praveenkumar** [comment]
Not sure what @hferentschik had in the mind when created this issue. we can add katacoda or other online resources. I am also happy to close this and then create a new one if we know what should be added on that front.

**Comment by budhrg** [comment]
+1 for closing.

**Comment by gbraad** [comment]
We can point to something from the docs, but a page? Besides, this is more
something related to OpenShift... If they have a resource, refer to it
instead. It is not something we can/should maintain directly... Unless we
can use it as a test case for ourselves before releasing?

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by budhrg** [comment]
@LalatenduMohanty @gbraad Further reading can be included as part minishift tutorial https://github.com/minishift/minishift/issues/2064

I am in favor of closing it.

**Comment by agajdosi** [comment]
The issue has been closed after 184 days of inactivity.
