### ISSUE TITLE
Getting error while executing minishift start command in windows cmd in Windows 7

### ISSUE THREAD

**Issue by sauravbond** [minishift/minishift#863]
Hi I am new in Minishift and I have downloaded the latest relase if minishift which have minishift.exe file. I have executed below command minishift start. But I am getting error in creating vm. Please help me here to get me out from this issue.

C:\minishift-1.0.0-windows-amd64>minishift start
Starting local OpenShift cluster using 'hyperv' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/downloa
d/v1.0.2/minishift-b2d.iso'
 40.00 MB / 40.00 MB [=============================================] 100.00% 0s
E0506 10:09:26.016491    7120 start.go:171] Error starting the VM: Error creatin
g the VM. Error with pre-create check: "read tcp 127.0.0.1:65460->127.0.0.1:6545
9: wsarecv: An existing connection was forcibly closed by the remote host.". Ret
rying.
E0506 10:09:32.424131    7120 start.go:171] Error starting the VM: Error creatin
g the VM. Error with pre-create check: "read tcp 127.0.0.1:65477->127.0.0.1:6547
6: wsarecv: An existing connection was forcibly closed by the remote host.". Ret
rying.
E0506 10:09:38.692758    7120 start.go:171] Error starting the VM: Error creatin
g the VM. Error with pre-create check: "read tcp 127.0.0.1:65483->127.0.0.1:6548
2: wsarecv: An existing connection was forcibly closed by the remote host.". Ret
rying.
Error starting the VM:  Error creating the VM. Error with pre-create check: "rea
d tcp 127.0.0.1:65460->127.0.0.1:65459: wsarecv: An existing connection was forc
ibly closed by the remote host."
Error creating the VM. Error with pre-create check: "read tcp 127.0.0.1:65477->1
27.0.0.1:65476: wsarecv: An existing connection was forcibly closed by the remot
e host."
Error creating the VM. Error with pre-create check: "read tcp 127.0.0.1:65483->1
27.0.0.1:65482: wsarecv: An existing connection was forcibly closed by the remot
e host."

**Comment by budhrg** [comment]
Did you created any external virtual switch before running `minishift start`?

**Comment by sauravbond** [comment]
I have installed HyperV and enbaled that through control panel but I am not able to create external virtual switch. Can you please share some steps how to do this in Windows7.

**Comment by budhrg** [comment]
@sauravbond ,  check this Video https://www.youtube.com/watch?v=cfauedEoh3E

Make sure you select the network adapter which has network connectivity.

**Comment by budhrg** [comment]
Also we have some Windows 7 issue here as well https://github.com/minishift/minishift/issues/755.

Let us know if you face similar one when.

**Comment by sauravbond** [comment]
Thanks for helping me, but when I opened a HyperV Manager at right side there is option connect to server, I was trying with the localhost but it is saying that HyperV is not installed at localhost, other option is remote host, which IP or host need to give there, sorry for this stupid question.

**Comment by hferentschik** [comment]
AFAIK, you cannot install Hyper-V on Windows 7. You might be install the Hyper-V Manager, but creating actual VM is not possible. On Windows 7 you will need to use VirtualBox. @sauravbond, have you tried this option?

**Comment by sauravbond** [comment]
Yes Hyper-V Manager is installed in my machine. I dont have Virtual box into my machine. I did not tried this. Do I need to install Virtual Box explicitly apart from Hyper-V Manager, then I can use Miniscript. Please correct me if I am wrong

**Comment by hferentschik** [comment]
Yes, you will need to install VirtualBox. 

You cannot run Hyper-V on Windows 7, but just use the manager for remote instances.

**Comment by sauravbond** [comment]
okay one more quesstion, If I install VirtualBox, so in HyperV-Manager there is option of connect server then we can create virtual switch, while cliking on connect server it ask 2 options one for local host and other for remote which option have to go and what details I need to set there.

**Comment by hferentschik** [comment]
You don't have to do anything with Hyper-V. Just ignore it. Download and install VirtualBox and then run:

    $ minishift start --vm-driver virtual box

**Comment by sauravbond** [comment]
thank you so much, I appreciate for this help.

**Comment by budhrg** [comment]
@sauravbond ,

Actual command is `$ minishift start --vm-driver virtualbox` typo in above command.

Please let us know if it is working for you.

**Comment by sauravbond** [comment]
Hi @budhrg ,

I have installed virtual box and after that I have executed above command and getting the error : 
C:\minishift-1.0.0-windows-amd64>minishift start --vm-driver virtualbox
Starting local OpenShift cluster using 'virtualbox' hypervisor...
E0507 13:08:09.239203   13608 start.go:171] Error starting the VM: Error creatin
g the VM. Error creating machine: Error in driver during machine creation: Unabl
e to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm min
ishift --type headless failed:
VBoxManage.exe: error: AMD-V is disabled in the BIOS (or by the host OS) (VERR_S
VM_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap,
 interface IConsole

Details: 00:00:02.639684 Power up failed (vrc=VERR_SVM_DISABLED, rc=E_FAIL (0X80
004005)). Retrying.
E0507 13:08:22.112674   13608 start.go:171] Error starting the VM: Error startin
g stopped host: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxM
anage.exe startvm minishift --type headless failed:
VBoxManage.exe: error: AMD-V is disabled in the BIOS (or by the host OS) (VERR_S
VM_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap,
 interface IConsole

Details: 00:00:02.120673 Power up failed (vrc=VERR_SVM_DISABLED, rc=E_FAIL (0X80
004005)). Retrying.
E0507 13:08:32.138824   13608 start.go:171] Error starting the VM: Error startin
g stopped host: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxM
anage.exe startvm minishift --type headless failed:
VBoxManage.exe: error: AMD-V is disabled in the BIOS (or by the host OS) (VERR_S
VM_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap,
 interface IConsole

Details: 00:00:01.661722 Power up failed (vrc=VERR_SVM_DISABLED, rc=E_FAIL (0X80
004005)). Retrying.
Error starting the VM:  Error creating the VM. Error creating machine: Error in
driver during machine creation: Unable to start the VM: C:\Program Files\Oracle\
VirtualBox\VBoxManage.exe startvm minishift --type headless failed:
VBoxManage.exe: error: AMD-V is disabled in the BIOS (or by the host OS) (VERR_S
VM_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap,
 interface IConsole

Details: 00:00:02.639684 Power up failed (vrc=VERR_SVM_DISABLED, rc=E_FAIL (0X80
004005))
Error starting stopped host: Unable to start the VM: C:\Program Files\Oracle\Vir
tualBox\VBoxManage.exe startvm minishift --type headless failed:
VBoxManage.exe: error: AMD-V is disabled in the BIOS (or by the host OS) (VERR_S
VM_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap,
 interface IConsole

Details: 00:00:02.120673 Power up failed (vrc=VERR_SVM_DISABLED, rc=E_FAIL (0X80
004005))
Error starting stopped host: Unable to start the VM: C:\Program Files\Oracle\Vir
tualBox\VBoxManage.exe startvm minishift --type headless failed:
VBoxManage.exe: error: AMD-V is disabled in the BIOS (or by the host OS) (VERR_S
VM_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap,
 interface IConsole

Details: 00:00:01.661722 Power up failed (vrc=VERR_SVM_DISABLED, rc=E_FAIL (0X80
004005))

**Comment by budhrg** [comment]
@sauravbond , you have not enabled Virtualization in your machine. 

Please enable from BIOS setting. Check https://askubuntu.com/a/118020 .

**Comment by budhrg** [comment]
@sauravbond , you have not enabled Virtualization in your machine. 

Please enable from BIOS setting. Check https://askubuntu.com/a/118020 .

**Comment by gbraad** [comment]
I believe we can close the issue, as the original report was invalid (no hyper-v on Windows 7). For further problems, please open a new issue, or contact us on IRC.

**Comment by Shivaraju1996** [comment]
Hi team,
started learning Openshift by using MInishift, i have installed virtualbox and tried to start minishift by
 minishift start --vm-driver=virtualbox but getting this error 
 
![image](https://user-images.githubusercontent.com/51816701/188536796-9516f70c-f98f-4876-
![image](https://user-images.githubusercontent.com/51816701/188536898-c3def57c-fa67-4fd6-84ac-fc8cb6c5a8f3.png)
89f8-8bfc96273eec.png)
