### ISSUE TITLE
oc-env subcommand should probably not depend on machine status

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#867]
****
Right now `oc-env` sub-command depends on status of VM, however information provided by `oc-env` can be obtained in every state. Question is if there are going to be additions to `oc-env` which will depend on status of VM...

**Actual behaviour:**
```
[agajdosi@dhcp-24-156 ~]$ minishift oc-env
There is currently no 'minishift' VM defined.
```

**Expected behaviour:**
```
[agajdosi@dhcp-24-156 ~]$ minishift oc-env
export PATH="/home/agajdosi/.minishift/cache/oc/v1.5.0:$PATH"
# Run this command to configure your shell: 
# eval $(minishift oc-env)
```

**Comment by hferentschik** [comment]
> Right now oc-env sub-command depends on status of VM, however information provided by oc-env can be obtained in every state.

That's not correct. The Vm does matter. We are aligning _oc_ versions. So If you for example bootstrap 3.6, we you a 3.6 version of _oc_ which should be added to the path. So the VM state does matter.

**Comment by agajdosi** [comment]
@hferentschik Ah, ok. Thank you for information, going to check with code next time. Sorry for mistake.

**Comment by hferentschik** [comment]
No worries at all.
