### ISSUE TITLE
Minishift is not starting even Virtual box installed and Virtualization is enabled  from BIOS

### ISSUE THREAD

**Issue by sauravbond** [minishift/minishift#869]
Hi,

As I had discussed on how to set virtual box to start with browser I got all the help on issue #863 , I did all the process but at last minishift has not been started but when I have seen on virtual box the error which I am getting is "This Kernel requires x86-64 cpu, but only detected i686 cpu. Unable to boot -  Please use a kernel appropriate foryour cpu". I am using Windows7 and I am not sure why this error is coming because virtual box have started, I have enabled Virtualization from BIOS.  I am sending screen shot what I am getting error. Please help me here to sort out this issue.

I have used command to start minishift is : `minishift start --vm-driver virtualbox`
![virtual_box_not_running](https://cloud.githubusercontent.com/assets/19723773/25863132/4006fa52-3508-11e7-8fe6-fa874df1a724.JPG)

**Comment by gbraad** [comment]
Can you answer the following questions?
  * What is the type of CPU in your machine?
  * Is Windows 32 or 64bits?

**Comment by sauravbond** [comment]
Hi @gbraad I have attached screenshot of my system details. Please have a look.

![system_details](https://cloud.githubusercontent.com/assets/19723773/25883209/5cf7ee38-3566-11e7-96a6-e2eaf7267f84.JPG)

**Comment by praveenkumar** [comment]
@sauravbond From your first screen shot looks like it detecting minishift iso as `ubuntu (32 bit)` which is not correct. Which version of virtualbox are you using and did you make any changes in the virtualbox configuration to use 32 bit system as default?

If you google your error you will see a lot of same issue which point to using wrong version of guest OS when starting using virtualbox.

**Comment by sauravbond** [comment]
No I have not changed any thing in virtual box. Latest version of virtual
box I am using. Before using virtual box I have installed hyperV manager, I
was not aware that hyperV don't support in Windows 7. So I had installed
hyperV manager and when I was installing this it was displaying service
pack 1 is updating. So can you guide me what I need to do, how I can get
minishift for Windows not for Linux.

**Comment by sauravbond** [comment]
This issue I have fixed, actually intially when I have installed virtualbox and downloaded minishift, I executed the command "minishift start" which downloaded iso file of bitdocker but didnot download minishift console. so I deleted all files from .minishift and executed command "minishift start --vm-driver virtualbox" then it has downloaded all required files and server started at some given IP which you can see on command prompt. Thanks to all who helped me alot here.
