### ISSUE TITLE
How do I customize values in OpenShift's master config ?

### ISSUE THREAD

**Issue by linux360** [minishift/minishift#871]
The master-config.yaml provided with minishift sets 3 values which conflict with my network.
How can I customize the following values for master-config.yaml?

    servicesSubnet: 172.30.0.0/16
    ingressIPNetworkCIDR: 172.29.0.0/16
    serviceNetworkCIDR: 172.30.0.0/16

Thank you

**Comment by budhrg** [comment]
@linux360 , you would be interested in [`minishift openshift config`](https://docs.openshift.org/latest/minishift/using/interacting-with-openshift.html#update-openshift-config) command.

**Comment by hferentschik** [comment]
So to understand this correct, you are talking about the master configuration of OpenShift as provisioned by Minishift? I am kind of intrigued that these settings you mention should conflict for you, since they are internal to the VM/OpenShift. 

Can you provide some more context?

**Comment by linux360** [comment]
Thank you for the guidance.  I was looking at these pages
https://docs.openshift.org/latest/minishift/command-ref/minishift_config_set.html 
https://docs.openshift.org/latest/minishift/command-ref/minishift_openshift_config.html
which did not give me much to get started.

Starting minishift like this made the changes I was looking for.

minishift openshift config set --patch "{\"kubernetesMasterConfig\": {\"servicesSubnet\": \"10.30.0.0/16\"},\"networkConfig\": {\"serviceNetworkCIDR\": \"10.30.0.0/16\",\"ingressIPNetworkCIDR\": \"10.29.0.0/16\",\"subdomain\": \"192.168.99.101.sandbox.mydomain.com\"}}" --target master

**Comment by hferentschik** [comment]
@linux360 np. The command-ref pages alone are indeed not so helpful. You need to look at the example in the using guide. Glad to hear that it works now. 

Still not quite sure about your use case and network setup. You even seem to have a custom subdomain. How do you make routing work?
