### ISSUE TITLE
How can I set a private registry for use with minishift?

### ISSUE THREAD

**Issue by linux360** [minishift/minishift#872]
Is there a technique to have minishift docker instance use a private registry?
If so, please share how it can be done.

Thank you

**Comment by budhrg** [comment]
Hi @linux360 ,

You can use `--insecure-registry` option in start command. Refer https://docs.openshift.org/latest/minishift/command-ref/minishift_start.html.

or

Interact with integrated docker registry as https://docs.openshift.org/latest/minishift/using/accessing-the-openshift-docker-registry.html

**Comment by hferentschik** [comment]
Crewe talking about a secured or insecure registry here. If it is insecure the '--insecure-registry' should do the trick. If it is secured you will have to jump through some more hoops. Could you provide some more feedback?

**Comment by hferentschik** [comment]
I might be a duplicate of #430

**Comment by budhrg** [comment]
> I might be a duplicate of #430

I also feel the same.

**Comment by linux360** [comment]
I've spent a fair amount of time on this and still cannot get minishift to not use 172.30.1.1 for its registry.
Based on everything I've tried, Any attempt to start minishift without including '--insecure-registry 172.30.0.0/16',
including multiple --insecure-registry options, which match my Origin and OCP clusters, gives a FAIL like this.

-- Checking Docker daemon configuration ... FAIL
   Error: did not detect an --insecure-registry argument on the Docker daemon
   Solution:

     Ensure that the Docker daemon is running with the following argument:
        --insecure-registry 172.30.0.0/16


Why do I need this?
The network my host is connected to uses 172.16.0.0/12 to define the subnets.
As a result it appears that minishift is trying to route to 172.30.1.1 when I do a build.


Pushing image 172.30.1.1:5000/myproject/nodejs-example:latest ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Registry server Address: 
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
error: build error: Failed to push image: Put http://172.30.1.1:5000/v1/repositories/myproject/nodejs-example/: dial tcp 172.30.1.1:5000: getsockopt: connection refused


So, maybe I'm still missing something, but am I just not clear on the technique to have the default minishift registry something other than 172.30.1.1 and in turn get a good minishift start which could also then use my private registry.

I see that 172.30.1.1 is hard coded into these files in the source.

me@mypc ~/dev/minishift/git $ find . -type f -exec grep -l "172.30.1.1" {} \;
./minishift/addons/registry-route/registry-route.addon
./minishift/test/integration/features/basic.feature
./minishift/docs/source/using/addons.adoc
./minishift/cmd/minishift/cmd/start.go
me@mypc ~/dev/minishift/git $


Should I be rebuilding minishfit from source chagning 172.30.1.1 to an IP that works for me or is anyone else aware of another simpler way?


Thank you

**Comment by linux360** [comment]
I've found a bit more info, seems my suspicion on the same network blocks was a red herring.
What I have learned is that when I start minishfit the router and docker-registry deployments both fail starting with this error:

`error: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined`

If I retry the deployment config it works as expected after minishift has fully started, things works as expected.


```
[root@minishift bin]# oc project default
Now using project "default" on server "https://192.168.99.100:8443".
[root@minishift bin]# oc get pods
NAME                            READY     STATUS      RESTARTS   AGE
docker-registry-1-deploy        0/1       Error       0          10m
persistent-volume-setup-njvb6   0/1       Completed   0          10m
persistent-volume-setup-r9f6j   0/1       Error       0          10m
router-1-deploy                 0/1       Error       0          10m
[root@minishift bin]# oc status -v
In project default on server https://192.168.99.100:8443

svc/docker-registry - 172.30.1.1:5000
  dc/docker-registry deploys docker.io/openshift/origin-docker-registry:v1.5.0
    deployment #1 failed 10 minutes ago: config change

svc/kubernetes - 172.30.0.1 ports 443, 53->8053, 53->8053

svc/router - 172.30.36.252 ports 80, 443, 1936
  dc/router deploys docker.io/openshift/origin-haproxy-router:v1.5.0
    deployment #1 failed 10 minutes ago: config change

Info:
  * pod/docker-registry-1-deploy has no liveness probe to verify pods are still running.
    try: oc set probe pod/docker-registry-1-deploy --liveness ...
  * pod/persistent-volume-setup-njvb6 has no liveness probe to verify pods are still running.
    try: oc set probe pod/persistent-volume-setup-njvb6 --liveness ...
  * pod/persistent-volume-setup-r9f6j has no liveness probe to verify pods are still running.
    try: oc set probe pod/persistent-volume-setup-r9f6j --liveness ...
  * pod/router-1-deploy has no liveness probe to verify pods are still running.
    try: oc set probe pod/router-1-deploy --liveness ...
View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
[root@minishift bin]# 

[root@minishift origin]# oc deploy router --retry
Retried #1
Use 'oc logs -f dc/router' to track its progress.
[root@minishift origin]# 

[root@minishift origin]# oc describe svc/router
Name:                   router
Namespace:              default
Labels:                 router=router
Selector:               router=router
Type:                   ClusterIP
IP:                     172.30.52.185
Port:                   80-tcp  80/TCP
Endpoints:              192.168.99.100:80
Port:                   443-tcp 443/TCP
Endpoints:              192.168.99.100:443
Port:                   1936-tcp        1936/TCP
Endpoints:              192.168.99.100:1936
Session Affinity:       None
No events.
[root@minishift origin]#

[root@minishift origin]# oc deploy docker-registry --retry
Retried #1
Use 'oc logs -f dc/docker-registry' to track its progress.
[root@minishift origin]# 

[root@minishift bin]# oc logs -f dc/docker-registry
--> Scaling docker-registry-1 to 1
--> Waiting up to 10m0s for pods in rc docker-registry-1 to become ready
--> Success
[root@minishift origin]#

[root@minishift origin]# oc describe svc/docker-registry
Name:                   docker-registry
Namespace:              default
Labels:                 docker-registry=default
Selector:               docker-registry=default
Type:                   ClusterIP
IP:                     172.30.1.1
Port:                   5000-tcp        5000/TCP
Endpoints:              172.17.0.3:5000
Session Affinity:       ClientIP
No events.
[root@minishift origin]#

```

**Comment by praveenkumar** [comment]
@linux360 Can we close this issue or you have something else here which need our help?

**Comment by fiunchinho** [comment]
Fresh minishift install gave me the same problems as @linux360 . [Doing these steps fixed the issue](https://github.com/minishift/minishift/issues/872#issuecomment-300870649), but I don't think this is the expected behavior.

**Comment by druminik** [comment]
Had the same problem and fix as described by @fiunchinho and @linux360

**Comment by linux360** [comment]
Apologies for the delay, yes this can be closed and thank you for the assistance

**Comment by fiunchinho** [comment]
But I don't think that's the expected behavior. I wouldn't close it

**Comment by mtttcgcg** [comment]
Same issue - can't ping or reach 172.30.1.1 - most likely this range is taken by other things on our network... 
If I pass a different arg to --insecure-registry, like 10.0.0.1/24, it is ignored.

**Comment by jlussagnet** [comment]
@linux360 , isn't that what you were asking for => https://github.com/minishift/minishift/issues/2246

**Comment by farazdurrani** [comment]
For me, providing `minishift start --insecure-registry ip-address` did not resolve the issue.

I did `minishift delete -f` and then `minishift start`. That resolved the issue.
