### ISSUE TITLE
Store the current version of minishift in the config.json

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#877]
We need to store the current version of minishift in some persistate store like config.json 
to be available for easy reference for comparison. 

This is required for checking the update or during the execution of addon during start.

See more here https://github.com/minishift/minishift/issues/639#issuecomment-300410844

**Comment by hferentschik** [comment]
I don't think we need this for now.

**Comment by jorgemoralespou** [comment]
I agree with @budhrg that once profiles get picked up by minishift, it's important to have a reference of what oc/minishift version was used when creating, as the user may end up requiring different oc clients for different profiles. Right now the user can also do "--openshift-version" and this is relevant to diagnose errors, to be able to report both:
minishift and oc versions "at creation" and "current".

**Comment by agajdosi** [comment]
Hi @budhrg, this issue has milestone v1.3.0 and seems it got a little bit forgotten. Is it still valid?

**Comment by budhrg** [comment]
@agajdosi , updated to 1.8.0 to discuss in next sprint.

**Comment by LalatenduMohanty** [comment]
> This is required for checking the update or during the execution of addon during start.

This will be handled in https://github.com/minishift/minishift/issues/1313

**Comment by gbraad** [comment]
Storing the version in a config is not helpful in the sense that the actual executable to install the add-ons knows it's own version. If the value is stored, what does it solve? and how aboiut using a newer client? the value in that case that was stored is irrelevant.

**Comment by budhrg** [comment]
I am closing this as #1313 make sense than this.
