### ISSUE TITLE
addons: openshift config set gives error

### ISSUE THREAD

**Issue by rbaumgar** [minishift/minishift#880]
I have created an addon where I have following line in the my.add

`openshift config set --patch '{"assetConfig": {"metricsPublicURL": "https://hawkular-metrics-openshift-infra.#{ip}.nip.io"}}'`

```
.Error executing addon commands:  Error executing command 'ssh command error:
command : docker exec -t origin /usr/bin/openshift config set --patch '{"assetConfig": {"metricsPublicURL": "https://hawkular-metrics-openshift-infra.192.168.42.54.nip.io"}}'
err     : exit status 1
output  : Error: unknown command "config" for "openshift"
Run 'openshift --help' for usage. ':
```

on the VM I get following response on the --help
```
docker@minishift:~$ docker exec -t origin /usr/bin/openshift --help
OpenShift Application Platform 

The OpenShift distribution of Kubernetes helps you build, deploy, and manage your applications on top of Docker
containers. To start an all-in-one server with the default configuration, run: 

  $ openshift start &

Available Commands:
  admin       Tools for managing a cluster
  cli         Command line tools for managing applications
  completion  Output shell completion code for the given shell (bash or zsh)
  ex          Experimental commands under active development
  help        Help about any command
  kube        Kubernetes cluster management via kubectl
  start       Launch all-in-one server
  version     Display client and server versions
docker@minishift:~$ docker exec -t origin /usr/bin/openshift version
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
etcd 3.1.0
```

from the host it works perfect:
```
$ minishift openshift config set --patch '{"assetConfig": {"metricsPublicURL": "\"https://hawkular-metrics-openshift-infra.192.168.42.222.nip.io\""}}'
Patching OpenShift configuration /var/lib/origin/openshift.local.config/master/master-config.yaml with {"assetConfig": {"metricsPublicURL": "https://hawkular-metrics-openshift-infra.192.168.42.222.nip.io"}}
Restarting OpenShift
```

Any hint?

**Comment by hferentschik** [comment]
> from the host it works perfect:

except, you are executing a Minishift command. 'minishift openshift config set' is a command of the Minishift CLI, there is no ' openshift config set' in the _openshift_ binary. Under the hood, _ex config patch_ is called. See https://github.com/minishift/minishift/blob/1ea9ac59a9dd3a7dc4c02d721cfd29a350e1daac/pkg/minishift/openshift/openshift.go#L109-L109

So if you want to do the patching as part of an add-on, you will need to use 'openshift ex config patch'.

That said, why do you try to set the metric public URL? If you are starting Minishift with metrics enabled ('minishift start --metrics'), this is taken care off.

**Comment by hferentschik** [comment]
Going to close this issue.

**Comment by rbaumgar** [comment]
Thx.

But "ex" stands for "Experimental commands under active development". So it looks like it is only a temporary solution...

Yes, I know that I can install metrics automatically... It was only a value for the test.

**Comment by hferentschik** [comment]
> But "ex" stands for "Experimental commands under active development". So it looks like it is only a temporary solution...

Sure, commands under 'ex' might change or be removed. I don't think this is likely though. From a Minishift we would then potentially  be looking at other ways of doing this. 

> Yes, I know that I can install metrics automatically... It was only a value for the test.

Ok

**Comment by rbaumgar** [comment]
would be nice if minishift and addon syntax would be the same for "config view" and "config set"

**Comment by hferentschik** [comment]
the add-on syntax and the 'openshift config' command are orthogonal to each other. The Minishift _openshift_ command created a group of commands related to OpenShift. There is also _registry_ or _service_. It is a grouping of commands which belong/affect the OpenShift instance, opposed to the Minishift top level commands which mainly deal with live cycle management and configuration of the Minishift VM. 

In the case of add-ons, the supported _openshift_ commands as part of the Minishift add-on DSL, is literally calling the _openshift_ binary in the _origin_ container.
