### ISSUE TITLE
Error starting the VM:  Error getting the state for host: machine does not exist

### ISSUE THREAD

**Issue by elmehdi92** [minishift/minishift#882]
I tried to install minishift on my windows 7 machine, But I cannot use minishift start nor minishift start --vm-driver virtualbox. 

I m having this Error : 

    Error starting the VM:  Error getting the state for host: machine does not exist, it's like my machine does not detect virtualbox ... 

Have you guys any ideas how to solve this  ? 

It worked perfectly on OS X. 

thank you,

**Comment by agajdosi** [comment]
Hi @elmehdi92, there is similar known issue with Minishift and VirtualBox in version < 5.1.12. Can I ask you which version your VirtualBox is?

**Comment by elmehdi92** [comment]
Hello @agajdosi, thank you for your reply. 

Actually I m using the 5.1.22 version. 

Thank you

**Comment by elmehdi92** [comment]
Thanks @agajdosi, it may be a problem on my machine too, I ll be waiting for your return, Thank you

**Comment by agajdosi** [comment]
@elmehdi92 I am not able to reproduce it with VB 5.1.22 and Minishift 1.0.0. Seems like this is more specific problem or misconfiguration in your machine. 

I remember I have seen `[...]machine does not exist` error few times when I crazed Minishift by starting it with wrong --vm-provider and then starting it again with good one, or other strange combinations of starts, stops with different flags. Not sure if this is your case, but what I am trying usually is:

- `minishift delete` - does it delete something, report no machine exists, or does it fail?
- looking at provider, is there VM named "minishift"? If so I am deleting it manualy (usually after minishift delete reports an error while deleting machine)
- deleting ~/.minishift folder

If this does not fix or change the error, then I am out if ideas and probably longer logs via `minishift start --vm-provider virtualbox -v 5 --show-` will help other folks to investigate in this issue.

**Comment by elmehdi92** [comment]
thank you @agajdosi, when I run minishift delete and then retried it worked.

**Comment by agajdosi** [comment]
@elmehdi92 Great, glad to hear that Minishift is working for you now.

**Comment by anumber8** [comment]
Hi everyone,

I've faced the same problem through several minishift versions. Finally I've figured out that the problems is with permissions for the running process on the minishift home. So, change the path for minishift home to a directory where your user has write permissions. run minishift delete command and then start minishift again.

I hope it helps.

**Comment by DimiT** [comment]
Can you describe in detail what should be done? How to change the path of minishift home? I'm running into same problem.

**Comment by DimiT** [comment]
In case if someone will find this question via search then the answer is simple - minishift home can be setted through setting MINISHIFT_HOME environment variable. It helped in my case.

**Comment by anumber8** [comment]
I'm sorry to answer late i was in vacation. I'm glad you managed to fix the problem.

**Comment by snyderdb** [comment]
Thank you for providing the "minishift delete" recommendation!  I had inadvertently deleted a VM and attempted to restart the install process and it failed due to looking for the vm that I had deleted.  Issuing a minishift delte allowed me to restart the install process.  Thank you

**Comment by 62mkv** [comment]
Can this recommendation concerning MINISHIFT_HOME on Windows for non-administrative users be placed here https://docs.okd.io/latest/minishift/getting-started/installing.html or here https://docs.okd.io/latest/minishift/getting-started/installing.html ? That would really help a lot!! Thanks!
