### ISSUE TITLE
Login to registry fails

### ISSUE THREAD

**Issue by sebgoa** [minishift/minishift#884]
Hi, latest minishift release.

 I followed this guide:
https://docs.openshift.org/latest/minishift/using/accessing-the-openshift-docker-registry.html

and when I try to log in the registry it fails:

```
$ docker login -u developer -p $(oc whoami -t) $(minishift openshift registry)
No information found for 'service/docker-registry'
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```

suggestions.

**Comment by praveenkumar** [comment]
@sebgoa looks like you hit this command way too soon and registry container was not running that time. Once you do `minishift start` wait some time till all the OpenShift containers up and running (mostly take 1-2 mins as per your network).  

You can also check if you have registry container up and running by `minishift ssh` and `docker ps` which should list registry container.

**Comment by sebgoa** [comment]
nope, the container has been up and running for 20 minutes, but the basic minishift command does not seem to run:

```
$ minishift openshift registry
No information found for 'service/docker-registry'
```

**Comment by hferentschik** [comment]
Can you try:

    $ docker login -u developer -p $(oc whoami -t) 172.30.1.1:5000

At the moment 'minishift openshift registry' will return the internal registry IP, which is  172.30.1.1
This way you can verify whether the problem is "just" with ' minishift openshift registry' for whether there are problems with the registry in general.

Also, please re-try to see whether this is reproducible at all?

    $ minishift delete 
    $ minishift start <your options>
    $ minishift openshift registry

The latter should return something like:

    172.30.1.1:5000

**Comment by praveenkumar** [comment]
@sebgoa does it works, can you provide an update?

**Comment by sebgoa** [comment]
here it is:

on OSX 10.11.6, I have minishit 1.0.0 and minikube v0.18.0 also installed
SUCCESS, the registry works fine.

on OSX 10.12.4, I have minishift 1.0.0 and minikube v0.18.0 also installed.
FAILURE.

I am going to close the issue though since I got the registry access working.
I do think there is an issue with the `brew cask install minishift` setup on 10.12.4 but I don't have time to give any detailed report.

and I am seeing quite a bit of errors due to the dual install minishit/minikube in both cases.

**Comment by paoloantinori** [comment]
FWIW I have also faced the same issue that went away recreating the cluster

**Comment by 40a** [comment]
+1

**Comment by piomin** [comment]
I've got the same problem for minishift. It has been solved after installation of default addons:
$ minishift addons install --defaults
