### ISSUE TITLE
minishift's glide does not list "make test" dependencies

### ISSUE THREAD

**Issue by marcindulak** [minishift/minishift#895]
This includes for example (list is probably not exhaustive):

```
github.com/Azure/azure-sdk-for-go/arm/storage
github.com/Azure/go-autorest/autorest
github.com/aws/aws-sdk-go/aws
github.com/codegangsta/cli
github.com/digitalocean/godo
github.com/pyr/egoscale/src/egoscale
github.com/rackspace/gophercloud
github.com/skarademir/naturalsort
github.com/vmware/govcloudair
github.com/vmware/govmomi
github.com/xordataexchange/crypt/config
github.com/DATA-DOG/go-txdb
```

**Comment by budhrg** [comment]
@marcindulak , I am not sure, what is expected here?

`make clean test` works fine for us.

**Comment by hferentschik** [comment]
I have not idea where this is coming from, but these are not dependencies of Minishift. The dependencies listed here are SDK libraries for various cloud providers - Azure, digitialocean, rackspace, ...
They are by no means test dependencies of Minishift.

**Comment by marcindulak** [comment]
That's right, these are the dependencies of the dependencies of minishift.
For example github.com/DATA-DOG/go-txdb is needed by github.com/DATA-DOG/godog's tests,
and this is what happens to `make test` when I remove github.com/DATA-DOG/go-txdb:

```
# github.com/minishift/minishift/bundled/godog/examples/db
bundled/godog/examples/db/api_test.go:11:2: cannot find package "github.com/DATA-DOG/go-txdb" in any of:
	/root/rpmbuild/BUILD/minishift-270a4da8a68f96d93895e4aea3534efda868dd15/src/github.com/minishift/minishift/vendor/github.com/DATA-DOG/go-txdb (vendor tree)
	/usr/lib/golang/src/github.com/DATA-DOG/go-txdb (from $GOROOT)
	/root/rpmbuild/BUILD/minishift-270a4da8a68f96d93895e4aea3534efda868dd15/src/github.com/DATA-DOG/go-txdb (from $GOPATH)
FAIL	github.com/minishift/minishift/bundled/godog/examples/db [setup failed]
?   	github.com/minishift/minishift	[no test files]
```

Can one be sure that minishift won't use one of it's direct dependencies and it in turn won't use one of it's internal dependencies?
