### ISSUE TITLE
Document requirements for profile feature

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#899]
Preparation of issue #549

**Comment by LalatenduMohanty** [comment]
Just for information, here is how minikube implementation works
```
$ minikube start --memory 3000 --profile test1 

$ minikube start --memory 4000 --profile test2

# kubectl  get nodes  will use test2 context by-default
# User can run multiple instances of minikube at one go. However I am not sure how to change the context. 

#stopping 

$ minikube stop --profile test1 

#delete

$ minikube delete --profile test1

```

**Comment by LalatenduMohanty** [comment]
There is the `profile` command which supposed help manage multiple minikube instance, but sure if it works as expected. 
```
$ minikube profile --help
profile sets the current minikube profile.  This is used to run and manage multiple minikube instance.  You can return to the default minikube profile by running `minikube profile default`
```
```
$ kubectl get nodes
NAME      STATUS    AGE
test2     Ready     42s

$ minikube profile test1
minikube profile was successfully set to test1

[lmohanty@LalatenduM-laptop ~]$ kubectl get nodes
NAME      STATUS    AGE
test2     Ready     7m
```

**Comment by jorgemoralespou** [comment]
@LalatenduMohanty I think that profiles in the scope of minikube are something totally different with what is requested in #549, which does define a set of addons to be applied at once, atomically, at machine creation.

minikube feature does align with #126. Not sure if you want to mix both on the same feature, but definitely not the same.

Currently to change profiles in qinikube, you need to:
````
inikube config set name <NAME>
````

If you look into https://github.com/kubernetes/minikube/pull/1320 there is some discussion on enhancing the usability. Not sure they have done it though.

**Comment by hferentschik** [comment]
@LalatenduMohanty Is this not a mixup  as @jorgemoralespou says? 

What we discussed so far under the term _profile_ was about a name for a custom configuration of OpenShift. This parameter really only is relevant during `minishift start`.

In my world, _profile_ was just names list of add-ons. Instead of enabling a specific set of add-ons manually, specifying a _profile_ would do the job for you. So instead of telling Minishift which exact add-ons you want, you just specify a wanted end state (a specific type of OpenShift configuration).

@LalatenduMohanty what you describe is belongs to #549 and is about managing multiple Minishift instances. IMO Minikube choose a bad name with _profile_. Even taking our meaning of _profile_ out of the picture, we are really talking about _named_ instances. 

I think we need to keep things straight here. First question is what we do name wise. Do we want to align with Minikube and call multiple instances _profiles_? If so, we need to find another name for what we discussed as profiles in terms of OpenShift configurations.

**Comment by hferentschik** [comment]
Personally I would prefer to stick with our usage of the term 'profile' and use 'name' for multiple instances. However, that won't go down so well with the intend of aligning with Minikube.

**Comment by jorgemoralespou** [comment]
@hferentschik I would prefer to align with minikube. Maybe you should monitor minikube community more to avoid them taking names wrong :-D

In my case, probably I've been one of the advocates of profiles as a name for that feature, taking into account what I had in my wrapper, and not having the use case of bundles/addons in mind. Although I could agree with you that probably naming wise is more correct having profiles for the bundles, I would not introduce confusion with minikube and find a new name.

Here are some options:
- addon-set
- bundle
- addon-bundle
- config-profile
- cluster-profile
- featureset
- feature

**Comment by hferentschik** [comment]
> Maybe you should monitor minikube community more to avoid them taking names wrong

We did ;-), but they moved fast on this.

> In my case, probably I've been one of the advocates of profiles as a name for that feature, taking into account what I had in my wrapper, and not having the use case of bundles/addons in mind

As said, I think even add-ons and wrapper aside, _profile_ is a bad name. For me a profile is something you a apply to a single instance to modify its behaviour, not multiple instances altogether. Also if you look at docker-machine, they use the _name_ parameter. 

> Although I could agree with you that probably naming wise is more correct having profiles for the bundles, I would not introduce confusion with minikube and find a new name.

Probably. Not happy about this at all, but it might be the best option, given the users who seem to be using both Minikube and Minishift. 

Regarding your suggestion on how to call the OpenShift "profile" feature, I think I prefer "cluster-profile".

**Comment by hferentschik** [comment]
One thing I am wondering about is how the 'cluster-profile' relates to other enabled add-ons. Does it just ignore otherwise installed add-ons, re-configure them to match the requested 'cluster-profile' or does it throw an error. To give an example, say the user has the _anyuid_ add-on installed and enabled and then executes:

    $ minishift start --cluster-profile openshift-online

What is going to happen? 

Also what's going to happen with custom add-ons? Are they applied. In the same scenario, the user has _anyuid_ and the custom _acme_ add-on installed and specifies the _openshift-online_ cluster-profile during start. Obviously _anyuid_ cannot be applied. Either it needs to be ignored or the command will actually disable it to match the requested profile. What happens with _acme_ though. Does it get applied regardless, since it is not a Minishift "managed" add-on? 

Apart of these semantic decisions which we need to make, I think as said we are just dealing with a list of add-ons with a name when talking about _cluster-profile_.

**Comment by hferentschik** [comment]
Another question is, do we just support 'cluster-profiles' we define, or can the user define their own. If so, what type of commands do we need? Will we add them under the 'add-on' scope?

**Comment by LalatenduMohanty** [comment]
@jorgemoralespou @hferentschik I somehow think both the things are related i.e. #126 and #549. Which may be incorrect.  I should have put my observations to #126 .

 There are couple of things we need to decide first which you already mentioned
 * Do we want to align with the `profile` command similar to minikube `profile` feature. You should see a mail about this from me. 

*  how the 'cluster-profile' relates to other enabled add-ons ?
IMO when user creates a new cluster-profile, he gets the default environment as per the cluster-profile irrespective of what add-ons he had enabled in the other cluster-profile  (default is the cluster-profile name if user did not choose any pre-defined cluster-profile name). Once he gets the environment he can do what ever he wants to do with it.  For example if can enable `anyuid` add-on. The user has all the freedom, but the difference is the default `cluster-profile openshift-online` will be exactly like OpenShift online. Then it is up to the user. 

* Do we agree that we would keep the name `cluster-profile`  for ` --cluster-profile openshift-online` ?

Even if I like `cluster-profile` name I feel it might be confusing for people when we will have both `profile` and `cluster-profile`. 

* Do we want user to define custom cluster-profile?

I do not think it is necessary. At least in the beginning. With add-ons and profiles users will be able to customize to a great extent. I think we should go with predefined cluster-profiles to begin with.

**Comment by LalatenduMohanty** [comment]
Specially talking about `--cluster-profile openshift-online`  it is a combination of CPU, RAM and some SCC rules. I do not think we can do it  with just add-on.

**Comment by hferentschik** [comment]
> I somehow think both the things are related i.e. #126 and #549. 

Where is the relation? There is a detail which is indeed related and that's the fact that Minikube decided to share it's addon directory across instances. I don't think we should do this for our case. Add-ons should also be per instance. If anything we should at best share the cache and even there we might need to think twice whether it would not be easier not to do it. If we want to share the cache we will need to improve the cache structure since cache keys won't be unique. This applies for the cached ISO as well as cached container images moving forward. Easiest would be to not share anything between instances (on cost of disk space of course). This is, however, an impl details. Overall multiple instances and cluster-profiles are imo still orthogonal features.

>> How the 'cluster-profile' relates to other enabled add-ons ?

> IMO when user creates a new cluster-profile, he gets the default environment as per the cluster-profile irrespective of what add-ons he had enabled in the other cluster-profile (default is the cluster-profile name if user did not choose any pre-defined cluster-profile name).

I am confused, you seem to mix  cluster-profile vs add-ons vs multiple instances. No doubt creating two instances with two different cluster-profiles gives me two differently configured OpenShift instances, honouring the respectively requested 'cluster-profile'. The question is how to deal with add-ons installed and enabled via `minishift addons` and its sub-commands. 

> Once he gets the environment he can do what ever he wants to do with it. 

Of course.

> For example if can enable anyuid add-on. The user has all the freedom, but the difference is the default cluster-profile openshift-online will be exactly like OpenShift online. Then it is up to the user.

Sure, but what do we do when (clean start from scratch):

    $ minishift addons enable anyuid
    $ minishift start 
    # dos stuff
    $ minishift delete
    $ minishift start  --cluster-profile openshiftonline

The user has _anyuid_ enabled per default, but he also now requests the cluster-profile openshiftonline which cannot have this add-on applied. The question is how to deal with these cases. We need to find a consistent user experience which combines existing add-ons behaviour with cluster-profile. 

> Do we agree that we would keep the name cluster-profile for --cluster-profile openshift-online ?

cluster-profile is my most favourite alternative atm.

> Even if I like cluster-profile name I feel it might be confusing for people when we will have both profile and cluster-profile.

Sure. Do you have a better suggestion? 

>> Do we want user to define custom cluster-profile?

>I do not think it is necessary. At least in the beginning. 

+1, I think initially we don't have to. This saves us to decide right now which new commands to add. Moving forward it might makes sense though to allow for this case, since it solves another use case indirectly which is a more explicit way to express dependencies between add-ons. A profile could be seen as a named list of add-ons which is also resolving the dependency issue.

**Comment by hferentschik** [comment]
> Specially talking about --cluster-profile openshift-online it is a combination of CPU, RAM and some SCC rules. I do not think we can do it with just add-on.

I am not quite sure whether this is correct. I don't think CPU and RAM constraints should be managed on VM level. The VM should always get as much CPU and RAM as possible. In terms of matching OpenShift Online I would expect that OpenShift quotas and limits will be used to ensure constraints on a project/namespace. This can be configured via add-ons.

**Comment by jorgemoralespou** [comment]
I totally agree with @hferentschik on all comments. I would think that implementing a cluster-profile as a set of addons, could simplify those use cases where one wants a modified version of a cluster-profile.
I would also consider that if a cluster-profile is specified, no "addons" should be installed that are not part of the cluster-profile, unless manually installed, but not as part of the initial bootstrapping, so:

If cluster-profile then 
  apply addons for the cluster-profile
else
  apply enabled addons
fi

**Comment by hferentschik** [comment]
Ok, let's try to sum this up:

* We call this feature _cluster-profile_ moving forward to be able to call multiple instances "profiles" (in order to align with Minikube)
*  Cluster profiles are based on add-ons
* A profile is a name for a list of add-ons to apply (defining the add-ons to apply and the order in which they apply)
* When Minishift is started with the --cluster-profile option, the add-ons defined in this profile are applied , ignoring otherwise configured add-ons
  * We can make things a bit more explicit by appropriate user messages (aka that a profile is enabled and hence add-on x won't be applied)
* We provide a given set of cluster profiles 
  * _openshift-online_ (matching the OpenShift Online settings)
  * _liberal_ (name to be discussed; most importantly it will allow the user to run any image)
  * _none_ (might be required depending on what we decide which profile becomes the default)
* Initially there won't be a way to define custom profiles by the user
  * There might be no need for this anyways, since the user can just enable hist custom add-ons and adjust their priority to achieve the same outcome
* If no _cluster-profile_ parameter is specified a default applies. The choice is between:
  * _openshift-online_ - in this case a default Minishift start will match more closely OpenShift Online, however, to allow existing add-ons to continue to work, one would need a _none_ cluster profile which effectively runs the current add-on behaviour 
  * Not specifying a _cluster-profile_ during start, means an implicit _none_ and things behave as they currently are. To match OpenShift Online the _openshift-online_ cluster profile needs to be explicitly specified.

**Comment by hferentschik** [comment]
I am marking this issue as resolved. I think we have enough to implement this. There are still some questions around the right defaults, but I think we can deal with this as part of the actual implementation for issue #549.

**Comment by jorgemoralespou** [comment]
@hferentschik just making one comment.

openshift-online has many flavours that you can see [online](https://www.openshift.com/pricing/index.html). I would not make this a default cluster-profile, as I think main target for minishift is users that don't use online but rather OpenShift on-premises. I would go for "none" as default.

**Comment by hferentschik** [comment]
> openshift-online has many flavours that you can see online. I would not make this a default cluster-profile, as I think main target for minishift is users that don't use online but rather OpenShift on-premises. I would go for "none" as default.

+1 this would be preferred choice as well. It keep backwards compatibility and we "nicely" add a new feature. I just recall that in some discussion we have some preference for default being _openshift-online_, but for my part definitely _none.

**Comment by LalatenduMohanty** [comment]
> A profile is a name for a list of add-ons to apply (defining the add-ons to apply and the order in which they apply)

@hferentschik  You mean cluster-profile right?

**Comment by hferentschik** [comment]
> You mean cluster-profile right?

sure.
