### ISSUE TITLE
Fix the links in installation and installation guide

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#902]
Found that the KVM hyperlink is pointing to minishift.io here https://docs.openshift.org/latest/minishift/getting-started/installing.html#install-prerequisites 

and

Using -> Uninstalling   uses minishift.io here https://github.com/minishift/minishift/blob/master/docs/source/getting-started/uninstalling.adoc

**Comment by hferentschik** [comment]
Merged via pull request #904
