### ISSUE TITLE
Invalid handle when no SSH installed on Windows

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#912]
See: https://github.com/minishift/minishift-centos-iso/issues/95

**Comment by gbraad** [comment]
@budhrg you mentioned something is failing now?

**Comment by budhrg** [comment]
@gbraad  Comment here https://github.com/minishift/minishift/pull/911#issuecomment-302043786

**Comment by hferentschik** [comment]
@gbraad so we don't need a separate ssh client installed on Windows anymore? What about the performance issues around ssh taking so long? Is this still an issue?

**Comment by gbraad** [comment]
Some of the slow interaction I am currently experiencing is with `oc login` #563.
