### ISSUE TITLE
make integration failed on scenario "User can deploy application ruby-ex to namespace ruby" 

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#913]
Environment 
```
Fedora 23, minishift master branch, minishift 1.0.1
```
Steps to reproduce : 
```
1. Clone minishift master (or download minishift 1.0.1)
2. Run "make integration" (or make integration MINISHIFT_BINARY=<path-to-minishift 1.0.1)
```
The first failure causes due to step 
```
When executing "oc rollout status deploymentconfig ruby-ex --watch" succeeds
Then stdout should contain
     """
     "ruby-ex-1" successfully rolled out
     """
```
ERROR : 
```
Then  stdout should contain # features/basic.feature:147
      Error: Output did not match. Expected: "ruby-ex-1" successfully rolled out, Actual: Deployment conf
ig "ruby-ex" waiting on image update
```
Step execution went fine when I did manually on minishift-1.0.1

**Comment by praveenkumar** [comment]
@amitkrout might be network issue from your side or you may need clean env. I did try to execute same way you described and not able to reproduce.

**Comment by amitkrout** [comment]
@praveenkumar yes it might be network issue. Its been a long time when i last rebooted my system. Will do some cleanup and update the outcome.

**Comment by amitkrout** [comment]
Good news !!!! 
All the test scenario went through without any failures
