### ISSUE TITLE
Change minishift version to string to use vX.X.X

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#924]
Refer https://github.com/minishift/minishift/pull/923

The version output format looks quite different to the output from `minishift openshift version` and `s2i version` which is a minor annoyance for automation.

Old format:
```bash
$ minishift version
Minishift version: 1.0.1
```

New format:
```bash
$ minishift version
minishift v1.0.1
```

Other tools with similar formats:
```
$ minishift openshift version
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
etcd 3.1.0
$ s2i version
s2i v1.1.6
```

**Comment by hferentschik** [comment]
Merged via pull request #923
