### ISSUE TITLE
Add a '-u' short alternative to `--url` to the `minishift (openshift) service foo` command

### ISSUE THREAD

**Issue by jstrachan** [minishift/minishift#928]
less typing FTW

**Comment by budhrg** [comment]
> less typing FTW

Agree, short form is good.

**Comment by aditya-konarde** [comment]
@jstrachan @budhrg @LalatenduMohanty is someone already working on this? I would like to work on this as my first contribution to the project.

**Comment by budhrg** [comment]
Go ahead @aditya-konarde :+1:

**Comment by aditya-konarde** [comment]
#1346 is now merged. Can we close this issue now?

**Comment by budhrg** [comment]
Sure thanks @aditya-konarde for contribution.
