### ISSUE TITLE
Alias `minishift dashboard` to `minishift console`

### ISSUE THREAD

**Issue by jstrachan** [minishift/minishift#929]
folks who have used minikube can get used to typing `minikube dashboard` and end up typing `minishift dashboard` and getting an error. They both do basically the same thing - open the web UI for the cluster - so it'd be nice to have the same command names to minimise friction for developers who use both minikube and minishift and smooth the transition between the two

**Comment by jstrachan** [comment]
whether we wanna deprecate `minishift console` or keep both I don't much mind; but letting users type either sounds a reasonable tactical approach in the short term

**Comment by praveenkumar** [comment]
@jstrachan Some time back even `minikube` had console and looks like they changed it with `dashboard`. This is mostly a trivial change and we discuss around it and implement.

**Comment by gbraad** [comment]
A reasonable request, but the question is what action we take:

1. change, leaving only one option
2. add a command, offering two options
    a. mark `console` as deprecated
    b. no further actions for now

**Comment by jorgemoralespou** [comment]
Sadly we use the term console in openshift and dashboard is the name of the console in k8s. It's a sad move from minikube that makes us support it for compatibility, I would keep both though.

**Comment by hferentschik** [comment]
> Sadly we use the term console in openshift

+1 I think the same way. In OpenShift we are talking about the OpenShift console, so 'minishift console' makes most sense imo. I guess we can alias dashboard, but we should not remove console. To me, not working so much with Kube, dashboard even feels wrong. It really comes down to from which angle you are looking at it.

**Comment by gbraad** [comment]
My 2c; my initial thought when using minishift, during prototype, was that
console would open a terminal, while ssh would run one of commands. In
other words, the terminology is extra confusing in a CLI only tool.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by hferentschik** [comment]
I am find that "OpenShift Console" is a bit an odd name for the web app, but that's what it is. If we rename to 'dashboard', we are using terminology which is not used anywhere else in OpenShift.

**Comment by gbraad** [comment]
We can't change openshift now...
... so use two commands for one purpose. OK. A little bit odd, but doable

**Comment by hferentschik** [comment]
Right, an alias seems the best option.

**Comment by hferentschik** [comment]
Merged via pull request #1018
