### ISSUE TITLE
`minishift start` fails on mac/xhyve

### ISSUE THREAD

**Issue by caruccio** [minishift/minishift#932]
I am unable to start minishift on mac:
```
$ minishift start
Starting local OpenShift cluster using 'xhyve' hypervisor...
E0519 16:48:03.096205   36976 start.go:176] Error starting the VM: Unused explicit driver options: map[xhyve-virtio-9p:true xhyve-uuid:F4BB3F79-AB4E-4708-95CA-E32FBFCDEFD3]. Retrying.
E0519 16:48:03.121593   36976 start.go:176] Error starting the VM: Unused explicit driver options: map[xhyve-uuid:F4BB3F79-AB4E-4708-95CA-E32FBFCDEFD3 xhyve-virtio-9p:true]. Retrying.
E0519 16:48:03.151993   36976 start.go:176] Error starting the VM: Unused explicit driver options: map[xhyve-virtio-9p:true xhyve-uuid:F4BB3F79-AB4E-4708-95CA-E32FBFCDEFD3]. Retrying.
Error starting the VM:  Unused explicit driver options: map[xhyve-virtio-9p:true xhyve-uuid:F4BB3F79-AB4E-4708-95CA-E32FBFCDEFD3]
Unused explicit driver options: map[xhyve-uuid:F4BB3F79-AB4E-4708-95CA-E32FBFCDEFD3 xhyve-virtio-9p:true]
Unused explicit driver options: map[xhyve-virtio-9p:true xhyve-uuid:F4BB3F79-AB4E-4708-95CA-E32FBFCDEFD3]
```

![captura de tela 2017-05-19 as 16 51 27](https://cloud.githubusercontent.com/assets/540936/26264500/6f7aa1f0-3cb3-11e7-818a-9e980434f596.png)

**Comment by praveenkumar** [comment]
@caruccio Can you check if `XHYVE_VIRTIO_9P` env variable is set to `true` for your case if yes can you `unset` it and try it again? Make sure you delete existing `minishift` instance if any,

```
$ unset XHYVE_VIRTIO_9P
$ minishift delete
$ minishift start
```

**Comment by hferentschik** [comment]
What's your xhyve driver version as well? Can you make sure you have the latest installed? See also https://docs.openshift.org/latest/minishift/getting-started/docker-machine-drivers.html#xhyve-driver-install

**Comment by LalatenduMohanty** [comment]
@caruccio Are you still seeing this issue. Please let us know the information for us to move ahead with the issue.

**Comment by caruccio** [comment]
@praveenkumar XHYVE_VIRTIO_9P wasn't set
@hferentschik I was running 0.2.2. After update, it's now working fine.
@LalatenduMohanty No issues anymore.

Thanks all for you support.
