### ISSUE TITLE
Boot2Docker can't connect to SMB2.0 leads to failed start on Win10 / HyperV

### ISSUE THREAD

**Issue by jischebeck** [minishift/minishift#936]
Hi,

after several attempts I could start a virtual machine using "minishift start" on Win10 using the hyperv hypervisor.

```
C:\>minishift start
Starting local OpenShift cluster using 'hyperv' hypervisor...
Error creating required host directories:  Error attempting to get plugin server 
address for RPC: Failed to dial the plugin server in 10s
```
As hyperv doesn't support host directory sharing, I had to create a host folder myself.
```
C:\>minishift hostfolder add usershare
UNC path: //XXXXXXXX/Users
Mountpoint [/mnt/sda1/usershare]:
Username: XXXXXXX
Password: [HIDDEN]
Domain: XXXXXXXX
Added: usershare

C:\>minishift hostfolder mount usershare
   Mounting 'usershare': '//XXXXXXX/Users' as '/mnt/sda1/usershare' ... FAIL
```
Switching on the logging (-v10) shows, that the mount command fails on linux. Executing the command in linux gives the following result.

```
root@minishift:~# sudo mount -t cifs //XXXXXXX/Users /mnt/sda1/usershare -o username=XXXXX,password=XXXX,domain=XXXXX
mount error (112): Host is down
```

Further investigation shows, that the Win10 host computer has deactivated SMB1.0. [due to Wanna Cry] Switching to SMB2.0 using a command option -o vers=2.0 is not supported by the boot2docker image. 

```
root@minishift:~# sudo mount -t cifs //XXXXXXX/Users /mnt/sda1/usershare -o username=XXXXX,password=XXXX,domain=XXXXX,vers=2.0
mount error (22): Invalid argument
```

Any ideas how to work around the issue?

**Comment by gbraad** [comment]
Either we update the B2D image, or we mark this as a known issue (although we have already removed the table of support for this). Or close, and regard this as solved when we move to the Minikube ISO

**Comment by LalatenduMohanty** [comment]
> regard this as solved when we move to the Minikube ISO

+1.

@jischebeck  you should retry this with minishift v1.11.0 and minikube ISO i.e. `minishift start --iso-url minikube`. We are planning to drop B2D for technical reasons.

**Comment by praveenkumar** [comment]
Closing this now, since we already removed the support table and in future, we will put b2d ISO in maintenance mode.
