### ISSUE TITLE
Usage of openshift_cache file for minishift

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#937]
Currently we have `pkg/minishift/cache/openshift_cache.go` file laying in our code base which doesn't seem to use anywhere. As per my understanding this file was there because before we started using `oc cluster up` for openshift cluster, we used to use `openshift` binary and this file for that. Can we remove this file from our code base if I am not missing any usage of it.

@hferentschik @LalatenduMohanty @budhrg  WDYT?

**Comment by LalatenduMohanty** [comment]
+1, I do not see any use of this file in present code base.

**Comment by budhrg** [comment]
+1 Looks like we might not do `openshift` caching. That's why there is extra folder `openshift` in `$MINISHIFT_HOME/cache/openshift`.

**Comment by hferentschik** [comment]
This file is obsolete. I actually already removed it, on a feature branch of mine.

**Comment by hferentschik** [comment]
> That's why there is extra folder openshift in $MINISHIFT_HOME/cache/openshift.

This is removed as well. Or better renamed to something we need.

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift/pull/949
