### ISSUE TITLE
Add native integration for toolbar icon

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#946]
It would be nice to have a native icon (like Docker for Windows or Windows for Mac) that will display an icon showing whether minishift is running or not.
Additionally, whenever profiles exist (multiple clusters running) it would be also nice to show which clusters are running, as memory consumption for the VMs can be a big slower for overall laptop performance and users typically forget that and if minishift is running.

**Comment by gbraad** [comment]
As mentioned on #907 I have been working on a Windows tray icon, which can help which some of the issue arround Hyper-V. However, this is not a scheduled task and something on the side...
