### ISSUE TITLE
After upgrading the minishift binary we should tell the user to delete + start their VM again

### ISSUE THREAD

**Issue by jstrachan** [minishift/minishift#947]
what would be even cooler would be to capture the start flags & configurations and let the users do it automatically.

e.g..
```
$ minishift update
A newer version of minishift is available.
Do you want to update from 1.0.0 to 1.0.1 now? [y/N]: y
Downloading https://github.com/minishift/minishift/releases/download/v1.0.1/minishift-1.0.1-linux-amd64.tgz
 3.43 MiB / 3.43 MiB [============================================================================================================================] 100.00% 0s
 65 B / 65 B [====================================================================================================================================] 100.00% 0s

Updated to minishift v1.0.1 successfully.

Would you like to recreate your openshift cluster?
WARNING: this will remove all the resources in your openshift cluster!

recreate openshift cluster:  [y/N]: y

deleting openshift VM....
creating openshift VM...
```

**Comment by hferentschik** [comment]
If the user uses the _minishift config_ command to set his preferred options, this will happen automatically. If the user specifies everything via the command line we are atm out of luck, since we don't have a way to get to this parameters once the VM is started. What we could do is to persist the applied parameters, so that we could then re-use it. We have been discussing this before, also in the context of #179.

Whether re-creating the OpenShift cluster will make sense, depends really. Unless the OpenShift baseline used by the new Minishift version, there won't be any difference.

**Comment by jstrachan** [comment]
Persisting the configuration somewhere sounds really handy.

For minor upgrades in minishift where there's no underlying VM / openshift change there's no need to recreate the OpenShift VM; but when openshift has upgraded from, say, 1.4 to 1.5 then there is. 

Maybe the upgrade command could be smart enough to detect if there is a significant VM / openshift version change in the new minishift binary and only present the 'recreate OpenShift VM' option if there's a significant upgrade to openshift?

**Comment by LalatenduMohanty** [comment]
Just to add update can bring in a new ISO. Obviously it is not a case always. Also I think application developers might want to keep working a specific version of OpenShift to match their production version of OpenShift and will not want to move to a newly release OpenShift version quickly. But I guess this is different for Red Hat folks.

**Comment by LalatenduMohanty** [comment]
What I mean is, auto create might not be useful to all users of Minishift but to some portion of it.

**Comment by hferentschik** [comment]
If I have a working setup, I don't see a reason to throw this away. I think we should not prescribe a delete and start in general. It's a different issue if we are introducing backwards incompatible change, then yes. But this will also be marked by a change in the major version. 

Generally, things should continue to work after an update. If not, the first stop remedy is to stop, delete and then re-start. 

Let's close this issue.

**Comment by LalatenduMohanty** [comment]
> If I have a working setup, I don't see a reason to throw this away. I think we should not prescribe a delete and start in general. It's a different issue if we are introducing backwards incompatible change, then yes. But this will also be marked by a change in the major version.

Ideally we should tell the user, when backward compatible changes are introduced. I think agreed that we need to inform the user for sure (can not find that issue though).
