### ISSUE TITLE
minishift start --help should document environment variables applicable in Minishift

### ISSUE THREAD

**Issue by rctrh** [minishift/minishift#950]
I think it will come up frequently enough that `minishift start --help` should document the environment variables that can be used to store the registration username and password.

**Comment by hferentschik** [comment]
I think we need to add something to the generic usage of  the help output, not only the username and password. All the parameters are configurable by env variables https://docs.openshift.org/latest/minishift/using/managing-minishift.html#environment-variables. This generic approach should be mentioned.

**Comment by gbraad** [comment]
I believe `minikube` doesn't specify this either, but only refers to it from their documentation.  I could be wrong, but my 2c? I doubt `-h`/`--help` output is the place for this... it will clutter the help output. I do not think people will look for this functionality there.

Minikube docs reference:
Originally https://github.com/kubernetes/minikube/pull/1094/files, but moved to https://github.com/kubernetes/minikube/blob/master/docs/env_vars.md

**Comment by praveenkumar** [comment]
>  I doubt -h/--help output is the place for this... it will clutter the help output. I do not think people will look for this functionality there

I do agree. Either we create a separate command option for this which provide info about what can be set as environment variable. Also as per `minikube` document it says only config which are part of `config view` can be set as env but for us this list is very big now.

**Comment by hferentschik** [comment]
Merged via pull request #1096
