### ISSUE TITLE
PV issues with gitlab on minishift 1.0.1 - any tips on an easier way to install it?

### ISSUE THREAD

**Issue by jstrachan** [minishift/minishift#955]
I wanted to run gitlab on minishift. I've found this blog:
https://about.gitlab.com/2016/06/28/get-started-with-openshift-origin-3-and-gitlab/#import-the-template

which uses this template: https://gitlab.com/gitlab-org/omnibus-gitlab/raw/master/docker/openshift-template.json

You need to do the `oc edit scc anyuid` thing to get around the run as user thing. 

Then I followed the instructions to install and run the template; but I got issues in the gitlab pod which seemed to be permission issues on the PVs.

To get it to work I found I had to find the PVC -> PV names (`oc get pvc`) then run something like this:
```
minishift ssh
cd /var/lib/minishift
cd openshift.local.pv
sudo sh
cd pvXXXX
chmod -R 777 .*
cd ./pvYYYY
chmod -R 777 .*
```
where `pvXXXX` and `pvYYYY` are the actual PV names that got bound.

Is this an effect of how the PVs work on minishift and the fact that we are not running as a random user? I wondered if there was a way to get this to work any cleaner OOTB on minishift?

Ideally we'd find a gitlab template that supported running as a random user really which might fix all of this

**Comment by LalatenduMohanty** [comment]
@jstrachan Not sure if you are aware of anyuid add-on we have in Minishift. You need to run anyuid addon and then start minishift. The PV thing is taken care of automatically when user enables anyuid. 
Related we are working on #637 . Just mentioning before you ask for it :)
```
$ minishift addons install --defaults --enable
Default add-ons anyuid, admin-user installed

$ minishift start
```

**Comment by LalatenduMohanty** [comment]
@jstrachan Let us know if this works for you.

**Comment by praveenkumar** [comment]
@jstrachan below are steps which I followed and have gitlab up and running. Let us know if you still have issue around PV's.

```
$ ./minishift addons list
- admin-user     : enabled    P(0)
- anyuid         : enabled    P(0)

$ ./minishift start 
...
-- Waiting for persistent volumes to be created ... OK

-- Applying addon 'admin-user':..

-- Applying addon 'anyuid':.
   Add-on 'anyuid' changed the default security context constraints to allow pods to run as any user.
   Per default OpenShift runs containers using an arbitrarily assigned user ID.
   Refer to https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html#security-context-constraints and
   https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-origin-specific-guidelines for more information.
...

$ eval $(./minishift oc-env)
$ oc create -f https://gitlab.com/gitlab-org/omnibus-gitlab/raw/master/docker/openshift-template.json
$ oc new-app gitlab-ce APPLICATION_HOSTNAME=test.<vm_ip>.nip.io
$ oc get pods
NAME                           READY     STATUS    RESTARTS   AGE
gitlab-ce-1-nlngq              1/1       Running   0          11m
gitlab-ce-postgresql-1-92b0w   1/1       Running   0          11m
gitlab-ce-redis-1-73r7q        1/1       Running   0          11m
```

**Comment by jstrachan** [comment]
works great many thanks!

**Comment by hferentschik** [comment]
> works great many thanks

:-)

**Comment by jorgemoralespou** [comment]
@jstrachan You do not need to execute the anyuid addon, which gives anyuid to every user, but should only require the anyuid to the gitlab-ce-user (actually, ${APP_NAME}-user) serviceaccount. 

@praveenkumar @LalatenduMohanty @hferentschik I'm concerned that we recommend the anyuid for every use case, as I have said before, this is a bad pattern, and should be avoided as much as possible.

We need to schedule the openshift training you wanted and discuss these patterns.

People end up finding these issues and think are as good as documentation :-(

**Comment by LalatenduMohanty** [comment]
@jorgemoralespou ack. We will schedule a discussion.  We (at least I ) need to understand this better).
