### ISSUE TITLE
Allow hostfolder configuration non interactively 

### ISSUE THREAD

**Issue by ruifortes** [minishift/minishift#959]
Hi.
Sorry for the off-topic post but since the command I'm struggling is from minishift I hope yu don't mind me posting.
I not at all proficient with linux but surely this is a n brainer for you guys.
I'm trying to call "minishift hostfolder add" in a shell script (wel...actually a npm script) that automatically fills all input prompts.
I followed [this](https://askubuntu.com/questions/338857/automatically-enter-input-in-command-line) instructions but something gets broken and although "add" works the "mount" fails.

Heres the line I use:
`printf '//192.168.1.33/datafolder\n/mnt/sda1/datafolder\nsomeuser\nsomepass\n\n' | minishift hostfolder add mymount`
It adds but mount fails.
if I enter manually it works

Can someone tell me how to fill all input in a single command?
Thanks

**Comment by gbraad** [comment]
Can you check the config file for the VM ? what does the entry contan for your defined hostfolder?

BTW, we will offer parameter options in a future increment.

**Comment by hferentschik** [comment]
@gbraad Do you want to rename this issue to match what we are planning to do, aka "Add command line switches for `minishift hostfolder add`" or shall we create a new issue and reference it from here?

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/2093
