### ISSUE TITLE
Unmanageble Minishift state after host restart

### ISSUE THREAD

**Issue by cescoffier** [minishift/minishift#960]
This is more a hint than an issue (probably something to add in the FAQ or in the doc).

Yesterday, I've updated my Mac to 10.12.5 (latest Sierra).

Minishift was not starting after the update. Most commands (delete, stop) was reporting:

```
Error stopping cluster: Error unregistring the VM: ssh command error: # BTW, it should be unregistering no?
command : sudo cat /etc/os-release
err     : exit status 255
```
I've deleted my ~/.minishift directory and restarted minishift.... I'm now back on track

**Comment by Preeticp** [comment]
Thanks for reporting this @cescoffier we will look into this and add it to our docs.

**Comment by LalatenduMohanty** [comment]
@cescoffier what was the state of Minishift when you updated macOS to Sierra?

**Comment by gbraad** [comment]
This sounds like the VM was in running state, but not having an IP address. Since xhyve does not have a friendly interface to shutdown the VM, this is a slightly cumbersome situation.

**Comment by cescoffier** [comment]
> @cescoffier what was the state of Minishift when you updated macOS to Sierra?

Running. Probably not a good idea... However, the update requires a restart of the computer.

**Comment by gbraad** [comment]
@cescoffier what were you running BEFORE the update?

**Comment by cescoffier** [comment]
> @cescoffier what were you running BEFORE the update?

minishift.

**Comment by gbraad** [comment]
@cescoffier You update macOS, right?
> Yesterday, I've updated my Mac to 10.12.5 (latest Sierra).

What was it runnintg before this?

**Comment by cescoffier** [comment]
It was Sierra, but the previous updates (I don't know the version)

**Comment by gbraad** [comment]
OK, check... a point release (update)

**Comment by praveenkumar** [comment]
>  does xhyve keep a local cache/config for configured virtual machines? or any idea how Hypervisor.framework keeps thsi config?

I don't think so. As per @cescoffier report looks like when he started to update that time minishift was running and he did reboot system where minishift didn't update the state and when he tried to delete then not able to access the VM.

**Comment by gbraad** [comment]
Does Hypervisor.framework/xhyve do autostart of VM ? IIRC is does not...
So maybe he tried to start the VM, but did not get an IP assigned? (old
lease?)

**Comment by praveenkumar** [comment]
> Does Hypervisor.framework/xhyve do autostart of VM ? IIRC is does not...

No I don't think it autostart VM (if you restart your OSx host when minishift is running on xhyve then it will after restart it minishift state not be running) If that is you meant.

**Comment by hferentschik** [comment]
We are actually discouraging a right out deletion of  ~/.minishift (MINISHIFT_HOME). If anything, you want to remove the _machines_ sub-directory.

**Comment by LalatenduMohanty** [comment]
I think this is the second issue I am seeing where Minishift is in running state and the host OS is restarted. We need to find out if we can handle the situation gracefully and provide user proper feedback if possible.

**Comment by jorgemoralespou** [comment]
+1
related to #1066

**Comment by gbraad** [comment]
@lalatenduM looking at the code for `xhyve`/`bhyve`, hoping to find how state is kept.

**Comment by gbraad** [comment]
The actual issue is in the `docker-machine-driver-xhyve`: https://github.com/zchee/docker-machine-driver-xhyve/issues/179

**Comment by LalatenduMohanty** [comment]
IMO we should add this to troubleshooting guide i.e. 
1. If you want to restart the host, make sure Minishift VM is stopped state.
2. In case you have restarted the host when the Minishift VM was running then user needs to delete the machines sub-directory and start fresh.

**Comment by gbraad** [comment]
This got solved... not sure why this is still open/reopened.

This got fixed with https://github.com/zchee/docker-machine-driver-xhyve/issues/179 (Closed)

**Comment by gbraad** [comment]
Option 1 is recommended
Option 2 is not true, as the issue with NOT on the Minishift VM side, but how the driver plugin internally represented the state.
