### ISSUE TITLE
'docker push' w/ docker-registry route from addons fails with "unauthorized: authentication required"

### ISSUE THREAD

**Issue by thomasmckay** [minishift/minishift#976]
Using the registry-route addons https://github.com/minishift/minishift/blob/master/addons/registry-route/registry-route.addon I am able to login to registry but not docker push to it. Could be related to https://github.com/openshift/origin/issues/14249 and https://github.com/openshift/openshift-ansible/pull/4254 ?

**Comment by thomasmckay** [comment]
My minishift setup
```
      pushd github/minishift/addons && minishift addons install registry-route && popd
      pushd github/minishift/addons && minishift addons install anyuid && popd
      minishift addons enable registry-route
      minishift addons enable anyuid
      minishift start
      oc login -u system:admin
      oc project default
      oc adm policy add-role-to-user cluster-admin developer
      eval $(minishift docker-env)
      oc create -n default -f https://raw.githubusercontent.com/openshift/openshift-ansible/master/roles/openshift_hosted_templates/files/v1.5/origin/registry-console.yaml
      oc create route passthrough --service registry-console --port registry-console -n default
      oc new-app -n default --template=registry-console -p OPENSHIFT_OAUTH_PROVIDER_URL="https://$(minishift ip):8443" -p REGISTRY_HOST=$(oc get route docker-registry -n default --template='{{ .spec.host }}') -p COCKPIT_KUBE_URL=$(oc get route registry-console -n default --template='https://{{ .spec.host }}')
```

From another host
```
docker push docker-registry-default.192.168.42.181.nip.io/rhcc/logging-deployment:retagged
```
I tried setting the 'minishift docker-env' locally on the host pushing from (copying certs over locally too) but stil get unauthorized error. I have added the registry as insecure. I can pull from the registry fine.

```
$ docker push docker-registry-default.192.168.42.181.nip.io/rhcc/logging-deployment:retaggedThe push refers to a repository [docker-registry-default.192.168.42.181.nip.io/rhcc/logging-deployment]
9eee71018de4: Layer already exists 
435e32e8fdca: Layer already exists 
705614d69604: Layer already exists 
1bc67546e0db: Layer already exists 
43818193b2cf: Layer already exists 
unauthorized: authentication required
```

**Comment by thomasmckay** [comment]
docker-1.12.6-16.el7.centos.x86_64

**Comment by thomasmckay** [comment]
duplicate of https://github.com/minishift/minishift/issues/817 ?

**Comment by gbraad** [comment]
What is your host OS?

**Comment by gbraad** [comment]
Did you login with:
```
docker login -u developer -p $(oc whoami -t) $(minishift openshift)
```

**Comment by praveenkumar** [comment]
@thomasmckay Can you try with a different iso like centos one using below (make sure you delete minishift vm before start it again)

```
minishift --start --iso-url https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0/minishift-centos7.iso
```

**Comment by hferentschik** [comment]
@thomasmckay, you need to tag the image explicitly with the port 443. This is needed due to a bug in Docker and the reason why we don't enable this add-on per default atm. For that reason we also use the internal registry IP as part of 'minishift openshift registry'.

Could you try something like:

     $ docker tag logging-deployment docker-registry-default.192.168.42.181.nip.io:433/rhcc/logging-deployment:retagged
     $ docker push docker-registry-default.192.168.42.181.nip.io:433/rhcc/logging-deployment:retagged

**Comment by michelebariani** [comment]
Hi,

Although I am not using any add-on, I have exactly the same "authentication required" and wanted to let @thomasmckay know that switching from default minishift-b2d.iso image to minishift-centos7.iso actually fixed the issue in my case.

Thanks, and keep up the good work :-)

Note: host is Fedora 25 (fully updated), using Virtualbox as vm-driver

**Comment by hferentschik** [comment]
There might be several issues then. Using the add-on makes a huge difference on how the registry is accessed. @michelebariani, I understand you are using the internal registry IP. This should indeed work fine out of the box. If to make this work you have to switch to another ISO, we have a regression somewhere.

Regarding the route add-on and using a dedicated route to access the registry, you will need to add the port when tagging the image. This is a known issue. If it still fails after adding the port, it might be that @thomasmckay runs into the same issue as @michelebariani.

**Comment by thomasmckay** [comment]
Still fails after adding :443
Still fails using centos7 iso and specifying :443

**Comment by thomasmckay** [comment]
A conversation on openshift-dev irc caught my eye and it's the source of my problem. It seems the user I was pushing with did not have priveleges to push imagestreams. I'm not sure, as a new user, what the correct flow should be to correct this.

Instead of pushing to a project I created in the registry console I instead pushed to "myproject"
```
$ sudo docker push docker-registry-default.192.168.42.126.nip.io:443/myproject/my-logging:first
The push refers to a repository [docker-registry-default.192.168.42.126.nip.io:443/myproject/my-logging]
9cc7cd5985bd: Pushed 
36e9d4751236: Pushed 
324b3773d534: Pushed 
9320560b5404: Pushed 
first: digest: sha256:d1613244f3cd565de4e5f7cdb544d32daacec2b08943dab00afc6ebb3ac44220 size: 3559
```

I would say this issue can be closed and perhaps some documentation issues created? Open to suggestions on how best to educate users like myself.

Thanks!

**Comment by michelebariani** [comment]
Very good point from @thomasmckay and I thought it would be the fix for the default boot2docker iso, but no luck in my case.

On a fresh minishift (b2d) VM tried pushing into myproject, both as *developer* and as *system:admin*, without success.
Also added *system:image-builder* role (not 100% sure it's the right one, anyway) to *developer*, no luck. Even added *admin* role to developer, still no luck.

As an additional info, as it may somehow be related at this point: out of the box the original error I have is upon docker login, that fails with

`could not read CA certificate "/etc/docker/ca.pem": open /etc/docker/ca.pem: no such file or directory`

My current workaround

`sudo ln -s ~/.minishift/certs/* /etc/docker/`

**Comment by jorgemoralespou** [comment]
Docker push into the registry will not create the projects/namespaces in the registry. These need to exist and you need to have permissions to push to them. You would most likely push to either one of your projects (as you'll use the image there) or a shared project (openshift) that is meant to be shared for every user (although not sure you can push here), but never to a non existent project.

In your example above, you were trying to push to rhcc, which did not exist on openshift, so you can:
- create the project (then you'll have permissions to push to it)
- use an existing project (validating you have permissions to push)
- tag differently your image.

**Comment by jorgemoralespou** [comment]
@michelebariani as you're using self-signed certificates, you either add the certificates to your docker trust or you add the registry to the list of insecure registries.

And for the permission, you can validate the builder serviceaccount, which is the one that pushes internally.
https://docs.openshift.org/latest/dev_guide/managing_images.html#accessing-the-internal-registry

**Comment by budhrg** [comment]
It's a duplicate of https://github.com/minishift/minishift/issues/817 and we are tracking there.
