### ISSUE TITLE
Minishift on Macos ignores the --vm-driver flag

### ISSUE THREAD

**Issue by orf** [minishift/minishift#977]
Minishift version 1.0.1

```
> brew cask install minishift

> minishift start --vm-driver=virtualbox --logtostderr --show-libmachine-logs

Starting local OpenShift cluster using 'virtualbox' hypervisor...
I0531 22:03:01.614119    4880 cluster.go:74] Machine exists!
I0531 22:03:01.614350    4880 cluster.go:82] Machine state:  Error
E0531 22:03:01.614370    4880 start.go:176] Error starting the VM: Error getting the state for host: Driver "xhyve" not found. Do you have the plugin binary accessible in your PATH?. Retrying.
I0531 22:03:01.614381    4880 cluster.go:74] Machine exists!
I0531 22:03:01.614520    4880 cluster.go:82] Machine state:  Error
E0531 22:03:01.614528    4880 start.go:176] Error starting the VM: Error getting the state for host: Driver "xhyve" not found. Do you have the plugin binary accessible in your PATH?. Retrying.
I0531 22:03:01.614535    4880 cluster.go:74] Machine exists!
I0531 22:03:01.614659    4880 cluster.go:82] Machine state:  Error
E0531 22:03:01.614666    4880 start.go:176] Error starting the VM: Error getting the state for host: Driver "xhyve" not found. Do you have the plugin binary accessible in your PATH?. Retrying.
Error starting the VM:  Error getting the state for host: Driver "xhyve" not found. Do you have the plugin binary accessible in your PATH?
Error getting the state for host: Driver "xhyve" not found. Do you have the plugin binary accessible in your PATH?
Error getting the state for host: Driver "xhyve" not found. Do you have the plugin binary accessible in your PATH?
```

`virtualbox` is a driver that is supported by docker-machine on MacOS, but `minishift` seems to use `xhyve` all the time.

**Comment by praveenkumar** [comment]
@orf No it's not looks like you have already minishift VM which provisioned using `xhyve` and not deleted so can you please do `minishift delete` first and then try with different driver option?

**Comment by gbraad** [comment]
Unable to reproduce for a new instance. This is a duplicate of #179.

**Comment by orf** [comment]
Perhaps @praveenkumar and @gbraad, but `docker-machine` doesn't list any active machines. I will have another try later.

**Comment by hferentschik** [comment]
> but docker-machine doesn't list any active machines.

docker-machine and Minishift are independent and use different directories to keep their state. Minishift uses docker-machine (or better libmachine) under the hood to create and manage its VM, but they are not part of the docker-machine managed VMs.

**Comment by orf** [comment]
Ahh, that makes sense. I cleared out `.minishift/machines` and now `minishift start` works as expected with virtualbox.

I was confused as the `virtualbox` docker-machines show up in `docker-machine ls` whereas the `xhyve` one does/did not.

Thanks for the quick replies, I will close this issue as it seems to be #179.
