### ISSUE TITLE
Allow providing credentials when generating service URL

### ISSUE THREAD

**Issue by ctron** [minishift/minishift#978]
Creating a service URL or opening a service URL using `minishift openshift service` should allow providing credentials.

Assume you have:
```
minishift openshift service console -n kura-emulator --url
http://console-kura-emulator.192.168.42.28.nip.io
```

But would like to add basic auth credentials to the URL, this is currently not possible. So I would propose to add a new parameter (e.g. `--credentials`) which would merge this into the URL. E.g.:

```
minishift openshift service console -n kura-emulator --url --credentials "foo:bar"
http://foo:bar@console-kura-emulator.192.168.42.28.nip.io
```

Of course the same when not using `--url`.

**Comment by jorgemoralespou** [comment]
@praveenkumar I don't think this should be done on the minishift client. This is an edge case, and also opens the door to requesting formatting the url in many different formats.

Anyone could use a script (e.g. https://gist.github.com/joshisa/297b0bc1ec0dcdda0d1625029711fa24) to parse the url and then add the authentication as they need.

**Comment by praveenkumar** [comment]
I agree, closing this as we are going to do any work on that.
