### ISSUE TITLE
Refine release instructions

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#993]
The release instructions can lead to ambiguity due to scarsity of information and changed permissions:

> Commit and push your changes with a message of the form "cut v1.0.0"

  * push as a branch to your own repo? push as a branch to origin? or push to master?
However pushing to master is not allowed, as this is a declined hook

Show Gist disallowed pushing to master: https://gist.github.com/gbraad/08b1ab53453afe2fe25ee1f8347bb782#file-when-pushing-to-master

> Create binaries and upload them to GitHub (this will also tag the release):

  * "upload them to github", does this need to be done manually?

When the `GITHUB_ACCESS_TOKEN` is empty, `make release` will fail with an error 2. However, no information is given about the actual error. This target should mention and fail when the token is not set.

Show Gist `make release` https://gist.github.com/gbraad/08b1ab53453afe2fe25ee1f8347bb782#file-when-token-not-set-or-empty

Post-release instructions needs to use a milestone id, but it is not mentioned where to get this. in the case of this release; the id is `7`, so lower than the described `9` in the instructions...feels weird. needs more instructions

**Comment by gbraad** [comment]
Permissions to master where not properly set. However, instructions around this still needs to be refined.

**Comment by LalatenduMohanty** [comment]
> Show Gist disallowed pushing to master: https://gist.github.com/gbraad/08b1ab53453afe2fe25ee1f8347bb782#file-when-pushing-to-master

I think you need to be an owner of the project to able to do it.

**Comment by LalatenduMohanty** [comment]
> "upload them to github", does this need to be done manually?

Nope, `make release` will do it for you.

**Comment by gbraad** [comment]
The text is phrased as if you should do this yourself

**Comment by hferentschik** [comment]
@gbraad Are you able to provide some refinements to the notes? Let's do this before the next release.

BTW, release is of the master branch, so all actions are assumed to be executed for the master. However, I agree that we would make this explicit.

**Comment by gbraad** [comment]
Will submit improvements ASAP.

Note: work on the master branch was not possible as I did not have te right permissions. This has been corrected since.

**Comment by hferentschik** [comment]
Sure, I got that.

**Comment by gbraad** [comment]
@thatdocslady if you want to work on this, ask me for clarification...

**Comment by hferentschik** [comment]
I think we can close this issue, in particular since the docs will change anyways with the merge of #1109. @gbraad WDYT?

**Comment by gbraad** [comment]
> docs will change anyways with the merge of #1109

The reason I held back. So closing is OK

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]
