### ISSUE TITLE
Fix PowerShell instruction to add HYPERV_VIRTUAL_SWITCH env variable

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#994]
Found that the PowerShell instructions for adding environment variable `HYPERV_VIRTUAL_SWITCH` is missing `$`.
Check here https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html#hyper-v.  
![screenshot from 2017-06-06 14-53-51](https://cloud.githubusercontent.com/assets/1132451/26822550/0e2d4a7e-4ac8-11e7-9ccd-7917d642d722.png)

**Comment by gbraad** [comment]
it is not missing... it is plain wrong: `PS> ` or `PS C:\>` is better for PS... and `C:\> ` for DOS

**Comment by budhrg** [comment]
> it is not missing...

May be unnecessary space here.
