### ISSUE TITLE
certificate is valid for *.xip.io not certificate is valid for *.nip.io

### ISSUE THREAD

**Issue by rawlingsj** [minishift/minishift#999]
minishift v1.1.0

I'm trying to log into the new fabric8 ui vi a keycloak openshift provider.  We get a certificate error which mentions valid "xip.io" hostnames but not "nip.io" which is the route suffix that's used.

`post fail Post https://keycloak-fabric8.192.168.64.82.nip.io/auth/realms/fabric8/protocol/openid-connect/token: x509: certificate is valid for *.192.168.64.82.xip.io, 192.168.64.82.xip.io, not keycloak-fabric8.192.168.64.82.nip.io?error`

I'm not really sure what's causing the issue yet but initially wondered if there's certificates being generated by minishift / oc cluster up that use the old xip default rather than nip after it was switched? https://github.com/minishift/minishift/commit/aafa268f4965dda559cb7c16bc6817b5bb93aae1

Does this sounds feasible?

**Comment by LalatenduMohanty** [comment]
@rawlingsj Sounds like a bug with `oc cluster up` . I have seen similar when I was creating edge termination route https://github.com/openshift/origin/issues/13646.  @csrwng have fixed it in `cluster up`. But I am not sure if the fix is in Origin version 1.5.1 or in https://github.com/openshift/origin/releases/tag/v3.6.0-alpha.1. Can you please check with https://github.com/openshift/origin/releases/tag/v3.6.0-alpha.1 ?

**Comment by csrwng** [comment]
@LalatenduMohanty at some point .xip.io was the default suffix in cluster up. However, this can be overridden by specifying --route-suffix=[your-ip].nip.io.

**Comment by rawlingsj** [comment]
thanks @csrwng but I also get the error when I provide the --route-suffix flag, any chance the certificate generation still uses xip?  I've not tried @LalatenduMohanty suggestion of v3.6.0-alpha.1 yet but will do later this evening.

**Comment by csrwng** [comment]
@rawlingsj I'll try it on minishift as well... I would have thought that the --route-suffix flag would work

**Comment by rawlingsj** [comment]
Yay!  So running with v3.6.0-alpha.1 I get a different error but I think I'm further along and just need to trust insecure certs.

Using:
```
minishift start --vm-driver=xhyve --memory=6096 --cpus=2 --openshift-version=v3.6.0-alpha.1
```
I get now get:
`Post https://keycloak-fabric8.192.168.64.151.nip.io/auth/realms/fabric8/protocol/openid-connect/token: x509: certificate signed by unknown authority`

Does that seem a fair assumption?

**Comment by rawlingsj** [comment]
I'll close this as running with `--openshift-version=v3.6.0-alpha.1` means I don't see the error.

**Comment by rawlingsj** [comment]
Thanks both @LalatenduMohanty and @csrwng for your help!
